// AUTO-GENERATED by scripts/escape-i18n-gen.mjs - do not edit by hand.
import { createEscapeTranslator, type EscapeLevelTranslations } from '../../../create-translator'
import { enLevel02 } from './en'
import { frLevel02 } from './fr'
import { ptBRLevel02 } from './pt-BR'
import { thLevel02 } from './th'
import { idLevel02 } from './id'
import { viLevel02 } from './vi'
import { jaLevel02 } from './ja'

export const LEVEL_02_TRANSLATIONS: EscapeLevelTranslations = {
  "en": enLevel02,
  "fr": frLevel02,
  "pt-BR": ptBRLevel02,
  "th": thLevel02,
  "id": idLevel02,
  "vi": viLevel02,
  "ja": jaLevel02,
}

export const t = createEscapeTranslator(LEVEL_02_TRANSLATIONS)
