// AUTO-GENERATED by scripts/escape-i18n-gen.mjs - do not edit by hand.
import { createEscapeTranslator, type EscapeLevelTranslations } from '../../../create-translator'
import { enLevel09 } from './en'
import { frLevel09 } from './fr'
import { ptBRLevel09 } from './pt-BR'
import { thLevel09 } from './th'
import { idLevel09 } from './id'
import { viLevel09 } from './vi'
import { jaLevel09 } from './ja'

export const LEVEL_09_TRANSLATIONS: EscapeLevelTranslations = {
  "en": enLevel09,
  "fr": frLevel09,
  "pt-BR": ptBRLevel09,
  "th": thLevel09,
  "id": idLevel09,
  "vi": viLevel09,
  "ja": jaLevel09,
}

export const t = createEscapeTranslator(LEVEL_09_TRANSLATIONS)
