import type { ClozeItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-1 cloze EXTRA set — covers grammars the base N1_CLOZE leaves untouched
 * (purpose-of-motion, past experience, -겠어요, -(으)ㄹ래요?, -네요, -지요?,
 * permission, negative imperative, N 말고, 도, 만, honorific -아/어 드리다).
 * ko matches grammars-n1.ts verbatim. Drafted + Korean-lens adversarially
 * verified (single-correct-answer crux). Korean wife native review = final gate.
 */

export const N1_CLOZE_EXTRA: ClozeItem[] = [
  {
    ko: '-(으)러 가다/오다',
    sentence: '저는 책을 {} 서점에 갔어요.',
    answer: '사러',
    distractors: ['사고', '사면', '사서'],
    trans: L(
      'I went to the bookstore to buy a book.',
      'Fui a la librería a comprar un libro.',
      'Je suis allé à la librairie pour acheter un livre.',
      'Fui à livraria para comprar um livro.',
      'ฉันไปร้านหนังสือเพื่อซื้อหนังสือ',
      'Saya pergi ke toko buku untuk membeli buku.',
      'Tôi đến nhà sách để mua sách.',
      '私は本を買いに本屋へ行きました。',
    ),
    why: L(
      'With a motion verb (갔어요), purpose is marked by -(으)러; 사고 just lists actions, 사면 is a condition, 사서 a cause/sequence — none expresses the goal of going.',
      'Con un verbo de movimiento (갔어요), el propósito se marca con -(으)러; 사고 solo enumera, 사면 es condición, 사서 causa/secuencia — ninguno expresa la meta de ir.',
      "Avec un verbe de mouvement (갔어요), le but se marque par -(으)러 ; 사고 énumère, 사면 est une condition, 사서 une cause/suite — aucun n'exprime le but du déplacement.",
      'Com um verbo de movimento (갔어요), o propósito é marcado por -(으)러; 사고 só enumera, 사면 é condição, 사서 causa/sequência — nenhum expressa o objetivo de ir.',
      'กับกริยาเคลื่อนที่ (갔어요) จุดประสงค์ใช้ -(으)러; 사고 แค่เรียง, 사면 เป็นเงื่อนไข, 사서 เป็นเหตุ/ลำดับ ไม่มีตัวใดบอกจุดประสงค์ของการไป',
      'Dengan verba gerak (갔어요), tujuan ditandai -(으)러; 사고 hanya mendaftar, 사면 syarat, 사서 sebab/urutan — tak ada yang menyatakan maksud kepergian.',
      'Với động từ chuyển động (갔어요), mục đích dùng -(으)러; 사고 chỉ liệt kê, 사면 là điều kiện, 사서 là nguyên nhân/trình tự — không cái nào nêu mục đích đi.',
      '移動動詞（갔어요）では目的を -(으)러 で表す。사고 は羅列、사면 は条件、사서 は原因・連続で、行く目的を表せない。',
    ),
  },
  {
    ko: '-(으)ㄴ 적이 있다/없다',
    sentence: '저는 제주도에 한 번 {} 적이 있어요.',
    answer: '간',
    distractors: ['가는', '갈', '가고'],
    trans: L(
      'I have been to Jeju Island once.',
      'He estado en la isla de Jeju una vez.',
      "Je suis allé une fois à l'île de Jeju.",
      'Eu já estive na ilha de Jeju uma vez.',
      'ฉันเคยไปเกาะเชจูครั้งหนึ่ง',
      'Saya pernah ke Pulau Jeju sekali.',
      'Tôi đã từng đến đảo Jeju một lần.',
      '私は済州島に一度行ったことがあります。',
    ),
    why: L(
      'Past experience uses the past modifier -(으)ㄴ before 적이 있다 (간 적이 있다); 가는 is present, 갈 future, and 가고 is a connector that cannot modify 적.',
      'La experiencia pasada usa el modificador de pasado -(으)ㄴ antes de 적이 있다 (간 적이 있다); 가는 es presente, 갈 futuro y 가고 un conector que no puede modificar 적.',
      "L'expérience passée emploie le modificateur passé -(으)ㄴ devant 적이 있다 (간 적이 있다) ; 가는 est présent, 갈 futur, et 가고 un connecteur qui ne peut modifier 적.",
      'A experiência passada usa o modificador de passado -(으)ㄴ antes de 적이 있다 (간 적이 있다); 가는 é presente, 갈 futuro e 가고 um conector que não modifica 적.',
      'ประสบการณ์ในอดีตใช้รูปขยายอดีต -(으)ㄴ หน้า 적이 있다 (간 적이 있다); 가는 ปัจจุบัน, 갈 อนาคต, 가고 เป็นคำเชื่อมที่ขยาย 적 ไม่ได้',
      'Pengalaman lampau memakai pewatas lampau -(으)ㄴ sebelum 적이 있다 (간 적이 있다); 가는 kini, 갈 akan datang, dan 가고 penghubung yang tak bisa mewatasi 적.',
      'Kinh nghiệm quá khứ dùng định ngữ quá khứ -(으)ㄴ trước 적이 있다 (간 적이 있다); 가는 hiện tại, 갈 tương lai, còn 가고 là liên từ không thể bổ nghĩa cho 적.',
      '過去の経験は 적이 있다 の前に過去連体形 -(으)ㄴ を取る（간 적이 있다）。가는 は現在、갈 は未来、가고 は接続語尾で 적 を修飾できない。',
    ),
  },
  {
    ko: '-겠어요',
    sentence: '하늘을 보니 곧 비가 {}.',
    answer: '오겠어요',
    distractors: ['왔어요', '와요', '오세요'],
    trans: L(
      'Looking at the sky, it looks like it will rain soon.',
      'Mirando el cielo, parece que pronto va a llover.',
      'En regardant le ciel, on dirait qu’il va bientôt pleuvoir.',
      'Olhando o céu, parece que vai chover logo.',
      'ดูจากท้องฟ้าแล้ว เดี๋ยวฝนน่าจะตก',
      'Melihat langit, sepertinya sebentar lagi akan hujan.',
      'Nhìn trời thì có vẻ sắp mưa.',
      '空を見ると、もうすぐ雨が降りそうです。',
    ),
    why: L(
      'A guess from present evidence (하늘을 보니… 곧) calls for the conjecture -겠어요; 왔어요 is past (contradicts 곧 "soon"), 와요 a flat present, 오세요 a request to the rain (nonsense).',
      'Una conjetura a partir de evidencia presente (하늘을 보니… 곧) pide -겠어요; 왔어요 es pasado (choca con 곧 "pronto"), 와요 presente plano, 오세요 una orden a la lluvia (sin sentido).',
      "Une conjecture fondée sur un indice présent (하늘을 보니… 곧) appelle -겠어요 ; 왔어요 est passé (incompatible avec 곧 « bientôt »), 와요 un présent neutre, 오세요 un ordre à la pluie (absurde).",
      'Uma conjectura a partir de evidência presente (하늘을 보니… 곧) pede -겠어요; 왔어요 é passado (choca com 곧 "logo"), 와요 presente neutro, 오세요 uma ordem à chuva (sem sentido).',
      'การคาดเดาจากหลักฐานปัจจุบัน (하늘을 보니… 곧) ต้องใช้ -겠어요; 왔어요 อดีต (ขัดกับ 곧 "เดี๋ยว"), 와요 ปัจจุบันเฉย ๆ, 오세요 สั่งฝน (ไม่สมเหตุผล)',
      'Dugaan dari bukti kini (하늘을 보니… 곧) menuntut -겠어요; 왔어요 lampau (bentrok dengan 곧 "sebentar lagi"), 와요 present datar, 오세요 memerintah hujan (tak masuk akal).',
      'Suy đoán từ bằng chứng hiện tại (하늘을 보니… 곧) cần -겠어요; 왔어요 quá khứ (mâu thuẫn với 곧 "sắp"), 와요 hiện tại trơn, 오세요 ra lệnh cho mưa (vô lý).',
      '現在の根拠からの推量（하늘을 보니… 곧）には -겠어요 が必要。왔어요 は過去で곧（もうすぐ）と矛盾、와요 は平叙の現在、오세요 は雨への依頼で不自然。',
    ),
  },
  {
    ko: '-(으)ㄹ래요?',
    sentence: '심심한데 우리 같이 영화 {}',
    answer: '볼래요?',
    distractors: ['봤어요?', '보세요', '볼게요'],
    trans: L(
      "I'm bored — do you want to watch a movie together?",
      'Estoy aburrido, ¿quieres ver una película juntos?',
      "Je m'ennuie — tu veux regarder un film ensemble ?",
      'Estou entediado — quer ver um filme juntos?',
      'เบื่อจัง เราดูหนังด้วยกันไหม',
      'Saya bosan — mau nonton film bareng?',
      'Tôi chán quá — mình xem phim cùng nhau nhé?',
      '退屈なんだけど、一緒に映画見ませんか？',
    ),
    why: L(
      "Inviting the listener (우리 같이) uses the offer -(으)ㄹ래요?; 봤어요? asks about the past, 보세요 commands the listener alone, 볼게요 is the speaker's own promise — none invites a joint plan.",
      'Invitar al oyente (우리 같이) usa la oferta -(으)ㄹ래요?; 봤어요? pregunta por el pasado, 보세요 ordena solo al oyente, 볼게요 es la promesa del hablante — ninguno propone hacerlo juntos.',
      "Inviter l'interlocuteur (우리 같이) emploie la proposition -(으)ㄹ래요? ; 봤어요? interroge sur le passé, 보세요 ordonne à l'autre seul, 볼게요 est la promesse du locuteur — aucun ne propose une action commune.",
      'Convidar o ouvinte (우리 같이) usa a oferta -(으)ㄹ래요?; 봤어요? pergunta sobre o passado, 보세요 ordena só ao ouvinte, 볼게요 é a promessa do falante — nenhum propõe fazer juntos.',
      'การชวนผู้ฟัง (우리 같이) ใช้คำชวน -(으)ㄹ래요?; 봤어요? ถามอดีต, 보세요 สั่งเฉพาะผู้ฟัง, 볼게요 เป็นคำสัญญาของผู้พูด ไม่มีตัวใดชวนทำด้วยกัน',
      'Mengajak lawan bicara (우리 같이) memakai tawaran -(으)ㄹ래요?; 봤어요? menanyakan masa lalu, 보세요 menyuruh lawan bicara saja, 볼게요 janji si penutur — tak ada yang mengajak bersama.',
      'Rủ người nghe (우리 같이) dùng lời mời -(으)ㄹ래요?; 봤어요? hỏi về quá khứ, 보세요 sai bảo riêng người nghe, 볼게요 là lời hứa của người nói — không cái nào rủ cùng làm.',
      '相手を誘う（우리 같이）には勧誘の -(으)ㄹ래요? を使う。봤어요? は過去の質問、보세요 は相手だけへの命令、볼게요 は話し手の約束で、一緒の提案にならない。',
    ),
  },
  {
    ko: '-네요',
    sentence: '와, 오늘 날씨가 정말 {}',
    answer: '좋네요!',
    distractors: ['좋았어요!', '좋겠어요!', '좋으세요!'],
    trans: L(
      'Wow, the weather is really nice today!',
      '¡Vaya, hoy hace muy buen tiempo!',
      "Waouh, il fait vraiment beau aujourd'hui !",
      'Nossa, o tempo está muito bom hoje!',
      'ว้าว วันนี้อากาศดีจริง ๆ เลยนะ',
      'Wah, cuaca hari ini benar-benar bagus!',
      'Ồ, hôm nay thời tiết đẹp thật đấy!',
      'わあ、今日は本当にいい天気ですね！',
    ),
    why: L(
      'A fresh realization in the moment (와, 오늘…정말) takes the discovery -네요; 좋았어요 is past, 좋겠어요 a guess about the unseen, 좋으세요 an honorific about the listener (not the weather).',
      'Una constatación en el momento (와, 오늘…정말) usa el descubrimiento -네요; 좋았어요 es pasado, 좋겠어요 una conjetura sobre lo no visto, 좋으세요 honorífico sobre el oyente (no el clima).',
      "Une prise de conscience sur l'instant (와, 오늘…정말) prend la découverte -네요 ; 좋았어요 est passé, 좋겠어요 une conjecture sur l'invisible, 좋으세요 un honorifique visant l'interlocuteur (pas la météo).",
      'Uma constatação no momento (와, 오늘…정말) usa a descoberta -네요; 좋았어요 é passado, 좋겠어요 uma conjetura sobre o não visto, 좋으세요 honorífico sobre o ouvinte (não o clima).',
      'การรับรู้ ณ ขณะนั้น (와, 오늘…정말) ใช้รูปค้นพบ -네요; 좋았어요 อดีต, 좋겠어요 คาดเดาสิ่งที่ยังไม่เห็น, 좋으세요 ยกย่องผู้ฟัง (ไม่ใช่อากาศ)',
      'Kesadaran seketika (와, 오늘…정말) memakai penemuan -네요; 좋았어요 lampau, 좋겠어요 dugaan atas yang tak terlihat, 좋으세요 hormat untuk lawan bicara (bukan cuaca).',
      'Sự nhận ra ngay lúc đó (와, 오늘…정말) dùng phát hiện -네요; 좋았어요 quá khứ, 좋겠어요 phỏng đoán điều chưa thấy, 좋으세요 kính ngữ về người nghe (không phải thời tiết).',
      'その場での気づき（와, 오늘…정말）には発見の -네요 を使う。좋았어요 は過去、좋겠어요 は未確認の推量、좋으세요 は相手への尊敬で天気には合わない。',
    ),
  },
  {
    ko: '-지요? / -죠?',
    sentence: '민수 씨도 내일 모임에 {}',
    answer: '오지요?',
    distractors: ['올까요?', '왔어요?', '오네요?'],
    trans: L(
      "You're coming to tomorrow's gathering too, right, Minsu?",
      'Minsu, tú también vienes a la reunión de mañana, ¿verdad?',
      "Minsu, tu viens aussi à la réunion de demain, non ?",
      'Minsu, você também vem ao encontro de amanhã, né?',
      'คุณมินซูก็มางานพรุ่งนี้ใช่ไหม',
      'Minsu, kamu juga datang ke pertemuan besok, kan?',
      'Anh Minsu cũng đến buổi gặp ngày mai phải không?',
      'ミンスさんも明日の集まりに来ますよね？',
    ),
    why: L(
      'Confirming something the speaker already assumes (도 "also" presupposes it) takes -지요?/-죠?; 올까요? wonders/proposes, 왔어요? asks about the past, 오네요? is a remark, not a confirmation request.',
      'Confirmar algo que el hablante ya supone (도 "también" lo presupone) usa -지요?/-죠?; 올까요? se pregunta/propone, 왔어요? pregunta por el pasado, 오네요? es un comentario, no una confirmación.',
      "Confirmer ce que le locuteur présuppose déjà (도 « aussi » le présuppose) prend -지요?/-죠? ; 올까요? se demande/propose, 왔어요? interroge le passé, 오네요? est une remarque, pas une demande de confirmation.",
      'Confirmar algo que o falante já pressupõe (도 "também" pressupõe isso) usa -지요?/-죠?; 올까요? indaga/propõe, 왔어요? pergunta sobre o passado, 오네요? é um comentário, não um pedido de confirmação.',
      'การยืนยันสิ่งที่ผู้พูดสันนิษฐานอยู่แล้ว (도 "ก็" บ่งเป็นนัย) ใช้ -지요?/-죠?; 올까요? สงสัย/ชวน, 왔어요? ถามอดีต, 오네요? เป็นการออกความเห็น ไม่ใช่ขอยืนยัน',
      'Mengonfirmasi yang sudah diasumsikan penutur (도 "juga" mempraanggapnya) memakai -지요?/-죠?; 올까요? bertanya-tanya/mengajak, 왔어요? menanyakan masa lalu, 오네요? komentar, bukan permintaan konfirmasi.',
      'Xác nhận điều người nói đã giả định (도 "cũng" tiền giả định điều đó) dùng -지요?/-죠?; 올까요? phân vân/đề nghị, 왔어요? hỏi quá khứ, 오네요? là lời nhận xét, không phải yêu cầu xác nhận.',
      '話し手が既に前提していること（도「も」が前提）を確認するには -지요?/-죠? を使う。올까요? は推量・勧誘、왔어요? は過去の質問、오네요? は感想で確認要求ではない。',
    ),
  },
  {
    ko: '-아/어도 되다',
    sentence: '선생님, 여기 잠깐 {} 돼요?',
    answer: '앉아도',
    distractors: ['앉지', '앉고', '앉아서'],
    trans: L(
      'Teacher, may I sit here for a moment?',
      'Profesor, ¿puedo sentarme aquí un momento?',
      "Madame/Monsieur, puis-je m'asseoir ici un instant ?",
      'Professor, posso me sentar aqui um momento?',
      'อาจารย์คะ ขอนั่งตรงนี้สักครู่ได้ไหมคะ',
      'Bu/Pak Guru, boleh saya duduk di sini sebentar?',
      'Thưa thầy/cô, em ngồi đây một lát được không ạ?',
      '先生、ここにちょっと座ってもいいですか？',
    ),
    why: L(
      'Asking permission needs -아/어도 before 되다 (앉아도 돼요); 앉지 돼요 / 앉고 돼요 / 앉아서 돼요 are not the permission pattern and read as broken strings.',
      'Pedir permiso requiere -아/어도 antes de 되다 (앉아도 돼요); 앉지 돼요 / 앉고 돼요 / 앉아서 돼요 no son el patrón de permiso y suenan como cadenas rotas.',
      "Demander la permission exige -아/어도 devant 되다 (앉아도 돼요) ; 앉지 돼요 / 앉고 돼요 / 앉아서 돼요 ne sont pas le schéma de permission et sonnent faux.",
      'Pedir permissão exige -아/어도 antes de 되다 (앉아도 돼요); 앉지 돼요 / 앉고 돼요 / 앉아서 돼요 não são o padrão de permissão e soam quebrados.',
      'การขออนุญาตต้องใช้ -아/어도 หน้า 되다 (앉아도 돼요); 앉지 돼요 / 앉고 돼요 / 앉아서 돼요 ไม่ใช่รูปขออนุญาตและฟังดูผิด',
      'Meminta izin butuh -아/어도 sebelum 되다 (앉아도 돼요); 앉지 돼요 / 앉고 돼요 / 앉아서 돼요 bukan pola izin dan terdengar rusak.',
      'Xin phép cần -아/어도 trước 되다 (앉아도 돼요); 앉지 돼요 / 앉고 돼요 / 앉아서 돼요 không phải mẫu xin phép và nghe sai.',
      '許可を求めるには 되다 の前に -아/어도 が必要（앉아도 돼요）。앉지 돼요 / 앉고 돼요 / 앉아서 돼요 は許可表現でなく不自然。',
    ),
  },
  {
    ko: '-지 말다',
    sentence: '여기는 도서관이니까 큰 소리로 {}.',
    answer: '말하지 마세요',
    distractors: ['말하세요', '말했어요', '말할 거예요'],
    trans: L(
      "This is a library, so please don't talk loudly.",
      'Esto es una biblioteca, así que no hable en voz alta, por favor.',
      "Ici, c'est une bibliothèque, alors ne parlez pas fort, s'il vous plaît.",
      'Aqui é uma biblioteca, então não fale alto, por favor.',
      'ที่นี่เป็นห้องสมุด กรุณาอย่าพูดเสียงดังนะคะ',
      'Ini perpustakaan, jadi tolong jangan berbicara keras.',
      'Đây là thư viện nên xin đừng nói to.',
      'ここは図書館なので、大きな声で話さないでください。',
    ),
    why: L(
      'A prohibition (도서관이니까) uses the negative imperative -지 말다 (말하지 마세요); 말하세요 commands the opposite, 말했어요 is past, 말할 거예요 future — none forbids the action.',
      'Una prohibición (도서관이니까) usa el imperativo negativo -지 말다 (말하지 마세요); 말하세요 ordena lo contrario, 말했어요 es pasado, 말할 거예요 futuro — ninguno prohíbe la acción.',
      "Une interdiction (도서관이니까) emploie l'impératif négatif -지 말다 (말하지 마세요) ; 말하세요 ordonne le contraire, 말했어요 est passé, 말할 거예요 futur — aucun n'interdit l'action.",
      'Uma proibição (도서관이니까) usa o imperativo negativo -지 말다 (말하지 마세요); 말하세요 ordena o contrário, 말했어요 é passado, 말할 거예요 futuro — nenhum proíbe a ação.',
      'การห้าม (도서관이니까) ใช้คำสั่งห้าม -지 말다 (말하지 마세요); 말하세요 สั่งให้ทำตรงข้าม, 말했어요 อดีต, 말할 거예요 อนาคต ไม่มีตัวใดห้ามการกระทำ',
      'Larangan (도서관이니까) memakai imperatif negatif -지 말다 (말하지 마세요); 말하세요 menyuruh sebaliknya, 말했어요 lampau, 말할 거예요 akan datang — tak ada yang melarang.',
      'Lời cấm (도서관이니까) dùng mệnh lệnh phủ định -지 말다 (말하지 마세요); 말하세요 ra lệnh ngược lại, 말했어요 quá khứ, 말할 거예요 tương lai — không cái nào cấm hành động.',
      '禁止（도서관이니까）には否定命令 -지 말다（말하지 마세요）を使う。말하세요 は逆の命令、말했어요 は過去、말할 거예요 は未来で、行為を禁じられない。',
    ),
  },
  {
    ko: 'N 말고',
    sentence: '저는 콜라 {} 물 주세요.',
    answer: '말고',
    distractors: ['에서', '처럼', '한테'],
    trans: L(
      'Not cola — please give me water.',
      'Cola no, deme agua, por favor.',
      'Pas de cola — donnez-moi de l’eau, s’il vous plaît.',
      'Cola não, me dê água, por favor.',
      'ไม่เอาโคล่า ขอน้ำเปล่าค่ะ',
      'Bukan cola — tolong beri saya air putih.',
      'Không phải cola — cho tôi nước lọc.',
      'コーラではなく水をください。',
    ),
    why: L(
      'Rejecting one option for another (콜라 instead of 물) uses N 말고; 에서 marks a place ("from cola"), 처럼 means "like cola," 한테 marks a person recipient — none rejects the first noun.',
      'Rechazar una opción por otra (콜라 en vez de 물) usa N 말고; 에서 marca lugar ("desde la cola"), 처럼 "como la cola", 한테 marca destinatario persona — ninguno rechaza el primer sustantivo.',
      "Rejeter une option pour une autre (콜라 au lieu de 물) emploie N 말고 ; 에서 marque un lieu (« depuis le cola »), 처럼 « comme le cola », 한테 marque un destinataire personne — aucun ne rejette le premier nom.",
      'Rejeitar uma opção por outra (콜라 em vez de 물) usa N 말고; 에서 marca lugar ("do cola"), 처럼 "como a cola", 한테 marca destinatário pessoa — nenhum rejeita o primeiro substantivo.',
      'การปฏิเสธตัวเลือกหนึ่งเพื่ออีกตัว (콜라 แทนด้วย 물) ใช้ N 말고; 에서 บอกสถานที่ ("จากโคล่า"), 처럼 "เหมือนโคล่า", 한테 บอกผู้รับที่เป็นคน ไม่มีตัวใดปฏิเสธคำนามแรก',
      'Menolak satu pilihan demi yang lain (콜라 diganti 물) memakai N 말고; 에서 menandai tempat ("dari cola"), 처럼 "seperti cola", 한테 menandai penerima orang — tak ada yang menolak nomina pertama.',
      'Từ chối lựa chọn này để lấy lựa chọn khác (콜라 thay bằng 물) dùng N 말고; 에서 đánh dấu nơi chốn ("từ cola"), 처럼 "giống cola", 한테 đánh dấu người nhận — không cái nào bác bỏ danh từ đầu.',
      'ある選択肢を別のものに替える（콜라 ではなく 물）には N 말고 を使う。에서 は場所（「コーラから」）、처럼 は「コーラのように」、한테 は人への授与で、最初の名詞を否定しない。',
    ),
  },
  {
    ko: '도',
    sentence: '언니는 커피를 마셔요. 저{} 커피를 마셔요.',
    answer: '도',
    distractors: ['는', '가', '를'],
    trans: L(
      'My older sister drinks coffee. I drink coffee too.',
      'Mi hermana mayor toma café. Yo también tomo café.',
      'Ma grande sœur boit du café. Moi aussi, je bois du café.',
      'Minha irmã mais velha toma café. Eu também tomo café.',
      'พี่สาวดื่มกาแฟ ฉันก็ดื่มกาแฟเหมือนกัน',
      'Kakak perempuan saya minum kopi. Saya juga minum kopi.',
      'Chị tôi uống cà phê. Tôi cũng uống cà phê.',
      '姉はコーヒーを飲みます。私もコーヒーを飲みます。',
    ),
    why: L(
      'Adding the same action to a new subject ("I too") needs 도; 는 only re-topicalizes (loses "too"), 가 marks plain subject, 를 marks an object — none gives the "also" meaning.',
      'Añadir la misma acción a un nuevo sujeto ("yo también") necesita 도; 는 solo retematiza (pierde el "también"), 가 marca sujeto neutro, 를 marca objeto — ninguno da el sentido de "también".',
      "Ajouter la même action à un nouveau sujet (« moi aussi ») exige 도 ; 는 ne fait que re-thématiser (perd « aussi »), 가 marque le sujet neutre, 를 marque l'objet — aucun ne rend « aussi ».",
      'Acrescentar a mesma ação a um novo sujeito ("eu também") exige 도; 는 só re-topicaliza (perde o "também"), 가 marca sujeito neutro, 를 marca objeto — nenhum dá o sentido de "também".',
      'การเพิ่มการกระทำเดียวกันให้ประธานใหม่ ("ฉันก็") ต้องใช้ 도; 는 แค่ทำให้เป็นหัวเรื่องใหม่ (เสียความ "ก็"), 가 บอกประธานเฉย ๆ, 를 บอกกรรม ไม่มีตัวใดให้ความหมาย "ด้วย"',
      'Menambahkan aksi yang sama pada subjek baru ("saya juga") butuh 도; 는 hanya menjadikan topik lagi (kehilangan "juga"), 가 subjek biasa, 를 objek — tak ada yang memberi makna "juga".',
      'Thêm cùng hành động cho chủ thể mới ("tôi cũng") cần 도; 는 chỉ nêu lại chủ đề (mất nghĩa "cũng"), 가 đánh dấu chủ ngữ trơn, 를 đánh dấu tân ngữ — không cái nào cho nghĩa "cũng".',
      '新しい主語に同じ行為を加える（「私も」）には 도 が必要。는 は主題化のみで「も」を失い、가 は単なる主語、를 は目的語で、「も」の意味を出せない。',
    ),
  },
  {
    ko: '만',
    sentence: '돈이 없어서 물{} 샀어요.',
    answer: '만',
    distractors: ['도', '부터', '까지'],
    trans: L(
      "I had no money, so I only bought water.",
      'No tenía dinero, así que solo compré agua.',
      "Je n'avais pas d'argent, donc je n'ai acheté que de l'eau.",
      'Eu não tinha dinheiro, então só comprei água.',
      'ฉันไม่มีเงิน เลยซื้อแค่น้ำเปล่า',
      'Saya tidak punya uang, jadi hanya membeli air.',
      'Tôi không có tiền nên chỉ mua nước.',
      'お金がなくて水だけ買いました。',
    ),
    why: L(
      'The reason 돈이 없어서 forces exclusivity ("only water") → 만; 도 means "water too" (the opposite), 부터 "from water," 까지 "even up to water" — none gives "only."',
      'La razón 돈이 없어서 fuerza exclusividad ("solo agua") → 만; 도 significa "agua también" (lo contrario), 부터 "desde el agua", 까지 "hasta el agua" — ninguno da "solo".',
      "La raison 돈이 없어서 impose l'exclusivité (« seulement de l'eau ») → 만 ; 도 signifie « de l'eau aussi » (le contraire), 부터 « à partir de l'eau », 까지 « jusqu'à l'eau » — aucun ne rend « seulement ».",
      'A razão 돈이 없어서 força exclusividade ("só água") → 만; 도 significa "água também" (o oposto), 부터 "a partir da água", 까지 "até a água" — nenhum dá "só".',
      'เหตุผล 돈이 없어서 บังคับความจำกัด ("แค่น้ำ") → 만; 도 แปลว่า "น้ำด้วย" (ตรงข้าม), 부터 "ตั้งแต่น้ำ", 까지 "จนถึงน้ำ" ไม่มีตัวใดให้ความหมาย "แค่"',
      'Alasan 돈이 없어서 memaksa eksklusivitas ("hanya air") → 만; 도 berarti "air juga" (kebalikannya), 부터 "dari air", 까지 "sampai air" — tak ada yang memberi "hanya".',
      'Lý do 돈이 없어서 buộc tính độc nhất ("chỉ nước") → 만; 도 nghĩa "nước cũng" (ngược lại), 부터 "từ nước", 까지 "đến tận nước" — không cái nào cho nghĩa "chỉ".',
      '理由 돈이 없어서 が限定（「水だけ」）を要求 → 만。도 は「水も」（逆）、부터 は「水から」、까지 は「水まで」で、「だけ」の意味にならない。',
    ),
  },
  {
    ko: '-아/어 드리다',
    sentence: '할머니, 무거우시죠? 제가 가방을 {}.',
    answer: '들어 드릴게요',
    distractors: ['들어 줄게요', '들어 드세요', '들 거예요'],
    trans: L(
      'Grandma, it must be heavy, right? I’ll carry the bag for you.',
      'Abuela, pesa, ¿verdad? Yo le llevo la bolsa.',
      'Mamie, c’est lourd, non ? Je vais porter le sac pour vous.',
      'Vovó, está pesado, né? Eu carrego a bolsa para a senhora.',
      'คุณยายคะ หนักใช่ไหมคะ เดี๋ยวหนูถือกระเป๋าให้นะคะ',
      'Nenek, berat ya? Biar saya yang membawakan tasnya.',
      'Bà ơi, nặng phải không ạ? Để cháu xách túi giúp bà.',
      'おばあちゃん、重いでしょう？私が荷物をお持ちしますね。',
    ),
    why: L(
      'Doing a favor for an elder (할머니) needs the humble -아/어 드리다 (들어 드릴게요); 들어 줄게요 is the plain non-honorific 주다 (too casual for 할머니), 들어 드세요 wrongly uses 드시다 "eat," 들 거예요 drops the "for you" benefit entirely.',
      'Hacer un favor a un mayor (할머니) requiere el humilde -아/어 드리다 (들어 드릴게요); 들어 줄게요 es el 주다 sin honorífico (demasiado casual para 할머니), 들어 드세요 usa por error 드시다 "comer", 들 거예요 omite el matiz "para usted".',
      "Rendre service à une aînée (할머니) exige l'humble -아/어 드리다 (들어 드릴게요) ; 들어 줄게요 est le 주다 non honorifique (trop familier pour 할머니), 들어 드세요 emploie à tort 드시다 « manger », 들 거예요 supprime le « pour vous ».",
      'Fazer um favor a uma idosa (할머니) exige o humilde -아/어 드리다 (들어 드릴게요); 들어 줄게요 é o 주다 sem honorífico (casual demais para 할머니), 들어 드세요 usa por engano 드시다 "comer", 들 거예요 perde o sentido "para a senhora".',
      'การทำให้ผู้ใหญ่ (할머니) ต้องใช้รูปถ่อมตน -아/어 드리다 (들어 드릴게요); 들어 줄게요 เป็น 주다 ธรรมดา (ไม่สุภาพพอสำหรับ 할머니), 들어 드세요 ใช้ 드시다 "ทาน" ผิด, 들 거예요 ตัดความหมาย "ให้" ออกหมด',
      'Membantu orang yang lebih tua (할머니) butuh bentuk merendah -아/어 드리다 (들어 드릴게요); 들어 줄게요 adalah 주다 biasa (terlalu santai untuk 할머니), 들어 드세요 keliru memakai 드시다 "makan", 들 거예요 menghilangkan makna "untuk Anda".',
      'Làm giúp người lớn tuổi (할머니) cần dạng khiêm nhường -아/어 드리다 (들어 드릴게요); 들어 줄게요 là 주다 thường (quá suồng sã với 할머니), 들어 드세요 dùng nhầm 드시다 "ăn", 들 거예요 bỏ mất nghĩa "giúp bà".',
      '目上（할머니）への奉仕には謙譲の -아/어 드리다（들어 드릴게요）が必要。들어 줄게요 は非尊敬の 주다 で할머니には砕けすぎ、들어 드세요 は「召し上がる」드시다 の誤用、들 거예요 は「〜してあげる」を欠く。',
    ),
  },
]
