// app/seed/cloze/n1.ts
import type { ClozeItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-1 grammar-pattern cloze items (choose the pattern that fits the blank).
 * ko matches grammars-n1.ts verbatim. Drafted + Korean-lens adversarially verified
 * (single-correct-answer crux). Korean wife native review = documented final gate.
 */

export const N1_CLOZE: ClozeItem[] = [
  {
    ko: '-았/었어요',
    sentence: '어제 도서관에서 친구를 {}.',
    answer: '만났어요',
    distractors: ['만나요', '만날 거예요', '만납니다'],
    trans: L(
      'I met a friend at the library yesterday.',
      'Ayer me encontré con un amigo en la biblioteca.',
      "Hier, j'ai rencontré un ami à la bibliothèque.",
      'Ontem encontrei um amigo na biblioteca.',
      'เมื่อวานเจอเพื่อนที่ห้องสมุด',
      'Kemarin saya bertemu teman di perpustakaan.',
      'Hôm qua tôi đã gặp bạn ở thư viện.',
      '昨日、図書館で友達に会いました。',
    ),
    why: L(
      '어제 (yesterday) forces past -았/었어요; 만나요 is present, 만날 거예요 future, 만납니다 formal present — none fits a completed past.',
      '어제 (ayer) exige el pasado -았/었어요; 만나요 es presente, 만날 거예요 futuro, 만납니다 presente formal — ninguno encaja en un pasado.',
      '어제 (hier) impose le passé -았/었어요 ; 만나요 présent, 만날 거예요 futur, 만납니다 présent formel — aucun ne convient au passé.',
      '어제 (ontem) exige o passado -았/었어요; 만나요 presente, 만날 거예요 futuro, 만납니다 presente formal — nenhum cabe no passado.',
      '어제 (เมื่อวาน) บังคับอดีต -았/었어요; 만나요 ปัจจุบัน, 만날 거예요 อนาคต, 만납니다 ปัจจุบันทางการ ล้วนไม่เข้ากับอดีต',
      '어제 (kemarin) mengharuskan lampau -았/었어요; 만나요 sekarang, 만날 거예요 akan datang, 만납니다 present formal — tak ada yang cocok untuk lampau.',
      '어제 (hôm qua) buộc quá khứ -았/었어요; 만나요 hiện tại, 만날 거예요 tương lai, 만납니다 hiện tại trang trọng — không cái nào hợp quá khứ.',
      '어제（昨日）が過去 -았/었어요 を要求。만나요 は現在、만날 거예요 は未来、만납니다 は格式の現在で、いずれも過去に合わない。',
    ),
  },
  {
    ko: '-았/었어요',
    sentence: '아침에 빵하고 우유를 {}.',
    answer: '먹었어요',
    distractors: ['먹어요', '먹을 거예요', '먹습니다'],
    trans: L(
      'I ate bread and milk in the morning.',
      'Por la mañana comí pan y leche.',
      "Le matin, j'ai mangé du pain et bu du lait.",
      'De manhã comi pão e leite.',
      'ตอนเช้ากินขนมปังกับนม',
      'Pagi tadi saya makan roti dan minum susu.',
      'Buổi sáng tôi đã ăn bánh mì và uống sữa.',
      '朝、パンと牛乳を食べました。',
    ),
    why: L(
      '아침에 here marks a completed past, so -았/었어요; 먹어요 present, 먹을 거예요 future, 먹습니다 formal present — all clash with the finished action.',
      '아침에 marca un pasado ya hecho, por eso -았/었어요; 먹어요 presente, 먹을 거예요 futuro, 먹습니다 presente formal — todos chocan con la acción terminada.',
      "아침에 marque un passé accompli, donc -았/었어요 ; 먹어요 présent, 먹을 거예요 futur, 먹습니다 présent formel — tous incompatibles avec l'action achevée.",
      '아침에 marca um passado já concluído, logo -았/었어요; 먹어요 presente, 먹을 거예요 futuro, 먹습니다 presente formal — todos destoam da ação concluída.',
      '아침에 บอกอดีตที่ทำเสร็จแล้ว จึงใช้ -았/었어요; 먹어요 ปัจจุบัน, 먹을 거예요 อนาคต, 먹습니다 ปัจจุบันทางการ ขัดกับการกระทำที่จบแล้ว',
      '아침에 menandai lampau yang sudah selesai, jadi -았/었어요; 먹어요 sekarang, 먹을 거예요 akan datang, 먹습니다 present formal — semua bentrok dengan aksi selesai.',
      '아침에 đánh dấu quá khứ đã hoàn tất nên -았/었어요; 먹어요 hiện tại, 먹을 거예요 tương lai, 먹습니다 hiện tại trang trọng — đều nghịch với hành động đã xong.',
      '아침에 が完了した過去を示すので -았/었어요。먹어요 は現在、먹을 거예요 は未来、먹습니다 は格式の現在で、完了動作と矛盾する。',
    ),
  },
  {
    ko: '-았/었어요',
    sentence: '어젯밤에 너무 피곤해서 일찍 {}.',
    answer: '잤어요',
    distractors: ['자요', '잘 거예요', '잡니다'],
    trans: L(
      'I was so tired last night that I went to bed early.',
      'Anoche estaba tan cansado que me acosté temprano.',
      "Hier soir, j'étais si fatigué que je me suis couché tôt.",
      'Ontem à noite eu estava tão cansado que dormi cedo.',
      'เมื่อคืนเหนื่อยมากเลยนอนเร็ว',
      'Tadi malam saya sangat lelah jadi tidur lebih awal.',
      'Tối qua tôi quá mệt nên đã đi ngủ sớm.',
      '昨夜はとても疲れて早く寝ました。',
    ),
    why: L(
      '어젯밤에 (last night) forces past -았/었어요; 자요 present, 잘 거예요 future, 잡니다 formal present — none fits last night.',
      '어젯밤에 (anoche) exige el pasado -았/었어요; 자요 presente, 잘 거예요 futuro, 잡니다 presente formal — ninguno encaja con anoche.',
      '어젯밤에 (hier soir) impose le passé -았/었어요 ; 자요 présent, 잘 거예요 futur, 잡니다 présent formel — aucun ne convient à hier soir.',
      '어젯밤에 (ontem à noite) exige o passado -았/었어요; 자요 presente, 잘 거예요 futuro, 잡니다 presente formal — nenhum cabe em ontem à noite.',
      '어젯밤에 (เมื่อคืน) บังคับอดีต -았/었어요; 자요 ปัจจุบัน, 잘 거예요 อนาคต, 잡니다 ปัจจุบันทางการ ไม่เข้ากับเมื่อคืน',
      '어젯밤에 (tadi malam) mengharuskan lampau -았/었어요; 자요 sekarang, 잘 거예요 akan datang, 잡니다 present formal — tak ada yang cocok untuk tadi malam.',
      '어젯밤에 (tối qua) buộc quá khứ -았/었어요; 자요 hiện tại, 잘 거예요 tương lai, 잡니다 hiện tại trang trọng — không hợp tối qua.',
      '어젯밤에（昨夜）が過去 -았/었어요 を要求。자요 は現在、잘 거예요 は未来、잡니다 は格式の現在で、昨夜に合わない。',
    ),
  },
  {
    ko: '-(으)ㄹ 거예요',
    sentence: '내일 시간이 있으면 영화를 {}.',
    answer: '볼 거예요',
    distractors: ['봤어요', '보세요', '봅니다'],
    trans: L(
      "If I have time tomorrow, I'm going to watch a movie.",
      'Si tengo tiempo mañana, voy a ver una película.',
      "Si j'ai le temps demain, je vais regarder un film.",
      'Se eu tiver tempo amanhã, vou ver um filme.',
      'พรุ่งนี้ถ้ามีเวลาจะดูหนัง',
      'Kalau besok ada waktu, saya akan menonton film.',
      'Ngày mai nếu có thời gian tôi sẽ xem phim.',
      '明日、時間があれば映画を見るつもりです。',
    ),
    why: L(
      '내일 + 1st-person intention forces future -(으)ㄹ 거예요; 봤어요 is past, 보세요 a request, 봅니다 formal present statement.',
      '내일 + intención en 1ª persona exige el futuro -(으)ㄹ 거예요; 봤어요 pasado, 보세요 petición, 봅니다 presente formal.',
      '내일 + intention à la 1ʳᵉ personne impose le futur -(으)ㄹ 거예요 ; 봤어요 passé, 보세요 demande, 봅니다 présent formel.',
      '내일 + intenção em 1ª pessoa exige o futuro -(으)ㄹ 거예요; 봤어요 passado, 보세요 pedido, 봅니다 presente formal.',
      '내일 + เจตนาบุรุษที่ 1 บังคับอนาคต -(으)ㄹ 거예요; 봤어요 อดีต, 보세요 คำขอ, 봅니다 ปัจจุบันทางการ',
      '내일 + niat orang pertama mengharuskan masa depan -(으)ㄹ 거예요; 봤어요 lampau, 보세요 permintaan, 봅니다 present formal.',
      '내일 + dự định ngôi 1 buộc tương lai -(으)ㄹ 거예요; 봤어요 quá khứ, 보세요 lời nhờ, 봅니다 hiện tại trang trọng.',
      '내일＋一人称の意志が未来 -(으)ㄹ 거예요 を要求。봤어요 は過去、보세요 は依頼、봅니다 は格式の現在。',
    ),
  },
  {
    ko: '-(으)ㄹ 거예요',
    sentence: '이번 주말에 가족하고 부산에 {}.',
    answer: '갈 거예요',
    distractors: ['갔어요', '가세요', '갑니다'],
    trans: L(
      "This weekend I'm going to go to Busan with my family.",
      'Este fin de semana voy a ir a Busan con mi familia.',
      'Ce week-end, je vais aller à Busan avec ma famille.',
      'Neste fim de semana vou a Busan com a minha família.',
      'สุดสัปดาห์นี้จะไปปูซานกับครอบครัว',
      'Akhir pekan ini saya akan pergi ke Busan bersama keluarga.',
      'Cuối tuần này tôi sẽ đi Busan với gia đình.',
      '今週末、家族とプサンに行くつもりです。',
    ),
    why: L(
      '이번 주말에 (this coming weekend) plans the future, so -(으)ㄹ 거예요; 갔어요 past, 가세요 request, 갑니다 formal present habitual.',
      '이번 주말에 (este fin de semana próximo) planea el futuro, por eso -(으)ㄹ 거예요; 갔어요 pasado, 가세요 petición, 갑니다 presente formal.',
      '이번 주말에 (ce week-end à venir) planifie le futur, donc -(으)ㄹ 거예요 ; 갔어요 passé, 가세요 demande, 갑니다 présent formel.',
      '이번 주말에 (neste próximo fim de semana) planeja o futuro, logo -(으)ㄹ 거예요; 갔어요 passado, 가세요 pedido, 갑니다 presente formal.',
      '이번 주말에 (สุดสัปดาห์นี้ที่จะถึง) วางแผนอนาคต จึงใช้ -(으)ㄹ 거예요; 갔어요 อดีต, 가세요 คำขอ, 갑니다 ปัจจุบันทางการ',
      '이번 주말에 (akhir pekan mendatang) merencanakan masa depan, jadi -(으)ㄹ 거예요; 갔어요 lampau, 가세요 permintaan, 갑니다 present formal.',
      '이번 주말에 (cuối tuần sắp tới) lên kế hoạch tương lai nên -(으)ㄹ 거예요; 갔어요 quá khứ, 가세요 lời nhờ, 갑니다 hiện tại trang trọng.',
      '이번 주말에（今度の週末）は未来の予定なので -(으)ㄹ 거예요。갔어요 は過去、가세요 は依頼、갑니다 は格式の現在。',
    ),
  },
  {
    ko: '-(으)ㄹ 거예요',
    sentence: '다음 달부터 저는 한국어를 {}.',
    answer: '배울 거예요',
    distractors: ['배웠어요', '배우세요', '배웁니다'],
    trans: L(
      "Starting next month, I'm going to learn Korean.",
      'A partir del mes que viene, voy a aprender coreano.',
      'À partir du mois prochain, je vais apprendre le coréen.',
      'A partir do mês que vem, vou aprender coreano.',
      'ตั้งแต่เดือนหน้าฉันจะเรียนภาษาเกาหลี',
      'Mulai bulan depan saya akan belajar bahasa Korea.',
      'Từ tháng sau tôi sẽ học tiếng Hàn.',
      '来月から私は韓国語を学ぶつもりです。',
    ),
    why: L(
      '다음 달부터 (from next month) projects future intent, so -(으)ㄹ 거예요; 배웠어요 past, 배우세요 request, 배웁니다 formal present.',
      '다음 달부터 (desde el mes que viene) proyecta intención futura, por eso -(으)ㄹ 거예요; 배웠어요 pasado, 배우세요 petición, 배웁니다 presente formal.',
      '다음 달부터 (à partir du mois prochain) projette une intention future, donc -(으)ㄹ 거예요 ; 배웠어요 passé, 배우세요 demande, 배웁니다 présent formel.',
      '다음 달부터 (a partir do mês que vem) projeta intenção futura, logo -(으)ㄹ 거예요; 배웠어요 passado, 배우세요 pedido, 배웁니다 presente formal.',
      '다음 달부터 (ตั้งแต่เดือนหน้า) บ่งเจตนาอนาคต จึงใช้ -(으)ㄹ 거예요; 배웠어요 อดีต, 배우세요 คำขอ, 배웁니다 ปัจจุบันทางการ',
      '다음 달부터 (mulai bulan depan) memproyeksikan niat masa depan, jadi -(으)ㄹ 거예요; 배웠어요 lampau, 배우세요 permintaan, 배웁니다 present formal.',
      '다음 달부터 (từ tháng sau) thể hiện dự định tương lai nên -(으)ㄹ 거예요; 배웠어요 quá khứ, 배우세요 lời nhờ, 배웁니다 hiện tại trang trọng.',
      '다음 달부터（来月から）は未来の意志を示すので -(으)ㄹ 거예요。배웠어요 は過去、배우세요 は依頼、배웁니다 は格式の現在。',
    ),
  },
  {
    ko: '-(으)세요',
    sentence: '위험하니까 여기에서 사진을 찍지 마시고 저쪽으로 {}.',
    answer: '가세요',
    distractors: ['갔어요', '갈 거예요', '갑니다'],
    trans: L(
      "It's dangerous, so don't take photos here; please go over there.",
      'Es peligroso, así que no tome fotos aquí; vaya hacia allá, por favor.',
      "C'est dangereux, alors ne prenez pas de photos ici ; allez par là, s'il vous plaît.",
      'É perigoso, então não tire fotos aqui; vá para lá, por favor.',
      'อันตรายนะคะ อย่าถ่ายรูปตรงนี้ ไปทางโน้นนะคะ',
      'Berbahaya, jadi jangan ambil foto di sini; silakan pergi ke sana.',
      'Nguy hiểm nên đừng chụp ảnh ở đây, bạn hãy đi sang bên kia nhé.',
      '危ないので、ここで写真を撮らずにあちらへ行ってください。',
    ),
    why: L(
      'The command chained after -지 마시고 needs the polite imperative -(으)세요; 갔어요 past, 갈 거예요 future, 갑니다 formal declarative — none can be an order here.',
      'El mandato encadenado tras -지 마시고 pide el imperativo cortés -(으)세요; 갔어요 pasado, 갈 거예요 futuro, 갑니다 declarativo formal — ninguno puede ser una orden.',
      "L'ordre enchaîné après -지 마시고 exige l'impératif poli -(으)세요 ; 갔어요 passé, 갈 거예요 futur, 갑니다 déclaratif formel — aucun ne peut être un ordre.",
      'A ordem encadeada após -지 마시고 pede o imperativo polido -(으)세요; 갔어요 passado, 갈 거예요 futuro, 갑니다 declarativo formal — nenhum pode ser ordem.',
      'คำสั่งที่ต่อจาก -지 마시고 ต้องใช้คำสั่งสุภาพ -(으)세요; 갔어요 อดีต, 갈 거예요 อนาคต, 갑니다 บอกเล่าทางการ ไม่มีอันใดเป็นคำสั่งได้',
      'Perintah yang dirangkai setelah -지 마시고 butuh imperatif sopan -(으)세요; 갔어요 lampau, 갈 거예요 akan datang, 갑니다 deklaratif formal — tak ada yang bisa jadi perintah.',
      'Mệnh lệnh nối sau -지 마시고 cần mệnh lệnh lịch sự -(으)세요; 갔어요 quá khứ, 갈 거예요 tương lai, 갑니다 trần thuật trang trọng — không cái nào là mệnh lệnh được.',
      '-지 마시고 に続く命令には丁寧な命令 -(으)세요 が必要。갔어요 は過去、갈 거예요 は未来、갑니다 は格式の平叙で、命令にならない。',
    ),
  },
  {
    ko: '-(으)세요',
    sentence: '감기에 걸렸으니까 따뜻한 물을 많이 {}.',
    answer: '드세요',
    distractors: ['마셨어요', '마실 거예요', '마십니다'],
    trans: L(
      "You've caught a cold, so please drink a lot of warm water.",
      'Te has resfriado, así que bebe mucha agua tibia, por favor.',
      "Vous avez attrapé un rhume, alors buvez beaucoup d'eau chaude, s'il vous plaît.",
      'Você está resfriado, então beba bastante água morna, por favor.',
      'เป็นหวัดแล้ว ดื่มน้ำอุ่นเยอะ ๆ นะคะ',
      'Anda terkena flu, jadi minumlah banyak air hangat.',
      'Bạn bị cảm rồi nên hãy uống nhiều nước ấm nhé.',
      '風邪をひいたので、温かい水をたくさん飲んでください。',
    ),
    why: L(
      'The advice to a sick listener is a request → polite imperative; 드세요 is the honorific of 마시다, while 마셨어요 past, 마실 거예요 future, 마십니다 formal declarative cannot be the advice.',
      'El consejo a alguien enfermo es una petición → imperativo cortés; 드세요 es el honorífico de 마시다, mientras 마셨어요 pasado, 마실 거예요 futuro, 마십니다 declarativo formal no sirven como consejo.',
      "Le conseil à un malade est une demande → impératif poli ; 드세요 est l'honorifique de 마시다, alors que 마셨어요 passé, 마실 거예요 futur, 마십니다 déclaratif formel ne peuvent être le conseil.",
      'O conselho a alguém doente é um pedido → imperativo polido; 드세요 é o honorífico de 마시다, enquanto 마셨어요 passado, 마실 거예요 futuro, 마십니다 declarativo formal não servem como conselho.',
      'การแนะนำคนป่วยคือคำขอ → คำสั่งสุภาพ; 드세요 เป็นรูปยกย่องของ 마시다 ส่วน 마셨어요 อดีต, 마실 거예요 อนาคต, 마십니다 บอกเล่าทางการ เป็นคำแนะนำไม่ได้',
      'Saran kepada orang sakit adalah permintaan → imperatif sopan; 드세요 bentuk hormat dari 마시다, sedangkan 마셨어요 lampau, 마실 거예요 akan datang, 마십니다 deklaratif formal tak bisa jadi saran.',
      'Lời khuyên cho người bệnh là lời nhờ → mệnh lệnh lịch sự; 드세요 là kính ngữ của 마시다, còn 마셨어요 quá khứ, 마실 거예요 tương lai, 마십니다 trần thuật trang trọng không thể là lời khuyên.',
      '病人への助言は依頼 → 丁寧な命令。드세요 は 마시다 の尊敬語。마셨어요 は過去、마실 거예요 は未来、마십니다 は格式の平叙で助言にならない。',
    ),
  },
  {
    ko: '-(으)세요',
    sentence: '다음 손님, 이쪽 자리에 {}.',
    answer: '앉으세요',
    distractors: ['앉았어요', '앉을 거예요', '앉습니다'],
    trans: L(
      'Next customer, please sit in this seat.',
      'Siguiente cliente, siéntese en este asiento, por favor.',
      "Client suivant, asseyez-vous à cette place, s'il vous plaît.",
      'Próximo cliente, sente-se neste lugar, por favor.',
      'ลูกค้าท่านต่อไป เชิญนั่งตรงนี้นะคะ',
      'Pelanggan berikutnya, silakan duduk di kursi ini.',
      'Khách tiếp theo, mời bạn ngồi vào chỗ này.',
      '次のお客様、こちらの席にお座りください。',
    ),
    why: L(
      'Directing a customer to sit is a request, so -(으)세요; 앉았어요 past, 앉을 거예요 future, 앉습니다 formal declarative — none can invite the customer to sit.',
      'Indicar a un cliente que se siente es una petición, por eso -(으)세요; 앉았어요 pasado, 앉을 거예요 futuro, 앉습니다 declarativo formal — ninguno invita a sentarse.',
      "Inviter un client à s'asseoir est une demande, donc -(으)세요 ; 앉았어요 passé, 앉을 거예요 futur, 앉습니다 déclaratif formel — aucun n'invite à s'asseoir.",
      'Indicar a um cliente que se sente é um pedido, logo -(으)세요; 앉았어요 passado, 앉을 거예요 futuro, 앉습니다 declarativo formal — nenhum convida a sentar.',
      'การเชิญลูกค้าให้นั่งคือคำขอ จึงใช้ -(으)세요; 앉았어요 อดีต, 앉을 거예요 อนาคต, 앉습니다 บอกเล่าทางการ เชิญนั่งไม่ได้',
      'Mempersilakan pelanggan duduk adalah permintaan, jadi -(으)세요; 앉았어요 lampau, 앉을 거예요 akan datang, 앉습니다 deklaratif formal — tak ada yang bisa mempersilakan duduk.',
      'Mời khách ngồi là lời nhờ nên -(으)세요; 앉았어요 quá khứ, 앉을 거예요 tương lai, 앉습니다 trần thuật trang trọng — không cái nào mời ngồi được.',
      '客に着席を促すのは依頼なので -(으)세요。앉았어요 は過去、앉을 거예요 は未来、앉습니다 は格式の平叙で、着席を促せない。',
    ),
  },
  {
    ko: '-ㅂ/습니다',
    sentence: '회의를 시작하겠습니다. 저는 김민수라고 {}.',
    answer: '합니다',
    distractors: ['했어요', '할 거예요', '하세요'],
    trans: L(
      "Let's begin the meeting. My name is Kim Minsu.",
      'Vamos a empezar la reunión. Me llamo Kim Minsu.',
      "Commençons la réunion. Je m'appelle Kim Minsu.",
      'Vamos começar a reunião. Meu nome é Kim Minsu.',
      'จะเริ่มประชุมแล้วครับ ผมชื่อคิมมินซู',
      'Mari kita mulai rapatnya. Nama saya Kim Minsu.',
      'Chúng ta bắt đầu cuộc họp. Tôi tên là Kim Minsu.',
      '会議を始めます。私はキム・ミンスと申します。',
    ),
    why: L(
      'The formal meeting register (시작하겠습니다) plus -라고 하다 self-introduction demands -ㅂ/습니다; 했어요 casual past, 할 거예요 future, 하세요 a request.',
      'El registro formal de reunión (시작하겠습니다) más la presentación -라고 하다 exige -ㅂ/습니다; 했어요 pasado coloquial, 할 거예요 futuro, 하세요 petición.',
      'Le registre formel de réunion (시작하겠습니다) avec la présentation -라고 하다 impose -ㅂ/습니다 ; 했어요 passé familier, 할 거예요 futur, 하세요 demande.',
      'O registro formal de reunião (시작하겠습니다) com a apresentação -라고 하다 exige -ㅂ/습니다; 했어요 passado coloquial, 할 거예요 futuro, 하세요 pedido.',
      'ทะเบียนทางการของการประชุม (시작하겠습니다) กับการแนะนำตัว -라고 하다 ต้องใช้ -ㅂ/습니다; 했어요 อดีตลำลอง, 할 거예요 อนาคต, 하세요 คำขอ',
      'Register formal rapat (시작하겠습니다) plus perkenalan -라고 하다 menuntut -ㅂ/습니다; 했어요 lampau santai, 할 거예요 akan datang, 하세요 permintaan.',
      'Văn phong trang trọng của cuộc họp (시작하겠습니다) cùng cách tự giới thiệu -라고 하다 đòi -ㅂ/습니다; 했어요 quá khứ thân mật, 할 거예요 tương lai, 하세요 lời nhờ.',
      '会議の改まった文体（시작하겠습니다）と -라고 하다 の自己紹介が -ㅂ/습니다 を要求。했어요 はくだけた過去、할 거예요 は未来、하세요 は依頼。',
    ),
  },
  {
    ko: '-ㅂ/습니다',
    sentence: '지금부터 다음 발표를 {}.',
    answer: '시작합니다',
    distractors: ['시작했어요', '시작할 거예요', '시작하세요'],
    trans: L(
      'From now, the next presentation begins.',
      'A partir de ahora comienza la siguiente presentación.',
      'À partir de maintenant, la présentation suivante commence.',
      'A partir de agora começa a próxima apresentação.',
      'ตั้งแต่นี้ การนำเสนอถัดไปจะเริ่มขึ้น',
      'Mulai sekarang, presentasi berikutnya dimulai.',
      'Từ bây giờ, phần trình bày tiếp theo bắt đầu.',
      'ただ今より、次の発表を始めます。',
    ),
    why: L(
      '지금부터 marks a formal present announcement, so -ㅂ/습니다; 시작했어요 past, 시작할 거예요 future, 시작하세요 a request.',
      '지금부터 marca un anuncio formal en presente, por eso -ㅂ/습니다; 시작했어요 pasado, 시작할 거예요 futuro, 시작하세요 petición.',
      '지금부터 marque une annonce formelle au présent, donc -ㅂ/습니다 ; 시작했어요 passé, 시작할 거예요 futur, 시작하세요 demande.',
      '지금부터 marca um anúncio formal no presente, logo -ㅂ/습니다; 시작했어요 passado, 시작할 거예요 futuro, 시작하세요 pedido.',
      '지금부터 บอกการประกาศปัจจุบันแบบทางการ จึงใช้ -ㅂ/습니다; 시작했어요 อดีต, 시작할 거예요 อนาคต, 시작하세요 คำขอ',
      '지금부터 menandai pengumuman formal masa kini, jadi -ㅂ/습니다; 시작했어요 lampau, 시작할 거예요 akan datang, 시작하세요 permintaan.',
      '지금부터 đánh dấu thông báo trang trọng hiện tại nên -ㅂ/습니다; 시작했어요 quá khứ, 시작할 거예요 tương lai, 시작하세요 lời nhờ.',
      '지금부터 が改まった現在の告知を示すので -ㅂ/습니다。시작했어요 は過去、시작할 거예요 は未来、시작하세요 は依頼。',
    ),
  },
  {
    ko: '-ㅂ/습니다',
    sentence: '발표를 마치겠습니다. 끝까지 들어 주셔서 {}.',
    answer: '감사합니다',
    distractors: ['감사했어요', '감사할 거예요', '감사하세요'],
    trans: L(
      'I will conclude the presentation. Thank you for listening to the end.',
      'Voy a concluir la presentación. Gracias por escuchar hasta el final.',
      "Je vais conclure la présentation. Merci de m'avoir écouté jusqu'au bout.",
      'Vou encerrar a apresentação. Obrigado por ouvir até o fim.',
      'จะจบการนำเสนอแล้วครับ ขอบคุณที่รับฟังจนจบ',
      'Saya akhiri presentasinya. Terima kasih telah menyimak sampai akhir.',
      'Tôi xin kết thúc phần trình bày. Cảm ơn đã lắng nghe đến cuối.',
      '発表を終わります。最後まで聞いてくださり、ありがとうございます。',
    ),
    why: L(
      'The formal closing (마치겠습니다) demands the set formal phrase 감사합니다 in -ㅂ/습니다; 감사했어요 casual past, 감사할 거예요 future, 감사하세요 a request — none is the closing thanks.',
      'El cierre formal (마치겠습니다) exige la fórmula 감사합니다 en -ㅂ/습니다; 감사했어요 pasado coloquial, 감사할 거예요 futuro, 감사하세요 petición — ninguno es el agradecimiento de cierre.',
      "La conclusion formelle (마치겠습니다) impose la formule 감사합니다 en -ㅂ/습니다 ; 감사했어요 passé familier, 감사할 거예요 futur, 감사하세요 demande — aucun n'est le remerciement final.",
      'O encerramento formal (마치겠습니다) exige a fórmula 감사합니다 em -ㅂ/습니다; 감사했어요 passado coloquial, 감사할 거예요 futuro, 감사하세요 pedido — nenhum é o agradecimento final.',
      'การปิดท้ายแบบทางการ (마치겠습니다) ต้องใช้สำนวน 감사합니다 รูป -ㅂ/습니다; 감사했어요 อดีตลำลอง, 감사할 거예요 อนาคต, 감사하세요 คำขอ ไม่ใช่คำขอบคุณปิดท้าย',
      'Penutup formal (마치겠습니다) menuntut frasa 감사합니다 dalam -ㅂ/습니다; 감사했어요 lampau santai, 감사할 거예요 akan datang, 감사하세요 permintaan — bukan ucapan terima kasih penutup.',
      'Lời kết trang trọng (마치겠습니다) đòi cụm 감사합니다 ở -ㅂ/습니다; 감사했어요 quá khứ thân mật, 감사할 거예요 tương lai, 감사하세요 lời nhờ — không phải lời cảm ơn kết thúc.',
      '改まった締め（마치겠습니다）は定型句 감사합니다（-ㅂ/습니다）を要求。감사했어요 はくだけた過去、감사할 거예요 は未来、감사하세요 は依頼で、締めの謝辞ではない。',
    ),
  },
  {
    ko: '-아/어요',
    sentence: '동생은 지금 방에서 음악을 {}.',
    answer: '들어요',
    distractors: ['들었어요', '들을 거예요', '들으세요'],
    trans: L(
      'My younger sibling is listening to music in the room right now.',
      'Mi hermano menor está escuchando música en la habitación ahora.',
      'Mon petit frère écoute de la musique dans la chambre en ce moment.',
      'Meu irmão mais novo está ouvindo música no quarto agora.',
      'ตอนนี้น้องกำลังฟังเพลงอยู่ในห้อง',
      'Adik saya sekarang sedang mendengarkan musik di kamar.',
      'Em tôi bây giờ đang nghe nhạc trong phòng.',
      '弟は今、部屋で音楽を聞きます。',
    ),
    why: L(
      '지금 + the non-honorable subject 동생 calls for the plain polite present -아/어요; 들었어요 past, 들을 거예요 future, 들으세요 honorific/request (clashes with 동생).',
      '지금 + el sujeto no honorífico 동생 pide el presente cortés -아/어요; 들었어요 pasado, 들을 거예요 futuro, 들으세요 honorífico/petición (choca con 동생).',
      '지금 + le sujet non honorifique 동생 appelle le présent poli -아/어요 ; 들었어요 passé, 들을 거예요 futur, 들으세요 honorifique/demande (incompatible avec 동생).',
      '지금 + o sujeito não honorífico 동생 pede o presente polido -아/어요; 들었어요 passado, 들을 거예요 futuro, 들으세요 honorífico/pedido (destoa de 동생).',
      '지금 + ประธานที่ไม่ยกย่อง 동생 ต้องการปัจจุบันสุภาพ -아/어요; 들었어요 อดีต, 들을 거예요 อนาคต, 들으세요 ยกย่อง/คำขอ (ขัดกับ 동생)',
      '지금 + subjek non-hormat 동생 memerlukan present sopan -아/어요; 들었어요 lampau, 들을 거예요 akan datang, 들으세요 hormat/permintaan (bentrok dengan 동생).',
      '지금 + chủ thể không kính ngữ 동생 cần hiện tại lịch sự -아/어요; 들었어요 quá khứ, 들을 거예요 tương lai, 들으세요 kính ngữ/lời nhờ (nghịch với 동생).',
      '지금＋目上でない主語 동생 が現在の丁寧形 -아/어요 を求める。들었어요 は過去、들을 거예요 は未来、들으세요 は尊敬・依頼で 동생 と矛盾。',
    ),
  },
  {
    ko: '-아/어요',
    sentence: '저는 보통 주말에 집에서 {}.',
    answer: '쉬어요',
    distractors: ['쉬었어요', '쉴 거예요', '쉽니다'],
    trans: L(
      'I usually rest at home on weekends.',
      'Normalmente descanso en casa los fines de semana.',
      'Le week-end, je me repose généralement à la maison.',
      'Normalmente eu descanso em casa nos fins de semana.',
      'ปกติวันหยุดฉันพักผ่อนที่บ้าน',
      'Saya biasanya beristirahat di rumah pada akhir pekan.',
      'Cuối tuần tôi thường nghỉ ngơi ở nhà.',
      '私はたいてい週末に家で休みます。',
    ),
    why: L(
      '보통 (usually) signals a habitual present in everyday 해요체 -아/어요; 쉬었어요 past, 쉴 거예요 future, 쉽니다 formal register (clashes with the casual 저는…보통 frame).',
      '보통 (normalmente) señala un presente habitual en 해요체 cotidiano -아/어요; 쉬었어요 pasado, 쉴 거예요 futuro, 쉽니다 registro formal (choca con el marco coloquial 저는…보통).',
      "보통 (généralement) indique un présent d'habitude en 해요체 courant -아/어요 ; 쉬었어요 passé, 쉴 거예요 futur, 쉽니다 registre formel (incompatible avec le cadre familier 저는…보통).",
      '보통 (normalmente) sinaliza um presente habitual no 해요체 do dia a dia -아/어요; 쉬었어요 passado, 쉴 거예요 futuro, 쉽니다 registro formal (destoa do enquadramento coloquial 저는…보통).',
      '보통 (ปกติ) บ่งปัจจุบันที่เป็นนิสัยใน 해요체 ทั่วไป -아/어요; 쉬었어요 อดีต, 쉴 거예요 อนาคต, 쉽니다 ทะเบียนทางการ (ขัดกับกรอบลำลอง 저는…보통)',
      '보통 (biasanya) menandai present kebiasaan dalam 해요체 sehari-hari -아/어요; 쉬었어요 lampau, 쉴 거예요 akan datang, 쉽니다 register formal (bentrok dengan bingkai santai 저는…보통).',
      '보통 (thường) báo hiệu hiện tại thói quen ở 해요체 đời thường -아/어요; 쉬었어요 quá khứ, 쉴 거예요 tương lai, 쉽니다 văn phong trang trọng (nghịch với khung thân mật 저는…보통).',
      '보통（普段）は日常の 해요체 の習慣の現在 -아/어요 を示す。쉬었어요 は過去、쉴 거예요 は未来、쉽니다 は格式体で、くだけた 저는…보통 の枠と矛盾。',
    ),
  },
  {
    ko: '-아/어요',
    sentence: '친구는 지금 부엌에서 저녁을 {}.',
    answer: '만들어요',
    distractors: ['만들었어요', '만들 거예요', '만드세요'],
    trans: L(
      'My friend is making dinner in the kitchen right now.',
      'Mi amigo está haciendo la cena en la cocina ahora.',
      'Mon ami prépare le dîner dans la cuisine en ce moment.',
      'Meu amigo está fazendo o jantar na cozinha agora.',
      'ตอนนี้เพื่อนกำลังทำมื้อเย็นอยู่ในครัว',
      'Teman saya sekarang sedang membuat makan malam di dapur.',
      'Bạn tôi bây giờ đang nấu bữa tối trong bếp.',
      '友達は今、台所で夕飯を作ります。',
    ),
    why: L(
      '지금 + the non-honorable subject 친구 fixes the present polite -아/어요; 만들었어요 past, 만들 거예요 future, 만드세요 honorific/request (clashes with 친구).',
      '지금 + el sujeto no honorífico 친구 fija el presente cortés -아/어요; 만들었어요 pasado, 만들 거예요 futuro, 만드세요 honorífico/petición (choca con 친구).',
      '지금 + le sujet non honorifique 친구 fixe le présent poli -아/어요 ; 만들었어요 passé, 만들 거예요 futur, 만드세요 honorifique/demande (incompatible avec 친구).',
      '지금 + o sujeito não honorífico 친구 fixa o presente polido -아/어요; 만들었어요 passado, 만들 거예요 futuro, 만드세요 honorífico/pedido (destoa de 친구).',
      '지금 + ประธานที่ไม่ยกย่อง 친구 กำหนดปัจจุบันสุภาพ -아/어요; 만들었어요 อดีต, 만들 거예요 อนาคต, 만드세요 ยกย่อง/คำขอ (ขัดกับ 친구)',
      '지금 + subjek non-hormat 친구 menetapkan present sopan -아/어요; 만들었어요 lampau, 만들 거예요 akan datang, 만드세요 hormat/permintaan (bentrok dengan 친구).',
      '지금 + chủ thể không kính ngữ 친구 ấn định hiện tại lịch sự -아/어요; 만들었어요 quá khứ, 만들 거예요 tương lai, 만드세요 kính ngữ/lời nhờ (nghịch với 친구).',
      '지금＋目上でない主語 친구 が現在の丁寧形 -아/어요 を確定。만들었어요 は過去、만들 거예요 は未来、만드세요 は尊敬・依頼で 친구 と矛盾。',
    ),
  },
  {
    ko: '-고',
    sentence: '저는 키가 크{} 머리가 길어요.',
    answer: '크고',
    distractors: ['커서', '크지만', '크면'],
    trans: L(
      'I am tall and have long hair.',
      'Soy alto y tengo el pelo largo.',
      "Je suis grand et j'ai les cheveux longs.",
      'Eu sou alto e tenho cabelo comprido.',
      'ฉันตัวสูงและผมยาว',
      'Saya tinggi dan berambut panjang.',
      'Tôi cao và tóc dài.',
      '私は背が高くて髪が長いです。',
    ),
    why: L(
      'Two unrelated traits simply listed → -고; -아/어서 would falsely make tallness the cause of long hair, -지만 needs a contrast (none), -(으)면 a condition (none).',
      'Dos rasgos sin relación, solo enumerados → -고; -아/어서 haría la altura causa del pelo largo (falso), -지만 exige contraste (no hay), -(으)면 condición (no hay).',
      'Deux traits sans lien, simplement listés → -고 ; -아/어서 ferait de la taille la cause des cheveux longs (faux), -지만 exige un contraste (absent), -(으)면 une condition (absente).',
      'Dois traços sem relação, apenas listados → -고; -아/어서 faria a altura causar o cabelo longo (falso), -지만 exige contraste (não há), -(으)면 condição (não há).',
      'ลักษณะสองอย่างที่ไม่เกี่ยวกัน เรียงเฉย ๆ → -고; -아/어서 จะทำให้ความสูงเป็นเหตุของผมยาว (ผิด), -지만 ต้องมีความขัดแย้ง (ไม่มี), -(으)면 ต้องมีเงื่อนไข (ไม่มี).',
      'Dua sifat tak berkaitan yang sekadar didaftar → -고; -아/어서 keliru menjadikan tinggi sebab rambut panjang, -지만 perlu kontras (tak ada), -(으)면 perlu syarat (tak ada).',
      'Hai đặc điểm không liên quan chỉ được liệt kê → -고; -아/어서 biến cái cao thành nguyên nhân tóc dài (sai), -지만 cần tương phản (không có), -(으)면 cần điều kiện (không có).',
      '無関係な二つの特徴を単に並列 → -고。-아/어서では背の高さが髪の長さの原因になり不自然、-지만は逆接（無し）、-(으)면は条件（無し）が必要。',
    ),
  },
  {
    ko: '-고',
    sentence: '이 방은 넓{} 깨끗해요.',
    answer: '넓고',
    distractors: ['넓어서', '넓지만', '넓으면'],
    trans: L(
      'This room is spacious and clean.',
      'Esta habitación es amplia y está limpia.',
      'Cette chambre est spacieuse et propre.',
      'Este quarto é espaçoso e limpo.',
      'ห้องนี้กว้างและสะอาด',
      'Kamar ini luas dan bersih.',
      'Phòng này rộng và sạch.',
      'この部屋は広くてきれいです。',
    ),
    why: L(
      'Two positive traits co-listed → -고; -아/어서 would force spaciousness to cause cleanliness (illogical), -지만 needs a contrast, -(으)면 a condition, neither present.',
      'Dos cualidades positivas enumeradas → -고; -아/어서 haría que lo amplio cause lo limpio (ilógico), -지만 exige contraste, -(으)면 condición, ninguna presente.',
      'Deux qualités positives listées → -고 ; -아/어서 ferait que la grandeur cause la propreté (illogique), -지만 exige un contraste, -(으)면 une condition, absentes.',
      'Duas qualidades positivas listadas → -고; -아/어서 faria o espaço causar a limpeza (ilógico), -지만 exige contraste, -(으)면 condição, ausentes.',
      'คุณสมบัติเชิงบวกสองอย่างเรียงกัน → -고; -아/어서 จะทำให้ความกว้างเป็นเหตุของความสะอาด (ไม่สมเหตุผล), -지만 ต้องมีความขัดแย้ง, -(으)면 ต้องมีเงื่อนไข ซึ่งไม่มี.',
      'Dua sifat positif didaftar → -고; -아/어서 memaksa keluasan menyebabkan kebersihan (tak logis), -지만 perlu kontras, -(으)면 perlu syarat, tak ada.',
      'Hai đặc điểm tích cực liệt kê → -고; -아/어서 buộc cái rộng gây ra cái sạch (phi lý), -지만 cần tương phản, -(으)면 cần điều kiện, đều không có.',
      '肯定的特徴を二つ並列 → -고。-아/어서は広さが清潔さの原因になり不自然、-지만は逆接、-(으)면は条件が必要だが無い。',
    ),
  },
  {
    ko: '-고',
    sentence: '동생은 빵을 먹{} 저는 밥을 먹어요.',
    answer: '먹고',
    distractors: ['먹어서', '먹으면', '먹은'],
    trans: L(
      'My younger sibling eats bread and I eat rice.',
      'Mi hermano menor come pan y yo como arroz.',
      'Mon cadet mange du pain et moi je mange du riz.',
      'Meu irmão mais novo come pão e eu como arroz.',
      'น้องกินขนมปังส่วนฉันกินข้าว',
      'Adik saya makan roti dan saya makan nasi.',
      'Em tôi ăn bánh mì còn tôi ăn cơm.',
      '弟はパンを食べて私はご飯を食べます。',
    ),
    why: L(
      "Two different subjects' parallel actions → -고; -아/어서 needs one shared subject in a cause/sequence (so 먹어서 is impossible here), -(으)면 makes a false condition, -은 is a noun-modifier ending that can't link clauses.",
      'Acciones paralelas de sujetos distintos → -고; -아/어서 exige un mismo sujeto en causa/secuencia (먹어서 imposible aquí), -(으)면 crea condición falsa, -은 es terminación de modificador nominal, no enlaza cláusulas.',
      'Actions parallèles de sujets différents → -고 ; -아/어서 exige un même sujet en cause/suite (먹어서 impossible ici), -(으)면 crée une fausse condition, -은 est une terminaison de modificateur nominal, ne relie pas les propositions.',
      'Ações paralelas de sujeitos diferentes → -고; -아/어서 exige o mesmo sujeito em causa/sequência (먹어서 impossível aqui), -(으)면 cria condição falsa, -은 é terminação de modificador nominal, não liga orações.',
      'การกระทำคู่ขนานของคนละประธาน → -고; -아/어서 ต้องเป็นประธานเดียวกันในเหตุ/ลำดับ (먹어서 ใช้ไม่ได้), -(으)면 สร้างเงื่อนไขเท็จ, -은 เป็นวิภัตติขยายนาม เชื่อมประโยคไม่ได้.',
      'Aksi paralel dari subjek berbeda → -고; -아/어서 butuh subjek sama dalam sebab/urutan (먹어서 mustahil di sini), -(으)면 membuat syarat palsu, -은 akhiran pewatas nomina, tak bisa menghubungkan klausa.',
      'Hành động song song của hai chủ ngữ khác nhau → -고; -아/어서 cần cùng một chủ ngữ trong nguyên nhân/trình tự (먹어서 không thể ở đây), -(으)면 tạo điều kiện sai, -은 là đuôi định ngữ danh từ, không nối mệnh đề.',
      '別々の主語の並行動作 → -고。-아/어서は原因・連続で主語が同一でなければならず（ここでは먹어서は不可）、-(으)면は偽の条件、-은は連体形語尾で節をつなげない。',
    ),
  },
  {
    ko: '-아/어서',
    sentence: '비가 많이 와{} 우리는 집에 있었어요.',
    answer: '와서',
    distractors: ['오면', '오지만', '오는'],
    trans: L(
      'It rained a lot, so we stayed home.',
      'Llovió mucho, así que nos quedamos en casa.',
      'Il a beaucoup plu, alors nous sommes restés à la maison.',
      'Choveu muito, então ficamos em casa.',
      'ฝนตกหนักพวกเราเลยอยู่บ้าน',
      'Hujan turun lebat, jadi kami tinggal di rumah.',
      'Trời mưa to nên chúng tôi ở nhà.',
      '雨がたくさん降ったので、私たちは家にいました。',
    ),
    why: L(
      "Rain is the realized reason for a past result (있었어요) → -아/어서; -(으)면 is hypothetical (clashes with the past fact), -지만 needs a contrast (none), -는 is a noun-modifier ending that can't link clauses.",
      'La lluvia es la causa real de un resultado pasado (있었어요) → -아/어서; -(으)면 es hipotético (choca con el hecho pasado), -지만 exige contraste (no hay), -는 es modificador nominal, no enlaza cláusulas.',
      "La pluie est la cause réelle d'un résultat passé (있었어요) → -아/어서 ; -(으)면 est hypothétique (incompatible avec le fait passé), -지만 exige un contraste (absent), -는 est un modificateur nominal, ne relie pas les propositions.",
      'A chuva é a causa real de um resultado passado (있었어요) → -아/어서; -(으)면 é hipotético (choca com o fato passado), -지만 exige contraste (não há), -는 é modificador nominal, não liga orações.',
      'ฝนคือเหตุจริงของผลในอดีต (있었어요) → -아/어서; -(으)면 เป็นการสมมติ (ขัดกับข้อเท็จจริงอดีต), -지만 ต้องมีความขัดแย้ง (ไม่มี), -는 เป็นวิภัตติขยายนาม เชื่อมประโยคไม่ได้.',
      'Hujan adalah sebab nyata dari hasil lampau (있었어요) → -아/어서; -(으)면 bersifat andaian (bentrok dengan fakta lampau), -지만 perlu kontras (tak ada), -는 pewatas nomina, tak menghubungkan klausa.',
      'Mưa là nguyên nhân thực của kết quả quá khứ (있었어요) → -아/어서; -(으)면 mang tính giả định (mâu thuẫn với sự thật quá khứ), -지만 cần tương phản (không có), -는 là định ngữ danh từ, không nối mệnh đề.',
      '雨が過去の結果（있었어요）の現実の原因 → -아/어서。-(으)면は仮定で過去の事実と矛盾、-지만は逆接（無し）、-는は連体形語尾で節をつなげない。',
    ),
  },
  {
    ko: '-아/어서',
    sentence: '어제 너무 피곤해{} 일찍 잤어요.',
    answer: '피곤해서',
    distractors: ['피곤하면', '피곤하지만', '피곤한'],
    trans: L(
      'Yesterday I was so tired that I went to bed early.',
      'Ayer estaba tan cansado que me acosté temprano.',
      "Hier, j'étais si fatigué que je me suis couché tôt.",
      'Ontem eu estava tão cansado que dormi cedo.',
      'เมื่อวานเหนื่อยมากเลยนอนเร็ว',
      'Kemarin saya sangat lelah, jadi tidur lebih awal.',
      'Hôm qua tôi quá mệt nên đi ngủ sớm.',
      '昨日はとても疲れたので早く寝ました。',
    ),
    why: L(
      "Tiredness is the realized reason for a past act (어제…잤어요) → -아/어서; -(으)면 is hypothetical (clashes with 어제), -지만 needs a contrast (none), -ㄴ is a noun-modifier ending that can't link clauses.",
      'El cansancio es la causa real de un acto pasado (어제…잤어요) → -아/어서; -(으)면 es hipotético (choca con 어제), -지만 exige contraste (no hay), -ㄴ es modificador nominal, no enlaza cláusulas.',
      "La fatigue est la cause réelle d'un acte passé (어제…잤어요) → -아/어서 ; -(으)면 est hypothétique (incompatible avec 어제), -지만 exige un contraste (absent), -ㄴ est un modificateur nominal, ne relie pas les propositions.",
      'O cansaço é a causa real de um ato passado (어제…잤어요) → -아/어서; -(으)면 é hipotético (choca com 어제), -지만 exige contraste (não há), -ㄴ é modificador nominal, não liga orações.',
      'ความเหนื่อยคือเหตุจริงของการกระทำในอดีต (어제…잤어요) → -아/어서; -(으)면 เป็นการสมมติ (ขัดกับ 어제), -지만 ต้องมีความขัดแย้ง (ไม่มี), -ㄴ เป็นวิภัตติขยายนาม เชื่อมประโยคไม่ได้.',
      'Lelah adalah sebab nyata dari tindakan lampau (어제…잤어요) → -아/어서; -(으)면 andaian (bentrok dengan 어제), -지만 perlu kontras (tak ada), -ㄴ pewatas nomina, tak menghubungkan klausa.',
      'Mệt là nguyên nhân thực của hành động quá khứ (어제…잤어요) → -아/어서; -(으)면 là giả định (mâu thuẫn với 어제), -지만 cần tương phản (không có), -ㄴ là định ngữ danh từ, không nối mệnh đề.',
      '疲れが過去の行為（어제…잤어요）の現実の原因 → -아/어서。-(으)면は仮定で어제と矛盾、-지만は逆接（無し）、-ㄴは連体形語尾で節をつなげない。',
    ),
  },
  {
    ko: '-아/어서',
    sentence: '늦{} 정말 죄송합니다.',
    answer: '늦어서',
    distractors: ['늦고', '늦지만', '늦으면'],
    trans: L(
      "I'm really sorry for being late.",
      'Lamento mucho llegar tarde.',
      "Je suis vraiment désolé d'être en retard.",
      'Sinto muito por estar atrasado.',
      'ขอโทษจริง ๆ ที่มาสาย',
      'Saya benar-benar minta maaf karena terlambat.',
      'Tôi thực sự xin lỗi vì đã đến muộn.',
      '遅れて本当に申し訳ありません。',
    ),
    why: L(
      'Apology states its cause → fixed -아/어서 죄송합니다; -고 only lists, -지만 contrasts, -(으)면 is a condition, none introduces the reason being apologized for.',
      'La disculpa indica su causa → fijo -아/어서 죄송합니다; -고 solo enumera, -지만 contrasta, -(으)면 es condición, ninguna introduce el motivo de la disculpa.',
      "L'excuse indique sa cause → -아/어서 죄송합니다 figé ; -고 énumère, -지만 contraste, -(으)면 est une condition, aucune n'introduit le motif de l'excuse.",
      'A desculpa indica sua causa → fixo -아/어서 죄송합니다; -고 só lista, -지만 contrasta, -(으)면 é condição, nenhuma introduz o motivo da desculpa.',
      'คำขอโทษบอกเหตุ → -아/어서 죄송합니다 ตายตัว; -고 แค่เรียง, -지만 ขัดแย้ง, -(으)면 เป็นเงื่อนไข ไม่มีตัวใดบอกเหตุของการขอโทษ.',
      'Permintaan maaf menyatakan sebabnya → tetap -아/어서 죄송합니다; -고 hanya mendaftar, -지만 kontras, -(으)면 syarat, tak ada yang memperkenalkan alasan maaf.',
      'Lời xin lỗi nêu nguyên nhân → cố định -아/어서 죄송합니다; -고 chỉ liệt kê, -지만 tương phản, -(으)면 là điều kiện, đều không nêu lý do xin lỗi.',
      '謝罪は理由を述べる → 定型の-아/어서 죄송합니다。-고は羅列、-지만は逆接、-(으)면は条件で、謝罪の理由を導けない。',
    ),
  },
  {
    ko: '-지만',
    sentence: '이 옷이 비싸{} 안 예뻐요.',
    answer: '비싸지만',
    distractors: ['비싸고', '비싸서', '비싸면'],
    trans: L(
      'These clothes are expensive but not pretty.',
      'Esta ropa es cara pero no es bonita.',
      'Ces vêtements sont chers mais pas jolis.',
      'Esta roupa é cara, mas não é bonita.',
      'เสื้อผ้าชุดนี้แพงแต่ไม่สวย',
      'Baju ini mahal tapi tidak cantik.',
      'Bộ đồ này đắt nhưng không đẹp.',
      'この服は高いけどかわいくないです。',
    ),
    why: L(
      'Expensive yet not-pretty defies expectation → contrast -지만; -고 merely lists, -아/어서 would make price the cause of ugliness (illogical), -(으)면 is a condition (none).',
      'Caro pero no bonito desafía lo esperado → contraste -지만; -고 solo enumera, -아/어서 haría el precio causa de la fealdad (ilógico), -(으)면 es condición (no hay).',
      "Cher mais pas joli déjoue l'attente → contraste -지만 ; -고 énumère, -아/어서 ferait du prix la cause de la laideur (illogique), -(으)면 est une condition (absente).",
      'Caro mas não bonito contraria a expectativa → contraste -지만; -고 só lista, -아/어서 faria o preço causar a feiura (ilógico), -(으)면 é condição (não há).',
      'แพงแต่ไม่สวยขัดกับที่คาด → ขัดแย้ง -지만; -고 แค่เรียง, -아/어서 จะทำให้ราคาเป็นเหตุของความไม่สวย (ไม่สมเหตุผล), -(으)면 เป็นเงื่อนไข (ไม่มี).',
      'Mahal tetapi tidak cantik melawan harapan → kontras -지만; -고 hanya mendaftar, -아/어서 menjadikan harga sebab keburukan (tak logis), -(으)면 syarat (tak ada).',
      'Đắt mà không đẹp trái với kỳ vọng → tương phản -지만; -고 chỉ liệt kê, -아/어서 biến giá thành nguyên nhân của sự xấu (phi lý), -(으)면 là điều kiện (không có).',
      '高いのにかわいくない＝予想に反する → 逆接の-지만。-고は羅列、-아/어서は値段が不格好さの原因になり不自然、-(으)면は条件（無し）。',
    ),
  },
  {
    ko: '-지만',
    sentence: '한국어는 어렵{} 정말 재미있어요.',
    answer: '어렵지만',
    distractors: ['어렵고', '어려워서', '어려우면'],
    trans: L(
      "Korean is hard, but it's really interesting.",
      'El coreano es difícil, pero es muy interesante.',
      'Le coréen est difficile, mais vraiment intéressant.',
      'O coreano é difícil, mas muito interessante.',
      'ภาษาเกาหลียากแต่สนุกมากจริง ๆ',
      'Bahasa Korea sulit, tapi sangat menarik.',
      'Tiếng Hàn khó nhưng thật sự thú vị.',
      '韓国語は難しいけど本当に面白いです。',
    ),
    why: L(
      'Hard yet fun defies expectation → contrast -지만; -고 just lists, -아/어서 would make difficulty the cause of fun (illogical), -(으)면 is a condition (none).',
      'Difícil pero divertido desafía lo esperado → contraste -지만; -고 enumera, -아/어서 haría la dificultad causa de la diversión (ilógico), -(으)면 es condición (no hay).',
      "Difficile mais amusant déjoue l'attente → contraste -지만 ; -고 énumère, -아/어서 ferait de la difficulté la cause du plaisir (illogique), -(으)면 est une condition (absente).",
      'Difícil mas divertido contraria a expectativa → contraste -지만; -고 lista, -아/어서 faria a dificuldade causar a diversão (ilógico), -(으)면 é condição (não há).',
      'ยากแต่สนุกขัดกับที่คาด → ขัดแย้ง -지만; -고 เรียง, -아/어서 จะทำให้ความยากเป็นเหตุของความสนุก (ไม่สมเหตุผล), -(으)면 เป็นเงื่อนไข (ไม่มี).',
      'Sulit tetapi menyenangkan melawan harapan → kontras -지만; -고 mendaftar, -아/어서 menjadikan kesulitan sebab kesenangan (tak logis), -(으)면 syarat (tak ada).',
      'Khó mà thú vị trái với kỳ vọng → tương phản -지만; -고 liệt kê, -아/어서 biến cái khó thành nguyên nhân thú vị (phi lý), -(으)면 là điều kiện (không có).',
      '難しいのに面白い＝予想に反する → 逆接の-지만。-고は羅列、-아/어서は難しさが面白さの原因になり不自然、-(으)면は条件（無し）。',
    ),
  },
  {
    ko: '-지만',
    sentence: '동생은 키가 크{} 저는 작아요.',
    answer: '크지만',
    distractors: ['크고', '커서', '크면'],
    trans: L(
      "My younger sibling is tall, but I'm short.",
      'Mi hermano menor es alto, pero yo soy bajo.',
      'Mon cadet est grand, mais moi je suis petit.',
      'Meu irmão mais novo é alto, mas eu sou baixo.',
      'น้องตัวสูงแต่ฉันตัวเตี้ย',
      'Adik saya tinggi, tetapi saya pendek.',
      'Em tôi cao nhưng tôi thấp.',
      '弟は背が高いけど、私は背が低いです。',
    ),
    why: L(
      "Tall sibling vs short me are opposed → contrast -지만; -고 only lists, -아/어서 needs one subject and a cause link (the sibling's height can't cause my shortness), -(으)면 is a condition (none).",
      'Hermano alto frente a yo bajo se oponen → contraste -지만; -고 enumera, -아/어서 exige un sujeto y causa (su altura no causa mi baja estatura), -(으)면 es condición (no hay).',
      "Cadet grand contre moi petit s'opposent → contraste -지만 ; -고 énumère, -아/어서 exige un sujet et une cause (sa taille ne cause pas ma petitesse), -(으)면 est une condition (absente).",
      'Irmão alto x eu baixo se opõem → contraste -지만; -고 enumera, -아/어서 exige um sujeito e causa (a altura dele não causa minha baixa estatura), -(으)면 é condição (não há).',
      'น้องสูงกับฉันเตี้ยขัดกัน → ขัดแย้ง -지만; -고 เรียง, -아/어서 ต้องประธานเดียวและเป็นเหตุ (ความสูงของน้องไม่ทำให้ฉันเตี้ย), -(으)면 เป็นเงื่อนไข (ไม่มี).',
      'Adik tinggi vs saya pendek bertentangan → kontras -지만; -고 mendaftar, -아/어서 butuh satu subjek dan sebab (tinggi adik tak menyebabkan saya pendek), -(으)면 syarat (tak ada).',
      'Em cao và tôi thấp đối lập → tương phản -지만; -고 liệt kê, -아/어서 cần cùng chủ ngữ và quan hệ nhân quả (chiều cao của em không làm tôi thấp), -(으)면 là điều kiện (không có).',
      '「弟は高い」と「私は低い」が対立 → 逆接の-지만。-고は羅列、-아/어서は同一主語と因果が必要（弟の身長が私の低さの原因にならない）、-(으)면は条件（無し）。',
    ),
  },
  {
    ko: '-(으)면',
    sentence: '내일 비가 오{} 우리는 안 갈 거예요.',
    answer: '오면',
    distractors: ['오고', '와서', '오지만'],
    trans: L(
      "If it rains tomorrow, we won't go.",
      'Si llueve mañana, no iremos.',
      "S'il pleut demain, nous n'irons pas.",
      'Se chover amanhã, não vamos.',
      'ถ้าพรุ่งนี้ฝนตก พวกเราจะไม่ไป',
      'Kalau besok hujan, kami tidak akan pergi.',
      'Nếu ngày mai trời mưa, chúng tôi sẽ không đi.',
      '明日雨が降ったら、私たちは行きません。',
    ),
    why: L(
      'Future hypothetical (내일 + 거예요) → condition -(으)면; -아/어서 marks a realized cause (clashes with the unrealized future), -고 lists, -지만 contrasts.',
      'Hipótesis futura (내일 + 거예요) → condición -(으)면; -아/어서 marca causa real (choca con el futuro no realizado), -고 enumera, -지만 contrasta.',
      'Hypothèse future (내일 + 거예요) → condition -(으)면 ; -아/어서 marque une cause réalisée (incompatible avec le futur non réalisé), -고 énumère, -지만 contraste.',
      'Hipótese futura (내일 + 거예요) → condição -(으)면; -아/어서 marca causa realizada (choca com o futuro não realizado), -고 enumera, -지만 contrasta.',
      'สมมติอนาคต (내일 + 거예요) → เงื่อนไข -(으)면; -아/어서 บอกเหตุที่เกิดจริง (ขัดกับอนาคตที่ยังไม่เกิด), -고 เรียง, -지만 ขัดแย้ง.',
      'Pengandaian masa depan (내일 + 거예요) → syarat -(으)면; -아/어서 menandai sebab nyata (bentrok dengan masa depan yang belum terjadi), -고 mendaftar, -지만 kontras.',
      'Giả định tương lai (내일 + 거예요) → điều kiện -(으)면; -아/어서 đánh dấu nguyên nhân đã xảy ra (mâu thuẫn với tương lai chưa xảy ra), -고 liệt kê, -지만 tương phản.',
      '未来の仮定（내일＋거예요）→ 条件の-(으)면。-아/어서は実現した原因を示し未実現の未来と矛盾、-고は羅列、-지만は逆接。',
    ),
  },
  {
    ko: '-(으)면',
    sentence: '시간이 있{} 저한테 전화하세요.',
    answer: '있으면',
    distractors: ['있고', '있어서', '있지만'],
    trans: L(
      'If you have time, please call me.',
      'Si tienes tiempo, llámame por favor.',
      'Si vous avez le temps, appelez-moi.',
      'Se tiver tempo, me ligue por favor.',
      'ถ้ามีเวลา กรุณาโทรหาฉันด้วย',
      'Kalau ada waktu, tolong telepon saya.',
      'Nếu có thời gian, hãy gọi cho tôi nhé.',
      '時間があったら、私に電話してください。',
    ),
    why: L(
      'An imperative 2nd clause (전화하세요) demands a condition → -(으)면; -아/어서 cannot precede a command, -고 lists, -지만 contrasts.',
      'La 2ª cláusula imperativa (전화하세요) exige condición → -(으)면; -아/어서 no puede preceder a un mandato, -고 enumera, -지만 contrasta.',
      'La 2e proposition impérative (전화하세요) exige une condition → -(으)면 ; -아/어서 ne peut précéder un ordre, -고 énumère, -지만 contraste.',
      'A 2ª oração imperativa (전화하세요) exige condição → -(으)면; -아/어서 não pode preceder uma ordem, -고 enumera, -지만 contrasta.',
      'ประโยคที่สองเป็นคำสั่ง (전화하세요) ต้องมีเงื่อนไข → -(으)면; -아/어서 นำหน้าคำสั่งไม่ได้, -고 เรียง, -지만 ขัดแย้ง.',
      'Klausa kedua imperatif (전화하세요) menuntut syarat → -(으)면; -아/어서 tak bisa mendahului perintah, -고 mendaftar, -지만 kontras.',
      'Mệnh đề sau là mệnh lệnh (전화하세요) đòi điều kiện → -(으)면; -아/어서 không thể đứng trước câu mệnh lệnh, -고 liệt kê, -지만 tương phản.',
      '後文が命令（전화하세요）→ 条件の-(으)면が必要。-아/어서は命令の前に立てず、-고は羅列、-지만は逆接。',
    ),
  },
  {
    ko: '-(으)면',
    sentence: '이 약을 먹{} 금방 나을 거예요.',
    answer: '먹으면',
    distractors: ['먹고', '먹어서', '먹지만'],
    trans: L(
      "If you take this medicine, you'll get better soon.",
      'Si tomas esta medicina, te recuperarás pronto.',
      'Si tu prends ce médicament, tu iras vite mieux.',
      'Se tomar este remédio, vai melhorar logo.',
      'ถ้ากินยานี้ เดี๋ยวก็จะหายเร็ว ๆ นี้',
      'Kalau minum obat ini, kamu akan cepat sembuh.',
      'Nếu uống thuốc này, bạn sẽ sớm khỏi.',
      'この薬を飲んだら、すぐに治りますよ。',
    ),
    why: L(
      'Hypothetical future outcome (거예요) of taking medicine → condition -(으)면; -아/어서 asserts a realized cause (clashes with the unrealized result), -고 just lists, -지만 contrasts.',
      'Resultado futuro hipotético (거예요) de tomar la medicina → condición -(으)면; -아/어서 afirma causa realizada (choca con el resultado no realizado), -고 enumera, -지만 contrasta.',
      'Résultat futur hypothétique (거예요) de la prise du médicament → condition -(으)면 ; -아/어서 affirme une cause réalisée (incompatible avec le résultat non réalisé), -고 énumère, -지만 contraste.',
      'Resultado futuro hipotético (거예요) de tomar o remédio → condição -(으)면; -아/어서 afirma causa realizada (choca com o resultado não realizado), -고 enumera, -지만 contrasta.',
      'ผลลัพธ์อนาคตเชิงสมมติ (거예요) จากการกินยา → เงื่อนไข -(으)면; -아/어서 ยืนยันเหตุที่เกิดจริง (ขัดกับผลที่ยังไม่เกิด), -고 แค่เรียง, -지만 ขัดแย้ง.',
      'Hasil masa depan andaian (거예요) dari minum obat → syarat -(으)면; -아/어서 menyatakan sebab nyata (bentrok dengan hasil yang belum terjadi), -고 mendaftar, -지만 kontras.',
      'Kết quả tương lai giả định (거예요) của việc uống thuốc → điều kiện -(으)면; -아/어서 khẳng định nguyên nhân đã xảy ra (mâu thuẫn với kết quả chưa xảy ra), -고 chỉ liệt kê, -지만 tương phản.',
      '薬を飲んだ場合の仮定的未来結果（거예요）→ 条件の-(으)면。-아/어서は実現した原因を断定し未実現の結果と矛盾、-고は羅列、-지만は逆接。',
    ),
  },
  {
    ko: '-ㄴ/는데',
    sentence: '시간이 좀 있{}, 같이 커피 마실까요?',
    answer: '있는데',
    distractors: ['있어서', '있지만', '있고'],
    trans: L(
      "I've got a bit of time, so shall we have coffee together?",
      'Tengo algo de tiempo, ¿tomamos un café juntos?',
      "J'ai un peu de temps, on prend un café ensemble ?",
      'Tenho um tempinho, vamos tomar um café juntos?',
      'พอมีเวลาอยู่ ดื่มกาแฟด้วยกันไหม',
      'Saya ada sedikit waktu, mau minum kopi bareng?',
      'Tôi có chút thời gian, mình uống cà phê cùng nhau nhé?',
      'ちょっと時間があるんだけど、一緒にコーヒー飲みませんか？',
    ),
    why: L(
      'A background set-up before a proposal (-ㄹ까요?) takes -ㄴ/는데; -아/어서 (있어서) is barred before a proposal, -고 just lists, and -지만 (but) clashes with the friendly invitation.',
      'El contexto previo a una propuesta (-ㄹ까요?) va con -ㄴ/는데; -아/어서 (있어서) está prohibido antes de una propuesta, -고 solo enumera y -지만 (pero) choca con la invitación amable.',
      "L'amorce avant une proposition (-ㄹ까요?) prend -ㄴ/는데 ; -아/어서 (있어서) est interdit avant une proposition, -고 ne fait qu'énumérer, et -지만 (mais) jure avec l'invitation conviviale.",
      'O contexto antes de uma proposta (-ㄹ까요?) usa -ㄴ/는데; -아/어서 (있어서) é vedado antes de proposta, -고 só enumera e -지만 (mas) destoa do convite amigável.',
      'การเกริ่นก่อนชวน (-ㄹ까요?) ใช้ -ㄴ/는데; -아/어서 (있어서) ห้ามมาก่อนการชวน, -고 แค่เรียงความ และ -지만 (แต่) ขัดกับคำชวนแบบเป็นกันเอง',
      'Latar sebelum ajakan (-ㄹ까요?) memakai -ㄴ/는데; -아/어서 (있어서) terlarang sebelum ajakan, -고 hanya merangkai, dan -지만 (tapi) bentrok dengan ajakan ramah.',
      'Lời dẫn trước câu rủ (-ㄹ까요?) dùng -ㄴ/는데; -아/어서 (있어서) bị cấm trước lời rủ, -고 chỉ liệt kê, còn -지만 (nhưng) chỏi với lời mời thân thiện.',
      '提案(-ㄹ까요?)の前置きには -ㄴ/는데 を使う。-아/어서(있어서)は提案の前に立てられず、-고 は並列にすぎず、-지만(でも)は親しい誘いと合わない。',
    ),
  },
  {
    ko: '-ㄴ/는데',
    sentence: '이 식당 음식이 맛있{}, 한번 가 보세요.',
    answer: '맛있는데',
    distractors: ['맛있어서', '맛있으면', '맛있지만'],
    trans: L(
      "This restaurant's food is delicious, so do give it a try.",
      'La comida de este restaurante está rica, así que pruébalo.',
      'La cuisine de ce restaurant est délicieuse, alors essayez-le.',
      'A comida deste restaurante é gostosa, então experimente.',
      'อาหารร้านนี้อร่อยนะ ลองไปกินดูสิ',
      'Makanan restoran ini enak, coba mampir, ya.',
      'Đồ ăn quán này ngon đấy, bạn thử ghé xem.',
      'この食堂、料理がおいしいんですけど、一度行ってみてください。',
    ),
    why: L(
      "A background recommendation before a command (-(으)세요) takes -ㄴ/는데; -아/어서 (맛있어서) is barred before an imperative, -으면 (if) gives the wrong 'if it's tasty' reading, and -지만 (but) contradicts the recommendation.",
      "La recomendación de fondo antes de un mandato (-(으)세요) va con -ㄴ/는데; -아/어서 (맛있어서) está prohibido antes de un imperativo, -으면 (si) da el sentido erróneo 'si está rica', y -지만 (pero) contradice la recomendación.",
      "La recommandation de fond avant un ordre (-(으)세요) prend -ㄴ/는데 ; -아/어서 (맛있어서) est interdit avant un impératif, -으면 (si) donne le sens erroné « si c'est bon », et -지만 (mais) contredit la recommandation.",
      "A recomendação de fundo antes de uma ordem (-(으)세요) usa -ㄴ/는데; -아/어서 (맛있어서) é vedado antes de imperativo, -으면 (se) dá o sentido errado 'se for gostoso', e -지만 (mas) contradiz a recomendação.",
      "การเกริ่นแนะนำก่อนคำสั่ง (-(으)세요) ใช้ -ㄴ/는데; -아/어서 (맛있어서) ห้ามมาก่อนคำสั่ง, -으면 (ถ้า) ให้ความหมายผิดว่า 'ถ้าอร่อย' และ -지만 (แต่) ขัดกับการแนะนำ",
      "Rekomendasi latar sebelum perintah (-(으)세요) memakai -ㄴ/는데; -아/어서 (맛있어서) terlarang sebelum perintah, -으면 (kalau) memberi makna salah 'kalau enak', dan -지만 (tapi) bertentangan dengan rekomendasi.",
      "Lời giới thiệu nền trước câu sai bảo (-(으)세요) dùng -ㄴ/는데; -아/어서 (맛있어서) bị cấm trước mệnh lệnh, -으면 (nếu) cho nghĩa sai 'nếu ngon', và -지만 (nhưng) mâu thuẫn với lời khuyến nghị.",
      '命令(-(으)세요)の前の前置き推薦には -ㄴ/는데 を使う。-아/어서(맛있어서)は命令の前に立てられず、-으면(なら)は「おいしければ」と誤った意味になり、-지만(でも)は推薦と矛盾する。',
    ),
  },
  {
    ko: '-ㄴ/는데',
    sentence: '어제 백화점에 갔{}, 사람이 정말 많았어요.',
    answer: '갔는데',
    distractors: ['가지만', '가면', '가고'],
    trans: L(
      'I went to the department store yesterday, and there were really a lot of people.',
      'Ayer fui a los grandes almacenes y había muchísima gente.',
      'Hier, je suis allé au grand magasin, et il y avait vraiment beaucoup de monde.',
      'Ontem fui ao shopping e tinha muita gente mesmo.',
      'เมื่อวานไปห้าง คนเยอะมากเลย',
      'Kemarin saya ke mal, dan orangnya benar-benar ramai.',
      'Hôm qua tôi đã đến trung tâm thương mại, mà người đông thật.',
      '昨日デパートに行ったんですが、人が本当に多かったです。',
    ),
    why: L(
      "The past cue 어제 + past 2nd clause needs the past background form 갔는데; the distractors are present and ignore 어제, and -지만/-면/-고 can't carry the 'I went, and (found)' set-up here.",
      "La marca de pasado 어제 + 2ª cláusula en pasado exige la forma de fondo en pasado 갔는데; los distractores están en presente e ignoran 어제, y -지만/-면/-고 no dan el matiz 'fui y (resultó que)'.",
      "Le marqueur de passé 어제 + 2ᵉ proposition au passé exige la forme de fond au passé 갔는데 ; les distracteurs sont au présent et ignorent 어제, et -지만/-면/-고 ne rendent pas l'amorce « j'y suis allé, et (il s'est avéré que) ».",
      "A marca de passado 어제 + 2ª oração no passado exige a forma de fundo no passado 갔는데; os distratores estão no presente e ignoram 어제, e -지만/-면/-고 não trazem o sentido 'fui e (vi que)'.",
      "คำบอกอดีต 어제 + ประโยคหลังเป็นอดีต ต้องใช้รูปเกริ่นอดีต 갔는데; ตัวลวงเป็นปัจจุบันและไม่สอดคล้องกับ 어제 ทั้ง -지만/-면/-고 ก็ไม่ให้ความหมาย 'ไปแล้วพบว่า'",
      "Penanda lampau 어제 + klausa kedua lampau menuntut bentuk latar lampau 갔는데; pengecoh berbentuk kini dan mengabaikan 어제, lalu -지만/-면/-고 tak memberi nuansa 'saya pergi, dan (ternyata)'.",
      "Dấu hiệu quá khứ 어제 + mệnh đề hai ở quá khứ đòi dạng nền quá khứ 갔는데; các phương án nhiễu ở hiện tại, bỏ qua 어제, và -지만/-면/-고 không diễn được ý 'tôi đã đến, và (thấy rằng)'.",
      '過去の手がかり 어제 と過去の後続節には過去の前置き形 갔는데 が必要。誤答は現在形で 어제 と合わず、-지만/-면/-고 では「行ったら〜だった」という前置きにならない。',
    ),
  },
  {
    ko: '-고 싶다',
    sentence: '주말에 바다를 보러 부산에 가{} 싶어요.',
    answer: '가고',
    distractors: ['가서', '가지만', '가면'],
    trans: L(
      'On the weekend I want to go to Busan to see the sea.',
      'El fin de semana quiero ir a Busan a ver el mar.',
      'Le week-end, je veux aller à Busan pour voir la mer.',
      'No fim de semana quero ir a Busan para ver o mar.',
      'สุดสัปดาห์อยากไปปูซานเพื่อดูทะเล',
      'Akhir pekan saya ingin pergi ke Busan untuk melihat laut.',
      'Cuối tuần tôi muốn đi Busan để ngắm biển.',
      '週末は海を見に釜山に行きたいです。',
    ),
    why: L(
      "싶다 only attaches to -고 (가고 싶다 = 'want to go'); 가서/가지만/가면 + 싶다 are ungrammatical strings since those connectors can't feed 싶다.",
      "싶다 solo se une a -고 (가고 싶다 = 'querer ir'); 가서/가지만/가면 + 싶다 son cadenas agramaticales porque esos conectores no alimentan a 싶다.",
      "싶다 ne se rattache qu'à -고 (가고 싶다 = « vouloir aller ») ; 가서/가지만/가면 + 싶다 sont des suites agrammaticales, ces connecteurs ne pouvant nourrir 싶다.",
      "싶다 só se liga a -고 (가고 싶다 = 'querer ir'); 가서/가지만/가면 + 싶다 são cadeias agramaticais, pois esses conectores não alimentam 싶다.",
      "싶다 ต่อได้กับ -고 เท่านั้น (가고 싶다 = 'อยากไป'); 가서/가지만/가면 + 싶다 เป็นรูปผิดไวยากรณ์ เพราะคำเชื่อมเหล่านี้ต่อ 싶다 ไม่ได้",
      "싶다 hanya menempel pada -고 (가고 싶다 = 'ingin pergi'); 가서/가지만/가면 + 싶다 adalah rangkaian tak gramatikal karena penghubung itu tak bisa menyuapi 싶다.",
      "싶다 chỉ gắn với -고 (가고 싶다 = 'muốn đi'); 가서/가지만/가면 + 싶다 là chuỗi sai ngữ pháp vì các liên từ đó không thể đứng trước 싶다.",
      '싶다 は -고 にしか付かない(가고 싶다=「行きたい」)。가서/가지만/가면 + 싶다 はこれらの接続が 싶다 を取れず非文になる。',
    ),
  },
  {
    ko: '-고 싶다',
    sentence: '오늘은 집에서 푹 쉬{} 싶어요.',
    answer: '쉬고',
    distractors: ['쉬어서', '쉬면', '쉬지만'],
    trans: L(
      'Today I want to rest well at home.',
      'Hoy quiero descansar bien en casa.',
      "Aujourd'hui, je veux bien me reposer à la maison.",
      'Hoje quero descansar bem em casa.',
      'วันนี้อยากพักผ่อนเต็มที่ที่บ้าน',
      'Hari ini saya ingin beristirahat dengan nyaman di rumah.',
      'Hôm nay tôi muốn nghỉ ngơi thật thoải mái ở nhà.',
      '今日は家でゆっくり休みたいです。',
    ),
    why: L(
      "Desire 'want to rest' needs -고 before 싶다 (쉬고 싶다); 쉬어서/쉬면/쉬지만 + 싶다 are ungrammatical because only -고 chains into 싶다.",
      "El deseo 'querer descansar' necesita -고 antes de 싶다 (쉬고 싶다); 쉬어서/쉬면/쉬지만 + 싶다 son agramaticales porque solo -고 enlaza con 싶다.",
      "Le désir « vouloir se reposer » exige -고 devant 싶다 (쉬고 싶다) ; 쉬어서/쉬면/쉬지만 + 싶다 sont agrammaticaux, seul -고 s'enchaînant à 싶다.",
      "O desejo 'querer descansar' precisa de -고 antes de 싶다 (쉬고 싶다); 쉬어서/쉬면/쉬지만 + 싶다 são agramaticais, pois só -고 encadeia em 싶다.",
      "ความอยาก 'อยากพัก' ต้องมี -고 ก่อน 싶다 (쉬고 싶다); 쉬어서/쉬면/쉬지만 + 싶다 ผิดไวยากรณ์ เพราะมีแต่ -고 ที่ต่อเข้า 싶다 ได้",
      "Keinginan 'ingin istirahat' butuh -고 sebelum 싶다 (쉬고 싶다); 쉬어서/쉬면/쉬지만 + 싶다 tak gramatikal karena hanya -고 yang menyambung ke 싶다.",
      "Mong muốn 'muốn nghỉ' cần -고 trước 싶다 (쉬고 싶다); 쉬어서/쉬면/쉬지만 + 싶다 sai ngữ pháp vì chỉ -고 nối được vào 싶다.",
      '「休みたい」という願望は 싶다 の前に -고 が必要(쉬고 싶다)。쉬어서/쉬면/쉬지만 + 싶다 は -고 以外が 싶다 に繋がらず非文。',
    ),
  },
  {
    ko: '-고 싶다',
    sentence: '배가 너무 고파서 빨리 뭐 좀 먹{} 싶어요.',
    answer: '먹고',
    distractors: ['먹어서', '먹지만', '먹으면'],
    trans: L(
      "I'm so hungry that I want to eat something quickly.",
      'Tengo tanta hambre que quiero comer algo rápido.',
      "J'ai tellement faim que je veux manger quelque chose vite.",
      'Estou com tanta fome que quero comer algo rápido.',
      'หิวมากเลยอยากกินอะไรสักอย่างเร็ว ๆ',
      'Saya sangat lapar, jadi ingin segera makan sesuatu.',
      'Tôi đói quá nên muốn ăn gì đó nhanh nhanh.',
      'お腹がすごく空いて、早く何か食べたいです。',
    ),
    why: L(
      "'Want to eat' is 먹고 싶다 — 싶다 selects only -고; 먹어서/먹지만/먹으면 + 싶다 are ungrammatical since those connectors can't precede 싶다.",
      "'Querer comer' es 먹고 싶다 — 싶다 solo admite -고; 먹어서/먹지만/먹으면 + 싶다 son agramaticales porque esos conectores no preceden a 싶다.",
      '« Vouloir manger » se dit 먹고 싶다 — 싶다 ne prend que -고 ; 먹어서/먹지만/먹으면 + 싶다 sont agrammaticaux, ces connecteurs ne précédant pas 싶다.',
      "'Querer comer' é 먹고 싶다 — 싶다 só aceita -고; 먹어서/먹지만/먹으면 + 싶다 são agramaticais, pois esses conectores não precedem 싶다.",
      "'อยากกิน' คือ 먹고 싶다 — 싶다 รับได้แค่ -고; 먹어서/먹지만/먹으면 + 싶다 ผิดไวยากรณ์ เพราะคำเชื่อมเหล่านี้มาก่อน 싶다 ไม่ได้",
      "'Ingin makan' adalah 먹고 싶다 — 싶다 hanya menerima -고; 먹어서/먹지만/먹으면 + 싶다 tak gramatikal karena penghubung itu tak bisa mendahului 싶다.",
      "'Muốn ăn' là 먹고 싶다 — 싶다 chỉ nhận -고; 먹어서/먹지만/먹으면 + 싶다 sai ngữ pháp vì các liên từ đó không đứng trước 싶다.",
      '「食べたい」は 먹고 싶다。싶다 は -고 だけを取る。먹어서/먹지만/먹으면 + 싶다 はこれらの接続が 싶다 の前に立てず非文。',
    ),
  },
  {
    ko: '-고 있다',
    sentence: '동생은 지금 방에서 게임을 하{} 있어요.',
    answer: '하고',
    distractors: ['했고', '할', '하면'],
    trans: L(
      'My younger sibling is playing a game in the room right now.',
      'Mi hermano menor está jugando un videojuego en su cuarto ahora mismo.',
      'Mon petit frère est en train de jouer à un jeu dans sa chambre en ce moment.',
      'Meu irmão mais novo está jogando videogame no quarto agora.',
      'ตอนนี้น้องกำลังเล่นเกมอยู่ในห้อง',
      'Adik saya sekarang sedang main game di kamar.',
      'Bây giờ em tôi đang chơi game trong phòng.',
      '弟は今、部屋でゲームをしています。',
    ),
    why: L(
      "지금 (right now) marks progressive, so the only fit is 하고 있다 ('is playing'); 했고/할/하면 + 있어요 are ungrammatical and clash with the 'now in progress' cue.",
      "지금 (ahora mismo) marca progresivo, así que solo encaja 하고 있다 ('está jugando'); 했고/할/하면 + 있어요 son agramaticales y chocan con la pista de 'en curso ahora'.",
      "지금 (en ce moment) marque le progressif, donc seul 하고 있다 (« est en train de jouer ») convient ; 했고/할/하면 + 있어요 sont agrammaticaux et jurent avec l'indice « en cours maintenant ».",
      "지금 (agora mesmo) marca progressivo, então só cabe 하고 있다 ('está jogando'); 했고/할/하면 + 있어요 são agramaticais e destoam da pista 'em andamento agora'.",
      "지금 (ตอนนี้) บ่งบอกรูปกำลังกระทำ จึงเข้าได้แค่ 하고 있다 ('กำลังเล่น'); 했고/할/하면 + 있어요 ผิดไวยากรณ์และขัดกับคำบอก 'กำลังดำเนินอยู่ตอนนี้'",
      "지금 (sekarang) menandai progresif, jadi yang cocok hanya 하고 있다 ('sedang main'); 했고/할/하면 + 있어요 tak gramatikal dan bentrok dengan petunjuk 'sedang berlangsung sekarang'.",
      "지금 (bây giờ) đánh dấu thì tiếp diễn, nên chỉ 하고 있다 ('đang chơi') hợp; 했고/할/하면 + 있어요 sai ngữ pháp và chỏi với dấu hiệu 'đang diễn ra lúc này'.",
      '지금(今)は進行を示すので、合うのは 하고 있다(「している」)だけ。했고/할/하면 + 있어요 は非文で、「今進行中」の手がかりと矛盾する。',
    ),
  },
  {
    ko: '-고 있다',
    sentence: '여보세요? 저는 지금 버스를 기다리{} 있어요.',
    answer: '기다리고',
    distractors: ['기다렸고', '기다릴', '기다려서'],
    trans: L(
      "Hello? I'm waiting for the bus right now.",
      '¿Aló? Ahora mismo estoy esperando el autobús.',
      "Allô ? Je suis en train d'attendre le bus en ce moment.",
      'Alô? Agora estou esperando o ônibus.',
      'ฮัลโหล ตอนนี้ฉันกำลังรอรถบัสอยู่',
      'Halo? Sekarang saya sedang menunggu bus.',
      'Alô? Bây giờ tôi đang đợi xe buýt.',
      'もしもし？私は今、バスを待っています。',
    ),
    why: L(
      "지금 forces the progressive 기다리고 있다 ('am waiting'); 기다렸고/기다릴/기다려서 + 있어요 are ungrammatical and contradict the ongoing-now cue.",
      "지금 obliga al progresivo 기다리고 있다 ('estoy esperando'); 기다렸고/기다릴/기다려서 + 있어요 son agramaticales y contradicen la pista de 'ahora en curso'.",
      "지금 impose le progressif 기다리고 있다 (« j'attends ») ; 기다렸고/기다릴/기다려서 + 있어요 sont agrammaticaux et contredisent l'indice « en cours maintenant ».",
      "지금 obriga ao progressivo 기다리고 있다 ('estou esperando'); 기다렸고/기다릴/기다려서 + 있어요 são agramaticais e contradizem a pista de 'agora em andamento'.",
      "지금 บังคับให้ใช้รูปกำลังกระทำ 기다리고 있다 ('กำลังรอ'); 기다렸고/기다릴/기다려서 + 있어요 ผิดไวยากรณ์และขัดกับคำบอก 'กำลังดำเนินอยู่ตอนนี้'",
      "지금 mengharuskan progresif 기다리고 있다 ('sedang menunggu'); 기다렸고/기다릴/기다려서 + 있어요 tak gramatikal dan bertentangan dengan petunjuk 'sedang berlangsung sekarang'.",
      "지금 buộc dùng thì tiếp diễn 기다리고 있다 ('đang đợi'); 기다렸고/기다릴/기다려서 + 있어요 sai ngữ pháp và mâu thuẫn với dấu hiệu 'đang diễn ra lúc này'.",
      '지금 が進行形 기다리고 있다(「待っている」)を要求する。기다렸고/기다릴/기다려서 + 있어요 は非文で、「今進行中」の手がかりと矛盾する。',
    ),
  },
  {
    ko: '-고 있다',
    sentence: '엄마가 지금 부엌에서 저녁을 만들{} 있어요.',
    answer: '만들고',
    distractors: ['만들었고', '만들', '만들면'],
    trans: L(
      'Mom is making dinner in the kitchen right now.',
      'Mamá está preparando la cena en la cocina ahora mismo.',
      'Maman est en train de préparer le dîner dans la cuisine en ce moment.',
      'A mamãe está fazendo o jantar na cozinha agora.',
      'ตอนนี้แม่กำลังทำอาหารเย็นอยู่ในครัว',
      'Ibu sekarang sedang memasak makan malam di dapur.',
      'Bây giờ mẹ đang nấu bữa tối trong bếp.',
      'お母さんが今、台所で夕飯を作っています。',
    ),
    why: L(
      "The 지금 cue makes the action ongoing, so only 만들고 있다 ('is making') fits; 만들었고/만들/만들면 + 있어요 are ungrammatical and don't express present progress.",
      "La pista 지금 hace la acción en curso, así que solo encaja 만들고 있다 ('está preparando'); 만들었고/만들/만들면 + 있어요 son agramaticales y no expresan progreso actual.",
      "L'indice 지금 rend l'action en cours, donc seul 만들고 있다 (« est en train de préparer ») convient ; 만들었고/만들/만들면 + 있어요 sont agrammaticaux et n'expriment pas le progrès actuel.",
      "A pista 지금 torna a ação em andamento, então só cabe 만들고 있다 ('está fazendo'); 만들었고/만들/만들면 + 있어요 são agramaticais e não expressam progresso atual.",
      "คำบอก 지금 ทำให้การกระทำกำลังดำเนินอยู่ จึงเข้าได้แค่ 만들고 있다 ('กำลังทำ'); 만들었고/만들/만들면 + 있어요 ผิดไวยากรณ์และไม่สื่อความกำลังดำเนินในปัจจุบัน",
      "Petunjuk 지금 membuat aksi berlangsung, jadi hanya 만들고 있다 ('sedang membuat') yang cocok; 만들었고/만들/만들면 + 있어요 tak gramatikal dan tak menyatakan progres kini.",
      "Dấu hiệu 지금 khiến hành động đang diễn ra, nên chỉ 만들고 있다 ('đang nấu') hợp; 만들었고/만들/만들면 + 있어요 sai ngữ pháp và không diễn được tiến trình hiện tại.",
      '지금 の手がかりで動作は進行中になるため、合うのは 만들고 있다(「作っている」)だけ。만들었고/만들/만들면 + 있어요 は非文で現在の進行を表さない。',
    ),
  },
  {
    ko: '안 + V / -지 않다',
    sentence: '저는 매운 음식을 싫어해서 김치를 {}.',
    answer: '안 먹어요',
    distractors: ['못 먹어요', '먹지 못해요', '먹지 못했어요'],
    trans: L(
      "I dislike spicy food, so I don't eat kimchi.",
      'No me gusta la comida picante, así que no como kimchi.',
      "Je n'aime pas la nourriture épicée, donc je ne mange pas de kimchi.",
      'Não gosto de comida apimentada, então não como kimchi.',
      'ฉันไม่ชอบอาหารเผ็ด เลยไม่กินกิมจิ',
      'Saya tidak suka makanan pedas, jadi saya tidak makan kimchi.',
      'Tôi không thích đồ ăn cay nên tôi không ăn kim chi.',
      '私は辛い食べ物が嫌いなので、キムチを食べません。',
    ),
    why: L(
      'Cue 싫어해서 marks a personal CHOICE not to eat, so 안 (안 먹어요) fits; the 못/-지 못하다 options (먹지 못해요) would falsely mean inability.',
      'La pista 싫어해서 indica una ELECCIÓN de no comer, así que va 안 (안 먹어요); las opciones 못/-지 못하다 (먹지 못해요) implicarían incapacidad.',
      "L'indice 싫어해서 marque un CHOIX de ne pas manger, donc 안 (안 먹어요) ; les options 못/-지 못하다 (먹지 못해요) signifieraient à tort une incapacité.",
      'A pista 싫어해서 marca uma ESCOLHA de não comer, então cabe 안 (안 먹어요); as opções 못/-지 못하다 (먹지 못해요) significariam incapacidade.',
      'คำชี้นำ 싫어해서 บอกการเลือกที่จะไม่กิน จึงใช้ 안 (안 먹어요); ตัวเลือก 못/-지 못하다 (먹지 못해요) จะสื่อผิดว่าทำไม่ได้',
      'Petunjuk 싫어해서 menandai PILIHAN untuk tidak makan, jadi 안 (안 먹어요) cocok; opsi 못/-지 못하다 (먹지 못해요) salah karena berarti ketidakmampuan.',
      'Dấu hiệu 싫어해서 cho thấy LỰA CHỌN không ăn nên dùng 안 (안 먹어요); các phương án 못/-지 못하다 (먹지 못해요) sẽ sai vì ngụ ý bất khả.',
      '手がかり 싫어해서 は「意志的選択」を示すので 안（안 먹어요）が適切。못/-지 못하다（먹지 못해요）だと不可能の意味になり不自然。',
    ),
  },
  {
    ko: '안 + V / -지 않다',
    sentence: '내일은 쉬는 날이라서 학교에 {}.',
    answer: '가지 않아요',
    distractors: ['가지 못해요', '못 가요', '가지 못했어요'],
    trans: L(
      "Tomorrow is a day off, so I'm not going to school.",
      'Mañana es día libre, así que no voy a la escuela.',
      "Demain est un jour de congé, donc je ne vais pas à l'école.",
      'Amanhã é folga, então não vou à escola.',
      'พรุ่งนี้เป็นวันหยุด เลยไม่ไปโรงเรียน',
      'Besok hari libur, jadi saya tidak pergi ke sekolah.',
      'Ngày mai là ngày nghỉ nên tôi không đến trường.',
      '明日は休みの日なので、学校に行きません。',
    ),
    why: L(
      'Cue 쉬는 날이라서 means you simply CHOOSE not to go, so -지 않다 (가지 않아요) fits; the 못/-지 못하다 options (가지 못해요) would wrongly mean you are prevented from going.',
      'La pista 쉬는 날이라서 significa que simplemente ELIGES no ir, así que va -지 않다 (가지 않아요); las opciones 못/-지 못하다 (가지 못해요) implicarían que algo te lo impide.',
      "L'indice 쉬는 날이라서 signifie que tu CHOISIS de ne pas y aller, donc -지 않다 (가지 않아요) ; les options 못/-지 못하다 (가지 못해요) signifieraient à tort que tu en es empêché.",
      'A pista 쉬는 날이라서 significa que você simplesmente ESCOLHE não ir, então cabe -지 않다 (가지 않아요); as opções 못/-지 못하다 (가지 못해요) implicariam estar impedido.',
      'คำชี้นำ 쉬는 날이라서 หมายความว่าคุณเลือกที่จะไม่ไป จึงใช้ -지 않다 (가지 않아요); ตัวเลือก 못/-지 못하다 (가지 못해요) จะสื่อผิดว่าถูกขัดขวาง',
      'Petunjuk 쉬는 날이라서 berarti kamu memang MEMILIH tidak pergi, jadi -지 않다 (가지 않아요) cocok; opsi 못/-지 못하다 (가지 못해요) salah karena berarti terhalang.',
      'Dấu hiệu 쉬는 날이라서 nghĩa là bạn tự CHỌN không đi nên dùng -지 않다 (가지 않아요); các phương án 못/-지 못하다 (가지 못해요) sẽ sai vì ngụ ý bị cản trở.',
      '手がかり 쉬는 날이라서 は単に「行かない」選択を示すので -지 않다（가지 않아요）が適切。못/-지 못하다（가지 못해요）だと行けない（妨げられる）意味になり不自然。',
    ),
  },
  {
    ko: '못 + V / -지 못하다',
    sentence: '다리를 다쳐서 오늘은 빨리 {}.',
    answer: '못 뛰어요',
    distractors: ['안 뛰어요', '뛰지 않아요', '뛰지 않았어요'],
    trans: L(
      "I hurt my leg, so today I can't run fast.",
      'Me lastimé la pierna, así que hoy no puedo correr rápido.',
      "Je me suis blessé à la jambe, donc aujourd'hui je ne peux pas courir vite.",
      'Machuquei a perna, então hoje não consigo correr rápido.',
      'ฉันบาดเจ็บที่ขา วันนี้เลยวิ่งเร็วไม่ได้',
      'Kaki saya cedera, jadi hari ini saya tidak bisa berlari cepat.',
      'Tôi bị thương ở chân nên hôm nay không thể chạy nhanh.',
      '足を怪我したので、今日は速く走れません。',
    ),
    why: L(
      'Cue 다리를 다쳐서 (injury) removes ABILITY, so 못 (못 뛰어요) fits; the 안/-지 않다 options (뛰지 않아요) would wrongly imply a free choice not to run.',
      'La pista 다리를 다쳐서 (lesión) quita la CAPACIDAD, así que va 못 (못 뛰어요); las opciones 안/-지 않다 (뛰지 않아요) implicarían falsamente una elección.',
      "L'indice 다리를 다쳐서 (blessure) ôte la CAPACITÉ, donc 못 (못 뛰어요) convient ; les options 안/-지 않다 (뛰지 않아요) impliqueraient à tort un choix.",
      'A pista 다리를 다쳐서 (lesão) tira a CAPACIDADE, então cabe 못 (못 뛰어요); as opções 안/-지 않다 (뛰지 않아요) sugeririam erradamente uma escolha.',
      'คำชี้นำ 다리를 다쳐서 (บาดเจ็บ) ทำให้ขาดความสามารถ จึงใช้ 못 (못 뛰어요); ตัวเลือก 안/-지 않다 (뛰지 않아요) จะสื่อผิดว่าเป็นการเลือก',
      'Petunjuk 다리를 다쳐서 (cedera) menghilangkan KEMAMPUAN, jadi 못 (못 뛰어요) cocok; opsi 안/-지 않다 (뛰지 않아요) salah karena menyiratkan pilihan.',
      'Dấu hiệu 다리를 다쳐서 (chấn thương) làm mất KHẢ NĂNG nên dùng 못 (못 뛰어요); các phương án 안/-지 않다 (뛰지 않아요) sẽ sai vì ngụ ý lựa chọn.',
      '手がかり 다리를 다쳐서（怪我）で「能力」が失われるため 못（못 뛰어요）が適切。안/-지 않다（뛰지 않아요）だと意志的選択になり不自然。',
    ),
  },
  {
    ko: '못 + V / -지 못하다',
    sentence: '일이 너무 많아서 이번 주말에도 {}.',
    answer: '쉬지 못해요',
    distractors: ['쉬지 않아요', '안 쉬어요', '쉬지 않았어요'],
    trans: L(
      "I have too much work, so I can't rest this weekend either.",
      'Tengo demasiado trabajo, así que tampoco puedo descansar este fin de semana.',
      "J'ai trop de travail, donc je ne peux pas non plus me reposer ce week-end.",
      'Tenho trabalho demais, então também não consigo descansar neste fim de semana.',
      'งานเยอะเกินไป สุดสัปดาห์นี้ก็เลยพักไม่ได้',
      'Pekerjaan saya terlalu banyak, jadi akhir pekan ini pun saya tidak bisa istirahat.',
      'Tôi có quá nhiều việc nên cuối tuần này cũng không thể nghỉ.',
      '仕事が多すぎて、今週末も休めません。',
    ),
    why: L(
      'Cue 일이 너무 많아서 is an external constraint blocking rest, so -지 못하다 (쉬지 못해요) fits; the 안/-지 않다 options (쉬지 않아요) would wrongly mean choosing not to rest.',
      'La pista 일이 너무 많아서 es una restricción externa que impide descansar, así que va -지 못하다 (쉬지 못해요); las opciones 안/-지 않다 (쉬지 않아요) implicarían elegir no descansar.',
      "L'indice 일이 너무 많아서 est une contrainte extérieure empêchant le repos, donc -지 못하다 (쉬지 못해요) ; les options 안/-지 않다 (쉬지 않아요) impliqueraient un choix.",
      'A pista 일이 너무 많아서 é uma restrição externa que impede o descanso, então cabe -지 못하다 (쉬지 못해요); as opções 안/-지 않다 (쉬지 않아요) implicariam escolha.',
      'คำชี้นำ 일이 너무 많아서 เป็นข้อจำกัดภายนอกที่ทำให้พักไม่ได้ จึงใช้ -지 못하다 (쉬지 못해요); ตัวเลือก 안/-지 않다 (쉬지 않아요) จะสื่อผิดว่าเลือกไม่พัก',
      'Petunjuk 일이 너무 많아서 adalah kendala eksternal yang menghalangi istirahat, jadi -지 못하다 (쉬지 못해요) cocok; opsi 안/-지 않다 (쉬지 않아요) salah karena berarti memilih tidak istirahat.',
      'Dấu hiệu 일이 너무 많아서 là trở ngại bên ngoài cản việc nghỉ nên dùng -지 못하다 (쉬지 못해요); các phương án 안/-지 않다 (쉬지 않아요) sẽ sai vì ngụ ý chọn không nghỉ.',
      '手がかり 일이 너무 많아서 は休めない外的制約なので -지 못하다（쉬지 못해요）が適切。안/-지 않다（쉬지 않아요）だと休まない選択の意味になり不自然。',
    ),
  },
  {
    ko: '-고 있다',
    sentence: '지금 동생이 방에서 만화책을 {}.',
    answer: '읽고 있어요',
    distractors: ['읽어 있어요', '읽으려고 해요', '읽어야 해요'],
    trans: L(
      'Right now my younger sibling is reading comics in the room.',
      'Ahora mismo mi hermano menor está leyendo cómics en la habitación.',
      'En ce moment, mon petit frère lit des bandes dessinées dans la chambre.',
      'Agora meu irmão mais novo está lendo quadrinhos no quarto.',
      'ตอนนี้น้องกำลังอ่านหนังสือการ์ตูนอยู่ในห้อง',
      'Sekarang adik saya sedang membaca komik di kamar.',
      'Bây giờ em tôi đang đọc truyện tranh trong phòng.',
      '今、弟が部屋でマンガを読んでいます。',
    ),
    why: L(
      '지금 + the object 만화책을 mark an action in progress, so transitive 읽다 takes -고 있다 (읽고 있어요); -아/어 있다 (읽어 있어요) attaches only to intransitives (ungrammatical), -(으)려고 하다 is intention, -아/어야 하다 obligation.',
      '지금 + el objeto 만화책을 marcan acción en curso, así que el transitivo 읽다 usa -고 있다 (읽고 있어요); -아/어 있다 (읽어 있어요) solo va con intransitivos (agramatical), -(으)려고 하다 intención, -아/어야 하다 obligación.',
      "지금 + l'objet 만화책을 marquent une action en cours, donc le transitif 읽다 prend -고 있다 (읽고 있어요) ; -아/어 있다 (읽어 있어요) ne va qu'aux intransitifs (agrammatical), -(으)려고 하다 intention, -아/어야 하다 obligation.",
      '지금 + o objeto 만화책을 marcam ação em progresso, então o transitivo 읽다 usa -고 있다 (읽고 있어요); -아/어 있다 (읽어 있어요) só liga a intransitivos (agramatical), -(으)려고 하다 intenção, -아/어야 하다 obrigação.',
      '지금 + กรรม 만화책을 บ่งการกำลังดำเนิน กริยาสกรรม 읽다 จึงใช้ -고 있다 (읽고 있어요) ส่วน -아/어 있다 (읽어 있어요) ต่อกับอกรรมเท่านั้น (ผิดไวยากรณ์), -(으)려고 하다 ความตั้งใจ, -아/어야 하다 ความจำเป็น',
      '지금 + objek 만화책을 menandai aksi berlangsung, jadi verba transitif 읽다 pakai -고 있다 (읽고 있어요); -아/어 있다 (읽어 있어요) hanya untuk intransitif (tak gramatikal), -(으)려고 하다 niat, -아/어야 하다 keharusan.',
      '지금 + tân ngữ 만화책을 cho thấy hành động đang diễn ra, nên ngoại động từ 읽다 dùng -고 있다 (읽고 있어요); -아/어 있다 (읽어 있어요) chỉ gắn nội động từ (sai ngữ pháp), -(으)려고 하다 ý định, -아/어야 하다 sự bắt buộc.',
      '지금 と目的語 만화책을 が進行中の動作を示すので他動詞 읽다 は -고 있다(읽고 있어요)。-아/어 있다(읽어 있어요)は自動詞専用で非文、-(으)려고 하다 は意図、-아/어야 하다 は義務。',
    ),
  },
]
