// app/seed/cloze/n2-extra.ts
import type { ClozeItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-2 grammar-pattern cloze items — supplementary batch.
 * Covers grammars NOT exercised by n2.ts (ability, time-overlap, conjecture,
 * suggestion, auxiliaries, comparison, indirect question, reactions, etc.).
 * ko matches grammars-n2.ts verbatim. Drafted + Korean-lens adversarially
 * verified (single-correct-answer crux). Korean wife native review = final gate.
 */

export const N2_CLOZE_EXTRA: ClozeItem[] = [
  {
    ko: '-(으)ㄹ 수 있다/없다',
    sentence: '저는 수영을 못 배워서 바다에서 {}.',
    answer: '수영할 수 없어요',
    distractors: ['수영하면 안 돼요', '수영할까요', '수영하고 싶어요'],
    trans: L(
      "I never learned to swim, so I can't swim in the sea.",
      'Nunca aprendí a nadar, así que no puedo nadar en el mar.',
      "Je n'ai jamais appris à nager, donc je ne peux pas nager dans la mer.",
      'Nunca aprendi a nadar, então não consigo nadar no mar.',
      'ฉันว่ายน้ำไม่เป็น เลยว่ายน้ำในทะเลไม่ได้',
      'Saya tidak pernah belajar berenang, jadi tidak bisa berenang di laut.',
      'Tôi chưa học bơi nên không thể bơi ở biển.',
      '私は泳ぎを習わなかったので、海で泳げません。',
    ),
    why: L(
      'The cause "못 배워서" (never learned) makes this about lack of ABILITY, so -(으)ㄹ 수 없다 (수영할 수 없어요) fits; -(으)면 안 되다 is "not allowed" (a rule, not inability), -(으)ㄹ까요 is "shall we?", -고 싶다 is "want to".',
      'La causa "못 배워서" (no lo aprendió) trata de falta de CAPACIDAD, así que va -(으)ㄹ 수 없다 (수영할 수 없어요); -(으)면 안 되다 es "no está permitido" (una regla, no incapacidad), -(으)ㄹ까요 "¿hacemos?", -고 싶다 "querer".',
      "La cause « 못 배워서 » (jamais appris) renvoie à un manque de CAPACITÉ, donc -(으)ㄹ 수 없다 (수영할 수 없어요) ; -(으)면 안 되다 = « interdit » (une règle, pas l'incapacité), -(으)ㄹ까요 « on…? », -고 싶다 « vouloir ».",
      'A causa "못 배워서" (nunca aprendeu) trata de falta de CAPACIDADE, então cabe -(으)ㄹ 수 없다 (수영할 수 없어요); -(으)면 안 되다 é "não é permitido" (regra, não incapacidade), -(으)ㄹ까요 "vamos?", -고 싶다 "querer".',
      'สาเหตุ "못 배워서" (ไม่เคยเรียน) เกี่ยวกับการขาดความสามารถ จึงใช้ -(으)ㄹ 수 없다 (수영할 수 없어요) ส่วน -(으)면 안 되다 "ห้าม" (เป็นกฎ ไม่ใช่ทำไม่เป็น), -(으)ㄹ까요 "...กันไหม", -고 싶다 "อยาก"',
      'Sebab "못 배워서" (tak pernah belajar) tentang kurangnya KEMAMPUAN, jadi -(으)ㄹ 수 없다 (수영할 수 없어요) cocok; -(으)면 안 되다 "tidak boleh" (aturan, bukan ketakmampuan), -(으)ㄹ까요 "yuk?", -고 싶다 "ingin".',
      'Nguyên nhân "못 배워서" (chưa từng học) nói về thiếu KHẢ NĂNG, nên dùng -(으)ㄹ 수 없다 (수영할 수 없어요); -(으)면 안 되다 là "không được phép" (luật, không phải bất lực), -(으)ㄹ까요 "…nhé?", -고 싶다 "muốn".',
      '原因「못 배워서」(習わなかった)は能力の欠如なので -(으)ㄹ 수 없다(수영할 수 없어요)。-(으)면 안 되다 は「禁止」(規則であって不可能ではない)、-(으)ㄹ까요 は「ましょうか」、-고 싶다 は「たい」。',
    ),
  },
  {
    ko: '-(으)ㄹ 때',
    sentence: '한국에서는 사람을 처음 {} 보통 인사를 하면서 가볍게 고개를 숙여요.',
    answer: '만날 때',
    distractors: ['만나기 전에', '만난 후에', '만나니까'],
    trans: L(
      'In Korea, when you first meet someone, you usually greet them while bowing your head slightly.',
      'En Corea, cuando conoces a alguien por primera vez, sueles saludar inclinando ligeramente la cabeza.',
      "En Corée, quand on rencontre quelqu'un pour la première fois, on salue d'ordinaire en inclinant légèrement la tête.",
      'Na Coreia, quando você conhece alguém pela primeira vez, costuma cumprimentar inclinando levemente a cabeça.',
      'ที่เกาหลี เวลาพบใครครั้งแรก มักจะทักทายพร้อมก้มศีรษะเล็กน้อย',
      'Di Korea, ketika pertama kali bertemu seseorang, biasanya menyapa sambil sedikit menundukkan kepala.',
      'Ở Hàn Quốc, khi lần đầu gặp ai đó, người ta thường chào và hơi cúi đầu.',
      '韓国では、人に初めて会うとき、普通あいさつをしながら軽く頭を下げます。',
    ),
    why: L(
      'The greeting happens AT THE MOMENT of first meeting (it co-occurs with it), so -(으)ㄹ 때 (만날 때) fits; -기 전에 "before meeting" is illogical (you greet AS you meet, not before), -(으)ㄴ 후에 "after meeting" misplaces the greeting, -(으)니까 states a reason — none means "at the time of".',
      'El saludo ocurre EN EL MOMENTO del primer encuentro (coincide con él), así que va -(으)ㄹ 때 (만날 때); -기 전에 "antes de conocer" es ilógico (saludas AL conocer, no antes), -(으)ㄴ 후에 "después de conocer" desubica el saludo, -(으)니까 da una razón.',
      "Le salut a lieu AU MOMENT de la première rencontre (il coïncide avec elle), donc -(으)ㄹ 때 (만날 때) ; -기 전에 « avant de rencontrer » est illogique (on salue EN rencontrant), -(으)ㄴ 후에 « après avoir rencontré » déplace le salut, -(으)니까 = une raison.",
      'O cumprimento ocorre NO MOMENTO do primeiro encontro (coincide com ele), então cabe -(으)ㄹ 때 (만날 때); -기 전에 "antes de conhecer" é ilógico (cumprimenta-se AO conhecer), -(으)ㄴ 후에 "depois de conhecer" desloca o cumprimento, -(으)니까 dá um motivo.',
      'การทักทายเกิดขึ้น "ขณะ" พบกันครั้งแรก (พร้อมกัน) จึงใช้ -(으)ㄹ 때 (만날 때) ส่วน -기 전에 "ก่อนพบ" ไม่สมเหตุผล (ทักทายตอนพบ ไม่ใช่ก่อน), -(으)ㄴ 후에 "หลังพบ" ผิดที่, -(으)니까 บอกเหตุผล',
      'Sapaan terjadi PADA SAAT pertemuan pertama (bersamaan dengannya), jadi -(으)ㄹ 때 (만날 때) cocok; -기 전에 "sebelum bertemu" tak masuk akal (menyapa SAAT bertemu), -(으)ㄴ 후에 "setelah bertemu" salah tempat, -(으)니까 memberi alasan.',
      'Lời chào diễn ra VÀO LÚC gặp lần đầu (đồng thời với nó), nên dùng -(으)ㄹ 때 (만날 때); -기 전에 "trước khi gặp" vô lý (chào KHI gặp, không phải trước), -(으)ㄴ 후에 "sau khi gặp" đặt sai chỗ, -(으)니까 nêu lý do.',
      'あいさつは初めて会う「とき」(同時)に起こるので -(으)ㄹ 때(만날 때)。-기 전에 は「会う前に」(会う前にあいさつは不自然)、-(으)ㄴ 후에 は「会った後で」で位置がずれる、-(으)니까 は理由。',
    ),
  },
  {
    ko: '-는 동안',
    sentence: '제가 요리하는 {} 동생은 청소를 했어요.',
    answer: '동안',
    distractors: ['때문에', '덕분에', '뒤에'],
    trans: L(
      'While I was cooking, my younger sibling cleaned.',
      'Mientras yo cocinaba, mi hermano menor limpiaba.',
      'Pendant que je cuisinais, mon cadet faisait le ménage.',
      'Enquanto eu cozinhava, meu irmão mais novo limpava.',
      'ระหว่างที่ฉันทำอาหาร น้องก็ทำความสะอาด',
      'Selama saya memasak, adik saya membersihkan.',
      'Trong khi tôi nấu ăn, em tôi dọn dẹp.',
      '私が料理している間、弟は掃除をしました。',
    ),
    why: L(
      'Two actions overlap over a span, and the modifier 요리하는 + ___ needs the duration noun, so -는 동안 (동안) fits; 요리하는 때문에 and 요리하는 덕분에 are ungrammatical (때문에 needs -기/a noun, 덕분에 wants -(으)ㄴ/a noun), and 뒤에 ("behind/after") does not form a "while" clause off 하는.',
      'Dos acciones se superponen en un lapso y el modificador 요리하는 + ___ pide el sustantivo de duración, así que va -는 동안 (동안); 요리하는 때문에 y 요리하는 덕분에 son agramaticales (때문에 exige -기/un sustantivo, 덕분에 quiere -(으)ㄴ/un sustantivo), y 뒤에 ("detrás/después") no forma una cláusula de simultaneidad sobre 하는.',
      "Deux actions se chevauchent sur une durée et le déterminant 요리하는 + ___ exige le nom de durée, donc -는 동안 (동안) ; 요리하는 때문에 et 요리하는 덕분에 sont agrammaticaux (때문에 demande -기/un nom, 덕분에 veut -(으)ㄴ/un nom), et 뒤에 (« derrière/après ») ne forme pas une proposition de simultanéité sur 하는.",
      'Duas ações se sobrepõem num período e o modificador 요리하는 + ___ pede o substantivo de duração, então cabe -는 동안 (동안); 요리하는 때문에 e 요리하는 덕분에 são agramaticais (때문에 pede -기/um substantivo, 덕분에 quer -(으)ㄴ/um substantivo), e 뒤에 ("atrás/depois") não forma oração de simultaneidade com 하는.',
      'สองการกระทำเกิดพร้อมกันช่วงหนึ่ง และตัวขยาย 요리하는 + ___ ต้องการคำนามบอกช่วงเวลา จึงใช้ -는 동안 (동안) ส่วน 요리하는 때문에 และ 요리하는 덕분에 ผิดไวยากรณ์ (때문에 ต้องการ -기/คำนาม, 덕분에 ต้องการ -(으)ㄴ/คำนาม) และ 뒤에 ("ข้างหลัง/หลัง") ไม่สร้างประโยค "ขณะ" จาก 하는',
      'Dua aksi tumpang-tindih dalam rentang waktu, dan pewatas 요리하는 + ___ butuh kata benda durasi, jadi -는 동안 (동안) cocok; 요리하는 때문에 dan 요리하는 덕분에 tak gramatikal (때문에 butuh -기/kata benda, 덕분에 mau -(으)ㄴ/kata benda), dan 뒤에 ("di belakang/setelah") tak membentuk klausa "selama" dari 하는.',
      'Hai hành động chồng lên trong một khoảng thời gian, và định ngữ 요리하는 + ___ cần danh từ chỉ thời lượng, nên dùng -는 동안 (동안); 요리하는 때문에 và 요리하는 덕분에 sai ngữ pháp (때문에 cần -기/danh từ, 덕분에 cần -(으)ㄴ/danh từ), và 뒤에 ("phía sau/sau") không tạo mệnh đề "trong khi" từ 하는.',
      '二つの動作が一定時間重なり、連体形 요리하는 + ___ は期間の名詞を要するので -는 동안(동안)。요리하는 때문에・요리하는 덕분에 は非文(때문에 は -기/名詞、덕분에 は -(으)ㄴ/名詞を要する)、뒤에(「後ろ/後」)は 하는 から「間」の節を作らない。',
    ),
  },
  {
    ko: '-고 나서 / -고 나면',
    sentence: '운동을 {} 나서 샤워를 했어요.',
    answer: '하고',
    distractors: ['하지만', '하거나', '하려고'],
    trans: L(
      'After (finishing) exercising, I took a shower.',
      'Después de (terminar de) hacer ejercicio, me duché.',
      "Après avoir (fini de) faire du sport, j'ai pris une douche.",
      'Depois de (terminar de) me exercitar, tomei banho.',
      'หลังจากออกกำลังกายเสร็จ ฉันก็อาบน้ำ',
      'Setelah selesai berolahraga, saya mandi.',
      'Sau khi tập thể dục xong, tôi đi tắm.',
      '運動をしてからシャワーを浴びました。',
    ),
    why: L(
      'The fixed form -고 나서 (하고 나서) marks "after fully finishing exercise, then shower"; only -고 attaches to 나서. -지만 "but", -거나 "or", -려고 "in order to" cannot precede 나서 and don\'t give the after-completion sequence.',
      'La forma fija -고 나서 (하고 나서) marca "tras terminar el ejercicio, entonces ducharse"; solo -고 se une a 나서. -지만 "pero", -거나 "o", -려고 "para" no pueden preceder a 나서 ni dan la secuencia de finalización.',
      "La forme figée -고 나서 (하고 나서) marque « après avoir fini le sport, alors la douche » ; seul -고 se lie à 나서. -지만 « mais », -거나 « ou », -려고 « pour » ne précèdent pas 나서.",
      'A forma fixa -고 나서 (하고 나서) marca "depois de terminar o exercício, então o banho"; só -고 liga-se a 나서. -지만 "mas", -거나 "ou", -려고 "para" não antecedem 나서.',
      'รูปตายตัว -고 나서 (하고 나서) บอก "พอออกกำลังกายเสร็จแล้วค่อยอาบน้ำ" มีแต่ -고 ที่ต่อกับ 나서 ได้ ส่วน -지만 "แต่", -거나 "หรือ", -려고 "เพื่อ" ต่อ 나서 ไม่ได้',
      'Bentuk tetap -고 나서 (하고 나서) berarti "setelah selesai olahraga, lalu mandi"; hanya -고 yang menempel ke 나서. -지만 "tapi", -거나 "atau", -려고 "untuk" tak bisa mendahului 나서.',
      'Dạng cố định -고 나서 (하고 나서) nghĩa là "sau khi tập xong rồi tắm"; chỉ -고 gắn với 나서. -지만 "nhưng", -거나 "hoặc", -려고 "để" không đứng trước 나서.',
      '固定形 -고 나서(하고 나서)は「運動を終えてからシャワー」を表し、나서 に付くのは -고 のみ。-지만「が」、-거나「か」、-려고「ために」は 나서 の前に置けない。',
    ),
  },
  {
    ko: '-(으)ㄴ/는 것 같다',
    sentence: '하늘이 어두운 걸 보니 곧 비가 {}.',
    answer: '올 것 같아요',
    distractors: ['와야 해요', '오면 안 돼요', '온 적이 있어요'],
    trans: L(
      'The sky is dark, so it looks like it will rain soon.',
      'El cielo está oscuro, así que parece que pronto lloverá.',
      'Le ciel est sombre, on dirait donc qu\'il va bientôt pleuvoir.',
      'O céu está escuro, então parece que vai chover logo.',
      'ท้องฟ้ามืด ดูเหมือนว่าฝนจะตกเร็ว ๆ นี้',
      'Langit gelap, sepertinya sebentar lagi akan hujan.',
      'Trời tối, có vẻ sắp mưa rồi.',
      '空が暗いのを見ると、もうすぐ雨が降りそうです。',
    ),
    why: L(
      'Dark sky is visual evidence for a soft guess about the future, so -(으)ㄹ 것 같다 (올 것 같아요) fits; -아/어야 하다 means "must rain" (obligation, impossible for weather), -(으)면 안 되다 "must not", -(으)ㄴ 적이 있다 "have once done" — none is a conjecture.',
      'El cielo oscuro es evidencia visual para una suposición suave sobre el futuro, así que va -(으)ㄹ 것 같다 (올 것 같아요); -아/어야 하다 "tiene que llover" (obligación, imposible para el clima), -(으)면 안 되다 "no debe", -(으)ㄴ 적이 있다 "haber hecho alguna vez".',
      "Le ciel sombre est un indice visuel d'une supposition douce sur l'avenir, donc -(으)ㄹ 것 같다 (올 것 같아요) ; -아/어야 하다 « il doit pleuvoir » (obligation, absurde pour la météo), -(으)면 안 되다 « il ne faut pas », -(으)ㄴ 적이 있다 « avoir déjà fait ».",
      'O céu escuro é evidência visual para um palpite suave sobre o futuro, então cabe -(으)ㄹ 것 같다 (올 것 같아요); -아/어야 하다 "tem que chover" (obrigação, impossível para o clima), -(으)면 안 되다 "não pode", -(으)ㄴ 적이 있다 "já fez uma vez".',
      'ท้องฟ้ามืดเป็นหลักฐานทางสายตาสำหรับการคาดเดาอนาคตเบา ๆ จึงใช้ -(으)ㄹ 것 같다 (올 것 같아요) ส่วน -아/어야 하다 "ฝนต้องตก" (เป็นข้อบังคับ ใช้กับอากาศไม่ได้), -(으)면 안 되다 "ห้าม", -(으)ㄴ 적이 있다 "เคย"',
      'Langit gelap adalah bukti visual untuk dugaan halus tentang masa depan, jadi -(으)ㄹ 것 같다 (올 것 같아요) cocok; -아/어야 하다 "harus hujan" (kewajiban, mustahil bagi cuaca), -(으)면 안 되다 "tidak boleh", -(으)ㄴ 적이 있다 "pernah".',
      'Trời tối là bằng chứng thị giác cho phỏng đoán nhẹ về tương lai, nên dùng -(으)ㄹ 것 같다 (올 것 같아요); -아/어야 하다 "phải mưa" (bắt buộc, vô lý với thời tiết), -(으)면 안 되다 "không được", -(으)ㄴ 적이 있다 "đã từng".',
      '暗い空は未来への弱い推量の視覚的根拠なので -(으)ㄹ 것 같다(올 것 같아요)。-아/어야 하다 は「降らねば」(義務で天気に不適)、-(으)면 안 되다 は「禁止」、-(으)ㄴ 적이 있다 は「したことがある」。',
    ),
  },
  {
    ko: '-(으)면 되다',
    sentence: '표는 그냥 여기에서 {} 돼요.',
    answer: '사면',
    distractors: ['사니까', '사거나', '사지만'],
    trans: L(
      'You just need to buy the ticket right here.',
      'Solo tienes que comprar el boleto aquí mismo.',
      "Il suffit d'acheter le billet ici même.",
      'Você só precisa comprar o ingresso aqui mesmo.',
      'แค่ซื้อตั๋วตรงนี้ก็พอ',
      'Cukup beli tiketnya di sini saja.',
      'Bạn chỉ cần mua vé ngay tại đây là được.',
      'チケットはここで買えばいいです。',
    ),
    why: L(
      'With 돼요 closing the clause, the "just need to / it suffices to" pattern is -(으)면 되다 (사면 돼요); the connectives -(으)니까 "because", -거나 "or", -지만 "but" cannot attach to 되다 here (*사니까 돼요 / *사거나 돼요 / *사지만 돼요 are ungrammatical) and none gives "it\'s enough to".',
      'Con 돼요 cerrando la cláusula, el patrón "basta con / solo hay que" es -(으)면 되다 (사면 돼요); los conectores -(으)니까 "porque", -거나 "o", -지만 "pero" no se unen a 되다 aquí (*사니까 돼요 / *사거나 돼요 / *사지만 돼요 son agramaticales) y ninguno da "basta con".',
      "Avec 돼요 en fin de proposition, le motif « il suffit de » est -(으)면 되다 (사면 돼요) ; les connecteurs -(으)니까 « parce que », -거나 « ou », -지만 « mais » ne se lient pas à 되다 ici (*사니까 돼요 / *사거나 돼요 / *사지만 돼요 sont agrammaticaux).",
      'Com 돼요 fechando a oração, o padrão "basta / só precisa" é -(으)면 되다 (사면 돼요); os conectores -(으)니까 "porque", -거나 "ou", -지만 "mas" não se ligam a 되다 aqui (*사니까 돼요 / *사거나 돼요 / *사지만 돼요 são agramaticais).',
      'เมื่อมี 돼요 ปิดประโยค รูป "แค่...ก็พอ" คือ -(으)면 되다 (사면 돼요) ส่วนคำเชื่อม -(으)니까 "เพราะ", -거나 "หรือ", -지만 "แต่" ต่อกับ 되다 ไม่ได้ (*사니까 돼요 / *사거나 돼요 / *사지만 돼요 ผิดไวยากรณ์)',
      'Dengan 돼요 menutup klausa, pola "cukup / tinggal" adalah -(으)면 되다 (사면 돼요); konektor -(으)니까 "karena", -거나 "atau", -지만 "tapi" tak bisa menempel ke 되다 di sini (*사니까 돼요 / *사거나 돼요 / *사지만 돼요 tak gramatikal).',
      'Với 돼요 kết thúc mệnh đề, mẫu "chỉ cần" là -(으)면 되다 (사면 돼요); các liên từ -(으)니까 "vì", -거나 "hoặc", -지만 "nhưng" không gắn với 되다 ở đây (*사니까 돼요 / *사거나 돼요 / *사지만 돼요 sai ngữ pháp).',
      '돼요 が節を締めるので「〜ばいい」は -(으)면 되다(사면 돼요)。接続の -(으)니까「から」、-거나「か」、-지만「が」は ここで 되다 に付けない(*사니까 돼요 / *사거나 돼요 / *사지만 돼요 は非文)。',
    ),
  },
  {
    ko: '-(으)ㄹ 필요가 있다/없다',
    sentence: '시험에 다 통과했으니까 더 이상 걱정할 {}.',
    answer: '필요가 없어요',
    distractors: ['수밖에 없어요', '뻔했어요', '리가 없어요'],
    trans: L(
      'Since you passed all the exams, there\'s no need to worry anymore.',
      'Como aprobaste todos los exámenes, ya no hay necesidad de preocuparse.',
      'Comme tu as réussi tous les examens, plus besoin de t\'inquiéter.',
      'Como você passou em todas as provas, não há mais necessidade de se preocupar.',
      'เพราะสอบผ่านหมดแล้ว จึงไม่จำเป็นต้องกังวลอีกต่อไป',
      'Karena sudah lulus semua ujian, tidak perlu khawatir lagi.',
      'Vì đã đậu hết các kỳ thi nên không cần lo lắng nữa.',
      '試験に全部受かったから、もう心配する必要がありません。',
    ),
    why: L(
      'Passing removes the need, so 걱정할 + -(으)ㄹ 필요가 없다 (필요가 없어요) fits; -(으)ㄹ 수밖에 없다 = "have no choice but", -(으)ㄹ 뻔했다 = "almost did", -(으)ㄹ 리가 없다 = "there\'s no way" — none means "no need to".',
      'Aprobar elimina la necesidad, así que 걱정할 + -(으)ㄹ 필요가 없다 (필요가 없어요); -(으)ㄹ 수밖에 없다 = "no quedar más remedio", -(으)ㄹ 뻔했다 = "estar a punto de", -(으)ㄹ 리가 없다 = "es imposible que".',
      "Réussir supprime le besoin, donc 걱정할 + -(으)ㄹ 필요가 없다 (필요가 없어요) ; -(으)ㄹ 수밖에 없다 « n'avoir d'autre choix que », -(으)ㄹ 뻔했다 « avoir failli », -(으)ㄹ 리가 없다 « impossible que ».",
      'Passar elimina a necessidade, então 걱정할 + -(으)ㄹ 필요가 없다 (필요가 없어요); -(으)ㄹ 수밖에 없다 = "não ter escolha senão", -(으)ㄹ 뻔했다 = "quase fez", -(으)ㄹ 리가 없다 = "não há como".',
      'การสอบผ่านทำให้ไม่ต้องกังวล จึงใช้ 걱정할 + -(으)ㄹ 필요가 없다 (필요가 없어요) ส่วน -(으)ㄹ 수밖에 없다 "ไม่มีทางเลือกอื่น", -(으)ㄹ 뻔했다 "เกือบจะ", -(으)ㄹ 리가 없다 "เป็นไปไม่ได้"',
      'Lulus menghilangkan kebutuhan, jadi 걱정할 + -(으)ㄹ 필요가 없다 (필요가 없어요) cocok; -(으)ㄹ 수밖에 없다 = "tak ada pilihan selain", -(으)ㄹ 뻔했다 = "hampir saja", -(으)ㄹ 리가 없다 = "mustahil".',
      'Đậu rồi thì hết cần, nên dùng 걱정할 + -(으)ㄹ 필요가 없다 (필요가 없어요); -(으)ㄹ 수밖에 없다 = "không còn cách nào khác", -(으)ㄹ 뻔했다 = "suýt nữa", -(으)ㄹ 리가 없다 = "không thể nào".',
      '合格で必要が消えるので 걱정할 + -(으)ㄹ 필요가 없다(필요가 없어요)。-(으)ㄹ 수밖에 없다 は「するしかない」、-(으)ㄹ 뻔했다 は「しそうだった」、-(으)ㄹ 리가 없다 は「はずがない」。',
    ),
  },
  {
    ko: '-(으)ㄹ게요',
    sentence: '걱정 마세요. 이번 일은 제가 책임지고 {}.',
    answer: '할게요',
    distractors: ['해요', '할까요', '하잖아요'],
    trans: L(
      "Don't worry. I'll take responsibility and do this myself.",
      'No te preocupes. De esto me hago cargo yo y lo haré.',
      'Ne t\'inquiète pas. Je prends la responsabilité et je le ferai.',
      'Não se preocupe. Eu assumo a responsabilidade e farei isto.',
      'ไม่ต้องห่วง เรื่องนี้ผมจะรับผิดชอบทำเอง',
      'Jangan khawatir. Urusan ini akan saya tangani sendiri.',
      'Đừng lo. Việc này tôi sẽ chịu trách nhiệm và làm.',
      '心配しないでください。今回のことは私が責任を持ってやります。',
    ),
    why: L(
      'The speaker makes an on-the-spot promise to the listener, so 1st-person -(으)ㄹ게요 (할게요) fits; -아/어요 is plain present (no commitment nuance), -(으)ㄹ까요 asks "shall we?", -잖아요 recalls shared info — none is a promise.',
      'El hablante hace una promesa en el momento al oyente, así que va la 1ª persona -(으)ㄹ게요 (할게요); -아/어요 es presente neutro (sin matiz de compromiso), -(으)ㄹ까요 pregunta "¿hacemos?", -잖아요 alude a info compartida.',
      "Le locuteur fait une promesse immédiate à l'interlocuteur, donc la 1ʳᵉ personne -(으)ㄹ게요 (할게요) ; -아/어요 = présent neutre, -(으)ㄹ까요 « on…? », -잖아요 rappelle une info connue.",
      'O falante faz uma promessa no momento ao ouvinte, então cabe a 1ª pessoa -(으)ㄹ게요 (할게요); -아/어요 é presente neutro, -(으)ㄹ까요 pergunta "vamos?", -잖아요 retoma info compartilhada.',
      'ผู้พูดให้สัญญาในขณะนั้นกับผู้ฟัง จึงใช้บุรุษที่ 1 -(으)ㄹ게요 (할게요) ส่วน -아/어요 ปัจจุบันธรรมดา, -(으)ㄹ까요 ถาม "...ไหม", -잖아요 เตือนสิ่งที่รู้กัน',
      'Penutur berjanji saat itu juga kepada pendengar, jadi orang pertama -(으)ㄹ게요 (할게요) cocok; -아/어요 present netral, -(으)ㄹ까요 "yuk?", -잖아요 mengingatkan info bersama.',
      'Người nói hứa ngay lúc đó với người nghe, nên dùng ngôi 1 -(으)ㄹ게요 (할게요); -아/어요 hiện tại trung tính, -(으)ㄹ까요 "…nhé?", -잖아요 nhắc thông tin đã biết.',
      '話し手がその場で聞き手に約束するので一人称 -(으)ㄹ게요(할게요)。-아/어요 は中立の現在、-(으)ㄹ까요 は「ましょうか」、-잖아요 は既知情報の確認。',
    ),
  },
  {
    ko: '-(으)ㄹ까요?',
    sentence: '날씨가 좋은데 우리 같이 공원에 {}',
    answer: '산책하러 갈까요?',
    distractors: ['산책하러 갔어요', '산책하러 가야 해요', '산책하러 가잖아요'],
    trans: L(
      'The weather is nice — shall we go for a walk in the park together?',
      'Hace buen tiempo, ¿vamos juntos a pasear al parque?',
      'Il fait beau — on va se promener ensemble au parc ?',
      'O tempo está bom — vamos passear juntos no parque?',
      'อากาศดีจัง เราไปเดินเล่นที่สวนด้วยกันไหม',
      'Cuacanya bagus — yuk kita jalan-jalan ke taman bareng?',
      'Trời đẹp quá — chúng ta cùng đi dạo công viên nhé?',
      '天気がいいですね、一緒に公園へ散歩しに行きましょうか？',
    ),
    why: L(
      'It proposes a shared activity and invites agreement, so -(으)ㄹ까요? (갈까요?) fits; -았/었어요 is past statement, -아/어야 하다 is "must" (obligation, not invitation), -잖아요 recalls shared info — none is a suggestion.',
      'Propone una actividad conjunta e invita a aceptar, así que va -(으)ㄹ까요? (갈까요?); -았/었어요 es pasado, -아/어야 하다 es "deber" (obligación, no invitación), -잖아요 alude a info compartida.',
      "Cela propose une activité commune et invite à accepter, donc -(으)ㄹ까요? (갈까요?) ; -았/었어요 = passé, -아/어야 하다 = « devoir » (obligation), -잖아요 rappelle une info connue.",
      'Propõe uma atividade conjunta e convida a aceitar, então cabe -(으)ㄹ까요? (갈까요?); -았/었어요 é passado, -아/어야 하다 é "dever" (obrigação, não convite), -잖아요 retoma info compartilhada.',
      'เป็นการชวนทำกิจกรรมร่วมกันและรอการตอบรับ จึงใช้ -(으)ㄹ까요? (갈까요?) ส่วน -았/었어요 อดีต, -아/어야 하다 "ต้อง" (ข้อบังคับ ไม่ใช่ชวน), -잖아요 เตือนสิ่งที่รู้กัน',
      'Mengajukan kegiatan bersama dan mengundang persetujuan, jadi -(으)ㄹ까요? (갈까요?) cocok; -았/었어요 lampau, -아/어야 하다 "harus" (kewajiban, bukan ajakan), -잖아요 mengingatkan info bersama.',
      'Đề xuất một hoạt động chung và mời đồng ý, nên dùng -(으)ㄹ까요? (갈까요?); -았/었어요 quá khứ, -아/어야 하다 "phải" (bắt buộc, không phải rủ), -잖아요 nhắc thông tin đã biết.',
      '共同の活動を提案し同意を促すので -(으)ㄹ까요?(갈까요?)。-았/었어요 は過去、-아/어야 하다 は「ねばならない」(義務で勧誘でない)、-잖아요 は既知情報。',
    ),
  },
  {
    ko: '-아/어 보다',
    sentence: '이 떡볶이 정말 맛있어요. 한번 {}.',
    answer: '먹어 보세요',
    distractors: ['먹어 버리세요', '먹어 놓으세요', '먹고 있으세요'],
    trans: L(
      "This tteokbokki is really tasty. Try it once.",
      'Este tteokbokki está muy rico. Pruébalo una vez.',
      "Ce tteokbokki est vraiment bon. Goûtes-y une fois.",
      'Este tteokbokki está muito gostoso. Experimente uma vez.',
      'ต็อกบกกีนี้อร่อยมาก ลองชิมดูสักครั้งสิ',
      'Tteokbokki ini sangat enak. Cobalah sekali.',
      'Tteokbokki này ngon lắm. Thử một lần đi.',
      'このトッポッキ、本当に美味しいですよ。一度食べてみてください。',
    ),
    why: L(
      'Inviting someone to give it a go = -아/어 보다 (먹어 보세요); -아/어 버리다 means "eat it up completely" (relief/regret), -아/어 놓다 "eat and leave it ready", -고 있다 "be eating" — none is "try it".',
      'Invitar a probar = -아/어 보다 (먹어 보세요); -아/어 버리다 "comérselo del todo" (alivio/lamento), -아/어 놓다 "dejarlo comido/listo", -고 있다 "estar comiendo".',
      "Inviter à essayer = -아/어 보다 (먹어 보세요) ; -아/어 버리다 « tout manger » (soulagement/regret), -아/어 놓다 « manger et laisser prêt », -고 있다 « être en train de manger ».",
      'Convidar a experimentar = -아/어 보다 (먹어 보세요); -아/어 버리다 "comer tudo" (alívio/pesar), -아/어 놓다 "deixar comido/pronto", -고 있다 "estar comendo".',
      'ชวนให้ลอง = -아/어 보다 (먹어 보세요) ส่วน -아/어 버리다 "กินจนหมด" (โล่ง/เสียดาย), -아/어 놓다 "กินเตรียมไว้", -고 있다 "กำลังกิน"',
      'Mengajak mencoba = -아/어 보다 (먹어 보세요); -아/어 버리다 "menghabiskan" (lega/sesal), -아/어 놓다 "makan dan siapkan", -고 있다 "sedang makan".',
      'Mời thử = -아/어 보다 (먹어 보세요); -아/어 버리다 "ăn sạch" (nhẹ nhõm/tiếc), -아/어 놓다 "ăn để sẵn", -고 있다 "đang ăn".',
      '試すよう勧める = -아/어 보다(먹어 보세요)。-아/어 버리다 は「食べきる」(安堵/後悔)、-아/어 놓다 は「食べておく」、-고 있다 は「食べている」。',
    ),
  },
  {
    ko: '-아/어 버리다',
    sentence: '너무 배가 고파서 케이크를 혼자 다 {}.',
    answer: '먹어 버렸어요',
    distractors: ['먹어 봤어요', '먹어 뒀어요', '먹는 편이에요'],
    trans: L(
      'I was so hungry that I ended up eating the whole cake by myself.',
      'Tenía tanta hambre que me comí todo el pastel yo solo.',
      "J'avais tellement faim que j'ai fini par manger tout le gâteau tout seul.",
      'Eu estava com tanta fome que acabei comendo o bolo todo sozinho.',
      'หิวมากจนกินเค้กหมดคนเดียวเลย',
      'Saya begitu lapar sampai menghabiskan seluruh kue sendirian.',
      'Tôi đói quá nên đã ăn sạch cả cái bánh một mình.',
      'お腹がすきすぎて、ケーキを一人で全部食べてしまいました。',
    ),
    why: L(
      'A finished-off action with an emotional "oops, all gone" flavor = -아/어 버리다 (먹어 버렸어요); -아/어 보다 "try eating" (past 먹어 봤어요 = "have tried"), -아/어 두다 "eat and store for later", -는 편이다 "tend to" — none carries the complete-and-regret nuance.',
      'Acción consumada con matiz de "ya no queda" = -아/어 버리다 (먹어 버렸어요); -아/어 보다 "probar a comer" (먹어 봤어요 = "haber probado"), -아/어 두다 "dejar guardado", -는 편이다 "soler / tender a".',
      "Action menée à terme avec nuance « tout est parti » = -아/어 버리다 (먹어 버렸어요) ; -아/어 보다 « goûter » (먹어 봤어요 = « avoir essayé »), -아/어 두다 « garder pour plus tard », -는 편이다 « avoir tendance à ».",
      'Ação concluída com tom de "acabou tudo" = -아/어 버리다 (먹어 버렸어요); -아/어 보다 "experimentar" (먹어 봤어요 = "já ter experimentado"), -아/어 두다 "guardar", -는 편이다 "costumar / tender a".',
      'การกระทำที่จบเด็ดขาดพร้อมอารมณ์ "หมดเกลี้ยง" = -아/어 버리다 (먹어 버렸어요) ส่วน -아/어 보다 "ลองกิน" (먹어 봤어요 "เคยลอง"), -아/어 두다 "เก็บไว้", -는 편이다 "มักจะ"',
      'Aksi tuntas dengan nuansa "habis semua" = -아/어 버리다 (먹어 버렸어요); -아/어 보다 "coba makan" (먹어 봤어요 "pernah coba"), -아/어 두다 "simpan untuk nanti", -는 편이다 "cenderung".',
      'Hành động xong xuôi kèm cảm xúc "hết sạch" = -아/어 버리다 (먹어 버렸어요); -아/어 보다 "thử ăn" (먹어 봤어요 "đã từng thử"), -아/어 두다 "để dành", -는 편이다 "có xu hướng".',
      '完全に終え「全部なくなった」感情を伴う = -아/어 버리다(먹어 버렸어요)。-아/어 보다 は「食べてみる」(먹어 봤어요=「食べたことがある」)、-아/어 두다 は「取っておく」、-는 편이다 は「〜する方だ」。',
    ),
  },
  {
    ko: '-아/어 놓다 / -아/어 두다',
    sentence: '손님이 오시기 전에 음식을 미리 만들어 {}.',
    answer: '놓았어요',
    distractors: ['보았어요', '버렸어요', '주었어요'],
    trans: L(
      'I prepared the food in advance before the guests arrived.',
      'Preparé la comida con antelación antes de que llegaran los invitados.',
      "J'ai préparé la nourriture à l'avance avant l'arrivée des invités.",
      'Preparei a comida com antecedência antes de os convidados chegarem.',
      'ฉันทำอาหารเตรียมไว้ล่วงหน้าก่อนที่แขกจะมา',
      'Saya menyiapkan makanan lebih dulu sebelum tamu datang.',
      'Tôi đã làm sẵn đồ ăn trước khi khách đến.',
      'お客さんが来る前に、料理を前もって作っておきました。',
    ),
    why: L(
      '"미리" (in advance) signals doing and leaving it ready for later = -아/어 놓다 (만들어 놓았어요); -아/어 보다 "try making", -아/어 버리다 "finish off / use up", -아/어 주다 "make for someone" — none means "prepare and leave ready".',
      '"미리" (de antemano) indica hacerlo y dejarlo listo = -아/어 놓다 (만들어 놓았어요); -아/어 보다 "probar a hacer", -아/어 버리다 "terminar/gastar", -아/어 주다 "hacer para alguien".',
      "« 미리 » (à l'avance) indique faire et laisser prêt = -아/어 놓다 (만들어 놓았어요) ; -아/어 보다 « essayer de faire », -아/어 버리다 « finir/épuiser », -아/어 주다 « faire pour qqn ».",
      '"미리" (com antecedência) indica fazer e deixar pronto = -아/어 놓다 (만들어 놓았어요); -아/어 보다 "tentar fazer", -아/어 버리다 "terminar/gastar", -아/어 주다 "fazer para alguém".',
      '"미리" (ล่วงหน้า) บอกว่าทำเตรียมไว้ = -아/어 놓다 (만들어 놓았어요) ส่วน -아/어 보다 "ลองทำ", -아/어 버리다 "ทำให้หมด", -아/어 주다 "ทำให้ใคร"',
      '"미리" (sebelumnya) menandakan membuat dan menyiapkan = -아/어 놓다 (만들어 놓았어요); -아/어 보다 "coba buat", -아/어 버리다 "habiskan/selesaikan", -아/어 주다 "buatkan untuk seseorang".',
      '"미리" (trước) cho thấy làm và để sẵn = -아/어 놓다 (만들어 놓았어요); -아/어 보다 "thử làm", -아/어 버리다 "làm hết / xong sạch", -아/어 주다 "làm giúp ai".',
      '「미리」(前もって)は作って準備しておくことを示す = -아/어 놓다(만들어 놓았어요)。-아/어 보다 は「作ってみる」、-아/어 버리다 は「使い切る/やってしまう」、-아/어 주다 は「作ってあげる」。',
    ),
  },
  {
    ko: '때문에 / 기 때문에',
    sentence: '어제는 갑자기 일이 {} 모임에 못 갔어요.',
    answer: '생겼기 때문에',
    distractors: ['생기더라도', '생기는지', '생기거나'],
    trans: L(
      'Something came up suddenly yesterday, so I couldn\'t go to the gathering.',
      'Ayer me surgió algo de repente, así que no pude ir a la reunión.',
      "Hier, quelque chose est survenu soudainement, donc je n'ai pas pu aller au rassemblement.",
      'Ontem surgiu algo de repente, então não pude ir ao encontro.',
      'เมื่อวานจู่ ๆ มีธุระ เลยไปงานรวมตัวไม่ได้',
      'Kemarin tiba-tiba ada urusan, jadi saya tidak bisa datang ke pertemuan.',
      'Hôm qua đột nhiên có việc nên tôi không đi họp mặt được.',
      '昨日は急に用事ができたので、集まりに行けませんでした。',
    ),
    why: L(
      'It gives the clear cause for not going (formal reason on a verb), so V + -기 때문에 (생겼기 때문에) fits; -더라도 "even if", -(으)ㄴ/는지 "whether", -거나 "or" — none states a cause.',
      'Da la causa clara de no ir (razón formal sobre un verbo), así que va V + -기 때문에 (생겼기 때문에); -더라도 "aunque", -(으)ㄴ/는지 "si/acaso", -거나 "o".',
      "Cela donne la cause claire de l'absence (raison formelle sur un verbe), donc V + -기 때문에 (생겼기 때문에) ; -더라도 « même si », -(으)ㄴ/는지 « si/quand », -거나 « ou ».",
      'Dá a causa clara de não ir (razão formal sobre um verbo), então cabe V + -기 때문에 (생겼기 때문에); -더라도 "mesmo que", -(으)ㄴ/는지 "se", -거나 "ou".',
      'บอกสาเหตุชัดเจนที่ไปไม่ได้ (เหตุผลทางการกับกริยา) จึงใช้ V + -기 때문에 (생겼기 때문에) ส่วน -더라도 "แม้ว่า", -(으)ㄴ/는지 "ว่า...หรือไม่", -거나 "หรือ"',
      'Memberi sebab jelas tidak hadir (alasan formal pada verba), jadi V + -기 때문에 (생겼기 때문에) cocok; -더라도 "meskipun", -(으)ㄴ/는지 "apakah", -거나 "atau".',
      'Nêu rõ nguyên nhân không đi (lý do trang trọng trên động từ), nên dùng V + -기 때문에 (생겼기 때문에); -더라도 "dù", -(으)ㄴ/는지 "liệu", -거나 "hoặc".',
      '行けなかった明確な理由(動詞に付く格式的理由)なので V + -기 때문에(생겼기 때문에)。-더라도 は「ても」、-(으)ㄴ/는지 は「かどうか」、-거나 は「か」。',
    ),
  },
  {
    ko: '-보다',
    sentence: '오늘은 어제{} 날씨가 더 따뜻해요.',
    answer: '보다',
    distractors: ['처럼', '마다', '부터'],
    trans: L(
      'Today the weather is warmer than yesterday.',
      'Hoy el clima está más cálido que ayer.',
      "Aujourd'hui il fait plus chaud qu'hier.",
      'Hoje o tempo está mais quente que ontem.',
      'วันนี้อากาศอุ่นกว่าเมื่อวาน',
      'Hari ini cuacanya lebih hangat daripada kemarin.',
      'Hôm nay thời tiết ấm hơn hôm qua.',
      '今日は昨日より天気が暖かいです。',
    ),
    why: L(
      'With 더 ("more") marking comparison, the standard "than" particle is -보다 (어제보다); -처럼 means "like/as" (similarity, not comparison), -마다 "every", -부터 "from" — none expresses "than".',
      'Con 더 ("más") marcando la comparación, la partícula "que" es -보다 (어제보다); -처럼 "como" (semejanza, no comparación), -마다 "cada", -부터 "desde".',
      "Avec 더 (« plus ») marquant la comparaison, la particule « que » est -보다 (어제보다) ; -처럼 « comme » (ressemblance), -마다 « chaque », -부터 « à partir de ».",
      'Com 더 ("mais") marcando a comparação, a partícula "que" é -보다 (어제보다); -처럼 "como" (semelhança), -마다 "cada", -부터 "desde".',
      'เมื่อมี 더 ("กว่า") บอกการเปรียบเทียบ คำช่วย "กว่า" คือ -보다 (어제보다) ส่วน -처럼 "เหมือน" (ความคล้าย), -마다 "ทุก", -부터 "ตั้งแต่"',
      'Dengan 더 ("lebih") menandai perbandingan, partikel "daripada" adalah -보다 (어제보다); -처럼 "seperti" (kemiripan), -마다 "setiap", -부터 "sejak".',
      'Với 더 ("hơn") đánh dấu so sánh, tiểu từ "hơn" là -보다 (어제보다); -처럼 "như" (giống), -마다 "mỗi", -부터 "từ".',
      '더(「もっと」)が比較を示すので「より」は -보다(어제보다)。-처럼 は「のように」(類似)、-마다 は「ごと」、-부터 は「から」。',
    ),
  },
  {
    ko: '-(으)ㄴ/는지',
    sentence: '회의가 몇 시에 {} 혹시 아세요?',
    answer: '시작하는지',
    distractors: ['시작하니까', '시작하거나', '시작해서'],
    trans: L(
      'Do you happen to know what time the meeting starts?',
      '¿Sabes por casualidad a qué hora empieza la reunión?',
      "Sais-tu par hasard à quelle heure commence la réunion ?",
      'Você por acaso sabe a que horas começa a reunião?',
      'คุณบังเอิญรู้ไหมว่าประชุมเริ่มกี่โมง',
      'Apakah Anda kebetulan tahu jam berapa rapat dimulai?',
      'Bạn có tình cờ biết cuộc họp bắt đầu lúc mấy giờ không?',
      '会議が何時に始まるか、もしかして知っていますか？',
    ),
    why: L(
      'The embedded "what time it starts" is an indirect question fed to 아세요?, so -(으)ㄴ/는지 (시작하는지) fits; -(으)니까 "because", -거나 "or", -아/어서 "and/because" are connectors that can\'t embed a wh-question.',
      'El "a qué hora empieza" incrustado es una pregunta indirecta para 아세요?, así que va -(으)ㄴ/는지 (시작하는지); -(으)니까 "porque", -거나 "o", -아/어서 "y/porque" son conectores que no incrustan una pregunta.',
      "Le « à quelle heure ça commence » enchâssé est une question indirecte pour 아세요?, donc -(으)ㄴ/는지 (시작하는지) ; -(으)니까 « parce que », -거나 « ou », -아/어서 « et/car » sont des connecteurs qui n'enchâssent pas une question.",
      'O "a que horas começa" embutido é uma pergunta indireta para 아세요?, então cabe -(으)ㄴ/는지 (시작하는지); -(으)니까 "porque", -거나 "ou", -아/어서 "e/porque" são conectores que não embutem pergunta.',
      '"เริ่มกี่โมง" ที่ฝังอยู่เป็นคำถามอ้อมที่ส่งให้ 아세요? จึงใช้ -(으)ㄴ/는지 (시작하는지) ส่วน -(으)니까 "เพราะ", -거나 "หรือ", -아/어서 "แล้ว/เพราะ" เป็นคำเชื่อมที่ฝังคำถามไม่ได้',
      '"Mulai jam berapa" yang tersemat adalah pertanyaan tak langsung untuk 아세요?, jadi -(으)ㄴ/는지 (시작하는지) cocok; -(으)니까 "karena", -거나 "atau", -아/어서 "lalu/karena" konektor yang tak bisa menyematkan pertanyaan.',
      '"Bắt đầu lúc mấy giờ" được nhúng là câu hỏi gián tiếp cho 아세요?, nên dùng -(으)ㄴ/는지 (시작하는지); -(으)니까 "vì", -거나 "hoặc", -아/어서 "rồi/vì" là liên từ không nhúng được câu hỏi.',
      '埋め込まれた「何時に始まるか」は 아세요? に渡る間接疑問なので -(으)ㄴ/는지(시작하는지)。-(으)니까「から」、-거나「か」、-아/어서「て/ので」は疑問を埋め込めない接続。',
    ),
  },
  {
    ko: '-(으)ㄹ까 봐',
    sentence: '시험에 {} 어젯밤에 잠도 못 잤어요.',
    answer: '떨어질까 봐',
    distractors: ['떨어지니까', '떨어지려고', '떨어지지만'],
    trans: L(
      "I couldn't even sleep last night, afraid I might fail the exam.",
      'Anoche ni pude dormir, por miedo a suspender el examen.',
      "La nuit dernière, je n'ai même pas pu dormir, de peur d'échouer à l'examen.",
      'Ontem à noite nem consegui dormir, com medo de reprovar na prova.',
      'เมื่อคืนนอนไม่หลับเลย เพราะกลัวว่าจะสอบตก',
      'Tadi malam saya tak bisa tidur, takut kalau-kalau gagal ujian.',
      'Tối qua tôi không ngủ được vì sợ thi rớt.',
      '試験に落ちるかと思って、昨夜は眠れませんでした。',
    ),
    why: L(
      'The sleeplessness is a worry-driven precaution against a feared outcome, so -(으)ㄹ까 봐 (떨어질까 봐) fits; -(으)니까 just states a reason without the fear nuance, -(으)려고 is "in order to" (purpose, wrong direction), -지만 "but".',
      'El insomnio es una precaución por miedo a un resultado temido, así que va -(으)ㄹ까 봐 (떨어질까 봐); -(으)니까 solo da una razón sin el matiz de temor, -(으)려고 "para" (propósito, dirección equivocada), -지만 "pero".',
      "L'insomnie est une précaution née de la peur d'un résultat redouté, donc -(으)ㄹ까 봐 (떨어질까 봐) ; -(으)니까 ne donne qu'une raison sans nuance de crainte, -(으)려고 « pour » (but, mauvaise direction), -지만 « mais ».",
      'A insônia é uma precaução motivada pelo medo de um resultado temido, então cabe -(으)ㄹ까 봐 (떨어질까 봐); -(으)니까 só dá um motivo sem o medo, -(으)려고 "para" (propósito, direção errada), -지만 "mas".',
      'การนอนไม่หลับเป็นการระวังเพราะกลัวผลที่ไม่อยากให้เกิด จึงใช้ -(으)ㄹ까 봐 (떨어질까 봐) ส่วน -(으)니까 บอกเหตุผลเฉย ๆ ไม่มีความกลัว, -(으)려고 "เพื่อ" (จุดประสงค์ ผิดทิศ), -지만 "แต่"',
      'Tak bisa tidur adalah kewaspadaan karena takut hasil buruk, jadi -(으)ㄹ까 봐 (떨어질까 봐) cocok; -(으)니까 cuma alasan tanpa rasa takut, -(으)려고 "untuk" (tujuan, arah salah), -지만 "tapi".',
      'Việc mất ngủ là sự đề phòng do sợ một kết quả xấu, nên dùng -(으)ㄹ까 봐 (떨어질까 봐); -(으)니까 chỉ nêu lý do không có nỗi sợ, -(으)려고 "để" (mục đích, sai hướng), -지만 "nhưng".',
      '眠れないのは恐れる結果への不安からの用心なので -(으)ㄹ까 봐(떨어질까 봐)。-(으)니까 は恐れの含みなく理由を述べるだけ、-(으)려고 は「ために」(目的で方向違い)、-지만 は「が」。',
    ),
  },
]
