// app/seed/cloze/n3.ts
import type { ClozeItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-3 grammar-pattern cloze items (choose the pattern that fits the blank).
 * ko matches grammars-n3.ts verbatim. Drafted + Korean-lens adversarially verified
 * (single-correct-answer crux). Korean wife native review = documented final gate.
 */

export const N3_CLOZE: ClozeItem[] = [
  {
    ko: '-게 되다',
    sentence: '회사 사정 때문에 갑자기 부산으로 {}.',
    answer: '이사하게 됐어요',
    distractors: ['이사할 거예요', '이사하고 싶어요', '이사하면 돼요'],
    trans: L(
      'Due to company circumstances, I ended up suddenly moving to Busan.',
      'Por circunstancias de la empresa, acabé mudándome de repente a Busan.',
      "À cause de la situation de l'entreprise, j'ai fini par déménager soudainement à Busan.",
      'Por circunstâncias da empresa, acabei me mudando de repente para Busan.',
      'เพราะสถานการณ์ของบริษัท ฉันเลยต้องย้ายไปปูซานกะทันหัน',
      'Karena keadaan perusahaan, saya jadi pindah mendadak ke Busan.',
      'Vì hoàn cảnh của công ty, cuối cùng tôi đã chuyển đến Busan một cách đột ngột.',
      '会社の事情で、急にプサンに引っ越すことになりました。',
    ),
    why: L(
      '회사 사정 때문에 + 갑자기 marks a change forced by circumstance, not will → -게 되다; 이사할 거예요 is a chosen future plan, 이사하고 싶어요 a personal wish, 이사하면 돼요 "it is okay to move" — none expresses the non-volitional outcome.',
      '회사 사정 때문에 + 갑자기 marca un cambio impuesto por las circunstancias, no por voluntad → -게 되다; 이사할 거예요 es un plan futuro elegido, 이사하고 싶어요 un deseo, 이사하면 돼요 "basta con mudarse" — ninguno expresa el resultado no volitivo.',
      "회사 사정 때문에 + 갑자기 marque un changement imposé par les circonstances, non choisi → -게 되다 ; 이사할 거예요 est un projet futur choisi, 이사하고 싶어요 un souhait, 이사하면 돼요 « il suffit de déménager » — aucun n'exprime le résultat non volontaire.",
      '회사 사정 때문에 + 갑자기 marca uma mudança imposta pelas circunstâncias, não pela vontade → -게 되다; 이사할 거예요 é um plano futuro escolhido, 이사하고 싶어요 um desejo, 이사하면 돼요 "basta mudar" — nenhum expressa o resultado não volitivo.',
      '회사 사정 때문에 + 갑자기 บ่งการเปลี่ยนแปลงที่ถูกบังคับด้วยสถานการณ์ ไม่ใช่เจตนา → -게 되다; 이사할 거예요 เป็นแผนอนาคตที่เลือกเอง, 이사하고 싶어요 เป็นความอยาก, 이사하면 돼요 "ย้ายก็ได้" ล้วนไม่สื่อผลที่ไม่ได้ตั้งใจ',
      '회사 사정 때문에 + 갑자기 menandai perubahan akibat keadaan, bukan kemauan → -게 되다; 이사할 거예요 rencana masa depan yang dipilih, 이사하고 싶어요 keinginan, 이사하면 돼요 "boleh pindah" — tak ada yang menyatakan hasil di luar kehendak.',
      '회사 사정 때문에 + 갑자기 đánh dấu sự thay đổi do hoàn cảnh ép buộc, không do ý chí → -게 되다; 이사할 거예요 là kế hoạch tương lai tự chọn, 이사하고 싶어요 là mong muốn, 이사하면 돼요 "chuyển nhà là được" — không cái nào diễn tả kết quả ngoài ý muốn.',
      '회사 사정 때문에＋갑자기 は意志でなく状況による変化を示すので -게 되다。이사할 거예요 は選んだ未来の予定、이사하고 싶어요 は願望、이사하면 돼요 は「引っ越せばよい」で、いずれも非意志的な結果を表さない。',
    ),
  },
  {
    ko: '-아/어지다',
    sentence: '봄이 되니까 날씨가 점점 {}.',
    answer: '따뜻해졌어요',
    distractors: ['따뜻했어요', '따뜻하게 했어요', '따뜻할 거예요'],
    trans: L(
      'Now that spring has come, the weather has gradually gotten warm.',
      'Como llegó la primavera, el tiempo se ha ido poniendo cálido poco a poco.',
      "Comme le printemps est arrivé, le temps s'est peu à peu radouci.",
      'Como chegou a primavera, o tempo foi ficando quente aos poucos.',
      'พอถึงฤดูใบไม้ผลิ อากาศก็ค่อย ๆ อุ่นขึ้น',
      'Karena musim semi tiba, cuacanya jadi hangat sedikit demi sedikit.',
      'Vì mùa xuân đã đến, thời tiết dần dần trở nên ấm áp.',
      '春になったので、天気がだんだん暖かくなりました。',
    ),
    why: L(
      '점점 (gradually) + an adjective = a change of state into warmth → -아/어지다 (따뜻해졌어요); 따뜻했어요 just states a past state (no change), 따뜻하게 했어요 is causative "made it warm", 따뜻할 거예요 is a future guess — none renders the gradual becoming.',
      '점점 (poco a poco) + adjetivo = cambio de estado hacia lo cálido → -아/어지다 (따뜻해졌어요); 따뜻했어요 solo enuncia un estado pasado (sin cambio), 따뜻하게 했어요 es causativo "lo puso cálido", 따뜻할 거예요 es conjetura futura — ninguno expresa el devenir gradual.',
      "점점 (peu à peu) + adjectif = changement d'état vers la chaleur → -아/어지다 (따뜻해졌어요) ; 따뜻했어요 énonce seulement un état passé (sans changement), 따뜻하게 했어요 est causatif « l'a rendu chaud », 따뜻할 거예요 est une conjecture future — aucun ne rend le devenir graduel.",
      '점점 (aos poucos) + adjetivo = mudança de estado para o quente → -아/어지다 (따뜻해졌어요); 따뜻했어요 apenas afirma um estado passado (sem mudança), 따뜻하게 했어요 é causativo "deixou quente", 따뜻할 거예요 é conjectura futura — nenhum expressa o tornar-se gradual.',
      '점점 (ค่อย ๆ) + คำคุณศัพท์ = การเปลี่ยนสภาพไปสู่ความอุ่น → -아/어지다 (따뜻해졌어요); 따뜻했어요 บอกแค่สภาพในอดีต (ไม่มีการเปลี่ยน), 따뜻하게 했어요 เป็นการก "ทำให้อุ่น", 따뜻할 거예요 เป็นการเดาอนาคต ล้วนไม่สื่อการค่อย ๆ กลายเป็น',
      '점점 (sedikit demi sedikit) + adjektiva = perubahan keadaan menjadi hangat → -아/어지다 (따뜻해졌어요); 따뜻했어요 hanya menyatakan keadaan lampau (tanpa perubahan), 따뜻하게 했어요 kausatif "membuatnya hangat", 따뜻할 거예요 dugaan masa depan — tak ada yang menyatakan proses menjadi.',
      '점점 (dần dần) + tính từ = sự đổi trạng thái sang ấm → -아/어지다 (따뜻해졌어요); 따뜻했어요 chỉ nêu trạng thái quá khứ (không đổi), 따뜻하게 했어요 là sai khiến "làm cho ấm", 따뜻할 거예요 là phỏng đoán tương lai — không cái nào diễn tả sự dần trở nên.',
      '점점（だんだん）＋形容詞は暖かさへの状態変化を示すので -아/어지다（따뜻해졌어요）。따뜻했어요 は過去の状態のみ（変化なし）、따뜻하게 했어요 は使役「暖かくした」、따뜻할 거예요 は未来の推量で、いずれも段階的な変化を表さない。',
    ),
  },
  {
    ko: '-아/어 있다',
    sentence: '교실에 들어가 보니 칠판에 이름이 {}.',
    answer: '쓰여 있었어요',
    distractors: ['쓰고 있었어요', '썼어요', '쓸 거예요'],
    trans: L(
      'When I went into the classroom, a name was written on the board.',
      'Cuando entré en el aula, había un nombre escrito en la pizarra.',
      "Quand je suis entré dans la salle, un nom était écrit au tableau.",
      'Quando entrei na sala, havia um nome escrito no quadro.',
      'พอเข้าไปในห้องเรียน ก็เห็นชื่อเขียนอยู่บนกระดาน',
      'Saat masuk ke kelas, ada nama yang tertulis di papan tulis.',
      'Khi vào lớp học, tôi thấy một cái tên được viết trên bảng.',
      '教室に入ってみると、黒板に名前が書いてありました。',
    ),
    why: L(
      'The name is a resultant state remaining after the act of writing → -아/어 있다 (쓰여 있었어요, passive stem); -고 있다 (쓰고 있었어요) is an action in progress (someone actively writing), 썼어요 just reports the act, 쓸 거예요 is future — only the resultant-state form describes what is on the board.',
      'El nombre es un estado resultante que permanece tras escribir → -아/어 있다 (쓰여 있었어요, raíz pasiva); -고 있다 (쓰고 있었어요) es acción en curso (alguien escribiendo), 썼어요 solo reporta el acto, 쓸 거예요 es futuro — solo la forma de estado resultante describe lo que hay en la pizarra.',
      "Le nom est un état résultant qui subsiste après l'écriture → -아/어 있다 (쓰여 있었어요, base passive) ; -고 있다 (쓰고 있었어요) est une action en cours (quelqu'un écrit), 썼어요 rapporte seulement l'acte, 쓸 거예요 est futur — seule la forme d'état résultant décrit ce qui est au tableau.",
      'O nome é um estado resultante que permanece após escrever → -아/어 있다 (쓰여 있었어요, radical passivo); -고 있다 (쓰고 있었어요) é ação em curso (alguém escrevendo), 썼어요 só relata o ato, 쓸 거예요 é futuro — só a forma de estado resultante descreve o que está no quadro.',
      'ชื่อคือสภาพคงค้างหลังจากการเขียนเสร็จ → -아/어 있다 (쓰여 있었어요, รากกริยาถูกกระทำ); -고 있다 (쓰고 있었어요) คือกำลังทำ (มีคนกำลังเขียน), 썼어요 บอกแค่การกระทำ, 쓸 거예요 เป็นอนาคต มีเพียงรูปสภาพคงค้างที่อธิบายสิ่งที่อยู่บนกระดาน',
      'Nama itu adalah keadaan hasil yang tersisa setelah ditulis → -아/어 있다 (쓰여 있었어요, akar pasif); -고 있다 (쓰고 있었어요) aksi berlangsung (sedang menulis), 썼어요 hanya melaporkan aksinya, 쓸 거예요 masa depan — hanya bentuk keadaan hasil yang menggambarkan apa yang ada di papan.',
      'Cái tên là trạng thái kết quả còn lại sau khi viết → -아/어 있다 (쓰여 있었어요, gốc bị động); -고 있다 (쓰고 있었어요) là hành động đang diễn ra (ai đó đang viết), 썼어요 chỉ thuật lại hành động, 쓸 거예요 là tương lai — chỉ dạng trạng thái kết quả mới mô tả thứ trên bảng.',
      '名前は書く行為の後に残る結果状態なので -아/어 있다（쓰여 있었어요、受動語幹）。-고 있다（쓰고 있었어요）は進行（誰かが書いている）、썼어요 は行為の報告、쓸 거예요 は未来で、黒板にある状態を表すのは結果状態の形だけ。',
    ),
  },
  {
    ko: '-기 때문에',
    sentence: '그날 길이 많이 {} 약속에 늦었어요.',
    answer: '막혔기 때문에',
    distractors: ['막히기 때문에', '막혀도', '막히려고'],
    trans: L(
      'Because the roads were very congested that day, I was late for the appointment.',
      'Porque ese día había mucho tráfico, llegué tarde a la cita.',
      "Parce que les routes étaient très embouteillées ce jour-là, j'étais en retard au rendez-vous.",
      'Porque naquele dia o trânsito estava muito congestionado, cheguei atrasado ao compromisso.',
      'เพราะวันนั้นรถติดมาก ฉันเลยไปสายตามนัด',
      'Karena hari itu jalanan sangat macet, saya terlambat ke janji temu.',
      'Vì hôm đó đường rất kẹt xe, tôi đã đến trễ cuộc hẹn.',
      'その日は道がとても混んでいたため、約束に遅れました。',
    ),
    why: L(
      'The result clause is past (늦었어요), so the realized past cause takes -기 때문에 on a past stem (막혔기 때문에); 막히기 때문에 leaves it present (not matching the past event), 막혀도 is concessive "even if blocked", 막히려고 is intention "in order to be blocked" — only the past-cause form fits.',
      'La cláusula de resultado es pasada (늦었어요), por eso la causa real pasada lleva -기 때문에 sobre raíz en pasado (막혔기 때문에); 막히기 때문에 la deja en presente (no concuerda con el hecho pasado), 막혀도 es concesivo "aunque se atasque", 막히려고 es intención "para atascarse" — solo la causa pasada encaja.',
      "La proposition de résultat est au passé (늦었어요), donc la cause réelle passée prend -기 때문에 sur une base au passé (막혔기 때문에) ; 막히기 때문에 la laisse au présent (incohérent avec le fait passé), 막혀도 est concessif « même bloqué », 막히려고 est l'intention « pour être bloqué » — seule la cause passée convient.",
      'A oração de resultado é passada (늦었어요), logo a causa real passada leva -기 때문에 sobre radical no passado (막혔기 때문에); 막히기 때문에 a deixa no presente (não combina com o fato passado), 막혀도 é concessivo "mesmo congestionado", 막히려고 é intenção "para congestionar" — só a causa passada cabe.',
      'ประโยคผลเป็นอดีต (늦었어요) เหตุจริงในอดีตจึงใช้ -기 때문에 บนรากอดีต (막혔기 때문에); 막히기 때문에 ทำให้เป็นปัจจุบัน (ไม่ตรงกับเหตุการณ์อดีต), 막혀도 เป็นการยอมแม้ "แม้รถจะติด", 막히려고 เป็นเจตนา "เพื่อให้รถติด" มีเพียงรูปเหตุอดีตที่เข้ากัน',
      'Klausa hasil berbentuk lampau (늦었어요), maka sebab nyata lampau memakai -기 때문에 pada akar lampau (막혔기 때문에); 막히기 때문에 membuatnya kini (tak cocok dengan kejadian lampau), 막혀도 konsesif "meski macet", 막히려고 niat "agar macet" — hanya bentuk sebab lampau yang cocok.',
      'Mệnh đề kết quả ở quá khứ (늦었어요) nên nguyên nhân thực ở quá khứ dùng -기 때문에 trên gốc quá khứ (막혔기 때문에); 막히기 때문에 để ở hiện tại (không khớp sự việc quá khứ), 막혀도 là nhượng bộ "dù kẹt xe", 막히려고 là ý định "để bị kẹt" — chỉ dạng nguyên nhân quá khứ là hợp.',
      '結果節が過去（늦었어요）なので、実現した過去の原因は過去語幹に -기 때문에（막혔기 때문에）。막히기 때문에 は現在のままで過去の出来事と合わず、막혀도 は譲歩「混んでも」、막히려고 は意図「混むために」で、過去の原因形だけが適合する。',
    ),
  },
  {
    ko: '-(으)면서',
    sentence: '동생은 항상 음악을 {} 숙제를 해요.',
    answer: '들으면서',
    distractors: ['들어서', '들으니까', '들으려고'],
    trans: L(
      'My younger sibling always does homework while listening to music.',
      'Mi hermano menor siempre hace los deberes mientras escucha música.',
      'Mon cadet fait toujours ses devoirs tout en écoutant de la musique.',
      'Meu irmão mais novo sempre faz a lição enquanto ouve música.',
      'น้องชอบทำการบ้านไปฟังเพลงไปเสมอ',
      'Adik saya selalu mengerjakan PR sambil mendengarkan musik.',
      'Em tôi luôn vừa nghe nhạc vừa làm bài tập.',
      '弟はいつも音楽を聞きながら宿題をします。',
    ),
    why: L(
      'One subject doing two simultaneous actions (listening + homework) → -(으)면서 (들으면서); -아/어서 would wrongly make listening the cause/sequence of doing homework, -(으)니까 marks reason, -(으)려고 marks purpose "in order to listen" — none gives simultaneity.',
      'Un sujeto con dos acciones simultáneas (escuchar + deberes) → -(으)면서 (들으면서); -아/어서 haría de escuchar la causa/secuencia de los deberes, -(으)니까 marca razón, -(으)려고 marca propósito "para escuchar" — ninguno da simultaneidad.',
      "Un seul sujet, deux actions simultanées (écouter + devoirs) → -(으)면서 (들으면서) ; -아/어서 ferait de l'écoute la cause/suite des devoirs, -(으)니까 marque la raison, -(으)려고 le but « pour écouter » — aucun ne donne la simultanéité.",
      'Um sujeito com duas ações simultâneas (ouvir + lição) → -(으)면서 (들으면서); -아/어서 faria de ouvir a causa/sequência da lição, -(으)니까 marca razão, -(으)려고 marca propósito "para ouvir" — nenhum dá simultaneidade.',
      'ประธานเดียวทำสองอย่างพร้อมกัน (ฟัง + ทำการบ้าน) → -(으)면서 (들으면서); -아/어서 จะทำให้การฟังเป็นเหตุ/ลำดับของการบ้าน, -(으)니까 บอกเหตุผล, -(으)려고 บอกจุดประสงค์ "เพื่อจะฟัง" ล้วนไม่ให้ความหมายพร้อมกัน',
      'Satu subjek dua aksi serentak (mendengar + PR) → -(으)면서 (들으면서); -아/어서 keliru menjadikan mendengar sebab/urutan PR, -(으)니까 menandai alasan, -(으)려고 menandai tujuan "untuk mendengar" — tak ada yang menyatakan keserentakan.',
      'Một chủ ngữ làm hai việc đồng thời (nghe + làm bài) → -(으)면서 (들으면서); -아/어서 biến việc nghe thành nguyên nhân/trình tự của làm bài, -(으)니까 đánh dấu lý do, -(으)려고 đánh dấu mục đích "để nghe" — không cái nào cho nghĩa đồng thời.',
      '一人の主語が同時に二つの動作（聞く＋宿題）をするので -(으)면서（들으면서）。-아/어서 は聞くことを宿題の原因・連続にしてしまい、-(으)니까 は理由、-(으)려고 は目的「聞くために」で、いずれも同時性を表さない。',
    ),
  },
  {
    ko: '-(으)ㄹ 수밖에 없다',
    sentence: '막차가 끊겨서 택시를 {}.',
    answer: '탈 수밖에 없었어요',
    distractors: ['탈 수 있었어요', '타면 안 됐어요', '타지 않았어요'],
    trans: L(
      'The last train had stopped running, so I had no choice but to take a taxi.',
      'El último tren ya no pasaba, así que no tuve más remedio que tomar un taxi.',
      "Le dernier train ne circulait plus, je n'ai donc eu d'autre choix que de prendre un taxi.",
      'O último trem já não passava, então não tive escolha senão pegar um táxi.',
      'รถไฟเที่ยวสุดท้ายหมดแล้ว เลยจำเป็นต้องนั่งแท็กซี่',
      'Kereta terakhir sudah berhenti, jadi terpaksa naik taksi.',
      'Chuyến tàu cuối đã hết nên tôi đành phải bắt taxi.',
      '終電がなくなったので、タクシーに乗るしかありませんでした。',
    ),
    why: L(
      '막차가 끊겨서 leaves only one forced option → -(으)ㄹ 수밖에 없다 (탈 수밖에 없었어요); 탈 수 있었어요 says merely "was able to take" (a free possibility, not forced), 타면 안 됐어요 = "must not take", 타지 않았어요 = "did not take" — only the no-choice form matches.',
      '막차가 끊겨서 deja una única opción forzada → -(으)ㄹ 수밖에 없다 (탈 수밖에 없었어요); 탈 수 있었어요 dice solo "se podía tomar" (posibilidad libre, no forzada), 타면 안 됐어요 = "no se debía tomar", 타지 않았어요 = "no tomó" — solo la forma de no haber más remedio encaja.',
      "막차가 끊겨서 ne laisse qu'une seule option contrainte → -(으)ㄹ 수밖에 없다 (탈 수밖에 없었어요) ; 탈 수 있었어요 dit seulement « pouvait prendre » (possibilité libre, non contrainte), 타면 안 됐어요 = « ne devait pas prendre », 타지 않았어요 = « n'a pas pris » — seule la forme « pas le choix » convient.",
      '막차가 끊겨서 deixa uma única opção forçada → -(으)ㄹ 수밖에 없다 (탈 수밖에 없었어요); 탈 수 있었어요 diz apenas "podia pegar" (possibilidade livre, não forçada), 타면 안 됐어요 = "não podia pegar", 타지 않았어요 = "não pegou" — só a forma de não ter escolha cabe.',
      '막차가 끊겨서 เหลือทางเลือกเดียวที่ถูกบังคับ → -(으)ㄹ 수밖에 없다 (탈 수밖에 없었어요); 탈 수 있었어요 บอกแค่ "ขึ้นได้" (ความเป็นไปได้อิสระ ไม่ถูกบังคับ), 타면 안 됐어요 = "ขึ้นไม่ได้", 타지 않았어요 = "ไม่ได้ขึ้น" มีเพียงรูป "ไม่มีทางเลือก" ที่เข้ากัน',
      '막차가 끊겨서 menyisakan satu pilihan terpaksa → -(으)ㄹ 수밖에 없다 (탈 수밖에 없었어요); 탈 수 있었어요 hanya berarti "bisa naik" (kemungkinan bebas, tak terpaksa), 타면 안 됐어요 = "tak boleh naik", 타지 않았어요 = "tidak naik" — hanya bentuk tak ada pilihan yang cocok.',
      '막차가 끊겨서 chỉ còn một lựa chọn bắt buộc → -(으)ㄹ 수밖에 없다 (탈 수밖에 없었어요); 탈 수 있었어요 chỉ nói "có thể đi" (khả năng tự do, không bắt buộc), 타면 안 됐어요 = "không được đi", 타지 않았어요 = "đã không đi" — chỉ dạng không còn cách nào là hợp.',
      '막차가 끊겨서 は強いられた唯一の選択肢を残すので -(으)ㄹ 수밖에 없다（탈 수밖에 없었어요）。탈 수 있었어요 は「乗れた」という自由な可能性で強制ではなく、타면 안 됐어요 は「乗ってはいけなかった」、타지 않았어요 は「乗らなかった」で、選択の余地がない形だけが合う。',
    ),
  },
  {
    ko: '-기 위해(서) / -을/를 위해(서)',
    sentence: '시험에 {} 매일 밤늦게까지 공부했어요.',
    answer: '합격하기 위해서',
    distractors: ['합격하기 때문에', '합격하는데', '합격하자마자'],
    trans: L(
      'In order to pass the exam, I studied late into the night every day.',
      'Para aprobar el examen, estudié hasta altas horas de la noche todos los días.',
      "Pour réussir l'examen, j'ai étudié tard dans la nuit chaque jour.",
      'Para passar na prova, estudei até tarde da noite todos os dias.',
      'เพื่อสอบผ่าน ฉันเลยอ่านหนังสือจนดึกทุกวัน',
      'Untuk lulus ujian, saya belajar sampai larut malam setiap hari.',
      'Để đỗ kỳ thi, mỗi ngày tôi học đến tận khuya.',
      '試験に合格するために、毎日夜遅くまで勉強しました。',
    ),
    why: L(
      'Studying is goal-directed toward passing → purpose -기 위해(서) (합격하기 위해서); -기 때문에 marks a cause (passing did not cause the studying), -는데 is a background/contrast connective, -자마자 means "as soon as one passes" — only the purpose form fits the intent.',
      'Estudiar está orientado a aprobar → propósito -기 위해(서) (합격하기 위해서); -기 때문에 marca causa (aprobar no causó el estudio), -는데 es conector de fondo/contraste, -자마자 significa "en cuanto se aprueba" — solo la forma de propósito encaja con la intención.',
      "Étudier vise la réussite → but -기 위해(서) (합격하기 위해서) ; -기 때문에 marque une cause (réussir n'a pas causé l'étude), -는데 est un connecteur de fond/contraste, -자마자 signifie « dès qu'on réussit » — seule la forme de but correspond à l'intention.",
      'Estudar é orientado a passar → propósito -기 위해(서) (합격하기 위해서); -기 때문에 marca causa (passar não causou o estudo), -는데 é conector de fundo/contraste, -자마자 significa "assim que passa" — só a forma de propósito combina com a intenção.',
      'การอ่านหนังสือมุ่งสู่การสอบผ่าน → จุดประสงค์ -기 위해(서) (합격하기 위해서); -기 때문에 บอกเหตุ (การสอบผ่านไม่ได้เป็นเหตุของการอ่าน), -는데 เป็นตัวเชื่อมปูพื้น/ขัดแย้ง, -자마자 แปลว่า "ทันทีที่สอบผ่าน" มีเพียงรูปจุดประสงค์ที่เข้ากับเจตนา',
      'Belajar diarahkan untuk lulus → tujuan -기 위해(서) (합격하기 위해서); -기 때문에 menandai sebab (lulus bukan penyebab belajar), -는데 konektor latar/kontras, -자마자 berarti "begitu lulus" — hanya bentuk tujuan yang cocok dengan niat.',
      'Việc học hướng tới việc đỗ → mục đích -기 위해(서) (합격하기 위해서); -기 때문에 đánh dấu nguyên nhân (đỗ không gây ra việc học), -는데 là liên từ nền/tương phản, -자마자 nghĩa là "ngay khi đỗ" — chỉ dạng mục đích hợp với ý định.',
      '勉強は合格を目指す行為なので目的の -기 위해(서)（합격하기 위해서）。-기 때문에 は原因（合格が勉強の原因ではない）、-는데 は背景・対比の接続、-자마자 は「合格するやいなや」で、意図に合うのは目的形だけ。',
    ),
  },
  {
    ko: '에 따라(서)',
    sentence: '사람마다 성격이 다르니까 상황{} 대처 방법도 달라져요.',
    answer: '에 따라서',
    distractors: ['에 비해서', '에 대해서', '을 위해서'],
    trans: L(
      "Since everyone's personality differs, the way to cope also changes depending on the situation.",
      'Como cada persona tiene un carácter distinto, la forma de afrontarlo también cambia según la situación.',
      "Comme chacun a un caractère différent, la façon de réagir change aussi selon la situation.",
      'Como cada pessoa tem um temperamento diferente, a forma de lidar também muda conforme a situação.',
      'เพราะแต่ละคนนิสัยต่างกัน วิธีรับมือก็เปลี่ยนไปตามสถานการณ์',
      'Karena setiap orang berbeda kepribadian, cara menghadapinya pun berubah tergantung situasi.',
      'Vì mỗi người tính cách khác nhau nên cách ứng phó cũng thay đổi tùy theo tình huống.',
      '人それぞれ性格が違うので、対処の仕方も状況によって変わります。',
    ),
    why: L(
      '달라져요 (it varies) signals dependence/variation on the situation → 에 따라(서) (에 따라서); 에 비해(서) is "compared to", 에 대해(서) is "about/regarding", 을 위해(서) is "for the sake of" — only the variation marker yields "changes depending on".',
      '달라져요 (varía) indica dependencia/variación según la situación → 에 따라(서) (에 따라서); 에 비해(서) es "en comparación con", 에 대해(서) es "acerca de", 을 위해(서) es "para" — solo el marcador de variación da "cambia según".',
      "달라져요 (cela varie) indique la dépendance/variation selon la situation → 에 따라(서) (에 따라서) ; 에 비해(서) = « par rapport à », 에 대해(서) = « au sujet de », 을 위해(서) = « pour » — seul le marqueur de variation donne « change selon ».",
      '달라져요 (varia) indica dependência/variação conforme a situação → 에 따라(서) (에 따라서); 에 비해(서) é "em comparação com", 에 대해(서) é "sobre", 을 위해(서) é "para" — só o marcador de variação dá "muda conforme".',
      '달라져요 (เปลี่ยนไป) บ่งการขึ้นอยู่กับ/แปรผันตามสถานการณ์ → 에 따라(서) (에 따라서); 에 비해(서) คือ "เมื่อเทียบกับ", 에 대해(서) คือ "เกี่ยวกับ", 을 위해(서) คือ "เพื่อ" มีเพียงตัวบ่งการแปรผันที่ให้ความหมาย "เปลี่ยนตาม"',
      '달라져요 (berubah) menandakan ketergantungan/variasi pada situasi → 에 따라(서) (에 따라서); 에 비해(서) "dibandingkan", 에 대해(서) "tentang", 을 위해(서) "untuk" — hanya penanda variasi yang menghasilkan "berubah tergantung".',
      '달라져요 (thay đổi) báo hiệu sự phụ thuộc/biến đổi theo tình huống → 에 따라(서) (에 따라서); 에 비해(서) là "so với", 에 대해(서) là "về", 을 위해(서) là "vì/để" — chỉ dấu hiệu biến đổi mới cho nghĩa "thay đổi tùy theo".',
      '달라져요（変わる）は状況による依存・変動を示すので 에 따라(서)（에 따라서）。에 비해(서) は「〜に比べて」、에 대해(서) は「〜について」、을 위해(서) は「〜のために」で、「〜によって変わる」を表すのは変動の標識だけ。',
    ),
  },
  {
    ko: '-(으)ㄹ 것 같다',
    sentence: '하늘이 어두운 걸 보니 곧 비가 {}.',
    answer: '올 것 같아요',
    distractors: ['왔을 것 같아요', '오는 것 같아요', '왔어요'],
    trans: L(
      'Judging by how dark the sky is, it looks like it will rain soon.',
      'Por lo oscuro que está el cielo, parece que pronto va a llover.',
      "Vu comme le ciel est sombre, on dirait qu'il va bientôt pleuvoir.",
      'Pelo céu escuro, parece que vai chover em breve.',
      'ดูจากท้องฟ้าที่มืดครึ้ม เดี๋ยวฝนน่าจะตก',
      'Melihat langit yang gelap, sepertinya sebentar lagi akan hujan.',
      'Nhìn bầu trời tối thế kia, có vẻ sắp mưa rồi.',
      '空が暗いのを見ると、もうすぐ雨が降りそうです。',
    ),
    why: L(
      '곧 (soon) makes this a conjecture about a future event → -(으)ㄹ 것 같다 (올 것 같아요); 왔을 것 같아요 guesses about the past ("it probably rained"), 오는 것 같아요 guesses about now ("it seems to be raining"), 왔어요 flatly asserts past rain — only the future-conjecture form fits 곧.',
      '곧 (pronto) lo convierte en conjetura sobre un evento futuro → -(으)ㄹ 것 같다 (올 것 같아요); 왔을 것 같아요 conjetura sobre el pasado ("habrá llovido"), 오는 것 같아요 sobre el presente ("parece que llueve"), 왔어요 afirma lluvia pasada — solo la conjetura futura encaja con 곧.',
      "곧 (bientôt) en fait une conjecture sur un fait futur → -(으)ㄹ 것 같다 (올 것 같아요) ; 왔을 것 같아요 suppose le passé (« il a dû pleuvoir »), 오는 것 같아요 le présent (« on dirait qu'il pleut »), 왔어요 affirme la pluie passée — seule la conjecture future convient à 곧.",
      '곧 (em breve) torna isto conjectura sobre evento futuro → -(으)ㄹ 것 같다 (올 것 같아요); 왔을 것 같아요 supõe o passado ("deve ter chovido"), 오는 것 같아요 o presente ("parece que está chovendo"), 왔어요 afirma chuva passada — só a conjectura futura combina com 곧.',
      '곧 (เดี๋ยว/ในไม่ช้า) ทำให้เป็นการเดาเหตุการณ์อนาคต → -(으)ㄹ 것 같다 (올 것 같아요); 왔을 것 같아요 เดาอดีต ("คงตกไปแล้ว"), 오는 것 같아요 เดาปัจจุบัน ("เหมือนกำลังตก"), 왔어요 ยืนยันว่าฝนตกไปแล้ว มีเพียงการเดาอนาคตที่เข้ากับ 곧',
      '곧 (sebentar lagi) menjadikannya dugaan tentang kejadian masa depan → -(으)ㄹ 것 같다 (올 것 같아요); 왔을 것 같아요 menduga masa lalu ("mungkin sudah hujan"), 오는 것 같아요 masa kini ("sepertinya sedang hujan"), 왔어요 menyatakan hujan lampau — hanya dugaan masa depan yang cocok dengan 곧.',
      '곧 (sắp) khiến đây là phỏng đoán về sự việc tương lai → -(으)ㄹ 것 같다 (올 것 같아요); 왔을 것 같아요 đoán quá khứ ("chắc đã mưa"), 오는 것 같아요 đoán hiện tại ("hình như đang mưa"), 왔어요 khẳng định đã mưa — chỉ phỏng đoán tương lai hợp với 곧.',
      '곧（もうすぐ）は未来の出来事への推量にするので -(으)ㄹ 것 같다（올 것 같아요）。왔을 것 같아요 は過去の推量「降ったようだ」、오는 것 같아요 は現在「降っているようだ」、왔어요 は過去の断定で、곧 に合うのは未来推量の形だけ。',
    ),
  },
  {
    ko: '-(으)면 좋겠다',
    sentence: '이번 휴가 때 비가 안 오고 날씨가 {}.',
    answer: '맑으면 좋겠어요',
    distractors: ['맑아서 좋아요', '맑으니까 좋아요', '맑으려고 해요'],
    trans: L(
      'I hope the weather will be clear, with no rain, during this vacation.',
      'Ojalá durante estas vacaciones no llueva y el tiempo esté despejado.',
      "J'aimerais bien que, pendant ces vacances, il ne pleuve pas et que le temps soit clair.",
      'Tomara que nestas férias não chova e o tempo fique limpo.',
      'อยากให้วันหยุดนี้ฝนไม่ตกแล้วอากาศแจ่มใส',
      'Semoga selama liburan ini tidak hujan dan cuacanya cerah.',
      'Mong sao kỳ nghỉ này trời không mưa và thời tiết quang đãng.',
      '今度の休暇は雨が降らずに天気が晴れたらいいです。',
    ),
    why: L(
      'A wish about an uncontrollable situation → -(으)면 좋겠다 (맑으면 좋겠어요); 맑아서 좋아요 ("it is clear, so it is good") and 맑으니까 좋아요 ("since it is clear, it is good") both presuppose it is already clear, 맑으려고 해요 means "is about to clear" — only the wish form expresses the unrealized hope.',
      'Un deseo sobre una situación incontrolable → -(으)면 좋겠다 (맑으면 좋겠어요); 맑아서 좋아요 ("está despejado, así que es bueno") y 맑으니까 좋아요 ("como está despejado, es bueno") presuponen que ya está despejado, 맑으려고 해요 = "está por despejarse" — solo la forma de deseo expresa la esperanza no realizada.',
      "Un souhait sur une situation incontrôlable → -(으)면 좋겠다 (맑으면 좋겠어요) ; 맑아서 좋아요 (« c'est clair, donc bien ») et 맑으니까 좋아요 (« comme c'est clair, c'est bien ») présupposent que c'est déjà clair, 맑으려고 해요 = « est sur le point de s'éclaircir » — seule la forme de souhait exprime l'espoir non réalisé.",
      'Um desejo sobre uma situação incontrolável → -(으)면 좋겠다 (맑으면 좋겠어요); 맑아서 좋아요 ("está limpo, então é bom") e 맑으니까 좋아요 ("como está limpo, é bom") pressupõem que já está limpo, 맑으려고 해요 = "está prestes a clarear" — só a forma de desejo expressa a esperança não realizada.',
      'ความปรารถนาต่อสถานการณ์ที่ควบคุมไม่ได้ → -(으)면 좋겠다 (맑으면 좋겠어요); 맑아서 좋아요 ("อากาศแจ่มใส เลยดี") และ 맑으니까 좋아요 ("เพราะแจ่มใส เลยดี") สันนิษฐานว่าแจ่มใสอยู่แล้ว, 맑으려고 해요 = "กำลังจะแจ่มใส" มีเพียงรูปปรารถนาที่สื่อความหวังที่ยังไม่เป็นจริง',
      'Harapan atas situasi yang tak terkendali → -(으)면 좋겠다 (맑으면 좋겠어요); 맑아서 좋아요 ("cerah, jadi bagus") dan 맑으니까 좋아요 ("karena cerah, bagus") mengandaikan sudah cerah, 맑으려고 해요 = "akan segera cerah" — hanya bentuk harapan yang menyatakan harapan belum terwujud.',
      'Mong muốn về một tình huống không kiểm soát được → -(으)면 좋겠다 (맑으면 좋겠어요); 맑아서 좋아요 ("trời quang nên tốt") và 맑으니까 좋아요 ("vì quang nên tốt") đều mặc định trời đã quang, 맑으려고 해요 = "sắp quang" — chỉ dạng mong muốn diễn tả hy vọng chưa thành.',
      'コントロールできない状況への願望なので -(으)면 좋겠다（맑으면 좋겠어요）。맑아서 좋아요「晴れているからよい」と 맑으니까 좋아요「晴れているのでよい」は既に晴れている前提、맑으려고 해요 は「晴れそうとしている」で、未実現の願いを表すのは願望形だけ。',
    ),
  },
  {
    ko: '-기로 하다',
    sentence: '친구들하고 다음 주에 같이 등산을 {}.',
    answer: '가기로 했어요',
    distractors: ['가게 됐어요', '가는 편이에요', '가 버렸어요'],
    trans: L(
      'My friends and I decided to go hiking together next week.',
      'Mis amigos y yo quedamos en ir juntos de excursión a la montaña la semana que viene.',
      "Mes amis et moi avons convenu d'aller faire de la randonnée ensemble la semaine prochaine.",
      'Eu e meus amigos combinamos de ir fazer trilha juntos na semana que vem.',
      'ฉันกับเพื่อน ๆ ตกลงกันว่าจะไปปีนเขาด้วยกันสัปดาห์หน้า',
      'Saya dan teman-teman sepakat pergi mendaki bersama minggu depan.',
      'Tôi và bạn bè đã hẹn nhau tuần sau cùng đi leo núi.',
      '友達と来週一緒に登山に行くことにしました。',
    ),
    why: L(
      'A mutual plan agreed among friends → -기로 하다 (가기로 했어요); -게 되다 (가게 됐어요) would mean circumstances forced the trip (not a chosen agreement), -는 편이다 (가는 편이에요) states a habitual tendency, -아/어 버리다 (가 버렸어요) means "already went and it is done" — only the decision form fits a future agreement.',
      'Un plan acordado entre amigos → -기로 하다 (가기로 했어요); -게 되다 (가게 됐어요) implicaría que las circunstancias forzaron el viaje (no un acuerdo elegido), -는 편이다 (가는 편이에요) enuncia una tendencia habitual, -아/어 버리다 (가 버렸어요) = "ya fue y está hecho" — solo la forma de decisión encaja con un acuerdo futuro.',
      "Un projet convenu entre amis → -기로 하다 (가기로 했어요) ; -게 되다 (가게 됐어요) signifierait que les circonstances ont imposé la sortie (non un accord choisi), -는 편이다 (가는 편이에요) énonce une tendance, -아/어 버리다 (가 버렸어요) = « est déjà parti, c'est fait » — seule la forme de décision convient à un accord futur.",
      'Um plano combinado entre amigos → -기로 하다 (가기로 했어요); -게 되다 (가게 됐어요) significaria que as circunstâncias forçaram o passeio (não um acordo escolhido), -는 편이다 (가는 편이에요) enuncia tendência habitual, -아/어 버리다 (가 버렸어요) = "já foi e acabou" — só a forma de decisão cabe num acordo futuro.',
      'แผนที่ตกลงกันในหมู่เพื่อน → -기로 하다 (가기로 했어요); -게 되다 (가게 됐어요) จะหมายถึงสถานการณ์บังคับให้ไป (ไม่ใช่ข้อตกลงที่เลือกเอง), -는 편이다 (가는 편이에요) บอกแนวโน้มเป็นนิสัย, -아/어 버리다 (가 버렸어요) = "ไปแล้วเสร็จเรียบร้อย" มีเพียงรูปการตัดสินใจที่เข้ากับข้อตกลงอนาคต',
      'Rencana yang disepakati antar teman → -기로 하다 (가기로 했어요); -게 되다 (가게 됐어요) berarti keadaan memaksa perjalanan (bukan kesepakatan pilihan), -는 편이다 (가는 편이에요) menyatakan kecenderungan, -아/어 버리다 (가 버렸어요) = "sudah terlanjur pergi" — hanya bentuk keputusan yang cocok untuk kesepakatan masa depan.',
      'Một kế hoạch được bạn bè thỏa thuận → -기로 하다 (가기로 했어요); -게 되다 (가게 됐어요) nghĩa là hoàn cảnh ép phải đi (không phải thỏa thuận tự chọn), -는 편이다 (가는 편이에요) nêu xu hướng, -아/어 버리다 (가 버렸어요) = "đã đi mất rồi" — chỉ dạng quyết định hợp với thỏa thuận tương lai.',
      '友達同士で決めた予定なので -기로 하다（가기로 했어요）。-게 되다（가게 됐어요）は状況に強いられた意味で選んだ約束ではなく、-는 편이다（가는 편이에요）は傾向、-아/어 버리다（가 버렸어요）は「もう行ってしまった」で、未来の約束に合うのは決定の形だけ。',
    ),
  },
  {
    ko: '-자마자',
    sentence: '너무 피곤해서 침대에 {} 잠이 들었어요.',
    answer: '눕자마자',
    distractors: ['누우면서', '누우니까', '누우려고'],
    trans: L(
      'I was so tired that I fell asleep the moment I lay down on the bed.',
      'Estaba tan cansado que me dormí en cuanto me acosté en la cama.',
      "J'étais si fatigué que je me suis endormi dès que je me suis allongé sur le lit.",
      'Eu estava tão cansado que adormeci assim que me deitei na cama.',
      'เหนื่อยมากจนพอล้มตัวลงบนเตียงก็หลับไปเลย',
      'Saya sangat lelah sampai langsung tertidur begitu berbaring di kasur.',
      'Tôi mệt đến mức vừa nằm xuống giường là ngủ ngay.',
      'とても疲れていて、ベッドに横になるやいなや眠ってしまいました。',
    ),
    why: L(
      'Falling asleep happens instantly right after lying down → -자마자 (눕자마자); -(으)면서 would mean falling asleep simultaneously while lying (the verbs are not concurrent), -(으)니까 gives reason "because I lay down", -(으)려고 ("in order to lie down") wrongly makes lying down the goal of falling asleep — only -자마자 captures the instant sequence.',
      'Quedarse dormido ocurre justo al acostarse → -자마자 (눕자마자); -(으)면서 implicaría dormirse a la vez que se acuesta (no son simultáneos), -(으)니까 da razón "porque me acosté", -(으)려고 ("para acostarme") hace de acostarse el propósito de dormirse (ilógico) — solo -자마자 capta la secuencia instantánea.',
      "S'endormir survient juste après s'allonger → -자마자 (눕자마자) ; -(으)면서 voudrait dire s'endormir en même temps qu'on s'allonge (non simultanés), -(으)니까 donne la raison « parce que je me suis allongé », -(으)려고 (« pour m'allonger ») fait de l'action de s'allonger le but de l'endormissement (illogique) — seul -자마자 rend la séquence instantanée.",
      'Adormecer acontece logo após se deitar → -자마자 (눕자마자); -(으)면서 significaria adormecer ao mesmo tempo em que se deita (não simultâneos), -(으)니까 dá razão "porque me deitei", -(으)려고 ("para me deitar") faz do deitar o propósito de adormecer (ilógico) — só -자마자 capta a sequência instantânea.',
      'การหลับเกิดขึ้นทันทีหลังล้มตัวลงนอน → -자마자 (눕자마자); -(으)면서 จะหมายถึงหลับพร้อมกับการนอนลง (ไม่ใช่พร้อมกัน), -(으)니까 ให้เหตุผล "เพราะนอนลง", -(으)려고 ("เพื่อจะนอนลง") ทำให้การนอนลงเป็นจุดประสงค์ของการหลับ (ไม่สมเหตุผล) มีเพียง -자마자 ที่จับลำดับฉับพลันได้',
      'Tertidur terjadi langsung setelah berbaring → -자마자 (눕자마자); -(으)면서 berarti tertidur bersamaan dengan berbaring (tak serentak), -(으)니까 memberi alasan "karena berbaring", -(으)려고 ("agar berbaring") menjadikan berbaring tujuan dari tertidur (tak logis) — hanya -자마자 yang menangkap urutan seketika.',
      'Việc ngủ thiếp xảy ra ngay sau khi nằm xuống → -자마자 (눕자마자); -(으)면서 nghĩa là ngủ đồng thời lúc nằm (không đồng thời), -(으)니까 cho lý do "vì đã nằm", -(으)려고 ("để nằm xuống") biến việc nằm thành mục đích của việc ngủ (phi lý) — chỉ -자마자 nắm bắt trình tự tức khắc.',
      '眠りは横になった直後に起こるので -자마자（눕자마자）。-(으)면서 は横になると同時に眠る意味（同時ではない）、-(으)니까 は理由「横になったから」、-(으)려고（横になるために）は横になることを眠る目的にしてしまい不自然。瞬間の連続を表すのは -자마자 だけ。',
    ),
  },
  {
    ko: '-아/어도',
    sentence: '아무리 바{} 아침은 꼭 챙겨 먹어요.',
    answer: '빠도',
    distractors: ['빠서', '쁘니까', '쁘면'],
    trans: L(
      'No matter how busy I am, I always make sure to eat breakfast.',
      'Por muy ocupado que esté, siempre me aseguro de desayunar.',
      "Aussi occupé que je sois, je prends toujours soin de déjeuner le matin.",
      'Por mais ocupado que eu esteja, sempre faço questão de tomar café da manhã.',
      'ไม่ว่าจะยุ่งแค่ไหน ฉันก็กินมื้อเช้าให้ได้เสมอ',
      'Sesibuk apa pun, saya selalu menyempatkan sarapan.',
      'Dù bận đến mấy, tôi luôn cố gắng ăn sáng đầy đủ.',
      'どんなに忙しくても、朝ご飯は必ず食べます。',
    ),
    why: L(
      '아무리 (no matter how) demands the concessive -아/어도 (바빠도); -아/어서 (바빠서) makes busyness the cause of eating (illogical with 아무리), -(으)니까 (바쁘니까) gives reason, -(으)면 (바쁘면) sets a condition "if busy" — only -아/어도 pairs with 아무리.',
      '아무리 (por mucho que) exige el concesivo -아/어도 (바빠도); -아/어서 (바빠서) hace de lo ocupado la causa de comer (ilógico con 아무리), -(으)니까 (바쁘니까) da razón, -(으)면 (바쁘면) pone condición "si está ocupado" — solo -아/어도 acompaña a 아무리.',
      "아무리 (aussi… que) exige le concessif -아/어도 (바빠도) ; -아/어서 (바빠서) fait de l'activité la cause du repas (illogique avec 아무리), -(으)니까 (바쁘니까) donne la raison, -(으)면 (바쁘면) pose une condition « si occupé » — seul -아/어도 va avec 아무리.",
      '아무리 (por mais que) exige o concessivo -아/어도 (바빠도); -아/어서 (바빠서) faz da ocupação a causa de comer (ilógico com 아무리), -(으)니까 (바쁘니까) dá razão, -(으)면 (바쁘면) põe condição "se ocupado" — só -아/어도 acompanha 아무리.',
      '아무리 (ไม่ว่าจะ...แค่ไหน) ต้องใช้รูปยอมตาม -아/어도 (바빠도); -아/어서 (바빠서) ทำให้ความยุ่งเป็นเหตุของการกิน (ไม่สมเหตุผลกับ 아무리), -(으)니까 (바쁘니까) ให้เหตุผล, -(으)면 (바쁘면) วางเงื่อนไข "ถ้ายุ่ง" มีเพียง -아/어도 ที่คู่กับ 아무리',
      '아무리 (sebagaimanapun) menuntut bentuk konsesif -아/어도 (바빠도); -아/어서 (바빠서) menjadikan kesibukan sebab makan (tak logis dengan 아무리), -(으)니까 (바쁘니까) memberi alasan, -(으)면 (바쁘면) memberi syarat "jika sibuk" — hanya -아/어도 yang berpasangan dengan 아무리.',
      '아무리 (dù… đến mấy) đòi dạng nhượng bộ -아/어도 (바빠도); -아/어서 (바빠서) biến cái bận thành nguyên nhân ăn (phi lý với 아무리), -(으)니까 (바쁘니까) cho lý do, -(으)면 (바쁘면) đặt điều kiện "nếu bận" — chỉ -아/어도 đi cùng 아무리.',
      '아무리（どんなに〜ても）は譲歩の -아/어도（바빠도）を要求する。-아/어서（바빠서）は忙しさを食べる原因にし（아무리 と矛盾）、-(으)니까（바쁘니까）は理由、-(으)면（바쁘면）は条件「忙しければ」で、아무리 と組むのは -아/어도 だけ。',
    ),
  },
  {
    ko: '-(으)ㄴ/는데도',
    sentence: '약을 {} 열이 전혀 안 내려요.',
    answer: '먹었는데도',
    distractors: ['먹어서', '먹으니까', '먹으려고'],
    trans: L(
      'Even though I took the medicine, the fever does not go down at all.',
      'A pesar de que tomé la medicina, la fiebre no baja en absoluto.',
      "Bien que j'aie pris le médicament, la fièvre ne baisse pas du tout.",
      'Mesmo tendo tomado o remédio, a febre não baixa nada.',
      'ทั้งที่กินยาแล้ว แต่ไข้ก็ไม่ลดลงเลย',
      'Padahal sudah minum obat, demamnya sama sekali tidak turun.',
      'Mặc dù đã uống thuốc rồi mà cơn sốt vẫn không hạ chút nào.',
      '薬を飲んだのに、熱が全然下がりません。',
    ),
    why: L(
      'Taking medicine should lower a fever, yet it does not — an unexpected outcome → -(으)ㄴ/는데도 (먹었는데도); -아/어서 (먹어서) would make medicine the cause of the unbroken fever (contradictory), -(으)니까 (먹으니까) gives a plain reason, -(으)려고 (먹으려고) is purpose — only the concessive captures the contradiction.',
      'Tomar medicina debería bajar la fiebre, pero no lo hace — resultado inesperado → -(으)ㄴ/는데도 (먹었는데도); -아/어서 (먹어서) haría de la medicina la causa de la fiebre persistente (contradictorio), -(으)니까 (먹으니까) da una razón simple, -(으)려고 (먹으려고) es propósito — solo el concesivo capta la contradicción.',
      "Le médicament devrait faire baisser la fièvre, mais non — résultat inattendu → -(으)ㄴ/는데도 (먹었는데도) ; -아/어서 (먹어서) ferait du médicament la cause de la fièvre persistante (contradictoire), -(으)니까 (먹으니까) donne une raison simple, -(으)려고 (먹으려고) est un but — seul le concessif rend la contradiction.",
      'Tomar o remédio deveria baixar a febre, mas não baixa — resultado inesperado → -(으)ㄴ/는데도 (먹었는데도); -아/어서 (먹어서) faria do remédio a causa da febre persistente (contraditório), -(으)니까 (먹으니까) dá uma razão simples, -(으)려고 (먹으려고) é propósito — só o concessivo capta a contradição.',
      'การกินยาควรทำให้ไข้ลด แต่กลับไม่ลด — ผลที่ไม่คาดคิด → -(으)ㄴ/는데도 (먹었는데도); -아/어서 (먹어서) จะทำให้ยาเป็นเหตุของไข้ที่ไม่ลด (ขัดแย้ง), -(으)니까 (먹으니까) ให้เหตุผลธรรมดา, -(으)려고 (먹으려고) เป็นจุดประสงค์ มีเพียงรูปยอมตามที่จับความขัดแย้งได้',
      'Minum obat seharusnya menurunkan demam, tapi tidak — hasil tak terduga → -(으)ㄴ/는데도 (먹었는데도); -아/어서 (먹어서) menjadikan obat sebab demam yang menetap (kontradiktif), -(으)니까 (먹으니까) memberi alasan biasa, -(으)려고 (먹으려고) tujuan — hanya bentuk konsesif yang menangkap kontradiksi.',
      'Uống thuốc lẽ ra phải hạ sốt nhưng lại không — kết quả bất ngờ → -(으)ㄴ/는데도 (먹었는데도); -아/어서 (먹어서) biến thuốc thành nguyên nhân của cơn sốt dai dẳng (mâu thuẫn), -(으)니까 (먹으니까) cho lý do thường, -(으)려고 (먹으려고) là mục đích — chỉ dạng nhượng bộ nắm bắt được mâu thuẫn.',
      '薬を飲めば熱は下がるはずなのに下がらない、という意外な結果なので -(으)ㄴ/는데도（먹었는데도）。-아/어서（먹어서）は薬を下がらない熱の原因にしてしまい矛盾、-(으)니까（먹으니까）は単なる理由、-(으)려고（먹으려고）は目的で、矛盾を表すのは譲歩形だけ。',
    ),
  },
]
