// app/seed/cloze/n4.ts
import type { ClozeItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-4 grammar-pattern cloze items (choose the pattern that fits the blank).
 * ko matches grammars-n4.ts verbatim. Drafted + Korean-lens adversarially verified
 * (single-correct-answer crux). Korean wife native review = documented final gate.
 */

export const N4_CLOZE: ClozeItem[] = [
  {
    ko: '-다고 하다',
    sentence: '친구가 내일은 시간이 {} 했어요.',
    answer: '없다고',
    distractors: ['없으라고', '없냐고', '없자고'],
    trans: L(
      'My friend said they have no time tomorrow.',
      'Mi amigo dijo que mañana no tiene tiempo.',
      "Mon ami a dit qu'il n'a pas de temps demain.",
      'Meu amigo disse que amanhã não tem tempo.',
      'เพื่อนบอกว่าพรุ่งนี้ไม่มีเวลา',
      'Teman saya bilang besok tidak ada waktu.',
      'Bạn tôi nói ngày mai không có thời gian.',
      '友達は明日は時間がないと言いました。',
    ),
    why: L(
      'Reporting a statement (a fact) takes -다고 하다; -(으)라고 is for commands, -냐고 for questions, -자고 for suggestions — none reports a plain statement.',
      'Reportar una afirmación (un hecho) usa -다고 하다; -(으)라고 es mandato, -냐고 pregunta, -자고 propuesta — ninguno reporta una afirmación.',
      "Rapporter une affirmation (un fait) prend -다고 하다 ; -(으)라고 sert à l'ordre, -냐고 à la question, -자고 à la proposition — aucun ne rapporte une affirmation.",
      'Relatar uma afirmação (um fato) usa -다고 하다; -(으)라고 é ordem, -냐고 pergunta, -자고 sugestão — nenhum relata uma afirmação.',
      'การรายงานประโยคบอกเล่า (ข้อเท็จจริง) ใช้ -다고 하다; -(으)라고 คือคำสั่ง, -냐고 คำถาม, -자고 คำชวน ไม่มีอันใดรายงานบอกเล่าได้',
      'Melaporkan pernyataan (fakta) memakai -다고 하다; -(으)라고 untuk perintah, -냐고 untuk tanya, -자고 untuk ajakan — tak ada yang melaporkan pernyataan.',
      'Tường thuật một câu trần thuật (sự việc) dùng -다고 하다; -(으)라고 là mệnh lệnh, -냐고 là câu hỏi, -자고 là lời rủ — không cái nào tường thuật câu trần thuật.',
      '平叙文（事実）の伝達は -다고 하다。-(으)라고 は命令、-냐고 は疑問、-자고 は勧誘で、平叙の伝達にならない。',
    ),
  },
  {
    ko: '-(으)라고 하다',
    sentence: '의사 선생님이 약을 식사 후에 {} 했어요.',
    answer: '먹으라고',
    distractors: ['먹는다고', '먹냐고', '먹자고'],
    trans: L(
      'The doctor told me to take the medicine after meals.',
      'El médico me dijo que tomara la medicina después de comer.',
      'Le médecin m’a dit de prendre le médicament après les repas.',
      'O médico me disse para tomar o remédio depois das refeições.',
      'คุณหมอบอกให้กินยาหลังอาหาร',
      'Dokter menyuruh saya minum obat setelah makan.',
      'Bác sĩ bảo tôi uống thuốc sau bữa ăn.',
      '医者は食後に薬を飲むようにと言いました。',
    ),
    why: L(
      'A relayed instruction (take it after meals) needs the indirect command -(으)라고 하다; -ㄴ/는다고 reports a statement, -냐고 a question, -자고 a joint suggestion — none conveys an order.',
      'Una instrucción transmitida (tómalo tras comer) exige el mandato indirecto -(으)라고 하다; -ㄴ/는다고 reporta afirmación, -냐고 pregunta, -자고 propuesta conjunta — ninguno transmite una orden.',
      "Une consigne transmise (à prendre après les repas) exige l'ordre indirect -(으)라고 하다 ; -ㄴ/는다고 rapporte une affirmation, -냐고 une question, -자고 une proposition — aucun ne transmet un ordre.",
      'Uma instrução transmitida (tomar após as refeições) exige a ordem indireta -(으)라고 하다; -ㄴ/는다고 relata afirmação, -냐고 pergunta, -자고 sugestão conjunta — nenhum transmite ordem.',
      'คำสั่งที่ถ่ายทอด (ให้กินหลังอาหาร) ต้องใช้คำสั่งอ้อม -(으)라고 하다; -ㄴ/는다고 รายงานบอกเล่า, -냐고 คำถาม, -자고 คำชวน ไม่มีอันใดสื่อคำสั่ง',
      'Instruksi yang diteruskan (minum sesudah makan) butuh perintah tak langsung -(으)라고 하다; -ㄴ/는다고 melaporkan pernyataan, -냐고 tanya, -자고 ajakan — tak ada yang menyampaikan perintah.',
      'Một chỉ dẫn được truyền lại (uống sau khi ăn) cần mệnh lệnh gián tiếp -(으)라고 하다; -ㄴ/는다고 tường thuật câu trần thuật, -냐고 câu hỏi, -자고 lời rủ — không cái nào truyền đạt mệnh lệnh.',
      '伝達された指示（食後に飲め）には間接命令 -(으)라고 하다 が必要。-ㄴ/는다고 は平叙、-냐고 は疑問、-자고 は勧誘で命令を伝えられない。',
    ),
  },
  {
    ko: '-는 반면에',
    sentence: '이 도시는 물가가 {} 교통은 아주 편리해요.',
    answer: '비싼 반면에',
    distractors: ['비싸기 때문에', '비싸기는커녕', '비싸기 전에'],
    trans: L(
      'In this city prices are high, whereas transport is very convenient.',
      'En esta ciudad los precios son altos, mientras que el transporte es muy cómodo.',
      'Dans cette ville les prix sont élevés, tandis que les transports sont très pratiques.',
      'Nesta cidade os preços são altos, ao passo que o transporte é muito prático.',
      'เมืองนี้ของแพง ในขณะที่การเดินทางสะดวกมาก',
      'Di kota ini harga mahal, sementara transportasinya sangat nyaman.',
      'Ở thành phố này vật giá đắt, ngược lại giao thông rất tiện lợi.',
      'この都市は物価が高い反面、交通はとても便利です。',
    ),
    why: L(
      'Two contrasting facts about one place call for -는 반면에 (the adjective form 비싼 반면에); -기 때문에 makes a (false) cause, -기는커녕 needs a "let alone" denial, -기 전에 means "before" — none expresses the contrast.',
      'Dos hechos contrastantes sobre un lugar exigen -는 반면에 (la forma adjetiva 비싼 반면에); -기 때문에 da una causa (falsa), -기는커녕 exige una negación "ni mucho menos", -기 전에 significa "antes de" — ninguno expresa el contraste.',
      'Deux faits opposés sur un même lieu appellent -는 반면에 (forme adjectivale 비싼 반면에) ; -기 때문에 donne une cause (fausse), -기는커녕 exige un démenti «loin de», -기 전에 signifie «avant» — aucun n’exprime le contraste.',
      'Dois fatos contrastantes sobre um lugar pedem -는 반면에 (a forma adjetiva 비싼 반면에); -기 때문에 dá uma causa (falsa), -기는커녕 exige negação "muito menos", -기 전에 significa "antes de" — nenhum expressa o contraste.',
      'ข้อเท็จจริงสองอย่างที่ตรงข้ามกันของที่เดียวต้องใช้ -는 반면에 (รูปคุณศัพท์ 비싼 반면에); -기 때문에 ให้เหตุ (ผิด), -기는커녕 ต้องเป็นการปฏิเสธ "อย่าว่าแต่", -기 전에 แปลว่า "ก่อน" ไม่มีอันใดบอกความขัดแย้ง',
      'Dua fakta yang kontras tentang satu tempat menuntut -는 반면에 (bentuk adjektiva 비싼 반면에); -기 때문에 memberi sebab (keliru), -기는커녕 perlu penyangkalan "jangankan", -기 전에 berarti "sebelum" — tak ada yang menyatakan kontras.',
      'Hai sự việc tương phản về cùng một nơi cần -는 반면에 (dạng tính từ 비싼 반면에); -기 때문에 nêu nguyên nhân (sai), -기는커녕 cần phủ định "đừng nói chi", -기 전에 nghĩa là "trước khi" — không cái nào diễn đạt sự tương phản.',
      '同じ場所の対照的な二事実には -는 반면에（形容詞形 비싼 반면에）が必要。-기 때문에 は（誤った）原因、-기는커녕 は「どころか」の否定、-기 전에 は「前に」で、対比を表せない。',
    ),
  },
  {
    ko: '-에도 불구하고',
    sentence: '여러 번 실패했{} 그는 끝까지 포기하지 않았어요.',
    answer: '음에도 불구하고',
    distractors: ['기 때문에', '으려고', '기 위해서'],
    trans: L(
      'Despite failing several times, he never gave up to the end.',
      'A pesar de haber fracasado varias veces, él no se rindió hasta el final.',
      'Malgré plusieurs échecs, il n’a pas abandonné jusqu’au bout.',
      'Apesar de ter falhado várias vezes, ele não desistiu até o fim.',
      'แม้จะล้มเหลวหลายครั้ง เขาก็ไม่ยอมแพ้จนถึงที่สุด',
      'Meskipun gagal berkali-kali, dia tidak menyerah sampai akhir.',
      'Bất chấp thất bại nhiều lần, anh ấy không bỏ cuộc đến cùng.',
      '何度も失敗したにもかかわらず、彼は最後まで諦めませんでした。',
    ),
    why: L(
      'A concession (failed, yet did not give up) requires -에도 불구하고 on the noun-form 실패했음에도 불구하고; -기 때문에 marks cause, -(으)려고 / -기 위해서 mark purpose — none yields the "despite" meaning.',
      'Una concesión (fracasó pero no se rindió) requiere -에도 불구하고 sobre la forma nominal 실패했음에도 불구하고; -기 때문에 marca causa, -(으)려고 / -기 위해서 marcan finalidad — ninguno da el sentido "a pesar de".',
      'Une concession (a échoué mais n’a pas abandonné) exige -에도 불구하고 sur la forme nominale 실패했음에도 불구하고 ; -기 때문에 marque la cause, -(으)려고 / -기 위해서 le but — aucun ne donne le sens «malgré».',
      'Uma concessão (falhou mas não desistiu) exige -에도 불구하고 sobre a forma nominal 실패했음에도 불구하고; -기 때문에 marca causa, -(으)려고 / -기 위해서 finalidade — nenhum dá o sentido "apesar de".',
      'การยอมรับเงื่อนไขแย้ง (ล้มเหลวแต่ไม่ยอมแพ้) ต้องใช้ -에도 불구하고 บนรูปนาม 실패했음에도 불구하고; -기 때문에 บอกเหตุ, -(으)려고 / -기 위해서 บอกจุดประสงค์ ไม่มีอันใดให้ความหมาย "แม้ว่า"',
      'Konsesi (gagal tapi tidak menyerah) memerlukan -에도 불구하고 pada bentuk nomina 실패했음에도 불구하고; -기 때문에 menandai sebab, -(으)려고 / -기 위해서 tujuan — tak ada yang memberi makna "meskipun".',
      'Một sự nhượng bộ (thất bại nhưng không bỏ cuộc) cần -에도 불구하고 trên dạng danh từ 실패했음에도 불구하고; -기 때문에 chỉ nguyên nhân, -(으)려고 / -기 위해서 chỉ mục đích — không cái nào cho nghĩa "bất chấp".',
      '逆接の譲歩（失敗したが諦めなかった）には名詞形 실패했음에도 불구하고 の -에도 불구하고 が必要。-기 때문에 は原因、-(으)려고 / -기 위해서 は目的で、「にもかかわらず」にならない。',
    ),
  },
  {
    ko: '-(으)ㄹ수록',
    sentence: '이 노래는 {} 들을수록 더 좋아져요.',
    answer: '들으면',
    distractors: ['들어도', '들으니까', '들으려고'],
    trans: L(
      'The more I listen to this song, the more I like it.',
      'Cuanto más escucho esta canción, más me gusta.',
      'Plus j’écoute cette chanson, plus je l’aime.',
      'Quanto mais escuto essa música, mais gosto dela.',
      'เพลงนี้ยิ่งฟังยิ่งชอบ',
      'Lagu ini semakin didengar semakin saya suka.',
      'Bài hát này càng nghe càng thích.',
      'この歌は聞けば聞くほど好きになります。',
    ),
    why: L(
      'The proportional "the more X, the more Y" is built with -(으)면 ... -(으)ㄹ수록 (들으면 들을수록); -아/어도 means "even if", -(으)니까 a reason, -(으)려고 a purpose — none pairs with 들을수록 to give the escalating sense.',
      'La correlación "cuanto más X, más Y" se forma con -(으)면 ... -(으)ㄹ수록 (들으면 들을수록); -아/어도 es "aunque", -(으)니까 razón, -(으)려고 finalidad — ninguno se empareja con 들을수록 para el sentido creciente.',
      'La corrélation «plus X, plus Y» se construit avec -(으)면 ... -(으)ㄹ수록 (들으면 들을수록) ; -아/어도 = «même si», -(으)니까 = raison, -(으)려고 = but — aucun ne s’accorde avec 들을수록 pour le sens croissant.',
      'A correlação "quanto mais X, mais Y" se forma com -(으)면 ... -(으)ㄹ수록 (들으면 들을수록); -아/어도 é "mesmo que", -(으)니까 razão, -(으)려고 finalidade — nenhum combina com 들을수록 para o sentido crescente.',
      'ความสัมพันธ์ "ยิ่ง X ยิ่ง Y" สร้างด้วย -(으)면 ... -(으)ㄹ수록 (들으면 들을수록); -아/어도 = "ถึงแม้", -(으)니까 = เหตุผล, -(으)려고 = จุดประสงค์ ไม่มีอันใดเข้าคู่กับ 들을수록 ให้ความหมายเพิ่มขึ้น',
      'Korelasi "semakin X, semakin Y" dibentuk dengan -(으)면 ... -(으)ㄹ수록 (들으면 들을수록); -아/어도 = "walaupun", -(으)니까 = alasan, -(으)려고 = tujuan — tak ada yang berpasangan dengan 들을수록 untuk makna meningkat.',
      'Tương quan "càng X càng Y" được tạo bởi -(으)면 ... -(으)ㄹ수록 (들으면 들을수록); -아/어도 = "dù", -(으)니까 = lý do, -(으)려고 = mục đích — không cái nào ghép với 들을수록 cho nghĩa tăng dần.',
      '比例の「〜ば〜ほど」は -(으)면 ... -(으)ㄹ수록（들으면 들을수록）で作る。-아/어도 は「ても」、-(으)니까 は理由、-(으)려고 は目的で、들을수록 と組んで増大の意味にならない。',
    ),
  },
  {
    ko: '-는 바람에',
    sentence: '갑자기 차가 {} 회의에 늦고 말았어요.',
    answer: '고장 나는 바람에',
    distractors: ['고장 나는 대신에', '고장 나는 김에', '고장 나는 동안에'],
    trans: L(
      'Because the car suddenly broke down, I ended up late for the meeting.',
      'Por culpa de que el coche se averió de pronto, terminé llegando tarde a la reunión.',
      "À cause de la panne soudaine de la voiture, j'ai fini par arriver en retard à la réunion.",
      'Por causa de o carro quebrar de repente, acabei me atrasando para a reunião.',
      'พอดีรถเสียกะทันหัน เลยไปประชุมสาย',
      'Gara-gara mobil tiba-tiba mogok, saya jadi telat ke rapat.',
      'Do xe đột nhiên hỏng, tôi đã bị muộn cuộc họp.',
      '車が急に故障したせいで、会議に遅れてしまいました。',
    ),
    why: L(
      'A sudden out-of-control cause with a bad result (was late) is exactly -는 바람에; -는 대신에 means "instead of", -는 김에 "while at it", -는 동안에 "during" — none expresses the unexpected negative cause.',
      'Una causa repentina e incontrolable con mal resultado (llegó tarde) es justamente -는 바람에; -는 대신에 es "en vez de", -는 김에 "ya que", -는 동안에 "mientras" — ninguno expresa la causa negativa imprevista.',
      'Une cause soudaine et incontrôlable au résultat fâcheux (en retard) est précisément -는 바람에 ; -는 대신에 = «au lieu de», -는 김에 = «tant qu’à», -는 동안에 = «pendant» — aucun n’exprime la cause négative imprévue.',
      'Uma causa repentina e incontrolável com resultado ruim (atrasou) é justamente -는 바람에; -는 대신에 é "em vez de", -는 김에 "já que", -는 동안에 "durante" — nenhum expressa a causa negativa inesperada.',
      'เหตุฉับพลันที่ควบคุมไม่ได้และผลร้าย (มาสาย) คือ -는 바람에 พอดี; -는 대신에 = "แทนที่จะ", -는 김에 = "ในเมื่อ...แล้ว", -는 동안에 = "ระหว่างที่" ไม่มีอันใดบอกเหตุร้ายที่ไม่คาดคิด',
      'Sebab mendadak di luar kendali dengan akibat buruk (terlambat) tepatnya -는 바람에; -는 대신에 = "alih-alih", -는 김에 = "mumpung", -는 동안에 = "selama" — tak ada yang menyatakan sebab negatif tak terduga.',
      'Nguyên nhân đột ngột ngoài tầm kiểm soát với kết quả xấu (bị muộn) chính là -는 바람에; -는 대신에 = "thay vì", -는 김에 = "nhân tiện", -는 동안에 = "trong khi" — không cái nào diễn đạt nguyên nhân xấu bất ngờ.',
      '制御不能で突発の悪い原因（遅刻）はまさに -는 바람에。-는 대신에 は「代わりに」、-는 김에 は「ついでに」、-는 동안에 は「間に」で、予期せぬ悪い原因を表せない。',
    ),
  },
  {
    ko: '-(으)ㄹ 리가 없다',
    sentence: '그렇게 성실한 사람이 약속을 {}.',
    answer: '잊었을 리가 없어요',
    distractors: ['잊는 척했어요', '잊을 뻔했어요', '잊기 마련이에요'],
    trans: L(
      'There’s no way such a sincere person forgot the promise.',
      'No puede ser que una persona tan responsable haya olvidado la promesa.',
      'Il est impossible qu’une personne aussi sérieuse ait oublié la promesse.',
      'Não tem como uma pessoa tão responsável ter esquecido a promessa.',
      'คนที่จริงจังขนาดนั้นไม่มีทางลืมสัญญาแน่',
      'Tidak mungkin orang serajin itu melupakan janji.',
      'Người chăm chỉ như thế không thể nào quên lời hứa được.',
      'あんなに誠実な人が約束を忘れたはずがありません。',
    ),
    why: L(
      'A confident judgment of impossibility ("no way they forgot") is -(으)ㄹ 리가 없다; -(으)ㄴ/는 척하다 means "pretend", -(으)ㄹ 뻔하다 a near-miss, -기 마련이다 an inevitability — none denies the possibility itself.',
      'Un juicio firme de imposibilidad ("no pudo olvidar") es -(으)ㄹ 리가 없다; -(으)ㄴ/는 척하다 es "fingir", -(으)ㄹ 뻔하다 un casi-accidente, -기 마련이다 una inevitabilidad — ninguno niega la posibilidad en sí.',
      'Un jugement ferme d’impossibilité (« il n’a pas pu oublier ») est -(으)ㄹ 리가 없다 ; -(으)ㄴ/는 척하다 = «faire semblant», -(으)ㄹ 뻔하다 un quasi-accident, -기 마련이다 une fatalité — aucun ne nie la possibilité elle-même.',
      'Um juízo firme de impossibilidade ("não tem como ter esquecido") é -(으)ㄹ 리가 없다; -(으)ㄴ/는 척하다 = "fingir", -(으)ㄹ 뻔하다 um quase-acidente, -기 마련이다 uma inevitabilidade — nenhum nega a possibilidade em si.',
      'การตัดสินด้วยความมั่นใจว่าเป็นไปไม่ได้ ("ไม่มีทางลืม") คือ -(으)ㄹ 리가 없다; -(으)ㄴ/는 척하다 = "แกล้งทำ", -(으)ㄹ 뻔하다 เกือบเกิดเหตุ, -기 마련이다 ความเลี่ยงไม่ได้ ไม่มีอันใดปฏิเสธความเป็นไปได้',
      'Penilaian yakin akan kemustahilan ("tidak mungkin lupa") adalah -(으)ㄹ 리가 없다; -(으)ㄴ/는 척하다 = "berpura-pura", -(으)ㄹ 뻔하다 nyaris terjadi, -기 마련이다 keniscayaan — tak ada yang menyangkal kemungkinannya.',
      'Phán đoán chắc chắn về sự bất khả ("không thể quên") là -(으)ㄹ 리가 없다; -(으)ㄴ/는 척하다 = "giả vờ", -(으)ㄹ 뻔하다 suýt xảy ra, -기 마련이다 điều tất yếu — không cái nào phủ định chính khả năng đó.',
      '不可能だという確信の判断（「忘れたはずがない」）は -(으)ㄹ 리가 없다。-(으)ㄴ/는 척하다 は「ふりをする」、-(으)ㄹ 뻔하다 は危うく、-기 마련이다 は必然で、可能性そのものを否定しない。',
    ),
  },
  {
    ko: '-(으)ㄹ걸 그랬다',
    sentence: '길이 이렇게 막힐 줄 알았으면 지하철을 {}.',
    answer: '탈걸 그랬어요',
    distractors: ['타고 말았어요', '탄 적이 있어요', '타기로 했어요'],
    trans: L(
      'If I’d known traffic would be this bad, I should have taken the subway.',
      'Si hubiera sabido que habría tanto tráfico, debería haber tomado el metro.',
      'Si j’avais su qu’il y aurait autant de circulation, j’aurais dû prendre le métro.',
      'Se eu soubesse que o trânsito estaria assim, deveria ter pegado o metrô.',
      'รู้อย่างนี้ว่ารถจะติดขนาดนี้ น่าจะนั่งรถไฟใต้ดิน',
      'Kalau tahu macetnya separah ini, seharusnya saya naik kereta bawah tanah.',
      'Biết kẹt xe thế này thì đáng lẽ tôi nên đi tàu điện ngầm.',
      'こんなに渋滞するとわかっていたら、地下鉄に乗ればよかったです。',
    ),
    why: L(
      'Regret over a past choice not made (should have taken the subway) is -(으)ㄹ걸 그랬다; -고 말다 reports an unwanted completed act, -(으)ㄴ 적이 있다 past experience, -기로 하다 a decision — none expresses retrospective regret.',
      'El arrepentimiento por una opción pasada no tomada (debí tomar el metro) es -(으)ㄹ걸 그랬다; -고 말다 narra un acto consumado no deseado, -(으)ㄴ 적이 있다 experiencia, -기로 하다 una decisión — ninguno expresa arrepentimiento retrospectivo.',
      'Le regret d’un choix passé non fait (j’aurais dû prendre le métro) est -(으)ㄹ걸 그랬다 ; -고 말다 rapporte un acte achevé non voulu, -(으)ㄴ 적이 있다 une expérience, -기로 하다 une décision — aucun n’exprime le regret rétrospectif.',
      'O arrependimento por uma escolha passada não feita (devia ter pegado o metrô) é -(으)ㄹ걸 그랬다; -고 말다 narra um ato concluído indesejado, -(으)ㄴ 적이 있다 experiência, -기로 하다 uma decisão — nenhum expressa arrependimento retrospectivo.',
      'ความเสียดายต่อทางเลือกในอดีตที่ไม่ได้ทำ (น่าจะนั่งรถไฟใต้ดิน) คือ -(으)ㄹ걸 그랬다; -고 말다 เล่าเหตุที่เกิดขึ้นแล้วโดยไม่ตั้งใจ, -(으)ㄴ 적이 있다 ประสบการณ์, -기로 하다 การตัดสินใจ ไม่มีอันใดบอกความเสียดายย้อนหลัง',
      'Penyesalan atas pilihan lampau yang tak diambil (mestinya naik kereta) adalah -(으)ㄹ걸 그랬다; -고 말다 menceritakan perbuatan selesai yang tak diinginkan, -(으)ㄴ 적이 있다 pengalaman, -기로 하다 keputusan — tak ada yang menyatakan penyesalan retrospektif.',
      'Sự hối tiếc về lựa chọn quá khứ không thực hiện (đáng lẽ đi tàu điện ngầm) là -(으)ㄹ걸 그랬다; -고 말다 kể một việc đã hoàn tất ngoài ý muốn, -(으)ㄴ 적이 있다 kinh nghiệm, -기로 하다 một quyết định — không cái nào diễn đạt sự hối tiếc nhìn lại.',
      '過去にしなかった選択への後悔（地下鉄に乗ればよかった）は -(으)ㄹ걸 그랬다。-고 말다 は望まぬ完了、-(으)ㄴ 적이 있다 は経験、-기로 하다 は決定で、振り返りの後悔を表せない。',
    ),
  },
  {
    ko: '-다가',
    sentence: '텔레비전을 {} 그대로 소파에서 잠이 들었어요.',
    answer: '보다가',
    distractors: ['보려고', '보거나', '보는데도'],
    trans: L(
      'I was watching TV and fell asleep right there on the sofa.',
      'Estaba viendo la tele y me quedé dormido ahí mismo en el sofá.',
      'Je regardais la télé et je me suis endormi tel quel sur le canapé.',
      'Eu estava vendo TV e acabei dormindo ali mesmo no sofá.',
      'กำลังดูทีวีอยู่แล้วก็เผลอหลับบนโซฟาเลย',
      'Sedang menonton TV, lalu ketiduran begitu saja di sofa.',
      'Đang xem tivi thì tôi ngủ thiếp đi ngay trên ghế sofa.',
      'テレビを見ていて、そのままソファで寝てしまいました。',
    ),
    why: L(
      'One subject’s action interrupted by a shift to another (watching → fell asleep) is -다가; -(으)려고 marks intent, -거나 lists alternatives, -는데도 is concessive — none captures the interruption.',
      'La acción de un sujeto interrumpida por un cambio (veía → se durmió) es -다가; -(으)려고 marca intención, -거나 enumera alternativas, -는데도 es concesivo — ninguno capta la interrupción.',
      'L’action d’un sujet interrompue par un basculement (regardait → s’est endormi) est -다가 ; -(으)려고 marque l’intention, -거나 énumère des options, -는데도 est concessif — aucun ne rend l’interruption.',
      'A ação de um sujeito interrompida por uma mudança (assistia → adormeceu) é -다가; -(으)려고 marca intenção, -거나 lista alternativas, -는데도 é concessivo — nenhum capta a interrupção.',
      'การกระทำของประธานเดียวที่ถูกตัดด้วยการเปลี่ยน (ดูอยู่ → หลับ) คือ -다가; -(으)려고 บอกเจตนา, -거나 เรียงตัวเลือก, -는데도 เป็นการยอมแย้ง ไม่มีอันใดจับการสะดุดได้',
      'Aksi satu subjek yang terputus oleh peralihan (menonton → tertidur) adalah -다가; -(으)려고 menandai niat, -거나 mendaftar pilihan, -는데도 konsesif — tak ada yang menangkap interupsi.',
      'Hành động của một chủ ngữ bị gián đoạn bởi sự chuyển sang việc khác (đang xem → ngủ thiếp) là -다가; -(으)려고 chỉ ý định, -거나 liệt kê lựa chọn, -는데도 nhượng bộ — không cái nào diễn đạt sự gián đoạn.',
      '同一主語の動作が別の動作に切り替わる中断（見ていて→寝た）は -다가。-(으)려고 は意図、-거나 は選択列挙、-는데도 は逆接で、中断を表せない。',
    ),
  },
  {
    ko: '-(으)ㄴ/는 척하다',
    sentence: '선생님과 눈이 마주치자 그는 책을 {}.',
    answer: '읽는 척했어요',
    distractors: ['읽는 편이에요', '읽기 마련이에요', '읽을 뻔했어요'],
    trans: L(
      'The moment his eyes met the teacher’s, he pretended to be reading the book.',
      'En cuanto sus ojos se cruzaron con los del profesor, fingió estar leyendo el libro.',
      'Dès que son regard a croisé celui du professeur, il a fait semblant de lire le livre.',
      'Assim que seu olhar cruzou com o do professor, ele fingiu estar lendo o livro.',
      'พอสบตากับครู เขาก็แกล้งทำเป็นอ่านหนังสือ',
      'Begitu matanya beradu dengan guru, dia pura-pura sedang membaca buku.',
      'Vừa chạm mắt với cô giáo, cậu ấy liền giả vờ đang đọc sách.',
      '先生と目が合うと、彼は本を読むふりをしました。',
    ),
    why: L(
      'Feigning an action (pretended to read) is -(으)ㄴ/는 척하다; -는 편이다 states a tendency, -기 마련이다 an inevitability, -(으)ㄹ 뻔하다 a near-miss — none means "pretend".',
      'Aparentar una acción (fingió leer) es -(으)ㄴ/는 척하다; -는 편이다 expresa tendencia, -기 마련이다 inevitabilidad, -(으)ㄹ 뻔하다 un casi-accidente — ninguno significa "fingir".',
      'Feindre une action (a fait semblant de lire) est -(으)ㄴ/는 척하다 ; -는 편이다 exprime une tendance, -기 마련이다 une fatalité, -(으)ㄹ 뻔하다 un quasi-accident — aucun ne signifie «faire semblant».',
      'Fingir uma ação (fingiu ler) é -(으)ㄴ/는 척하다; -는 편이다 expressa tendência, -기 마련이다 inevitabilidade, -(으)ㄹ 뻔하다 um quase-acidente — nenhum significa "fingir".',
      'การแกล้งทำกิริยา (แกล้งอ่าน) คือ -(으)ㄴ/는 척하다; -는 편이다 บอกแนวโน้ม, -기 마련이다 ความเลี่ยงไม่ได้, -(으)ㄹ 뻔하다 เกือบเกิดเหตุ ไม่มีอันใดแปลว่า "แกล้งทำ"',
      'Berpura-pura melakukan tindakan (pura-pura membaca) adalah -(으)ㄴ/는 척하다; -는 편이다 menyatakan kecenderungan, -기 마련이다 keniscayaan, -(으)ㄹ 뻔하다 nyaris — tak ada yang berarti "berpura-pura".',
      'Giả vờ một hành động (giả vờ đọc) là -(으)ㄴ/는 척하다; -는 편이다 nêu xu hướng, -기 마련이다 điều tất yếu, -(으)ㄹ 뻔하다 suýt — không cái nào nghĩa là "giả vờ".',
      '動作を装う（読むふりをした）は -(으)ㄴ/는 척하다。-는 편이다 は傾向、-기 마련이다 は必然、-(으)ㄹ 뻔하다 は危うくで、「ふりをする」にならない。',
    ),
  },
  {
    ko: '-(으)ㄹ 만하다',
    sentence: '이 책은 내용이 알차서 한번 {}.',
    answer: '읽을 만해요',
    distractors: ['읽을 뻔해요', '읽기 마련이에요', '읽는 척해요'],
    trans: L(
      'This book has rich content, so it’s worth reading once.',
      'Este libro tiene un contenido sustancioso, así que vale la pena leerlo una vez.',
      'Ce livre a un contenu riche, alors il vaut la peine d’être lu une fois.',
      'Este livro tem conteúdo rico, então vale a pena ler uma vez.',
      'หนังสือเล่มนี้เนื้อหาแน่น เลยน่าอ่านสักครั้ง',
      'Buku ini isinya berbobot, jadi layak dibaca sekali.',
      'Cuốn sách này nội dung phong phú nên đáng đọc một lần.',
      'この本は内容が充実していて、一度読む価値があります。',
    ),
    why: L(
      'Saying something is worth doing (worth reading) is -(으)ㄹ 만하다; -(으)ㄹ 뻔하다 means "almost", -기 마련이다 "is bound to", -(으)ㄴ/는 척하다 "pretend" — none conveys merit/worth.',
      'Decir que algo vale la pena (vale la pena leerlo) es -(으)ㄹ 만하다; -(으)ㄹ 뻔하다 es "casi", -기 마련이다 "es inevitable", -(으)ㄴ/는 척하다 "fingir" — ninguno transmite mérito/valor.',
      'Dire que cela vaut la peine (vaut la peine d’être lu) est -(으)ㄹ 만하다 ; -(으)ㄹ 뻔하다 = «presque», -기 마련이다 = «forcément», -(으)ㄴ/는 척하다 = «faire semblant» — aucun n’exprime la valeur.',
      'Dizer que algo vale a pena (vale a pena ler) é -(으)ㄹ 만하다; -(으)ㄹ 뻔하다 é "quase", -기 마련이다 "é inevitável", -(으)ㄴ/는 척하다 "fingir" — nenhum transmite mérito/valor.',
      'การบอกว่าคุ้มที่จะทำ (น่าอ่าน) คือ -(으)ㄹ 만하다; -(으)ㄹ 뻔하다 = "เกือบ", -기 마련이다 = "เลี่ยงไม่ได้", -(으)ㄴ/는 척하다 = "แกล้งทำ" ไม่มีอันใดสื่อคุณค่า',
      'Mengatakan sesuatu layak dilakukan (layak dibaca) adalah -(으)ㄹ 만하다; -(으)ㄹ 뻔하다 = "hampir", -기 마련이다 = "pasti terjadi", -(으)ㄴ/는 척하다 = "berpura-pura" — tak ada yang menyatakan nilai/kelayakan.',
      'Nói rằng điều gì đó đáng làm (đáng đọc) là -(으)ㄹ 만하다; -(으)ㄹ 뻔하다 = "suýt", -기 마련이다 = "tất nhiên", -(으)ㄴ/는 척하다 = "giả vờ" — không cái nào diễn đạt giá trị.',
      '価値があると言う（読む価値がある）は -(으)ㄹ 만하다。-(으)ㄹ 뻔하다 は「危うく」、-기 마련이다 は「当然」、-(으)ㄴ/는 척하다 は「ふりをする」で、価値を表せない。',
    ),
  },
  {
    ko: '-았/었더라면',
    sentence: '그때 네 말을 {} 이런 실수는 하지 않았을 거야.',
    answer: '들었더라면',
    distractors: ['들으면', '들었지만', '들으려고'],
    trans: L(
      'If I had listened to you back then, I wouldn’t have made this kind of mistake.',
      'Si te hubiera hecho caso en ese momento, no habría cometido este tipo de error.',
      'Si je t’avais écouté à l’époque, je n’aurais pas fait ce genre d’erreur.',
      'Se eu tivesse te ouvido naquela época, não teria cometido esse tipo de erro.',
      'ถ้าตอนนั้นฉันฟังเธอ ก็คงไม่ทำผิดพลาดแบบนี้',
      'Andai dulu aku mendengarkanmu, aku tidak akan membuat kesalahan seperti ini.',
      'Giá mà hồi đó tôi nghe lời bạn thì đã không mắc lỗi thế này.',
      'あのとき君の言うことを聞いていたら、こんな失敗はしなかっただろう。',
    ),
    why: L(
      'A past counterfactual ("if I had listened ...") is -았/었더라면; plain -(으)면 is a real/future condition, -았/었지만 is past contrast "but", -(으)려고 is purpose — none builds the unreal past hypothesis.',
      'Un contrafactual pasado ("si hubiera hecho caso ...") es -았/었더라면; -(으)면 es condición real/futura, -았/었지만 contraste pasado "pero", -(으)려고 finalidad — ninguno forma la hipótesis irreal del pasado.',
      'Un irréel du passé («si je t’avais écouté ...») est -았/었더라면 ; -(으)면 est une condition réelle/future, -았/었지만 un contraste passé «mais», -(으)려고 un but — aucun ne construit l’hypothèse irréelle du passé.',
      'Um contrafactual passado ("se eu tivesse ouvido ...") é -았/었더라면; -(으)면 é condição real/futura, -았/었지만 contraste passado "mas", -(으)려고 finalidade — nenhum forma a hipótese irreal do passado.',
      'การสมมุติย้อนหลังในอดีต ("ถ้าตอนนั้นฉันฟัง ...") คือ -았/었더라면; -(으)면 เป็นเงื่อนไขจริง/อนาคต, -았/었지만 ความขัดแย้งอดีต "แต่", -(으)려고 จุดประสงค์ ไม่มีอันใดสร้างสมมุติอดีตที่ไม่เป็นจริง',
      'Kontrafaktual lampau ("andai dulu aku mendengarkan ...") adalah -았/었더라면; -(으)면 syarat nyata/masa depan, -았/었지만 kontras lampau "tapi", -(으)려고 tujuan — tak ada yang membentuk pengandaian lampau yang tak nyata.',
      'Phản thực quá khứ ("giá mà hồi đó tôi nghe ...") là -았/었더라면; -(으)면 là điều kiện thực/tương lai, -았/었지만 là tương phản quá khứ "nhưng", -(으)려고 là mục đích — không cái nào tạo giả định không có thực ở quá khứ.',
      '過去の反実仮想（「あのとき聞いていたら」）は -았/었더라면。-(으)면 は現実・未来の条件、-았/었지만 は過去の逆接「が」、-(으)려고 は目的で、過去の非現実の仮定を作れない。',
    ),
  },
  {
    ko: '-(으)ㄴ/는 김에',
    sentence: '우체국에 {} 은행에도 들러서 일을 봤어요.',
    answer: '간 김에',
    distractors: ['가는 대신에', '가는 바람에', '가는 동안에'],
    trans: L(
      'Since I was going to the post office, I stopped by the bank too and got things done.',
      'Ya que iba a la oficina de correos, pasé también por el banco y resolví mis asuntos.',
      'Tant qu’à aller à la poste, je suis aussi passé à la banque pour régler mes affaires.',
      'Já que fui ao correio, passei também no banco e resolvi as coisas.',
      'ในเมื่อไปไปรษณีย์แล้ว เลยแวะธนาคารจัดการธุระไปด้วย',
      'Mumpung ke kantor pos, saya sekalian mampir ke bank mengurus keperluan.',
      'Nhân tiện đi bưu điện, tôi ghé luôn ngân hàng giải quyết công việc.',
      '郵便局に行ったついでに、銀行にも寄って用事を済ませました。',
    ),
    why: L(
      'Taking the opportunity of one trip to do a second errand is -(으)ㄴ/는 김에 (past-motion form 간 김에); -는 대신에 "instead of", -는 바람에 "because (bad result)", -는 동안에 "during" — none gives the "while I’m at it" sense.',
      'Aprovechar un viaje para hacer otra gestión es -(으)ㄴ/는 김에 (forma de movimiento pasado 간 김에); -는 대신에 "en vez de", -는 바람에 "por culpa de (mal resultado)", -는 동안에 "mientras" — ninguno da el sentido "ya que estoy".',
      'Profiter d’un déplacement pour faire une seconde course est -(으)ㄴ/는 김에 (forme de mouvement passé 간 김에) ; -는 대신에 «au lieu de», -는 바람에 «à cause de (mauvais résultat)», -는 동안에 «pendant» — aucun ne donne le sens «tant qu’à».',
      'Aproveitar uma ida para fazer outra tarefa é -(으)ㄴ/는 김에 (forma de movimento passado 간 김에); -는 대신에 "em vez de", -는 바람에 "por causa de (resultado ruim)", -는 동안에 "durante" — nenhum dá o sentido "já que estou".',
      'การใช้โอกาสจากการไปครั้งเดียวทำธุระอีกอย่างคือ -(으)ㄴ/는 김에 (รูปการเคลื่อนที่อดีต 간 김에); -는 대신에 "แทนที่จะ", -는 바람에 "เพราะ (ผลร้าย)", -는 동안에 "ระหว่างที่" ไม่มีอันใดให้ความหมาย "ในเมื่อ...แล้ว"',
      'Memanfaatkan satu kepergian untuk urusan kedua adalah -(으)ㄴ/는 김에 (bentuk gerak lampau 간 김에); -는 대신에 "alih-alih", -는 바람에 "gara-gara (akibat buruk)", -는 동안에 "selama" — tak ada yang memberi makna "mumpung".',
      'Tận dụng một chuyến đi để làm thêm việc khác là -(으)ㄴ/는 김에 (dạng chuyển động quá khứ 간 김에); -는 대신에 "thay vì", -는 바람에 "do (kết quả xấu)", -는 동안에 "trong khi" — không cái nào cho nghĩa "nhân tiện".',
      '一度の移動のついでに別の用事をするのは -(으)ㄴ/는 김에（過去移動形 간 김에）。-는 대신에 は「代わりに」、-는 바람에 は「せいで（悪い結果）」、-는 동안에 は「間に」で、「ついでに」にならない。',
    ),
  },
  {
    ko: '-고서야',
    sentence: '직접 {} 그 일이 얼마나 힘든지 깨달았어요.',
    answer: '해 보고서야',
    distractors: ['해 보는 대로', '해 보는 동안', '해 보기 전에'],
    trans: L(
      'Only after trying it myself did I realize how hard that work is.',
      'Solo después de probarlo yo mismo me di cuenta de lo difícil que es ese trabajo.',
      'Ce n’est qu’après l’avoir essayé moi-même que j’ai réalisé à quel point ce travail est dur.',
      'Só depois de eu mesmo tentar é que percebi como aquele trabalho é difícil.',
      'พอลองทำเองแล้วถึงจะรู้ว่างานนั้นยากแค่ไหน',
      'Baru setelah mencobanya sendiri, saya sadar betapa sulitnya pekerjaan itu.',
      'Chỉ sau khi tự mình thử, tôi mới nhận ra công việc đó khó đến nhường nào.',
      '自分でやってみてはじめて、その仕事がどれほど大変か気づきました。',
    ),
    why: L(
      'A precondition realized only afterward ("only after trying, I realized") is -고서야; -는 대로 means "as soon as / just as", -는 동안 "while", -기 전에 "before" — none carries the "not until then" nuance.',
      'Una condición previa cumplida solo después ("solo tras probar, me di cuenta") es -고서야; -는 대로 es "en cuanto / tal como", -는 동안 "mientras", -기 전에 "antes de" — ninguno lleva el matiz "no hasta entonces".',
      'Une condition préalable réalisée seulement après («ce n’est qu’après avoir essayé que ...») est -고서야 ; -는 대로 = «dès que / comme», -는 동안 = «pendant que», -기 전에 = «avant» — aucun ne porte la nuance «pas avant cela».',
      'Uma precondição cumprida só depois ("só depois de tentar, percebi") é -고서야; -는 대로 é "assim que / do jeito que", -는 동안 "enquanto", -기 전에 "antes de" — nenhum carrega o sentido "só então".',
      'เงื่อนไขที่เป็นจริงเฉพาะภายหลัง ("พอลองแล้วถึงรู้") คือ -고서야; -는 대로 = "ทันทีที่ / ตามที่", -는 동안 = "ระหว่างที่", -기 전에 = "ก่อน" ไม่มีอันใดให้ความหมาย "เพิ่งจะหลังจากนั้น"',
      'Prasyarat yang baru terpenuhi setelahnya ("baru setelah mencoba, saya sadar") adalah -고서야; -는 대로 = "begitu / sebagaimana", -는 동안 = "selama", -기 전에 = "sebelum" — tak ada yang membawa nuansa "baru sesudah itu".',
      'Điều kiện tiên quyết chỉ đạt được sau đó ("chỉ sau khi thử mới nhận ra") là -고서야; -는 대로 = "ngay khi / theo như", -는 동안 = "trong khi", -기 전에 = "trước khi" — không cái nào mang sắc thái "mãi đến lúc đó mới".',
      'あとになってはじめて満たされる前提（「やってみてはじめて気づいた」）は -고서야。-는 대로 は「次第・とおりに」、-는 동안 は「間」、-기 전에 は「前に」で、「それまで〜なかった」のニュアンスを持たない。',
    ),
  },
]
