// app/seed/cloze/n5.ts
import type { ClozeItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-5 grammar-pattern cloze items (choose the pattern that fits the blank).
 * ko matches grammars-n5.ts verbatim. Drafted + Korean-lens adversarially verified
 * (single-correct-answer crux). Korean wife native review = documented final gate.
 */

export const N5_CLOZE: ClozeItem[] = [
  {
    ko: '-더니',
    sentence: '동생이 아침부터 배가 아프{} 결국 병원에 갔어요.',
    answer: '더니',
    distractors: ['거나', '지만', '면서'],
    trans: L(
      'My sibling had a stomachache from the morning, and in the end went to the hospital.',
      'A mi hermano le dolía el estómago desde la mañana y al final fue al hospital.',
      'Mon frère avait mal au ventre depuis le matin, et finalement il est allé à l’hôpital.',
      'Meu irmão estava com dor de barriga desde de manhã e, no fim, foi ao hospital.',
      'น้องปวดท้องตั้งแต่เช้า สุดท้ายก็ไปโรงพยาบาล',
      'Adik saya sakit perut sejak pagi, dan akhirnya pergi ke rumah sakit.',
      'Em tôi đau bụng từ sáng, cuối cùng đã phải đi bệnh viện.',
      '弟は朝からお腹が痛がっていたが、結局病院に行きました。',
    ),
    why: L(
      'A directly observed past state leading to a consequence needs -더니; -거나 lists alternatives, -지만 marks contrast, -(으)면서 means "while" simultaneously — none expresses observed cause-then-result.',
      'Un estado pasado observado que lleva a una consecuencia exige -더니; -거나 enumera alternativas, -지만 marca contraste, -(으)면서 es "mientras" — ninguno expresa observación seguida de resultado.',
      'Un état passé observé entraînant une conséquence exige -더니 ; -거나 énumère des options, -지만 marque un contraste, -(으)면서 signifie « tout en » — aucun n’exprime l’observation puis le résultat.',
      'Um estado passado observado que leva a uma consequência exige -더니; -거나 lista alternativas, -지만 marca contraste, -(으)면서 é "enquanto" — nenhum exprime observação e resultado.',
      'สภาพในอดีตที่สังเกตเองและนำไปสู่ผลลัพธ์ต้องใช้ -더니; -거나 บอกทางเลือก, -지만 บอกความขัดแย้ง, -(으)면서 แปลว่า "ขณะที่" ล้วนไม่ใช่การสังเกตแล้วเกิดผล',
      'Keadaan lampau yang diamati dan berujung pada akibat butuh -더니; -거나 mendaftar pilihan, -지만 menandai kontras, -(으)면서 berarti "sambil" — tak ada yang menyatakan amatan lalu hasil.',
      'Trạng thái quá khứ được chứng kiến rồi dẫn đến kết quả cần -더니; -거나 liệt kê lựa chọn, -지만 nêu tương phản, -(으)면서 nghĩa là "trong khi" — không cái nào diễn tả quan sát rồi có kết quả.',
      '直接観察した過去の状態が結果に至るには -더니 が必要。-거나 は選択列挙、-지만 は逆接、-(으)면서 は「〜しながら」で、観察→結果を表せない。',
    ),
  },
  {
    ko: '-(으)ㄹ지언정',
    sentence: '굶{} 그 사람에게는 절대 도움을 청하지 않겠어요.',
    answer: '을지언정',
    distractors: ['으면', '어서', '으니까'],
    trans: L(
      'Even if I starve, I will never ask that person for help.',
      'Aunque pase hambre, jamás le pediré ayuda a esa persona.',
      'Quitte à mourir de faim, je ne demanderai jamais d’aide à cette personne.',
      'Mesmo que eu passe fome, jamais pedirei ajuda a essa pessoa.',
      'ต่อให้ต้องอดข้าว ฉันก็จะไม่มีวันขอความช่วยเหลือจากคนนั้น',
      'Walau harus kelaparan, saya tak akan pernah minta tolong pada orang itu.',
      'Thà nhịn đói chứ tôi nhất quyết không nhờ vả người ấy.',
      'たとえ飢えることがあっても、あの人には決して助けを求めません。',
    ),
    why: L(
      'The firm "I’d rather suffer X than yield" determination requires concessive -(으)ㄹ지언정; -(으)면 is a neutral condition, -아/어서 a real cause, -(으)니까 a reason — none carries the defiant concession.',
      'La determinación firme "antes X que ceder" exige el concesivo -(으)ㄹ지언정; -(으)면 es condición neutra, -아/어서 causa real, -(으)니까 razón — ninguno aporta la concesión desafiante.',
      'La résolution ferme « plutôt souffrir que céder » exige le concessif -(으)ㄹ지언정 ; -(으)면 est une condition neutre, -아/어서 une cause réelle, -(으)니까 une raison — aucun ne porte la concession.',
      'A determinação firme "prefiro sofrer X a ceder" exige o concessivo -(으)ㄹ지언정; -(으)면 é condição neutra, -아/어서 causa real, -(으)니까 razão — nenhum traz a concessão desafiadora.',
      'ความเด็ดเดี่ยว "ยอมลำบากดีกว่ายอมแพ้" ต้องใช้รูปยอมความ -(으)ㄹ지언정; -(으)면 เป็นเงื่อนไขกลาง, -아/어서 เป็นเหตุจริง, -(으)니까 เป็นเหตุผล ล้วนไม่สื่อการยอมความแบบท้าทาย',
      'Tekad bulat "lebih baik menderita daripada menyerah" butuh konsesif -(으)ㄹ지언정; -(으)면 syarat netral, -아/어서 sebab nyata, -(으)니까 alasan — tak ada yang membawa konsesi menantang.',
      'Quyết tâm dứt khoát "thà chịu khổ chứ không nhượng bộ" cần đuôi nhượng bộ -(으)ㄹ지언정; -(으)면 là điều kiện trung tính, -아/어서 là nguyên nhân thực, -(으)니까 là lý do — không cái nào mang sắc thái nhượng bộ.',
      '「苦しんでも譲らない」という固い決意には譲歩の -(으)ㄹ지언정 が必要。-(으)면 は中立の条件、-아/어서 は実際の原因、-(으)니까 は理由で、挑むような譲歩を表せない。',
    ),
  },
  {
    ko: '-고도',
    sentence: '그렇게 많이 먹{} 또 배가 고프다고요?',
    answer: '고도',
    distractors: ['어서', '으면', '거나'],
    trans: L(
      'You ate that much and you’re saying you’re hungry again?',
      '¿Comiste tanto y aun así dices que tienes hambre otra vez?',
      'Tu as mangé autant et tu dis que tu as encore faim ?',
      'Você comeu tudo aquilo e ainda diz que está com fome de novo?',
      'กินไปขนาดนั้นแล้วยังจะบอกว่าหิวอีกเหรอ',
      'Sudah makan sebanyak itu dan masih bilang lapar lagi?',
      'Ăn nhiều đến thế rồi mà vẫn bảo là đói à?',
      'あんなにたくさん食べたのに、また空腹だと言うのですか？',
    ),
    why: L(
      'A completed action that "still" yields a surprising opposite needs concessive -고도; -아/어서 would make eating the cause of hunger (illogical), -(으)면 sets a condition, -거나 lists options — none fits "even after eating".',
      'Una acción completada que "aun así" da un resultado opuesto exige el concesivo -고도; -아/어서 haría que comer cause el hambre (ilógico), -(으)면 pone condición, -거나 enumera — ninguno encaja con "aun habiendo comido".',
      'Une action accomplie qui aboutit malgré tout au contraire exige le concessif -고도 ; -아/어서 ferait du fait de manger la cause de la faim (illogique), -(으)면 pose une condition, -거나 énumère — aucun ne convient.',
      'Uma ação concluída que "ainda assim" gera o oposto exige o concessivo -고도; -아/어서 faria comer causar a fome (ilógico), -(으)면 põe condição, -거나 enumera — nenhum cabe.',
      'การกระทำที่ทำเสร็จแล้วแต่ "ก็ยัง" ได้ผลตรงข้ามต้องใช้รูปยอมความ -고도; -아/어서 จะทำให้การกินเป็นเหตุของความหิว (ไม่สมเหตุผล), -(으)면 เป็นเงื่อนไข, -거나 บอกทางเลือก ล้วนไม่เข้า',
      'Aksi yang sudah selesai tetapi "tetap" berhasil sebaliknya butuh konsesif -고도; -아/어서 menjadikan makan sebab lapar (tak logis), -(으)면 syarat, -거나 daftar pilihan — tak ada yang cocok.',
      'Hành động đã hoàn tất mà "vẫn" cho kết quả ngược lại cần đuôi nhượng bộ -고도; -아/어서 biến việc ăn thành nguyên nhân của đói (phi lý), -(으)면 nêu điều kiện, -거나 liệt kê — không cái nào hợp.',
      '完了した行為が「それでもなお」反対の結果になるには譲歩の -고도 が必要。-아/어서 は食べたことが空腹の原因になり不自然、-(으)면 は条件、-거나 は選択で合わない。',
    ),
  },
  {
    ko: '-느니 (차라리)',
    sentence: '거짓말을 하{} 차라리 아무 말도 하지 않겠어요.',
    answer: '느니',
    distractors: ['니까', '는데', '려고'],
    trans: L(
      'Rather than lie, I’d sooner say nothing at all.',
      'Antes que mentir, prefiero no decir nada en absoluto.',
      'Plutôt que de mentir, je préfère ne rien dire du tout.',
      'Em vez de mentir, prefiro não dizer absolutamente nada.',
      'แทนที่จะโกหก ฉันยอมไม่พูดอะไรเลยดีกว่า',
      'Daripada berbohong, lebih baik saya tidak berkata apa-apa.',
      'Thà không nói gì còn hơn là nói dối.',
      '嘘をつくくらいなら、いっそ何も言わない方がましです。',
    ),
    why: L(
      'Choosing the lesser of two undesirable options (paired with 차라리) requires -느니; -(으)니까 gives a reason, -는데 sets background, -(으)려고 marks purpose — none expresses "rather than".',
      'Elegir el menor de dos males (con 차라리) exige -느니; -(으)니까 da razón, -는데 da trasfondo, -(으)려고 marca propósito — ninguno expresa "antes que".',
      'Choisir le moindre de deux maux (avec 차라리) exige -느니 ; -(으)니까 donne une raison, -는데 pose le contexte, -(으)려고 marque le but — aucun n’exprime « plutôt que ».',
      'Escolher o menor de dois males (com 차라리) exige -느니; -(으)니까 dá razão, -는데 dá pano de fundo, -(으)려고 marca propósito — nenhum exprime "em vez de".',
      'การเลือกสิ่งที่แย่น้อยกว่าระหว่างสองสิ่งที่ไม่ดี (คู่กับ 차라리) ต้องใช้ -느니; -(으)니까 บอกเหตุผล, -는데 บอกภูมิหลัง, -(으)려고 บอกจุดประสงค์ ล้วนไม่สื่อ "แทนที่จะ"',
      'Memilih yang kurang buruk dari dua pilihan buruk (dengan 차라리) butuh -느니; -(으)니까 memberi alasan, -는데 memberi latar, -(으)려고 menandai tujuan — tak ada yang menyatakan "daripada".',
      'Chọn cái ít tệ hơn trong hai lựa chọn xấu (đi với 차라리) cần -느니; -(으)니까 nêu lý do, -는데 nêu bối cảnh, -(으)려고 nêu mục đích — không cái nào diễn tả "thà ... còn hơn".',
      '二つの嫌な選択肢のうち、ましな方を選ぶ（차라리 と対）には -느니 が必要。-(으)니까 は理由、-는데 は前置き、-(으)려고 は目的で「〜するくらいなら」を表せない。',
    ),
  },
  {
    ko: '-(으)ㄴ/는 셈이다',
    sentence: '하루에 세 번 먹으니까 규칙적으로 먹는 {}.',
    answer: '셈이에요',
    distractors: ['뻔했어요', '척했어요', '체했어요'],
    trans: L(
      'Since I eat three times a day, it practically amounts to eating regularly.',
      'Como como tres veces al día, viene a ser que como con regularidad.',
      'Comme je mange trois fois par jour, cela revient à manger régulièrement.',
      'Como como três vezes ao dia, é como se comesse com regularidade.',
      'เพราะกินวันละสามมื้อ ก็เท่ากับว่ากินอย่างสม่ำเสมอ',
      'Karena makan tiga kali sehari, praktisnya berarti makan teratur.',
      'Vì ăn ba bữa mỗi ngày nên coi như là ăn đều đặn.',
      '一日三回食べているので、規則正しく食べているようなものです。',
    ),
    why: L(
      'A reasoned "it amounts to / comes to be" equivalence after -는 needs 셈이다; -(으)ㄹ 뻔하다 means "almost happened", -(으)ㄴ/는 척하다 and -(으)ㄴ/는 체하다 both mean "pretend" — none states an equivalence.',
      'La equivalencia razonada "viene a ser" tras -는 exige 셈이다; -(으)ㄹ 뻔하다 es "casi pasó", -(으)ㄴ/는 척하다 y -(으)ㄴ/는 체하다 son "fingir" — ninguno expresa equivalencia.',
      'L’équivalence raisonnée « cela revient à » après -는 exige 셈이다 ; -(으)ㄹ 뻔하다 = « a failli », -(으)ㄴ/는 척하다 et -(으)ㄴ/는 체하다 = « faire semblant » — aucun n’exprime l’équivalence.',
      'A equivalência raciocinada "é como se" após -는 exige 셈이다; -(으)ㄹ 뻔하다 é "quase aconteceu", -(으)ㄴ/는 척하다 e -(으)ㄴ/는 체하다 são "fingir" — nenhum exprime equivalência.',
      'การเทียบเท่าเชิงสรุป "เท่ากับว่า" หลัง -는 ต้องใช้ 셈이다; -(으)ㄹ 뻔하다 แปลว่า "เกือบจะ", -(으)ㄴ/는 척하다 และ -(으)ㄴ/는 체하다 แปลว่า "แสร้งทำ" ล้วนไม่ใช่การเทียบเท่า',
      'Kesetaraan beralasan "praktisnya berarti" setelah -는 butuh 셈이다; -(으)ㄹ 뻔하다 = "nyaris terjadi", -(으)ㄴ/는 척하다 dan -(으)ㄴ/는 체하다 = "berpura-pura" — tak ada yang menyatakan kesetaraan.',
      'Sự tương đương có lý lẽ "coi như là" sau -는 cần 셈이다; -(으)ㄹ 뻔하다 nghĩa là "suýt", -(으)ㄴ/는 척하다 và -(으)ㄴ/는 체하다 nghĩa là "giả vờ" — không cái nào nêu sự tương đương.',
      '-는 の後で理屈の上の等価「〜ようなものだ」を表すには 셈이다 が必要。-(으)ㄹ 뻔하다 は「〜しそうだった」、-(으)ㄴ/는 척하다 と -(으)ㄴ/는 체하다 は「〜のふりをする」で等価を表さない。',
    ),
  },
  {
    ko: '-(으)ㄹ 뿐이다',
    sentence: '저는 그냥 제 의견을 말했{} 다른 뜻은 없었어요.',
    answer: '을 뿐이지',
    distractors: ['을 텐데', '을 정도로', '을 만큼'],
    trans: L(
      'I merely stated my opinion; I had no other intention.',
      'Simplemente expresé mi opinión, no tenía otra intención.',
      'Je n’ai fait que donner mon avis ; je n’avais pas d’autre intention.',
      'Eu apenas dei a minha opinião; não tinha outra intenção.',
      'ฉันแค่บอกความคิดเห็นเท่านั้น ไม่ได้มีความหมายอื่น',
      'Saya hanya menyampaikan pendapat, tidak ada maksud lain.',
      'Tôi chỉ nói ra ý kiến của mình thôi, không có ý gì khác.',
      '私はただ自分の意見を言っただけで、他意はありませんでした。',
    ),
    why: L(
      'The restrictive "merely X, nothing more" sense needs -(으)ㄹ 뿐이다 (here 뿐이지, contrasting with the 다른 뜻은 없다 clause); -(으)ㄹ 텐데 is a supposition, -(으)ㄹ 정도로 a degree, -(으)ㄹ 만큼 an extent — none means "only/just".',
      'El sentido restrictivo "solo X, nada más" exige -(으)ㄹ 뿐이다 (aquí 뿐이지, en contraste con 다른 뜻은 없다); -(으)ㄹ 텐데 es suposición, -(으)ㄹ 정도로 grado, -(으)ㄹ 만큼 medida — ninguno significa "solo".',
      'Le sens restrictif « rien que X » exige -(으)ㄹ 뿐이다 (ici 뿐이지, en contraste avec 다른 뜻은 없다) ; -(으)ㄹ 텐데 est une supposition, -(으)ㄹ 정도로 un degré, -(으)ㄹ 만큼 une mesure — aucun ne signifie « seulement ».',
      'O sentido restritivo "apenas X, nada mais" exige -(으)ㄹ 뿐이다 (aqui 뿐이지, em contraste com 다른 뜻은 없다); -(으)ㄹ 텐데 é suposição, -(으)ㄹ 정도로 grau, -(으)ㄹ 만큼 medida — nenhum significa "só".',
      'ความหมายจำกัด "แค่ X เท่านั้น ไม่มีอะไรมากกว่า" ต้องใช้ -(으)ㄹ 뿐이다 (ที่นี่คือ 뿐이지 คู่กับประโยค 다른 뜻은 없다); -(으)ㄹ 텐데 เป็นการคาดเดา, -(으)ㄹ 정도로 บอกระดับ, -(으)ㄹ 만큼 บอกขนาด ล้วนไม่ได้แปลว่า "แค่"',
      'Makna pembatas "hanya X, tak lebih" butuh -(으)ㄹ 뿐이다 (di sini 뿐이지, kontras dengan klausa 다른 뜻은 없다); -(으)ㄹ 텐데 dugaan, -(으)ㄹ 정도로 derajat, -(으)ㄹ 만큼 ukuran — tak ada yang berarti "hanya".',
      'Nghĩa giới hạn "chỉ X mà thôi" cần -(으)ㄹ 뿐이다 (ở đây là 뿐이지, đối với mệnh đề 다른 뜻은 없다); -(으)ㄹ 텐데 là suy đoán, -(으)ㄹ 정도로 là mức độ, -(으)ㄹ 만큼 là chừng mực — không cái nào nghĩa là "chỉ".',
      '「ただ〜だけだ」という限定には -(으)ㄹ 뿐이다（ここでは 다른 뜻은 없다 と対の 뿐이지）が必要。-(으)ㄹ 텐데 は推量、-(으)ㄹ 정도로 は程度、-(으)ㄹ 만큼 は度合いで「〜だけ」を表さない。',
    ),
  },
  {
    ko: '에 불과하다',
    sentence: '지금 보이는 이 성과는 아직 시작{} 갈 길이 멀어요.',
    answer: '에 불과해서',
    distractors: ['에 대해서', '에 비해서', '에 의해서'],
    trans: L(
      'This result you see now is no more than a beginning, so there’s still a long way to go.',
      'Este resultado que se ve ahora no es más que un comienzo, así que aún queda un largo camino.',
      'Ce résultat que l’on voit maintenant n’est qu’un début, il reste donc un long chemin.',
      'Este resultado que se vê agora não passa de um começo, então ainda há um longo caminho.',
      'ผลงานที่เห็นตอนนี้เป็นเพียงจุดเริ่มต้นเท่านั้น หนทางยังอีกยาวไกล',
      'Hasil yang terlihat sekarang ini tidak lebih dari permulaan, jadi jalannya masih panjang.',
      'Thành quả thấy được bây giờ chẳng qua chỉ là khởi đầu nên đường còn dài.',
      '今見えているこの成果はまだ始まりにすぎず、先は長いです。',
    ),
    why: L(
      'Minimizing a noun to "no more than" requires 에 불과하다 (here causal 불과해서); 에 대해서 means "about", 에 비해서 "compared to", 에 의해서 "by means of" — none minimizes.',
      'Minimizar un sustantivo a "no más que" exige 에 불과하다 (aquí causal 불과해서); 에 대해서 es "acerca de", 에 비해서 "en comparación con", 에 의해서 "por" — ninguno minimiza.',
      'Réduire un nom à « ne … qu’un » exige 에 불과하다 (ici causal 불과해서) ; 에 대해서 = « à propos de », 에 비해서 = « par rapport à », 에 의해서 = « au moyen de » — aucun ne minimise.',
      'Minimizar um substantivo a "não passa de" exige 에 불과하다 (aqui causal 불과해서); 에 대해서 é "sobre", 에 비해서 "em comparação com", 에 의해서 "por meio de" — nenhum minimiza.',
      'การลดทอนคำนามให้เป็น "เพียงแค่" ต้องใช้ 에 불과하다 (ที่นี่คือรูปเหตุ 불과해서); 에 대해서 แปลว่า "เกี่ยวกับ", 에 비해서 "เมื่อเทียบกับ", 에 의해서 "โดย" ล้วนไม่ได้ลดทอน',
      'Mengecilkan nomina menjadi "tidak lebih dari" butuh 에 불과하다 (di sini bentuk sebab 불과해서); 에 대해서 = "tentang", 에 비해서 = "dibandingkan", 에 의해서 = "oleh" — tak ada yang mengecilkan.',
      'Hạ thấp một danh từ thành "chẳng qua chỉ là" cần 에 불과하다 (ở đây là dạng nguyên nhân 불과해서); 에 대해서 = "về", 에 비해서 = "so với", 에 의해서 = "bằng/bởi" — không cái nào hạ thấp.',
      '名詞を「〜にすぎない」と低く言うには 에 불과하다（ここでは原因の 불과해서）が必要。에 대해서 は「〜について」、에 비해서 は「〜に比べて」、에 의해서 は「〜によって」で最小化しない。',
    ),
  },
  {
    ko: '-(으)ㄴ/는 탓에',
    sentence: '어젯밤에 늦게 잔 {} 오늘 하루 종일 피곤했어요.',
    answer: '탓에',
    distractors: ['덕분에', '대신에', '김에'],
    trans: L(
      'Because I went to bed late last night, I was tired all day today.',
      'Por culpa de acostarme tarde anoche, hoy estuve cansado todo el día.',
      'À cause de m’être couché tard hier soir, j’ai été fatigué toute la journée.',
      'Por culpa de ter dormido tarde ontem à noite, fiquei cansado o dia todo hoje.',
      'เพราะเมื่อคืนนอนดึก วันนี้เลยเหนื่อยทั้งวัน',
      'Gara-gara tidur larut tadi malam, hari ini saya lelah seharian.',
      'Vì tối qua ngủ muộn nên hôm nay tôi mệt cả ngày.',
      '昨夜遅く寝たせいで、今日は一日中疲れていました。',
    ),
    why: L(
      'A negative outcome blamed on a cause needs -(으)ㄴ/는 탓에; -(으)ㄴ/는 덕분에 credits a positive cause (wrong polarity), -는 대신에 means "instead of", -(으)ㄴ/는 김에 "while at it" — none assigns blame for a bad result.',
      'Un resultado negativo achacado a una causa exige -(으)ㄴ/는 탓에; -(으)ㄴ/는 덕분에 atribuye una causa positiva (polaridad errónea), -는 대신에 es "en vez de", -(으)ㄴ/는 김에 "ya que estoy" — ninguno culpa por un mal resultado.',
      'Un résultat négatif imputé à une cause exige -(으)ㄴ/는 탓에 ; -(으)ㄴ/는 덕분에 attribue une cause positive (mauvaise polarité), -는 대신에 = « au lieu de », -(으)ㄴ/는 김에 « tant qu’à faire » — aucun n’impute un mauvais résultat.',
      'Um resultado negativo atribuído a uma causa exige -(으)ㄴ/는 탓에; -(으)ㄴ/는 덕분에 credita uma causa positiva (polaridade errada), -는 대신에 é "em vez de", -(으)ㄴ/는 김에 "já que" — nenhum atribui culpa por mau resultado.',
      'ผลลัพธ์เชิงลบที่โทษว่าเกิดจากเหตุต้องใช้ -(으)ㄴ/는 탓에; -(으)ㄴ/는 덕분에 ยกความดีให้เหตุเชิงบวก (ขั้วผิด), -는 대신에 แปลว่า "แทนที่จะ", -(으)ㄴ/는 김에 "ในเมื่อกำลัง" ล้วนไม่ใช่การโทษผลร้าย',
      'Hasil negatif yang disalahkan pada suatu sebab butuh -(으)ㄴ/는 탓에; -(으)ㄴ/는 덕분에 memuji sebab positif (polaritas salah), -는 대신에 = "alih-alih", -(으)ㄴ/는 김에 = "mumpung" — tak ada yang menyalahkan hasil buruk.',
      'Kết quả tiêu cực bị quy cho một nguyên nhân cần -(으)ㄴ/는 탓에; -(으)ㄴ/는 덕분에 ghi công cho nguyên nhân tích cực (sai cực), -는 대신에 = "thay vì", -(으)ㄴ/는 김에 = "nhân tiện" — không cái nào đổ lỗi cho kết quả xấu.',
      '悪い結果を原因のせいにするには -(으)ㄴ/는 탓에 が必要。-(으)ㄴ/는 덕분에 は良い原因への感謝で極性が逆、-는 대신에 は「〜の代わりに」、-(으)ㄴ/는 김에 は「〜のついでに」で、悪い結果のせいにできない。',
    ),
  },
  {
    ko: '-(으)로 인해(서)',
    sentence: '갑작스러운 폭우{} 도로 곳곳이 통제되었습니다.',
    answer: '로 인해',
    distractors: ['를 위해', '에 따라', '를 통해'],
    trans: L(
      'Due to the sudden downpour, roads were closed in many places.',
      'Debido al aguacero repentino, varias carreteras fueron cerradas.',
      'En raison de l’averse soudaine, des routes ont été fermées en plusieurs endroits.',
      'Devido à chuva torrencial repentina, estradas foram interditadas em vários pontos.',
      'เนื่องจากฝนตกหนักกะทันหัน ถนนหลายจุดจึงถูกปิด',
      'Akibat hujan deras mendadak, ruas-ruas jalan ditutup.',
      'Do trận mưa lớn bất ngờ, nhiều đoạn đường đã bị phong tỏa.',
      '突然の豪雨により、各所で道路が通行止めになりました。',
    ),
    why: L(
      'A formal written cause-and-effect needs -(으)로 인해(서); -을/를 위해 marks purpose ("for the sake of"), -에 따라 "according to", -을/를 통해 "through (a medium)" — none states the causing factor.',
      'Una relación causa-efecto formal exige -(으)로 인해(서); -을/를 위해 marca propósito, -에 따라 "según", -을/를 통해 "a través de" — ninguno expresa el factor causante.',
      'Une relation cause-effet formelle exige -(으)로 인해(서) ; -을/를 위해 marque le but, -에 따라 « selon », -을/를 통해 « par l’intermédiaire de » — aucun n’énonce la cause.',
      'Uma relação causa-efeito formal exige -(으)로 인해(서); -을/를 위해 marca propósito, -에 따라 "conforme", -을/를 통해 "por meio de" — nenhum expressa o fator causador.',
      'ความสัมพันธ์เหตุ-ผลแบบทางการต้องใช้ -(으)로 인해(서); -을/를 위해 บอกจุดประสงค์, -에 따라 "ตามที่", -을/를 통해 "ผ่านทาง" ล้วนไม่บอกตัวเหตุ',
      'Hubungan sebab-akibat formal butuh -(으)로 인해(서); -을/를 위해 menandai tujuan, -에 따라 "menurut", -을/를 통해 "melalui" — tak ada yang menyatakan faktor penyebab.',
      'Quan hệ nhân-quả trang trọng cần -(으)로 인해(서); -을/를 위해 nêu mục đích, -에 따라 "theo", -을/를 통해 "thông qua" — không cái nào nêu yếu tố gây ra.',
      '改まった因果関係には -(으)로 인해(서) が必要。-을/를 위해 は目的、-에 따라 は「〜に従って」、-을/를 통해 は「〜を通じて」で原因を表さない。',
    ),
  },
  {
    ko: '-고자',
    sentence: '더 나은 사회를 만들{} 저희는 끊임없이 노력하고 있습니다.',
    answer: '고자',
    distractors: ['거나', '더니', '느라고'],
    trans: L(
      'In order to build a better society, we are striving ceaselessly.',
      'Con el propósito de construir una sociedad mejor, nos esforzamos sin cesar.',
      'Afin de bâtir une société meilleure, nous nous efforçons sans relâche.',
      'A fim de construir uma sociedade melhor, esforçamo-nos incessantemente.',
      'เพื่อสร้างสังคมที่ดีกว่า พวกเราพยายามอย่างไม่หยุดหย่อน',
      'Demi membangun masyarakat yang lebih baik, kami berupaya tanpa henti.',
      'Nhằm xây dựng một xã hội tốt đẹp hơn, chúng tôi không ngừng nỗ lực.',
      'より良い社会を作るべく、私どもは絶えず努力しております。',
    ),
    why: L(
      'A formal statement of purpose ("in order to") in a written register needs -고자; -거나 lists options, -더니 is observed past, -느라고 gives a cause that hinders — none expresses a formal goal.',
      'Una declaración formal de propósito ("con el fin de") exige -고자; -거나 enumera, -더니 es pasado observado, -느라고 da una causa que impide — ninguno expresa una meta formal.',
      'Une déclaration formelle de but (« afin de ») exige -고자 ; -거나 énumère, -더니 = passé observé, -느라고 = cause qui entrave — aucun n’exprime un objectif formel.',
      'Uma declaração formal de propósito ("a fim de") exige -고자; -거나 enumera, -더니 é passado observado, -느라고 dá causa que atrapalha — nenhum exprime meta formal.',
      'การระบุจุดประสงค์แบบทางการ ("เพื่อที่จะ") ต้องใช้ -고자; -거나 บอกทางเลือก, -더니 เป็นอดีตที่สังเกต, -느라고 เป็นเหตุที่ขัดขวาง ล้วนไม่สื่อเป้าหมายทางการ',
      'Pernyataan tujuan formal ("demi/agar") butuh -고자; -거나 mendaftar, -더니 lampau yang diamati, -느라고 sebab yang menghambat — tak ada yang menyatakan tujuan formal.',
      'Cách nêu mục đích trang trọng ("nhằm để") cần -고자; -거나 liệt kê, -더니 là quá khứ chứng kiến, -느라고 là nguyên nhân cản trở — không cái nào nêu mục tiêu trang trọng.',
      '改まった文体での目的（「〜すべく」）には -고자 が必要。-거나 は選択、-더니 は観察した過去、-느라고 は妨げとなる原因で、改まった目的を表さない。',
    ),
  },
  {
    ko: '-(으)ㄴ/는 나머지',
    sentence: '너무 긴장한 {} 준비한 내용을 다 잊어버렸어요.',
    answer: '나머지',
    distractors: ['대로', '만큼', '데다가'],
    trans: L(
      'I was so nervous that I forgot everything I had prepared.',
      'Estaba tan nervioso que olvidé todo lo que había preparado.',
      'J’étais tellement nerveux que j’ai oublié tout ce que j’avais préparé.',
      'Fiquei tão nervoso que esqueci tudo o que havia preparado.',
      'เพราะตื่นเต้นมากจนลืมเนื้อหาที่เตรียมไว้หมดเลย',
      'Saking gugupnya, saya lupa semua yang sudah saya siapkan.',
      'Vì quá hồi hộp nên tôi quên hết những gì đã chuẩn bị.',
      '緊張のあまり、準備した内容をすべて忘れてしまいました。',
    ),
    why: L(
      'An excessive state spilling into an unexpected result needs -(으)ㄴ/는 나머지; -(으)ㄴ/는 대로 means "as/according to", -(으)ㄴ/는 만큼 "as much as", -(으)ㄴ데다가 "on top of that" — none conveys "so much that".',
      'Un estado excesivo que desemboca en un resultado inesperado exige -(으)ㄴ/는 나머지; -(으)ㄴ/는 대로 es "tal como", -(으)ㄴ/는 만큼 "tanto como", -(으)ㄴ데다가 "además" — ninguno transmite "tanto que".',
      'Un état excessif débouchant sur un résultat inattendu exige -(으)ㄴ/는 나머지 ; -(으)ㄴ/는 대로 = « selon », -(으)ㄴ/는 만큼 = « autant que », -(으)ㄴ데다가 = « en plus » — aucun ne rend « à tel point que ».',
      'Um estado excessivo que resulta em algo inesperado exige -(으)ㄴ/는 나머지; -(으)ㄴ/는 대로 é "conforme", -(으)ㄴ/는 만큼 "tanto quanto", -(으)ㄴ데다가 "além disso" — nenhum traz "tanto que".',
      'สภาพที่มากเกินจนเกิดผลไม่คาดคิดต้องใช้ -(으)ㄴ/는 나머지; -(으)ㄴ/는 대로 แปลว่า "ตามที่", -(으)ㄴ/는 만큼 "เท่ากับ", -(으)ㄴ데다가 "ยิ่งไปกว่านั้น" ล้วนไม่สื่อ "มากจน"',
      'Keadaan berlebihan yang berujung pada hasil tak terduga butuh -(으)ㄴ/는 나머지; -(으)ㄴ/는 대로 = "sesuai", -(으)ㄴ/는 만큼 = "sebanyak", -(으)ㄴ데다가 = "ditambah lagi" — tak ada yang berarti "saking ... sampai".',
      'Trạng thái thái quá dẫn đến kết quả bất ngờ cần -(으)ㄴ/는 나머지; -(으)ㄴ/는 대로 = "theo đúng", -(으)ㄴ/는 만큼 = "bằng chừng", -(으)ㄴ데다가 = "thêm vào đó" — không cái nào diễn tả "quá ... đến nỗi".',
      '度が過ぎて思わぬ結果になるには -(으)ㄴ/는 나머지 が必要。-(으)ㄴ/는 대로 は「〜のとおり」、-(으)ㄴ/는 만큼 は「〜だけ」、-(으)ㄴ데다가 は「〜うえに」で「〜のあまり」を表さない。',
    ),
  },
  {
    ko: '-는 커녕',
    sentence: '도와주기는 {} 오히려 일을 더 망쳐 놓았어요.',
    answer: '커녕',
    distractors: ['는데도', '거든요', '으려고'],
    trans: L(
      'Far from helping, they actually made the work even worse.',
      'Lejos de ayudar, encima estropeó más el trabajo.',
      'Loin d’aider, il a au contraire encore plus gâché le travail.',
      'Longe de ajudar, na verdade estragou ainda mais o trabalho.',
      'จะช่วยก็ไม่ช่วย กลับทำให้งานพังยิ่งกว่าเดิม',
      'Jangankan membantu, malah membuat pekerjaannya tambah berantakan.',
      'Đừng nói là giúp, ngược lại còn làm hỏng việc thêm.',
      '手伝うどころか、かえって仕事をもっとめちゃくちゃにしました。',
    ),
    why: L(
      'A strong "far from X — the opposite happened" reversal needs -는 커녕 (after 도와주기는); -는데도 is "even though", -거든요 gives a reason, -(으)려고 marks intent — none flips to the negative extreme.',
      'Una inversión fuerte "lejos de X, lo contrario" exige -는 커녕 (tras 도와주기는); -는데도 es "aunque", -거든요 da una razón, -(으)려고 marca intención — ninguno produce el giro negativo.',
      'Une inversion forte « loin de X, le contraire » exige -는 커녕 (après 도와주기는) ; -는데도 = « bien que », -거든요 donne une raison, -(으)려고 marque l’intention — aucun ne produit le retournement.',
      'Uma inversão forte "longe de X, o oposto" exige -는 커녕 (após 도와주기는); -는데도 é "mesmo que", -거든요 dá razão, -(으)려고 marca intenção — nenhum produz a virada negativa.',
      'การพลิกกลับอย่างแรง "ไม่ใช่แค่ไม่ X แต่กลับตรงข้าม" ต้องใช้ -는 커녕 (หลัง 도와주기는); -는데도 แปลว่า "แม้ว่า", -거든요 บอกเหตุผล, -(으)려고 บอกความตั้งใจ ล้วนไม่ทำให้พลิกกลับ',
      'Pembalikan kuat "jangankan X, malah sebaliknya" butuh -는 커녕 (setelah 도와주기는); -는데도 = "meskipun", -거든요 memberi alasan, -(으)려고 menandai niat — tak ada yang membalik ke ekstrem negatif.',
      'Sự đảo ngược mạnh "đừng nói X, ngược lại còn ..." cần -는 커녕 (sau 도와주기는); -는데도 = "dù vậy", -거든요 nêu lý do, -(으)려고 nêu ý định — không cái nào tạo cú lật ngược.',
      '「〜どころか、むしろ逆」という強い反転には -는 커녕（도와주기는 の後）が必要。-는데도 は「〜のに」、-거든요 は理由、-(으)려고 は意図で反転を作れない。',
    ),
  },
  {
    ko: '-기 십상이다',
    sentence: '그렇게 급하게 운전하면 사고가 나{}.',
    answer: '기 십상이에요',
    distractors: ['기 나름이에요', '기 일쑤예요', '기 그지없어요'],
    trans: L(
      'If you drive in such a hurry, you’re bound to end up in an accident.',
      'Si conduces con tanta prisa, es muy fácil que acabes en un accidente.',
      'Si tu conduis aussi vite, tu as toutes les chances de finir par avoir un accident.',
      'Se você dirige com tanta pressa, é bem fácil acabar em um acidente.',
      'ถ้าขับรถรีบขนาดนั้น มีโอกาสสูงที่จะเกิดอุบัติเหตุ',
      'Kalau menyetir seterburu itu, mudah sekali berakhir kecelakaan.',
      'Lái xe vội vàng như thế thì dễ gặp tai nạn lắm.',
      'そんなに急いで運転すると、事故を起こしがちです。',
    ),
    why: L(
      'A conditional warning that a bad outcome is highly likely needs -기 십상이다; -기 나름이다 means "depends on how" (no warning), -기 일쑤이다 reports a past recurring habit (clashes with the future 운전하면), -기 그지없다 attaches only to emotion/state adjectives (그립기 그지없다), never to the eventive 사고가 나다 — only 십상이다 gives the "bound to (badly)" warning.',
      'Una advertencia condicional de que un mal resultado es muy probable exige -기 십상이다; -기 나름이다 es "depende de cómo" (sin advertencia), -기 일쑤이다 narra un hábito pasado recurrente (choca con el futuro 운전하면), -기 그지없다 solo se une a adjetivos de emoción/estado (그립기 그지없다), nunca al eventivo 사고가 나다 — solo 십상이다 da la advertencia.',
      'Un avertissement conditionnel qu’un mauvais résultat est très probable exige -기 십상이다 ; -기 나름이다 = « ça dépend » (pas d’avertissement), -기 일쑤이다 = habitude passée répétée (incompatible avec le futur 운전하면), -기 그지없다 ne s’attache qu’aux adjectifs d’émotion/état (그립기 그지없다), jamais à l’événementiel 사고가 나다 — seul 십상이다 avertit.',
      'Um aviso condicional de que um mau resultado é muito provável exige -기 십상이다; -기 나름이다 é "depende de como" (sem aviso), -기 일쑤이다 narra um hábito passado recorrente (destoa do futuro 운전하면), -기 그지없다 só se liga a adjetivos de emoção/estado (그립기 그지없다), nunca ao eventivo 사고가 나다 — só 십상이다 dá o aviso.',
      'คำเตือนแบบมีเงื่อนไขว่าผลร้ายมีโอกาสสูงต้องใช้ -기 십상이다; -기 나름이다 แปลว่า "ขึ้นอยู่กับวิธี" (ไม่ใช่คำเตือน), -기 일쑤이다 เล่านิสัยซ้ำในอดีต (ขัดกับอนาคต 운전하면), -기 그지없다 ใช้กับคำคุณศัพท์บอกอารมณ์/สภาพเท่านั้น (그립기 그지없다) ไม่ใช้กับ 사고가 나다 ที่เป็นเหตุการณ์ มีแต่ 십상이다 ที่เป็นคำเตือน',
      'Peringatan bersyarat bahwa hasil buruk sangat mungkin butuh -기 십상이다; -기 나름이다 = "tergantung cara" (bukan peringatan), -기 일쑤이다 menceritakan kebiasaan lampau berulang (bentrok dengan futur 운전하면), -기 그지없다 hanya melekat pada adjektiva emosi/keadaan (그립기 그지없다), bukan pada peristiwa 사고가 나다 — hanya 십상이다 yang memberi peringatan.',
      'Lời cảnh báo có điều kiện rằng kết quả xấu rất dễ xảy ra cần -기 십상이다; -기 나름이다 = "tùy cách" (không cảnh báo), -기 일쑤이다 kể thói quen lặp lại trong quá khứ (nghịch với tương lai 운전하면), -기 그지없다 chỉ gắn với tính từ cảm xúc/trạng thái (그립기 그지없다), không gắn với sự kiện 사고가 나다 — chỉ 십상이다 mới là lời cảnh báo.',
      '悪い結果になりやすいという条件付きの警告には -기 십상이다 が必要。-기 나름이다 は「やり方次第」で警告ではなく、-기 일쑤이다 は過去の繰り返しの習慣で未来の 운전하면 と矛盾、-기 그지없다 は感情・状態の形容詞（그립기 그지없다）にしか付かず事象の 사고가 나다 には付かない。警告になるのは 십상이다 のみ。',
    ),
  },
  {
    ko: '-(으)ㄴ 끝에',
    sentence: '오랜 시간 고민한 {} 마침내 유학을 가기로 결정했어요.',
    answer: '끝에',
    distractors: ['김에', '나머지', '데다가'],
    trans: L(
      'After a long time of deliberation, I finally decided to go study abroad.',
      'Tras mucho tiempo de reflexión, finalmente decidí ir a estudiar al extranjero.',
      'Au bout d’une longue réflexion, j’ai enfin décidé de partir étudier à l’étranger.',
      'Depois de muito tempo refletindo, finalmente decidi ir estudar fora.',
      'หลังจากครุ่นคิดอยู่นาน ในที่สุดก็ตัดสินใจไปเรียนต่อต่างประเทศ',
      'Setelah lama berpikir, akhirnya saya memutuskan untuk studi ke luar negeri.',
      'Sau một thời gian dài đắn đo, cuối cùng tôi đã quyết định đi du học.',
      '長い間悩んだ末に、ついに留学に行くことに決めました。',
    ),
    why: L(
      'A decision reached after a prolonged process needs -(으)ㄴ 끝에 (with 마침내); -(으)ㄴ/는 김에 means "while at it", -(으)ㄴ/는 나머지 "so much that (excess)", -(으)ㄴ데다가 "on top of that" — only 끝에 marks the outcome of a long effort.',
      'Una decisión alcanzada tras un proceso prolongado exige -(으)ㄴ 끝에 (con 마침내); -(으)ㄴ/는 김에 es "ya que estoy", -(으)ㄴ/는 나머지 "tanto que", -(으)ㄴ데다가 "además" — solo 끝에 marca el desenlace de un largo esfuerzo.',
      'Une décision prise au terme d’un long processus exige -(으)ㄴ 끝에 (avec 마침내) ; -(으)ㄴ/는 김에 = « tant qu’à faire », -(으)ㄴ/는 나머지 = « à force de », -(으)ㄴ데다가 = « en plus » — seul 끝에 marque l’aboutissement.',
      'Uma decisão tomada após um processo prolongado exige -(으)ㄴ 끝에 (com 마침내); -(으)ㄴ/는 김에 é "já que", -(으)ㄴ/는 나머지 "de tanto", -(으)ㄴ데다가 "além disso" — só 끝에 marca o desfecho de um longo esforço.',
      'การตัดสินใจที่ได้หลังกระบวนการยาวนานต้องใช้ -(으)ㄴ 끝에 (คู่กับ 마침내); -(으)ㄴ/는 김에 แปลว่า "ในเมื่อกำลัง", -(으)ㄴ/는 나머지 "มากจน", -(으)ㄴ데다가 "ยิ่งไปกว่านั้น" มีแต่ 끝에 ที่บอกผลของความพยายามอันยาวนาน',
      'Keputusan yang dicapai setelah proses panjang butuh -(으)ㄴ 끝에 (dengan 마침내); -(으)ㄴ/는 김에 = "mumpung", -(으)ㄴ/는 나머지 = "saking", -(으)ㄴ데다가 = "ditambah lagi" — hanya 끝에 yang menandai hasil dari upaya panjang.',
      'Một quyết định đạt được sau quá trình dài cần -(으)ㄴ 끝에 (đi với 마침내); -(으)ㄴ/는 김에 = "nhân tiện", -(으)ㄴ/는 나머지 = "quá đến nỗi", -(으)ㄴ데다가 = "thêm vào đó" — chỉ 끝에 mới nêu kết cục của nỗ lực lâu dài.',
      '長い過程の末の決定には -(으)ㄴ 끝에（마침내 と共に）が必要。-(으)ㄴ/는 김에 は「〜のついでに」、-(으)ㄴ/는 나머지 は「〜のあまり」、-(으)ㄴ데다가 は「〜うえに」で、長い努力の帰結を表すのは 끝에 のみ。',
    ),
  },
]
