// app/seed/cloze/n6.ts
import type { ClozeItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-6 grammar-pattern cloze items (choose the literary/formal pattern that
 * fits the blank). ko matches grammars-n6.ts verbatim. Drafted + Korean-lens
 * adversarially verified (single-correct-answer crux). Korean wife native
 * review = documented final gate.
 */

export const N6_CLOZE: ClozeItem[] = [
  {
    ko: '-ㄴ들',
    sentence: '이제 와서 후회{} 무슨 소용이 있겠어요?',
    answer: '한들',
    distractors: ['하니까', '하지만', '하느라고'],
    trans: L(
      'What good would it do to regret it now?',
      '¿De qué serviría arrepentirse a estas alturas?',
      'Même si tu le regrettes maintenant, à quoi bon ?',
      'De que adiantaria se arrepender a esta altura?',
      'มาเสียใจตอนนี้จะมีประโยชน์อะไร',
      'Apa gunanya menyesal sekarang?',
      'Đến giờ này có hối hận thì ích gì?',
      '今さら後悔したところで何の意味があるでしょう。',
    ),
    why: L(
      'The rhetorical "even if … what good?" frame (무슨 소용이 있겠어요?) forces -ㄴ들; -니까 states a real cause, -지만 a flat contrast, -느라고 a "busy doing X" cause — none carries the futile-rhetorical force the rhetorical question demands.',
      'El marco retórico "aunque … ¿de qué sirve?" (무슨 소용이 있겠어요?) exige -ㄴ들; -니까 da una causa real, -지만 un contraste neutro, -느라고 una causa de "estar ocupado haciendo X" — ninguno aporta la fuerza retórica de inutilidad que pide la pregunta.',
      'Le cadre rhétorique « même si … à quoi bon ? » (무슨 소용이 있겠어요?) impose -ㄴ들 ; -니까 énonce une cause réelle, -지만 un contraste plat, -느라고 une cause « en train de faire X » — aucun ne porte la force rhétorique de vanité exigée.',
      'O molde retórico "mesmo que … de que adianta?" (무슨 소용이 있겠어요?) exige -ㄴ들; -니까 dá causa real, -지만 contraste neutro, -느라고 uma causa de "estar ocupado fazendo X" — nenhum carrega a força retórica de inutilidade que a pergunta pede.',
      'โครงสร้างเชิงวาทศิลป์ "ถึงจะ … ก็ไร้ประโยชน์" (무슨 소용이 있겠어요?) บังคับ -ㄴ들; -니까 บอกเหตุจริง, -지만 ขัดแย้งเฉย ๆ, -느라고 เหตุแบบ "มัวแต่ทำ X" ไม่มีอันใดให้นํ้าเสียงเชิงวาทศิลป์ที่ว่าทำไปก็เปล่า',
      'Kerangka retoris "meskipun … apa gunanya?" (무슨 소용이 있겠어요?) mengharuskan -ㄴ들; -니까 menyatakan sebab nyata, -지만 kontras datar, -느라고 sebab "sibuk melakukan X" — tak ada yang membawa nuansa retoris kesia-siaan yang dituntut.',
      'Khung tu từ "dù … thì ích gì?" (무슨 소용이 있겠어요?) buộc -ㄴ들; -니까 nêu nguyên nhân thật, -지만 tương phản phẳng, -느라고 nguyên nhân "mải lo làm X" — không cái nào mang sắc thái tu từ vô ích mà câu hỏi đòi.',
      '反語の枠組み「〜したところで何の意味が」（무슨 소용이 있겠어요?）が -ㄴ들 を要求。-니까 は実際の原因、-지만 は単なる逆接、-느라고 は「〜するのに忙しくて」の原因で、いずれも反語の無意味さの含みを持たない。',
    ),
  },
  {
    ko: '-(으)ㄹ망정',
    sentence: '굶어 죽{} 남의 것에 손을 대지는 않겠습니다.',
    answer: '을망정',
    distractors: ['으니까', '어서', '으려고'],
    trans: L(
      "Even if I starve to death, I will not lay a hand on what belongs to others.",
      'Aunque me muera de hambre, no tocaré lo ajeno.',
      "Quitte à mourir de faim, je ne toucherai pas au bien d'autrui.",
      'Mesmo que eu morra de fome, não porei a mão no que é dos outros.',
      'ต่อให้อดตาย ก็จะไม่แตะต้องของของคนอื่น',
      'Sekalipun mati kelaparan, saya tidak akan menyentuh milik orang lain.',
      'Thà chết đói tôi cũng không đụng đến của người khác.',
      'たとえ飢え死にしようとも、人の物に手を出しはしません。',
    ),
    why: L(
      'A defiant moral resolve ("even if it means the worst, I still won\'t …") requires -(으)ㄹ망정; -(으)니까 makes starving a reason, -아/어서 a cause/sequence, -(으)려고 a purpose — none expresses the worst-case concession with firm refusal.',
      'Una resolución moral desafiante ("aunque sea lo peor, aun así no …") exige -(으)ㄹ망정; -(으)니까 convierte el morir de hambre en razón, -아/어서 en causa/secuencia, -(으)려고 en propósito — ninguno expresa la concesión extrema con rechazo firme.',
      'Une résolution morale de défi (« quitte au pire, je refuse quand même ») exige -(으)ㄹ망정 ; -(으)니까 fait de la faim une cause, -아/어서 une cause/suite, -(으)려고 un but — aucun n\'exprime la concession extrême avec refus ferme.',
      'Uma resolução moral desafiadora ("ainda que seja o pior, mesmo assim não …") exige -(으)ㄹ망정; -(으)니까 torna a fome razão, -아/어서 causa/sequência, -(으)려고 propósito — nenhum expressa a concessão extrema com recusa firme.',
      'ความมุ่งมั่นทางคุณธรรมเชิงท้าทาย ("ต่อให้แย่ที่สุด ก็ยังไม่…") ต้องใช้ -(으)ㄹ망정; -(으)니까 ทำให้การอดตายเป็นเหตุ, -아/어서 เหตุ/ลำดับ, -(으)려고 จุดประสงค์ ไม่มีอันใดสื่อการยอมขั้นสุดพร้อมการปฏิเสธหนักแน่น',
      'Tekad moral menantang ("sekalipun yang terburuk, tetap tidak …") memerlukan -(으)ㄹ망정; -(으)니까 menjadikan kelaparan sebab, -아/어서 sebab/urutan, -(으)려고 tujuan — tak ada yang mengungkap konsesi ekstrem dengan penolakan tegas.',
      'Quyết tâm đạo đức ngang ngạnh ("thà chịu điều tệ nhất vẫn không …") cần -(으)ㄹ망정; -(으)니까 biến chết đói thành nguyên nhân, -아/어서 nguyên nhân/trình tự, -(으)려고 mục đích — không cái nào diễn đạt nhượng bộ cực độ kèm khước từ dứt khoát.',
      '挑むような道徳的決意（「最悪でも、それでも〜しない」）には -(으)ㄹ망정 が必要。-(으)니까 は飢えを原因に、-아/어서 は原因・連続に、-(으)려고 は目的にしてしまい、断固たる拒否を伴う極限の譲歩を表せない。',
    ),
  },
  {
    ko: '-기로서니',
    sentence: '아무리 바쁘{} 부모님 전화 한 통 못 받을까?',
    answer: '기로서니',
    distractors: ['기 때문에', '기는커녕', '기에'],
    trans: L(
      'No matter how busy you are, can you not even take one call from your parents?',
      'Por muy ocupado que estés, ¿no puedes ni atender una llamada de tus padres?',
      "Si occupé que tu sois, tu ne peux même pas répondre à un appel de tes parents ?",
      'Por mais ocupado que esteja, não dá nem para atender uma ligação dos pais?',
      'ต่อให้ยุ่งแค่ไหน รับโทรศัพท์พ่อแม่สักสายยังไม่ได้เลยหรือ',
      'Sesibuk apa pun, tidak bisa mengangkat satu telepon dari orang tua?',
      'Dù bận đến mấy, không nghe nổi một cuộc gọi của bố mẹ sao?',
      'いくら忙しいからって、親からの電話一本も取れないの？',
    ),
    why: L(
      'The reproachful "just because you\'re busy, surely that\'s no excuse to …" pairs with 아무리 and a rhetorical question → -기로서니; -기 때문에 grants the reason as valid, -기는커녕 means "far from," -기에 gives a plain cause — none rebukes by minimizing the excuse.',
      'El reproche "solo porque estás ocupado, eso no justifica …" se combina con 아무리 y una pregunta retórica → -기로서니; -기 때문에 acepta la razón como válida, -기는커녕 significa "lejos de", -기에 da una causa llana — ninguno reprocha minimizando la excusa.',
      'Le reproche « ce n\'est pas parce que tu es occupé que … » va avec 아무리 et une question rhétorique → -기로서니 ; -기 때문에 valide la raison, -기는커녕 signifie « loin de », -기에 donne une cause neutre — aucun ne réprimande en minimisant l\'excuse.',
      'A reprovação "só porque você está ocupado, isso não desculpa …" combina com 아무리 e pergunta retórica → -기로서니; -기 때문에 valida a razão, -기는커녕 significa "longe de", -기에 dá causa neutra — nenhum repreende minimizando a desculpa.',
      'การตำหนิ "แค่ยุ่ง ก็ไม่ใช่ข้ออ้างที่จะ…" เข้าคู่กับ 아무리 และคำถามเชิงวาทศิลป์ → -기로서니; -기 때문에 ยอมรับเหตุผลว่าถูก, -기는커녕 แปลว่า "ไม่ต้องพูดถึง", -기에 ให้เหตุเฉย ๆ ไม่มีอันใดตำหนิด้วยการลดทอนข้ออ้าง',
      'Teguran "hanya karena sibuk, itu bukan alasan untuk …" berpadu dengan 아무리 dan pertanyaan retoris → -기로서니; -기 때문에 mengesahkan alasan, -기는커녕 berarti "jangankan", -기에 memberi sebab datar — tak ada yang menegur dengan meremehkan alasan.',
      'Lời trách "chỉ vì bận thôi đâu phải cớ để …" đi với 아무리 và câu hỏi tu từ → -기로서니; -기 때문에 công nhận lý do, -기는커녕 nghĩa "đừng nói chi", -기에 nêu nguyên nhân phẳng — không cái nào trách bằng cách hạ thấp cái cớ.',
      '「いくら忙しいからといって、それを言い訳に〜」という咎めは 아무리 と反語に呼応し -기로서니 を要求。-기 때문에 は理由を正当化、-기는커녕 は「どころか」、-기에 は単なる原因で、言い訳を貶めて咎める働きがない。',
    ),
  },
  {
    ko: '-(으)로 말미암아',
    sentence: '오랜 가뭄{} 올해 농사를 완전히 망치고 말았다.',
    answer: '으로 말미암아',
    distractors: ['에 비하여', '을 비롯하여', '에 불과하여'],
    trans: L(
      "Owing to the prolonged drought, this year's harvest was completely ruined.",
      'A causa de la prolongada sequía, la cosecha de este año se arruinó por completo.',
      "En raison de la longue sécheresse, la récolte de cette année a été entièrement perdue.",
      'Em razão da prolongada seca, a colheita deste ano ficou totalmente arruinada.',
      'อันเนื่องมาจากภัยแล้งที่ยาวนาน ผลผลิตปีนี้จึงเสียหายโดยสิ้นเชิง',
      'Akibat kekeringan yang berkepanjangan, panen tahun ini benar-benar gagal.',
      'Do hạn hán kéo dài, vụ mùa năm nay hoàn toàn thất bát.',
      '長引く干ばつによって、今年の農作はすっかり台無しになってしまった。',
    ),
    why: L(
      'A high-register written cause leading to a result needs -(으)로 말미암아; -에 비하여 means "compared to," -을 비롯하여 "including," -에 불과하여 "being merely" — none is a causal connective, so only the cause marker fits the drought→ruin link.',
      'Una causa escrita de registro alto que lleva a un resultado pide -(으)로 말미암아; -에 비하여 es "en comparación con", -을 비롯하여 "incluyendo", -에 불과하여 "no siendo más que" — ninguno es conector causal, así que solo el marcador de causa une sequía→ruina.',
      'Une cause écrite de registre élevé menant à un résultat exige -(으)로 말미암아 ; -에 비하여 = « par rapport à », -을 비롯하여 = « y compris », -에 불과하여 = « n\'étant que » — aucun n\'est causal, seul le marqueur de cause relie sécheresse→perte.',
      'Uma causa escrita de registro alto que leva a um resultado exige -(으)로 말미암아; -에 비하여 é "em comparação com", -을 비롯하여 "incluindo", -에 불과하여 "não passando de" — nenhum é causal, só o marcador de causa liga seca→ruína.',
      'เหตุในภาษาเขียนระดับสูงที่นำไปสู่ผลต้องใช้ -(으)로 말미암아; -에 비하여 คือ "เมื่อเทียบกับ", -을 비롯하여 "รวมถึง", -에 불과하여 "เป็นเพียง" ไม่มีอันใดเป็นตัวเชื่อมเหตุ จึงมีแต่ตัวบอกเหตุที่เชื่อมภัยแล้ง→เสียหาย',
      'Sebab tulis beregister tinggi yang menuju hasil memerlukan -(으)로 말미암아; -에 비하여 berarti "dibanding", -을 비롯하여 "termasuk", -에 불과하여 "hanyalah" — tak ada yang konektif sebab, jadi hanya penanda sebab yang menautkan kekeringan→gagal.',
      'Một nguyên nhân văn viết trang trọng dẫn tới kết quả cần -(으)로 말미암아; -에 비하여 nghĩa "so với", -을 비롯하여 "bao gồm", -에 불과하여 "chỉ là" — không cái nào là liên từ nhân quả, nên chỉ dấu nguyên nhân nối hạn hán→thất bát.',
      '結果に至る文語の高い改まりの原因には -(으)로 말미암아 が必要。-에 비하여 は「比べて」、-을 비롯하여 は「をはじめ」、-에 불과하여 は「にすぎず」で、いずれも因果の接続ではなく、干ばつ→台無しを結ぶのは原因標識だけ。',
    ),
  },
  {
    ko: '-거니와',
    sentence: '그 식당은 음식 맛도 뛰어나{} 분위기 또한 아주 좋다.',
    answer: '거니와',
    distractors: ['더라도', '기는커녕', '다가는'],
    trans: L(
      'That restaurant not only has outstanding food but its atmosphere is also excellent.',
      'Ese restaurante no solo tiene una comida excelente, sino que su ambiente también es muy bueno.',
      "Ce restaurant a non seulement une cuisine remarquable, mais son ambiance est aussi excellente.",
      'Aquele restaurante não só tem comida excelente, como também um ambiente ótimo.',
      'ร้านนั้นไม่เพียงอาหารอร่อยเยี่ยม บรรยากาศก็ยังดีมากอีกด้วย',
      'Restoran itu tidak hanya masakannya luar biasa, suasananya pun sangat baik.',
      'Nhà hàng ấy không chỉ món ngon xuất sắc mà bầu không khí cũng rất tuyệt.',
      'あの店は料理の味も抜群なうえに、雰囲気もまたとても良い。',
    ),
    why: L(
      'The additive "not only … but also" (reinforced by 또한) needs the literary -거니와; -더라도 is concessive ("even if"), -기는커녕 reverses to "far from," -다가는 warns of a bad outcome — none simply adds a second positive trait.',
      'El aditivo "no solo … sino también" (reforzado por 또한) pide el literario -거니와; -더라도 es concesivo ("aunque"), -기는커녕 invierte a "lejos de", -다가는 advierte un mal desenlace — ninguno suma simplemente un segundo rasgo positivo.',
      'L\'additif « non seulement … mais aussi » (renforcé par 또한) exige le littéraire -거니와 ; -더라도 est concessif (« même si »), -기는커녕 inverse en « loin de », -다가는 avertit d\'une mauvaise issue — aucun n\'ajoute simplement un second trait positif.',
      'O aditivo "não só … como também" (reforçado por 또한) pede o literário -거니와; -더라도 é concessivo ("mesmo que"), -기는커녕 inverte para "longe de", -다가는 alerta para um mau desfecho — nenhum apenas soma um segundo traço positivo.',
      'การเสริม "ไม่เพียง … ยัง … อีกด้วย" (ย้ำด้วย 또한) ต้องใช้ -거니와 เชิงวรรณกรรม; -더라도 เป็นการยอม ("แม้"), -기는커녕 กลับเป็น "ไม่ต้องพูดถึง", -다가는 เตือนผลร้าย ไม่มีอันใดเพียงเพิ่มคุณสมบัติดีข้อที่สอง',
      'Penambah "tidak hanya … tetapi juga" (diperkuat 또한) memerlukan -거니와 sastrawi; -더라도 konsesif ("meskipun"), -기는커녕 membalik jadi "jangankan", -다가는 memperingatkan hasil buruk — tak ada yang sekadar menambah sifat positif kedua.',
      'Phép cộng thêm "không những … mà còn" (được 또한 củng cố) cần -거니와 văn chương; -더라도 là nhượng bộ ("dù"), -기는커녕 đảo thành "đừng nói chi", -다가는 cảnh báo hậu quả xấu — không cái nào chỉ thêm một đặc điểm tốt thứ hai.',
      '「〜のみならず」という付加（또한 で強化）には文語の -거니와 が必要。-더라도 は譲歩（「ても」）、-기는커녕 は「どころか」と反転、-다가는 は悪い結果の警告で、二つ目の長所を単に付け加える働きがない。',
    ),
  },
  {
    ko: '-는 마당에',
    sentence: '회사가 망하게 생긴 {} 휴가를 떠날 수는 없지요.',
    answer: '마당에',
    distractors: ['김에', '바람에', '와중에'],
    trans: L(
      'With the company on the verge of collapse, there is no way I can go on vacation.',
      'Con la empresa al borde de la quiebra, no hay manera de irme de vacaciones.',
      "Alors que l'entreprise est au bord de la faillite, il est hors de question de partir en vacances.",
      'Com a empresa à beira da falência, não há como sair de férias.',
      'ในเมื่อบริษัทกำลังจะล่ม จะไปเที่ยวพักร้อนได้อย่างไร',
      'Saat perusahaan di ambang kebangkrutan, mustahil saya pergi berlibur.',
      'Trong khi công ty sắp phá sản thì làm sao tôi đi nghỉ mát được.',
      '会社が潰れかけているこの状況で、休暇に出かけるわけにはいきません。',
    ),
    why: L(
      'A grave, decisive situation framing an impossible choice takes -는 마당에; -는 김에 means "while I\'m at it" (an added bonus), -는 바람에 a sudden cause, -는 와중에 just "in the midst of" without the critical-stakes nuance — only -는 마당에 conveys the irreversible context.',
      'Una situación grave y decisiva que enmarca una elección imposible toma -는 마당에; -는 김에 es "ya que estoy", -는 바람에 una causa súbita, -는 와중에 solo "en medio de" sin el matiz crítico — solo -는 마당에 transmite el contexto irreversible.',
      "Une situation grave et décisive encadrant un choix impossible prend -는 마당에 ; -는 김에 = « tant qu'à faire », -는 바람에 = cause soudaine, -는 와중에 = « au milieu de » sans l'enjeu critique — seul -는 마당에 rend le contexte irréversible.",
      'Uma situação grave e decisiva que enquadra uma escolha impossível usa -는 마당에; -는 김에 é "já que estou", -는 바람에 causa súbita, -는 와중에 só "em meio a" sem a nuance crítica — só -는 마당에 transmite o contexto irreversível.',
      'สถานการณ์ร้ายแรงเด็ดขาดที่กรอบทางเลือกอันเป็นไปไม่ได้ใช้ -는 마당에; -는 김에 คือ "ถือโอกาส", -는 바람에 เหตุฉับพลัน, -는 와중에 แค่ "ท่ามกลาง" ไม่มีนัยวิกฤต มีแต่ -는 마당에 ที่สื่อบริบทย้อนกลับไม่ได้',
      'Situasi gawat dan menentukan yang membingkai pilihan mustahil memakai -는 마당에; -는 김에 berarti "mumpung", -는 바람에 sebab mendadak, -는 와중에 sekadar "di tengah" tanpa nuansa kritis — hanya -는 마당에 yang menyampaikan konteks tak terbalikkan.',
      'Một tình huống nghiêm trọng, quyết định khung cho lựa chọn bất khả dùng -는 마당에; -는 김에 nghĩa "nhân tiện", -는 바람에 nguyên nhân đột ngột, -는 와중에 chỉ "giữa lúc" không có sắc thái nguy cấp — chỉ -는 마당에 truyền tải bối cảnh không thể đảo ngược.',
      '不可能な選択を枠づける重大で決定的な状況には -는 마당에 を用いる。-는 김에 は「ついでに」、-는 바람에 は突発的原因、-는 와중에 は危機のニュアンスなしの「最中に」で、後戻りできない文脈を表すのは -는 마당에 のみ。',
    ),
  },
  {
    ko: '-는 즉시',
    sentence: '결과가 나오{} 바로 연락드리겠습니다.',
    answer: '는 즉시',
    distractors: ['는 동안', '는 대신', '는 한'],
    trans: L(
      'I will contact you immediately as soon as the results come out.',
      'Me pondré en contacto con usted de inmediato en cuanto salgan los resultados.',
      "Je vous contacterai immédiatement dès que les résultats seront disponibles.",
      'Entrarei em contato imediatamente assim que sair o resultado.',
      'พอผลออก จะติดต่อกลับทันที',
      'Saya akan menghubungi Anda segera begitu hasilnya keluar.',
      'Ngay khi có kết quả, tôi sẽ liên hệ ngay với bạn.',
      '結果が出次第、すぐにご連絡いたします。',
    ),
    why: L(
      'The formal "the very moment X happens, Y" (paired with 바로) requires -는 즉시; -는 동안 means "while/during," -는 대신 "instead of," -는 한 "as long as (a condition holds)" — none expresses the instant-trigger sequence the sentence needs.',
      'El formal "en el instante en que X, Y" (con 바로) exige -는 즉시; -는 동안 es "mientras", -는 대신 "en vez de", -는 한 "siempre que (se cumpla una condición)" — ninguno expresa el disparo inmediato que pide la frase.',
      'Le formel « à l\'instant même où X, Y » (avec 바로) exige -는 즉시 ; -는 동안 = « pendant », -는 대신 = « au lieu de », -는 한 = « tant que (une condition tient) » — aucun n\'exprime le déclenchement immédiat requis.',
      'O formal "no instante em que X, Y" (com 바로) exige -는 즉시; -는 동안 é "enquanto", -는 대신 "em vez de", -는 한 "desde que (uma condição valha)" — nenhum expressa o disparo imediato que a frase pede.',
      'รูปทางการ "ทันทีที่ X ก็ Y" (คู่กับ 바로) ต้องใช้ -는 즉시; -는 동안 คือ "ระหว่าง", -는 대신 "แทนที่จะ", -는 한 "ตราบใดที่ (เงื่อนไขคงอยู่)" ไม่มีอันใดสื่อการกระตุ้นทันทีที่ประโยคต้องการ',
      'Bentuk formal "begitu X terjadi, Y" (berpasangan dengan 바로) memerlukan -는 즉시; -는 동안 berarti "selama", -는 대신 "alih-alih", -는 한 "selama (syarat berlaku)" — tak ada yang mengungkap pemicu seketika yang dibutuhkan.',
      'Cấu trúc trang trọng "ngay khoảnh khắc X, thì Y" (kèm 바로) cần -는 즉시; -는 동안 nghĩa "trong khi", -는 대신 "thay vì", -는 한 "chừng nào (điều kiện còn)" — không cái nào diễn đạt sự kích hoạt tức thì mà câu cần.',
      '「Xした瞬間にY」という改まった表現（바로 と呼応）には -는 즉시 が必要。-는 동안 は「間」、-는 대신 は「代わりに」、-는 한 は「限り（条件）」で、即時の引き金となる連続を表せない。',
    ),
  },
  {
    ko: '-(이)야말로',
    sentence: '꾸준한 노력{} 진정한 실력을 만드는 비결이다.',
    answer: '이야말로',
    distractors: ['이라도', '이나마', '이라서'],
    trans: L(
      'Steady effort is precisely the secret to building genuine skill.',
      'El esfuerzo constante es justamente el secreto para forjar una verdadera habilidad.',
      "C'est précisément l'effort constant qui est le secret d'une vraie compétence.",
      'O esforço constante é justamente o segredo para construir uma habilidade verdadeira.',
      'ความพยายามอย่างสม่ำเสมอนี่แหละคือเคล็ดลับสร้างฝีมือที่แท้จริง',
      'Justru usaha yang konsisten itulah rahasia membentuk kemampuan sejati.',
      'Chính sự nỗ lực bền bỉ mới là bí quyết tạo nên thực lực thật sự.',
      '地道な努力こそが真の実力を作る秘訣だ。',
    ),
    why: L(
      'Singling out the subject as "this and nothing else is the very thing" requires the emphatic -(이)야말로; -(이)라도 means "even/at least," -(이)나마 "though only," -(이)라서 "because it is" — none gives the exclusive, superlative identification the sentence asserts.',
      'Destacar el sujeto como "esto y nada más es justamente lo que" exige el enfático -(이)야말로; -(이)라도 es "aunque/al menos", -(이)나마 "aunque solo", -(이)라서 "porque es" — ninguno da la identificación exclusiva y superlativa que afirma la frase.',
      'Mettre en avant le sujet comme « c\'est précisément cela » exige l\'emphatique -(이)야말로 ; -(이)라도 = « même/au moins », -(이)나마 = « ne serait-ce que », -(이)라서 = « parce que c\'est » — aucun ne donne l\'identification exclusive et superlative affirmée.',
      'Destacar o sujeito como "isto e nada mais é justamente o que" exige o enfático -(이)야말로; -(이)라도 é "ao menos/mesmo", -(이)나마 "embora só", -(이)라서 "por ser" — nenhum dá a identificação exclusiva e superlativa que a frase afirma.',
      'การชี้ประธานว่า "สิ่งนี้แหละไม่ใช่อื่นใดที่เป็น" ต้องใช้ -(이)야말로 เชิงเน้น; -(이)라도 คือ "แม้/อย่างน้อย", -(이)나마 "ถึงจะแค่", -(이)라서 "เพราะเป็น" ไม่มีอันใดให้การระบุเชิงเดี่ยวสูงสุดที่ประโยคยืนยัน',
      'Menonjolkan subjek sebagai "inilah dan bukan yang lain" memerlukan -(이)야말로 yang menegaskan; -(이)라도 berarti "setidaknya/bahkan", -(이)나마 "meski hanya", -(이)라서 "karena merupakan" — tak ada yang memberi identifikasi eksklusif-superlatif yang ditegaskan.',
      'Việc nêu bật chủ ngữ như "chính cái này chứ không gì khác" cần -(이)야말로 nhấn mạnh; -(이)라도 nghĩa "ít nhất/dù", -(이)나마 "tuy chỉ", -(이)라서 "vì là" — không cái nào cho sự xác định độc nhất, tột bậc mà câu khẳng định.',
      '主語を「ほかでもなくこれこそが」と際立たせるには強調の -(이)야말로 が必要。-(이)라도 は「でも・せめて」、-(이)나마 は「ながらも」、-(이)라서 は「だから」で、文が主張する排他的・最上級の同定を与えない。',
    ),
  },
  {
    ko: '-(으)ㄴ/는 이상',
    sentence: '일단 맡기로 한 {} 끝까지 책임을 져야 한다.',
    answer: '이상',
    distractors: ['덕분에', '대신에', '반면에'],
    trans: L(
      'Given that you agreed to take it on, you must see it through to the end.',
      'Ya que aceptaste encargarte, debes asumir la responsabilidad hasta el final.',
      "Dès lors que tu as accepté de t'en charger, tu dois en assumer la responsabilité jusqu'au bout.",
      'Já que aceitou assumir, deve arcar com a responsabilidade até o fim.',
      'ในเมื่อรับปากจะทำแล้ว ก็ต้องรับผิดชอบจนถึงที่สุด',
      'Karena sudah setuju untuk menanganinya, kamu harus bertanggung jawab sampai akhir.',
      'Đã nhận đảm nhận thì phải chịu trách nhiệm đến cùng.',
      'いったん引き受けた以上、最後まで責任を負わなければならない。',
    ),
    why: L(
      'An established premise that obligates a consequence (끝까지 …져야 한다) takes -(으)ㄴ/는 이상; -덕분에 means "thanks to" (positive cause), -대신에 "instead of," -반면에 "on the other hand" — none links a settled fact to an ensuing duty.',
      'Una premisa establecida que obliga a una consecuencia (끝까지 …져야 한다) toma -(으)ㄴ/는 이상; -덕분에 es "gracias a", -대신에 "en vez de", -반면에 "por otro lado" — ninguno une un hecho consumado con el deber resultante.',
      "Une prémisse établie qui oblige une conséquence (끝까지 …져야 한다) prend -(으)ㄴ/는 이상 ; -덕분에 = « grâce à », -대신에 = « au lieu de », -반면에 = « en revanche » — aucun ne lie un fait acquis à un devoir qui en découle.",
      'Uma premissa estabelecida que obriga a uma consequência (끝까지 …져야 한다) usa -(으)ㄴ/는 이상; -덕분에 é "graças a", -대신에 "em vez de", -반면에 "por outro lado" — nenhum liga um fato consumado a um dever decorrente.',
      'ข้อตั้งที่ก่อหน้าที่ตามมา (끝까지 …져야 한다) ใช้ -(으)ㄴ/는 이상; -덕분에 คือ "ด้วยอานิสงส์", -대신에 "แทนที่จะ", -반면에 "ในทางกลับกัน" ไม่มีอันใดเชื่อมข้อเท็จจริงที่ตกลงแล้วกับหน้าที่ที่ตามมา',
      'Premis yang sudah ditetapkan yang mewajibkan konsekuensi (끝까지 …져야 한다) memakai -(으)ㄴ/는 이상; -덕분에 berarti "berkat", -대신에 "alih-alih", -반면에 "sebaliknya" — tak ada yang menautkan fakta yang sudah pasti dengan kewajiban yang menyusul.',
      'Một tiền đề đã xác lập buộc ra hệ quả (끝까지 …져야 한다) dùng -(으)ㄴ/는 이상; -덕분에 nghĩa "nhờ", -대신에 "thay vì", -반면에 "ngược lại" — không cái nào nối sự thật đã định với nghĩa vụ kéo theo.',
      '結果（끝까지 …져야 한다）を義務づける確定した前提には -(으)ㄴ/는 이상 を用いる。-덕분에 は「おかげで」、-대신에 は「代わりに」、-반면에 は「一方で」で、確定事実とそれに伴う義務を結ばない。',
    ),
  },
  {
    ko: '-다시피',
    sentence: '여러분도 잘 아{} 이 사업은 처음부터 무리가 있었습니다.',
    answer: '시다시피',
    distractors: ['는 김에', 'ㄹ수록', 'ㄹ 뿐더러'],
    trans: L(
      'As you all well know, this project was overstretched from the very beginning.',
      'Como todos saben bien, este proyecto fue excesivo desde el principio.',
      "Comme vous le savez tous bien, ce projet était excessif dès le départ.",
      'Como todos sabem bem, este projeto foi excessivo desde o início.',
      'อย่างที่ทุกท่านทราบดี โครงการนี้หักโหมเกินไปตั้งแต่แรก',
      'Sebagaimana Anda semua ketahui, proyek ini sudah berlebihan sejak awal.',
      'Như quý vị đều biết rõ, dự án này đã quá sức ngay từ đầu.',
      'みなさんもよくご存じのとおり、この事業は初めから無理がありました。',
    ),
    why: L(
      'Appealing to shared knowledge ("as you know") attaches -다시피 to 알다, giving 아시다시피; -는 김에 means "while at it," -ㄹ수록 means "the more … the more," -ㄹ 뿐더러 adds "moreover" — none cites the listener\'s existing awareness.',
      'Apelar al saber compartido ("como saben") une -다시피 a 알다, dando 아시다시피; -는 김에 es "ya que estoy", -ㄹ수록 es "cuanto más … más", -ㄹ 뿐더러 añade "además" — ninguno invoca el conocimiento previo del oyente.',
      "Faire appel au savoir partagé (« comme vous le savez ») attache -다시피 à 알다, d'où 아시다시피 ; -는 김에 = « tant qu'à faire », -ㄹ수록 = « plus … plus », -ㄹ 뿐더러 = « de plus » — aucun n'invoque la connaissance déjà acquise de l'auditeur.",
      'Apelar ao saber compartilhado ("como sabem") liga -다시피 a 알다, gerando 아시다시피; -는 김에 é "já que estou", -ㄹ수록 é "quanto mais … mais", -ㄹ 뿐더러 acrescenta "além disso" — nenhum invoca o conhecimento prévio do ouvinte.',
      'การอ้างความรู้ร่วม ("อย่างที่ทราบ") ติด -다시피 กับ 알다 เป็น 아시다시피; -는 김에 คือ "ถือโอกาส", -ㄹ수록 คือ "ยิ่ง … ยิ่ง", -ㄹ 뿐더러 เสริม "ยิ่งกว่านั้น" ไม่มีอันใดอ้างความรู้เดิมของผู้ฟัง',
      'Mengacu pada pengetahuan bersama ("seperti Anda tahu") melekatkan -다시피 pada 알다, menjadi 아시다시피; -는 김에 berarti "mumpung", -ㄹ수록 berarti "semakin … semakin", -ㄹ 뿐더러 menambah "lagi pula" — tak ada yang menyitir kesadaran pendengar yang sudah ada.',
      'Việc viện dẫn hiểu biết chung ("như quý vị biết") gắn -다시피 vào 알다, thành 아시다시피; -는 김에 nghĩa "nhân tiện", -ㄹ수록 nghĩa "càng … càng", -ㄹ 뿐더러 thêm "hơn nữa" — không cái nào viện đến nhận thức sẵn có của người nghe.',
      '共有知識への訴え（「ご存じのとおり」）は 알다 に -다시피 を付け 아시다시피 となる。-는 김에 は「ついでに」、-ㄹ수록 は「ほど」、-ㄹ 뿐더러 は「うえに」で、聞き手の既知の認識を引き合いに出さない。',
    ),
  },
  {
    ko: '-건만',
    sentence: '그렇게 애를 썼{} 결과는 끝내 달라지지 않았다.',
    answer: '건만',
    distractors: ['더라면', '느라고', '도록'],
    trans: L(
      'Though I tried so very hard, the outcome ultimately did not change.',
      'Aunque me esforcé tanto, el resultado al final no cambió.',
      "J'ai eu beau tant m'efforcer, le résultat n'a finalement pas changé.",
      'Por mais que eu tenha me esforçado, o resultado no fim não mudou.',
      'แม้จะพยายามขนาดนั้น แต่ผลลัพธ์ก็ไม่เปลี่ยนแปลงในที่สุด',
      'Meski sudah berusaha sekeras itu, hasilnya pada akhirnya tidak berubah.',
      'Dẫu đã cố gắng đến thế mà rốt cuộc kết quả vẫn không đổi.',
      'あれほど苦労したけれど、結果は結局変わらなかった。',
    ),
    why: L(
      'A literary adversative tinged with lament ("though …, yet …") takes -건만; -더라면 sets a counterfactual condition ("had I …"), -느라고 gives a cause with a negative side-effect, -도록 expresses purpose/extent — none is the regretful "and yet" contrast.',
      'Un adversativo literario con lamento ("aunque …, sin embargo …") toma -건만; -더라면 plantea una condición contrafáctica ("si hubiera …"), -느라고 da una causa con efecto negativo, -도록 expresa propósito/grado — ninguno es el contraste de "y sin embargo" con pesar.',
      "Un adversatif littéraire teinté de regret (« j'ai beau …, et pourtant … ») prend -건만 ; -더라면 pose une condition contrefactuelle (« si j'avais … »), -느라고 donne une cause à effet négatif, -도록 exprime le but/degré — aucun n'est le contraste regrettant « et pourtant ».",
      'Um adversativo literário tingido de lamento ("por mais que …, ainda assim …") usa -건만; -더라면 põe uma condição contrafactual ("se eu tivesse …"), -느라고 dá causa com efeito negativo, -도록 expressa propósito/grau — nenhum é o contraste lamentoso de "ainda assim".',
      'การขัดแย้งเชิงวรรณกรรมเจือความเศร้า ("แม้จะ … แต่ …") ใช้ -건만; -더라면 ตั้งเงื่อนไขตรงข้ามจริง ("ถ้าได้…"), -느라고 ให้เหตุที่มีผลลบ, -도록 สื่อจุดประสงค์/ระดับ ไม่มีอันใดเป็นความขัดแย้ง "แต่กระนั้น" ที่เจือเสียดาย',
      'Adversatif sastrawi bernuansa sesal ("meski …, namun …") memakai -건만; -더라면 menetapkan kondisi kontrafaktual ("seandainya …"), -느라고 memberi sebab berefek negatif, -도록 mengungkap tujuan/derajat — tak ada yang menjadi kontras "namun" yang menyesal.',
      'Phép tương phản văn chương đượm tiếc nuối ("dẫu …, vậy mà …") dùng -건만; -더라면 đặt điều kiện phản thực ("giá mà …"), -느라고 nêu nguyên nhân kèm hệ quả xấu, -도록 diễn đạt mục đích/mức độ — không cái nào là sự tương phản "vậy mà" tiếc nuối.',
      '嘆きを帯びた文語の逆接（「あれほど〜けれど」）には -건만 を用いる。-더라면 は反実仮想の条件（「〜していたら」）、-느라고 は悪い副作用を伴う原因、-도록 は目的・程度で、悔やみの「それなのに」逆接ではない。',
    ),
  },
  {
    ko: '-(으)ㄹ세라',
    sentence: '행여 잠든 아이가 깰{} 발끝으로 살금살금 걸었다.',
    answer: '세라',
    distractors: ['수록', '망정', '뿐더러'],
    trans: L(
      'For fear the sleeping child might wake, I tiptoed ever so softly.',
      'Por miedo a que el niño dormido se despertara, caminé de puntillas con sigilo.',
      "De peur que l'enfant endormi ne se réveille, j'ai marché sur la pointe des pieds tout doucement.",
      'Com medo de que a criança adormecida acordasse, andei na ponta dos pés bem de leve.',
      'เกรงว่าเด็กที่หลับอยู่จะตื่น จึงเดินเขย่งปลายเท้าเบา ๆ',
      'Khawatir anak yang tertidur terbangun, saya berjingkat sangat pelan.',
      'Vì sợ đứa trẻ đang ngủ thức giấc, tôi rón rén nhón chân thật khẽ.',
      '眠っている子が起きるかと、つま先でそっと歩いた。',
    ),
    why: L(
      'A literary "for fear that X might happen" (set up by 행여) needs -(으)ㄹ세라; -(으)ㄹ수록 means "the more … the more," -(으)ㄹ망정 a defiant concession, -(으)ㄹ뿐더러 "moreover" — none expresses the anxious precaution against an undesired event.',
      'Un literario "por miedo a que X ocurra" (introducido por 행여) pide -(으)ㄹ세라; -(으)ㄹ수록 es "cuanto más … más", -(으)ㄹ망정 una concesión desafiante, -(으)ㄹ뿐더러 "además" — ninguno expresa la cautela ansiosa ante un suceso no deseado.',
      "Un littéraire « de peur que X n'arrive » (amorcé par 행여) exige -(으)ㄹ세라 ; -(으)ㄹ수록 = « plus … plus », -(으)ㄹ망정 = concession de défi, -(으)ㄹ뿐더러 = « de plus » — aucun n'exprime la précaution anxieuse contre un événement redouté.",
      'Um literário "com medo de que X aconteça" (introduzido por 행여) pede -(으)ㄹ세라; -(으)ㄹ수록 é "quanto mais … mais", -(으)ㄹ망정 uma concessão desafiadora, -(으)ㄹ뿐더러 "além disso" — nenhum expressa a cautela ansiosa contra um evento indesejado.',
      'รูปวรรณกรรม "เกรงว่า X จะเกิด" (เปิดด้วย 행여) ต้องใช้ -(으)ㄹ세라; -(으)ㄹ수록 คือ "ยิ่ง … ยิ่ง", -(으)ㄹ망정 การยอมเชิงท้าทาย, -(으)ㄹ뿐더러 "ยิ่งกว่านั้น" ไม่มีอันใดสื่อความระวังกังวลต่อเหตุที่ไม่พึงประสงค์',
      'Bentuk sastrawi "khawatir kalau-kalau X terjadi" (dibuka oleh 행여) memerlukan -(으)ㄹ세라; -(으)ㄹ수록 berarti "semakin … semakin", -(으)ㄹ망정 konsesi menantang, -(으)ㄹ뿐더러 "lagi pula" — tak ada yang mengungkap kewaspadaan cemas terhadap kejadian yang tak diinginkan.',
      'Cách nói văn chương "sợ rằng X xảy ra" (mở bằng 행여) cần -(으)ㄹ세라; -(으)ㄹ수록 nghĩa "càng … càng", -(으)ㄹ망정 nhượng bộ ngang ngạnh, -(으)ㄹ뿐더러 "hơn nữa" — không cái nào diễn đạt sự đề phòng lo lắng trước một sự việc không mong muốn.',
      '「Xするかと案じて」という文語（행여 で導く）には -(으)ㄹ세라 が必要。-(으)ㄹ수록 は「ほど」、-(으)ㄹ망정 は挑む譲歩、-(으)ㄹ뿐더러 は「うえに」で、望まぬ事態への不安な用心を表せない。',
    ),
  },
]
