// AUTO-GENERATED by scripts/escape-i18n-gen.mjs — do not edit by hand.
import type { LocaleCode } from '~/lib/domain'
import { en } from './en'
import { fr } from './fr'
import { ptBR } from './pt-BR'
import { th } from './th'
import { id } from './id'
import { vi } from './vi'
import { ja } from './ja'

/**
 * Per-locale escape-room seed translations, keyed by Spanish source string.
 * 'es' is the source-of-truth (empty map -> t() uses the literal es value).
 */
export const TRANSLATIONS: Record<LocaleCode, Record<string, string>> = {
  es: {},
  en: en,
  fr: fr,
  'pt-BR': ptBR,
  th: th,
  id: id,
  vi: vi,
  ja: ja,
}
