// AUTO-GENERATED by scripts/escape-i18n-gen.mjs — do not edit by hand.
import type { LocaleCode } from '~/lib/domain'
import { en } from './en'
import { fr } from './fr'
import { ptBR } from './pt-BR'
import { th } from './th'
import { id } from './id'
import { vi } from './vi'
import { ja } from './ja'
import { enLevels04To10 } from './levels-04-10/en'
import { frLevels04To10 } from './levels-04-10/fr'
import { ptBRLevels04To10 } from './levels-04-10/pt-BR'
import { thLevels04To10 } from './levels-04-10/th'
import { idLevels04To10 } from './levels-04-10/id'
import { viLevels04To10 } from './levels-04-10/vi'
import { jaLevels04To10 } from './levels-04-10/ja'

/**
 * Per-locale escape-room seed translations, keyed by Spanish source string.
 * 'es' is the source-of-truth (empty map -> t() uses the literal es value).
 */
export const TRANSLATIONS: Record<LocaleCode, Record<string, string>> = {
  es: {},
  en: { ...en, ...enLevels04To10 },
  fr: { ...fr, ...frLevels04To10 },
  'pt-BR': { ...ptBR, ...ptBRLevels04To10 },
  th: { ...th, ...thLevels04To10 },
  id: { ...id, ...idLevels04To10 },
  vi: { ...vi, ...viLevels04To10 },
  ja: { ...ja, ...jaLevels04To10 },
}
