import type { Grammar, Deck, LocalizedString } from '~/lib/domain'

export const DEFAULT_DECK: Deck = {
  id: 'general',
  name: 'General',
  colorId: 'indigo',
  order: 0,
  collapsed: false,
}

const L = (
  en: string,
  es: string,
  fr: string,
  ptBR: string,
  th: string,
  id: string,
  vi: string,
  ja: string,
): LocalizedString => ({ en, es, fr, 'pt-BR': ptBR, th, id, vi, ja })

export const DEFAULT_GRAMMAR: Grammar[] = [
  {
    ko: '에서/부터~까지',
    meaning: L(
      'from...to (place/time)',
      'desde...hasta',
      'de...à',
      'de...até',
      'จาก...ถึง',
      'dari...sampai',
      'từ...đến',
      '〜から〜まで',
    ),
    example: '9시부터 5시까지 일해요.',
    trans: L(
      'I work from 9 to 5.',
      'Trabajo de 9 a 5.',
      'Je travaille de 9h à 17h.',
      'Trabalho das 9 às 5.',
      'ฉันทำงานตั้งแต่ 9 โมงถึง 5 โมง',
      'Saya bekerja dari jam 9 sampai jam 5.',
      'Tôi làm việc từ 9 giờ đến 5 giờ.',
      '9時から5時まで働きます。',
    ),
    deckId: 'general',
  },
  {
    ko: '-(으)면',
    meaning: L(
      'if / when (conditional)',
      'si / cuando (condicional)',
      'si / quand (conditionnel)',
      'se / quando (condicional)',
      'ถ้า / เมื่อ',
      'jika / kalau',
      'nếu / khi',
      'もし〜たら / 〜ば',
    ),
    example: '시간이 있으면 같이 가요.',
    trans: L(
      "If you have time, let's go together.",
      'Si tienes tiempo, vamos juntos.',
      "Si tu as le temps, allons-y ensemble.",
      'Se tiver tempo, vamos juntos.',
      'ถ้ามีเวลา ไปด้วยกันนะ',
      'Kalau ada waktu, ayo pergi bersama.',
      'Nếu có thời gian, đi cùng nhau nhé.',
      '時間があれば一緒に行きましょう。',
    ),
    deckId: 'general',
  },
  {
    ko: '-(으)니까',
    meaning: L(
      'because (allows imperative/suggestion)',
      'porque (permite imperativo)',
      "parce que (permet l'impératif)",
      'porque (permite imperativo)',
      'เพราะ (ใช้กับคำสั่งได้)',
      'karena (boleh dengan perintah)',
      'bởi vì (cho phép mệnh lệnh)',
      '〜から/ので (命令OK)',
    ),
    example: '비가 오니까 우산을 가져가세요.',
    trans: L(
      "It's raining, so take an umbrella.",
      'Como llueve, lleva paraguas.',
      'Il pleut, alors prends un parapluie.',
      'Como está chovendo, leva guarda-chuva.',
      'ฝนตก เอาร่มไปด้วยนะ',
      'Karena hujan, bawa payung ya.',
      'Vì trời mưa, hãy mang ô đi.',
      '雨が降っているから傘を持って行ってください。',
    ),
    deckId: 'general',
  },
  {
    ko: '는/은',
    meaning: L(
      'topic particle',
      'partícula de tema',
      'particule de thème',
      'partícula de tópico',
      'อนุภาคหัวเรื่อง',
      'partikel topik',
      'tiểu từ chủ đề',
      '主題助詞「は」',
    ),
    example: '저는 학생이에요.',
    trans: L(
      'I am a student.',
      'Yo soy estudiante.',
      'Je suis étudiant.',
      'Eu sou estudante.',
      'ฉันเป็นนักเรียน',
      'Saya seorang pelajar.',
      'Tôi là học sinh.',
      '私は学生です。',
    ),
    deckId: 'general',
  },
  {
    ko: '이/가',
    meaning: L(
      'subject particle',
      'partícula de sujeto',
      'particule de sujet',
      'partícula de sujeito',
      'อนุภาคประธาน',
      'partikel subjek',
      'tiểu từ chủ ngữ',
      '主語助詞「が」',
    ),
    example: '고양이가 귀여워요.',
    trans: L(
      'The cat is cute.',
      'El gato es lindo.',
      'Le chat est mignon.',
      'O gato é fofo.',
      'แมวน่ารัก',
      'Kucingnya lucu.',
      'Con mèo dễ thương.',
      '猫がかわいいです。',
    ),
    deckId: 'general',
  },
  {
    ko: '을/를',
    meaning: L(
      'object particle',
      'partícula de objeto',
      "particule d'objet",
      'partícula de objeto',
      'อนุภาคกรรม',
      'partikel objek',
      'tiểu từ tân ngữ',
      '目的語助詞「を」',
    ),
    example: '책을 읽어요.',
    trans: L(
      'I read a book.',
      'Leo un libro.',
      'Je lis un livre.',
      'Eu leio um livro.',
      'ฉันอ่านหนังสือ',
      'Saya membaca buku.',
      'Tôi đọc sách.',
      '本を読みます。',
    ),
    deckId: 'general',
  },
  {
    ko: '한테/한테서',
    meaning: L(
      'to / from (person) — informal',
      'a / de (persona) — informal',
      'à / de (personne) — informel',
      'para / de (pessoa) — informal',
      'ให้/จาก (คน) — ไม่ทางการ',
      'kepada / dari (orang) — informal',
      'cho / từ (người) — không trang trọng',
      '〜に/から (人・口語)',
    ),
    example: '친구한테 선물을 줬어요.',
    trans: L(
      'I gave a gift to my friend.',
      'Le di un regalo a mi amigo.',
      "J'ai donné un cadeau à mon ami.",
      'Dei um presente para meu amigo.',
      'ฉันให้ของขวัญเพื่อน',
      'Saya memberi hadiah kepada teman.',
      'Tôi đã tặng quà cho bạn.',
      '友達にプレゼントをあげました。',
    ),
    deckId: 'general',
  },
  {
    ko: '-(으)러',
    meaning: L(
      'in order to (purpose + motion verb)',
      'para (propósito + verbo de movimiento)',
      'pour (but + verbe de mouvement)',
      'para (propósito + verbo de movimento)',
      'เพื่อ (กับกริยาเคลื่อนไหว)',
      'untuk (tujuan + verba gerak)',
      'để (mục đích + động từ di chuyển)',
      '〜しに (移動の目的)',
    ),
    example: '밥 먹으러 가요.',
    trans: L(
      "I'm going to eat.",
      'Voy a comer.',
      'Je vais manger.',
      'Vou comer.',
      'ฉันจะไปกินข้าว',
      'Saya pergi makan.',
      'Tôi đi ăn cơm.',
      'ご飯を食べに行きます。',
    ),
    deckId: 'general',
  },
  {
    ko: '-(으)려고',
    meaning: L(
      'with the intention of',
      'con la intención de',
      "avec l'intention de",
      'com a intenção de',
      'ตั้งใจจะ',
      'berniat untuk',
      'với ý định',
      '〜しようと',
    ),
    example: '한국어를 배우려고 해요.',
    trans: L(
      'I intend to learn Korean.',
      'Tengo la intención de aprender coreano.',
      "J'ai l'intention d'apprendre le coréen.",
      'Tenho a intenção de aprender coreano.',
      'ฉันตั้งใจจะเรียนภาษาเกาหลี',
      'Saya berniat belajar bahasa Korea.',
      'Tôi định học tiếng Hàn.',
      '韓国語を学ぼうと思います。',
    ),
    deckId: 'general',
  },
  {
    ko: '-고 싶다',
    meaning: L(
      'want to do something',
      'querer hacer algo',
      'vouloir faire',
      'querer fazer algo',
      'อยากทำ',
      'ingin melakukan',
      'muốn làm',
      '〜したい',
    ),
    example: '드라마를 보고 싶어요.',
    trans: L(
      'I want to watch a drama.',
      'Quiero ver un drama.',
      'Je veux regarder un drama.',
      'Quero ver um drama.',
      'ฉันอยากดูซีรีส์',
      'Saya ingin menonton drama.',
      'Tôi muốn xem phim.',
      'ドラマを見たいです。',
    ),
    deckId: 'general',
  },
  {
    ko: '못',
    meaning: L(
      'cannot (impossibility)',
      'no poder (imposibilidad)',
      'ne pas pouvoir',
      'não conseguir',
      'ไม่สามารถ',
      'tidak bisa',
      'không thể',
      'できない (不可能)',
    ),
    example: '매운 거 못 먹어요.',
    trans: L(
      "I can't eat spicy food.",
      'No puedo comer picante.',
      'Je ne peux pas manger épicé.',
      'Não consigo comer picante.',
      'ฉันกินเผ็ดไม่ได้',
      'Saya tidak bisa makan pedas.',
      'Tôi không ăn cay được.',
      '辛いものは食べられません。',
    ),
    deckId: 'general',
  },
  {
    ko: '-지 않다',
    meaning: L(
      'not (formal negation)',
      'no (negación formal)',
      'ne ... pas (négation formelle)',
      'não (negação formal)',
      'ไม่ (ปฏิเสธทางการ)',
      'tidak (negasi formal)',
      'không (phủ định trang trọng)',
      '〜ない (改まった否定)',
    ),
    example: '오늘은 춥지 않아요.',
    trans: L(
      "It's not cold today.",
      'Hoy no hace frío.',
      "Il ne fait pas froid aujourd'hui.",
      'Hoje não está frio.',
      'วันนี้ไม่หนาว',
      'Hari ini tidak dingin.',
      'Hôm nay không lạnh.',
      '今日は寒くないです。',
    ),
    deckId: 'general',
  },
  {
    ko: '-고',
    meaning: L(
      'and (action connector)',
      'y (conectivo entre acciones)',
      "et (connecteur d'actions)",
      'e (conector de ações)',
      'แล้วก็ (เชื่อมการกระทำ)',
      'lalu / dan (penghubung aksi)',
      'và (nối hành động)',
      '〜して (動作の連結)',
    ),
    example: '숙제를 하고 잤어요.',
    trans: L(
      'I did my homework and went to sleep.',
      'Hice la tarea y me dormí.',
      "J'ai fait mes devoirs et je suis allé dormir.",
      'Fiz a lição e fui dormir.',
      'ทำการบ้านแล้วก็นอน',
      'Saya kerjakan PR lalu tidur.',
      'Tôi làm bài tập rồi đi ngủ.',
      '宿題をして寝ました。',
    ),
    deckId: 'general',
  },
  {
    ko: '-아/어야 되다',
    meaning: L(
      'have to / must',
      'tener que / deber',
      'devoir / il faut',
      'ter que / dever',
      'ต้อง',
      'harus',
      'phải',
      '〜なければならない',
    ),
    example: '내일 일찍 일어나야 돼요.',
    trans: L(
      'I have to wake up early tomorrow.',
      'Mañana tengo que levantarme temprano.',
      'Demain je dois me lever tôt.',
      'Amanhã tenho que acordar cedo.',
      'พรุ่งนี้ต้องตื่นเช้า',
      'Besok saya harus bangun pagi.',
      'Ngày mai tôi phải dậy sớm.',
      '明日早く起きなければなりません。',
    ),
    deckId: 'general',
  },
]
