import type { LocalizedString } from '~/lib/domain'
import { L } from './locale'

/**
 * Learner-facing meanings for every verb in the generated conjugation dataset.
 * Kept outside dataset.ts so regenerating engine fixtures never erases i18n.
 */
export const CONJUGATION_GLOSSES: Record<string, LocalizedString> = {
  먹다: L('eat', 'comer', 'manger', 'comer', 'กิน', 'makan', 'ăn', '食べる'),
  가다: L('go', 'ir', 'aller', 'ir', 'ไป', 'pergi', 'đi', '行く'),
  보다: L('see', 'ver', 'voir', 'ver', 'ดู', 'melihat', 'xem', '見る'),
  오다: L('come', 'venir', 'venir', 'vir', 'มา', 'datang', 'đến', '来る'),
  마시다: L('drink', 'beber', 'boire', 'beber', 'ดื่ม', 'minum', 'uống', '飲む'),
  되다: L('become', 'convertirse', 'devenir', 'tornar-se', 'กลายเป็น', 'menjadi', 'trở thành', 'なる'),
  주다: L('give', 'dar', 'donner', 'dar', 'ให้', 'memberi', 'cho', 'あげる'),
  만나다: L('meet', 'encontrarse', 'rencontrer', 'encontrar', 'พบ', 'bertemu', 'gặp', '会う'),
  공부하다: L('study', 'estudiar', 'étudier', 'estudar', 'เรียน', 'belajar', 'học', '勉強する'),
  좋다: L('be good', 'ser bueno', 'être bon', 'ser bom', 'ดี', 'baik', 'tốt', '良い'),
  받다: L('receive', 'recibir', 'recevoir', 'receber', 'รับ', 'menerima', 'nhận', '受け取る'),
  덥다: L('be hot', 'hacer calor', 'faire chaud', 'estar quente', 'ร้อน', 'panas', 'nóng', '暑い'),
  춥다: L('be cold', 'hacer frío', 'faire froid', 'estar frio', 'หนาว', 'dingin', 'lạnh', '寒い'),
  쉽다: L('be easy', 'ser fácil', 'être facile', 'ser fácil', 'ง่าย', 'mudah', 'dễ', '易しい'),
  어렵다: L('be difficult', 'ser difícil', 'être difficile', 'ser difícil', 'ยาก', 'sulit', 'khó', '難しい'),
  가깝다: L('be near', 'estar cerca', 'être proche', 'estar perto', 'ใกล้', 'dekat', 'gần', '近い'),
  아름답다: L('be beautiful', 'ser hermoso', 'être beau', 'ser bonito', 'สวย', 'indah', 'đẹp', '美しい'),
  맵다: L('be spicy', 'ser picante', 'être épicé', 'ser apimentado', 'เผ็ด', 'pedas', 'cay', '辛い'),
  굽다: L('grill or roast', 'asar', 'griller ou rôtir', 'grelhar ou assar', 'ย่าง', 'memanggang', 'nướng', '焼く'),
  눕다: L('lie down', 'acostarse', 's’allonger', 'deitar-se', 'นอนลง', 'berbaring', 'nằm xuống', '横になる'),
  돕다: L('help', 'ayudar', 'aider', 'ajudar', 'ช่วย', 'membantu', 'giúp', '手伝う'),
  곱다: L('be pretty or fine', 'ser bonito o fino', 'être joli ou délicat', 'ser bonito ou delicado', 'งดงามหรือละเอียด', 'cantik atau halus', 'đẹp hoặc mịn', 'きれい・きめ細かい'),
  좁다: L('be narrow', 'ser estrecho', 'être étroit', 'ser estreito', 'แคบ', 'sempit', 'hẹp', '狭い'),
  입다: L('wear', 'vestir', 'porter', 'vestir', 'ใส่', 'memakai', 'mặc', '着る'),
  잡다: L('catch or grab', 'agarrar', 'attraper', 'pegar', 'จับ', 'menangkap', 'bắt hoặc nắm', 'つかむ'),
  씹다: L('chew', 'masticar', 'mâcher', 'mastigar', 'เคี้ยว', 'mengunyah', 'nhai', '噛む'),
  뽑다: L('pull out or select', 'sacar o elegir', 'retirer ou choisir', 'tirar ou escolher', 'ดึงออกหรือเลือก', 'mencabut atau memilih', 'nhổ hoặc chọn', '抜く・選ぶ'),
  듣다: L('listen', 'escuchar', 'écouter', 'ouvir', 'ฟัง', 'mendengarkan', 'nghe', '聞く'),
  걷다: L('walk', 'caminar', 'marcher', 'caminhar', 'เดิน', 'berjalan', 'đi bộ', '歩く'),
  묻다: L('ask', 'preguntar', 'demander', 'perguntar', 'ถาม', 'bertanya', 'hỏi', '尋ねる'),
  싣다: L('load', 'cargar', 'charger', 'carregar', 'บรรทุก', 'memuat', 'chở', '積む'),
  깨닫다: L('realize', 'darse cuenta', 'se rendre compte', 'perceber', 'ตระหนัก', 'menyadari', 'nhận ra', '悟る'),
  닫다: L('close', 'cerrar', 'fermer', 'fechar', 'ปิด', 'menutup', 'đóng', '閉める'),
  믿다: L('believe', 'creer', 'croire', 'acreditar', 'เชื่อ', 'percaya', 'tin', '信じる'),
  바쁘다: L('be busy', 'estar ocupado', 'être occupé', 'estar ocupado', 'ยุ่ง', 'sibuk', 'bận', '忙しい'),
  예쁘다: L('be pretty', 'ser bonito', 'être joli', 'ser bonito', 'น่ารัก', 'cantik', 'xinh đẹp', 'かわいい'),
  쓰다: L('write or use', 'escribir o usar', 'écrire ou utiliser', 'escrever ou usar', 'เขียนหรือใช้', 'menulis atau menggunakan', 'viết hoặc dùng', '書く・使う'),
  크다: L('be big', 'ser grande', 'être grand', 'ser grande', 'ใหญ่', 'besar', 'lớn', '大きい'),
  아프다: L('be sick or hurt', 'estar enfermo o doler', 'être malade ou faire mal', 'estar doente ou doer', 'ป่วยหรือเจ็บ', 'sakit', 'ốm hoặc đau', '病気だ・痛い'),
  모으다: L('gather', 'reunir', 'rassembler', 'reunir', 'รวบรวม', 'mengumpulkan', 'gom', '集める'),
  슬프다: L('be sad', 'estar triste', 'être triste', 'estar triste', 'เศร้า', 'sedih', 'buồn', '悲しい'),
  기쁘다: L('be glad', 'estar feliz', 'être heureux', 'estar contente', 'ดีใจ', 'senang', 'vui', '嬉しい'),
  고프다: L('be hungry', 'tener hambre', 'avoir faim', 'estar com fome', 'หิว', 'lapar', 'đói', 'お腹がすく'),
  나쁘다: L('be bad', 'ser malo', 'être mauvais', 'ser ruim', 'แย่', 'buruk', 'xấu', '悪い'),
  잠그다: L('lock', 'cerrar con llave', 'verrouiller', 'trancar', 'ล็อก', 'mengunci', 'khóa', '鍵をかける'),
  담그다: L('soak or pickle', 'remojar o encurtir', 'faire tremper ou mariner', 'deixar de molho ou conservar', 'แช่หรือดอง', 'merendam atau mengasinkan', 'ngâm hoặc muối', '漬ける'),
  치르다: L('pay or undergo', 'pagar o pasar por', 'payer ou subir', 'pagar ou passar por', 'จ่ายหรือผ่าน', 'membayar atau menjalani', 'trả hoặc trải qua', '支払う・経験する'),
  따르다: L('follow or pour', 'seguir o verter', 'suivre ou verser', 'seguir ou despejar', 'ตามหรือริน', 'mengikuti atau menuang', 'theo hoặc rót', '従う・注ぐ'),
  들르다: L('stop by', 'pasar por', 'faire un saut', 'passar em', 'แวะ', 'singgah', 'ghé qua', '立ち寄る'),
  끄다: L('turn off', 'apagar', 'éteindre', 'desligar', 'ปิด', 'mematikan', 'tắt', '消す'),
  뜨다: L('float or rise', 'flotar o elevarse', 'flotter ou se lever', 'flutuar ou subir', 'ลอยหรือขึ้น', 'mengapung atau terbit', 'nổi hoặc lên', '浮く・昇る'),
  빠르다: L('be fast', 'ser rápido', 'être rapide', 'ser rápido', 'เร็ว', 'cepat', 'nhanh', '速い'),
  부르다: L('call or sing', 'llamar o cantar', 'appeler ou chanter', 'chamar ou cantar', 'เรียกหรือร้องเพลง', 'memanggil atau bernyanyi', 'gọi hoặc hát', '呼ぶ・歌う'),
  모르다: L('not know', 'no saber', 'ne pas savoir', 'não saber', 'ไม่รู้', 'tidak tahu', 'không biết', '知らない'),
  다르다: L('be different', 'ser diferente', 'être différent', 'ser diferente', 'ต่าง', 'berbeda', 'khác', '違う'),
  자르다: L('cut', 'cortar', 'couper', 'cortar', 'ตัด', 'memotong', 'cắt', '切る'),
  흐르다: L('flow', 'fluir', 'couler', 'fluir', 'ไหล', 'mengalir', 'chảy', '流れる'),
  그렇다: L('be so', 'ser así', 'être ainsi', 'ser assim', 'เป็นอย่างนั้น', 'begitu', 'là như vậy', 'そうだ'),
  빨갛다: L('be red', 'ser rojo', 'être rouge', 'ser vermelho', 'แดง', 'merah', 'đỏ', '赤い'),
  파랗다: L('be blue', 'ser azul', 'être bleu', 'ser azul', 'น้ำเงิน', 'biru', 'xanh lam', '青い'),
  어떻다: L('be how or what like', 'cómo ser', 'comment être', 'como ser', 'เป็นอย่างไร', 'bagaimana', 'thế nào', 'どうだ'),
  노랗다: L('be yellow', 'ser amarillo', 'être jaune', 'ser amarelo', 'เหลือง', 'kuning', 'vàng', '黄色い'),
  하얗다: L('be white', 'ser blanco', 'être blanc', 'ser branco', 'ขาว', 'putih', 'trắng', '白い'),
  이렇다: L('be like this', 'ser así', 'être comme ceci', 'ser assim', 'เป็นแบบนี้', 'seperti ini', 'như thế này', 'こうだ'),
  저렇다: L('be like that', 'ser de ese modo', 'être comme cela', 'ser daquele jeito', 'เป็นแบบนั้น', 'seperti itu', 'như thế kia', 'ああだ'),
  까맣다: L('be black', 'ser negro', 'être noir', 'ser preto', 'ดำ', 'hitam', 'đen', '黒い'),
  짓다: L('build', 'construir', 'construire', 'construir', 'สร้าง', 'membangun', 'xây', '建てる'),
  낫다: L('get better or heal', 'mejorar o curarse', 'aller mieux ou guérir', 'melhorar ou sarar', 'ดีขึ้นหรือหาย', 'sembuh atau lebih baik', 'khỏi hoặc tốt hơn', '治る・良くなる'),
  붓다: L('pour or swell', 'verter o hincharse', 'verser ou enfler', 'derramar ou inchar', 'เทหรือบวม', 'menuang atau membengkak', 'rót hoặc sưng', '注ぐ・腫れる'),
  잇다: L('connect', 'conectar', 'relier', 'conectar', 'เชื่อม', 'menghubungkan', 'nối', 'つなぐ'),
  긋다: L('draw a line', 'trazar una línea', 'tracer une ligne', 'traçar uma linha', 'ลากเส้น', 'menarik garis', 'kẻ đường', '線を引く'),
  젓다: L('stir', 'remover', 'remuer', 'mexer', 'คน', 'mengaduk', 'khuấy', 'かき混ぜる'),
  웃다: L('laugh', 'reír', 'rire', 'rir', 'หัวเราะ', 'tertawa', 'cười', '笑う'),
  씻다: L('wash', 'lavar', 'laver', 'lavar', 'ล้าง', 'mencuci', 'rửa', '洗う'),
  벗다: L('take off', 'quitarse', 'enlever', 'tirar', 'ถอด', 'melepas', 'cởi', '脱ぐ'),
  살다: L('live', 'vivir', 'vivre', 'viver', 'อาศัยอยู่', 'hidup', 'sống', '暮らす'),
  알다: L('know', 'saber', 'savoir', 'saber', 'รู้', 'tahu', 'biết', '知る'),
  만들다: L('make', 'hacer', 'fabriquer', 'fazer', 'ทำ', 'membuat', 'làm', '作る'),
  놀다: L('play', 'jugar', 'jouer', 'brincar', 'เล่น', 'bermain', 'chơi', '遊ぶ'),
  멀다: L('be far', 'estar lejos', 'être loin', 'ser distante', 'ไกล', 'jauh', 'xa', '遠い'),
}
