import type { Context } from '~/lib/domain'
import { L } from '~/seed/locale'

/**
 * Extra writing-prompt contexts that extend {@link DEFAULT_CONTEXTS} with more
 * situational variety for the ruleta sentence game. Each frames the Korean
 * sentence the learner writes in a concrete, everyday register.
 *
 * Drafted + KO-verified. Wife native review = final gate.
 */
export const DEFAULT_CONTEXTS_EXTRA: Context[] = [
  {
    id: 'restaurant-order',
    name: '식당에서 주문',
    scene: L(
      'ordering food at a restaurant',
      'pidiendo comida en un restaurante',
      'en commandant à manger au restaurant',
      'pedindo comida num restaurante',
      'สั่งอาหารที่ร้านอาหาร',
      'memesan makanan di restoran',
      'gọi món ở nhà hàng',
      'レストランで料理を注文する',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'phone-call',
    name: '전화 통화',
    scene: L(
      'on the phone, you can only hear the voice',
      'al teléfono, solo oyes la voz',
      'au téléphone, tu n’entends que la voix',
      'ao telefone, você só ouve a voz',
      'คุยโทรศัพท์ ได้ยินแค่เสียง',
      'di telepon, hanya dengar suara',
      'nói chuyện điện thoại, chỉ nghe được giọng',
      '電話で、声しか聞こえない',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'apology',
    name: '사과할 때',
    scene: L(
      'apologizing sincerely for a mistake',
      'disculpándote de verdad por un error',
      'en t’excusant sincèrement d’une erreur',
      'pedindo desculpas de verdade por um erro',
      'ขอโทษอย่างจริงใจที่ทำผิด',
      'meminta maaf dengan tulus atas kesalahan',
      'xin lỗi chân thành vì một lỗi lầm',
      '失敗を心から謝る',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'directions',
    name: '길 안내',
    scene: L(
      'giving someone directions on the street',
      'indicándole el camino a alguien en la calle',
      'en indiquant le chemin à quelqu’un dans la rue',
      'dando direções a alguém na rua',
      'บอกทางให้คนที่ถามบนถนน',
      'menunjukkan jalan ke orang di jalan',
      'chỉ đường cho ai đó trên phố',
      '道で誰かに道案内をする',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'congrats',
    name: '축하할 때',
    scene: L(
      'congratulating someone on good news',
      'felicitando a alguien por una buena noticia',
      'en félicitant quelqu’un pour une bonne nouvelle',
      'parabenizando alguém por uma boa notícia',
      'แสดงความยินดีกับข่าวดีของใครบางคน',
      'mengucapkan selamat atas kabar baik seseorang',
      'chúc mừng ai đó vì tin vui',
      '良い知らせを聞いて誰かを祝う',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'complaint',
    name: '항의할 때',
    scene: L(
      'making a complaint, firm but polite',
      'haciendo un reclamo, firme pero educado',
      'en faisant une réclamation, ferme mais poli',
      'fazendo uma reclamação, firme mas educado',
      'ร้องเรียน หนักแน่นแต่สุภาพ',
      'menyampaikan keluhan, tegas tapi sopan',
      'phàn nàn, cứng rắn nhưng lịch sự',
      '苦情を言う、毅然と、でも丁寧に',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'job-interview',
    name: '면접에서',
    scene: L(
      'in a job interview, making a good impression',
      'en una entrevista de trabajo, causando buena impresión',
      'en entretien d’embauche, en faisant bonne impression',
      'numa entrevista de emprego, causando boa impressão',
      'ในการสัมภาษณ์งาน สร้างความประทับใจ',
      'di wawancara kerja, memberi kesan baik',
      'trong buổi phỏng vấn xin việc, tạo ấn tượng tốt',
      '面接で、好印象を与える',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'doctor-visit',
    name: '병원에서',
    scene: L(
      'at the doctor, describing how you feel',
      'en el médico, describiendo cómo te sientes',
      'chez le médecin, en décrivant comment tu te sens',
      'no médico, descrevendo como você se sente',
      'ที่หมอ อธิบายอาการที่เป็น',
      'di dokter, menjelaskan keluhanmu',
      'ở bác sĩ, mô tả cảm giác của bạn',
      '病院で、体の調子を説明する',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'airport',
    name: '공항에서',
    scene: L(
      'at the airport, check-in or boarding',
      'en el aeropuerto, facturación o embarque',
      'à l’aéroport, enregistrement ou embarquement',
      'no aeroporto, check-in ou embarque',
      'ที่สนามบิน เช็คอินหรือขึ้นเครื่อง',
      'di bandara, check-in atau boarding',
      'ở sân bay, làm thủ tục hoặc lên máy bay',
      '空港で、チェックインや搭乗',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'crush-text',
    name: '썸 타는 사람한테',
    scene: L(
      'texting someone you have a crush on',
      'escribiéndole a la persona que te gusta',
      'en envoyant un message à la personne qui te plaît',
      'mandando mensagem para a pessoa de quem você gosta',
      'แชทกับคนที่แอบชอบ',
      'mengirim chat ke gebetan',
      'nhắn tin cho người bạn thầm thích',
      '気になる人にメッセージを送る',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'weekend-plans',
    name: '주말 약속',
    scene: L(
      'making weekend plans with a friend',
      'haciendo planes de fin de semana con un amigo',
      'en organisant le week-end avec un ami',
      'combinando planos de fim de semana com um amigo',
      'นัดแผนเที่ยวสุดสัปดาห์กับเพื่อน',
      'membuat rencana akhir pekan dengan teman',
      'lên kế hoạch cuối tuần với bạn',
      '友達と週末の予定を立てる',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'past-story',
    name: '옛날 얘기',
    scene: L(
      'telling a story about something that happened',
      'contando una historia de algo que pasó',
      'en racontant une histoire d’un événement passé',
      'contando uma história de algo que aconteceu',
      'เล่าเรื่องที่เคยเกิดขึ้น',
      'menceritakan kisah tentang sesuatu yang terjadi',
      'kể một câu chuyện đã xảy ra',
      '昔あった出来事を話す',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'ask-stranger',
    name: '낯선 사람한테 부탁',
    scene: L(
      'asking a stranger for a small favor',
      'pidiéndole un pequeño favor a un desconocido',
      'en demandant un petit service à un inconnu',
      'pedindo um pequeno favor a um estranho',
      'ขอความช่วยเหลือเล็กน้อยจากคนแปลกหน้า',
      'meminta tolong sedikit ke orang asing',
      'nhờ người lạ một việc nhỏ',
      '見知らぬ人にちょっとお願いをする',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'market-haggle',
    name: '시장에서 흥정',
    scene: L(
      'haggling over a price at the market',
      'regateando el precio en el mercado',
      'en marchandant le prix au marché',
      'pechinchando o preço na feira',
      'ต่อราคาที่ตลาด',
      'menawar harga di pasar',
      'mặc cả giá ở chợ',
      '市場で値段を交渉する',
    ),
    category: 'situacional',
    builtin: true,
  },
]
