import type { Context, LocalizedString } from '~/lib/domain'
import { DEFAULT_CONTEXTS_EXTRA } from './contexts-extra'

const L = (
  en: string,
  es: string,
  fr: string,
  ptBR: string,
  th: string,
  id: string,
  vi: string,
  ja: string,
): LocalizedString => ({ en, es, fr, 'pt-BR': ptBR, th, id, vi, ja })

const BUILTIN_CONTEXTS: Context[] = [
  {
    id: 'banmal',
    name: '반말',
    scene: L(
      'with your close friend, no formality',
      'con tu 친한 친구, sin formalidad',
      'avec ton ami proche, sans formalité',
      'com seu amigo próximo, sem formalidade',
      'กับเพื่อนสนิท ไม่มีพิธีรีตอง',
      'dengan teman dekat, tanpa formalitas',
      'với bạn thân, không trang trọng',
      '親しい友達と、敬語なし',
    ),
    category: 'formalidad',
    builtin: true,
  },
  {
    id: 'jondaetmal',
    name: '존댓말',
    scene: L(
      "polite normal, with someone you don't know well",
      'polite normal, con alguien que no conoces bien',
      'poli normal, avec quelqu’un que tu ne connais pas bien',
      'educado normal, com alguém que você não conhece bem',
      'สุภาพปกติ กับคนที่ไม่รู้จักดี',
      'sopan normal, dengan orang yang belum kenal',
      'lịch sự thông thường, với người không quen',
      '普通の丁寧語、よく知らない相手と',
    ),
    category: 'formalidad',
    builtin: true,
  },
  {
    id: 'gyeoksik',
    name: '격식체',
    scene: L(
      'formal — business meeting or presentation',
      'formal tipo reunión de trabajo o presentación',
      'formel — réunion ou présentation',
      'formal — reunião de trabalho ou apresentação',
      'ทางการ ประชุมหรือนำเสนอ',
      'formal — rapat kerja atau presentasi',
      'trang trọng — họp công việc hoặc thuyết trình',
      'フォーマル — 会議やプレゼン',
    ),
    category: 'formalidad',
    builtin: true,
  },
  {
    id: 'friends',
    name: '친구한테',
    scene: L(
      'telling something to your friends',
      'contando algo a tus amigos',
      'en racontant quelque chose à tes amis',
      'contando algo para seus amigos',
      'เล่าอะไรให้เพื่อนฟัง',
      'menceritakan sesuatu ke teman-teman',
      'kể chuyện cho bạn bè',
      '友達に何か話す感じ',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'drama',
    name: '드라마 장면',
    scene: L(
      'like a K-drama scene, intense',
      'como diálogo de K-drama, intenso',
      'comme une scène de K-drama, intense',
      'como cena de K-drama, intenso',
      'เหมือนซีนซีรีส์เกาหลี เข้มข้น',
      'seperti adegan K-drama, intens',
      'như cảnh phim Hàn, dữ dội',
      'Kドラマのシーンのように、激しい',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'work',
    name: '직장에서',
    scene: L(
      'in a work context, to a colleague',
      'en contexto laboral, a un compañero',
      'au travail, à un collègue',
      'no trabalho, para um colega',
      'ในที่ทำงาน กับเพื่อนร่วมงาน',
      'di kantor, ke rekan kerja',
      'ở chỗ làm, với đồng nghiệp',
      '職場で、同僚に',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'sns',
    name: 'SNS에',
    scene: L(
      'short, expressive social media post',
      'publicación corta, expresiva',
      'publication courte et expressive',
      'post curto e expressivo',
      'โพสต์โซเชียลสั้นๆ มีอารมณ์',
      'postingan medsos pendek, ekspresif',
      'bài đăng mạng xã hội ngắn, biểu cảm',
      'SNSの短く感情豊かな投稿',
    ),
    category: 'situacional',
    builtin: true,
  },
  {
    id: 'elder',
    name: '어른한테',
    scene: L(
      'to your grandparent, older teacher, senior boss',
      'a tu abuelo/a, profesor mayor, jefe con edad',
      'à ton grand-parent, professeur âgé, patron senior',
      'para seu avô/avó, professor mais velho, chefe sênior',
      'กับปู่ย่า อาจารย์ผู้ใหญ่ เจ้านายอาวุโส',
      'ke kakek/nenek, guru senior, bos senior',
      'với ông bà, thầy lớn tuổi, sếp lớn tuổi',
      'おじいさん・おばあさん、年配の先生や上司に',
    ),
    category: 'situacional',
    builtin: true,
  },
]

export const DEFAULT_CONTEXTS: Context[] = [...BUILTIN_CONTEXTS, ...DEFAULT_CONTEXTS_EXTRA]
