import type { ParticleDef } from '~/lib/domain'
import { L } from './locale'

/**
 * Particle set for the Particle Lab. `grammarKo` keys are verified against
 * `seed/grammars-n1.ts` (은/는 · 이/가 · 을/를 · 에 · 에서 · 도 · 만 ·
 * 에게 / 한테 / 께 · (으)로 · 와/과 · 하고 · (이)랑 · 부터 / 까지) so SRS
 * writes and study-sheet links resolve.
 */
export const PARTICLES: ParticleDef[] = [
  {
    id: 'topic',
    ko: '은/는',
    grammarKo: '은/는',
    role: 'topic',
    afterConsonant: '은',
    afterVowel: '는',
    label: L('topic', 'tema', 'thème', 'tópico', 'หัวเรื่อง', 'topik', 'chủ đề', '主題'),
    hint: L(
      'Marks the topic — what the sentence is about ("as for X…"). Known or general info; also contrast.',
      'Marca el tema — de qué va la frase ("en cuanto a X…"). Info conocida o general; también contraste.',
      'Marque le thème — ce dont on parle (« quant à X… »). Info connue ou générale ; aussi le contraste.',
      'Marca o tópico — sobre o que é a frase ("quanto a X…"). Info conhecida ou geral; também contraste.',
      'บอกหัวเรื่องของประโยค ("สำหรับ X…") ใช้กับข้อมูลที่รู้กันแล้วหรือทั่วไป และการเปรียบต่าง',
      'Menandai topik — apa yang dibicarakan ("mengenai X…"). Info umum/diketahui; juga kontras.',
      'Đánh dấu chủ đề — câu nói về điều gì ("về phần X…"). Thông tin đã biết/chung; cũng dùng đối chiếu.',
      '主題を示す（「Xについて言えば」）。既知・一般的な情報や対比に使う。',
    ),
  },
  {
    id: 'subject',
    ko: '이/가',
    grammarKo: '이/가',
    role: 'subject',
    afterConsonant: '이',
    afterVowel: '가',
    label: L('subject', 'sujeto', 'sujet', 'sujeito', 'ประธาน', 'subjek', 'chủ ngữ', '主語'),
    hint: L(
      'Marks the subject — who/what acts. New info, answers to "who?/what?", and 있다/없다 existence.',
      'Marca el sujeto — quién/qué actúa. Info nueva, respuestas a "¿quién?/¿qué?" y existencia con 있다/없다.',
      'Marque le sujet — qui/quoi agit. Info nouvelle, réponses à « qui ?/quoi ? », existence avec 있다/없다.',
      'Marca o sujeito — quem/o que age. Info nova, respostas a "quem?/o quê?" e existência com 있다/없다.',
      'บอกประธาน — ใคร/อะไรเป็นผู้กระทำ ข้อมูลใหม่ คำตอบของ "ใคร?/อะไร?" และ 있다/없다',
      'Menandai subjek — siapa/apa yang bertindak. Info baru, jawaban "siapa?/apa?", dan 있다/없다.',
      'Đánh dấu chủ ngữ — ai/cái gì hành động. Thông tin mới, trả lời "ai?/cái gì?", và 있다/없다.',
      '主語を示す。新情報、「誰が？何が？」への答え、있다/없다 の存在文に使う。',
    ),
  },
  {
    id: 'object',
    ko: '을/를',
    grammarKo: '을/를',
    role: 'object',
    afterConsonant: '을',
    afterVowel: '를',
    label: L('object', 'objeto', 'objet', 'objeto', 'กรรม', 'objek', 'tân ngữ', '目的語'),
    hint: L(
      'Marks the direct object — what receives the action. Very often dropped in casual speech.',
      'Marca el objeto directo — lo que recibe la acción. Se omite muchísimo al hablar informal.',
      "Marque l'objet direct — ce qui subit l'action. Très souvent omis à l'oral familier.",
      'Marca o objeto direto — o que recebe a ação. Cai com muita frequência na fala casual.',
      'บอกกรรมตรง — สิ่งที่ถูกกระทำ มักถูกตัดออกบ่อยมากในภาษาพูด',
      'Menandai objek langsung — yang menerima aksi. Sangat sering dilepas dalam percakapan santai.',
      'Đánh dấu tân ngữ trực tiếp — đối tượng nhận hành động. Rất hay được lược bỏ khi nói thân mật.',
      '目的語を示す。くだけた会話では非常によく省略される。',
    ),
  },
  {
    id: 'place-static',
    ko: '에',
    grammarKo: '에',
    role: 'place',
    afterConsonant: '에',
    afterVowel: '에',
    label: L(
      'place/time',
      'lugar/tiempo',
      'lieu/temps',
      'lugar/tempo',
      'ที่/เวลา',
      'tempat/waktu',
      'nơi/lúc',
      '場所・時',
    ),
    hint: L(
      'Static location, destination or point in time: 학교에 (to school), 아침에 (in the morning).',
      'Lugar estático, destino o momento: 학교에 (a la escuela), 아침에 (por la mañana).',
      "Lieu statique, destination ou moment : 학교에 (à l'école), 아침에 (le matin).",
      'Lugar estático, destino ou momento: 학교에 (para a escola), 아침에 (de manhã).',
      'สถานที่คงที่ ปลายทาง หรือเวลา: 학교에 (ไปโรงเรียน), 아침에 (ตอนเช้า)',
      'Tempat statis, tujuan, atau waktu: 학교에 (ke sekolah), 아침에 (pagi hari).',
      'Vị trí tĩnh, đích đến hoặc thời điểm: 학교에 (đến trường), 아침에 (vào buổi sáng).',
      '静的な場所・到達点・時点：학교에（学校へ）、아침에（朝に）。',
    ),
  },
  {
    id: 'place-action',
    ko: '에서',
    grammarKo: '에서',
    role: 'place',
    afterConsonant: '에서',
    afterVowel: '에서',
    label: L(
      'place of action',
      'lugar de acción',
      "lieu d'action",
      'lugar da ação',
      'ที่เกิดการกระทำ',
      'tempat aksi',
      'nơi hành động',
      '動作の場所',
    ),
    hint: L(
      'Where an action HAPPENS (or starting point "from"). 도서관에서 공부해요 — unlike 에, rarely dropped.',
      'Donde OCURRE la acción (o punto de partida, "desde"). 도서관에서 공부해요 — a diferencia de 에, casi no se omite.',
      "Là où l'action SE PASSE (ou point de départ, « depuis »). 도서관에서 공부해요 — contrairement à 에, rarement omise.",
      'Onde a ação ACONTECE (ou ponto de partida, "de"). 도서관에서 공부해요 — diferente de 에, quase não cai.',
      'ที่ที่การกระทำเกิดขึ้น (หรือจุดเริ่มต้น "จาก") 도서관에서 공부해요 — ต่างจาก 에 แทบไม่ถูกตัดออก',
      'Tempat aksi TERJADI (atau titik awal, "dari"). 도서관에서 공부해요 — beda dengan 에, jarang dilepas.',
      'Nơi hành động DIỄN RA (hoặc điểm xuất phát, "từ"). 도서관에서 공부해요 — khác 에, hiếm khi bị lược.',
      '動作が行われる場所（または起点「から」）。도서관에서 공부해요。에 と違い省略されにくい。',
    ),
  },
  {
    id: 'also',
    ko: '도',
    grammarKo: '도',
    role: 'addition',
    afterConsonant: '도',
    afterVowel: '도',
    label: L('also', 'también', 'aussi', 'também', 'ด้วย', 'juga', 'cũng', '〜も'),
    hint: L(
      '"Also/too". It REPLACES 은/는 and 이/가 — never 저는도. 저도 = "me too".',
      '"También". REEMPLAZA a 은/는 y 이/가 — nunca 저는도. 저도 = "yo también".',
      '« Aussi ». REMPLACE 은/는 et 이/가 — jamais 저는도. 저도 = « moi aussi ».',
      '"Também". SUBSTITUI 은/는 e 이/가 — nunca 저는도. 저도 = "eu também".',
      '"ด้วย/ก็" ใช้แทนที่ 은/는 และ 이/가 — ห้ามพูด 저는도. 저도 = "ฉันด้วย"',
      '"Juga". MENGGANTIKAN 은/는 dan 이/가 — jangan 저는도. 저도 = "saya juga".',
      '"Cũng". THAY THẾ 은/는 và 이/가 — không bao giờ 저는도. 저도 = "tôi cũng vậy".',
      '「〜も」。은/는・이/가 と置き換わる（저는도 は誤り）。저도＝「私も」。',
    ),
  },
  {
    id: 'only',
    ko: '만',
    grammarKo: '만',
    role: 'addition',
    afterConsonant: '만',
    afterVowel: '만',
    label: L('only', 'solo', 'seulement', 'só / apenas', 'เท่านั้น', 'hanya', 'chỉ', '〜だけ'),
    hint: L(
      '"Only/just X". Replaces 은/는·이/가·을/를 — 빵만 먹어요 = "I eat only bread". Limits to that one thing.',
      '"Solo/nada más que X". Reemplaza a 은/는·이/가·을/를 — 빵만 먹어요 = "como solo pan". Limita a esa única cosa.',
      '« Seulement X ». Remplace 은/는·이/가·을/를 — 빵만 먹어요 = « je ne mange que du pain ». Limite à cette seule chose.',
      '"Só/apenas X". Substitui 은/는·이/가·을/를 — 빵만 먹어요 = "como só pão". Limita àquela única coisa.',
      '"แค่/เท่านั้น" ใช้แทน 은/는·이/가·을/를 — 빵만 먹어요 = "กินแต่ขนมปัง" จำกัดอยู่แค่สิ่งเดียว',
      '"Hanya X". Menggantikan 은/는·이/가·을/를 — 빵만 먹어요 = "makan roti saja". Membatasi pada satu hal itu.',
      '"Chỉ X". Thay thế 은/는·이/가·을/를 — 빵만 먹어요 = "chỉ ăn bánh mì". Giới hạn ở mỗi thứ đó.',
      '「〜だけ」。은/는・이/가・을/를 と置き換わる — 빵만 먹어요＝「パンだけ食べます」。それ一つに限定。',
    ),
  },
  {
    id: 'recipient',
    ko: '한테',
    grammarKo: '에게 / 한테 / 께',
    role: 'recipient',
    afterConsonant: '한테',
    afterVowel: '한테',
    label: L(
      'recipient',
      'destinatario',
      'destinataire',
      'destinatário',
      'ผู้รับ',
      'penerima',
      'người nhận',
      '受け手',
    ),
    hint: L(
      'Marks the person who RECEIVES: 친구한테 (to a friend). 한테 is casual speech; 에게 is its written twin; 께 is the honorific.',
      'Marca a la persona que RECIBE: 친구한테 (a un amigo). 한테 es del habla informal; 에게 es su gemela escrita; 께 es la forma honorífica.',
      "Marque la personne qui REÇOIT : 친구한테 (à un ami). 한테 est familier à l'oral ; 에게 est son équivalent écrit ; 께 est honorifique.",
      'Marca a pessoa que RECEBE: 친구한테 (a um amigo). 한테 é da fala informal; 에게 é a gêmea escrita; 께 é a forma honorífica.',
      'บอกคนที่ "รับ": 친구한테 (ให้เพื่อน) 한테 ใช้ในภาษาพูด, 에게 ใช้เขียน, 께 เป็นรูปยกย่อง',
      'Menandai orang yang MENERIMA: 친구한테 (kepada teman). 한테 untuk percakapan; 에게 versi tulisan; 께 bentuk hormat.',
      'Đánh dấu người NHẬN: 친구한테 (cho một người bạn). 한테 dùng khi nói; 에게 là bản viết; 께 là dạng kính ngữ.',
      '「受け取る人」を示す：친구한테（友達に）。한테 は口語、에게 は文語、께 は尊敬語。',
    ),
  },
  {
    id: 'by-means',
    ko: '(으)로',
    grammarKo: '(으)로',
    role: 'means',
    afterConsonant: '으로',
    afterVowel: '로',
    label: L(
      'means / way',
      'medio / modo',
      'moyen',
      'meio / modo',
      'วิธี / ทาง',
      'cara / alat',
      'phương tiện',
      '手段',
    ),
    hint: L(
      'Means, instrument or direction: 버스로 (by bus), 연필로 (with a pencil). After a vowel OR ㄹ → 로; otherwise 으로.',
      'Medio, instrumento o dirección: 버스로 (en autobús), 연필로 (con lápiz). Tras vocal O ㄹ → 로; si no, 으로.',
      'Moyen, instrument ou direction : 버스로 (en bus), 연필로 (au crayon). Après voyelle OU ㄹ → 로 ; sinon 으로.',
      'Meio, instrumento ou direção: 버스로 (de ônibus), 연필로 (com lápis). Após vogal OU ㄹ → 로; senão 으로.',
      'วิธี เครื่องมือ หรือทิศทาง: 버스로 (โดยรถบัส), 연필로 (ด้วยดินสอ) หลังสระหรือ ㄹ → 로 ไม่งั้น 으로',
      'Cara, alat, atau arah: 버스로 (naik bus), 연필로 (pakai pensil). Setelah vokal ATAU ㄹ → 로; selain itu 으로.',
      'Phương tiện, công cụ hoặc hướng: 버스로 (bằng xe buýt), 연필로 (bằng bút chì). Sau nguyên âm HOẶC ㄹ → 로; còn lại 으로.',
      '手段・道具・方向：버스로（バスで）、연필로（鉛筆で）。母音か ㄹ の後は 로、それ以外は 으로。',
    ),
  },
  {
    id: 'and',
    ko: '와/과',
    grammarKo: '와/과 · 하고 · (이)랑',
    role: 'connective',
    afterConsonant: '과',
    afterVowel: '와',
    label: L(
      'and / with',
      'y / con',
      'et / avec',
      'e / com',
      'และ / กับ',
      'dan / dengan',
      'và / với',
      '〜と',
    ),
    hint: L(
      'Joins two nouns ("A and B") or "with": 사과와 바나나. 과 after a consonant, 와 after a vowel. Bookish — 하고 and (이)랑 are the spoken forms.',
      'Une dos sustantivos ("A y B") o "con": 사과와 바나나. 과 tras consonante, 와 tras vocal. De registro escrito — 하고 y (이)랑 son las formas habladas.',
      'Relie deux noms (« A et B ») ou « avec » : 사과와 바나나. 과 après consonne, 와 après voyelle. Littéraire — 하고 et (이)랑 sont les formes orales.',
      'Une dois substantivos ("A e B") ou "com": 사과와 바나나. 과 após consoante, 와 após vogal. De registro escrito — 하고 e (이)랑 são as formas faladas.',
      'เชื่อมคำนามสองคำ ("A และ B") หรือ "กับ": 사과와 바나나 과 หลังพยัญชนะ, 와 หลังสระ เป็นภาษาเขียน — 하고 กับ (이)랑 ใช้พูด',
      'Menggabungkan dua kata benda ("A dan B") atau "dengan": 사과와 바나나. 과 setelah konsonan, 와 setelah vokal. Formal — 하고 dan (이)랑 versi lisan.',
      'Nối hai danh từ ("A và B") hoặc "với": 사과와 바나나. 과 sau phụ âm, 와 sau nguyên âm. Văn viết — 하고 và (이)랑 là dạng nói.',
      '二つの名詞をつなぐ（「AとB」）や「〜と一緒に」：사과와 바나나。子音の後は 과、母音の後は 와。文語的で、하고・(이)랑 が口語。',
    ),
  },
  {
    id: 'from',
    ko: '부터',
    grammarKo: '부터 / 까지',
    role: 'addition',
    afterConsonant: '부터',
    afterVowel: '부터',
    label: L(
      'from (start)',
      'desde',
      'à partir de',
      'desde / a partir de',
      'ตั้งแต่',
      'dari / mulai',
      'từ',
      '〜から',
    ),
    hint: L(
      'Starting point in time or sequence: 아홉 시부터 (from 9 o\'clock). Pairs with 까지 (until). For a place "from", use 에서.',
      'Punto de inicio en el tiempo o una secuencia: 아홉 시부터 (desde las nueve). Se empareja con 까지 (hasta). Para lugares ("desde"), usa 에서.',
      "Point de départ dans le temps ou une séquence : 아홉 시부터 (à partir de neuf heures). Va avec 까지 (jusqu'à). Pour un lieu (« depuis »), on utilise 에서.",
      'Ponto de início no tempo ou numa sequência: 아홉 시부터 (a partir das nove). Forma par com 까지 (até). Para lugares ("de"), use 에서.',
      'จุดเริ่มต้นของเวลา/ลำดับ: 아홉 시부터 (ตั้งแต่เก้าโมง) คู่กับ 까지 (จนถึง) ถ้าเป็นสถานที่ "จาก" ใช้ 에서',
      'Titik awal waktu atau urutan: 아홉 시부터 (mulai jam sembilan). Berpasangan dengan 까지 (sampai). Untuk tempat ("dari"), pakai 에서.',
      'Điểm bắt đầu về thời gian hoặc trình tự: 아홉 시부터 (từ chín giờ). Đi cặp với 까지 (đến). Với nơi chốn ("từ"), dùng 에서.',
      '時間や順序の起点：아홉 시부터（9時から）。까지（まで）と対。場所の「から」は 에서。',
    ),
  },
  {
    id: 'until',
    ko: '까지',
    grammarKo: '부터 / 까지',
    role: 'addition',
    afterConsonant: '까지',
    afterVowel: '까지',
    label: L('until / up to', 'hasta', "jusqu'à", 'até', 'จนถึง', 'sampai', 'đến', '〜まで'),
    hint: L(
      'End point in time or place: 다섯 시까지 (until 5), 집까지 (all the way home). Pairs with 부터/에서; can also mean "even / as far as".',
      'Punto final en el tiempo o el espacio: 다섯 시까지 (hasta las cinco), 집까지 (hasta casa). Se empareja con 부터/에서; también "incluso / hasta".',
      "Point d'arrivée dans le temps ou l'espace : 다섯 시까지 (jusqu'à cinq heures), 집까지 (jusqu'à la maison). Va avec 부터/에서 ; peut aussi signifier « même ».",
      'Ponto final no tempo ou no espaço: 다섯 시까지 (até as cinco), 집까지 (até em casa). Forma par com 부터/에서; também pode significar "até mesmo".',
      'จุดสิ้นสุดของเวลา/สถานที่: 다섯 시까지 (จนถึงห้าโมง), 집까지 (จนถึงบ้าน) คู่กับ 부터/에서 และยังแปลว่า "แม้กระทั่ง" ได้',
      'Titik akhir waktu atau tempat: 다섯 시까지 (sampai jam lima), 집까지 (sampai rumah). Berpasangan dengan 부터/에서; bisa juga berarti "bahkan".',
      'Điểm kết thúc về thời gian hoặc nơi chốn: 다섯 시까지 (đến năm giờ), 집까지 (đến tận nhà). Đi cặp với 부터/에서; cũng có nghĩa "thậm chí".',
      '時間や場所の終点：다섯 시까지（5時まで）、집까지（家まで）。부터/에서 と対。「〜さえ」の意味も。',
    ),
  },
]

export function particleById(id: string): ParticleDef | undefined {
  return PARTICLES.find((p) => p.id === id)
}
