import type { DrillItem } from '~/lib/domain'
import { L } from './locale'

/** 은/는 vs 이/가 shock-filter drill. Fixed pedagogical order. */
export const PARTICLE_DRILLS: DrillItem[] = [
  {
    id: 'd01-jeo',
    cue: L(
      'You introduce yourself for the first time.',
      'Te presentas por primera vez.',
      'Tu te présentes pour la première fois.',
      'Você se apresenta pela primeira vez.',
      'คุณแนะนำตัวครั้งแรก',
      'Kamu memperkenalkan diri untuk pertama kali.',
      'Bạn tự giới thiệu lần đầu.',
      '初めて自己紹介する。',
    ),
    noun: '저',
    rest: ' 학생이에요.',
    setId: 'topic-subject',
    familyIndex: 0,
    reason: L(
      'Introducing yourself sets the TOPIC: "as for me…" → 은/는.',
      'Presentarte establece el TEMA: "en cuanto a mí…" → 은/는.',
      'Se présenter pose le THÈME : « quant à moi… » → 은/는.',
      'Apresentar-se define o TÓPICO: "quanto a mim…" → 은/는.',
      'การแนะนำตัวคือการตั้งหัวเรื่อง: "สำหรับฉัน…" → 은/는',
      'Memperkenalkan diri menetapkan TOPIK: "mengenai saya…" → 은/는.',
      'Tự giới thiệu là đặt CHỦ ĐỀ: "về phần tôi…" → 은/는.',
      '自己紹介は主題の提示（「私について言えば」）→ 은/는。',
    ),
    trans: L(
      'I am a student.',
      'Yo soy estudiante.',
      'Je suis étudiant·e.',
      'Eu sou estudante.',
      'ฉันเป็นนักเรียน',
      'Saya pelajar.',
      'Tôi là học sinh.',
      '私は学生です。',
    ),
  },
  {
    id: 'd02-chingu',
    cue: L(
      'You answer: "WHO came?"',
      'Respondes a: «¿QUIÉN vino?»',
      'Tu réponds à : « QUI est venu ? »',
      'Você responde: "QUEM veio?"',
      'คุณตอบคำถาม: "ใครมา?"',
      'Kamu menjawab: "SIAPA yang datang?"',
      'Bạn trả lời: "AI đã đến?"',
      '「誰が来たの？」に答える。',
    ),
    noun: '친구',
    rest: ' 왔어요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'Answers to "who?/what?" point at NEW info → 이/가.',
      'Las respuestas a "¿quién?/¿qué?" señalan info NUEVA → 이/가.',
      'Les réponses à « qui ?/quoi ? » désignent une info NOUVELLE → 이/가.',
      'Respostas a "quem?/o quê?" apontam info NOVA → 이/가.',
      'คำตอบของ "ใคร?/อะไร?" ชี้ข้อมูลใหม่ → 이/가',
      'Jawaban atas "siapa?/apa?" menunjuk info BARU → 이/가.',
      'Câu trả lời cho "ai?/cái gì?" chỉ thông tin MỚI → 이/가.',
      '「誰が？何が？」への答えは新情報 → 이/가。',
    ),
    trans: L(
      'A friend came.',
      'Vino un amigo.',
      'Un ami est venu.',
      'Um amigo veio.',
      'เพื่อนมา',
      'Seorang teman datang.',
      'Một người bạn đã đến.',
      '友達が来ました。',
    ),
  },
  {
    id: 'd03-hyeong',
    cue: L(
      'You talk about your older brother in general.',
      'Hablas de tu hermano mayor en general.',
      'Tu parles de ton grand frère en général.',
      'Você fala do seu irmão mais velho em geral.',
      'คุณเล่าเรื่องพี่ชายแบบทั่วไป',
      'Kamu bercerita tentang kakak laki-lakimu secara umum.',
      'Bạn kể về anh trai một cách chung chung.',
      '兄について一般的な話をする。',
    ),
    noun: '형',
    rest: ' 회사원이에요.',
    setId: 'topic-subject',
    familyIndex: 0,
    reason: L(
      'A general statement about someone known → topic 은/는. 형 ends in a consonant → 은.',
      'Una afirmación general sobre alguien conocido → tema 은/는. 형 termina en consonante → 은.',
      "Une affirmation générale sur quelqu'un de connu → thème 은/는. 형 finit par consonne → 은.",
      'Afirmação geral sobre alguém conhecido → tópico 은/는. 형 termina em consoante → 은.',
      'การพูดทั่วไปถึงคนที่รู้จัก → หัวเรื่อง 은/는. 형 ลงท้ายพยัญชนะ → 은',
      'Pernyataan umum tentang orang yang dikenal → topik 은/는. 형 berakhir konsonan → 은.',
      'Phát biểu chung về người đã biết → chủ đề 은/는. 형 kết thúc phụ âm → 은.',
      '既知の人物への一般的な記述 → 主題 은/는。형 は子音終わり → 은。',
    ),
    trans: L(
      'My older brother is an office worker.',
      'Mi hermano mayor es oficinista.',
      'Mon grand frère est employé de bureau.',
      'Meu irmão mais velho é funcionário de escritório.',
      'พี่ชายเป็นพนักงานบริษัท',
      'Kakakku karyawan kantor.',
      'Anh trai tôi là nhân viên văn phòng.',
      '兄は会社員です。',
    ),
  },
  {
    id: 'd04-chaek',
    cue: L(
      '"What\'s on the table?" — existence with 있다.',
      '«¿Qué hay en la mesa?» — existencia con 있다.',
      "« Qu'y a-t-il sur la table ? » — existence avec 있다.",
      '"O que tem na mesa?" — existência com 있다.',
      '"บนโต๊ะมีอะไร?" — การมีอยู่กับ 있다',
      '"Ada apa di meja?" — keberadaan dengan 있다.',
      '"Trên bàn có gì?" — tồn tại với 있다.',
      '「机に何がある？」— 있다 の存在文。',
    ),
    noun: '책',
    rest: ' 있어요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'Existence with 있다/없다 takes 이/가. 책 ends in a consonant → 이.',
      'La existencia con 있다/없다 lleva 이/가. 책 termina en consonante → 이.',
      "L'existence avec 있다/없다 prend 이/가. 책 finit par consonne → 이.",
      'Existência com 있다/없다 leva 이/가. 책 termina em consoante → 이.',
      'การมีอยู่กับ 있다/없다 ใช้ 이/가. 책 ลงท้ายพยัญชนะ → 이',
      'Keberadaan dengan 있다/없다 memakai 이/가. 책 berakhir konsonan → 이.',
      'Tồn tại với 있다/없다 dùng 이/가. 책 kết thúc phụ âm → 이.',
      '있다/없다 の存在文は 이/가。책 は子音終わり → 이。',
    ),
    trans: L(
      "There's a book.",
      'Hay un libro.',
      'Il y a un livre.',
      'Tem um livro.',
      'มีหนังสือ',
      'Ada buku.',
      'Có một quyển sách.',
      '本があります。',
    ),
  },
  {
    id: 'd05-bi',
    cue: L(
      'You look out the window and report the weather (new info).',
      'Miras por la ventana y comentas el clima (info nueva).',
      'Tu regardes par la fenêtre et annonces la météo (info nouvelle).',
      'Você olha pela janela e comenta o tempo (info nova).',
      'คุณมองออกหน้าต่างแล้วบอกสภาพอากาศ (ข้อมูลใหม่)',
      'Kamu melihat ke jendela dan melaporkan cuaca (info baru).',
      'Bạn nhìn ra cửa sổ và nói về thời tiết (thông tin mới).',
      '窓の外を見て天気を伝える（新情報）。',
    ),
    noun: '비',
    rest: ' 와요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'Weather phenomena appear as NEW info → 이/가. «비는 와요» would sound contrastive.',
      'Los fenómenos del clima aparecen como info NUEVA → 이/가. «비는 와요» sonaría a contraste.',
      'Les phénomènes météo surgissent comme info NOUVELLE → 이/가. « 비는 와요 » sonnerait contrastif.',
      'Fenômenos do tempo surgem como info NOVA → 이/가. «비는 와요» soaria contrastivo.',
      'ปรากฏการณ์อากาศคือข้อมูลใหม่ → 이/가. «비는 와요» จะฟังดูเชิงเปรียบต่าง',
      'Fenomena cuaca muncul sebagai info BARU → 이/가. «비는 와요» terdengar kontras.',
      'Hiện tượng thời tiết là thông tin MỚI → 이/가. «비는 와요» nghe như đối chiếu.',
      '天気は新情報として現れる → 이/가。「비는 와요」は対比に聞こえる。',
    ),
    trans: L(
      "It's raining.",
      'Está lloviendo.',
      'Il pleut.',
      'Está chovendo.',
      'ฝนกำลังตก',
      'Sedang hujan.',
      'Trời đang mưa.',
      '雨が降っています。',
    ),
  },
  {
    id: 'd06-goyangi',
    cue: L(
      'A general truth: cats (as a species) are cute.',
      'Una verdad general: los gatos (como especie) son lindos.',
      'Une vérité générale : les chats (en général) sont mignons.',
      'Uma verdade geral: gatos (como espécie) são fofos.',
      'ความจริงทั่วไป: แมว (โดยรวม) น่ารัก',
      'Kebenaran umum: kucing (sebagai spesies) itu lucu.',
      'Chân lý chung: mèo (nói chung) dễ thương.',
      '一般論：猫（という種）はかわいい。',
    ),
    noun: '고양이',
    rest: ' 귀여워요.',
    setId: 'topic-subject',
    familyIndex: 0,
    reason: L(
      'General truths and categories take topic 은/는: "cats (in general)…".',
      'Las verdades generales y categorías llevan tema 은/는: "los gatos (en general)…".',
      'Les vérités générales prennent le thème 은/는 : « les chats (en général)… ».',
      'Verdades gerais e categorias levam tópico 은/는: "gatos (em geral)…".',
      'ความจริงทั่วไปและหมวดหมู่ใช้หัวเรื่อง 은/는: "แมว (โดยทั่วไป)…"',
      'Kebenaran umum dan kategori memakai topik 은/는: "kucing (pada umumnya)…".',
      'Chân lý chung và phạm trù dùng chủ đề 은/는: "mèo (nói chung)…".',
      '一般論・カテゴリーは主題 은/는：「猫（一般）は…」。',
    ),
    trans: L(
      'Cats are cute.',
      'Los gatos son lindos.',
      'Les chats sont mignons.',
      'Os gatos são fofos.',
      'แมวน่ารัก',
      'Kucing itu lucu.',
      'Mèo dễ thương.',
      '猫はかわいいです。',
    ),
  },
  {
    id: 'd07-sigan',
    cue: L(
      'You apologize: you have no time (없다).',
      'Te disculpas: no tienes tiempo (없다).',
      "Tu t'excuses : tu n'as pas le temps (없다).",
      'Você se desculpa: não tem tempo (없다).',
      'คุณขอโทษ: ไม่มีเวลา (없다)',
      'Kamu minta maaf: tidak punya waktu (없다).',
      'Bạn xin lỗi: không có thời gian (없다).',
      '謝る：時間がない（없다）。',
    ),
    noun: '시간',
    rest: ' 없어요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      '있다/없다 (have/not have, exist) pair with 이/가. 시간 ends in a consonant → 이.',
      '있다/없다 (tener/no tener, existir) van con 이/가. 시간 termina en consonante → 이.',
      '있다/없다 (avoir/ne pas avoir) vont avec 이/가. 시간 finit par consonne → 이.',
      '있다/없다 (ter/não ter, existir) combinam com 이/가. 시간 termina em consoante → 이.',
      '있다/없다 (มี/ไม่มี) ใช้กับ 이/가. 시간 ลงท้ายพยัญชนะ → 이',
      '있다/없다 (punya/tidak punya) berpasangan dengan 이/가. 시간 berakhir konsonan → 이.',
      '있다/없다 (có/không có) đi với 이/가. 시간 kết thúc phụ âm → 이.',
      '있다/없다（ある・ない）は 이/가 と共起。시간 は子音終わり → 이。',
    ),
    trans: L(
      'I have no time.',
      'No tengo tiempo.',
      "Je n'ai pas le temps.",
      'Não tenho tempo.',
      'ไม่มีเวลา',
      'Tidak ada waktu.',
      'Tôi không có thời gian.',
      '時間がありません。',
    ),
  },
  {
    id: 'd08-keopi',
    cue: L(
      'Contrast: coffee yes, tea no.',
      'Contraste: el café sí, el té no.',
      'Contraste : le café oui, le thé non.',
      'Contraste: café sim, chá não.',
      'เปรียบต่าง: กาแฟใช่ ชาไม่',
      'Kontras: kopi iya, teh tidak.',
      'Đối chiếu: cà phê thì thích, trà thì không.',
      '対比：コーヒーは好き、お茶は嫌い。',
    ),
    noun: '커피',
    rest: ' 좋아하지만 차는 안 마셔요.',
    setId: 'topic-subject',
    familyIndex: 0,
    reason: L(
      'Explicit contrast between two things is the signature use of 은/는.',
      'El contraste explícito entre dos cosas es el uso estrella de 은/는.',
      "Le contraste explicite entre deux choses est l'usage signature de 은/는.",
      'Contraste explícito entre duas coisas é o uso clássico de 은/는.',
      'การเปรียบต่างชัดเจนระหว่างสองสิ่งคือการใช้เด่นของ 은/는',
      'Kontras eksplisit antara dua hal adalah penggunaan khas 은/는.',
      'Đối chiếu rõ ràng giữa hai thứ là cách dùng đặc trưng của 은/는.',
      '二つの物事の明示的な対比は 은/는 の代表的用法。',
    ),
    trans: L(
      "I like coffee, but I don't drink tea.",
      'El café me gusta, pero no bebo té.',
      "J'aime le café, mais je ne bois pas de thé.",
      'Gosto de café, mas não bebo chá.',
      'ชอบกาแฟ แต่ไม่ดื่มชา',
      'Suka kopi, tapi tidak minum teh.',
      'Thích cà phê, nhưng không uống trà.',
      'コーヒーは好きですが、お茶は飲みません。',
    ),
  },
  {
    id: 'd09-naemsae',
    cue: L(
      'You suddenly notice a smell (new sensory info).',
      'De repente notas un olor (info sensorial nueva).',
      'Tu remarques soudain une odeur (info sensorielle nouvelle).',
      'Você de repente nota um cheiro (info sensorial nova).',
      'จู่ๆ คุณได้กลิ่น (ข้อมูลใหม่ทางประสาทสัมผัส)',
      'Tiba-tiba kamu mencium bau (info indrawi baru).',
      'Bạn chợt nhận ra một mùi hương (thông tin cảm giác mới).',
      'ふと匂いに気づく（新しい感覚情報）。',
    ),
    noun: '냄새',
    rest: ' 좋아요!',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'Something you just perceived = new info bursting in → 이/가.',
      'Algo que acabas de percibir = info nueva que irrumpe → 이/가.',
      'Ce que tu viens de percevoir = info nouvelle qui surgit → 이/가.',
      'Algo que você acabou de perceber = info nova surgindo → 이/가.',
      'สิ่งที่เพิ่งรับรู้ = ข้อมูลใหม่ที่โผล่มา → 이/가',
      'Sesuatu yang baru kamu rasakan = info baru yang muncul → 이/가.',
      'Điều bạn vừa cảm nhận = thông tin mới ập đến → 이/가.',
      '今知覚したばかりのもの＝飛び込んでくる新情報 → 이/가。',
    ),
    trans: L(
      'It smells good!',
      '¡Qué bien huele!',
      'Ça sent bon !',
      'Que cheiro bom!',
      'กลิ่นหอมจัง!',
      'Baunya enak!',
      'Thơm quá!',
      'いい匂いですね！',
    ),
  },
  {
    id: 'd10-mul',
    cue: L(
      "You're still talking about the water you already mentioned.",
      'Sigues hablando del agua que ya mencionaron.',
      "Vous parlez encore de l'eau déjà mentionnée.",
      'Vocês continuam falando da água já mencionada.',
      'ยังคุยเรื่องน้ำที่พูดถึงไปแล้ว',
      'Kalian masih membicarakan air yang sudah disebut.',
      'Vẫn đang nói về nước đã nhắc đến trước đó.',
      'さっき話に出た水について話を続けている。',
    ),
    noun: '물',
    rest: ' 맛있어요.',
    setId: 'topic-subject',
    familyIndex: 0,
    reason: L(
      'Already-mentioned info becomes the TOPIC → 은/는. 물 ends in a consonant → 은.',
      'Lo ya mencionado pasa a ser TEMA → 은/는. 물 termina en consonante → 은.',
      'Une info déjà mentionnée devient le THÈME → 은/는. 물 finit par consonne → 은.',
      'Info já mencionada vira TÓPICO → 은/는. 물 termina em consoante → 은.',
      'สิ่งที่พูดถึงแล้วกลายเป็นหัวเรื่อง → 은/는. 물 ลงท้ายพยัญชนะ → 은',
      'Info yang sudah disebut menjadi TOPIK → 은/는. 물 berakhir konsonan → 은.',
      'Thông tin đã nhắc trở thành CHỦ ĐỀ → 은/는. 물 kết thúc phụ âm → 은.',
      '既出の情報は主題になる → 은/는。물 は子音終わり → 은。',
    ),
    trans: L(
      'The water is tasty.',
      'El agua está rica.',
      "L'eau est bonne.",
      'A água é gostosa.',
      'น้ำอร่อย',
      'Airnya enak.',
      'Nước ngon.',
      'その水はおいしいです。',
    ),
  },
  {
    id: 'd11-horangi',
    cue: L(
      'First mention in a story: "Once upon a time…".',
      'Primera mención en un cuento: «Érase una vez…».',
      'Première mention dans un conte : « Il était une fois… ».',
      'Primeira menção num conto: "Era uma vez…".',
      'การกล่าวถึงครั้งแรกในนิทาน: "กาลครั้งหนึ่ง…"',
      'Penyebutan pertama dalam dongeng: "Pada zaman dahulu…".',
      'Lần đầu nhắc đến trong truyện: "Ngày xửa ngày xưa…".',
      '物語の初登場：「昔々…」。',
    ),
    lead: '옛날에 ',
    noun: '호랑이',
    rest: ' 살았어요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'First mention of a character = brand-new info → 이/가. (Later mentions switch to 은/는.)',
      'La primera mención de un personaje = info totalmente nueva → 이/가. (Las siguientes cambian a 은/는.)',
      "La première mention d'un personnage = info toute nouvelle → 이/가. (Ensuite on passe à 은/는.)",
      'A primeira menção de um personagem = info nova → 이/가. (Depois muda para 은/는.)',
      'การแนะนำตัวละครครั้งแรก = ข้อมูลใหม่ → 이/가 (ครั้งถัดไปเปลี่ยนเป็น 은/는)',
      'Penyebutan pertama tokoh = info baru → 이/가. (Selanjutnya beralih ke 은/는.)',
      'Nhân vật xuất hiện lần đầu = thông tin hoàn toàn mới → 이/가. (Các lần sau chuyển sang 은/는.)',
      '登場人物の初出は完全な新情報 → 이/가。（以後は 은/는 に切り替わる。）',
    ),
    trans: L(
      'Once upon a time there lived a tiger.',
      'Érase una vez un tigre que vivía allí.',
      'Il était une fois un tigre qui vivait là.',
      'Era uma vez um tigre que ali vivia.',
      'กาลครั้งหนึ่งมีเสือตัวหนึ่งอาศัยอยู่',
      'Pada zaman dahulu hiduplah seekor harimau.',
      'Ngày xưa có một con hổ sinh sống.',
      '昔々、トラが住んでいました。',
    ),
  },
  {
    id: 'd12-kokkiri',
    cue: L(
      "You highlight the elephant's NOSE (the elephant is already the topic).",
      'Destacas la NARIZ del elefante (el elefante ya es el tema).',
      "Tu mets en relief la TROMPE de l'éléphant (l'éléphant est déjà le thème).",
      'Você destaca a TROMBA do elefante (o elefante já é o tópico).',
      'คุณเน้นจมูกของช้าง (ช้างเป็นหัวเรื่องอยู่แล้ว)',
      'Kamu menonjolkan HIDUNG gajah (gajah sudah jadi topik).',
      'Bạn nhấn mạnh cái MŨI của con voi (voi đã là chủ đề).',
      '象の鼻を際立たせる（象はすでに主題）。',
    ),
    lead: '코끼리는 ',
    noun: '코',
    rest: ' 길어요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'Classic double pattern: topic with 는 + highlighted feature with 가. "As for elephants, the NOSE is long."',
      'Patrón doble clásico: tema con 는 + rasgo destacado con 가. "El elefante, la NARIZ la tiene larga."',
      "Double construction classique : thème en 는 + trait saillant en 가. « L'éléphant, c'est la TROMPE qui est longue. »",
      'Padrão duplo clássico: tópico com 는 + traço destacado com 가. "O elefante, o NARIZ é longo."',
      'โครงสร้างคู่คลาสสิก: หัวเรื่องใช้ 는 + ลักษณะเด่นใช้ 가 "ช้างน่ะ จมูกยาว"',
      'Pola ganda klasik: topik dengan 는 + ciri yang ditonjolkan dengan 가. "Gajah itu, HIDUNGNYA panjang."',
      'Mẫu kép kinh điển: chủ đề với 는 + đặc điểm nổi bật với 가. "Con voi thì cái MŨI dài."',
      '典型的な二重構文：主題は 는、際立たせる特徴は 가。「象は鼻が長い」。',
    ),
    trans: L(
      'Elephants have long noses. (lit. "as for elephants, the nose is long")',
      'El elefante tiene la nariz larga. (lit. «el elefante, la nariz es larga»)',
      "L'éléphant a une longue trompe. (litt. « l'éléphant, la trompe est longue »)",
      'O elefante tem a tromba longa. (lit. "o elefante, o nariz é longo")',
      'ช้างจมูกยาว',
      'Gajah hidungnya panjang.',
      'Voi có cái mũi dài.',
      '象は鼻が長いです。',
    ),
  },

  // -- subject-object --
  {
    id: 'so-01-sagwa',
    cue: L(
      'Apples taste good (a state, not an action).',
      'Las manzanas saben bien (un estado, no una acción).',
      'Les pommes ont bon goût (un état, pas une action).',
      'Maçãs têm um gosto bom (um estado, não uma ação).',
      'แอปเปิลอร่อย (เป็นสภาพ ไม่ใช่การกระทำ)',
      'Apel rasanya enak (sebuah keadaan, bukan tindakan).',
      'Táo ngon (một trạng thái, không phải hành động).',
      'りんごはおいしい（動作ではなく状態）。',
    ),
    lead: '',
    noun: '사과',
    rest: ' 맛있어요.',
    setId: 'subject-object',
    familyIndex: 0,
    reason: L(
      'A stative verb (맛있다) marks its theme with the subject 이/가. 사과 ends in a vowel → 가.',
      'Un verbo de estado (맛있다) marca su tema con el sujeto 이/가. 사과 termina en vocal → 가.',
      "Un verbe d'état (맛있다) marque son thème avec le sujet 이/가. 사과 finit par une voyelle → 가.",
      'Um verbo de estado (맛있다) marca seu tema com o sujeito 이/가. 사과 termina em vogal → 가.',
      'คำกริยาบอกสภาพ (맛있다) ทำเครื่องหมายหัวเรื่องด้วยประธาน 이/가 사과 ลงท้ายด้วยสระ → 가',
      'Verba statif (맛있다) menandai temanya dengan subjek 이/가. 사과 berakhir dengan vokal → 가.',
      'Động từ trạng thái (맛있다) đánh dấu chủ đề bằng chủ ngữ 이/가. 사과 kết thúc bằng nguyên âm → 가.',
      '状態動詞（맛있다）は主題を主語の 이/가 で示す。사과 は母音で終わる → 가。',
    ),
    trans: L(
      'Apples taste good.',
      'Las manzanas saben bien.',
      'Les pommes ont bon goût.',
      'Maçãs têm um gosto bom.',
      'แอปเปิลอร่อย',
      'Apel rasanya enak.',
      'Táo ngon.',
      'りんごはおいしいです。',
    ),
  },
  {
    id: 'so-02-sagwa',
    cue: L(
      'You actively like apples.',
      'Te gustan activamente las manzanas.',
      'Tu aimes activement les pommes.',
      'Você gosta ativamente de maçãs.',
      'คุณชอบแอปเปิลอย่างจริงจัง',
      'Kamu aktif menyukai apel.',
      'Bạn chủ động thích táo.',
      'りんごを能動的に好む。',
    ),
    lead: '',
    noun: '사과',
    rest: ' 좋아해요.',
    setId: 'subject-object',
    familyIndex: 1,
    reason: L(
      'A transitive verb (좋아하다) takes the object 을/를. 사과 ends in a vowel → 를.',
      'Un verbo transitivo (좋아하다) lleva el objeto 을/를. 사과 termina en vocal → 를.',
      "Un verbe transitif (좋아하다) prend l'objet 을/를. 사과 finit par une voyelle → 를.",
      'Um verbo transitivo (좋아하다) leva o objeto 을/를. 사과 termina em vogal → 를.',
      'คำกริยาสกรรม (좋아하다) ใช้กรรม 을/를 사과 ลงท้ายด้วยสระ → 를',
      'Verba transitif (좋아하다) memakai objek 을/를. 사과 berakhir dengan vokal → 를.',
      'Động từ ngoại động (좋아하다) lấy tân ngữ 을/를. 사과 kết thúc bằng nguyên âm → 를.',
      '他動詞（좋아하다）は目的語の 을/를 を取る。사과 は母音で終わる → 를。',
    ),
    trans: L(
      'I like apples.',
      'Me gustan las manzanas.',
      "J'aime les pommes.",
      'Eu gosto de maçãs.',
      'ฉันชอบแอปเปิล',
      'Saya suka apel.',
      'Tôi thích táo.',
      '私はりんごが好きです。',
    ),
  },
  {
    id: 'so-03-goyangi',
    cue: L(
      'There exists a cat.',
      'Existe un gato.',
      'Il existe un chat.',
      'Existe um gato.',
      'มีแมวอยู่',
      'Ada seekor kucing.',
      'Có một con mèo.',
      '猫が存在する。',
    ),
    lead: '',
    noun: '고양이',
    rest: ' 있어요.',
    setId: 'subject-object',
    familyIndex: 0,
    reason: L(
      '있다 (existence) marks its theme with the subject 이/가. 고양이 ends in a vowel → 가.',
      '있다 (existencia) marca su tema con el sujeto 이/가. 고양이 termina en vocal → 가.',
      '있다 (existence) marque son thème avec le sujet 이/가. 고양이 finit par une voyelle → 가.',
      '있다 (existência) marca seu tema com o sujeito 이/가. 고양이 termina em vogal → 가.',
      '있다 (การมีอยู่) ทำเครื่องหมายหัวเรื่องด้วยประธาน 이/가 고양이 ลงท้ายด้วยสระ → 가',
      '있다 (keberadaan) menandai temanya dengan subjek 이/가. 고양이 berakhir dengan vokal → 가.',
      '있다 (sự tồn tại) đánh dấu chủ đề bằng chủ ngữ 이/가. 고양이 kết thúc bằng nguyên âm → 가.',
      '있다（存在）は主題を主語の 이/가 で示す。고양이 は母音で終わる → 가。',
    ),
    trans: L(
      'There is a cat.',
      'Hay un gato.',
      'Il y a un chat.',
      'Tem um gato.',
      'มีแมว',
      'Ada kucing.',
      'Có một con mèo.',
      '猫がいます。',
    ),
  },
  {
    id: 'so-04-uyu',
    cue: L(
      'You drink milk.',
      'Bebes leche.',
      'Tu bois du lait.',
      'Você bebe leite.',
      'คุณดื่มนม',
      'Kamu minum susu.',
      'Bạn uống sữa.',
      '牛乳を飲む。',
    ),
    lead: '',
    noun: '우유',
    rest: ' 마셔요.',
    setId: 'subject-object',
    familyIndex: 1,
    reason: L(
      'A transitive verb (마시다) takes the object 을/를. 우유 ends in a vowel → 를.',
      'Un verbo transitivo (마시다) lleva el objeto 을/를. 우유 termina en vocal → 를.',
      "Un verbe transitif (마시다) prend l'objet 을/를. 우유 finit par une voyelle → 를.",
      'Um verbo transitivo (마시다) leva o objeto 을/를. 우유 termina em vogal → 를.',
      'คำกริยาสกรรม (마시다) ใช้กรรม 을/를 우유 ลงท้ายด้วยสระ → 를',
      'Verba transitif (마시다) memakai objek 을/를. 우유 berakhir dengan vokal → 를.',
      'Động từ ngoại động (마시다) lấy tân ngữ 을/를. 우유 kết thúc bằng nguyên âm → 를.',
      '他動詞（마시다）は目的語の 을/를 を取る。우유 は母音で終わる → 를。',
    ),
    trans: L(
      'I drink milk.',
      'Bebo leche.',
      'Je bois du lait.',
      'Eu bebo leite.',
      'ฉันดื่มนม',
      'Saya minum susu.',
      'Tôi uống sữa.',
      '私は牛乳を飲みます。',
    ),
  },
  {
    id: 'so-05-chaek',
    cue: L(
      'You read a book.',
      'Lees un libro.',
      'Tu lis un livre.',
      'Você lê um livro.',
      'คุณอ่านหนังสือ',
      'Kamu membaca buku.',
      'Bạn đọc sách.',
      '本を読む。',
    ),
    lead: '',
    noun: '책',
    rest: ' 읽어요.',
    setId: 'subject-object',
    familyIndex: 1,
    reason: L(
      'A transitive verb (읽다) takes the object 을/를. 책 ends in a consonant → 을.',
      'Un verbo transitivo (읽다) lleva el objeto 을/를. 책 termina en consonante → 을.',
      "Un verbe transitif (읽다) prend l'objet 을/를. 책 finit par une consonne → 을.",
      'Um verbo transitivo (읽다) leva o objeto 을/를. 책 termina em consoante → 을.',
      'คำกริยาสกรรม (읽다) ใช้กรรม 을/를 책 ลงท้ายด้วยพยัญชนะ → 을',
      'Verba transitif (읽다) memakai objek 을/를. 책 berakhir dengan konsonan → 을.',
      'Động từ ngoại động (읽다) lấy tân ngữ 을/를. 책 kết thúc bằng phụ âm → 을.',
      '他動詞（읽다）は目的語の 을/를 を取る。책 は子音で終わる → 을。',
    ),
    trans: L(
      'I read a book.',
      'Leo un libro.',
      'Je lis un livre.',
      'Eu leio um livro.',
      'ฉันอ่านหนังสือ',
      'Saya membaca buku.',
      'Tôi đọc sách.',
      '私は本を読みます。',
    ),
  },
  {
    id: 'so-06-sigan',
    cue: L(
      "You don't have time.",
      'No tienes tiempo.',
      "Tu n'as pas le temps.",
      'Você não tem tempo.',
      'คุณไม่มีเวลา',
      'Kamu tidak punya waktu.',
      'Bạn không có thời gian.',
      '時間がない。',
    ),
    lead: '',
    noun: '시간',
    rest: ' 없어요.',
    setId: 'subject-object',
    familyIndex: 0,
    reason: L(
      '없다 (non-existence) marks its theme with the subject 이/가. 시간 ends in a consonant → 이.',
      '없다 (no existencia) marca su tema con el sujeto 이/가. 시간 termina en consonante → 이.',
      '없다 (non-existence) marque son thème avec le sujet 이/가. 시간 finit par une consonne → 이.',
      '없다 (não existência) marca seu tema com o sujeito 이/가. 시간 termina em consoante → 이.',
      '없다 (การไม่มีอยู่) ทำเครื่องหมายหัวเรื่องด้วยประธาน 이/가 시간 ลงท้ายด้วยพยัญชนะ → 이',
      '없다 (ketiadaan) menandai temanya dengan subjek 이/가. 시간 berakhir dengan konsonan → 이.',
      '없다 (sự không tồn tại) đánh dấu chủ đề bằng chủ ngữ 이/가. 시간 kết thúc bằng phụ âm → 이.',
      '없다（非存在）は主題を主語の 이/가 で示す。시간 は子音で終わる → 이。',
    ),
    trans: L(
      "I don't have time.",
      'No tengo tiempo.',
      "Je n'ai pas le temps.",
      'Eu não tenho tempo.',
      'ฉันไม่มีเวลา',
      'Saya tidak punya waktu.',
      'Tôi không có thời gian.',
      '私は時間がありません。',
    ),
  },
  {
    id: 'so-07-nalssi',
    cue: L(
      'The weather is good (a state).',
      'El clima está bueno (un estado).',
      'Le temps est beau (un état).',
      'O tempo está bom (um estado).',
      'อากาศดี (เป็นสภาพ)',
      'Cuacanya bagus (sebuah keadaan).',
      'Thời tiết đẹp (một trạng thái).',
      '天気が良い（状態）。',
    ),
    lead: '',
    noun: '날씨',
    rest: ' 좋아요.',
    setId: 'subject-object',
    familyIndex: 0,
    reason: L(
      'A stative verb (좋다) marks its theme with the subject 이/가. 날씨 ends in a vowel → 가.',
      'Un verbo de estado (좋다) marca su tema con el sujeto 이/가. 날씨 termina en vocal → 가.',
      "Un verbe d'état (좋다) marque son thème avec le sujet 이/가. 날씨 finit par une voyelle → 가.",
      'Um verbo de estado (좋다) marca seu tema com o sujeito 이/가. 날씨 termina em vogal → 가.',
      'คำกริยาบอกสภาพ (좋다) ทำเครื่องหมายหัวเรื่องด้วยประธาน 이/가 날씨 ลงท้ายด้วยสระ → 가',
      'Verba statif (좋다) menandai temanya dengan subjek 이/가. 날씨 berakhir dengan vokal → 가.',
      'Động từ trạng thái (좋다) đánh dấu chủ đề bằng chủ ngữ 이/가. 날씨 kết thúc bằng nguyên âm → 가.',
      '状態動詞（좋다）は主題を主語の 이/가 で示す。날씨 は母音で終わる → 가。',
    ),
    trans: L(
      'The weather is good.',
      'El clima está bueno.',
      'Le temps est beau.',
      'O tempo está bom.',
      'อากาศดี',
      'Cuacanya bagus.',
      'Thời tiết đẹp.',
      '天気が良いです。',
    ),
  },

  // -- place-static-action --
  {
    id: 'pa-01-hakgyo',
    cue: L(
      'You are going TO school.',
      'Vas A la escuela.',
      "Tu vas À l'école.",
      'Você vai PARA a escola.',
      'คุณกำลังไปโรงเรียน',
      'Kamu pergi KE sekolah.',
      'Bạn đang đi ĐẾN trường.',
      '学校へ行く。',
    ),
    noun: '학교',
    rest: ' 가요.',
    setId: 'place-static-action',
    familyIndex: 0,
    reason: L(
      '에 marks the destination of movement.',
      '에 marca el destino del movimiento.',
      '에 marque la destination du mouvement.',
      '에 marca o destino do movimento.',
      '에 บอกจุดหมายปลายทางของการเคลื่อนที่',
      '에 menandai tujuan pergerakan.',
      '에 đánh dấu điểm đến của sự di chuyển.',
      '에 は移動の目的地を表す。',
    ),
    trans: L(
      'I go to school.',
      'Voy a la escuela.',
      "Je vais à l'école.",
      'Eu vou para a escola.',
      'ฉันไปโรงเรียน',
      'Saya pergi ke sekolah.',
      'Tôi đi đến trường.',
      '学校へ行きます。',
    ),
  },
  {
    id: 'pa-02-doseogwan',
    cue: L(
      'You study IN the library.',
      'Estudias EN la biblioteca.',
      'Tu étudies DANS la bibliothèque.',
      'Você estuda NA biblioteca.',
      'คุณอ่านหนังสือในห้องสมุด',
      'Kamu belajar DI perpustakaan.',
      'Bạn học TRONG thư viện.',
      '図書館で勉強する。',
    ),
    noun: '도서관',
    rest: ' 공부해요.',
    setId: 'place-static-action',
    familyIndex: 1,
    reason: L(
      '에서 marks where an action takes place.',
      '에서 marca el lugar donde ocurre una acción.',
      "에서 marque l'endroit où se déroule une action.",
      '에서 marca onde uma ação acontece.',
      '에서 บอกสถานที่ที่กิจกรรมเกิดขึ้น',
      '에서 menandai tempat suatu tindakan berlangsung.',
      '에서 đánh dấu nơi một hành động diễn ra.',
      '에서 は動作が行われる場所を表す。',
    ),
    trans: L(
      'I study in the library.',
      'Estudio en la biblioteca.',
      "J'étudie à la bibliothèque.",
      'Eu estudo na biblioteca.',
      'ฉันอ่านหนังสือในห้องสมุด',
      'Saya belajar di perpustakaan.',
      'Tôi học trong thư viện.',
      '図書館で勉強します。',
    ),
  },
  {
    id: 'pa-03-jip',
    cue: L(
      "You're located AT home (no action).",
      'Estás EN casa (sin acción).',
      'Tu te trouves À la maison (sans action).',
      'Você está EM casa (sem ação).',
      'คุณอยู่ที่บ้าน (ไม่มีกิจกรรม)',
      'Kamu berada DI rumah (tanpa aksi).',
      'Bạn đang Ở nhà (không có hành động).',
      '家にいる（動作なし）。',
    ),
    noun: '집',
    rest: ' 있어요.',
    setId: 'place-static-action',
    familyIndex: 0,
    reason: L(
      'Static location/existence takes 에.',
      'La ubicación estática / existencia lleva 에.',
      "La localisation statique / l'existence prend 에.",
      'Localização estática / existência leva 에.',
      'ตำแหน่งที่อยู่นิ่ง / การมีอยู่ ใช้ 에',
      'Lokasi statis / keberadaan memakai 에.',
      'Vị trí tĩnh / sự tồn tại dùng 에.',
      '静的な所在・存在は 에 を取る。',
    ),
    trans: L(
      'I am at home.',
      'Estoy en casa.',
      'Je suis à la maison.',
      'Eu estou em casa.',
      'ฉันอยู่ที่บ้าน',
      'Saya ada di rumah.',
      'Tôi đang ở nhà.',
      '家にいます。',
    ),
  },
  {
    id: 'pa-04-sikdang',
    cue: L(
      'You eat at the restaurant.',
      'Comes en el restaurante.',
      'Tu manges au restaurant.',
      'Você come no restaurante.',
      'คุณกินข้าวที่ร้านอาหาร',
      'Kamu makan di restoran.',
      'Bạn ăn ở nhà hàng.',
      'レストランで食事をする。',
    ),
    noun: '식당',
    rest: ' 밥을 먹어요.',
    setId: 'place-static-action',
    familyIndex: 1,
    reason: L(
      'Eating is an action that happens 에서 a place.',
      'Comer es una acción que ocurre 에서 un lugar.',
      'Manger est une action qui se déroule 에서 un lieu.',
      'Comer é uma ação que acontece 에서 um lugar.',
      'การกินคือกิจกรรมที่เกิดขึ้น 에서 สถานที่หนึ่ง',
      'Makan adalah tindakan yang terjadi 에서 suatu tempat.',
      'Ăn là một hành động diễn ra 에서 một nơi.',
      '食べることは場所で行う動作 → 에서。',
    ),
    trans: L(
      'I eat at the restaurant.',
      'Como en el restaurante.',
      'Je mange au restaurant.',
      'Eu como no restaurante.',
      'ฉันกินข้าวที่ร้านอาหาร',
      'Saya makan di restoran.',
      'Tôi ăn cơm ở nhà hàng.',
      'レストランでご飯を食べます。',
    ),
  },
  {
    id: 'pa-05-hoesa',
    cue: L(
      'You work at the company.',
      'Trabajas en la empresa.',
      "Tu travailles à l'entreprise.",
      'Você trabalha na empresa.',
      'คุณทำงานที่บริษัท',
      'Kamu bekerja di perusahaan.',
      'Bạn làm việc ở công ty.',
      '会社で働く。',
    ),
    noun: '회사',
    rest: ' 일해요.',
    setId: 'place-static-action',
    familyIndex: 1,
    reason: L(
      'Working is an action that happens 에서 a place.',
      'Trabajar es una acción que ocurre 에서 un lugar.',
      'Travailler est une action qui se déroule 에서 un lieu.',
      'Trabalhar é uma ação que acontece 에서 um lugar.',
      'การทำงานคือกิจกรรมที่เกิดขึ้น 에서 สถานที่หนึ่ง',
      'Bekerja adalah tindakan yang terjadi 에서 suatu tempat.',
      'Làm việc là một hành động diễn ra 에서 một nơi.',
      '働くことは場所で行う動作 → 에서。',
    ),
    trans: L(
      'I work at the company.',
      'Trabajo en la empresa.',
      "Je travaille à l'entreprise.",
      'Eu trabalho na empresa.',
      'ฉันทำงานที่บริษัท',
      'Saya bekerja di perusahaan.',
      'Tôi làm việc ở công ty.',
      '会社で働きます。',
    ),
  },
  {
    id: 'pa-06-busan',
    cue: L(
      'You are going TO Busan.',
      'Vas A Busan.',
      'Tu vas À Busan.',
      'Você vai PARA Busan.',
      'คุณกำลังไปปูซาน',
      'Kamu pergi KE Busan.',
      'Bạn đang đi ĐẾN Busan.',
      '釜山へ行く。',
    ),
    noun: '부산',
    rest: ' 가요.',
    setId: 'place-static-action',
    familyIndex: 0,
    reason: L(
      '에 marks the destination of movement.',
      '에 marca el destino del movimiento.',
      '에 marque la destination du mouvement.',
      '에 marca o destino do movimento.',
      '에 บอกจุดหมายปลายทางของการเคลื่อนที่',
      '에 menandai tujuan pergerakan.',
      '에 đánh dấu điểm đến của sự di chuyển.',
      '에 は移動の目的地を表す。',
    ),
    trans: L(
      'I go to Busan.',
      'Voy a Busan.',
      'Je vais à Busan.',
      'Eu vou para Busan.',
      'ฉันไปปูซาน',
      'Saya pergi ke Busan.',
      'Tôi đi đến Busan.',
      '釜山へ行きます。',
    ),
  },

  // -- place-recipient --
  {
    id: 'pr-01-eomma',
    cue: L(
      'You tell something TO mom.',
      'Le dices algo A mamá.',
      'Tu dis quelque chose À maman.',
      'Você diz algo PARA a mãe.',
      'คุณพูดอะไรบางอย่างกับแม่',
      'Kamu mengatakan sesuatu KEPADA ibu.',
      'Bạn nói điều gì đó VỚI mẹ.',
      'お母さんに何かを話す。',
    ),
    noun: '엄마',
    rest: ' 말해요.',
    setId: 'place-recipient',
    familyIndex: 1,
    reason: L(
      'A person who receives words takes 한테 (= casual 에게), not 에.',
      'Una persona que recibe palabras lleva 한테 (= 에게 casual), no 에.',
      'Une personne qui reçoit la parole prend 한테 (= 에게 familier), pas 에.',
      'Uma pessoa que recebe palavras leva 한테 (= 에게 informal), não 에.',
      'คนที่รับคำพูดใช้ 한테 (= 에게 แบบกันเอง) ไม่ใช่ 에',
      'Orang yang menerima ucapan memakai 한테 (= 에게 santai), bukan 에.',
      'Người tiếp nhận lời nói dùng 한테 (= 에게 thân mật), không phải 에.',
      '言葉を受け取る相手は 에 ではなく 한테（くだけた 에게）。',
    ),
    trans: L(
      'I talk to mom.',
      'Le hablo a mamá.',
      'Je parle à maman.',
      'Eu falo com a mãe.',
      'ฉันพูดกับแม่',
      'Aku berbicara kepada ibu.',
      'Tôi nói chuyện với mẹ.',
      'お母さんに話します。',
    ),
  },
  {
    id: 'pr-02-busan',
    cue: L(
      'You go to Busan (a place).',
      'Vas a Busan (un lugar).',
      'Tu vas à Busan (un lieu).',
      'Você vai para Busan (um lugar).',
      'คุณไปปูซาน (สถานที่)',
      'Kamu pergi ke Busan (sebuah tempat).',
      'Bạn đi Busan (một địa điểm).',
      'プサン（場所）へ行く。',
    ),
    noun: '부산',
    rest: ' 가요.',
    setId: 'place-recipient',
    familyIndex: 0,
    reason: L(
      'A place destination takes 에.',
      'Un destino que es lugar lleva 에.',
      'Une destination qui est un lieu prend 에.',
      'Um destino que é lugar leva 에.',
      'จุดหมายที่เป็นสถานที่ใช้ 에',
      'Tujuan berupa tempat memakai 에.',
      'Đích đến là địa điểm dùng 에.',
      '行き先（場所）は 에。',
    ),
    trans: L(
      'I go to Busan.',
      'Voy a Busan.',
      'Je vais à Busan.',
      'Eu vou para Busan.',
      'ฉันไปปูซาน',
      'Aku pergi ke Busan.',
      'Tôi đi Busan.',
      'プサンへ行きます。',
    ),
  },
  {
    id: 'pr-03-seonsaengnim',
    cue: L(
      'You ask the teacher.',
      'Le preguntas al profesor.',
      'Tu demandes au professeur.',
      'Você pergunta ao professor.',
      'คุณถามครู',
      'Kamu bertanya kepada guru.',
      'Bạn hỏi giáo viên.',
      '先生に尋ねる。',
    ),
    noun: '선생님',
    rest: ' 물어봐요.',
    setId: 'place-recipient',
    familyIndex: 1,
    reason: L(
      'A person you address takes 한테 (= 에게).',
      'Una persona a la que te diriges lleva 한테 (= 에게).',
      "Une personne à qui tu t'adresses prend 한테 (= 에게).",
      'Uma pessoa a quem você se dirige leva 한테 (= 에게).',
      'คนที่คุณพูดด้วยใช้ 한테 (= 에게)',
      'Orang yang kamu ajak bicara memakai 한테 (= 에게).',
      'Người mà bạn hướng tới dùng 한테 (= 에게).',
      '話しかける相手は 한테（= 에게）。',
    ),
    trans: L(
      'I ask the teacher.',
      'Le pregunto al profesor.',
      'Je demande au professeur.',
      'Eu pergunto ao professor.',
      'ฉันถามครู',
      'Aku bertanya kepada guru.',
      'Tôi hỏi giáo viên.',
      '先生に尋ねます。',
    ),
  },
  {
    id: 'pr-04-chingu',
    cue: L(
      'You give a gift TO a friend.',
      'Le das un regalo A un amigo.',
      'Tu offres un cadeau À un ami.',
      'Você dá um presente PARA um amigo.',
      'คุณให้ของขวัญแก่เพื่อน',
      'Kamu memberi hadiah KEPADA teman.',
      'Bạn tặng quà CHO một người bạn.',
      '友達にプレゼントをあげる。',
    ),
    noun: '친구',
    rest: ' 선물을 줘요.',
    setId: 'place-recipient',
    familyIndex: 1,
    reason: L(
      'A recipient person takes 한테 (= 에게).',
      'Una persona destinataria lleva 한테 (= 에게).',
      'Une personne destinataire prend 한테 (= 에게).',
      'Uma pessoa destinatária leva 한테 (= 에게).',
      'คนที่เป็นผู้รับใช้ 한테 (= 에게)',
      'Orang yang menjadi penerima memakai 한테 (= 에게).',
      'Người nhận dùng 한테 (= 에게).',
      '受け手となる人は 한테（= 에게）。',
    ),
    trans: L(
      'I give a gift to my friend.',
      'Le doy un regalo a mi amigo.',
      "J'offre un cadeau à mon ami.",
      'Eu dou um presente para meu amigo.',
      'ฉันให้ของขวัญแก่เพื่อน',
      'Aku memberi hadiah kepada temanku.',
      'Tôi tặng quà cho bạn tôi.',
      '友達にプレゼントをあげます。',
    ),
  },
  {
    id: 'pr-05-hakgyo',
    cue: L(
      'You go to school (a place).',
      'Vas a la escuela (un lugar).',
      "Tu vas à l'école (un lieu).",
      'Você vai para a escola (um lugar).',
      'คุณไปโรงเรียน (สถานที่)',
      'Kamu pergi ke sekolah (sebuah tempat).',
      'Bạn đi đến trường (một địa điểm).',
      '学校（場所）へ行く。',
    ),
    noun: '학교',
    rest: ' 가요.',
    setId: 'place-recipient',
    familyIndex: 0,
    reason: L(
      'A place destination takes 에.',
      'Un destino que es lugar lleva 에.',
      'Une destination qui est un lieu prend 에.',
      'Um destino que é lugar leva 에.',
      'จุดหมายที่เป็นสถานที่ใช้ 에',
      'Tujuan berupa tempat memakai 에.',
      'Đích đến là địa điểm dùng 에.',
      '行き先（場所）は 에。',
    ),
    trans: L(
      'I go to school.',
      'Voy a la escuela.',
      "Je vais à l'école.",
      'Eu vou para a escola.',
      'ฉันไปโรงเรียน',
      'Aku pergi ke sekolah.',
      'Tôi đi đến trường.',
      '学校へ行きます。',
    ),
  },
  {
    id: 'pr-06-dongsaeng',
    cue: L(
      'You call your younger sibling.',
      'Llamas a tu hermano menor.',
      'Tu appelles ton cadet.',
      'Você liga para o seu irmão mais novo.',
      'คุณโทรหาน้อง',
      'Kamu menelepon adikmu.',
      'Bạn gọi điện cho em mình.',
      '弟・妹に電話する。',
    ),
    noun: '동생',
    rest: ' 전화해요.',
    setId: 'place-recipient',
    familyIndex: 1,
    reason: L(
      'A person you call takes 한테 (= 에게).',
      'Una persona a la que llamas lleva 한테 (= 에게).',
      'Une personne que tu appelles prend 한테 (= 에게).',
      'Uma pessoa para quem você liga leva 한테 (= 에게).',
      'คนที่คุณโทรหาใช้ 한테 (= 에게)',
      'Orang yang kamu telepon memakai 한테 (= 에게).',
      'Người bạn gọi điện dùng 한테 (= 에게).',
      '電話する相手は 한테（= 에게）。',
    ),
    trans: L(
      'I call my younger sibling.',
      'Llamo a mi hermano menor.',
      "J'appelle mon cadet.",
      'Eu ligo para o meu irmão mais novo.',
      'ฉันโทรหาน้อง',
      'Aku menelepon adikku.',
      'Tôi gọi điện cho em tôi.',
      '弟・妹に電話します。',
    ),
  },
  {
    id: 'pr-07-hanguk',
    cue: L(
      'You live in Korea (a place).',
      'Vives en Corea (un lugar).',
      'Tu vis en Corée (un lieu).',
      'Você mora na Coreia (um lugar).',
      'คุณอาศัยอยู่ในเกาหลี (สถานที่)',
      'Kamu tinggal di Korea (sebuah tempat).',
      'Bạn sống ở Hàn Quốc (một địa điểm).',
      '韓国（場所）に住む。',
    ),
    noun: '한국',
    rest: ' 살아요.',
    setId: 'place-recipient',
    familyIndex: 0,
    reason: L(
      'Residence in a place takes 에.',
      'La residencia en un lugar lleva 에.',
      'La résidence dans un lieu prend 에.',
      'A residência em um lugar leva 에.',
      'การอาศัยอยู่ในสถานที่ใช้ 에',
      'Tempat tinggal di suatu lokasi memakai 에.',
      'Việc cư trú ở một nơi dùng 에.',
      '住んでいる場所は 에。',
    ),
    trans: L(
      'I live in Korea.',
      'Vivo en Corea.',
      'Je vis en Corée.',
      'Eu moro na Coreia.',
      'ฉันอาศัยอยู่ในเกาหลี',
      'Aku tinggal di Korea.',
      'Tôi sống ở Hàn Quốc.',
      '韓国に住んでいます。',
    ),
  },

  // -- also-only --
  {
    id: 'am-01-jeo',
    cue: L(
      'Others are students, and so are you.',
      'Los demás son estudiantes, y tú también.',
      'Les autres sont étudiants, et toi aussi.',
      'Os outros são estudantes, e você também.',
      'คนอื่นเป็นนักเรียน และคุณก็เป็นด้วย',
      'Yang lain pelajar, dan kamu juga.',
      'Những người khác là học sinh, và bạn cũng vậy.',
      '他の人は学生で、あなたもそうだ。',
    ),
    noun: '저',
    rest: ' 학생이에요.',
    setId: 'also-only',
    familyIndex: 0,
    reason: L(
      '도 = "also/too"; adds you to the group. It replaces 은/는.',
      '도 = "también"; te suma al grupo. Reemplaza a 은/는.',
      "도 = « aussi »; t'ajoute au groupe. Il remplace 은/는.",
      '도 = "também"; te adiciona ao grupo. Substitui 은/는.',
      '도 = "ด้วย/ก็"; เพิ่มคุณเข้าไปในกลุ่ม ใช้แทน 은/는',
      '도 = "juga"; menambahkanmu ke kelompok. Menggantikan 은/는.',
      '도 = "cũng"; thêm bạn vào nhóm. Nó thay cho 은/는.',
      '도 =「〜も」。あなたをグループに加える。은/는 の代わりに使う。',
    ),
    trans: L(
      'I am also a student.',
      'Yo también soy estudiante.',
      'Moi aussi, je suis étudiant·e.',
      'Eu também sou estudante.',
      'ฉันก็เป็นนักเรียนเหมือนกัน',
      'Saya juga pelajar.',
      'Tôi cũng là học sinh.',
      '私も学生です。',
    ),
  },
  {
    id: 'am-02-mul',
    cue: L(
      'You drink water and nothing else.',
      'Bebes agua y nada más.',
      "Tu bois de l'eau et rien d'autre.",
      'Você bebe água e nada mais.',
      'คุณดื่มแต่น้ำ ไม่ดื่มอย่างอื่น',
      'Kamu minum air dan tidak yang lain.',
      'Bạn chỉ uống nước, không gì khác.',
      '水だけ飲んで、他は飲まない。',
    ),
    noun: '물',
    rest: ' 마셔요.',
    setId: 'also-only',
    familyIndex: 1,
    reason: L(
      '만 = "only"; restricts to that one thing.',
      '만 = "solo"; restringe a esa única cosa.',
      '만 = « seulement »; limite à cette seule chose.',
      '만 = "só"; restringe a essa única coisa.',
      '만 = "เท่านั้น"; จำกัดให้เหลือสิ่งเดียวนั้น',
      '만 = "hanya"; membatasi pada satu hal itu saja.',
      '만 = "chỉ"; giới hạn vào đúng một thứ đó.',
      '만 =「〜だけ」。そのひとつに限定する。',
    ),
    trans: L(
      'I drink only water.',
      'Solo bebo agua.',
      "Je bois seulement de l'eau.",
      'Eu bebo só água.',
      'ฉันดื่มแต่น้ำเท่านั้น',
      'Saya hanya minum air.',
      'Tôi chỉ uống nước.',
      '水だけ飲みます。',
    ),
  },
  {
    id: 'am-03-keopi',
    cue: L(
      'Besides tea, you also like coffee.',
      'Además del té, también te gusta el café.',
      'En plus du thé, tu aimes aussi le café.',
      'Além do chá, você também gosta de café.',
      'นอกจากชาแล้ว คุณยังชอบกาแฟด้วย',
      'Selain teh, kamu juga suka kopi.',
      'Ngoài trà, bạn cũng thích cà phê.',
      'お茶のほかに、コーヒーも好き。',
    ),
    lead: '',
    noun: '커피',
    rest: ' 좋아해요.',
    setId: 'also-only',
    familyIndex: 0,
    reason: L(
      '도 = "also/too"; it adds coffee to what you already like. It replaces 은/는 and 이/가.',
      '도 = "también"; añade el café a lo que ya te gusta. Reemplaza a 은/는 y 이/가.',
      '도 = « aussi » ; ajoute le café à ce que tu aimes déjà. Il remplace 은/는 et 이/가.',
      '도 = "também"; adiciona o café ao que você já gosta. Substitui 은/는 e 이/가.',
      '도 = "ด้วย"; เพิ่มกาแฟเข้าไปในสิ่งที่ชอบอยู่แล้ว ใช้แทน 은/는 และ 이/가',
      '도 = "juga"; menambahkan kopi ke yang sudah kamu suka. Menggantikan 은/는 dan 이/가.',
      '도 = "cũng"; thêm cà phê vào những gì bạn đã thích. Thay thế 은/는 và 이/가.',
      '도 =「〜も」。すでに好きなものにコーヒーも加える。은/는・이/가 と置き換わる。',
    ),
    trans: L(
      'I like coffee too.',
      'También me gusta el café.',
      "J'aime aussi le café.",
      'Eu também gosto de café.',
      'ฉันชอบกาแฟด้วย',
      'Saya juga suka kopi.',
      'Tôi cũng thích cà phê.',
      '私はコーヒーも好きです。',
    ),
  },
  {
    id: 'am-04-eorini',
    cue: L(
      'Only children, not adults, are free.',
      'Solo los niños, no los adultos, entran gratis.',
      'Seuls les enfants, pas les adultes, sont gratuits.',
      'Só as crianças, não os adultos, entram de graça.',
      'เฉพาะเด็กเท่านั้นที่ฟรี ผู้ใหญ่ไม่ฟรี',
      'Hanya anak-anak, bukan dewasa, yang gratis.',
      'Chỉ trẻ em, không phải người lớn, được miễn phí.',
      '子供だけが無料で、大人は無料ではない。',
    ),
    noun: '어린이',
    rest: ' 무료예요.',
    setId: 'also-only',
    familyIndex: 1,
    reason: L(
      '만 = "only"; excludes everyone else.',
      '만 = "solo"; excluye a todos los demás.',
      '만 = « seulement »; exclut tous les autres.',
      '만 = "só"; exclui todos os outros.',
      '만 = "เท่านั้น"; ตัดคนอื่นทั้งหมดออก',
      '만 = "hanya"; mengecualikan semua yang lain.',
      '만 = "chỉ"; loại trừ tất cả những người khác.',
      '만 =「〜だけ」。他の全員を除外する。',
    ),
    trans: L(
      'Only children are free.',
      'Solo los niños entran gratis.',
      'Seuls les enfants sont gratuits.',
      'Só as crianças são de graça.',
      'เฉพาะเด็กเท่านั้นที่ฟรี',
      'Hanya anak-anak yang gratis.',
      'Chỉ trẻ em được miễn phí.',
      '子供だけ無料です。',
    ),
  },
  {
    id: 'am-05-jeo',
    cue: L(
      'Only you can go, no one else.',
      'Solo tú puedes ir, nadie más.',
      "Toi seul peux y aller, personne d'autre.",
      'Só você pode ir, mais ninguém.',
      'มีแต่คุณเท่านั้นที่ไปได้ ไม่มีใครอื่น',
      'Hanya kamu yang boleh pergi, tidak ada yang lain.',
      'Chỉ mình bạn được đi, không ai khác.',
      'あなただけ行ける、他の誰も行けない。',
    ),
    noun: '저',
    rest: ' 갈 수 있어요.',
    setId: 'also-only',
    familyIndex: 1,
    reason: L(
      '만 = "only"; restricts to you alone.',
      '만 = "solo"; restringe a ti solo.',
      '만 = « seulement »; limite à toi seul.',
      '만 = "só"; restringe a você sozinho.',
      '만 = "เท่านั้น"; จำกัดให้เหลือแค่คุณคนเดียว',
      '만 = "hanya"; membatasi hanya pada kamu sendiri.',
      '만 = "chỉ"; giới hạn vào mỗi mình bạn.',
      '만 =「〜だけ」。あなた一人に限定する。',
    ),
    trans: L(
      'Only I can go.',
      'Solo yo puedo ir.',
      'Moi seul·e peux y aller.',
      'Só eu posso ir.',
      'มีแต่ฉันเท่านั้นที่ไปได้',
      'Hanya saya yang bisa pergi.',
      'Chỉ mình tôi có thể đi.',
      '私だけ行けます。',
    ),
  },
  {
    id: 'am-06-chingu',
    cue: L(
      'Someone else comes, and a friend also comes.',
      'Viene alguien más, y un amigo también viene.',
      "Quelqu'un d'autre vient, et un ami vient aussi.",
      'Vem outra pessoa, e um amigo também vem.',
      'มีคนอื่นมา และเพื่อนก็มาด้วย',
      'Ada orang lain datang, dan seorang teman juga datang.',
      'Có người khác đến, và một người bạn cũng đến.',
      '他の人が来て、友達も来る。',
    ),
    noun: '친구',
    rest: ' 와요.',
    setId: 'also-only',
    familyIndex: 0,
    reason: L(
      '도 = "also"; adds the friend to those coming.',
      '도 = "también"; suma al amigo a los que vienen.',
      "도 = « aussi »; ajoute l'ami à ceux qui viennent.",
      '도 = "também"; adiciona o amigo aos que vêm.',
      '도 = "ด้วย/ก็"; เพิ่มเพื่อนเข้าไปในกลุ่มคนที่มา',
      '도 = "juga"; menambahkan teman ke yang datang.',
      '도 = "cũng"; thêm người bạn vào những người đang đến.',
      '도 =「〜も」。来る人たちに友達を加える。',
    ),
    trans: L(
      'A friend also comes.',
      'Un amigo también viene.',
      'Un ami vient aussi.',
      'Um amigo também vem.',
      'เพื่อนก็มาด้วย',
      'Seorang teman juga datang.',
      'Một người bạn cũng đến.',
      '友達も来ます。',
    ),
  },

  // -- from-until --
  {
    id: 'fu-01-woryoil',
    cue: L(
      'Monday is when you START going.',
      'El lunes es cuando EMPIEZAS a ir.',
      "Lundi, c'est quand tu COMMENCES à y aller.",
      'Segunda é quando você COMEÇA a ir.',
      'วันจันทร์คือวันที่คุณ "เริ่ม" ไป',
      'Senin adalah saat kamu MULAI pergi.',
      'Thứ Hai là lúc bạn BẮT ĐẦU đi.',
      '月曜日が「行き始める」日。',
    ),
    noun: '월요일',
    rest: ' 학교에 가요.',
    setId: 'from-until',
    familyIndex: 0,
    reason: L(
      '부터 marks the starting point of a range ("from").',
      '부터 marca el punto de inicio de un rango ("desde").',
      "부터 marque le point de départ d'un intervalle (« à partir de »).",
      '부터 marca o ponto de início de um intervalo ("a partir de").',
      '부터 บอกจุดเริ่มต้นของช่วง ("ตั้งแต่")',
      '부터 menandai titik awal rentang ("dari").',
      '부터 đánh dấu điểm bắt đầu của một khoảng ("từ").',
      '부터 は範囲の始点を表す（「〜から」）。',
    ),
    trans: L(
      'I go to school from Monday.',
      'Voy a la escuela desde el lunes.',
      "Je vais à l'école à partir de lundi.",
      'Vou à escola a partir de segunda.',
      'ฉันไปโรงเรียนตั้งแต่วันจันทร์',
      'Saya pergi ke sekolah dari hari Senin.',
      'Tôi đi học từ thứ Hai.',
      '月曜日から学校に行きます。',
    ),
  },
  {
    id: 'fu-02-geumyoil',
    cue: L(
      'Friday is when you STOP going.',
      'El viernes es cuando DEJAS de ir.',
      "Vendredi, c'est quand tu ARRÊTES d'y aller.",
      'Sexta é quando você PARA de ir.',
      'วันศุกร์คือวันที่คุณ "หยุด" ไป',
      'Jumat adalah saat kamu BERHENTI pergi.',
      'Thứ Sáu là lúc bạn DỪNG đi.',
      '金曜日が「行くのをやめる」日。',
    ),
    noun: '금요일',
    rest: ' 학교에 가요.',
    setId: 'from-until',
    familyIndex: 1,
    reason: L(
      '까지 marks the end point of a range ("until").',
      '까지 marca el punto final de un rango ("hasta").',
      "까지 marque le point d'arrivée d'un intervalle (« jusqu'à »).",
      '까지 marca o ponto final de um intervalo ("até").',
      '까지 บอกจุดสิ้นสุดของช่วง ("จนถึง")',
      '까지 menandai titik akhir rentang ("sampai").',
      '까지 đánh dấu điểm kết thúc của một khoảng ("đến").',
      '까지 は範囲の終点を表す（「〜まで」）。',
    ),
    trans: L(
      'I go to school until Friday.',
      'Voy a la escuela hasta el viernes.',
      "Je vais à l'école jusqu'à vendredi.",
      'Vou à escola até sexta.',
      'ฉันไปโรงเรียนจนถึงวันศุกร์',
      'Saya pergi ke sekolah sampai hari Jumat.',
      'Tôi đi học đến thứ Sáu.',
      '金曜日まで学校に行きます。',
    ),
  },
  {
    id: 'fu-03-achim',
    cue: L(
      'It started raining in the morning and still is.',
      'Empezó a llover por la mañana y sigue.',
      'Il a commencé à pleuvoir le matin et il pleut encore.',
      'Começou a chover de manhã e ainda chove.',
      'ฝนเริ่มตกตั้งแต่เช้าและยังตกอยู่',
      'Hujan mulai turun pagi tadi dan masih turun.',
      'Trời bắt đầu mưa từ sáng và vẫn còn mưa.',
      '朝から雨が降り始めて、まだ降っている。',
    ),
    noun: '아침',
    rest: ' 비가 와요.',
    setId: 'from-until',
    familyIndex: 0,
    reason: L(
      '부터 marks the starting point ("since").',
      '부터 marca el punto de inicio ("desde").',
      '부터 marque le point de départ (« depuis »).',
      '부터 marca o ponto de início ("desde").',
      '부터 บอกจุดเริ่มต้น ("ตั้งแต่")',
      '부터 menandai titik awal ("sejak").',
      '부터 đánh dấu điểm bắt đầu ("từ lúc").',
      '부터 は始点を表す（「〜から（ずっと）」）。',
    ),
    trans: L(
      'It has been raining since morning.',
      'Llueve desde la mañana.',
      'Il pleut depuis le matin.',
      'Está chovendo desde de manhã.',
      'ฝนตกตั้งแต่เช้า',
      'Hujan turun sejak pagi.',
      'Trời mưa từ sáng.',
      '朝から雨が降っています。',
    ),
  },
  {
    id: 'fu-04-bam',
    cue: L(
      'You work up until night.',
      'Trabajas hasta la noche.',
      "Tu travailles jusqu'à la nuit.",
      'Você trabalha até a noite.',
      'คุณทำงานจนถึงกลางคืน',
      'Kamu bekerja sampai malam.',
      'Bạn làm việc đến tận đêm.',
      '夜まで働く。',
    ),
    noun: '밤',
    rest: ' 일해요.',
    setId: 'from-until',
    familyIndex: 1,
    reason: L(
      '까지 marks the end point ("until").',
      '까지 marca el punto final ("hasta").',
      "까지 marque le point d'arrivée (« jusqu'à »).",
      '까지 marca o ponto final ("até").',
      '까지 บอกจุดสิ้นสุด ("จนถึง")',
      '까지 menandai titik akhir ("sampai").',
      '까지 đánh dấu điểm kết thúc ("đến").',
      '까지 は終点を表す（「〜まで」）。',
    ),
    trans: L(
      'I work until night.',
      'Trabajo hasta la noche.',
      "Je travaille jusqu'à la nuit.",
      'Trabalho até a noite.',
      'ฉันทำงานจนถึงกลางคืน',
      'Saya bekerja sampai malam.',
      'Tôi làm việc đến đêm.',
      '夜まで働きます。',
    ),
  },
  {
    id: 'fu-05-ahopsi',
    cue: L(
      'You start working at 9.',
      'Empiezas a trabajar a las 9.',
      'Tu commences à travailler à 9 h.',
      'Você começa a trabalhar às 9.',
      'คุณเริ่มทำงานตอน 9 โมง',
      'Kamu mulai bekerja jam 9.',
      'Bạn bắt đầu làm việc lúc 9 giờ.',
      '9時に働き始める。',
    ),
    noun: '9시',
    rest: ' 일해요.',
    setId: 'from-until',
    familyIndex: 0,
    reason: L(
      '부터 marks the starting point ("from").',
      '부터 marca el punto de inicio ("desde").',
      '부터 marque le point de départ (« à partir de »).',
      '부터 marca o ponto de início ("a partir de").',
      '부터 บอกจุดเริ่มต้น ("ตั้งแต่")',
      '부터 menandai titik awal ("dari").',
      '부터 đánh dấu điểm bắt đầu ("từ").',
      '부터 は始点を表す（「〜から」）。',
    ),
    trans: L(
      "I work from 9 o'clock.",
      'Trabajo desde las 9.',
      'Je travaille à partir de 9 h.',
      'Trabalho a partir das 9.',
      'ฉันทำงานตั้งแต่ 9 โมง',
      'Saya bekerja dari jam 9.',
      'Tôi làm việc từ 9 giờ.',
      '9時から働きます。',
    ),
  },
  {
    id: 'fu-06-yeoseotsi',
    cue: L(
      'You work up until 6.',
      'Trabajas hasta las 6.',
      "Tu travailles jusqu'à 6 h.",
      'Você trabalha até as 6.',
      'คุณทำงานจนถึง 6 โมง',
      'Kamu bekerja sampai jam 6.',
      'Bạn làm việc đến 6 giờ.',
      '6時まで働く。',
    ),
    noun: '6시',
    rest: ' 일해요.',
    setId: 'from-until',
    familyIndex: 1,
    reason: L(
      '까지 marks the end point ("until").',
      '까지 marca el punto final ("hasta").',
      "까지 marque le point d'arrivée (« jusqu'à »).",
      '까지 marca o ponto final ("até").',
      '까지 บอกจุดสิ้นสุด ("จนถึง")',
      '까지 menandai titik akhir ("sampai").',
      '까지 đánh dấu điểm kết thúc ("đến").',
      '까지 は終点を表す（「〜まで」）。',
    ),
    trans: L(
      "I work until 6 o'clock.",
      'Trabajo hasta las 6.',
      "Je travaille jusqu'à 6 h.",
      'Trabalho até as 6.',
      'ฉันทำงานจนถึง 6 โมง',
      'Saya bekerja sampai jam 6.',
      'Tôi làm việc đến 6 giờ.',
      '6時まで働きます。',
    ),
  },

  // -- replay expansion (subproject 3): +18 items, each set to ~10 --

  // subject-object
  {
    id: 'so-08-sajin',
    cue: L(
      'What the camera captures — the thing acted on.',
      'Lo que captura la cámara: la cosa sobre la que actúas.',
      "Ce que l'appareil photo capture — la chose sur laquelle on agit.",
      'O que a câmera captura — a coisa sobre a qual você age.',
      'สิ่งที่กล้องถ่าย — สิ่งที่ถูกกระทำ',
      'Apa yang ditangkap kamera — hal yang dikenai tindakan.',
      'Thứ máy ảnh chụp — đối tượng bị tác động.',
      'カメラが捉えるもの — 動作の対象。',
    ),
    noun: '사진',
    rest: ' 찍어요.',
    setId: 'subject-object',
    familyIndex: 1,
    reason: L(
      '찍다 acts on the photo → object 을/를 (사진 ends in a consonant → 을).',
      '찍다 actúa sobre la foto → objeto 을/를 (사진 termina en consonante → 을).',
      '찍다 agit sur la photo → objet 을/를 (사진 finit par une consonne → 을).',
      '찍다 age sobre a foto → objeto 을/를 (사진 termina em consoante → 을).',
      '찍다 กระทำต่อรูปถ่าย → กรรม 을/를 (사진 ลงท้ายพยัญชนะ → 을)',
      '찍다 mengenai foto → objek 을/를 (사진 berakhiran konsonan → 을).',
      '찍다 tác động lên bức ảnh → tân ngữ 을/를 (사진 kết thúc phụ âm → 을).',
      '찍다 は写真に作用する → 目的語 을/를（사진 は子音終わり → 을）。',
    ),
    trans: L(
      'I take a photo.',
      'Saco una foto.',
      'Je prends une photo.',
      'Eu tiro uma foto.',
      'ฉันถ่ายรูป',
      'Saya memotret.',
      'Tôi chụp một bức ảnh.',
      '写真を撮ります。',
    ),
  },
  {
    id: 'so-09-mun',
    cue: L(
      'What you open — the thing acted on.',
      'Lo que abres — la cosa sobre la que actúas.',
      'Ce que tu ouvres — la chose sur laquelle on agit.',
      'O que você abre — a coisa sobre a qual você age.',
      'สิ่งที่คุณเปิด — สิ่งที่ถูกกระทำ',
      'Apa yang kamu buka — hal yang dikenai tindakan.',
      'Thứ bạn mở — đối tượng bị tác động.',
      'あなたが開けるもの — 動作の対象。',
    ),
    noun: '문',
    rest: ' 열어요.',
    setId: 'subject-object',
    familyIndex: 1,
    reason: L(
      '열다 acts on the door → object 을/를 (문 ends in a consonant → 을).',
      '열다 actúa sobre la puerta → objeto 을/를 (문 termina en consonante → 을).',
      '열다 agit sur la porte → objet 을/를 (문 finit par une consonne → 을).',
      '열다 age sobre a porta → objeto 을/를 (문 termina em consoante → 을).',
      '열다 กระทำต่อประตู → กรรม 을/를 (문 ลงท้ายพยัญชนะ → 을)',
      '열다 mengenai pintu → objek 을/를 (문 berakhiran konsonan → 을).',
      '열다 tác động lên cánh cửa → tân ngữ 을/를 (문 kết thúc phụ âm → 을).',
      '열다 はドアに作用する → 目的語 을/를（문 は子音終わり → 을）。',
    ),
    trans: L(
      'I open the door.',
      'Abro la puerta.',
      "J'ouvre la porte.",
      'Eu abro a porta.',
      'ฉันเปิดประตู',
      'Saya membuka pintu.',
      'Tôi mở cửa.',
      'ドアを開けます。',
    ),
  },
  {
    id: 'so-10-chingu',
    cue: L(
      'You answer: WHO is coming?',
      'Respondes a: ¿QUIÉN viene?',
      'Tu réponds à : QUI vient ?',
      'Você responde: QUEM está vindo?',
      'คุณตอบคำถาม: ใครกำลังมา?',
      'Kamu menjawab: SIAPA yang datang?',
      'Bạn trả lời: AI đang đến?',
      '「誰が来るの？」に答える。',
    ),
    noun: '친구',
    rest: ' 와요.',
    setId: 'subject-object',
    familyIndex: 0,
    reason: L(
      'The doer answering "who?" is new info → subject 이/가 (친구 ends in a vowel → 가).',
      'El que actúa, respuesta a "¿quién?", es info nueva → sujeto 이/가 (친구 termina en vocal → 가).',
      "L'agent, réponse à « qui ? », est une info nouvelle → sujet 이/가 (친구 finit par une voyelle → 가).",
      'Quem age, resposta a "quem?", é info nova → sujeito 이/가 (친구 termina em vogal → 가).',
      'ผู้กระทำที่ตอบ "ใคร?" คือข้อมูลใหม่ → ประธาน 이/가 (친구 ลงท้ายสระ → 가)',
      'Pelaku jawaban "siapa?" adalah info baru → subjek 이/가 (친구 berakhiran vokal → 가).',
      'Người thực hiện trả lời "ai?" là thông tin mới → chủ ngữ 이/가 (친구 kết thúc nguyên âm → 가).',
      '「誰が？」への答え（行為者）は新情報 → 主語 이/가（친구 は母音終わり → 가）。',
    ),
    trans: L(
      'A friend is coming.',
      'Viene un amigo.',
      'Un ami vient.',
      'Um amigo está vindo.',
      'เพื่อนกำลังมา',
      'Seorang teman datang.',
      'Một người bạn đang đến.',
      '友達が来ます。',
    ),
  },

  // place-static-action
  {
    id: 'pa-07-gonghang',
    cue: L(
      'WHERE you arrive — the destination, not where an action happens.',
      'ADÓNDE llegas — el destino, no donde ocurre una acción.',
      "OÙ tu arrives — la destination, pas le lieu d'une action.",
      'AONDE você chega — o destino, não onde uma ação acontece.',
      'คุณไปถึงที่ไหน — จุดหมาย ไม่ใช่ที่ที่เกิดการกระทำ',
      'KE MANA kamu tiba — tujuan, bukan tempat suatu aksi terjadi.',
      'NƠI bạn đến — đích đến, không phải nơi diễn ra hành động.',
      'どこに着くか — 到達点であって、動作の場所ではない。',
    ),
    noun: '공항',
    rest: ' 도착해요.',
    setId: 'place-static-action',
    familyIndex: 0,
    reason: L(
      '도착하다 marks the arrival destination with 에 (the end point), not the action-place 에서.',
      '도착하다 marca el destino de llegada con 에 (el punto final), no el 에서 de lugar de acción.',
      "도착하다 marque la destination d'arrivée avec 에 (le point final), pas le 에서 du lieu d'action.",
      '도착하다 marca o destino de chegada com 에 (o ponto final), não o 에서 de lugar de ação.',
      '도착하다 บอกจุดหมายที่ไปถึงด้วย 에 (จุดสิ้นสุด) ไม่ใช่ 에서 ที่บอกสถานที่ทำกิจกรรม',
      '도착하다 menandai tujuan kedatangan dengan 에 (titik akhir), bukan 에서 tempat aksi.',
      '도착하다 đánh dấu đích đến bằng 에 (điểm cuối), không phải 에서 chỉ nơi hành động.',
      '도착하다 は到着の到達点を 에 で示す。動作の場所の 에서 ではない。',
    ),
    trans: L(
      'I arrive at the airport.',
      'Llego al aeropuerto.',
      "J'arrive à l'aéroport.",
      'Eu chego ao aeroporto.',
      'ฉันไปถึงสนามบิน',
      'Saya tiba di bandara.',
      'Tôi đến sân bay.',
      '空港に到着します。',
    ),
  },
  {
    id: 'pa-08-gongwon',
    cue: L(
      'WHERE the walking happens.',
      'DÓNDE ocurre el paseo.',
      'OÙ se déroule la promenade.',
      'ONDE o passeio acontece.',
      'การเดินเล่นเกิดขึ้นที่ไหน',
      'DI MANA jalan-jalan itu terjadi.',
      'NƠI việc đi dạo diễn ra.',
      '散歩が行われる場所。',
    ),
    noun: '공원',
    rest: ' 산책해요.',
    setId: 'place-static-action',
    familyIndex: 1,
    reason: L(
      'Walking is an action that happens 에서 a place.',
      'Pasear es una acción que ocurre 에서 un lugar.',
      'Se promener est une action qui se déroule 에서 un lieu.',
      'Passear é uma ação que acontece 에서 um lugar.',
      'การเดินเล่นคือกิจกรรมที่เกิดขึ้น 에서 สถานที่หนึ่ง',
      'Berjalan-jalan adalah tindakan yang terjadi 에서 suatu tempat.',
      'Đi dạo là một hành động diễn ra 에서 một nơi.',
      '散歩は場所で行う動作 → 에서。',
    ),
    trans: L(
      'I take a walk in the park.',
      'Paseo por el parque.',
      'Je me promène dans le parc.',
      'Eu passeio no parque.',
      'ฉันเดินเล่นในสวนสาธารณะ',
      'Saya jalan-jalan di taman.',
      'Tôi đi dạo trong công viên.',
      '公園で散歩します。',
    ),
  },
  {
    id: 'pa-09-uija',
    cue: L(
      'WHERE you end up sitting (a resting spot).',
      'DÓNDE acabas sentado (un sitio donde te posas).',
      "OÙ tu finis assis (un point où l'on se pose).",
      'ONDE você acaba sentado (um ponto de pouso).',
      'คุณนั่งลงตรงไหน (จุดที่อยู่นิ่ง)',
      'DI MANA kamu duduk (titik tempat menetap).',
      'NƠI bạn ngồi xuống (một chỗ đặt mình).',
      'どこに座るか（落ち着く位置）。',
    ),
    noun: '의자',
    rest: ' 앉아요.',
    setId: 'place-static-action',
    familyIndex: 0,
    reason: L(
      '앉다 marks the resting position with 에 (the end point of sitting), not 에서.',
      '앉다 marca la posición de reposo con 에 (el punto donde te sientas), no 에서.',
      "앉다 marque la position d'arrivée avec 에 (le point où l'on s'assoit), pas 에서.",
      '앉다 marca a posição de repouso com 에 (o ponto onde se senta), não 에서.',
      '앉다 บอกตำแหน่งที่นั่งด้วย 에 (จุดที่ไปนั่ง) ไม่ใช่ 에서',
      '앉다 menandai posisi duduk dengan 에 (titik tempat duduk), bukan 에서.',
      '앉다 đánh dấu vị trí ngồi bằng 에 (điểm ngồi xuống), không phải 에서.',
      '앉다 は座る到達点を 에 で示す（에서 ではない）。',
    ),
    trans: L(
      'I sit on the chair.',
      'Me siento en la silla.',
      "Je m'assois sur la chaise.",
      'Eu me sento na cadeira.',
      'ฉันนั่งบนเก้าอี้',
      'Saya duduk di kursi.',
      'Tôi ngồi trên ghế.',
      '椅子に座ります。',
    ),
  },
  {
    id: 'pa-10-sijang',
    cue: L(
      'WHERE the buying happens.',
      'DÓNDE ocurre la compra.',
      "OÙ se déroule l'achat.",
      'ONDE a compra acontece.',
      'การซื้อเกิดขึ้นที่ไหน',
      'DI MANA pembelian terjadi.',
      'NƠI việc mua bán diễn ra.',
      '買い物が行われる場所。',
    ),
    noun: '시장',
    rest: ' 사요.',
    setId: 'place-static-action',
    familyIndex: 1,
    reason: L(
      'Buying is an action that happens 에서 a place.',
      'Comprar es una acción que ocurre 에서 un lugar.',
      'Acheter est une action qui se déroule 에서 un lieu.',
      'Comprar é uma ação que acontece 에서 um lugar.',
      'การซื้อคือกิจกรรมที่เกิดขึ้น 에서 สถานที่หนึ่ง',
      'Membeli adalah tindakan yang terjadi 에서 suatu tempat.',
      'Mua là một hành động diễn ra 에서 một nơi.',
      '買うことは場所で行う動作 → 에서。',
    ),
    trans: L(
      'I buy it at the market.',
      'Lo compro en el mercado.',
      "Je l'achète au marché.",
      'Eu compro no mercado.',
      'ฉันซื้อที่ตลาด',
      'Saya membelinya di pasar.',
      'Tôi mua ở chợ.',
      '市場で買います。',
    ),
  },

  // place-recipient
  {
    id: 'pr-08-byeongwon',
    cue: L(
      'You go to the hospital (a place).',
      'Vas al hospital (un lugar).',
      "Tu vas à l'hôpital (un lieu).",
      'Você vai ao hospital (um lugar).',
      'คุณไปโรงพยาบาล (สถานที่)',
      'Kamu pergi ke rumah sakit (sebuah tempat).',
      'Bạn đi đến bệnh viện (một địa điểm).',
      '病院（場所）へ行く。',
    ),
    noun: '병원',
    rest: ' 가요.',
    setId: 'place-recipient',
    familyIndex: 0,
    reason: L(
      'A place destination takes 에, not the person-marker 한테.',
      'Un destino que es lugar lleva 에, no el marcador de persona 한테.',
      'Une destination qui est un lieu prend 에, pas le marqueur de personne 한테.',
      'Um destino que é lugar leva 에, não o marcador de pessoa 한테.',
      'จุดหมายที่เป็นสถานที่ใช้ 에 ไม่ใช่ 한테 ที่ใช้กับคน',
      'Tujuan berupa tempat memakai 에, bukan penanda orang 한테.',
      'Đích đến là địa điểm dùng 에, không phải 한테 dành cho người.',
      '行き先（場所）は 에。人に使う 한테 ではない。',
    ),
    trans: L(
      'I go to the hospital.',
      'Voy al hospital.',
      "Je vais à l'hôpital.",
      'Eu vou ao hospital.',
      'ฉันไปโรงพยาบาล',
      'Saya pergi ke rumah sakit.',
      'Tôi đi đến bệnh viện.',
      '病院に行きます。',
    ),
  },
  {
    id: 'pr-09-gangaji',
    cue: L(
      'You give food TO the puppy (a living recipient).',
      'Le das comida AL perrito (un receptor vivo).',
      'Tu donnes à manger AU chiot (un destinataire vivant).',
      'Você dá comida PARA o cachorrinho (um receptor vivo).',
      'คุณให้อาหารแก่ลูกหมา (ผู้รับที่มีชีวิต)',
      'Kamu memberi makan KEPADA anak anjing (penerima hidup).',
      'Bạn đưa thức ăn CHO cún con (người/vật nhận sống).',
      '子犬に餌をあげる（生きた受け手）。',
    ),
    noun: '강아지',
    rest: ' 밥을 줘요.',
    setId: 'place-recipient',
    familyIndex: 1,
    reason: L(
      'A living recipient (person or animal) takes 한테 (= 에게), not the place 에.',
      'Un receptor vivo (persona o animal) lleva 한테 (= 에게), no el lugar 에.',
      'Un destinataire vivant (personne ou animal) prend 한테 (= 에게), pas le lieu 에.',
      'Um receptor vivo (pessoa ou animal) leva 한테 (= 에게), não o lugar 에.',
      'ผู้รับที่มีชีวิต (คนหรือสัตว์) ใช้ 한테 (= 에게) ไม่ใช่สถานที่ 에',
      'Penerima hidup (orang atau hewan) memakai 한테 (= 에게), bukan tempat 에.',
      'Người/vật nhận sống (người hay động vật) dùng 한테 (= 에게), không phải nơi chốn 에.',
      '生きた受け手（人や動物）は 한테（= 에게）。場所の 에 ではない。',
    ),
    trans: L(
      'I give food to the puppy.',
      'Le doy comida al perrito.',
      'Je donne à manger au chiot.',
      'Eu dou comida para o cachorrinho.',
      'ฉันให้อาหารลูกหมา',
      'Saya memberi makan anak anjing.',
      'Tôi cho cún con ăn cơm.',
      '子犬にご飯をあげます。',
    ),
  },
  {
    id: 'pr-10-hoesa',
    cue: L(
      'You commute to work (a place you attend).',
      'Vas al trabajo (un lugar al que asistes).',
      'Tu vas au travail (un lieu que tu fréquentes).',
      'Você vai ao trabalho (um lugar que frequenta).',
      'คุณไปทำงาน (สถานที่ที่ไปประจำ)',
      'Kamu pergi ke kantor (tempat yang kamu datangi).',
      'Bạn đi làm (nơi bạn lui tới).',
      '会社に通う（通う場所）。',
    ),
    noun: '회사',
    rest: ' 다녀요.',
    setId: 'place-recipient',
    familyIndex: 0,
    reason: L(
      '다니다 (attend/commute) marks the place with 에, not the person-marker 한테.',
      '다니다 (asistir/ir) marca el lugar con 에, no el marcador de persona 한테.',
      '다니다 (fréquenter) marque le lieu avec 에, pas le marqueur de personne 한테.',
      '다니다 (frequentar) marca o lugar com 에, não o marcador de pessoa 한테.',
      '다니다 (ไปประจำ) บอกสถานที่ด้วย 에 ไม่ใช่ 한테 ที่ใช้กับคน',
      '다니다 (rutin mendatangi) menandai tempat dengan 에, bukan penanda orang 한테.',
      '다니다 (lui tới) đánh dấu nơi chốn bằng 에, không phải 한테 dành cho người.',
      '다니다（通う）は場所を 에 で示す。人の 한테 ではない。',
    ),
    trans: L(
      'I go to work.',
      'Voy al trabajo.',
      'Je vais au travail.',
      'Eu vou ao trabalho.',
      'ฉันไปทำงาน',
      'Saya pergi ke kantor.',
      'Tôi đi làm.',
      '会社に通っています。',
    ),
  },

  // also-only
  {
    id: 'am-07-hangugeo',
    cue: L(
      'You study Korean and no other language.',
      'Estudias coreano y ningún otro idioma.',
      'Tu étudies le coréen et aucune autre langue.',
      'Você estuda coreano e nenhum outro idioma.',
      'คุณเรียนแต่ภาษาเกาหลี ไม่เรียนภาษาอื่น',
      'Kamu hanya belajar bahasa Korea, bukan bahasa lain.',
      'Bạn chỉ học tiếng Hàn, không học ngôn ngữ nào khác.',
      '韓国語だけ勉強して、他の言語はしない。',
    ),
    noun: '한국어',
    rest: ' 공부해요.',
    setId: 'also-only',
    familyIndex: 1,
    reason: L(
      '만 = "only"; it restricts to that one thing and replaces 을/를.',
      '만 = "solo"; restringe a esa única cosa y reemplaza a 을/를.',
      '만 = « seulement » ; limite à cette seule chose et remplace 을/를.',
      '만 = "só"; restringe a essa única coisa e substitui 을/를.',
      '만 = "เท่านั้น"; จำกัดให้เหลือสิ่งเดียวและใช้แทน 을/를',
      '만 = "hanya"; membatasi pada satu hal itu dan menggantikan 을/를.',
      '만 = "chỉ"; giới hạn vào đúng một thứ và thay cho 을/를.',
      '만 =「〜だけ」。そのひとつに限定し、을/를 と置き換わる。',
    ),
    trans: L(
      'I study only Korean.',
      'Solo estudio coreano.',
      "J'étudie seulement le coréen.",
      'Eu estudo só coreano.',
      'ฉันเรียนแต่ภาษาเกาหลี',
      'Saya hanya belajar bahasa Korea.',
      'Tôi chỉ học tiếng Hàn.',
      '韓国語だけ勉強します。',
    ),
  },
  {
    id: 'am-08-jumal',
    cue: L(
      'You work on weekdays — and on weekends too.',
      'Trabajas entre semana, y los fines de semana también.',
      'Tu travailles en semaine, et le week-end aussi.',
      'Você trabalha nos dias de semana, e nos fins de semana também.',
      'คุณทำงานวันธรรมดา และวันหยุดสุดสัปดาห์ก็ทำด้วย',
      'Kamu bekerja di hari kerja, dan akhir pekan juga.',
      'Bạn làm việc ngày thường, và cuối tuần cũng vậy.',
      '平日も働き、週末も働く。',
    ),
    noun: '주말',
    rest: ' 일해요.',
    setId: 'also-only',
    familyIndex: 0,
    reason: L(
      '도 = "also/even"; it adds the weekend to your working days.',
      '도 = "también/incluso"; suma el fin de semana a tus días de trabajo.',
      '도 = « aussi / même » ; ajoute le week-end à tes jours de travail.',
      '도 = "também/até"; adiciona o fim de semana aos seus dias de trabalho.',
      '도 = "ด้วย/แม้แต่"; เพิ่มสุดสัปดาห์เข้าไปในวันทำงาน',
      '도 = "juga/bahkan"; menambahkan akhir pekan ke hari kerjamu.',
      '도 = "cũng/ngay cả"; thêm cuối tuần vào những ngày làm việc.',
      '도 =「〜も」。働く日に週末も加える。',
    ),
    trans: L(
      'I work on weekends too.',
      'También trabajo los fines de semana.',
      'Je travaille le week-end aussi.',
      'Eu trabalho nos fins de semana também.',
      'ฉันทำงานวันหยุดสุดสัปดาห์ด้วย',
      'Saya juga bekerja di akhir pekan.',
      'Tôi cũng làm việc cuối tuần.',
      '週末も働きます。',
    ),
  },
  {
    id: 'am-09-dongsaeng',
    cue: L(
      'The others go, and your younger sibling goes too.',
      'Los demás van, y tu hermano menor también va.',
      'Les autres y vont, et ton cadet aussi.',
      'Os outros vão, e o seu irmão mais novo também.',
      'คนอื่นไป และน้องของคุณก็ไปด้วย',
      'Yang lain pergi, dan adikmu juga pergi.',
      'Những người khác đi, và em của bạn cũng đi.',
      '他の人が行き、弟・妹も行く。',
    ),
    noun: '동생',
    rest: ' 가요.',
    setId: 'also-only',
    familyIndex: 0,
    reason: L(
      '도 = "also"; it adds your sibling to the people going and replaces 이/가.',
      '도 = "también"; suma a tu hermano a los que van y reemplaza a 이/가.',
      '도 = « aussi » ; ajoute ton cadet à ceux qui y vont et remplace 이/가.',
      '도 = "também"; adiciona o seu irmão aos que vão e substitui 이/가.',
      '도 = "ด้วย/ก็"; เพิ่มน้องเข้าไปในกลุ่มคนที่ไป และใช้แทน 이/가',
      '도 = "juga"; menambahkan adikmu ke yang pergi dan menggantikan 이/가.',
      '도 = "cũng"; thêm em bạn vào những người đi và thay cho 이/가.',
      '도 =「〜も」。行く人に弟・妹を加え、이/가 と置き換わる。',
    ),
    trans: L(
      'My younger sibling is going too.',
      'Mi hermano menor también va.',
      'Mon cadet y va aussi.',
      'Meu irmão mais novo também vai.',
      'น้องของฉันก็ไปด้วย',
      'Adikku juga pergi.',
      'Em tôi cũng đi.',
      '弟・妹も行きます。',
    ),
  },
  {
    id: 'am-10-sagwa',
    cue: L(
      'You eat apples and no other fruit.',
      'Comes manzanas y ninguna otra fruta.',
      'Tu manges des pommes et aucun autre fruit.',
      'Você come maçãs e nenhuma outra fruta.',
      'คุณกินแต่แอปเปิล ไม่กินผลไม้อื่น',
      'Kamu hanya makan apel, bukan buah lain.',
      'Bạn chỉ ăn táo, không ăn loại quả nào khác.',
      'りんごだけ食べて、他の果物は食べない。',
    ),
    noun: '사과',
    rest: ' 먹어요.',
    setId: 'also-only',
    familyIndex: 1,
    reason: L(
      '만 = "only"; it restricts to apples and replaces 을/를.',
      '만 = "solo"; restringe a las manzanas y reemplaza a 을/를.',
      '만 = « seulement » ; limite aux pommes et remplace 을/를.',
      '만 = "só"; restringe às maçãs e substitui 을/를.',
      '만 = "เท่านั้น"; จำกัดให้เหลือแอปเปิล และใช้แทน 을/를',
      '만 = "hanya"; membatasi pada apel dan menggantikan 을/를.',
      '만 = "chỉ"; giới hạn vào táo và thay cho 을/를.',
      '만 =「〜だけ」。りんごに限定し、을/를 と置き換わる。',
    ),
    trans: L(
      'I eat only apples.',
      'Solo como manzanas.',
      'Je mange seulement des pommes.',
      'Eu como só maçãs.',
      'ฉันกินแต่แอปเปิล',
      'Saya hanya makan apel.',
      'Tôi chỉ ăn táo.',
      'りんごだけ食べます。',
    ),
  },

  // from-until
  {
    id: 'fu-07-jip',
    cue: L(
      'You walk all the way UP TO home (a spatial end point).',
      'Caminas hasta llegar A casa (un punto final en el espacio).',
      "Tu marches JUSQU'À la maison (un point d'arrivée dans l'espace).",
      'Você caminha ATÉ em casa (um ponto final no espaço).',
      'คุณเดินจนถึงบ้าน (จุดสิ้นสุดเชิงพื้นที่)',
      'Kamu berjalan SAMPAI rumah (titik akhir dalam ruang).',
      'Bạn đi bộ ĐẾN tận nhà (điểm cuối trong không gian).',
      '家まで歩く（空間の終点）。',
    ),
    noun: '집',
    rest: ' 걸어요.',
    setId: 'from-until',
    familyIndex: 1,
    reason: L(
      '까지 marks the end point — here a place ("as far as home").',
      '까지 marca el punto final — aquí un lugar ("hasta casa").',
      "까지 marque le point d'arrivée — ici un lieu (« jusqu'à la maison »).",
      '까지 marca o ponto final — aqui um lugar ("até em casa").',
      '까지 บอกจุดสิ้นสุด — ในที่นี้คือสถานที่ ("จนถึงบ้าน")',
      '까지 menandai titik akhir — di sini sebuah tempat ("sampai rumah").',
      '까지 đánh dấu điểm cuối — ở đây là một nơi ("đến tận nhà").',
      '까지 は終点を表す — ここでは場所（「家まで」）。',
    ),
    trans: L(
      'I walk all the way home.',
      'Camino hasta casa.',
      "Je marche jusqu'à la maison.",
      'Eu caminho até casa.',
      'ฉันเดินจนถึงบ้าน',
      'Saya berjalan sampai rumah.',
      'Tôi đi bộ đến tận nhà.',
      '家まで歩きます。',
    ),
  },
  {
    id: 'fu-08-yeogi',
    cue: L(
      'Reading STARTS right here (the starting point).',
      'La lectura EMPIEZA aquí mismo (el punto de inicio).',
      'La lecture COMMENCE ici même (le point de départ).',
      'A leitura COMEÇA bem aqui (o ponto de início).',
      'การอ่าน"เริ่ม"ตรงนี้ (จุดเริ่มต้น)',
      'Membaca DIMULAI dari sini (titik awal).',
      'Việc đọc BẮT ĐẦU ngay từ đây (điểm khởi đầu).',
      'ここから読み「始める」（始点）。',
    ),
    noun: '여기',
    rest: ' 시작해요.',
    setId: 'from-until',
    familyIndex: 0,
    reason: L(
      '부터 marks the starting point of a sequence ("starting from here").',
      '부터 marca el punto de inicio de una secuencia ("desde aquí").',
      "부터 marque le point de départ d'une séquence (« à partir d'ici »).",
      '부터 marca o ponto de início de uma sequência ("a partir daqui").',
      '부터 บอกจุดเริ่มต้นของลำดับ ("เริ่มจากตรงนี้")',
      '부터 menandai titik awal urutan ("mulai dari sini").',
      '부터 đánh dấu điểm bắt đầu của một trình tự ("bắt đầu từ đây").',
      '부터 は順序の始点を表す（「ここから」）。',
    ),
    trans: L(
      'We start from here.',
      'Empezamos desde aquí.',
      "On commence à partir d'ici.",
      'A gente começa a partir daqui.',
      'เราเริ่มจากตรงนี้',
      'Kita mulai dari sini.',
      'Chúng ta bắt đầu từ đây.',
      'ここから始めます。',
    ),
  },
  {
    id: 'fu-09-naeil',
    cue: L(
      'You rest UP TO tomorrow (the end of the rest).',
      'Descansas HASTA mañana (el final del descanso).',
      "Tu te reposes JUSQU'À demain (la fin du repos).",
      'Você descansa ATÉ amanhã (o fim do descanso).',
      'คุณพักจนถึงพรุ่งนี้ (จุดสิ้นสุดของการพัก)',
      'Kamu beristirahat SAMPAI besok (akhir istirahat).',
      'Bạn nghỉ ĐẾN ngày mai (điểm kết thúc kỳ nghỉ).',
      '明日まで休む（休みの終わり）。',
    ),
    noun: '내일',
    rest: ' 쉬어요.',
    setId: 'from-until',
    familyIndex: 1,
    reason: L(
      '까지 marks the end point of a time range ("until").',
      '까지 marca el punto final de un rango de tiempo ("hasta").',
      "까지 marque le point d'arrivée d'un intervalle de temps (« jusqu'à »).",
      '까지 marca o ponto final de um intervalo de tempo ("até").',
      '까지 บอกจุดสิ้นสุดของช่วงเวลา ("จนถึง")',
      '까지 menandai titik akhir rentang waktu ("sampai").',
      '까지 đánh dấu điểm kết thúc của một khoảng thời gian ("đến").',
      '까지 は時間範囲の終点を表す（「〜まで」）。',
    ),
    trans: L(
      'I rest until tomorrow.',
      'Descanso hasta mañana.',
      "Je me repose jusqu'à demain.",
      'Eu descanso até amanhã.',
      'ฉันพักจนถึงพรุ่งนี้',
      'Saya beristirahat sampai besok.',
      'Tôi nghỉ đến mai.',
      '明日まで休みます。',
    ),
  },
  {
    id: 'fu-10-jeomsim',
    cue: L(
      'You get busy STARTING at lunchtime.',
      'Estás ocupado A PARTIR del almuerzo.',
      'Tu deviens occupé À PARTIR du déjeuner.',
      'Você fica ocupado A PARTIR do almoço.',
      'คุณเริ่มยุ่งตั้งแต่ตอนกลางวัน',
      'Kamu mulai sibuk SEJAK waktu makan siang.',
      'Bạn bận rộn TỪ giờ ăn trưa.',
      '昼から忙しくなる。',
    ),
    noun: '점심',
    rest: ' 바빠요.',
    setId: 'from-until',
    familyIndex: 0,
    reason: L(
      '부터 marks the starting point ("from / since").',
      '부터 marca el punto de inicio ("desde").',
      '부터 marque le point de départ (« à partir de »).',
      '부터 marca o ponto de início ("a partir de").',
      '부터 บอกจุดเริ่มต้น ("ตั้งแต่")',
      '부터 menandai titik awal ("sejak / dari").',
      '부터 đánh dấu điểm bắt đầu ("từ").',
      '부터 は始点を表す（「〜から」）。',
    ),
    trans: L(
      'I am busy from lunchtime.',
      'Estoy ocupado desde el almuerzo.',
      'Je suis occupé à partir du déjeuner.',
      'Estou ocupado a partir do almoço.',
      'ฉันยุ่งตั้งแต่ตอนกลางวัน',
      'Saya sibuk sejak makan siang.',
      'Tôi bận từ giờ ăn trưa.',
      '昼から忙しいです。',
    ),
  },

  // -- contractions (subproject 5): 나/저/너/누구 + 가 → 내가/제가/네가/누가 --
  {
    id: 'ct-01-naega-galge',
    cue: L(
      'You volunteer: I will go.',
      'Te ofreces: yo voy.',
      "Tu te proposes : j'y vais.",
      'Você se oferece: eu vou.',
      'คุณอาสา: ฉันไปเอง',
      'Kamu menawarkan diri: aku yang pergi.',
      'Bạn xung phong: tôi đi.',
      '進んで「私が行く」と言う。',
    ),
    noun: '나',
    rest: ' 갈게요.',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '나 + 가 fuses into 내가 — never 나가.',
      '나 + 가 se fusiona en 내가 — nunca 나가.',
      '나 + 가 fusionne en 내가 — jamais 나가.',
      '나 + 가 funde-se em 내가 — nunca 나가.',
      '나 + 가 รวมกันเป็น 내가 ไม่ใช่ 나가',
      '나 + 가 melebur menjadi 내가 — bukan 나가.',
      '나 + 가 hợp thành 내가 — không phải 나가.',
      '나 + 가 は 내가 に融合。나가 ではない。',
    ),
    trans: L(
      "I'll go.",
      'Yo voy.',
      "J'y vais.",
      'Eu vou.',
      'ฉันไปเอง',
      'Aku yang pergi.',
      'Tôi sẽ đi.',
      '私が行きます。',
    ),
  },
  {
    id: 'ct-02-naega-haesseo',
    cue: L(
      'You own up: I am the one who did it.',
      'Lo admites: fui yo quien lo hizo.',
      "Tu avoues : c'est moi qui l'ai fait.",
      'Você admite: fui eu que fiz.',
      'คุณยอมรับ: ฉันเป็นคนทำ',
      'Kamu mengaku: akulah yang melakukannya.',
      'Bạn thừa nhận: chính tôi đã làm.',
      '「私がやった」と認める。',
    ),
    noun: '나',
    rest: ' 했어요.',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '나 + 가 fuses into 내가 — never 나가.',
      '나 + 가 se fusiona en 내가 — nunca 나가.',
      '나 + 가 fusionne en 내가 — jamais 나가.',
      '나 + 가 funde-se em 내가 — nunca 나가.',
      '나 + 가 รวมกันเป็น 내가 ไม่ใช่ 나가',
      '나 + 가 melebur menjadi 내가 — bukan 나가.',
      '나 + 가 hợp thành 내가 — không phải 나가.',
      '나 + 가 は 내가 に融合。나가 ではない。',
    ),
    trans: L(
      'I did it.',
      'Lo hice yo.',
      "C'est moi qui l'ai fait.",
      'Fui eu que fiz.',
      'ฉันเป็นคนทำ',
      'Aku yang melakukannya.',
      'Chính tôi đã làm.',
      '私がやりました。',
    ),
  },
  {
    id: 'ct-03-naega-mandeureo',
    cue: L(
      'You made it yourself — not someone else.',
      'Lo hiciste tú mismo, no otra persona.',
      "C'est toi qui l'as fait, pas un autre.",
      'Foi você mesmo que fez, não outra pessoa.',
      'คุณทำเอง ไม่ใช่คนอื่น',
      'Kamu sendiri yang membuatnya, bukan orang lain.',
      'Chính bạn làm, không phải người khác.',
      '他の人ではなく自分が作った。',
    ),
    noun: '나',
    rest: ' 만들었어요.',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '나 + 가 fuses into 내가 — never 나가.',
      '나 + 가 se fusiona en 내가 — nunca 나가.',
      '나 + 가 fusionne en 내가 — jamais 나가.',
      '나 + 가 funde-se em 내가 — nunca 나가.',
      '나 + 가 รวมกันเป็น 내가 ไม่ใช่ 나가',
      '나 + 가 melebur menjadi 내가 — bukan 나가.',
      '나 + 가 hợp thành 내가 — không phải 나가.',
      '나 + 가 は 내가 に融合。나가 ではない。',
    ),
    trans: L(
      'I made it.',
      'Lo hice yo.',
      "C'est moi qui l'ai fait.",
      'Fui eu que fiz.',
      'ฉันทำเอง',
      'Aku yang membuatnya.',
      'Tôi đã tự làm.',
      '私が作りました。',
    ),
  },
  {
    id: 'ct-04-jega-halge',
    cue: L(
      'You politely volunteer: I will do it.',
      'Te ofreces con cortesía: yo lo hago.',
      'Tu te proposes poliment : je le fais.',
      'Você se oferece com cortesia: eu faço.',
      'คุณอาสาอย่างสุภาพ: ฉันทำเอง',
      'Kamu menawarkan diri dengan sopan: saya yang melakukannya.',
      'Bạn lịch sự xung phong: tôi làm.',
      '丁寧に「私がやります」と申し出る。',
    ),
    noun: '저',
    rest: ' 할게요.',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '저 + 가 fuses into 제가 — never 저가 (저 is the humble "I").',
      '저 + 가 se fusiona en 제가 — nunca 저가 (저 es el "yo" humilde).',
      '저 + 가 fusionne en 제가 — jamais 저가 (저 = « je » humble).',
      '저 + 가 funde-se em 제가 — nunca 저가 (저 é o "eu" humilde).',
      '저 + 가 รวมเป็น 제가 ไม่ใช่ 저가 (저 คือ "ฉัน" แบบสุภาพ)',
      '저 + 가 melebur menjadi 제가 — bukan 저가 (저 = "saya" sopan).',
      '저 + 가 hợp thành 제가 — không phải 저가 (저 là "tôi" khiêm tốn).',
      '저 + 가 は 제가 に融合。저가 ではない（저 はへりくだった「私」）。',
    ),
    trans: L(
      "I'll do it.",
      'Yo lo hago.',
      'Je le fais.',
      'Eu faço.',
      'ฉันทำเอง',
      'Saya yang melakukannya.',
      'Tôi sẽ làm.',
      '私がやります。',
    ),
  },
  {
    id: 'ct-05-jega-anieyo',
    cue: L(
      'You politely deny it: it was not me.',
      'Lo niegas con cortesía: no fui yo.',
      "Tu nies poliment : ce n'était pas moi.",
      'Você nega com cortesia: não fui eu.',
      'คุณปฏิเสธอย่างสุภาพ: ไม่ใช่ฉัน',
      'Kamu menyangkal dengan sopan: bukan saya.',
      'Bạn lịch sự phủ nhận: không phải tôi.',
      '丁寧に「私ではありません」と否定する。',
    ),
    noun: '저',
    rest: ' 아니에요.',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '저 + 가 fuses into 제가 — never 저가 (저 is the humble "I").',
      '저 + 가 se fusiona en 제가 — nunca 저가 (저 es el "yo" humilde).',
      '저 + 가 fusionne en 제가 — jamais 저가 (저 = « je » humble).',
      '저 + 가 funde-se em 제가 — nunca 저가 (저 é o "eu" humilde).',
      '저 + 가 รวมเป็น 제가 ไม่ใช่ 저가 (저 คือ "ฉัน" แบบสุภาพ)',
      '저 + 가 melebur menjadi 제가 — bukan 저가 (저 = "saya" sopan).',
      '저 + 가 hợp thành 제가 — không phải 저가 (저 là "tôi" khiêm tốn).',
      '저 + 가 は 제가 に融合。저가 ではない（저 はへりくだった「私」）。',
    ),
    trans: L(
      "It wasn't me.",
      'No fui yo.',
      "Ce n'était pas moi.",
      'Não fui eu.',
      'ไม่ใช่ฉัน',
      'Bukan saya.',
      'Không phải tôi.',
      '私ではありません。',
    ),
  },
  {
    id: 'ct-06-jega-naelge',
    cue: L(
      'You politely offer to pay.',
      'Te ofreces con cortesía a pagar.',
      'Tu proposes poliment de payer.',
      'Você se oferece com cortesia para pagar.',
      'คุณอาสาจ่ายอย่างสุภาพ',
      'Kamu menawarkan diri membayar dengan sopan.',
      'Bạn lịch sự đề nghị trả tiền.',
      '丁寧に「私が払います」と申し出る。',
    ),
    noun: '저',
    rest: ' 낼게요.',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '저 + 가 fuses into 제가 — never 저가 (저 is the humble "I").',
      '저 + 가 se fusiona en 제가 — nunca 저가 (저 es el "yo" humilde).',
      '저 + 가 fusionne en 제가 — jamais 저가 (저 = « je » humble).',
      '저 + 가 funde-se em 제가 — nunca 저가 (저 é o "eu" humilde).',
      '저 + 가 รวมเป็น 제가 ไม่ใช่ 저가 (저 คือ "ฉัน" แบบสุภาพ)',
      '저 + 가 melebur menjadi 제가 — bukan 저가 (저 = "saya" sopan).',
      '저 + 가 hợp thành 제가 — không phải 저가 (저 là "tôi" khiêm tốn).',
      '저 + 가 は 제가 に融合。저가 ではない（저 はへりくだった「私」）。',
    ),
    trans: L(
      "I'll pay.",
      'Pago yo.',
      'Je paie.',
      'Eu pago.',
      'ฉันจ่ายเอง',
      'Saya yang bayar.',
      'Tôi sẽ trả.',
      '私が払います。',
    ),
  },
  {
    id: 'ct-07-nega-hae',
    cue: L(
      'You tell a friend: YOU do it.',
      'Le dices a un amigo: hazlo TÚ.',
      'Tu dis à un ami : fais-le, TOI.',
      'Você diz a um amigo: faça VOCÊ.',
      'คุณบอกเพื่อน: เธอทำสิ',
      'Kamu menyuruh teman: KAMU yang lakukan.',
      'Bạn bảo bạn mình: CẬU làm đi.',
      '友達に「君がやって」と言う。',
    ),
    noun: '너',
    rest: ' 해.',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '너 + 가 fuses into 네가 — never 너가; spoken 니가 to avoid sounding like 내가.',
      '너 + 가 se fusiona en 네가 — nunca 너가; al hablar se dice 니가 para no confundirlo con 내가.',
      "너 + 가 fusionne en 네가 — jamais 너가 ; à l'oral on dit 니가 pour ne pas le confondre avec 내가.",
      '너 + 가 funde-se em 네가 — nunca 너가; na fala diz-se 니가 para não soar como 내가.',
      '너 + 가 รวมเป็น 네가 ไม่ใช่ 너가; เวลาพูดออกเสียง 니가 เพื่อไม่ให้ซ้ำกับ 내가',
      '너 + 가 melebur menjadi 네가 — bukan 너가; saat bicara diucapkan 니가 agar tak rancu dengan 내가.',
      '너 + 가 hợp thành 네가 — không phải 너가; khi nói đọc 니가 để khỏi giống 내가.',
      '너 + 가 は 네가 に融合。너가 ではない。会話では 내가 と紛れぬよう 니가 と発音。',
    ),
    trans: L(
      'You do it.',
      'Hazlo tú.',
      'Fais-le, toi.',
      'Faça você.',
      'เธอทำสิ',
      'Kamu yang lakukan.',
      'Cậu làm đi.',
      '君がやって。',
    ),
  },
  {
    id: 'ct-08-nega-golla',
    cue: L(
      'You let a friend choose: YOU pick.',
      'Dejas que elija un amigo: elige TÚ.',
      'Tu laisses un ami choisir : choisis, TOI.',
      'Você deixa um amigo escolher: escolha VOCÊ.',
      'คุณให้เพื่อนเลือก: เธอเลือกสิ',
      'Kamu menyuruh teman memilih: KAMU yang pilih.',
      'Bạn để bạn mình chọn: CẬU chọn đi.',
      '友達に「君が選んで」と言う。',
    ),
    noun: '너',
    rest: ' 골라.',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '너 + 가 fuses into 네가 — never 너가; spoken 니가 to avoid sounding like 내가.',
      '너 + 가 se fusiona en 네가 — nunca 너가; al hablar se dice 니가 para no confundirlo con 내가.',
      "너 + 가 fusionne en 네가 — jamais 너가 ; à l'oral on dit 니가 pour ne pas le confondre avec 내가.",
      '너 + 가 funde-se em 네가 — nunca 너가; na fala diz-se 니가 para não soar como 내가.',
      '너 + 가 รวมเป็น 네가 ไม่ใช่ 너가; เวลาพูดออกเสียง 니가 เพื่อไม่ให้ซ้ำกับ 내가',
      '너 + 가 melebur menjadi 네가 — bukan 너가; saat bicara diucapkan 니가 agar tak rancu dengan 내가.',
      '너 + 가 hợp thành 네가 — không phải 너가; khi nói đọc 니가 để khỏi giống 내가.',
      '너 + 가 は 네가 に融合。너가 ではない。会話では 내가 と紛れぬよう 니가 と発音。',
    ),
    trans: L(
      'You choose.',
      'Elige tú.',
      'Choisis, toi.',
      'Escolha você.',
      'เธอเลือกสิ',
      'Kamu yang pilih.',
      'Cậu chọn đi.',
      '君が選んで。',
    ),
  },
  {
    id: 'ct-09-nuga-wasseo',
    cue: L(
      'You ask: WHO came?',
      'Preguntas: ¿QUIÉN vino?',
      'Tu demandes : QUI est venu ?',
      'Você pergunta: QUEM veio?',
      'คุณถาม: ใครมา?',
      'Kamu bertanya: SIAPA yang datang?',
      'Bạn hỏi: AI đã đến?',
      '「誰が来た？」と尋ねる。',
    ),
    noun: '누구',
    rest: ' 왔어요?',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '누구 + 가 fuses into 누가 — never 누구가.',
      '누구 + 가 se fusiona en 누가 — nunca 누구가.',
      '누구 + 가 fusionne en 누가 — jamais 누구가.',
      '누구 + 가 funde-se em 누가 — nunca 누구가.',
      '누구 + 가 รวมเป็น 누가 ไม่ใช่ 누구가',
      '누구 + 가 melebur menjadi 누가 — bukan 누구가.',
      '누구 + 가 hợp thành 누가 — không phải 누구가.',
      '누구 + 가 は 누가 に融合。누구가 ではない。',
    ),
    trans: L(
      'Who came?',
      '¿Quién vino?',
      'Qui est venu ?',
      'Quem veio?',
      'ใครมา?',
      'Siapa yang datang?',
      'Ai đã đến?',
      '誰が来ましたか？',
    ),
  },
  {
    id: 'ct-10-nuga-haesseo',
    cue: L(
      'You ask: WHO did it?',
      'Preguntas: ¿QUIÉN lo hizo?',
      "Tu demandes : QUI l'a fait ?",
      'Você pergunta: QUEM fez?',
      'คุณถาม: ใครทำ?',
      'Kamu bertanya: SIAPA yang melakukannya?',
      'Bạn hỏi: AI đã làm?',
      '「誰がやった？」と尋ねる。',
    ),
    noun: '누구',
    rest: ' 했어요?',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '누구 + 가 fuses into 누가 — never 누구가.',
      '누구 + 가 se fusiona en 누가 — nunca 누구가.',
      '누구 + 가 fusionne en 누가 — jamais 누구가.',
      '누구 + 가 funde-se em 누가 — nunca 누구가.',
      '누구 + 가 รวมเป็น 누가 ไม่ใช่ 누구가',
      '누구 + 가 melebur menjadi 누가 — bukan 누구가.',
      '누구 + 가 hợp thành 누가 — không phải 누구가.',
      '누구 + 가 は 누가 に融合。누구가 ではない。',
    ),
    trans: L(
      'Who did it?',
      '¿Quién lo hizo?',
      "Qui l'a fait ?",
      'Quem fez?',
      'ใครทำ?',
      'Siapa yang melakukannya?',
      'Ai đã làm?',
      '誰がやりましたか？',
    ),
  },
  {
    id: 'ct-11-nuga-igyeosseo',
    cue: L(
      'You ask: WHO won?',
      'Preguntas: ¿QUIÉN ganó?',
      'Tu demandes : QUI a gagné ?',
      'Você pergunta: QUEM ganhou?',
      'คุณถาม: ใครชนะ?',
      'Kamu bertanya: SIAPA yang menang?',
      'Bạn hỏi: AI đã thắng?',
      '「誰が勝った？」と尋ねる。',
    ),
    noun: '누구',
    rest: ' 이겼어요?',
    setId: 'contraction',
    familyIndex: 0,
    reason: L(
      '누구 + 가 fuses into 누가 — never 누구가.',
      '누구 + 가 se fusiona en 누가 — nunca 누구가.',
      '누구 + 가 fusionne en 누가 — jamais 누구가.',
      '누구 + 가 funde-se em 누가 — nunca 누구가.',
      '누구 + 가 รวมเป็น 누가 ไม่ใช่ 누구가',
      '누구 + 가 melebur menjadi 누가 — bukan 누구가.',
      '누구 + 가 hợp thành 누가 — không phải 누구가.',
      '누구 + 가 は 누가 に融合。누구가 ではない。',
    ),
    trans: L(
      'Who won?',
      '¿Quién ganó?',
      'Qui a gagné ?',
      'Quem ganhou?',
      'ใครชนะ?',
      'Siapa yang menang?',
      'Ai đã thắng?',
      '誰が勝ちましたか？',
    ),
  },
]
