import type { DrillItem } from '~/lib/domain'
import { L } from './locale'

/** 은/는 vs 이/가 shock-filter drill. Fixed pedagogical order. */
export const PARTICLE_DRILLS: DrillItem[] = [
  {
    id: 'd01-jeo',
    cue: L('You introduce yourself for the first time.', 'Te presentas por primera vez.', 'Tu te présentes pour la première fois.', 'Você se apresenta pela primeira vez.', 'คุณแนะนำตัวครั้งแรก', 'Kamu memperkenalkan diri untuk pertama kali.', 'Bạn tự giới thiệu lần đầu.', '初めて自己紹介する。'),
    noun: '저',
    rest: ' 학생이에요.',
    setId: 'topic-subject',
    familyIndex: 0,
    reason: L(
      'Introducing yourself sets the TOPIC: "as for me…" → 은/는.',
      'Presentarte establece el TEMA: "en cuanto a mí…" → 은/는.',
      'Se présenter pose le THÈME : « quant à moi… » → 은/는.',
      'Apresentar-se define o TÓPICO: "quanto a mim…" → 은/는.',
      'การแนะนำตัวคือการตั้งหัวเรื่อง: "สำหรับฉัน…" → 은/는',
      'Memperkenalkan diri menetapkan TOPIK: "mengenai saya…" → 은/는.',
      'Tự giới thiệu là đặt CHỦ ĐỀ: "về phần tôi…" → 은/는.',
      '自己紹介は主題の提示（「私について言えば」）→ 은/는。',
    ),
    trans: L('I am a student.', 'Yo soy estudiante.', 'Je suis étudiant·e.', 'Eu sou estudante.', 'ฉันเป็นนักเรียน', 'Saya pelajar.', 'Tôi là học sinh.', '私は学生です。'),
  },
  {
    id: 'd02-chingu',
    cue: L('You answer: "WHO came?"', 'Respondes a: «¿QUIÉN vino?»', 'Tu réponds à : « QUI est venu ? »', 'Você responde: "QUEM veio?"', 'คุณตอบคำถาม: "ใครมา?"', 'Kamu menjawab: "SIAPA yang datang?"', 'Bạn trả lời: "AI đã đến?"', '「誰が来たの？」に答える。'),
    noun: '친구',
    rest: ' 왔어요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'Answers to "who?/what?" point at NEW info → 이/가.',
      'Las respuestas a "¿quién?/¿qué?" señalan info NUEVA → 이/가.',
      'Les réponses à « qui ?/quoi ? » désignent une info NOUVELLE → 이/가.',
      'Respostas a "quem?/o quê?" apontam info NOVA → 이/가.',
      'คำตอบของ "ใคร?/อะไร?" ชี้ข้อมูลใหม่ → 이/가',
      'Jawaban atas "siapa?/apa?" menunjuk info BARU → 이/가.',
      'Câu trả lời cho "ai?/cái gì?" chỉ thông tin MỚI → 이/가.',
      '「誰が？何が？」への答えは新情報 → 이/가。',
    ),
    trans: L('A friend came.', 'Vino un amigo.', 'Un ami est venu.', 'Um amigo veio.', 'เพื่อนมา', 'Seorang teman datang.', 'Một người bạn đã đến.', '友達が来ました。'),
  },
  {
    id: 'd03-hyeong',
    cue: L('You talk about your older brother in general.', 'Hablas de tu hermano mayor en general.', 'Tu parles de ton grand frère en général.', 'Você fala do seu irmão mais velho em geral.', 'คุณเล่าเรื่องพี่ชายแบบทั่วไป', 'Kamu bercerita tentang kakak laki-lakimu secara umum.', 'Bạn kể về anh trai một cách chung chung.', '兄について一般的な話をする。'),
    noun: '형',
    rest: ' 회사원이에요.',
    setId: 'topic-subject',
    familyIndex: 0,
    reason: L(
      'A general statement about someone known → topic 은/는. 형 ends in a consonant → 은.',
      'Una afirmación general sobre alguien conocido → tema 은/는. 형 termina en consonante → 은.',
      'Une affirmation générale sur quelqu\'un de connu → thème 은/는. 형 finit par consonne → 은.',
      'Afirmação geral sobre alguém conhecido → tópico 은/는. 형 termina em consoante → 은.',
      'การพูดทั่วไปถึงคนที่รู้จัก → หัวเรื่อง 은/는. 형 ลงท้ายพยัญชนะ → 은',
      'Pernyataan umum tentang orang yang dikenal → topik 은/는. 형 berakhir konsonan → 은.',
      'Phát biểu chung về người đã biết → chủ đề 은/는. 형 kết thúc phụ âm → 은.',
      '既知の人物への一般的な記述 → 主題 은/는。형 は子音終わり → 은。',
    ),
    trans: L('My older brother is an office worker.', 'Mi hermano mayor es oficinista.', 'Mon grand frère est employé de bureau.', 'Meu irmão mais velho é funcionário de escritório.', 'พี่ชายเป็นพนักงานบริษัท', 'Kakakku karyawan kantor.', 'Anh trai tôi là nhân viên văn phòng.', '兄は会社員です。'),
  },
  {
    id: 'd04-chaek',
    cue: L('"What\'s on the table?" — existence with 있다.', '«¿Qué hay en la mesa?» — existencia con 있다.', '« Qu\'y a-t-il sur la table ? » — existence avec 있다.', '"O que tem na mesa?" — existência com 있다.', '"บนโต๊ะมีอะไร?" — การมีอยู่กับ 있다', '"Ada apa di meja?" — keberadaan dengan 있다.', '"Trên bàn có gì?" — tồn tại với 있다.', '「机に何がある？」— 있다 の存在文。'),
    noun: '책',
    rest: ' 있어요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'Existence with 있다/없다 takes 이/가. 책 ends in a consonant → 이.',
      'La existencia con 있다/없다 lleva 이/가. 책 termina en consonante → 이.',
      'L\'existence avec 있다/없다 prend 이/가. 책 finit par consonne → 이.',
      'Existência com 있다/없다 leva 이/가. 책 termina em consoante → 이.',
      'การมีอยู่กับ 있다/없다 ใช้ 이/가. 책 ลงท้ายพยัญชนะ → 이',
      'Keberadaan dengan 있다/없다 memakai 이/가. 책 berakhir konsonan → 이.',
      'Tồn tại với 있다/없다 dùng 이/가. 책 kết thúc phụ âm → 이.',
      '있다/없다 の存在文は 이/가。책 は子音終わり → 이。',
    ),
    trans: L('There\'s a book.', 'Hay un libro.', 'Il y a un livre.', 'Tem um livro.', 'มีหนังสือ', 'Ada buku.', 'Có một quyển sách.', '本があります。'),
  },
  {
    id: 'd05-bi',
    cue: L('You look out the window and report the weather (new info).', 'Miras por la ventana y comentas el clima (info nueva).', 'Tu regardes par la fenêtre et annonces la météo (info nouvelle).', 'Você olha pela janela e comenta o tempo (info nova).', 'คุณมองออกหน้าต่างแล้วบอกสภาพอากาศ (ข้อมูลใหม่)', 'Kamu melihat ke jendela dan melaporkan cuaca (info baru).', 'Bạn nhìn ra cửa sổ và nói về thời tiết (thông tin mới).', '窓の外を見て天気を伝える（新情報）。'),
    noun: '비',
    rest: ' 와요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'Weather phenomena appear as NEW info → 이/가. «비는 와요» would sound contrastive.',
      'Los fenómenos del clima aparecen como info NUEVA → 이/가. «비는 와요» sonaría a contraste.',
      'Les phénomènes météo surgissent comme info NOUVELLE → 이/가. « 비는 와요 » sonnerait contrastif.',
      'Fenômenos do tempo surgem como info NOVA → 이/가. «비는 와요» soaria contrastivo.',
      'ปรากฏการณ์อากาศคือข้อมูลใหม่ → 이/가. «비는 와요» จะฟังดูเชิงเปรียบต่าง',
      'Fenomena cuaca muncul sebagai info BARU → 이/가. «비는 와요» terdengar kontras.',
      'Hiện tượng thời tiết là thông tin MỚI → 이/가. «비는 와요» nghe như đối chiếu.',
      '天気は新情報として現れる → 이/가。「비는 와요」は対比に聞こえる。',
    ),
    trans: L('It\'s raining.', 'Está lloviendo.', 'Il pleut.', 'Está chovendo.', 'ฝนกำลังตก', 'Sedang hujan.', 'Trời đang mưa.', '雨が降っています。'),
  },
  {
    id: 'd06-goyangi',
    cue: L('A general truth: cats (as a species) are cute.', 'Una verdad general: los gatos (como especie) son lindos.', 'Une vérité générale : les chats (en général) sont mignons.', 'Uma verdade geral: gatos (como espécie) são fofos.', 'ความจริงทั่วไป: แมว (โดยรวม) น่ารัก', 'Kebenaran umum: kucing (sebagai spesies) itu lucu.', 'Chân lý chung: mèo (nói chung) dễ thương.', '一般論：猫（という種）はかわいい。'),
    noun: '고양이',
    rest: ' 귀여워요.',
    setId: 'topic-subject',
    familyIndex: 0,
    reason: L(
      'General truths and categories take topic 은/는: "cats (in general)…".',
      'Las verdades generales y categorías llevan tema 은/는: "los gatos (en general)…".',
      'Les vérités générales prennent le thème 은/는 : « les chats (en général)… ».',
      'Verdades gerais e categorias levam tópico 은/는: "gatos (em geral)…".',
      'ความจริงทั่วไปและหมวดหมู่ใช้หัวเรื่อง 은/는: "แมว (โดยทั่วไป)…"',
      'Kebenaran umum dan kategori memakai topik 은/는: "kucing (pada umumnya)…".',
      'Chân lý chung và phạm trù dùng chủ đề 은/는: "mèo (nói chung)…".',
      '一般論・カテゴリーは主題 은/는：「猫（一般）は…」。',
    ),
    trans: L('Cats are cute.', 'Los gatos son lindos.', 'Les chats sont mignons.', 'Os gatos são fofos.', 'แมวน่ารัก', 'Kucing itu lucu.', 'Mèo dễ thương.', '猫はかわいいです。'),
  },
  {
    id: 'd07-sigan',
    cue: L('You apologize: you have no time (없다).', 'Te disculpas: no tienes tiempo (없다).', 'Tu t\'excuses : tu n\'as pas le temps (없다).', 'Você se desculpa: não tem tempo (없다).', 'คุณขอโทษ: ไม่มีเวลา (없다)', 'Kamu minta maaf: tidak punya waktu (없다).', 'Bạn xin lỗi: không có thời gian (없다).', '謝る：時間がない（없다）。'),
    noun: '시간',
    rest: ' 없어요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      '있다/없다 (have/not have, exist) pair with 이/가. 시간 ends in a consonant → 이.',
      '있다/없다 (tener/no tener, existir) van con 이/가. 시간 termina en consonante → 이.',
      '있다/없다 (avoir/ne pas avoir) vont avec 이/가. 시간 finit par consonne → 이.',
      '있다/없다 (ter/não ter, existir) combinam com 이/가. 시간 termina em consoante → 이.',
      '있다/없다 (มี/ไม่มี) ใช้กับ 이/가. 시간 ลงท้ายพยัญชนะ → 이',
      '있다/없다 (punya/tidak punya) berpasangan dengan 이/가. 시간 berakhir konsonan → 이.',
      '있다/없다 (có/không có) đi với 이/가. 시간 kết thúc phụ âm → 이.',
      '있다/없다（ある・ない）は 이/가 と共起。시간 は子音終わり → 이。',
    ),
    trans: L('I have no time.', 'No tengo tiempo.', 'Je n\'ai pas le temps.', 'Não tenho tempo.', 'ไม่มีเวลา', 'Tidak ada waktu.', 'Tôi không có thời gian.', '時間がありません。'),
  },
  {
    id: 'd08-keopi',
    cue: L('Contrast: coffee yes, tea no.', 'Contraste: el café sí, el té no.', 'Contraste : le café oui, le thé non.', 'Contraste: café sim, chá não.', 'เปรียบต่าง: กาแฟใช่ ชาไม่', 'Kontras: kopi iya, teh tidak.', 'Đối chiếu: cà phê thì thích, trà thì không.', '対比：コーヒーは好き、お茶は嫌い。'),
    noun: '커피',
    rest: ' 좋아하지만 차는 안 마셔요.',
    setId: 'topic-subject',
    familyIndex: 0,
    reason: L(
      'Explicit contrast between two things is the signature use of 은/는.',
      'El contraste explícito entre dos cosas es el uso estrella de 은/는.',
      'Le contraste explicite entre deux choses est l\'usage signature de 은/는.',
      'Contraste explícito entre duas coisas é o uso clássico de 은/는.',
      'การเปรียบต่างชัดเจนระหว่างสองสิ่งคือการใช้เด่นของ 은/는',
      'Kontras eksplisit antara dua hal adalah penggunaan khas 은/는.',
      'Đối chiếu rõ ràng giữa hai thứ là cách dùng đặc trưng của 은/는.',
      '二つの物事の明示的な対比は 은/는 の代表的用法。',
    ),
    trans: L('I like coffee, but I don\'t drink tea.', 'El café me gusta, pero no bebo té.', 'J\'aime le café, mais je ne bois pas de thé.', 'Gosto de café, mas não bebo chá.', 'ชอบกาแฟ แต่ไม่ดื่มชา', 'Suka kopi, tapi tidak minum teh.', 'Thích cà phê, nhưng không uống trà.', 'コーヒーは好きですが、お茶は飲みません。'),
  },
  {
    id: 'd09-naemsae',
    cue: L('You suddenly notice a smell (new sensory info).', 'De repente notas un olor (info sensorial nueva).', 'Tu remarques soudain une odeur (info sensorielle nouvelle).', 'Você de repente nota um cheiro (info sensorial nova).', 'จู่ๆ คุณได้กลิ่น (ข้อมูลใหม่ทางประสาทสัมผัส)', 'Tiba-tiba kamu mencium bau (info indrawi baru).', 'Bạn chợt nhận ra một mùi hương (thông tin cảm giác mới).', 'ふと匂いに気づく（新しい感覚情報）。'),
    noun: '냄새',
    rest: ' 좋아요!',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'Something you just perceived = new info bursting in → 이/가.',
      'Algo que acabas de percibir = info nueva que irrumpe → 이/가.',
      'Ce que tu viens de percevoir = info nouvelle qui surgit → 이/가.',
      'Algo que você acabou de perceber = info nova surgindo → 이/가.',
      'สิ่งที่เพิ่งรับรู้ = ข้อมูลใหม่ที่โผล่มา → 이/가',
      'Sesuatu yang baru kamu rasakan = info baru yang muncul → 이/가.',
      'Điều bạn vừa cảm nhận = thông tin mới ập đến → 이/가.',
      '今知覚したばかりのもの＝飛び込んでくる新情報 → 이/가。',
    ),
    trans: L('It smells good!', '¡Qué bien huele!', 'Ça sent bon !', 'Que cheiro bom!', 'กลิ่นหอมจัง!', 'Baunya enak!', 'Thơm quá!', 'いい匂いですね！'),
  },
  {
    id: 'd10-mul',
    cue: L('You\'re still talking about the water you already mentioned.', 'Sigues hablando del agua que ya mencionaron.', 'Vous parlez encore de l\'eau déjà mentionnée.', 'Vocês continuam falando da água já mencionada.', 'ยังคุยเรื่องน้ำที่พูดถึงไปแล้ว', 'Kalian masih membicarakan air yang sudah disebut.', 'Vẫn đang nói về nước đã nhắc đến trước đó.', 'さっき話に出た水について話を続けている。'),
    noun: '물',
    rest: ' 맛있어요.',
    setId: 'topic-subject',
    familyIndex: 0,
    reason: L(
      'Already-mentioned info becomes the TOPIC → 은/는. 물 ends in a consonant → 은.',
      'Lo ya mencionado pasa a ser TEMA → 은/는. 물 termina en consonante → 은.',
      'Une info déjà mentionnée devient le THÈME → 은/는. 물 finit par consonne → 은.',
      'Info já mencionada vira TÓPICO → 은/는. 물 termina em consoante → 은.',
      'สิ่งที่พูดถึงแล้วกลายเป็นหัวเรื่อง → 은/는. 물 ลงท้ายพยัญชนะ → 은',
      'Info yang sudah disebut menjadi TOPIK → 은/는. 물 berakhir konsonan → 은.',
      'Thông tin đã nhắc trở thành CHỦ ĐỀ → 은/는. 물 kết thúc phụ âm → 은.',
      '既出の情報は主題になる → 은/는。물 は子音終わり → 은。',
    ),
    trans: L('The water is tasty.', 'El agua está rica.', 'L\'eau est bonne.', 'A água é gostosa.', 'น้ำอร่อย', 'Airnya enak.', 'Nước ngon.', 'その水はおいしいです。'),
  },
  {
    id: 'd11-horangi',
    cue: L('First mention in a story: "Once upon a time…".', 'Primera mención en un cuento: «Érase una vez…».', 'Première mention dans un conte : « Il était une fois… ».', 'Primeira menção num conto: "Era uma vez…".', 'การกล่าวถึงครั้งแรกในนิทาน: "กาลครั้งหนึ่ง…"', 'Penyebutan pertama dalam dongeng: "Pada zaman dahulu…".', 'Lần đầu nhắc đến trong truyện: "Ngày xửa ngày xưa…".', '物語の初登場：「昔々…」。'),
    lead: '옛날에 ',
    noun: '호랑이',
    rest: ' 살았어요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'First mention of a character = brand-new info → 이/가. (Later mentions switch to 은/는.)',
      'La primera mención de un personaje = info totalmente nueva → 이/가. (Las siguientes cambian a 은/는.)',
      'La première mention d\'un personnage = info toute nouvelle → 이/가. (Ensuite on passe à 은/는.)',
      'A primeira menção de um personagem = info nova → 이/가. (Depois muda para 은/는.)',
      'การแนะนำตัวละครครั้งแรก = ข้อมูลใหม่ → 이/가 (ครั้งถัดไปเปลี่ยนเป็น 은/는)',
      'Penyebutan pertama tokoh = info baru → 이/가. (Selanjutnya beralih ke 은/는.)',
      'Nhân vật xuất hiện lần đầu = thông tin hoàn toàn mới → 이/가. (Các lần sau chuyển sang 은/는.)',
      '登場人物の初出は完全な新情報 → 이/가。（以後は 은/는 に切り替わる。）',
    ),
    trans: L('Once upon a time there lived a tiger.', 'Érase una vez un tigre que vivía allí.', 'Il était une fois un tigre qui vivait là.', 'Era uma vez um tigre que ali vivia.', 'กาลครั้งหนึ่งมีเสือตัวหนึ่งอาศัยอยู่', 'Pada zaman dahulu hiduplah seekor harimau.', 'Ngày xưa có một con hổ sinh sống.', '昔々、トラが住んでいました。'),
  },
  {
    id: 'd12-kokkiri',
    cue: L('You highlight the elephant\'s NOSE (the elephant is already the topic).', 'Destacas la NARIZ del elefante (el elefante ya es el tema).', 'Tu mets en relief la TROMPE de l\'éléphant (l\'éléphant est déjà le thème).', 'Você destaca a TROMBA do elefante (o elefante já é o tópico).', 'คุณเน้นจมูกของช้าง (ช้างเป็นหัวเรื่องอยู่แล้ว)', 'Kamu menonjolkan HIDUNG gajah (gajah sudah jadi topik).', 'Bạn nhấn mạnh cái MŨI của con voi (voi đã là chủ đề).', '象の鼻を際立たせる（象はすでに主題）。'),
    lead: '코끼리는 ',
    noun: '코',
    rest: ' 길어요.',
    setId: 'topic-subject',
    familyIndex: 1,
    reason: L(
      'Classic double pattern: topic with 는 + highlighted feature with 가. "As for elephants, the NOSE is long."',
      'Patrón doble clásico: tema con 는 + rasgo destacado con 가. "El elefante, la NARIZ la tiene larga."',
      'Double construction classique : thème en 는 + trait saillant en 가. « L\'éléphant, c\'est la TROMPE qui est longue. »',
      'Padrão duplo clássico: tópico com 는 + traço destacado com 가. "O elefante, o NARIZ é longo."',
      'โครงสร้างคู่คลาสสิก: หัวเรื่องใช้ 는 + ลักษณะเด่นใช้ 가 "ช้างน่ะ จมูกยาว"',
      'Pola ganda klasik: topik dengan 는 + ciri yang ditonjolkan dengan 가. "Gajah itu, HIDUNGNYA panjang."',
      'Mẫu kép kinh điển: chủ đề với 는 + đặc điểm nổi bật với 가. "Con voi thì cái MŨI dài."',
      '典型的な二重構文：主題は 는、際立たせる特徴は 가。「象は鼻が長い」。',
    ),
    trans: L('Elephants have long noses. (lit. "as for elephants, the nose is long")', 'El elefante tiene la nariz larga. (lit. «el elefante, la nariz es larga»)', 'L\'éléphant a une longue trompe. (litt. « l\'éléphant, la trompe est longue »)', 'O elefante tem a tromba longa. (lit. "o elefante, o nariz é longo")', 'ช้างจมูกยาว', 'Gajah hidungnya panjang.', 'Voi có cái mũi dài.', '象は鼻が長いです。'),
  },
]
