import type { LabSentence } from '~/lib/domain'
import { L } from './locale'

/**
 * Explore-mode corpus. TOPIK 1 vocabulary only. Combos of two OFF particles
 * intentionally have no explicit reading — the resolver falls back to the
 * base translation + the generic "telegram style" nuance (i18n key).
 */
export const PARTICLE_SENTENCES: LabSentence[] = [
  {
    id: 's01-jeoneun',
    eojeols: [
      [
        {
          kind: 'word',
          text: '저',
          gloss: L('I (humble)', 'yo', 'je', 'eu', 'ฉัน', 'saya', 'tôi', '私'),
        },
        { kind: 'particle', text: '는', particleId: 'topic', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '학생이에요',
          gloss: L(
            'am a student',
            'soy estudiante',
            'suis étudiant·e',
            'sou estudante',
            'เป็นนักเรียน',
            'adalah pelajar',
            'là học sinh',
            '学生です',
          ),
        },
      ],
    ],
    trans: L(
      'I am a student.',
      'Yo soy estudiante.',
      'Je suis étudiant·e.',
      'Eu sou estudante.',
      'ฉันเป็นนักเรียน',
      'Saya pelajar.',
      'Tôi là học sinh.',
      '私は学生です。',
    ),
    nuance: L(
      '는 presents the topic: "as for me…". Standard when introducing yourself.',
      '는 presenta el tema: "en cuanto a mí…". Lo normal al presentarte.',
      '는 présente le thème : « quant à moi… ». Habituel pour se présenter.',
      '는 apresenta o tópico: "quanto a mim…". O normal ao se apresentar.',
      '는 บอกหัวเรื่อง: "สำหรับฉัน…" ใช้ตอนแนะนำตัว',
      '는 memperkenalkan topik: "mengenai saya…". Wajar saat memperkenalkan diri.',
      '는 nêu chủ đề: "về phần tôi…". Chuẩn khi tự giới thiệu.',
      '는 は主題を提示（「私について言えば」）。自己紹介の定番。',
    ),
    readings: [
      {
        off: ['topic'],
        trans: L(
          "I'm a student. (casual)",
          'Soy estudiante. (coloquial)',
          'Je suis étudiant·e. (familier)',
          'Sou estudante. (casual)',
          'เป็นนักเรียน (กันเอง)',
          'Saya pelajar. (santai)',
          'Tôi là học sinh. (thân mật)',
          '学生です。（くだけた言い方）',
        ),
        nuance: L(
          "Dropping 는 sounds direct and casual — fine when it's obvious you mean yourself.",
          'Sin 는 suena directo y casual — normal si ya está claro que hablas de ti.',
          "Sans 는, c'est direct et familier — naturel si on sait que tu parles de toi.",
          'Sem 는 soa direto e casual — normal se já está claro que fala de você.',
          'ตัด 는 ฟังดูตรงและเป็นกันเอง — ใช้ได้เมื่อรู้อยู่แล้วว่าพูดถึงตัวเอง',
          'Tanpa 는 terdengar langsung dan santai — wajar bila jelas membicarakan dirimu.',
          'Bỏ 는 nghe trực tiếp và thân mật — ổn khi đã rõ bạn nói về mình.',
          '는 を落とすと直接的でくだけた響き。自分の話だと明らかなら自然。',
        ),
      },
    ],
  },
  {
    id: 's02-goyangi',
    eojeols: [
      [
        {
          kind: 'word',
          text: '고양이',
          gloss: L('cat', 'gato', 'chat', 'gato', 'แมว', 'kucing', 'con mèo', '猫'),
        },
        { kind: 'particle', text: '가', particleId: 'subject', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '우유',
          gloss: L('milk', 'leche', 'lait', 'leite', 'นม', 'susu', 'sữa', '牛乳'),
        },
        { kind: 'particle', text: '를', particleId: 'object', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '마셔요',
          gloss: L('drinks', 'bebe', 'boit', 'bebe', 'ดื่ม', 'minum', 'uống', '飲みます'),
        },
      ],
    ],
    trans: L(
      'The cat drinks milk.',
      'El gato bebe leche.',
      'Le chat boit du lait.',
      'O gato bebe leite.',
      'แมวดื่มนม',
      'Kucing minum susu.',
      'Con mèo uống sữa.',
      '猫が牛乳を飲みます。',
    ),
    nuance: L(
      '가 highlights WHO drinks; 를 marks WHAT gets drunk.',
      '가 destaca QUIÉN bebe; 를 marca QUÉ es lo bebido.',
      '가 met en relief QUI boit ; 를 marque CE QUI est bu.',
      '가 destaca QUEM bebe; 를 marca O QUE é bebido.',
      '가 เน้นว่าใครดื่ม; 를 บอกว่าดื่มอะไร',
      '가 menonjolkan SIAPA yang minum; 를 menandai APA yang diminum.',
      '가 làm nổi bật AI uống; 를 đánh dấu uống CÁI GÌ.',
      '가 は「誰が」を、를 は「何を」を示す。',
    ),
    readings: [
      {
        off: ['subject'],
        trans: L(
          'The cat drinks milk. (casual)',
          'El gato bebe leche. (coloquial)',
          'Le chat boit du lait. (familier)',
          'O gato bebe leite. (casual)',
          'แมวดื่มนม (กันเอง)',
          'Kucing minum susu. (santai)',
          'Con mèo uống sữa. (thân mật)',
          '猫、牛乳を飲みます。（くだけた）',
        ),
        nuance: L(
          'Without 가 the role comes from word order alone — casual but clear here.',
          'Sin 가 el rol se deduce solo del orden — casual pero claro aquí.',
          "Sans 가, le rôle vient de l'ordre des mots — familier mais clair ici.",
          'Sem 가 o papel vem só da ordem — casual mas claro aqui.',
          'ไม่มี 가 ต้องเดาบทบาทจากลำดับคำ — กันเองแต่ยังชัด',
          'Tanpa 가 peran ditebak dari urutan kata — santai tapi masih jelas.',
          'Không có 가, vai trò suy từ trật tự từ — thân mật nhưng vẫn rõ.',
          '가 がないと役割は語順頼み。くだけているがここでは明確。',
        ),
      },
      {
        off: ['object'],
        trans: L(
          'The cat drinks milk. (casual)',
          'El gato bebe leche. (coloquial)',
          'Le chat boit du lait. (familier)',
          'O gato bebe leite. (casual)',
          'แมวดื่มนม (กันเอง)',
          'Kucing minum susu. (santai)',
          'Con mèo uống sữa. (thân mật)',
          '猫が牛乳、飲みます。（くだけた）',
        ),
        nuance: L(
          'Dropping 를 is THE most common omission in real speech.',
          'Omitir 를 es LA omisión más común en el habla real.',
          "Omettre 를 est L'omission la plus courante à l'oral.",
          'Omitir 를 é A omissão mais comum na fala real.',
          'การตัด 를 คือการละที่พบบ่อยที่สุดในภาษาพูดจริง',
          'Melepas 를 adalah pelesapan PALING umum dalam percakapan nyata.',
          'Bỏ 를 là kiểu lược phổ biến NHẤT trong khẩu ngữ.',
          '를 の省略は実際の会話で最も多い省略。',
        ),
      },
    ],
  },
  {
    id: 's03-hakgyo',
    eojeols: [
      [
        {
          kind: 'word',
          text: '학교',
          gloss: L('school', 'escuela', 'école', 'escola', 'โรงเรียน', 'sekolah', 'trường', '学校'),
        },
        { kind: 'particle', text: '에', particleId: 'place-static', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '가요',
          gloss: L('go', 'voy', 'vais', 'vou', 'ไป', 'pergi', 'đi', '行きます'),
        },
      ],
    ],
    trans: L(
      "I'm going to school.",
      'Voy a la escuela.',
      "Je vais à l'école.",
      'Vou para a escola.',
      'ฉันไปโรงเรียน',
      'Saya pergi ke sekolah.',
      'Tôi đi đến trường.',
      '学校に行きます。',
    ),
    nuance: L(
      '에 marks the destination of the movement.',
      '에 marca el destino del movimiento.',
      '에 marque la destination du déplacement.',
      '에 marca o destino do movimento.',
      '에 บอกปลายทางของการเคลื่อนที่',
      '에 menandai tujuan pergerakan.',
      '에 đánh dấu đích đến của chuyển động.',
      '에 は移動の到達点を示す。',
    ),
    readings: [
      {
        off: ['place-static'],
        trans: L(
          "I'm going to school. (casual)",
          'Voy a la escuela. (coloquial)',
          "Je vais à l'école. (familier)",
          'Vou para a escola. (casual)',
          'ไปโรงเรียน (กันเอง)',
          'Pergi ke sekolah. (santai)',
          'Đi học đây. (thân mật)',
          '学校行きます。（くだけた）',
        ),
        nuance: L(
          '«학교 가요» is everyday speech — the destination is understood.',
          '«학교 가요» es habitual hablando: el destino se sobreentiende.',
          "« 학교 가요 » est courant à l'oral : la destination va de soi.",
          '«학교 가요» é comum na fala: o destino fica subentendido.',
          '«학교 가요» พูดกันทั่วไป — ปลายทางเข้าใจได้เอง',
          '«학교 가요» lazim diucapkan — tujuannya sudah dipahami.',
          '«학교 가요» rất thường gặp khi nói — đích đến tự hiểu.',
          '「학교 가요」は日常会話で普通。行き先は文脈で分かる。',
        ),
      },
    ],
  },
  {
    id: 's04-doseogwan',
    eojeols: [
      [
        {
          kind: 'word',
          text: '도서관',
          gloss: L(
            'library',
            'biblioteca',
            'bibliothèque',
            'biblioteca',
            'ห้องสมุด',
            'perpustakaan',
            'thư viện',
            '図書館',
          ),
        },
        { kind: 'particle', text: '에서', particleId: 'place-action', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '공부해요',
          gloss: L('study', 'estudio', 'étudie', 'estudo', 'เรียน', 'belajar', 'học', '勉強します'),
        },
      ],
    ],
    trans: L(
      'I study at the library.',
      'Estudio en la biblioteca.',
      "J'étudie à la bibliothèque.",
      'Estudo na biblioteca.',
      'ฉันเรียนที่ห้องสมุด',
      'Saya belajar di perpustakaan.',
      'Tôi học ở thư viện.',
      '図書館で勉強します。',
    ),
    nuance: L(
      '에서 = where the action HAPPENS. Compare with 에 (static place / destination).',
      '에서 = lugar donde OCURRE la acción. Compárala con 에 (lugar estático / destino).',
      "에서 = lieu où l'action SE PASSE. À comparer avec 에 (lieu statique / destination).",
      '에서 = onde a ação ACONTECE. Compare com 에 (lugar estático / destino).',
      '에서 = ที่ที่การกระทำเกิดขึ้น เทียบกับ 에 (สถานที่คงที่/ปลายทาง)',
      '에서 = tempat aksi TERJADI. Bandingkan dengan 에 (tempat statis / tujuan).',
      '에서 = nơi hành động DIỄN RA. So sánh với 에 (vị trí tĩnh / đích đến).',
      '에서 は動作が行われる場所。에（静的な場所・到達点）と比較せよ。',
    ),
    readings: [
      {
        off: ['place-action'],
        trans: L(
          'I study… library? (sounds incomplete)',
          'Estudio… ¿biblioteca? (suena incompleto)',
          "J'étudie… bibliothèque ? (incomplet)",
          'Estudo… biblioteca? (soa incompleto)',
          'เรียน…ห้องสมุด? (ฟังดูไม่ครบ)',
          'Belajar… perpustakaan? (terasa janggal)',
          'Học… thư viện? (nghe thiếu)',
          '勉強します…図書館？（不完全に聞こえる）',
        ),
        nuance: L(
          '에서 is rarely dropped: without it the sentence loses its "where".',
          '에서 casi nunca se omite: sin ella la frase pierde el "dónde".',
          "에서 s'omet rarement : sans elle, la phrase perd son « où ».",
          '에서 quase nunca cai: sem ela a frase perde o "onde".',
          '에서 แทบไม่ถูกตัด: ถ้าไม่มีประโยคจะขาด "ที่ไหน"',
          '에서 jarang dilepas: tanpanya kalimat kehilangan "di mana"-nya.',
          '에서 hiếm khi bị lược: thiếu nó câu mất nghĩa "ở đâu".',
          '에서 はめったに省略されない。ないと「どこで」が失われる。',
        ),
      },
    ],
  },
  {
    id: 's05-jeodo',
    eojeols: [
      [
        {
          kind: 'word',
          text: '저',
          gloss: L('I (humble)', 'yo', 'je', 'eu', 'ฉัน', 'saya', 'tôi', '私'),
        },
        { kind: 'particle', text: '도', particleId: 'also', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '커피',
          gloss: L('coffee', 'café', 'café', 'café', 'กาแฟ', 'kopi', 'cà phê', 'コーヒー'),
        },
        { kind: 'particle', text: '를', particleId: 'object', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '좋아해요',
          gloss: L('like', 'me gusta', 'aime', 'gosto', 'ชอบ', 'suka', 'thích', '好きです'),
        },
      ],
    ],
    trans: L(
      'I like coffee too.',
      'A mí también me gusta el café.',
      "Moi aussi j'aime le café.",
      'Eu também gosto de café.',
      'ฉันก็ชอบกาแฟด้วย',
      'Saya juga suka kopi.',
      'Tôi cũng thích cà phê.',
      '私もコーヒーが好きです。',
    ),
    nuance: L(
      '도 REPLACES 은/는 — never 저는도. One slot, one particle.',
      '도 REEMPLAZA a 은/는 — nunca 저는도. Un hueco, una partícula.',
      '도 REMPLACE 은/는 — jamais 저는도. Une place, une particule.',
      '도 SUBSTITUI 은/는 — nunca 저는도. Um espaço, uma partícula.',
      '도 ใช้แทน 은/는 — ห้าม 저는도 ช่องเดียว อนุภาคเดียว',
      '도 MENGGANTIKAN 은/는 — jangan 저는도. Satu slot, satu partikel.',
      '도 THAY THẾ 은/는 — không bao giờ 저는도. Một vị trí, một tiểu từ.',
      '도 は 은/는 と置き換わる（저는도 は誤り）。一つの枠に一つの助詞。',
    ),
    readings: [
      {
        off: ['also'],
        trans: L(
          'I like coffee.',
          'Me gusta el café.',
          "J'aime le café.",
          'Gosto de café.',
          'ฉันชอบกาแฟ',
          'Saya suka kopi.',
          'Tôi thích cà phê.',
          '私、コーヒーが好きです。',
        ),
        nuance: L(
          'Without 도 you lose the "too". To mark plain topic you\'d say 저는.',
          'Sin 도 pierdes el "también". Para marcar tema normal dirías 저는.',
          'Sans 도, tu perds le « aussi ». Pour un simple thème : 저는.',
          'Sem 도 você perde o "também". Para tópico normal seria 저는.',
          'ไม่มี 도 จะเสียความหมาย "ด้วย" ถ้าจะบอกหัวเรื่องปกติใช้ 저는',
          'Tanpa 도 makna "juga" hilang. Untuk topik biasa pakai 저는.',
          'Không có 도 thì mất nghĩa "cũng". Đánh dấu chủ đề thường thì dùng 저는.',
          '도 がないと「も」が消える。普通の主題なら 저는 と言う。',
        ),
      },
      {
        off: ['object'],
        trans: L(
          'I like coffee too. (casual)',
          'A mí también me gusta el café. (coloquial)',
          "Moi aussi j'aime le café. (familier)",
          'Eu também gosto de café. (casual)',
          'ฉันก็ชอบกาแฟ (กันเอง)',
          'Saya juga suka kopi. (santai)',
          'Tôi cũng thích cà phê. (thân mật)',
          '私もコーヒー、好きです。（くだけた）',
        ),
        nuance: L(
          'Dropping 를 here is completely natural in speech.',
          'Omitir 를 aquí es naturalísimo al hablar.',
          "Omettre 를 ici est tout à fait naturel à l'oral.",
          'Omitir 를 aqui é super natural na fala.',
          'ตัด 를 ตรงนี้เป็นธรรมชาติมากในภาษาพูด',
          'Melepas 를 di sini sangat alami saat bicara.',
          'Bỏ 를 ở đây hoàn toàn tự nhiên khi nói.',
          'ここで 를 を落とすのは会話では完全に自然。',
        ),
      },
    ],
  },
  {
    id: 's06-achime',
    eojeols: [
      [
        {
          kind: 'word',
          text: '아침',
          gloss: L('morning', 'mañana', 'matin', 'manhã', 'เช้า', 'pagi', 'buổi sáng', '朝'),
        },
        { kind: 'particle', text: '에', particleId: 'place-static', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '빵',
          gloss: L('bread', 'pan', 'pain', 'pão', 'ขนมปัง', 'roti', 'bánh mì', 'パン'),
        },
        { kind: 'particle', text: '을', particleId: 'object', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '먹어요',
          gloss: L('eat', 'como', 'mange', 'como', 'กิน', 'makan', 'ăn', '食べます'),
        },
      ],
    ],
    trans: L(
      'In the morning I eat bread.',
      'Por la mañana como pan.',
      'Le matin, je mange du pain.',
      'De manhã eu como pão.',
      'ตอนเช้าฉันกินขนมปัง',
      'Pagi hari saya makan roti.',
      'Buổi sáng tôi ăn bánh mì.',
      '朝、パンを食べます。',
    ),
    nuance: L(
      '에 also marks TIME: 아침에 = "in the morning". Note 빵 takes 을 (ends in consonant).',
      '에 también marca TIEMPO: 아침에 = "por la mañana". Fíjate: 빵 lleva 을 (termina en consonante).',
      '에 marque aussi le TEMPS : 아침에 = « le matin ». Note : 빵 prend 을 (finit par consonne).',
      '에 também marca TEMPO: 아침에 = "de manhã". Note: 빵 leva 을 (termina em consoante).',
      '에 ใช้บอกเวลาได้ด้วย: 아침에 = "ตอนเช้า" สังเกต 빵 ใช้ 을 (ลงท้ายพยัญชนะ)',
      '에 juga menandai WAKTU: 아침에 = "pagi hari". Catat: 빵 pakai 을 (akhiran konsonan).',
      '에 còn đánh dấu THỜI GIAN: 아침에 = "vào buổi sáng". Lưu ý: 빵 lấy 을 (kết thúc phụ âm).',
      '에 は時も示す：아침에＝「朝に」。빵 は子音終わりなので 을。',
    ),
    readings: [
      {
        off: ['place-static'],
        trans: L(
          'I eat morning-bread(?) — ambiguous',
          'Como pan de mañana(?) — ambiguo',
          'Je mange du pain du matin(?) — ambigu',
          'Como pão da manhã(?) — ambíguo',
          'กิน "ขนมปังตอนเช้า"(?) — กำกวม',
          'Makan roti pagi(?) — ambigu',
          'Ăn "bánh mì buổi sáng"(?) — mơ hồ',
          '「朝パン」を食べる？ — 曖昧',
        ),
        nuance: L(
          'Without 에, «아침 빵» can read as a compound ("breakfast bread"). The particle disambiguates.',
          'Sin 에, «아침 빵» puede leerse como compuesto ("pan de desayuno"). La partícula desambigua.',
          "Sans 에, « 아침 빵 » peut se lire comme un composé (« pain du matin »). La particule lève l'ambiguïté.",
          'Sem 에, «아침 빵» pode virar composto ("pão de café da manhã"). A partícula desambigua.',
          'ถ้าไม่มี 에, «아침 빵» อาจกลายเป็นคำประสม ("ขนมปังเช้า") อนุภาคช่วยให้ชัด',
          'Tanpa 에, «아침 빵» bisa terbaca sebagai kata majemuk ("roti pagi"). Partikel menghilangkan ambiguitas.',
          'Không có 에, «아침 빵» có thể hiểu thành từ ghép ("bánh mì sáng"). Tiểu từ giúp rõ nghĩa.',
          '에 がないと「아침 빵」は複合語（朝のパン）にも読める。助詞が曖昧さを消す。',
        ),
      },
      {
        off: ['object'],
        trans: L(
          'In the morning I eat bread. (casual)',
          'Por la mañana como pan. (coloquial)',
          'Le matin, je mange du pain. (familier)',
          'De manhã como pão. (casual)',
          'ตอนเช้ากินขนมปัง (กันเอง)',
          'Pagi hari makan roti. (santai)',
          'Buổi sáng ăn bánh mì. (thân mật)',
          '朝、パン食べます。（くだけた）',
        ),
        nuance: L(
          'Casual and very common — the object is obvious.',
          'Casual y muy común — el objeto es obvio.',
          "Familier et très courant — l'objet est évident.",
          'Casual e muito comum — o objeto é óbvio.',
          'กันเองและพบบ่อยมาก — กรรมชัดเจนอยู่แล้ว',
          'Santai dan sangat umum — objeknya sudah jelas.',
          'Thân mật và rất phổ biến — tân ngữ đã rõ.',
          'くだけた言い方で非常によくある。目的語は明白。',
        ),
      },
    ],
  },
  {
    id: 's07-biga',
    eojeols: [
      [
        {
          kind: 'word',
          text: '비',
          gloss: L('rain', 'lluvia', 'pluie', 'chuva', 'ฝน', 'hujan', 'mưa', '雨'),
        },
        { kind: 'particle', text: '가', particleId: 'subject', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '와요',
          gloss: L('comes', 'viene', 'vient', 'vem', 'มา', 'datang', 'đến', '来ます'),
        },
      ],
    ],
    trans: L(
      'It\'s raining. (lit. "rain comes")',
      'Está lloviendo. (lit. «la lluvia viene»)',
      'Il pleut. (litt. « la pluie vient »)',
      'Está chovendo. (lit. "a chuva vem")',
      'ฝนกำลังตก (ตรงตัว: "ฝนมา")',
      'Sedang hujan. (harfiah: "hujan datang")',
      'Trời đang mưa. (nghĩa đen: "mưa đến")',
      '雨が降っています。（直訳「雨が来る」）',
    ),
    nuance: L(
      'Weather "shows up" as new info → always 가, never 는 here.',
      'El clima "aparece" como info nueva → siempre 가, nunca 는 aquí.',
      'La météo « surgit » comme info nouvelle → toujours 가, jamais 는 ici.',
      'O clima "surge" como info nova → sempre 가, nunca 는 aqui.',
      'สภาพอากาศ "โผล่มา" เป็นข้อมูลใหม่ → ใช้ 가 เสมอ ไม่ใช่ 는',
      'Cuaca "muncul" sebagai info baru → selalu 가, bukan 는 di sini.',
      'Thời tiết "xuất hiện" như thông tin mới → luôn là 가, không phải 는.',
      '天気は新情報として「現れる」→ ここでは常に 가。는 は不可。',
    ),
    readings: [
      {
        off: ['subject'],
        trans: L(
          "It's raining. (very casual)",
          'Está lloviendo. (muy coloquial)',
          'Il pleut. (très familier)',
          'Está chovendo. (bem casual)',
          'ฝนตก (กันเองมาก)',
          'Hujan. (sangat santai)',
          'Mưa rồi. (rất thân mật)',
          '雨、降ってます。（とてもくだけた）',
        ),
        nuance: L(
          '«비 와요» is everyday talk. But careful: «비는 와요» would sound contrastive ("as for rain, it IS raining, but…").',
          '«비 와요» se dice a diario. Ojo: «비는 와요» sonaría a contraste ("llover, llueve… pero").',
          '« 비 와요 » est du quotidien. Attention : « 비는 와요 » sonnerait contrastif (« pleuvoir, il pleut… mais »).',
          '«비 와요» é fala do dia a dia. Cuidado: «비는 와요» soaria contrastivo ("chover, chove… mas").',
          '«비 와요» พูดกันทุกวัน ระวัง: «비는 와요» จะกลายเป็นเชิงเปรียบต่าง ("ฝนน่ะตก…แต่")',
          '«비 와요» bahasa sehari-hari. Hati-hati: «비는 와요» terdengar kontras ("hujan sih hujan… tapi").',
          '«비 와요» là cách nói hằng ngày. Cẩn thận: «비는 와요» nghe như đối chiếu ("mưa thì có mưa… nhưng").',
          '「비 와요」は日常語。ただし「비는 와요」だと対比（「雨は降るが…」）に聞こえる。',
        ),
      },
    ],
  },
  {
    id: 's08-chinguhante',
    eojeols: [
      [
        {
          kind: 'word',
          text: '친구',
          gloss: L('friend', 'amigo', 'ami', 'amigo', 'เพื่อน', 'teman', 'bạn', '友達'),
        },
        { kind: 'particle', text: '한테', particleId: 'recipient', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '편지',
          gloss: L('letter', 'carta', 'lettre', 'carta', 'จดหมาย', 'surat', 'lá thư', '手紙'),
        },
        { kind: 'particle', text: '를', particleId: 'object', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '써요',
          gloss: L('write', 'escribo', 'écris', 'escrevo', 'เขียน', 'menulis', 'viết', '書きます'),
        },
      ],
    ],
    trans: L(
      'I write a letter to a friend.',
      'Le escribo una carta a un amigo.',
      "J'écris une lettre à un ami.",
      'Escrevo uma carta para um amigo.',
      'ฉันเขียนจดหมายถึงเพื่อน',
      'Saya menulis surat kepada teman.',
      'Tôi viết thư cho một người bạn.',
      '友達に手紙を書きます。',
    ),
    nuance: L(
      '한테 marks the receiver — 친구 is who the letter goes to; 를 marks 편지 as what gets written.',
      '한테 marca al receptor — 친구 es a quien va la carta; 를 marca 편지 como lo que se escribe.',
      "한테 marque le destinataire — 친구 est à qui va la lettre ; 를 marque 편지 comme ce qu'on écrit.",
      '한테 marca o receptor — 친구 é para quem vai a carta; 를 marca 편지 como o que se escreve.',
      '한테 บอกผู้รับ — 친구 คือคนที่จดหมายไปถึง; 를 บอกว่า 편지 คือสิ่งที่เขียน',
      '한테 menandai penerima — 친구 tujuan suratnya; 를 menandai 편지 sebagai yang ditulis.',
      '한테 đánh dấu người nhận — 친구 là nơi lá thư gửi đến; 를 đánh dấu 편지 là thứ được viết.',
      '한테 は受け手を示す — 친구 は手紙の宛先。를 は 편지 を「書く対象」として示す。',
    ),
    readings: [
      {
        off: ['recipient'],
        trans: L(
          "I write a friend's letter? — ambiguous",
          '¿Escribo la carta de un amigo? — ambiguo',
          "J'écris la lettre d'un ami ? — ambigu",
          'Escrevo a carta de um amigo? — ambíguo',
          'เขียน "จดหมายของเพื่อน"? — กำกวม',
          'Menulis "surat teman"? — ambigu',
          'Viết "lá thư của bạn"? — mơ hồ',
          '「友達の手紙」を書く？ — 曖昧',
        ),
        nuance: L(
          'Without 한테, 친구 편지 reads as "(the) friend\'s letter" (친구의 편지) — the particle is what makes 친구 the recipient.',
          'Sin 한테, 친구 편지 se lee como "la carta del amigo" (친구의 편지) — la partícula es lo que hace de 친구 el destinatario.',
          "Sans 한테, 친구 편지 se lit « la lettre de l'ami » (친구의 편지) — c'est la particule qui fait de 친구 le destinataire.",
          'Sem 한테, 친구 편지 lê-se como "a carta do amigo" (친구의 편지) — a partícula é o que torna 친구 o destinatário.',
          'ถ้าไม่มี 한테, 친구 편지 จะอ่านเป็น "จดหมายของเพื่อน" (친구의 편지) อนุภาคคือสิ่งที่ทำให้ 친구 เป็นผู้รับ',
          'Tanpa 한테, 친구 편지 terbaca "surat teman" (친구의 편지) — partikel itulah yang menjadikan 친구 penerima.',
          'Không có 한테, 친구 편지 đọc thành "lá thư của bạn" (친구의 편지) — tiểu từ mới biến 친구 thành người nhận.',
          '한테 がないと 친구 편지 は「友達の手紙」（친구의 편지）と読める。助詞が 친구 を受け手にする。',
        ),
      },
      {
        off: ['object'],
        trans: L(
          'I write a letter to a friend. (casual)',
          'Le escribo una carta a un amigo. (coloquial)',
          "J'écris une lettre à un ami. (familier)",
          'Escrevo uma carta para um amigo. (casual)',
          'เขียนจดหมายถึงเพื่อน (กันเอง)',
          'Menulis surat ke teman. (santai)',
          'Viết thư cho bạn. (thân mật)',
          '友達に手紙、書きます。（くだけた）',
        ),
        nuance: L(
          'Dropping 를 is natural in speech — 편지 is obviously what gets written.',
          'Omitir 를 es natural al hablar — está claro que 편지 es lo que se escribe.',
          "Omettre 를 est naturel à l'oral — 편지 est évidemment ce qu'on écrit.",
          'Omitir 를 é natural na fala — 편지 é claramente o que se escreve.',
          'การตัด 를 เป็นธรรมชาติในภาษาพูด — รู้อยู่แล้วว่า 편지 คือสิ่งที่เขียน',
          'Melepas 를 wajar saat bicara — jelas 편지 yang ditulis.',
          'Bỏ 를 là tự nhiên khi nói — rõ ràng 편지 là thứ được viết.',
          '를 を落とすのは会話で自然 — 편지 が書く対象なのは明白。',
        ),
      },
    ],
  },
  {
    id: 's09-beoseuro',
    eojeols: [
      [
        {
          kind: 'word',
          text: '버스',
          gloss: L('bus', 'autobús', 'bus', 'ônibus', 'รถบัส', 'bus', 'xe buýt', 'バス'),
        },
        { kind: 'particle', text: '로', particleId: 'by-means', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '학교',
          gloss: L('school', 'escuela', 'école', 'escola', 'โรงเรียน', 'sekolah', 'trường', '学校'),
        },
        { kind: 'particle', text: '에', particleId: 'place-static', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '가요',
          gloss: L('go', 'voy', 'vais', 'vou', 'ไป', 'pergi', 'đi', '行きます'),
        },
      ],
    ],
    trans: L(
      'I go to school by bus.',
      'Voy a la escuela en autobús.',
      "Je vais à l'école en bus.",
      'Vou para a escola de ônibus.',
      'ฉันไปโรงเรียนโดยรถบัส',
      'Saya pergi ke sekolah naik bus.',
      'Tôi đi học bằng xe buýt.',
      'バスで学校に行きます。',
    ),
    nuance: L(
      '로 = the means (how you go: by bus); 에 = the destination (where to: school).',
      '로 = el medio (cómo vas: en autobús); 에 = el destino (adónde: la escuela).',
      "로 = le moyen (comment : en bus) ; 에 = la destination (où : l'école).",
      '로 = o meio (como você vai: de ônibus); 에 = o destino (para onde: a escola).',
      '로 = วิธี (ไปยังไง: รถบัส); 에 = ปลายทาง (ไปไหน: โรงเรียน)',
      '로 = cara (naik apa: bus); 에 = tujuan (ke mana: sekolah).',
      '로 = phương tiện (đi bằng gì: xe buýt); 에 = đích đến (đi đâu: trường).',
      '로 は手段（どうやって：バスで）、에 は到達点（どこへ：学校）。',
    ),
    readings: [
      {
        off: ['by-means'],
        trans: L(
          'I go to school… bus? (role unclear)',
          'Voy a la escuela… ¿autobús? (rol poco claro)',
          "Je vais à l'école… bus ? (rôle flou)",
          'Vou para a escola… ônibus? (papel pouco claro)',
          'ไปโรงเรียน…รถบัส? (บทบาทไม่ชัด)',
          'Pergi ke sekolah… bus? (peran kabur)',
          'Đi học… xe buýt? (vai trò không rõ)',
          '学校に行きます…バス？（役割が不明）',
        ),
        nuance: L(
          'Without 로, 버스 floats with no role — 로 is what says "by bus". It\'s rarely dropped.',
          'Sin 로, 버스 queda sin rol — 로 es lo que dice "en autobús". Casi no se omite.',
          "Sans 로, 버스 reste sans rôle — c'est 로 qui dit « en bus ». On l'omet rarement.",
          'Sem 로, 버스 fica sem papel — 로 é o que diz "de ônibus". Raramente cai.',
          'ถ้าไม่มี 로, 버스 ไม่มีบทบาท — 로 คือสิ่งที่บอกว่า "โดยรถบัส" แทบไม่ถูกตัด',
          'Tanpa 로, 버스 tak punya peran — 로 yang menyatakan "naik bus". Jarang dilepas.',
          'Không có 로, 버스 chẳng có vai trò — 로 mới nói "bằng xe buýt". Hiếm khi bị bỏ.',
          '로 がないと 버스 は役割を失う — 로 が「バスで」を表す。省略はまれ。',
        ),
      },
      {
        off: ['place-static'],
        trans: L(
          'I go to school by bus. (casual)',
          'Voy a la escuela en autobús. (coloquial)',
          "Je vais à l'école en bus. (familier)",
          'Vou para a escola de ônibus. (casual)',
          'ไปโรงเรียนโดยรถบัส (กันเอง)',
          'Naik bus ke sekolah. (santai)',
          'Đi học bằng xe buýt. (thân mật)',
          'バスで学校、行きます。（くだけた）',
        ),
        nuance: L(
          'Dropping 에 is everyday speech — the destination 학교 is understood (cf. 학교 가요).',
          'Omitir 에 es habla cotidiana — el destino 학교 se sobreentiende (cf. 학교 가요).',
          'Omettre 에 relève du quotidien — la destination 학교 est sous-entendue (cf. 학교 가요).',
          'Omitir 에 é fala do dia a dia — o destino 학교 fica subentendido (cf. 학교 가요).',
          'การตัด 에 เป็นภาษาพูดทั่วไป — ปลายทาง 학교 เข้าใจได้เอง (เทียบ 학교 가요)',
          'Melepas 에 lazim dalam percakapan — tujuan 학교 sudah dipahami (bdk. 학교 가요).',
          'Bỏ 에 là lời nói thường ngày — đích đến 학교 tự hiểu (xem 학교 가요).',
          '에 を落とすのは日常会話 — 行き先 학교 は文脈で分かる（cf. 학교 가요）。',
        ),
      },
    ],
  },
  {
    id: 's10-ppangman',
    eojeols: [
      [
        {
          kind: 'word',
          text: '빵',
          gloss: L('bread', 'pan', 'pain', 'pão', 'ขนมปัง', 'roti', 'bánh mì', 'パン'),
        },
        { kind: 'particle', text: '만', particleId: 'only', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '먹어요',
          gloss: L('eat', 'como', 'mange', 'como', 'กิน', 'makan', 'ăn', '食べます'),
        },
      ],
    ],
    trans: L(
      'I eat only bread.',
      'Como solo pan.',
      'Je ne mange que du pain.',
      'Como só pão.',
      'ฉันกินแต่ขนมปัง',
      'Saya makan roti saja.',
      'Tôi chỉ ăn bánh mì.',
      'パンだけ食べます。',
    ),
    nuance: L(
      '만 = "only", and it replaces 은/는·이/가·을/를 — 빵만, never 빵을만. One thing, nothing else.',
      '만 = "solo", y reemplaza a 은/는·이/가·을/를 — 빵만, nunca 빵을만. Una cosa, nada más.',
      "만 = « seulement », et il remplace 은/는·이/가·을/를 — 빵만, jamais 빵을만. Une chose, rien d'autre.",
      '만 = "só", e substitui 은/는·이/가·을/를 — 빵만, nunca 빵을만. Uma coisa, nada mais.',
      '만 = "เท่านั้น" และใช้แทน 은/는·이/가·을/를 — 빵만 ไม่ใช่ 빵을만 สิ่งเดียว ไม่มีอื่น',
      '만 = "saja", menggantikan 은/는·이/가·을/를 — 빵만, bukan 빵을만. Satu hal, tak ada lain.',
      '만 = "chỉ", thay thế 은/는·이/가·을/를 — 빵만, không phải 빵을만. Một thứ, không gì khác.',
      '만＝「だけ」。은/는・이/가・을/를 と置き換わる — 빵만、빵을만 は誤り。一つだけ。',
    ),
    readings: [
      {
        off: ['only'],
        trans: L(
          'I eat bread.',
          'Como pan.',
          'Je mange du pain.',
          'Como pão.',
          'ฉันกินขนมปัง',
          'Saya makan roti.',
          'Tôi ăn bánh mì.',
          'パンを食べます。',
        ),
        nuance: L(
          'Without 만 you lose "only" — it\'s just "I eat bread". To mark a plain object you\'d say 빵을.',
          'Sin 만 pierdes el "solo" — queda "como pan". Para marcar objeto normal dirías 빵을.',
          "Sans 만, le « seulement » disparaît — ce n'est plus que « je mange du pain ». Pour un objet simple : 빵을.",
          'Sem 만 você perde o "só" — vira só "como pão". Para objeto normal seria 빵을.',
          'ไม่มี 만 จะเสีย "เท่านั้น" — เหลือแค่ "กินขนมปัง" ถ้าจะบอกกรรมปกติใช้ 빵을',
          'Tanpa 만, makna "saja" hilang — tinggal "makan roti". Untuk objek biasa pakai 빵을.',
          'Không có 만 thì mất "chỉ" — chỉ còn "ăn bánh mì". Đánh dấu tân ngữ thường thì dùng 빵을.',
          '만 がないと「だけ」が消え、「パンを食べます」に。普通の目的語なら 빵을。',
        ),
      },
    ],
  },
  {
    id: 's11-sagwawa',
    eojeols: [
      [
        {
          kind: 'word',
          text: '사과',
          gloss: L('apple', 'manzana', 'pomme', 'maçã', 'แอปเปิล', 'apel', 'táo', 'りんご'),
        },
        { kind: 'particle', text: '와', particleId: 'and', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '바나나',
          gloss: L('banana', 'plátano', 'banane', 'banana', 'กล้วย', 'pisang', 'chuối', 'バナナ'),
        },
        { kind: 'particle', text: '를', particleId: 'object', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '사요',
          gloss: L('buy', 'compro', 'achète', 'compro', 'ซื้อ', 'membeli', 'mua', '買います'),
        },
      ],
    ],
    trans: L(
      'I buy apples and bananas.',
      'Compro manzanas y plátanos.',
      "J'achète des pommes et des bananes.",
      'Compro maçãs e bananas.',
      'ฉันซื้อแอปเปิลและกล้วย',
      'Saya membeli apel dan pisang.',
      'Tôi mua táo và chuối.',
      'りんごとバナナを買います。',
    ),
    nuance: L(
      '와 joins the two nouns. 사과 ends in a vowel → 와 (과 after a consonant). Written tone; speech prefers 사과하고/사과랑.',
      '와 une los dos sustantivos. 사과 termina en vocal → 와 (과 tras consonante). Tono escrito; al hablar se prefiere 사과하고/사과랑.',
      "와 relie les deux noms. 사과 finit par une voyelle → 와 (과 après consonne). Ton écrit ; à l'oral on préfère 사과하고/사과랑.",
      '와 une os dois substantivos. 사과 termina em vogal → 와 (과 após consoante). Tom escrito; na fala prefere-se 사과하고/사과랑.',
      '와 เชื่อมคำนามสองคำ 사과 ลงท้ายสระ → 와 (과 หลังพยัญชนะ) น้ำเสียงเขียน ภาษาพูดนิยม 사과하고/사과랑',
      '와 menggabungkan dua kata benda. 사과 berakhiran vokal → 와 (과 setelah konsonan). Nada tulisan; lisan lebih suka 사과하고/사과랑.',
      '와 nối hai danh từ. 사과 kết thúc bằng nguyên âm → 와 (과 sau phụ âm). Giọng văn viết; khi nói ưa 사과하고/사과랑.',
      '와 が二つの名詞をつなぐ。사과 は母音終わり → 와（子音なら 과）。文語的で、会話では 사과하고/사과랑 が好まれる。',
    ),
    readings: [
      {
        off: ['and'],
        trans: L(
          'I buy apples bananas? (the list breaks)',
          '¿Compro manzanas plátanos? (la lista se rompe)',
          "J'achète pommes bananes ? (la liste casse)",
          'Compro maçãs bananas? (a lista quebra)',
          'ซื้อแอปเปิล กล้วย? (รายการขาด)',
          'Beli apel pisang? (daftarnya putus)',
          'Mua táo chuối? (danh sách đứt đoạn)',
          'りんご バナナを買う？（並びが崩れる）',
        ),
        nuance: L(
          'Without 와 the two nouns just collide — 와/하고/(이)랑 are what link "A and B".',
          'Sin 와 los dos sustantivos chocan sin más — 와/하고/(이)랑 son lo que enlaza "A y B".',
          'Sans 와, les deux noms se télescopent — 와/하고/(이)랑 sont ce qui relie « A et B ».',
          'Sem 와 os dois substantivos só colidem — 와/하고/(이)랑 é o que liga "A e B".',
          'ไม่มี 와 คำนามสองคำชนกันเฉยๆ — 와/하고/(이)랑 คือตัวเชื่อม "A และ B"',
          'Tanpa 와, dua kata benda hanya bertabrakan — 와/하고/(이)랑 yang menautkan "A dan B".',
          'Không có 와, hai danh từ chỉ va vào nhau — 와/하고/(이)랑 mới nối "A và B".',
          '와 がないと二つの名詞がただ並ぶだけ — 「AとB」をつなぐのは 와/하고/(이)랑。',
        ),
      },
      {
        off: ['object'],
        trans: L(
          'I buy apples and bananas. (casual)',
          'Compro manzanas y plátanos. (coloquial)',
          "J'achète des pommes et des bananes. (familier)",
          'Compro maçãs e bananas. (casual)',
          'ซื้อแอปเปิลและกล้วย (กันเอง)',
          'Beli apel dan pisang. (santai)',
          'Mua táo và chuối. (thân mật)',
          'りんごとバナナ、買います。（くだけた）',
        ),
        nuance: L(
          "Dropping 를 is natural in speech — what's bought is obvious.",
          'Omitir 를 es natural al hablar — lo que se compra es obvio.',
          "Omettre 를 est naturel à l'oral — ce qu'on achète est évident.",
          'Omitir 를 é natural na fala — o que se compra é óbvio.',
          'การตัด 를 เป็นธรรมชาติในภาษาพูด — สิ่งที่ซื้อชัดเจน',
          'Melepas 를 wajar saat bicara — yang dibeli sudah jelas.',
          'Bỏ 를 là tự nhiên khi nói — thứ được mua đã rõ.',
          '를 を落とすのは会話で自然 — 買う物は明白。',
        ),
      },
    ],
  },
  {
    id: 's12-ahopsibuteo',
    eojeols: [
      [
        {
          kind: 'word',
          text: '아홉',
          gloss: L('nine', 'nueve', 'neuf', 'nove', 'เก้า', 'sembilan', 'chín', '九'),
        },
      ],
      [
        {
          kind: 'word',
          text: '시',
          gloss: L("o'clock", 'hora', 'heure', 'hora', 'โมง', 'pukul', 'giờ', '時'),
        },
        { kind: 'particle', text: '부터', particleId: 'from', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '다섯',
          gloss: L('five', 'cinco', 'cinq', 'cinco', 'ห้า', 'lima', 'năm', '五'),
        },
      ],
      [
        {
          kind: 'word',
          text: '시',
          gloss: L("o'clock", 'hora', 'heure', 'hora', 'โมง', 'pukul', 'giờ', '時'),
        },
        { kind: 'particle', text: '까지', particleId: 'until', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '일해요',
          gloss: L(
            'work',
            'trabajo',
            'travaille',
            'trabalho',
            'ทำงาน',
            'bekerja',
            'làm việc',
            '働きます',
          ),
        },
      ],
    ],
    trans: L(
      'I work from nine to five.',
      'Trabajo de nueve a cinco.',
      'Je travaille de neuf heures à cinq heures.',
      'Trabalho das nove às cinco.',
      'ฉันทำงานตั้งแต่เก้าโมงถึงห้าโมง',
      'Saya bekerja dari jam sembilan sampai jam lima.',
      'Tôi làm việc từ chín giờ đến năm giờ.',
      '9時から5時まで働きます。',
    ),
    nuance: L(
      '부터…까지 is the classic range pair: 부터 sets the start (9), 까지 the end (5).',
      '부터…까지 es el clásico par de rango: 부터 marca el inicio (9), 까지 el final (5).',
      "부터…까지 est le couple classique d'intervalle : 부터 fixe le début (9 h), 까지 la fin (5 h).",
      '부터…까지 é o clássico par de intervalo: 부터 marca o início (9), 까지 o fim (5).',
      '부터…까지 คือคู่ช่วงคลาสสิก: 부터 กำหนดจุดเริ่ม (9), 까지 จุดจบ (5)',
      '부터…까지 adalah pasangan rentang klasik: 부터 menandai awal (9), 까지 akhir (5).',
      '부터…까지 là cặp khoảng kinh điển: 부터 đặt điểm đầu (9), 까지 điểm cuối (5).',
      '부터…까지 は定番の範囲ペア：부터 が始まり（9時）、까지 が終わり（5時）。',
    ),
    readings: [
      {
        off: ['from'],
        trans: L(
          'I work … to five.',
          'Trabajo … hasta las cinco.',
          "Je travaille … jusqu'à cinq heures.",
          'Trabalho … até as cinco.',
          'ทำงาน … จนถึงห้าโมง',
          'Bekerja … sampai jam lima.',
          'Làm việc … đến năm giờ.',
          '… 5時まで働きます。',
        ),
        nuance: L(
          'Without 부터 the start time is gone — you only hear the "until five" end.',
          'Sin 부터 desaparece la hora de inicio — solo queda el final "hasta las cinco".',
          "Sans 부터, l'heure de début disparaît — il ne reste que la fin « jusqu'à cinq heures ».",
          'Sem 부터 some a hora de início — fica só o fim "até as cinco".',
          'ไม่มี 부터 เวลาเริ่มหายไป — เหลือแค่จุดจบ "จนถึงห้าโมง"',
          'Tanpa 부터 waktu mulai hilang — tinggal akhir "sampai jam lima".',
          'Không có 부터 thì mất giờ bắt đầu — chỉ còn điểm cuối "đến năm giờ".',
          '부터 がないと開始時刻が消え、「5時まで」だけが残る。',
        ),
      },
      {
        off: ['until'],
        trans: L(
          'I work from nine …',
          'Trabajo desde las nueve …',
          'Je travaille à partir de neuf heures …',
          'Trabalho desde as nove …',
          'ทำงานตั้งแต่เก้าโมง …',
          'Bekerja dari jam sembilan …',
          'Làm việc từ chín giờ …',
          '9時から働きます …',
        ),
        nuance: L(
          'Without 까지 the end time is gone — only the "from nine" start remains.',
          'Sin 까지 desaparece la hora final — solo queda el inicio "desde las nueve".',
          "Sans 까지, l'heure de fin disparaît — il ne reste que le début « à partir de neuf heures ».",
          'Sem 까지 some a hora final — fica só o início "desde as nove".',
          'ไม่มี 까지 เวลาจบหายไป — เหลือแค่จุดเริ่ม "ตั้งแต่เก้าโมง"',
          'Tanpa 까지 waktu akhir hilang — tinggal awal "dari jam sembilan".',
          'Không có 까지 thì mất giờ kết thúc — chỉ còn điểm đầu "từ chín giờ".',
          '까지 がないと終了時刻が消え、「9時から」だけが残る。',
        ),
      },
    ],
  },
  {
    id: 's13-yeonpillo',
    eojeols: [
      [
        {
          kind: 'word',
          text: '연필',
          gloss: L('pencil', 'lápiz', 'crayon', 'lápis', 'ดินสอ', 'pensil', 'bút chì', '鉛筆'),
        },
        { kind: 'particle', text: '로', particleId: 'by-means', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '편지',
          gloss: L('letter', 'carta', 'lettre', 'carta', 'จดหมาย', 'surat', 'lá thư', '手紙'),
        },
        { kind: 'particle', text: '를', particleId: 'object', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '써요',
          gloss: L('write', 'escribo', 'écris', 'escrevo', 'เขียน', 'menulis', 'viết', '書きます'),
        },
      ],
    ],
    trans: L(
      'I write a letter with a pencil.',
      'Escribo una carta con lápiz.',
      "J'écris une lettre au crayon.",
      'Escrevo uma carta com lápis.',
      'ฉันเขียนจดหมายด้วยดินสอ',
      'Saya menulis surat dengan pensil.',
      'Tôi viết thư bằng bút chì.',
      '鉛筆で手紙を書きます。',
    ),
    nuance: L(
      'Here 로 is the instrument (with what: a pencil). 연필 ends in ㄹ, so it takes 로, not 으로 — the ㄹ exception.',
      'Aquí 로 es el instrumento (con qué: un lápiz). 연필 termina en ㄹ, así que toma 로, no 으로 — la excepción de ㄹ.',
      "Ici 로 est l'instrument (avec quoi : un crayon). 연필 finit par ㄹ, donc 로, pas 으로 — l'exception du ㄹ.",
      'Aqui 로 é o instrumento (com quê: um lápis). 연필 termina em ㄹ, então usa 로, não 으로 — a exceção do ㄹ.',
      'ที่นี่ 로 คือเครื่องมือ (ด้วยอะไร: ดินสอ) 연필 ลงท้ายด้วย ㄹ จึงใช้ 로 ไม่ใช่ 으로 — ข้อยกเว้น ㄹ',
      'Di sini 로 adalah alat (pakai apa: pensil). 연필 berakhiran ㄹ, jadi pakai 로, bukan 으로 — pengecualian ㄹ.',
      'Ở đây 로 là công cụ (bằng gì: bút chì). 연필 kết thúc bằng ㄹ nên dùng 로, không phải 으로 — ngoại lệ ㄹ.',
      'ここでの 로 は道具（何で：鉛筆で）。연필 は ㄹ 終わりなので 으로 でなく 로 — ㄹ の例外。',
    ),
    readings: [
      {
        off: ['by-means'],
        trans: L(
          'I write a letter… pencil? (no "with")',
          'Escribo una carta… ¿lápiz? (sin "con")',
          "J'écris une lettre… crayon ? (pas de « avec »)",
          'Escrevo uma carta… lápis? (sem "com")',
          'เขียนจดหมาย…ดินสอ? (ไม่มี "ด้วย")',
          'Menulis surat… pensil? (tanpa "dengan")',
          'Viết thư… bút chì? (không có "bằng")',
          '手紙を書きます…鉛筆？（「で」がない）',
        ),
        nuance: L(
          'Without 로 you lose "with a pencil" — 로 is what marks the instrument.',
          'Sin 로 pierdes "con lápiz" — 로 es lo que marca el instrumento.',
          "Sans 로, « au crayon » disparaît — c'est 로 qui marque l'instrument.",
          'Sem 로 você perde "com lápis" — 로 é o que marca o instrumento.',
          'ไม่มี 로 จะเสีย "ด้วยดินสอ" — 로 คือสิ่งที่บอกเครื่องมือ',
          'Tanpa 로, "dengan pensil" hilang — 로 yang menandai alat.',
          'Không có 로 thì mất "bằng bút chì" — 로 mới đánh dấu công cụ.',
          '로 がないと「鉛筆で」が消える — 로 が道具を示す。',
        ),
      },
      {
        off: ['object'],
        trans: L(
          'I write a letter with a pencil. (casual)',
          'Escribo una carta con lápiz. (coloquial)',
          "J'écris une lettre au crayon. (familier)",
          'Escrevo uma carta com lápis. (casual)',
          'เขียนจดหมายด้วยดินสอ (กันเอง)',
          'Menulis surat pakai pensil. (santai)',
          'Viết thư bằng bút chì. (thân mật)',
          '鉛筆で手紙、書きます。（くだけた）',
        ),
        nuance: L(
          "Dropping 를 is natural in speech; 편지 is clearly what's written.",
          'Omitir 를 es natural al hablar; está claro que 편지 es lo que se escribe.',
          "Omettre 를 est naturel à l'oral ; 편지 est clairement ce qu'on écrit.",
          'Omitir 를 é natural na fala; 편지 é claramente o que se escreve.',
          'การตัด 를 เป็นธรรมชาติในภาษาพูด; 편지 คือสิ่งที่เขียนชัดเจน',
          'Melepas 를 wajar saat bicara; jelas 편지 yang ditulis.',
          'Bỏ 를 là tự nhiên khi nói; rõ 편지 là thứ được viết.',
          '를 を落とすのは会話で自然。편지 が書く対象なのは明らか。',
        ),
      },
    ],
  },
  {
    id: 's14-jeodo',
    eojeols: [
      [
        {
          kind: 'word',
          text: '저',
          gloss: L('I (humble)', 'yo', 'je', 'eu', 'ฉัน', 'saya', 'tôi', '私'),
        },
        { kind: 'particle', text: '도', particleId: 'also', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '커피',
          gloss: L('coffee', 'café', 'café', 'café', 'กาแฟ', 'kopi', 'cà phê', 'コーヒー'),
        },
        { kind: 'particle', text: '를', particleId: 'object', toggleable: true },
      ],
      [
        {
          kind: 'word',
          text: '마셔요',
          gloss: L('drink', 'bebo', 'bois', 'bebo', 'ดื่ม', 'minum', 'uống', '飲みます'),
        },
      ],
    ],
    trans: L(
      'I drink coffee too.',
      'Yo también bebo café.',
      'Moi aussi je bois du café.',
      'Eu também bebo café.',
      'ฉันก็ดื่มกาแฟด้วย',
      'Saya juga minum kopi.',
      'Tôi cũng uống cà phê.',
      '私もコーヒーを飲みます。',
    ),
    nuance: L(
      '도 = "too", and it replaces 는/가 — 저도, never 저는도. Same one-slot rule as 만.',
      '도 = "también", y reemplaza a 는/가 — 저도, nunca 저는도. La misma regla de un solo hueco que 만.',
      "도 = « aussi », et il remplace 는/가 — 저도, jamais 저는도. Même règle d'une seule place que 만.",
      '도 = "também", e substitui 는/가 — 저도, nunca 저는도. A mesma regra de um só espaço que 만.',
      '도 = "ด้วย" และใช้แทน 는/가 — 저도 ไม่ใช่ 저는도 กฎช่องเดียวเหมือน 만',
      '도 = "juga", menggantikan 는/가 — 저도, bukan 저는도. Aturan satu slot sama seperti 만.',
      '도 = "cũng", thay thế 는/가 — 저도, không phải 저는도. Cùng quy tắc một vị trí như 만.',
      '도＝「も」。는/가 と置き換わる — 저도、저는도 は誤り。만 と同じ「一枠一助詞」。',
    ),
    readings: [
      {
        off: ['also'],
        trans: L(
          'I drink coffee.',
          'Yo bebo café.',
          'Je bois du café.',
          'Eu bebo café.',
          'ฉันดื่มกาแฟ',
          'Saya minum kopi.',
          'Tôi uống cà phê.',
          '私はコーヒーを飲みます。',
        ),
        nuance: L(
          'Without 도 the "too" is gone. For a plain topic you\'d say 저는.',
          'Sin 도 desaparece el "también". Para un tema normal dirías 저는.',
          'Sans 도, le « aussi » disparaît. Pour un simple thème : 저는.',
          'Sem 도 o "também" some. Para um tópico normal seria 저는.',
          'ไม่มี 도 "ด้วย" หายไป ถ้าจะบอกหัวเรื่องปกติใช้ 저는',
          'Tanpa 도, makna "juga" hilang. Untuk topik biasa pakai 저는.',
          'Không có 도 thì mất "cũng". Đánh dấu chủ đề thường thì dùng 저는.',
          '도 がないと「も」が消える。普通の主題なら 저는。',
        ),
      },
      {
        off: ['object'],
        trans: L(
          'I drink coffee too. (casual)',
          'Yo también bebo café. (coloquial)',
          'Moi aussi je bois du café. (familier)',
          'Eu também bebo café. (casual)',
          'ฉันก็ดื่มกาแฟ (กันเอง)',
          'Saya juga minum kopi. (santai)',
          'Tôi cũng uống cà phê. (thân mật)',
          '私もコーヒー、飲みます。（くだけた）',
        ),
        nuance: L(
          'Dropping 를 is completely natural in speech.',
          'Omitir 를 es completamente natural al hablar.',
          "Omettre 를 est tout à fait naturel à l'oral.",
          'Omitir 를 é completamente natural na fala.',
          'การตัด 를 เป็นธรรมชาติอย่างยิ่งในภาษาพูด',
          'Melepas 를 sangat alami saat bicara.',
          'Bỏ 를 hoàn toàn tự nhiên khi nói.',
          '를 を落とすのは会話で完全に自然。',
        ),
      },
    ],
  },
]
