// app/seed/placement/n1.ts
import type { PlacementItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-1 placement items (choose the surface form the context forces).
 * Each item targets a different TOPIK-1 grammar point; `ko` matches
 * grammars-n1.ts verbatim. Single-correct-answer crux drafted + self-reviewed;
 * Korean wife native review = documented final gate.
 */

export const N1_PLACEMENT: PlacementItem[] = [
  {
    ko: '-았/었어요',
    level: 1,
    sentence: '어제 도서관에서 친구를 {}.',
    answer: '만났어요',
    distractors: ['만나요', '만날 거예요', '만납니다'],
    trans: L(
      'I met a friend at the library yesterday.',
      'Ayer me encontré con un amigo en la biblioteca.',
      "Hier, j'ai rencontré un ami à la bibliothèque.",
      'Ontem encontrei um amigo na biblioteca.',
      'เมื่อวานเจอเพื่อนที่ห้องสมุด',
      'Kemarin saya bertemu teman di perpustakaan.',
      'Hôm qua tôi đã gặp bạn ở thư viện.',
      '昨日、図書館で友達に会いました。',
    ),
    why: L(
      '어제 (yesterday) forces the past -았/었어요; 만나요 is present, 만날 거예요 future, 만납니다 formal present.',
      '어제 (ayer) exige el pasado -았/었어요; 만나요 es presente, 만날 거예요 futuro, 만납니다 presente formal.',
      '어제 (hier) impose le passé -았/었어요 ; 만나요 présent, 만날 거예요 futur, 만납니다 présent formel.',
      '어제 (ontem) exige o passado -았/었어요; 만나요 presente, 만날 거예요 futuro, 만납니다 presente formal.',
      '어제 (เมื่อวาน) บังคับอดีต -았/었어요; 만나요 ปัจจุบัน, 만날 거예요 อนาคต, 만납니다 ปัจจุบันทางการ',
      '어제 (kemarin) mengharuskan lampau -았/었어요; 만나요 kini, 만날 거예요 nanti, 만납니다 present formal.',
      '어제 (hôm qua) buộc quá khứ -았/었어요; 만나요 hiện tại, 만날 거예요 tương lai, 만납니다 hiện tại trang trọng.',
      '어제（昨日）が過去 -았/었어요 を要求。만나요 は現在、만날 거예요 は未来、만납니다 は格式の現在。',
    ),
  },
  {
    ko: '-(으)ㄹ 거예요',
    level: 1,
    sentence: '내일 시간이 있으면 영화를 {}.',
    answer: '볼 거예요',
    distractors: ['봤어요', '보세요', '봅니다'],
    trans: L(
      "If I have time tomorrow, I'm going to watch a movie.",
      'Si tengo tiempo mañana, voy a ver una película.',
      "Si j'ai le temps demain, je vais regarder un film.",
      'Se eu tiver tempo amanhã, vou ver um filme.',
      'พรุ่งนี้ถ้ามีเวลาจะดูหนัง',
      'Kalau besok ada waktu, saya akan menonton film.',
      'Ngày mai nếu có thời gian tôi sẽ xem phim.',
      '明日、時間があれば映画を見るつもりです。',
    ),
    why: L(
      '내일 + 1st-person intention forces future -(으)ㄹ 거예요; 봤어요 is past, 보세요 a request, 봅니다 formal present.',
      '내일 + intención en 1ª persona exige el futuro -(으)ㄹ 거예요; 봤어요 pasado, 보세요 petición, 봅니다 presente formal.',
      '내일 + intention à la 1ʳᵉ personne impose le futur -(으)ㄹ 거예요 ; 봤어요 passé, 보세요 demande, 봅니다 présent formel.',
      '내일 + intenção em 1ª pessoa exige o futuro -(으)ㄹ 거예요; 봤어요 passado, 보세요 pedido, 봅니다 presente formal.',
      '내일 + เจตนาบุรุษที่ 1 บังคับอนาคต -(으)ㄹ 거예요; 봤어요 อดีต, 보세요 คำขอ, 봅니다 ปัจจุบันทางการ',
      '내일 + niat orang pertama mengharuskan masa depan -(으)ㄹ 거예요; 봤어요 lampau, 보세요 permintaan, 봅니다 present formal.',
      '내일 + dự định ngôi 1 buộc tương lai -(으)ㄹ 거예요; 봤어요 quá khứ, 보세요 lời nhờ, 봅니다 hiện tại trang trọng.',
      '내일＋一人称の意志が未来 -(으)ㄹ 거예요 を要求。봤어요 は過去、보세요 は依頼、봅니다 は格式の現在。',
    ),
  },
  {
    ko: '-(으)세요',
    level: 1,
    sentence: '다음 손님, 이쪽 자리에 {}.',
    answer: '앉으세요',
    distractors: ['앉았어요', '앉을 거예요', '앉습니다'],
    trans: L(
      'Next customer, please sit in this seat.',
      'Siguiente cliente, siéntese en este asiento, por favor.',
      "Client suivant, asseyez-vous à cette place, s'il vous plaît.",
      'Próximo cliente, sente-se neste lugar, por favor.',
      'ลูกค้าท่านต่อไป เชิญนั่งตรงนี้นะคะ',
      'Pelanggan berikutnya, silakan duduk di kursi ini.',
      'Khách tiếp theo, mời bạn ngồi vào chỗ này.',
      '次のお客様、こちらの席にお座りください。',
    ),
    why: L(
      'Directing a customer to sit is a request → -(으)세요; 앉았어요 past, 앉을 거예요 future, 앉습니다 formal declarative cannot invite.',
      'Indicar a un cliente que se siente es una petición → -(으)세요; 앉았어요 pasado, 앉을 거예요 futuro, 앉습니다 declarativo formal no invita.',
      "Inviter un client à s'asseoir est une demande → -(으)세요 ; 앉았어요 passé, 앉을 거예요 futur, 앉습니다 déclaratif formel n'invite pas.",
      'Indicar a um cliente que se sente é um pedido → -(으)세요; 앉았어요 passado, 앉을 거예요 futuro, 앉습니다 declarativo formal não convida.',
      'การเชิญลูกค้าให้นั่งคือคำขอ → -(으)세요; 앉았어요 อดีต, 앉을 거예요 อนาคต, 앉습니다 บอกเล่าทางการ เชิญไม่ได้',
      'Mempersilakan pelanggan duduk adalah permintaan → -(으)세요; 앉았어요 lampau, 앉을 거예요 nanti, 앉습니다 deklaratif formal tak mempersilakan.',
      'Mời khách ngồi là lời nhờ → -(으)세요; 앉았어요 quá khứ, 앉을 거예요 tương lai, 앉습니다 trần thuật trang trọng không mời được.',
      '客に着席を促すのは依頼 → -(으)세요。앉았어요 は過去、앉을 거예요 は未来、앉습니다 は格式の平叙で促せない。',
    ),
  },
  {
    ko: '-고',
    level: 1,
    sentence: '아침에 운동을 {} 저녁에 친구를 만났어요.',
    answer: '하고',
    distractors: ['해서', '하지만', '하면'],
    trans: L(
      'In the morning I exercised, and in the evening I met a friend.',
      'Por la mañana hice ejercicio y por la tarde me encontré con un amigo.',
      "Le matin j'ai fait du sport, et le soir j'ai rencontré un ami.",
      'De manhã fiz exercício e à noite encontrei um amigo.',
      'ตอนเช้าออกกำลังกาย แล้วตอนเย็นไปเจอเพื่อน',
      'Pagi hari saya berolahraga, lalu malamnya bertemu teman.',
      'Buổi sáng tôi tập thể dục, rồi buổi tối gặp bạn.',
      '朝は運動をして、夜は友達に会いました。',
    ),
    why: L(
      'Two separate actions at different times, simply sequenced → -고 ("and then"); -아/어서 would force the morning exercise to be the basis/cause of the evening meeting (impossible across the time gap), -지만 needs a contrast, -(으)면 a condition (but 만났어요 is a realized past fact).',
      'Dos acciones distintas en momentos distintos, en secuencia → -고 ("y luego"); -아/어서 obligaría a que el ejercicio matutino fuera la base/causa del encuentro nocturno (imposible con la separación temporal), -지만 exige contraste, -(으)면 una condición (pero 만났어요 es un hecho pasado real).',
      "Deux actions distinctes à des moments différents, en séquence → -고 (« et puis ») ; -아/어서 ferait du sport matinal la base/cause de la rencontre du soir (impossible vu l'écart temporel), -지만 exige un contraste, -(으)면 une condition (or 만났어요 est un fait passé réel).",
      'Duas ações distintas em momentos distintos, em sequência → -고 ("e depois"); -아/어서 forçaria o exercício da manhã a ser a base/causa do encontro à noite (impossível com a distância temporal), -지만 exige contraste, -(으)면 uma condição (mas 만났어요 é fato passado real).',
      'สองการกระทำต่างเวลากันเรียงตามลำดับ → -고 ("แล้วก็"); -아/어서 จะบังคับให้การออกกำลังตอนเช้าเป็นเหตุของการเจอเพื่อนตอนเย็น (เป็นไปไม่ได้เพราะคนละเวลา), -지만 ต้องมีความขัดแย้ง, -(으)면 ต้องเป็นเงื่อนไข (แต่ 만났어요 เป็นอดีตที่เกิดจริง)',
      'Dua aksi berbeda pada waktu berbeda, berurutan → -고 ("lalu"); -아/어서 akan memaksa olahraga pagi menjadi dasar/sebab pertemuan malam (mustahil karena jeda waktu), -지만 perlu kontras, -(으)면 perlu syarat (padahal 만났어요 fakta lampau nyata).',
      'Hai hành động khác nhau ở thời điểm khác nhau, nối tiếp → -고 ("rồi"); -아/어서 buộc việc tập buổi sáng thành cơ sở/nguyên nhân của việc gặp buổi tối (bất khả vì cách quãng thời gian), -지만 cần tương phản, -(으)면 cần điều kiện (nhưng 만났어요 là sự thật quá khứ).',
      '異なる時間帯の別々の動作を順に並べる → -고（「〜して」）。-아/어서は朝の運動を夜の対面の前提・原因にしてしまい時間差で不自然、-지만は逆接、-(으)면は条件だが 만났어요 は実現済みの過去。',
    ),
  },
  {
    ko: '-아/어서',
    level: 1,
    sentence: '비가 많이 {} 우리는 집에 있었어요.',
    answer: '와서',
    distractors: ['오면', '오지만', '오거나'],
    trans: L(
      'It rained a lot, so we stayed home.',
      'Llovió mucho, así que nos quedamos en casa.',
      'Il a beaucoup plu, alors nous sommes restés à la maison.',
      'Choveu muito, então ficamos em casa.',
      'ฝนตกหนักพวกเราเลยอยู่บ้าน',
      'Hujan turun lebat, jadi kami tinggal di rumah.',
      'Trời mưa to nên chúng tôi ở nhà.',
      '雨がたくさん降ったので、私たちは家にいました。',
    ),
    why: L(
      'Rain is the realized reason for a past result (있었어요) → -아/어서; -(으)면 is hypothetical, -지만 needs a contrast, -거나 lists alternatives.',
      'La lluvia es la causa real de un resultado pasado (있었어요) → -아/어서; -(으)면 es hipotético, -지만 exige contraste, -거나 enumera alternativas.',
      "La pluie est la cause réelle d'un résultat passé (있었어요) → -아/어서 ; -(으)면 est hypothétique, -지만 exige un contraste, -거나 énumère des alternatives.",
      'A chuva é a causa real de um resultado passado (있었어요) → -아/어서; -(으)면 é hipotético, -지만 exige contraste, -거나 lista alternativas.',
      'ฝนคือเหตุจริงของผลในอดีต (있었어요) → -아/어서; -(으)면 เป็นการสมมติ, -지만 ต้องมีความขัดแย้ง, -거나 เรียงทางเลือก',
      'Hujan adalah sebab nyata dari hasil lampau (있었어요) → -아/어서; -(으)면 andaian, -지만 perlu kontras, -거나 mendaftar alternatif.',
      'Mưa là nguyên nhân thực của kết quả quá khứ (있었어요) → -아/어서; -(으)면 giả định, -지만 cần tương phản, -거나 liệt kê lựa chọn.',
      '雨が過去の結果（있었어요）の現実の原因 → -아/어서。-(으)면は仮定、-지만は逆接、-거나は選択列挙。',
    ),
  },
  {
    ko: '-(으)면',
    level: 1,
    sentence: '내일 비가 {} 등산을 안 갈 거예요.',
    answer: '오면',
    distractors: ['와서', '오지만', '오고'],
    trans: L(
      "If it rains tomorrow, I won't go hiking.",
      'Si mañana llueve, no iré de excursión.',
      "S'il pleut demain, je n'irai pas en randonnée.",
      'Se chover amanhã, não vou fazer trilha.',
      'พรุ่งนี้ถ้าฝนตกจะไม่ไปปีนเขา',
      'Kalau besok hujan, saya tidak akan mendaki.',
      'Ngày mai nếu trời mưa thì tôi sẽ không đi leo núi.',
      '明日雨が降ったら登山に行きません。',
    ),
    why: L(
      '내일 makes the rain a future condition → -(으)면; -아/어서 would assert it as a real past cause, -지만 a contrast, -고 a plain listing.',
      '내일 hace de la lluvia una condición futura → -(으)면; -아/어서 la afirmaría como causa real pasada, -지만 contraste, -고 mera enumeración.',
      '내일 fait de la pluie une condition future → -(으)면 ; -아/어서 l\'affirmerait comme cause réelle passée, -지만 contraste, -고 simple énumération.',
      '내일 torna a chuva uma condição futura → -(으)면; -아/어서 a afirmaria como causa real passada, -지만 contraste, -고 mera enumeração.',
      '내일 ทำให้ฝนเป็นเงื่อนไขอนาคต → -(으)면; -아/어서 จะยืนยันว่าเป็นเหตุจริงในอดีต, -지만 ขัดแย้ง, -고 เรียงเฉย ๆ',
      '내일 menjadikan hujan syarat masa depan → -(으)면; -아/어서 menegaskannya sebab nyata lampau, -지만 kontras, -고 sekadar daftar.',
      '내일 khiến mưa thành điều kiện tương lai → -(으)면; -아/어서 khẳng định là nguyên nhân thực quá khứ, -지만 tương phản, -고 chỉ liệt kê.',
      '내일 が雨を未来の条件にする → -(으)면。-아/어서は現実の過去原因、-지만は逆接、-고は単純並列。',
    ),
  },
]
