// app/seed/placement/n2.ts
import type { PlacementItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-2 placement items. Each targets a different TOPIK-2 grammar point;
 * `ko` matches grammars-n2.ts verbatim. Single-correct-answer crux drafted +
 * self-reviewed; Korean wife native review = documented final gate.
 */

export const N2_PLACEMENT: PlacementItem[] = [
  {
    ko: '-(으)ㄹ 수 있다/없다',
    level: 2,
    sentence: '저는 어렸을 때 배워서 지금 수영을 {}.',
    answer: '할 수 있어요',
    distractors: ['하고 싶어요', '한 적이 있어요', '하면 돼요'],
    trans: L(
      'I learned as a child, so now I can swim.',
      'Aprendí de pequeño, así que ahora sé nadar.',
      "J'ai appris enfant, donc maintenant je sais nager.",
      'Aprendi quando criança, então agora sei nadar.',
      'ฉันเรียนตอนเด็ก ตอนนี้เลยว่ายน้ำได้',
      'Saya belajar sejak kecil, jadi sekarang bisa berenang.',
      'Tôi học từ nhỏ nên bây giờ biết bơi.',
      '子供のとき習ったので、今は泳ぐことができます。',
    ),
    why: L(
      'The clause states an acquired ability → -(으)ㄹ 수 있다; -고 싶다 is desire, -(으)ㄴ 적이 있다 past experience, -(으)면 되다 sufficiency.',
      'La oración expresa una capacidad adquirida → -(으)ㄹ 수 있다; -고 싶다 es deseo, -(으)ㄴ 적이 있다 experiencia, -(으)면 되다 suficiencia.',
      "La proposition exprime une capacité acquise → -(으)ㄹ 수 있다 ; -고 싶다 désir, -(으)ㄴ 적이 있다 expérience, -(으)면 되다 suffisance.",
      'A oração expressa uma capacidade adquirida → -(으)ㄹ 수 있다; -고 싶다 desejo, -(으)ㄴ 적이 있다 experiência, -(으)면 되다 suficiência.',
      'ประโยคบอกความสามารถที่ได้มา → -(으)ㄹ 수 있다; -고 싶다 ความอยาก, -(으)ㄴ 적이 있다 ประสบการณ์, -(으)면 되다 ความเพียงพอ',
      'Klausa menyatakan kemampuan yang diperoleh → -(으)ㄹ 수 있다; -고 싶다 keinginan, -(으)ㄴ 적이 있다 pengalaman, -(으)면 되다 kecukupan.',
      'Mệnh đề nêu khả năng đã có → -(으)ㄹ 수 있다; -고 싶다 mong muốn, -(으)ㄴ 적이 있다 kinh nghiệm, -(으)면 되다 đủ điều kiện.',
      '習得した能力を述べる → -(으)ㄹ 수 있다。-고 싶다 は願望、-(으)ㄴ 적이 있다 は経験、-(으)면 되다 は充足。',
    ),
  },
  {
    ko: '-기 전에',
    level: 2,
    sentence: '저는 {} 항상 상을 차려요.',
    answer: '밥을 먹기 전에',
    distractors: ['밥을 먹은 후에', '밥을 먹으면서', '밥을 먹은 다음에'],
    trans: L(
      'I always set the table before eating.',
      'Siempre pongo la mesa antes de comer.',
      'Je mets toujours la table avant de manger.',
      'Eu sempre ponho a mesa antes de comer.',
      'ฉันจัดโต๊ะอาหารก่อนกินข้าวเสมอ',
      'Saya selalu menyiapkan meja makan sebelum makan.',
      'Tôi luôn dọn bàn ăn trước khi ăn.',
      '私はご飯を食べる前にいつも食卓を整えます。',
    ),
    why: L(
      'Setting the table comes before the meal → -기 전에 (before); you don\'t set the table -(으)ㄴ 후에 / 다음에 (after) or -(으)면서 (while) eating, so only "before" fits.',
      'Poner la mesa ocurre antes de la comida → -기 전에 (antes); no se pone la mesa -(으)ㄴ 후에 / 다음에 (después) ni -(으)면서 (mientras) se come, así que solo cabe "antes".',
      'Mettre la table précède le repas → -기 전에 (avant) ; on ne met pas la table -(으)ㄴ 후에 / 다음에 (après) ni -(으)면서 (pendant) le repas, donc seul « avant » convient.',
      'Pôr a mesa vem antes da refeição → -기 전에 (antes); não se põe a mesa -(으)ㄴ 후에 / 다음에 (depois) nem -(으)면서 (enquanto) se come, então só cabe "antes".',
      'การจัดโต๊ะเกิดก่อนมื้ออาหาร → -기 전에 (ก่อน); เราไม่จัดโต๊ะ -(으)ㄴ 후에 / 다음에 (หลัง) หรือ -(으)면서 (ขณะ) กินข้าว จึงใช้ได้แค่ "ก่อน"',
      'Menyiapkan meja terjadi sebelum makan → -기 전에 (sebelum); kita tidak menyiapkan meja -(으)ㄴ 후에 / 다음에 (sesudah) atau -(으)면서 (sambil) makan, jadi hanya "sebelum" yang cocok.',
      'Dọn bàn diễn ra trước bữa ăn → -기 전에 (trước); không ai dọn bàn -(으)ㄴ 후에 / 다음에 (sau) hay -(으)면서 (trong khi) ăn, nên chỉ "trước" là hợp.',
      '食卓を整えるのは食事の前 → -기 전에（前に）。食後の -(으)ㄴ 후에／다음에 や食事中の -(으)면서 には食卓を整えないので「前に」だけが合う。',
    ),
  },
  {
    ko: '-(으)니까',
    level: 2,
    sentence: '날씨가 {} 같이 산책할까요?',
    answer: '좋으니까',
    distractors: ['좋아서', '좋지만', '좋으면'],
    trans: L(
      'The weather is nice, so shall we take a walk together?',
      'Hace buen tiempo, ¿así que damos un paseo juntos?',
      'Il fait beau, alors on se promène ensemble ?',
      'O tempo está bom, então vamos passear juntos?',
      'อากาศดี ไปเดินเล่นด้วยกันไหม',
      'Cuacanya bagus, jadi bagaimana kalau jalan-jalan bersama?',
      'Thời tiết đẹp nên cùng đi dạo nhé?',
      '天気がいいから一緒に散歩しましょうか。',
    ),
    why: L(
      'A reason leading to a suggestion (-(으)ㄹ까요?) takes -(으)니까; -아/어서 cannot precede a proposal/imperative, -지만 is contrast, -(으)면 condition.',
      'Una razón que lleva a una propuesta (-(으)ㄹ까요?) usa -(으)니까; -아/어서 no precede a propuestas/órdenes, -지만 contraste, -(으)면 condición.',
      'Une raison menant à une suggestion (-(으)ㄹ까요?) prend -(으)니까 ; -아/어서 ne précède pas une proposition/un ordre, -지만 contraste, -(으)면 condition.',
      'Uma razão que leva a uma sugestão (-(으)ㄹ까요?) usa -(으)니까; -아/어서 não precede proposta/ordem, -지만 contraste, -(으)면 condição.',
      'เหตุผลที่นำไปสู่ข้อเสนอ (-(으)ㄹ까요?) ใช้ -(으)니까; -아/어서 นำหน้าข้อเสนอ/คำสั่งไม่ได้, -지만 ขัดแย้ง, -(으)면 เงื่อนไข',
      'Alasan menuju ajakan (-(으)ㄹ까요?) memakai -(으)니까; -아/어서 tak bisa mendahului ajakan/perintah, -지만 kontras, -(으)면 syarat.',
      'Lý do dẫn tới lời rủ (-(으)ㄹ까요?) dùng -(으)니까; -아/어서 không đứng trước lời rủ/mệnh lệnh, -지만 tương phản, -(으)면 điều kiện.',
      '提案（-(으)ㄹ까요?）につながる理由は -(으)니까。-아/어서 は提案・命令の前に立てず、-지만 は逆接、-(으)면 は条件。',
    ),
  },
  {
    ko: '-아/어 보다',
    level: 2,
    sentence: '이 김치가 정말 맛있어요. 한번 {}.',
    answer: '먹어 보세요',
    distractors: ['먹어 봤어요', '먹고 싶어요', '먹어야 돼요'],
    trans: L(
      'This kimchi is really delicious. Try eating some.',
      'Este kimchi está buenísimo. Pruébalo.',
      'Ce kimchi est vraiment délicieux. Goûtez-y.',
      'Este kimchi está muito gostoso. Experimente.',
      'กิมจินี้อร่อยมาก ลองกินดูสิ',
      'Kimchi ini sangat enak. Coba makan, ya.',
      'Kimchi này ngon thật. Bạn ăn thử đi.',
      'このキムチ、本当においしいです。一度食べてみてください。',
    ),
    why: L(
      '한번 + recommendation to attempt → -아/어 보세요 (try); 먹어 봤어요 is past "have tried", -고 싶다 desire, -아/어야 되다 obligation.',
      '한번 + recomendación de intentar → -아/어 보세요; 먹어 봤어요 es pasado "haber probado", -고 싶다 deseo, -아/어야 되다 obligación.',
      "한번 + recommandation d'essayer → -아/어 보세요 ; 먹어 봤어요 passé « avoir essayé », -고 싶다 désir, -아/어야 되다 obligation.",
      '한번 + recomendação para tentar → -아/어 보세요; 먹어 봤어요 passado "já experimentou", -고 싶다 desejo, -아/어야 되다 obrigação.',
      '한번 + การชวนให้ลอง → -아/어 보세요; 먹어 봤어요 อดีต "เคยลอง", -고 싶다 ความอยาก, -아/어야 되다 ข้อบังคับ',
      '한번 + ajakan mencoba → -아/어 보세요; 먹어 봤어요 lampau "pernah coba", -고 싶다 keinginan, -아/어야 되다 keharusan.',
      '한번 + lời rủ thử → -아/어 보세요; 먹어 봤어요 quá khứ "đã thử", -고 싶다 mong muốn, -아/어야 되다 bắt buộc.',
      '한번＋試すよう勧める → -아/어 보세요。먹어 봤어요 は過去「試したことがある」、-고 싶다 は願望、-아/어야 되다 は義務。',
    ),
  },
  {
    ko: '-(으)ㄹ게요',
    level: 2,
    sentence: '걱정 마세요. 제가 내일 꼭 {}.',
    answer: '전화할게요',
    distractors: ['전화했어요', '전화하세요', '전화할까요'],
    trans: L(
      "Don't worry. I'll definitely call you tomorrow.",
      'No te preocupes. Mañana sin falta te llamo.',
      "Ne t'inquiète pas. Je t'appellerai sans faute demain.",
      'Não se preocupe. Eu te ligo amanhã sem falta.',
      'ไม่ต้องห่วง พรุ่งนี้ฉันจะโทรหาแน่นอน',
      'Jangan khawatir. Besok saya pasti menelepon.',
      'Đừng lo. Ngày mai nhất định tôi sẽ gọi.',
      '心配しないでください。明日必ず電話します。',
    ),
    why: L(
      'A 1st-person promise to the listener → -(으)ㄹ게요; 전화했어요 is past, 전화하세요 a request to the other, 전화할까요 a suggestion/question.',
      'Una promesa en 1ª persona al oyente → -(으)ㄹ게요; 전화했어요 pasado, 전화하세요 petición al otro, 전화할까요 propuesta/pregunta.',
      "Une promesse à la 1ʳᵉ personne à l'interlocuteur → -(으)ㄹ게요 ; 전화했어요 passé, 전화하세요 demande à l'autre, 전화할까요 proposition/question.",
      'Uma promessa em 1ª pessoa ao ouvinte → -(으)ㄹ게요; 전화했어요 passado, 전화하세요 pedido ao outro, 전화할까요 proposta/pergunta.',
      'คำสัญญาบุรุษที่ 1 ต่อผู้ฟัง → -(으)ㄹ게요; 전화했어요 อดีต, 전화하세요 คำขอต่ออีกฝ่าย, 전화할까요 ข้อเสนอ/คำถาม',
      'Janji orang pertama kepada pendengar → -(으)ㄹ게요; 전화했어요 lampau, 전화하세요 permintaan ke lawan bicara, 전화할까요 ajakan/pertanyaan.',
      'Lời hứa ngôi 1 với người nghe → -(으)ㄹ게요; 전화했어요 quá khứ, 전화하세요 lời nhờ với người kia, 전화할까요 lời rủ/câu hỏi.',
      '聞き手への一人称の約束 → -(으)ㄹ게요。전화했어요 は過去、전화하세요 は相手への依頼、전화할까요 は提案・疑問。',
    ),
  },
  {
    ko: '-거나',
    level: 2,
    sentence: '주말에는 보통 책을 {} 영화를 봐요.',
    answer: '읽거나',
    distractors: ['읽어서', '읽으면', '읽지만'],
    trans: L(
      'On weekends I usually read books or watch movies.',
      'Los fines de semana normalmente leo libros o veo películas.',
      'Le week-end, je lis généralement des livres ou regarde des films.',
      'Nos fins de semana costumo ler livros ou ver filmes.',
      'วันหยุดปกติฉันอ่านหนังสือหรือไม่ก็ดูหนัง',
      'Di akhir pekan saya biasanya membaca buku atau menonton film.',
      'Cuối tuần tôi thường đọc sách hoặc xem phim.',
      '週末はたいてい本を読んだり映画を見たりします。',
    ),
    why: L(
      'Two alternative activities ("or") → -거나; -아/어서 makes reading the cause of watching, -(으)면 a condition, -지만 a contrast.',
      'Dos actividades alternativas ("o") → -거나; -아/어서 hace de leer la causa de ver, -(으)면 condición, -지만 contraste.',
      'Deux activités alternatives (« ou ») → -거나 ; -아/어서 fait de la lecture la cause du visionnage, -(으)면 condition, -지만 contraste.',
      'Duas atividades alternativas ("ou") → -거나; -아/어서 faz a leitura ser a causa de assistir, -(으)면 condição, -지만 contraste.',
      'กิจกรรมทางเลือกสองอย่าง ("หรือ") → -거나; -아/어서 ทำให้การอ่านเป็นเหตุของการดู, -(으)면 เงื่อนไข, -지만 ขัดแย้ง',
      'Dua kegiatan alternatif ("atau") → -거나; -아/어서 menjadikan membaca sebab menonton, -(으)면 syarat, -지만 kontras.',
      'Hai hoạt động thay thế ("hoặc") → -거나; -아/어서 biến việc đọc thành nguyên nhân của việc xem, -(으)면 điều kiện, -지만 tương phản.',
      '二つの代替活動（「または」）→ -거나。-아/어서 は読書を視聴の原因にし、-(으)면 は条件、-지만 は逆接。',
    ),
  },
]
