// app/seed/placement/n3.ts
import type { PlacementItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-3 placement items. Each targets a different TOPIK-3 grammar point;
 * `ko` matches grammars-n3.ts verbatim. Single-correct-answer crux drafted +
 * self-reviewed; Korean wife native review = documented final gate.
 */

export const N3_PLACEMENT: PlacementItem[] = [
  {
    ko: '-(으)면서',
    level: 3,
    sentence: '동생은 음악을 {} 공부해요.',
    answer: '들으면서',
    distractors: ['들어서', '들으니까', '들으려고'],
    trans: L(
      'My younger sibling studies while listening to music.',
      'Mi hermano menor estudia mientras escucha música.',
      'Mon cadet étudie en écoutant de la musique.',
      'Meu irmão mais novo estuda enquanto ouve música.',
      'น้องเรียนไปฟังเพลงไป',
      'Adik saya belajar sambil mendengarkan musik.',
      'Em tôi vừa nghe nhạc vừa học.',
      '弟は音楽を聞きながら勉強します。',
    ),
    why: L(
      'Two simultaneous actions by one subject → -(으)면서 (while); -아/어서 cause/sequence, -(으)니까 reason, -(으)려고 purpose.',
      'Dos acciones simultáneas de un mismo sujeto → -(으)면서 (mientras); -아/어서 causa/secuencia, -(으)니까 razón, -(으)려고 propósito.',
      'Deux actions simultanées d\'un même sujet → -(으)면서 (en) ; -아/어서 cause/suite, -(으)니까 raison, -(으)려고 but.',
      'Duas ações simultâneas do mesmo sujeito → -(으)면서 (enquanto); -아/어서 causa/sequência, -(으)니까 razão, -(으)려고 propósito.',
      'การกระทำพร้อมกันของประธานเดียว → -(으)면서 (ขณะที่); -아/어서 เหตุ/ลำดับ, -(으)니까 เหตุผล, -(으)려고 จุดประสงค์',
      'Dua aksi serentak satu subjek → -(으)면서 (sambil); -아/어서 sebab/urutan, -(으)니까 alasan, -(으)려고 tujuan.',
      'Hai hành động đồng thời của một chủ ngữ → -(으)면서 (vừa); -아/어서 nguyên nhân/trình tự, -(으)니까 lý do, -(으)려고 mục đích.',
      '同一主語の同時動作 → -(으)면서（ながら）。-아/어서 は原因・連続、-(으)니까 は理由、-(으)려고 は目的。',
    ),
  },
  {
    ko: '-기로 하다',
    level: 3,
    sentence: '고민 끝에 저는 담배를 {} 결심했어요.',
    answer: '끊기로',
    distractors: ['끊으려고', '끊는다고', '끊거나'],
    trans: L(
      'After much thought, I made up my mind to quit smoking.',
      'Tras pensarlo mucho, decidí dejar de fumar.',
      "Après mûre réflexion, j'ai pris la décision d'arrêter de fumer.",
      'Depois de muito pensar, decidi parar de fumar.',
      'หลังจากคิดอยู่นาน ฉันตัดสินใจเลิกบุหรี่',
      'Setelah lama menimbang, saya bertekad berhenti merokok.',
      'Sau khi suy nghĩ nhiều, tôi quyết tâm bỏ thuốc lá.',
      '悩んだ末に、私はタバコをやめることを決心しました。',
    ),
    why: L(
      '결심하다 (resolve) selects the decision complement -기로; 끊으려고 marks intention, -ㄴ/는다고 reported speech, -거나 alternatives — none pairs with 결심했어요.',
      '결심하다 (resolver) selecciona el complemento de decisión -기로; 끊으려고 marca intención, -ㄴ/는다고 estilo indirecto, -거나 alternativas — ninguno combina con 결심했어요.',
      "결심하다 (se résoudre) sélectionne le complément de décision -기로 ; 끊으려고 marque l'intention, -ㄴ/는다고 discours rapporté, -거나 alternatives — aucun ne va avec 결심했어요.",
      '결심하다 (resolver) seleciona o complemento de decisão -기로; 끊으려고 marca intenção, -ㄴ/는다고 discurso indireto, -거나 alternativas — nenhum combina com 결심했어요.',
      '결심하다 (ตัดสินใจ) เลือกส่วนเติมเต็มการตัดสินใจ -기로; 끊으려고 บอกเจตนา, -ㄴ/는다고 คำพูดอ้อม, -거나 ทางเลือก — ไม่มีอันใดเข้ากับ 결심했어요',
      '결심하다 (bertekad) memilih komplemen keputusan -기로; 끊으려고 menandai niat, -ㄴ/는다고 ujaran tak langsung, -거나 alternatif — tak ada yang cocok dengan 결심했어요.',
      '결심하다 (quyết tâm) chọn bổ ngữ quyết định -기로; 끊으려고 đánh dấu ý định, -ㄴ/는다고 lời dẫn gián tiếp, -거나 lựa chọn — không cái nào hợp với 결심했어요.',
      '결심하다（決心する）は決定の補語 -기로 を選ぶ。끊으려고 は意図、-ㄴ/는다고 は引用、-거나 は選択で、결심했어요 と結びつかない。',
    ),
  },
  {
    ko: '-자마자',
    level: 3,
    sentence: '집에 {} 손을 씻고 바로 잤어요.',
    answer: '도착하자마자',
    distractors: ['도착하더니', '도착하도록', '도착하느라고'],
    trans: L(
      'As soon as I arrived home, I washed my hands and went straight to sleep.',
      'En cuanto llegué a casa, me lavé las manos y me dormí enseguida.',
      'Dès que je suis arrivé à la maison, je me suis lavé les mains et me suis endormi aussitôt.',
      'Assim que cheguei em casa, lavei as mãos e dormi logo.',
      'พอถึงบ้านก็ล้างมือแล้วนอนเลย',
      'Begitu sampai di rumah, saya cuci tangan lalu langsung tidur.',
      'Vừa về đến nhà tôi rửa tay rồi đi ngủ ngay.',
      '家に着くやいなや手を洗ってすぐ寝ました。',
    ),
    why: L(
      'Two events back-to-back with a 1st-person past → -자마자 (as soon as); -더니 needs a 2nd/3rd-person observed shift, -도록 purpose/degree, -느라고 a hindering cause.',
      'Dos hechos seguidos en pasado de 1ª persona → -자마자; -더니 exige un cambio observado en 2ª/3ª persona, -도록 propósito/grado, -느라고 causa que estorba.',
      'Deux faits qui s\'enchaînent au passé à la 1ʳᵉ personne → -자마자 ; -더니 exige un changement observé à la 2ᵉ/3ᵉ personne, -도록 but/degré, -느라고 cause gênante.',
      'Dois fatos em sequência no passado de 1ª pessoa → -자마자; -더니 exige mudança observada em 2ª/3ª pessoa, -도록 propósito/grau, -느라고 causa que atrapalha.',
      'สองเหตุการณ์ต่อเนื่องในอดีตบุรุษที่ 1 → -자마자; -더니 ต้องเป็นการเปลี่ยนที่สังเกตในบุรุษที่ 2/3, -도록 จุดประสงค์/ระดับ, -느라고 เหตุที่ขัดขวาง',
      'Dua kejadian beruntun di lampau orang pertama → -자마자; -더니 perlu perubahan teramati orang ke-2/3, -도록 tujuan/derajat, -느라고 sebab yang menghambat.',
      'Hai sự việc nối tiếp ở quá khứ ngôi 1 → -자마자; -더니 cần thay đổi quan sát ở ngôi 2/3, -도록 mục đích/mức độ, -느라고 nguyên nhân gây cản trở.',
      '一人称過去の連続する二事象 → -자마자。-더니 は二・三人称で観察した変化が必要、-도록 は目的・程度、-느라고 は妨げの原因。',
    ),
  },
  {
    ko: '-(으)ㄴ 지',
    level: 3,
    sentence: '한국에 {} 벌써 삼 년이 됐어요.',
    answer: '온 지',
    distractors: ['오는데', '오면서', '오니까'],
    trans: L(
      "It's already been three years since I came to Korea.",
      'Ya han pasado tres años desde que vine a Corea.',
      'Cela fait déjà trois ans que je suis venu en Corée.',
      'Já faz três anos desde que vim para a Coreia.',
      'มาเกาหลีได้สามปีแล้ว',
      'Sudah tiga tahun sejak saya datang ke Korea.',
      'Đã ba năm kể từ khi tôi đến Hàn Quốc.',
      '韓国に来てからもう三年になりました。',
    ),
    why: L(
      'Elapsed time since an event (벌써 삼 년이 됐어요) → -(으)ㄴ 지; -는데 background, -(으)면서 simultaneity, -(으)니까 reason cannot count duration.',
      'Tiempo transcurrido desde un evento (벌써 삼 년이 됐어요) → -(으)ㄴ 지; -는데 trasfondo, -(으)면서 simultaneidad, -(으)니까 razón no mide duración.',
      'Temps écoulé depuis un événement (벌써 삼 년이 됐어요) → -(으)ㄴ 지 ; -는데 contexte, -(으)면서 simultanéité, -(으)니까 raison ne mesurent pas la durée.',
      'Tempo decorrido desde um evento (벌써 삼 년이 됐어요) → -(으)ㄴ 지; -는데 pano de fundo, -(으)면서 simultaneidade, -(으)니까 razão não medem duração.',
      'เวลาที่ผ่านไปนับจากเหตุการณ์ (벌써 삼 년이 됐어요) → -(으)ㄴ 지; -는데 ปูพื้น, -(으)면서 พร้อมกัน, -(으)니까 เหตุผล วัดระยะเวลาไม่ได้',
      'Waktu berlalu sejak suatu peristiwa (벌써 삼 년이 됐어요) → -(으)ㄴ 지; -는데 latar, -(으)면서 keserentakan, -(으)니까 alasan tak mengukur durasi.',
      'Thời gian trôi qua kể từ một sự việc (벌써 삼 년이 됐어요) → -(으)ㄴ 지; -는데 nền, -(으)면서 đồng thời, -(으)니까 lý do không đo thời lượng.',
      '出来事からの経過時間（벌써 삼 년이 됐어요）→ -(으)ㄴ 지。-는데 は背景、-(으)면서 は同時、-(으)니까 は理由で期間を数えられない。',
    ),
  },
  {
    ko: '-도록',
    level: 3,
    sentence: '뒤에서도 잘 {} 큰 소리로 말해 주세요.',
    answer: '들리도록',
    distractors: ['들리니까', '들려서', '들리면'],
    trans: L(
      'Please speak loudly so that it can be heard well from the back too.',
      'Hable en voz alta para que se oiga bien también desde atrás, por favor.',
      "Parlez fort pour qu'on entende bien aussi depuis le fond, s'il vous plaît.",
      'Fale alto para que se ouça bem também lá de trás, por favor.',
      'กรุณาพูดเสียงดังเพื่อให้ได้ยินชัดจากด้านหลังด้วย',
      'Tolong bicara keras agar terdengar jelas dari belakang juga.',
      'Hãy nói to để phía sau cũng nghe rõ.',
      '後ろでもよく聞こえるように大きな声で話してください。',
    ),
    why: L(
      'A goal/purpose set up for a following request → -도록 (so that); -(으)니까 states a reason, -아/어서 cause, -(으)면 a condition — none names a target outcome.',
      'Una meta/propósito antes de una petición → -도록 (para que); -(으)니까 da una razón, -아/어서 causa, -(으)면 condición — ninguno expresa el resultado buscado.',
      'Un but/objectif posé avant une demande → -도록 (pour que) ; -(으)니까 donne une raison, -아/어서 cause, -(으)면 condition — aucun ne vise un résultat.',
      'Uma meta/propósito antes de um pedido → -도록 (para que); -(으)니까 dá uma razão, -아/어서 causa, -(으)면 condição — nenhum visa o resultado.',
      'เป้าหมาย/จุดประสงค์ก่อนคำขอ → -도록 (เพื่อให้); -(으)니까 ให้เหตุผล, -아/어서 เหตุ, -(으)면 เงื่อนไข — ไม่มีอันใดระบุผลที่มุ่งหวัง',
      'Tujuan/maksud sebelum permintaan → -도록 (supaya); -(으)니까 alasan, -아/어서 sebab, -(으)면 syarat — tak ada yang menyatakan hasil yang dituju.',
      'Mục tiêu/mục đích đặt trước lời nhờ → -도록 (để cho); -(으)니까 nêu lý do, -아/어서 nguyên nhân, -(으)면 điều kiện — không cái nào chỉ kết quả nhắm tới.',
      '依頼の前に置く目標・目的 → -도록（ように）。-(으)니까 は理由、-아/어서 は原因、-(으)면 は条件で、狙う結果を示さない。',
    ),
  },
  {
    ko: '-아/어지다',
    level: 3,
    sentence: '봄이 되니까 날씨가 점점 {}.',
    answer: '따뜻해져요',
    distractors: ['따뜻해요', '따뜻했어요', '따뜻하세요'],
    trans: L(
      'As spring comes, the weather is gradually getting warmer.',
      'Como llega la primavera, el clima se va poniendo cálido poco a poco.',
      "Comme le printemps arrive, le temps devient peu à peu plus chaud.",
      'Como a primavera chega, o tempo vai ficando cada vez mais quente.',
      'พอถึงฤดูใบไม้ผลิ อากาศก็ค่อย ๆ อุ่นขึ้น',
      'Karena musim semi tiba, cuaca lambat laun menjadi hangat.',
      'Mùa xuân đến nên thời tiết dần dần ấm lên.',
      '春になって、天気がだんだん暖かくなります。',
    ),
    why: L(
      '점점 (gradually) signals a change of state → -아/어지다 (become); 따뜻해요 is a static present, 따뜻했어요 past state, 따뜻하세요 honorific/request.',
      '점점 (poco a poco) indica un cambio de estado → -아/어지다 (volverse); 따뜻해요 presente estático, 따뜻했어요 estado pasado, 따뜻하세요 honorífico/petición.',
      "점점 (peu à peu) signale un changement d'état → -아/어지다 (devenir) ; 따뜻해요 présent statique, 따뜻했어요 état passé, 따뜻하세요 honorifique/demande.",
      '점점 (pouco a pouco) indica mudança de estado → -아/어지다 (tornar-se); 따뜻해요 presente estático, 따뜻했어요 estado passado, 따뜻하세요 honorífico/pedido.',
      '점점 (ค่อย ๆ) บ่งการเปลี่ยนสภาพ → -아/어지다 (กลายเป็น); 따뜻해요 ปัจจุบันคงที่, 따뜻했어요 สภาพอดีต, 따뜻하세요 ยกย่อง/คำขอ',
      '점점 (lambat laun) menandai perubahan keadaan → -아/어지다 (menjadi); 따뜻해요 kini statis, 따뜻했어요 keadaan lampau, 따뜻하세요 hormat/permintaan.',
      '점점 (dần dần) báo hiệu thay đổi trạng thái → -아/어지다 (trở nên); 따뜻해요 hiện tại tĩnh, 따뜻했어요 trạng thái quá khứ, 따뜻하세요 kính ngữ/lời nhờ.',
      '점점（だんだん）は状態変化を示す → -아/어지다（〜くなる）。따뜻해요 は静的現在、따뜻했어요 は過去の状態、따뜻하세요 は尊敬・依頼。',
    ),
  },
]
