// app/seed/placement/n4.ts
import type { PlacementItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-4 placement items. Each targets a different TOPIK-4 grammar point;
 * `ko` matches grammars-n4.ts verbatim. Single-correct-answer crux drafted +
 * self-reviewed; Korean wife native review = documented final gate.
 */

export const N4_PLACEMENT: PlacementItem[] = [
  {
    ko: '-(으)라고 하다',
    level: 4,
    sentence: '의사 선생님이 약을 식사 후에 {}.',
    answer: '먹으라고 했어요',
    distractors: ['먹는다고 했어요', '먹냐고 했어요', '먹자고 했어요'],
    trans: L(
      'The doctor told me to take the medicine after meals.',
      'El médico me dijo que tomara el medicamento después de las comidas.',
      'Le médecin m\'a dit de prendre le médicament après les repas.',
      'O médico me disse para tomar o remédio depois das refeições.',
      'หมอบอกให้กินยาหลังอาหาร',
      'Dokter menyuruh saya minum obat setelah makan.',
      'Bác sĩ bảo tôi uống thuốc sau bữa ăn.',
      '医者は食後に薬を飲むようにと言いました。',
    ),
    why: L(
      'Reporting a command → -(으)라고 하다; -ㄴ/는다고 reports a statement, -냐고 a question, -자고 a suggestion.',
      'Reportar una orden → -(으)라고 하다; -ㄴ/는다고 reporta una afirmación, -냐고 una pregunta, -자고 una propuesta.',
      'Rapporter un ordre → -(으)라고 하다 ; -ㄴ/는다고 rapporte une affirmation, -냐고 une question, -자고 une proposition.',
      'Relatar uma ordem → -(으)라고 하다; -ㄴ/는다고 relata uma afirmação, -냐고 uma pergunta, -자고 uma proposta.',
      'การรายงานคำสั่ง → -(으)라고 하다; -ㄴ/는다고 รายงานบอกเล่า, -냐고 คำถาม, -자고 ข้อเสนอ',
      'Melaporkan perintah → -(으)라고 하다; -ㄴ/는다고 melaporkan pernyataan, -냐고 pertanyaan, -자고 ajakan.',
      'Tường thuật mệnh lệnh → -(으)라고 하다; -ㄴ/는다고 thuật câu trần thuật, -냐고 câu hỏi, -자고 lời rủ.',
      '命令の引用 → -(으)라고 하다。-ㄴ/는다고 は平叙、-냐고 は疑問、-자고 は勧誘の引用。',
    ),
  },
  {
    ko: '-(으)ㄹ수록',
    level: 4,
    sentence: '이 노래는 {} 더 좋아져요.',
    answer: '들을수록',
    distractors: ['들으니까', '들어도', '들으려고'],
    trans: L(
      'The more I listen to this song, the more I like it.',
      'Cuanto más escucho esta canción, más me gusta.',
      "Plus j'écoute cette chanson, plus je l'aime.",
      'Quanto mais ouço esta música, mais gosto dela.',
      'ยิ่งฟังเพลงนี้ก็ยิ่งชอบ',
      'Semakin sering mendengar lagu ini, semakin saya menyukainya.',
      'Càng nghe bài hát này tôi càng thích.',
      'この歌は聞けば聞くほど好きになります。',
    ),
    why: L(
      '"The more… the more" proportionality → -(으)ㄹ수록; -(으)니까 reason, -아/어도 concession, -(으)려고 purpose.',
      'Proporcionalidad "cuanto más… más" → -(으)ㄹ수록; -(으)니까 razón, -아/어도 concesión, -(으)려고 propósito.',
      'Proportion « plus… plus » → -(으)ㄹ수록 ; -(으)니까 raison, -아/어도 concession, -(으)려고 but.',
      'Proporcionalidade "quanto mais… mais" → -(으)ㄹ수록; -(으)니까 razão, -아/어도 concessão, -(으)려고 propósito.',
      'ความสัมพันธ์ "ยิ่ง…ยิ่ง" → -(으)ㄹ수록; -(으)니까 เหตุผล, -아/어도 ยอมรับ, -(으)려고 จุดประสงค์',
      'Proporsi "semakin… semakin" → -(으)ㄹ수록; -(으)니까 alasan, -아/어도 konsesi, -(으)려고 tujuan.',
      'Tỉ lệ thuận "càng… càng" → -(으)ㄹ수록; -(으)니까 lý do, -아/어도 nhượng bộ, -(으)려고 mục đích.',
      '「〜ほど〜」の比例 → -(으)ㄹ수록。-(으)니까 は理由、-아/어도 は譲歩、-(으)려고 は目的。',
    ),
  },
  {
    ko: '-는 바람에',
    level: 4,
    sentence: '갑자기 비가 {} 옷이 다 젖었어요.',
    answer: '오는 바람에',
    distractors: ['오는 덕분에', '오는 대신에', '오는 김에'],
    trans: L(
      'Because it suddenly rained, my clothes got all wet.',
      'Por culpa de que llovió de repente, se me mojó toda la ropa.',
      "À cause d'une pluie soudaine, mes vêtements ont été trempés.",
      'Por causa da chuva repentina, minha roupa ficou toda molhada.',
      'เพราะจู่ ๆ ฝนตก เสื้อผ้าเลยเปียกหมด',
      'Gara-gara tiba-tiba hujan, baju saya basah semua.',
      'Vì trời bỗng đổ mưa nên quần áo tôi ướt hết.',
      '急に雨が降ったせいで、服が全部濡れました。',
    ),
    why: L(
      'A negative unexpected cause → -는 바람에 (because of, bad result); -는 덕분에 is a positive thanks-to, -는 대신에 "instead of", -는 김에 "while at it".',
      'Una causa negativa inesperada → -는 바람에 (por culpa de); -는 덕분에 es positivo "gracias a", -는 대신에 "en lugar de", -는 김에 "ya que".',
      'Une cause négative inattendue → -는 바람에 (à cause de, mauvais résultat) ; -는 덕분에 positif « grâce à », -는 대신에 « au lieu de », -는 김에 « tant qu\'à ».',
      'Uma causa negativa inesperada → -는 바람에 (por causa de, resultado ruim); -는 덕분에 positivo "graças a", -는 대신에 "em vez de", -는 김에 "já que".',
      'เหตุลบที่ไม่คาดคิด → -는 바람에 (เพราะ ผลร้าย); -는 덕분에 บวก "ด้วยความช่วยเหลือ", -는 대신에 "แทนที่", -는 김에 "ถือโอกาส"',
      'Sebab negatif tak terduga → -는 바람에 (gara-gara); -는 덕분에 positif "berkat", -는 대신에 "alih-alih", -는 김에 "sekalian".',
      'Nguyên nhân tiêu cực bất ngờ → -는 바람에 (vì, kết quả xấu); -는 덕분에 tích cực "nhờ", -는 대신에 "thay vì", -는 김에 "nhân tiện".',
      '予期せぬ悪い原因 → -는 바람에（せいで）。-는 덕분에 は良い「おかげで」、-는 대신에 は「代わりに」、-는 김에 は「ついでに」。',
    ),
  },
  {
    ko: '-(으)ㄹ 텐데',
    level: 4,
    sentence: '지금쯤 길이 많이 {} 일찍 출발하는 게 좋겠어요.',
    answer: '막힐 텐데',
    distractors: ['막혔는데', '막히는데', '막히니까'],
    trans: L(
      "The roads are probably very congested by now, so we'd better leave early.",
      'A esta hora las calles estarán muy congestionadas, así que mejor salimos pronto.',
      'À cette heure les routes doivent être très embouteillées, donc mieux vaut partir tôt.',
      'A esta altura as ruas devem estar muito congestionadas, então é melhor sair cedo.',
      'ป่านนี้รถน่าจะติดมาก เราออกแต่เนิ่น ๆ ดีกว่า',
      'Sekarang jalanan mungkin macet parah, jadi sebaiknya berangkat lebih awal.',
      'Giờ này đường chắc đang kẹt xe lắm, nên đi sớm thì hơn.',
      '今ごろ道がかなり混んでいるだろうから、早めに出発したほうがいいです。',
    ),
    why: L(
      'A speaker\'s conjecture (지금쯤) about an unverified situation → -(으)ㄹ 텐데; 막혔는데 asserts a known past, 막히는데 a known present, -(으)니까 a firm reason.',
      'Una conjetura del hablante (지금쯤) sobre algo no verificado → -(으)ㄹ 텐데; 막혔는데 afirma un pasado conocido, 막히는데 un presente conocido, -(으)니까 una razón firme.',
      "Une conjecture du locuteur (지금쯤) sur une situation non vérifiée → -(으)ㄹ 텐데 ; 막혔는데 affirme un passé connu, 막히는데 un présent connu, -(으)니까 une raison ferme.",
      'Uma conjectura do falante (지금쯤) sobre algo não verificado → -(으)ㄹ 텐데; 막혔는데 afirma um passado conhecido, 막히는데 um presente conhecido, -(으)니까 uma razão firme.',
      'การคาดเดาของผู้พูด (지금쯤) ต่อสิ่งที่ยังไม่ยืนยัน → -(으)ㄹ 텐데; 막혔는데 ยืนยันอดีตที่รู้, 막히는데 ปัจจุบันที่รู้, -(으)니까 เหตุผลที่แน่ชัด',
      'Dugaan penutur (지금쯤) atas situasi belum terverifikasi → -(으)ㄹ 텐데; 막혔는데 menegaskan lampau yang diketahui, 막히는데 kini yang diketahui, -(으)니까 alasan pasti.',
      'Phỏng đoán của người nói (지금쯤) về tình huống chưa kiểm chứng → -(으)ㄹ 텐데; 막혔는데 khẳng định quá khứ đã biết, 막히는데 hiện tại đã biết, -(으)니까 lý do chắc chắn.',
      '話し手の推量（지금쯤）で未確認の状況 → -(으)ㄹ 텐데。막혔는데 は既知の過去、막히는데 は既知の現在、-(으)니까 は確かな理由。',
    ),
  },
  {
    ko: '-(으)ㄴ 채(로)',
    level: 4,
    sentence: '너무 피곤해서 불을 {} 잠이 들었어요.',
    answer: '켠 채로',
    distractors: ['켜면서', '켜고서', '켜자마자'],
    trans: L(
      'I was so tired that I fell asleep with the light still on.',
      'Estaba tan cansado que me quedé dormido con la luz encendida.',
      "J'étais si fatigué que je me suis endormi en laissant la lumière allumée.",
      'Eu estava tão cansado que adormeci com a luz acesa.',
      'เหนื่อยมากจนเผลอหลับไปทั้งที่เปิดไฟไว้',
      'Saya sangat lelah hingga tertidur dengan lampu masih menyala.',
      'Tôi mệt đến mức ngủ thiếp đi khi đèn vẫn bật.',
      'とても疲れて、電気をつけたまま眠ってしまいました。',
    ),
    why: L(
      'A maintained state during another action → -(으)ㄴ 채(로) (in the state of); -(으)면서 simultaneity of two actions, -고서 sequence, -자마자 immediacy.',
      'Un estado mantenido durante otra acción → -(으)ㄴ 채(로) (en el estado de); -(으)면서 simultaneidad de dos acciones, -고서 secuencia, -자마자 inmediatez.',
      "Un état maintenu pendant une autre action → -(으)ㄴ 채(로) (dans l'état de) ; -(으)면서 simultanéité de deux actions, -고서 succession, -자마자 immédiateté.",
      'Um estado mantido durante outra ação → -(으)ㄴ 채(로) (no estado de); -(으)면서 simultaneidade de duas ações, -고서 sequência, -자마자 imediatismo.',
      'สภาพที่คงไว้ระหว่างอีกการกระทำ → -(으)ㄴ 채(로) (ในสภาพที่); -(으)면서 สองการกระทำพร้อมกัน, -고서 ลำดับ, -자마자 ทันที',
      'Keadaan yang dipertahankan selama aksi lain → -(으)ㄴ 채(로) (dalam keadaan); -(으)면서 dua aksi serentak, -고서 urutan, -자마자 segera.',
      'Một trạng thái được giữ nguyên trong khi làm việc khác → -(으)ㄴ 채(로) (trong tình trạng); -(으)면서 hai hành động đồng thời, -고서 trình tự, -자마자 ngay lập tức.',
      '別の動作中に保たれた状態 → -(으)ㄴ 채(로)（〜のまま）。-(으)면서 は二動作の同時、-고서 は連続、-자마자 は即時。',
    ),
  },
  {
    ko: '-느라(고)',
    level: 4,
    sentence: '어제 밤늦게까지 게임을 {} 숙제를 못 했어요.',
    answer: '하느라고',
    distractors: ['하니까', '하지만', '하거나'],
    trans: L(
      "Because I was playing games until late last night, I couldn't do my homework.",
      'Por estar jugando videojuegos hasta tarde anoche, no pude hacer la tarea.',
      "À force de jouer aux jeux vidéo tard hier soir, je n'ai pas pu faire mes devoirs.",
      'Por ficar jogando até tarde ontem à noite, não consegui fazer a lição.',
      'เพราะมัวเล่นเกมจนดึกเมื่อคืน เลยทำการบ้านไม่ได้',
      'Gara-gara asyik main game sampai larut tadi malam, saya tak sempat mengerjakan PR.',
      'Vì mải chơi game đến khuya tối qua nên tôi không làm bài tập được.',
      '昨夜遅くまでゲームをしていたせいで、宿題ができませんでした。',
    ),
    why: L(
      'One action consumes time/effort and blocks another (negative result) → -느라(고); -(으)니까 a neutral reason, -지만 contrast, -거나 alternatives.',
      'Una acción consume tiempo/esfuerzo e impide otra (resultado negativo) → -느라(고); -(으)니까 razón neutra, -지만 contraste, -거나 alternativas.',
      "Une action consomme du temps/de l'effort et en empêche une autre (résultat négatif) → -느라(고) ; -(으)니까 raison neutre, -지만 contraste, -거나 alternatives.",
      'Uma ação consome tempo/esforço e impede outra (resultado negativo) → -느라(고); -(으)니까 razão neutra, -지만 contraste, -거나 alternativas.',
      'การกระทำหนึ่งกินเวลา/แรงและขัดอีกอย่าง (ผลลบ) → -느라(고); -(으)니까 เหตุผลกลาง ๆ, -지만 ขัดแย้ง, -거나 ทางเลือก',
      'Satu aksi menghabiskan waktu/tenaga dan menghalangi yang lain (hasil negatif) → -느라(고); -(으)니까 alasan netral, -지만 kontras, -거나 alternatif.',
      'Một hành động tốn thời gian/công sức và cản trở việc khác (kết quả xấu) → -느라(고); -(으)니까 lý do trung tính, -지만 tương phản, -거나 lựa chọn.',
      'ある動作が時間・労力を費やし他を妨げる（否定的結果）→ -느라(고)。-(으)니까 は中立の理由、-지만 は逆接、-거나 は選択。',
    ),
  },
]
