// app/seed/placement/n5.ts
import type { PlacementItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-5 placement items. Each targets a different TOPIK-5 grammar point;
 * `ko` matches grammars-n5.ts verbatim. Single-correct-answer crux drafted +
 * self-reviewed; Korean wife native review = documented final gate.
 */

export const N5_PLACEMENT: PlacementItem[] = [
  {
    ko: '-더니',
    level: 5,
    sentence: '동생이 아침부터 배가 {} 결국 병원에 갔어요.',
    answer: '아프더니',
    distractors: ['아프느라고', '아프든지', '아프거든'],
    trans: L(
      'My younger sibling had a stomachache from the morning, and ended up going to the hospital.',
      'A mi hermano menor le dolía el estómago desde la mañana y al final fue al hospital.',
      'Mon cadet avait mal au ventre depuis le matin, et a fini par aller à l\'hôpital.',
      'Meu irmão mais novo estava com dor de barriga desde de manhã e acabou indo ao hospital.',
      'น้องปวดท้องตั้งแต่เช้า สุดท้ายเลยไปโรงพยาบาล',
      'Adik saya sakit perut sejak pagi, akhirnya pergi ke rumah sakit.',
      'Em tôi đau bụng từ sáng, cuối cùng phải đi bệnh viện.',
      '弟は朝からお腹が痛かったあげく、結局病院に行きました。',
    ),
    why: L(
      'An observed past cause leading to a later result on a 3rd person → -더니; -느라고 a hindering cause, -든지 alternatives, -거든 a backgrounding "since".',
      'Una causa pasada observada que lleva a un resultado posterior en 3ª persona → -더니; -느라고 causa que estorba, -든지 alternativas, -거든 trasfondo "ya que".',
      'Une cause passée observée menant à un résultat ultérieur sur une 3ᵉ personne → -더니 ; -느라고 cause gênante, -든지 alternatives, -거든 « puisque » de contexte.',
      'Uma causa passada observada que leva a um resultado posterior em 3ª pessoa → -더니; -느라고 causa que atrapalha, -든지 alternativas, -거든 "já que" de fundo.',
      'เหตุในอดีตที่สังเกตเห็นนำสู่ผลภายหลังของบุรุษที่ 3 → -더니; -느라고 เหตุที่ขัดขวาง, -든지 ทางเลือก, -거든 "เพราะว่า" ปูพื้น',
      'Sebab lampau yang teramati menuju akibat kemudian pada orang ke-3 → -더니; -느라고 sebab yang menghambat, -든지 alternatif, -거든 "karena" latar.',
      'Nguyên nhân quá khứ quan sát được dẫn tới kết quả sau ở ngôi 3 → -더니; -느라고 nguyên nhân cản trở, -든지 lựa chọn, -거든 "vì" làm nền.',
      '三人称で観察した過去の原因が後の結果につながる → -더니。-느라고 は妨げの原因、-든지 は選択、-거든 は背景の「〜だから」。',
    ),
  },
  {
    ko: '-는 커녕',
    level: 5,
    sentence: '너무 바빠서 {} 주말에 쉬지도 못해요.',
    answer: '여행은커녕',
    distractors: ['여행보다', '여행처럼', '여행마다'],
    trans: L(
      "I'm so busy that, far from traveling, I can't even rest on weekends.",
      'Estoy tan ocupado que, lejos de viajar, ni siquiera puedo descansar el fin de semana.',
      "Je suis si occupé que, loin de voyager, je ne peux même pas me reposer le week-end.",
      'Estou tão ocupado que, longe de viajar, nem consigo descansar no fim de semana.',
      'ยุ่งมากจนอย่าว่าแต่เที่ยวเลย วันหยุดยังพักไม่ได้',
      'Saya sangat sibuk sampai jangankan jalan-jalan, akhir pekan pun tak bisa istirahat.',
      'Tôi bận đến mức đừng nói đi du lịch, đến cuối tuần cũng không nghỉ được.',
      '忙しすぎて、旅行どころか週末に休むこともできません。',
    ),
    why: L(
      '"Far from X, not even Y" → 여행은커녕 (noun + -는커녕, written solid); 여행보다 "than travel", 여행처럼 "like travel", 여행마다 "every trip" are well-formed particle strings but give the wrong meaning and don\'t license the dismissed-greater-option frame (쉬지도 못해요).',
      '"Lejos de X, ni siquiera Y" → 여행은커녕 (sustantivo + -는커녕, escrito junto); 여행보다 "que un viaje", 여행처럼 "como un viaje", 여행마다 "cada viaje" son cadenas de partícula válidas pero con sentido erróneo y no habilitan el marco de la opción mayor descartada (쉬지도 못해요).',
      "« Loin de X, même pas Y » → 여행은커녕 (nom + -는커녕, écrit collé) ; 여행보다 « qu'un voyage », 여행처럼 « comme un voyage », 여행마다 « chaque voyage » sont des chaînes de particule correctes mais au sens erroné et ne posent pas le cadre de l'option majeure écartée (쉬지도 못해요).",
      '"Longe de X, nem mesmo Y" → 여행은커녕 (substantivo + -는커녕, escrito junto); 여행보다 "do que viagem", 여행처럼 "como viagem", 여행마다 "cada viagem" são cadeias de partícula válidas mas de sentido errado e não montam o quadro da opção maior descartada (쉬지도 못해요).',
      '"อย่าว่าแต่ X เลย Y ก็ยัง" → 여행은커녕 (คำนาม + -는커녕 เขียนติดกัน); 여행보다 "กว่าการเที่ยว", 여행처럼 "เหมือนการเที่ยว", 여행마다 "ทุกการเที่ยว" เป็นวลีอนุภาคที่ถูกหลักแต่ความหมายผิดและไม่สร้างกรอบปฏิเสธสิ่งที่ใหญ่กว่า (쉬지도 못해요)',
      '"Jangankan X, Y pun tidak" → 여행은커녕 (nomina + -는커녕, ditulis menyatu); 여행보다 "daripada jalan-jalan", 여행처럼 "seperti jalan-jalan", 여행마다 "tiap perjalanan" adalah rangkaian partikel sah tapi salah makna dan tak membangun bingkai menolak opsi yang lebih besar (쉬지도 못해요).',
      '"Đừng nói X, đến Y cũng không" → 여행은커녕 (danh từ + -는커녕, viết liền); 여행보다 "hơn du lịch", 여행처럼 "như du lịch", 여행마다 "mỗi chuyến đi" là chuỗi trợ từ đúng ngữ pháp nhưng sai nghĩa và không tạo khung phủ nhận lựa chọn lớn hơn (쉬지도 못해요).',
      '「XどころかYさえ」→ 여행은커녕（名詞＋-는커녕、続けて表記）。여행보다「旅行より」、여행처럼「旅行のように」、여행마다「旅行ごとに」は文法上正しい助詞列だが意味が合わず、より大きな選択肢を退ける枠（쉬지도 못해요）を作らない。',
    ),
  },
  {
    ko: '-기에',
    level: 5,
    sentence: '가격이 너무 {} 한꺼번에 많이 사 두었습니다.',
    answer: '저렴하기에',
    distractors: ['저렴하더라도', '저렴하든지', '저렴한지'],
    trans: L(
      'Since the price was so cheap, I bought a lot all at once.',
      'Como el precio era tan barato, compré bastante de una vez.',
      "Le prix étant si bas, j'en ai acheté beaucoup d'un coup.",
      'Como o preço estava tão barato, comprei bastante de uma vez.',
      'เพราะราคาถูกมาก ฉันเลยซื้อตุนไว้เยอะในคราวเดียว',
      'Karena harganya sangat murah, saya membeli banyak sekaligus.',
      'Vì giá quá rẻ nên tôi đã mua nhiều một lúc.',
      '価格があまりに安かったので、一度にたくさん買っておきました。',
    ),
    why: L(
      'A reasoned cause grounding the speaker\'s own past act → -기에; -더라도 is concession, -든지 alternatives, -(으)ㄴ지 an embedded question — none states the grounds.',
      'Una causa razonada que motiva el acto pasado propio → -기에; -더라도 concesión, -든지 alternativas, -(으)ㄴ지 pregunta incrustada — ninguna da el motivo.',
      "Une cause raisonnée motivant l'acte passé du locuteur → -기에 ; -더라도 concession, -든지 alternatives, -(으)ㄴ지 question enchâssée — aucune ne donne le motif.",
      'Uma causa raciocinada que motiva o ato passado do falante → -기에; -더라도 concessão, -든지 alternativas, -(으)ㄴ지 pergunta encaixada — nenhuma dá o motivo.',
      'เหตุผลที่ใช้คิดเป็นมูลเหตุของการกระทำในอดีตของผู้พูด → -기에; -더라도 ยอมรับ, -든지 ทางเลือก, -(으)ㄴ지 คำถามฝัง — ไม่มีอันใดระบุมูลเหตุ',
      'Sebab beralasan yang melatari tindakan lampau penutur → -기에; -더라도 konsesi, -든지 alternatif, -(으)ㄴ지 pertanyaan tersemat — tak ada yang menyatakan dasar.',
      'Lý do được suy xét làm căn cứ cho hành động quá khứ của người nói → -기에; -더라도 nhượng bộ, -든지 lựa chọn, -(으)ㄴ지 câu hỏi lồng — không cái nào nêu căn cứ.',
      '話し手自身の過去の行為の根拠となる理路ある原因 → -기에。-더라도 は譲歩、-든지 は選択、-(으)ㄴ지 は埋め込み疑問で、根拠を示さない。',
    ),
  },
  {
    ko: '-(으)ㄹ 뿐이다',
    level: 5,
    sentence: '저는 제 할 일을 {} 특별한 건 없습니다.',
    answer: '했을 뿐이지',
    distractors: ['했더라도', '했든지', '했다시피'],
    trans: L(
      'I merely did what I had to do; there is nothing special.',
      'Yo solo hice lo que tenía que hacer; no hay nada especial.',
      "Je n'ai fait que ce que je devais faire ; il n'y a rien de spécial.",
      'Eu apenas fiz o que tinha de fazer; não há nada de especial.',
      'ผมแค่ทำในสิ่งที่ต้องทำ ไม่มีอะไรพิเศษ',
      'Saya hanya melakukan tugas saya; tidak ada yang istimewa.',
      'Tôi chỉ làm việc mình phải làm thôi, không có gì đặc biệt.',
      '私は自分のすべきことをしただけで、特別なことはありません。',
    ),
    why: L(
      '"Merely / nothing more than" → -(으)ㄹ 뿐이다 (here connective 뿐이지); -더라도 concession, -든지 alternatives, -다시피 "as you know".',
      '"Solo / nada más que" → -(으)ㄹ 뿐이다 (aquí conectivo 뿐이지); -더라도 concesión, -든지 alternativas, -다시피 "como sabes".',
      '« Seulement / rien de plus que » → -(으)ㄹ 뿐이다 (ici connectif 뿐이지) ; -더라도 concession, -든지 alternatives, -다시피 « comme vous savez ».',
      '"Apenas / nada além de" → -(으)ㄹ 뿐이다 (aqui conectivo 뿐이지); -더라도 concessão, -든지 alternativas, -다시피 "como você sabe".',
      '"แค่ / ไม่มากไปกว่า" → -(으)ㄹ 뿐이다 (ที่นี่เชื่อม 뿐이지); -더라도 ยอมรับ, -든지 ทางเลือก, -다시피 "อย่างที่รู้"',
      '"Hanya / tak lebih dari" → -(으)ㄹ 뿐이다 (di sini penghubung 뿐이지); -더라도 konsesi, -든지 alternatif, -다시피 "seperti yang diketahui".',
      '"Chỉ / không hơn" → -(으)ㄹ 뿐이다 (ở đây nối 뿐이지); -더라도 nhượng bộ, -든지 lựa chọn, -다시피 "như đã biết".',
      '「〜だけ・〜にすぎない」→ -(으)ㄹ 뿐이다（ここでは接続の 뿐이지）。-더라도 は譲歩、-든지 は選択、-다시피 は「ご存じのとおり」。',
    ),
  },
  {
    ko: '-자',
    level: 5,
    sentence: '문을 열{} 고양이가 밖으로 뛰어나갔어요.',
    answer: '자',
    distractors: ['도록', '거나', '더라도'],
    trans: L(
      'The moment I opened the door, the cat dashed outside.',
      'En el momento en que abrí la puerta, el gato salió corriendo.',
      "Au moment où j'ai ouvert la porte, le chat s'est précipité dehors.",
      'No momento em que abri a porta, o gato disparou para fora.',
      'พอเปิดประตู แมวก็วิ่งออกไปข้างนอกทันที',
      'Begitu saya membuka pintu, kucing langsung berlari keluar.',
      'Vừa mở cửa ra thì con mèo lao ra ngoài.',
      'ドアを開けるやいなや、猫が外へ飛び出しました。',
    ),
    why: L(
      'A formal "the moment X, then Y" with an immediate consequence → -자; -도록 purpose/degree, -거나 alternatives, -더라도 concession.',
      'Un "en el momento en que X, Y" formal con consecuencia inmediata → -자; -도록 propósito/grado, -거나 alternativas, -더라도 concesión.',
      "Un « au moment où X, Y » formel à conséquence immédiate → -자 ; -도록 but/degré, -거나 alternatives, -더라도 concession.",
      'Um "no momento em que X, Y" formal com consequência imediata → -자; -도록 propósito/grau, -거나 alternativas, -더라도 concessão.',
      '"พอ X ก็ Y" แบบทางการที่มีผลทันที → -자; -도록 จุดประสงค์/ระดับ, -거나 ทางเลือก, -더라도 ยอมรับ',
      'Pola formal "begitu X, lalu Y" dengan akibat seketika → -자; -도록 tujuan/derajat, -거나 alternatif, -더라도 konsesi.',
      'Mẫu trang trọng "vừa X thì Y" với hệ quả tức thì → -자; -도록 mục đích/mức độ, -거나 lựa chọn, -더라도 nhượng bộ.',
      '即時の結果を伴う改まった「XするやY」→ -자。-도록 は目的・程度、-거나 は選択、-더라도 は譲歩。',
    ),
  },
  {
    ko: '-고도',
    level: 5,
    sentence: '그 사람은 잘못을 {} 사과하지 않았어요.',
    answer: '하고도',
    distractors: ['하느라고', '하도록', '하든지'],
    trans: L(
      'That person did wrong and yet did not apologize.',
      'Esa persona hizo algo mal y aun así no se disculpó.',
      "Cette personne a mal agi et n'a pourtant pas présenté d'excuses.",
      'Aquela pessoa errou e mesmo assim não pediu desculpas.',
      'คนนั้นทำผิดแล้วก็ยังไม่ขอโทษ',
      'Orang itu berbuat salah namun tetap tidak minta maaf.',
      'Người đó làm sai mà vẫn không xin lỗi.',
      'その人は過ちを犯しておきながら、謝りませんでした。',
    ),
    why: L(
      'One subject does X and yet not the expected Y (concessive) → -고도; -느라고 a hindering cause, -도록 purpose, -든지 alternatives.',
      'Un mismo sujeto hace X y aun así no la Y esperada (concesivo) → -고도; -느라고 causa que estorba, -도록 propósito, -든지 alternativas.',
      "Un même sujet fait X et pourtant pas le Y attendu (concessif) → -고도 ; -느라고 cause gênante, -도록 but, -든지 alternatives.",
      'Um mesmo sujeito faz X e mesmo assim não o Y esperado (concessivo) → -고도; -느라고 causa que atrapalha, -도록 propósito, -든지 alternativas.',
      'ประธานเดียวทำ X แต่กลับไม่ทำ Y ที่คาด (สัมปทาน) → -고도; -느라고 เหตุที่ขัดขวาง, -도록 จุดประสงค์, -든지 ทางเลือก',
      'Satu subjek melakukan X namun tak melakukan Y yang diharap (konsesif) → -고도; -느라고 sebab yang menghambat, -도록 tujuan, -든지 alternatif.',
      'Một chủ ngữ làm X mà vẫn không làm Y mong đợi (nhượng bộ) → -고도; -느라고 nguyên nhân cản trở, -도록 mục đích, -든지 lựa chọn.',
      '同一主語がXしておきながら期待のYをしない（譲歩）→ -고도。-느라고 は妨げの原因、-도록 は目的、-든지 は選択。',
    ),
  },
]
