// app/seed/placement/n6.ts
import type { PlacementItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-6 placement items. Each targets a different TOPIK-6 grammar point;
 * `ko` matches grammars-n6.ts verbatim. Single-correct-answer crux drafted +
 * self-reviewed; Korean wife native review = documented final gate.
 */

export const N6_PLACEMENT: PlacementItem[] = [
  {
    ko: '-ㄴ들',
    level: 6,
    sentence: '이제 와서 후회한{} 무슨 소용이 있겠어요?',
    answer: '들',
    distractors: ['다면', '다거나', '다시피'],
    trans: L(
      'Even if you regret it now, what good would it do?',
      'Aunque te arrepientas ahora, ¿de qué serviría?',
      "Même si tu le regrettes maintenant, à quoi bon ?",
      'Mesmo que você se arrependa agora, de que adiantaria?',
      'ถึงจะมาเสียใจตอนนี้ก็ไม่มีประโยชน์อะไรหรอก',
      'Sekalipun menyesal sekarang, apa gunanya?',
      'Bây giờ có hối hận thì cũng đâu ích gì?',
      '今さら後悔したところで何の役に立つでしょうか。',
    ),
    why: L(
      'A rhetorical "even if X, it\'s futile" → -ㄴ들; -다면 a plain condition, -다거나 listing, -다시피 "as you know".',
      'Un "aunque X, es en vano" retórico → -ㄴ들; -다면 condición simple, -다거나 enumeración, -다시피 "como sabes".',
      '« Même si X, c\'est vain » rhétorique → -ㄴ들 ; -다면 condition simple, -다거나 énumération, -다시피 « comme vous savez ».',
      'Um "mesmo que X, é em vão" retórico → -ㄴ들; -다면 condição simples, -다거나 enumeração, -다시피 "como você sabe".',
      '"ถึงจะ X ก็เปล่าประโยชน์" เชิงวาทศิลป์ → -ㄴ들; -다면 เงื่อนไขธรรมดา, -다거나 เรียง, -다시피 "อย่างที่รู้"',
      '"Sekalipun X, sia-sia" retoris → -ㄴ들; -다면 syarat biasa, -다거나 pendaftaran, -다시피 "seperti yang diketahui".',
      '"Dù X cũng vô ích" mang tính tu từ → -ㄴ들; -다면 điều kiện thường, -다거나 liệt kê, -다시피 "như đã biết".',
      '反語的な「Xしたところで無駄」→ -ㄴ들。-다면 は単純条件、-다거나 は列挙、-다시피 は「ご存じのとおり」。',
    ),
  },
  {
    ko: '-(으)ㄹ망정',
    level: 6,
    sentence: '비록 가난할{} 양심을 팔지는 않겠습니다.',
    answer: '망정',
    distractors: ['수록', '뿐더러', '거니와'],
    trans: L(
      'Even though I may be poor, I will never sell my conscience.',
      'Aunque sea pobre, jamás venderé mi conciencia.',
      'Même si je suis pauvre, je ne vendrai jamais ma conscience.',
      'Mesmo que eu seja pobre, jamais venderei a minha consciência.',
      'แม้จะยากจน แต่ก็จะไม่ขายมโนธรรมเด็ดขาด',
      'Sekalipun miskin, saya tak akan menjual hati nurani.',
      'Dẫu có nghèo, tôi cũng quyết không bán lương tâm.',
      'たとえ貧しくとも、良心を売ることはしません。',
    ),
    why: L(
      '비록 + a conceded lesser state set against a firmly refused act → -(으)ㄹ망정; -(으)ㄹ수록 is proportionality, -(으)ㄹ뿐더러 and -거니와 are additive ("not only") — none fits the 비록…-(으)ㄹ망정 concessive frame.',
      '비록 + un estado menor concedido frente a un acto rechazado con firmeza → -(으)ㄹ망정; -(으)ㄹ수록 es proporcionalidad, -(으)ㄹ뿐더러 y -거니와 son aditivos ("no solo") — ninguno encaja en el marco concesivo 비록…-(으)ㄹ망정.',
      '비록 + un état moindre concédé face à un acte fermement refusé → -(으)ㄹ망정 ; -(으)ㄹ수록 est une proportion, -(으)ㄹ뿐더러 et -거니와 sont additifs (« non seulement ») — aucun ne convient au cadre concessif 비록…-(으)ㄹ망정.',
      '비록 + um estado menor concedido diante de um ato firmemente recusado → -(으)ㄹ망정; -(으)ㄹ수록 é proporção, -(으)ㄹ뿐더러 e -거니와 são aditivos ("não só") — nenhum cabe no quadro concessivo 비록…-(으)ㄹ망정.',
      '비록 + สภาพด้อยที่ยอมรับ ตรงข้ามกับการกระทำที่ปฏิเสธหนักแน่น → -(으)ㄹ망정; -(으)ㄹ수록 คือสัดส่วน, -(으)ㄹ뿐더러 และ -거니와 เป็นการเสริม ("ไม่เพียง") — ไม่มีอันใดเข้ากรอบสัมปทาน 비록…-(으)ㄹ망정',
      '비록 + keadaan rendah yang diakui berhadapan dengan tindakan yang tegas ditolak → -(으)ㄹ망정; -(으)ㄹ수록 adalah proporsi, -(으)ㄹ뿐더러 dan -거니와 bersifat aditif ("tak hanya") — tak ada yang cocok dengan bingkai konsesif 비록…-(으)ㄹ망정.',
      '비록 + một trạng thái kém được nhượng đối lại hành động bị từ chối dứt khoát → -(으)ㄹ망정; -(으)ㄹ수록 là tỉ lệ, -(으)ㄹ뿐더러 và -거니와 mang tính bổ sung ("không những") — không cái nào hợp khung nhượng bộ 비록…-(으)ㄹ망정.',
      '비록＋譲歩した劣位の状態と断固拒否する行為の対比 → -(으)ㄹ망정。-(으)ㄹ수록 は比例、-(으)ㄹ뿐더러 と -거니와 は付加（「〜だけでなく」）で、いずれも 비록…-(으)ㄹ망정 の譲歩枠に合わない。',
    ),
  },
  {
    ko: '-기로서니',
    level: 6,
    sentence: '아무리 화가 {} 그렇게 말하면 안 되지요.',
    answer: '나기로서니',
    distractors: ['나더라도', '나거니와', '나다시피'],
    trans: L(
      'No matter how angry you may be, you shouldn\'t speak like that.',
      'Por muy enfadado que estés, no deberías hablar así.',
      'Aussi en colère sois-tu, tu ne devrais pas parler ainsi.',
      'Por mais bravo que você esteja, não deveria falar assim.',
      'ต่อให้โกรธแค่ไหน ก็ไม่ควรพูดแบบนั้น',
      'Sekalipun semarah apa pun, tidak seharusnya bicara begitu.',
      'Dù có tức giận đến đâu, cũng không nên nói như vậy.',
      'いくら腹が立つからといって、そんなふうに言ってはいけません。',
    ),
    why: L(
      '아무리 + "just because X (you still shouldn\'t)" reproach → -기로서니; -더라도 is a neutral concession, -거니와 adds a point, -다시피 "as you know".',
      '아무리 + reproche "por más que X (no por eso)" → -기로서니; -더라도 concesión neutra, -거니와 añade un punto, -다시피 "como sabes".',
      '아무리 + reproche « ce n\'est pas parce que X » → -기로서니 ; -더라도 concession neutre, -거니와 ajoute un point, -다시피 « comme vous savez ».',
      '아무리 + reprovação "só porque X (nem por isso)" → -기로서니; -더라도 concessão neutra, -거니와 acrescenta um ponto, -다시피 "como você sabe".',
      '아무리 + การต่อว่า "ต่อให้ X ก็ไม่ใช่ว่า" → -기로서니; -더라도 ยอมรับกลาง ๆ, -거니와 เสริมประเด็น, -다시피 "อย่างที่รู้"',
      '아무리 + teguran "sekalipun X bukan berarti" → -기로서니; -더라도 konsesi netral, -거니와 menambah poin, -다시피 "seperti yang diketahui".',
      '아무리 + lời trách "dù X cũng không vì thế mà" → -기로서니; -더라도 nhượng bộ trung tính, -거니와 thêm ý, -다시피 "như đã biết".',
      '아무리＋「Xだからといって」という叱責 → -기로서니。-더라도 は中立の譲歩、-거니와 は付加、-다시피 は「ご存じのとおり」。',
    ),
  },
  {
    ko: '-다시피',
    level: 6,
    sentence: '여러분도 {} 이번 사업은 큰 성공을 거두었습니다.',
    answer: '아시다시피',
    distractors: ['아는데도', '알기로서니', '알다가는'],
    trans: L(
      'As you all know, this project achieved great success.',
      'Como todos saben, este proyecto logró un gran éxito.',
      'Comme vous le savez tous, ce projet a remporté un grand succès.',
      'Como todos vocês sabem, este projeto alcançou um grande sucesso.',
      'อย่างที่ทุกท่านทราบ โครงการครั้งนี้ประสบความสำเร็จอย่างมาก',
      'Seperti yang Anda semua ketahui, proyek ini meraih sukses besar.',
      'Như quý vị đều biết, dự án lần này đã thành công lớn.',
      '皆さんもご存じのとおり、今回の事業は大きな成功を収めました。',
    ),
    why: L(
      '"As you know/see" appeals to shared knowledge → -다시피; -는데도 concessive, -기로서니 reproachful concession, -다가는 a warning of bad outcome.',
      '"Como saben/ven" apela al saber compartido → -다시피; -는데도 concesivo, -기로서니 concesión de reproche, -다가는 advertencia de mal resultado.',
      '« Comme vous savez/voyez » fait appel au savoir partagé → -다시피 ; -는데도 concessif, -기로서니 concession de reproche, -다가는 avertissement de mauvais résultat.',
      '"Como sabem/veem" apela ao saber compartilhado → -다시피; -는데도 concessivo, -기로서니 concessão de reprovação, -다가는 aviso de mau resultado.',
      '"อย่างที่ทราบ/เห็น" อ้างความรู้ร่วม → -다시피; -는데도 สัมปทาน, -기로서니 สัมปทานเชิงต่อว่า, -다가는 เตือนผลร้าย',
      '"Seperti yang Anda tahu/lihat" merujuk pengetahuan bersama → -다시피; -는데도 konsesif, -기로서니 konsesi teguran, -다가는 peringatan akibat buruk.',
      '"Như quý vị biết/thấy" viện đến hiểu biết chung → -다시피; -는데도 nhượng bộ, -기로서니 nhượng bộ kèm trách, -다가는 cảnh báo kết quả xấu.',
      '「ご存じ・ご覧のとおり」共有知に訴える → -다시피。-는데도 は譲歩、-기로서니 は叱責の譲歩、-다가는 は悪い結果の警告。',
    ),
  },
  {
    ko: '-(으)ㄴ/는 이상',
    level: 6,
    sentence: '이미 계약서에 서명한 {} 약속을 지켜야 합니다.',
    answer: '이상',
    distractors: ['김에', '대로', '채로'],
    trans: L(
      'Now that you have already signed the contract, you must keep your promise.',
      'Ya que ya has firmado el contrato, debes cumplir tu promesa.',
      'Dès lors que vous avez déjà signé le contrat, vous devez tenir votre promesse.',
      'Já que você já assinou o contrato, deve cumprir a promessa.',
      'ในเมื่อเซ็นสัญญาไปแล้ว ก็ต้องรักษาคำมั่นสัญญา',
      'Karena Anda sudah menandatangani kontrak, Anda harus menepati janji.',
      'Một khi đã ký hợp đồng thì phải giữ lời hứa.',
      'すでに契約書に署名した以上、約束を守らなければなりません。',
    ),
    why: L(
      '"Now that / given that X, then obligation" → -(으)ㄴ/는 이상; -(으)ㄴ 김에 "while at it", -(으)ㄴ 대로 "as", -(으)ㄴ 채로 "in the state of".',
      '"Ya que / dado que X, obligación" → -(으)ㄴ/는 이상; -(으)ㄴ 김에 "ya que estamos", -(으)ㄴ 대로 "según", -(으)ㄴ 채로 "en el estado de".',
      '« Dès lors que X, obligation » → -(으)ㄴ/는 이상 ; -(으)ㄴ 김에 « tant qu\'à », -(으)ㄴ 대로 « selon », -(으)ㄴ 채로 « dans l\'état de ».',
      '"Já que / dado que X, obrigação" → -(으)ㄴ/는 이상; -(으)ㄴ 김에 "já que", -(으)ㄴ 대로 "conforme", -(으)ㄴ 채로 "no estado de".',
      '"ในเมื่อ X จึงต้อง" → -(으)ㄴ/는 이상; -(으)ㄴ 김에 "ถือโอกาส", -(으)ㄴ 대로 "ตามที่", -(으)ㄴ 채로 "ในสภาพที่"',
      '"Karena/sudah begitu X, maka wajib" → -(으)ㄴ/는 이상; -(으)ㄴ 김에 "sekalian", -(으)ㄴ 대로 "sesuai", -(으)ㄴ 채로 "dalam keadaan".',
      '"Một khi đã X thì phải" → -(으)ㄴ/는 이상; -(으)ㄴ 김에 "nhân tiện", -(으)ㄴ 대로 "theo như", -(으)ㄴ 채로 "trong tình trạng".',
      '「Xした以上は義務」→ -(으)ㄴ/는 이상。-(으)ㄴ 김에 は「ついでに」、-(으)ㄴ 대로 は「〜のとおり」、-(으)ㄴ 채로 は「〜のまま」。',
    ),
  },
  {
    ko: '-거니와',
    level: 6,
    sentence: '그분은 실력도 {} 인품도 훌륭하십니다.',
    answer: '뛰어나거니와',
    distractors: ['뛰어나거든', '뛰어나더라도', '뛰어나다가는'],
    trans: L(
      'That person is not only outstanding in skill but also excellent in character.',
      'Esa persona no solo destaca en habilidad, sino que también es excelente de carácter.',
      'Cette personne est non seulement remarquable en compétence, mais aussi excellente de caractère.',
      'Aquela pessoa não só se destaca em habilidade, como também é excelente de caráter.',
      'ท่านผู้นั้นไม่เพียงเก่ง แต่ยังมีอุปนิสัยดีเยี่ยม',
      'Beliau tak hanya unggul dalam kemampuan, tetapi juga berbudi luhur.',
      'Vị ấy không những giỏi giang mà nhân cách cũng tuyệt vời.',
      'あの方は実力も優れているうえに、人柄も立派でいらっしゃいます。',
    ),
    why: L(
      '"Not only X but also Y" additive in formal register → -거니와; -거든 backgrounds, -더라도 concedes, -다가는 warns of a bad outcome.',
      '"No solo X sino también Y" aditivo en registro formal → -거니와; -거든 da trasfondo, -더라도 concede, -다가는 advierte de un mal resultado.',
      '« Non seulement X mais aussi Y » additif en registre formel → -거니와 ; -거든 contextualise, -더라도 concède, -다가는 avertit d\'un mauvais résultat.',
      '"Não só X mas também Y" aditivo em registro formal → -거니와; -거든 dá pano de fundo, -더라도 concede, -다가는 avisa de mau resultado.',
      '"ไม่เพียง X แต่ยัง Y" เชิงเสริมในภาษาทางการ → -거니와; -거든 ปูพื้น, -더라도 ยอมรับ, -다가는 เตือนผลร้าย',
      '"Tak hanya X tetapi juga Y" aditif dalam register formal → -거니와; -거든 melatari, -더라도 mengakui, -다가는 memperingatkan akibat buruk.',
      '"Không những X mà còn Y" mang tính bổ sung trong văn trang trọng → -거니와; -거든 làm nền, -더라도 nhượng bộ, -다가는 cảnh báo kết quả xấu.',
      '改まった文体での「Xうえにも Y」付加 → -거니와。-거든 は背景、-더라도 は譲歩、-다가는 は悪い結果の警告。',
    ),
  },
]
