// AUTO-GENERATED by scripts/escape-i18n-gen.mjs - do not edit by hand.
import { createEscapeTranslator, type EscapeLevelTranslations } from '../../../create-translator'
import { enLevel08 } from './en'
import { frLevel08 } from './fr'
import { ptBRLevel08 } from './pt-BR'
import { thLevel08 } from './th'
import { idLevel08 } from './id'
import { viLevel08 } from './vi'
import { jaLevel08 } from './ja'

export const LEVEL_08_TRANSLATIONS: EscapeLevelTranslations = {
  "en": enLevel08,
  "fr": frLevel08,
  "pt-BR": ptBRLevel08,
  "th": thLevel08,
  "id": idLevel08,
  "vi": viLevel08,
  "ja": jaLevel08,
}

export const t = createEscapeTranslator(LEVEL_08_TRANSLATIONS)
