import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * Extra confusable grammar/ending pairs for TOPIK 1 (location vs action particle
 * 에/에서, and recipient 에게 vs target 에). a/b match grammars-n1.ts verbatim.
 * 2 pairs x 3 two-choice discrimination items, 8-locale trans + why.
 *
 * Drafted + Korean-lens adversarially verified (single-answer-per-item crux,
 * naturalness, particle selection, 8-locale fidelity). Native (Korean wife)
 * review is the documented final gate.
 */
export const N1_PAIRS_EXTRA: ConfusablePair[] = [
  {
    id: 'e-eseo',
    a: '에',
    b: '에서',
    note: L(
      '에 marks a static location (where something EXISTS), a destination, or a point in time; 에서 marks the place where a DYNAMIC action happens, or an origin ("from").',
      '에 marca una ubicación estática (donde algo EXISTE), un destino o un momento; 에서 marca el lugar donde ocurre una ACCIÓN dinámica, o un origen ("desde").',
      "에 marque un lieu statique (où quelque chose EXISTE), une destination ou un moment ; 에서 marque le lieu où se déroule une ACTION dynamique, ou une origine (« depuis »).",
      '에 marca um lugar estático (onde algo EXISTE), um destino ou um momento; 에서 marca o lugar onde acontece uma AÇÃO dinâmica, ou uma origem ("de").',
      '에 บอกสถานที่อยู่นิ่ง (ที่บางสิ่งมีอยู่) ปลายทาง หรือจุดเวลา ส่วน 에서 บอกสถานที่ที่เกิดการกระทำที่เคลื่อนไหว หรือจุดเริ่มต้น ("จาก")',
      '에 menandai lokasi statis (tempat sesuatu BERADA), tujuan, atau titik waktu; 에서 menandai tempat AKSI dinamis terjadi, atau asal ("dari").',
      '에 đánh dấu vị trí tĩnh (nơi cái gì TỒN TẠI), đích đến hoặc thời điểm; 에서 đánh dấu nơi diễn ra HÀNH ĐỘNG động, hoặc nguồn gốc ("từ").',
      '에 は静的な場所（何かが「存在する」所）・到達点・時点を表し、에서 は動的な「動作」が行われる場所、または起点（〜から）を表す。',
    ),
    items: [
      {
        sentence: '주말마다 도서관{} 공부해요.',
        optionA: '에',
        optionB: '에서',
        answer: 'b',
        trans: L(
          'Every weekend I study at the library.',
          'Cada fin de semana estudio en la biblioteca.',
          'Chaque week-end, j’étudie à la bibliothèque.',
          'Todo fim de semana eu estudo na biblioteca.',
          'ทุกสุดสัปดาห์ฉันอ่านหนังสือที่ห้องสมุด',
          'Setiap akhir pekan saya belajar di perpustakaan.',
          'Mỗi cuối tuần tôi học ở thư viện.',
          '毎週末、図書館で勉強します。',
        ),
        why: L(
          '공부하다 is a dynamic action performed at that place, so the action-location particle 에서 is required; 에 only marks existence or a destination, not where an action happens.',
          '공부하다 es una acción dinámica realizada en ese lugar, así que se exige la partícula de lugar de acción 에서; 에 solo marca existencia o destino, no dónde ocurre una acción.',
          '공부하다 est une action dynamique faite à cet endroit, donc la particule de lieu d’action 에서 est requise ; 에 ne marque que l’existence ou la destination, pas le lieu d’une action.',
          '공부하다 é uma ação dinâmica feita nesse lugar, então exige-se a partícula de lugar de ação 에서; 에 só marca existência ou destino, não onde uma ação ocorre.',
          '공부하다 เป็นการกระทำที่เคลื่อนไหวซึ่งทำที่สถานที่นั้น จึงต้องใช้อนุภาคสถานที่ของการกระทำ 에서; 에 บอกแค่การมีอยู่หรือปลายทาง ไม่ได้บอกที่ที่เกิดการกระทำ',
          '공부하다 adalah aksi dinamis yang dilakukan di tempat itu, jadi partikel lokasi aksi 에서 diperlukan; 에 hanya menandai keberadaan atau tujuan, bukan tempat aksi terjadi.',
          '공부하다 là hành động động được thực hiện tại nơi đó, nên cần tiểu từ địa điểm hành động 에서; 에 chỉ đánh dấu sự tồn tại hoặc đích đến, không phải nơi diễn ra hành động.',
          '공부하다 はその場所で行う動的な動作なので動作の場所を表す 에서 が必要。에 は存在や到達点を表すだけで、動作の場所には使えない。',
        ),
      },
      {
        sentence: '냉장고 안{} 우유가 있어요.',
        optionA: '에',
        optionB: '에서',
        answer: 'a',
        trans: L(
          'There is milk inside the fridge.',
          'Hay leche dentro del refrigerador.',
          'Il y a du lait dans le réfrigérateur.',
          'Há leite dentro da geladeira.',
          'มีนมอยู่ในตู้เย็น',
          'Ada susu di dalam kulkas.',
          'Có sữa ở trong tủ lạnh.',
          '冷蔵庫の中に牛乳があります。',
        ),
        why: L(
          '있다 states existence at a static location, which takes 에; 에서 marks where an action occurs, but nothing is being done here — the milk simply exists.',
          '있다 indica existencia en una ubicación estática, que lleva 에; 에서 marca dónde ocurre una acción, pero aquí no se hace nada: la leche simplemente existe.',
          '있다 exprime l’existence à un lieu statique, qui prend 에 ; 에서 marque le lieu d’une action, mais ici rien n’est fait — le lait existe simplement.',
          '있다 indica existência em um lugar estático, que leva 에; 에서 marca onde ocorre uma ação, mas aqui nada é feito — o leite simplesmente existe.',
          '있다 บอกการมีอยู่ ณ สถานที่อยู่นิ่ง ซึ่งใช้ 에; 에서 บอกที่ที่เกิดการกระทำ แต่ที่นี่ไม่มีการกระทำ นมแค่มีอยู่เฉย ๆ',
          '있다 menyatakan keberadaan di lokasi statis, yang memakai 에; 에서 menandai tempat aksi terjadi, tapi di sini tidak ada aksi — susunya hanya ada.',
          '있다 nêu sự tồn tại ở vị trí tĩnh, dùng 에; 에서 đánh dấu nơi diễn ra hành động, nhưng ở đây không có hành động — sữa chỉ tồn tại.',
          '있다 は静的な場所での存在を表し 에 を取る。에서 は動作の場所を表すが、ここでは動作がなく牛乳が存在するだけ。',
        ),
      },
      {
        sentence: '내일 아침 일찍 공항{} 가야 해요.',
        optionA: '에',
        optionB: '에서',
        answer: 'a',
        trans: L(
          'I have to go to the airport early tomorrow morning.',
          'Tengo que ir al aeropuerto temprano mañana por la mañana.',
          'Je dois aller à l’aéroport tôt demain matin.',
          'Tenho que ir ao aeroporto cedo amanhã de manhã.',
          'พรุ่งนี้เช้าฉันต้องไปสนามบินแต่เช้า',
          'Besok pagi-pagi saya harus pergi ke bandara.',
          'Sáng sớm mai tôi phải đi đến sân bay.',
          '明日の朝早く空港へ行かなければなりません。',
        ),
        why: L(
          'With the motion verb 가다, 공항 is the destination, which takes 에; 에서 would mean the action starts FROM the airport (origin), contradicting "go to the airport".',
          'Con el verbo de movimiento 가다, 공항 es el destino, que lleva 에; 에서 significaría que la acción parte DESDE el aeropuerto (origen), contradiciendo "ir al aeropuerto".',
          'Avec le verbe de mouvement 가다, 공항 est la destination, qui prend 에 ; 에서 voudrait dire que l’action part DE l’aéroport (origine), ce qui contredit « aller à l’aéroport ».',
          'Com o verbo de movimento 가다, 공항 é o destino, que leva 에; 에서 significaria que a ação parte DO aeroporto (origem), contradizendo "ir ao aeroporto".',
          'กับกริยาเคลื่อนที่ 가다 공항 เป็นปลายทางซึ่งใช้ 에; 에서 จะหมายความว่าการกระทำเริ่มจากสนามบิน (จุดเริ่มต้น) ซึ่งขัดกับ "ไปสนามบิน"',
          'Dengan verba gerak 가다, 공항 adalah tujuan, yang memakai 에; 에서 berarti aksi berangkat DARI bandara (asal), bertentangan dengan "pergi ke bandara".',
          'Với động từ chuyển động 가다, 공항 là đích đến, dùng 에; 에서 sẽ có nghĩa hành động xuất phát TỪ sân bay (nguồn gốc), trái với "đi đến sân bay".',
          '移動動詞 가다 では 공항 は到達点なので 에 を取る。에서 だと空港「から」出発する（起点）意味になり、「空港へ行く」と矛盾する。',
        ),
      },
    ],
  },
  {
    id: 'ege-e',
    a: '에게 / 한테 / 께',
    b: '에',
    note: L(
      'For the recipient of giving/sending verbs, use 에게/한테/께 when the recipient is a PERSON or animal (animate); use 에 when the recipient is a PLACE, organization, plant, or thing (inanimate).',
      'Para el destinatario de verbos de dar/enviar, usa 에게/한테/께 cuando el destinatario es una PERSONA o animal (animado); usa 에 cuando es un LUGAR, organización, planta o cosa (inanimado).',
      "Pour le destinataire des verbes de don/envoi, employez 에게/한테/께 quand le destinataire est une PERSONNE ou un animal (animé) ; employez 에 quand c’est un LIEU, une organisation, une plante ou une chose (inanimé).",
      'Para o destinatário de verbos de dar/enviar, use 에게/한테/께 quando o destinatário é uma PESSOA ou animal (animado); use 에 quando é um LUGAR, organização, planta ou coisa (inanimado).',
      'สำหรับผู้รับของกริยาให้/ส่ง ให้ใช้ 에게/한테/께 เมื่อผู้รับเป็นคนหรือสัตว์ (มีชีวิต); ใช้ 에 เมื่อผู้รับเป็นสถานที่ องค์กร พืช หรือสิ่งของ (ไม่มีชีวิต)',
      'Untuk penerima pada verba memberi/mengirim, pakai 에게/한테/께 jika penerimanya ORANG atau hewan (bernyawa); pakai 에 jika penerimanya TEMPAT, organisasi, tumbuhan, atau benda (tak bernyawa).',
      'Với người nhận của động từ cho/gửi, dùng 에게/한테/께 khi người nhận là NGƯỜI hoặc động vật (hữu sinh); dùng 에 khi người nhận là NƠI CHỐN, tổ chức, cây cối hoặc vật (vô sinh).',
      '授与・送付の動詞の受け手には、受け手が人・動物（有情）なら 에게/한테/께、場所・組織・植物・物（無情）なら 에 を使う。',
    ),
    items: [
      {
        sentence: '어제 할머니{} 편지를 보냈어요.',
        optionA: '께',
        optionB: '에',
        answer: 'a',
        trans: L(
          'Yesterday I sent a letter to my grandmother.',
          'Ayer le envié una carta a mi abuela.',
          'Hier, j’ai envoyé une lettre à ma grand-mère.',
          'Ontem enviei uma carta para a minha avó.',
          'เมื่อวานฉันส่งจดหมายถึงคุณยาย',
          'Kemarin saya mengirim surat kepada nenek.',
          'Hôm qua tôi đã gửi thư cho bà.',
          '昨日、祖母に手紙を送りました。',
        ),
        why: L(
          '할머니 is a person (and an honored elder), so the animate recipient marker 께 (honorific of 에게) is correct; 에 is only for inanimate recipients like places.',
          '할머니 es una persona (y mayor respetada), así que el marcador de destinatario animado 께 (honorífico de 에게) es correcto; 에 solo es para destinatarios inanimados como lugares.',
          '할머니 est une personne (et une aînée respectée), donc le marqueur de destinataire animé 께 (honorifique de 에게) convient ; 에 ne sert que pour les destinataires inanimés comme les lieux.',
          '할머니 é uma pessoa (e uma idosa respeitada), então o marcador de destinatário animado 께 (honorífico de 에게) é correto; 에 é só para destinatários inanimados como lugares.',
          '할머니 เป็นคน (และผู้ใหญ่ที่ควรเคารพ) จึงต้องใช้อนุภาคผู้รับที่มีชีวิต 께 (รูปยกย่องของ 에게); 에 ใช้กับผู้รับที่ไม่มีชีวิตอย่างสถานที่เท่านั้น',
          '할머니 adalah orang (dan sesepuh yang dihormati), jadi penanda penerima bernyawa 께 (bentuk hormat 에게) yang benar; 에 hanya untuk penerima tak bernyawa seperti tempat.',
          '할머니 là người (và bậc trên đáng kính), nên dùng dấu người nhận hữu sinh 께 (kính ngữ của 에게); 에 chỉ dùng cho người nhận vô sinh như nơi chốn.',
          '할머니 は人（しかも敬うべき年長者）なので有情の受け手を表す 께（에게の尊敬形）が正しい。에 は場所など無情の受け手専用。',
        ),
      },
      {
        sentence: '아침마다 화분{} 물을 줘요.',
        optionA: '에게',
        optionB: '에',
        answer: 'b',
        trans: L(
          'Every morning I water the flowerpot.',
          'Cada mañana le doy agua a la maceta.',
          'Chaque matin, j’arrose le pot de fleurs.',
          'Toda manhã eu rego o vaso de flores.',
          'ทุกเช้าฉันรดน้ำกระถางต้นไม้',
          'Setiap pagi saya menyiram pot bunga.',
          'Mỗi sáng tôi tưới nước cho chậu cây.',
          '毎朝、植木鉢に水をやります。',
        ),
        why: L(
          'A flowerpot/plant is inanimate, so the recipient takes 에; 에게 is reserved for people and animals and would be wrong for a plant.',
          'Una maceta/planta es inanimada, así que el destinatario lleva 에; 에게 se reserva para personas y animales y sería incorrecto para una planta.',
          'Un pot de fleurs / une plante est inanimé, donc le destinataire prend 에 ; 에게 est réservé aux personnes et aux animaux et serait faux pour une plante.',
          'Um vaso/planta é inanimado, então o destinatário leva 에; 에게 é reservado a pessoas e animais e estaria errado para uma planta.',
          'กระถาง/ต้นไม้ไม่มีชีวิต (ในเชิงไวยากรณ์) ผู้รับจึงใช้ 에; 에게 ใช้กับคนและสัตว์ จะผิดถ้าใช้กับต้นไม้',
          'Pot/tanaman tak bernyawa, jadi penerimanya memakai 에; 에게 khusus untuk orang dan hewan dan salah untuk tanaman.',
          'Chậu cây/cây là vô sinh, nên người nhận dùng 에; 에게 chỉ dành cho người và động vật, dùng cho cây là sai.',
          '植木鉢・植物は無情なので受け手は 에 を取る。에게 は人や動物専用で、植物には使えない。',
        ),
      },
      {
        sentence: '생일에 친구{} 선물을 줬어요.',
        optionA: '한테',
        optionB: '에',
        answer: 'a',
        trans: L(
          'On their birthday I gave my friend a present.',
          'En su cumpleaños le di un regalo a mi amigo.',
          'Pour son anniversaire, j’ai offert un cadeau à mon ami.',
          'No aniversário, dei um presente ao meu amigo.',
          'วันเกิดฉันให้ของขวัญเพื่อน',
          'Saat ulang tahun, saya memberi hadiah kepada teman.',
          'Vào sinh nhật, tôi đã tặng quà cho bạn.',
          '誕生日に友達にプレゼントをあげました。',
        ),
        why: L(
          '친구 is a person, so the spoken animate-recipient marker 한테 (= 에게) is correct; 에 is only for inanimate recipients and cannot mark a person.',
          '친구 es una persona, así que el marcador hablado de destinatario animado 한테 (= 에게) es correcto; 에 solo es para destinatarios inanimados y no puede marcar a una persona.',
          '친구 est une personne, donc le marqueur oral de destinataire animé 한테 (= 에게) convient ; 에 ne sert qu’aux destinataires inanimés et ne peut marquer une personne.',
          '친구 é uma pessoa, então o marcador falado de destinatário animado 한테 (= 에게) é correto; 에 é só para destinatários inanimados e não pode marcar uma pessoa.',
          '친구 เป็นคน จึงใช้อนุภาคผู้รับมีชีวิตแบบภาษาพูด 한테 (= 에게); 에 ใช้กับผู้รับไม่มีชีวิตเท่านั้น ใช้กับคนไม่ได้',
          '친구 adalah orang, jadi penanda penerima bernyawa lisan 한테 (= 에게) yang benar; 에 hanya untuk penerima tak bernyawa dan tak bisa menandai orang.',
          '친구 là người, nên dùng dấu người nhận hữu sinh dạng nói 한테 (= 에게); 에 chỉ dùng cho người nhận vô sinh, không thể đánh dấu người.',
          '친구 は人なので口語の有情受け手 한테（＝에게）が正しい。에 は無情の受け手専用で人には使えない。',
        ),
      },
    ],
  },
]
