import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * Confusable grammar/ending pairs (roadmap Step 7). a/b match grammars-n{1,2,3}.ts
 * verbatim. 4 pairs x 3 two-choice discrimination items, 8-locale trans + why.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow
 * (single-answer-per-item crux, naturalness, conjugation, 8-locale fidelity).
 * Native (Korean wife) review is the documented final gate.
 */
export const N1_PAIRS: ConfusablePair[] = [
  {
    id: 'an-mot',
    a: '안 + V / -지 않다',
    b: '못 + V / -지 못하다',
    note: L(
      "안 / -지 않다 negates by CHOICE (won't, do not), while 못 / -지 못하다 negates by INABILITY (can't, because of circumstance).",
      '안 / -지 않다 niega por ELECCIÓN (no quiero, no lo hago), mientras 못 / -지 못하다 niega por INCAPACIDAD (no puedo, por las circunstancias).',
      '안 / -지 않다 nie par CHOIX (ne pas vouloir), tandis que 못 / -지 못하다 nie par INCAPACITÉ (ne pas pouvoir, à cause des circonstances).',
      '안 / -지 않다 nega por ESCOLHA (não quero, não faço), enquanto 못 / -지 못하다 nega por INCAPACIDADE (não consigo, por circunstância).',
      '안 / -지 않다 ปฏิเสธโดยการเลือก (ไม่ทำเอง) ส่วน 못 / -지 못하다 ปฏิเสธเพราะทำไม่ได้ (เพราะข้อจำกัด)',
      '안 / -지 않다 menegasi karena PILIHAN (tidak mau), sedangkan 못 / -지 못하다 menegasi karena KETIDAKMAMPUAN (tidak bisa, karena keadaan).',
      '안 / -지 않다 phủ định do LỰA CHỌN (không muốn), còn 못 / -지 못하다 phủ định do BẤT KHẢ (không thể, vì hoàn cảnh).',
      '안 / -지 않다 は意志による否定（しない）、못 / -지 못하다 は能力・状況による否定（できない）。',
    ),
    items: [
      {
        sentence: '다리를 다쳐서 지금은 빨리 {} 뛰어요.',
        optionA: '안',
        optionB: '못',
        answer: 'b',
        trans: L(
          "I hurt my leg, so right now I can't run fast.",
          'Me lastimé la pierna, así que ahora no puedo correr rápido.',
          'Je me suis blessé à la jambe, donc je ne peux pas courir vite en ce moment.',
          'Machuquei a perna, então agora não consigo correr rápido.',
          'ฉันบาดเจ็บที่ขา ตอนนี้เลยวิ่งเร็วไม่ได้',
          'Kaki saya cedera, jadi sekarang saya tidak bisa berlari cepat.',
          'Tôi bị thương ở chân nên bây giờ không thể chạy nhanh.',
          '足を怪我したので、今は速く走れません。',
        ),
        why: L(
          "An injury removes ABILITY, so 못 (can't) fits; 안 (won't) would wrongly imply a free choice.",
          'Una lesión quita la CAPACIDAD, así que va 못 (no poder); 안 (no querer) implicaría falsamente una elección.',
          'Une blessure ôte la CAPACITÉ, donc 못 (ne pas pouvoir) convient ; 안 (ne pas vouloir) impliquerait à tort un choix.',
          'Uma lesão tira a CAPACIDADE, então cabe 못 (não conseguir); 안 (não querer) sugeriria erradamente uma escolha.',
          'การบาดเจ็บทำให้ขาดความสามารถ จึงใช้ 못 (ทำไม่ได้); 안 (ไม่ทำเอง) จะสื่อผิดว่าเป็นการเลือก',
          'Cedera menghilangkan KEMAMPUAN, jadi 못 (tidak bisa) cocok; 안 (tidak mau) salah karena menyiratkan pilihan.',
          'Chấn thương làm mất KHẢ NĂNG nên dùng 못 (không thể); 안 (không muốn) sẽ sai vì ngụ ý lựa chọn.',
          '怪我で「能力」が失われるため 못（できない）が適切。안（しない）だと意志的選択になり不自然。',
        ),
      },
      {
        sentence: '저는 커피를 싫어해서 {} 마셔요.',
        optionA: '안',
        optionB: '못',
        answer: 'a',
        trans: L(
          "I dislike coffee, so I don't drink it.",
          'No me gusta el café, así que no lo bebo.',
          "Je n'aime pas le café, donc je n'en bois pas.",
          'Não gosto de café, então não bebo.',
          'ฉันไม่ชอบกาแฟ เลยไม่ดื่ม',
          'Saya tidak suka kopi, jadi saya tidak meminumnya.',
          'Tôi không thích cà phê nên tôi không uống.',
          '私はコーヒーが嫌いなので、飲みません。',
        ),
        why: L(
          "Disliking is a personal CHOICE not to drink, so 안 (won't) fits; 못 (can't) would falsely suggest inability.",
          'Que no te guste es una ELECCIÓN de no beberlo, así que va 안 (no quiero); 못 (no poder) sugeriría incapacidad.',
          "Ne pas aimer relève d'un CHOIX de ne pas en boire, donc 안 (ne pas vouloir) ; 못 (ne pas pouvoir) suggérerait à tort une incapacité.",
          'Não gostar é uma ESCOLHA de não beber, então cabe 안 (não querer); 못 (não conseguir) sugeriria incapacidade.',
          'การไม่ชอบคือการเลือกที่จะไม่ดื่ม จึงใช้ 안 (ไม่ทำเอง); 못 (ทำไม่ได้) จะสื่อผิดว่าทำไม่ได้',
          'Tidak suka adalah PILIHAN untuk tidak minum, jadi 안 (tidak mau) cocok; 못 (tidak bisa) salah menyiratkan ketidakmampuan.',
          'Không thích là LỰA CHỌN không uống nên dùng 안 (không muốn); 못 (không thể) sẽ sai vì ngụ ý bất khả.',
          '嫌いだから飲まないのは「意志的選択」なので 안 が適切。못（できない）だと不可能の意味になり不自然。',
        ),
      },
      {
        sentence: '일이 너무 많아서 이번 주말에도 {} 쉬어요.',
        optionA: '안',
        optionB: '못',
        answer: 'b',
        trans: L(
          "I have too much work, so I can't rest this weekend either.",
          'Tengo demasiado trabajo, así que tampoco puedo descansar este fin de semana.',
          "J'ai trop de travail, donc je ne peux pas non plus me reposer ce week-end.",
          'Tenho trabalho demais, então também não consigo descansar neste fim de semana.',
          'งานเยอะเกินไป สุดสัปดาห์นี้ก็เลยพักไม่ได้',
          'Pekerjaan saya terlalu banyak, jadi akhir pekan ini pun saya tidak bisa istirahat.',
          'Tôi có quá nhiều việc nên cuối tuần này cũng không thể nghỉ.',
          '仕事が多すぎて、今週末も休めません。',
        ),
        why: L(
          "Too much work is an external constraint blocking rest, so 못 (can't) fits; 안 (won't) would wrongly imply choosing not to rest.",
          'El exceso de trabajo es una restricción externa que impide descansar, así que va 못 (no poder); 안 (no querer) implicaría elegir no descansar.',
          'Trop de travail est une contrainte extérieure empêchant le repos, donc 못 (ne pas pouvoir) ; 안 (ne pas vouloir) impliquerait un choix.',
          'Excesso de trabalho é uma restrição externa que impede o descanso, então cabe 못 (não conseguir); 안 (não querer) implicaria escolha.',
          'งานที่มากเกินไปเป็นข้อจำกัดภายนอกที่ทำให้พักไม่ได้ จึงใช้ 못 (ทำไม่ได้); 안 (ไม่ทำเอง) จะสื่อผิดว่าเลือกไม่พัก',
          'Pekerjaan berlebih adalah kendala eksternal yang menghalangi istirahat, jadi 못 (tidak bisa) cocok; 안 (tidak mau) salah menyiratkan memilih tidak istirahat.',
          'Quá nhiều việc là trở ngại bên ngoài cản việc nghỉ nên dùng 못 (không thể); 안 (không muốn) sẽ sai vì ngụ ý chọn không nghỉ.',
          '仕事が多すぎるのは休めない外的制約なので 못（できない）が適切。안（しない）だと休まない選択の意味になり不自然。',
        ),
      },
    ],
  },
  {
    id: 'aseo-nikka',
    a: '-아/어서',
    b: '-(으)니까',
    note: L(
      'Both mean "because": -아/어서 states a natural cause and cannot be followed by a command or suggestion (and takes no past marker), while -(으)니까 gives a reason that CAN precede an imperative or propositive and allows past tense.',
      'Ambos significan "porque": -아/어서 da una causa natural y NO puede ir seguido de imperativo ni propuesta (ni lleva pasado), mientras que -(으)니까 da una razón que SÍ puede preceder a un imperativo o propuesta y admite pasado.',
      "Les deux signifient « parce que » : -아/어서 exprime une cause naturelle et ne peut être suivi d'un impératif ni d'une suggestion (ni marqueur de passé), tandis que -(으)니까 donne une raison qui PEUT précéder un impératif ou une proposition et accepte le passé.",
      'Ambos significam "porque": -아/어서 indica uma causa natural e NÃO pode ser seguido de ordem ou sugestão (nem leva passado), enquanto -(으)니까 dá um motivo que PODE preceder imperativo ou proposta e aceita passado.',
      'ทั้งคู่แปลว่า "เพราะ": -아/어서 บอกเหตุผลตามธรรมชาติและตามด้วยคำสั่งหรือการชวนไม่ได้ (และเติมอดีตไม่ได้) ส่วน -(으)니까 บอกเหตุผลที่นำหน้าคำสั่งหรือการชวนได้และใช้อดีตได้',
      'Keduanya berarti "karena": -아/어서 menyatakan sebab alami dan TIDAK boleh diikuti perintah atau ajakan (juga tanpa penanda lampau), sedangkan -(으)니까 memberi alasan yang BISA mendahului imperatif atau ajakan dan boleh lampau.',
      'Cả hai nghĩa là "vì": -아/어서 nêu nguyên nhân tự nhiên và KHÔNG thể đứng trước mệnh lệnh hay rủ rê (cũng không gắn quá khứ), còn -(으)니까 nêu lý do CÓ THỂ đứng trước mệnh lệnh hoặc đề nghị và cho phép quá khứ.',
      'どちらも「〜から」の意味だが、-아/어서 は自然な因果を表し後ろに命令・勧誘を置けず(過去も付かない)、-(으)니까 は理由を表して命令や勧誘の前に置け、過去も使える。',
    ),
    items: [
      {
        sentence: '날씨가 {} 창문을 닫으세요.',
        optionA: '추워서',
        optionB: '추우니까',
        answer: 'b',
        trans: L(
          "It's cold, so please close the window.",
          'Hace frío, así que cierra la ventana, por favor.',
          "Il fait froid, alors ferme la fenêtre, s'il te plaît.",
          'Está frio, então feche a janela, por favor.',
          'อากาศหนาว ช่วยปิดหน้าต่างด้วยนะคะ',
          'Cuacanya dingin, jadi tolong tutup jendelanya.',
          'Trời lạnh, nên hãy đóng cửa sổ lại nhé.',
          '寒いから窓を閉めてください。',
        ),
        why: L(
          'The second clause is a command (닫으세요), so only -(으)니까 (추우니까) is allowed; -아/어서 cannot precede an imperative.',
          'La segunda cláusula es una orden (닫으세요), así que solo se admite -(으)니까 (추우니까); -아/어서 no puede ir antes de un imperativo.',
          'La seconde proposition est un impératif (닫으세요), donc seul -(으)니까 (추우니까) est permis ; -아/어서 ne peut précéder un impératif.',
          'A segunda oração é uma ordem (닫으세요), então só cabe -(으)니까 (추우니까); -아/어서 não pode anteceder um imperativo.',
          'ประโยคหลังเป็นคำสั่ง (닫으세요) จึงใช้ได้แค่ -(으)니까 (추우니까) ส่วน -아/어서 นำหน้าคำสั่งไม่ได้',
          'Klausa kedua adalah perintah (닫으세요), jadi hanya -(으)니까 (추우니까) yang boleh; -아/어서 tak bisa mendahului imperatif.',
          'Vế sau là mệnh lệnh (닫으세요), nên chỉ dùng -(으)니까 (추우니까); -아/어서 không thể đứng trước mệnh lệnh.',
          '後ろが命令(닫으세요)なので -(으)니까(추우니까)しか使えない。-아/어서 は命令の前に置けない。',
        ),
      },
      {
        sentence: '{} 반가워요.',
        optionA: '만나서',
        optionB: '만나니까',
        answer: 'a',
        trans: L(
          'Nice to meet you.',
          'Encantado de conocerte.',
          'Ravi de te rencontrer.',
          'Prazer em conhecê-lo.',
          'ยินดีที่ได้พบกันค่ะ',
          'Senang bertemu denganmu.',
          'Rất vui được gặp bạn.',
          'お会いできてうれしいです。',
        ),
        why: L(
          'This is the fixed greeting 만나서 반가워요; emotion/greeting reasons take -아/어서, so 만나니까 is wrong here.',
          'Es el saludo fijo 만나서 반가워요; las razones de emoción/saludo usan -아/어서, por eso 만나니까 es incorrecto.',
          "C'est la salutation figée 만나서 반가워요 ; les raisons d'émotion/salutation prennent -아/어서, donc 만나니까 est faux.",
          'É a saudação fixa 만나서 반가워요; razões de emoção/saudação usam -아/어서, então 만나니까 está errado.',
          'เป็นวลีทักทายตายตัว 만나서 반가워요 เหตุผลเชิงอารมณ์/คำทักทายใช้ -아/어서 ดังนั้น 만나니까 จึงผิด',
          'Ini sapaan baku 만나서 반가워요; alasan emosi/sapaan memakai -아/어서, jadi 만나니까 salah.',
          'Đây là câu chào cố định 만나서 반가워요; lý do cảm xúc/lời chào dùng -아/어서, nên 만나니까 sai.',
          'これは決まった挨拶 만나서 반가워요。感情・挨拶の理由は -아/어서 を使うので 만나니까 は誤り。',
        ),
      },
      {
        sentence: '시간이 {} 택시를 탑시다.',
        optionA: '없어서',
        optionB: '없으니까',
        answer: 'b',
        trans: L(
          "We don't have time, so let's take a taxi.",
          'No tenemos tiempo, así que tomemos un taxi.',
          "On n'a pas le temps, alors prenons un taxi.",
          'Não temos tempo, então vamos de táxi.',
          'ไม่มีเวลา งั้นนั่งแท็กซี่กันเถอะ',
          'Tidak ada waktu, jadi ayo naik taksi.',
          'Không có thời gian, nên chúng ta đi taxi đi.',
          '時間がないからタクシーに乗りましょう。',
        ),
        why: L(
          'The second clause is a propositive (탑시다 "let\'s take"), which requires -(으)니까 (없으니까); -아/어서 cannot precede a suggestion.',
          'La segunda cláusula es una propuesta (탑시다 "tomemos"), que exige -(으)니까 (없으니까); -아/어서 no puede ir antes de una propuesta.',
          'La seconde proposition est une suggestion (탑시다 « prenons »), qui exige -(으)니까 (없으니까) ; -아/어서 ne peut précéder une proposition.',
          'A segunda oração é uma proposta (탑시다 "vamos"), que exige -(으)니까 (없으니까); -아/어서 não pode anteceder uma sugestão.',
          'ประโยคหลังเป็นการชวน (탑시다 "นั่งกันเถอะ") ต้องใช้ -(으)니까 (없으니까) ส่วน -아/어서 นำหน้าการชวนไม่ได้',
          'Klausa kedua adalah ajakan (탑시다 "ayo naik"), yang menuntut -(으)니까 (없으니까); -아/어서 tak bisa mendahului ajakan.',
          'Vế sau là lời rủ (탑시다 "đi đi"), đòi hỏi -(으)니까 (없으니까); -아/어서 không thể đứng trước lời đề nghị.',
          '後ろが勧誘(탑시다「乗りましょう」)なので -(으)니까(없으니까)が必要。-아/어서 は勧誘の前に置けない。',
        ),
      },
    ],
  },
  {
    id: 'go-aseo',
    a: '-고',
    b: '-아/어서',
    note: L(
      '-고 just lists/sequences two independent actions; -아/어서 ties them so the first enables or leads into the second.',
      '-고 solo enumera o secuencia dos acciones independientes; -아/어서 las une de modo que la primera habilita o lleva a la segunda.',
      '-고 énumère ou enchaîne simplement deux actions indépendantes ; -아/어서 les lie pour que la première rende possible ou amène la seconde.',
      '-고 apenas lista ou sequencia duas ações independentes; -아/어서 as liga para que a primeira possibilite ou leve à segunda.',
      '-고 แค่เรียงสองการกระทำที่เป็นอิสระต่อกัน ส่วน -아/어서 ผูกให้การกระทำแรกเป็นเงื่อนไข/นำไปสู่การกระทำที่สอง',
      '-고 hanya mengurutkan dua aksi yang mandiri; -아/어서 mengikatnya sehingga aksi pertama memungkinkan atau menuju aksi kedua.',
      '-고 chỉ liệt kê hai hành động độc lập theo thứ tự; -아/어서 nối chúng sao cho hành động đầu tạo điều kiện hoặc dẫn vào hành động sau.',
      '-고 は独立した二つの動作を単に並べるだけ。-아/어서 は前の動作が後の動作を可能にする・つながる形で結びつける。',
    ),
    items: [
      {
        sentence: '도서관에 {} 책을 빌렸어요.',
        optionA: '가고',
        optionB: '가서',
        answer: 'b',
        trans: L(
          'I went to the library and borrowed a book (there).',
          'Fui a la biblioteca y (allí) pedí prestado un libro.',
          "Je suis allé à la bibliothèque et j'y ai emprunté un livre.",
          'Fui à biblioteca e (lá) peguei um livro emprestado.',
          'ฉันไปห้องสมุดแล้วยืมหนังสือ (ที่นั่น)',
          'Saya pergi ke perpustakaan lalu meminjam buku (di sana).',
          'Tôi đến thư viện rồi mượn sách (ở đó).',
          '図書館に行って(そこで)本を借りました。',
        ),
        why: L(
          'With a motion verb, the borrowing happens at the destination, so the actions are linked → 가서; 가고 detaches them and is unnatural here.',
          'Con un verbo de movimiento, el préstamo ocurre en el destino, así que las acciones están ligadas → 가서; 가고 las separa y suena antinatural aquí.',
          "Avec un verbe de mouvement, l'emprunt a lieu à destination, les actions sont donc liées → 가서 ; 가고 les détache et sonne mal ici.",
          'Com um verbo de movimento, o empréstimo ocorre no destino, então as ações estão ligadas → 가서; 가고 as separa e soa não natural aqui.',
          'กับกริยาเคลื่อนที่ การยืมเกิดที่ปลายทาง การกระทำจึงเชื่อมกัน → 가서; 가고 จะแยกออกจากกันและฟังดูไม่เป็นธรรมชาติ',
          'Dengan verba gerak, peminjaman terjadi di tujuan, jadi aksinya terkait → 가서; 가고 memisahkannya dan terdengar tidak alami di sini.',
          'Với động từ chuyển động, việc mượn diễn ra tại đích đến nên hai hành động gắn nhau → 가서; 가고 tách rời chúng và nghe không tự nhiên ở đây.',
          '移動動詞では本を借りるのは到着先での行為なので動作がつながる → 가서。가고 だと切り離されて不自然になる。',
        ),
      },
      {
        sentence: '손을 {} 밥을 먹어요.',
        optionA: '씻고',
        optionB: '씻어서',
        answer: 'a',
        trans: L(
          'I wash my hands and (then) eat.',
          'Me lavo las manos y (luego) como.',
          'Je me lave les mains et (puis) je mange.',
          'Lavo as mãos e (depois) como.',
          'ฉันล้างมือแล้วก็กินข้าว',
          'Saya cuci tangan lalu makan.',
          'Tôi rửa tay rồi ăn cơm.',
          '手を洗ってからご飯を食べます。',
        ),
        why: L(
          'Washing hands and eating are two separate, sequential actions, not a means→result link → 씻고; 씻어서 would wrongly imply washing causes/enables the eating.',
          'Lavarse las manos y comer son dos acciones separadas y sucesivas, no un vínculo medio→resultado → 씻고; 씻어서 implicaría que lavarse causa/habilita el comer.',
          'Se laver les mains et manger sont deux actions distinctes et successives, pas un lien moyen→résultat → 씻고 ; 씻어서 sous-entendrait que le lavage permet de manger.',
          'Lavar as mãos e comer são duas ações separadas e sucessivas, não um elo meio→resultado → 씻고; 씻어서 implicaria que lavar causa/possibilita o comer.',
          'การล้างมือกับการกินเป็นสองการกระทำที่แยกกันและเรียงลำดับ ไม่ใช่ความสัมพันธ์เหตุ→ผล → 씻고; 씻어서 จะสื่อผิดว่าการล้างมือทำให้/นำไปสู่การกิน',
          'Mencuci tangan dan makan adalah dua aksi terpisah dan berurutan, bukan hubungan sarana→hasil → 씻고; 씻어서 keliru menyiratkan mencuci menyebabkan/memungkinkan makan.',
          'Rửa tay và ăn là hai hành động riêng biệt nối tiếp nhau, không phải liên hệ phương tiện→kết quả → 씻고; 씻어서 sẽ ngụ ý sai rằng rửa tay khiến/giúp cho việc ăn.',
          '手を洗うことと食べることは別々の連続動作で、手段→結果の関係ではない → 씻고。씻어서 だと洗うことが食べることを引き起こす・可能にする意味になり不自然。',
        ),
      },
      {
        sentence: '친구를 {} 같이 영화를 봤어요.',
        optionA: '만나고',
        optionB: '만나서',
        answer: 'b',
        trans: L(
          'I met my friend and watched a movie together.',
          'Me encontré con mi amigo y vimos una película juntos.',
          "J'ai retrouvé mon ami et nous avons regardé un film ensemble.",
          'Encontrei meu amigo e assistimos a um filme juntos.',
          'ฉันเจอเพื่อนแล้วดูหนังด้วยกัน',
          'Saya bertemu teman lalu menonton film bersama.',
          'Tôi gặp bạn rồi cùng xem phim.',
          '友だちに会って一緒に映画を見ました。',
        ),
        why: L(
          'Meeting the friend is what makes watching together possible — the actions are tied (same people, one flow) → 만나서; 만나고 would mean meeting and then watching separately.',
          'Encontrarse con el amigo es lo que hace posible verla juntos: las acciones están ligadas (mismas personas, un solo flujo) → 만나서; 만나고 significaría encontrarse y luego ver por separado.',
          "Retrouver l'ami est ce qui rend possible le visionnage ensemble — les actions sont liées (mêmes personnes, un seul fil) → 만나서 ; 만나고 voudrait dire se retrouver puis regarder séparément.",
          'Encontrar o amigo é o que torna possível assistir juntos — as ações estão ligadas (mesmas pessoas, um único fluxo) → 만나서; 만나고 significaria encontrar e depois assistir separadamente.',
          'การเจอเพื่อนคือสิ่งที่ทำให้ดูหนังด้วยกันได้ การกระทำจึงผูกกัน (คนเดียวกัน เหตุการณ์เดียว) → 만나서; 만나고 จะหมายถึงเจอกันแล้วต่างคนต่างดู',
          'Bertemu teman itulah yang memungkinkan menonton bersama — aksinya terkait (orang sama, satu alur) → 만나서; 만나고 berarti bertemu lalu menonton sendiri-sendiri.',
          'Gặp bạn chính là điều giúp cùng xem phim được — hai hành động gắn nhau (cùng người, một mạch) → 만나서; 만나고 lại có nghĩa gặp xong rồi xem riêng.',
          '友だちに会うことで一緒に映画を見ることが可能になる — 動作がつながっている(同じ人・一連の流れ)→ 만나서。만나고 だと会ってから別々に見た意味になる。',
        ),
      },
    ],
  },
  {
    id: 'goitda-aitda',
    a: '-고 있다',
    b: '-아/어 있다',
    note: L(
      '-고 있다 marks an action in progress (be ...ing); -아/어 있다 marks the lasting state after an intransitive change-of-state action finishes.',
      '-고 있다 marca una acción en curso (estar + gerundio); -아/어 있다 marca el estado resultante tras completarse una acción intransitiva de cambio.',
      "-고 있다 marque une action en cours (être en train de) ; -아/어 있다 marque l'état durable après une action intransitive de changement achevée.",
      '-고 있다 marca uma ação em progresso (estar fazendo); -아/어 있다 marca o estado resultante após uma ação intransitiva de mudança terminar.',
      '-고 있다 บอกการกระทำที่กำลังดำเนินอยู่ (กำลัง...); -아/어 있다 บอกสภาพที่คงอยู่หลังกริยาอกรรมเปลี่ยนสภาพจบลงแล้ว',
      '-고 있다 menandai aksi yang sedang berlangsung (sedang...); -아/어 있다 menandai keadaan yang bertahan setelah aksi intransitif perubahan selesai.',
      '-고 있다 chỉ hành động đang diễn ra (đang...); -아/어 있다 chỉ trạng thái còn lại sau khi hành động nội động từ chuyển trạng thái kết thúc.',
      '-고 있다 は進行中の動作（〜している）、-아/어 있다 は自動詞の変化動作が完了した後の持続状態を表す。',
    ),
    items: [
      {
        sentence: '책상 위에 휴대폰이 {}.',
        optionA: '켜고 있어요',
        optionB: '켜져 있어요',
        answer: 'b',
        trans: L(
          'The phone is (left) on, on the desk.',
          'El móvil está encendido sobre el escritorio.',
          'Le téléphone est allumé sur le bureau.',
          'O celular está ligado em cima da mesa.',
          'โทรศัพท์เปิดอยู่บนโต๊ะ',
          'Ponselnya menyala di atas meja.',
          'Điện thoại đang bật trên bàn.',
          '机の上で携帯がついています。',
        ),
        why: L(
          '휴대폰 is the subject (휴대폰이), so we need the intransitive resulting state 켜져 있어요 (켜지다); 켜고 있어요 is transitive 켜다 and would mean the phone itself is turning something on, which is nonsensical here.',
          '휴대폰 es el sujeto (휴대폰이), así que se necesita el estado resultante intransitivo 켜져 있어요 (켜지다); 켜고 있어요 es 켜다 transitivo y significaría que el móvil está encendiendo algo, lo cual no tiene sentido aquí.',
          "휴대폰 est le sujet (휴대폰이), il faut donc l'état résultant intransitif 켜져 있어요 (켜지다) ; 켜고 있어요 est 켜다 transitif et voudrait dire que le téléphone allume quelque chose, ce qui n'a pas de sens ici.",
          '휴대폰 é o sujeito (휴대폰이), então precisamos do estado resultante intransitivo 켜져 있어요 (켜지다); 켜고 있어요 é 켜다 transitivo e significaria que o celular está ligando algo, o que não faz sentido aqui.',
          '휴대폰 เป็นประธาน (휴대폰이) จึงต้องใช้สภาพคงค้างจากกริยาอกรรม 켜져 있어요 (켜지다); 켜고 있어요 เป็น 켜다 สกรรม จะแปลว่าโทรศัพท์กำลังเปิดอะไรบางอย่าง ซึ่งไม่สมเหตุผลในที่นี้',
          '휴대폰 adalah subjek (휴대폰이), jadi perlu keadaan hasil intransitif 켜져 있어요 (켜지다); 켜고 있어요 adalah 켜다 transitif dan berarti ponselnya sedang menyalakan sesuatu, yang tidak masuk akal di sini.',
          '휴대폰 là chủ ngữ (휴대폰이), nên cần trạng thái kết quả nội động từ 켜져 있어요 (켜지다); 켜고 있어요 là 켜다 ngoại động từ, sẽ có nghĩa là điện thoại đang bật một thứ gì đó, vô nghĩa ở đây.',
          '휴대폰 が主語（휴대폰이）なので自動詞の結果状態 켜져 있어요（켜지다）が必要。켜고 있어요 は他動詞 켜다 で、携帯が何かを点けている意味になり不自然。',
        ),
      },
      {
        sentence: '잠깐만요, 제가 지금 창문을 {}.',
        optionA: '닫고 있어요',
        optionB: '닫혀 있어요',
        answer: 'a',
        trans: L(
          "Just a moment, I'm closing the window right now.",
          'Un momento, estoy cerrando la ventana ahora mismo.',
          'Un instant, je suis en train de fermer la fenêtre.',
          'Só um momento, estou fechando a janela agora.',
          'เดี๋ยวนะ ตอนนี้ฉันกำลังปิดหน้าต่างอยู่',
          'Sebentar, saya sedang menutup jendela sekarang.',
          'Đợi một chút, tôi đang đóng cửa sổ.',
          'ちょっと待って、今窓を閉めています。',
        ),
        why: L(
          '제가 (agent) + 창문을 (object) + 지금 means an action in progress → 닫고 있어요 (transitive 닫다); 닫혀 있어요 is the intransitive state of 닫히다 and cannot take 제가 as agent or 창문을 as object.',
          '제가 (agente) + 창문을 (objeto) + 지금 indica acción en curso → 닫고 있어요 (닫다 transitivo); 닫혀 있어요 es el estado intransitivo de 닫히다 y no admite 제가 como agente ni 창문을 como objeto.',
          "제가 (agent) + 창문을 (objet) + 지금 indique une action en cours → 닫고 있어요 (닫다 transitif) ; 닫혀 있어요 est l'état intransitif de 닫히다 et n'admet ni 제가 comme agent ni 창문을 comme objet.",
          '제가 (agente) + 창문을 (objeto) + 지금 indica ação em progresso → 닫고 있어요 (닫다 transitivo); 닫혀 있어요 é o estado intransitivo de 닫히다 e não aceita 제가 como agente nem 창문을 como objeto.',
          '제가 (ผู้กระทำ) + 창문을 (กรรม) + 지금 บ่งการกระทำที่กำลังดำเนิน → 닫고 있어요 (닫다 สกรรม); 닫혀 있어요 เป็นสภาพอกรรมของ 닫히다 ใช้ 제가 เป็นผู้กระทำหรือ 창문을 เป็นกรรมไม่ได้',
          '제가 (pelaku) + 창문을 (objek) + 지금 menunjukkan aksi berlangsung → 닫고 있어요 (닫다 transitif); 닫혀 있어요 adalah keadaan intransitif 닫히다 dan tak bisa pakai 제가 sebagai pelaku maupun 창문을 sebagai objek.',
          '제가 (chủ thể) + 창문을 (tân ngữ) + 지금 cho thấy hành động đang diễn ra → 닫고 있어요 (닫다 ngoại động từ); 닫혀 있어요 là trạng thái nội động từ của 닫히다, không nhận 제가 làm chủ thể hay 창문을 làm tân ngữ.',
          '제가（動作主）＋창문을（目的語）＋지금 は進行中の動作 → 닫고 있어요（他動詞 닫다）。닫혀 있어요 は自動詞 닫히다 の状態で、제가 を動作主にも 창문을 を目的語にも取れない。',
        ),
      },
      {
        sentence: '추워서 두꺼운 코트를 {}.',
        optionA: '입고 있어요',
        optionB: '입어 있어요',
        answer: 'a',
        trans: L(
          "It's cold, so I'm wearing a thick coat.",
          'Hace frío, así que llevo puesto un abrigo grueso.',
          'Il fait froid, donc je porte un gros manteau.',
          'Está frio, então estou usando um casaco grosso.',
          'อากาศหนาว เลยใส่เสื้อโค้ตหนาอยู่',
          'Karena dingin, saya memakai mantel tebal.',
          'Trời lạnh nên tôi đang mặc áo khoác dày.',
          '寒いので厚いコートを着ています。',
        ),
        why: L(
          '입다 is transitive and takes the object 코트를, so wearing is expressed with 입고 있어요; -아/어 있다 attaches only to intransitive verbs, making 입어 있어요 ungrammatical.',
          '입다 es transitivo y lleva el objeto 코트를, así que se usa 입고 있어요; -아/어 있다 solo va con verbos intransitivos, por lo que 입어 있어요 es agramatical.',
          "입다 est transitif et prend l'objet 코트를, donc on emploie 입고 있어요 ; -아/어 있다 ne s'attache qu'aux verbes intransitifs, d'où l'agrammaticalité de 입어 있어요.",
          '입다 é transitivo e leva o objeto 코트를, então usa-se 입고 있어요; -아/어 있다 só liga a verbos intransitivos, tornando 입어 있어요 agramatical.',
          '입다 เป็นกริยาสกรรมและรับกรรม 코트를 จึงใช้ 입고 있어요; -아/어 있다 ต่อกับกริยาอกรรมเท่านั้น ทำให้ 입어 있어요 ผิดไวยากรณ์',
          '입다 transitif dan mengambil objek 코트를, jadi pakai 입고 있어요; -아/어 있다 hanya untuk verba intransitif, sehingga 입어 있어요 tidak gramatikal.',
          '입다 là ngoại động từ và nhận tân ngữ 코트를 nên dùng 입고 있어요; -아/어 있다 chỉ gắn với nội động từ, khiến 입어 있어요 sai ngữ pháp.',
          '입다 は目的語 코트를 を取る他動詞なので 입고 있어요 を使う。-아/어 있다 は自動詞専用で 입어 있어요 は非文。',
        ),
      },
    ],
  },
]
