import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * Extra TOPIK 2 confusable grammar/ending pairs. a/b match grammars-n2.ts kos
 * verbatim. Each pair: a contrast note + 3 single-answer discrimination items,
 * 8-locale note/trans/why.
 *
 * Drafted + Korean-lens adversarially verified (single-correct-answer crux,
 * naturalness, conjugation, 8-locale fidelity). Native (Korean wife) review is
 * the documented final gate.
 */
export const N2_PAIRS_EXTRA: ConfusablePair[] = [
  {
    id: 'gijeone-nhue',
    a: '-기 전에',
    b: '-(으)ㄴ 후에 / 다음에',
    note: L(
      '-기 전에 means "before (doing)" — the main-clause event happens EARLIER than the verb in the clause; -(으)ㄴ 후에 / 다음에 means "after (doing)" — the main-clause event happens LATER, once that verb is completed. They put the two actions in opposite time order, so the real-world sequence in each sentence fixes exactly one.',
      '-기 전에 significa "antes de (hacer)" — el evento de la cláusula principal ocurre ANTES que el verbo de la cláusula; -(으)ㄴ 후에 / 다음에 significa "después de (hacer)" — el evento principal ocurre DESPUÉS, una vez completado ese verbo. Ponen las dos acciones en orden temporal opuesto, así que la secuencia real de cada oración fija una sola.',
      '-기 전에 signifie « avant de (faire) » — l\'événement de la principale a lieu PLUS TÔT que le verbe de la subordonnée ; -(으)ㄴ 후에 / 다음에 signifie « après (avoir fait) » — l\'événement principal a lieu PLUS TARD, une fois ce verbe achevé. Ils placent les deux actions dans l\'ordre temporel inverse, donc la séquence réelle de chaque phrase n\'en fixe qu\'une.',
      '-기 전에 significa "antes de (fazer)" — o evento da oração principal acontece ANTES do verbo da oração; -(으)ㄴ 후에 / 다음에 significa "depois de (fazer)" — o evento principal acontece DEPOIS, uma vez concluído esse verbo. Eles colocam as duas ações em ordem temporal oposta, então a sequência real de cada frase fixa apenas uma.',
      '-기 전에 หมายถึง "ก่อน(ทำ)" — เหตุการณ์ในประโยคหลักเกิดขึ้นก่อนกริยาในอนุประโยค ส่วน -(으)ㄴ 후에 / 다음에 หมายถึง "หลังจาก(ทำ)" — เหตุการณ์หลักเกิดขึ้นทีหลัง เมื่อกริยานั้นเสร็จแล้ว ทั้งสองวางสองการกระทำไว้ในลำดับเวลาตรงข้ามกัน ดังนั้นลำดับตามความเป็นจริงในแต่ละประโยคจึงกำหนดได้เพียงรูปเดียว',
      '-기 전에 berarti "sebelum (melakukan)" — peristiwa klausa utama terjadi LEBIH AWAL daripada verba di klausa itu; -(으)ㄴ 후에 / 다음에 berarti "setelah (melakukan)" — peristiwa utama terjadi LEBIH LAMBAT, setelah verba itu selesai. Keduanya menempatkan dua aksi dalam urutan waktu yang berlawanan, jadi urutan nyata di tiap kalimat hanya mengunci satu.',
      '-기 전에 nghĩa là "trước khi (làm)" — sự việc ở mệnh đề chính xảy ra SỚM HƠN động từ trong mệnh đề; -(으)ㄴ 후에 / 다음에 nghĩa là "sau khi (làm)" — sự việc chính xảy ra MUỘN HƠN, sau khi động từ đó hoàn tất. Chúng đặt hai hành động theo trình tự thời gian ngược nhau, nên trình tự thực tế trong mỗi câu chỉ ghim đúng một dạng.',
      '-기 전에 は「〜する前に」の意味で、主節の出来事が従属節の動詞より先に起こる。-(으)ㄴ 후에 / 다음에 は「〜した後で」の意味で、その動詞が完了した後に主節の出来事が起こる。両者は二つの動作を逆の時間順に置くため、各文の現実の順序が一つの形だけに決まる。',
    ),
    items: [
      {
        sentence: '저는 {} 이를 닦아요.',
        optionA: '자기 전에',
        optionB: '잔 후에',
        answer: 'a',
        trans: L(
          'I brush my teeth before sleeping.',
          'Me cepillo los dientes antes de dormir.',
          'Je me brosse les dents avant de dormir.',
          'Eu escovo os dentes antes de dormir.',
          'ฉันแปรงฟันก่อนนอน',
          'Saya menyikat gigi sebelum tidur.',
          'Tôi đánh răng trước khi đi ngủ.',
          '私は寝る前に歯を磨きます。',
        ),
        why: L(
          'Brushing teeth as nightly hygiene comes BEFORE going to sleep, so 자기 전에 (before) fits; 잔 후에 (after sleeping) would mean brushing once you wake from sleep, which contradicts the bedtime routine.',
          'Cepillarse los dientes como higiene nocturna va ANTES de irse a dormir, así que encaja 자기 전에 (antes); 잔 후에 (después de dormir) significaría cepillarse al despertar, lo que contradice la rutina de antes de dormir.',
          'Se brosser les dents comme hygiène du soir vient AVANT de s\'endormir, donc 자기 전에 (avant) convient ; 잔 후에 (après avoir dormi) voudrait dire se brosser au réveil, ce qui contredit le rituel du coucher.',
          'Escovar os dentes como higiene noturna vem ANTES de ir dormir, então cabe 자기 전에 (antes); 잔 후에 (depois de dormir) significaria escovar ao acordar, o que contradiz a rotina de dormir.',
          'การแปรงฟันเป็นสุขอนามัยก่อนนอนซึ่งทำก่อนเข้านอน จึงใช้ 자기 전에 (ก่อน); ส่วน 잔 후에 (หลังจากนอน) จะหมายถึงแปรงฟันตอนตื่น ซึ่งขัดกับกิจวัตรก่อนนอน',
          'Menyikat gigi sebagai higiene malam dilakukan SEBELUM tidur, jadi 자기 전에 (sebelum) cocok; 잔 후에 (setelah tidur) berarti menyikat saat bangun, yang bertentangan dengan rutinitas menjelang tidur.',
          'Đánh răng như vệ sinh buổi tối diễn ra TRƯỚC khi đi ngủ, nên 자기 전에 (trước khi) phù hợp; 잔 후에 (sau khi ngủ) lại có nghĩa đánh răng khi thức dậy, mâu thuẫn với thói quen trước khi ngủ.',
          '夜の習慣としての歯磨きは寝る前に行うので 자기 전에（前に）が合う。잔 후에（寝た後で）だと目覚めてから磨く意味になり、就寝前の習慣と矛盾する。',
        ),
      },
      {
        sentence: '저는 {} 설거지를 해요.',
        optionA: '먹기 전에',
        optionB: '먹은 후에',
        answer: 'b',
        trans: L(
          'I wash the dishes after eating.',
          'Lavo los platos después de comer.',
          'Je fais la vaisselle après avoir mangé.',
          'Eu lavo a louça depois de comer.',
          'ฉันล้างจานหลังจากกินข้าว',
          'Saya mencuci piring setelah makan.',
          'Tôi rửa bát sau khi ăn.',
          '私は食べた後で皿洗いをします。',
        ),
        why: L(
          'Dirty dishes exist only once the meal is over, so washing them comes AFTER eating → 먹은 후에; 먹기 전에 (before eating) would put the cleanup before there is anything to clean.',
          'Los platos sucios solo existen una vez terminada la comida, así que lavarlos va DESPUÉS de comer → 먹은 후에; 먹기 전에 (antes de comer) pondría la limpieza antes de que haya algo que limpiar.',
          'La vaisselle sale n\'existe qu\'une fois le repas terminé, donc la laver vient APRÈS avoir mangé → 먹은 후에 ; 먹기 전에 (avant de manger) placerait le nettoyage avant qu\'il y ait quoi que ce soit à nettoyer.',
          'A louça suja só existe depois que a refeição acaba, então lavá-la vem DEPOIS de comer → 먹은 후에; 먹기 전에 (antes de comer) colocaria a limpeza antes de haver algo para limpar.',
          'จานสกปรกมีก็ต่อเมื่อกินเสร็จแล้ว การล้างจึงทำหลังจากกิน → 먹은 후에; ส่วน 먹기 전에 (ก่อนกิน) จะวางการล้างไว้ก่อนที่จะมีอะไรให้ล้าง',
          'Piring kotor baru ada setelah makan selesai, jadi mencucinya dilakukan SETELAH makan → 먹은 후에; 먹기 전에 (sebelum makan) akan menaruh pencucian sebelum ada yang perlu dicuci.',
          'Bát đĩa bẩn chỉ có khi bữa ăn đã xong, nên rửa chúng diễn ra SAU khi ăn → 먹은 후에; 먹기 전에 (trước khi ăn) sẽ đặt việc dọn rửa trước khi có gì để rửa.',
          '汚れた食器は食事が終わってから生じるので、洗うのは食べた後 → 먹은 후에。먹기 전에（食べる前に）だと、洗う対象がまだない時点に片付けを置くことになる。',
        ),
      },
      {
        sentence: '영화관에서는 {} 표를 사야 해요.',
        optionA: '보기 전에',
        optionB: '본 후에',
        answer: 'a',
        trans: L(
          'At the cinema you have to buy the ticket before watching (the movie).',
          'En el cine hay que comprar la entrada antes de ver (la película).',
          'Au cinéma, il faut acheter le billet avant de regarder (le film).',
          'No cinema, é preciso comprar o ingresso antes de assistir (ao filme).',
          'ที่โรงหนังต้องซื้อตั๋วก่อนดู (หนัง)',
          'Di bioskop, kamu harus membeli tiket sebelum menonton (filmnya).',
          'Ở rạp phim, bạn phải mua vé trước khi xem (phim).',
          '映画館では見る前にチケットを買わなければなりません。',
        ),
        why: L(
          'A ticket admits you to the screening, so you must buy it BEFORE watching → 보기 전에; 본 후에 (after watching) is illogical because you cannot enter to watch without already holding the ticket.',
          'La entrada te da acceso a la función, así que hay que comprarla ANTES de ver → 보기 전에; 본 후에 (después de ver) es ilógico porque no podés entrar a ver sin tener ya la entrada.',
          'Le billet vous donne accès à la séance, il faut donc l\'acheter AVANT de regarder → 보기 전에 ; 본 후에 (après avoir regardé) est illogique car on ne peut entrer pour regarder sans avoir déjà le billet.',
          'O ingresso dá acesso à sessão, então é preciso comprá-lo ANTES de assistir → 보기 전에; 본 후에 (depois de assistir) é ilógico porque não dá para entrar para assistir sem já ter o ingresso.',
          'ตั๋วเป็นสิ่งที่ให้คุณเข้าชมรอบฉาย จึงต้องซื้อก่อนดู → 보기 전에; ส่วน 본 후에 (หลังจากดู) ไม่สมเหตุผล เพราะเข้าไปดูไม่ได้ถ้ายังไม่มีตั๋ว',
          'Tiket memberimu akses ke pemutaran, jadi harus dibeli SEBELUM menonton → 보기 전에; 본 후에 (setelah menonton) tidak masuk akal karena kamu tidak bisa masuk menonton tanpa sudah memegang tiket.',
          'Vé cho bạn vào suất chiếu, nên phải mua TRƯỚC khi xem → 보기 전에; 본 후에 (sau khi xem) là vô lý vì bạn không thể vào xem khi chưa có vé.',
          'チケットは上映への入場を可能にするので、見る前に買う必要がある → 보기 전에。본 후에（見た後で）は、チケットなしには見るために入れないため不合理。',
        ),
      },
    ],
  },
  {
    id: 'geore-jido',
    a: '-(으)ㄹ까 봐',
    b: '-(으)ㄹ지도 모르다',
    note: L(
      '-(으)ㄹ까 봐 is a CONNECTIVE meaning "for fear that / worried that ..." — it expresses an apprehension that motivates a precaution, so it must be followed by a main clause (the precautionary action) and cannot end the sentence on its own. -(으)ㄹ지도 모르다 is a sentence-FINAL predicate meaning "might / maybe / it\'s possible that ..." — a neutral statement of uncertain possibility that closes the sentence. So when the blank ends the sentence, only -(으)ㄹ지도 모르다 works; when the blank is followed by a worried precaution, only -(으)ㄹ까 봐 works.',
      '-(으)ㄹ까 봐 es un CONECTOR que significa "por miedo a que / preocupado de que ..." — expresa una aprensión que motiva una precaución, así que debe ir seguido de una cláusula principal (la acción preventiva) y no puede cerrar la oración por sí solo. -(으)ㄹ지도 모르다 es un predicado FINAL que significa "puede que / quizás / es posible que ..." — una afirmación neutra de posibilidad incierta que cierra la oración. Por eso, cuando el espacio cierra la oración, solo funciona -(으)ㄹ지도 모르다; cuando al espacio le sigue una precaución por preocupación, solo funciona -(으)ㄹ까 봐.',
      '-(으)ㄹ까 봐 est un CONNECTEUR signifiant « de peur que / inquiet que ... » — il exprime une appréhension qui motive une précaution, il doit donc être suivi d\'une principale (l\'action de précaution) et ne peut pas terminer la phrase seul. -(으)ㄹ지도 모르다 est un prédicat FINAL signifiant « il se peut que / peut-être ... » — une affirmation neutre de possibilité incertaine qui clôt la phrase. Donc, quand le blanc termine la phrase, seul -(으)ㄹ지도 모르다 fonctionne ; quand le blanc est suivi d\'une précaution inquiète, seul -(으)ㄹ까 봐 fonctionne.',
      '-(으)ㄹ까 봐 é um CONECTIVO que significa "com medo de que / preocupado de que ..." — exprime uma apreensão que motiva uma precaução, então deve ser seguido de uma oração principal (a ação preventiva) e não pode encerrar a frase sozinho. -(으)ㄹ지도 모르다 é um predicado FINAL que significa "pode ser que / talvez ..." — uma afirmação neutra de possibilidade incerta que fecha a frase. Por isso, quando a lacuna encerra a frase, só funciona -(으)ㄹ지도 모르다; quando a lacuna é seguida de uma precaução preocupada, só funciona -(으)ㄹ까 봐.',
      '-(으)ㄹ까 봐 เป็นคำเชื่อมที่หมายถึง "เพราะกลัวว่าจะ / กังวลว่าจะ ..." — แสดงความกังวลที่ผลักดันให้ทำการป้องกัน จึงต้องตามด้วยประโยคหลัก (การกระทำเพื่อป้องกัน) และจบประโยคด้วยตัวเองไม่ได้ ส่วน -(으)ㄹ지도 모르다 เป็นภาคแสดงท้ายประโยคที่หมายถึง "อาจจะ / เป็นไปได้ว่า ..." — เป็นการกล่าวอย่างเป็นกลางถึงความเป็นไปได้ที่ไม่แน่นอนซึ่งปิดประโยค ดังนั้นเมื่อช่องว่างอยู่ท้ายประโยค ใช้ได้แค่ -(으)ㄹ지도 모르다; เมื่อหลังช่องว่างมีการป้องกันที่มาจากความกังวล ใช้ได้แค่ -(으)ㄹ까 봐',
      '-(으)ㄹ까 봐 adalah KONJUNGSI yang berarti "khawatir kalau-kalau / takut bahwa ..." — mengungkapkan kekhawatiran yang mendorong suatu pencegahan, jadi harus diikuti klausa utama (tindakan pencegahan) dan tidak bisa mengakhiri kalimat sendiri. -(으)ㄹ지도 모르다 adalah predikat AKHIR yang berarti "mungkin / bisa jadi ..." — pernyataan netral tentang kemungkinan tak pasti yang menutup kalimat. Maka, ketika rumpang mengakhiri kalimat, hanya -(으)ㄹ지도 모르다 yang berfungsi; ketika rumpang diikuti pencegahan karena khawatir, hanya -(으)ㄹ까 봐 yang berfungsi.',
      '-(으)ㄹ까 봐 là một LIÊN TỪ nghĩa là "vì sợ rằng / lo rằng ..." — diễn tả nỗi lo thúc đẩy một biện pháp phòng ngừa, nên phải có một mệnh đề chính theo sau (hành động phòng ngừa) và không thể tự mình kết thúc câu. -(으)ㄹ지도 모르다 là một vị ngữ KẾT THÚC câu nghĩa là "có thể / biết đâu ..." — một câu khẳng định trung tính về khả năng không chắc chắn, dùng để khép câu. Vì vậy, khi chỗ trống kết thúc câu, chỉ -(으)ㄹ지도 모르다 dùng được; khi sau chỗ trống là một biện pháp phòng ngừa do lo lắng, chỉ -(으)ㄹ까 봐 dùng được.',
      '-(으)ㄹ까 봐 は「〜するのではないかと心配して」という意味の接続表現で、用心を促す不安を表すため、後ろに主節（その用心の行動）が必要で、それだけで文を終えられない。-(으)ㄹ지도 모르다 は「〜かもしれない」という意味の文末述語で、不確実な可能性を中立的に述べて文を締めくくる。したがって、空所が文末なら -(으)ㄹ지도 모르다 だけが成立し、空所の後ろに心配からくる用心が続くなら -(으)ㄹ까 봐 だけが成立する。',
    ),
    items: [
      {
        sentence: '아직 확실하지 않지만, 내일 갑자기 일이 {}.',
        optionA: '생길까 봐',
        optionB: '생길지도 몰라요',
        answer: 'b',
        trans: L(
          'It\'s not certain yet, but something might suddenly come up tomorrow.',
          'Todavía no es seguro, pero mañana puede que surja algo de repente.',
          'Ce n\'est pas encore sûr, mais il se peut qu\'un imprévu survienne demain.',
          'Ainda não é certo, mas amanhã pode ser que surja algo de repente.',
          'ยังไม่แน่นอน แต่พรุ่งนี้อาจจะมีอะไรเกิดขึ้นกะทันหัน',
          'Belum pasti, tetapi besok mungkin tiba-tiba ada urusan.',
          'Vẫn chưa chắc, nhưng ngày mai biết đâu lại đột nhiên có việc.',
          'まだ確実ではありませんが、明日急に用事ができるかもしれません。',
        ),
        why: L(
          'The blank ends the sentence as its final predicate and the clause is a neutral guess ("not certain yet, but ..."), so only the sentence-final 생길지도 몰라요 works; 생길까 봐 is a connective that needs a following precaution clause and cannot close the sentence.',
          'El espacio cierra la oración como su predicado final y la cláusula es una conjetura neutra ("todavía no es seguro, pero ..."), así que solo funciona el final 생길지도 몰라요; 생길까 봐 es un conector que necesita una cláusula de precaución posterior y no puede cerrar la oración.',
          'Le blanc termine la phrase en tant que prédicat final et la proposition est une supposition neutre (« pas encore sûr, mais ... »), donc seul le final 생길지도 몰라요 fonctionne ; 생길까 봐 est un connecteur qui exige une proposition de précaution à la suite et ne peut clore la phrase.',
          'A lacuna encerra a frase como seu predicado final e a oração é um palpite neutro ("ainda não é certo, mas ..."), então só funciona o final 생길지도 몰라요; 생길까 봐 é um conectivo que precisa de uma oração de precaução em seguida e não pode fechar a frase.',
          'ช่องว่างปิดประโยคในฐานะภาคแสดงท้ายประโยค และอนุประโยคเป็นการคาดเดาอย่างเป็นกลาง ("ยังไม่แน่นอน แต่ ...") จึงใช้ได้แค่รูปท้ายประโยค 생길지도 몰라요; ส่วน 생길까 봐 เป็นคำเชื่อมที่ต้องมีอนุประโยคการป้องกันตามมา และปิดประโยคไม่ได้',
          'Rumpang mengakhiri kalimat sebagai predikat akhirnya dan klausanya adalah tebakan netral ("belum pasti, tetapi ..."), jadi hanya 생길지도 몰라요 di akhir yang berfungsi; 생길까 봐 adalah konjungsi yang memerlukan klausa pencegahan setelahnya dan tidak bisa menutup kalimat.',
          'Chỗ trống kết thúc câu với vai trò vị ngữ cuối và mệnh đề là một phỏng đoán trung tính ("chưa chắc, nhưng ..."), nên chỉ 생길지도 몰라요 ở cuối câu dùng được; 생길까 봐 là liên từ cần một mệnh đề phòng ngừa theo sau và không thể khép câu.',
          '空所は文末述語として文を終え、節は中立的な推測（「まだ確実ではないが…」）なので、文末形 생길지도 몰라요 だけが成立する。생길까 봐 は後ろに用心の節を必要とする接続表現で、文を締めくくれない。',
        ),
      },
      {
        sentence: '시험에 {} 매일 밤늦게까지 공부했어요.',
        optionA: '떨어질까 봐',
        optionB: '떨어질지도 몰라요',
        answer: 'a',
        trans: L(
          'Worried I might fail the exam, I studied late into the night every day.',
          'Por miedo a reprobar el examen, estudié hasta tarde todas las noches.',
          'De peur de rater l\'examen, j\'ai étudié tard chaque nuit.',
          'Com medo de reprovar na prova, estudei até tarde toda noite.',
          'เพราะกลัวว่าจะสอบตก ฉันเลยอ่านหนังสือจนดึกทุกคืน',
          'Karena khawatir gagal ujian, saya belajar sampai larut malam setiap hari.',
          'Vì sợ trượt kỳ thi, tôi đã học đến tận khuya mỗi ngày.',
          '試験に落ちるのではないかと心配で、毎日夜遅くまで勉強しました。',
        ),
        why: L(
          'The blank is followed by a precaution (studying hard) driven by worry, exactly the connective role of 떨어질까 봐; 떨어질지도 몰라요 is a sentence-final form and cannot grammatically connect to the following "I studied every night" clause as its motivation.',
          'Al espacio le sigue una precaución (estudiar mucho) motivada por la preocupación, justo el papel conector de 떨어질까 봐; 떨어질지도 몰라요 es una forma final y no puede conectarse gramaticalmente con la cláusula siguiente "estudié todas las noches" como su motivo.',
          'Le blanc est suivi d\'une précaution (étudier dur) motivée par l\'inquiétude, exactement le rôle connecteur de 떨어질까 봐 ; 떨어질지도 몰라요 est une forme finale et ne peut se relier grammaticalement à la proposition suivante « j\'ai étudié chaque nuit » comme sa motivation.',
          'A lacuna é seguida de uma precaução (estudar muito) movida pela preocupação, exatamente o papel conectivo de 떨어질까 봐; 떨어질지도 몰라요 é uma forma final e não pode se conectar gramaticalmente à oração seguinte "estudei toda noite" como seu motivo.',
          'หลังช่องว่างมีการป้องกัน (อ่านหนังสืออย่างหนัก) ที่เกิดจากความกังวล ซึ่งตรงกับบทบาทคำเชื่อมของ 떨어질까 봐; ส่วน 떨어질지도 몰라요 เป็นรูปท้ายประโยค และเชื่อมกับอนุประโยค "อ่านหนังสือทุกคืน" ที่ตามมาในฐานะแรงจูงใจไม่ได้ตามหลักไวยากรณ์',
          'Rumpang diikuti pencegahan (belajar keras) yang didorong kekhawatiran, persis peran konjungsi 떨어질까 봐; 떨어질지도 몰라요 adalah bentuk akhir dan tidak bisa secara gramatikal terhubung ke klausa berikut "saya belajar tiap malam" sebagai motifnya.',
          'Sau chỗ trống là một biện pháp phòng ngừa (học chăm) do lo lắng thúc đẩy, đúng vai trò liên từ của 떨어질까 봐; 떨어질지도 몰라요 là dạng kết thúc câu và không thể nối về mặt ngữ pháp với mệnh đề "tôi học mỗi đêm" theo sau như là động cơ.',
          '空所の後ろには心配から来る用心（一生懸命勉強する）が続いており、まさに 떨어질까 봐 の接続的役割。떨어질지도 몰라요 は文末形で、後続の「毎晩勉強した」という節にその動機として文法的につなげられない。',
        ),
      },
      {
        sentence: '연락이 안 되네요. 그 사람이 벌써 {}.',
        optionA: '떠났을까 봐',
        optionB: '떠났을지도 몰라요',
        answer: 'b',
        trans: L(
          'I can\'t reach them. They might have already left.',
          'No logro contactarlos. Puede que ya se hayan ido.',
          'Je n\'arrive pas à les joindre. Ils sont peut-être déjà partis.',
          'Não consigo contato. Pode ser que já tenham ido embora.',
          'ติดต่อไม่ได้เลย เขาอาจจะไปแล้วก็ได้',
          'Tidak bisa dihubungi. Mungkin dia sudah pergi.',
          'Không liên lạc được. Biết đâu người đó đã đi rồi.',
          '連絡がつきませんね。あの人はもう発ったかもしれません。',
        ),
        why: L(
          'The blank is the final predicate stating a neutral past possibility ("might have already left"), which only the sentence-final 떠났을지도 몰라요 expresses; 떠났을까 봐 is a connective demanding a following precaution clause, so it cannot end the sentence here.',
          'El espacio es el predicado final que enuncia una posibilidad pasada neutra ("puede que ya se hayan ido"), lo que solo expresa el final 떠났을지도 몰라요; 떠났을까 봐 es un conector que exige una cláusula de precaución posterior, así que no puede cerrar la oración acá.',
          'Le blanc est le prédicat final énonçant une possibilité passée neutre (« peut-être déjà partis »), ce que seul le final 떠났을지도 몰라요 exprime ; 떠났을까 봐 est un connecteur exigeant une proposition de précaution à la suite, il ne peut donc pas terminer la phrase ici.',
          'A lacuna é o predicado final que enuncia uma possibilidade passada neutra ("pode ser que já tenham ido"), o que só o final 떠났을지도 몰라요 expressa; 떠났을까 봐 é um conectivo que exige uma oração de precaução em seguida, então não pode encerrar a frase aqui.',
          'ช่องว่างคือภาคแสดงท้ายประโยคที่กล่าวถึงความเป็นไปได้ในอดีตอย่างเป็นกลาง ("อาจจะไปแล้ว") ซึ่งมีแต่รูปท้ายประโยค 떠났을지도 몰라요 ที่แสดงได้; ส่วน 떠났을까 봐 เป็นคำเชื่อมที่ต้องมีอนุประโยคการป้องกันตามมา จึงปิดประโยคในที่นี้ไม่ได้',
          'Rumpang adalah predikat akhir yang menyatakan kemungkinan lampau yang netral ("mungkin sudah pergi"), yang hanya diungkapkan oleh 떠났을지도 몰라요 di akhir; 떠났을까 봐 adalah konjungsi yang menuntut klausa pencegahan setelahnya, jadi tidak bisa mengakhiri kalimat di sini.',
          'Chỗ trống là vị ngữ cuối nêu một khả năng quá khứ trung tính ("biết đâu đã đi rồi"), điều mà chỉ 떠났을지도 몰라요 ở cuối câu diễn đạt được; 떠났을까 봐 là liên từ đòi hỏi một mệnh đề phòng ngừa theo sau, nên không thể kết thúc câu ở đây.',
          '空所は中立的な過去の可能性（「もう発ったかもしれない」）を述べる文末述語であり、それを表せるのは文末形 떠났을지도 몰라요 だけ。떠났을까 봐 は後ろに用心の節を要求する接続表現なので、ここで文を終えられない。',
        ),
      },
    ],
  },
]
