import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK 2 confusable grammar/ending pairs. a/b match grammars-n*.ts kos
 * verbatim. Each pair: a contrast note + 3 single-answer discrimination items,
 * 8-locale note/trans/why.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow
 * (single-correct-answer crux, naturalness, conjugation, 8-locale fidelity).
 * Native (Korean wife) review is the documented final gate.
 */
export const N2_PAIRS: ConfusablePair[] = [
  {
    id: 'lge-georeyo',
    a: '-(으)ㄹ게요',
    b: '-(으)ㄹ 거예요',
    note: L(
      '-(으)ㄹ게요 is a first-person promise or offer the speaker commits TO a present listener in reaction to the situation (needs a "you" and a willing subject); -(으)ㄹ 거예요 is a neutral statement of future plan, intention, or prediction that needs no listener and is the only option for third persons and non-volitional events like the weather. Watch out: with a first-person volitional verb and no reactive-commitment force, BOTH forms are often acceptable, so each item must pin the context to exactly one.',
      '-(으)ㄹ게요 es una promesa u ofrecimiento en primera persona que el hablante se compromete a cumplir ANTE un oyente presente, como reacción a la situación (necesita un "vos" y un sujeto con voluntad); -(으)ㄹ 거예요 es una afirmación neutra de plan, intención o predicción futura que no requiere oyente y es la única opción para terceras personas y eventos no volitivos como el clima. Ojo: con un verbo volitivo en primera persona y sin fuerza de compromiso reactivo, AMBAS formas suelen ser aceptables, así que cada ítem debe fijar el contexto a una sola.',
      '-(으)ㄹ게요 est une promesse ou une offre à la première personne que le locuteur s\'engage à tenir DEVANT un interlocuteur présent, en réaction à la situation (il faut un "tu" et un sujet doté de volonté) ; -(으)ㄹ 거예요 est une affirmation neutre de projet, d\'intention ou de prédiction future qui n\'a besoin d\'aucun interlocuteur et constitue la seule option pour les troisièmes personnes et les événements non volontaires comme la météo. Attention : avec un verbe volontaire à la première personne et sans force d\'engagement réactif, les DEUX formes sont souvent acceptables, donc chaque item doit fixer le contexte à une seule.',
      '-(으)ㄹ게요 é uma promessa ou oferecimento na primeira pessoa que o falante se compromete a cumprir DIANTE de um ouvinte presente, como reação à situação (precisa de um "você" e de um sujeito com vontade); -(으)ㄹ 거예요 é uma afirmação neutra de plano, intenção ou previsão futura que não exige ouvinte e é a única opção para terceiras pessoas e eventos não volitivos como o clima. Atenção: com um verbo volitivo na primeira pessoa e sem força de compromisso reativo, AMBAS as formas costumam ser aceitáveis, então cada item precisa fixar o contexto a apenas uma.',
      '-(으)ㄹ게요 คือคำสัญญาหรือข้อเสนอในบุรุษที่หนึ่งที่ผู้พูดให้คำมั่นว่าจะทำ ต่อหน้าผู้ฟังที่อยู่ตรงนั้น เพื่อตอบสนองต่อสถานการณ์ (ต้องมี "คุณ" และประธานที่มีเจตจำนง); ส่วน -(으)ㄹ 거예요 เป็นการกล่าวอย่างเป็นกลางถึงแผน ความตั้งใจ หรือการทำนายในอนาคต ซึ่งไม่จำเป็นต้องมีผู้ฟัง และเป็นทางเลือกเดียวสำหรับบุรุษที่สามและเหตุการณ์ที่ไม่ได้เกิดจากเจตจำนง เช่น สภาพอากาศ ข้อควรระวัง: เมื่อใช้กับกริยาที่มีเจตจำนงในบุรุษที่หนึ่งและไม่มีน้ำหนักของการให้คำมั่นแบบตอบสนอง ทั้งสองรูปมักใช้ได้ทั้งคู่ ดังนั้นแต่ละข้อต้องกำหนดบริบทให้ลงตัวกับรูปเดียวเท่านั้น',
      '-(으)ㄹ게요 adalah janji atau tawaran orang pertama yang penutur ikrarkan untuk dilakukan DI HADAPAN pendengar yang hadir, sebagai reaksi atas situasi (memerlukan "kamu" dan subjek yang berkehendak); -(으)ㄹ 거예요 adalah pernyataan netral tentang rencana, niat, atau prediksi masa depan yang tidak memerlukan pendengar dan merupakan satu-satunya pilihan untuk orang ketiga serta peristiwa nonvolitif seperti cuaca. Perhatikan: dengan verba volitif orang pertama dan tanpa daya komitmen reaktif, KEDUA bentuk sering kali dapat diterima, jadi tiap butir harus mengunci konteks ke satu bentuk saja.',
      '-(으)ㄹ게요 là một lời hứa hoặc lời đề nghị ở ngôi thứ nhất mà người nói cam kết thực hiện TRƯỚC một người nghe đang có mặt, để phản ứng với tình huống (cần có một "bạn" và một chủ ngữ có ý chí); -(으)ㄹ 거예요 là một câu khẳng định trung tính về kế hoạch, ý định hoặc dự đoán tương lai, không cần người nghe và là lựa chọn duy nhất cho ngôi thứ ba cùng những sự việc không mang ý chí như thời tiết. Lưu ý: với một động từ mang ý chí ở ngôi thứ nhất và không có lực cam kết phản ứng, CẢ HAI dạng thường đều chấp nhận được, nên mỗi mục phải ghim ngữ cảnh về đúng một dạng.',
      '-(으)ㄹ게요 は、状況への反応として、話し手がその場にいる聞き手に対して果たすと約束する一人称の約束や申し出である(「あなた」と意志を持つ主語が必要)。-(으)ㄹ 거예요 は、聞き手を必要としない未来の計画・意図・予測を中立的に述べるもので、三人称や天気のような非意志的な出来事にはこちらが唯一の選択肢となる。注意:一人称の意志動詞で反応的な約束の力がない場合、両方の形がしばしば成立するため、各項目は文脈を一つの形だけに絞り込む必要がある。',
    ),
    items: [
      {
        sentence: '(친구에게) 걱정하지 마. 내가 도와{}.',
        optionA: '줄게',
        optionB: '줄 거야',
        answer: 'a',
        trans: L(
          '(To a friend) Don\'t worry. I\'ll help you.',
          '(A un amigo) No te preocupes. Yo te ayudo.',
          '(À un ami) Ne t\'inquiète pas. Je vais t\'aider.',
          '(Para um amigo) Não se preocupe. Eu vou te ajudar.',
          '(พูดกับเพื่อน) ไม่ต้องห่วงนะ เดี๋ยวฉันช่วยเอง',
          '(Kepada teman) Jangan khawatir. Aku akan membantumu.',
          '(Nói với bạn) Đừng lo. Mình sẽ giúp cậu.',
          '(友達に)心配しないで。私が手伝ってあげるよ。',
        ),
        why: L(
          'A reassuring offer made directly to the worried listener, in reaction to their worry, takes the commitment form 줄게; 줄 거야 states a detached future fact and does not function as the act of reassuring them here.',
          'Un ofrecimiento tranquilizador hecho directamente al oyente preocupado, en reacción a su preocupación, lleva la forma de compromiso 줄게; 줄 거야 expresa un hecho futuro distante y acá no funciona como el acto de tranquilizarlo.',
          'Une offre rassurante faite directement à l\'interlocuteur inquiet, en réaction à son inquiétude, prend la forme d\'engagement 줄게 ; 줄 거야 énonce un fait futur détaché et ne fonctionne pas ici comme l\'acte de le rassurer.',
          'Um oferecimento tranquilizador feito diretamente ao ouvinte preocupado, em reação à preocupação dele, usa a forma de compromisso 줄게; 줄 거야 enuncia um fato futuro distante e não funciona aqui como o ato de tranquilizá-lo.',
          'ข้อเสนอที่ให้ความอุ่นใจซึ่งพูดตรงกับผู้ฟังที่กำลังกังวล เป็นการตอบสนองต่อความกังวลของเขา จึงใช้รูปคำมั่น 줄게; ส่วน 줄 거야 เป็นการบอกข้อเท็จจริงในอนาคตแบบไม่เกี่ยวข้องโดยตรง และไม่ได้ทำหน้าที่ปลอบใจเขาในที่นี้',
          'Tawaran yang menenangkan yang ditujukan langsung kepada pendengar yang khawatir, sebagai reaksi atas kekhawatirannya, memakai bentuk komitmen 줄게; 줄 거야 menyatakan fakta masa depan yang lepas dan di sini tidak berfungsi sebagai tindakan menenangkannya.',
          'Một lời đề nghị trấn an nói thẳng với người nghe đang lo lắng, để phản ứng lại nỗi lo của họ, dùng dạng cam kết 줄게; 줄 거야 nêu một sự việc tương lai tách biệt và ở đây không đóng vai trò trấn an họ.',
          '心配している聞き手に直接、その心配に反応して差し出す安心の申し出なので、約束の形 줄게 を使う。줄 거야 は切り離された未来の事実を述べるだけで、ここでは相手を安心させる行為としては機能しない。',
        ),
      },
      {
        sentence: '일기예보를 보니까 내일은 비가 {}.',
        optionA: '올게요',
        optionB: '올 거예요',
        answer: 'b',
        trans: L(
          'According to the forecast, it\'ll rain tomorrow.',
          'Según el pronóstico, mañana va a llover.',
          'D\'après les prévisions, il va pleuvoir demain.',
          'Segundo a previsão, amanhã vai chover.',
          'ตามพยากรณ์อากาศ พรุ่งนี้ฝนจะตก',
          'Menurut ramalan cuaca, besok akan hujan.',
          'Theo dự báo, ngày mai trời sẽ mưa.',
          '予報によると、明日は雨が降るそうだ。',
        ),
        why: L(
          'Rain is non-volitional and this is a forecast-based prediction, so only 올 거예요 works; 올게요 would make the rain promise something to the listener, which is impossible since 게요 needs a willing first-person subject.',
          'La lluvia no es volitiva y esto es una predicción basada en el pronóstico, así que solo funciona 올 거예요; 올게요 haría que la lluvia le prometiera algo al oyente, lo cual es imposible porque 게요 necesita un sujeto de primera persona con voluntad.',
          'La pluie n\'est pas volontaire et il s\'agit d\'une prédiction fondée sur les prévisions, donc seul 올 거예요 fonctionne ; 올게요 ferait que la pluie promette quelque chose à l\'interlocuteur, ce qui est impossible puisque 게요 exige un sujet de première personne doté de volonté.',
          'A chuva não é volitiva e isto é uma previsão baseada no boletim, então só funciona 올 거예요; 올게요 faria a chuva prometer algo ao ouvinte, o que é impossível porque 게요 precisa de um sujeito de primeira pessoa com vontade.',
          'ฝนไม่ใช่สิ่งที่เกิดจากเจตจำนง และนี่คือการคาดการณ์จากพยากรณ์อากาศ จึงใช้ได้แค่ 올 거예요; ส่วน 올게요 จะทำให้ฝนสัญญาอะไรบางอย่างกับผู้ฟัง ซึ่งเป็นไปไม่ได้ เพราะ 게요 ต้องการประธานบุรุษที่หนึ่งที่มีเจตจำนง',
          'Hujan bukan hal yang berkehendak dan ini adalah prediksi berdasarkan ramalan cuaca, jadi hanya 올 거예요 yang berfungsi; 올게요 akan membuat hujan menjanjikan sesuatu kepada pendengar, yang mustahil karena 게요 membutuhkan subjek orang pertama yang berkehendak.',
          'Mưa không mang ý chí và đây là một dự đoán dựa trên dự báo, nên chỉ 올 거예요 dùng được; 올게요 sẽ khiến cơn mưa hứa hẹn điều gì đó với người nghe, điều bất khả thi vì 게요 cần một chủ ngữ ngôi thứ nhất có ý chí.',
          '雨は意志を持たず、これは予報に基づく予測なので、使えるのは 올 거예요 だけ。올게요 にすると雨が聞き手に何かを約束することになってしまい、게요 は意志のある一人称主語を必要とするため不可能である。',
        ),
      },
      {
        sentence: '늦어서 정말 죄송합니다. 다음부터는 꼭 일찍 {}.',
        optionA: '오겠습니다',
        optionB: '올 겁니다',
        answer: 'a',
        trans: L(
          'I\'m so sorry I was late. From now on I\'ll definitely come early.',
          'Perdón de verdad por llegar tarde. De ahora en adelante voy a venir temprano sin falta.',
          'Je suis vraiment désolé d\'être arrivé en retard. À partir de maintenant, je viendrai tôt sans faute.',
          'Desculpe mesmo por ter chegado tarde. De agora em diante vou chegar cedo sem falta.',
          'ขอโทษจริงๆ ที่มาสาย ต่อจากนี้ไปจะมาแต่เช้าให้ได้แน่นอน',
          'Maaf sekali aku terlambat. Mulai sekarang aku pasti akan datang lebih awal.',
          'Tôi thật sự xin lỗi vì đã đến muộn. Từ giờ trở đi tôi nhất định sẽ đến sớm.',
          '遅れて本当にすみません。これからは必ず早く来ます。',
        ),
        why: L(
          'Apologizing to the listener and pledging future behavior in reaction is a commitment, so the promise form 오겠습니다 (the formal counterpart of 올게요) fits; 올 겁니다 states a prediction about oneself and does not carry the apologetic pledge the situation demands.',
          'Disculparse con el oyente y comprometerse a un comportamiento futuro en reacción es un compromiso, así que encaja la forma de promesa 오겠습니다 (la contraparte formal de 올게요); 올 겁니다 expresa una predicción sobre uno mismo y no carga la promesa de disculpa que la situación exige.',
          'S\'excuser auprès de l\'interlocuteur et s\'engager à un comportement futur en réaction est un engagement, donc la forme de promesse 오겠습니다 (l\'équivalent formel de 올게요) convient ; 올 겁니다 énonce une prédiction sur soi-même et ne porte pas l\'engagement d\'excuse que la situation exige.',
          'Pedir desculpas ao ouvinte e se comprometer com um comportamento futuro em reação é um compromisso, então a forma de promessa 오겠습니다 (a contraparte formal de 올게요) encaixa; 올 겁니다 enuncia uma previsão sobre si mesmo e não carrega o juramento de desculpa que a situação exige.',
          'การขอโทษผู้ฟังและให้คำมั่นเกี่ยวกับพฤติกรรมในอนาคตเพื่อตอบสนองคือการให้คำมั่น จึงเหมาะกับรูปคำสัญญา 오겠습니다 (รูปทางการที่คู่กับ 올게요); ส่วน 올 겁니다 เป็นการทำนายเกี่ยวกับตัวเอง และไม่มีน้ำหนักของคำมั่นในการขอโทษที่สถานการณ์ต้องการ',
          'Meminta maaf kepada pendengar dan berjanji akan berperilaku tertentu di masa depan sebagai reaksi adalah sebuah komitmen, jadi bentuk janji 오겠습니다 (padanan formal dari 올게요) cocok; 올 겁니다 menyatakan prediksi tentang diri sendiri dan tidak membawa ikrar permintaan maaf yang dituntut situasi ini.',
          'Xin lỗi người nghe và cam kết hành vi tương lai để phản ứng lại là một sự cam kết, nên dạng hứa hẹn 오겠습니다 (dạng trang trọng tương ứng của 올게요) là phù hợp; 올 겁니다 nêu một dự đoán về chính mình và không mang lời cam kết kèm xin lỗi mà tình huống đòi hỏi.',
          '聞き手に謝り、その反応として今後の行動を誓うのは約束なので、約束の形 오겠습니다(올게요 の格式体に当たる形)が合う。올 겁니다 は自分についての予測を述べるだけで、状況が求める謝罪の誓いを担わない。',
        ),
      },
    ],
  },
  {
    id: 'eojuda-deurida',
    a: '-아/어 주다',
    b: '-아/어 드리다',
    note: L(
      'Both -아/어 주다 and -아/어 드리다 mean to do a favour for someone; choose by who RECEIVES it. Use plain -아/어 주다 for peers or juniors, and the humble -아/어 드리다 to raise the recipient when they are a senior, an elder, or a customer.',
      'Tanto -아/어 주다 como -아/어 드리다 significan hacerle un favor a alguien; elegí según QUIÉN lo RECIBE. Usá el -아/어 주다 simple para pares o personas menores, y el humilde -아/어 드리다 para elevar a quien recibe el favor cuando es alguien mayor, un superior o un cliente.',
      '-아/어 주다 et -아/어 드리다 signifient tous deux rendre service à quelqu\'un ; choisis selon QUI le REÇOIT. Utilise le -아/어 주다 simple pour des pairs ou des cadets, et le -아/어 드리다 humble pour élever le destinataire quand c\'est un aîné, un supérieur ou un client.',
      'Tanto -아/어 주다 quanto -아/어 드리다 significam fazer um favor para alguém; escolha pela pessoa que o RECEBE. Use o -아/어 주다 simples para colegas ou pessoas mais novas, e o humilde -아/어 드리다 para elevar quem recebe o favor quando for um superior, um mais velho ou um cliente.',
      'ทั้ง -아/어 주다 และ -아/어 드리다 ต่างก็หมายถึงการช่วยทำสิ่งใดให้ใครสักคน เลือกตามว่าใครเป็นผู้รับ ใช้ -아/어 주다 แบบธรรมดากับคนรุ่นเดียวกันหรือคนที่อายุน้อยกว่า และใช้ -아/어 드리다 ที่สุภาพถ่อมตนเพื่อยกย่องผู้รับเมื่อเขาเป็นผู้อาวุโส ผู้ใหญ่ หรือลูกค้า',
      'Baik -아/어 주다 maupun -아/어 드리다 berarti melakukan sesuatu sebagai bantuan untuk seseorang; pilih berdasarkan siapa yang MENERIMANYA. Gunakan -아/어 주다 biasa untuk teman sebaya atau orang yang lebih muda, dan -아/어 드리다 yang merendah untuk meninggikan penerima ketika ia adalah orang yang lebih senior, lebih tua, atau pelanggan.',
      'Cả -아/어 주다 và -아/어 드리다 đều có nghĩa là làm giúp ai đó một việc; hãy chọn dựa trên người NHẬN. Dùng -아/어 주다 thường cho người ngang hàng hoặc người nhỏ tuổi hơn, và dùng -아/어 드리다 khiêm nhường để nâng cao người nhận khi họ là bậc trên, người lớn tuổi hơn, hoặc khách hàng.',
      '-아/어 주다 も -아/어 드리다 も「誰かのために何かをしてあげる」という意味で、どちらを使うかは受け手が誰かで決まる。同等の相手や目下には普通の -아/어 주다 を使い、相手が目上・年長者・お客様の場合は受け手を立てる謙譲の -아/어 드리다 を使う。',
    ),
    items: [
      {
        sentence: '할머니, 제가 무거운 짐을 들어 {}.',
        optionA: '줄게요',
        optionB: '드릴게요',
        answer: 'b',
        trans: L(
          'Grandma, I\'ll carry the heavy bags for you.',
          'Abuela, te llevo las bolsas pesadas.',
          'Mamie, je vais te porter les sacs lourds.',
          'Vovó, vou carregar as sacolas pesadas para a senhora.',
          'คุณยายคะ หนูจะถือถุงหนัก ๆ ให้เองนะคะ',
          'Nenek, biar aku yang membawakan tas-tas berat itu untuk Nenek.',
          'Bà ơi, để cháu xách mấy túi nặng giúp bà nhé.',
          'おばあちゃん、重い荷物は私が持ってあげるね。',
        ),
        why: L(
          'The recipient of the favour is 할머니 (a senior), so the humble 드리다 is required; plain 주다 would fail to raise her.',
          'Quien recibe el favor es 할머니 (una persona mayor), así que se requiere el humilde 드리다; el 주다 simple no lograría elevarla.',
          'Le destinataire du service est 할머니 (une aînée), donc le 드리다 humble est requis ; le 주다 simple ne parviendrait pas à l\'élever.',
          'Quem recebe o favor é 할머니 (uma pessoa mais velha), então o humilde 드리다 é necessário; o 주다 simples não conseguiria elevá-la.',
          'ผู้รับน้ำใจคือ 할머니 (ผู้อาวุโส) จึงต้องใช้ 드리다 ที่ถ่อมตน หากใช้ 주다 แบบธรรมดาจะไม่สามารถยกย่องท่านได้',
          'Penerima bantuan adalah 할머니 (orang yang lebih tua), jadi 드리다 yang merendah diperlukan; 주다 biasa tidak akan meninggikannya.',
          'Người nhận sự giúp đỡ là 할머니 (bậc trên), nên phải dùng 드리다 khiêm nhường; 주다 thường sẽ không nâng cao được bà.',
          '恩恵を受けるのは 할머니（目上の人）なので、謙譲の 드리다 が必要であり、普通の 주다 では相手を立てられない。',
        ),
      },
      {
        sentence: '동생아, 이 책 좀 책상에 올려 {}.',
        optionA: '줄래',
        optionB: '드릴래',
        answer: 'a',
        trans: L(
          'Hey little brother, put this book up on the desk for me, will you?',
          'Che, hermanito, ¿me ponés este libro arriba del escritorio?',
          'Hé, petit frère, tu me poses ce livre sur le bureau, d\'accord ?',
          'Ei, irmãozinho, coloca esse livro em cima da escrivaninha pra mim, vai?',
          'นี่ น้องชาย ช่วยพี่วางหนังสือเล่มนี้ขึ้นบนโต๊ะหน่อยสิ',
          'Hei, adik, tolong taruh buku ini di atas meja untukku, ya?',
          'Này em trai, đặt giúp anh quyển sách này lên bàn nhé?',
          'おい、弟よ、この本を机の上に置いてくれよ。',
        ),
        why: L(
          'The recipient is a younger sibling (an inferior), so plain 주다 is natural; humble 드리다 would absurdly elevate a younger brother.',
          'Quien recibe es un hermano menor (un inferior), así que el 주다 simple es natural; el humilde 드리다 elevaría de manera absurda a un hermano menor.',
          'Le destinataire est un frère cadet (un inférieur), donc le 주다 simple est naturel ; le 드리다 humble élèverait absurdement un petit frère.',
          'Quem recebe é um irmão mais novo (um inferior), então o 주다 simples é natural; o humilde 드리다 elevaria de forma absurda um irmão mais novo.',
          'ผู้รับคือน้องชาย (ผู้ที่อยู่ต่ำกว่า) จึงใช้ 주다 แบบธรรมดาได้อย่างเป็นธรรมชาติ หากใช้ 드리다 ที่ถ่อมตนจะกลายเป็นการยกย่องน้องชายอย่างไร้เหตุผล',
          'Penerimanya adalah adik (orang yang lebih rendah), jadi 주다 biasa terdengar wajar; 드리다 yang merendah akan secara janggal meninggikan seorang adik.',
          'Người nhận là em trai (người dưới), nên 주다 thường là tự nhiên; 드리다 khiêm nhường sẽ nâng cao một cách vô lý một đứa em.',
          '受け手は弟（目下）なので普通の 주다 が自然であり、謙譲の 드리다 を使うと弟を不自然に持ち上げてしまう。',
        ),
      },
      {
        sentence: '손님, 영수증은 봉투에 넣어 {}.',
        optionA: '줄까요',
        optionB: '드릴까요',
        answer: 'b',
        trans: L(
          'Sir/Ma\'am, shall I put the receipt in the bag for you?',
          'Señor/Señora, ¿le pongo el recibo en la bolsa?',
          'Monsieur/Madame, je mets le reçu dans le sac pour vous ?',
          'Senhor/Senhora, coloco o recibo na sacola para o senhor/a senhora?',
          'คุณลูกค้าคะ จะให้ใส่ใบเสร็จลงในถุงให้ไหมคะ',
          'Bapak/Ibu, apakah saya masukkan struknya ke dalam tas?',
          'Thưa quý khách, em bỏ hóa đơn vào túi cho quý khách nhé?',
          'お客様、レシートを袋にお入れしましょうか。',
        ),
        why: L(
          'Serving a customer (손님) demands the humble 드리다 to honour the recipient; plain 주다 would be rude in this service context.',
          'Atender a un cliente (손님) exige el humilde 드리다 para honrar a quien recibe; el 주다 simple sería descortés en este contexto de servicio.',
          'Servir un client (손님) exige le 드리다 humble pour honorer le destinataire ; le 주다 simple serait impoli dans ce contexte de service.',
          'Atender um cliente (손님) exige o humilde 드리다 para honrar quem recebe; o 주다 simples seria rude nesse contexto de atendimento.',
          'การให้บริการลูกค้า (손님) ต้องใช้ 드리다 ที่ถ่อมตนเพื่อให้เกียรติผู้รับ หากใช้ 주다 แบบธรรมดาจะดูไม่สุภาพในบริบทการบริการเช่นนี้',
          'Melayani pelanggan (손님) menuntut 드리다 yang merendah untuk menghormati penerima; 주다 biasa akan terdengar tidak sopan dalam konteks layanan ini.',
          'Phục vụ khách hàng (손님) đòi hỏi 드리다 khiêm nhường để tôn trọng người nhận; 주다 thường sẽ thất lễ trong ngữ cảnh phục vụ này.',
          'お客様（손님）に対応する際は受け手を敬う謙譲の 드리다 が必要であり、この接客の場面で普通の 주다 を使うと失礼になる。',
        ),
      },
    ],
  },
  {
    id: 'geotgatda-moyangida',
    a: '-(으)ㄴ/는 것 같다',
    b: '-(으)ㄴ/는 모양이다',
    note: L(
      'Both render as "it seems," but they are NOT symmetric. -(으)ㄴ/는 것 같다 is the broad default: a soft personal guess that can describe the speaker\'s OWN body, feelings, opinion, or intention, and also others. -(으)ㄴ/는 모양이다 is a detached inference about someone/something ELSE drawn from outside evidence and CANNOT describe the speaker\'s own inner state, feeling, opinion, or will. So the only watertight single-answer cases force 것 같다 (when the subject is the speaker\'s own state). For external third-party evidence both forms are usually acceptable, so such sentences are avoided here unless one option is independently unnatural.',
      'Las dos se traducen como "parece que", pero NO son simétricas. -(으)ㄴ/는 것 같다 es la opción amplia por defecto: una suposición personal suave que puede describir el PROPIO cuerpo, sentimientos, opinión o intención del hablante, y también los de otros. -(으)ㄴ/는 모양이다 es una inferencia distanciada sobre OTRA persona/cosa, sacada a partir de evidencia externa, y NO puede describir el estado interno, sentimiento, opinión o voluntad propios del hablante. Así que los únicos casos de respuesta única a prueba de balas obligan a usar 것 같다 (cuando el sujeto es el propio estado del hablante). Para evidencia externa de un tercero, ambas formas suelen ser aceptables, así que esas oraciones se evitan acá salvo que una opción sea poco natural por sí sola.',
      'Les deux se traduisent par « on dirait que / il semble que », mais elles ne sont PAS symétriques. -(으)ㄴ/는 것 같다 est l\'option large par défaut : une supposition personnelle douce qui peut décrire le PROPRE corps, les sentiments, l\'opinion ou l\'intention du locuteur, et aussi ceux des autres. -(으)ㄴ/는 모양이다 est une inférence détachée à propos de quelqu\'un/quelque chose d\'AUTRE, tirée d\'une preuve extérieure, et NE PEUT PAS décrire l\'état intérieur, le sentiment, l\'opinion ou la volonté propres du locuteur. Donc les seuls cas à réponse unique vraiment étanches imposent 것 같다 (quand le sujet est le propre état du locuteur). Pour une preuve externe concernant un tiers, les deux formes sont généralement acceptables, donc on évite ici de telles phrases sauf si une des options est en elle-même peu naturelle.',
      'As duas se traduzem como "parece que", mas NÃO são simétricas. -(으)ㄴ/는 것 같다 é a opção ampla padrão: um palpite pessoal suave que pode descrever o PRÓPRIO corpo, sentimentos, opinião ou intenção do falante, e também os dos outros. -(으)ㄴ/는 모양이다 é uma inferência distanciada sobre OUTRA pessoa/coisa, tirada de evidência externa, e NÃO pode descrever o estado interno, sentimento, opinião ou vontade do próprio falante. Então os únicos casos de resposta única à prova de falhas forçam 것 같다 (quando o sujeito é o próprio estado do falante). Para evidência externa de um terceiro, ambas as formas costumam ser aceitáveis, então tais frases são evitadas aqui a menos que uma das opções seja não natural por si só.',
      'ทั้งสองแปลว่า "ดูเหมือนว่า" แต่ไม่ได้ใช้แทนกันได้เสมอ -(으)ㄴ/는 것 같다 เป็นตัวเลือกพื้นฐานที่ใช้ได้กว้าง: เป็นการคาดเดาส่วนตัวอย่างนุ่มนวลที่ใช้บรรยายร่างกาย ความรู้สึก ความคิดเห็น หรือความตั้งใจของตัวผู้พูดเองได้ และของคนอื่นได้ด้วย ส่วน -(으)ㄴ/는 모양이다 เป็นการอนุมานแบบวางตัวห่างเกี่ยวกับคน/สิ่งอื่น โดยอาศัยหลักฐานจากภายนอก และไม่สามารถใช้บรรยายสภาวะภายใน ความรู้สึก ความคิดเห็น หรือความตั้งใจของตัวผู้พูดเองได้ ดังนั้นกรณีที่มีคำตอบเดียวแน่นอนจึงบังคับให้ใช้ 것 같다 (เมื่อประธานคือสภาวะของตัวผู้พูดเอง) สำหรับหลักฐานภายนอกเกี่ยวกับบุคคลที่สาม โดยทั่วไปทั้งสองรูปมักใช้ได้ จึงหลีกเลี่ยงประโยคแบบนั้นในที่นี้ เว้นแต่ตัวเลือกหนึ่งจะไม่เป็นธรรมชาติในตัวเอง',
      'Keduanya sama-sama berarti "sepertinya", tetapi keduanya TIDAK simetris. -(으)ㄴ/는 것 같다 adalah pilihan default yang luas: tebakan pribadi yang halus yang bisa menggambarkan tubuh, perasaan, pendapat, atau niat penutur SENDIRI, dan juga orang lain. -(으)ㄴ/는 모양이다 adalah kesimpulan yang berjarak tentang orang/hal LAIN yang ditarik dari bukti luar dan TIDAK BISA menggambarkan keadaan batin, perasaan, pendapat, atau kehendak penutur sendiri. Jadi satu-satunya kasus berjawaban tunggal yang benar-benar pasti memaksa penggunaan 것 같다 (ketika subjeknya adalah keadaan penutur sendiri). Untuk bukti eksternal dari pihak ketiga, kedua bentuk biasanya dapat diterima, sehingga kalimat semacam itu dihindari di sini kecuali salah satu pilihan memang tidak alami dengan sendirinya.',
      'Cả hai đều dịch là "có vẻ như", nhưng chúng KHÔNG đối xứng. -(으)ㄴ/는 것 같다 là lựa chọn mặc định rộng rãi: một phỏng đoán cá nhân nhẹ nhàng có thể mô tả chính cơ thể, cảm xúc, ý kiến hay ý định của CHÍNH người nói, và cả của người khác. -(으)ㄴ/는 모양이다 là một suy luận tách biệt về một người/vật KHÁC rút ra từ bằng chứng bên ngoài và KHÔNG THỂ mô tả trạng thái nội tâm, cảm xúc, ý kiến hay ý chí của chính người nói. Vì vậy, những trường hợp chỉ có một đáp án chắc chắn duy nhất buộc phải dùng 것 같다 (khi chủ ngữ là trạng thái của chính người nói). Đối với bằng chứng bên ngoài về một bên thứ ba, cả hai dạng thường đều chấp nhận được, nên những câu như vậy được tránh ở đây trừ khi một lựa chọn tự nó đã không tự nhiên.',
      'どちらも「〜のようだ／〜らしい」と訳せますが、対称的ではありません。-(으)ㄴ/는 것 같다 は幅広く使える基本形で、話し手自身の体・感情・意見・意図を表すこともでき、他人についても使える、やわらかい個人的な推測です。-(으)ㄴ/는 모양이다 は、外的な根拠から導く、他者・他の物事についての距離を置いた推論であり、話し手自身の内面・感情・意見・意志を表すことはできません。したがって、答えが一つに確定する確実なケースは、主語が話し手自身の状態であるときに 것 같다 を強制する場合だけです。第三者についての外的な根拠の場合は通常どちらの形も使えるため、一方の選択肢がそれ自体不自然でない限り、そうした文はここでは避けています。',
    ),
    items: [
      {
        sentence: '저는 요즘 감기에 걸린 {}. 자꾸 기침이 나요.',
        optionA: '걸린 것 같아요',
        optionB: '걸린 모양이에요',
        answer: 'a',
        trans: L(
          'I think I\'ve caught a cold these days. I keep coughing.',
          'Creo que me resfrié estos días. No paro de toser.',
          'Je crois que j\'ai attrapé un rhume ces jours-ci. Je n\'arrête pas de tousser.',
          'Acho que peguei um resfriado esses dias. Não paro de tossir.',
          'ช่วงนี้ฉันคิดว่าเป็นหวัดแล้วล่ะ ไอไม่หยุดเลย',
          'Sepertinya akhir-akhir ini aku kena pilek. Aku batuk terus.',
          'Mình nghĩ dạo này mình bị cảm rồi. Cứ ho mãi.',
          '最近、風邪をひいたみたいです。ずっと咳が出るんです。',
        ),
        why: L(
          'The speaker is guessing about their OWN body. 모양이다 cannot describe the speaker\'s own physical condition, so \'걸린 모양이에요\' about oneself is unnatural; only 것 같다 works.',
          'El hablante está suponiendo sobre su PROPIO cuerpo. 모양이다 no puede describir el propio estado físico del hablante, así que \'걸린 모양이에요\' referido a uno mismo es poco natural; solo funciona 것 같다.',
          'Le locuteur fait une supposition sur son PROPRE corps. 모양이다 ne peut pas décrire l\'état physique propre du locuteur, donc \'걸린 모양이에요\' à propos de soi-même est peu naturel ; seul 것 같다 convient.',
          'O falante está supondo sobre o PRÓPRIO corpo. 모양이다 não pode descrever o próprio estado físico do falante, então \'걸린 모양이에요\' referindo-se a si mesmo é não natural; só 것 같다 funciona.',
          'ผู้พูดกำลังคาดเดาเกี่ยวกับร่างกายของตัวเอง 모양이다 ใช้บรรยายสภาพร่างกายของตัวผู้พูดเองไม่ได้ ดังนั้น \'걸린 모양이에요\' เมื่อพูดถึงตัวเองจึงไม่เป็นธรรมชาติ มีแต่ 것 같다 ที่ใช้ได้',
          'Penutur sedang menebak tentang tubuhnya SENDIRI. 모양이다 tidak bisa menggambarkan kondisi fisik penutur sendiri, jadi \'걸린 모양이에요\' tentang diri sendiri terdengar tidak alami; hanya 것 같다 yang cocok.',
          'Người nói đang phỏng đoán về chính cơ thể MÌNH. 모양이다 không thể mô tả tình trạng thể chất của chính người nói, nên \'걸린 모양이에요\' nói về bản thân là không tự nhiên; chỉ có 것 같다 mới dùng được.',
          '話し手は自分自身の体について推測しています。모양이다 は話し手自身の身体的な状態を表せないため、自分について \'걸린 모양이에요\' と言うのは不自然で、것 같다 だけが使えます。',
        ),
      },
      {
        sentence: '제 생각에는 이 식당이 저 식당보다 더 {}.',
        optionA: '맛있는 것 같아요',
        optionB: '맛있는 모양이에요',
        answer: 'a',
        trans: L(
          'In my opinion, this restaurant seems tastier than that one.',
          'En mi opinión, este restaurante parece más rico que aquel.',
          'À mon avis, ce restaurant a l\'air plus savoureux que celui-là.',
          'Na minha opinião, este restaurante parece mais gostoso do que aquele.',
          'ในความคิดของฉัน ร้านนี้ดูเหมือนจะอร่อยกว่าร้านนั้น',
          'Menurutku, restoran ini sepertinya lebih enak daripada yang itu.',
          'Theo mình thấy, quán này có vẻ ngon hơn quán kia.',
          '私の考えでは、この店はあの店より美味しいようです。',
        ),
        why: L(
          '\'제 생각에는\' makes this the speaker\'s own judgment/opinion. 모양이다 reports an inference about an external situation and cannot voice the speaker\'s own opinion, so only 것 같다 is natural here.',
          '\'제 생각에는\' convierte esto en el propio juicio/opinión del hablante. 모양이다 reporta una inferencia sobre una situación externa y no puede expresar la propia opinión del hablante, así que acá solo 것 같다 es natural.',
          '\'제 생각에는\' fait de ceci le propre jugement/opinion du locuteur. 모양이다 rapporte une inférence sur une situation externe et ne peut pas exprimer l\'opinion propre du locuteur, donc ici seul 것 같다 est naturel.',
          '\'제 생각에는\' faz disto o próprio juízo/opinião do falante. 모양이다 relata uma inferência sobre uma situação externa e não pode expressar a opinião do próprio falante, então aqui só 것 같다 é natural.',
          '\'제 생각에는\' ทำให้ประโยคนี้เป็นการตัดสิน/ความคิดเห็นของตัวผู้พูดเอง 모양이다 ใช้รายงานการอนุมานเกี่ยวกับสถานการณ์ภายนอก และไม่สามารถใช้แสดงความคิดเห็นของตัวผู้พูดเองได้ ดังนั้นในที่นี้มีแต่ 것 같다 ที่เป็นธรรมชาติ',
          '\'제 생각에는\' menjadikan ini penilaian/pendapat penutur sendiri. 모양이다 melaporkan kesimpulan tentang situasi eksternal dan tidak bisa menyuarakan pendapat penutur sendiri, jadi di sini hanya 것 같다 yang alami.',
          '\'제 생각에는\' khiến đây trở thành nhận định/ý kiến của chính người nói. 모양이다 tường thuật một suy luận về tình huống bên ngoài và không thể nói lên ý kiến của chính người nói, nên ở đây chỉ có 것 같다 là tự nhiên.',
          '\'제 생각에는\' によって、これは話し手自身の判断・意見になります。모양이다 は外的な状況についての推論を述べるもので、話し手自身の意見を表すことはできないため、ここでは 것 같다 だけが自然です。',
        ),
      },
      {
        sentence: '동생이 아침부터 아무 말도 안 하고 방에만 있어요. 무슨 일이 {}.',
        optionA: '있는 것 같아요',
        optionB: '있는 모양이에요',
        answer: 'b',
        trans: L(
          'My younger sibling has been silent and stuck in their room since morning. Something seems to be going on.',
          'Mi hermano menor está callado y encerrado en su cuarto desde la mañana. Parece que pasa algo.',
          'Mon petit frère (ou ma petite sœur) reste silencieux et enfermé dans sa chambre depuis ce matin. On dirait qu\'il se passe quelque chose.',
          'Meu irmão mais novo está calado e trancado no quarto desde de manhã. Parece que está acontecendo alguma coisa.',
          'น้องของฉันเงียบและเก็บตัวอยู่ในห้องตั้งแต่เช้า ดูเหมือนว่าจะมีอะไรเกิดขึ้น',
          'Adikku diam saja dan mengurung diri di kamar sejak pagi. Sepertinya ada sesuatu yang sedang terjadi.',
          'Em mình im lặng và ở lì trong phòng từ sáng đến giờ. Có vẻ như đang có chuyện gì đó.',
          '弟（妹）は朝からずっと黙って部屋にこもっています。何かあったようです。',
        ),
        why: L(
          'The speaker infers a third party\'s hidden situation purely from observed outside behavior with no personal involvement — the detached, evidence-based deduction that 모양이다 is built for. 것 같다 here would lean toward the speaker\'s own vague feeling, whereas the sentence frames it as an objective deduction about the sibling, making 모양이다 the fitting choice.',
          'El hablante infiere la situación oculta de un tercero puramente a partir de un comportamiento externo observado, sin implicación personal: la deducción distanciada y basada en evidencia para la que está hecho 모양이다. Acá 것 같다 tendería hacia la propia sensación vaga del hablante, mientras que la oración lo plantea como una deducción objetiva sobre el hermano, lo que hace de 모양이다 la opción adecuada.',
          'Le locuteur déduit la situation cachée d\'un tiers uniquement à partir d\'un comportement extérieur observé, sans implication personnelle : la déduction détachée et fondée sur des preuves pour laquelle 모양이다 est fait. Ici 것 같다 pencherait vers le vague ressenti propre du locuteur, alors que la phrase la présente comme une déduction objective au sujet du frère/de la sœur, ce qui fait de 모양이다 le choix approprié.',
          'O falante infere a situação oculta de um terceiro puramente a partir de um comportamento externo observado, sem envolvimento pessoal: a dedução distanciada e baseada em evidências para a qual 모양이다 foi feito. Aqui 것 같다 tenderia para a própria sensação vaga do falante, enquanto a frase a enquadra como uma dedução objetiva sobre o irmão, tornando 모양이다 a escolha adequada.',
          'ผู้พูดอนุมานสถานการณ์ที่ซ่อนอยู่ของบุคคลที่สามล้วนๆ จากพฤติกรรมภายนอกที่สังเกตเห็น โดยไม่มีส่วนเกี่ยวข้องส่วนตัว ซึ่งเป็นการอนุมานแบบวางตัวห่างและอิงหลักฐานที่ 모양이다 ถูกสร้างมาเพื่อสิ่งนี้ ในที่นี้ 것 같다 จะออกไปทางความรู้สึกคลุมเครือของตัวผู้พูดเอง ขณะที่ประโยควางกรอบให้เป็นการอนุมานอย่างเป็นกลางเกี่ยวกับน้อง ทำให้ 모양이다 เป็นตัวเลือกที่เหมาะสม',
          'Penutur menyimpulkan situasi tersembunyi pihak ketiga murni dari perilaku luar yang teramati tanpa keterlibatan pribadi — deduksi yang berjarak dan berbasis bukti yang memang menjadi tujuan 모양이다. Di sini 것 같다 akan cenderung ke perasaan samar penutur sendiri, sedangkan kalimat ini membingkainya sebagai deduksi objektif tentang sang adik, sehingga 모양이다 menjadi pilihan yang tepat.',
          'Người nói suy ra tình huống ẩn giấu của một bên thứ ba hoàn toàn từ hành vi bên ngoài quan sát được, không có sự dính líu cá nhân — đúng kiểu suy luận tách biệt, dựa trên bằng chứng mà 모양이다 được dùng cho. Ở đây 것 같다 sẽ nghiêng về cảm giác mơ hồ của chính người nói, trong khi câu này đóng khung nó như một suy luận khách quan về đứa em, khiến 모양이다 là lựa chọn phù hợp.',
          '話し手は、個人的な関与なしに、観察した外的な行動だけから第三者の隠れた状況を推測しています。これはまさに 모양이다 が想定する、距離を置いた根拠に基づく推論です。ここで 것 같다 を使うと話し手自身の漠然とした感覚寄りになりますが、この文は弟（妹）についての客観的な推論として組み立てられているため、모양이다 が適切な選択になります。',
        ),
      },
    ],
  },
  {
    id: 'myeondoeda-aeoyahada',
    a: '-(으)면 되다',
    b: '-아/어야 하다 / 되다',
    note: L(
      'A = -(으)면 되다 means "it\'s enough to / all you have to do is" — it frames an action as a sufficient step that solves the situation (reassuring). B = -아/어야 하다/되다 means "must / have to" — it frames the action as a requirement or obligation. Use A to tell someone the simple sufficient thing to do; use B to stress that something is necessary or mandatory. Collocational cues decide: 걱정 마세요·괜찮아요·그냥 ~만 pull toward A, while 반드시 (and similar strong necessity adverbs) demand B and block -(으)면 되다.',
      'A = -(으)면 되다 significa "basta con / lo único que tenés que hacer es": enmarca una acción como un paso suficiente que resuelve la situación (es tranquilizador). B = -아/어야 하다/되다 significa "deber / tener que": enmarca la acción como un requisito u obligación. Usá A para decirle a alguien la cosa simple y suficiente que tiene que hacer; usá B para recalcar que algo es necesario u obligatorio. Las pistas de colocación deciden: 걱정 마세요·괜찮아요·그냥 ~만 empujan hacia A, mientras que 반드시 (y adverbios fuertes de necesidad similares) exigen B y bloquean -(으)면 되다.',
      'A = -(으)면 되다 signifie "il suffit de / tout ce que tu as à faire, c\'est" : il présente une action comme une étape suffisante qui résout la situation (rassurant). B = -아/어야 하다/되다 signifie "devoir / être obligé de" : il présente l\'action comme une exigence ou une obligation. Utilise A pour dire à quelqu\'un la chose simple et suffisante à faire ; utilise B pour souligner que quelque chose est nécessaire ou obligatoire. Les indices de collocation décident : 걱정 마세요·괜찮아요·그냥 ~만 tirent vers A, tandis que 반드시 (et d\'autres adverbes forts de nécessité) exigent B et bloquent -(으)면 되다.',
      'A = -(으)면 되다 significa "basta / tudo o que você precisa fazer é": enquadra uma ação como um passo suficiente que resolve a situação (tranquilizador). B = -아/어야 하다/되다 significa "dever / ter que": enquadra a ação como um requisito ou obrigação. Use A para dizer a alguém a coisa simples e suficiente a fazer; use B para enfatizar que algo é necessário ou obrigatório. As pistas de colocação decidem: 걱정 마세요·괜찮아요·그냥 ~만 puxam para A, enquanto 반드시 (e advérbios fortes de necessidade semelhantes) exigem B e bloqueiam -(으)면 되다.',
      'A = -(으)면 되다 หมายถึง "แค่...ก็พอ / สิ่งเดียวที่ต้องทำคือ" — มันวางการกระทำให้เป็นขั้นตอนที่เพียงพอซึ่งแก้สถานการณ์ได้ (ให้ความอุ่นใจ) B = -아/어야 하다/되다 หมายถึง "ต้อง / จำเป็นต้อง" — มันวางการกระทำให้เป็นข้อกำหนดหรือพันธะ ใช้ A เพื่อบอกใครบางคนถึงสิ่งง่าย ๆ ที่ทำแล้วเพียงพอ ใช้ B เพื่อย้ำว่าบางอย่างจำเป็นหรือบังคับ คำที่อยู่ร่วมกันเป็นตัวตัดสิน: 걱정 마세요·괜찮아요·그냥 ~만 ดึงไปทาง A ขณะที่ 반드시 (และคำกริยาวิเศษณ์บอกความจำเป็นที่หนักแน่นคล้ายกัน) เรียกร้อง B และกีดกัน -(으)면 되다.',
      'A = -(으)면 되다 berarti "cukup dengan / yang perlu kamu lakukan hanyalah" — ia membingkai suatu tindakan sebagai langkah yang cukup untuk menyelesaikan situasi (menenangkan). B = -아/어야 하다/되다 berarti "harus / wajib" — ia membingkai tindakan sebagai syarat atau kewajiban. Gunakan A untuk memberi tahu seseorang hal sederhana yang cukup dilakukan; gunakan B untuk menekankan bahwa sesuatu itu perlu atau wajib. Petunjuk kolokasi menentukan: 걱정 마세요·괜찮아요·그냥 ~만 menarik ke arah A, sementara 반드시 (dan kata keterangan keharusan kuat sejenis) menuntut B dan menghalangi -(으)면 되다.',
      'A = -(으)면 되다 nghĩa là "chỉ cần / việc bạn phải làm chỉ là" — nó khung hành động thành một bước đủ để giải quyết tình huống (mang tính trấn an). B = -아/어야 하다/되다 nghĩa là "phải / bắt buộc" — nó khung hành động thành một yêu cầu hay nghĩa vụ. Dùng A để nói cho ai đó điều đơn giản chỉ cần làm là đủ; dùng B để nhấn mạnh rằng điều gì đó là cần thiết hoặc bắt buộc. Các gợi ý đi kèm sẽ quyết định: 걱정 마세요·괜찮아요·그냥 ~만 kéo về phía A, trong khi 반드시 (và các trạng từ chỉ sự cần thiết mạnh tương tự) đòi hỏi B và loại trừ -(으)면 되다.',
      'A = -(으)면 되다 は「~すればいい/しさえすればいい」という意味で、ある行動を状況を解決する十分な手段として枠づける（安心感を与える）。B = -아/어야 하다/되다 は「~しなければならない」という意味で、その行動を要件や義務として枠づける。簡単で十分なやるべきことを相手に伝えるときは A を使い、何かが必要・必須であることを強調するときは B を使う。共起の手がかりが決め手になる：걱정 마세요・괜찮아요・그냥 ~만 は A の方へ引き寄せ、一方 반드시（および同様の強い必要性の副詞）は B を要求し、-(으)면 되다 を排除する。',
    ),
    items: [
      {
        sentence: '걱정 마세요. 이 버튼만 {} 모든 게 자동으로 저장돼요.',
        optionA: '누르면 돼요',
        optionB: '눌러야 돼요',
        answer: 'a',
        trans: L(
          'Don\'t worry. You just have to press this button and everything saves automatically.',
          'No te preocupes. Solo tenés que presionar este botón y todo se guarda automáticamente.',
          'Ne t\'inquiète pas. Tu n\'as qu\'à appuyer sur ce bouton et tout s\'enregistre automatiquement.',
          'Não se preocupe. Você só precisa apertar este botão e tudo é salvo automaticamente.',
          'ไม่ต้องกังวล แค่กดปุ่มนี้ก็พอ แล้วทุกอย่างจะถูกบันทึกโดยอัตโนมัติ',
          'Jangan khawatir. Kamu cukup menekan tombol ini dan semuanya tersimpan otomatis.',
          'Đừng lo. Bạn chỉ cần nhấn nút này là mọi thứ tự động được lưu.',
          '心配しないで。このボタンを押すだけで、すべて自動的に保存されます。',
        ),
        why: L(
          'The reassuring \'걱정 마세요\' + \'~만\' frames pressing as the sufficient step, so -(으)면 되다 fits; -아/어야 되다 would clash by stressing obligation instead of reassurance.',
          'El tranquilizador \'걱정 마세요\' + \'~만\' enmarca presionar como el paso suficiente, así que -(으)면 되다 encaja; -아/어야 되다 chocaría al recalcar obligación en lugar de tranquilidad.',
          'Le rassurant \'걱정 마세요\' + \'~만\' présente le fait d\'appuyer comme l\'étape suffisante, donc -(으)면 되다 convient ; -아/어야 되다 jurerait en soulignant l\'obligation au lieu du réconfort.',
          'O tranquilizador \'걱정 마세요\' + \'~만\' enquadra apertar como o passo suficiente, então -(으)면 되다 se encaixa; -아/어야 되다 destoaria ao enfatizar obrigação em vez de tranquilidade.',
          'คำปลอบใจ \'걱정 마세요\' + \'~만\' วางการกดให้เป็นขั้นตอนที่เพียงพอ ดังนั้น -(으)면 되다 จึงเข้ากัน ส่วน -아/어야 되다 จะขัดกันเพราะไปย้ำพันธะแทนการให้ความอุ่นใจ',
          'Frasa menenangkan \'걱정 마세요\' + \'~만\' membingkai menekan sebagai langkah yang cukup, jadi -(으)면 되다 cocok; -아/어야 되다 akan bertabrakan karena menekankan kewajiban alih-alih ketenangan.',
          'Cụm trấn an \'걱정 마세요\' + \'~만\' khung việc nhấn thành bước đủ, nên -(으)면 되다 phù hợp; -아/어야 되다 sẽ chỏi vì nhấn mạnh nghĩa vụ thay vì sự trấn an.',
          '安心させる \'걱정 마세요\' + \'~만\' が、押すことを十分な手段として枠づけるので -(으)면 되다 が合う。-아/어야 되다 だと安心ではなく義務を強調してしまい衝突する。',
        ),
      },
      {
        sentence: '비자를 받으려면 반드시 서류를 모두 {}.',
        optionA: '내면 돼요',
        optionB: '내야 돼요',
        answer: 'b',
        trans: L(
          'To get the visa, you absolutely must submit all the documents.',
          'Para obtener la visa, sí o sí tenés que presentar todos los documentos.',
          'Pour obtenir le visa, tu dois absolument soumettre tous les documents.',
          'Para conseguir o visto, você obrigatoriamente precisa entregar todos os documentos.',
          'เพื่อให้ได้วีซ่า คุณต้องยื่นเอกสารทั้งหมดอย่างแน่นอน',
          'Untuk mendapatkan visa, kamu mutlak harus menyerahkan semua dokumen.',
          'Để được cấp visa, bạn nhất định phải nộp tất cả giấy tờ.',
          'ビザを取得するには、必ずすべての書類を提出しなければなりません。',
        ),
        why: L(
          '\'반드시(absolutely)\' demands the obligation form -아/어야 되다 and does not collocate with -(으)면 되다, which would wrongly downplay it as a mere sufficient option.',
          '\'반드시(sí o sí)\' exige la forma de obligación -아/어야 되다 y no se coloca con -(으)면 되다, que lo restaría importancia tratándolo erróneamente como una mera opción suficiente.',
          '\'반드시(absolument)\' exige la forme d\'obligation -아/어야 되다 et ne se combine pas avec -(으)면 되다, qui le minimiserait à tort comme une simple option suffisante.',
          '\'반드시(obrigatoriamente)\' exige a forma de obrigação -아/어야 되다 e não combina com -(으)면 되다, que erroneamente o reduziria a uma mera opção suficiente.',
          '\'반드시(อย่างแน่นอน)\' เรียกร้องรูปบอกพันธะ -아/어야 되다 และไม่อยู่ร่วมกับ -(으)면 되다 ซึ่งจะลดทอนมันลงอย่างผิด ๆ ให้กลายเป็นเพียงทางเลือกที่เพียงพอ',
          '\'반드시(mutlak)\' menuntut bentuk kewajiban -아/어야 되다 dan tidak berkolokasi dengan -(으)면 되다, yang akan keliru meremehkannya sebagai sekadar opsi yang cukup.',
          '\'반드시(nhất định)\' đòi hỏi dạng nghĩa vụ -아/어야 되다 và không đi kèm với -(으)면 되다, vì hình thức đó sẽ sai lầm hạ thấp nó thành một lựa chọn chỉ cần là đủ.',
          '\'반드시(必ず)\' は義務形 -아/어야 되다 を要求し、-(으)면 되다 とは共起しない。-(으)면 되다 だと単なる十分な選択肢として誤って軽く扱ってしまう。',
        ),
      },
      {
        sentence: '표가 없어도 괜찮아요. 그냥 입구에서 이름만 {}.',
        optionA: '말하면 돼요',
        optionB: '말해야 돼요',
        answer: 'a',
        trans: L(
          'It\'s fine even without a ticket. You just have to say your name at the entrance.',
          'Está bien aunque no tengas entrada. Solo tenés que decir tu nombre en la entrada.',
          'Ce n\'est pas grave même sans billet. Tu n\'as qu\'à dire ton nom à l\'entrée.',
          'Tudo bem mesmo sem ingresso. Você só precisa dizer seu nome na entrada.',
          'ไม่มีตั๋วก็ไม่เป็นไร แค่บอกชื่อของคุณที่ทางเข้าก็พอ',
          'Tidak apa-apa walaupun tanpa tiket. Kamu cukup menyebutkan namamu di pintu masuk.',
          'Không có vé cũng không sao. Bạn chỉ cần nói tên mình ở lối vào là được.',
          'チケットがなくても大丈夫です。入口で名前を言うだけでいいです。',
        ),
        why: L(
          '\'괜찮아요\' + \'그냥 ~만\' presents saying your name as the easy sufficient condition, fitting -(으)면 되다; -아/어야 되다 would turn a reassurance into an unwanted obligation.',
          '\'괜찮아요\' + \'그냥 ~만\' presenta decir tu nombre como la condición fácil y suficiente, encajando con -(으)면 되다; -아/어야 되다 convertiría una tranquilidad en una obligación no deseada.',
          '\'괜찮아요\' + \'그냥 ~만\' présente le fait de dire ton nom comme la condition facile et suffisante, ce qui convient à -(으)면 되다 ; -아/어야 되다 transformerait un réconfort en une obligation indésirable.',
          '\'괜찮아요\' + \'그냥 ~만\' apresenta dizer seu nome como a condição fácil e suficiente, encaixando com -(으)면 되다; -아/어야 되다 transformaria uma tranquilização em uma obrigação indesejada.',
          '\'괜찮아요\' + \'그냥 ~만\' นำเสนอการบอกชื่อให้เป็นเงื่อนไขที่ง่ายและเพียงพอ จึงเข้ากับ -(으)면 되다 ส่วน -아/어야 되다 จะเปลี่ยนการปลอบใจให้กลายเป็นพันธะที่ไม่พึงประสงค์',
          '\'괜찮아요\' + \'그냥 ~만\' menyajikan menyebutkan nama sebagai syarat yang mudah dan cukup, cocok dengan -(으)면 되다; -아/어야 되다 akan mengubah penenangan menjadi kewajiban yang tidak diinginkan.',
          '\'괜찮아요\' + \'그냥 ~만\' trình bày việc nói tên như điều kiện dễ dàng và đủ, hợp với -(으)면 되다; -아/어야 되다 sẽ biến một lời trấn an thành nghĩa vụ không mong muốn.',
          '\'괜찮아요\' + \'그냥 ~만\' が、名前を言うことを簡単で十分な条件として提示するので -(으)면 되다 に合う。-아/어야 되다 だと安心の言葉を望まない義務に変えてしまう。',
        ),
      },
    ],
  },
  {
    id: 'geona-ina',
    a: '-거나',
    b: '(이)나',
    note: L(
      'Both mean "or," but -거나 connects verbs, adjectives, or whole clauses (보거나 읽거나 = "watch or read"), while (이)나 connects nouns (커피나 차 = "coffee or tea"). Pick (이)나 when the alternatives are nouns, and -거나 when they are verbs/adjectives/clauses.',
      'Ambos significan "o", pero -거나 conecta verbos, adjetivos o cláusulas enteras (보거나 읽거나 = "ver o leer"), mientras que (이)나 conecta sustantivos (커피나 차 = "café o té"). Usá (이)나 cuando las alternativas son sustantivos, y -거나 cuando son verbos/adjetivos/cláusulas.',
      'Les deux signifient « ou », mais -거나 relie des verbes, des adjectifs ou des propositions entières (보거나 읽거나 = « regarder ou lire »), alors que (이)나 relie des noms (커피나 차 = « café ou thé »). Choisis (이)나 quand les alternatives sont des noms, et -거나 quand ce sont des verbes/adjectifs/propositions.',
      'Ambos significam "ou", mas -거나 conecta verbos, adjetivos ou orações inteiras (보거나 읽거나 = "assistir ou ler"), enquanto (이)나 conecta substantivos (커피나 차 = "café ou chá"). Escolha (이)나 quando as alternativas forem substantivos, e -거나 quando forem verbos/adjetivos/orações.',
      'ทั้งสองแปลว่า "หรือ" แต่ -거나 ใช้เชื่อมคำกริยา คำคุณศัพท์ หรือทั้งประโยค (보거나 읽거나 = "ดูหรืออ่าน") ในขณะที่ (이)나 ใช้เชื่อมคำนาม (커피나 차 = "กาแฟหรือชา") เลือกใช้ (이)나 เมื่อตัวเลือกเป็นคำนาม และใช้ -거나 เมื่อเป็นคำกริยา/คำคุณศัพท์/ประโยค',
      'Keduanya berarti "atau", tetapi -거나 menghubungkan kata kerja, kata sifat, atau seluruh klausa (보거나 읽거나 = "menonton atau membaca"), sedangkan (이)나 menghubungkan kata benda (커피나 차 = "kopi atau teh"). Pilih (이)나 jika alternatifnya kata benda, dan -거나 jika berupa kata kerja/kata sifat/klausa.',
      'Cả hai đều nghĩa là "hoặc", nhưng -거나 nối động từ, tính từ hoặc cả mệnh đề (보거나 읽거나 = "xem hoặc đọc"), còn (이)나 nối danh từ (커피나 차 = "cà phê hoặc trà"). Hãy dùng (이)나 khi các lựa chọn là danh từ, và dùng -거나 khi chúng là động từ/tính từ/mệnh đề.',
      'どちらも「～か」を意味しますが、-거나 は動詞・形容詞や文全体をつなぎ（보거나 읽거나 =「見たり読んだり」）、(이)나 は名詞をつなぎます（커피나 차 =「コーヒーかお茶」）。選択肢が名詞のときは (이)나 を、動詞・形容詞・文のときは -거나 を選びましょう。',
    ),
    items: [
      {
        sentence: '주말에는 보통 집에서 {} 차를 마셔요.',
        optionA: '커피거나',
        optionB: '커피나',
        answer: 'b',
        trans: L(
          'On weekends I usually drink coffee or tea at home.',
          'Los fines de semana normalmente tomo café o té en casa.',
          'Le week-end, je bois généralement du café ou du thé à la maison.',
          'Nos fins de semana eu costumo tomar café ou chá em casa.',
          'ในวันหยุดสุดสัปดาห์ ฉันมักจะดื่มกาแฟหรือชาที่บ้าน',
          'Di akhir pekan saya biasanya minum kopi atau teh di rumah.',
          'Vào cuối tuần mình thường uống cà phê hoặc trà ở nhà.',
          '週末はたいてい家でコーヒーかお茶を飲みます。',
        ),
        why: L(
          '커피 and 차 are nouns, so noun-joining (이)나 is required; -거나 cannot attach to a bare noun, making 커피거나 ungrammatical.',
          '커피 y 차 son sustantivos, así que se requiere la unión de sustantivos (이)나; -거나 no puede pegarse a un sustantivo pelado, lo que hace que 커피거나 sea agramatical.',
          '커피 et 차 sont des noms, donc la liaison de noms (이)나 est requise ; -거나 ne peut pas s\'attacher à un nom seul, ce qui rend 커피거나 agrammatical.',
          '커피 e 차 são substantivos, então a junção de substantivos (이)나 é necessária; -거나 não pode se ligar a um substantivo puro, tornando 커피거나 agramatical.',
          '커피 และ 차 เป็นคำนาม จึงต้องใช้ (이)나 ที่เชื่อมคำนาม; -거나 ไม่สามารถต่อท้ายคำนามเปล่าๆ ได้ ทำให้ 커피거나 ผิดหลักไวยากรณ์',
          '커피 dan 차 adalah kata benda, jadi penghubung kata benda (이)나 diperlukan; -거나 tidak bisa menempel pada kata benda telanjang, sehingga 커피거나 menjadi tidak gramatikal.',
          '커피 và 차 là danh từ, nên cần dùng (이)나 nối danh từ; -거나 không thể gắn vào một danh từ trần, khiến 커피거나 sai ngữ pháp.',
          '커피 と 차 は名詞なので、名詞をつなぐ (이)나 が必要です。-거나 は裸の名詞には付けられず、커피거나 は非文になります。',
        ),
      },
      {
        sentence: '주말에 심심할 때는 영화를 {} 책을 읽어요.',
        optionA: '보거나',
        optionB: '보나',
        answer: 'a',
        trans: L(
          'When I\'m bored on weekends, I watch a movie or read a book.',
          'Cuando me aburro los fines de semana, veo una película o leo un libro.',
          'Quand je m\'ennuie le week-end, je regarde un film ou je lis un livre.',
          'Quando fico entediado nos fins de semana, assisto a um filme ou leio um livro.',
          'เวลาเบื่อในวันหยุดสุดสัปดาห์ ฉันจะดูหนังหรืออ่านหนังสือ',
          'Kalau bosan di akhir pekan, saya menonton film atau membaca buku.',
          'Khi buồn chán vào cuối tuần, mình xem phim hoặc đọc sách.',
          '週末に退屈なときは、映画を見たり本を読んだりします。',
        ),
        why: L(
          '보다 and 읽다 are verbs offered as alternatives, so verb-joining -거나 is needed; 보나 (보- + -(으)나) means \'although I watch,\' a concession that does not give the intended \'or\' sense.',
          '보다 y 읽다 son verbos ofrecidos como alternativas, así que se necesita la unión de verbos -거나; 보나 (보- + -(으)나) significa \'aunque vea\', una concesión que no da el sentido de \'o\' que se busca.',
          '보다 et 읽다 sont des verbes proposés comme alternatives, donc la liaison de verbes -거나 est nécessaire ; 보나 (보- + -(으)나) signifie « bien que je regarde », une concession qui ne donne pas le sens « ou » voulu.',
          '보다 e 읽다 são verbos oferecidos como alternativas, então é preciso a junção de verbos -거나; 보나 (보- + -(으)나) significa \'embora eu assista\', uma concessão que não dá o sentido pretendido de \'ou\'.',
          '보다 และ 읽다 เป็นคำกริยาที่เสนอเป็นทางเลือก จึงต้องใช้ -거나 ที่เชื่อมคำกริยา; 보나 (보- + -(으)나) แปลว่า \'ถึงแม้จะดู\' ซึ่งเป็นการยอมรับเงื่อนไข ไม่ได้ให้ความหมาย \'หรือ\' ตามที่ต้องการ',
          '보다 dan 읽다 adalah kata kerja yang ditawarkan sebagai alternatif, jadi penghubung kata kerja -거나 diperlukan; 보나 (보- + -(으)나) berarti \'meskipun saya menonton\', sebuah konsesi yang tidak memberi makna \'atau\' yang dimaksud.',
          '보다 và 읽다 là động từ được đưa ra như các lựa chọn, nên cần dùng -거나 nối động từ; 보나 (보- + -(으)나) nghĩa là \'mặc dù mình xem\', một sự nhượng bộ không mang nghĩa \'hoặc\' như mong muốn.',
          '보다 と 읽다 は選択肢として示された動詞なので、動詞をつなぐ -거나 が必要です。보나（보- + -(으)나）は「見るけれど」という譲歩の意味になり、意図した「～か」の意味になりません。',
        ),
      },
      {
        sentence: '날씨가 너무 {} 추우면 저는 밖에 안 나가요.',
        optionA: '덥거나',
        optionB: '더우나',
        answer: 'a',
        trans: L(
          'If the weather is too hot or cold, I don\'t go outside.',
          'Si hace demasiado calor o frío, no salgo afuera.',
          'S\'il fait trop chaud ou trop froid, je ne sors pas dehors.',
          'Se está muito quente ou frio, eu não saio.',
          'ถ้าอากาศร้อนเกินไปหรือหนาวเกินไป ฉันจะไม่ออกไปข้างนอก',
          'Kalau cuacanya terlalu panas atau dingin, saya tidak keluar.',
          'Nếu thời tiết quá nóng hoặc quá lạnh, mình không ra ngoài.',
          '天気が暑すぎたり寒すぎたりすると、外に出ません。',
        ),
        why: L(
          '덥다 and 춥다 are adjectives offered as alternatives, so -거나 fits the \'hot or cold\' meaning; 더우나 means \'even though hot\' (concession), which breaks the parallel \'or\' structure with 추우면.',
          '덥다 y 춥다 son adjetivos ofrecidos como alternativas, así que -거나 encaja con el sentido \'caliente o frío\'; 더우나 significa \'aunque haga calor\' (concesión), lo que rompe la estructura paralela de \'o\' con 추우면.',
          '덥다 et 춥다 sont des adjectifs proposés comme alternatives, donc -거나 convient au sens « chaud ou froid » ; 더우나 signifie « même s\'il fait chaud » (concession), ce qui brise la structure parallèle « ou » avec 추우면.',
          '덥다 e 춥다 são adjetivos oferecidos como alternativas, então -거나 encaixa no sentido \'quente ou frio\'; 더우나 significa \'mesmo que esteja quente\' (concessão), o que quebra a estrutura paralela de \'ou\' com 추우면.',
          '덥다 และ 춥다 เป็นคำคุณศัพท์ที่เสนอเป็นทางเลือก ดังนั้น -거나 จึงเข้ากับความหมาย \'ร้อนหรือหนาว\'; 더우나 แปลว่า \'ถึงแม้จะร้อน\' (การยอมรับเงื่อนไข) ซึ่งทำให้โครงสร้างคู่ขนาน \'หรือ\' กับ 추우면 พังลง',
          '덥다 dan 춥다 adalah kata sifat yang ditawarkan sebagai alternatif, jadi -거나 cocok dengan makna \'panas atau dingin\'; 더우나 berarti \'meskipun panas\' (konsesi), yang merusak struktur paralel \'atau\' dengan 추우면.',
          '덥다 và 춥다 là tính từ được đưa ra như các lựa chọn, nên -거나 phù hợp với nghĩa \'nóng hoặc lạnh\'; 더우나 nghĩa là \'dù trời nóng\' (nhượng bộ), làm hỏng cấu trúc song song \'hoặc\' với 추우면.',
          '덥다 と 춥다 は選択肢として示された形容詞なので、-거나 が「暑いか寒いか」の意味に合います。더우나 は「暑くても」（譲歩）の意味になり、추우면 と並ぶ「～か」の対構造を壊してしまいます。',
        ),
      },
    ],
  },
  {
    id: 'deorado-aeodo',
    a: '-더라도',
    b: '-아/어도',
    note: L(
      'Both -아/어도 and -더라도 mean "even if/though." Use -아/어도 for everyday concessives, including real, factual, or about-to-happen situations ("even though it actually is/will be X"). Reserve -더라도 for stronger, purely hypothetical or extreme suppositions ("even supposing X were to happen"), often dramatic or unlikely. -더라도 is rarely outright ungrammatical against -아/어도; the choice is usually one of register and how hypothetical the premise feels.',
      'Tanto -아/어도 como -더라도 significan "aunque/incluso si". Usá -아/어도 para concesivos cotidianos, incluyendo situaciones reales, fácticas o que están por suceder ("aunque de verdad es/va a ser X"). Reservá -더라도 para suposiciones más fuertes, puramente hipotéticas o extremas ("aun suponiendo que llegara a pasar X"), a menudo dramáticas o improbables. -더라도 rara vez es directamente agramatical frente a -아/어도; la elección suele ser cuestión de registro y de qué tan hipotética se siente la premisa.',
      '-아/어도 et -더라도 signifient tous deux "même si". Utilise -아/어도 pour les concessives du quotidien, y compris les situations réelles, factuelles ou sur le point d\'arriver ("même si c\'est/ce sera vraiment X"). Réserve -더라도 aux suppositions plus fortes, purement hypothétiques ou extrêmes ("à supposer même que X arrive"), souvent dramatiques ou peu probables. -더라도 est rarement franchement agrammatical face à -아/어도 ; le choix relève généralement du registre et du degré d\'hypothèse ressenti de la prémisse.',
      'Tanto -아/어도 quanto -더라도 significam "mesmo que/ainda que". Use -아/어도 para concessivas do dia a dia, incluindo situações reais, factuais ou prestes a acontecer ("mesmo que realmente seja/vá ser X"). Reserve -더라도 para suposições mais fortes, puramente hipotéticas ou extremas ("mesmo supondo que X viesse a acontecer"), muitas vezes dramáticas ou improváveis. -더라도 raramente é totalmente agramatical em relação a -아/어도; a escolha costuma ser uma questão de registro e de quão hipotética a premissa parece.',
      'ทั้ง -아/어도 และ -더라도 แปลว่า "แม้ว่า/ถึงแม้" ใช้ -아/어도 กับประโยคยอมรับเงื่อนไขในชีวิตประจำวัน รวมถึงสถานการณ์ที่เป็นจริง เป็นข้อเท็จจริง หรือกำลังจะเกิดขึ้น ("แม้ว่ามันจะเป็น/กำลังจะเป็น X จริง ๆ") เก็บ -더라도 ไว้สำหรับการสมมติที่หนักแน่นกว่า เป็นเพียงสมมติฐานล้วน ๆ หรือสุดโต่ง ("แม้สมมติว่า X จะเกิดขึ้นก็ตาม") ซึ่งมักเป็นเรื่องดราม่าหรือไม่น่าจะเป็นไปได้ -더라도 ไม่ค่อยผิดไวยากรณ์อย่างชัดเจนเมื่อเทียบกับ -아/어도 การเลือกใช้มักเป็นเรื่องของระดับภาษาและความรู้สึกว่าข้อสมมติฐานนั้นเป็นเพียงสมมติมากเพียงใด',
      'Baik -아/어도 maupun -더라도 berarti "meskipun/walaupun". Gunakan -아/어도 untuk kalimat konsesif sehari-hari, termasuk situasi yang nyata, faktual, atau yang hampir terjadi ("meskipun memang benar X/akan jadi X"). Simpan -더라도 untuk pengandaian yang lebih kuat, murni hipotetis, atau ekstrem ("sekalipun seandainya X benar-benar terjadi"), sering kali dramatis atau tidak mungkin. -더라도 jarang benar-benar tidak gramatikal dibandingkan -아/어도; pilihannya biasanya soal ragam bahasa dan seberapa hipotetis premisnya terasa.',
      'Cả -아/어도 và -더라도 đều có nghĩa "dù/cho dù". Dùng -아/어도 cho các câu nhượng bộ thường ngày, bao gồm những tình huống có thật, thực tế hoặc sắp xảy ra ("dù thực sự là/sẽ là X"). Để dành -더라도 cho những giả định mạnh hơn, thuần túy giả thuyết hoặc cực đoan ("cho dù giả sử X có xảy ra đi nữa"), thường mang tính kịch tính hoặc khó xảy ra. -더라도 hiếm khi hoàn toàn sai ngữ pháp so với -아/어도; việc lựa chọn thường là vấn đề về sắc thái ngôn ngữ và mức độ giả định của tiền đề.',
      '-아/어도 と -더라도 はどちらも「〜しても／たとえ〜でも」を意味します。-아/어도 は日常的な譲歩、つまり現実の・事実の・今にも起こりそうな状況（「実際にXである／Xになるとしても」）に使います。-더라도 はより強い、純粋に仮定的または極端な想定（「たとえXが起こったとしても」）に取っておき、しばしば大げさだったりありそうになかったりするものに使います。-더라도 は -아/어도 に対して完全に非文法的になることはまれで、選択はたいてい文体の問題と、前提がどれほど仮定的に感じられるかの問題です。',
    ),
    items: [
      {
        sentence: '지금 {} 막차를 못 타니까 택시를 부르자.',
        optionA: '출발하더라도',
        optionB: '출발해도',
        answer: 'b',
        trans: L(
          'Even if we leave right now we can\'t catch the last train, so let\'s call a taxi.',
          'Aunque salgamos ahora mismo no vamos a alcanzar el último tren, así que llamemos un taxi.',
          'Même si on part tout de suite, on ne pourra pas attraper le dernier train, alors appelons un taxi.',
          'Mesmo que a gente saia agora mesmo, não vai dar pra pegar o último trem, então vamos chamar um táxi.',
          'ถึงเราจะออกเดี๋ยวนี้ก็ขึ้นรถไฟเที่ยวสุดท้ายไม่ทันอยู่ดี งั้นเรียกแท็กซี่กันเถอะ',
          'Meskipun kita berangkat sekarang juga, kita tetap tidak akan terkejar kereta terakhir, jadi ayo panggil taksi.',
          'Dù chúng ta đi ngay bây giờ thì cũng không kịp chuyến tàu cuối, nên gọi taxi đi.',
          '今すぐ出発しても終電には間に合わないから、タクシーを呼ぼう。',
        ),
        why: L(
          'Leaving \'right now\' (지금) is a real, immediate, about-to-happen action, so the everyday -아/어도 is the natural fit. -더라도 frames the departure as a remote hypothetical, which clashes with the concrete, present-moment 지금.',
          'Salir "ahora mismo" (지금) es una acción real, inmediata y que está por suceder, así que el -아/어도 cotidiano es lo que encaja naturalmente. -더라도 plantea la salida como una hipótesis remota, lo que choca con el 지금 concreto y del momento presente.',
          'Partir "tout de suite" (지금) est une action réelle, immédiate et sur le point d\'arriver, donc le -아/어도 du quotidien convient naturellement. -더라도 présente le départ comme une hypothèse lointaine, ce qui jure avec le 지금 concret et ancré dans l\'instant présent.',
          'Sair "agora mesmo" (지금) é uma ação real, imediata e prestes a acontecer, então o -아/어도 do dia a dia é o que se encaixa naturalmente. -더라도 enquadra a saída como uma hipótese remota, o que destoa do 지금 concreto e do momento presente.',
          'การออก "เดี๋ยวนี้" (지금) เป็นการกระทำที่เป็นจริง เกิดขึ้นทันที และกำลังจะเกิดขึ้น ดังนั้น -아/어도 แบบใช้ในชีวิตประจำวันจึงเข้ากันโดยธรรมชาติ ส่วน -더라도 ทำให้การออกเดินทางกลายเป็นสมมติฐานที่ห่างไกล ซึ่งขัดกับ 지금 ที่เป็นรูปธรรมและอยู่ในขณะปัจจุบัน',
          'Berangkat "sekarang juga" (지금) adalah tindakan yang nyata, langsung, dan hampir terjadi, jadi -아/어도 sehari-hari adalah pilihan yang paling pas secara alami. -더라도 membingkai keberangkatan sebagai pengandaian yang jauh, yang berbenturan dengan 지금 yang konkret dan terjadi saat ini juga.',
          'Việc đi "ngay bây giờ" (지금) là một hành động có thật, tức thì và sắp xảy ra, nên -아/어도 thường ngày là lựa chọn tự nhiên nhất. -더라도 lại khiến việc khởi hành thành một giả định xa vời, mâu thuẫn với 지금 cụ thể và thuộc thời điểm hiện tại.',
          '「今すぐ」(지금) 出発するのは現実的で即時の、今にも起こる行動なので、日常的な -아/어도 が自然に合います。-더라도 は出発を遠い仮定として枠づけてしまい、具体的で今この瞬間を表す 지금 と衝突します。',
        ),
      },
      {
        sentence: '하늘이 {} 나는 너를 지킬 거야.',
        optionA: '무너지더라도',
        optionB: '무너져도',
        answer: 'a',
        trans: L(
          'Even if the sky were to fall, I will protect you.',
          'Aunque se cayera el cielo, te voy a proteger.',
          'Même si le ciel devait s\'effondrer, je te protégerai.',
          'Mesmo que o céu desabasse, eu vou te proteger.',
          'แม้ฟ้าจะถล่มลงมา ฉันก็จะปกป้องเธอ',
          'Sekalipun langit runtuh, aku akan melindungimu.',
          'Cho dù bầu trời có sụp xuống, anh cũng sẽ bảo vệ em.',
          'たとえ空が落ちてきても、私はあなたを守る。',
        ),
        why: L(
          'An extreme, near-impossible premise is the signature use of the stronger, more hypothetical -더라도, matching the dramatic vow. Plain -아/어도 is grammatical but sounds too light and casual for such a hyperbolic \'supposing\' clause, so -더라도 is the natural choice here.',
          'Una premisa extrema y casi imposible es el uso por excelencia del -더라도, más fuerte y más hipotético, que combina con el juramento dramático. El -아/어도 simple es gramatical, pero suena demasiado leve y casual para una cláusula de "suponiendo que" tan hiperbólica, así que -더라도 es la elección natural acá.',
          'Une prémisse extrême et quasi impossible est l\'usage emblématique du -더라도, plus fort et plus hypothétique, qui s\'accorde avec le serment dramatique. Le -아/어도 simple est grammatical, mais paraît trop léger et trop familier pour une proposition "à supposer que" aussi hyperbolique, donc -더라도 est le choix naturel ici.',
          'Uma premissa extrema e quase impossível é o uso por excelência do -더라도, mais forte e mais hipotético, que combina com o juramento dramático. O -아/어도 simples é gramatical, mas soa leve e casual demais para uma oração de "supondo que" tão hiperbólica, então -더라도 é a escolha natural aqui.',
          'ข้อสมมติฐานที่สุดโต่งและแทบเป็นไปไม่ได้คือการใช้งานอันเป็นเอกลักษณ์ของ -더라도 ที่หนักแน่นและเป็นสมมติฐานมากกว่า ซึ่งเข้ากับคำสาบานอันดราม่า ส่วน -아/어도 แบบธรรมดาถูกไวยากรณ์ก็จริง แต่ฟังดูเบาและเป็นกันเองเกินไปสำหรับอนุประโยค "สมมติว่า" ที่เกินจริงเช่นนี้ ดังนั้น -더라도 จึงเป็นตัวเลือกที่เป็นธรรมชาติที่นี่',
          'Premis yang ekstrem dan nyaris mustahil adalah penggunaan khas dari -더라도 yang lebih kuat dan lebih hipotetis, cocok dengan sumpah yang dramatis. -아/어도 biasa memang gramatikal, tetapi terdengar terlalu ringan dan santai untuk klausa "seandainya" yang sehiperbolis ini, jadi -더라도 adalah pilihan yang alami di sini.',
          'Một tiền đề cực đoan, gần như bất khả thi chính là cách dùng đặc trưng của -더라도 vốn mạnh hơn và mang tính giả định hơn, hợp với lời thề đầy kịch tính. -아/어도 thông thường thì đúng ngữ pháp, nhưng nghe quá nhẹ và xuồng xã đối với một mệnh đề "giả sử" cường điệu như vậy, nên -더라도 là lựa chọn tự nhiên ở đây.',
          '極端でほぼ不可能な前提は、より強くより仮定的な -더라도 の代表的な用法で、大げさな誓いに合います。素の -아/어도 も文法的ですが、これほど誇張された「仮に〜としても」の節には軽くカジュアルすぎる響きになるため、ここでは -더라도 が自然な選択です。',
        ),
      },
      {
        sentence: '비가 {} 우산이 있으니까 괜찮아요.',
        optionA: '오더라도',
        optionB: '와도',
        answer: 'b',
        trans: L(
          'Even if it rains, it\'s fine because I have an umbrella.',
          'Aunque llueva, no hay problema porque tengo paraguas.',
          'Même s\'il pleut, ce n\'est pas grave parce que j\'ai un parapluie.',
          'Mesmo que chova, tudo bem porque eu tenho guarda-chuva.',
          'ถึงฝนจะตกก็ไม่เป็นไรเพราะฉันมีร่ม',
          'Meskipun hujan, tidak apa-apa karena aku punya payung.',
          'Dù trời có mưa thì cũng không sao vì tôi có ô.',
          '雨が降っても、傘があるから大丈夫だよ。',
        ),
        why: L(
          'Rain is an ordinary, plausible everyday possibility, and the reassuring 괜찮아요 keeps the tone light, so the neutral -아/어도 is the unmarked natural pick. -더라도 would over-dramatize a mundane weather case as if it were an extreme supposition.',
          'La lluvia es una posibilidad cotidiana, común y plausible, y el tranquilizador 괜찮아요 mantiene el tono liviano, así que el neutral -아/어도 es la opción natural y no marcada. -더라도 dramatizaría de más un caso mundano de clima, como si fuera una suposición extrema.',
          'La pluie est une possibilité ordinaire, courante et plausible, et le rassurant 괜찮아요 garde un ton léger, donc le neutre -아/어도 est le choix naturel et non marqué. -더라도 dramatiserait à l\'excès un banal cas de météo, comme s\'il s\'agissait d\'une supposition extrême.',
          'A chuva é uma possibilidade comum, corriqueira e plausível do dia a dia, e o tranquilizador 괜찮아요 mantém o tom leve, então o neutro -아/어도 é a escolha natural e não marcada. -더라도 dramatizaria demais um caso banal de clima, como se fosse uma suposição extrema.',
          'ฝนตกเป็นความเป็นไปได้ในชีวิตประจำวันที่ธรรมดาและสมเหตุสมผล และคำว่า 괜찮아요 ที่ให้ความอุ่นใจช่วยคงโทนเบา ๆ ไว้ ดังนั้น -아/어도 ที่เป็นกลางจึงเป็นตัวเลือกที่เป็นธรรมชาติและไม่เน้นย้ำ ส่วน -더라도 จะทำให้เรื่องสภาพอากาศธรรมดา ๆ กลายเป็นดราม่าเกินไป ราวกับว่ามันเป็นการสมมติที่สุดโต่ง',
          'Hujan adalah kemungkinan sehari-hari yang biasa dan masuk akal, dan 괜찮아요 yang menenangkan menjaga nadanya tetap ringan, jadi -아/어도 yang netral adalah pilihan alami dan tidak menonjol. -더라도 akan terlalu mendramatisasi kasus cuaca biasa seolah-olah itu pengandaian yang ekstrem.',
          'Mưa là một khả năng đời thường, bình thường và hợp lý, còn lời trấn an 괜찮아요 giữ cho giọng điệu nhẹ nhàng, nên -아/어도 trung tính là lựa chọn tự nhiên và không đánh dấu. -더라도 sẽ kịch tính hóa quá mức một chuyện thời tiết tầm thường như thể đó là một giả định cực đoan.',
          '雨は日常的でありふれた、起こりそうな可能性であり、安心させる 괜찮아요 が軽い調子を保つので、中立的な -아/어도 が自然で無標の選択です。-더라도 だと、ありふれた天気の話をまるで極端な想定であるかのように大げさにしてしまいます。',
        ),
      },
    ],
  },
]
