import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK 3 confusable grammar/ending pairs (extra batch). a/b match
 * grammars-n*.ts kos verbatim. Each pair: a contrast note + 3 single-answer
 * discrimination items, 8-locale note/trans/why.
 *
 * Drafted + Korean-lens adversarially verified (single-correct-answer crux,
 * naturalness, conjugation, 8-locale fidelity). Native (Korean wife) review is
 * the documented final gate.
 */
export const N3_PAIRS_EXTRA: ConfusablePair[] = [
  {
    id: 'julmoreuda-julmollatda',
    a: '-(으)ㄹ 줄 알다/모르다',
    b: '-(으)ㄴ/는 줄 알다/몰랐다',
    note: L(
      'These look alike but mean different things. -(으)ㄹ 줄 알다/모르다 (future-style ㄹ form) is about a LEARNED SKILL: "know / don\'t know HOW to do" something. -(으)ㄴ/는 줄 알다/몰랐다 (past ㄴ or present 는 form) is about a MISTAKEN BELIEF: "thought that ... (but was wrong)" or "didn\'t know that ...". Decide by meaning: an ability you possess → ㄹ 줄; a (wrong) assumption about a fact → ㄴ/는 줄.',
      'Se parecen pero significan cosas distintas. -(으)ㄹ 줄 알다/모르다 (forma ㄹ, tipo futuro) trata de una HABILIDAD APRENDIDA: "saber / no saber CÓMO hacer" algo. -(으)ㄴ/는 줄 알다/몰랐다 (forma pasada ㄴ o presente 는) trata de una CREENCIA ERRÓNEA: "creía que ... (pero me equivoqué)" o "no sabía que ...". Decidí por el significado: una capacidad que tenés → ㄹ 줄; una suposición (equivocada) sobre un hecho → ㄴ/는 줄.',
      'Elles se ressemblent mais ont des sens différents. -(으)ㄹ 줄 알다/모르다 (forme ㄹ, de type futur) concerne une COMPÉTENCE ACQUISE : « savoir / ne pas savoir COMMENT faire » quelque chose. -(으)ㄴ/는 줄 알다/몰랐다 (forme passée ㄴ ou présente 는) concerne une CROYANCE ERRONÉE : « je croyais que ... (mais à tort) » ou « je ne savais pas que ... ». Décide par le sens : une capacité que tu possèdes → ㄹ 줄 ; une supposition (fausse) sur un fait → ㄴ/는 줄.',
      'Elas se parecem, mas significam coisas diferentes. -(으)ㄹ 줄 알다/모르다 (forma ㄹ, tipo futuro) é sobre uma HABILIDADE APRENDIDA: "saber / não saber COMO fazer" algo. -(으)ㄴ/는 줄 알다/몰랐다 (forma passada ㄴ ou presente 는) é sobre uma CRENÇA EQUIVOCADA: "achei que ... (mas estava errado)" ou "não sabia que ...". Decida pelo sentido: uma capacidade que você tem → ㄹ 줄; uma suposição (errada) sobre um fato → ㄴ/는 줄.',
      'รูปสองอย่างนี้คล้ายกันแต่ความหมายต่างกัน -(으)ㄹ 줄 알다/모르다 (รูป ㄹ แบบอนาคต) เกี่ยวกับทักษะที่เรียนรู้มา: "รู้/ไม่รู้วิธีทำ" บางอย่าง ส่วน -(으)ㄴ/는 줄 알다/몰랐다 (รูปอดีต ㄴ หรือปัจจุบัน 는) เกี่ยวกับความเชื่อที่ผิด: "คิดว่า ... (แต่ผิด)" หรือ "ไม่รู้ว่า ..." ตัดสินจากความหมาย: ความสามารถที่คุณมี → ㄹ 줄; การคาดเดา (ที่ผิด) เกี่ยวกับข้อเท็จจริง → ㄴ/는 줄',
      'Keduanya tampak mirip tetapi maknanya berbeda. -(으)ㄹ 줄 알다/모르다 (bentuk ㄹ, gaya masa depan) tentang KETERAMPILAN yang dipelajari: "tahu / tidak tahu BAGAIMANA melakukan" sesuatu. -(으)ㄴ/는 줄 알다/몰랐다 (bentuk lampau ㄴ atau kini 는) tentang KEYAKINAN yang KELIRU: "saya kira ... (ternyata salah)" atau "saya tidak tahu kalau ...". Putuskan dari maknanya: kemampuan yang kamu miliki → ㄹ 줄; dugaan (yang keliru) tentang suatu fakta → ㄴ/는 줄.',
      'Hai dạng này trông giống nhau nhưng nghĩa khác nhau. -(으)ㄹ 줄 알다/모르다 (dạng ㄹ, kiểu tương lai) nói về KỸ NĂNG học được: "biết / không biết CÁCH làm" việc gì đó. -(으)ㄴ/는 줄 알다/몰랐다 (dạng quá khứ ㄴ hoặc hiện tại 는) nói về NIỀM TIN SAI LẦM: "tôi tưởng là ... (nhưng sai)" hoặc "tôi không biết là ...". Quyết định theo nghĩa: một khả năng bạn có → ㄹ 줄; một phỏng đoán (sai) về một sự việc → ㄴ/는 줄.',
      'この二つは似ているが意味が異なる。-(으)ㄹ 줄 알다/모르다（未来型の ㄹ 形）は習得した能力を表し、何かの「やり方を知っている/知らない」という意味だ。-(으)ㄴ/는 줄 알다/몰랐다（過去の ㄴ または現在の 는 形）は思い違いを表し、「〜と思っていた（が違った）」や「〜とは知らなかった」という意味になる。意味で判断する：自分が持つ能力なら ㄹ 줄、事実についての（誤った）思い込みなら ㄴ/는 줄。',
    ),
    items: [
      {
        sentence: '저는 어릴 때부터 배워서 피아노를 {} 알아요.',
        optionA: '칠 줄',
        optionB: '치는 줄',
        answer: 'a',
        trans: L(
          'I learned from a young age, so I know how to play the piano.',
          'Aprendí desde pequeño, así que sé tocar el piano.',
          'J\'ai appris dès mon plus jeune âge, donc je sais jouer du piano.',
          'Aprendi desde pequeno, então sei tocar piano.',
          'ฉันเรียนมาตั้งแต่เด็ก เลยเล่นเปียโนเป็น',
          'Saya belajar sejak kecil, jadi saya bisa main piano.',
          'Tôi học từ nhỏ nên tôi biết chơi piano.',
          '私は小さい頃から習ったので、ピアノが弾けます。',
        ),
        why: L(
          'This is about a learned ability ("know how to play"), which takes the ㄹ form → 칠 줄 알아요. 치는 줄 알아요 would mean "I thought (someone) was playing the piano", a mistaken-belief reading that clashes with 어릴 때부터 배워서 (because I learned it).',
          'Se trata de una capacidad aprendida ("saber tocar"), que lleva la forma ㄹ → 칠 줄 알아요. 치는 줄 알아요 significaría "creía que (alguien) tocaba el piano", una lectura de creencia errónea que choca con 어릴 때부터 배워서 (porque lo aprendí).',
          'Il s\'agit d\'une capacité acquise (« savoir jouer »), qui prend la forme ㄹ → 칠 줄 알아요. 치는 줄 알아요 voudrait dire « je croyais que (quelqu\'un) jouait du piano », une lecture de croyance erronée qui contredit 어릴 때부터 배워서 (parce que je l\'ai appris).',
          'Trata-se de uma capacidade aprendida ("saber tocar"), que leva a forma ㄹ → 칠 줄 알아요. 치는 줄 알아요 significaria "achei que (alguém) estava tocando piano", uma leitura de crença equivocada que conflita com 어릴 때부터 배워서 (porque aprendi).',
          'นี่เป็นเรื่องความสามารถที่เรียนรู้มา ("เล่นเป็น") ซึ่งใช้รูป ㄹ → 칠 줄 알아요 ส่วน 치는 줄 알아요 จะแปลว่า "คิดว่า (ใครบางคน) กำลังเล่นเปียโน" ซึ่งเป็นการตีความแบบความเชื่อที่ผิด ขัดกับ 어릴 때부터 배워서 (เพราะเรียนมา)',
          'Ini tentang kemampuan yang dipelajari ("bisa bermain"), yang memakai bentuk ㄹ → 칠 줄 알아요. 치는 줄 알아요 akan berarti "saya kira (seseorang) sedang main piano", pembacaan keyakinan keliru yang bertabrakan dengan 어릴 때부터 배워서 (karena saya mempelajarinya).',
          'Đây là về một khả năng học được ("biết chơi"), nên dùng dạng ㄹ → 칠 줄 알아요. 치는 줄 알아요 sẽ có nghĩa "tôi tưởng (ai đó) đang chơi piano", một cách hiểu theo niềm tin sai lầm, xung đột với 어릴 때부터 배워서 (vì tôi đã học nó).',
          'これは習得した能力（「弾ける」）の話なので ㄹ 形 → 칠 줄 알아요 を使う。치는 줄 알아요 だと「（誰かが）ピアノを弾いていると思っていた」という思い違いの読みになり、어릴 때부터 배워서（習ったので）と矛盾する。',
        ),
      },
      {
        sentence: '옆자리 동료가 매일 이렇게 늦게까지 {} 몰랐어요.',
        optionA: '일할 줄',
        optionB: '일하는 줄',
        answer: 'b',
        trans: L(
          'I didn\'t know the coworker next to me works this late every day.',
          'No sabía que el compañero de al lado trabaja hasta tan tarde todos los días.',
          'Je ne savais pas que le collègue à côté de moi travaille aussi tard tous les jours.',
          'Eu não sabia que o colega ao meu lado trabalha até tão tarde todos os dias.',
          'ฉันไม่รู้เลยว่าเพื่อนร่วมงานข้าง ๆ ทำงานดึกขนาดนี้ทุกวัน',
          'Saya tidak tahu kalau rekan kerja di sebelah saya kerja sampai selarut ini setiap hari.',
          'Tôi không biết là đồng nghiệp ngồi cạnh tôi ngày nào cũng làm việc đến muộn thế này.',
          '隣の席の同僚が毎日こんなに遅くまで働いているとは知りませんでした。',
        ),
        why: L(
          'This realizes a standing habitual fact ("works this late every day"), a mistaken-belief reading that needs the present 는 form → 일하는 줄 몰랐어요. 매일 forces a habitual present, so 일할 줄 (the ㄹ skill/expectation form) does not fit here — it would be read as "didn\'t expect he\'d work", which 매일 blocks.',
          'Esto es darse cuenta de un hecho habitual y permanente ("trabaja hasta tan tarde todos los días"), una lectura de creencia errónea que necesita la forma presente 는 → 일하는 줄 몰랐어요. 매일 obliga a un presente habitual, así que 일할 줄 (la forma ㄹ de habilidad/expectativa) no encaja aquí — se leería como "no esperaba que trabajara", algo que 매일 bloquea.',
          'On prend conscience d\'un fait habituel et permanent (« travaille aussi tard tous les jours »), une lecture de croyance erronée qui exige la forme présente 는 → 일하는 줄 몰랐어요. 매일 impose un présent habituel, donc 일할 줄 (la forme ㄹ compétence/attente) ne convient pas ici — elle se lirait « je ne m\'attendais pas à ce qu\'il travaille », ce que 매일 exclut.',
          'Isto é perceber um fato habitual e permanente ("trabalha até tão tarde todos os dias"), uma leitura de crença equivocada que exige a forma presente 는 → 일하는 줄 몰랐어요. 매일 força um presente habitual, então 일할 줄 (a forma ㄹ de habilidade/expectativa) não cabe aqui — seria lido como "não esperava que ele trabalhasse", o que 매일 impede.',
          'นี่คือการเพิ่งรู้ข้อเท็จจริงที่เป็นนิสัยประจำ ("ทำงานดึกขนาดนี้ทุกวัน") เป็นการตีความแบบความเชื่อที่ผิดซึ่งต้องใช้รูปปัจจุบัน 는 → 일하는 줄 몰랐어요 คำว่า 매일 บังคับให้เป็นปัจจุบันแบบเป็นนิสัย ดังนั้น 일할 줄 (รูป ㄹ ทักษะ/การคาดหวัง) จึงไม่เข้ากับที่นี่ เพราะจะอ่านได้ว่า "ไม่คิดว่าเขาจะทำงาน" ซึ่ง 매일 ปิดกั้นไว้',
          'Ini adalah menyadari fakta kebiasaan yang menetap ("kerja selarut ini setiap hari"), pembacaan keyakinan keliru yang membutuhkan bentuk kini 는 → 일하는 줄 몰랐어요. 매일 memaksa kala kini yang habitual, jadi 일할 줄 (bentuk ㄹ keterampilan/ekspektasi) tidak cocok di sini — itu akan terbaca "tidak menyangka dia akan kerja", yang justru dihalangi oleh 매일.',
          'Đây là việc nhận ra một sự thật mang tính thói quen, cố định ("ngày nào cũng làm việc đến muộn thế này"), một cách hiểu theo niềm tin sai lầm cần dạng hiện tại 는 → 일하는 줄 몰랐어요. 매일 buộc phải dùng hiện tại mang tính thói quen, nên 일할 줄 (dạng ㄹ kỹ năng/dự đoán) không hợp ở đây — nó sẽ được hiểu là "không ngờ anh ấy sẽ làm việc", điều mà 매일 ngăn lại.',
          'これは持続的・習慣的な事実（「毎日こんなに遅くまで働いている」）に気づくという思い違いの読みであり、現在の 는 形 → 일하는 줄 몰랐어요 が必要だ。매일 が習慣的現在を要求するため、일할 줄（能力・予期の ㄹ 形）はここに合わず、「働くとは思わなかった」という読みになるが、それは 매일 が排除する。',
        ),
      },
      {
        sentence: '저는 아직 한 번도 안 배워서 자전거를 {} 몰라요.',
        optionA: '탈 줄',
        optionB: '타는 줄',
        answer: 'a',
        trans: L(
          'I haven\'t learned even once yet, so I don\'t know how to ride a bicycle.',
          'Todavía no he aprendido ni una vez, así que no sé andar en bicicleta.',
          'Je n\'ai pas encore appris une seule fois, donc je ne sais pas faire du vélo.',
          'Ainda não aprendi nem uma vez, então não sei andar de bicicleta.',
          'ฉันยังไม่เคยเรียนสักครั้ง เลยขี่จักรยานไม่เป็น',
          'Saya belum pernah belajar sama sekali, jadi tidak bisa naik sepeda.',
          'Tôi vẫn chưa học lần nào nên không biết đi xe đạp.',
          '私はまだ一度も習っていないので、自転車に乗れません。',
        ),
        why: L(
          'This denies a learned ability ("don\'t know how to ride"), which uses the ㄹ form → 탈 줄 몰라요, reinforced by 안 배워서 (because I haven\'t learned). 타는 줄 몰라요 would mean "didn\'t know (someone) rides", an unintended mistaken-belief reading.',
          'Esto niega una capacidad aprendida ("no sé andar"), que usa la forma ㄹ → 탈 줄 몰라요, reforzado por 안 배워서 (porque no lo he aprendido). 타는 줄 몰라요 significaría "no sabía que (alguien) anda", una lectura de creencia errónea no buscada.',
          'Cela nie une capacité acquise (« je ne sais pas faire du vélo »), ce qui emploie la forme ㄹ → 탈 줄 몰라요, renforcé par 안 배워서 (parce que je ne l\'ai pas appris). 타는 줄 몰라요 voudrait dire « je ne savais pas que (quelqu\'un) en fait », une lecture de croyance erronée non voulue.',
          'Isto nega uma capacidade aprendida ("não sei andar"), que usa a forma ㄹ → 탈 줄 몰라요, reforçado por 안 배워서 (porque não aprendi). 타는 줄 몰라요 significaria "não sabia que (alguém) anda", uma leitura de crença equivocada não pretendida.',
          'นี่เป็นการปฏิเสธความสามารถที่เรียนรู้มา ("ขี่ไม่เป็น") ซึ่งใช้รูป ㄹ → 탈 줄 몰라요 และถูกย้ำด้วย 안 배워서 (เพราะยังไม่ได้เรียน) ส่วน 타는 줄 몰라요 จะแปลว่า "ไม่รู้ว่า (ใครบางคน) ขี่" ซึ่งเป็นการตีความแบบความเชื่อที่ผิดที่ไม่ได้ตั้งใจ',
          'Ini menyangkal kemampuan yang dipelajari ("tidak bisa naik"), yang memakai bentuk ㄹ → 탈 줄 몰라요, diperkuat oleh 안 배워서 (karena belum belajar). 타는 줄 몰라요 akan berarti "tidak tahu kalau (seseorang) naik", pembacaan keyakinan keliru yang tidak dimaksudkan.',
          'Câu này phủ định một khả năng học được ("không biết đi"), nên dùng dạng ㄹ → 탈 줄 몰라요, được củng cố bởi 안 배워서 (vì chưa học). 타는 줄 몰라요 sẽ có nghĩa "không biết là (ai đó) đi", một cách hiểu theo niềm tin sai lầm không mong muốn.',
          'これは習得した能力（「乗れない」）を否定しており ㄹ 形 → 탈 줄 몰라요 を使う。안 배워서（習っていないので）がそれを裏づける。타는 줄 몰라요 だと「（誰かが）乗ると知らなかった」という意図しない思い違いの読みになる。',
        ),
      },
    ],
  },
  {
    id: 'aeodo-ndedo',
    a: '-아/어도',
    b: '-(으)ㄴ/는데도',
    note: L(
      'Both are concessive ("even though"), but they frame the first clause differently. -아/어도 is HYPOTHETICAL or GENERAL: "even if / no matter whether X" — the condition may or may not be real, and it pairs naturally with 아무리 and future situations. -(으)ㄴ/는데도 is FACTUAL: "despite X actually being so" — it states a real situation and stresses that the result is surprising or contrary to expectation. Pick -아/어도 for an open/future "even if"; pick -(으)ㄴ/는데도 for a real fact with an unexpected outcome.',
      'Ambas son concesivas ("aunque"), pero plantean la primera cláusula de forma distinta. -아/어도 es HIPOTÉTICA o GENERAL: "aunque / sin importar si X" — la condición puede ser real o no, y combina naturalmente con 아무리 y situaciones futuras. -(으)ㄴ/는데도 es FÁCTICA: "a pesar de que X realmente ocurre" — afirma una situación real y subraya que el resultado es sorprendente o contrario a lo esperado. Elegí -아/어도 para un "aunque" abierto/futuro; elegí -(으)ㄴ/는데도 para un hecho real con un resultado inesperado.',
      'Toutes deux sont concessives (« même si / bien que »), mais elles cadrent différemment la première proposition. -아/어도 est HYPOTHÉTIQUE ou GÉNÉRALE : « même si / peu importe que X » — la condition peut être réelle ou non, et s\'associe naturellement à 아무리 et aux situations futures. -(으)ㄴ/는데도 est FACTUELLE : « bien que X soit réellement le cas » — elle énonce une situation réelle et souligne que le résultat est surprenant ou contraire à l\'attente. Choisis -아/어도 pour un « même si » ouvert/futur ; choisis -(으)ㄴ/는데도 pour un fait réel à l\'issue inattendue.',
      'Ambas são concessivas ("mesmo que / embora"), mas enquadram a primeira oração de forma diferente. -아/어도 é HIPOTÉTICA ou GERAL: "mesmo que / não importa se X" — a condição pode ser real ou não, e combina naturalmente com 아무리 e situações futuras. -(으)ㄴ/는데도 é FACTUAL: "apesar de X realmente acontecer" — afirma uma situação real e enfatiza que o resultado é surpreendente ou contrário ao esperado. Escolha -아/어도 para um "mesmo que" aberto/futuro; escolha -(으)ㄴ/는데도 para um fato real com um desfecho inesperado.',
      'ทั้งคู่เป็นการยอมรับเงื่อนไข ("แม้ว่า") แต่กรอบประโยคแรกต่างกัน -아/어도 เป็นแบบสมมุติหรือทั่วไป: "แม้ว่า / ไม่ว่า X" เงื่อนไขอาจจริงหรือไม่ก็ได้ และเข้าคู่กับ 아무리 และสถานการณ์อนาคตอย่างเป็นธรรมชาติ ส่วน -(으)ㄴ/는데도 เป็นข้อเท็จจริง: "แม้ว่า X จะเป็นจริง" ระบุสถานการณ์ที่เกิดขึ้นจริงและเน้นว่าผลลัพธ์น่าแปลกใจหรือขัดกับที่คาด เลือก -아/어도 สำหรับ "แม้ว่า" แบบเปิด/อนาคต เลือก -(으)ㄴ/는데도 สำหรับข้อเท็จจริงที่มีผลลัพธ์ไม่คาดคิด',
      'Keduanya konsesif ("meskipun"), tetapi membingkai klausa pertama secara berbeda. -아/어도 bersifat HIPOTETIS atau UMUM: "meskipun / terlepas dari apakah X" — kondisinya bisa nyata atau tidak, dan cocok secara alami dengan 아무리 serta situasi masa depan. -(으)ㄴ/는데도 bersifat FAKTUAL: "padahal X memang demikian" — menyatakan situasi nyata dan menekankan bahwa hasilnya mengejutkan atau berlawanan dengan harapan. Pilih -아/어도 untuk "meskipun" yang terbuka/masa depan; pilih -(으)ㄴ/는데도 untuk fakta nyata dengan hasil yang tak terduga.',
      'Cả hai đều nhượng bộ ("dù / mặc dù"), nhưng đóng khung mệnh đề đầu khác nhau. -아/어도 mang tính GIẢ ĐỊNH hoặc CHUNG: "dù / bất kể X có hay không" — điều kiện có thể thật hoặc không, và đi tự nhiên với 아무리 cùng các tình huống tương lai. -(으)ㄴ/는데도 mang tính SỰ THẬT: "mặc dù X thực sự là vậy" — nêu một tình huống có thật và nhấn mạnh rằng kết quả gây bất ngờ hoặc trái với mong đợi. Chọn -아/어도 cho một "dù" mở/tương lai; chọn -(으)ㄴ/는데도 cho một sự thật có kết cục bất ngờ.',
      'どちらも譲歩（「〜ても／〜のに」）だが、前の節の捉え方が違う。-아/어도 は仮定的・一般的で「たとえ〜でも／〜であろうとなかろうと」を表し、条件が現実かどうかは問わず、아무리 や未来の状況と自然に結びつく。-(으)ㄴ/는데도 は事実的で「実際に〜であるのに」を表し、現実の状況を述べたうえで結果が意外・予想に反することを強調する。開かれた・未来の「〜ても」には -아/어도、意外な結果を伴う現実の事実には -(으)ㄴ/는데도 を選ぶ。',
    ),
    items: [
      {
        sentence: '저는 아무리 {} 아침은 꼭 챙겨 먹어요.',
        optionA: '바빠도',
        optionB: '바쁜데도',
        answer: 'a',
        trans: L(
          'No matter how busy I am, I always make sure to eat breakfast.',
          'Por muy ocupado que esté, siempre me aseguro de desayunar.',
          'Aussi occupé que je sois, je veille toujours à prendre le petit-déjeuner.',
          'Por mais ocupado que eu esteja, sempre faço questão de tomar café da manhã.',
          'ไม่ว่าจะยุ่งแค่ไหน ฉันก็กินอาหารเช้าเสมอ',
          'Sesibuk apa pun saya, saya selalu memastikan makan sarapan.',
          'Dù bận đến đâu, tôi cũng luôn cố gắng ăn sáng.',
          'どんなに忙しくても、私は朝ごはんを必ず食べます。',
        ),
        why: L(
          '아무리 (no matter how) is a fixed partner of -아/어도 and frames a general/hypothetical concession → 바빠도. 아무리 ... 바쁜데도 is unnatural, because 아무리 does not combine with the factual -(으)ㄴ/는데도.',
          '아무리 (por muy ... que) es la pareja fija de -아/어도 y plantea una concesión general/hipotética → 바빠도. 아무리 ... 바쁜데도 es poco natural, porque 아무리 no se combina con la fáctica -(으)ㄴ/는데도.',
          '아무리 (aussi ... que) est le partenaire fixe de -아/어도 et pose une concession générale/hypothétique → 바빠도. 아무리 ... 바쁜데도 est peu naturel, car 아무리 ne se combine pas avec la factuelle -(으)ㄴ/는데도.',
          '아무리 (por mais ... que) é o par fixo de -아/어도 e enquadra uma concessão geral/hipotética → 바빠도. 아무리 ... 바쁜데도 é pouco natural, porque 아무리 não combina com a factual -(으)ㄴ/는데도.',
          '아무리 (ไม่ว่าจะ...แค่ไหน) เป็นคู่ตายตัวของ -아/어도 และวางกรอบการยอมรับแบบทั่วไป/สมมุติ → 바빠도 ส่วน 아무리 ... 바쁜데도 ไม่เป็นธรรมชาติ เพราะ 아무리 ไม่เข้าคู่กับ -(으)ㄴ/는데도 ที่เป็นข้อเท็จจริง',
          '아무리 (sebanyak/sesibuk apa pun) adalah pasangan tetap dari -아/어도 dan membingkai konsesi umum/hipotetis → 바빠도. 아무리 ... 바쁜데도 tidak alami, karena 아무리 tidak berpadu dengan -(으)ㄴ/는데도 yang faktual.',
          '아무리 (dù ... đến đâu) là cặp đôi cố định của -아/어도 và đóng khung một sự nhượng bộ chung/giả định → 바빠도. 아무리 ... 바쁜데도 nghe không tự nhiên, vì 아무리 không kết hợp với -(으)ㄴ/는데도 mang tính sự thật.',
          '아무리（どんなに）は -아/어도 と固定的に対になり、一般的・仮定的な譲歩を枠づける → 바빠도。아무리 ... 바쁜데도 は不自然で、아무리 は事実的な -(으)ㄴ/는데도 とは結びつかない。',
        ),
      },
      {
        sentence: '분명히 약을 {} 열이 계속 안 내려요.',
        optionA: '먹어도',
        optionB: '먹었는데도',
        answer: 'b',
        trans: L(
          'I clearly did take the medicine, yet the fever keeps not going down.',
          'Claramente tomé el medicamento, y sin embargo la fiebre sigue sin bajar.',
          'J\'ai clairement pris le médicament, et pourtant la fièvre continue de ne pas baisser.',
          'Eu claramente tomei o remédio, e ainda assim a febre continua não baixando.',
          'ฉันกินยาไปแล้วชัด ๆ แต่ไข้ก็ยังไม่ลดสักที',
          'Saya jelas-jelas sudah minum obat, tapi demamnya terus tidak turun.',
          'Tôi rõ ràng đã uống thuốc rồi, vậy mà sốt vẫn cứ không hạ.',
          'はっきり薬を飲んだのに、熱がずっと下がりません。',
        ),
        why: L(
          '분명히 (clearly) + 계속 (keeps) describes a real, completed action with a surprising actual result, which is the factual -(으)ㄴ/는데도 → 먹었는데도. 먹어도 would read as a general "even if I take medicine", contradicting 분명히 that marks it as something that really happened.',
          '분명히 (claramente) + 계속 (sigue) describe una acción real y ya realizada con un resultado actual sorprendente, que es la fáctica -(으)ㄴ/는데도 → 먹었는데도. 먹어도 se leería como un "aunque tome el medicamento" general, contradiciendo 분명히, que lo marca como algo que de verdad ocurrió.',
          '분명히 (clairement) + 계속 (continue) décrit une action réelle et accomplie avec un résultat actuel surprenant, soit la factuelle -(으)ㄴ/는데도 → 먹었는데도. 먹어도 se lirait comme un « même si je prends le médicament » général, contredisant 분명히 qui le marque comme réellement arrivé.',
          '분명히 (claramente) + 계속 (continua) descreve uma ação real e já realizada com um resultado atual surpreendente, que é a factual -(으)ㄴ/는데도 → 먹었는데도. 먹어도 seria lido como um "mesmo que eu tome o remédio" geral, contradizendo 분명히, que o marca como algo que realmente aconteceu.',
          '분명히 (ชัด ๆ) + 계속 (ยังคง) บรรยายการกระทำที่เกิดขึ้นจริงและเสร็จไปแล้วพร้อมผลลัพธ์ปัจจุบันที่น่าแปลกใจ ซึ่งคือ -(으)ㄴ/는데도 ที่เป็นข้อเท็จจริง → 먹었는데도 ส่วน 먹어도 จะอ่านได้ว่า "แม้ฉันจะกินยา" แบบทั่วไป ขัดกับ 분명히 ที่บ่งว่ามันเกิดขึ้นจริง',
          '분명히 (jelas) + 계속 (terus) menggambarkan tindakan nyata yang sudah selesai dengan hasil aktual yang mengejutkan, yaitu -(으)ㄴ/는데도 yang faktual → 먹었는데도. 먹어도 akan terbaca sebagai "meskipun saya minum obat" yang umum, bertentangan dengan 분명히 yang menandai bahwa itu benar-benar terjadi.',
          '분명히 (rõ ràng) + 계속 (cứ) mô tả một hành động có thật, đã hoàn tất với kết quả thực tế gây bất ngờ, đó là -(으)ㄴ/는데도 mang tính sự thật → 먹었는데도. 먹어도 sẽ được hiểu là "dù tôi uống thuốc" mang tính chung chung, mâu thuẫn với 분명히 vốn đánh dấu rằng việc đó thực sự đã xảy ra.',
          '분명히（はっきり）＋계속（ずっと）は、実際に行った完了動作と意外な現実の結果を述べており、事実的な -(으)ㄴ/는데도 → 먹었는데도 だ。먹어도 だと一般的な「薬を飲んでも」の読みになり、それが本当に起きたと示す 분명히 と矛盾する。',
        ),
      },
      {
        sentence: '내일 비가 {} 우리는 예정대로 등산을 갈 거예요.',
        optionA: '와도',
        optionB: '오는데도',
        answer: 'a',
        trans: L(
          'Even if it rains tomorrow, we will go hiking as planned.',
          'Aunque mañana llueva, iremos de excursión según lo planeado.',
          'Même s\'il pleut demain, nous irons faire de la randonnée comme prévu.',
          'Mesmo que chova amanhã, vamos fazer a trilha conforme o planejado.',
          'แม้ว่าพรุ่งนี้ฝนจะตก เราก็จะไปปีนเขาตามแผน',
          'Meskipun besok hujan, kami akan tetap mendaki sesuai rencana.',
          'Dù ngày mai trời mưa, chúng tôi vẫn sẽ đi leo núi theo kế hoạch.',
          '明日雨が降っても、私たちは予定どおり登山に行きます。',
        ),
        why: L(
          'This is a future hypothetical ("even if it rains tomorrow"), which only -아/어도 can express → 와도. 오는데도 is factual ("despite it raining"), so it clashes with 내일 (tomorrow) and the future plan 갈 거예요, where the rain has not happened yet.',
          'Esto es una hipótesis futura ("aunque mañana llueva"), que solo -아/어도 puede expresar → 와도. 오는데도 es fáctica ("a pesar de que llueve"), así que choca con 내일 (mañana) y el plan futuro 갈 거예요, donde la lluvia aún no ha ocurrido.',
          'C\'est une hypothèse future (« même s\'il pleut demain »), que seul -아/어도 peut exprimer → 와도. 오는데도 est factuelle (« bien qu\'il pleuve »), donc elle contredit 내일 (demain) et le projet futur 갈 거예요, où la pluie n\'a pas encore eu lieu.',
          'Isto é uma hipótese futura ("mesmo que chova amanhã"), que só -아/어도 pode expressar → 와도. 오는데도 é factual ("apesar de estar chovendo"), então conflita com 내일 (amanhã) e o plano futuro 갈 거예요, em que a chuva ainda não aconteceu.',
          'นี่คือสมมุติฐานในอนาคต ("แม้พรุ่งนี้ฝนจะตก") ซึ่งมีแต่ -아/어도 เท่านั้นที่แสดงได้ → 와도 ส่วน 오는데도 เป็นข้อเท็จจริง ("แม้ว่าฝนกำลังตก") จึงขัดกับ 내일 (พรุ่งนี้) และแผนอนาคต 갈 거예요 ที่ฝนยังไม่ได้ตก',
          'Ini adalah hipotesis masa depan ("meskipun besok hujan"), yang hanya bisa diungkapkan dengan -아/어도 → 와도. 오는데도 bersifat faktual ("padahal sedang hujan"), jadi bertabrakan dengan 내일 (besok) dan rencana masa depan 갈 거예요, di mana hujannya belum terjadi.',
          'Đây là một giả định về tương lai ("dù ngày mai trời mưa"), điều mà chỉ -아/어도 diễn đạt được → 와도. 오는데도 mang tính sự thật ("mặc dù trời đang mưa"), nên xung đột với 내일 (ngày mai) và kế hoạch tương lai 갈 거예요, khi mưa còn chưa xảy ra.',
          'これは未来の仮定（「明日雨が降っても」）であり、-아/어도 のみが表せる → 와도。오는데도 は事実的（「降っているのに」）なので、雨がまだ起きていない 내일（明日）と未来の予定 갈 거예요 と矛盾する。',
        ),
      },
    ],
  },
]
