import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK 3 confusable grammar/ending pairs. a/b match grammars-n*.ts kos
 * verbatim. Each pair: a contrast note + 3 single-answer discrimination items,
 * 8-locale note/trans/why.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow
 * (single-correct-answer crux, naturalness, conjugation, 8-locale fidelity).
 * Native (Korean wife) review is the documented final gate.
 */
export const N3_PAIRS: ConfusablePair[] = [
  {
    id: 'gedoeda-eojida',
    a: '-게 되다',
    b: '-아/어지다',
    note: L(
      'Use -게 되다 when an action or situation comes about through outside circumstances rather than your own choice (you "end up" doing/being something). Use -아/어지다 when a quality or state itself gradually changes — typically "become/get" with adjectives.',
      'Usá -게 되다 cuando una acción o situación se da por circunstancias externas y no por tu propia elección (terminás haciendo/siendo algo). Usá -아/어지다 cuando una cualidad o estado en sí cambia de a poco; típicamente \'volverse/ponerse\' con adjetivos.',
      'Utilise -게 되다 quand une action ou une situation se produit du fait de circonstances extérieures et non de ton propre choix (tu « finis par » faire/être quelque chose). Utilise -아/어지다 quand une qualité ou un état lui-même change progressivement ; typiquement « devenir » avec des adjectifs.',
      'Use -게 되다 quando uma ação ou situação acontece por circunstâncias externas em vez de pela sua própria escolha (você \'acaba\' fazendo/sendo algo). Use -아/어지다 quando uma qualidade ou estado em si muda gradualmente; tipicamente \'ficar/tornar-se\' com adjetivos.',
      'ใช้ -게 되다 เมื่อการกระทำหรือสถานการณ์เกิดขึ้นจากสภาวการณ์ภายนอกมากกว่าจากการเลือกของคุณเอง (คุณ \'ลงเอย\' ด้วยการทำ/เป็นอะไรบางอย่าง) ใช้ -아/어지다 เมื่อคุณสมบัติหรือสภาพในตัวมันเองค่อย ๆ เปลี่ยนแปลง โดยทั่วไปคือ \'กลายเป็น/เริ่ม\' กับคำคุณศัพท์',
      'Gunakan -게 되다 ketika suatu tindakan atau situasi terjadi melalui keadaan luar, bukan pilihanmu sendiri (kamu \'jadi\' melakukan/menjadi sesuatu). Gunakan -아/어지다 ketika suatu kualitas atau keadaan itu sendiri berubah secara bertahap; biasanya \'menjadi\' dengan kata sifat.',
      'Dùng -게 되다 khi một hành động hay tình huống xảy ra do hoàn cảnh bên ngoài chứ không phải do lựa chọn của chính bạn (bạn \'rốt cuộc\' làm/trở thành điều gì đó). Dùng -아/어지다 khi bản thân một tính chất hay trạng thái dần dần thay đổi; thường là \'trở nên\' với tính từ.',
      '自分の選択ではなく外的な状況によって行動や状況が生じる場合(何かを『することになる/であることになる』)には -게 되다 を使う。性質や状態そのものが少しずつ変化する場合には -아/어지다 を使い、形容詞とともに『〜になる』を表すのが典型だ。',
    ),
    items: [
      {
        sentence: '회사가 이사를 가서 저도 부산에서 {} 됐어요.',
        optionA: '살게',
        optionB: '살아지게',
        answer: 'a',
        trans: L(
          'Because the company relocated, I ended up living in Busan too.',
          'Como la empresa se mudó, yo también terminé viviendo en Busan.',
          'Comme l\'entreprise a déménagé, j\'ai fini par habiter à Busan moi aussi.',
          'Como a empresa se mudou, eu também acabei morando em Busan.',
          'เพราะบริษัทย้ายที่ตั้ง ฉันเลยลงเอยด้วยการไปอยู่ที่ปูซานด้วย',
          'Karena perusahaan pindah, aku jadi ikut tinggal di Busan juga.',
          'Vì công ty chuyển địa điểm nên tôi cũng rốt cuộc sống ở Busan.',
          '会社が移転したので、私も結局プサンに住むことになった。',
        ),
        why: L(
          'An action you end up doing through outside circumstances takes -게 되다. 살다 is an action verb; *살아지다 is not a real form, so option B is simply ungrammatical here.',
          'Una acción que terminás haciendo por circunstancias externas lleva -게 되다. 살다 es un verbo de acción; *살아지다 no es una forma real, así que la opción B simplemente es agramatical acá.',
          'Une action qu\'on finit par faire à cause de circonstances extérieures prend -게 되다. 살다 est un verbe d\'action ; *살아지다 n\'est pas une forme réelle, donc l\'option B est tout simplement agrammaticale ici.',
          'Uma ação que você acaba fazendo por circunstâncias externas leva -게 되다. 살다 é um verbo de ação; *살아지다 não é uma forma real, então a opção B é simplesmente agramatical aqui.',
          'การกระทำที่คุณลงเอยทำเพราะสถานการณ์ภายนอกใช้ -게 되다 살다 เป็นคำกริยาแสดงการกระทำ ส่วน *살아지다 ไม่ใช่รูปที่มีจริง ดังนั้นตัวเลือก B จึงผิดไวยากรณ์ในที่นี้',
          'Tindakan yang akhirnya kamu lakukan karena keadaan luar memakai -게 되다. 살다 adalah kata kerja aksi; *살아지다 bukan bentuk yang nyata, jadi pilihan B memang tidak gramatikal di sini.',
          'Một hành động mà bạn rốt cuộc làm do hoàn cảnh bên ngoài dùng -게 되다. 살다 là động từ hành động; *살아지다 không phải là dạng có thật, nên phương án B đơn giản là sai ngữ pháp ở đây.',
          '外的な状況の結果として結局やることになる行動には -게 되다 を使う。살다 は動作動詞で、*살아지다 は実在しない形なので、選択肢 B はここでは単純に非文法的だ。',
        ),
      },
      {
        sentence: '봄이 오니까 날씨가 점점 {}.',
        optionA: '따뜻하게 돼요',
        optionB: '따뜻해져요',
        answer: 'b',
        trans: L(
          'As spring arrives, the weather is gradually getting warmer.',
          'A medida que llega la primavera, el clima se va poniendo poco a poco más cálido.',
          'À mesure que le printemps arrive, le temps devient peu à peu plus chaud.',
          'À medida que a primavera chega, o tempo vai ficando gradualmente mais quente.',
          'พอฤดูใบไม้ผลิมาถึง อากาศก็ค่อย ๆ อุ่นขึ้นเรื่อย ๆ',
          'Seiring musim semi tiba, cuaca lambat laun menjadi semakin hangat.',
          'Khi mùa xuân đến, thời tiết dần dần trở nên ấm hơn.',
          '春が来るにつれて、天気が少しずつ暖かくなっている。',
        ),
        why: L(
          '점점 (gradually) signals a quality on an adjective changing by degree, which is exactly -아/어지다. 따뜻하게 돼요 would frame it as a one-time circumstance-driven switch, clashing with 점점, so B is the natural answer.',
          '점점 (poco a poco) señala una cualidad de un adjetivo que cambia por grados, que es justo -아/어지다. 따뜻하게 돼요 lo plantearía como un cambio puntual provocado por la circunstancia, chocando con 점점, así que B es la respuesta natural.',
          '점점 (peu à peu) indique une qualité d\'un adjectif qui change par degrés, ce qui correspond exactement à -아/어지다. 따뜻하게 돼요 le présenterait comme un basculement ponctuel dû aux circonstances, en contradiction avec 점점, donc B est la réponse naturelle.',
          '점점 (gradualmente) sinaliza uma qualidade de um adjetivo mudando por graus, que é exatamente -아/어지다. 따뜻하게 돼요 enquadraria como uma mudança pontual provocada pela circunstância, conflitando com 점점, então B é a resposta natural.',
          '점점 (ค่อย ๆ) บ่งบอกถึงคุณสมบัติของคำคุณศัพท์ที่เปลี่ยนแปลงทีละระดับ ซึ่งตรงกับ -아/어지다 พอดี ส่วน 따뜻하게 돼요 จะทำให้กลายเป็นการเปลี่ยนแบบครั้งเดียวที่เกิดจากสถานการณ์ ซึ่งขัดกับ 점점 ดังนั้น B จึงเป็นคำตอบที่เป็นธรรมชาติ',
          '점점 (lambat laun) menandakan kualitas pada kata sifat yang berubah secara bertahap, yang persis -아/어지다. 따뜻하게 돼요 akan membingkainya sebagai perubahan sekali jadi yang dipicu keadaan, bertabrakan dengan 점점, jadi B adalah jawaban yang alami.',
          '점점 (dần dần) báo hiệu một tính chất ở tính từ thay đổi theo mức độ, đúng là -아/어지다. 따뜻하게 돼요 sẽ khắc họa nó như một sự chuyển đổi một lần do hoàn cảnh gây ra, xung đột với 점점, nên B là đáp án tự nhiên.',
          '점점(少しずつ)は形容詞の性質が程度的に変化することを示し、これはまさに -아/어지다 だ。따뜻하게 돼요 だと状況によって引き起こされる一度きりの切り替わりとして枠づけられ、점점 と衝突するので、B が自然な答えになる。',
        ),
      },
      {
        sentence: '원래 매운 걸 못 먹었는데 한국에 살면서 잘 {} 됐어요.',
        optionA: '먹게',
        optionB: '먹어지게',
        answer: 'a',
        trans: L(
          'I originally couldn\'t eat spicy food, but living in Korea I came to eat it well.',
          'Al principio no podía comer comida picante, pero viviendo en Corea llegué a comerla bien.',
          'Au départ je ne pouvais pas manger épicé, mais à force de vivre en Corée j\'en suis venu à bien le manger.',
          'No começo eu não conseguia comer comida apimentada, mas morando na Coreia passei a comê-la bem.',
          'ตอนแรกฉันกินอาหารเผ็ดไม่ได้ แต่พออยู่เกาหลีก็เลยกินได้เก่งขึ้น',
          'Awalnya aku tidak bisa makan makanan pedas, tapi karena tinggal di Korea aku jadi bisa memakannya dengan baik.',
          'Ban đầu tôi không ăn được đồ cay, nhưng sống ở Hàn Quốc nên tôi đã đi đến chỗ ăn được ngon lành.',
          '最初は辛い食べ物が食べられなかったが、韓国に住んでいて上手に食べられるようになった。',
        ),
        why: L(
          'Coming to do an action (eating) as a result of circumstance takes -게 되다. 먹다 is an action verb; *먹어지다 in this \'ended up eating\' sense is unnatural/ungrammatical, so option B is wrong.',
          'Llegar a hacer una acción (comer) como resultado de la circunstancia lleva -게 되다. 먹다 es un verbo de acción; *먹어지다 en este sentido de \'terminar comiendo\' es poco natural/agramatical, así que la opción B está mal.',
          'En venir à faire une action (manger) par suite des circonstances prend -게 되다. 먹다 est un verbe d\'action ; *먹어지다 dans ce sens de « finir par manger » est peu naturel/agrammatical, donc l\'option B est fausse.',
          'Passar a fazer uma ação (comer) como resultado da circunstância leva -게 되다. 먹다 é um verbo de ação; *먹어지다 nesse sentido de \'acabar comendo\' é não natural/agramatical, então a opção B está errada.',
          'การที่มาถึงจุดที่ทำการกระทำ (กิน) อันเป็นผลจากสถานการณ์ใช้ -게 되다 먹다 เป็นคำกริยาแสดงการกระทำ ส่วน *먹어지다 ในความหมาย \'ลงเอยด้วยการกิน\' นี้ฟังไม่เป็นธรรมชาติ/ผิดไวยากรณ์ ดังนั้นตัวเลือก B จึงผิด',
          'Sampai melakukan suatu tindakan (makan) sebagai akibat dari keadaan memakai -게 되다. 먹다 adalah kata kerja aksi; *먹어지다 dalam arti \'akhirnya makan\' ini tidak alami/tidak gramatikal, jadi pilihan B salah.',
          'Việc đi đến chỗ làm một hành động (ăn) như là kết quả của hoàn cảnh dùng -게 되다. 먹다 là động từ hành động; *먹어지다 theo nghĩa \'rốt cuộc ăn\' này nghe không tự nhiên/sai ngữ pháp, nên phương án B là sai.',
          '状況の結果としてある行動(食べること)をするに至るのには -게 되다 を使う。먹다 は動作動詞で、この『結局食べることになった』という意味での *먹어지다 は不自然・非文法的なので、選択肢 B は誤りだ。',
        ),
      },
    ],
  },
  {
    id: 'myeonseo-dongan',
    a: '-(으)면서',
    b: '-는 동안',
    note: L(
      'Use -(으)면서 when ONE subject does two things at the same time (the two clauses must share the same subject). Use -는 동안 for a time window "during which" something else happens — typically when the two clauses have DIFFERENT subjects, framing a stretch of time rather than two simultaneous actions by one person.',
      'Usá -(으)면서 cuando UN solo sujeto hace dos cosas al mismo tiempo (las dos cláusulas tienen que compartir el mismo sujeto). Usá -는 동안 para una ventana de tiempo "durante la cual" pasa otra cosa: normalmente cuando las dos cláusulas tienen sujetos DISTINTOS, enmarcando un lapso de tiempo en vez de dos acciones simultáneas de una sola persona.',
      'Utilise -(으)면서 quand UN seul sujet fait deux choses en même temps (les deux propositions doivent partager le même sujet). Utilise -는 동안 pour une fenêtre de temps "pendant laquelle" autre chose se produit, typiquement quand les deux propositions ont des sujets DIFFÉRENTS, en cadrant une durée plutôt que deux actions simultanées d\'une seule personne.',
      'Use -(으)면서 quando UM único sujeito faz duas coisas ao mesmo tempo (as duas orações precisam ter o mesmo sujeito). Use -는 동안 para uma janela de tempo "durante a qual" outra coisa acontece, normalmente quando as duas orações têm sujeitos DIFERENTES, enquadrando um intervalo de tempo em vez de duas ações simultâneas de uma só pessoa.',
      'ใช้ -(으)면서 เมื่อประธานคนเดียวทำสองสิ่งพร้อมกัน (สองอนุประโยคต้องมีประธานเดียวกัน) ใช้ -는 동안 สำหรับช่วงเวลา "ระหว่างที่" มีอย่างอื่นเกิดขึ้น โดยทั่วไปเมื่อสองอนุประโยคมีประธานต่างกัน เป็นการกำหนดกรอบช่วงเวลามากกว่าการกระทำสองอย่างพร้อมกันโดยคนคนเดียว',
      'Gunakan -(으)면서 ketika SATU subjek melakukan dua hal pada saat yang sama (kedua klausa harus memiliki subjek yang sama). Gunakan -는 동안 untuk rentang waktu "selama" sesuatu yang lain terjadi, biasanya ketika kedua klausa memiliki subjek yang BERBEDA, membingkai suatu rentang waktu alih-alih dua tindakan serentak oleh satu orang.',
      'Dùng -(으)면서 khi MỘT chủ ngữ làm hai việc cùng một lúc (hai mệnh đề phải có chung chủ ngữ). Dùng -는 동안 cho một khoảng thời gian "trong lúc" một việc khác diễn ra, thường là khi hai mệnh đề có chủ ngữ KHÁC nhau, đóng khung một quãng thời gian thay vì hai hành động đồng thời của một người.',
      '一人の主語が二つのことを同時に行うときは -(으)면서 を使う(二つの節は同じ主語を共有しなければならない)。何か別のことが起こっている「その間」という時間の枠には -는 동안 を使う。これは通常、二つの節の主語が異なる場合で、一人による二つの同時動作ではなく、ある時間の幅を枠づけする。',
    ),
    items: [
      {
        sentence: '저는 보통 음악을 {} 공부해요.',
        optionA: '들으면서',
        optionB: '듣는 동안',
        answer: 'a',
        trans: L(
          'I usually study while listening to music.',
          'Normalmente estudio mientras escucho música.',
          'D\'habitude j\'étudie en écoutant de la musique.',
          'Normalmente eu estudo enquanto escuto música.',
          'ปกติฉันเรียนไปฟังเพลงไป',
          'Aku biasanya belajar sambil mendengarkan musik.',
          'Mình thường vừa nghe nhạc vừa học.',
          '私はたいてい音楽を聴きながら勉強します。',
        ),
        why: L(
          'One person doing two simultaneous habitual actions (listen + study) with a shared subject → -(으)면서. 듣는 동안 frames the listening as a separate time window and is the marked choice for two different subjects, so it is unnatural for this same-subject \'do both at once\' meaning.',
          'Una sola persona haciendo dos acciones habituales simultáneas (escuchar + estudiar) con un sujeto compartido → -(으)면서. 듣는 동안 enmarca el escuchar como una ventana de tiempo aparte y es la opción marcada para dos sujetos distintos, así que resulta poco natural para este sentido de "hacer ambas a la vez" con el mismo sujeto.',
          'Une seule personne faisant deux actions habituelles simultanées (écouter + étudier) avec un sujet partagé → -(으)면서. 듣는 동안 cadre l\'écoute comme une fenêtre de temps distincte et est le choix marqué pour deux sujets différents, donc c\'est peu naturel pour ce sens de "faire les deux à la fois" avec le même sujet.',
          'Uma só pessoa fazendo duas ações habituais simultâneas (escutar + estudar) com um sujeito compartilhado → -(으)면서. 듣는 동안 enquadra o escutar como uma janela de tempo separada e é a escolha marcada para dois sujeitos diferentes, então fica pouco natural para esse sentido de "fazer as duas ao mesmo tempo" com o mesmo sujeito.',
          'คนเดียวทำสองการกระทำที่เป็นนิสัยพร้อมกัน (ฟัง + เรียน) โดยมีประธานเดียวกัน → -(으)면서 ส่วน 듣는 동안 จะกำหนดกรอบการฟังเป็นช่วงเวลาแยกต่างหาก และเป็นตัวเลือกที่ใช้กับสองประธานต่างกัน จึงไม่เป็นธรรมชาติสำหรับความหมาย "ทำทั้งสองอย่างพร้อมกัน" ที่มีประธานเดียวกันนี้',
          'Satu orang melakukan dua tindakan kebiasaan secara serentak (mendengarkan + belajar) dengan subjek yang sama → -(으)면서. 듣는 동안 membingkai kegiatan mendengarkan sebagai rentang waktu terpisah dan merupakan pilihan bertanda untuk dua subjek berbeda, sehingga terdengar tidak alami untuk makna "melakukan keduanya sekaligus" dengan subjek yang sama ini.',
          'Một người làm hai hành động thói quen đồng thời (nghe + học) với cùng một chủ ngữ → -(으)면서. 듣는 동안 đóng khung việc nghe như một khoảng thời gian riêng và là lựa chọn được đánh dấu cho hai chủ ngữ khác nhau, nên nó nghe không tự nhiên với nghĩa "làm cả hai cùng lúc" có cùng chủ ngữ này.',
          '一人が二つの習慣的な動作を同時に行い(聴く+勉強する)、主語が共通している → -(으)면서。듣는 동안 は聴くことを別の時間の枠として捉え、二つの異なる主語に対する有標の選択なので、同じ主語で「両方を同時にする」というこの意味には不自然である。',
        ),
      },
      {
        sentence: '제가 {} 동생이 제 케이크를 다 먹었어요.',
        optionA: '자면서',
        optionB: '자는 동안',
        answer: 'b',
        trans: L(
          'While I was sleeping, my little brother ate all my cake.',
          'Mientras yo dormía, mi hermanito se comió todo mi pastel.',
          'Pendant que je dormais, mon petit frère a mangé tout mon gâteau.',
          'Enquanto eu dormia, meu irmãozinho comeu todo o meu bolo.',
          'ตอนที่ฉันนอนหลับ น้องชายของฉันกินเค้กของฉันหมดเลย',
          'Saat aku sedang tidur, adik laki-lakiku menghabiskan semua kueku.',
          'Trong lúc mình đang ngủ, em trai mình đã ăn hết bánh của mình.',
          '私が寝ている間に、弟が私のケーキを全部食べてしまいました。',
        ),
        why: L(
          'Two different subjects (I sleep / brother eats) across a time window → -는 동안. -(으)면서 requires one shared subject, so 제가 자면서 ... 먹었어요 would mean I myself ate the cake while sleeping, which is not the intended sentence.',
          'Dos sujetos distintos (yo duermo / hermano come) a lo largo de una ventana de tiempo → -는 동안. -(으)면서 exige un único sujeto compartido, así que 제가 자면서 ... 먹었어요 querría decir que yo mismo me comí el pastel mientras dormía, que no es la oración buscada.',
          'Deux sujets différents (je dors / le frère mange) sur une fenêtre de temps → -는 동안. -(으)면서 exige un seul sujet partagé, donc 제가 자면서 ... 먹었어요 voudrait dire que c\'est moi-même qui ai mangé le gâteau en dormant, ce qui n\'est pas la phrase visée.',
          'Dois sujeitos diferentes (eu durmo / irmão come) ao longo de uma janela de tempo → -는 동안. -(으)면서 exige um único sujeito compartilhado, então 제가 자면서 ... 먹었어요 significaria que eu mesmo comi o bolo enquanto dormia, o que não é a frase pretendida.',
          'สองประธานต่างกัน (ฉันนอน / น้องชายกิน) ในช่วงเวลาหนึ่ง → -는 동안 ส่วน -(으)면서 ต้องใช้ประธานเดียวที่ร่วมกัน ดังนั้น 제가 자면서 ... 먹었어요 จะหมายความว่าฉันเองกินเค้กขณะที่หลับอยู่ ซึ่งไม่ใช่ประโยคที่ตั้งใจ',
          'Dua subjek berbeda (aku tidur / adik makan) sepanjang suatu rentang waktu → -는 동안. -(으)면서 menuntut satu subjek yang sama, jadi 제가 자면서 ... 먹었어요 akan berarti aku sendiri yang memakan kue itu sambil tidur, yang bukan kalimat yang dimaksud.',
          'Hai chủ ngữ khác nhau (mình ngủ / em trai ăn) trong một khoảng thời gian → -는 동안. -(으)면서 đòi hỏi một chủ ngữ chung duy nhất, nên 제가 자면서 ... 먹었어요 sẽ có nghĩa là chính mình ăn bánh trong lúc ngủ, không phải câu được nhắm tới.',
          '異なる二つの主語(私が寝る/弟が食べる)がある時間の枠にわたっている → -는 동안。-(으)면서 は共通の単一の主語を必要とするので、제가 자면서 ... 먹었어요 は私自身が寝ながらケーキを食べたという意味になってしまい、意図した文ではない。',
        ),
      },
      {
        sentence: '엄마는 전화를 {} 설거지를 하셨어요.',
        optionA: '하면서',
        optionB: '하는 동안',
        answer: 'a',
        trans: L(
          'Mom did the dishes while talking on the phone.',
          'Mamá lavó los platos mientras hablaba por teléfono.',
          'Maman a fait la vaisselle tout en parlant au téléphone.',
          'A mamãe lavou a louça enquanto falava ao telefone.',
          'แม่ล้างจานไปคุยโทรศัพท์ไป',
          'Ibu mencuci piring sambil menelepon.',
          'Mẹ vừa rửa chén vừa nói chuyện điện thoại.',
          'お母さんは電話で話しながら皿を洗いました。',
        ),
        why: L(
          'Same subject (Mom) performing two actions simultaneously → -(으)면서. 하는 동안 frames the call as a window for a separate second subject\'s action; with the same subject doing both, -(으)면서 is the natural and expected form.',
          'Mismo sujeto (mamá) realizando dos acciones simultáneas → -(으)면서. 하는 동안 enmarcaría la llamada como una ventana para la acción de un segundo sujeto distinto; con el mismo sujeto haciendo ambas, -(으)면서 es la forma natural y esperada.',
          'Même sujet (maman) réalisant deux actions simultanées → -(으)면서. 하는 동안 cadrerait l\'appel comme une fenêtre pour l\'action d\'un second sujet distinct ; avec le même sujet faisant les deux, -(으)면서 est la forme naturelle et attendue.',
          'Mesmo sujeito (mamãe) realizando duas ações simultâneas → -(으)면서. 하는 동안 enquadraria a ligação como uma janela para a ação de um segundo sujeito distinto; com o mesmo sujeito fazendo as duas, -(으)면서 é a forma natural e esperada.',
          'ประธานเดียวกัน (แม่) ทำสองการกระทำพร้อมกัน → -(으)면서 ส่วน 하는 동안 จะกำหนดกรอบการโทรเป็นช่วงเวลาสำหรับการกระทำของประธานที่สองอีกคน เมื่อประธานเดียวกันทำทั้งสองอย่าง -(으)면서 จึงเป็นรูปที่เป็นธรรมชาติและถูกคาดหมาย',
          'Subjek yang sama (ibu) melakukan dua tindakan serentak → -(으)면서. 하는 동안 akan membingkai panggilan telepon sebagai rentang waktu bagi tindakan subjek kedua yang berbeda; dengan subjek yang sama melakukan keduanya, -(으)면서 adalah bentuk yang alami dan diharapkan.',
          'Cùng một chủ ngữ (mẹ) thực hiện hai hành động đồng thời → -(으)면서. 하는 동안 sẽ đóng khung cuộc gọi như một khoảng thời gian cho hành động của một chủ ngữ thứ hai khác; khi cùng một chủ ngữ làm cả hai, -(으)면서 là hình thức tự nhiên và được mong đợi.',
          '同じ主語(お母さん)が二つの動作を同時に行う → -(으)면서。하는 동안 は電話を別の二番目の主語の動作のための枠として捉えてしまう。同じ主語が両方を行う場合は、-(으)면서 が自然で予想される形である。',
        ),
      },
    ],
  },
  {
    id: 'giwihae-euro',
    a: '-기 위해(서) / -을/를 위해(서)',
    b: '-(으)러 가다/오다',
    note: L(
      'Both express purpose ("in order to"), but -(으)러 가다/오다 attaches only to a motion main verb (가다/오다), while -기 위해(서) works with ANY main verb and is more formal. The decisive test: when the main verb is NOT going or coming, -(으)러 is ungrammatical and you must use -기 위해(서). With a motion verb, -(으)러 is the natural everyday choice and -기 위해 is the wrong register only if the option itself is malformed.',
      'Ambas expresan propósito (\'para\'), pero -(으)러 가다/오다 solo se une a un verbo principal de movimiento (가다/오다), mientras que -기 위해(서) funciona con CUALQUIER verbo principal y es más formal. La prueba decisiva: cuando el verbo principal NO es ir ni venir, -(으)러 es agramatical y tenés que usar -기 위해(서). Con un verbo de movimiento, -(으)러 es la opción natural del día a día y -기 위해 es el registro equivocado solo si la opción en sí está mal formada.',
      'Les deux expriment le but (\'pour\'), mais -(으)러 가다/오다 ne se rattache qu\'à un verbe principal de mouvement (가다/오다), tandis que -기 위해(서) fonctionne avec N\'IMPORTE QUEL verbe principal et est plus formel. Le test décisif : quand le verbe principal n\'est NI aller NI venir, -(으)러 est agrammatical et tu dois utiliser -기 위해(서). Avec un verbe de mouvement, -(으)러 est le choix naturel du quotidien et -기 위해 est le mauvais registre seulement si l\'option elle-même est mal formée.',
      'Ambas expressam propósito (\'para\'), mas -(으)러 가다/오다 só se liga a um verbo principal de movimento (가다/오다), enquanto -기 위해(서) funciona com QUALQUER verbo principal e é mais formal. O teste decisivo: quando o verbo principal NÃO é ir nem vir, -(으)러 é agramatical e você precisa usar -기 위해(서). Com um verbo de movimento, -(으)러 é a escolha natural do dia a dia e -기 위해 é o registro errado apenas se a opção em si estiver malformada.',
      'ทั้งสองแสดงจุดประสงค์ (\'เพื่อ\') แต่ -(으)러 가다/오다 ใช้ต่อกับคำกริยาหลักที่เป็นการเคลื่อนที่เท่านั้น (가다/오다) ในขณะที่ -기 위해(서) ใช้ได้กับคำกริยาหลักใดก็ได้ และเป็นทางการกว่า บททดสอบชี้ขาด: เมื่อคำกริยาหลักไม่ใช่การไปหรือมา -(으)러 จะผิดไวยากรณ์ และคุณต้องใช้ -기 위해(서) เมื่อใช้กับกริยาเคลื่อนที่ -(으)러 เป็นทางเลือกที่เป็นธรรมชาติในชีวิตประจำวัน และ -기 위해 จะเป็นระดับภาษาที่ผิดก็ต่อเมื่อตัวเลือกนั้นเองถูกสร้างมาผิดเท่านั้น',
      'Keduanya menyatakan tujuan (\'untuk\'), tetapi -(으)러 가다/오다 hanya melekat pada verba utama gerak (가다/오다), sedangkan -기 위해(서) berfungsi dengan verba utama APA PUN dan lebih formal. Tes penentunya: ketika verba utamanya BUKAN pergi atau datang, -(으)러 tidak gramatikal dan kamu harus memakai -기 위해(서). Dengan verba gerak, -(으)러 adalah pilihan alami sehari-hari, dan -기 위해 menjadi register yang salah hanya jika opsinya sendiri salah bentuk.',
      'Cả hai đều diễn đạt mục đích (\'để\'), nhưng -(으)러 가다/오다 chỉ gắn với động từ chính chỉ chuyển động (가다/오다), trong khi -기 위해(서) dùng được với BẤT KỲ động từ chính nào và trang trọng hơn. Phép thử quyết định: khi động từ chính KHÔNG phải là đi hay đến, -(으)러 sai ngữ pháp và bạn phải dùng -기 위해(서). Với động từ chuyển động, -(으)러 là lựa chọn tự nhiên hằng ngày, và -기 위해 chỉ sai về sắc thái ngôn ngữ nếu bản thân lựa chọn đó bị viết sai.',
      'どちらも目的（「〜するために」）を表しますが、-(으)러 가다/오다 は移動の主動詞（가다/오다）にしか付かないのに対し、-기 위해(서) はどんな主動詞とも使え、より形式的です。決定的なテスト：主動詞が行く・来るでない場合、-(으)러 は非文法的で、-기 위해(서) を使わなければなりません。移動動詞の場合、-(으)러 が日常的に自然な選択であり、-기 위해 はその選択肢自体が誤って作られている場合にのみ不適切な語法となります。',
    ),
    items: [
      {
        sentence: '동생은 책을 {} 도서관에 갔어요.',
        optionA: '빌리기에',
        optionB: '빌리러',
        answer: 'b',
        trans: L(
          'My younger sibling went to the library to borrow a book.',
          'Mi hermanito fue a la biblioteca a pedir prestado un libro.',
          'Mon petit frère est allé à la bibliothèque pour emprunter un livre.',
          'Meu irmãozinho foi à biblioteca para pegar um livro emprestado.',
          'น้องของฉันไปห้องสมุดเพื่อยืมหนังสือ',
          'Adik saya pergi ke perpustakaan untuk meminjam buku.',
          'Em tôi đã đến thư viện để mượn sách.',
          '私の弟は本を借りに図書館へ行きました。',
        ),
        why: L(
          'The main verb is 갔어요 (motion), so the purpose attaches as -(으)러 가다 → 빌리러 갔어요. optionA 빌리기에 is a different grammar (cause/\'too...to\'), not a purpose marker, so it is ungrammatical here; only 빌리러 is correct.',
          'El verbo principal es 갔어요 (movimiento), así que el propósito se une con -(으)러 가다 → 빌리러 갔어요. La opción A 빌리기에 es otra gramática (causa / \'demasiado... para\'), no un marcador de propósito, así que acá es agramatical; solo 빌리러 es correcto.',
          'Le verbe principal est 갔어요 (mouvement), donc le but se rattache avec -(으)러 가다 → 빌리러 갔어요. L\'option A 빌리기에 est une autre grammaire (cause / \'trop... pour\'), pas un marqueur de but, donc elle est agrammaticale ici ; seul 빌리러 est correct.',
          'O verbo principal é 갔어요 (movimento), então o propósito se liga com -(으)러 가다 → 빌리러 갔어요. A opção A 빌리기에 é outra gramática (causa / \'demais para\'), não um marcador de propósito, então é agramatical aqui; só 빌리러 está correto.',
          'คำกริยาหลักคือ 갔어요 (การเคลื่อนที่) ดังนั้นจุดประสงค์จึงเชื่อมด้วย -(으)러 가다 → 빌리러 갔어요 ตัวเลือก A 빌리기에 เป็นไวยากรณ์คนละแบบ (เหตุ / \'เกินไปจน...\') ไม่ใช่ตัวบ่งบอกจุดประสงค์ จึงผิดไวยากรณ์ในที่นี้ มีเพียง 빌리러 เท่านั้นที่ถูกต้อง',
          'Kata kerja utamanya adalah 갔어요 (gerak), jadi tujuannya melekat dengan -(으)러 가다 → 빌리러 갔어요. Opsi A 빌리기에 adalah tata bahasa yang berbeda (sebab / \'terlalu... untuk\'), bukan penanda tujuan, jadi tidak gramatikal di sini; hanya 빌리러 yang benar.',
          'Động từ chính là 갔어요 (chuyển động), nên mục đích gắn với -(으)러 가다 → 빌리러 갔어요. Lựa chọn A 빌리기에 là ngữ pháp khác (nguyên nhân / \'quá... đến nỗi\'), không phải dấu chỉ mục đích, nên ở đây sai ngữ pháp; chỉ 빌리러 mới đúng.',
          '主動詞は 갔어요(移動)なので、目的は -(으)러 가다 → 빌리러 갔어요 として付きます。選択肢A 빌리기에 は別の文法(原因 / 「〜すぎて」)で、目的を表す標識ではないため、ここでは非文法的です。正しいのは 빌리러 だけです。',
        ),
      },
      {
        sentence: '시험에 {} 매일 밤늦게까지 공부해요.',
        optionA: '합격하기 위해',
        optionB: '합격하러',
        answer: 'a',
        trans: L(
          'I study late every night in order to pass the exam.',
          'Estudio hasta tarde cada noche para aprobar el examen.',
          'J\'étudie tard chaque soir pour réussir l\'examen.',
          'Eu estudo até tarde toda noite para passar na prova.',
          'ฉันเรียนจนดึกทุกคืนเพื่อสอบผ่าน',
          'Saya belajar sampai larut setiap malam untuk lulus ujian.',
          'Tôi học khuya mỗi đêm để thi đậu.',
          '私は試験に合格するために毎晩遅くまで勉強します。',
        ),
        why: L(
          'The main verb is 공부하다 (not a motion verb), so only -기 위해(서) works; -(으)러 is ungrammatical because it requires 가다/오다 as the main verb.',
          'El verbo principal es 공부하다 (no es de movimiento), así que solo funciona -기 위해(서); -(으)러 es agramatical porque exige 가다/오다 como verbo principal.',
          'Le verbe principal est 공부하다 (pas un verbe de mouvement), donc seul -기 위해(서) fonctionne ; -(으)러 est agrammatical car il exige 가다/오다 comme verbe principal.',
          'O verbo principal é 공부하다 (não é de movimento), então só funciona -기 위해(서); -(으)러 é agramatical porque exige 가다/오다 como verbo principal.',
          'คำกริยาหลักคือ 공부하다 (ไม่ใช่กริยาเคลื่อนที่) ดังนั้นใช้ได้แค่ -기 위해(서); -(으)러 ผิดไวยากรณ์เพราะต้องการ 가다/오다 เป็นคำกริยาหลัก',
          'Kata kerja utamanya adalah 공부하다 (bukan gerak), jadi hanya -기 위해(서) yang berfungsi; -(으)러 tidak gramatikal karena memerlukan 가다/오다 sebagai kata kerja utama.',
          'Động từ chính là 공부하다 (không phải động từ chuyển động), nên chỉ -기 위해(서) dùng được; -(으)러 sai ngữ pháp vì nó cần 가다/오다 làm động từ chính.',
          '主動詞は 공부하다(移動ではない)なので、使えるのは -기 위해(서) だけです。-(으)러 は主動詞として 가다/오다 を必要とするため非文法的です。',
        ),
      },
      {
        sentence: '건강을 {} 운동을 시작했어요.',
        optionA: '지키기 위해',
        optionB: '지키러',
        answer: 'a',
        trans: L(
          'I started exercising in order to protect my health.',
          'Empecé a hacer ejercicio para cuidar mi salud.',
          'J\'ai commencé à faire du sport pour préserver ma santé.',
          'Comecei a me exercitar para proteger minha saúde.',
          'ฉันเริ่มออกกำลังกายเพื่อรักษาสุขภาพ',
          'Saya mulai berolahraga untuk menjaga kesehatan saya.',
          'Tôi bắt đầu tập thể dục để bảo vệ sức khỏe của mình.',
          '私は健康を守るために運動を始めました。',
        ),
        why: L(
          'The main verb is 시작하다 (not motion), so -기 위해(서) is required; -(으)러 can\'t attach because the main clause isn\'t going or coming.',
          'El verbo principal es 시작하다 (no es de movimiento), así que se requiere -기 위해(서); -(으)러 no puede unirse porque la cláusula principal no es de ir o venir.',
          'Le verbe principal est 시작하다 (pas un verbe de mouvement), donc -기 위해(서) est requis ; -(으)러 ne peut pas se rattacher car la proposition principale n\'est pas d\'aller ou de venir.',
          'O verbo principal é 시작하다 (não é de movimento), então -기 위해(서) é exigido; -(으)러 não pode se ligar porque a oração principal não é de ir ou vir.',
          'คำกริยาหลักคือ 시작하다 (ไม่ใช่การเคลื่อนที่) ดังนั้นต้องใช้ -기 위해(서); -(으)러 ใช้ไม่ได้เพราะประโยคหลักไม่ใช่การไปหรือมา',
          'Kata kerja utamanya adalah 시작하다 (bukan gerak), jadi -기 위해(서) diperlukan; -(으)러 tidak bisa melekat karena klausa utamanya bukan pergi atau datang.',
          'Động từ chính là 시작하다 (không phải chuyển động), nên cần -기 위해(서); -(으)러 không thể gắn vào vì mệnh đề chính không phải là đi hay đến.',
          '主動詞は 시작하다(移動ではない)なので、-기 위해(서) が必要です。主節が行く・来るではないため -(으)러 は付けられません。',
        ),
      },
    ],
  },
  {
    id: 'boida-geotgatda',
    a: '-아/어 보이다',
    b: '-(으)ㄴ/는 것 같다',
    note: L(
      'Use -아/어 보이다 only when the judgment rests on a direct VISUAL impression of something right in front of you (it looks that way on the surface). Use -(으)ㄴ/는 것 같다 for any inference — from non-visible facts, reasoning, or guesses about the future. When the basis is explicitly framed as outward appearance contrasted with reality, only 보이다 fits; for a guess about an unseen situation or a future event, only 것 같다 fits.',
      'Usá -아/어 보이다 solo cuando el juicio se basa en una impresión VISUAL directa de algo que tenés justo delante (se ve así en la superficie). Usá -(으)ㄴ/는 것 같다 para cualquier inferencia — a partir de hechos no visibles, razonamiento o conjeturas sobre el futuro. Cuando la base se plantea explícitamente como apariencia externa contrastada con la realidad, solo encaja 보이다; para una conjetura sobre una situación no vista o un evento futuro, solo encaja 것 같다.',
      'Utilise -아/어 보이다 uniquement quand le jugement repose sur une impression VISUELLE directe de quelque chose juste devant toi (ça a l\'air ainsi en surface). Utilise -(으)ㄴ/는 것 같다 pour toute inférence — à partir de faits non visibles, de raisonnement ou de suppositions sur l\'avenir. Quand la base est explicitement présentée comme une apparence extérieure opposée à la réalité, seul 보이다 convient ; pour une supposition sur une situation non vue ou un événement futur, seul 것 같다 convient.',
      'Use -아/어 보이다 só quando o julgamento se baseia numa impressão VISUAL direta de algo bem na sua frente (parece assim na superfície). Use -(으)ㄴ/는 것 같다 para qualquer inferência — a partir de fatos não visíveis, raciocínio ou palpites sobre o futuro. Quando a base é explicitamente apresentada como aparência externa em contraste com a realidade, só 보이다 encaixa; para um palpite sobre uma situação não vista ou um evento futuro, só 것 같다 encaixa.',
      'ใช้ -아/어 보이다 เฉพาะเมื่อการตัดสินตั้งอยู่บนความประทับใจทางสายตา (VISUAL) โดยตรงต่อสิ่งที่อยู่ตรงหน้าคุณ (ดูเป็นเช่นนั้นที่ผิวเผิน) ใช้ -(으)ㄴ/는 것 같다 สำหรับการอนุมานใด ๆ — จากข้อเท็จจริงที่มองไม่เห็น การให้เหตุผล หรือการคาดเดาเกี่ยวกับอนาคต เมื่อพื้นฐานถูกกรอบไว้อย่างชัดเจนว่าเป็นรูปลักษณ์ภายนอกที่ตรงข้ามกับความเป็นจริง มีแต่ 보이다 เท่านั้นที่เหมาะ ส่วนการคาดเดาเกี่ยวกับสถานการณ์ที่มองไม่เห็นหรือเหตุการณ์ในอนาคต มีแต่ 것 같다 เท่านั้นที่เหมาะ',
      'Gunakan -아/어 보이다 hanya ketika penilaian didasarkan pada kesan VISUAL langsung terhadap sesuatu yang ada tepat di depanmu (terlihat begitu di permukaan). Gunakan -(으)ㄴ/는 것 같다 untuk inferensi apa pun — dari fakta yang tidak terlihat, penalaran, atau dugaan tentang masa depan. Ketika dasarnya secara eksplisit dibingkai sebagai penampilan luar yang dikontraskan dengan kenyataan, hanya 보이다 yang cocok; untuk dugaan tentang situasi yang tidak terlihat atau peristiwa masa depan, hanya 것 같다 yang cocok.',
      'Chỉ dùng -아/어 보이다 khi phán đoán dựa trên ấn tượng THỊ GIÁC trực tiếp về một thứ ngay trước mặt bạn (trông như vậy ở bề ngoài). Dùng -(으)ㄴ/는 것 같다 cho bất kỳ suy luận nào — từ sự việc không nhìn thấy, lập luận, hoặc phỏng đoán về tương lai. Khi cơ sở được khung định rõ ràng là vẻ ngoài đối lập với thực tế, chỉ 보이다 phù hợp; còn với phỏng đoán về một tình huống không nhìn thấy hoặc một sự kiện tương lai, chỉ 것 같다 phù hợp.',
      '-아/어 보이다 は、目の前にあるものの直接的な視覚的（VISUAL）印象に判断が基づくときだけ使います（表面上そう見える）。-(으)ㄴ/는 것 같다 はあらゆる推論に使います — 目に見えない事実、推理、または未来についての推測から。根拠が現実と対比された外見として明示的に枠づけられている場合は 보이다 のみが合い、見えていない状況や未来の出来事についての推測の場合は 것 같다 のみが合います。',
    ),
    items: [
      {
        sentence: '오늘 사장님 표정이 안 좋으시네요. 무슨 일이 {}.',
        optionA: '있어 보여요',
        optionB: '있는 것 같아요',
        answer: 'b',
        trans: L(
          'The boss looks unhappy today. It seems like something is going on.',
          'El jefe hoy se ve molesto. Parece que algo está pasando.',
          'Le patron a l\'air contrarié aujourd\'hui. On dirait qu\'il se passe quelque chose.',
          'O chefe está com cara de chateado hoje. Parece que está acontecendo alguma coisa.',
          'วันนี้หัวหน้าดูไม่พอใจ ดูเหมือนว่ามีอะไรเกิดขึ้น',
          'Bos hari ini kelihatan tidak senang. Sepertinya ada sesuatu yang sedang terjadi.',
          'Hôm nay sếp trông có vẻ không vui. Hình như có chuyện gì đó đang xảy ra.',
          '上司は今日不機嫌そうに見えます。何かあるみたいです。',
        ),
        why: L(
          'You can\'t visually see that \'a problem exists\' — you infer the hidden situation from his face, so 것 같다. 있어 보여요 tries to make the existence of a problem a visual impression, which is unnatural here.',
          'No podés ver visualmente que \'existe un problema\' — inferís la situación oculta a partir de su cara, por eso 것 같다. 있어 보여요 intenta convertir la existencia de un problema en una impresión visual, lo cual acá resulta poco natural.',
          'Tu ne peux pas voir visuellement qu\'« un problème existe » — tu déduis la situation cachée à partir de son visage, donc 것 같다. 있어 보여요 essaie de faire de l\'existence d\'un problème une impression visuelle, ce qui est peu naturel ici.',
          'Você não consegue ver visualmente que \'existe um problema\' — você infere a situação oculta a partir do rosto dele, por isso 것 같다. 있어 보여요 tenta transformar a existência de um problema numa impressão visual, o que é pouco natural aqui.',
          'คุณไม่สามารถมองเห็นได้ด้วยตาว่า \'มีปัญหาอยู่\' — คุณอนุมานสถานการณ์ที่ซ่อนอยู่จากสีหน้าของเขา จึงใช้ 것 같다 ส่วน 있어 보여요 พยายามทำให้การมีอยู่ของปัญหากลายเป็นภาพที่เห็นด้วยตา ซึ่งไม่เป็นธรรมชาติในที่นี้',
          'Kamu tidak bisa melihat secara visual bahwa \'ada masalah\' — kamu menyimpulkan situasi tersembunyi dari wajahnya, jadi 것 같다. 있어 보여요 mencoba menjadikan keberadaan suatu masalah sebagai kesan visual, yang terasa tidak alami di sini.',
          'Bạn không thể nhìn thấy bằng mắt rằng \'có một vấn đề tồn tại\' — bạn suy ra tình huống ẩn từ khuôn mặt của anh ấy, nên dùng 것 같다. 있어 보여요 cố biến sự tồn tại của một vấn đề thành ấn tượng thị giác, điều này không tự nhiên ở đây.',
          '「問題がある」ことは目で見えるわけではなく、彼の表情から隠れた状況を推測しているので 것 같다 を使います。있어 보여요 は問題の存在を視覚的な印象にしようとしており、ここでは不自然です。',
        ),
      },
      {
        sentence: '하늘이 어두워졌어요. 곧 비가 {}.',
        optionA: '와 보여요',
        optionB: '올 것 같아요',
        answer: 'b',
        trans: L(
          'The sky has gotten dark. It looks like it\'s going to rain soon.',
          'El cielo se puso oscuro. Parece que va a llover pronto.',
          'Le ciel s\'est assombri. On dirait qu\'il va bientôt pleuvoir.',
          'O céu ficou escuro. Parece que vai chover logo.',
          'ท้องฟ้ามืดลงแล้ว ดูเหมือนว่าฝนจะตกเร็ว ๆ นี้',
          'Langit sudah menjadi gelap. Sepertinya sebentar lagi akan hujan.',
          'Trời đã tối lại. Hình như sắp mưa rồi.',
          '空が暗くなりました。もうすぐ雨が降りそうです。',
        ),
        why: L(
          'This is a prediction about a future event (곧), which only 것 같다 expresses. 보이다 cannot attach to a future guess, so 와 보여요 is ungrammatical.',
          'Esto es una predicción sobre un evento futuro (곧), que solo 것 같다 expresa. 보이다 no puede unirse a una conjetura futura, por eso 와 보여요 es agramatical.',
          'C\'est une prédiction sur un événement futur (곧), que seul 것 같다 exprime. 보이다 ne peut pas se rattacher à une supposition future, donc 와 보여요 est agrammatical.',
          'Isto é uma previsão sobre um evento futuro (곧), que só 것 같다 expressa. 보이다 não pode se ligar a um palpite futuro, por isso 와 보여요 é agramatical.',
          'นี่คือการทำนายเหตุการณ์ในอนาคต (곧) ซึ่งมีแต่ 것 같다 เท่านั้นที่แสดงได้ 보이다 ไม่สามารถต่อกับการคาดเดาอนาคตได้ ดังนั้น 와 보여요 จึงผิดไวยากรณ์',
          'Ini adalah prediksi tentang peristiwa di masa depan (곧), yang hanya bisa diungkapkan dengan 것 같다. 보이다 tidak bisa menempel pada dugaan tentang masa depan, sehingga 와 보여요 tidak gramatikal.',
          'Đây là một dự đoán về sự việc trong tương lai (곧), điều mà chỉ 것 같다 diễn đạt được. 보이다 không thể gắn với một phỏng đoán về tương lai, nên 와 보여요 là sai ngữ pháp.',
          'これは未来の出来事（곧）についての予測であり、것 같다 のみが表せます。보이다 は未来の推測には付けられないため、와 보여요 は非文法的です。',
        ),
      },
      {
        sentence: '이 가방, 겉으로는 가죽이라 비싸 보이지만 사실은 싸요. 정말 비싸 {}.',
        optionA: '보여요',
        optionB: '있는 것 같아요',
        answer: 'a',
        trans: L(
          'This bag, on the surface it looks expensive because it\'s leather, but it\'s actually cheap. It really looks expensive.',
          'Este bolso, por fuera se ve caro porque es de cuero, pero en realidad es barato. Realmente se ve caro.',
          'Ce sac, en apparence il a l\'air cher parce qu\'il est en cuir, mais en réalité il est bon marché. Il a vraiment l\'air cher.',
          'Esta bolsa, por fora parece cara porque é de couro, mas na verdade é barata. Realmente parece cara.',
          'กระเป๋าใบนี้ ภายนอกดูแพงเพราะเป็นหนัง แต่จริง ๆ แล้วถูก ดูแพงจริง ๆ',
          'Tas ini, dari luar kelihatan mahal karena terbuat dari kulit, tapi sebenarnya murah. Benar-benar kelihatan mahal.',
          'Cái túi này, bề ngoài trông đắt vì là da, nhưng thật ra lại rẻ. Nhìn thật sự rất đắt.',
          'このかばんは、見た目は革なので高そうに見えますが、実は安いです。本当に高そうに見えます。',
        ),
        why: L(
          'The sentence explicitly frames this as a surface visual impression (겉으로는…) that contradicts the known reality (사실은 싸요). Only 보이다 conveys \'looks that way to the eye despite the truth\'; 것 같다 would assert a genuine inference that it IS expensive, contradicting 사실은 싸요. optionB 있는 것 같아요 also fails to fit the adjective 비싸-, making it the clear wrong choice.',
          'La oración enmarca esto explícitamente como una impresión visual de superficie (겉으로는…) que contradice la realidad conocida (사실은 싸요). Solo 보이다 transmite \'se ve así a la vista a pesar de la verdad\'; 것 같다 afirmaría una inferencia genuina de que ES caro, contradiciendo 사실은 싸요. La opción B 있는 것 같아요 además no concuerda con el adjetivo 비싸-, lo que la vuelve la opción claramente equivocada.',
          'La phrase présente explicitement cela comme une impression visuelle de surface (겉으로는…) qui contredit la réalité connue (사실은 싸요). Seul 보이다 traduit « ça a l\'air ainsi à l\'œil malgré la vérité » ; 것 같다 affirmerait une véritable inférence que c\'EST cher, contredisant 사실은 싸요. L\'option B 있는 것 같아요 ne s\'accorde pas non plus avec l\'adjectif 비싸-, ce qui en fait le choix clairement erroné.',
          'A frase enquadra isto explicitamente como uma impressão visual de superfície (겉으로는…) que contradiz a realidade conhecida (사실은 싸요). Só 보이다 transmite \'parece assim aos olhos apesar da verdade\'; 것 같다 afirmaria uma inferência genuína de que É cara, contradizendo 사실은 싸요. A opção B 있는 것 같아요 também não combina com o adjetivo 비싸-, tornando-a a escolha claramente errada.',
          'ประโยคนี้กรอบไว้อย่างชัดเจนว่าเป็นความรู้สึกทางสายตาที่ผิวเผิน (겉으로는…) ซึ่งขัดกับความจริงที่รู้กันอยู่ (사실은 싸요) มีแต่ 보이다 เท่านั้นที่สื่อว่า \'ดูเป็นเช่นนั้นในสายตาแม้ความจริงจะต่างออกไป\' ส่วน 것 같다 จะเป็นการยืนยันการอนุมานจริง ๆ ว่ามันแพง ซึ่งขัดกับ 사실은 싸요 ตัวเลือก B 있는 것 같아요 ก็ยังไม่เข้ากับคำคุณศัพท์ 비싸- ทำให้เป็นตัวเลือกที่ผิดอย่างชัดเจน',
          'Kalimat ini secara eksplisit membingkainya sebagai kesan visual permukaan (겉으로는…) yang bertentangan dengan kenyataan yang diketahui (사실은 싸요). Hanya 보이다 yang menyampaikan \'kelihatan begitu di mata meskipun kenyataannya berbeda\'; 것 같다 akan menegaskan inferensi sungguhan bahwa tas itu MEMANG mahal, bertentangan dengan 사실은 싸요. Opsi B 있는 것 같아요 juga tidak cocok dengan kata sifat 비싸-, sehingga jelas menjadi pilihan yang salah.',
          'Câu này khung định rõ ràng đây là một ấn tượng thị giác bề mặt (겉으로는…) mâu thuẫn với thực tế đã biết (사실은 싸요). Chỉ 보이다 truyền đạt \'trông như vậy trong mắt dù sự thật khác\'; 것 같다 sẽ khẳng định một suy luận thực sự rằng nó ĐẮT, mâu thuẫn với 사실은 싸요. Phương án B 있는 것 같아요 cũng không hợp với tính từ 비싸-, khiến nó rõ ràng là lựa chọn sai.',
          'この文は、これを既知の現実（사실은 싸요）と矛盾する表面的な視覚的印象（겉으로는…）として明示的に枠づけています。보이다 のみが「真実とは違っても目にはそう見える」を伝えます。것 같다 は本当に高いという真の推論を主張することになり、사실은 싸요 と矛盾します。選択肢B 있는 것 같아요 も形容詞 비싸- に合わず、明らかに誤った選択肢になります。',
        ),
      },
    ],
  },
  {
    id: 'dabomyeon-daboni',
    a: '-다 보면',
    b: '-다 보니',
    note: L(
      '-다 보면 = "if you keep doing X, a natural result will follow" — points to a future/general consequence, so it pairs with non-past, encouraging outcomes. -다 보니 = "while doing X, I came to realize / it turned out that..." — reports a past realization or discovery you arrived at through the action.',
      '-다 보면 = "si seguís haciendo X, va a seguir un resultado natural" — apunta a una consecuencia futura/general, por eso se combina con el no-pasado y con resultados alentadores. -다 보니 = "mientras hacía X, llegué a darme cuenta / resultó que..." — reporta una constatación o un descubrimiento pasado al que llegaste a través de la acción.',
      '-다 보면 = « si tu continues à faire X, un résultat naturel s\'ensuivra » — pointe vers une conséquence future/générale, c\'est pourquoi il se combine avec le non-passé et des résultats encourageants. -다 보니 = « en faisant X, j\'ai fini par me rendre compte / il s\'est avéré que... » — rapporte une prise de conscience ou une découverte passée à laquelle tu es parvenu à travers l\'action.',
      '-다 보면 = "se você continuar fazendo X, um resultado natural vai seguir" — aponta para uma consequência futura/geral, por isso combina com o não-passado e com resultados encorajadores. -다 보니 = "enquanto fazia X, acabei percebendo / acabou que..." — relata uma constatação ou descoberta passada à qual você chegou por meio da ação.',
      '-다 보면 = "ถ้าทำ X ต่อไปเรื่อยๆ ผลลัพธ์ตามธรรมชาติก็จะตามมา" — ชี้ไปยังผลลัพธ์ในอนาคต/ทั่วไป จึงเข้าคู่กับรูปไม่ใช่อดีตและผลลัพธ์เชิงให้กำลังใจ ส่วน -다 보니 = "ขณะที่ทำ X ฉันก็ได้ตระหนักรู้ / กลายเป็นว่า..." — รายงานการตระหนักรู้หรือการค้นพบในอดีตที่คุณได้มาถึงผ่านการกระทำนั้น',
      '-다 보면 = "kalau kamu terus melakukan X, suatu hasil alami akan menyusul" — menunjuk pada konsekuensi masa depan/umum, sehingga berpasangan dengan bentuk non-lampau dan hasil yang membesarkan hati. -다 보니 = "sambil melakukan X, aku jadi menyadari / ternyata..." — melaporkan kesadaran atau penemuan masa lampau yang kamu capai melalui tindakan tersebut.',
      '-다 보면 = "nếu bạn cứ tiếp tục làm X, một kết quả tự nhiên sẽ theo sau" — chỉ tới một hệ quả tương lai/chung chung, nên nó đi với thì phi quá khứ và những kết quả khích lệ. -다 보니 = "trong khi làm X, tôi đã nhận ra / hóa ra là..." — thuật lại một sự nhận ra hay khám phá trong quá khứ mà bạn đạt tới thông qua hành động.',
      '-다 보면 =「Xをし続ければ、自然な結果が後に続く」——未来的・一般的な帰結を指すため、非過去や前向きな結果と組み合わさる。-다 보니 =「Xをしているうちに、気づいた／〜だと分かった」——その行動を通してたどり着いた過去の気づきや発見を報告する。',
    ),
    items: [
      {
        sentence: '한국어를 매일 {} 자연스럽게 실력이 늘 거예요.',
        optionA: '공부하다 보면',
        optionB: '공부하다 보니',
        answer: 'a',
        trans: L(
          'If you keep studying Korean every day, your skills will naturally improve.',
          'Si seguís estudiando coreano todos los días, tus habilidades van a mejorar naturalmente.',
          'Si tu continues à étudier le coréen tous les jours, ton niveau va naturellement s\'améliorer.',
          'Se você continuar estudando coreano todos os dias, suas habilidades vão melhorar naturalmente.',
          'ถ้าคุณศึกษาภาษาเกาหลีทุกวันต่อไปเรื่อยๆ ทักษะของคุณก็จะดีขึ้นเองตามธรรมชาติ',
          'Kalau kamu terus belajar bahasa Korea setiap hari, kemampuanmu akan meningkat dengan sendirinya.',
          'Nếu bạn cứ tiếp tục học tiếng Hàn mỗi ngày, trình độ của bạn sẽ tự nhiên tiến bộ.',
          '毎日韓国語を勉強し続ければ、実力が自然に伸びるでしょう。',
        ),
        why: L(
          'The clause \'늘 거예요\' is a future natural consequence, so -다 보면 fits; -다 보니 would wrongly mark a past realization and clashes with the future-tense outcome.',
          'La cláusula \'늘 거예요\' es una consecuencia natural futura, así que -다 보면 encaja; -다 보니 marcaría erróneamente una constatación pasada y choca con el resultado en tiempo futuro.',
          'La proposition \'늘 거예요\' est une conséquence naturelle future, donc -다 보면 convient ; -다 보니 marquerait à tort une prise de conscience passée et entre en conflit avec le résultat au futur.',
          'A oração \'늘 거예요\' é uma consequência natural futura, então -다 보면 se encaixa; -다 보니 marcaria erroneamente uma constatação passada e entra em conflito com o resultado no futuro.',
          'ประโยค \'늘 거예요\' เป็นผลลัพธ์ตามธรรมชาติในอนาคต ดังนั้น -다 보면 จึงเหมาะสม ส่วน -다 보니 จะกลายเป็นการบ่งบอกการตระหนักรู้ในอดีตอย่างผิดๆ และขัดกับผลลัพธ์ที่เป็นอนาคต',
          'Klausa \'늘 거예요\' adalah konsekuensi alami di masa depan, jadi -다 보면 cocok; -다 보니 akan keliru menandai kesadaran masa lampau dan bertabrakan dengan hasil bertenses masa depan.',
          'Mệnh đề \'늘 거예요\' là một hệ quả tự nhiên trong tương lai, nên -다 보면 phù hợp; -다 보니 sẽ đánh dấu sai một sự nhận ra trong quá khứ và mâu thuẫn với kết quả ở thì tương lai.',
          '「늘 거예요」は未来の自然な結果なので -다 보면 が合う。-다 보니 だと過去の気づきを誤って表すことになり、未来時制の結果と矛盾する。',
        ),
      },
      {
        sentence: '이 동네에서 오래 {} 어느새 정이 들었어요.',
        optionA: '살다 보면',
        optionB: '살다 보니',
        answer: 'b',
        trans: L(
          'Living in this neighborhood for a long time, I came to grow attached to it (before I knew it).',
          'Como viví mucho tiempo en este barrio, sin darme cuenta le terminé tomando cariño.',
          'À force de vivre longtemps dans ce quartier, je m\'y suis attaché sans même m\'en rendre compte.',
          'Como morei muito tempo neste bairro, sem perceber acabei me afeiçoando a ele.',
          'พออาศัยอยู่ในย่านนี้มานาน ก็เผลอเกิดความผูกพันขึ้นมาโดยไม่รู้ตัว',
          'Karena lama tinggal di lingkungan ini, tanpa terasa aku jadi merasa terikat padanya.',
          'Vì sống ở khu phố này lâu, lúc nào không hay tôi đã trở nên gắn bó với nó.',
          'この町に長く住んでいるうちに、いつの間にか情が移っていた。',
        ),
        why: L(
          '\'어느새 정이 들었어요\' is a completed past realization the speaker arrived at, so -다 보니 fits; -다 보면 cannot take a completed past result.',
          '\'어느새 정이 들었어요\' es una constatación pasada ya completada a la que llegó el hablante, así que -다 보니 encaja; -다 보면 no puede tomar un resultado pasado completado.',
          '\'어느새 정이 들었어요\' est une prise de conscience passée déjà accomplie à laquelle le locuteur est parvenu, donc -다 보니 convient ; -다 보면 ne peut pas accueillir un résultat passé accompli.',
          '\'어느새 정이 들었어요\' é uma constatação passada já concluída à qual o falante chegou, então -다 보니 se encaixa; -다 보면 não pode tomar um resultado passado concluído.',
          '\'어느새 정이 들었어요\' เป็นการตระหนักรู้ในอดีตที่เสร็จสมบูรณ์แล้วซึ่งผู้พูดได้มาถึง ดังนั้น -다 보니 จึงเหมาะสม ส่วน -다 보면 ไม่สามารถรับผลลัพธ์ในอดีตที่เสร็จสมบูรณ์ได้',
          '\'어느새 정이 들었어요\' adalah kesadaran masa lampau yang sudah selesai yang dicapai penutur, jadi -다 보니 cocok; -다 보면 tidak bisa menerima hasil masa lampau yang sudah selesai.',
          '\'어느새 정이 들었어요\' là một sự nhận ra trong quá khứ đã hoàn tất mà người nói đạt tới, nên -다 보니 phù hợp; -다 보면 không thể nhận một kết quả quá khứ đã hoàn tất.',
          '「어느새 정이 들었어요」は話し手がたどり着いた完了した過去の気づきなので -다 보니 が合う。-다 보면 は完了した過去の結果を取れない。',
        ),
      },
      {
        sentence: '처음엔 어려워도 계속 {} 누구나 잘하게 돼요.',
        optionA: '연습하다 보면',
        optionB: '연습하다 보니',
        answer: 'a',
        trans: L(
          'Even if it\'s hard at first, if you keep practicing, anyone will get good at it.',
          'Aunque al principio sea difícil, si seguís practicando, cualquiera va a llegar a hacerlo bien.',
          'Même si c\'est difficile au début, si tu continues à t\'entraîner, n\'importe qui finira par bien y arriver.',
          'Mesmo que seja difícil no começo, se você continuar praticando, qualquer um vai acabar mandando bem.',
          'ถึงตอนแรกจะยาก แต่ถ้าฝึกฝนต่อไปเรื่อยๆ ใครก็เก่งขึ้นได้ทั้งนั้น',
          'Meskipun pada awalnya sulit, kalau terus berlatih, siapa pun akan jadi mahir.',
          'Dù lúc đầu có khó, nhưng nếu cứ tiếp tục luyện tập thì ai cũng sẽ trở nên giỏi.',
          '最初は難しくても、練習を続けていけば誰でも上手になります。',
        ),
        why: L(
          '\'누구나 잘하게 돼요\' is a general non-past outcome of continued practice, exactly -다 보면; -다 보니 reports the speaker\'s own personal past discovery, which clashes with the universal \'누구나\' + present statement.',
          '\'누구나 잘하게 돼요\' es un resultado general en no-pasado de la práctica continuada, exactamente -다 보면; -다 보니 reporta el descubrimiento pasado y personal del hablante, lo cual choca con el universal \'누구나\' + la afirmación en presente.',
          '\'누구나 잘하게 돼요\' est un résultat général au non-passé de l\'entraînement continu, exactement -다 보면 ; -다 보니 rapporte la découverte passée et personnelle du locuteur, ce qui entre en conflit avec l\'universel \'누구나\' + l\'énoncé au présent.',
          '\'누구나 잘하게 돼요\' é um resultado geral em não-passado da prática continuada, exatamente -다 보면; -다 보니 relata a descoberta passada e pessoal do falante, o que entra em conflito com o universal \'누구나\' + a afirmação no presente.',
          '\'누구나 잘하게 돼요\' เป็นผลลัพธ์ทั่วไปแบบไม่ใช่อดีตของการฝึกฝนอย่างต่อเนื่อง ตรงกับ -다 보면 พอดี ส่วน -다 보니 บ่งบอกการค้นพบส่วนตัวในอดีตของผู้พูด ซึ่งขัดกับ \'누구나\' ที่เป็นสากล + ประโยคปัจจุบัน',
          '\'누구나 잘하게 돼요\' adalah hasil umum bertenses non-lampau dari latihan yang berkelanjutan, persis -다 보면; -다 보니 melaporkan penemuan pribadi penutur di masa lampau, yang bertabrakan dengan \'누구나\' yang universal + pernyataan masa kini.',
          '\'누구나 잘하게 돼요\' là một kết quả chung ở thì phi quá khứ của việc luyện tập liên tục, đúng là -다 보면; -다 보니 thuật lại sự khám phá cá nhân trong quá khứ của người nói, điều này mâu thuẫn với \'누구나\' mang tính phổ quát + câu ở hiện tại.',
          '「누구나 잘하게 돼요」は練習を続けた結果としての非過去の一般的な帰結で、まさに -다 보면 だ。-다 보니 は話し手自身の個人的な過去の発見を表すため、普遍的な「누구나」＋現在の叙述と矛盾する。',
        ),
      },
    ],
  },
  {
    id: 'dapda-seureopda',
    a: 'N + 답다',
    b: 'N + 스럽다',
    note: L(
      'Use N답다 when the thing genuinely IS that N and lives up to what a true/proper N should be (befitting, worthy of being N): 학생답다 "acts as a real student should," 남자답다 "truly manly." Use N스럽다 when something merely gives the impression or quality of N — a resemblance or feeling, without actually being it: 사랑스럽다 "lovable," 자연스럽다 "natural," 어른스럽다 "(a child who) seems grown-up." Tell them apart by asking: does the subject really embody N (답다), or only resemble/evoke N (스럽다)?',
      'Usá N답다 cuando la cosa genuinamente ES esa N y está a la altura de lo que una verdadera/auténtica N debería ser (digna de ser N, propia de N): 학생답다 "se comporta como un estudiante de verdad debería", 남자답다 "verdaderamente varonil". Usá N스럽다 cuando algo solo da la impresión o la cualidad de N — un parecido o una sensación, sin serlo realmente: 사랑스럽다 "adorable", 자연스럽다 "natural", 어른스럽다 "(un niño que) parece adulto". Distinguílas preguntándote: ¿el sujeto realmente encarna N (답다), o solo se parece a N / la evoca (스럽다)?',
      'Utilise N답다 quand la chose EST véritablement ce N et se montre à la hauteur de ce qu\'un vrai/authentique N devrait être (digne de N, propre à N) : 학생답다 « se comporte comme un vrai étudiant le devrait », 남자답다 « vraiment viril ». Utilise N스럽다 quand quelque chose donne seulement l\'impression ou la qualité de N — une ressemblance ou une sensation, sans l\'être réellement : 사랑스럽다 « adorable », 자연스럽다 « naturel », 어른스럽다 « (un enfant qui) a l\'air adulte ». Distingue-les en te demandant : le sujet incarne-t-il réellement N (답다), ou ne fait-il que ressembler à N / l\'évoquer (스럽다) ?',
      'Use N답다 quando a coisa genuinamente É aquele N e está à altura do que um verdadeiro/autêntico N deveria ser (digno de ser N, próprio de N): 학생답다 "age como um estudante de verdade deveria", 남자답다 "verdadeiramente viril". Use N스럽다 quando algo apenas dá a impressão ou a qualidade de N — uma semelhança ou sensação, sem realmente sê-lo: 사랑스럽다 "adorável", 자연스럽다 "natural", 어른스럽다 "(uma criança que) parece adulta". Diferencie-os perguntando: o sujeito realmente encarna N (답다), ou apenas se assemelha a N / o evoca (스럽다)?',
      'ใช้ N답다 เมื่อสิ่งนั้นเป็น N นั้นอย่างแท้จริงและสมกับสิ่งที่ N ที่แท้จริง/ถูกต้องควรเป็น (สมกับการเป็น N, คู่ควรกับการเป็น N): 학생답다 "ทำตัวอย่างที่นักเรียนที่แท้จริงควรทำ", 남자답다 "เป็นลูกผู้ชายอย่างแท้จริง" ใช้ N스럽다 เมื่อบางสิ่งเพียงให้ความรู้สึกหรือคุณลักษณะของ N เท่านั้น — เป็นความคล้ายคลึงหรือความรู้สึก โดยที่ไม่ได้เป็นจริง ๆ: 사랑스럽다 "น่ารักน่าเอ็นดู", 자연스럽다 "เป็นธรรมชาติ", 어른스럽다 "(เด็กที่) ดูเป็นผู้ใหญ่" แยกความแตกต่างด้วยการถามว่า: ประธานนั้นแสดงถึงความเป็น N จริง ๆ (답다) หรือเพียงคล้าย/ชวนให้นึกถึง N (스럽다)?',
      'Gunakan N답다 ketika sesuatu memang benar-benar ADALAH N itu dan memenuhi apa yang seharusnya menjadi N yang sejati/pantas (pantas menjadi N, layak disebut N): 학생답다 "bertindak sebagaimana seharusnya seorang siswa sejati", 남자답다 "benar-benar jantan". Gunakan N스럽다 ketika sesuatu hanya memberi kesan atau kualitas N — kemiripan atau perasaan, tanpa benar-benar menjadi itu: 사랑스럽다 "menggemaskan", 자연스럽다 "alami", 어른스럽다 "(anak yang) tampak dewasa". Bedakan keduanya dengan bertanya: apakah subjek benar-benar mewujudkan N (답다), atau hanya menyerupai/mengingatkan pada N (스럽다)?',
      'Dùng N답다 khi sự vật thật sự LÀ N đó và xứng với những gì một N đích thực/đúng nghĩa nên có (xứng đáng là N, đúng chất N): 학생답다 "hành xử đúng như một học sinh thật sự nên thế", 남자답다 "thật sự nam tính". Dùng N스럽다 khi cái gì đó chỉ tạo cảm giác hoặc mang tính chất của N — một sự giống hay một cảm giác, mà không thật sự là nó: 사랑스럽다 "đáng yêu", 자연스럽다 "tự nhiên", 어른스럽다 "(một đứa trẻ) trông ra dáng người lớn". Phân biệt chúng bằng cách tự hỏi: chủ thể có thật sự hiện thân cho N (답다), hay chỉ giống/gợi lên N (스럽다)?',
      'そのものが本当にそのNであり、真の・本来あるべきNにふさわしい（Nにふさわしい、Nにふさわしく値する）ときは N답다 を使う：학생답다「本物の学生らしく振る舞う」、남자답다「本当に男らしい」。実際にはそうでないのに、Nの印象や性質を与えるだけ — 似ている、そう感じられる — のときは N스럽다 を使う：사랑스럽다「愛らしい」、자연스럽다「自然だ」、어른스럽다「(子どもが)大人びて見える」。見分けるには次のように問う：主語は本当にNを体現しているか（답다）、それとも単にNに似ている・Nを思わせるだけか（스럽다）？',
    ),
    items: [
      {
        sentence: '그는 약속을 꼭 지키니까 정말 {}.',
        optionA: '남자답다',
        optionB: '남자스럽다',
        answer: 'a',
        trans: L(
          'He always keeps his promises, so he\'s truly manly.',
          'Él siempre cumple sus promesas, así que es verdaderamente varonil.',
          'Il tient toujours ses promesses, donc il est vraiment viril.',
          'Ele sempre cumpre suas promessas, então é realmente viril.',
          'เขารักษาสัญญาเสมอ ดังนั้นเขาจึงเป็นลูกผู้ชายอย่างแท้จริง',
          'Dia selalu menepati janjinya, jadi dia benar-benar jantan.',
          'Anh ấy luôn giữ lời hứa, nên anh ấy thật sự nam tính.',
          '彼はいつも約束を守るので、本当に男らしい。',
        ),
        why: L(
          'He genuinely is a man living up to the ideal, so befitting-N 남자답다 fits; 남자스럽다 is not standard Korean and is wrong here.',
          'Él genuinamente es un hombre que está a la altura del ideal, así que el 남자답다 (digno de ser N) encaja; 남자스럽다 no es coreano estándar y es incorrecto acá.',
          'Il est véritablement un homme à la hauteur de l\'idéal, donc 남자답다 (digne d\'être N) convient ; 남자스럽다 n\'est pas du coréen standard et est incorrect ici.',
          'Ele genuinamente é um homem que está à altura do ideal, então 남자답다 (digno de ser N) se encaixa; 남자스럽다 não é coreano padrão e está errado aqui.',
          'เขาเป็นผู้ชายที่สมกับอุดมคติอย่างแท้จริง ดังนั้น 남자답다 (สมกับการเป็น N) จึงเหมาะสม ส่วน 남자스럽다 ไม่ใช่ภาษาเกาหลีมาตรฐานและผิดในที่นี้',
          'Dia memang benar-benar pria yang memenuhi ideal, jadi 남자답다 (pantas menjadi N) cocok; 남자스럽다 bukan bahasa Korea baku dan salah di sini.',
          'Anh ấy thật sự là một người đàn ông xứng với hình mẫu lý tưởng, nên 남자답다 (xứng đáng là N) phù hợp; 남자스럽다 không phải tiếng Hàn chuẩn và sai ở đây.',
          '彼は理想にふさわしい本物の男なので、Nにふさわしいという 남자답다 が合う。남자스럽다 は標準的な韓国語ではなく、ここでは誤り。',
        ),
      },
      {
        sentence: '아기가 방긋 웃는 모습이 너무 {}.',
        optionA: '사랑답다',
        optionB: '사랑스럽다',
        answer: 'b',
        trans: L(
          'The way the baby smiles is so lovable.',
          'La forma en que sonríe el bebé es tan adorable.',
          'La façon dont le bébé sourit est si adorable.',
          'O jeito que o bebê sorri é tão adorável.',
          'ท่าทางที่ทารกยิ้มช่างน่ารักน่าเอ็นดูเหลือเกิน',
          'Cara bayi itu tersenyum sangat menggemaskan.',
          'Cách em bé cười thật đáng yêu.',
          '赤ちゃんが笑う様子がとても愛らしい。',
        ),
        why: L(
          'The baby gives off the quality/impression of love (lovable), so 사랑스럽다 fits; 사랑답다 (\'befitting love itself\') is not a used word.',
          'El bebé transmite la cualidad o impresión de amor (adorable), así que 사랑스럽다 encaja; 사랑답다 (\'digno del amor mismo\') no es una palabra que se use.',
          'Le bébé dégage la qualité ou l\'impression d\'amour (adorable), donc 사랑스럽다 convient ; 사랑답다 (« digne de l\'amour lui-même ») n\'est pas un mot utilisé.',
          'O bebê transmite a qualidade ou impressão de amor (adorável), então 사랑스럽다 se encaixa; 사랑답다 (\'digno do próprio amor\') não é uma palavra usada.',
          'ทารกให้ความรู้สึกหรือคุณลักษณะของความรัก (น่ารัก) ดังนั้น 사랑스럽다 จึงเหมาะสม ส่วน 사랑답다 (\'สมกับความรักเอง\') ไม่ใช่คำที่ใช้กัน',
          'Bayi itu memancarkan kualitas atau kesan cinta (menggemaskan), jadi 사랑스럽다 cocok; 사랑답다 (\'pantas menjadi cinta itu sendiri\') bukan kata yang dipakai.',
          'Em bé toát ra phẩm chất hoặc cảm giác của tình yêu (đáng yêu), nên 사랑스럽다 phù hợp; 사랑답다 (\'xứng với chính tình yêu\') không phải là từ được dùng.',
          '赤ちゃんは愛という性質・印象（愛らしさ）を与えているので 사랑스럽다 が合う。사랑답다（「愛そのものにふさわしい」）は使われる語ではない。',
        ),
      },
      {
        sentence: '겨우 일곱 살인데 동생을 잘 챙기는 걸 보면 참 {}.',
        optionA: '어른답다',
        optionB: '어른스럽다',
        answer: 'b',
        trans: L(
          'He\'s only seven, but seeing how well he looks after his younger sibling, he really seems grown-up.',
          'Tiene apenas siete años, pero viendo lo bien que cuida a su hermanito, de verdad parece todo un adulto.',
          'Il n\'a que sept ans, mais à voir comme il s\'occupe bien de son petit frère, il a vraiment l\'air d\'un adulte.',
          'Ele tem apenas sete anos, mas vendo como cuida bem do irmãozinho, ele realmente parece um adulto.',
          'เขาอายุแค่เจ็ดขวบ แต่เมื่อเห็นว่าเขาดูแลน้องได้ดีแค่ไหน ก็รู้สึกว่าเขาช่างเป็นผู้ใหญ่จริง ๆ',
          'Dia baru tujuh tahun, tapi melihat betapa baiknya dia menjaga adiknya, dia benar-benar terlihat dewasa.',
          'Em ấy mới bảy tuổi thôi, nhưng nhìn cách em chăm sóc em nhỏ giỏi thế nào thì thật sự trông rất ra dáng người lớn.',
          'まだ七歳なのに、弟（妹）の面倒をよく見ているのを見ると、本当に大人びている。',
        ),
        why: L(
          'A seven-year-old only resembles an adult (gives the impression), so 어른스럽다 fits; 어른답다 would assert he genuinely is a proper adult, which \'겨우 일곱 살\' contradicts.',
          'Un niño de siete años solo se parece a un adulto (da la impresión), así que 어른스럽다 encaja; 어른답다 afirmaría que genuinamente es un adulto hecho y derecho, lo cual \'겨우 일곱 살\' contradice.',
          'Un enfant de sept ans ne fait que ressembler à un adulte (il en donne l\'impression), donc 어른스럽다 convient ; 어른답다 affirmerait qu\'il est véritablement un adulte à part entière, ce que \'겨우 일곱 살\' contredit.',
          'Uma criança de sete anos apenas se parece com um adulto (dá a impressão), então 어른스럽다 se encaixa; 어른답다 afirmaria que ele genuinamente é um adulto de verdade, o que \'겨우 일곱 살\' contradiz.',
          'เด็กอายุเจ็ดขวบเพียงแค่ดูคล้ายผู้ใหญ่ (ให้ความรู้สึกนั้น) ดังนั้น 어른스럽다 จึงเหมาะสม ส่วน 어른답다 จะยืนยันว่าเขาเป็นผู้ใหญ่เต็มตัวจริง ๆ ซึ่งขัดกับ \'겨우 일곱 살\'',
          'Anak tujuh tahun hanya mirip orang dewasa (memberi kesan), jadi 어른스럽다 cocok; 어른답다 akan menegaskan bahwa dia benar-benar orang dewasa sejati, yang bertentangan dengan \'겨우 일곱 살\'.',
          'Một đứa trẻ bảy tuổi chỉ giống người lớn (gây ấn tượng đó), nên 어른스럽다 phù hợp; 어른답다 sẽ khẳng định em thật sự là một người lớn đúng nghĩa, điều mà \'겨우 일곱 살\' mâu thuẫn.',
          '七歳の子は大人に似ているだけ（印象を与える）なので 어른스럽다 が合う。어른답다 は本当に一人前の大人だと断定することになり、\'겨우 일곱 살\' と矛盾する。',
        ),
      },
    ],
  },
]
