import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * Extra TOPIK-4 confusable grammar pairs (discrimination drill).
 * a/b are copied verbatim from grammars-n4.ts catalog 'ko' fields.
 * Each pair: 8-locale note + >=3 single-correct-answer items (8-locale trans + why).
 *
 * Drafted + Korean-lens adversarially verified (single-answer-per-item crux,
 * naturalness, conjugation, 8-locale fidelity). Native (Korean wife) review is
 * the documented final gate.
 */
export const N4_PAIRS_EXTRA: ConfusablePair[] = [
  {
    id: 'barame-neura',
    a: '-는 바람에',
    b: '-느라(고)',
    note: L(
      'Both give a "because" cause with a usually negative result, but -는 바람에 marks a SUDDEN, often external event outside the speaker\'s control (subjects may differ), while -느라(고) means the SAME subject was busy doing a deliberate action, so it crowded out the result.',
      'Ambos dan una causa "porque" de resultado normalmente negativo, pero -는 바람에 marca un suceso REPENTINO, a menudo externo y fuera del control del hablante (los sujetos pueden diferir), mientras que -느라(고) significa que el MISMO sujeto estaba ocupado haciendo algo deliberado, lo que impidió el resultado.',
      'Les deux donnent une cause « parce que » à résultat généralement négatif, mais -는 바람에 marque un événement SOUDAIN, souvent externe et hors du contrôle du locuteur (sujets pouvant différer), tandis que -느라(고) signifie que le MÊME sujet était occupé à faire une action délibérée, ce qui a empêché le résultat.',
      'Ambos dão uma causa "porque" de resultado geralmente negativo, mas -는 바람에 marca um evento REPENTINO, muitas vezes externo e fora do controle do falante (os sujeitos podem diferir), enquanto -느라(고) significa que o MESMO sujeito estava ocupado fazendo algo deliberado, o que impediu o resultado.',
      'ทั้งคู่บอกเหตุ "เพราะ" ที่ผลมักเป็นลบ แต่ -는 바람에 บอกเหตุการณ์ที่เกิดขึ้นกะทันหัน มักมาจากภายนอกและอยู่นอกการควบคุมของผู้พูด (ประธานต่างกันได้) ส่วน -느라(고) หมายถึงประธานคนเดียวกันกำลังยุ่งกับการทำสิ่งหนึ่งโดยตั้งใจ จึงทำให้ทำอีกสิ่งไม่ได้',
      'Keduanya memberi sebab "karena" yang hasilnya biasanya negatif, tetapi -는 바람에 menandai kejadian MENDADAK, sering eksternal dan di luar kendali penutur (subjek bisa berbeda), sedangkan -느라(고) berarti subjek yang SAMA sibuk melakukan tindakan yang disengaja, sehingga menghalangi hasilnya.',
      'Cả hai nêu nguyên nhân "vì" với kết quả thường tiêu cực, nhưng -는 바람에 chỉ một sự việc BẤT NGỜ, thường từ bên ngoài và ngoài tầm kiểm soát của người nói (chủ ngữ có thể khác nhau), còn -느라(고) nghĩa là CÙNG một chủ ngữ bận làm một hành động có chủ ý, nên cản trở kết quả.',
      'どちらも「〜から」の原因で結果は通常マイナスだが、-는 바람에 は話者の制御外の突発的・外的な出来事を表し(主語が異なってもよい)、-느라(고) は同じ主語が意図的な行為に追われていたことを表す。',
    ),
    items: [
      {
        sentence: '앞차가 갑자기 {} 사고가 날 뻔했어요.',
        optionA: '서는 바람에',
        optionB: '서느라고',
        answer: 'a',
        trans: L(
          'The car ahead stopped suddenly, so I almost had an accident.',
          'El coche de delante frenó de golpe, así que casi tengo un accidente.',
          'La voiture devant s\'est arrêtée brusquement, j\'ai donc failli avoir un accident.',
          'O carro da frente parou de repente, então quase sofri um acidente.',
          'รถคันหน้าหยุดกะทันหัน ฉันเลยเกือบเกิดอุบัติเหตุ',
          'Mobil di depan berhenti mendadak, jadi saya nyaris kecelakaan.',
          'Xe phía trước bất ngờ dừng lại nên tôi suýt gây tai nạn.',
          '前の車が急に止まったせいで、事故を起こしそうになりました。',
        ),
        why: L(
          'The cause is a SUDDEN external action by another car (앞차), outside the speaker\'s control, so -는 바람에 fits; -느라고 needs the same subject busy with their own deliberate action, which fails here.',
          'La causa es una acción REPENTINA y externa de otro coche (앞차), fuera del control del hablante, así que va -는 바람에; -느라고 exige el mismo sujeto ocupado en su propia acción deliberada, lo que aquí no se cumple.',
          'La cause est une action SOUDAINE et externe d\'une autre voiture (앞차), hors du contrôle du locuteur, donc -는 바람에 convient ; -느라고 exige le même sujet occupé à sa propre action délibérée, ce qui échoue ici.',
          'A causa é uma ação REPENTINA e externa de outro carro (앞차), fora do controle do falante, então cabe -는 바람에; -느라고 exige o mesmo sujeito ocupado com sua própria ação deliberada, o que não se aplica aqui.',
          'เหตุคือการกระทำกะทันหันจากภายนอกของรถอีกคัน (앞차) ซึ่งอยู่นอกการควบคุมของผู้พูด จึงใช้ -는 바람에; ส่วน -느라고 ต้องเป็นประธานคนเดียวกันที่ยุ่งกับการกระทำของตนเอง ซึ่งไม่ตรงในที่นี้',
          'Penyebabnya adalah tindakan MENDADAK dan eksternal dari mobil lain (앞차), di luar kendali penutur, jadi -는 바람에 cocok; -느라고 menuntut subjek yang sama sibuk dengan tindakannya sendiri yang disengaja, yang tidak terpenuhi di sini.',
          'Nguyên nhân là hành động BẤT NGỜ từ bên ngoài của xe khác (앞차), ngoài tầm kiểm soát của người nói, nên dùng -는 바람에; -느라고 đòi cùng chủ ngữ bận với hành động có chủ ý của chính mình, không đúng ở đây.',
          '原因は別の車(앞차)の突発的・外的な動作で話者の制御外なので -는 바람에 が適切。-느라고 は同じ主語が自分の意図的行為に追われる必要があり、ここでは成立しない。',
        ),
      },
      {
        sentence: '어제 밤늦게까지 게임을 {} 숙제를 못 했어요.',
        optionA: '하는 바람에',
        optionB: '하느라고',
        answer: 'b',
        trans: L(
          'I was playing games until late last night, so I couldn\'t do my homework.',
          'Anoche estuve jugando videojuegos hasta tarde, así que no pude hacer la tarea.',
          'Hier soir j\'ai joué aux jeux vidéo jusqu\'à tard, donc je n\'ai pas pu faire mes devoirs.',
          'Ontem à noite fiquei jogando até tarde, então não consegui fazer a lição.',
          'เมื่อคืนฉันมัวเล่นเกมจนดึก เลยทำการบ้านไม่ได้',
          'Tadi malam saya asyik main game sampai larut, jadi tidak bisa mengerjakan PR.',
          'Tối qua tôi mải chơi game tới khuya nên không làm được bài tập.',
          '昨夜遅くまでゲームをしていて、宿題ができませんでした。',
        ),
        why: L(
          'The same speaker was busy with a deliberate, sustained activity (playing games) that crowded out the homework, so -느라고 fits; -는 바람에 marks a sudden uncontrollable event, which a chosen all-night activity is not.',
          'El mismo hablante estaba ocupado con una actividad deliberada y prolongada (jugar) que impidió la tarea, así que va -느라고; -는 바람에 marca un suceso repentino e incontrolable, que no es una actividad elegida toda la noche.',
          'Le même locuteur était occupé à une activité délibérée et prolongée (jouer) qui a empêché les devoirs, donc -느라고 convient ; -는 바람에 marque un événement soudain et incontrôlable, ce que n\'est pas une activité choisie toute la nuit.',
          'O mesmo falante estava ocupado com uma atividade deliberada e prolongada (jogar) que impediu a lição, então cabe -느라고; -는 바람에 marca um evento repentino e incontrolável, o que uma atividade escolhida a noite toda não é.',
          'ผู้พูดคนเดียวกันยุ่งกับกิจกรรมที่ตั้งใจและต่อเนื่อง (เล่นเกม) จนทำการบ้านไม่ได้ จึงใช้ -느라고; ส่วน -는 바람에 บอกเหตุการณ์กะทันหันที่ควบคุมไม่ได้ ซึ่งการเล่นทั้งคืนที่เลือกเองไม่ใช่',
          'Penutur yang sama sibuk dengan aktivitas yang disengaja dan berkepanjangan (main game) sehingga menghalangi PR, jadi -느라고 cocok; -는 바람에 menandai kejadian mendadak yang tak terkendali, yang bukan aktivitas semalaman yang dipilih sendiri.',
          'Cùng người nói bận với một hoạt động có chủ ý, kéo dài (chơi game) khiến không làm bài, nên dùng -느라고; -는 바람에 chỉ sự việc bất ngờ không kiểm soát được, mà hoạt động thâu đêm tự chọn thì không phải vậy.',
          '同じ話者が意図的で持続的な行為(ゲーム)に追われて宿題ができなかったので -느라고 が適切。-는 바람에 は突発的で制御できない出来事を表し、自ら選んだ夜通しの行為はそれに当たらない。',
        ),
      },
      {
        sentence: '버스가 갑자기 {} 가방에 있던 커피가 쏟아졌어요.',
        optionA: '흔들리는 바람에',
        optionB: '흔들리느라고',
        answer: 'a',
        trans: L(
          'The bus suddenly jolted, so the coffee in my bag spilled.',
          'El autobús dio una sacudida de repente, así que se derramó el café que llevaba en la bolsa.',
          'Le bus a soudain été secoué, donc le café dans mon sac s\'est renversé.',
          'O ônibus sacudiu de repente, então o café que estava na minha bolsa derramou.',
          'รถบัสสั่นกะทันหัน กาแฟที่อยู่ในกระเป๋าเลยหกออกมา',
          'Bus tiba-tiba terguncang, jadi kopi di dalam tas saya tumpah.',
          'Xe buýt bất ngờ rung lắc nên cà phê trong túi tôi bị đổ.',
          'バスが急に揺れたせいで、かばんの中のコーヒーがこぼれました。',
        ),
        why: L(
          'A bus jolting is a sudden, involuntary event (흔들리다 is intransitive, no agent intent), so -는 바람에 fits; -느라고 requires a controllable action the same subject is busy with, but a bus cannot "be busy shaking" on purpose.',
          'Que el autobús se sacuda es un suceso repentino e involuntario (흔들리다 es intransitivo, sin intención de un agente), así que va -는 바람에; -느라고 exige una acción controlable en la que el mismo sujeto está ocupado, pero un autobús no puede "estar ocupado sacudiéndose" a propósito.',
          'Le bus qui est secoué est un événement soudain et involontaire (흔들리다 est intransitif, sans intention d\'un agent), donc -는 바람에 convient ; -느라고 exige une action contrôlable dont le même sujet est occupé, mais un bus ne peut pas « être occupé à trembler » exprès.',
          'O ônibus sacudir é um evento repentino e involuntário (흔들리다 é intransitivo, sem intenção de um agente), então cabe -는 바람에; -느라고 exige uma ação controlável com a qual o mesmo sujeito está ocupado, mas um ônibus não pode "estar ocupado balançando" de propósito.',
          'การที่รถบัสสั่นเป็นเหตุการณ์กะทันหันและไม่ได้ตั้งใจ (흔들리다 เป็นอกรรมกริยา ไม่มีเจตนาของผู้กระทำ) จึงใช้ -는 바람에; ส่วน -느라고 ต้องเป็นการกระทำที่ควบคุมได้ซึ่งประธานเดียวกันยุ่งอยู่ แต่รถบัส "ยุ่งกับการสั่น" โดยตั้งใจไม่ได้',
          'Bus terguncang adalah kejadian mendadak dan tak disengaja (흔들리다 intransitif, tanpa niat pelaku), jadi -는 바람에 cocok; -느라고 menuntut tindakan terkendali yang subjek samanya sedang sibuk lakukan, tetapi bus tidak bisa "sibuk berguncang" dengan sengaja.',
          'Xe buýt rung lắc là sự việc bất ngờ, không chủ ý (흔들리다 là nội động từ, không có ý định của chủ thể) nên dùng -는 바람에; -느라고 đòi một hành động kiểm soát được mà cùng chủ ngữ đang bận làm, nhưng xe buýt không thể "bận rung lắc" một cách cố ý.',
          'バスが揺れるのは突発的で非意図的な出来事(흔들리다 は自動詞で動作主の意図がない)なので -는 바람에 が適切。-느라고 は同じ主語が従事する制御可能な行為が必要だが、バスが意図して「揺れるのに忙しい」ことはありえない。',
        ),
      },
    ],
  },
  {
    id: 'gime-gile',
    a: '-(으)ㄴ/는 김에',
    b: '-(으)ㄴ/는 길에',
    note: L(
      'These differ by one syllable and are easily mixed up. -는 김에 means "while you\'re at it / taking the opportunity of doing X" — any action becomes a chance to also do something extra ON PURPOSE. -는 길에 literally means "on the way" and ONLY attaches to motion verbs (가다/오다/나가다…): something happens DURING a physical journey, even an unplanned encounter you didn\'t choose.',
      'Se diferencian en una sílaba y se confunden con facilidad. -는 김에 significa "ya que estás / aprovechando que haces X" — cualquier acción se vuelve ocasión para hacer algo extra A PROPÓSITO. -는 길에 significa literalmente "de camino" y SOLO va con verbos de movimiento (가다/오다/나가다…): algo ocurre DURANTE un trayecto físico, incluso un encuentro imprevisto que no elegiste.',
      'Ils diffèrent d\'une syllabe et se confondent facilement. -는 김에 signifie « tant qu\'à faire / en profitant de faire X » — toute action devient l\'occasion de faire qqch en plus VOLONTAIREMENT. -는 길에 signifie littéralement « en chemin » et ne s\'attache QU\'aux verbes de mouvement (가다/오다/나가다…) : qqch survient PENDANT un trajet physique, même une rencontre imprévue non choisie.',
      'Diferem por uma sílaba e são facilmente confundidos. -는 김에 significa "já que está / aproveitando que faz X" — qualquer ação vira oportunidade de fazer algo a mais DE PROPÓSITO. -는 길에 significa literalmente "a caminho" e SÓ se liga a verbos de movimento (가다/오다/나가다…): algo acontece DURANTE um trajeto físico, até um encontro imprevisto que você não escolheu.',
      'ทั้งสองต่างกันแค่พยางค์เดียวจึงสับสนได้ง่าย -는 김에 แปลว่า "ในเมื่อ/ถือโอกาสที่ทำ X" การกระทำใดก็กลายเป็นโอกาสทำสิ่งเพิ่มโดยตั้งใจได้ ส่วน -는 길에 แปลตรงตัวว่า "ระหว่างทาง" และใช้ได้เฉพาะกับกริยาเคลื่อนที่ (가다/오다/나가다…) คือมีสิ่งหนึ่งเกิดขึ้นระหว่างการเดินทางจริง แม้แต่เหตุการณ์ที่ไม่ได้ตั้งใจ',
      'Keduanya berbeda satu suku kata dan mudah tertukar. -는 김에 berarti "mumpung / sekalian saat melakukan X" — tindakan apa pun jadi kesempatan melakukan hal tambahan DENGAN SENGAJA. -는 길에 secara harfiah berarti "di tengah jalan" dan HANYA melekat pada verba gerak (가다/오다/나가다…): sesuatu terjadi SELAMA perjalanan fisik, bahkan kejadian tak terduga yang tidak kamu pilih.',
      'Hai cấu trúc khác nhau một âm tiết nên dễ nhầm. -는 김에 nghĩa là "nhân tiện / tận dụng việc làm X" — bất kỳ hành động nào cũng thành cơ hội CHỦ Ý làm thêm việc khác. -는 길에 nghĩa đen là "trên đường" và CHỈ gắn với động từ chuyển động (가다/오다/나가다…): điều gì đó xảy ra TRONG lúc di chuyển thực sự, kể cả một sự việc bất ngờ bạn không chọn.',
      '一音節違いで混同しやすい。-는 김에 は「ついでに/Xするのを機に」の意味で、どんな動作も何かを意図的に追加する機会になる。-는 길에 は文字どおり「途中で」の意味で、移動動詞(가다/오다/나가다…)にしか付かず、実際の移動の途中に何か(自分で選んでいない不意の出来事も含む)が起こる。',
    ),
    items: [
      {
        sentence: '학교에 {} 옛날 친구를 우연히 만났어요.',
        optionA: '가는 김에',
        optionB: '가는 길에',
        answer: 'b',
        trans: L(
          'On the way to school, I ran into an old friend by chance.',
          'De camino a la escuela, me encontré por casualidad con un viejo amigo.',
          'En allant à l\'école, je suis tombé par hasard sur un vieil ami.',
          'A caminho da escola, encontrei por acaso um velho amigo.',
          'ระหว่างทางไปโรงเรียน ฉันบังเอิญเจอเพื่อนเก่า',
          'Dalam perjalanan ke sekolah, saya tak sengaja bertemu teman lama.',
          'Trên đường đến trường, tôi tình cờ gặp một người bạn cũ.',
          '学校に行く途中で、偶然昔の友達に会いました。',
        ),
        why: L(
          'Running into an old friend "by chance" (우연히) during the trip to school (가다, a motion verb) is an unplanned encounter, so -는 길에 ("on the way") fits; -는 김에 means deliberately leveraging "since I\'m going anyway, I\'ll also do Y," but a chance meeting is not a chosen extra action, so 김에 is blocked.',
          'Encontrarse "por casualidad" (우연히) con un viejo amigo durante el trayecto a la escuela (가다, verbo de movimiento) es un encuentro imprevisto, así que va -는 길에 ("de camino"); -는 김에 significa aprovechar a propósito "ya que voy, también hago Y", pero un encuentro casual no es una acción extra elegida, así que 김에 queda bloqueado.',
          'Tomber « par hasard » (우연히) sur un vieil ami pendant le trajet vers l\'école (가다, verbe de mouvement) est une rencontre imprévue, donc -는 길에 (« en chemin ») convient ; -는 김에 signifie profiter volontairement de « puisque j\'y vais, je fais aussi Y », mais une rencontre fortuite n\'est pas une action choisie, donc 김에 est bloqué.',
          'Encontrar "por acaso" (우연히) um velho amigo durante o trajeto à escola (가다, verbo de movimento) é um encontro imprevisto, então cabe -는 길에 ("a caminho"); -는 김에 significa aproveitar de propósito "já que vou, também faço Y", mas um encontro casual não é uma ação extra escolhida, então 김에 fica bloqueado.',
          'การบังเอิญ (우연히) เจอเพื่อนเก่าระหว่างเดินทางไปโรงเรียน (가다 กริยาเคลื่อนที่) เป็นการพบโดยไม่ได้ตั้งใจ จึงใช้ -는 길에 ("ระหว่างทาง"); ส่วน -는 김에 หมายถึงการตั้งใจถือโอกาส "ในเมื่อจะไปอยู่แล้วก็เลยทำ Y" แต่การเจอโดยบังเอิญไม่ใช่การกระทำที่เลือกเอง 김에 จึงใช้ไม่ได้',
          'Bertemu teman lama "secara tak sengaja" (우연히) selama perjalanan ke sekolah (가다, verba gerak) adalah perjumpaan tak terencana, jadi -는 길에 ("di tengah jalan") cocok; -는 김에 berarti dengan sengaja memanfaatkan "mumpung pergi, sekalian Y", tetapi pertemuan kebetulan bukan tindakan tambahan yang dipilih, jadi 김에 terhalang.',
          'Việc "tình cờ" (우연히) gặp bạn cũ trong lúc đến trường (가다, động từ chuyển động) là một cuộc gặp ngoài dự tính, nên dùng -는 길에 ("trên đường"); -는 김에 nghĩa là chủ ý tận dụng "đằng nào cũng đi nên làm thêm Y", nhưng gặp gỡ tình cờ không phải hành động được chọn, nên 김에 bị loại.',
          '学校へ行く途中(가다、移動動詞)で「偶然(우연히)」昔の友達に会うのは予期しない出来事なので -는 길에(「途中で」)が適切。-는 김에 は「どうせ行くついでに意図的にYもする」という意味で、偶然の出会いは選んだ行為ではないため 김에 は使えない。',
        ),
      },
      {
        sentence: '설거지를 {} 가스레인지도 닦았어요.',
        optionA: '하는 김에',
        optionB: '하는 길에',
        answer: 'a',
        trans: L(
          'While I was doing the dishes, I also wiped down the stove.',
          'Ya que estaba lavando los platos, también limpié la cocina de gas.',
          'Tant qu\'à faire la vaisselle, j\'ai aussi nettoyé la gazinière.',
          'Já que estava lavando a louça, também limpei o fogão.',
          'ถือโอกาสที่ล้างจาน ฉันก็เลยเช็ดเตาแก๊สด้วย',
          'Mumpung sedang mencuci piring, saya sekalian membersihkan kompor.',
          'Nhân tiện rửa bát, tôi lau luôn cả bếp ga.',
          '皿洗いをするついでにガスコンロも拭きました。',
        ),
        why: L(
          'Washing dishes (하다) is NOT a motion verb and there is no journey, so only -는 김에 ("while at it") works; -는 길에 is impossible because it requires a movement verb and a physical route.',
          'Lavar los platos (하다) NO es un verbo de movimiento y no hay trayecto, así que solo funciona -는 김에 ("ya que estás"); -는 길에 es imposible porque exige un verbo de movimiento y una ruta física.',
          'Faire la vaisselle (하다) n\'est PAS un verbe de mouvement et il n\'y a pas de trajet, donc seul -는 김에 (« tant qu\'à faire ») marche ; -는 길에 est impossible car il exige un verbe de mouvement et un trajet physique.',
          'Lavar a louça (하다) NÃO é verbo de movimento e não há trajeto, então só -는 김에 ("já que está") funciona; -는 길에 é impossível porque exige verbo de movimento e uma rota física.',
          'การล้างจาน (하다) ไม่ใช่กริยาเคลื่อนที่และไม่มีการเดินทาง จึงใช้ได้แค่ -는 김에 ("ในเมื่อทำอยู่แล้ว"); ส่วน -는 길에 ใช้ไม่ได้เพราะต้องมีกริยาเคลื่อนที่และเส้นทางจริง',
          'Mencuci piring (하다) BUKAN verba gerak dan tidak ada perjalanan, jadi hanya -는 김에 ("mumpung") yang cocok; -는 길에 mustahil karena menuntut verba gerak dan rute fisik.',
          'Rửa bát (하다) KHÔNG phải động từ chuyển động và không có chuyến đi, nên chỉ -는 김에 ("nhân tiện") dùng được; -는 길에 không thể vì đòi động từ chuyển động và một lộ trình thực sự.',
          '皿洗い(하다)は移動動詞ではなく移動もないので -는 김에(「ついでに」)しか使えない。-는 길에 は移動動詞と実際の経路が必要なため不可能。',
        ),
      },
      {
        sentence: '집에 {} 갑자기 비가 쏟아져서 옷이 다 젖었어요.',
        optionA: '오는 김에',
        optionB: '오는 길에',
        answer: 'b',
        trans: L(
          'On the way home, it suddenly poured and my clothes got soaked.',
          'De camino a casa, de repente se puso a diluviar y se me empapó la ropa.',
          'Sur le chemin du retour, il s\'est soudain mis à pleuvoir à verse et mes vêtements ont été trempés.',
          'Na volta para casa, de repente caiu um toró e minha roupa ficou encharcada.',
          'ระหว่างทางกลับบ้าน จู่ ๆ ฝนก็เทลงมา เสื้อผ้าเลยเปียกหมด',
          'Dalam perjalanan pulang, tiba-tiba hujan deras dan baju saya basah kuyup.',
          'Trên đường về nhà, trời bất ngờ đổ mưa to nên quần áo tôi ướt hết.',
          '家に帰る途中で急に大雨が降って、服がびしょ濡れになりました。',
        ),
        why: L(
          'Getting caught in a sudden downpour happens DURING the trip home (오다, a motion verb) and is an involuntary event, so -는 길에 ("on the way") fits; -는 김에 needs a deliberate extra action you choose to do, but being rained on is nothing you leverage or choose, so 김에 is impossible.',
          'Que te pille un aguacero repentino ocurre DURANTE el regreso a casa (오다, verbo de movimiento) y es un suceso involuntario, así que va -는 길에 ("de camino"); -는 김에 exige una acción extra deliberada que decides hacer, pero mojarse con la lluvia no es algo que aproveches o elijas, así que 김에 es imposible.',
          'Se faire surprendre par une averse soudaine se produit PENDANT le retour à la maison (오다, verbe de mouvement) et est un événement involontaire, donc -는 길에 (« en chemin ») convient ; -는 김에 exige une action volontaire que l\'on choisit de faire, mais être trempé par la pluie n\'est ni un avantage ni un choix, donc 김에 est impossible.',
          'Ser pego por um toró repentino acontece DURANTE a volta para casa (오다, verbo de movimento) e é um evento involuntário, então cabe -는 길에 ("a caminho"); -는 김에 exige uma ação extra deliberada que você escolhe fazer, mas tomar chuva não é algo que se aproveite ou escolha, então 김에 é impossível.',
          'การโดนฝนเทกะทันหันเกิดขึ้นระหว่างทางกลับบ้าน (오다 กริยาเคลื่อนที่) และเป็นเหตุการณ์ที่ไม่ได้ตั้งใจ จึงใช้ -는 길에 ("ระหว่างทาง"); ส่วน -는 김에 ต้องเป็นการกระทำเพิ่มที่ตั้งใจเลือกทำ แต่การโดนฝนไม่ใช่สิ่งที่ถือโอกาสหรือเลือกได้ 김에 จึงใช้ไม่ได้',
          'Kehujanan deras mendadak terjadi SELAMA perjalanan pulang (오다, verba gerak) dan merupakan kejadian tak disengaja, jadi -는 길에 ("di tengah jalan") cocok; -는 김에 menuntut tindakan tambahan yang sengaja kamu pilih, tetapi kehujanan bukan sesuatu yang dimanfaatkan atau dipilih, jadi 김에 mustahil.',
          'Việc bị mắc mưa lớn bất ngờ xảy ra TRONG lúc về nhà (오다, động từ chuyển động) và là sự việc không chủ ý, nên dùng -는 길에 ("trên đường"); -는 김에 cần một hành động thêm có chủ ý mà bạn chọn làm, nhưng bị mưa dội không phải điều bạn tận dụng hay lựa chọn, nên 김에 không thể dùng.',
          '急な大雨に降られるのは家へ帰る途中(오다、移動動詞)で起こる非意図的な出来事なので -는 길에(「途中で」)が適切。-는 김에 は自分で選んで行う意図的な追加行為が必要だが、雨に降られるのは利用も選択もできないため 김에 は使えない。',
        ),
      },
    ],
  },
]
