import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK 4 confusable grammar/ending pairs. a/b match grammars-n*.ts kos
 * verbatim. Each pair: a contrast note + 3 single-answer discrimination items,
 * 8-locale note/trans/why.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow
 * (single-correct-answer crux, naturalness, conjugation, 8-locale fidelity).
 * Native (Korean wife) review is the documented final gate.
 */
export const N4_PAIRS: ConfusablePair[] = [
  {
    id: 'dago-nyago',
    a: '-다고 하다',
    b: '-냐고 하다 / -(으)냐고 묻다',
    note: L(
      'Use -다고 하다 to report someone\'s STATEMENT (a declarative: "X said that..."), and -냐고 하다 / -(으)냐고 묻다 to report someone\'s QUESTION ("X asked whether..."). Decide by whether the original utterance was a statement or a question — a question word (어디, 언제) or a reporting verb like 묻다/물어보다 signals the -냐고 question form.',
      'Usá -다고 하다 para reportar la AFIRMACIÓN de alguien (un declarativo: "X dijo que..."), y -냐고 하다 / -(으)냐고 묻다 para reportar la PREGUNTA de alguien ("X preguntó si..."). Decidí según si el enunciado original fue una afirmación o una pregunta: una palabra interrogativa (어디, 언제) o un verbo de reporte como 묻다/물어보다 indican la forma de pregunta -냐고.',
      'Utilise -다고 하다 pour rapporter la DÉCLARATION de quelqu\'un (un déclaratif : « X a dit que... »), et -냐고 하다 / -(으)냐고 묻다 pour rapporter la QUESTION de quelqu\'un (« X a demandé si... »). Décide selon que l\'énoncé d\'origine était une affirmation ou une question : un mot interrogatif (어디, 언제) ou un verbe de rapport comme 묻다/물어보다 signale la forme interrogative -냐고.',
      'Use -다고 하다 para relatar a AFIRMAÇÃO de alguém (um declarativo: "X disse que..."), e -냐고 하다 / -(으)냐고 묻다 para relatar a PERGUNTA de alguém ("X perguntou se..."). Decida pelo fato de o enunciado original ter sido uma afirmação ou uma pergunta: uma palavra interrogativa (어디, 언제) ou um verbo de relato como 묻다/물어보다 sinaliza a forma de pergunta -냐고.',
      'ใช้ -다고 하다 เพื่อรายงานคำบอกเล่า (statement) ของใครบางคน (รูปบอกเล่า: "X พูดว่า...") และใช้ -냐고 하다 / -(으)냐고 묻다 เพื่อรายงานคำถามของใครบางคน ("X ถามว่า...") ตัดสินใจโดยดูว่าคำพูดต้นฉบับเป็นคำบอกเล่าหรือคำถาม คำคำถาม (어디, 언제) หรือคำกริยาที่ใช้รายงานอย่าง 묻다/물어보다 เป็นสัญญาณบอกว่าใช้รูปคำถาม -냐고',
      'Gunakan -다고 하다 untuk melaporkan PERNYATAAN seseorang (deklaratif: "X berkata bahwa..."), dan -냐고 하다 / -(으)냐고 묻다 untuk melaporkan PERTANYAAN seseorang ("X bertanya apakah..."). Tentukan berdasarkan apakah ucapan aslinya berupa pernyataan atau pertanyaan: kata tanya (어디, 언제) atau verba pelaporan seperti 묻다/물어보다 menandakan bentuk pertanyaan -냐고.',
      'Dùng -다고 하다 để tường thuật LỜI KHẲNG ĐỊNH của ai đó (dạng trần thuật: "X nói rằng..."), và -냐고 하다 / -(으)냐고 묻다 để tường thuật CÂU HỎI của ai đó ("X hỏi liệu..."). Quyết định dựa trên việc lời nói gốc là một câu khẳng định hay một câu hỏi: từ để hỏi (어디, 언제) hoặc động từ tường thuật như 묻다/물어보다 báo hiệu dạng câu hỏi -냐고.',
      '誰かの「発言」（叙述：「Xが〜と言った」）を伝えるには -다고 하다 を使い、誰かの「質問」（「Xが〜かと尋ねた」）を伝えるには -냐고 하다 / -(으)냐고 묻다 を使う。元の発話が叙述だったか質問だったかで判断する。疑問詞（어디、언제）や 묻다/물어보다 のような伝達動詞は、質問形の -냐고 を示すサインである。',
    ),
    items: [
      {
        sentence: '수민 씨가 내일 회의에 {} 했어요.',
        optionA: '온다고',
        optionB: '오냐고',
        answer: 'a',
        trans: L(
          'Sumin said she\'s coming to the meeting tomorrow.',
          'Sumin dijo que mañana viene a la reunión.',
          'Sumin a dit qu\'elle vient à la réunion demain.',
          'Sumin disse que vem à reunião amanhã.',
          'ซูมินบอกว่าพรุ่งนี้เธอจะมาประชุม',
          'Sumin bilang dia akan datang ke rapat besok.',
          'Sumin nói rằng ngày mai cô ấy sẽ đến cuộc họp.',
          'スミンは明日会議に来ると言った。',
        ),
        why: L(
          'It reports Sumin\'s STATEMENT about coming, so the declarative -다고 (온다고) fits; -냐고 (오냐고) would mean she ASKED whether someone is coming, which makes no sense here.',
          'Reporta una AFIRMACIÓN de Sumin sobre venir, así que encaja el declarativo -다고 (온다고); -냐고 (오냐고) significaría que ella PREGUNTÓ si alguien viene, lo cual no tiene sentido acá.',
          'Cela rapporte une DÉCLARATION de Sumin à propos de sa venue, donc le déclaratif -다고 (온다고) convient ; -냐고 (오냐고) signifierait qu\'elle a DEMANDÉ si quelqu\'un vient, ce qui n\'a pas de sens ici.',
          'Relata uma AFIRMAÇÃO de Sumin sobre vir, então o declarativo -다고 (온다고) se encaixa; -냐고 (오냐고) significaria que ela PERGUNTOU se alguém vem, o que não faz sentido aqui.',
          'ประโยคนี้รายงานคำบอกเล่า (statement) ของซูมินเกี่ยวกับการมา จึงใช้รูปบอกเล่า -다고 (온다고) ได้เหมาะสม ส่วน -냐고 (오냐고) จะหมายความว่าเธอถามว่ามีใครมาหรือไม่ ซึ่งไม่สมเหตุสมผลในที่นี้',
          'Ini melaporkan PERNYATAAN Sumin tentang akan datang, jadi bentuk deklaratif -다고 (온다고) cocok; -냐고 (오냐고) berarti dia BERTANYA apakah seseorang datang, yang tidak masuk akal di sini.',
          'Câu này tường thuật một LỜI KHẲNG ĐỊNH của Sumin về việc đến, nên dạng trần thuật -다고 (온다고) là phù hợp; -냐고 (오냐고) sẽ có nghĩa là cô ấy HỎI liệu có ai đến không, điều này vô nghĩa ở đây.',
          'これはスミンの「来る」という発言（叙述文）を伝えているので、叙述形の -다고 (온다고) が合う。-냐고 (오냐고) だと誰かが来るかどうかを「尋ねた」という意味になり、ここでは意味をなさない。',
        ),
      },
      {
        sentence: '친구가 나한테 지금 어디에 {} 물었어요.',
        optionA: '있다고',
        optionB: '있냐고',
        answer: 'b',
        trans: L(
          'My friend asked me where I am right now.',
          'Mi amigo me preguntó dónde estoy ahora mismo.',
          'Mon ami m\'a demandé où je suis en ce moment.',
          'Meu amigo me perguntou onde eu estou agora.',
          'เพื่อนของฉันถามฉันว่าตอนนี้ฉันอยู่ที่ไหน',
          'Temanku bertanya kepadaku di mana aku sekarang.',
          'Bạn tôi hỏi tôi bây giờ tôi đang ở đâu.',
          '友達が私に今どこにいるのか尋ねた。',
        ),
        why: L(
          'With 물었어요 (asked) and the question word 어디, it reports a QUESTION, so -냐고 (있냐고) is required; 묻다 cannot take a declarative -다고 complement, so 있다고 is ungrammatical here.',
          'Con 물었어요 (preguntó) y la palabra interrogativa 어디, reporta una PREGUNTA, así que se requiere -냐고 (있냐고); 묻다 no puede tomar un complemento declarativo -다고, por eso 있다고 es agramatical acá.',
          'Avec 물었어요 (a demandé) et le mot interrogatif 어디, cela rapporte une QUESTION, donc -냐고 (있냐고) est requis ; 묻다 ne peut pas prendre un complément déclaratif -다고, c\'est pourquoi 있다고 est agrammatical ici.',
          'Com 물었어요 (perguntou) e a palavra interrogativa 어디, relata uma PERGUNTA, então -냐고 (있냐고) é exigido; 묻다 não pode receber um complemento declarativo -다고, por isso 있다고 é agramatical aqui.',
          'เมื่อมี 물었어요 (ถาม) และคำคำถาม 어디 ประโยคนี้รายงานคำถาม จึงต้องใช้ -냐고 (있냐고); 묻다 ไม่สามารถรับส่วนเติมเต็มแบบบอกเล่า -다고 ได้ ดังนั้น 있다고 จึงผิดไวยากรณ์ในที่นี้',
          'Dengan 물었어요 (bertanya) dan kata tanya 어디, ini melaporkan PERTANYAAN, jadi -냐고 (있냐고) diperlukan; 묻다 tidak bisa mengambil komplemen deklaratif -다고, sehingga 있다고 tidak gramatikal di sini.',
          'Với 물었어요 (đã hỏi) và từ để hỏi 어디, câu này tường thuật một CÂU HỎI, nên cần dùng -냐고 (있냐고); 묻다 không thể nhận bổ ngữ trần thuật -다고, vì vậy 있다고 là sai ngữ pháp ở đây.',
          '물었어요（尋ねた）と疑問詞 어디 があるため、これは「質問」を伝えている。したがって -냐고 (있냐고) が必要。묻다 は叙述形の補文 -다고 を取れないので、ここで 있다고 は非文法的である。',
        ),
      },
      {
        sentence: '의사 선생님이 어제부터 많이 {} 물어보셨어요.',
        optionA: '아프다고',
        optionB: '아프냐고',
        answer: 'b',
        trans: L(
          'The doctor asked whether it has been hurting a lot since yesterday.',
          'El doctor preguntó si me dolía mucho desde ayer.',
          'Le médecin a demandé si ça faisait très mal depuis hier.',
          'O médico perguntou se estava doendo muito desde ontem.',
          'หมอถามว่าตั้งแต่เมื่อวานเจ็บมากไหม',
          'Dokter bertanya apakah sudah sangat sakit sejak kemarin.',
          'Bác sĩ hỏi liệu từ hôm qua có đau nhiều không.',
          '医者は昨日からとても痛むのか尋ねた。',
        ),
        why: L(
          '물어보셨어요 (asked) signals a reported QUESTION, so the adjective takes -냐고 (아프냐고); 묻다/물어보다 cannot take a declarative -다고 complement, so 아프다고 is ungrammatical here.',
          '물어보셨어요 (preguntó) señala una PREGUNTA reportada, así que el adjetivo toma -냐고 (아프냐고); 묻다/물어보다 no pueden tomar un complemento declarativo -다고, por eso 아프다고 es agramatical acá.',
          '물어보셨어요 (a demandé) signale une QUESTION rapportée, donc l\'adjectif prend -냐고 (아프냐고) ; 묻다/물어보다 ne peuvent pas prendre un complément déclaratif -다고, c\'est pourquoi 아프다고 est agrammatical ici.',
          '물어보셨어요 (perguntou) sinaliza uma PERGUNTA relatada, então o adjetivo recebe -냐고 (아프냐고); 묻다/물어보다 não podem receber um complemento declarativo -다고, por isso 아프다고 é agramatical aqui.',
          '물어보셨어요 (ถาม) บ่งบอกว่าเป็นคำถามที่ถูกรายงาน คำคุณศัพท์จึงใช้ -냐고 (아프냐고); 묻다/물어보다 ไม่สามารถรับส่วนเติมเต็มแบบบอกเล่า -다고 ได้ ดังนั้น 아프다고 จึงผิดไวยากรณ์ในที่นี้',
          '물어보셨어요 (bertanya) menandakan PERTANYAAN yang dilaporkan, jadi kata sifat mengambil -냐고 (아프냐고); 묻다/물어보다 tidak bisa mengambil komplemen deklaratif -다고, sehingga 아프다고 tidak gramatikal di sini.',
          '물어보셨어요 (đã hỏi) báo hiệu một CÂU HỎI được tường thuật, nên tính từ dùng -냐고 (아프냐고); 묻다/물어보다 không thể nhận bổ ngữ trần thuật -다고, vì vậy 아프다고 là sai ngữ pháp ở đây.',
          '물어보셨어요（尋ねた）は伝聞の「質問」を示すため、形容詞は -냐고 (아프냐고) を取る。묻다/물어보다 は叙述形の補文 -다고 を取れないので、ここで 아프다고 は非文法的である。',
        ),
      },
    ],
  },
  {
    id: 'tende-tenikka',
    a: '-(으)ㄹ 텐데',
    b: '-(으)ㄹ 테니까',
    note: L(
      'Both express the speaker\'s supposition ("X probably will/does..."). Use -(으)ㄹ 텐데 when the next clause is a contrasting remark or concern that reacts to that supposition (often a contrary fact, no request follows); use -(으)ㄹ 테니까 when the supposition — especially the speaker\'s own intended action — is given as the reason/basis for a following request, command, or plan.',
      'Ambos expresan la suposición del hablante ("X probablemente va a/hace..."). Usá -(으)ㄹ 텐데 cuando la cláusula siguiente es un comentario o una preocupación contrastantes que reaccionan a esa suposición (a menudo un hecho contrario, sin que siga un pedido); usá -(으)ㄹ 테니까 cuando la suposición —sobre todo la acción que el propio hablante piensa hacer— se da como la razón o base de un pedido, una orden o un plan que vienen a continuación.',
      'Les deux expriment la supposition du locuteur (« X va probablement.../fait probablement... »). Emploie -(으)ㄹ 텐데 quand la proposition suivante est une remarque ou une inquiétude contrastante qui réagit à cette supposition (souvent un fait contraire, sans demande qui suive) ; emploie -(으)ㄹ 테니까 quand la supposition — surtout l\'action que le locuteur lui-même compte faire — sert de raison ou de base à une demande, un ordre ou un plan qui suit.',
      'Ambos expressam a suposição do falante ("X provavelmente vai/faz..."). Use -(으)ㄹ 텐데 quando a oração seguinte for um comentário ou preocupação contrastante que reage a essa suposição (muitas vezes um fato contrário, sem pedido em seguida); use -(으)ㄹ 테니까 quando a suposição — sobretudo a ação que o próprio falante pretende fazer — for dada como a razão ou base de um pedido, ordem ou plano que vem a seguir.',
      'ทั้งสองแบบแสดงการสันนิษฐานของผู้พูด ("X คงจะ/น่าจะ...") ใช้ -(으)ㄹ 텐데 เมื่ออนุประโยคถัดไปเป็นความเห็นหรือความกังวลที่ขัดแย้งซึ่งตอบสนองต่อการสันนิษฐานนั้น (มักเป็นข้อเท็จจริงที่ตรงกันข้าม และไม่มีคำขอตามมา) ใช้ -(으)ㄹ 테니까 เมื่อการสันนิษฐานนั้น —โดยเฉพาะการกระทำที่ผู้พูดตั้งใจจะทำเอง— ถูกใช้เป็นเหตุผลหรือพื้นฐานของคำขอ คำสั่ง หรือแผนที่ตามมา',
      'Keduanya mengungkapkan dugaan penutur ("X mungkin akan/biasanya..."). Gunakan -(으)ㄹ 텐데 ketika klausa berikutnya adalah komentar atau kekhawatiran yang berlawanan yang menanggapi dugaan itu (sering kali fakta yang bertentangan, tanpa permintaan setelahnya); gunakan -(으)ㄹ 테니까 ketika dugaan itu — terutama tindakan yang penutur sendiri berniat lakukan — diberikan sebagai alasan atau dasar bagi permintaan, perintah, atau rencana yang menyusul.',
      'Cả hai đều diễn tả sự suy đoán của người nói ("X chắc sẽ/thường..."). Dùng -(으)ㄹ 텐데 khi mệnh đề tiếp theo là một nhận xét hoặc mối lo ngại trái ngược phản ứng lại sự suy đoán đó (thường là một sự thật trái ngược, không có lời nhờ theo sau); dùng -(으)ㄹ 테니까 khi sự suy đoán — nhất là hành động mà chính người nói dự định làm — được đưa ra làm lý do hoặc cơ sở cho một lời nhờ, mệnh lệnh, hay kế hoạch theo sau.',
      'どちらも話し手の推測（「Xはきっと～だろう／するだろう」）を表す。-(으)ㄹ 텐데 は、次の節がその推測に反応する対照的な発言や懸念（多くは反対の事実で、依頼は続かない）であるときに使う。-(으)ㄹ 테니까 は、推測—とりわけ話し手自身がしようとしている行動—が、続く依頼・命令・計画の理由や根拠として示されるときに使う。',
    ),
    items: [
      {
        sentence: '제가 음식을 준비{} 너는 그냥 와서 먹기만 해.',
        optionA: '할 텐데',
        optionB: '할 테니까',
        answer: 'b',
        trans: L(
          'I\'ll prepare the food, so you just come and eat.',
          'Yo preparo la comida, así que vos solo vení y comé.',
          'Je prépare le repas, alors viens juste manger.',
          'Eu preparo a comida, então você só vem e come.',
          'เดี๋ยวฉันเตรียมอาหารเอง เพราะฉะนั้นเธอแค่มากินก็พอ',
          'Aku yang menyiapkan makanannya, jadi kamu tinggal datang dan makan saja.',
          'Để tôi chuẩn bị đồ ăn, nên bạn cứ đến và ăn thôi.',
          '私が料理を用意しておくから、あなたはただ来て食べればいいよ。',
        ),
        why: L(
          '테니까 fits because the speaker\'s own planned action (I\'ll prepare it) is the basis for an instruction (just come and eat); 할 텐데 would need a contrasting remark or concern, not a command, after it.',
          '테니까 encaja porque la acción que el propio hablante planea (yo la preparo) es la base de una instrucción (solo vení y comé); 할 텐데 necesitaría después un comentario o una preocupación contrastantes, no una orden.',
          '테니까 convient car l\'action que le locuteur lui-même prévoit (je la prépare) sert de base à une instruction (viens juste manger) ; 할 텐데 exigerait ensuite une remarque ou une inquiétude contrastante, pas un ordre.',
          '테니까 se encaixa porque a ação que o próprio falante planeja (eu preparo) é a base de uma instrução (só vem e come); 할 텐데 exigiria depois um comentário ou preocupação contrastante, não uma ordem.',
          '테니까 เหมาะ เพราะการกระทำที่ผู้พูดวางแผนเอง (ฉันจะเตรียมเอง) เป็นพื้นฐานของคำสั่ง (แค่มากิน); ส่วน 할 텐데 ต้องตามด้วยความเห็นหรือความกังวลที่ขัดแย้ง ไม่ใช่คำสั่ง',
          '테니까 cocok karena tindakan yang direncanakan penutur sendiri (aku akan menyiapkannya) menjadi dasar bagi sebuah perintah (tinggal datang dan makan); 할 텐데 akan butuh komentar atau kekhawatiran yang berlawanan setelahnya, bukan perintah.',
          '테니까 phù hợp vì hành động mà chính người nói dự định (tôi sẽ chuẩn bị) là cơ sở cho một mệnh lệnh (cứ đến và ăn); 할 텐데 sẽ cần một nhận xét hoặc mối lo ngại trái ngược theo sau, chứ không phải một mệnh lệnh.',
          '테니까 が合うのは、話し手自身が計画している行動（私が用意する）が指示（ただ来て食べて）の根拠になっているから。할 텐데 だとその後に対照的な発言や懸念が必要で、命令は来ない。',
        ),
      },
      {
        sentence: '날씨가 많이 추{} 코트도 안 입고 나갔어요.',
        optionA: '울 텐데',
        optionB: '울 테니까',
        answer: 'a',
        trans: L(
          'It\'s probably really cold out, yet he went out without even a coat.',
          'Seguramente afuera hace mucho frío, y sin embargo él salió sin siquiera un abrigo.',
          'Il fait sûrement très froid dehors, et pourtant il est sorti sans même un manteau.',
          'Lá fora deve estar bem frio, mesmo assim ele saiu sem nem um casaco.',
          'ข้างนอกคงหนาวมากแน่ๆ แต่เขากลับออกไปโดยไม่ใส่แม้แต่เสื้อโค้ท',
          'Di luar pasti sangat dingin, tapi dia malah keluar tanpa mantel sama sekali.',
          'Bên ngoài chắc lạnh lắm, vậy mà anh ấy lại ra ngoài mà chẳng có cả áo khoác.',
          '外はきっととても寒いだろうに、彼はコートも着ずに出かけた。',
        ),
        why: L(
          '춥다 → 추울; 텐데 fits because the second clause is a contrasting remark (he did the opposite of what the supposition warrants). 테니까 would make it a reason for the following action, but going out coatless contradicts \'it\'ll be cold,\' so 테니까 is illogical here — only 텐데 has one valid reading.',
          '춥다 → 추울; 텐데 encaja porque la segunda cláusula es un comentario contrastante (hizo lo contrario de lo que sugiere la suposición). 테니까 lo convertiría en razón de la acción siguiente, pero salir sin abrigo contradice \'hará frío\', así que 테니까 es ilógico acá: solo 텐데 tiene una lectura válida.',
          '춥다 → 추울 ; 텐데 convient car la deuxième proposition est une remarque contrastante (il a fait l\'inverse de ce que la supposition laisse attendre). 테니까 en ferait la raison de l\'action suivante, mais sortir sans manteau contredit « il fera froid », donc 테니까 est illogique ici : seul 텐데 a une lecture valable.',
          '춥다 → 추울; 텐데 se encaixa porque a segunda oração é um comentário contrastante (ele fez o oposto do que a suposição indicaria). 테니까 tornaria isso a razão para a ação seguinte, mas sair sem casaco contradiz \'vai estar frio\', então 테니까 é ilógico aqui: só 텐데 tem uma leitura válida.',
          '춥다 → 추울; 텐데 เหมาะ เพราะอนุประโยคที่สองเป็นความเห็นที่ขัดแย้ง (เขาทำตรงข้ามกับสิ่งที่การสันนิษฐานบ่งบอก) ส่วน 테니까 จะทำให้กลายเป็นเหตุผลของการกระทำที่ตามมา แต่การออกไปโดยไม่ใส่โค้ทขัดกับ \'มันจะหนาว\' ดังนั้น 테니까 จึงไม่สมเหตุสมผลตรงนี้ มีแต่ 텐데 ที่อ่านได้อย่างถูกต้องทางเดียว',
          '춥다 → 추울; 텐데 cocok karena klausa kedua adalah komentar yang berlawanan (dia melakukan kebalikan dari yang seharusnya menurut dugaan itu). 테니까 akan menjadikannya alasan untuk tindakan berikutnya, tapi keluar tanpa mantel bertentangan dengan \'pasti dingin\', jadi 테니까 tidak logis di sini: hanya 텐데 yang punya satu pembacaan yang valid.',
          '춥다 → 추울; 텐데 phù hợp vì mệnh đề thứ hai là một nhận xét trái ngược (anh ấy làm điều ngược lại với điều mà suy đoán gợi ý). 테니까 sẽ biến nó thành lý do cho hành động tiếp theo, nhưng ra ngoài không áo khoác lại mâu thuẫn với \'trời sẽ lạnh\', nên 테니까 phi logic ở đây: chỉ 텐데 mới có một cách hiểu hợp lệ.',
          '춥다 → 추울；텐데 が合うのは、後の節が対照的な発言だから（彼は推測が示すのと逆のことをした）。테니까 だと続く行動の理由になるが、コートなしで出かけるのは『寒いだろう』と矛盾するので、ここでは 테니까 は非論理的で、텐데 だけが妥当な解釈を持つ。',
        ),
      },
      {
        sentence: '제가 먼저 가 있{} 너는 천천히 따라와.',
        optionA: '을 텐데',
        optionB: '을 테니까',
        answer: 'b',
        trans: L(
          'I\'ll be there ahead of you, so you take your time and follow.',
          'Yo voy a llegar antes que vos, así que tomate tu tiempo y seguime.',
          'J\'arriverai avant toi, alors prends ton temps et suis-moi.',
          'Eu vou chegar antes de você, então vá com calma e me siga.',
          'เดี๋ยวฉันไปถึงก่อนเธอเอง เพราะฉะนั้นเธอค่อยๆ ตามมาก็ได้',
          'Aku akan sampai duluan, jadi kamu santai saja dan ikuti dari belakang.',
          'Tôi sẽ đến đó trước, nên bạn cứ thong thả rồi đi theo sau.',
          '私が先に着いておくから、あなたはゆっくり後から来て。',
        ),
        why: L(
          '테니까 fits because the speaker\'s own volitional plan (I\'ll go ahead) grounds a request (take your time and follow). 텐데 expresses conjecture about uncontrollable facts, not the speaker\'s own intended action used as a basis for a command, so 을 텐데 is unnatural here.',
          '테니까 encaja porque el plan volitivo del propio hablante (yo voy adelante) sustenta un pedido (tomate tu tiempo y seguime). 텐데 expresa conjetura sobre hechos incontrolables, no la acción que el propio hablante intenta usada como base de una orden, así que 을 텐데 suena poco natural acá.',
          '테니까 convient car le projet volontaire du locuteur lui-même (je pars devant) fonde une demande (prends ton temps et suis-moi). 텐데 exprime une conjecture sur des faits incontrôlables, pas l\'action que le locuteur lui-même prévoit utilisée comme base d\'un ordre, donc 을 텐데 sonne peu naturel ici.',
          '테니까 se encaixa porque o plano volitivo do próprio falante (eu vou na frente) fundamenta um pedido (vá com calma e me siga). 텐데 expressa conjectura sobre fatos incontroláveis, não a ação que o próprio falante pretende usada como base de uma ordem, então 을 텐데 soa pouco natural aqui.',
          '테니까 เหมาะ เพราะแผนตามเจตนาของผู้พูดเอง (ฉันจะไปก่อน) เป็นพื้นฐานของคำขอ (ค่อยๆ ตามมา) ส่วน 텐데 แสดงการคาดเดาเกี่ยวกับสิ่งที่ควบคุมไม่ได้ ไม่ใช่การกระทำที่ผู้พูดตั้งใจเองมาใช้เป็นพื้นฐานของคำสั่ง ดังนั้น 을 텐데 จึงฟังดูไม่เป็นธรรมชาติตรงนี้',
          '테니까 cocok karena rencana kehendak penutur sendiri (aku duluan) menjadi landasan sebuah permintaan (santai saja dan ikuti). 텐데 mengungkapkan dugaan atas hal-hal yang tak terkendali, bukan tindakan yang penutur sendiri niatkan untuk dijadikan dasar perintah, jadi 을 텐데 terdengar tidak alami di sini.',
          '테니까 phù hợp vì kế hoạch chủ ý của chính người nói (tôi đi trước) làm cơ sở cho một lời nhờ (cứ thong thả rồi đi theo). 텐데 diễn tả phỏng đoán về những điều không kiểm soát được, chứ không phải hành động mà chính người nói dự định dùng làm cơ sở cho mệnh lệnh, nên 을 텐데 nghe không tự nhiên ở đây.',
          '테니까 が合うのは、話し手自身の意志的な計画（私が先に行く）が依頼（ゆっくり後から来て）を支えているから。텐데 は制御できない事柄についての推量を表し、話し手自身が意図する行動を命令の根拠にするものではないので、ここでは 을 텐데 は不自然。',
        ),
      },
    ],
  },
  {
    id: 'ppunman-dedaga',
    a: '-(으)ㄹ 뿐만 아니라',
    b: '-(으)ㄴ/는 데다가',
    note: L(
      'Use -(으)ㄹ 뿐만 아니라 for "not only X but also Y," where X is presented as one notable point and Y is added as a further (often evaluative, more formal) point — it does not require X and Y to be the same kind of circumstance. Use -(으)ㄴ/는 데다가 to pile one more circumstance of the SAME tendency onto another ("on top of X, also Y"); it is conversational and strongly prefers the two clauses to push in the same direction (both good, or both bad). 데다가 sounds wrong when the added clause is unconnected/opposite in direction, and 뿐만 아니라 sounds stiff when you are merely listing same-direction misfortunes piling up.',
      'Usá -(으)ㄹ 뿐만 아니라 para "no solo X sino también Y", donde X se presenta como un punto notable e Y se agrega como un punto adicional (a menudo evaluativo, más formal); no requiere que X e Y sean el mismo tipo de circunstancia. Usá -(으)ㄴ/는 데다가 para amontonar una circunstancia más de la MISMA tendencia sobre otra ("encima de X, también Y"); es conversacional y prefiere fuertemente que las dos cláusulas empujen en la misma dirección (ambas buenas, o ambas malas). 데다가 suena mal cuando la cláusula agregada no está conectada o va en dirección opuesta, y 뿐만 아니라 suena rígido cuando solo estás enumerando desgracias de la misma dirección que se acumulan.',
      'Utilise -(으)ㄹ 뿐만 아니라 pour "non seulement X mais aussi Y", où X est présenté comme un point notable et Y est ajouté comme un point supplémentaire (souvent évaluatif, plus formel) ; cela n\'exige pas que X et Y soient le même type de circonstance. Utilise -(으)ㄴ/는 데다가 pour empiler une circonstance de plus de la MÊME tendance sur une autre ("en plus de X, aussi Y") ; c\'est conversationnel et cela préfère fortement que les deux propositions aillent dans la même direction (les deux bonnes, ou les deux mauvaises). 데다가 sonne mal quand la proposition ajoutée n\'est pas liée ou va en direction opposée, et 뿐만 아니라 sonne rigide quand tu ne fais qu\'énumérer des malheurs de même direction qui s\'accumulent.',
      'Use -(으)ㄹ 뿐만 아니라 para "não só X mas também Y", em que X é apresentado como um ponto notável e Y é acrescentado como um ponto adicional (muitas vezes avaliativo, mais formal); não exige que X e Y sejam o mesmo tipo de circunstância. Use -(으)ㄴ/는 데다가 para empilhar mais uma circunstância da MESMA tendência sobre outra ("em cima de X, também Y"); é coloquial e prefere fortemente que as duas orações empurrem na mesma direção (ambas boas, ou ambas ruins). 데다가 soa errado quando a oração acrescentada é desconexa ou de direção oposta, e 뿐만 아니라 soa rígido quando você está apenas listando infortúnios da mesma direção que se acumulam.',
      'ใช้ -(으)ㄹ 뿐만 아니라 สำหรับ "ไม่เพียงแต่ X แต่ยัง Y" โดยที่ X ถูกนำเสนอเป็นจุดที่โดดเด่นจุดหนึ่ง และ Y ถูกเพิ่มเข้ามาเป็นจุดเสริม (มักเป็นเชิงประเมินและเป็นทางการมากกว่า) — ไม่จำเป็นต้องให้ X และ Y เป็นสถานการณ์ชนิดเดียวกัน ใช้ -(으)ㄴ/는 데다가 เพื่อซ้อนสถานการณ์อีกอย่างหนึ่งที่เป็นแนวโน้มเดียวกันลงบนอีกอย่าง ("นอกจาก X แล้วยัง Y") เป็นภาษาพูดและชอบให้สองประโยคไปในทิศทางเดียวกันอย่างมาก (ดีทั้งคู่ หรือแย่ทั้งคู่) 데다가 จะฟังดูผิดเมื่อประโยคที่เพิ่มเข้ามาไม่เกี่ยวข้องหรือไปคนละทิศทาง และ 뿐만 아니라 จะฟังดูแข็งทื่อเมื่อคุณแค่ไล่เรียงเรื่องโชคร้ายในทิศทางเดียวกันที่สะสมกัน',
      'Gunakan -(으)ㄹ 뿐만 아니라 untuk "tidak hanya X tetapi juga Y", di mana X disajikan sebagai satu poin yang menonjol dan Y ditambahkan sebagai poin lanjutan (sering bersifat evaluatif, lebih formal); ini tidak mengharuskan X dan Y berupa jenis keadaan yang sama. Gunakan -(으)ㄴ/는 데다가 untuk menumpuk satu keadaan lagi dengan kecenderungan yang SAMA di atas keadaan lain ("di atas X, juga Y"); ini bersifat percakapan dan sangat lebih suka kedua klausa mengarah ke arah yang sama (keduanya baik, atau keduanya buruk). 데다가 terdengar salah ketika klausa tambahan tidak terhubung atau berlawanan arah, dan 뿐만 아니라 terdengar kaku ketika kamu hanya mendaftar kemalangan searah yang menumpuk.',
      'Dùng -(으)ㄹ 뿐만 아니라 cho "không chỉ X mà còn Y", trong đó X được trình bày như một điểm đáng chú ý và Y được thêm vào như một điểm bổ sung (thường mang tính đánh giá, trang trọng hơn); nó không đòi hỏi X và Y phải cùng loại tình huống. Dùng -(으)ㄴ/는 데다가 để chồng thêm một tình huống nữa cùng KHUYNH HƯỚNG lên một tình huống khác ("thêm vào X, còn có Y"); nó mang tính hội thoại và rất ưu tiên hai mệnh đề đi cùng một hướng (cả hai đều tốt, hoặc cả hai đều xấu). 데다가 nghe sai khi mệnh đề thêm vào không liên quan hoặc ngược hướng, còn 뿐만 아니라 nghe cứng nhắc khi bạn chỉ đang liệt kê những điều xui xẻo cùng hướng chồng chất lên nhau.',
      '-(으)ㄹ 뿐만 아니라 は「XだけでなくYも」に使い、Xを一つの注目すべき点として提示し、Yをさらなる（しばしば評価的で、より形式的な）点として付け加える。XとYが同じ種類の状況である必要はない。-(으)ㄴ/는 데다가 は、同じ傾向の状況をもう一つ別の状況の上に積み重ねるのに使う（「Xに加えてYも」）。会話的で、二つの節が同じ方向に向かうことを強く好む（両方良い、または両方悪い）。데다가 は、付け加える節がつながりがない、または方向が逆のときに不自然に聞こえ、뿐만 아니라 は、同じ方向の不運が積み重なるのを単に列挙しているだけのときに堅苦しく聞こえる。',
    ),
    items: [
      {
        sentence: '그 사람은 약속에 자주 늦을 {} 사과도 안 해서 사람들이 싫어해요.',
        optionA: '늦을 뿐만 아니라',
        optionB: '늦는 데다가',
        answer: 'b',
        trans: L(
          'That person is often late for appointments and on top of that doesn\'t even apologize, so people dislike him.',
          'Esa persona suele llegar tarde a las citas y, encima, ni siquiera se disculpa, así que la gente le tiene antipatía.',
          'Cette personne est souvent en retard aux rendez-vous et, en plus, elle ne s\'excuse même pas, donc les gens ne l\'aiment pas.',
          'Essa pessoa costuma se atrasar para os compromissos e, ainda por cima, nem pede desculpas, então as pessoas não gostam dela.',
          'คนคนนั้นมักมาสายในการนัดหมาย แล้วยังไม่ขอโทษอีกด้วย คนเลยไม่ชอบเขา',
          'Orang itu sering terlambat untuk janji temu dan, di atas itu, bahkan tidak minta maaf, jadi orang-orang tidak menyukainya.',
          'Người đó thường đến trễ các cuộc hẹn, hơn nữa còn chẳng thèm xin lỗi, nên mọi người không ưa anh ta.',
          'あの人は約束によく遅れるうえに、謝りもしないので、人に嫌われる。',
        ),
        why: L(
          'Two same-direction faults (being late, not apologizing) piling up to explain why people dislike him — pure accumulation of negative circumstances, which is 데다가; 뿐만 아니라\'s \'not only...but also\' framing presents the first point as something notable to top, which sounds stiff and off for merely listing complaints.',
          'Dos defectos en la misma dirección (llegar tarde, no disculparse) que se acumulan para explicar por qué la gente le tiene antipatía: pura acumulación de circunstancias negativas, lo cual corresponde a 데다가; el marco "no solo... sino también" de 뿐만 아니라 presenta el primer punto como algo notable que se supera, lo que suena rígido y fuera de lugar para una simple lista de quejas.',
          'Deux défauts de même direction (être en retard, ne pas s\'excuser) qui s\'accumulent pour expliquer pourquoi les gens ne l\'aiment pas : pure accumulation de circonstances négatives, ce qui correspond à 데다가 ; le cadre "non seulement... mais aussi" de 뿐만 아니라 présente le premier point comme quelque chose de notable à surpasser, ce qui sonne rigide et déplacé pour une simple liste de griefs.',
          'Dois defeitos na mesma direção (chegar atrasado, não pedir desculpas) que se acumulam para explicar por que as pessoas não gostam dele: pura acumulação de circunstâncias negativas, o que corresponde a 데다가; o enquadramento "não só... mas também" de 뿐만 아니라 apresenta o primeiro ponto como algo notável a ser superado, o que soa rígido e fora de lugar para apenas listar reclamações.',
          'ข้อเสียสองอย่างที่ไปในทิศทางเดียวกัน (มาสาย ไม่ขอโทษ) สะสมกันเพื่ออธิบายว่าทำไมคนถึงไม่ชอบเขา เป็นการสะสมสถานการณ์เชิงลบล้วน ๆ ซึ่งคือ 데다가; กรอบ "ไม่เพียงแต่... แต่ยัง" ของ 뿐만 아니라 นำเสนอจุดแรกเป็นสิ่งที่โดดเด่นเพื่อจะต่อยอด ซึ่งฟังดูแข็งทื่อและไม่เข้ากันสำหรับการแค่ไล่เรียงคำบ่น',
          'Dua kekurangan searah (terlambat, tidak minta maaf) yang menumpuk untuk menjelaskan mengapa orang tidak menyukainya: murni akumulasi keadaan negatif, yang merupakan 데다가; kerangka "tidak hanya... tetapi juga" dari 뿐만 아니라 menyajikan poin pertama sebagai sesuatu yang menonjol untuk dilampaui, yang terdengar kaku dan janggal untuk sekadar mendaftar keluhan.',
          'Hai khuyết điểm cùng chiều (đến trễ, không xin lỗi) chồng chất lên nhau để giải thích vì sao mọi người không ưa anh ta — thuần túy là sự tích lũy các tình huống tiêu cực, đó chính là 데다가; cách diễn đạt "không chỉ... mà còn" của 뿐만 아니라 trình bày điểm đầu tiên như một điều đáng chú ý để bồi thêm, nghe cứng nhắc và lạc lõng khi chỉ đơn thuần liệt kê lời than phiền.',
          '同じ方向の二つの欠点（遅刻すること、謝らないこと）が積み重なって、人に嫌われる理由を説明している。純粋にマイナスの状況が積み重なる場合で、これは 데다가 にあたる。뿐만 아니라 の「～だけでなく～も」という枠組みは、最初の点を上塗りすべき注目点として提示するので、単に不満を並べるには堅苦しく不自然に聞こえる。',
        ),
      },
      {
        sentence: '오늘 아침에 비가 {} 길까지 막혀서 회사에 늦었어요.',
        optionA: '올 뿐만 아니라',
        optionB: '오는 데다가',
        answer: 'b',
        trans: L(
          'This morning it was raining and on top of that the roads were jammed, so I was late to work.',
          'Esta mañana llovía y, encima, las calles estaban congestionadas, así que llegué tarde al trabajo.',
          'Ce matin il pleuvait et, en plus, les routes étaient embouteillées, donc je suis arrivé en retard au travail.',
          'Esta manhã estava chovendo e, ainda por cima, as ruas estavam congestionadas, então cheguei atrasado ao trabalho.',
          'เช้านี้ฝนตก แล้วถนนยังรถติดอีกด้วย ฉันเลยไปทำงานสาย',
          'Pagi ini hujan dan, di atas itu, jalanan macet, jadi saya terlambat ke kantor.',
          'Sáng nay trời mưa, hơn nữa đường lại còn kẹt xe, nên tôi đi làm trễ.',
          '今朝は雨が降っていたうえに、道も混んでいたので、会社に遅刻した。',
        ),
        why: L(
          'Two piled-up bad circumstances causing lateness — same-direction accumulation (\'on top of X, Y\'), which is 데다가; 올 뿐만 아니라 forces a \'not only...but also\' emphasis that is awkward for simply listing the morning\'s unlucky conditions.',
          'Dos circunstancias malas amontonadas que causan el retraso: acumulación en la misma dirección ("encima de X, Y"), lo cual es 데다가; 올 뿐만 아니라 fuerza un énfasis de "no solo... sino también" que resulta torpe para simplemente enumerar las condiciones desafortunadas de la mañana.',
          'Deux mauvaises circonstances empilées qui causent le retard : accumulation de même direction ("en plus de X, Y"), ce qui est 데다가 ; 올 뿐만 아니라 impose une emphase "non seulement... mais aussi" qui est maladroite pour simplement énumérer les conditions malchanceuses du matin.',
          'Duas circunstâncias ruins empilhadas que causam o atraso: acumulação na mesma direção ("em cima de X, Y"), o que é 데다가; 올 뿐만 아니라 força uma ênfase de "não só... mas também" que fica esquisita para apenas listar as condições azaradas da manhã.',
          'สถานการณ์แย่สองอย่างที่ทับซ้อนกันทำให้มาสาย เป็นการสะสมในทิศทางเดียวกัน ("นอกจาก X แล้วยัง Y") ซึ่งคือ 데다가; 올 뿐만 아니라 บังคับให้เน้นแบบ "ไม่เพียงแต่... แต่ยัง" ซึ่งฟังดูเก้งก้างสำหรับการแค่ไล่เรียงสภาพโชคร้ายของเช้านั้น',
          'Dua keadaan buruk yang menumpuk menyebabkan keterlambatan: akumulasi searah ("di atas X, Y"), yang merupakan 데다가; 올 뿐만 아니라 memaksakan penekanan "tidak hanya... tetapi juga" yang terasa canggung untuk sekadar mendaftar kondisi sial pagi itu.',
          'Hai tình huống xấu chồng lên nhau gây ra việc đến trễ — sự tích lũy cùng chiều ("thêm vào X, có Y"), đó là 데다가; 올 뿐만 아니라 ép một sự nhấn mạnh kiểu "không chỉ... mà còn" nghe lủng củng khi chỉ đơn giản liệt kê những điều xui xẻo của buổi sáng.',
          '遅刻を引き起こす二つの悪い状況が積み重なっている。同じ方向の積み重ね（「Xに加えてY」）で、これは 데다가 にあたる。올 뿐만 아니라 は「～だけでなく～も」という強調を強いるため、その朝の不運な状況を単に並べるには不自然である。',
        ),
      },
      {
        sentence: '이 노트북은 디자인이 예쁠 {} 보안 기능까지 뛰어나서 전문가들이 추천해요.',
        optionA: '예쁠 뿐만 아니라',
        optionB: '예쁜 데다가',
        answer: 'a',
        trans: L(
          'This laptop is not only pretty in design but also has outstanding security features, so experts recommend it.',
          'Esta laptop no solo tiene un diseño bonito, sino que además cuenta con funciones de seguridad excepcionales, así que los expertos la recomiendan.',
          'Ce portable n\'est pas seulement joli en termes de design, mais il dispose en plus de fonctions de sécurité exceptionnelles, donc les experts le recommandent.',
          'Este laptop não só tem um design bonito, mas também conta com recursos de segurança excepcionais, então os especialistas o recomendam.',
          'แล็ปท็อปเครื่องนี้ไม่เพียงแต่ดีไซน์สวยเท่านั้น แต่ยังมีฟังก์ชันด้านความปลอดภัยที่ยอดเยี่ยมอีกด้วย ผู้เชี่ยวชาญจึงแนะนำ',
          'Laptop ini tidak hanya cantik desainnya, tetapi juga memiliki fitur keamanan yang luar biasa, jadi para ahli merekomendasikannya.',
          'Chiếc laptop này không chỉ đẹp về thiết kế mà còn có cả tính năng bảo mật xuất sắc, nên các chuyên gia khuyên dùng.',
          'このノートパソコンはデザインがきれいなだけでなく、セキュリティ機能まで優れているので、専門家が勧める。',
        ),
        why: L(
          'The point escalates from a surface merit (looks) to a serious technical merit (security) marked by 까지 and tied to an evaluative \'experts recommend it\' — 뿐만 아니라 carries that \'not only...but also, and even\' upgrading emphasis; plain 데다가 would flatten two unlike merits into a casual same-level list and clashes with the formal evaluative framing.',
          'El argumento escala de un mérito superficial (la apariencia) a un mérito técnico serio (la seguridad) marcado por 까지 y ligado a un "los expertos la recomiendan" evaluativo: 뿐만 아니라 lleva ese énfasis de "no solo... sino también, e incluso" que sube de nivel; un simple 데다가 aplanaría dos méritos disímiles en una lista casual del mismo nivel y choca con el marco evaluativo formal.',
          'L\'argument monte d\'un mérite superficiel (l\'apparence) à un mérite technique sérieux (la sécurité) marqué par 까지 et lié à un "les experts le recommandent" évaluatif : 뿐만 아니라 porte cette emphase "non seulement... mais aussi, et même" qui monte en gamme ; un simple 데다가 aplatirait deux mérites différents en une liste banale de même niveau et se heurte au cadre évaluatif formel.',
          'O argumento escala de um mérito superficial (a aparência) a um mérito técnico sério (a segurança) marcado por 까지 e ligado a um "os especialistas o recomendam" avaliativo: 뿐만 아니라 carrega essa ênfase de "não só... mas também, e até" que sobe de nível; um simples 데다가 achataria dois méritos diferentes numa lista casual do mesmo nível e destoa do enquadramento avaliativo formal.',
          'ประเด็นไต่ระดับจากข้อดีผิวเผิน (รูปลักษณ์) ไปสู่ข้อดีเชิงเทคนิคที่จริงจัง (ความปลอดภัย) ซึ่งทำเครื่องหมายด้วย 까지 และเชื่อมโยงกับการประเมิน "ผู้เชี่ยวชาญแนะนำ" — 뿐만 아니라 สื่อการเน้นแบบ "ไม่เพียงแต่... แต่ยัง แถมยัง" ที่ยกระดับขึ้น; 데다가 ธรรมดาจะทำให้ข้อดีสองอย่างที่ต่างกันแบนราบเป็นรายการระดับเดียวกันแบบลำลอง และขัดกับกรอบการประเมินที่เป็นทางการ',
          'Argumennya naik dari kelebihan permukaan (penampilan) ke kelebihan teknis yang serius (keamanan) yang ditandai dengan 까지 dan terkait dengan penilaian "para ahli merekomendasikannya" — 뿐만 아니라 membawa penekanan "tidak hanya... tetapi juga, bahkan" yang meningkatkan taraf; 데다가 biasa akan meratakan dua kelebihan berbeda menjadi daftar santai setingkat dan berbenturan dengan kerangka penilaian formal.',
          'Luận điểm leo thang từ một ưu điểm bề mặt (vẻ ngoài) lên một ưu điểm kỹ thuật nghiêm túc (bảo mật) được đánh dấu bằng 까지 và gắn với đánh giá "chuyên gia khuyên dùng" — 뿐만 아니라 mang sắc thái nhấn mạnh "không chỉ... mà còn, thậm chí" có tính nâng cấp; 데다가 thông thường sẽ san bằng hai ưu điểm khác loại thành một danh sách cùng cấp xuề xòa và xung khắc với khung đánh giá trang trọng.',
          '論点は表面的な長所（見た目）から、까지 で示された本格的な技術的長所（セキュリティ）へと格上げされ、評価的な「専門家が勧める」に結びついている。뿐만 아니라 はその「～だけでなく～も、さらには」という格上げの強調を担う。単なる 데다가 では、異質な二つの長所を同じレベルの気軽な羅列に平板化してしまい、形式的で評価的な枠組みとそぐわない。',
        ),
      },
    ],
  },
  {
    id: 'naboda-ngaboda',
    a: '-나 보다',
    b: '-(으)ㄴ가 보다',
    note: L(
      'Both express a conjecture "(I guess/it seems) ..." drawn from indirect evidence; they differ by the predicate. Use -나 보다 after action verbs and 있다/없다; use -(으)ㄴ가 보다 after 이다 and (prescriptively) adjectives. Note that with plain adjectives colloquial Korean increasingly tolerates -나 보다 too, so reliable discrimination items contrast verbs/있다 (only -나) against 이다 (only -ㄴ가).',
      'Ambas expresan una conjetura "(supongo/parece que)..." sacada de evidencia indirecta; se diferencian por el predicado. Usá -나 보다 después de verbos de acción y 있다/없다; usá -(으)ㄴ가 보다 después de 이다 y (prescriptivamente) adjetivos. Tené en cuenta que con adjetivos simples el coreano coloquial cada vez tolera más -나 보다 también, así que los ítems de discriminación confiables contrastan verbos/있다 (solo -나) contra 이다 (solo -ㄴ가).',
      'Les deux expriment une conjecture « (je suppose/il semble que)… » tirée d\'une preuve indirecte ; elles diffèrent par le prédicat. Emploie -나 보다 après les verbes d\'action et 있다/없다 ; emploie -(으)ㄴ가 보다 après 이다 et (de façon prescriptive) les adjectifs. Note qu\'avec les adjectifs simples le coréen familier tolère de plus en plus -나 보다 aussi, donc les items de discrimination fiables opposent les verbes/있다 (uniquement -나) à 이다 (uniquement -ㄴ가).',
      'Ambas expressam uma conjectura "(suponho/parece que)..." tirada de evidência indireta; diferem pelo predicado. Use -나 보다 depois de verbos de ação e 있다/없다; use -(으)ㄴ가 보다 depois de 이다 e (prescritivamente) adjetivos. Observe que, com adjetivos simples, o coreano coloquial cada vez mais também tolera -나 보다, então os itens de discriminação confiáveis contrastam verbos/있다 (só -나) com 이다 (só -ㄴ가).',
      'ทั้งสองรูปแสดงการคาดเดา "(เดาว่า/ดูเหมือนว่า)..." ที่ได้จากหลักฐานทางอ้อม ต่างกันที่ภาคแสดง ใช้ -나 보다 หลังคำกริยาแสดงการกระทำและ 있다/없다 ใช้ -(으)ㄴ가 보다 หลัง 이다 และ (ตามหลักไวยากรณ์ที่กำหนด) คำคุณศัพท์ พึงสังเกตว่ากับคำคุณศัพท์ทั่วไป ภาษาเกาหลีแบบพูดยอมรับ -나 보다 มากขึ้นเรื่อยๆ ด้วย ดังนั้นข้อแยกแยะที่เชื่อถือได้จะเปรียบเทียบคำกริยา/있다 (ใช้ได้แค่ -나) กับ 이다 (ใช้ได้แค่ -ㄴ가)',
      'Keduanya mengungkapkan dugaan "(kurasa/sepertinya)..." yang ditarik dari bukti tidak langsung; bedanya pada predikat. Gunakan -나 보다 setelah kata kerja aksi dan 있다/없다; gunakan -(으)ㄴ가 보다 setelah 이다 dan (secara preskriptif) kata sifat. Perhatikan bahwa dengan kata sifat biasa, bahasa Korea kolokial makin menoleransi -나 보다 juga, jadi butir diskriminasi yang andal mempertentangkan kata kerja/있다 (hanya -나) dengan 이다 (hanya -ㄴ가).',
      'Cả hai đều diễn đạt một phỏng đoán "(chắc là/có vẻ như)..." rút ra từ bằng chứng gián tiếp; chúng khác nhau ở vị ngữ. Dùng -나 보다 sau động từ hành động và 있다/없다; dùng -(으)ㄴ가 보다 sau 이다 và (theo quy phạm) tính từ. Lưu ý rằng với tính từ thông thường, tiếng Hàn khẩu ngữ ngày càng chấp nhận cả -나 보다, nên các mục phân biệt đáng tin cậy sẽ đối lập động từ/있다 (chỉ -나) với 이다 (chỉ -ㄴ가).',
      'どちらも間接的な証拠から導かれる「(～みたいだ／～らしい)」という推量を表すが、述語によって使い分ける。動作動詞や 있다/없다 の後には -나 보다 を、이다 や（規範的には）形容詞の後には -(으)ㄴ가 보다 を使う。なお、普通の形容詞では口語の韓国語が -나 보다 もますます許容するようになっているため、信頼できる判別問題は、動詞/있다（-나 のみ）と 이다（-ㄴ가 のみ）を対比させる。',
    ),
    items: [
      {
        sentence: '밖에 사람들이 우산을 쓰고 있어요. 비가 {}.',
        optionA: '오나 봐요',
        optionB: '오는가 봐요',
        answer: 'a',
        trans: L(
          'People outside are using umbrellas. I guess it\'s raining.',
          'La gente afuera está usando paraguas. Me imagino que está lloviendo.',
          'Les gens dehors utilisent des parapluies. J\'imagine qu\'il pleut.',
          'As pessoas lá fora estão usando guarda-chuva. Acho que está chovendo.',
          'คนข้างนอกกำลังกางร่มกัน ท่าทางฝนคงจะตก',
          'Orang-orang di luar memakai payung. Sepertinya sedang hujan.',
          'Mọi người bên ngoài đang dùng ô. Chắc là trời đang mưa.',
          '外の人が傘をさしている。雨が降っているみたいだ。',
        ),
        why: L(
          '오다 is an action verb, so the natural conjecture form is -나 보다 → 오나 봐요. -(으)ㄴ가 보다 belongs to adjectives/이다; forcing it onto a verb gives 오는가 봐요, which is stiff/literary and not used in this everyday spoken context.',
          '오다 es un verbo de acción, así que la forma natural de conjetura es -나 보다 → 오나 봐요. -(으)ㄴ가 보다 pertenece a los adjetivos/이다; forzarla sobre un verbo da 오는가 봐요, que suena rígido/literario y no se usa en este contexto cotidiano hablado.',
          '오다 est un verbe d\'action, donc la forme naturelle de conjecture est -나 보다 → 오나 봐요. -(으)ㄴ가 보다 appartient aux adjectifs/이다 ; l\'imposer à un verbe donne 오는가 봐요, qui sonne rigide/littéraire et ne s\'emploie pas dans ce contexte parlé du quotidien.',
          '오다 é um verbo de ação, então a forma natural de conjectura é -나 보다 → 오나 봐요. -(으)ㄴ가 보다 pertence aos adjetivos/이다; forçá-la sobre um verbo dá 오는가 봐요, que soa rígido/literário e não é usado neste contexto falado do dia a dia.',
          '오다 เป็นคำกริยาแสดงการกระทำ ดังนั้นรูปคาดเดาที่เป็นธรรมชาติคือ -나 보다 → 오나 봐요 ส่วน -(으)ㄴ가 보다 ใช้กับคำคุณศัพท์/이다 การฝืนเอามาใช้กับคำกริยาจะได้ 오는가 봐요 ซึ่งฟังดูแข็งทื่อ/เป็นภาษาหนังสือ และไม่ใช้ในบริบทพูดในชีวิตประจำวันเช่นนี้',
          '오다 adalah kata kerja aksi, jadi bentuk dugaan yang alami adalah -나 보다 → 오나 봐요. -(으)ㄴ가 보다 termasuk untuk kata sifat/이다; memaksakannya pada kata kerja menghasilkan 오는가 봐요, yang terdengar kaku/sastrawi dan tidak dipakai dalam konteks lisan sehari-hari ini.',
          '오다 là động từ hành động, nên dạng phỏng đoán tự nhiên là -나 보다 → 오나 봐요. -(으)ㄴ가 보다 thuộc về tính từ/이다; ép nó vào động từ tạo ra 오는가 봐요, nghe cứng nhắc/văn chương và không dùng trong ngữ cảnh nói hằng ngày này.',
          '오다 は動作動詞なので、自然な推量の形は -나 보다 → 오나 봐요 になる。-(으)ㄴ가 보다 は形容詞/이다 に付くもので、動詞に無理に付けると 오는가 봐요 となり、硬く文語的で、この日常会話の文脈では使われない。',
        ),
      },
      {
        sentence: '불이 켜져 있는 걸 보니 안에 누가 {}.',
        optionA: '있나 봐요',
        optionB: '있은가 봐요',
        answer: 'a',
        trans: L(
          'The light is on, so I guess someone is inside.',
          'La luz está encendida, así que me imagino que hay alguien adentro.',
          'La lumière est allumée, donc j\'imagine qu\'il y a quelqu\'un à l\'intérieur.',
          'A luz está acesa, então acho que tem alguém lá dentro.',
          'ไฟเปิดอยู่ ท่าทางคงจะมีใครอยู่ข้างใน',
          'Lampunya menyala, jadi sepertinya ada orang di dalam.',
          'Đèn đang bật, nên chắc là có ai đó ở bên trong.',
          '電気がついているから、中に誰かいるみたいだ。',
        ),
        why: L(
          '있다 always takes -나 보다 → 있나 봐요. -(으)ㄴ가 never attaches to 있다 (있은가 봐요 is ungrammatical), so only option A is possible.',
          '있다 siempre toma -나 보다 → 있나 봐요. -(으)ㄴ가 nunca se adjunta a 있다 (있은가 봐요 es agramatical), así que solo la opción A es posible.',
          '있다 prend toujours -나 보다 → 있나 봐요. -(으)ㄴ가 ne s\'attache jamais à 있다 (있은가 봐요 est agrammatical), donc seule l\'option A est possible.',
          '있다 sempre toma -나 보다 → 있나 봐요. -(으)ㄴ가 nunca se anexa a 있다 (있은가 봐요 é agramatical), então só a opção A é possível.',
          '있다 ใช้กับ -나 보다 เสมอ → 있나 봐요 ส่วน -(으)ㄴ가 ไม่เคยต่อกับ 있다 (있은가 봐요 ผิดไวยากรณ์) ดังนั้นจึงเป็นไปได้เฉพาะตัวเลือก A เท่านั้น',
          '있다 selalu memakai -나 보다 → 있나 봐요. -(으)ㄴ가 tidak pernah melekat pada 있다 (있은가 봐요 tidak gramatikal), jadi hanya pilihan A yang mungkin.',
          '있다 luôn dùng -나 보다 → 있나 봐요. -(으)ㄴ가 không bao giờ gắn vào 있다 (있은가 봐요 là sai ngữ pháp), nên chỉ có phương án A là khả thi.',
          '있다 は常に -나 보다 を取る → 있나 봐요。-(으)ㄴ가 は 있다 には決して付かず（있은가 봐요 は非文）、よって選択肢 A だけが可能である。',
        ),
      },
      {
        sentence: '교복을 입고 있는 걸 보니 아직 {}.',
        optionA: '학생이나 봐요',
        optionB: '학생인가 봐요',
        answer: 'b',
        trans: L(
          'Judging by the school uniform, I guess he\'s still a student.',
          'A juzgar por el uniforme escolar, me imagino que todavía es estudiante.',
          'À en juger par l\'uniforme scolaire, j\'imagine qu\'il est encore étudiant.',
          'A julgar pelo uniforme escolar, acho que ele ainda é estudante.',
          'ดูจากชุดนักเรียนแล้ว ท่าทางเขาคงยังเป็นนักเรียนอยู่',
          'Dilihat dari seragam sekolahnya, sepertinya dia masih pelajar.',
          'Nhìn vào bộ đồng phục, chắc là cậu ấy vẫn còn là học sinh.',
          '制服から判断すると、彼はまだ学生みたいだ。',
        ),
        why: L(
          '이다 (학생이다) takes -(으)ㄴ가 보다 → 학생인가 봐요. 학생이나 reads as the particle 이나 (\'students or...\'), so 학생이나 봐요 is not a conjecture and is wrong here.',
          '이다 (학생이다) toma -(으)ㄴ가 보다 → 학생인가 봐요. 학생이나 se lee como la partícula 이나 (\'estudiantes o...\'), así que 학생이나 봐요 no es una conjetura y acá es incorrecto.',
          '이다 (학생이다) prend -(으)ㄴ가 보다 → 학생인가 봐요. 학생이나 se lit comme la particule 이나 (« étudiants ou… »), donc 학생이나 봐요 n\'est pas une conjecture et est incorrect ici.',
          '이다 (학생이다) toma -(으)ㄴ가 보다 → 학생인가 봐요. 학생이나 é lido como a partícula 이나 (\'estudantes ou...\'), então 학생이나 봐요 não é uma conjectura e está errado aqui.',
          '이다 (학생이다) ใช้กับ -(으)ㄴ가 보다 → 학생인가 봐요 ส่วน 학생이나 จะอ่านเป็นคำช่วย 이나 (\'นักเรียนหรือ...\') ดังนั้น 학생이나 봐요 จึงไม่ใช่การคาดเดาและผิดในที่นี้',
          '이다 (학생이다) memakai -(으)ㄴ가 보다 → 학생인가 봐요. 학생이나 terbaca sebagai partikel 이나 (\'pelajar atau...\'), jadi 학생이나 봐요 bukan dugaan dan salah di sini.',
          '이다 (학생이다) dùng -(으)ㄴ가 보다 → 학생인가 봐요. 학생이나 đọc thành tiểu từ 이나 (\'học sinh hay...\'), nên 학생이나 봐요 không phải là phỏng đoán và sai ở đây.',
          '이다 (학생이다) は -(으)ㄴ가 보다 を取る → 학생인가 봐요。학생이나 は助詞の 이나（「学生か…」）と読めてしまうため、학생이나 봐요 は推量にならず、ここでは誤り。',
        ),
      },
    ],
  },
  {
    id: 'eoyahaetda-georeotda',
    a: '-았/었어야 했다',
    b: '-(으)ㄹ걸 그랬다',
    note: L(
      'Both look back on something you didn\'t do. Use -았/었어야 했다 for an impersonal judgment that something was the right or necessary thing to do (duty/correctness, often with real consequences, and usable about other people); use -(으)ㄹ걸 그랬다 for a softer, personal regret or wish — strictly first-person self-talk about something you wish you\'d done, never about someone else\'s obligation.',
      'Ambas miran hacia atrás sobre algo que no hiciste. Usá -았/었어야 했다 para un juicio impersonal de que algo era lo correcto o lo necesario (deber/corrección, a menudo con consecuencias reales, y se puede usar sobre otras personas); usá -(으)ㄹ걸 그랬다 para un arrepentimiento o deseo personal más suave: estrictamente un monólogo en primera persona sobre algo que ojalá hubieras hecho, nunca sobre la obligación de otra persona.',
      'Les deux reviennent sur quelque chose que tu n\'as pas fait. Utilise -았/었어야 했다 pour un jugement impersonnel selon lequel quelque chose était la bonne ou la chose nécessaire à faire (devoir/justesse, souvent avec des conséquences réelles, et utilisable à propos d\'autres personnes) ; utilise -(으)ㄹ걸 그랬다 pour un regret ou un souhait personnel plus doux — strictement un monologue à la première personne sur quelque chose que tu aurais aimé faire, jamais sur l\'obligation de quelqu\'un d\'autre.',
      'Ambas olham para trás sobre algo que você não fez. Use -았/었어야 했다 para um juízo impessoal de que algo era a coisa certa ou necessária a fazer (dever/correção, muitas vezes com consequências reais, e utilizável sobre outras pessoas); use -(으)ㄹ걸 그랬다 para um arrependimento ou desejo pessoal mais suave — estritamente uma fala consigo mesmo na primeira pessoa sobre algo que você gostaria de ter feito, nunca sobre a obrigação de outra pessoa.',
      'ทั้งสองรูปย้อนมองสิ่งที่คุณไม่ได้ทำ ใช้ -았/었어야 했다 สำหรับการตัดสินแบบไม่เจาะจงตัวบุคคลว่าบางสิ่งเป็นสิ่งที่ถูกต้องหรือจำเป็นต้องทำ (หน้าที่/ความถูกต้อง มักมีผลลัพธ์จริง และใช้พูดถึงคนอื่นได้); ใช้ -(으)ㄹ걸 그랬다 สำหรับความเสียดายหรือความปรารถนาส่วนตัวที่นุ่มนวลกว่า — เป็นการพูดกับตัวเองในบุรุษที่หนึ่งล้วนๆ เกี่ยวกับสิ่งที่อยากให้ตัวเองได้ทำ ไม่เคยใช้กับหน้าที่ของคนอื่น',
      'Keduanya menengok kembali ke sesuatu yang tidak kamu lakukan. Gunakan -았/었어야 했다 untuk penilaian impersonal bahwa sesuatu adalah hal yang benar atau perlu dilakukan (kewajiban/kebenaran, sering dengan konsekuensi nyata, dan bisa dipakai tentang orang lain); gunakan -(으)ㄹ걸 그랬다 untuk penyesalan atau harapan pribadi yang lebih lembut — murni bicara pada diri sendiri dalam orang pertama tentang sesuatu yang seandainya kamu lakukan, tidak pernah tentang kewajiban orang lain.',
      'Cả hai đều nhìn lại điều bạn đã không làm. Dùng -았/었어야 했다 cho phán xét phi cá nhân rằng điều gì đó là việc đúng hoặc cần thiết phải làm (bổn phận/sự đúng đắn, thường kèm hậu quả thực, và có thể dùng nói về người khác); dùng -(으)ㄹ걸 그랬다 cho sự tiếc nuối hoặc mong muốn cá nhân nhẹ nhàng hơn — chỉ thuần là tự nói với mình ở ngôi thứ nhất về điều mình ước đã làm, không bao giờ nói về nghĩa vụ của người khác.',
      'どちらも、自分がしなかったことを振り返る表現。-았/었어야 했다 は、何かをするのが正しい・必要なことだったという非個人的な判断（義務・正しさ、しばしば現実の結果を伴い、他人についても使える）に使う。-(으)ㄹ걸 그랬다 はより柔らかく個人的な後悔や願望に使う――あくまで一人称の自分への独り言で、こうしておけばよかったという内容に限られ、他人の義務には決して使わない。',
    ),
    items: [
      {
        sentence: '규정상 신청서는 마감일 전에 {} 하는데, 깜빡하고 안 냈어요.',
        optionA: '제출했어야',
        optionB: '제출할걸',
        answer: 'a',
        trans: L(
          'By the rules the application had to be submitted before the deadline, but I forgot and didn\'t.',
          'Según las reglas, la solicitud tenía que entregarse antes de la fecha límite, pero me olvidé y no lo hice.',
          'Selon le règlement, le dossier devait être soumis avant la date limite, mais j\'ai oublié et je ne l\'ai pas fait.',
          'Segundo as regras, a inscrição tinha que ser entregue antes do prazo, mas eu esqueci e não fiz.',
          'ตามกฎแล้ว ใบสมัครต้องยื่นก่อนเส้นตาย แต่ฉันลืมและไม่ได้ยื่น',
          'Menurut aturan, lamaran harus diserahkan sebelum tenggat waktu, tetapi aku lupa dan tidak melakukannya.',
          'Theo quy định thì hồ sơ phải được nộp trước hạn chót, nhưng tôi đã quên và không nộp.',
          '規則では、願書は締め切り前に提出しなければならなかったのに、忘れて出さなかった。',
        ),
        why: L(
          '규정상(\'by the rules\') frames this as an obligation/what was required, so only -았어야 하다 fits; -(으)ㄹ걸 그랬다 is soft personal preference and clashes with the stated rule, plus it can\'t pair with the following 하는데 obligation frame.',
          '규정상(\'según las reglas\') enmarca esto como una obligación / lo que se requería, así que solo encaja -았어야 하다; -(으)ㄹ걸 그랬다 es una preferencia personal suave y choca con la regla planteada, además no puede combinarse con el marco de obligación 하는데 que sigue.',
          '규정상(\'selon le règlement\') présente cela comme une obligation / ce qui était requis, donc seul -았어야 하다 convient ; -(으)ㄹ걸 그랬다 est une préférence personnelle douce qui entre en conflit avec la règle énoncée, et il ne peut pas se combiner avec le cadre d\'obligation 하는데 qui suit.',
          '규정상(\'segundo as regras\') enquadra isto como uma obrigação / o que era exigido, então só -았어야 하다 encaixa; -(으)ㄹ걸 그랬다 é uma preferência pessoal suave e colide com a regra declarada, além de não poder se combinar com o quadro de obrigação 하는데 que segue.',
          '규정상(\'ตามกฎ\') ทำให้ประโยคนี้เป็นข้อบังคับ/สิ่งที่จำเป็นต้องทำ จึงเข้าได้เฉพาะ -았어야 하다; -(으)ㄹ걸 그랬다 เป็นความชอบส่วนตัวแบบนุ่มนวลซึ่งขัดกับกฎที่ระบุไว้ อีกทั้งยังเข้าคู่กับโครงข้อบังคับ 하는데 ที่ตามมาไม่ได้',
          '규정상(\'menurut aturan\') membingkai ini sebagai kewajiban/hal yang dipersyaratkan, jadi hanya -았어야 하다 yang cocok; -(으)ㄹ걸 그랬다 adalah preferensi pribadi yang lembut dan bentrok dengan aturan yang dinyatakan, lagipula tidak bisa dipasangkan dengan kerangka kewajiban 하는데 berikutnya.',
          '규정상(\'theo quy định\') định khung câu này như một nghĩa vụ/điều bắt buộc, nên chỉ -았어야 하다 mới phù hợp; -(으)ㄹ걸 그랬다 là sự tiếc nuối/mong muốn cá nhân nhẹ nhàng và mâu thuẫn với quy định đã nêu, hơn nữa không thể đi cùng khung nghĩa vụ 하는데 theo sau.',
          '규정상(\'規則では\')はこれを義務・必要だったこととして枠づけるので、-았어야 하다 のみが合う。-(으)ㄹ걸 그랬다 は柔らかい個人的な好みで、述べられた規則と衝突し、さらに後続の義務の枠 하는데 とは結びつけられない。',
        ),
      },
      {
        sentence: '아까 그 카페에서 케이크가 진짜 맛있어 보였는데, 그냥 {} 그랬어.',
        optionA: '먹었어야',
        optionB: '먹을',
        answer: 'b',
        trans: L(
          'That cake at the cafe earlier looked really delicious; I should have just eaten it.',
          'Ese pastel del café de hace un rato se veía riquísimo; debería habérmelo comido nomás.',
          'Ce gâteau au café tout à l\'heure avait l\'air vraiment délicieux ; j\'aurais dû simplement le manger.',
          'Aquele bolo no café mais cedo parecia muito gostoso; eu devia ter comido mesmo.',
          'เค้กที่คาเฟ่เมื่อกี้ดูอร่อยมากเลย น่าจะกินไปซะก็ดี',
          'Kue di kafe tadi kelihatan enak banget; mestinya aku makan saja.',
          'Cái bánh ở quán cà phê lúc nãy trông ngon thật đấy; đáng lẽ tôi cứ ăn đi cho rồi.',
          'さっきカフェにあったあのケーキ、すごくおいしそうだった。やっぱり食べておけばよかった。',
        ),
        why: L(
          'The sentence is closed by 그랬어, which only combines with -(으)ㄹ걸, so 먹을걸 그랬어 is the only grammatical completion; 먹었어야 그랬어 is not a valid construction, and the content is light self-regret, not a duty.',
          'La oración se cierra con 그랬어, que solo se combina con -(으)ㄹ걸, así que 먹을걸 그랬어 es la única terminación gramatical; 먹었어야 그랬어 no es una construcción válida, y el contenido es un autorreproche leve, no un deber.',
          'La phrase se termine par 그랬어, qui ne se combine qu\'avec -(으)ㄹ걸, donc 먹을걸 그랬어 est la seule complétion grammaticale ; 먹었어야 그랬어 n\'est pas une construction valide, et le contenu est un léger regret personnel, pas un devoir.',
          'A frase é fechada por 그랬어, que só combina com -(으)ㄹ걸, então 먹을걸 그랬어 é a única conclusão gramatical; 먹었어야 그랬어 não é uma construção válida, e o conteúdo é um autoarrependimento leve, não um dever.',
          'ประโยคจบด้วย 그랬어 ซึ่งรวมได้เฉพาะกับ -(으)ㄹ걸 ดังนั้น 먹을걸 그랬어 จึงเป็นการเติมเต็มที่ถูกไวยากรณ์เพียงรูปเดียว; 먹었어야 그랬어 ไม่ใช่โครงสร้างที่ใช้ได้ และเนื้อหาเป็นความเสียดายตัวเองเบาๆ ไม่ใช่หน้าที่',
          'Kalimat ditutup oleh 그랬어, yang hanya bisa digabung dengan -(으)ㄹ걸, sehingga 먹을걸 그랬어 adalah satu-satunya penyelesaian yang gramatikal; 먹었어야 그랬어 bukan konstruksi yang sah, dan isinya adalah penyesalan diri yang ringan, bukan kewajiban.',
          'Câu được kết thúc bằng 그랬어, vốn chỉ kết hợp với -(으)ㄹ걸, nên 먹을걸 그랬어 là cách hoàn thành đúng ngữ pháp duy nhất; 먹었어야 그랬어 không phải là một cấu trúc hợp lệ, và nội dung là sự tự tiếc nuối nhẹ nhàng, không phải nghĩa vụ.',
          '文は 그랬어 で締めくくられており、これは -(으)ㄹ걸 とだけ結びつくので、먹을걸 그랬어 が唯一の文法的な完成形である。먹었어야 그랬어 は成立しない構文で、内容は軽い自己後悔であって義務ではない。',
        ),
      },
      {
        sentence: '환자 상태가 이렇게 나빠지기 전에 의사가 검사를 {}.',
        optionA: '했어야 했어요',
        optionB: '할걸 그랬어요',
        answer: 'a',
        trans: L(
          'The doctor should have done the test before the patient\'s condition got this bad.',
          'El médico debería haber hecho el análisis antes de que el estado del paciente se pusiera así de mal.',
          'Le médecin aurait dû faire l\'examen avant que l\'état du patient n\'empire à ce point.',
          'O médico devia ter feito o exame antes de o estado do paciente ficar tão ruim.',
          'หมอควรจะทำการตรวจก่อนที่อาการของผู้ป่วยจะแย่ขนาดนี้',
          'Dokter seharusnya melakukan tes itu sebelum kondisi pasien menjadi separah ini.',
          'Bác sĩ lẽ ra phải làm xét nghiệm trước khi tình trạng của bệnh nhân trở nên tệ đến mức này.',
          '医者は患者の容態がこれほど悪くなる前に検査をしておくべきだった。',
        ),
        why: L(
          'It judges a third party\'s professional duty with a serious outcome, so 했어야 했어요 fits; -(으)ㄹ걸 그랬다 is strictly first-person self-regret and cannot take a third-person subject like 의사가, making 할걸 그랬어요 ungrammatical here.',
          'Juzga el deber profesional de un tercero con un desenlace grave, así que encaja 했어야 했어요; -(으)ㄹ걸 그랬다 es estrictamente autorreproche en primera persona y no puede llevar un sujeto en tercera persona como 의사가, lo que vuelve agramatical aquí 할걸 그랬어요.',
          'Cela juge le devoir professionnel d\'un tiers avec une conséquence grave, donc 했어야 했어요 convient ; -(으)ㄹ걸 그랬다 est strictement un regret personnel à la première personne et ne peut pas prendre un sujet à la troisième personne comme 의사가, ce qui rend 할걸 그랬어요 agrammatical ici.',
          'Julga o dever profissional de um terceiro com um desfecho grave, então 했어야 했어요 encaixa; -(으)ㄹ걸 그랬다 é estritamente autoarrependimento em primeira pessoa e não pode levar um sujeito em terceira pessoa como 의사가, o que torna 할걸 그랬어요 agramatical aqui.',
          'ประโยคนี้ตัดสินหน้าที่ทางวิชาชีพของบุคคลที่สามพร้อมผลลัพธ์ที่ร้ายแรง จึงเข้ากับ 했어야 했어요; -(으)ㄹ걸 그랬다 เป็นความเสียดายตัวเองในบุรุษที่หนึ่งล้วนๆ และใช้ประธานบุรุษที่สามอย่าง 의사가 ไม่ได้ ทำให้ 할걸 그랬어요 ผิดไวยากรณ์ในที่นี้',
          'Kalimat ini menilai kewajiban profesional pihak ketiga dengan akibat yang serius, jadi 했어야 했어요 cocok; -(으)ㄹ걸 그랬다 murni penyesalan diri orang pertama dan tidak bisa mengambil subjek orang ketiga seperti 의사가, sehingga 할걸 그랬어요 menjadi tidak gramatikal di sini.',
          'Câu đánh giá nghĩa vụ nghề nghiệp của bên thứ ba với hậu quả nghiêm trọng, nên 했어야 했어요 phù hợp; -(으)ㄹ걸 그랬다 chỉ thuần là sự tự tiếc nuối ở ngôi thứ nhất và không thể đi với chủ ngữ ngôi thứ ba như 의사가, khiến 할걸 그랬어요 sai ngữ pháp ở đây.',
          'これは第三者の職業上の義務を深刻な結果とともに判断しているので 했어야 했어요 が合う。-(으)ㄹ걸 그랬다 は厳密に一人称の自己後悔であり、의사가 のような三人称の主語を取れないため、ここでは 할걸 그랬어요 は非文法的になる。',
        ),
      },
    ],
  },
  {
    id: 'daga-go',
    a: '-다가',
    b: '-고',
    note: L(
      'Use -다가 when one action is interrupted or switched mid-stream — you stop or leave X partway and shift to Y, or X is still ongoing when Y happens. Use -고 when X is fully completed first and then Y follows as a separate, sequential action.',
      'Usá -다가 cuando una acción se interrumpe o se cambia a mitad de camino: parás o dejás X a medias y pasás a Y, o X todavía está en curso cuando ocurre Y. Usá -고 cuando X se completa del todo primero y después sigue Y como una acción separada y secuencial.',
      'Utilise -다가 quand une action est interrompue ou changée en cours de route : tu arrêtes ou laisses X à mi-chemin et tu passes à Y, ou X est encore en cours quand Y se produit. Utilise -고 quand X est entièrement achevée d\'abord, puis Y suit comme une action séparée et séquentielle.',
      'Use -다가 quando uma ação é interrompida ou trocada no meio do caminho: você para ou deixa X pela metade e muda para Y, ou X ainda está em andamento quando Y acontece. Use -고 quando X é totalmente concluída primeiro e depois Y segue como uma ação separada e sequencial.',
      'ใช้ -다가 เมื่อการกระทำหนึ่งถูกขัดจังหวะหรือเปลี่ยนกลางคัน คือคุณหยุดหรือละ X ไว้กลางทางแล้วเปลี่ยนไปทำ Y หรือ X ยังดำเนินอยู่ตอนที่ Y เกิดขึ้น ใช้ -고 เมื่อ X เสร็จสมบูรณ์ก่อน แล้ว Y จึงตามมาเป็นการกระทำที่แยกกันและเป็นลำดับ',
      'Gunakan -다가 ketika satu aksi terputus atau beralih di tengah jalan: kamu berhenti atau meninggalkan X separuh jalan lalu beralih ke Y, atau X masih berlangsung ketika Y terjadi. Gunakan -고 ketika X sepenuhnya selesai dulu lalu Y menyusul sebagai aksi terpisah dan berurutan.',
      'Dùng -다가 khi một hành động bị gián đoạn hoặc chuyển đổi giữa chừng: bạn dừng hoặc bỏ dở X rồi chuyển sang Y, hoặc X vẫn đang diễn ra khi Y xảy ra. Dùng -고 khi X hoàn tất hoàn toàn trước rồi Y mới theo sau như một hành động riêng biệt, tuần tự.',
      '-다가 は、ある動作が途中で中断または切り替わるときに使います。X を途中でやめたり離れたりして Y に移る場合や、X がまだ続いている最中に Y が起こる場合です。-고 は、X が完全に先に終わってから、Y が別々の連続した動作として続くときに使います。',
    ),
    items: [
      {
        sentence: '숙제를 {} 너무 졸려서 그냥 잤어요.',
        optionA: '하다가',
        optionB: '하고',
        answer: 'a',
        trans: L(
          'I was doing my homework and then (in the middle of it) got so sleepy that I just went to sleep.',
          'Estaba haciendo la tarea y entonces (en medio de eso) me dio tanto sueño que me fui a dormir nomás.',
          'J\'étais en train de faire mes devoirs et puis (au milieu) j\'ai eu tellement sommeil que je me suis simplement endormi.',
          'Eu estava fazendo a lição de casa e então (no meio dela) fiquei com tanto sono que simplesmente fui dormir.',
          'ฉันกำลังทำการบ้านอยู่ แล้ว (ระหว่างนั้น) ก็ง่วงมากจนนอนหลับไปเลย',
          'Aku sedang mengerjakan PR lalu (di tengah-tengahnya) jadi sangat ngantuk sampai langsung tidur saja.',
          'Tôi đang làm bài tập thì (giữa chừng) buồn ngủ quá nên ngủ luôn.',
          '宿題をしている途中で、眠くなってそのまま寝てしまいました。',
        ),
        why: L(
          'You fell asleep partway through the homework (it was interrupted), so the mid-action switch 다가 fits; 하고 would mean you finished the homework first, which contradicts 졸려서 그냥 잤어요.',
          'Te dormiste a mitad de la tarea (quedó interrumpida), así que el cambio a mitad de acción 다가 encaja; 하고 significaría que primero terminaste la tarea, lo que contradice 졸려서 그냥 잤어요.',
          'Tu t\'es endormi au milieu des devoirs (action interrompue), donc le changement en cours d\'action 다가 convient ; 하고 voudrait dire que tu as d\'abord fini les devoirs, ce qui contredit 졸려서 그냥 잤어요.',
          'Você adormeceu no meio da lição (ela foi interrompida), então a troca no meio da ação 다가 encaixa; 하고 significaria que você terminou a lição primeiro, o que contradiz 졸려서 그냥 잤어요.',
          'คุณหลับไปกลางคันขณะทำการบ้าน (มันถูกขัดจังหวะ) ดังนั้นการสลับกลางการกระทำด้วย 다가 จึงเหมาะ ส่วน 하고 จะหมายความว่าคุณทำการบ้านเสร็จก่อน ซึ่งขัดกับ 졸려서 그냥 잤어요',
          'Kamu tertidur di tengah mengerjakan PR (kegiatannya terputus), jadi peralihan di tengah aksi 다가 cocok; 하고 berarti kamu menyelesaikan PR dulu, yang bertentangan dengan 졸려서 그냥 잤어요.',
          'Bạn ngủ thiếp đi giữa chừng khi làm bài tập (nó bị gián đoạn), nên việc chuyển giữa chừng hành động 다가 là phù hợp; 하고 sẽ có nghĩa bạn làm xong bài tập trước, điều này mâu thuẫn với 졸려서 그냥 잤어요.',
          '宿題の途中で寝てしまった(中断された)ので、行為の途中での切り替えを表す 다가 が合います。하고 だと先に宿題を終えたことになり、졸려서 그냥 잤어요 と矛盾します。',
        ),
      },
      {
        sentence: '매일 아침에 {} 물을 한 잔 마셔요.',
        optionA: '일어나다가',
        optionB: '일어나고',
        answer: 'b',
        trans: L(
          'Every morning I get up and then drink a glass of water.',
          'Todas las mañanas me levanto y después tomo un vaso de agua.',
          'Tous les matins, je me lève et ensuite je bois un verre d\'eau.',
          'Toda manhã eu me levanto e depois bebo um copo de água.',
          'ทุกเช้าฉันตื่นนอนแล้วก็ดื่มน้ำหนึ่งแก้ว',
          'Setiap pagi aku bangun lalu minum segelas air.',
          'Mỗi sáng tôi thức dậy rồi uống một cốc nước.',
          '毎朝起きて、それから水を一杯飲みます。',
        ),
        why: L(
          'Getting up is a punctual, completed action that finishes before drinking water (clean sequence), so 고 is natural; 다가 would wrongly imply you stop halfway through getting up to drink, which makes no sense.',
          'Levantarse es una acción puntual y completada que termina antes de tomar agua (secuencia limpia), así que 고 es natural; 다가 implicaría erróneamente que dejás de levantarte a la mitad para tomar agua, lo que no tiene sentido.',
          'Se lever est une action ponctuelle et achevée qui se termine avant de boire de l\'eau (séquence nette), donc 고 est naturel ; 다가 impliquerait à tort que tu t\'arrêtes en plein milieu de te lever pour boire, ce qui n\'a aucun sens.',
          'Levantar-se é uma ação pontual e concluída que termina antes de beber água (sequência limpa), então 고 é natural; 다가 implicaria erroneamente que você para no meio de levantar-se para beber, o que não faz sentido.',
          'การตื่นนอนเป็นการกระทำที่เกิดขึ้นทันทีและเสร็จสิ้นก่อนการดื่มน้ำ (เป็นลำดับชัดเจน) ดังนั้น 고 จึงเป็นธรรมชาติ ส่วน 다가 จะสื่อผิด ๆ ว่าคุณหยุดกลางคันขณะลุกขึ้นเพื่อไปดื่มน้ำ ซึ่งไม่สมเหตุสมผล',
          'Bangun tidur adalah aksi sesaat yang tuntas dan selesai sebelum minum air (urutan yang bersih), jadi 고 terdengar alami; 다가 akan salah mengisyaratkan bahwa kamu berhenti di tengah-tengah bangun untuk minum, yang tidak masuk akal.',
          'Việc thức dậy là một hành động tức thời và hoàn tất trước khi uống nước (trình tự rõ ràng), nên 고 là tự nhiên; 다가 sẽ ngụ ý sai rằng bạn dừng giữa chừng việc thức dậy để uống nước, điều này vô lý.',
          '起きるのは瞬間的で完了した動作であり、水を飲む前に終わる(きれいな順序)ので 고 が自然です。다가 だと起きる途中でやめて水を飲むことになり、意味をなしません。',
        ),
      },
      {
        sentence: '학교에 {} 친구를 만나서 같이 카페에 갔어요.',
        optionA: '가다가',
        optionB: '가고',
        answer: 'a',
        trans: L(
          'On my way to school I ran into a friend and we went to a cafe together.',
          'De camino a la escuela me crucé con un amigo y nos fuimos juntos a una cafetería.',
          'En allant à l\'école, je suis tombé sur un ami et on est allés ensemble dans un café.',
          'No caminho para a escola encontrei um amigo e fomos juntos a um café.',
          'ระหว่างทางไปโรงเรียน ฉันบังเอิญเจอเพื่อนแล้วก็ไปคาเฟ่ด้วยกัน',
          'Dalam perjalanan ke sekolah aku berpapasan dengan teman lalu kami pergi ke kafe bersama.',
          'Trên đường đến trường tôi tình cờ gặp một người bạn rồi chúng tôi cùng đi đến quán cà phê.',
          '学校に行く途中で友達に会って、一緒にカフェに行きました。',
        ),
        why: L(
          'Meeting the friend happens en route, interrupting/diverting the trip to school, so 다가 (\'on the way\') fits; 가고 would mean you arrived at school first and only then met the friend, which contradicts then heading off to the cafe.',
          'Encontrarse con el amigo pasa en el trayecto, interrumpiendo/desviando el camino a la escuela, así que 다가 (\'de camino\') encaja; 가고 significaría que primero llegaste a la escuela y recién entonces te encontraste con el amigo, lo que contradice el irse después a la cafetería.',
          'Croiser l\'ami se produit en chemin, interrompant/déviant le trajet vers l\'école, donc 다가 (« en chemin ») convient ; 가고 voudrait dire que tu es d\'abord arrivé à l\'école et que tu n\'as rencontré l\'ami qu\'ensuite, ce qui contredit le fait de partir ensuite au café.',
          'Encontrar o amigo acontece no caminho, interrompendo/desviando o trajeto para a escola, então 다가 (\'no caminho\') encaixa; 가고 significaria que você primeiro chegou à escola e só então encontrou o amigo, o que contradiz ir depois para o café.',
          'การเจอเพื่อนเกิดขึ้นระหว่างทาง ทำให้การไปโรงเรียนถูกขัดจังหวะ/เปลี่ยนเส้นทาง ดังนั้น 다가 (\'ระหว่างทาง\') จึงเหมาะ ส่วน 가고 จะหมายความว่าคุณไปถึงโรงเรียนก่อนแล้วจึงเจอเพื่อน ซึ่งขัดกับการที่ไปคาเฟ่ต่อ',
          'Bertemu teman terjadi di tengah jalan, memutus/mengalihkan perjalanan ke sekolah, jadi 다가 (\'di perjalanan\') cocok; 가고 berarti kamu sampai di sekolah dulu baru bertemu teman, yang bertentangan dengan kemudian pergi ke kafe.',
          'Việc gặp bạn xảy ra trên đường, làm gián đoạn/chuyển hướng chuyến đi đến trường, nên 다가 (\'trên đường\') là phù hợp; 가고 sẽ có nghĩa bạn đến trường trước rồi mới gặp bạn, điều này mâu thuẫn với việc sau đó đi đến quán cà phê.',
          '友達に会うのは途中で起こり、学校への道のりを中断/転換させるので 다가 (「途中で」)が合います。가고 だと先に学校に着いてから友達に会ったことになり、その後カフェに向かうという流れと矛盾します。',
        ),
      },
    ],
  },
]
