import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * Extra confusable grammar/ending pairs for TOPIK 5. a/b match grammars-n5.ts
 * 'ko' values verbatim. 2 pairs x 3 two-choice discrimination items, 8-locale
 * trans + why.
 *
 * Drafted + Korean-lens adversarially verified (single-correct-answer crux per
 * item, naturalness, conjugation, 8-locale fidelity). Native (Korean wife)
 * review is the documented final gate.
 */
export const N5_PAIRS_EXTRA: ConfusablePair[] = [
  {
    id: 'giie-tase',
    a: '-기에',
    b: '-(으)ㄴ/는 탓에',
    note: L(
      'Both give a reason, but -기에 is a neutral, observation-based "because" that allows any outcome (good or bad), while -(으)ㄴ/는 탓에 assigns blame and demands a NEGATIVE result ("because of / it\'s the fault of").',
      'Ambos dan una razón, pero -기에 es un "porque" neutral, basado en la observación, que admite cualquier resultado (bueno o malo), mientras que -(으)ㄴ/는 탓에 atribuye culpa y exige un resultado NEGATIVO ("por culpa de").',
      'Les deux donnent une raison, mais -기에 est un « parce que » neutre, fondé sur l\'observation, qui admet n\'importe quel résultat (bon ou mauvais), tandis que -(으)ㄴ/는 탓에 rejette la faute et exige un résultat NÉGATIF (« à cause de / par la faute de »).',
      'Ambos dão um motivo, mas -기에 é um "porque" neutro, baseado em observação, que aceita qualquer resultado (bom ou ruim), enquanto -(으)ㄴ/는 탓에 atribui culpa e exige um resultado NEGATIVO ("por culpa de").',
      'ทั้งคู่บอกเหตุผล แต่ -기에 เป็น "เพราะ" ที่เป็นกลางและอิงสิ่งที่สังเกตเห็น ใช้ได้กับผลทุกแบบ (ดีหรือร้าย) ส่วน -(으)ㄴ/는 탓에 เป็นการโทษและต้องใช้กับผลที่เป็น "ลบ" เท่านั้น',
      'Keduanya memberi alasan, tetapi -기에 adalah "karena" yang netral dan berbasis pengamatan, boleh berakibat apa saja (baik atau buruk), sedangkan -(으)ㄴ/는 탓에 menyalahkan dan menuntut hasil NEGATIF ("gara-gara").',
      'Cả hai đều nêu lý do, nhưng -기에 là "vì" trung lập, dựa trên quan sát, cho phép mọi kết quả (tốt hay xấu), còn -(으)ㄴ/는 탓에 quy trách nhiệm và đòi hỏi kết quả TIÊU CỰC ("tại / do lỗi của").',
      'どちらも理由を表すが、-기에 は観察に基づく中立的な「〜ので」で良い結果も悪い結果も取れる。-(으)ㄴ/는 탓에 は責任を負わせる表現で、必ず「悪い結果」を要求する（〜せいで）。',
    ),
    items: [
      {
        sentence: '준비를 게을리한 {} 시험에 떨어졌어요.',
        optionA: '기에',
        optionB: '탓에',
        answer: 'b',
        trans: L(
          'Because I was lazy about preparing, I failed the exam.',
          'Por culpa de descuidar la preparación, suspendí el examen.',
          'À cause de ma négligence dans la préparation, j\'ai échoué à l\'examen.',
          'Por culpa de relaxar na preparação, fui reprovado na prova.',
          'เพราะเตรียมตัวอย่างขี้เกียจ ฉันเลยสอบตก',
          'Gara-gara malas mempersiapkan diri, saya gagal ujian.',
          'Tại lười chuẩn bị nên tôi đã trượt kỳ thi.',
          '準備を怠ったせいで試験に落ちました。',
        ),
        why: L(
          'The outcome (failing) is negative and the speaker blames their own laziness, so 탓에 fits; the neutral 기에 attaches to a verb stem (게을리하기에), not to the determiner 게을리한, so 기에 is grammatically wrong here too.',
          'El resultado (suspender) es negativo y el hablante se culpa de su pereza, así que va 탓에; el neutral 기에 se une al raíz verbal (게을리하기에), no al determinante 게을리한, así que aquí 기에 también es agramatical.',
          'Le résultat (échouer) est négatif et le locuteur s\'en prend à sa propre paresse, donc 탓에 convient ; le neutre 기에 se joint au radical verbal (게을리하기에), pas au déterminant 게을리한, donc 기에 est ici aussi agrammatical.',
          'O resultado (reprovar) é negativo e o falante culpa a própria preguiça, então cabe 탓에; o neutro 기에 liga-se ao radical verbal (게을리하기에), não ao determinante 게을리한, então 기에 também é agramatical aqui.',
          'ผลลัพธ์ (สอบตก) เป็นลบและผู้พูดโทษความขี้เกียจของตัวเอง จึงใช้ 탓에; 기에 ที่เป็นกลางต่อท้ายรากกริยา (게을리하기에) ไม่ใช่รูปขยายนาม 게을리한 ดังนั้น 기에 ในที่นี้จึงผิดไวยากรณ์ด้วย',
          'Hasilnya (gagal) negatif dan penutur menyalahkan kemalasannya sendiri, jadi 탓에 cocok; 기에 yang netral melekat pada akar verba (게을리하기에), bukan pada bentuk determinatif 게을리한, jadi 기에 di sini juga tidak gramatikal.',
          'Kết quả (trượt) là tiêu cực và người nói tự trách sự lười biếng của mình, nên dùng 탓에; 기에 trung lập gắn vào thân động từ (게을리하기에), không gắn vào dạng định ngữ 게을리한, nên 기에 ở đây cũng sai ngữ pháp.',
          '結果（不合格）は否定的で、話者が自分の怠慢を責めているので 탓에 が適切。中立的な 기에 は動詞語幹（게을리하기에）に付き、連体形 게을리한 には付かないので、ここでは 기에 は文法的にも誤り。',
        ),
      },
      {
        sentence: '날씨가 좋{} 오래 산책했어요.',
        optionA: '기에',
        optionB: '은 탓에',
        answer: 'a',
        trans: L(
          'Since the weather was so nice, I took a long walk.',
          'Como el clima estaba tan bueno, paseé largo rato.',
          'Comme il faisait si beau, je me suis longuement promené.',
          'Como o tempo estava tão bom, passeei por um bom tempo.',
          'เพราะอากาศดีมาก ฉันเลยเดินเล่นนาน',
          'Karena cuacanya begitu bagus, saya berjalan-jalan lama.',
          'Vì thời tiết đẹp quá nên tôi đã đi dạo lâu.',
          '天気がとても良かったので、長く散歩しました。',
        ),
        why: L(
          'The reason (nice weather) and result (a long, pleasant walk) are both positive, so neutral 기에 fits; 탓에 forces a negative/blaming reading and clashes with this pleasant outcome.',
          'La razón (buen clima) y el resultado (un paseo largo y agradable) son positivos, así que va el neutral 기에; 탓에 obliga a una lectura negativa/de culpa y choca con este resultado agradable.',
          'La raison (beau temps) et le résultat (une longue promenade agréable) sont positifs, donc le neutre 기에 convient ; 탓에 impose une lecture négative/accusatrice qui jure avec ce résultat agréable.',
          'A razão (tempo bom) e o resultado (um passeio longo e agradável) são positivos, então cabe o neutro 기에; 탓에 força uma leitura negativa/de culpa e destoa deste resultado agradável.',
          'เหตุผล (อากาศดี) และผล (เดินเล่นนานอย่างเพลิดเพลิน) ล้วนเป็นบวก จึงใช้ 기에 ที่เป็นกลาง; 탓에 บังคับให้เป็นความหมายเชิงลบ/โทษกัน ซึ่งขัดกับผลที่ดีนี้',
          'Alasan (cuaca bagus) dan hasilnya (jalan-jalan lama yang menyenangkan) sama-sama positif, jadi 기에 yang netral cocok; 탓에 memaksa makna negatif/menyalahkan yang bertabrakan dengan hasil menyenangkan ini.',
          'Lý do (thời tiết đẹp) và kết quả (đi dạo lâu, dễ chịu) đều tích cực, nên dùng 기에 trung lập; 탓에 ép một cách hiểu tiêu cực/đổ lỗi, xung khắc với kết quả dễ chịu này.',
          '理由（良い天気）も結果（長く心地よい散歩）も肯定的なので中立的な 기에 が適切。탓에 は否定・責任の読みを強い、この好ましい結果と矛盾する。',
        ),
      },
      {
        sentence: '옆집이 시끄러운 {} 한숨도 못 잤어요.',
        optionA: '기에',
        optionB: '탓에',
        answer: 'b',
        trans: L(
          'Because the neighbors were noisy, I couldn\'t sleep a wink.',
          'Por culpa de que los vecinos hicieron ruido, no pegué ojo.',
          'À cause des voisins bruyants, je n\'ai pas fermé l\'œil.',
          'Por culpa dos vizinhos barulhentos, não preguei o olho.',
          'เพราะบ้านข้าง ๆ เสียงดัง ฉันเลยนอนไม่หลับเลย',
          'Gara-gara tetangga berisik, saya tak bisa tidur sama sekali.',
          'Tại nhà bên cạnh ồn ào nên tôi không chợp mắt nổi.',
          '隣の家がうるさかったせいで、一睡もできませんでした。',
        ),
        why: L(
          'The result (not sleeping a wink) is negative and is blamed on the noisy neighbors, so 탓에 fits; the neutral 기에 attaches to a stem (시끄럽기에), not to the determiner 시끄러운, so 기에 is ungrammatical here and also drops the "their fault" blame.',
          'El resultado (no dormir nada) es negativo y se culpa a los vecinos ruidosos, así que va 탓에; el neutral 기에 se une a la raíz (시끄럽기에), no al determinante 시끄러운, así que aquí 기에 es agramatical y además pierde el reproche de "es culpa de ellos".',
          'Le résultat (ne pas dormir du tout) est négatif et imputé aux voisins bruyants, donc 탓에 convient ; le neutre 기에 se joint au radical (시끄럽기에), pas au déterminant 시끄러운, donc 기에 est ici agrammatical et perd en plus le reproche « c\'est leur faute ».',
          'O resultado (não dormir nada) é negativo e culpa os vizinhos barulhentos, então cabe 탓에; o neutro 기에 liga-se ao radical (시끄럽기에), não ao determinante 시끄러운, então 기에 é agramatical aqui e ainda perde a culpa de "é culpa deles".',
          'ผลลัพธ์ (นอนไม่หลับเลย) เป็นลบและโทษเพื่อนบ้านที่เสียงดัง จึงใช้ 탓에; 기에 ที่เป็นกลางต่อท้ายราก (시끄럽기에) ไม่ใช่รูปขยายนาม 시끄러운 ดังนั้น 기에 ในที่นี้จึงผิดไวยากรณ์และยังทำให้การโทษว่า "เป็นความผิดของพวกเขา" หายไป',
          'Hasilnya (tak tidur sama sekali) negatif dan menyalahkan tetangga yang berisik, jadi 탓에 cocok; 기에 yang netral melekat pada akar (시끄럽기에), bukan pada bentuk determinatif 시끄러운, jadi 기에 di sini tidak gramatikal dan juga menghilangkan tudingan "salah mereka".',
          'Kết quả (không ngủ được chút nào) là tiêu cực và đổ lỗi cho hàng xóm ồn ào, nên dùng 탓에; 기에 trung lập gắn vào thân từ (시끄럽기에), không gắn vào dạng định ngữ 시끄러운, nên 기에 ở đây sai ngữ pháp và còn làm mất ý "lỗi tại họ".',
          '結果（一睡もできない）は否定的で、うるさい隣家のせいにしているので 탓에 が適切。中立的な 기에 は語幹（시끄럽기에）に付き、連体形 시끄러운 には付かないので、ここでは 기에 は文法的に誤りで、さらに「彼らのせい」という非難も消えてしまう。',
        ),
      },
    ],
  },
  {
    id: 'dagohaeseo-dagohaedo',
    a: '-다고 해서',
    b: '-다고 해도',
    note: L(
      'Both quote reported info, but -다고 해서 means "because (they) say ..." and the main clause is a CONSISTENT consequence of trusting that report, while -다고 해도 means "even if (they) say ..." and the main clause CONTRASTS with / resists the report (concession).',
      'Ambos citan información reportada, pero -다고 해서 significa "porque (dicen) que ..." y la oración principal es una consecuencia COHERENTE con creer ese dato, mientras que -다고 해도 significa "aunque digan que ..." y la principal CONTRASTA con / se resiste al dato (concesión).',
      'Les deux rapportent une information, mais -다고 해서 signifie « parce qu\'on dit que ... » et la principale est une conséquence COHÉRENTE avec le fait de croire ce propos, tandis que -다고 해도 signifie « même si on dit que ... » et la principale CONTRASTE avec / résiste à ce propos (concession).',
      'Ambos citam informação relatada, mas -다고 해서 significa "porque dizem que ..." e a oração principal é uma consequência COERENTE com acreditar nisso, enquanto -다고 해도 significa "mesmo que digam que ..." e a principal CONTRASTA com / resiste ao relato (concessão).',
      'ทั้งคู่อ้างข้อมูลที่ได้ยินมา แต่ -다고 해서 แปลว่า "เพราะได้ยินว่า ..." และประโยคหลักเป็นผลที่ "สอดคล้อง" กับการเชื่อข้อมูลนั้น ส่วน -다고 해도 แปลว่า "แม้จะบอกว่า ..." และประโยคหลัก "ขัดแย้ง" กับ/ต้านข้อมูลนั้น (การยอมรับแบบมีข้อแม้)',
      'Keduanya mengutip info yang didengar, tetapi -다고 해서 berarti "karena katanya ..." dan klausa utama adalah akibat yang SEJALAN dengan memercayai info itu, sedangkan -다고 해도 berarti "meskipun katanya ..." dan klausa utama BERTENTANGAN dengan / menolak info itu (konsesi).',
      'Cả hai đều trích thông tin nghe được, nhưng -다고 해서 nghĩa là "vì nghe nói ..." và mệnh đề chính là hệ quả NHẤT QUÁN với việc tin lời đó, còn -다고 해도 nghĩa là "dù có nói rằng ..." và mệnh đề chính TƯƠNG PHẢN với / chống lại lời đó (nhượng bộ).',
      'どちらも伝聞を引用するが、-다고 해서 は「〜だと言うので」で、主節はその情報を信じた「一致した」帰結になる。-다고 해도 は「〜だと言われても」で、主節はその情報に「反する」内容になる（譲歩）。',
    ),
    items: [
      {
        sentence: '아무리 바쁘{} 식사는 거르지 마세요.',
        optionA: '다고 해서',
        optionB: '다고 해도',
        answer: 'b',
        trans: L(
          'No matter how busy you say you are, don\'t skip meals.',
          'Por muy ocupado que digas que estás, no te saltes las comidas.',
          'Aussi occupé que tu dises être, ne saute pas de repas.',
          'Por mais ocupado que diga estar, não pule refeições.',
          'ต่อให้บอกว่ายุ่งแค่ไหน ก็อย่าอดอาหารนะ',
          'Sesibuk apa pun katamu, jangan lewatkan makan.',
          'Dù có nói bận đến đâu thì cũng đừng bỏ bữa.',
          'どんなに忙しいと言っても、食事は抜かないでください。',
        ),
        why: L(
          'The 아무리 ... frame and the main clause (don\'t skip meals) RESIST the claim of being busy, so the concessive 다고 해도 fits; 다고 해서 would wrongly make busyness the reason for the command.',
          'El marco 아무리 ... y la oración principal (no te saltes las comidas) SE RESISTEN a la afirmación de estar ocupado, así que va el concesivo 다고 해도; 다고 해서 haría erróneamente que la ocupación fuera la razón de la orden.',
          'Le cadre 아무리 ... et la principale (ne saute pas de repas) RÉSISTENT à l\'affirmation d\'être occupé, donc le concessif 다고 해도 convient ; 다고 해서 ferait à tort de l\'occupation la raison de l\'ordre.',
          'A moldura 아무리 ... e a oração principal (não pule refeições) RESISTEM à alegação de estar ocupado, então cabe o concessivo 다고 해도; 다고 해서 faria erradamente da ocupação o motivo da ordem.',
          'โครง 아무리 ... และประโยคหลัก (อย่าอดอาหาร) "ต้าน" คำกล่าวอ้างว่ายุ่ง จึงใช้ 다고 해도 แบบยอมรับมีข้อแม้; 다고 해서 จะทำให้ความยุ่งกลายเป็นเหตุผลของคำสั่งอย่างผิด ๆ',
          'Kerangka 아무리 ... dan klausa utama (jangan lewatkan makan) MENOLAK klaim sibuk, jadi konsesif 다고 해도 cocok; 다고 해서 keliru menjadikan kesibukan sebagai alasan perintah.',
          'Khung 아무리 ... và mệnh đề chính (đừng bỏ bữa) CHỐNG LẠI lời nói bận, nên dùng 다고 해도 nhượng bộ; 다고 해서 sẽ sai khi biến sự bận rộn thành lý do của mệnh lệnh.',
          '아무리 ... の枠組みと主節（食事を抜くな）は「忙しい」という主張に反するので、譲歩の 다고 해도 が適切。다고 해서 だと忙しさが命令の理由になってしまい誤り。',
        ),
      },
      {
        sentence: '그 약이 효과가 좋{} 한 통을 샀어요.',
        optionA: '다고 해서',
        optionB: '다고 해도',
        answer: 'a',
        trans: L(
          'Because they said that medicine works well, I bought a bottle.',
          'Como dijeron que esa medicina funciona bien, compré un frasco.',
          'Comme on disait que ce médicament est efficace, j\'en ai acheté un flacon.',
          'Como disseram que esse remédio funciona bem, comprei um frasco.',
          'เพราะได้ยินว่ายานั้นได้ผลดี ฉันเลยซื้อมาหนึ่งขวด',
          'Karena katanya obat itu manjur, saya beli satu botol.',
          'Vì nghe nói thuốc đó hiệu quả nên tôi đã mua một lọ.',
          'その薬が効くと言うので、一瓶買いました。',
        ),
        why: L(
          'Buying the medicine is a CONSISTENT consequence of trusting the report that it works, so causal 다고 해서 fits; 다고 해도 (concession) would expect the main clause to resist the report (e.g. "I won\'t buy it").',
          'Comprar la medicina es una consecuencia COHERENTE con creer el dato de que funciona, así que va el causal 다고 해서; 다고 해도 (concesivo) esperaría que la principal se resistiera al dato (p. ej. "no la compro").',
          'Acheter le médicament est une conséquence COHÉRENTE avec le fait de croire qu\'il marche, donc le causal 다고 해서 convient ; 다고 해도 (concessif) attendrait que la principale résiste au propos (par ex. « je ne l\'achète pas »).',
          'Comprar o remédio é uma consequência COERENTE com acreditar que funciona, então cabe o causal 다고 해서; 다고 해도 (concessivo) esperaria que a principal resistisse ao relato (ex.: "não compro").',
          'การซื้อยาเป็นผลที่ "สอดคล้อง" กับการเชื่อว่ามันได้ผล จึงใช้ 다고 해서 เชิงเหตุผล; 다고 해도 (ยอมรับมีข้อแม้) จะคาดว่าประโยคหลักต้านข้อมูล (เช่น "ไม่ซื้อ")',
          'Membeli obat adalah akibat yang SEJALAN dengan memercayai bahwa obat itu manjur, jadi 다고 해서 kausal cocok; 다고 해도 (konsesi) menuntut klausa utama menolak info itu (mis. "tidak saya beli").',
          'Việc mua thuốc là hệ quả NHẤT QUÁN với việc tin lời nói thuốc hiệu quả, nên dùng 다고 해서 nhân quả; 다고 해도 (nhượng bộ) sẽ đòi mệnh đề chính chống lại lời đó (vd. "tôi không mua").',
          '薬を買うのは「効く」という伝聞を信じた一致した帰結なので、因果の 다고 해서 が適切。다고 해도（譲歩）なら主節は伝聞に反する内容（例：買わない）になるはず。',
        ),
      },
      {
        sentence: '값이 좀 비싸{} 품질이 좋으면 살 가치가 있어요.',
        optionA: '다고 해서',
        optionB: '다고 해도',
        answer: 'b',
        trans: L(
          'Even if they say it\'s a bit pricey, if the quality is good it\'s worth buying.',
          'Aunque digan que es un poco caro, si la calidad es buena vale la pena comprarlo.',
          'Même si on dit que c\'est un peu cher, si la qualité est bonne, ça vaut la peine de l\'acheter.',
          'Mesmo que digam que é um pouco caro, se a qualidade for boa, vale a pena comprar.',
          'แม้จะบอกว่าราคาแพงไปหน่อย แต่ถ้าคุณภาพดีก็คุ้มที่จะซื้อ',
          'Meskipun katanya agak mahal, kalau kualitasnya bagus tetap layak dibeli.',
          'Dù có nói là hơi đắt, nếu chất lượng tốt thì vẫn đáng mua.',
          '少し高いと言われても、品質が良ければ買う価値があります。',
        ),
        why: L(
          'The main clause grants worth DESPITE the reported high price, a contrast that needs concessive 다고 해도; 다고 해서 would mean "because it\'s pricey ...", which contradicts the positive "worth buying" verdict.',
          'La oración principal concede valor A PESAR del precio alto reportado, un contraste que exige el concesivo 다고 해도; 다고 해서 significaría "porque es caro ...", lo que contradice el veredicto positivo de "vale la pena".',
          'La principale accorde de la valeur MALGRÉ le prix élevé rapporté, un contraste qui exige le concessif 다고 해도 ; 다고 해서 voudrait dire « parce que c\'est cher ... », ce qui contredit le verdict positif « ça vaut la peine ».',
          'A oração principal concede valor APESAR do preço alto relatado, um contraste que exige o concessivo 다고 해도; 다고 해서 significaria "porque é caro ...", o que contradiz o veredicto positivo de "vale a pena".',
          'ประโยคหลักยอมรับว่าคุ้มค่า "ทั้งที่" มีรายงานว่าราคาแพง เป็นการขัดแย้งที่ต้องใช้ 다고 해도 แบบยอมรับมีข้อแม้; 다고 해서 จะแปลว่า "เพราะแพง ..." ซึ่งขัดกับคำตัดสินเชิงบวกว่า "คุ้มที่จะซื้อ"',
          'Klausa utama mengakui kelayakannya MESKIPUN harganya dikabarkan tinggi, kontras yang menuntut konsesif 다고 해도; 다고 해서 berarti "karena mahal ...", yang bertentangan dengan vonis positif "layak dibeli".',
          'Mệnh đề chính khẳng định đáng mua BẤT CHẤP lời nói giá cao, một sự tương phản cần 다고 해도 nhượng bộ; 다고 해서 sẽ có nghĩa "vì đắt ...", mâu thuẫn với phán định tích cực "đáng mua".',
          '主節は「高い」という伝聞にもかかわらず価値を認めており、この対比には譲歩の 다고 해도 が必要。다고 해서 だと「高いので…」となり、肯定的な「買う価値がある」という結論と矛盾する。',
        ),
      },
    ],
  },
]