import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK 5 confusable grammar/ending pairs. a/b match grammars-n*.ts kos
 * verbatim. Each pair: a contrast note + 3 single-answer discrimination items,
 * 8-locale note/trans/why.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow
 * (single-correct-answer crux, naturalness, conjugation, 8-locale fidelity).
 * Native (Korean wife) review is the documented final gate.
 */
export const N5_PAIRS: ConfusablePair[] = [
  {
    id: 'dagohaeseo-haedo',
    a: '-다고 해서',
    b: '-다고 해도',
    note: L(
      'Use -다고 해서 to set up a premise you then DENY — almost always with a negative result clause like "...다 ~은/는 것은 아니다" ("just because X, it doesn\'t follow that..."). Use -다고 해도 for a concession ("even if one says/supposes X") that still GRANTS the following clause.',
      'Usá -다고 해서 para plantear una premisa que luego NEGÁS — casi siempre con una cláusula de resultado negativo como \'...다 ~은/는 것은 아니다\' (\'solo porque X, no se sigue que...\'). Usá -다고 해도 para una concesión (\'aun si se dice/supone X\') que de todas formas CONCEDE la cláusula siguiente.',
      'Utilise -다고 해서 pour poser une prémisse que tu NIES ensuite — presque toujours avec une proposition de résultat négatif comme \'...다 ~은/는 것은 아니다\' (\'ce n\'est pas parce que X qu\'il s\'ensuit que...\'). Utilise -다고 해도 pour une concession (\'même si l\'on dit/suppose X\') qui ACCORDE quand même la proposition suivante.',
      'Use -다고 해서 para estabelecer uma premissa que você depois NEGA — quase sempre com uma oração de resultado negativo como \'...다 ~은/는 것은 아니다\' (\'só porque X, não se segue que...\'). Use -다고 해도 para uma concessão (\'mesmo que se diga/suponha X\') que ainda assim CONCEDE a oração seguinte.',
      'ใช้ -다고 해서 เพื่อตั้งสมมติฐานที่คุณจะ ปฏิเสธ ในภายหลัง — เกือบทุกครั้งจะมาพร้อมอนุประโยคผลลัพธ์เชิงปฏิเสธ เช่น \'...다 ~은/는 것은 아니다\' (\'แค่เพราะ X ก็ไม่ได้หมายความว่า...\') ใช้ -다고 해도 สำหรับการยอมความ (\'แม้จะบอก/สมมติว่า X\') ที่ยังคง ยอมรับ อนุประโยคที่ตามมา',
      'Gunakan -다고 해서 untuk menetapkan premis yang kemudian kamu SANGKAL — hampir selalu dengan klausa hasil negatif seperti \'...다 ~은/는 것은 아니다\' (\'hanya karena X, bukan berarti...\'). Gunakan -다고 해도 untuk konsesi (\'bahkan jika dikatakan/diandaikan X\') yang tetap MEMBERIKAN klausa berikutnya.',
      'Dùng -다고 해서 để nêu ra một tiền đề mà bạn sau đó PHỦ NHẬN — hầu như luôn đi với mệnh đề kết quả phủ định như \'...다 ~은/는 것은 아니다\' (\'chỉ vì X, không có nghĩa là...\'). Dùng -다고 해도 cho một sự nhượng bộ (\'dù có nói/giả sử là X\') mà vẫn CHẤP NHẬN mệnh đề theo sau.',
      '-다고 해서 は、後で 否定する 前提を立てるときに使う — ほぼ必ず \'...다 ~은/는 것은 아니다\'（「Xだからといって、〜とは限らない」）のような否定的な結果節を伴う。-다고 해도 は、それでも次の節を 容認する 譲歩（「Xと言っても／仮定しても」）に使う。',
    ),
    items: [
      {
        sentence: '비싸{} 다 좋은 건 아니에요.',
        optionA: '비싸다고 해서',
        optionB: '비싸다고 해도',
        answer: 'a',
        trans: L(
          'Just because something is expensive doesn\'t mean it\'s all good.',
          'Que algo sea caro no significa que sea todo bueno.',
          'Ce n\'est pas parce qu\'une chose est chère qu\'elle est forcément bonne.',
          'Só porque algo é caro não significa que seja tudo bom.',
          'แค่เพราะของแพงก็ไม่ได้แปลว่ามันจะดีไปหมด',
          'Hanya karena sesuatu mahal, bukan berarti semuanya bagus.',
          'Chỉ vì đắt tiền không có nghĩa là mọi thứ đều tốt.',
          '値段が高いからといって、すべてが良いわけではない。',
        ),
        why: L(
          'The negative result clause \'다 ~ 건 아니다\' (denying the premise) is the signature of -다고 해서. -다고 해도 expects a granted result, so it clashes with this \'not necessarily\' denial pattern.',
          'La cláusula de resultado negativo \'다 ~ 건 아니다\' (que niega la premisa) es la firma de -다고 해서. -다고 해도 espera un resultado concedido, así que choca con este patrón de negación de \'no necesariamente\'.',
          'La proposition de résultat négatif \'다 ~ 건 아니다\' (qui nie la prémisse) est la signature de -다고 해서. -다고 해도 attend un résultat accordé, donc il entre en conflit avec ce schéma de négation \'pas forcément\'.',
          'A oração de resultado negativo \'다 ~ 건 아니다\' (que nega a premissa) é a marca registrada de -다고 해서. -다고 해도 espera um resultado concedido, então colide com esse padrão de negação \'não necessariamente\'.',
          'อนุประโยคผลลัพธ์เชิงปฏิเสธ \'다 ~ 건 아니다\' (ที่ปฏิเสธสมมติฐาน) คือเอกลักษณ์ของ -다고 해서 ส่วน -다고 해도 คาดหวังผลลัพธ์ที่ยอมรับ จึงขัดกับรูปแบบการปฏิเสธ \'ไม่จำเป็นเสมอไป\' นี้',
          'Klausa hasil negatif \'다 ~ 건 아니다\' (yang menyangkal premis) adalah ciri khas -다고 해서. -다고 해도 mengharapkan hasil yang diberikan, sehingga bentrok dengan pola penyangkalan \'tidak selalu\' ini.',
          'Mệnh đề kết quả phủ định \'다 ~ 건 아니다\' (phủ nhận tiền đề) là dấu hiệu đặc trưng của -다고 해서. -다고 해도 mong đợi một kết quả được chấp nhận, nên xung đột với mẫu phủ định \'không hẳn là\' này.',
          '前提を否定する否定的な結果節 \'다 ~ 건 아니다\' は -다고 해서 の特徴である。-다고 해도 は容認される結果を期待するため、この「必ずしも〜ではない」という否定パターンとは衝突する。',
        ),
      },
      {
        sentence: '아무리 바쁘{} 아침은 꼭 먹어야죠.',
        optionA: '바쁘다고 해서',
        optionB: '바쁘다고 해도',
        answer: 'b',
        trans: L(
          'No matter how busy you are, you really should eat breakfast.',
          'Por más ocupado que estés, de verdad deberías desayunar.',
          'Même si tu es très occupé, tu devrais vraiment prendre un petit-déjeuner.',
          'Por mais ocupado que você esteja, você realmente deveria tomar café da manhã.',
          'ไม่ว่าจะยุ่งแค่ไหน ก็ควรกินอาหารเช้าจริง ๆ',
          'Sesibuk apa pun, kamu benar-benar harus sarapan.',
          'Dù bận đến đâu thì bạn cũng thực sự nên ăn sáng.',
          'どんなに忙しくても、朝ごはんは本当に食べたほうがいい。',
        ),
        why: L(
          '\'아무리\' pairs only with a concessive ending and a still-granted next clause (\'you still must...\'), which needs -다고 해도. \'아무리 ...해서\' is ungrammatical because -다고 해서 sets up a denial that never arrives.',
          '\'아무리\' se combina solo con una terminación concesiva y una cláusula siguiente que se concede igualmente (\'aun así debés...\'), lo cual requiere -다고 해도. \'아무리 ...해서\' es agramatical porque -다고 해서 plantea una negación que nunca llega.',
          '\'아무리\' ne se combine qu\'avec une terminaison concessive et une proposition suivante qui est tout de même accordée (\'tu dois quand même...\'), ce qui exige -다고 해도. \'아무리 ...해서\' est agrammatical parce que -다고 해서 pose une négation qui n\'arrive jamais.',
          '\'아무리\' combina apenas com uma terminação concessiva e uma oração seguinte que mesmo assim é concedida (\'você ainda assim deve...\'), o que exige -다고 해도. \'아무리 ...해서\' é agramatical porque -다고 해서 estabelece uma negação que nunca chega.',
          '\'아무리\' จับคู่ได้เฉพาะกับท้ายประโยคแบบยอมความและอนุประโยคถัดไปที่ยังคงยอมรับ (\'คุณก็ยังต้อง...\') ซึ่งต้องใช้ -다고 해도 ส่วน \'아무리 ...해서\' ผิดไวยากรณ์เพราะ -다고 해서 ตั้งการปฏิเสธที่ไม่เคยมาถึง',
          '\'아무리\' hanya berpasangan dengan akhiran konsesif dan klausa berikutnya yang tetap diberikan (\'kamu tetap harus...\'), yang memerlukan -다고 해도. \'아무리 ...해서\' tidak gramatikal karena -다고 해서 menyiapkan penyangkalan yang tidak pernah datang.',
          '\'아무리\' chỉ đi cùng với một đuôi nhượng bộ và một mệnh đề tiếp theo vẫn được chấp nhận (\'bạn vẫn phải...\'), điều này cần -다고 해도. \'아무리 ...해서\' là sai ngữ pháp vì -다고 해서 thiết lập một sự phủ định không bao giờ đến.',
          '\'아무리\' は譲歩の語尾と、それでも容認される次の節（「それでも〜しなければならない」）とのみ結びつき、これには -다고 해도 が必要である。\'아무리 ...해서\' は非文法的である。なぜなら -다고 해서 は決して現れない否定を設定するからである。',
        ),
      },
      {
        sentence: '친구가 그 식당이 맛있{} 한번 가 보려고 해요.',
        optionA: '다고 해서',
        optionB: '다고 해도',
        answer: 'a',
        trans: L(
          'My friend said that restaurant is good, so I\'m going to try going there once.',
          'Mi amiga dijo que ese restaurante es bueno, así que voy a probar ir una vez.',
          'Mon amie a dit que ce restaurant est bon, alors je vais essayer d\'y aller une fois.',
          'Minha amiga disse que aquele restaurante é bom, então vou tentar ir lá uma vez.',
          'เพื่อนบอกว่าร้านอาหารนั้นอร่อย เลยจะลองไปสักครั้ง',
          'Temanku bilang restoran itu enak, jadi aku akan coba ke sana sekali.',
          'Bạn tôi nói nhà hàng đó ngon, nên tôi sẽ thử đến đó một lần.',
          '友達があのレストランがおいしいと言ったので、一度行ってみようと思う。',
        ),
        why: L(
          'The quoted premise is the REASON the speaker acts (so → goes), which is -다고 해서. -다고 해도 (\'even if she says it\'s good\') would presuppose doubt or a contrasting outcome, contradicting the trusting \'I\'ll try it\' clause that simply follows from the recommendation.',
          'La premisa citada es la RAZÓN por la que el hablante actúa (así que → va), lo cual es -다고 해서. -다고 해도 (\'aunque ella diga que es bueno\') presupondría duda o un resultado contrastante, contradiciendo la cláusula confiada \'voy a probarlo\' que simplemente se desprende de la recomendación.',
          'La prémisse citée est la RAISON pour laquelle le locuteur agit (alors → y va), ce qui est -다고 해서. -다고 해도 (\'même si elle dit que c\'est bon\') présupposerait un doute ou un résultat contrasté, contredisant la proposition confiante \'je vais essayer\' qui découle simplement de la recommandation.',
          'A premissa citada é a RAZÃO pela qual o falante age (então → vai), o que é -다고 해서. -다고 해도 (\'mesmo que ela diga que é bom\') pressuporia dúvida ou um resultado contrastante, contradizendo a oração confiante \'vou experimentar\' que simplesmente decorre da recomendação.',
          'สมมติฐานที่ยกมาคือ เหตุผล ที่ผู้พูดลงมือทำ (เลย → ไป) ซึ่งคือ -다고 해서 ส่วน -다고 해도 (\'ถึงแม้เธอจะบอกว่าอร่อย\') จะสื่อถึงความสงสัยหรือผลลัพธ์ที่ตรงข้าม ขัดกับอนุประโยคที่ไว้ใจว่า \'จะลองไป\' ซึ่งสืบเนื่องมาจากคำแนะนำโดยตรง',
          'Premis yang dikutip adalah ALASAN penutur bertindak (jadi → pergi), yaitu -다고 해서. -다고 해도 (\'meskipun dia bilang itu enak\') akan mengandaikan keraguan atau hasil yang bertentangan, bertentangan dengan klausa penuh percaya \'aku akan coba\' yang sekadar mengikuti dari rekomendasi tersebut.',
          'Tiền đề được trích dẫn là LÝ DO khiến người nói hành động (nên → đi), đó là -다고 해서. -다고 해도 (\'dù cô ấy nói là ngon\') sẽ giả định sự nghi ngờ hoặc một kết quả trái ngược, mâu thuẫn với mệnh đề tin tưởng \'tôi sẽ thử đến đó\' vốn chỉ đơn giản nối tiếp từ lời gợi ý.',
          '引用された前提は話し手が行動する 理由 である（だから→行く）。これが -다고 해서 である。-다고 해도（「おいしいと言っても」）は疑念や対照的な結果を前提とし、推薦から素直に導かれる「行ってみよう」という信頼の節と矛盾する。',
        ),
      },
    ],
  },
  {
    id: 'tase-inhae',
    a: '-(으)ㄴ/는 탓에',
    b: '-(으)로 인해(서)',
    note: L(
      'Both mark cause, but -(으)ㄴ/는 탓에 assigns BLAME for a negative cause that produces a bad result (often personal: oversleeping, a mistake), while -(으)로 인해(서) is a neutral, formal cause-effect for any (often impersonal) cause, common in news and writing (heavy rain, an accident). Use 탓에 when you mean "it\'s because of [someone/something]\'s fault," and 으로 인해 when you simply state an objective cause.',
      'Ambas marcan causa, pero -(으)ㄴ/는 탓에 atribuye la CULPA a una causa negativa que produce un mal resultado (a menudo personal: quedarse dormido, un error), mientras que -(으)로 인해(서) es una relación causa-efecto neutra y formal para cualquier causa (a menudo impersonal), común en noticias y textos escritos (lluvia fuerte, un accidente). Usá 탓에 cuando querés decir "es por culpa de [alguien/algo]", y 으로 인해 cuando simplemente enunciás una causa objetiva.',
      'Les deux marquent la cause, mais -(으)ㄴ/는 탓에 attribue la FAUTE à une cause négative qui produit un mauvais résultat (souvent personnel : avoir trop dormi, une erreur), tandis que -(으)로 인해(서) est une relation cause-effet neutre et formelle pour n\'importe quelle cause (souvent impersonnelle), courante dans les nouvelles et à l\'écrit (fortes pluies, un accident). Emploie 탓에 quand tu veux dire « c\'est à cause de la faute de [quelqu\'un/quelque chose] », et 으로 인해 quand tu énonces simplement une cause objective.',
      'Ambas marcam causa, mas -(으)ㄴ/는 탓에 atribui a CULPA a uma causa negativa que produz um mau resultado (muitas vezes pessoal: dormir demais, um erro), enquanto -(으)로 인해(서) é uma relação causa-efeito neutra e formal para qualquer causa (muitas vezes impessoal), comum em notícias e textos escritos (chuva forte, um acidente). Use 탓에 quando você quer dizer "é por culpa de [alguém/algo]", e 으로 인해 quando você simplesmente enuncia uma causa objetiva.',
      'ทั้งสองตัวบอกสาเหตุ แต่ -(으)ㄴ/는 탓에 เป็นการโยนความผิดให้กับสาเหตุเชิงลบที่ก่อให้เกิดผลร้าย (มักเป็นเรื่องส่วนตัว เช่น นอนตื่นสาย ความผิดพลาด) ส่วน -(으)로 인해(서) เป็นความสัมพันธ์เหตุ-ผลที่เป็นกลางและเป็นทางการ ใช้กับสาเหตุใดก็ได้ (มักไม่เจาะจงตัวบุคคล) พบบ่อยในข่าวและงานเขียน (ฝนตกหนัก อุบัติเหตุ) ใช้ 탓에 เมื่อต้องการสื่อว่า "เป็นเพราะความผิดของ [ใคร/อะไร]" และใช้ 으로 인해 เมื่อเพียงระบุสาเหตุตามข้อเท็จจริง',
      'Keduanya menandai sebab, tetapi -(으)ㄴ/는 탓에 menimpakan KESALAHAN pada sebab negatif yang menghasilkan akibat buruk (sering bersifat pribadi: kesiangan, sebuah kekeliruan), sedangkan -(으)로 인해(서) adalah hubungan sebab-akibat yang netral dan formal untuk sebab apa pun (sering impersonal), lazim dalam berita dan tulisan (hujan lebat, kecelakaan). Pakai 탓에 saat kamu bermaksud "ini gara-gara kesalahan [seseorang/sesuatu]", dan 으로 인해 saat kamu sekadar menyatakan sebab yang objektif.',
      'Cả hai đều đánh dấu nguyên nhân, nhưng -(으)ㄴ/는 탓에 quy LỖI cho một nguyên nhân tiêu cực dẫn đến kết quả xấu (thường mang tính cá nhân: ngủ quên, một sai lầm), trong khi -(으)로 인해(서) là quan hệ nhân-quả trung tính, trang trọng dùng cho bất kỳ nguyên nhân nào (thường khách quan), phổ biến trong tin tức và văn viết (mưa lớn, một vụ tai nạn). Dùng 탓에 khi bạn muốn nói "đó là do lỗi của [ai/cái gì]", và dùng 으로 인해 khi bạn chỉ đơn thuần nêu một nguyên nhân khách quan.',
      'どちらも原因を表すが、-(으)ㄴ/는 탓에 は悪い結果を生む否定的な原因に「責任・せい」を帰す（多くは個人的：寝坊、ミスなど）。一方 -(으)로 인해(서) はあらゆる原因に使える中立的でフォーマルな因果関係で（多くは非人称的）、ニュースや書き言葉でよく使われる（大雨、事故など）。「[誰か・何か]のせいだ」と言いたいときは 탓에 を、客観的な原因を単に述べるときは 으로 인해 を使う。',
    ),
    items: [
      {
        sentence: '어젯밤에 늦게까지 게임을 한 {} 오늘 너무 피곤해요.',
        optionA: '한 탓에',
        optionB: '함으로 인해',
        answer: 'a',
        trans: L(
          'Because I played games late last night, I\'m so tired today.',
          'Como anoche jugué videojuegos hasta tarde, hoy estoy muy cansado.',
          'Parce que j\'ai joué aux jeux vidéo tard hier soir, je suis très fatigué aujourd\'hui.',
          'Como joguei videogame até tarde ontem à noite, hoje estou muito cansado.',
          'เพราะเมื่อคืนเล่นเกมจนดึก วันนี้เลยเหนื่อยมาก',
          'Karena tadi malam main game sampai larut, hari ini aku capek sekali.',
          'Vì tối qua chơi game đến khuya nên hôm nay tôi mệt lắm.',
          '昨日の夜遅くまでゲームをしたせいで、今日はとても疲れています。',
        ),
        why: L(
          'A blameworthy personal habit (staying up gaming) leading to a bad result (tiredness) calls for 탓에; the formal/impersonal 함으로 인해 clashes with the casual 피곤해요 register and sounds stiff and unnatural for self-blame.',
          'Un hábito personal reprochable (quedarse jugando hasta tarde) que lleva a un mal resultado (cansancio) pide 탓에; el formal/impersonal 함으로 인해 choca con el registro casual de 피곤해요 y suena rígido y poco natural para autocriticarse.',
          'Une habitude personnelle blâmable (jouer tard) menant à un mauvais résultat (la fatigue) appelle 탓에 ; le formel/impersonnel 함으로 인해 jure avec le registre familier de 피곤해요 et sonne raide et peu naturel pour s\'auto-blâmer.',
          'Um hábito pessoal repreensível (ficar jogando até tarde) que leva a um resultado ruim (cansaço) pede 탓에; o formal/impessoal 함으로 인해 destoa do registro casual de 피곤해요 e soa rígido e nada natural para se autocensurar.',
          'นิสัยส่วนตัวที่น่าตำหนิ (เล่นเกมจนดึก) ซึ่งนำไปสู่ผลลบ (ความเหนื่อย) ควรใช้ 탓에; ส่วน 함으로 인해 ที่เป็นทางการและไม่เจาะจงตัวบุคคล ขัดกับระดับภาษากันเองอย่าง 피곤해요 และฟังดูแข็งทื่อ ไม่เป็นธรรมชาติเมื่อจะตำหนิตัวเอง',
          'Kebiasaan pribadi yang patut disalahkan (begadang main game) yang berujung pada hasil buruk (kelelahan) menuntut 탓에; bentuk formal/impersonal 함으로 인해 bertabrakan dengan ragam santai 피곤해요 dan terdengar kaku serta tidak alami untuk menyalahkan diri sendiri.',
          'Một thói quen cá nhân đáng trách (thức chơi game đến khuya) dẫn đến kết quả xấu (mệt mỏi) cần dùng 탓에; dạng trang trọng/khách quan 함으로 인해 xung khắc với văn phong thân mật 피곤해요 và nghe cứng nhắc, không tự nhiên khi tự trách bản thân.',
          '咎められるべき個人的な習慣（夜遅くまでゲームをすること）が悪い結果（疲れ）を招く場合は 탓에 がふさわしい。フォーマルで非人称的な 함으로 인해 はくだけた 피곤해요 の語調とぶつかり、自己批判には堅苦しく不自然に聞こえる。',
        ),
      },
      {
        sentence: '이번 {} 도로가 통제되어 출근길이 막혔습니다.',
        optionA: '폭설인 탓에',
        optionB: '폭설로 인해',
        answer: 'b',
        trans: L(
          'Due to this heavy snowfall, the roads were closed and the commute was jammed.',
          'Debido a esta fuerte nevada, las carreteras se cerraron y el trayecto al trabajo quedó atascado.',
          'En raison de ces fortes chutes de neige, les routes ont été fermées et les trajets domicile-travail ont été bloqués.',
          'Devido a esta forte nevasca, as estradas foram fechadas e o trajeto ao trabalho ficou congestionado.',
          'เนื่องจากหิมะตกหนักครั้งนี้ ถนนถูกปิดและการเดินทางไปทำงานติดขัด',
          'Akibat salju lebat ini, jalan-jalan ditutup dan perjalanan kerja menjadi macet.',
          'Do trận tuyết rơi dày này, các con đường bị đóng và việc đi làm bị tắc nghẽn.',
          'この大雪のため、道路が閉鎖され、通勤が渋滞しました。',
        ),
        why: L(
          'In this formal report register (-습니다) a neutral, impersonal cause (heavy snow) takes 으로 인해; the form 폭설인 탓에 is awkward (natives drop the 인) and 탓에 wrongly assigns blame as if the snow were at fault.',
          'En este registro formal de informe (-습니다), una causa neutra e impersonal (la fuerte nevada) lleva 으로 인해; la forma 폭설인 탓에 es torpe (los nativos omiten el 인) y 탓에 atribuye culpa erróneamente, como si la nieve tuviera la culpa.',
          'Dans ce registre formel de compte rendu (-습니다), une cause neutre et impersonnelle (la forte neige) prend 으로 인해 ; la forme 폭설인 탓에 est maladroite (les natifs omettent le 인) et 탓에 attribue à tort un blâme, comme si la neige était fautive.',
          'Neste registro formal de relato (-습니다), uma causa neutra e impessoal (a forte nevasca) leva 으로 인해; a forma 폭설인 탓에 é estranha (os nativos omitem o 인) e 탓에 atribui culpa erroneamente, como se a neve tivesse culpa.',
          'ในระดับภาษารายงานที่เป็นทางการ (-습니다) สาเหตุที่เป็นกลางและไม่เจาะจงตัวบุคคล (หิมะตกหนัก) จะใช้ 으로 인해; ส่วนรูป 폭설인 탓에 ฟังดูแปลก (เจ้าของภาษาจะตัด 인 ทิ้ง) และ 탓에 กลับโยนความผิดผิด ๆ ราวกับว่าหิมะเป็นฝ่ายผิด',
          'Dalam ragam laporan formal (-습니다), penyebab yang netral dan impersonal (salju lebat) memakai 으로 인해; bentuk 폭설인 탓에 terdengar janggal (penutur asli melesapkan 인) dan 탓에 keliru menimpakan kesalahan seolah-olah saljulah yang bersalah.',
          'Trong văn phong báo cáo trang trọng (-습니다), một nguyên nhân trung tính, khách quan (tuyết rơi dày) dùng 으로 인해; dạng 폭설인 탓에 nghe vụng về (người bản xứ lược bỏ 인) và 탓에 quy lỗi sai, như thể tuyết là bên có lỗi.',
          'このフォーマルな報告体（-습니다）では、中立的で非人称的な原因（大雪）には 으로 인해 を用いる。폭설인 탓에 という形はぎこちなく（ネイティブは 인 を落とす）、탓에 はまるで雪に非があるかのように誤って責めを負わせてしまう。',
        ),
      },
      {
        sentence: '제가 길을 잘못 {} 우리가 약속에 늦고 말았어요.',
        optionA: '안내한 탓에',
        optionB: '안내함으로 인해',
        answer: 'a',
        trans: L(
          'Because I gave the wrong directions, we ended up being late for our appointment.',
          'Como di mal las indicaciones, terminamos llegando tarde a la cita.',
          'Parce que j\'ai mal indiqué le chemin, nous avons fini par arriver en retard au rendez-vous.',
          'Como dei as direções erradas, acabamos nos atrasando para o compromisso.',
          'เพราะฉันบอกทางผิด เราเลยไปสายจนพลาดนัด',
          'Karena aku memberi petunjuk arah yang salah, kami akhirnya terlambat ke janji temu.',
          'Vì tôi chỉ đường sai nên rốt cuộc chúng tôi đã trễ hẹn.',
          '私が道案内を間違えたせいで、私たちは約束に遅れてしまいました。',
        ),
        why: L(
          'The speaker is owning a personal fault (misguiding) that caused a bad outcome (being late), exactly what 탓에 expresses; the formal 안내함으로 인해 is too detached and unnatural for admitting one\'s own mistake in casual speech (말았어요).',
          'El hablante asume una falta personal (indicar mal) que causó un mal resultado (llegar tarde), justo lo que expresa 탓에; el formal 안내함으로 인해 es demasiado distante y poco natural para admitir el propio error en el habla casual (말았어요).',
          'Le locuteur assume une faute personnelle (avoir mal indiqué) ayant causé un mauvais résultat (le retard), exactement ce qu\'exprime 탓에 ; le formel 안내함으로 인해 est trop détaché et peu naturel pour admettre sa propre erreur dans un langage familier (말았어요).',
          'O falante assume uma falha pessoal (orientar mal) que causou um resultado ruim (atraso), exatamente o que 탓에 expressa; o formal 안내함으로 인해 é distante demais e nada natural para admitir o próprio erro na fala casual (말았어요).',
          'ผู้พูดยอมรับความผิดส่วนตัว (บอกทางผิด) ที่ทำให้เกิดผลลบ (มาสาย) ซึ่งตรงกับสิ่งที่ 탓에 สื่อ; ส่วน 안내함으로 인해 ที่เป็นทางการนั้นห่างเหินเกินไปและไม่เป็นธรรมชาติเมื่อจะยอมรับความผิดของตัวเองในคำพูดกันเอง (말았어요)',
          'Penutur mengakui kesalahan pribadi (salah memberi arah) yang menyebabkan hasil buruk (terlambat), persis seperti yang diungkapkan 탓에; bentuk formal 안내함으로 인해 terlalu berjarak dan tidak alami untuk mengakui kesalahan sendiri dalam tuturan santai (말았어요).',
          'Người nói đang nhận lỗi cá nhân (chỉ đường sai) đã gây ra kết quả xấu (trễ hẹn), đúng như 탓에 diễn đạt; dạng trang trọng 안내함으로 인해 quá xa cách và không tự nhiên khi thừa nhận lỗi của chính mình trong lời nói thân mật (말았어요).',
          '話し手は個人的な過ち（道案内を間違えたこと）が悪い結果（遅刻）を招いたことを認めており、まさに 탓에 が表すものだ。フォーマルな 안내함으로 인해 はよそよそしすぎて、くだけた話し方（말았어요）で自分のミスを認めるには不自然である。',
        ),
      },
    ],
  },
  {
    id: 'semida-semchida',
    a: '-(으)ㄴ/는 셈이다',
    b: '-(으)ㄴ/는 셈 치다',
    note: L(
      '-(으)ㄴ/는 셈이다 draws a factual CONCLUSION that something practically amounts to / is as good as the case ("it\'s basically X"). -(으)ㄴ/는 셈 치다 expresses a DECISION to TREAT/suppose something as true even though it isn\'t, often as 셈 치고 ("let\'s just count it as / suppose X").',
      '-(으)ㄴ/는 셈이다 saca una CONCLUSIÓN basada en hechos: que algo prácticamente equivale a / es casi como el caso ("es básicamente X"). -(으)ㄴ/는 셈 치다 expresa la DECISIÓN de TRATAR/dar por supuesto algo como cierto aunque no lo sea, a menudo como 셈 치고 ("hagamos de cuenta que / supongamos X").',
      '-(으)ㄴ/는 셈이다 tire une CONCLUSION factuelle : quelque chose revient pratiquement à / équivaut presque au cas ("c\'est en gros X"). -(으)ㄴ/는 셈 치다 exprime une DÉCISION de TRAITER/supposer quelque chose comme vrai même si ça ne l\'est pas, souvent sous la forme 셈 치고 ("faisons comme si / supposons X").',
      '-(으)ㄴ/는 셈이다 tira uma CONCLUSÃO factual: que algo praticamente equivale a / é quase o mesmo que o caso ("é basicamente X"). -(으)ㄴ/는 셈 치다 expressa a DECISÃO de TRATAR/supor algo como verdadeiro mesmo que não seja, muitas vezes como 셈 치고 ("vamos fazer de conta que / supor X").',
      '-(으)ㄴ/는 셈이다 ใช้สรุปตามข้อเท็จจริงว่าบางอย่างแทบจะเท่ากับ / เกือบจะเป็นอย่างนั้นเลย ("ก็เท่ากับว่าเป็น X") ส่วน -(으)ㄴ/는 셈 치다 แสดงการตัดสินใจที่จะถือ/สมมติว่าบางอย่างเป็นจริงทั้งที่จริง ๆ แล้วไม่ใช่ มักอยู่ในรูป 셈 치고 ("เอาเป็นว่า / สมมติว่าเป็น X")',
      '-(으)ㄴ/는 셈이다 menarik KESIMPULAN faktual bahwa sesuatu secara praktis sama dengan / hampir sama dengan keadaan itu ("pada dasarnya X"). -(으)ㄴ/는 셈 치다 menyatakan KEPUTUSAN untuk MENGANGGAP/mengandaikan sesuatu sebagai benar meski sebenarnya tidak, sering dalam bentuk 셈 치고 ("anggap saja / andaikan X").',
      '-(으)ㄴ/는 셈이다 đưa ra một KẾT LUẬN có thật rằng điều gì đó thực chất tương đương với / gần như là đúng vậy ("về cơ bản là X"). -(으)ㄴ/는 셈 치다 thể hiện QUYẾT ĐỊNH COI/giả định điều gì đó là đúng dù thực ra không phải vậy, thường ở dạng 셈 치고 ("cứ coi như / giả sử là X").',
      '-(으)ㄴ/는 셈이다 は、あることが実質的に〜に等しい／ほぼそうである、という事実としての結論を導く("基本的にXだ")。-(으)ㄴ/는 셈 치다 は、本当はそうでなくても、あることを真実だと見なす／仮定するという決断を表し、しばしば 셈 치고("〜したことにしよう／Xだと仮定しよう")の形で使う。',
    ),
    items: [
      {
        sentence: '발표 자료를 거의 다 만들었으니까 일이 다 {} .',
        optionA: '끝난 셈이에요',
        optionB: '끝난 셈 쳐요',
        answer: 'a',
        trans: L(
          'Since I\'ve made almost all of the presentation materials, the work is practically all done.',
          'Como ya hice casi todos los materiales de la presentación, el trabajo prácticamente está terminado.',
          'Comme j\'ai déjà fait presque tous les supports de la présentation, le travail est pratiquement terminé.',
          'Como já fiz quase todos os materiais da apresentação, o trabalho está praticamente terminado.',
          'เพราะฉันทำสื่อสำหรับการนำเสนอเสร็จเกือบหมดแล้ว งานก็แทบจะเสร็จเรียบร้อยแล้ว',
          'Karena aku sudah membuat hampir semua materi presentasinya, pekerjaannya praktis sudah selesai semua.',
          'Vì mình đã làm gần hết tài liệu thuyết trình rồi, nên công việc coi như đã xong gần hết.',
          'プレゼンの資料をほとんど作ったので、仕事はほぼ終わったようなものだ。',
        ),
        why: L(
          'It\'s a factual conclusion that the work is as good as finished (셈이다). 끝난 셈 쳐요 would mean deciding to pretend it\'s done when it isn\'t, which contradicts 거의 다 만들었으니까 (it really is nearly done).',
          'Es una conclusión basada en hechos: el trabajo está casi terminado (셈이다). 끝난 셈 쳐요 significaría decidir hacer de cuenta que está terminado cuando no lo está, lo cual contradice 거의 다 만들었으니까 (de verdad está casi terminado).',
          'C\'est une conclusion factuelle : le travail est quasiment terminé (셈이다). 끝난 셈 쳐요 voudrait dire décider de faire comme s\'il était terminé alors qu\'il ne l\'est pas, ce qui contredit 거의 다 만들었으니까 (il l\'est réellement presque).',
          'É uma conclusão factual: o trabalho está praticamente terminado (셈이다). 끝난 셈 쳐요 significaria decidir fingir que está terminado quando não está, o que contradiz 거의 다 만들었으니까 (ele realmente está quase terminado).',
          'เป็นข้อสรุปตามข้อเท็จจริงว่างานแทบจะเสร็จแล้ว (셈이다) ส่วน 끝난 셈 쳐요 จะหมายถึงการตัดสินใจแกล้งทำเป็นว่าเสร็จทั้งที่ยังไม่เสร็จ ซึ่งขัดกับ 거의 다 만들었으니까 (มันเกือบเสร็จจริง ๆ)',
          'Ini kesimpulan faktual bahwa pekerjaannya praktis sudah selesai (셈이다). 끝난 셈 쳐요 akan berarti memutuskan untuk berpura-pura sudah selesai padahal belum, yang bertentangan dengan 거의 다 만들었으니까 (memang benar-benar hampir selesai).',
          'Đây là một kết luận có thật rằng công việc coi như đã xong (셈이다). 끝난 셈 쳐요 sẽ có nghĩa là quyết định giả vờ đã xong trong khi chưa xong, điều này mâu thuẫn với 거의 다 만들었으니까 (thực sự gần như đã xong).',
          '仕事がほぼ終わったという事実上の結論である(셈이다)。끝난 셈 쳐요 だと、本当は終わっていないのに終わったことにする決断を意味し、거의 다 만들었으니까(本当にほとんどできている)と矛盾する。',
        ),
      },
      {
        sentence: '잃어버린 돈은 못 찾을 테니까 그냥 없는 셈 {} 잊어버리자.',
        optionA: '이고',
        optionB: '치고',
        answer: 'b',
        trans: L(
          'We won\'t be able to find the lost money, so let\'s just regard it as nonexistent and forget about it.',
          'No vamos a poder recuperar el dinero perdido, así que hagamos de cuenta que no existe y olvidémoslo.',
          'On ne pourra pas récupérer l\'argent perdu, alors faisons comme s\'il n\'existait pas et oublions-le.',
          'Não vamos conseguir recuperar o dinheiro perdido, então vamos fazer de conta que ele não existe e esquecer.',
          'เราคงหาเงินที่หายไปไม่เจอแล้ว ก็เอาเป็นว่ามันไม่มีอยู่แล้วลืม ๆ มันไปเถอะ',
          'Kita tidak akan bisa menemukan uang yang hilang itu, jadi anggap saja uang itu tidak ada dan lupakan saja.',
          'Tiền bị mất chắc không tìm lại được đâu, nên cứ coi như nó không tồn tại rồi quên nó đi thôi.',
          'なくしたお金は見つけられないだろうから、もう無いものとして忘れてしまおう。',
        ),
        why: L(
          'The speaker decides to TREAT the money as if it doesn\'t exist in order to move on (없는 셈 치고). 없는 셈이고 would factually assert the money doesn\'t exist, which is false here (it exists but is lost) and clashes with the volitional 잊어버리자 (let\'s just forget it).',
          'El hablante decide TRATAR el dinero como si no existiera para poder seguir adelante (없는 셈 치고). 없는 셈이고 afirmaría como un hecho que el dinero no existe, lo cual es falso acá (existe pero está perdido) y choca con el volitivo 잊어버리자 (olvidémoslo nomás).',
          'Le locuteur décide de TRAITER l\'argent comme s\'il n\'existait pas pour passer à autre chose (없는 셈 치고). 없는 셈이고 affirmerait factuellement que l\'argent n\'existe pas, ce qui est faux ici (il existe mais est perdu) et entre en conflit avec le volitif 잊어버리자 (oublions-le).',
          'O falante decide TRATAR o dinheiro como se não existisse para poder seguir em frente (없는 셈 치고). 없는 셈이고 afirmaria como fato que o dinheiro não existe, o que é falso aqui (ele existe mas está perdido) e choca com o volitivo 잊어버리자 (vamos esquecer).',
          'ผู้พูดตัดสินใจถือว่าเงินนั้นเหมือนไม่มีอยู่เพื่อจะก้าวต่อไป (없는 셈 치고) ส่วน 없는 셈이고 จะเป็นการยืนยันตามข้อเท็จจริงว่าเงินไม่มีอยู่ ซึ่งไม่จริงในที่นี้ (เงินมีอยู่แต่หายไป) และขัดกับรูปแสดงเจตนา 잊어버리자 (ลืม ๆ มันไปเถอะ)',
          'Penutur memutuskan untuk MENGANGGAP uang itu seolah tidak ada agar bisa melanjutkan hidup (없는 셈 치고). 없는 셈이고 akan menyatakan sebagai fakta bahwa uang itu tidak ada, yang salah di sini (uang itu ada tapi hilang) dan bertabrakan dengan bentuk kehendak 잊어버리자 (ayo lupakan saja).',
          'Người nói quyết định COI số tiền như thể nó không tồn tại để bước tiếp (없는 셈 치고). 없는 셈이고 sẽ khẳng định như một sự thật rằng số tiền không tồn tại, điều này sai ở đây (tiền có tồn tại nhưng bị mất) và xung đột với dạng ý chí 잊어버리자 (cứ quên nó đi thôi).',
          '話し手は前に進むために、お金を無いものとして扱う決断をしている(없는 셈 치고)。없는 셈이고 だとお金が存在しないと事実として断定することになり、ここでは誤り(お金は存在するが失われている)で、意志を表す 잊어버리자(忘れてしまおう)とも合わない。',
        ),
      },
      {
        sentence: '이 약이 효과가 있을지 모르겠지만, 속는 셈 {} 한번 먹어 볼게.',
        optionA: '이야',
        optionB: '치고',
        answer: 'b',
        trans: L(
          'I\'m not sure this medicine will work, but I\'ll just suppose I\'m being fooled and give it a try.',
          'No estoy seguro de que este medicamento funcione, pero hago de cuenta que me engañan y lo pruebo igual.',
          'Je ne suis pas sûr que ce médicament fasse effet, mais je vais faire comme si on me trompait et l\'essayer quand même.',
          'Não tenho certeza se este remédio vai funcionar, mas vou fazer de conta que estou sendo enganado e experimentar mesmo assim.',
          'ฉันไม่แน่ใจว่ายานี้จะได้ผลไหม แต่ก็จะลองทำเป็นว่าถูกหลอกแล้วลองกินดูสักครั้ง',
          'Aku tidak yakin obat ini akan manjur, tapi aku akan anggap saja aku ditipu dan tetap mencobanya.',
          'Mình không chắc thuốc này có hiệu nghiệm không, nhưng cứ coi như bị lừa rồi thử uống một lần xem sao.',
          'この薬が効くかどうかわからないけど、だまされたと思って一度飲んでみるよ。',
        ),
        why: L(
          '속는 셈 치고 is the fixed pattern meaning \'on the assumption you\'ll be deceived, try it anyway\' — a decision to suppose. 속는 셈이야 (\'it amounts to being deceived\') is a standalone factual statement that cannot connect to 한번 먹어 볼게 and gives no coherent meaning here.',
          '속는 셈 치고 es el patrón fijo que significa \'dando por supuesto que te engañarán, pruébalo igual\' — una decisión de suponer. 속는 셈이야 (\'equivale a ser engañado\') es una afirmación factual independiente que no puede conectarse con 한번 먹어 볼게 y no da ningún sentido coherente acá.',
          '속는 셈 치고 est le schéma figé qui signifie \'en supposant que tu seras trompé, essaie quand même\' — une décision de supposer. 속는 셈이야 (\'cela revient à être trompé\') est une affirmation factuelle autonome qui ne peut pas se connecter à 한번 먹어 볼게 et ne donne ici aucun sens cohérent.',
          '속는 셈 치고 é o padrão fixo que significa \'partindo do pressuposto de que você será enganado, experimente mesmo assim\' — uma decisão de supor. 속는 셈이야 (\'equivale a ser enganado\') é uma afirmação factual independente que não se conecta com 한번 먹어 볼게 e não dá nenhum sentido coerente aqui.',
          '속는 셈 치고 เป็นรูปสำเร็จที่แปลว่า \'สมมติว่าจะถูกหลอก แต่ก็ลองดูอยู่ดี\' — เป็นการตัดสินใจที่จะสมมติ ส่วน 속는 셈이야 (\'ก็เท่ากับถูกหลอก\') เป็นประโยคบอกข้อเท็จจริงที่อยู่ลำพัง ไม่สามารถเชื่อมกับ 한번 먹어 볼게 ได้ และไม่ให้ความหมายที่ลงตัวในที่นี้',
          '속는 셈 치고 adalah pola tetap yang berarti \'dengan mengandaikan kamu akan tertipu, tetap saja coba\' — sebuah keputusan untuk mengandaikan. 속는 셈이야 (\'sama saja dengan tertipu\') adalah pernyataan faktual yang berdiri sendiri yang tidak bisa menyambung dengan 한번 먹어 볼게 dan tidak memberi makna yang koheren di sini.',
          '속는 셈 치고 là mẫu cố định nghĩa là \'cứ giả định rằng sẽ bị lừa, nhưng vẫn thử xem\' — một quyết định để giả định. 속는 셈이야 (\'coi như bị lừa\') là một câu khẳng định sự thật độc lập, không thể nối với 한번 먹어 볼게 và không tạo ra ý nghĩa mạch lạc nào ở đây.',
          '속는 셈 치고 は『だまされると仮定して、それでも試してみる』という意味の固定表現で、仮定するという決断である。속는 셈이야(『だまされるようなものだ』)は単独の事実陳述で、한번 먹어 볼게 とつなげられず、ここでは意味が通らない。',
        ),
      },
    ],
  },
  {
    id: 'jieonjeong-jirado',
    a: '-(으)ㄹ지언정',
    b: '-(으)ㄹ지라도',
    note: L(
      'Use -(으)ㄹ지언정 for a defiant "I would rather X than Y" — willingly accepting a harsh cost to defend the following clause (often paired with 차라리/-는 않겠다). Use -(으)ㄹ지라도 for a plain, neutral hypothetical concession ("even if/though X, still Y"), especially with impersonal or matter-of-fact suppositions where there is no willful self-sacrifice. Note that 비록 collocates naturally with BOTH endings, so 비록 alone cannot disambiguate them.',
      'Usá -(으)ㄹ지언정 para un desafiante \'prefiero X antes que Y\', aceptando de buena gana un costo duro para defender la cláusula siguiente (suele ir con 차라리/-는 않겠다). Usá -(으)ㄹ지라도 para una concesión hipotética llana y neutra (\'aunque X, igual Y\'), sobre todo con suposiciones impersonales o de hecho donde no hay autosacrificio voluntario. Tené en cuenta que 비록 combina naturalmente con AMBAS terminaciones, así que 비록 por sí solo no las distingue.',
      'Utilise -(으)ㄹ지언정 pour un « je préférerais X plutôt que Y » de défi, en acceptant volontiers un coût dur pour défendre la clause suivante (souvent associé à 차라리/-는 않겠다). Utilise -(으)ㄹ지라도 pour une concession hypothétique simple et neutre (« même si X, quand même Y »), surtout avec des suppositions impersonnelles ou factuelles sans sacrifice de soi volontaire. Note que 비록 se combine naturellement avec les DEUX terminaisons, donc 비록 seul ne permet pas de les distinguer.',
      'Use -(으)ㄹ지언정 para um desafiador \'eu prefiro X a Y\', aceitando de bom grado um custo duro para defender a próxima cláusula (muitas vezes junto com 차라리/-는 않겠다). Use -(으)ㄹ지라도 para uma concessão hipotética simples e neutra (\'mesmo que X, ainda assim Y\'), especialmente com suposições impessoais ou factuais onde não há autossacrifício voluntário. Observe que 비록 combina naturalmente com AMBAS as terminações, então 비록 sozinho não consegue distingui-las.',
      'ใช้ -(으)ㄹ지언정 สำหรับความหมายเชิงท้าทาย \'ยอม X ดีกว่า Y\' โดยยอมรับราคาที่ต้องจ่ายอันหนักหน่วงด้วยความเต็มใจเพื่อปกป้องอนุประโยคที่ตามมา (มักใช้คู่กับ 차라리/-는 않겠다) ใช้ -(으)ㄹ지라도 สำหรับการยอมรับเชิงสมมติแบบเรียบ ๆ และเป็นกลาง (\'แม้ X ก็ยัง Y\') โดยเฉพาะกับการสมมติที่ไม่มีตัวบุคคลหรือเป็นข้อเท็จจริงซึ่งไม่มีการเสียสละตนเองด้วยความเต็มใจ พึงสังเกตว่า 비록 เข้าคู่ได้อย่างเป็นธรรมชาติกับลงท้ายทั้งสองแบบ ดังนั้น 비록 เพียงลำพังจึงแยกแยะทั้งสองไม่ได้',
      'Gunakan -(으)ㄹ지언정 untuk makna menantang \'aku lebih baik X daripada Y\' — dengan rela menerima biaya berat demi membela klausa berikutnya (sering dipasangkan dengan 차라리/-는 않겠다). Gunakan -(으)ㄹ지라도 untuk konsesi hipotetis yang datar dan netral (\'meskipun X, tetap Y\'), terutama dengan pengandaian impersonal atau apa adanya di mana tidak ada pengorbanan diri yang disengaja. Perhatikan bahwa 비록 berpadu secara alami dengan KEDUA akhiran, jadi 비록 saja tidak bisa membedakannya.',
      'Dùng -(으)ㄹ지언정 cho nghĩa ngang ngạnh \'tôi thà X còn hơn Y\' — sẵn lòng chấp nhận một cái giá khắc nghiệt để bảo vệ mệnh đề tiếp theo (thường đi kèm với 차라리/-는 않겠다). Dùng -(으)ㄹ지라도 cho một sự nhượng bộ giả định bình thường, trung tính (\'dù X, vẫn Y\'), đặc biệt với những giả định phi cá nhân hoặc mang tính sự thật, nơi không có sự tự hy sinh tự nguyện. Lưu ý rằng 비록 kết hợp tự nhiên với CẢ HAI đuôi, nên chỉ riêng 비록 không thể phân biệt chúng.',
      '-(으)ㄹ지언정 は「YよりむしろX」という反骨的な意味に使う。次の節を守るために厳しい代償を進んで受け入れる場合である（しばしば 차라리/-는 않겠다 と組み合わせる）。-(으)ㄹ지라도 は素直で中立的な仮定の譲歩（「Xでも、それでもY」）に使い、特に自発的な自己犠牲のない非人称的・淡々とした想定に向く。비록 は両方の語尾と自然に共起するため、비록 だけでは両者を区別できないことに注意。',
    ),
    items: [
      {
        sentence: '차라리 회사를 {} 부당한 지시는 따르지 않겠다.',
        optionA: '그만둘지언정',
        optionB: '그만둘지라도',
        answer: 'a',
        trans: L(
          'I would rather quit the company than follow an unjust order.',
          'Prefiero renunciar a la empresa antes que obedecer una orden injusta.',
          'Je préférerais quitter l\'entreprise plutôt que d\'obéir à un ordre injuste.',
          'Eu prefiro pedir demissão da empresa a obedecer a uma ordem injusta.',
          'ฉันยอมลาออกจากบริษัทดีกว่าที่จะทำตามคำสั่งที่ไม่เป็นธรรม',
          'Aku lebih baik keluar dari perusahaan daripada menuruti perintah yang tidak adil.',
          'Tôi thà nghỉ việc ở công ty còn hơn là tuân theo một mệnh lệnh bất công.',
          '不当な命令に従うくらいなら、いっそ会社を辞める。',
        ),
        why: L(
          '차라리 sets up a \'rather X than Y\' preference, and willingly choosing to quit in order to refuse the next clause is the signature defiant trade-off of 지언정. 차라리 clashes with the plain concessive 지라도, which carries no notion of a preferred sacrifice, so only 그만둘지언정 is natural here.',
          '차라리 plantea una preferencia de \'mejor X que Y\', y elegir voluntariamente renunciar para rechazar la cláusula siguiente es el típico trueque desafiante de 지언정. 차라리 choca con el concesivo plano 지라도, que no conlleva ninguna idea de sacrificio preferido, así que acá solo 그만둘지언정 suena natural.',
          '차라리 établit une préférence du type « plutôt X que Y », et choisir volontairement de démissionner pour refuser la clause suivante est le compromis de défi caractéristique de 지언정. 차라리 entre en conflit avec le concessif neutre 지라도, qui ne porte aucune notion de sacrifice préféré, donc seul 그만둘지언정 est naturel ici.',
          '차라리 estabelece uma preferência do tipo \'antes X que Y\', e escolher voluntariamente pedir demissão para recusar a próxima cláusula é a típica troca desafiadora de 지언정. 차라리 choca com o concessivo neutro 지라도, que não carrega nenhuma noção de sacrifício preferido, então só 그만둘지언정 é natural aqui.',
          '차라리 วางกรอบความชอบแบบ \'ยอม X ดีกว่า Y\' และการเลือกลาออกด้วยความเต็มใจเพื่อปฏิเสธอนุประโยคถัดไปคือการแลกเปลี่ยนเชิงท้าทายอันเป็นเอกลักษณ์ของ 지언정 ส่วน 차라리 ขัดกับ 지라도 ที่เป็นการยอมรับแบบกลาง ๆ ซึ่งไม่มีความหมายของการเสียสละที่เลือกเอง ดังนั้นที่นี่มีแต่ 그만둘지언정 เท่านั้นที่เป็นธรรมชาติ',
          '차라리 membangun preferensi \'lebih baik X daripada Y\', dan dengan sukarela memilih keluar demi menolak klausa berikutnya adalah ciri khas pertukaran menantang dari 지언정. 차라리 berbenturan dengan konsesif netral 지라도, yang tidak membawa gagasan pengorbanan yang dipilih, jadi di sini hanya 그만둘지언정 yang terasa wajar.',
          '차라리 thiết lập một sự ưu tiên kiểu \'thà X còn hơn Y\', và việc tự nguyện chọn nghỉ việc để từ chối mệnh đề tiếp theo chính là sự đánh đổi ngang ngạnh đặc trưng của 지언정. 차라리 xung khắc với 지라도 vốn là nhượng bộ trung tính, không mang ý nghĩa hy sinh được ưu tiên, nên ở đây chỉ có 그만둘지언정 là tự nhiên.',
          '차라리 は「YよりむしろX」という選好を設定し、次の節を拒むために進んで辞めることを選ぶのは 지언정 ならではの反骨的な取引である。차라리 は、好んだ犠牲という含みのない中立的な譲歩の 지라도 と相容れないため、ここでは 그만둘지언정 だけが自然である。',
        ),
      },
      {
        sentence: '내일 비가 {} 행사는 예정대로 진행됩니다.',
        optionA: '올지언정',
        optionB: '올지라도',
        answer: 'b',
        trans: L(
          'Even if it rains tomorrow, the event will proceed as scheduled.',
          'Aunque mañana llueva, el evento seguirá según lo previsto.',
          'Même s\'il pleut demain, l\'événement se déroulera comme prévu.',
          'Mesmo que chova amanhã, o evento ocorrerá conforme programado.',
          'แม้พรุ่งนี้ฝนจะตก งานก็จะดำเนินไปตามกำหนดการ',
          'Meskipun besok hujan, acara akan tetap berlangsung sesuai jadwal.',
          'Dù ngày mai trời có mưa, sự kiện vẫn sẽ diễn ra theo đúng lịch trình.',
          'たとえ明日雨が降っても、イベントは予定どおり行われる。',
        ),
        why: L(
          'A neutral hypothetical concession (\'even if it rains, still...\') is 지라도; 지언정 forces a \'rather than\' defiant trade-off, which makes no sense for an impersonal weather supposition with no willful self-sacrifice.',
          'Una concesión hipotética neutra (\'aunque llueva, igual...\') es 지라도; 지언정 fuerza un trueque desafiante de \'antes que\', que no tiene sentido para una suposición impersonal sobre el clima donde no hay sacrificio voluntario.',
          'Une concession hypothétique neutre (« même s\'il pleut, quand même... ») se dit 지라도 ; 지언정 impose un compromis de défi du type « plutôt que », ce qui n\'a aucun sens pour une supposition impersonnelle sur la météo sans sacrifice volontaire.',
          'Uma concessão hipotética neutra (\'mesmo que chova, ainda assim...\') é 지라도; 지언정 força uma troca desafiadora do tipo \'antes que\', o que não faz sentido para uma suposição impessoal sobre o clima sem sacrifício voluntário.',
          'การยอมรับเชิงสมมติแบบกลาง ๆ (\'แม้ฝนตก ก็ยัง...\') คือ 지라도 ส่วน 지언정 บังคับให้เกิดการแลกเปลี่ยนเชิงท้าทายแบบ \'ยอม...ดีกว่า\' ซึ่งไม่สมเหตุสมผลกับการสมมติเรื่องสภาพอากาศที่ไม่มีตัวบุคคลและไม่มีการเสียสละด้วยความเต็มใจ',
          'Konsesi hipotetis netral (\'meskipun hujan, tetap...\') adalah 지라도; 지언정 memaksakan pertukaran menantang bertipe \'daripada\', yang tidak masuk akal untuk pengandaian cuaca yang impersonal tanpa pengorbanan yang disengaja.',
          'Một sự nhượng bộ giả định trung tính (\'dù mưa, vẫn...\') là 지라도; 지언정 áp đặt một sự đánh đổi ngang ngạnh kiểu \'thà... còn hơn\', điều này vô nghĩa với một giả định phi cá nhân về thời tiết vốn không có sự hy sinh tự nguyện.',
          '中立的な仮定の譲歩（「雨が降っても、それでも…」）は 지라도 である。지언정 は「よりむしろ」という反骨的な取引を強いるが、自発的な犠牲のない非人称の天候の仮定にはそぐわない。',
        ),
      },
      {
        sentence: '굶어 {} 그 사람의 도움은 받지 않겠다.',
        optionA: '죽을지언정',
        optionB: '죽을지라도',
        answer: 'a',
        trans: L(
          'I would rather starve to death than accept that person\'s help.',
          'Prefiero morir de hambre antes que aceptar la ayuda de esa persona.',
          'Je préférerais mourir de faim plutôt que d\'accepter l\'aide de cette personne.',
          'Eu prefiro morrer de fome a aceitar a ajuda daquela pessoa.',
          'ฉันยอมอดตายดีกว่าที่จะรับความช่วยเหลือจากคนคนนั้น',
          'Aku lebih baik mati kelaparan daripada menerima bantuan dari orang itu.',
          'Tôi thà chết đói còn hơn là nhận sự giúp đỡ của người đó.',
          'あの人の助けを受けるくらいなら、いっそ飢え死にする。',
        ),
        why: L(
          '굶어 죽을지언정 is the fixed idiom for choosing an extreme cost precisely to refuse the next clause, and the defiant 도움은 받지 않겠다 frame reinforces the willful trade-off; 지라도 would flatten it into a weak neutral concession that loses the self-sacrifice.',
          '굶어 죽을지언정 es el modismo fijo para elegir un costo extremo precisamente para rechazar la cláusula siguiente, y el marco desafiante 도움은 받지 않겠다 refuerza el trueque voluntario; 지라도 lo aplanaría en una concesión neutra débil que pierde el autosacrificio.',
          '굶어 죽을지언정 est l\'expression figée pour choisir un coût extrême précisément afin de refuser la clause suivante, et le cadre de défi 도움은 받지 않겠다 renforce le compromis volontaire ; 지라도 l\'aplatirait en une faible concession neutre qui perd le sacrifice de soi.',
          '굶어 죽을지언정 é a expressão fixa para escolher um custo extremo justamente para recusar a próxima cláusula, e o quadro desafiador 도움은 받지 않겠다 reforça a troca voluntária; 지라도 o achataria numa concessão neutra fraca que perde o autossacrifício.',
          '굶어 죽을지언정 เป็นสำนวนตายตัวสำหรับการเลือกราคาที่ต้องจ่ายอย่างสุดขั้วเพื่อปฏิเสธอนุประโยคถัดไปโดยเฉพาะ และกรอบเชิงท้าทาย 도움은 받지 않겠다 ยิ่งตอกย้ำการแลกเปลี่ยนด้วยความเต็มใจ ส่วน 지라도 จะทำให้มันแบนราบกลายเป็นการยอมรับแบบกลาง ๆ ที่อ่อนซึ่งสูญเสียความหมายของการเสียสละตนเอง',
          '굶어 죽을지언정 adalah ungkapan baku untuk memilih biaya ekstrem justru demi menolak klausa berikutnya, dan kerangka menantang 도움은 받지 않겠다 memperkuat pertukaran yang disengaja; 지라도 akan meratakannya menjadi konsesi netral lemah yang kehilangan pengorbanan diri.',
          '굶어 죽을지언정 là thành ngữ cố định để chọn một cái giá cực đoan chính là nhằm từ chối mệnh đề tiếp theo, và khung ngang ngạnh 도움은 받지 않겠다 củng cố thêm sự đánh đổi tự nguyện; 지라도 sẽ làm nó trở nên nhạt thành một nhượng bộ trung tính yếu ớt, đánh mất sự tự hy sinh.',
          '굶어 죽을지언정 は、まさに次の節を拒むために極端な代償を選ぶことを表す定型表現であり、反骨的な 도움은 받지 않겠다 という枠組みが自発的な取引を強める。지라도 ではそれが弱い中立的な譲歩に平板化され、自己犠牲が失われてしまう。',
        ),
      },
    ],
  },
  {
    id: 'ppunida-ttareumida',
    a: '-(으)ㄹ 뿐이다',
    b: '-(으)ㄹ 따름이다',
    note: L(
      'Both mean "merely/only X, nothing more." Use -(으)ㄹ 뿐이다 for the everyday "just/only": it works with past as well as present, in any register, and after nouns (그냥 농담했을 뿐이에요 "I was only joking"; 학생일 뿐이다). Reserve -(으)ㄹ 따름이다 for a formal, humble, present-tense "I can do nothing but / merely," almost always in set polite phrases (감사할/죄송할 따름입니다). Key asymmetry for testing: 따름이다 is present-only and very formal, so it cannot take a past stem and clashes with casual 반말 — but in those slots 뿐이다 is the only natural choice. Avoid neutral present-tense set phrases like 감사할 ___입니다 where BOTH are equally acceptable.',
      'Ambas significan \'meramente/solo X, nada más\'. Usá -(으)ㄹ 뿐이다 para el \'solo/nada más\' de todos los días: funciona tanto con pasado como con presente, en cualquier registro, y después de sustantivos (그냥 농담했을 뿐이에요 \'solo estaba bromeando\'; 학생일 뿐이다). Reservá -(으)ㄹ 따름이다 para un \'no puedo sino / meramente\' formal, humilde y en presente, casi siempre en frases corteses fijas (감사할/죄송할 따름입니다). Asimetría clave para evaluar: 따름이다 es solo de presente y muy formal, así que no puede llevar raíz en pasado y choca con el 반말 informal; pero en esos huecos 뿐이다 es la única opción natural. Evitá frases fijas neutras en presente como 감사할 ___입니다, donde AMBAS son igualmente aceptables.',
      'Les deux signifient \'simplement/seulement X, rien de plus\'. Utilise -(으)ㄹ 뿐이다 pour le \'juste/seulement\' du quotidien : il fonctionne au passé comme au présent, dans tous les registres, et après des noms (그냥 농담했을 뿐이에요 \'je plaisantais seulement\' ; 학생일 뿐이다). Réserve -(으)ㄹ 따름이다 à un \'je ne peux que / simplement\' formel, humble et au présent, presque toujours dans des formules de politesse figées (감사할/죄송할 따름입니다). Asymétrie clé pour les tests : 따름이다 est uniquement au présent et très formel, il ne peut donc pas prendre de radical au passé et entre en conflit avec le 반말 familier ; mais dans ces cas, 뿐이다 est le seul choix naturel. Évite les formules figées neutres au présent comme 감사할 ___입니다, où les DEUX sont également acceptables.',
      'Ambos significam \'meramente/só X, nada mais\'. Use -(으)ㄹ 뿐이다 para o \'só/apenas\' do dia a dia: funciona tanto no passado quanto no presente, em qualquer registro, e depois de substantivos (그냥 농담했을 뿐이에요 \'eu só estava brincando\'; 학생일 뿐이다). Reserve -(으)ㄹ 따름이다 para um \'não posso senão / meramente\' formal, humilde e no presente, quase sempre em frases polidas fixas (감사할/죄송할 따름입니다). Assimetria-chave para avaliar: 따름이다 é só de presente e muito formal, então não pode levar radical no passado e destoa do 반말 informal; mas nesses casos 뿐이다 é a única escolha natural. Evite frases fixas neutras no presente como 감사할 ___입니다, em que AMBOS são igualmente aceitáveis.',
      'ทั้งสองหมายถึง \'เพียงแค่ X เท่านั้น ไม่มีอะไรมากกว่านั้น\' ใช้ -(으)ㄹ 뿐이다 สำหรับ \'แค่/เพียง\' ในชีวิตประจำวัน: ใช้ได้ทั้งกับอดีตและปัจจุบัน ในทุกระดับภาษา และตามหลังคำนาม (그냥 농담했을 뿐이에요 \'แค่ล้อเล่นเท่านั้น\'; 학생일 뿐이다) ส่วน -(으)ㄹ 따름이다 ให้ใช้กับ \'ได้แต่ / เพียงแค่\' ที่เป็นทางการ ถ่อมตน และเป็นปัจจุบัน เกือบทั้งหมดอยู่ในวลีสุภาพตายตัว (감사할/죄송할 따름입니다) ความแตกต่างสำคัญสำหรับการสอบ: 따름이다 ใช้กับปัจจุบันเท่านั้นและเป็นทางการมาก จึงรับรากศัพท์อดีตไม่ได้ และขัดกับ 반말 แบบกันเอง แต่ในช่องเหล่านั้น 뿐이다 เป็นตัวเลือกธรรมชาติเพียงตัวเดียว หลีกเลี่ยงวลีตายตัวกลางๆ ในรูปปัจจุบันอย่าง 감사할 ___입니다 ที่ใช้ได้ทั้งสองตัวพอๆ กัน',
      'Keduanya berarti \'sekadar/hanya X, tidak lebih\'. Pakai -(으)ㄹ 뿐이다 untuk \'cuma/hanya\' sehari-hari: cocok dengan bentuk lampau maupun kini, di register apa pun, dan setelah kata benda (그냥 농담했을 뿐이에요 \'aku cuma bercanda\'; 학생일 뿐이다). Simpan -(으)ㄹ 따름이다 untuk \'tak bisa selain / sekadar\' yang formal, merendah, dan masa kini, hampir selalu dalam frasa sopan baku (감사할/죄송할 따름입니다). Asimetri kunci untuk ujian: 따름이다 hanya masa kini dan sangat formal, jadi tidak bisa memakai akar lampau dan bentrok dengan 반말 santai; tetapi di posisi itu 뿐이다 adalah satu-satunya pilihan alami. Hindari frasa baku netral masa kini seperti 감사할 ___입니다 yang KEDUANYA sama-sama berterima.',
      'Cả hai đều nghĩa là \'chỉ là X mà thôi, không gì hơn\'. Dùng -(으)ㄹ 뿐이다 cho nghĩa \'chỉ/thôi\' đời thường: nó dùng được với cả quá khứ lẫn hiện tại, ở mọi văn phong, và sau danh từ (그냥 농담했을 뿐이에요 \'tôi chỉ đùa thôi\'; 학생일 뿐이다). Dành -(으)ㄹ 따름이다 cho nghĩa \'không thể làm gì hơn ngoài / chỉ\' mang tính trang trọng, khiêm nhường, ở thì hiện tại, hầu như luôn nằm trong các cụm lịch sự cố định (감사할/죄송할 따름입니다). Điểm bất đối xứng quan trọng để kiểm tra: 따름이다 chỉ dùng ở hiện tại và rất trang trọng, nên không thể đi với gốc quá khứ và xung khắc với 반말 suồng sã; nhưng ở những chỗ đó 뿐이다 là lựa chọn tự nhiên duy nhất. Tránh các cụm cố định trung tính ở hiện tại như 감사할 ___입니다, nơi CẢ HAI đều chấp nhận được như nhau.',
      'どちらも『単にXだけ、それ以上ではない』という意味です。日常的な『ただ/だけ』には -(으)ㄹ 뿐이다 を使います。過去でも現在でも、どの語調でも、また名詞の後でも使えます（그냥 농담했을 뿐이에요『ただ冗談を言っただけです』；학생일 뿐이다）。-(으)ㄹ 따름이다 は、フォーマルで謙譲的、現在形の『～するほかない/ただ～だけ』に限って使い、ほぼ常に決まった丁寧表現の中で用います（감사할/죄송할 따름입니다）。出題で重要な非対称性：따름이다 は現在形のみで非常にフォーマルなため、過去語幹を取れず、くだけた 반말 とは衝突します。しかしそうした位置では 뿐이다 が唯一自然な選択肢です。감사할 ___입니다 のような中立的で現在形の決まり文句は、両方とも同じくらい自然なので避けてください。',
    ),
    items: [
      {
        sentence: '저는 그냥 사실대로 말했{}.',
        optionA: '을 뿐이에요',
        optionB: '을 따름이에요',
        answer: 'a',
        trans: L(
          'I merely told the truth, that\'s all.',
          'Solo dije la verdad, nada más.',
          'J\'ai simplement dit la vérité, c\'est tout.',
          'Eu apenas disse a verdade, só isso.',
          'ฉันแค่พูดความจริง แค่นั้นเอง',
          'Aku cuma mengatakan yang sebenarnya, itu saja.',
          'Tôi chỉ nói sự thật thôi, vậy thôi.',
          '私はただ本当のことを言っただけです。',
        ),
        why: L(
          'The stem is past (말했-). 뿐이다 freely follows a past stem (말했을 뿐이에요), but 따름이다 is present-only and humble; 말했을 따름이에요 is unnatural, so 뿐 is the only fit.',
          'La raíz está en pasado (말했-). 뿐이다 sigue libremente a una raíz en pasado (말했을 뿐이에요), pero 따름이다 es solo de presente y humilde; 말했을 따름이에요 suena poco natural, así que 뿐 es la única opción.',
          'Le radical est au passé (말했-). 뿐이다 suit librement un radical au passé (말했을 뿐이에요), mais 따름이다 est uniquement au présent et humble ; 말했을 따름이에요 n\'est pas naturel, donc 뿐 est le seul choix qui convient.',
          'O radical está no passado (말했-). 뿐이다 segue livremente um radical no passado (말했을 뿐이에요), mas 따름이다 é só de presente e humilde; 말했을 따름이에요 soa não natural, então 뿐 é a única opção.',
          'รากศัพท์เป็นรูปอดีต (말했-) 뿐이다 ตามหลังรากศัพท์อดีตได้อย่างอิสระ (말했을 뿐이에요) แต่ 따름이다 ใช้กับปัจจุบันเท่านั้นและเป็นรูปถ่อมตน 말했을 따름이에요 จึงฟังดูไม่เป็นธรรมชาติ ดังนั้น 뿐 จึงเป็นตัวเลือกเดียวที่เหมาะสม',
          'Akarnya bentuk lampau (말했-). 뿐이다 bebas mengikuti akar lampau (말했을 뿐이에요), tetapi 따름이다 hanya untuk masa kini dan bersifat merendah; 말했을 따름이에요 terdengar tidak alami, jadi 뿐 adalah satu-satunya yang pas.',
          'Gốc động từ ở thì quá khứ (말했-). 뿐이다 đi sau gốc quá khứ một cách thoải mái (말했을 뿐이에요), nhưng 따름이다 chỉ dùng ở hiện tại và mang tính khiêm nhường; 말했을 따름이에요 nghe không tự nhiên, nên 뿐 là lựa chọn duy nhất phù hợp.',
          '語幹は過去形（말했-）です。뿐이다 は過去語幹に自由に続きますが（말했을 뿐이에요）、따름이다 は現在形のみで謙譲的です。말했을 따름이에요 は不自然なので、뿐 が唯一の選択肢です。',
        ),
      },
      {
        sentence: '이번 사고로 심려를 끼쳐 드려 송구스러울 {}.',
        optionA: '뿐입니다',
        optionB: '따름입니다',
        answer: 'b',
        trans: L(
          'I can only feel deeply sorry for the worry this accident has caused you.',
          'Por la preocupación que les ha causado este accidente, no puedo sentir más que un profundo pesar.',
          'Pour l\'inquiétude que cet accident vous a causée, je ne peux que ressentir une profonde contrition.',
          'Pela preocupação que este acidente lhes causou, só posso sentir um profundo pesar.',
          'สำหรับความกังวลที่อุบัติเหตุครั้งนี้ทำให้ท่านต้องเป็นห่วง ผมได้แต่รู้สึกสำนึกผิดอย่างสุดซึ้ง',
          'Atas kekhawatiran yang ditimbulkan kecelakaan ini kepada Anda, saya hanya bisa merasa sangat menyesal.',
          'Vì sự lo lắng mà tai nạn này đã gây ra cho quý vị, tôi chỉ có thể cảm thấy vô cùng áy náy.',
          'この事故でご心配をおかけしたことについて、ただただ申し訳なく思うばかりです。',
        ),
        why: L(
          'Formal humble present apology. 송구스러울 따름입니다 is the fixed \'I can do nothing but feel sorry\' phrase; 송구스러울 뿐입니다 reads as \'I\'m merely sorry, that\'s it,\' which minimizes the apology and is off-register here.',
          'Disculpa formal, humilde y en presente. 송구스러울 따름입니다 es la frase fija de \'no puedo sino sentirlo\'; 송구스러울 뿐입니다 se lee como \'simplemente lo siento, y ya\', lo que minimiza la disculpa y no encaja en el registro.',
          'Excuse formelle, humble et au présent. 송구스러울 따름입니다 est la formule figée \'je ne peux que regretter\' ; 송구스러울 뿐입니다 se lit comme \'je suis simplement désolé, point\', ce qui minimise l\'excuse et est inadapté au registre.',
          'Desculpa formal, humilde e no presente. 송구스러울 따름입니다 é a frase fixa \'não posso senão lamentar\'; 송구스러울 뿐입니다 soa como \'estou apenas arrependido, e pronto\', o que minimiza o pedido de desculpas e foge do registro.',
          'คำขอโทษที่เป็นทางการ ถ่อมตน และเป็นปัจจุบัน 송구스러울 따름입니다 เป็นวลีตายตัวที่แปลว่า \'ได้แต่รู้สึกผิด\'; ส่วน 송구스러울 뿐입니다 ฟังดูเหมือน \'แค่รู้สึกผิดเท่านั้นแหละ\' ซึ่งลดทอนน้ำหนักของคำขอโทษและผิดระดับภาษาในที่นี้',
          'Permintaan maaf formal, merendah, dan masa kini. 송구스러울 따름입니다 adalah frasa baku \'tak bisa selain merasa bersalah\'; 송구스러울 뿐입니다 terbaca seperti \'saya cuma menyesal, sekian\', yang mengecilkan permintaan maaf dan tidak sesuai register di sini.',
          'Lời xin lỗi trang trọng, khiêm nhường, ở thì hiện tại. 송구스러울 따름입니다 là cụm cố định nghĩa \'không thể làm gì hơn ngoài việc áy náy\'; còn 송구스러울 뿐입니다 nghe như \'tôi chỉ thấy có lỗi, vậy thôi\', làm giảm nhẹ lời xin lỗi và sai sắc thái ở đây.',
          'フォーマルで謙譲的、現在形の謝罪です。송구스러울 따름입니다 は『申し訳なく思うほかない』という決まり文句です。송구스러울 뿐입니다 は『ただ申し訳ないだけだ』と読め、謝罪を軽くしてしまい、この場面では語調が合いません。',
        ),
      },
      {
        sentence: '화 안 났어. 나는 좀 피곤할 {}.',
        optionA: '뿐이야',
        optionB: '따름이야',
        answer: 'a',
        trans: L(
          'I\'m not angry. I\'m just a bit tired, that\'s all.',
          'No estoy enojado. Solo estoy un poco cansado, nada más.',
          'Je ne suis pas fâché. Je suis juste un peu fatigué, c\'est tout.',
          'Não estou bravo. Só estou um pouco cansado, só isso.',
          'ฉันไม่ได้โกรธ แค่เหนื่อยนิดหน่อยเท่านั้นเอง',
          'Aku nggak marah. Cuma agak capek, itu aja.',
          'Tôi không giận đâu. Chỉ hơi mệt một chút thôi, vậy thôi.',
          '怒ってないよ。ただちょっと疲れてるだけ、それだけ。',
        ),
        why: L(
          'Casual 반말 everyday \'just\' takes 뿐이야; 따름이다 is literary/humble and never used in this informal register, so 따름이야 is jarring.',
          'El \'solo\' cotidiano en 반말 informal lleva 뿐이야; 따름이다 es literario/humilde y nunca se usa en este registro informal, así que 따름이야 resulta chocante.',
          'Le \'juste\' du quotidien en 반말 informel prend 뿐이야 ; 따름이다 est littéraire/humble et ne s\'emploie jamais dans ce registre familier, donc 따름이야 détonne.',
          'O \'só\' cotidiano em 반말 informal usa 뿐이야; 따름이다 é literário/humilde e nunca se usa nesse registro informal, então 따름이야 soa estranho.',
          'คำว่า \'แค่\' ในชีวิตประจำวันแบบ 반말 ที่ไม่เป็นทางการใช้ 뿐이야; ส่วน 따름이다 เป็นภาษาเขียน/ถ่อมตน และไม่เคยใช้ในระดับภาษาแบบกันเองเช่นนี้ ดังนั้น 따름이야 จึงฟังดูขัดหู',
          'Kata \'cuma\' sehari-hari dalam 반말 informal memakai 뿐이야; 따름이다 bersifat sastrawi/merendah dan tak pernah dipakai dalam register santai ini, sehingga 따름이야 terdengar janggal.',
          'Từ \'chỉ\' đời thường trong 반말 thân mật dùng 뿐이야; còn 따름이다 mang tính văn chương/khiêm nhường và không bao giờ dùng ở văn phong suồng sã này, nên 따름이야 nghe chói tai.',
          '日常的な『ただ』を表すくだけた 반말 では 뿐이야 を使います。따름이다 は文語的・謙譲的で、このインフォーマルな語調では決して使われないため、따름이야 は不自然に響きます。',
        ),
      },
    ],
  },
  {
    id: 'kkasipda-jisipda',
    a: '-(으)ㄹ까 싶다',
    b: '-지 싶다',
    note: L(
      '-(으)ㄹ까 싶다 expresses a hesitant guess or half-formed intention about your own action ("maybe I\'ll..., I wonder if I should..."), so it attaches to an action you\'re weighing. -지 싶다 expresses a leaning judgment that a fact/state is the case ("I reckon / I\'d say that..."), so it attaches to your assessment of how things are.',
      '-(으)ㄹ까 싶다 expresa una conjetura vacilante o una intención a medio formar sobre tu propia acción ("quizás voy a..., me pregunto si debería..."), por eso se adjunta a una acción que estás sopesando. -지 싶다 expresa un juicio inclinado de que un hecho/estado es el caso ("yo diría que..., me parece que..."), por eso se adjunta a tu evaluación de cómo están las cosas.',
      '-(으)ㄹ까 싶다 exprime une supposition hésitante ou une intention à demi formée concernant ta propre action ("je vais peut-être..., je me demande si je devrais..."), c\'est pourquoi il s\'attache à une action que tu pèses. -지 싶다 exprime un jugement penché selon lequel un fait/état est le cas ("je dirais que..., il me semble que..."), c\'est pourquoi il s\'attache à ton évaluation de la situation.',
      '-(으)ㄹ까 싶다 expressa uma conjectura hesitante ou uma intenção meio formada sobre a sua própria ação ("talvez eu vá..., será que eu deveria..."), por isso se anexa a uma ação que você está ponderando. -지 싶다 expressa um juízo inclinado de que um fato/estado é o caso ("eu diria que..., me parece que..."), por isso se anexa à sua avaliação de como as coisas estão.',
      '-(으)ㄹ까 싶다 ใช้แสดงการคาดเดาแบบลังเลหรือความตั้งใจที่ยังก่อตัวไม่เต็มที่เกี่ยวกับการกระทำของตัวเอง ("บางทีฉันอาจจะ..., ฉันสงสัยว่าควรจะ...ดีไหม") จึงผูกกับการกระทำที่คุณกำลังชั่งใจอยู่ ส่วน -지 싶다 ใช้แสดงการตัดสินแบบโน้มเอียงว่าข้อเท็จจริง/สภาวะหนึ่งเป็นจริง ("ฉันว่า..., ฉันคิดว่าน่าจะ...") จึงผูกกับการประเมินสถานการณ์ของคุณว่าเป็นอย่างไร',
      '-(으)ㄹ까 싶다 mengungkapkan dugaan yang ragu-ragu atau niat yang setengah terbentuk tentang tindakanmu sendiri ("mungkin aku akan..., apakah sebaiknya aku..."), sehingga melekat pada tindakan yang sedang kamu timbang. -지 싶다 mengungkapkan penilaian yang condong bahwa suatu fakta/keadaan memang demikian ("kurasa..., menurutku..."), sehingga melekat pada penilaianmu tentang bagaimana keadaan sebenarnya.',
      '-(으)ㄹ까 싶다 diễn đạt một phỏng đoán do dự hoặc một ý định nửa vời về hành động của chính bạn ("có lẽ mình sẽ..., không biết mình có nên..."), nên nó gắn với một hành động bạn đang cân nhắc. -지 싶다 diễn đạt một phán đoán thiên về một hướng rằng một sự việc/trạng thái là đúng như vậy ("mình đoán là..., theo mình thì..."), nên nó gắn với đánh giá của bạn về tình hình thực tế.',
      '-(으)ㄹ까 싶다 は、自分の行動についてのためらいがちな推量や半ば固まった意図（「~しようかな、~すべきかな」）を表すので、検討中の行動に付く。-지 싶다 は、ある事実・状態がそうであるという傾いた判断（「~だと思う、~じゃないかな」）を表すので、物事がどうであるかについての自分の見立てに付く。',
    ),
    items: [
      {
        sentence: '오늘은 피곤하니까 그냥 집에 일찍 {}.',
        optionA: '갈까 싶어요',
        optionB: '가지 싶어요',
        answer: 'a',
        trans: L(
          'I\'m tired today, so I\'m thinking maybe I\'ll just go home early.',
          'Hoy estoy cansado, así que estoy pensando que quizás me voy a casa temprano.',
          'Je suis fatigué aujourd\'hui, alors je me dis que je vais peut-être rentrer tôt.',
          'Hoje estou cansado, então estou pensando que talvez vá para casa cedo.',
          'วันนี้เหนื่อย เลยคิดว่าบางทีอาจจะกลับบ้านเร็วหน่อยดีไหม',
          'Hari ini aku capek, jadi aku berpikir mungkin aku pulang lebih awal saja.',
          'Hôm nay mình mệt, nên mình đang nghĩ hay là về nhà sớm.',
          '今日は疲れたから、早めに家に帰ろうかなと思っている。',
        ),
        why: L(
          'This is a half-formed intention about your own action (whether to go home), so -(으)ㄹ까 싶다 fits; -지 싶다 would wrongly turn a decision you\'re weighing into a factual reckoning, which is unnatural for a first-person choice.',
          'Esta es una intención a medio formar sobre tu propia acción (si volver a casa), así que -(으)ㄹ까 싶다 encaja; -지 싶다 convertiría erróneamente una decisión que estás sopesando en una conjetura factual, lo cual no es natural para una elección en primera persona.',
          'C\'est une intention à demi formée concernant ta propre action (rentrer ou non), donc -(으)ㄹ까 싶다 convient ; -지 싶다 transformerait à tort une décision que tu pèses en une supposition factuelle, ce qui n\'est pas naturel pour un choix à la première personne.',
          'Esta é uma intenção meio formada sobre a sua própria ação (se vai para casa), então -(으)ㄹ까 싶다 encaixa; -지 싶다 transformaria erroneamente uma decisão que você está ponderando em uma conjectura factual, o que não é natural para uma escolha em primeira pessoa.',
          'นี่คือความตั้งใจที่ยังก่อตัวไม่เต็มที่เกี่ยวกับการกระทำของตัวเอง (จะกลับบ้านหรือไม่) ดังนั้น -(으)ㄹ까 싶다 จึงเหมาะสม ส่วน -지 싶다 จะเปลี่ยนการตัดสินใจที่กำลังชั่งใจให้กลายเป็นการคาดเดาเชิงข้อเท็จจริงอย่างผิด ๆ ซึ่งไม่เป็นธรรมชาติสำหรับการเลือกในมุมมองบุคคลที่หนึ่ง',
          'Ini adalah niat yang setengah terbentuk tentang tindakanmu sendiri (apakah pulang), jadi -(으)ㄹ까 싶다 cocok; -지 싶다 akan keliru mengubah keputusan yang sedang kamu timbang menjadi perkiraan faktual, yang tidak alami untuk pilihan orang pertama.',
          'Đây là một ý định nửa vời về hành động của chính bạn (có về nhà hay không), nên -(으)ㄹ까 싶다 phù hợp; -지 싶다 sẽ biến một quyết định bạn đang cân nhắc thành một phán đoán sự thật một cách sai lệch, điều không tự nhiên cho một lựa chọn ở ngôi thứ nhất.',
          'これは自分の行動（家に帰るかどうか）についての半ば固まった意図なので、-(으)ㄹ까 싶다 が合う。-지 싶다 だと、検討中の決断を事実的な推測に誤って変えてしまい、一人称の選択には不自然になる。',
        ),
      },
      {
        sentence: '표정을 보니까 민수가 좀 {}.',
        optionA: '화났을까 싶어요',
        optionB: '화났지 싶어요',
        answer: 'b',
        trans: L(
          'Judging from his face, I\'d say Minsu is a bit angry.',
          'A juzgar por su cara, diría que Minsu está un poco enojado.',
          'À en juger par son visage, je dirais que Minsu est un peu en colère.',
          'A julgar pela cara dele, eu diria que o Minsu está um pouco bravo.',
          'ดูจากสีหน้าของเขาแล้ว ฉันว่ามินซูน่าจะโกรธอยู่นิดหน่อย',
          'Dilihat dari raut wajahnya, kurasa Minsu agak marah.',
          'Nhìn vẻ mặt cậu ấy, mình đoán Minsu hơi giận đấy.',
          '彼の表情を見るに、ミンスは少し怒っているんじゃないかと思う。',
        ),
        why: L(
          'The evidential \'표정을 보니까\' (from his expression) means you\'ve already read the cue and are drawing a leaning conclusion, which is exactly -지 싶다; -(으)ㄹ까 싶다 would mean you\'re merely wondering whether he\'s angry, contradicting the fact that you can see the evidence.',
          'El evidencial \'표정을 보니까\' (por su expresión) significa que ya leíste la señal y estás sacando una conclusión inclinada, que es exactamente -지 싶다; -(으)ㄹ까 싶다 significaría que solo te estás preguntando si está enojado, contradiciendo el hecho de que podés ver la evidencia.',
          'L\'évidentiel \'표정을 보니까\' (d\'après son expression) signifie que tu as déjà lu l\'indice et que tu tires une conclusion penchée, ce qui est exactement -지 싶다 ; -(으)ㄹ까 싶다 voudrait dire que tu te demandes simplement s\'il est en colère, ce qui contredit le fait que tu peux voir la preuve.',
          'O evidencial \'표정을 보니까\' (pela expressão dele) significa que você já leu a pista e está tirando uma conclusão inclinada, que é exatamente -지 싶다; -(으)ㄹ까 싶다 significaria que você está apenas se perguntando se ele está bravo, contradizendo o fato de que você consegue ver a evidência.',
          'คำบ่งชี้หลักฐาน \'표정을 보니까\' (จากสีหน้าของเขา) หมายความว่าคุณได้อ่านสัญญาณแล้วและกำลังสรุปแบบโน้มเอียง ซึ่งตรงกับ -지 싶다 พอดี ส่วน -(으)ㄹ까 싶다 จะหมายความว่าคุณแค่สงสัยว่าเขาโกรธหรือไม่ ซึ่งขัดกับข้อเท็จจริงที่ว่าคุณเห็นหลักฐานอยู่',
          'Penanda bukti \'표정을 보니까\' (dari ekspresinya) berarti kamu sudah membaca isyaratnya dan menarik kesimpulan yang condong, yang persis -지 싶다; -(으)ㄹ까 싶다 akan berarti kamu sekadar bertanya-tanya apakah dia marah, bertentangan dengan fakta bahwa kamu bisa melihat buktinya.',
          'Dấu hiệu chứng cứ \'표정을 보니까\' (từ vẻ mặt của cậu ấy) nghĩa là bạn đã đọc được tín hiệu và đang rút ra kết luận thiên về một hướng, đó chính là -지 싶다; -(으)ㄹ까 싶다 sẽ có nghĩa bạn chỉ đang tự hỏi liệu cậu ấy có giận không, mâu thuẫn với việc bạn đã thấy bằng chứng.',
          '証拠を示す \'표정을 보니까\'（彼の表情を見て）は、すでに手がかりを読み取って傾いた結論を出していることを意味し、それがまさに -지 싶다 である。-(으)ㄹ까 싶다 だと、彼が怒っているかどうかを単に推し量っているという意味になり、証拠が見えているという事実と矛盾する。',
        ),
      },
      {
        sentence: '비가 이렇게 오는데 약속을 그냥 {}.',
        optionA: '취소할까 싶어요',
        optionB: '취소하지 싶어요',
        answer: 'a',
        trans: L(
          'It\'s raining like this, so I\'m thinking maybe I\'ll just cancel the appointment.',
          'Está lloviendo así, así que estoy pensando que quizás mejor cancelo la cita.',
          'Il pleut comme ça, alors je me dis que je vais peut-être annuler le rendez-vous.',
          'Está chovendo assim, então estou pensando que talvez seja melhor cancelar o compromisso.',
          'ฝนตกแบบนี้ ฉันเลยคิดว่าบางทีอาจจะยกเลิกนัดไปเลยดีไหม',
          'Hujannya begini, jadi aku berpikir mungkin lebih baik aku batalkan saja janjinya.',
          'Mưa thế này, nên mình đang nghĩ hay là hủy cuộc hẹn luôn.',
          'こんなに雨が降っているから、約束をキャンセルしようかなと思っている。',
        ),
        why: L(
          'This is a tentative intention about your own action (whether to cancel), so -(으)ㄹ까 싶다 fits; -지 싶다 would imply judging a fact, which is wrong for a decision you\'re weighing.',
          'Esta es una intención tentativa sobre tu propia acción (si cancelar), así que -(으)ㄹ까 싶다 encaja; -지 싶다 implicaría juzgar un hecho, lo cual es incorrecto para una decisión que estás sopesando.',
          'C\'est une intention provisoire concernant ta propre action (annuler ou non), donc -(으)ㄹ까 싶다 convient ; -지 싶다 impliquerait de juger un fait, ce qui est incorrect pour une décision que tu pèses.',
          'Esta é uma intenção tentativa sobre a sua própria ação (se cancelar), então -(으)ㄹ까 싶다 encaixa; -지 싶다 implicaria julgar um fato, o que é errado para uma decisão que você está ponderando.',
          'นี่คือความตั้งใจแบบลังเลเกี่ยวกับการกระทำของตัวเอง (จะยกเลิกหรือไม่) ดังนั้น -(으)ㄹ까 싶다 จึงเหมาะสม ส่วน -지 싶다 จะสื่อถึงการตัดสินข้อเท็จจริง ซึ่งผิดสำหรับการตัดสินใจที่กำลังชั่งใจอยู่',
          'Ini adalah niat tentatif tentang tindakanmu sendiri (apakah membatalkan), jadi -(으)ㄹ까 싶다 cocok; -지 싶다 akan menyiratkan menilai sebuah fakta, yang keliru untuk keputusan yang sedang kamu timbang.',
          'Đây là một ý định ướm thử về hành động của chính bạn (có hủy hay không), nên -(으)ㄹ까 싶다 phù hợp; -지 싶다 sẽ ngụ ý phán đoán một sự thật, điều sai cho một quyết định bạn đang cân nhắc.',
          'これは自分の行動（キャンセルするかどうか）についての暫定的な意図なので、-(으)ㄹ까 싶다 が合う。-지 싶다 だと事実を判断するという含みになり、検討中の決断には不適切である。',
        ),
      },
    ],
  },
]
