import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK 6 confusable grammar/ending pairs (extra batch). a/b match
 * grammars-n*.ts kos verbatim. Each pair: a contrast note + 3 single-answer
 * discrimination items, 8-locale note/trans/why.
 *
 * Drafted + Korean-lens adversarially verified (single-correct-answer crux,
 * naturalness, conjugation, register, 8-locale fidelity). Native (Korean wife)
 * review is the documented final gate.
 */
export const N6_PAIRS_EXTRA: ConfusablePair[] = [
  {
    id: 'geonniwa-ppunmanira',
    a: '-거니와',
    b: '-(으)ㄹ 뿐만 아니라',
    note: L(
      'Both add "not only ... but also." -거니와 is literary and elevated, used in essays, formal praise, and written prose, and often carries a tone of acknowledging the first fact before adding a second; the verb/adjective stem takes it directly (뛰어나거니와). -(으)ㄹ 뿐만 아니라 is the standard, register-neutral "not only" that fits everyday speech, news, and ordinary writing, realized on the future/attributive form (뛰어날 뿐만 아니라).',
      'Ambos añaden "no solo ... sino también". -거니와 es literario y elevado, propio de ensayos, elogios formales y prosa escrita, y a menudo lleva un matiz de reconocer el primer hecho antes de añadir el segundo; la raíz del verbo/adjetivo lo toma directamente (뛰어나거니와). -(으)ㄹ 뿐만 아니라 es el "no solo" estándar y neutro de registro, apto para el habla cotidiana, las noticias y la escritura común, realizado sobre la forma de futuro/atributiva (뛰어날 뿐만 아니라).',
      'Les deux ajoutent « non seulement ... mais aussi ». -거니와 est littéraire et soutenu, employé dans les essais, les éloges formels et la prose écrite, et porte souvent une nuance de reconnaissance du premier fait avant d\'ajouter le second ; le radical du verbe/adjectif le prend directement (뛰어나거니와). -(으)ㄹ 뿐만 아니라 est le « non seulement » standard et neutre de registre, adapté à la langue courante, aux nouvelles et à l\'écriture ordinaire, réalisé sur la forme de futur/attributive (뛰어날 뿐만 아니라).',
      'Ambos acrescentam "não só ... mas também". -거니와 é literário e elevado, usado em ensaios, elogios formais e prosa escrita, e muitas vezes traz um tom de reconhecer o primeiro fato antes de acrescentar o segundo; o radical do verbo/adjetivo o recebe diretamente (뛰어나거니와). -(으)ㄹ 뿐만 아니라 é o "não só" padrão e neutro de registro, adequado à fala cotidiana, ao noticiário e à escrita comum, realizado sobre a forma de futuro/atributiva (뛰어날 뿐만 아니라).',
      'ทั้งคู่ใช้เสริมความว่า "ไม่เพียง ... แต่ยัง" -거니와 เป็นรูปเชิงวรรณกรรมและสูงส่ง ใช้ในเรียงความ คำชมเชยทางการ และงานเขียนร้อยแก้ว และมักมีน้ำเสียงยอมรับข้อเท็จจริงแรกก่อนเสริมข้อที่สอง โดยรากของคำกริยา/คำคุณศัพท์เติมต่อได้โดยตรง (뛰어나거니와) ส่วน -(으)ㄹ 뿐만 아니라 เป็นรูป "ไม่เพียง" มาตรฐานที่เป็นกลางทางระดับภาษา เหมาะกับการพูดในชีวิตประจำวัน ข่าว และงานเขียนทั่วไป โดยเติมบนรูปอนาคต/รูปขยาย (뛰어날 뿐만 아니라)',
      'Keduanya menambahkan "tidak hanya ... tetapi juga". -거니와 bersifat sastrawi dan tinggi, dipakai dalam esai, pujian formal, dan prosa tulis, serta sering membawa nada mengakui fakta pertama sebelum menambahkan yang kedua; akar verba/adjektiva menerimanya langsung (뛰어나거니와). -(으)ㄹ 뿐만 아니라 adalah "tidak hanya" yang baku dan netral ragam, cocok untuk percakapan sehari-hari, berita, dan tulisan biasa, direalisasikan pada bentuk futur/atributif (뛰어날 뿐만 아니라).',
      'Cả hai đều bổ sung ý "không những ... mà còn". -거니와 mang tính văn chương và trang nhã, dùng trong tản văn, lời khen trang trọng và văn viết, và thường mang sắc thái thừa nhận sự việc thứ nhất trước khi thêm sự việc thứ hai; gốc động/tính từ gắn trực tiếp (뛰어나거니와). -(으)ㄹ 뿐만 아니라 là cách nói "không những" chuẩn mực, trung tính về phong cách, hợp với lời nói thường ngày, tin tức và văn viết thông thường, được hiện thực hóa trên dạng tương lai/định ngữ (뛰어날 뿐만 아니라).',
      'どちらも「〜だけでなく…も」を付け加える。-거니와 は文学的で格調が高く、随筆や改まった称賛、書き言葉の文章で用いられ、最初の事実を認めたうえで二つ目を付け加える語調をしばしば帯びる。動詞・形容詞の語幹に直接付く（뛰어나거니와）。-(으)ㄹ 뿐만 아니라 は語調が中立の標準的な「〜だけでなく」で、日常会話・報道・普通の文章に合い、未来・連体の形に付いて実現する（뛰어날 뿐만 아니라）。',
    ),
    items: [
      {
        sentence: '그분은 학식이 {} 인품 또한 더없이 고매하시다.',
        optionA: '깊거니와',
        optionB: '깊을 뿐만 아니라',
        answer: 'a',
        trans: L(
          'Not only is their learning profound, but their character too is supremely noble.',
          'No solo es profundo su saber, sino que su carácter también es sumamente noble.',
          'Non seulement leur savoir est profond, mais leur caractère aussi est suprêmement noble.',
          'Não só o seu saber é profundo, como também o seu caráter é sumamente nobre.',
          'ท่านผู้นั้นไม่เพียงมีความรู้ลึกซึ้ง หากอุปนิสัยใจคอยังสูงส่งหาที่เปรียบมิได้',
          'Ilmunya tidak hanya dalam, tetapi karakternya pun amat luhur.',
          'Người ấy không những học vấn uyên thâm mà nhân cách cũng cao quý khôn sánh.',
          'あの方は学識が深いのみならず、人格もこの上なく高潔でいらっしゃる。',
        ),
        why: L(
          'The solemn, written-praise tone (학식, 인품 또한, 고매하시다) calls for the literary -거니와 (깊거니와); the register-neutral -(으)ㄹ 뿐만 아니라 sits below this elevated, essay-like sentence.',
          'El tono solemne de elogio escrito (학식, 인품 또한, 고매하시다) pide el literario -거니와 (깊거니와); el neutro -(으)ㄹ 뿐만 아니라 queda por debajo de esta oración elevada, de tipo ensayo.',
          'Le ton solennel d\'éloge écrit (학식, 인품 또한, 고매하시다) appelle le littéraire -거니와 (깊거니와) ; le neutre -(으)ㄹ 뿐만 아니라 reste en deçà de cette phrase élevée, de type essai.',
          'O tom solene de elogio escrito (학식, 인품 또한, 고매하시다) pede o literário -거니와 (깊거니와); o neutro -(으)ㄹ 뿐만 아니라 fica abaixo desta frase elevada, de tipo ensaio.',
          'น้ำเสียงคำชมเชิงงานเขียนอันขรึมขลัง (학식, 인품 또한, 고매하시다) เรียกร้องให้ใช้ -거니와 เชิงวรรณกรรม (깊거니와) ส่วน -(으)ㄹ 뿐만 아니라 ที่เป็นกลางทางระดับภาษาต่ำกว่าประโยคสูงส่งแบบเรียงความนี้',
          'Nada pujian tertulis yang khidmat (학식, 인품 또한, 고매하시다) menuntut -거니와 yang sastrawi (깊거니와); -(으)ㄹ 뿐만 아니라 yang netral berada di bawah kalimat tinggi bergaya esai ini.',
          'Giọng điệu khen ngợi trang trọng trong văn viết (학식, 인품 또한, 고매하시다) đòi hỏi -거니와 văn chương (깊거니와); -(으)ㄹ 뿐만 아니라 trung tính nằm dưới câu văn cao nhã, đậm chất tản văn này.',
          '荘重な書き言葉の称賛の語調（학식・인품 또한・고매하시다）には文学的な -거니와（깊거니와）がふさわしく、語調が中立の -(으)ㄹ 뿐만 아니라 はこの格調高い随筆調の文には釣り合わない。',
        ),
      },
      {
        sentence: '이 식당은 가격이 {} 양도 진짜 많아서 자주 가요.',
        optionA: '싸거니와',
        optionB: '쌀 뿐만 아니라',
        answer: 'b',
        trans: L(
          'This restaurant is not only cheap but the portions are really big too, so I go often.',
          'Este restaurante no solo es barato, sino que las porciones también son enormes, así que voy seguido.',
          'Ce restaurant est non seulement bon marché, mais les portions sont vraiment grandes aussi, alors j\'y vais souvent.',
          'Este restaurante não só é barato, como as porções também são bem grandes, então vou com frequência.',
          'ร้านนี้ไม่เพียงราคาถูก แต่ปริมาณยังเยอะมากด้วย เลยไปบ่อย',
          'Restoran ini tidak hanya murah, tetapi porsinya juga benar-benar banyak, jadi aku sering ke sana.',
          'Quán này không những giá rẻ mà phần ăn cũng thật sự nhiều nên tôi hay ghé.',
          'この食堂は値段が安いだけでなく量も本当に多いので、よく行きます。',
        ),
        why: L(
          'A casual, spoken recommendation (진짜 많아서, 자주 가요) takes the register-neutral -(으)ㄹ 뿐만 아니라 (쌀 뿐만 아니라); the literary -거니와 would sound oddly bookish in this everyday chat.',
          'Una recomendación casual y hablada (진짜 많아서, 자주 가요) lleva el neutro -(으)ㄹ 뿐만 아니라 (쌀 뿐만 아니라); el literario -거니와 sonaría raramente libresco en esta charla cotidiana.',
          'Une recommandation orale et décontractée (진짜 많아서, 자주 가요) prend le neutre -(으)ㄹ 뿐만 아니라 (쌀 뿐만 아니라) ; le littéraire -거니와 sonnerait étrangement livresque dans cette conversation du quotidien.',
          'Uma recomendação casual e falada (진짜 많아서, 자주 가요) usa o neutro -(으)ㄹ 뿐만 아니라 (쌀 뿐만 아니라); o literário -거니와 soaria estranhamente livresco nesta conversa cotidiana.',
          'การแนะนำแบบลำลองในการพูด (진짜 많아서, 자주 가요) ใช้ -(으)ㄹ 뿐만 아니라 ที่เป็นกลาง (쌀 뿐만 아니라) ส่วน -거니와 เชิงวรรณกรรมจะฟังดูเป็นภาษาหนังสือแปลก ๆ ในบทสนทนาประจำวันนี้',
          'Rekomendasi santai dalam percakapan (진짜 많아서, 자주 가요) memakai -(으)ㄹ 뿐만 아니라 yang netral (쌀 뿐만 아니라); -거니와 yang sastrawi akan terdengar janggal seperti bahasa buku dalam obrolan sehari-hari ini.',
          'Một lời gợi ý đời thường khi nói (진짜 많아서, 자주 가요) dùng -(으)ㄹ 뿐만 아니라 trung tính (쌀 뿐만 아니라); -거니와 văn chương sẽ nghe sách vở một cách lạc lõng trong câu trò chuyện thường ngày này.',
          'くだけた話し言葉のおすすめ（진짜 많아서・자주 가요）には語調が中立の -(으)ㄹ 뿐만 아니라（쌀 뿐만 아니라）が合い、文学的な -거니와 はこの日常会話では不自然に書き言葉めいて聞こえる。',
        ),
      },
      {
        sentence: '그는 평생 학문에 헌신{} 후학을 기르는 데에도 온 힘을 쏟았다.',
        optionA: '했거니와',
        optionB: '할 뿐만 아니라',
        answer: 'a',
        trans: L(
          'He devoted his whole life to scholarship, and moreover poured all his strength into nurturing the next generation of scholars.',
          'Dedicó toda su vida al saber y, además, volcó todas sus fuerzas en formar a los estudiosos venideros.',
          'Il a consacré toute sa vie au savoir et, de plus, a déployé toutes ses forces à former la relève savante.',
          'Ele dedicou toda a vida ao saber e, além disso, empenhou todas as forças em formar os estudiosos vindouros.',
          'เขาอุทิศทั้งชีวิตให้แก่วิชาการ อีกทั้งยังทุ่มเทกำลังทั้งหมดในการบ่มเพาะนักวิชาการรุ่นหลังด้วย',
          'Ia mengabdikan seluruh hidupnya pada keilmuan, dan terlebih lagi mencurahkan segenap tenaganya untuk membina para sarjana penerus.',
          'Ông dành cả đời cho học vấn, hơn nữa còn dốc hết sức lực vào việc đào tạo lớp học giả kế cận.',
          '彼は生涯を学問に捧げたのみならず、後進を育てることにも全力を注いだ。',
        ),
        why: L(
          'A reflective, biographical-essay narration with a past-tense literary cadence (헌신했거니와, 온 힘을 쏟았다) takes -거니와, which can attach to the past stem; -(으)ㄹ 뿐만 아니라 lacks this elevated written tone and would flatten the eulogistic register.',
          'Una narración reflexiva, de ensayo biográfico, con cadencia literaria en pasado (헌신했거니와, 온 힘을 쏟았다) lleva -거니와, que puede adjuntarse a la raíz de pasado; -(으)ㄹ 뿐만 아니라 carece de este tono escrito elevado y aplanaría el registro elogioso.',
          'Une narration réflexive, d\'essai biographique, à la cadence littéraire au passé (헌신했거니와, 온 힘을 쏟았다) prend -거니와, qui peut s\'attacher au radical du passé ; -(으)ㄹ 뿐만 아니라 n\'a pas ce ton écrit élevé et aplatirait le registre élogieux.',
          'Uma narração reflexiva, de ensaio biográfico, com cadência literária no passado (헌신했거니와, 온 힘을 쏟았다) usa -거니와, que pode ligar-se ao radical de passado; -(으)ㄹ 뿐만 아니라 carece desse tom escrito elevado e achataria o registro elogioso.',
          'การเล่าเรื่องเชิงครุ่นคิดแบบเรียงความชีวประวัติด้วยจังหวะวรรณกรรมในรูปอดีต (헌신했거니와, 온 힘을 쏟았다) ใช้ -거니와 ซึ่งเติมต่อรากรูปอดีตได้ ส่วน -(으)ㄹ 뿐만 아니라 ขาดน้ำเสียงงานเขียนสูงส่งนี้และจะทำให้ระดับภาษาเชิงยกย่องแบนราบลง',
          'Narasi reflektif bergaya esai biografi dengan irama sastrawi berkala lampau (헌신했거니와, 온 힘을 쏟았다) memakai -거니와, yang bisa melekat pada akar lampau; -(으)ㄹ 뿐만 아니라 tak punya nada tulis tinggi ini dan akan mendatarkan ragam pujian.',
          'Lời kể suy ngẫm mang dáng dấp tản văn tiểu sử với nhịp văn chương ở quá khứ (헌신했거니와, 온 힘을 쏟았다) dùng -거니와, vốn có thể gắn vào gốc quá khứ; -(으)ㄹ 뿐만 아니라 thiếu giọng văn viết cao nhã này và sẽ làm nhạt đi văn phong ca tụng.',
          '過去形の文学的な韻律を伴う、内省的な評伝随筆の叙述（헌신했거니와・온 힘을 쏟았다）には、過去語幹にも付く -거니와 がふさわしい。-(으)ㄹ 뿐만 아니라 はこの格調高い書き言葉の語調を欠き、追慕的な語調を平板にしてしまう。',
        ),
      },
    ],
  },
  {
    id: 'ljieonjeong-lmangjeong',
    a: '-(으)ㄹ지언정',
    b: '-(으)ㄹ망정',
    note: L(
      'Both are literary concessions of firm resolve ("even if it means ..."). -(으)ㄹ지언정 sets up the extreme you would sooner accept and is strongly adversative, typically before a flat refusal or negation ("I\'d rather die than surrender"). -(으)ㄹ망정 grants a lesser or already-bad state as a given and then asserts a contrasting positive stance you still keep ("even if I end up poor, at least I\'ll stay honest") — it leans on "even though things are only this / have come to this, still ...".',
      'Ambas son concesiones literarias de firme resolución ("aunque eso signifique ..."). -(으)ㄹ지언정 plantea el extremo que aceptarías antes y es fuertemente adversativa, normalmente ante un rechazo rotundo o una negación ("preferiría morir antes que rendirme"). -(으)ㄹ망정 concede como dado un estado menor o ya malo y luego afirma una postura positiva contraria que igual mantenés ("aunque acabe pobre, al menos seré honesto") — se apoya en "aunque las cosas sean solo esto / hayan llegado a esto, aun así ...".',
      'Toutes deux sont des concessions littéraires de ferme résolution (« même si cela signifie ... »). -(으)ㄹ지언정 pose l\'extrême que l\'on accepterait plutôt et est fortement adversative, généralement devant un refus net ou une négation (« je préférerais mourir plutôt que me rendre »). -(으)ㄹ망정 concède comme un fait un état moindre ou déjà mauvais, puis affirme une posture positive contraire que l\'on garde quand même (« même si je finis pauvre, au moins je resterai honnête ») — elle s\'appuie sur « même si les choses n\'en sont qu\'à cela / en sont arrivées là, malgré tout ... ».',
      'Ambas são concessões literárias de firme resolução ("mesmo que isso signifique ..."). -(으)ㄹ지언정 estabelece o extremo que você aceitaria antes e é fortemente adversativa, em geral diante de uma recusa categórica ou negação ("prefiro morrer a me render"). -(으)ㄹ망정 concede como dado um estado menor ou já ruim e então afirma uma postura positiva contrária que você ainda mantém ("mesmo que eu acabe pobre, ao menos serei honesto") — apoia-se em "mesmo que as coisas sejam só isto / tenham chegado a isto, ainda assim ...".',
      'ทั้งคู่เป็นรูปยอม-อ้างเหตุเชิงวรรณกรรมที่แสดงความมุ่งมั่นแน่วแน่ ("ต่อให้นั่นหมายถึง ...") -(으)ㄹ지언정 วางขั้วสุดโต่งที่ผู้พูดยอมรับเสียมากกว่า และมีน้ำเสียงขัดแย้งอย่างหนักแน่น มักนำหน้าการปฏิเสธเด็ดขาด ("ข้ายอมตายดีกว่ายอมจำนน") ส่วน -(으)ㄹ망정 ยอมรับสภาพที่ด้อยกว่าหรือแย่อยู่แล้วเป็นข้อตั้ง แล้วยืนยันท่าทีเชิงบวกที่ตรงข้ามซึ่งยังคงรักษาไว้ ("ต่อให้ต้องจน อย่างน้อยก็จะซื่อสัตย์") — โดยอิงกับความหมายว่า "ถึงสภาพจะเป็นแค่นี้/มาถึงขั้นนี้แล้ว ก็ยังคง ..."',
      'Keduanya adalah konsesi sastrawi yang menyatakan tekad teguh ("sekalipun itu berarti ..."). -(으)ㄹ지언정 menetapkan keadaan ekstrem yang lebih rela diterima dan bersifat sangat adversatif, biasanya sebelum penolakan tegas atau negasi ("aku lebih baik mati daripada menyerah"). -(으)ㄹ망정 mengakui keadaan yang lebih rendah atau sudah buruk sebagai kenyataan, lalu menegaskan sikap positif yang berlawanan yang tetap dipegang ("meskipun aku jatuh miskin, setidaknya aku akan tetap jujur") — bertumpu pada "meskipun keadaan hanya sebatas ini / sudah sampai begini, tetap saja ...".',
      'Cả hai đều là cách nhượng bộ văn chương thể hiện quyết tâm vững vàng ("dù điều đó có nghĩa là ..."). -(으)ㄹ지언정 nêu ra điều cực đoan mà người nói thà chấp nhận và mang tính tương phản mạnh, thường đứng trước một sự từ chối dứt khoát hay phủ định ("thà chết chứ không đầu hàng"). -(으)ㄹ망정 thừa nhận một trạng thái kém hơn hoặc đã xấu như một điều hiển nhiên rồi khẳng định một lập trường tích cực trái ngược vẫn được giữ ("dù có nghèo đi, ít nhất tôi vẫn sống lương thiện") — dựa trên ý "dù mọi sự chỉ đến mức này / đã ra nông nỗi này, vẫn ...".',
      'どちらも固い決意を表す文学的な譲歩（「たとえそれが…を意味しても」）。-(으)ㄹ지언정 は、むしろ受け入れる極端なほうを提示し、強い逆接で、たいてい断固たる拒否や否定の前に置く（「降伏するくらいなら死を選ぶ」）。-(으)ㄹ망정 は、より劣る、あるいはすでに悪い状態を前提として認めたうえで、なお保ち続ける対照的に肯定的な態度を主張する（「たとえ貧しくなろうとも、せめて正直でいよう」）——「たとえ事態がこの程度であっても／ここまで来てしまっても、それでも…」に根ざす。',
    ),
    items: [
      {
        sentence: '나는 굶어 {} 도둑질만은 결코 하지 않겠다.',
        optionA: '죽을지언정',
        optionB: '죽을망정',
        answer: 'a',
        trans: L(
          'Even if I starve to death, I will never, ever steal.',
          'Aunque me muera de hambre, jamás robaré.',
          'Même si je dois mourir de faim, jamais je ne volerai.',
          'Mesmo que eu morra de fome, jamais roubarei.',
          'ต่อให้ข้าต้องอดตาย ก็จะไม่มีวันลักขโมยเป็นอันขาด',
          'Sekalipun aku mati kelaparan, aku tidak akan pernah mencuri.',
          'Dù có chết đói, tôi cũng quyết không bao giờ trộm cắp.',
          'たとえ飢え死にしようとも、盗みだけは決してしない。',
        ),
        why: L(
          'The clause names the extreme one would sooner accept (죽다) and is followed by a flat refusal (결코 하지 않겠다) — the prototypical adversative -(으)ㄹ지언정. -(으)ㄹ망정 grants a lesser/already-bad state to keep a positive stance, so it clashes with starving-to-death paired with an absolute "never" refusal.',
          'La cláusula nombra el extremo que uno aceptaría antes (죽다) y va seguida de un rechazo rotundo (결코 하지 않겠다): la adversativa prototípica -(으)ㄹ지언정. -(으)ㄹ망정 concede un estado menor/ya malo para mantener una postura positiva, así que choca con morir de hambre junto a un "jamás" absoluto.',
          'La proposition nomme l\'extrême que l\'on accepterait plutôt (죽다) et est suivie d\'un refus net (결코 하지 않겠다) : l\'adversative prototypique -(으)ㄹ지언정. -(으)ㄹ망정 concède un état moindre/déjà mauvais pour garder une posture positive, donc elle jure avec « mourir de faim » associé à un « jamais » absolu.',
          'A oração nomeia o extremo que se aceitaria antes (죽다) e é seguida de uma recusa categórica (결코 하지 않겠다): a adversativa prototípica -(으)ㄹ지언정. -(으)ㄹ망정 concede um estado menor/já ruim para manter uma postura positiva, então colide com morrer de fome aliado a um "jamais" absoluto.',
          'อนุประโยคระบุขั้วสุดโต่งที่ผู้พูดยอมรับเสียมากกว่า (죽다) และตามด้วยการปฏิเสธเด็ดขาด (결코 하지 않겠다) อันเป็น -(으)ㄹ지언정 แบบต้นแบบ ส่วน -(으)ㄹ망정 ยอมรับสภาพที่ด้อยกว่า/แย่อยู่แล้วเพื่อรักษาท่าทีเชิงบวก จึงขัดกับการอดตายที่จับคู่กับคำว่า "ไม่มีวัน" อย่างเด็ดขาด',
          'Klausa ini menyebut keadaan ekstrem yang lebih rela diterima (죽다) dan diikuti penolakan tegas (결코 하지 않겠다) — -(으)ㄹ지언정 yang prototipikal. -(으)ㄹ망정 mengakui keadaan lebih rendah/sudah buruk demi mempertahankan sikap positif, sehingga berbenturan dengan mati kelaparan yang dipasangkan dengan "tidak akan pernah" yang mutlak.',
          'Mệnh đề nêu điều cực đoan mà người ta thà chấp nhận (죽다) và theo sau là một sự từ chối dứt khoát (결코 하지 않겠다) — đúng kiểu -(으)ㄹ지언정 điển hình. -(으)ㄹ망정 thừa nhận một trạng thái kém hơn/đã xấu để giữ lập trường tích cực, nên xung khắc với "chết đói" đi kèm lời từ chối tuyệt đối "không bao giờ".',
          'この節は、むしろ受け入れる極端なほう（죽다）を挙げ、断固たる拒否（결코 하지 않겠다）が続く——まさに典型的な逆接の -(으)ㄹ지언정 だ。-(으)ㄹ망정 は、より劣る・すでに悪い状態を認めて肯定的な態度を保つ用法なので、飢え死にと絶対的な「決して〜ない」という拒否との組み合わせには合わない。',
        ),
      },
      {
        sentence: '비록 단칸방에 {} 마음만은 누구보다 넉넉했다.',
        optionA: '살지언정',
        optionB: '살망정',
        answer: 'b',
        trans: L(
          'Even though we lived in just a single room, in our hearts we were richer than anyone.',
          'Aunque vivíamos en una sola habitación, en el corazón éramos más ricos que nadie.',
          'Même si nous vivions dans une seule pièce, dans nos cœurs nous étions plus riches que quiconque.',
          'Mesmo morando num único cômodo, no coração éramos mais ricos que ninguém.',
          'แม้จะอยู่กันเพียงห้องเดียว แต่ในใจกลับอิ่มเอมยิ่งกว่าผู้ใด',
          'Meskipun kami hanya tinggal di satu kamar, dalam hati kami lebih kaya daripada siapa pun.',
          'Dẫu chỉ sống trong một căn phòng nhỏ, nhưng trong lòng lại sung túc hơn bất cứ ai.',
          'たとえ一間きりの部屋に住んでいようとも、心だけは誰よりも豊かだった。',
        ),
        why: L(
          'A lesser/humble state is granted as a given (단칸방에 삶) and then offset by a contrasting positive (마음만은 넉넉했다) — the "even if it\'s only this, still ..." pattern of -(으)ㄹ망정. -(으)ㄹ지언정 needs an extreme you\'d sooner accept before a refusal, which the warm, affirming main clause here is not.',
          'Se concede como dado un estado menor/humilde (vivir en una sola habitación) y luego se compensa con un positivo contrario (en el corazón éramos ricos): el patrón "aunque sea solo esto, aun así ..." de -(으)ㄹ망정. -(으)ㄹ지언정 exige un extremo que aceptarías antes de un rechazo, y la cálida cláusula afirmativa de aquí no lo es.',
          'Un état moindre/humble est concédé comme un fait (vivre dans une seule pièce) puis compensé par un positif contraire (dans nos cœurs nous étions riches) : le schéma « même si ce n\'est que cela, malgré tout ... » de -(으)ㄹ망정. -(으)ㄹ지언정 exige un extrême que l\'on accepterait avant un refus, ce que la chaleureuse proposition affirmative n\'est pas ici.',
          'Concede-se como dado um estado menor/humilde (morar num único cômodo) e depois compensa-se com um positivo contrário (no coração éramos ricos): o padrão "mesmo que seja só isto, ainda assim ..." de -(으)ㄹ망정. -(으)ㄹ지언정 exige um extremo que se aceitaria antes de uma recusa, e a calorosa oração afirmativa aqui não é isso.',
          'มีการยอมรับสภาพที่ด้อยกว่า/ต่ำต้อยเป็นข้อตั้ง (อยู่ห้องเดียว) แล้วถ่วงด้วยข้อความเชิงบวกที่ตรงข้าม (ในใจกลับอิ่มเอม) อันเป็นแบบแผน "ถึงจะเป็นแค่นี้ ก็ยังคง ..." ของ -(으)ㄹ망정 ส่วน -(으)ㄹ지언정 ต้องการขั้วสุดโต่งที่ยอมรับก่อนการปฏิเสธ ซึ่งประโยคหลักที่อบอุ่นและยืนยันในที่นี้ไม่ใช่เช่นนั้น',
          'Keadaan yang lebih rendah/sederhana diakui sebagai kenyataan (tinggal di satu kamar) lalu diimbangi dengan hal positif yang berlawanan (dalam hati kami kaya) — pola "meskipun hanya sebatas ini, tetap saja ..." dari -(으)ㄹ망정. -(으)ㄹ지언정 butuh keadaan ekstrem yang lebih rela diterima sebelum penolakan, yang bukan merupakan klausa utama yang hangat dan afirmatif di sini.',
          'Một trạng thái kém hơn/khiêm nhường được thừa nhận như điều hiển nhiên (sống trong một phòng nhỏ) rồi được bù lại bằng điều tích cực trái ngược (trong lòng sung túc) — đúng kiểu "dù chỉ đến mức này, vẫn ..." của -(으)ㄹ망정. -(으)ㄹ지언정 cần một điều cực đoan thà chấp nhận trước một sự từ chối, mà mệnh đề chính ấm áp, khẳng định ở đây thì không phải vậy.',
          'より劣る・つましい状態を前提として認め（一間きりの部屋に住む）、対照的に肯定的なこと（心は豊かだった）で受ける——「たとえこの程度でも、それでも…」という -(으)ㄹ망정 の型だ。-(으)ㄹ지언정 は拒否の前に、むしろ受け入れる極端なほうを必要とするが、ここの温かく肯定的な主節はそれに当たらない。',
        ),
      },
      {
        sentence: '회사가 {} 직원들의 월급을 떼어먹는 짓은 하지 않겠습니다.',
        optionA: '망할지언정',
        optionB: '망할망정',
        answer: 'a',
        trans: L(
          'Even if the company goes bankrupt, I will never withhold the employees\' wages.',
          'Aunque la empresa quiebre, jamás dejaré de pagar el sueldo a los empleados.',
          'Même si l\'entreprise fait faillite, jamais je ne retiendrai les salaires des employés.',
          'Mesmo que a empresa vá à falência, jamais deixarei de pagar os salários dos funcionários.',
          'ต่อให้บริษัทล้มละลาย ผมก็จะไม่มีวันเบี้ยวเงินเดือนพนักงานเป็นอันขาด',
          'Sekalipun perusahaan bangkrut, saya tidak akan pernah menahan gaji karyawan.',
          'Dù công ty có phá sản, tôi cũng quyết không bao giờ quỵt lương của nhân viên.',
          'たとえ会社がつぶれようとも、社員の給料を踏み倒すような真似はしません。',
        ),
        why: L(
          'The first clause states the extreme one would sooner accept (회사가 망함) and the main clause is a categorical refusal (하지 않겠습니다), which is exactly -(으)ㄹ지언정. -(으)ㄹ망정 would frame bankruptcy as a merely lesser/given state offset by a positive, but here it is the worst outcome being weighed against a moral line — so the adversative-refusal -(으)ㄹ지언정 is the single fit.',
          'La primera cláusula enuncia el extremo que uno aceptaría antes (que la empresa quiebre) y la principal es un rechazo categórico (no lo haré), que es justamente -(으)ㄹ지언정. -(으)ㄹ망정 plantearía la quiebra como un estado menor/dado compensado por un positivo, pero aquí es el peor desenlace sopesado frente a una línea moral, así que la adversativa-rechazo -(으)ㄹ지언정 es el único ajuste.',
          'La première proposition énonce l\'extrême que l\'on accepterait plutôt (que l\'entreprise fasse faillite) et la principale est un refus catégorique (je ne le ferai pas), ce qui est précisément -(으)ㄹ지언정. -(으)ㄹ망정 présenterait la faillite comme un état simplement moindre/admis compensé par un positif, mais ici c\'est le pire dénouement pesé contre une ligne morale, donc l\'adversative-refus -(으)ㄹ지언정 est le seul choix.',
          'A primeira oração enuncia o extremo que se aceitaria antes (a empresa falir) e a principal é uma recusa categórica (não o farei), que é exatamente -(으)ㄹ지언정. -(으)ㄹ망정 enquadraria a falência como um estado meramente menor/dado compensado por um positivo, mas aqui é o pior desfecho ponderado contra uma linha moral, então a adversativa-recusa -(으)ㄹ지언정 é o único encaixe.',
          'อนุประโยคแรกระบุขั้วสุดโต่งที่ยอมรับเสียมากกว่า (บริษัทล้มละลาย) และประโยคหลักเป็นการปฏิเสธเด็ดขาด (จะไม่ทำ) ซึ่งเป็น -(으)ㄹ지언정 พอดี ส่วน -(으)ㄹ망정 จะวางการล้มละลายเป็นเพียงสภาพที่ด้อยกว่า/เป็นข้อตั้งที่ถ่วงด้วยข้อความเชิงบวก แต่ในที่นี้มันคือผลลัพธ์ที่เลวร้ายที่สุดที่ถูกชั่งกับเส้นทางศีลธรรม ดังนั้น -(으)ㄹ지언정 แบบขัดแย้ง-ปฏิเสธจึงเป็นตัวเลือกเดียว',
          'Klausa pertama menyatakan keadaan ekstrem yang lebih rela diterima (perusahaan bangkrut) dan klausa utama adalah penolakan kategoris (tidak akan saya lakukan), yang persis -(으)ㄹ지언정. -(으)ㄹ망정 akan membingkai kebangkrutan sebagai keadaan yang sekadar lebih rendah/diberikan dan diimbangi hal positif, tetapi di sini itu adalah hasil terburuk yang ditimbang terhadap garis moral — jadi -(으)ㄹ지언정 yang adversatif-menolak adalah satu-satunya yang cocok.',
          'Mệnh đề đầu nêu điều cực đoan mà người ta thà chấp nhận (công ty phá sản) và mệnh đề chính là một sự từ chối dứt khoát (sẽ không làm), đúng là 지-(으)ㄹ지언정. -(으)ㄹ망정 sẽ đóng khung việc phá sản như một trạng thái chỉ kém hơn/hiển nhiên được bù bằng điều tích cực, nhưng ở đây đó là kết cục tệ nhất được đặt lên cân với một lằn ranh đạo đức — nên -(으)ㄹ지언정 mang tính tương phản-từ chối là lựa chọn duy nhất.',
          '前の節は、むしろ受け入れる極端なほう（会社がつぶれる）を述べ、主節は断固たる拒否（しません）であり、まさに -(으)ㄹ지언정 だ。-(으)ㄹ망정 は倒産を、肯定で受ける単に劣る・前提的な状態として枠づけてしまうが、ここでは道徳的一線と天秤にかけられた最悪の結末なので、逆接・拒否の -(으)ㄹ지언정 が唯一の正解となる。',
        ),
      },
    ],
  },
]
