import type { ConfusablePair } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK 6 confusable grammar/ending pairs. a/b match grammars-n*.ts kos
 * verbatim. Each pair: a contrast note + 3 single-answer discrimination items,
 * 8-locale note/trans/why.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow
 * (single-correct-answer crux, naturalness, conjugation, 8-locale fidelity).
 * Native (Korean wife) review is the documented final gate.
 */
export const N6_PAIRS: ConfusablePair[] = [
  {
    id: 'jeuksi-jamaja',
    a: '-는 즉시',
    b: '-자마자',
    note: L(
      'Both -는 즉시 and -자마자 mean "as soon as / immediately upon," but -는 즉시 is formal and stresses zero-gap immediacy, typical of notices, business messages and written rules, while -자마자 is the everyday, conversational "as soon as" for ordinary sequences of actions.',
      'Tanto -는 즉시 como -자마자 significan "tan pronto como / inmediatamente al," pero -는 즉시 es formal y enfatiza una inmediatez sin ninguna pausa, típica de avisos, mensajes empresariales y reglas escritas, mientras que -자마자 es el "tan pronto como" cotidiano y conversacional para secuencias de acciones comunes.',
      '-는 즉시 et -자마자 signifient tous deux « dès que / immédiatement après », mais -는 즉시 est formel et insiste sur une immédiateté sans le moindre délai, typique des avis, des messages professionnels et des règles écrites, tandis que -자마자 est le « dès que » courant et familier pour les enchaînements d\'actions ordinaires.',
      'Tanto -는 즉시 quanto -자마자 significam "assim que / imediatamente ao," mas -는 즉시 é formal e enfatiza uma imediatez sem nenhum intervalo, típica de avisos, mensagens empresariais e regras escritas, enquanto -자마자 é o "assim que" cotidiano e coloquial para sequências de ações comuns.',
      'ทั้ง -는 즉시 และ -자마자 ต่างก็แปลว่า "ทันทีที่ / ในทันทีที่" แต่ -는 즉시 เป็นรูปทางการและเน้นความฉับพลันแบบไม่มีช่วงเว้นว่างเลย มักใช้ในประกาศ ข้อความทางธุรกิจ และกฎที่เป็นลายลักษณ์อักษร ขณะที่ -자마자 เป็นคำว่า "ทันทีที่" แบบในชีวิตประจำวันและในการสนทนาทั่วไปสำหรับลำดับการกระทำธรรมดา',
      'Baik -는 즉시 maupun -자마자 sama-sama berarti "begitu / segera setelah," tetapi -는 즉시 bersifat formal dan menekankan kesegeraan tanpa jeda sama sekali, khas pengumuman, pesan bisnis, dan aturan tertulis, sedangkan -자마자 adalah "begitu" yang sehari-hari dan percakapan untuk urutan tindakan biasa.',
      'Cả -는 즉시 và -자마자 đều có nghĩa là "ngay khi / ngay lập tức sau khi," nhưng -는 즉시 mang tính trang trọng và nhấn mạnh sự tức thì không có khoảng cách, thường thấy trong thông báo, tin nhắn công việc và quy định bằng văn bản, trong khi -자마자 là cách nói "ngay khi" thường ngày, mang tính hội thoại cho những chuỗi hành động thông thường.',
      '-는 즉시 と -자마자 はどちらも「〜するとすぐに/〜した途端に」を意味するが、-는 즉시 はフォーマルで間を置かない即時性を強調し、お知らせやビジネスのメッセージ、書き言葉の規則で典型的に使われる一方、-자마자 は日常的で会話的な「〜するとすぐに」で、ありふれた一連の動作に使われる。',
    ),
    items: [
      {
        sentence: '저는 집에 {} 침대에 누웠어요.',
        optionA: '오는 즉시',
        optionB: '오자마자',
        answer: 'b',
        trans: L(
          'As soon as I got home, I lay down on the bed.',
          'Apenas llegué a casa, me acosté en la cama.',
          'Dès que je suis rentré à la maison, je me suis allongé sur le lit.',
          'Assim que cheguei em casa, me deitei na cama.',
          'พอกลับถึงบ้านปุ๊บ ฉันก็ล้มตัวลงนอนบนเตียงเลย',
          'Begitu sampai di rumah, aku langsung berbaring di kasur.',
          'Vừa về đến nhà là tôi nằm vật ra giường luôn.',
          '家に着くやいなや、ベッドに横になった。',
        ),
        why: L(
          'Casual everyday narration of a personal action takes -자마자; the formal 오는 즉시 sounds stiff and bureaucratic for relaxing at home.',
          'La narración cotidiana e informal de una acción personal lleva -자마자; el formal 오는 즉시 suena rígido y burocrático para algo tan relajado como descansar en casa.',
          'La narration quotidienne et familière d\'une action personnelle prend -자마자 ; le formel 오는 즉시 sonne raide et bureaucratique pour quelque chose d\'aussi décontracté que se détendre chez soi.',
          'A narração cotidiana e informal de uma ação pessoal usa -자마자; o formal 오는 즉시 soa rígido e burocrático para algo tão relaxado como descansar em casa.',
          'การเล่าเหตุการณ์ในชีวิตประจำวันแบบไม่เป็นทางการเกี่ยวกับการกระทำส่วนตัวใช้ -자마자 ส่วนรูปทางการ 오는 즉시 ฟังดูแข็งทื่อและเป็นทางการเกินไปสำหรับการพักผ่อนสบาย ๆ ที่บ้าน',
          'Narasi sehari-hari yang santai tentang tindakan pribadi memakai -자마자; bentuk formal 오는 즉시 terdengar kaku dan birokratis untuk situasi santai seperti bersantai di rumah.',
          'Lời kể thường ngày, thân mật về một hành động cá nhân dùng -자마자; dạng trang trọng 오는 즉시 nghe cứng nhắc và quan liêu đối với việc nghỉ ngơi thoải mái ở nhà.',
          '個人的な行動を日常的でくだけた調子で語る場面では -자마자 を使う。フォーマルな 오는 즉시 は、家でくつろぐような場面には堅苦しく事務的に響く。',
        ),
      },
      {
        sentence: '주문이 {} 문자로 안내해 드립니다.',
        optionA: '접수되는 즉시',
        optionB: '접수되자마자',
        answer: 'a',
        trans: L(
          'We will notify you by text message the instant your order is received.',
          'Te avisaremos por mensaje de texto en el instante en que se reciba tu pedido.',
          'Nous vous avertirons par SMS à l\'instant même où votre commande sera reçue.',
          'Avisaremos você por mensagem de texto no instante em que seu pedido for recebido.',
          'เราจะแจ้งให้คุณทราบทางข้อความทันทีที่ได้รับคำสั่งซื้อของคุณ',
          'Kami akan memberitahu Anda melalui pesan teks pada saat pesanan Anda diterima.',
          'Chúng tôi sẽ thông báo cho quý khách qua tin nhắn ngay khi đơn hàng của quý khách được tiếp nhận.',
          'ご注文を受け付けた時点で、ただちにショートメッセージにてご連絡いたします。',
        ),
        why: L(
          'This is a formal business notice stressing immediate processing, which calls for -는 즉시; conversational -자마자 clashes with the official 안내해 드립니다 register.',
          'Este es un aviso empresarial formal que enfatiza el procesamiento inmediato, lo que pide -는 즉시; el conversacional -자마자 choca con el registro oficial de 안내해 드립니다.',
          'C\'est un avis professionnel formel qui insiste sur le traitement immédiat, ce qui appelle -는 즉시 ; le familier -자마자 jure avec le registre officiel de 안내해 드립니다.',
          'Este é um aviso empresarial formal que enfatiza o processamento imediato, o que exige -는 즉시; o coloquial -자마자 destoa do registro oficial de 안내해 드립니다.',
          'นี่คือประกาศทางธุรกิจที่เป็นทางการซึ่งเน้นการดำเนินการในทันที จึงต้องใช้ -는 즉시 ส่วน -자마자 ที่เป็นภาษาสนทนาขัดกับระดับภาษาที่เป็นทางการอย่าง 안내해 드립니다',
          'Ini adalah pengumuman bisnis formal yang menekankan pemrosesan langsung, yang memerlukan -는 즉시; -자마자 yang percakapan berbenturan dengan ragam resmi 안내해 드립니다.',
          'Đây là một thông báo công việc trang trọng nhấn mạnh việc xử lý tức thì, nên cần dùng -는 즉시; -자마자 mang tính hội thoại sẽ xung khắc với văn phong trang trọng của 안내해 드립니다.',
          'これは即時の処理を強調するフォーマルなビジネス上のお知らせなので -는 즉시 がふさわしい。会話的な -자마자 は、改まった 안내해 드립니다 の文体とそぐわない。',
        ),
      },
      {
        sentence: '동생은 학교에서 {} 가방을 던지고 놀러 나가요.',
        optionA: '돌아오는 즉시',
        optionB: '돌아오자마자',
        answer: 'b',
        trans: L(
          'As soon as my little brother comes back from school, he throws down his bag and goes out to play.',
          'Apenas mi hermanito vuelve de la escuela, tira la mochila y se va a jugar.',
          'Dès que mon petit frère rentre de l\'école, il jette son sac et part jouer.',
          'Assim que meu irmãozinho volta da escola, joga a mochila no chão e sai para brincar.',
          'พอน้องชายกลับจากโรงเรียนปุ๊บ เขาก็โยนกระเป๋าทิ้งแล้วออกไปเล่นเลย',
          'Begitu adik laki-lakiku pulang dari sekolah, dia melempar tasnya dan keluar bermain.',
          'Vừa đi học về là thằng em tôi quăng cặp xuống rồi chạy ra ngoài chơi.',
          '弟は学校から帰ってくるやいなや、かばんを放り出して遊びに出かける。',
        ),
        why: L(
          'A casual habitual description of a family member uses -자마자; the formal 돌아오는 즉시 is too rigid for this everyday domestic tone.',
          'Una descripción habitual e informal de un familiar usa -자마자; el formal 돌아오는 즉시 resulta demasiado rígido para este tono doméstico cotidiano.',
          'Une description habituelle et familière d\'un membre de la famille utilise -자마자 ; le formel 돌아오는 즉시 est trop rigide pour ce ton domestique du quotidien.',
          'Uma descrição habitual e informal de um familiar usa -자마자; o formal 돌아오는 즉시 é rígido demais para este tom doméstico cotidiano.',
          'การบรรยายนิสัยประจำของสมาชิกในครอบครัวแบบไม่เป็นทางการใช้ -자마자 ส่วนรูปทางการ 돌아오는 즉시 แข็งทื่อเกินไปสำหรับบรรยากาศในบ้านแบบประจำวันนี้',
          'Deskripsi kebiasaan yang santai tentang anggota keluarga memakai -자마자; bentuk formal 돌아오는 즉시 terlalu kaku untuk nuansa rumah tangga sehari-hari ini.',
          'Lời mô tả thói quen thường ngày, thân mật về một thành viên trong gia đình dùng -자마자; dạng trang trọng 돌아오는 즉시 quá cứng nhắc đối với giọng điệu sinh hoạt gia đình thường ngày này.',
          '家族の習慣をくだけた調子で描写する場面では -자마자 を使う。フォーマルな 돌아오는 즉시 は、こうした日常的な家庭の雰囲気には硬すぎる。',
        ),
      },
    ],
  },
  {
    id: 'madange-isang',
    a: '-는 마당에',
    b: '-(으)ㄴ/는 이상',
    note: L(
      'Use -는 마당에 for a dire or already-ruined/changed situation where acting otherwise is pointless ("now that things are this bad, what\'s the use"). Use -(으)ㄴ/는 이상 for a binding, settled premise that commits you to a consequence or obligation ("since/given that this is true, you must..."). Because each marker takes a different modifier form (마당에 with -는, 이상 with -(으)ㄴ for a completed state), the full verb+ending lives in the options, so the sentence blank must NOT pre-state the verb.',
      'Usá -는 마당에 para una situación grave o ya arruinada/cambiada donde actuar de otro modo es inútil (\'ahora que las cosas están tan mal, de qué sirve\'). Usá -(으)ㄴ/는 이상 para una premisa vinculante y asentada que te compromete a una consecuencia u obligación (\'ya que/dado que esto es cierto, tenés que...\'). Como cada marcador toma una forma de modificador distinta (마당에 con -는, 이상 con -(으)ㄴ para un estado completado), el verbo+terminación completo va en las opciones, así que el espacio en blanco de la oración NO debe adelantar el verbo.',
      'Utilise -는 마당에 pour une situation grave ou déjà ruinée/changée où agir autrement est inutile (« maintenant que les choses vont si mal, à quoi bon »). Utilise -(으)ㄴ/는 이상 pour une prémisse contraignante et établie qui t\'engage à une conséquence ou une obligation (« puisque/étant donné que c\'est vrai, tu dois... »). Comme chaque marqueur prend une forme de modificateur différente (마당에 avec -는, 이상 avec -(으)ㄴ pour un état accompli), le verbe+terminaison complet se trouve dans les options, donc le blanc de la phrase ne doit PAS préénoncer le verbe.',
      'Use -는 마당에 para uma situação grave ou já arruinada/alterada em que agir de outra forma é inútil (\'agora que as coisas estão tão ruins, de que adianta\'). Use -(으)ㄴ/는 이상 para uma premissa vinculante e estabelecida que te compromete a uma consequência ou obrigação (\'já que/dado que isto é verdade, você tem que...\'). Como cada marcador toma uma forma de modificador diferente (마당에 com -는, 이상 com -(으)ㄴ para um estado concluído), o verbo+terminação completo fica nas opções, então a lacuna da frase NÃO deve adiantar o verbo.',
      'ใช้ -는 마당에 สำหรับสถานการณ์ที่เลวร้ายหรือพังทลาย/เปลี่ยนไปแล้ว ซึ่งการทำอย่างอื่นนั้นไร้ประโยชน์ (\'ในเมื่อสถานการณ์แย่ขนาดนี้แล้ว จะมีประโยชน์อะไร\') ใช้ -(으)ㄴ/는 이상 สำหรับข้อตั้งที่ผูกมัดและลงตัวแล้ว ซึ่งผูกมัดคุณกับผลที่ตามมาหรือภาระหน้าที่ (\'ในเมื่อ/เพราะว่าสิ่งนี้เป็นจริง คุณต้อง...\') เนื่องจากตัวบ่งชี้แต่ละตัวใช้รูปขยายที่ต่างกัน (마당에 ใช้กับ -는, 이상 ใช้กับ -(으)ㄴ สำหรับสถานะที่เสร็จสิ้น) คำกริยา+คำลงท้ายแบบเต็มจึงอยู่ในตัวเลือก ดังนั้นช่องว่างในประโยคต้องไม่ระบุคำกริยาไว้ล่วงหน้า',
      'Gunakan -는 마당에 untuk situasi yang gawat atau sudah hancur/berubah di mana bertindak sebaliknya itu sia-sia (\'sekarang setelah keadaan begitu buruk, apa gunanya\'). Gunakan -(으)ㄴ/는 이상 untuk premis yang mengikat dan sudah mapan yang mengikatmu pada suatu konsekuensi atau kewajiban (\'karena/mengingat ini benar, kamu harus...\'). Karena setiap penanda memakai bentuk pemodifikasi yang berbeda (마당에 dengan -는, 이상 dengan -(으)ㄴ untuk keadaan yang selesai), verba+akhiran lengkap berada di dalam pilihan, jadi bagian kosong pada kalimat TIDAK boleh menyebutkan verbanya lebih dulu.',
      'Dùng -는 마당에 cho một tình huống nguy ngập hoặc đã đổ vỡ/thay đổi, nơi mà hành động khác đi là vô ích (\'giờ mọi chuyện đã tệ thế này rồi thì còn ích gì\'). Dùng -(으)ㄴ/는 이상 cho một tiền đề ràng buộc, đã được xác lập, buộc bạn vào một hệ quả hay nghĩa vụ (\'vì/đã là sự thật như vậy nên bạn phải...\'). Vì mỗi dấu hiệu dùng một dạng định ngữ khác nhau (마당에 với -는, 이상 với -(으)ㄴ cho trạng thái đã hoàn tất), nên động từ+đuôi đầy đủ nằm trong các phương án, do đó chỗ trống của câu KHÔNG được nêu trước động từ.',
      '-는 마당에 は、他のように行動しても無意味な、切迫した、あるいはすでに破綻・変化した状況に使います（「ここまで悪くなった今、何の意味があるのか」）。-(으)ㄴ/는 이상 は、ある帰結や義務にあなたを縛りつける、拘束力のある確定した前提に使います（「これが本当である以上、～しなければならない」）。それぞれの標識が異なる連体形を取るため（마당에 は -는、이상 は完了状態を表す -(으)ㄴ）、動詞+語尾の全体は選択肢の中にあります。したがって、文の空欄に動詞を先に述べてはいけません。',
    ),
    items: [
      {
        sentence: '이미 시험에 {} 후회해 봤자 소용없어요.',
        optionA: '떨어진 마당에',
        optionB: '떨어진 이상',
        answer: 'a',
        trans: L(
          'Now that I\'ve already failed the exam, there\'s no point in regretting it.',
          'Ahora que ya reprobé el examen, no tiene sentido arrepentirme.',
          'Maintenant que j\'ai déjà raté l\'examen, ça ne sert à rien de le regretter.',
          'Agora que eu já reprovei na prova, não adianta me arrepender.',
          'ในเมื่อสอบตกไปแล้ว ก็ไม่มีประโยชน์ที่จะมานั่งเสียดาย',
          'Sekarang setelah aku sudah gagal dalam ujian, percuma saja menyesalinya.',
          'Giờ thì tôi đã thi rớt rồi, có hối tiếc cũng vô ích.',
          'もう試験に落ちてしまった以上、後悔したって意味がありません。',
        ),
        why: L(
          'The clause frames an already-bad, done situation where acting (regretting) is futile — the prototypical 마당에 context (이미...봤자 소용없어요). 이상 (\'since/given I failed\') sets up a forward obligation or judgment, which clashes with a \'no point regretting\' futility statement, so it is the wrong fit here.',
          'La cláusula plantea una situación ya mala y consumada en la que actuar (arrepentirse) es inútil: el contexto prototípico de 마당에 (이미...봤자 소용없어요). 이상 (\'ya que/dado que reprobé\') prepara una obligación o juicio hacia adelante, lo cual choca con un enunciado de futilidad de \'no sirve arrepentirse\', así que acá no encaja.',
          'La proposition décrit une situation déjà mauvaise et accomplie où agir (regretter) est inutile : le contexte prototypique de 마당에 (이미...봤자 소용없어요). 이상 (\'puisque/étant donné que j\'ai raté\') met en place une obligation ou un jugement à venir, ce qui entre en conflit avec un énoncé de futilité \'ça ne sert à rien de regretter\', donc il ne convient pas ici.',
          'A oração enquadra uma situação já ruim e consumada em que agir (arrepender-se) é inútil: o contexto prototípico de 마당에 (이미...봤자 소용없어요). 이상 (\'já que/dado que reprovei\') prepara uma obrigação ou juízo para frente, o que colide com uma afirmação de futilidade de \'não adianta arrepender-se\', então não se encaixa aqui.',
          'อนุประโยคนี้วางกรอบสถานการณ์ที่แย่และเสร็จสิ้นไปแล้ว ซึ่งการกระทำ (การเสียดาย) ไร้ประโยชน์ อันเป็นบริบทต้นแบบของ 마당에 (이미...봤자 소용없어요) ส่วน 이상 (\'ในเมื่อ/เพราะว่าสอบตก\') จะนำไปสู่ภาระหน้าที่หรือการตัดสินไปข้างหน้า ซึ่งขัดกับประโยคที่บอกว่า \'เสียดายไปก็ไม่มีประโยชน์\' จึงไม่เหมาะที่จะใช้ตรงนี้',
          'Klausa ini membingkai situasi yang sudah buruk dan sudah terjadi, di mana bertindak (menyesal) itu sia-sia: konteks prototipikal 마당에 (이미...봤자 소용없어요). 이상 (\'karena/mengingat aku gagal\') menyiapkan kewajiban atau penilaian ke depan, yang bertabrakan dengan pernyataan kesia-siaan \'tidak ada gunanya menyesal\', jadi tidak cocok di sini.',
          'Mệnh đề này khắc họa một tình huống đã xấu và đã rồi, nơi mà hành động (hối tiếc) là vô ích — bối cảnh điển hình của 마당에 (이미...봤자 소용없어요). 이상 (\'vì/đã rớt rồi nên\') thiết lập một nghĩa vụ hay phán đoán hướng tới phía trước, điều này xung đột với câu nói về sự vô ích \'hối tiếc cũng chẳng ích gì\', nên không phù hợp ở đây.',
          'この節は、行動（後悔）が無駄であるという、すでに悪く、終わってしまった状況を描いており、まさに 마당에 の典型的な文脈です（이미...봤자 소용없어요）。이상（「落ちたのだから/落ちた以上」）は前向きな義務や判断を導くため、「後悔しても無意味」という無益さの文と衝突するので、ここでは合いません。',
        ),
      },
      {
        sentence: '한번 {} 끝까지 책임지고 마무리해야지요.',
        optionA: '시작하는 마당에',
        optionB: '시작한 이상',
        answer: 'b',
        trans: L(
          'Once you\'ve started it, you should take responsibility and finish it to the end.',
          'Ya que lo empezaste, deberías hacerte responsable y terminarlo hasta el final.',
          'Puisque tu l\'as commencé, tu devrais en assumer la responsabilité et le mener jusqu\'au bout.',
          'Já que você começou, deveria assumir a responsabilidade e terminar até o fim.',
          'ในเมื่อเริ่มลงมือไปแล้ว ก็ควรรับผิดชอบและทำให้เสร็จจนถึงที่สุด',
          'Karena sudah memulainya, kamu harus bertanggung jawab dan menyelesaikannya sampai tuntas.',
          'Đã bắt đầu rồi thì bạn nên có trách nhiệm làm cho xong đến cùng.',
          '始めた以上は、責任を持って最後までやり遂げるべきです。',
        ),
        why: L(
          'This is a binding, settled premise (\'given that it has been started, one is committed to finishing\') driving an obligation (마무리해야지요), which is exactly 이상. 마당에 implies a dire/ruined situation where further effort is pointless, contradicting the sense of duty to finish; also 마당에 takes -는 (시작하는), so the 마당에 distractor reads as a fresh, ongoing start, not a settled fact.',
          'Esta es una premisa vinculante y asentada (\'dado que se ha empezado, uno queda comprometido a terminar\') que impulsa una obligación (마무리해야지요), que es exactamente 이상. 마당에 implica una situación desesperada/arruinada donde seguir esforzándose es inútil, lo que contradice el sentido de deber de terminar; además 마당에 lleva -는 (시작하는), así que el distractor con 마당에 se lee como un inicio fresco y en curso, no como un hecho asentado.',
          'C\'est une prémisse contraignante et établie (\'étant donné que cela a été commencé, on est engagé à terminer\') qui entraîne une obligation (마무리해야지요), ce qui correspond exactement à 이상. 마당에 implique une situation désespérée/ruinée où poursuivre l\'effort est inutile, ce qui contredit le sens du devoir d\'achever ; de plus 마당에 prend -는 (시작하는), donc le distracteur avec 마당에 se lit comme un début frais et en cours, et non comme un fait établi.',
          'Esta é uma premissa vinculante e estabelecida (\'dado que foi começado, fica-se comprometido a terminar\') que impulsiona uma obrigação (마무리해야지요), que é exatamente 이상. 마당에 implica uma situação desesperadora/arruinada em que continuar se esforçando é inútil, o que contradiz o sentido de dever de terminar; além disso 마당에 leva -는 (시작하는), então o distrator com 마당에 soa como um começo fresco e em andamento, não como um fato estabelecido.',
          'นี่คือข้อตั้งที่ผูกมัดและลงตัวแล้ว (\'ในเมื่อได้เริ่มไปแล้ว ก็ผูกมัดให้ต้องทำให้จบ\') ซึ่งนำไปสู่ภาระหน้าที่ (마무리해야지요) อันเป็น 이상 พอดี ส่วน 마당에 สื่อถึงสถานการณ์ที่สิ้นหวัง/พังทลายซึ่งการพยายามต่อไปไร้ประโยชน์ ขัดกับความรู้สึกว่ามีหน้าที่ต้องทำให้เสร็จ อีกทั้ง 마당에 ใช้กับ -는 (시작하는) ดังนั้นตัวลวง 마당에 จึงอ่านได้เป็นการเริ่มต้นใหม่ที่กำลังดำเนินอยู่ ไม่ใช่ข้อเท็จจริงที่ลงตัวแล้ว',
          'Ini adalah premis yang mengikat dan sudah mapan (\'mengingat sudah dimulai, seseorang terikat untuk menyelesaikannya\') yang mendorong suatu kewajiban (마무리해야지요), yang persis 이상. 마당에 menyiratkan situasi putus asa/hancur di mana upaya lebih lanjut percuma, yang bertentangan dengan rasa kewajiban untuk menyelesaikan; selain itu 마당에 memakai -는 (시작하는), sehingga pengecoh 마당에 terbaca sebagai permulaan baru yang sedang berlangsung, bukan fakta yang sudah mapan.',
          'Đây là một tiền đề ràng buộc và đã được xác lập (\'vì đã bắt đầu nên buộc phải hoàn thành\') dẫn tới một nghĩa vụ (마무리해야지요), đúng là 이상. 마당에 hàm ý một tình huống tuyệt vọng/đổ vỡ nơi mọi nỗ lực thêm là vô ích, mâu thuẫn với cảm giác về bổn phận phải hoàn thành; ngoài ra 마당에 dùng với -는 (시작하는), nên phương án gây nhiễu 마당에 đọc ra như một sự khởi đầu mới đang diễn ra, chứ không phải một sự thật đã được xác lập.',
          'これは義務（마무리해야지요）を導く、拘束力のある確定した前提（「始めた以上、終わらせることに縛られる」）であり、まさに 이상 です。마당에 は、これ以上の努力が無意味な、絶望的・破綻した状況を含意し、やり遂げるべきだという義務感と矛盾します。さらに 마당에 は -는（시작하는）を取るため、마당에 の誤答は確定した事実ではなく、新たに進行中の開始のように読めてしまいます。',
        ),
      },
      {
        sentence: '가게가 다 {} 인테리어가 다 무슨 소용이에요.',
        optionA: '망해 가는 마당에',
        optionB: '망해 가는 이상',
        answer: 'a',
        trans: L(
          'Now that the shop is going under, what\'s the point of any interior decorating?',
          'Ahora que la tienda está quebrando, ¿de qué sirve cualquier decoración de interiores?',
          'Maintenant que le magasin fait faillite, à quoi bon faire de la décoration intérieure ?',
          'Agora que a loja está indo à falência, de que adianta qualquer decoração de interiores?',
          'ในเมื่อร้านกำลังจะเจ๊งอยู่แล้ว จะตกแต่งภายในไปทำไม',
          'Sekarang setelah toko ini mau bangkrut, apa gunanya dekorasi interior apa pun?',
          'Giờ thì cửa hàng đang phá sản đến nơi, trang trí nội thất thì có ích gì chứ?',
          '店がつぶれかけている마당에、内装を飾ったところで何の意味があるんですか。',
        ),
        why: L(
          'A collapsing situation plus the rhetorical \'무슨 소용이에요\' (what\'s the use) is the futility framing that 마당에 owns. 이상 needs a settled/definite premise (망한 이상) to license its \'therefore you must\' consequence; with the progressive 망해 가는 and a futility punchline it is unnatural, leaving 마당에 as the single defensible answer.',
          'Una situación que se derrumba más el retórico \'무슨 소용이에요\' (de qué sirve) es el encuadre de futilidad que le pertenece a 마당에. 이상 necesita una premisa asentada/definitiva (망한 이상) para habilitar su consecuencia de \'por lo tanto debes\'; con el progresivo 망해 가는 y un remate de futilidad resulta poco natural, dejando a 마당에 como la única respuesta defendible.',
          'Une situation qui s\'effondre plus le rhétorique \'무슨 소용이에요\' (à quoi bon) est l\'encadrement de futilité qui appartient à 마당에. 이상 a besoin d\'une prémisse établie/définie (망한 이상) pour autoriser sa conséquence \'donc tu dois\' ; avec le progressif 망해 가는 et une chute sur la futilité, il est peu naturel, laissant 마당에 comme la seule réponse défendable.',
          'Uma situação que está desmoronando mais o retórico \'무슨 소용이에요\' (de que adianta) é o enquadramento de futilidade que pertence a 마당에. 이상 precisa de uma premissa estabelecida/definida (망한 이상) para licenciar sua consequência de \'portanto você deve\'; com o progressivo 망해 가는 e um arremate de futilidade fica pouco natural, deixando 마당에 como a única resposta defensável.',
          'สถานการณ์ที่กำลังพังทลายบวกกับคำเชิงวาทศิลป์ \'무슨 소용이에요\' (จะมีประโยชน์อะไร) คือกรอบความไร้ประโยชน์ที่เป็นของ 마당에 ส่วน 이상 ต้องการข้อตั้งที่ลงตัว/แน่ชัด (망한 이상) เพื่อรองรับผลที่ตามมาแบบ \'ดังนั้นต้อง\' เมื่อใช้กับรูปกำลังดำเนินอยู่ 망해 가는 และมุกปิดท้ายเรื่องความไร้ประโยชน์ มันจึงไม่เป็นธรรมชาติ เหลือ 마당에 เป็นคำตอบเดียวที่มีเหตุผลรองรับได้',
          'Situasi yang sedang runtuh ditambah \'무슨 소용이에요\' yang retoris (apa gunanya) adalah pembingkaian kesia-siaan yang menjadi milik 마당에. 이상 membutuhkan premis yang mapan/pasti (망한 이상) untuk mengizinkan konsekuensi \'maka kamu harus\'-nya; dengan progresif 망해 가는 dan pukulan penutup tentang kesia-siaan, ia terasa tidak alami, menyisakan 마당에 sebagai satu-satunya jawaban yang dapat dipertahankan.',
          'Một tình huống đang sụp đổ cộng với câu hỏi tu từ \'무슨 소용이에요\' (có ích gì) chính là khung vô ích thuộc về 마당에. 이상 cần một tiền đề đã xác lập/dứt khoát (망한 이상) để cho phép hệ quả \'do đó bạn phải\' của nó; với dạng tiếp diễn 망해 가는 và câu chốt về sự vô ích, nó trở nên không tự nhiên, để lại 마당에 là đáp án duy nhất có thể biện hộ.',
          '崩壊しつつある状況に、修辞的な \'무슨 소용이에요\'（何の意味があるのか）が加わったものは、まさに 마당에 が担う無益さの枠組みです。이상 は「だから～しなければ」という帰結を許可するために、確定的・確然とした前提（망한 이상）を必要とします。進行形の 망해 가는 と無益さのオチを伴うと不自然になり、마당에 が唯一妥当な答えとして残ります。',
        ),
      },
    ],
  },
  {
    id: 'beobida-maryeonida',
    a: '-는 법이다',
    b: '-기 마련이다',
    note: L(
      'Use -는 법이다 to state a general truth or principle — "that\'s the way things are / how it always goes" (a moral rule or natural law presented as a known, governing fact). Use -기 마련이다 for an unavoidable tendency that is "bound to" happen, especially rooted in human nature or the natural course of things.',
      'Usá -는 법이다 para enunciar una verdad o un principio general — \'así son las cosas / así suele pasar siempre\' (una regla moral o ley natural presentada como un hecho conocido y rector). Usá -기 마련이다 para una tendencia inevitable que \'sí o sí\' va a ocurrir, sobre todo arraigada en la naturaleza humana o en el curso natural de las cosas.',
      'Emploie -는 법이다 pour énoncer une vérité ou un principe général — \'c\'est ainsi que vont les choses / ça se passe toujours comme ça\' (une règle morale ou une loi naturelle présentée comme un fait connu et régissant). Emploie -기 마련이다 pour une tendance inévitable qui est \'vouée à\' se produire, surtout enracinée dans la nature humaine ou le cours naturel des choses.',
      'Use -는 법이다 para enunciar uma verdade ou princípio geral — \'é assim que as coisas são / é assim que sempre acontece\' (uma regra moral ou lei natural apresentada como um fato conhecido e regente). Use -기 마련이다 para uma tendência inevitável que \'fatalmente\' vai acontecer, sobretudo enraizada na natureza humana ou no curso natural das coisas.',
      'ใช้ -는 법이다 เพื่อกล่าวความจริงทั่วไปหรือหลักการ — \'มันก็เป็นเช่นนั้นแหละ / มันก็เป็นไปแบบนี้เสมอ\' (กฎทางศีลธรรมหรือกฎธรรมชาติที่นำเสนอเป็นข้อเท็จจริงที่รู้กันและเป็นตัวกำหนด) ใช้ -기 마련이다 สำหรับแนวโน้มที่เลี่ยงไม่ได้ซึ่ง \'ย่อมต้อง\' เกิดขึ้น โดยเฉพาะที่หยั่งรากอยู่ในธรรมชาติของมนุษย์หรือวิถีธรรมชาติของสรรพสิ่ง',
      'Gunakan -는 법이다 untuk menyatakan kebenaran atau prinsip umum — \'memang begitulah adanya / memang selalu begitu\' (kaidah moral atau hukum alam yang disajikan sebagai fakta yang sudah diketahui dan mengatur). Gunakan -기 마련이다 untuk kecenderungan tak terhindarkan yang \'pasti\' terjadi, terutama yang berakar pada sifat manusia atau jalannya hal-hal secara alami.',
      'Dùng -는 법이다 để phát biểu một chân lý hay nguyên tắc chung — \'mọi sự vốn là vậy / xưa nay vẫn thế\' (một quy tắc đạo đức hoặc quy luật tự nhiên được trình bày như một sự thật đã biết và mang tính chi phối). Dùng -기 마련이다 cho một xu hướng không thể tránh khỏi \'tất yếu\' sẽ xảy ra, nhất là khi bắt nguồn từ bản tính con người hoặc lẽ thường của tự nhiên.',
      '-는 법이다 は、一般的な真理や原則を述べるときに使う——『物事とはそういうものだ/いつもそうなるものだ』(既知で支配的な事実として提示される道徳的規則や自然法則)。-기 마련이다 は、『必ず』起こる避けられない傾向、とりわけ人間の本性や物事の自然な成り行きに根ざした傾向に使う。',
    ),
    items: [
      {
        sentence: '사람은 누구나 나이가 들면 늙{}.',
        optionA: '는 법이다',
        optionB: '기 마련이다',
        answer: 'b',
        trans: L(
          'Everyone is bound to grow old as the years pass.',
          'Todos vamos a envejecer sí o sí a medida que pasan los años.',
          'Tout le monde finit forcément par vieillir au fil des années.',
          'Todo mundo vai envelhecer inevitavelmente conforme os anos passam.',
          'ทุกคนย่อมต้องแก่ตัวลงอย่างเลี่ยงไม่ได้เมื่อเวลาผ่านไปหลายปี',
          'Semua orang pasti akan menua seiring berjalannya tahun.',
          'Ai rồi cũng tất yếu già đi khi năm tháng trôi qua.',
          '年月が経てば、誰もが必ず年を取るものだ。',
        ),
        why: L(
          'Aging is an unavoidable natural tendency every human is \'bound to\' undergo, the signature use of -기 마련이다. -는 법이다 frames something as a stated principle/rule that one ought to know; applied to plain biological inevitability (늙는 법이다) it sounds odd and preachy rather than descriptive.',
          'Envejecer es una tendencia natural inevitable que todo ser humano \'está destinado a\' atravesar, el uso característico de -기 마련이다. -는 법이다 plantea algo como un principio/regla declarado que uno debería conocer; aplicado a la pura inevitabilidad biológica (늙는 법이다) suena raro y sermoneador en vez de descriptivo.',
          'Vieillir est une tendance naturelle inévitable que tout être humain est \'voué à\' subir, l\'usage type de -기 마련이다. -는 법이다 présente quelque chose comme un principe/une règle énoncé que l\'on est censé connaître ; appliqué à la pure fatalité biologique (늙는 법이다), cela sonne bizarre et moralisateur plutôt que descriptif.',
          'Envelhecer é uma tendência natural inevitável que todo ser humano \'está fadado a\' atravessar, o uso característico de -기 마련이다. -는 법이다 enquadra algo como um princípio/regra declarado que se deveria conhecer; aplicado à pura inevitabilidade biológica (늙는 법이다), soa estranho e pregador em vez de descritivo.',
          'การแก่ตัวลงเป็นแนวโน้มตามธรรมชาติที่เลี่ยงไม่ได้ ซึ่งมนุษย์ทุกคน \'ย่อมต้อง\' ประสบ เป็นการใช้ที่เป็นเอกลักษณ์ของ -기 마련이다 ส่วน -는 법이다 วางกรอบสิ่งหนึ่งให้เป็นหลักการ/กฎที่ระบุไว้ซึ่งคนเราควรรู้ เมื่อนำมาใช้กับความเลี่ยงไม่ได้ทางชีววิทยาล้วน ๆ (늙는 법이다) จะฟังดูแปลกและสั่งสอนมากกว่าจะเป็นการบรรยาย',
          'Menua adalah kecenderungan alami yang tak terhindarkan dan \'pasti\' dialami setiap manusia, penggunaan khas -기 마련이다. -는 법이다 membingkai sesuatu sebagai prinsip/aturan yang dinyatakan dan seharusnya diketahui; bila diterapkan pada keniscayaan biologis murni (늙는 법이다), terdengar janggal dan menggurui ketimbang deskriptif.',
          'Già đi là một xu hướng tự nhiên không thể tránh khỏi mà mọi con người \'tất yếu\' phải trải qua, đúng kiểu dùng đặc trưng của -기 마련이다. -는 법이다 đóng khung điều gì đó như một nguyên tắc/quy luật được nêu ra mà người ta nên biết; khi áp vào sự tất yếu sinh học thuần túy (늙는 법이다) thì nghe lạ và lên giọng dạy đời chứ không phải mô tả.',
          '年を取ることは、人間誰しもが『必ず』経験する避けられない自然な傾向であり、これこそ -기 마련이다 の典型的な使い方だ。-는 법이다 は、知っておくべき原則・法則として述べる枠組みであり、純粋な生物学的必然(늙는 법이다)に当てはめると、描写的というより不自然で説教くさく聞こえる。',
        ),
      },
      {
        sentence: '죄를 지으면 언젠가 벌을 받{}.',
        optionA: '는 법이다',
        optionB: '기 마련이다',
        answer: 'a',
        trans: L(
          'If you commit a crime, you will be punished someday — that\'s the way it works.',
          'Si cometés un delito, algún día vas a ser castigado: así son las cosas.',
          'Si tu commets un crime, tu seras puni un jour — c\'est comme ça que ça marche.',
          'Se você comete um crime, um dia será punido — é assim que funciona.',
          'ถ้าก่ออาชญากรรม สักวันก็ต้องถูกลงโทษ นั่นแหละคือกฎของมัน',
          'Kalau kamu melakukan kejahatan, suatu hari kamu akan dihukum — begitulah cara kerjanya.',
          'Nếu phạm tội thì một ngày nào đó sẽ bị trừng phạt — quy luật là vậy.',
          '罪を犯せば、いつか罰を受ける——それが世の道理というものだ。',
        ),
        why: L(
          'This asserts a moral principle / law of how the world is ordered (\'that is the way things are\'), the core function of -는 법이다. -기 마련이다 would reduce a just, principled consequence to a mere statistical tendency, which clashes with the moralizing \'crime is always punished\' reading the sentence intends.',
          'Esto afirma un principio moral / una ley sobre cómo está ordenado el mundo (\'así son las cosas\'), la función central de -는 법이다. -기 마련이다 reduciría una consecuencia justa y de principios a una mera tendencia estadística, lo que choca con la lectura moralizante de que \'el delito siempre se castiga\' que pretende la oración.',
          'Cela affirme un principe moral / une loi sur la façon dont le monde est ordonné (\'c\'est comme ça\'), la fonction centrale de -는 법이다. -기 마련이다 réduirait une conséquence juste et fondée sur des principes à une simple tendance statistique, ce qui entre en conflit avec la lecture moralisatrice \'le crime est toujours puni\' que la phrase vise.',
          'Isto afirma um princípio moral / uma lei sobre como o mundo é ordenado (\'é assim que as coisas são\'), a função central de -는 법이다. -기 마련이다 reduziria uma consequência justa e baseada em princípios a uma mera tendência estatística, o que conflita com a leitura moralizante de que \'o crime é sempre punido\' pretendida pela frase.',
          'ประโยคนี้ยืนยันหลักการทางศีลธรรม / กฎของวิธีที่โลกถูกจัดวาง (\'มันก็เป็นเช่นนั้นแหละ\') ซึ่งเป็นหน้าที่หลักของ -는 법이다 ถ้าใช้ -기 마련이다 จะลดทอนผลลัพธ์ที่ยุติธรรมและมีหลักการให้เหลือเพียงแนวโน้มทางสถิติ ซึ่งขัดกับความหมายเชิงสั่งสอนว่า \'อาชญากรรมย่อมถูกลงโทษเสมอ\' ที่ประโยคต้องการสื่อ',
          'Ini menegaskan prinsip moral / hukum tentang bagaimana dunia ditata (\'begitulah adanya\'), fungsi inti dari -는 법이다. -기 마련이다 akan mereduksi konsekuensi yang adil dan berprinsip menjadi sekadar kecenderungan statistik, yang bertabrakan dengan makna menggurui \'kejahatan selalu dihukum\' yang dimaksudkan kalimat ini.',
          'Câu này khẳng định một nguyên tắc đạo đức / quy luật về cách thế giới được sắp đặt (\'mọi sự vốn là vậy\'), chính là chức năng cốt lõi của -는 법이다. -기 마련이다 sẽ hạ thấp một hệ quả công bằng, có nguyên tắc xuống thành chỉ là xu hướng thống kê, điều này xung đột với cách hiểu mang tính răn dạy \'tội ác luôn bị trừng phạt\' mà câu muốn truyền tải.',
          'これは世界がどう秩序づけられているかという道徳的原則・法則(『それが道理だ』)を主張しており、-는 법이다 の中心的な機能だ。-기 마련이다 を使うと、正当で原則的な帰結を単なる統計的傾向に格下げしてしまい、この文が意図する『罪は必ず罰せられる』という説諭的な読みと衝突する。',
        ),
      },
      {
        sentence: '처음 배우는 일은 누구나 실수하{}.',
        optionA: '는 법이다',
        optionB: '기 마련이다',
        answer: 'b',
        trans: L(
          'When learning something for the first time, anyone is bound to make mistakes.',
          'Cuando aprendés algo por primera vez, cualquiera comete errores sí o sí.',
          'Quand on apprend quelque chose pour la première fois, n\'importe qui fait forcément des erreurs.',
          'Quando se aprende algo pela primeira vez, qualquer um inevitavelmente comete erros.',
          'เวลาเรียนรู้อะไรเป็นครั้งแรก ใคร ๆ ก็ย่อมต้องทำผิดพลาดเป็นธรรมดา',
          'Saat belajar sesuatu untuk pertama kali, siapa pun pasti membuat kesalahan.',
          'Khi học một điều gì đó lần đầu, ai cũng tất yếu mắc lỗi.',
          '何かを初めて学ぶときは、誰でも失敗するものだ。',
        ),
        why: L(
          'Making mistakes while still learning is an unavoidable human tendency one is \'bound to\' fall into, fitting -기 마련이다. -는 법이다 (실수하는 법이다) would oddly elevate mistake-making to a governing principle/rule, which is unnatural; native usage here is overwhelmingly 실수하기 마련이다.',
          'Cometer errores mientras todavía estás aprendiendo es una tendencia humana inevitable en la que uno \'está destinado a\' caer, lo que encaja con -기 마련이다. -는 법이다 (실수하는 법이다) elevaría de forma rara el cometer errores a la categoría de principio/regla rectora, lo cual es poco natural; el uso nativo aquí es abrumadoramente 실수하기 마련이다.',
          'Faire des erreurs alors qu\'on apprend encore est une tendance humaine inévitable dans laquelle on est \'voué à\' tomber, ce qui correspond à -기 마련이다. -는 법이다 (실수하는 법이다) érigerait bizarrement le fait de se tromper en principe/règle directeur, ce qui est non naturel ; l\'usage natif ici est très majoritairement 실수하기 마련이다.',
          'Cometer erros enquanto ainda se está aprendendo é uma tendência humana inevitável na qual a pessoa \'está fadada a\' cair, o que combina com -기 마련이다. -는 법이다 (실수하는 법이다) elevaria estranhamente o ato de errar a um princípio/regra reitor, o que é pouco natural; o uso nativo aqui é esmagadoramente 실수하기 마련이다.',
          'การทำผิดพลาดขณะที่ยังเรียนรู้อยู่เป็นแนวโน้มของมนุษย์ที่เลี่ยงไม่ได้ซึ่งคนเรา \'ย่อมต้อง\' ตกอยู่ในนั้น เข้ากับ -기 마련이다 ส่วน -는 법이다 (실수하는 법이다) จะยกระดับการทำผิดพลาดให้กลายเป็นหลักการ/กฎที่ใช้ปกครองอย่างแปลก ๆ ซึ่งไม่เป็นธรรมชาติ การใช้ของเจ้าของภาษาในที่นี้คือ 실수하기 마련이다 อย่างท่วมท้น',
          'Membuat kesalahan saat masih belajar adalah kecenderungan manusiawi yang tak terhindarkan dan \'pasti\' dialami seseorang, yang cocok dengan -기 마련이다. -는 법이다 (실수하는 법이다) akan secara janggal mengangkat tindakan berbuat salah menjadi prinsip/aturan yang mengatur, yang terasa tidak alami; penggunaan penutur asli di sini secara mayoritas adalah 실수하기 마련이다.',
          'Mắc lỗi khi vẫn còn đang học là một xu hướng tự nhiên của con người không thể tránh khỏi mà ai cũng \'tất yếu\' rơi vào, phù hợp với -기 마련이다. -는 법이다 (실수하는 법이다) sẽ nâng việc mắc lỗi lên thành một nguyên tắc/quy luật chi phối một cách kỳ quặc, nghe không tự nhiên; cách dùng của người bản xứ ở đây áp đảo là 실수하기 마련이다.',
          'まだ学んでいる途中で失敗するのは、人間誰もが『必ず』陥る避けられない傾向であり、-기 마련이다 に合う。-는 법이다(실수하는 법이다)を使うと、失敗することを支配的な原則・法則へと不自然に格上げしてしまい、不自然だ。ここでのネイティブの用法は圧倒的に 실수하기 마련이다 である。',
        ),
      },
    ],
  },
  {
    id: 'malmiama-inhae',
    a: '-(으)로 말미암아',
    b: '-(으)로 인해(서)',
    note: L(
      'Both mean "owing to / due to" a noun cause. Use -(으)로 인해(서) for the standard formal cause of news, reports, and announcements (the default neutral choice). Reserve -(으)로 말미암아 for highly literary or elevated prose — essays, historical or reflective writing — where it sounds solemn rather than archaic. Note the allomorph: vowel-final and ㄹ-final nouns take 로 (폭설로, 교통사고로), other consonants take 으로 (선택으로).',
      'Ambos significan "a causa de / debido a" un sustantivo como causa. Usá -(으)로 인해(서) para la causa formal estándar de noticias, reportes y anuncios (la opción neutra por defecto). Reservá -(으)로 말미암아 para prosa muy literaria o elevada —ensayos, escritura histórica o reflexiva— donde suena solemne más que arcaico. Fijate en el alomorfo: los sustantivos terminados en vocal y en ㄹ toman 로 (폭설로, 교통사고로), y los terminados en otras consonantes toman 으로 (선택으로).',
      'Les deux signifient « à cause de / en raison de » un nom qui exprime une cause. Utilise -(으)로 인해(서) pour la cause formelle standard des nouvelles, rapports et annonces (le choix neutre par défaut). Réserve -(으)로 말미암아 à une prose très littéraire ou élevée — essais, écriture historique ou réflexive — où elle sonne solennelle plutôt qu\'archaïque. Note l\'allomorphe : les noms se terminant par une voyelle ou par ㄹ prennent 로 (폭설로, 교통사고로), les autres consonnes prennent 으로 (선택으로).',
      'Ambos significam "por causa de / devido a" um substantivo como causa. Use -(으)로 인해(서) para a causa formal padrão de notícias, relatórios e comunicados (a opção neutra padrão). Reserve -(으)로 말미암아 para prosa muito literária ou elevada — ensaios, escrita histórica ou reflexiva — onde soa solene em vez de arcaica. Observe o alomorfe: substantivos terminados em vogal e em ㄹ recebem 로 (폭설로, 교통사고로), outras consoantes recebem 으로 (선택으로).',
      'ทั้งสองแปลว่า "เนื่องจาก / อันเป็นผลมาจาก" คำนามที่เป็นสาเหตุ ใช้ -(으)로 인해(서) สำหรับการบอกสาเหตุแบบทางการมาตรฐานในข่าว รายงาน และประกาศ (ตัวเลือกกลางๆ ที่เป็นค่าเริ่มต้น) ส่วน -(으)로 말미암아 ให้สงวนไว้สำหรับงานร้อยแก้วเชิงวรรณกรรมหรือชั้นสูงอย่างยิ่ง เช่น เรียงความ งานเขียนเชิงประวัติศาสตร์หรือเชิงครุ่นคิด ซึ่งจะให้ความรู้สึกขรึมขลังมากกว่าโบราณ สังเกตรูปแปร (allomorph): คำนามที่ลงท้ายด้วยสระและด้วย ㄹ ใช้ 로 (폭설로, 교통사고로) ส่วนพยัญชนะอื่นๆ ใช้ 으로 (선택으로)',
      'Keduanya berarti "karena / akibat" suatu kata benda sebagai penyebab. Gunakan -(으)로 인해(서) untuk penanda sebab formal baku dalam berita, laporan, dan pengumuman (pilihan netral default). Sisihkan -(으)로 말미암아 untuk prosa yang sangat sastrawi atau tinggi — esai, tulisan sejarah atau reflektif — di mana ia terdengar khidmat alih-alih kuno. Perhatikan alomorfnya: kata benda berakhiran vokal dan ㄹ memakai 로 (폭설로, 교통사고로), konsonan lain memakai 으로 (선택으로).',
      'Cả hai đều có nghĩa "vì / do" một danh từ chỉ nguyên nhân. Dùng -(으)로 인해(서) cho cách diễn đạt nguyên nhân trang trọng chuẩn trong tin tức, báo cáo và thông báo (lựa chọn trung tính mặc định). Hãy dành -(으)로 말미암아 cho lối văn rất văn chương hoặc trang trọng — tản văn, văn viết mang tính lịch sử hay suy ngẫm — nơi nó nghe trang nghiêm chứ không cổ kính. Lưu ý biến thể (allomorph): danh từ kết thúc bằng nguyên âm và bằng ㄹ dùng 로 (폭설로, 교통사고로), các phụ âm khác dùng 으로 (선택으로).',
      'どちらも名詞の原因を「〜のために/〜によって」と表す。ニュース・報告・告知の標準的でフォーマルな原因には -(으)로 인해(서) を使う(無標のデフォルトの選択)。-(으)로 말미암아 は、随筆や歴史的・内省的な文章など、きわめて文学的または格調高い文体のために取っておくとよく、そこでは古風というより荘重に響く。異形態(allomorph)に注意:母音終わりおよび ㄹ 終わりの名詞は 로 を取り(폭설로、교통사고로)、それ以外の子音は 으로 を取る(선택으로)。',
    ),
    items: [
      {
        sentence: '이번 폭설{} 항공편 수십 편이 결항됐다.',
        optionA: '로 말미암아',
        optionB: '로 인해',
        answer: 'b',
        trans: L(
          'Due to this heavy snowfall, dozens of flights were canceled.',
          'Debido a esta fuerte nevada, se cancelaron decenas de vuelos.',
          'À cause de ces fortes chutes de neige, des dizaines de vols ont été annulés.',
          'Devido a esta forte nevasca, dezenas de voos foram cancelados.',
          'เนื่องจากหิมะตกหนักครั้งนี้ เที่ยวบินหลายสิบเที่ยวจึงถูกยกเลิก',
          'Akibat hujan salju lebat ini, puluhan penerbangan dibatalkan.',
          'Do trận tuyết rơi dày này, hàng chục chuyến bay đã bị hủy.',
          'この大雪により、数十便の航空便が欠航となった。',
        ),
        why: L(
          'A factual news report calls for the standard formal cause 로 인해; the literary 로 말미암아 sounds jarring in plain reporting. (폭설 ends in ㄹ, so it takes 로, not 으로.)',
          'Una noticia factual pide la causa formal estándar 로 인해; el literario 로 말미암아 suena discordante en un reporte llano. (폭설 termina en ㄹ, así que lleva 로, no 으로.)',
          'Un bulletin d\'information factuel appelle la cause formelle standard 로 인해 ; le littéraire 로 말미암아 détonne dans un reportage neutre. (폭설 se termine par ㄹ, il prend donc 로 et non 으로.)',
          'Uma notícia factual pede a causa formal padrão 로 인해; o literário 로 말미암아 soa estranho num relato simples. (폭설 termina em ㄹ, então leva 로, não 으로.)',
          'ข่าวเชิงข้อเท็จจริงต้องใช้คำบอกสาเหตุแบบทางการมาตรฐาน 로 인해 ส่วน 로 말미암아 ที่ออกแนววรรณกรรมจะฟังดูขัดหูในการรายงานธรรมดา (폭설 ลงท้ายด้วย ㄹ จึงใช้ 로 ไม่ใช่ 으로)',
          'Berita faktual menuntut penanda sebab formal baku 로 인해; 로 말미암아 yang sastrawi terdengar janggal dalam pelaporan biasa. (폭설 berakhir dengan ㄹ, jadi memakai 로, bukan 으로.)',
          'Một bản tin mang tính sự kiện cần cách diễn đạt nguyên nhân trang trọng chuẩn 로 인해; lối văn chương 로 말미암아 nghe lạc lõng trong tường thuật thông thường. (폭설 kết thúc bằng ㄹ nên dùng 로, không phải 으로.)',
          '事実を伝えるニュース報道には標準的でフォーマルな原因表現の 로 인해 がふさわしく、文学的な 로 말미암아 は素朴な報道では浮いて聞こえる。(폭설 は ㄹ で終わるので、으로 ではなく 로 を取る。)',
        ),
      },
      {
        sentence: '그 한 번의 잘못된 선택{} 그의 인생 전체가 송두리째 바뀌고 말았다.',
        optionA: '으로 말미암아',
        optionB: '으로 인해',
        answer: 'a',
        trans: L(
          'Owing to that one wrong choice, his entire life was utterly transformed.',
          'Por culpa de aquella sola elección equivocada, toda su vida cambió por completo.',
          'À cause de ce seul mauvais choix, toute sa vie fut entièrement transformée.',
          'Por causa daquela única escolha errada, toda a sua vida foi completamente transformada.',
          'เพราะการเลือกที่ผิดเพียงครั้งเดียวนั้น ชีวิตทั้งชีวิตของเขาก็เปลี่ยนไปอย่างสิ้นเชิง',
          'Akibat satu pilihan keliru itu, seluruh hidupnya berubah total.',
          'Vì một lựa chọn sai lầm duy nhất đó, cả cuộc đời anh đã hoàn toàn thay đổi.',
          'あのたった一度の誤った選択により、彼の人生はすっかり一変してしまった。',
        ),
        why: L(
          'The reflective, essay-like prose (그 한 번의, 송두리째, 바뀌고 말았다) suits the elevated, literary 으로 말미암아; 으로 인해 would flatten the deliberately solemn tone. (선택 ends in ㄱ, so 으로 is correct.)',
          'La prosa reflexiva, tipo ensayo (그 한 번의, 송두리째, 바뀌고 말았다) encaja con el elevado y literario 으로 말미암아; 으로 인해 aplanaría el tono solemne deliberado. (선택 termina en ㄱ, así que 으로 es lo correcto.)',
          'La prose réflexive, dans le style d\'un essai (그 한 번의, 송두리째, 바뀌고 말았다) convient au 으로 말미암아 élevé et littéraire ; 으로 인해 aplatirait le ton solennel voulu. (선택 se termine par ㄱ, donc 으로 est correct.)',
          'A prosa reflexiva, em estilo de ensaio (그 한 번의, 송두리째, 바뀌고 말았다) combina com o elevado e literário 으로 말미암아; 으로 인해 achataria o tom solene deliberado. (선택 termina em ㄱ, então 으로 está correto.)',
          'ร้อยแก้วเชิงครุ่นคิดแบบเรียงความ (그 한 번의, 송두리째, 바뀌고 말았다) เข้ากันกับ 으로 말미암아 ที่สูงส่งและเป็นวรรณกรรม ส่วน 으로 인해 จะทำให้น้ำเสียงขรึมขลังที่ตั้งใจไว้แบนราบลง (선택 ลงท้ายด้วย ㄱ ดังนั้น 으로 จึงถูกต้อง)',
          'Prosa reflektif bergaya esai (그 한 번의, 송두리째, 바뀌고 말았다) cocok dengan 으로 말미암아 yang tinggi dan sastrawi; 으로 인해 akan mendatarkan nada khidmat yang sengaja dibangun. (선택 berakhir dengan ㄱ, jadi 으로 yang benar.)',
          'Lối văn suy ngẫm, mang dáng dấp tản văn (그 한 번의, 송두리째, 바뀌고 말았다) hợp với 으로 말미암아 trang trọng, đậm chất văn chương; 으로 인해 sẽ làm nhạt đi giọng văn nghiêm trang có chủ ý. (선택 kết thúc bằng ㄱ nên 으로 là đúng.)',
          '内省的でエッセイのような文章(그 한 번의、송두리째、바뀌고 말았다)には格調高く文学的な 으로 말미암아 がふさわしく、으로 인해 では意図された荘重な調子が平板になってしまう。(선택 は ㄱ で終わるので、으로 が正しい。)',
        ),
      },
      {
        sentence: '교통사고{} 도로가 한동안 통제되었습니다.',
        optionA: '로 말미암아',
        optionB: '로 인해',
        answer: 'b',
        trans: L(
          'Due to a traffic accident, the road was closed for a while.',
          'Debido a un accidente de tránsito, la carretera estuvo cerrada un rato.',
          'À cause d\'un accident de la route, la route a été fermée un moment.',
          'Devido a um acidente de trânsito, a estrada ficou fechada por um tempo.',
          'เนื่องจากอุบัติเหตุทางรถยนต์ ถนนจึงถูกปิดไปชั่วขณะ',
          'Akibat kecelakaan lalu lintas, jalan ditutup untuk sementara.',
          'Do một vụ tai nạn giao thông, con đường đã bị đóng trong một lúc.',
          '交通事故により、その道路はしばらく通行止めとなった。',
        ),
        why: L(
          'A routine traffic announcement needs the standard formal 로 인해; the literary 로 말미암아 is out of place in everyday reporting. (교통사고 ends in a vowel, so it takes 로, not 으로.)',
          'Un anuncio de tránsito rutinario necesita el formal estándar 로 인해; el literario 로 말미암아 está fuera de lugar en un reporte cotidiano. (교통사고 termina en vocal, así que lleva 로, no 으로.)',
          'Un avis de circulation routinier nécessite le formel standard 로 인해 ; le littéraire 로 말미암아 est déplacé dans un reportage quotidien. (교통사고 se termine par une voyelle, il prend donc 로 et non 으로.)',
          'Um aviso de trânsito rotineiro precisa do formal padrão 로 인해; o literário 로 말미암아 fica deslocado num relato cotidiano. (교통사고 termina em vogal, então leva 로, não 으로.)',
          'ประกาศจราจรทั่วไปต้องใช้ 로 인해 แบบทางการมาตรฐาน ส่วน 로 말미암아 ที่ออกแนววรรณกรรมไม่เหมาะกับการรายงานในชีวิตประจำวัน (교통사고 ลงท้ายด้วยสระ จึงใช้ 로 ไม่ใช่ 으로)',
          'Pengumuman lalu lintas rutin memerlukan 로 인해 yang formal baku; 로 말미암아 yang sastrawi tidak pas dalam pelaporan sehari-hari. (교통사고 berakhir dengan vokal, jadi memakai 로, bukan 으로.)',
          'Một thông báo giao thông thường nhật cần cách diễn đạt trang trọng chuẩn 로 인해; lối văn chương 로 말미암아 không phù hợp trong tường thuật đời thường. (교통사고 kết thúc bằng nguyên âm nên dùng 로, không phải 으로.)',
          '日常的な交通の告知には標準的でフォーマルな 로 인해 が必要で、文学的な 로 말미암아 は日常の報道では場違いである。(교통사고 は母音で終わるので、으로 ではなく 로 を取る。)',
        ),
      },
    ],
  },
  {
    id: 'nora-neunda',
    a: '-노라',
    b: '-ㄴ/는다',
    note: L(
      'Use -ㄴ/는다 for the ordinary plain/written declarative of modern narration, diaries, and reporting (그는 매일 학교에 간다). Reserve -노라 for solemn, archaic/poetic first-person declarations found in literature and old texts (그대를 사랑하노라) — it sounds strange in everyday factual statements.',
      'Usá -ㄴ/는다 para el declarativo llano/escrito común de la narración moderna, los diarios y los reportes (그는 매일 학교에 간다). Reservá -노라 para declaraciones solemnes, arcaicas/poéticas en primera persona que aparecen en la literatura y los textos antiguos (그대를 사랑하노라) — suena raro en afirmaciones cotidianas y factuales.',
      'Utilise -ㄴ/는다 pour le déclaratif neutre/écrit ordinaire de la narration moderne, des journaux intimes et des comptes rendus (그는 매일 학교에 간다). Réserve -노라 aux déclarations solennelles, archaïques/poétiques à la première personne que l\'on trouve dans la littérature et les textes anciens (그대를 사랑하노라) — cela sonne étrange dans les énoncés factuels du quotidien.',
      'Use -ㄴ/는다 para o declarativo simples/escrito comum da narração moderna, de diários e de reportagens (그는 매일 학교에 간다). Reserve -노라 para declarações solenes, arcaicas/poéticas em primeira pessoa encontradas na literatura e em textos antigos (그대를 사랑하노라) — soa estranho em afirmações factuais do dia a dia.',
      'ใช้ -ㄴ/는다 สำหรับรูปบอกเล่าแบบธรรมดา/ภาษาเขียนทั่วไปในการเล่าเรื่องสมัยใหม่ ไดอารี และการรายงาน (그는 매일 학교에 간다) ส่วน -노라 ให้สงวนไว้สำหรับคำประกาศบุรุษที่หนึ่งอันขรึมขลัง โบราณ/เชิงกวี ที่พบในวรรณกรรมและตำราเก่า (그대를 사랑하노라) — ฟังดูแปลกในประโยคบอกข้อเท็จจริงในชีวิตประจำวัน',
      'Gunakan -ㄴ/는다 untuk deklaratif biasa/tulis yang umum dalam narasi modern, buku harian, dan pelaporan (그는 매일 학교에 간다). Sisakan -노라 untuk pernyataan orang pertama yang khidmat, kuno/puitis yang ditemukan dalam sastra dan teks lama (그대를 사랑하노라) — terdengar janggal dalam pernyataan faktual sehari-hari.',
      'Dùng -ㄴ/는다 cho dạng trần thuật bình thường/văn viết thông dụng trong lối kể chuyện hiện đại, nhật ký và tường thuật (그는 매일 학교에 간다). Dành -노라 cho những lời tuyên bố ngôi thứ nhất trang nghiêm, cổ kính/thơ ca thấy trong văn học và văn bản xưa (그대를 사랑하노라) — nó nghe lạ trong những câu nói sự thật thường ngày.',
      '現代の叙述、日記、報道における普通・書き言葉の平叙には-ㄴ/는다を使う（그는 매일 학교에 간다）。-노라は文学や古文に見られる荘重で古風・詩的な一人称の宣言にとどめること（그대를 사랑하노라）——日常的で事実的な文では不自然に聞こえる。',
    ),
    items: [
      {
        sentence: '형은 매일 아침 6시에 일어나 운동을 {}.',
        optionA: '하노라',
        optionB: '한다',
        answer: 'b',
        trans: L(
          'My brother gets up at 6 every morning and works out.',
          'Mi hermano se levanta a las 6 cada mañana y hace ejercicio.',
          'Mon frère se lève à 6 h chaque matin et fait de l\'exercice.',
          'Meu irmão acorda às 6 toda manhã e se exercita.',
          'พี่ชาย/น้องชายของฉันตื่นตอนตี 6 ทุกเช้าและออกกำลังกาย',
          'Saudara laki-laki saya bangun jam 6 setiap pagi dan berolahraga.',
          'Anh/em trai tôi thức dậy lúc 6 giờ mỗi sáng và tập thể dục.',
          '私の兄（弟）は毎朝6時に起きて運動する。',
        ),
        why: L(
          'This is plain modern narration of a daily habit, so -ㄴ/는다 (한다) is natural; 하노라 is archaic/poetic and absurd for describing a routine.',
          'Esta es narración moderna y llana de un hábito diario, así que -ㄴ/는다 (한다) es natural; 하노라 es arcaico/poético y absurdo para describir una rutina.',
          'C\'est une narration moderne et neutre d\'une habitude quotidienne, donc -ㄴ/는다 (한다) est naturel ; 하노라 est archaïque/poétique et absurde pour décrire une routine.',
          'Esta é uma narração moderna e simples de um hábito diário, então -ㄴ/는다 (한다) é natural; 하노라 é arcaico/poético e absurdo para descrever uma rotina.',
          'นี่คือการเล่าเรื่องสมัยใหม่แบบธรรมดาเกี่ยวกับนิสัยประจำวัน ดังนั้น -ㄴ/는다 (한다) จึงเป็นธรรมชาติ ส่วน 하노라 เป็นแบบโบราณ/กวี และฟังดูไร้สาระเมื่อใช้บรรยายกิจวัตร',
          'Ini adalah narasi modern yang biasa tentang kebiasaan sehari-hari, jadi -ㄴ/는다 (한다) terdengar alami; 하노라 bersifat kuno/puitis dan janggal untuk menggambarkan rutinitas.',
          'Đây là lối kể chuyện hiện đại thông thường về một thói quen hằng ngày, nên -ㄴ/는다 (한다) là tự nhiên; 하노라 mang tính cổ/thơ ca và vô lý khi mô tả thói quen.',
          'これは日常の習慣を述べる現代の普通の叙述なので、-ㄴ/는다（한다）が自然であり、하노라は古風・詩的で日課の描写には不自然だ。',
        ),
      },
      {
        sentence: '오 그대여, 내 너를 영원히 {}.',
        optionA: '사랑하노라',
        optionB: '사랑한다',
        answer: 'a',
        trans: L(
          'Oh my beloved, I do love thee forever.',
          'Oh, amada mía, de verdad te amo por siempre.',
          'Ô ma bien-aimée, je t\'aime vraiment pour toujours.',
          'Ó minha amada, eu de fato te amo para sempre.',
          'โอ้ ที่รักของข้า ข้ารักเจ้าตลอดกาล',
          'Wahai kekasihku, sungguh aku mencintaimu selamanya.',
          'Hỡi người yêu dấu của ta, ta thật lòng yêu nàng mãi mãi.',
          'おお、我が愛しき人よ、私は永遠に汝を愛するのだ。',
        ),
        why: L(
          'The lofty poetic vocative (그대여, 내 너를) calls for the solemn literary -노라 (사랑하노라); the plain 사랑한다 clashes with the elevated archaic tone.',
          'El vocativo poético y elevado (그대여, 내 너를) pide el solemne -노라 literario (사랑하노라); el llano 사랑한다 choca con el tono arcaico y elevado.',
          'Le vocatif poétique et solennel (그대여, 내 너를) appelle le -노라 littéraire et solennel (사랑하노라) ; le neutre 사랑한다 jure avec le ton archaïque et élevé.',
          'O vocativo poético e elevado (그대여, 내 너를) pede o solene -노라 literário (사랑하노라); o simples 사랑한다 destoa do tom arcaico e elevado.',
          'คำเรียกขานเชิงกวีอันสูงส่ง (그대여, 내 너를) เรียกร้องให้ใช้ -노라 แบบวรรณกรรมที่ขรึมขลัง (사랑하노라) ส่วน 사랑한다 แบบธรรมดาขัดกับน้ำเสียงโบราณอันสูงส่ง',
          'Sapaan puitis yang agung (그대여, 내 너를) menuntut -노라 sastrawi yang khidmat (사랑하노라); 사랑한다 yang biasa bertabrakan dengan nada kuno yang agung.',
          'Lối hô gọi thơ ca trang trọng (그대여, 내 너를) đòi hỏi -노라 văn chương trang nghiêm (사랑하노라); 사랑한다 bình thường thì lạc lõng với giọng điệu cổ kính, cao nhã.',
          '格調高い詩的な呼びかけ（그대여, 내 너를）には荘重で文学的な-노라（사랑하노라）がふさわしく、平叙の사랑한다は古風で高尚な調子と相いれない。',
        ),
      },
      {
        sentence: '기사에 따르면 정부는 내년에 세금을 {}.',
        optionA: '올리노라',
        optionB: '올린다',
        answer: 'b',
        trans: L(
          'According to the article, the government will raise taxes next year.',
          'Según el artículo, el gobierno subirá los impuestos el año que viene.',
          'Selon l\'article, le gouvernement augmentera les impôts l\'année prochaine.',
          'Segundo o artigo, o governo vai aumentar os impostos no ano que vem.',
          'ตามบทความนั้น รัฐบาลจะขึ้นภาษีในปีหน้า',
          'Menurut artikel itu, pemerintah akan menaikkan pajak tahun depan.',
          'Theo bài báo, chính phủ sẽ tăng thuế vào năm tới.',
          '記事によれば、政府は来年税金を上げる。',
        ),
        why: L(
          'This is factual news reporting, where the written plain declarative -ㄴ/는다 (올린다) is standard; 올리노라 is archaic and never used for reporting facts.',
          'Esto es reportaje noticioso factual, donde el declarativo llano escrito -ㄴ/는다 (올린다) es estándar; 올리노라 es arcaico y nunca se usa para reportar hechos.',
          'C\'est un reportage factuel, où le déclaratif neutre écrit -ㄴ/는다 (올린다) est la norme ; 올리노라 est archaïque et jamais utilisé pour rapporter des faits.',
          'Isto é reportagem factual, onde o declarativo simples escrito -ㄴ/는다 (올린다) é padrão; 올리노라 é arcaico e nunca usado para relatar fatos.',
          'นี่คือการรายงานข่าวตามข้อเท็จจริง ซึ่งรูปบอกเล่าแบบธรรมดาในภาษาเขียน -ㄴ/는다 (올린다) เป็นมาตรฐาน ส่วน 올리노라 เป็นแบบโบราณและไม่เคยใช้รายงานข้อเท็จจริง',
          'Ini adalah pelaporan berita faktual, di mana deklaratif tulis biasa -ㄴ/는다 (올린다) adalah standar; 올리노라 bersifat kuno dan tidak pernah dipakai untuk melaporkan fakta.',
          'Đây là việc tường thuật tin tức theo sự thật, trong đó dạng trần thuật văn viết thông thường -ㄴ/는다 (올린다) là chuẩn mực; 올리노라 mang tính cổ và không bao giờ dùng để tường thuật sự thật.',
          'これは事実を伝える報道であり、書き言葉の普通の叙述形-ㄴ/는다（올린다）が標準である。올리노라は古風で、事実の報道には決して使われない。',
        ),
      },
    ],
  },
  {
    id: 'ndeul-aeodo',
    a: '-ㄴ들',
    b: '-아/어도',
    note: L(
      'Both mean "even if/though," but -ㄴ들 is rhetorical and signals futility — use it when the sentence asks "what good would it do?" or implies the action is pointless (usually before a rhetorical question). -아/어도 is the plain everyday concessive that simply grants the next clause actually happens.',
      'Ambos significan \'aunque/aun si\', pero -ㄴ들 es retórico y señala inutilidad — usalo cuando la oración pregunta \'¿de qué serviría?\' o implica que la acción es inútil (normalmente antes de una pregunta retórica). -아/어도 es el concesivo cotidiano y simple que solo concede que la cláusula siguiente realmente ocurre.',
      'Les deux signifient \'même si/bien que\', mais -ㄴ들 est rhétorique et signale la futilité — utilise-le quand la phrase demande \'à quoi bon ?\' ou implique que l\'action est inutile (généralement avant une question rhétorique). -아/어도 est le concessif quotidien et simple qui accorde simplement que la proposition suivante se produit réellement.',
      'Ambos significam \'mesmo que/embora\', mas -ㄴ들 é retórico e sinaliza futilidade — use-o quando a frase pergunta \'de que adiantaria?\' ou implica que a ação é inútil (geralmente antes de uma pergunta retórica). -아/어도 é o concessivo cotidiano e simples que apenas concede que a oração seguinte de fato acontece.',
      'ทั้งสองแปลว่า \'แม้ว่า/ต่อให้\' แต่ -ㄴ들 เป็นเชิงโวหารและบ่งบอกถึงความไร้ประโยชน์ — ใช้เมื่อประโยคถามว่า \'จะมีประโยชน์อะไร?\' หรือสื่อว่าการกระทำนั้นไร้ความหมาย (มักอยู่หน้าคำถามเชิงโวหาร) ส่วน -아/어도 เป็นรูปแสดงการยอมรับแบบธรรมดาในชีวิตประจำวันที่เพียงยอมรับว่าอนุประโยคถัดไปเกิดขึ้นจริง',
      'Keduanya berarti \'sekalipun/meskipun\', tetapi -ㄴ들 bersifat retoris dan menandakan kesia-siaan — gunakan ketika kalimat bertanya \'apa gunanya?\' atau menyiratkan bahwa tindakan itu sia-sia (biasanya sebelum pertanyaan retoris). -아/어도 adalah konsesif sehari-hari yang sederhana yang hanya mengakui bahwa klausa berikutnya benar-benar terjadi.',
      'Cả hai đều có nghĩa \'dù/cho dù\', nhưng -ㄴ들 mang tính tu từ và biểu thị sự vô ích — dùng nó khi câu hỏi \'có ích gì?\' hoặc ngụ ý hành động là vô nghĩa (thường đứng trước một câu hỏi tu từ). -아/어도 là cách nhượng bộ thông thường, đơn giản, chỉ thừa nhận rằng mệnh đề tiếp theo thực sự xảy ra.',
      'どちらも「たとえ〜でも」を意味しますが、-ㄴ들 は反語的で無益さを示します — 文が「何の役に立つのか？」と問うとき、または行為が無意味であることを含意するとき（通常は反語的な質問の前で）使います。-아/어도 は日常的で単純な譲歩表現で、次の節が実際に起こることを認めるだけです。',
    ),
    items: [
      {
        sentence: '지금 와서 사과한들 {} 무슨 소용이 있겠어요?',
        optionA: '사과한들',
        optionB: '사과해도',
        answer: 'a',
        trans: L(
          'Even if you apologize now, what good would it do?',
          'Aunque te disculpes ahora, ¿de qué serviría?',
          'Même si tu t\'excuses maintenant, à quoi bon ?',
          'Mesmo que você se desculpe agora, de que adiantaria?',
          'ต่อให้ขอโทษตอนนี้ มันจะมีประโยชน์อะไร?',
          'Sekalipun kamu minta maaf sekarang, apa gunanya?',
          'Dù bây giờ bạn có xin lỗi thì có ích gì chứ?',
          '今さら謝ったところで、何の役に立つというの？',
        ),
        why: L(
          'The clause ends in a rhetorical \'무슨 소용이 있겠어요?\' (what use is it?) expressing futility, which is exactly what -ㄴ들 marks. -아/어도 is the neutral everyday concessive and lacks the built-in rhetorical/pointless force the sentence demands.',
          'La oración termina en una pregunta retórica \'무슨 소용이 있겠어요?\' (¿de qué sirve?) que expresa futilidad, que es justo lo que marca -ㄴ들. -아/어도 es el concesivo neutro de uso diario y carece de la fuerza retórica/de inutilidad incorporada que exige la oración.',
          'La proposition se termine par une question rhétorique \'무슨 소용이 있겠어요?\' (à quoi ça sert ?) exprimant la futilité, ce qui est exactement ce que marque -ㄴ들. -아/어도 est le concessif neutre du quotidien et n\'a pas la force rhétorique/d\'inutilité intégrée qu\'exige la phrase.',
          'A oração termina em uma pergunta retórica \'무슨 소용이 있겠어요?\' (de que adianta?) que expressa futilidade, que é exatamente o que -ㄴ들 marca. -아/어도 é o concessivo neutro do dia a dia e não tem a força retórica/de inutilidade embutida que a frase exige.',
          'ประโยคจบด้วยคำถามเชิงโวหาร \'무슨 소용이 있겠어요?\' (จะมีประโยชน์อะไร?) ที่แสดงถึงความไร้ประโยชน์ ซึ่งเป็นสิ่งที่ -ㄴ들 บ่งบอกพอดี ส่วน -아/어도 เป็นรูปแสดงการยอมรับแบบกลางๆ ในชีวิตประจำวัน และขาดพลังเชิงโวหาร/ความไร้ประโยชน์ที่ฝังอยู่ตามที่ประโยคต้องการ',
          'Klausa berakhir dengan pertanyaan retoris \'무슨 소용이 있겠어요?\' (apa gunanya?) yang mengungkapkan kesia-siaan, yang persis ditandai oleh -ㄴ들. -아/어도 adalah konsesif netral sehari-hari dan tidak memiliki daya retoris/kesia-siaan bawaan yang dituntut kalimat ini.',
          'Mệnh đề kết thúc bằng câu hỏi tu từ \'무슨 소용이 있겠어요?\' (có ích gì?) thể hiện sự vô ích, đúng là điều mà -ㄴ들 đánh dấu. -아/어도 là cách nhượng bộ trung tính hằng ngày và thiếu sắc thái tu từ/vô ích sẵn có mà câu này đòi hỏi.',
          'この節は無益さを表す反語的な \'무슨 소용이 있겠어요?\'（何の役に立つのか）で終わっており、それはまさに -ㄴ들 が示すものです。-아/어도 は日常的で中立的な譲歩表現で、この文が求める反語的・無益さのニュアンスを内在していません。',
        ),
      },
      {
        sentence: '오늘은 좀 {} 끝까지 마무리할게요.',
        optionA: '피곤한들',
        optionB: '피곤해도',
        answer: 'b',
        trans: L(
          'Even though I\'m a bit tired today, I\'ll finish it to the end.',
          'Aunque hoy esté un poco cansado, lo voy a terminar hasta el final.',
          'Même si je suis un peu fatigué aujourd\'hui, je vais le finir jusqu\'au bout.',
          'Mesmo que eu esteja um pouco cansado hoje, vou terminar até o fim.',
          'ถึงแม้วันนี้จะเหนื่อยอยู่บ้าง แต่ฉันก็จะทำให้เสร็จจนถึงที่สุด',
          'Meskipun hari ini agak lelah, aku akan menyelesaikannya sampai akhir.',
          'Dù hôm nay hơi mệt, tôi vẫn sẽ làm xong đến cùng.',
          '今日は少し疲れているけれど、最後までやり遂げるつもりだ。',
        ),
        why: L(
          'This is a plain, real concession leading to a positive resolve (\'I\'ll finish it\'), so everyday -아/어도 fits. -ㄴ들 implies the outcome is futile and pairs with a rhetorical question, which clashes with the determined main clause — making 피곤한들 unnatural here.',
          'Esta es una concesión simple y real que lleva a una resolución positiva (\'lo voy a terminar\'), así que el -아/어도 cotidiano encaja. -ㄴ들 implica que el resultado es inútil y se combina con una pregunta retórica, lo que choca con la oración principal decidida — haciendo que 피곤한들 suene poco natural acá.',
          'C\'est une concession simple et réelle menant à une résolution positive (\'je vais le finir\'), donc le -아/어도 du quotidien convient. -ㄴ들 implique que le résultat est futile et s\'associe à une question rhétorique, ce qui entre en conflit avec la proposition principale déterminée — rendant 피곤한들 peu naturel ici.',
          'Esta é uma concessão simples e real que leva a uma resolução positiva (\'vou terminar\'), então o -아/어도 do dia a dia se encaixa. -ㄴ들 implica que o resultado é inútil e combina com uma pergunta retórica, o que conflita com a oração principal decidida — tornando 피곤한들 não natural aqui.',
          'นี่เป็นการยอมรับแบบธรรมดาและเป็นจริงที่นำไปสู่ความตั้งใจเชิงบวก (\'ฉันจะทำให้เสร็จ\') ดังนั้น -아/어도 แบบใช้ในชีวิตประจำวันจึงเหมาะ ส่วน -ㄴ들 สื่อว่าผลลัพธ์ไร้ประโยชน์และเข้าคู่กับคำถามเชิงโวหาร ซึ่งขัดกับประโยคหลักที่แสดงความมุ่งมั่น ทำให้ 피곤한들 ฟังดูไม่เป็นธรรมชาติในที่นี้',
          'Ini adalah konsesi yang sederhana dan nyata yang mengarah pada tekad positif (\'aku akan menyelesaikannya\'), jadi -아/어도 sehari-hari cocok. -ㄴ들 menyiratkan hasilnya sia-sia dan berpasangan dengan pertanyaan retoris, yang bertabrakan dengan klausa utama yang penuh tekad — membuat 피곤한들 tidak natural di sini.',
          'Đây là một sự nhượng bộ đơn giản, có thật dẫn đến quyết tâm tích cực (\'tôi sẽ làm xong\'), nên -아/어도 hằng ngày là phù hợp. -ㄴ들 ngụ ý kết quả là vô ích và đi kèm câu hỏi tu từ, điều này xung đột với mệnh đề chính đầy quyết tâm — khiến 피곤한들 nghe không tự nhiên ở đây.',
          'これは肯定的な決意（「最後までやり遂げる」）につながる、ありふれた現実の譲歩なので、日常的な -아/어도 が適切です。-ㄴ들 は結果が無益であることを含意し、反語的な質問と組み合わさるため、決意を示す主節と衝突し、ここでは 피곤한들 が不自然になります。',
        ),
      },
      {
        sentence: '네가 아무리 {} 그 사람 마음이 바뀌겠니?',
        optionA: '노력한들',
        optionB: '노력해도',
        answer: 'a',
        trans: L(
          'No matter how hard you try, would that person\'s heart even change?',
          'Por más que te esfuerces, ¿acaso cambiaría el corazón de esa persona?',
          'Quels que soient tes efforts, le cœur de cette personne changerait-il vraiment ?',
          'Por mais que você se esforce, será que o coração daquela pessoa mudaria?',
          'ไม่ว่าจะพยายามมากแค่ไหน หัวใจของคนคนนั้นจะเปลี่ยนได้จริงหรือ?',
          'Sekeras apa pun kamu berusaha, apakah hati orang itu akan berubah?',
          'Dù bạn có cố gắng đến đâu, liệu lòng người đó có thay đổi được không?',
          'いくら頑張ったところで、あの人の心が変わるとでもいうの？',
        ),
        why: L(
          'Paired with 아무리 and the rhetorical question \'바뀌겠니?\' implying hopelessness, -ㄴ들 is the idiomatic choice. While -아/어도 is grammatical with 아무리, the futility-laden rhetorical question makes -ㄴ들 the markedly more natural and intended fit; the why has been sharpened to acknowledge 아무리+-아/어도 is common but reads neutral, lacking the resigned tone the question forces.',
          'Combinado con 아무리 y la pregunta retórica \'바뀌겠니?\' que implica desesperanza, -ㄴ들 es la opción idiomática. Si bien -아/어도 es gramatical con 아무리, la pregunta retórica cargada de futilidad hace que -ㄴ들 sea el ajuste marcadamente más natural e intencionado; el porqué se afinó para reconocer que 아무리+-아/어도 es común pero suena neutro, careciendo del tono resignado que fuerza la pregunta.',
          'Associé à 아무리 et à la question rhétorique \'바뀌겠니?\' qui implique le désespoir, -ㄴ들 est le choix idiomatique. Bien que -아/어도 soit grammatical avec 아무리, la question rhétorique chargée de futilité fait de -ㄴ들 le choix nettement plus naturel et voulu ; le pourquoi a été affiné pour reconnaître que 아무리+-아/어도 est courant mais paraît neutre, dépourvu du ton résigné que la question impose.',
          'Combinado com 아무리 e a pergunta retórica \'바뀌겠니?\' que implica desesperança, -ㄴ들 é a escolha idiomática. Embora -아/어도 seja gramatical com 아무리, a pergunta retórica carregada de futilidade faz de -ㄴ들 o encaixe nitidamente mais natural e pretendido; o porquê foi afinado para reconhecer que 아무리+-아/어도 é comum mas soa neutro, sem o tom resignado que a pergunta força.',
          'เมื่อจับคู่กับ 아무리 และคำถามเชิงโวหาร \'바뀌겠니?\' ที่สื่อถึงความสิ้นหวัง -ㄴ들 จึงเป็นตัวเลือกที่เป็นสำนวนธรรมชาติ แม้ว่า -아/어도 จะถูกหลักไวยากรณ์เมื่อใช้กับ 아무리 แต่คำถามเชิงโวหารที่เต็มไปด้วยความไร้ประโยชน์ทำให้ -ㄴ들 เป็นตัวเลือกที่เป็นธรรมชาติและตรงเจตนามากกว่าอย่างชัดเจน เหตุผลนี้ถูกปรับให้คมขึ้นเพื่อยอมรับว่า 아무리+-아/어도 พบได้ทั่วไปแต่ฟังดูเป็นกลาง ขาดน้ำเสียงยอมจำนนที่คำถามนี้บังคับให้มี',
          'Dipadukan dengan 아무리 dan pertanyaan retoris \'바뀌겠니?\' yang menyiratkan keputusasaan, -ㄴ들 adalah pilihan idiomatik. Meskipun -아/어도 gramatikal dengan 아무리, pertanyaan retoris yang sarat kesia-siaan menjadikan -ㄴ들 pilihan yang jelas lebih natural dan sesuai maksud; alasannya dipertajam untuk mengakui bahwa 아무리+-아/어도 umum tetapi terbaca netral, tanpa nada pasrah yang dipaksakan oleh pertanyaan itu.',
          'Kết hợp với 아무리 và câu hỏi tu từ \'바뀌겠니?\' ngụ ý sự tuyệt vọng, -ㄴ들 là lựa chọn mang tính thành ngữ. Dù -아/어도 đúng ngữ pháp khi đi với 아무리, câu hỏi tu từ đầy sắc thái vô ích khiến -ㄴ들 trở thành lựa chọn tự nhiên và đúng ý hơn hẳn; phần lý do đã được làm rõ để thừa nhận rằng 아무리+-아/어도 là phổ biến nhưng nghe trung tính, thiếu giọng điệu cam chịu mà câu hỏi này áp đặt.',
          '絶望を含意する 아무리 と反語的な質問 \'바뀌겠니?\' と組み合わさると、-ㄴ들 が慣用的な選択です。-아/어도 は 아무리 と文法的には成立しますが、無益さをはらんだ反語的な質問により、-ㄴ들 が明らかにより自然で意図に沿った選択になります。この理由は、아무리+-아/어도 が一般的ではあるものの中立的に読め、この質問が強いる諦めの口調を欠いていることを認めるよう明確化されています。',
        ),
      },
    ],
  },
]
