import type { GrammarExample } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-1 grammar examples (roadmap Step 6). `ko` values match grammars-n1.ts
 * verbatim. 12 verb-ending/expression points x 3 register-tagged examples each
 * (formal/polite/casual), 8-locale translations.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow
 * (grammaticality/naturalness, register-tag accuracy, 8-locale fidelity,
 * conjugation check). Native (Korean wife) review is the documented final gate.
 */
export const TOPIK_1_EXAMPLES: GrammarExample[] = [
  {
    ko: '-아/어요',
    sentence: '저는 물을 마셔요.',
    trans: L(
      'I drink water.',
      'Yo bebo agua.',
      "Je bois de l'eau.",
      'Eu bebo água.',
      'ฉันดื่มน้ำ',
      'Saya minum air.',
      'Tôi uống nước.',
      '私は水を飲みます。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어요',
    sentence: '친구가 책을 읽어요.',
    trans: L(
      'My friend reads a book.',
      'Mi amigo lee un libro.',
      'Mon ami lit un livre.',
      'Meu amigo lê um livro.',
      'เพื่อนอ่านหนังสือ',
      'Teman saya membaca buku.',
      'Bạn tôi đọc sách.',
      '友だちが本を読みます。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어요',
    sentence: '오늘 날씨가 좋아요.',
    trans: L(
      'The weather is nice today.',
      'Hoy hace buen tiempo.',
      "Il fait beau aujourd'hui.",
      'Hoje o tempo está bom.',
      'วันนี้อากาศดี',
      'Hari ini cuacanya bagus.',
      'Hôm nay thời tiết đẹp.',
      '今日は天気がいいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어요',
    sentence: '주말마다 방을 청소해요.',
    trans: L(
      'I clean my room every weekend.',
      'Limpio mi habitación todos los fines de semana.',
      'Je nettoie ma chambre tous les week-ends.',
      'Eu limpo o meu quarto todo fim de semana.',
      'ฉันทำความสะอาดห้องทุกสุดสัปดาห์',
      'Saya membersihkan kamar setiap akhir pekan.',
      'Tôi dọn dẹp phòng vào mỗi cuối tuần.',
      '週末ごとに部屋を掃除します。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었어요',
    sentence: '어제 친구를 만났어요.',
    trans: L(
      'I met a friend yesterday.',
      'Ayer me encontré con un amigo.',
      "Hier, j'ai vu un ami.",
      'Ontem encontrei um amigo.',
      'เมื่อวานเจอเพื่อน',
      'Kemarin saya bertemu teman.',
      'Hôm qua tôi đã gặp bạn.',
      '昨日友達に会いました。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었어요',
    sentence: '아침에 빵을 먹었어요.',
    trans: L(
      'I ate bread in the morning.',
      'Por la mañana comí pan.',
      "Le matin, j'ai mangé du pain.",
      'De manhã comi pão.',
      'ตอนเช้ากินขนมปัง',
      'Pagi tadi saya makan roti.',
      'Buổi sáng tôi đã ăn bánh mì.',
      '朝、パンを食べました。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었어요',
    sentence: '어젯밤에 일찍 잤어요.',
    trans: L(
      'I went to bed early last night.',
      'Anoche me acosté temprano.',
      'Hier soir, je me suis couché tôt.',
      'Ontem à noite dormi cedo.',
      'เมื่อคืนนอนเร็ว',
      'Tadi malam saya tidur lebih awal.',
      'Tối qua tôi đã đi ngủ sớm.',
      '昨夜は早く寝ました。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었어요',
    sentence: '저는 오늘 아침에 공원에서 운동했어요.',
    trans: L(
      'I exercised at the park this morning.',
      'Esta mañana hice ejercicio en el parque.',
      "Ce matin, j'ai fait du sport au parc.",
      'Esta manhã fiz exercício no parque.',
      'เมื่อเช้านี้ฉันออกกำลังกายที่สวนสาธารณะ',
      'Pagi ini saya berolahraga di taman.',
      'Sáng nay tôi đã tập thể dục ở công viên.',
      '今朝、公園で運動しました。',
    ),
    level: 'polite',
  },
  {
    ko: '-ㅂ/습니다',
    sentence: '저는 학생입니다.',
    trans: L(
      'I am a student.',
      'Soy estudiante.',
      'Je suis étudiant.',
      'Eu sou estudante.',
      'ผม/ฉันเป็นนักเรียน',
      'Saya seorang pelajar.',
      'Tôi là học sinh.',
      '私は学生です。',
    ),
    level: 'formal',
  },
  {
    ko: '-ㅂ/습니다',
    sentence: '매일 아침을 먹습니다.',
    trans: L(
      'I eat breakfast every day.',
      'Desayuno todos los días.',
      'Je prends le petit-déjeuner tous les jours.',
      'Eu tomo café da manhã todos os dias.',
      'ผม/ฉันกินอาหารเช้าทุกวัน',
      'Saya sarapan setiap hari.',
      'Tôi ăn sáng mỗi ngày.',
      '毎日朝ごはんを食べます。',
    ),
    level: 'formal',
  },
  {
    ko: '-ㅂ/습니다',
    sentence: '지금 학교에 갑니다.',
    trans: L(
      'I am going to school now.',
      'Ahora voy a la escuela.',
      "Je vais à l'école maintenant.",
      'Agora eu vou para a escola.',
      'ตอนนี้ผม/ฉันไปโรงเรียน',
      'Sekarang saya pergi ke sekolah.',
      'Bây giờ tôi đi đến trường.',
      '今、学校へ行きます。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)세요',
    sentence: '천천히 오세요.',
    trans: L(
      'Please come slowly (take your time).',
      'Venga despacio, por favor (tómese su tiempo).',
      "Venez doucement, s'il vous plaît (prenez votre temps).",
      'Venha devagar, por favor (sem pressa).',
      'ค่อย ๆ มานะคะ (ไม่ต้องรีบ)',
      'Datanglah pelan-pelan (santai saja).',
      'Bạn cứ đến từ từ nhé (đừng vội).',
      'ゆっくり来てください。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)세요',
    sentence: '이 책을 읽으세요.',
    trans: L(
      'Please read this book.',
      'Lea este libro, por favor.',
      "Lisez ce livre, s'il vous plaît.",
      'Leia este livro, por favor.',
      'กรุณาอ่านหนังสือเล่มนี้ค่ะ',
      'Tolong baca buku ini.',
      'Bạn hãy đọc quyển sách này.',
      'この本を読んでください。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)세요',
    sentence: '약을 드세요.',
    trans: L(
      'Please take your medicine.',
      'Tome su medicina, por favor.',
      "Prenez votre médicament, s'il vous plaît.",
      'Tome o remédio, por favor.',
      'กรุณาทานยาด้วยนะคะ',
      'Silakan minum obatnya.',
      'Bạn hãy uống thuốc nhé.',
      'お薬を飲んでください。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 거예요',
    sentence: '내일 친구를 만날 거예요.',
    trans: L(
      "I'm going to meet a friend tomorrow.",
      'Mañana voy a quedar con un amigo.',
      'Demain, je vais voir un ami.',
      'Amanhã vou encontrar um amigo.',
      'พรุ่งนี้ฉันจะไปเจอเพื่อน',
      'Besok saya akan bertemu teman.',
      'Ngày mai tôi sẽ gặp bạn.',
      '明日、友達に会うつもりです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 거예요',
    sentence: '저는 집에서 밥을 먹을 거예요.',
    trans: L(
      "I'm going to eat at home.",
      'Voy a comer en casa.',
      'Je vais manger à la maison.',
      'Vou comer em casa.',
      'ฉันจะกินข้าวที่บ้าน',
      'Saya akan makan di rumah.',
      'Tôi sẽ ăn cơm ở nhà.',
      '私は家でご飯を食べるつもりです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 거예요',
    sentence: '주말에 책을 읽을 거예요.',
    trans: L(
      "I'm going to read a book on the weekend.",
      'El fin de semana voy a leer un libro.',
      'Le week-end, je vais lire un livre.',
      'No fim de semana vou ler um livro.',
      'สุดสัปดาห์ฉันจะอ่านหนังสือ',
      'Akhir pekan saya akan membaca buku.',
      'Cuối tuần tôi sẽ đọc sách.',
      '週末に本を読むつもりです。',
    ),
    level: 'polite',
  },
  {
    ko: '-고',
    sentence: '손을 씻고 밥을 먹습니다.',
    trans: L(
      'I wash my hands and (then) eat.',
      'Me lavo las manos y como.',
      'Je me lave les mains et je mange.',
      'Lavo as mãos e como.',
      'ล้างมือแล้วกินข้าว',
      'Saya cuci tangan lalu makan.',
      'Tôi rửa tay rồi ăn cơm.',
      '手を洗ってご飯を食べます。',
    ),
    level: 'formal',
  },
  {
    ko: '-고',
    sentence: '방이 크고 깨끗해요.',
    trans: L(
      'The room is big and clean.',
      'La habitación es grande y está limpia.',
      'La chambre est grande et propre.',
      'O quarto é grande e limpo.',
      'ห้องกว้างและสะอาด',
      'Kamarnya besar dan bersih.',
      'Phòng rộng và sạch.',
      '部屋が広くてきれいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-고',
    sentence: '숙제를 하고 놀았어.',
    trans: L(
      'I did my homework and (then) played.',
      'Hice la tarea y jugué.',
      "J'ai fait mes devoirs et j'ai joué.",
      'Fiz a lição e brinquei.',
      'ทำการบ้านแล้วก็เล่น',
      'Aku mengerjakan PR lalu bermain.',
      'Tớ làm bài tập rồi đi chơi.',
      '宿題をして遊んだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어서',
    sentence: '늦어서 죄송합니다.',
    trans: L(
      "I'm sorry I'm late.",
      'Siento llegar tarde.',
      "Désolé d'être en retard.",
      'Desculpe pelo atraso.',
      'ขอโทษที่มาสายครับ',
      'Maaf saya terlambat.',
      'Xin lỗi vì tôi đến muộn.',
      '遅れて申し訳ありません。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어서',
    sentence: '비가 와서 집에 있어요.',
    trans: L(
      "It's raining, so I'm staying home.",
      'Está lloviendo, así que me quedo en casa.',
      'Il pleut, alors je reste à la maison.',
      'Está chovendo, então fico em casa.',
      'ฝนตกเลยอยู่บ้านค่ะ',
      'Hujan, jadi saya di rumah.',
      'Trời mưa nên tôi ở nhà.',
      '雨が降っているので家にいます。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어서',
    sentence: '피곤해서 일찍 잤어.',
    trans: L(
      'I was tired, so I went to bed early.',
      'Estaba cansado, así que me acosté temprano.',
      "J'étais fatigué, alors je me suis couché tôt.",
      'Eu estava cansado, então dormi cedo.',
      'เหนื่อยเลยนอนเร็ว',
      'Aku capek, jadi tidur lebih awal.',
      'Tôi mệt nên đi ngủ sớm.',
      '疲れたから早く寝た。',
    ),
    level: 'casual',
  },
  {
    ko: '-지만',
    sentence: '한국어는 어렵지만 재미있습니다.',
    trans: L(
      "Korean is hard, but it's interesting.",
      'El coreano es difícil, pero es interesante.',
      "Le coréen est difficile, mais c'est intéressant.",
      'O coreano é difícil, mas é interessante.',
      'ภาษาเกาหลียาก แต่ก็น่าสนใจ',
      'Bahasa Korea sulit, tapi menarik.',
      'Tiếng Hàn khó nhưng thú vị.',
      '韓国語は難しいですが、面白いです。',
    ),
    level: 'formal',
  },
  {
    ko: '-지만',
    sentence: '비가 오지만 우산이 없어요.',
    trans: L(
      "It's raining, but I don't have an umbrella.",
      'Está lloviendo, pero no tengo paraguas.',
      "Il pleut, mais je n'ai pas de parapluie.",
      'Está chovendo, mas eu não tenho guarda-chuva.',
      'ฝนตกแต่ไม่มีร่ม',
      'Hujan turun, tapi saya tidak punya payung.',
      'Trời mưa nhưng tôi không có ô.',
      '雨が降っていますが、傘がありません。',
    ),
    level: 'polite',
  },
  {
    ko: '-지만',
    sentence: '배고프지만 돈이 없어.',
    trans: L(
      "I'm hungry, but I have no money.",
      'Tengo hambre, pero no tengo dinero.',
      "J'ai faim, mais je n'ai pas d'argent.",
      'Estou com fome, mas não tenho dinheiro.',
      'หิวแต่ไม่มีเงิน',
      'Aku lapar, tapi tidak punya uang.',
      'Tớ đói nhưng không có tiền.',
      'お腹が空いたけど、お金がない。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)면',
    sentence: '비가 오면 집에 있습니다.',
    trans: L(
      'If it rains, I stay home.',
      'Si llueve, me quedo en casa.',
      "S'il pleut, je reste à la maison.",
      'Se chover, fico em casa.',
      'ถ้าฝนตก ฉันจะอยู่บ้าน',
      'Kalau hujan, saya di rumah.',
      'Nếu trời mưa, tôi ở nhà.',
      '雨が降ったら家にいます。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)면',
    sentence: '시간이 있으면 전화하세요.',
    trans: L(
      'If you have time, please call me.',
      'Si tienes tiempo, llámame por favor.',
      'Si vous avez le temps, appelez-moi.',
      'Se tiver tempo, me ligue.',
      'ถ้ามีเวลา โทรหาฉันด้วยนะคะ',
      'Kalau ada waktu, telepon saya ya.',
      'Nếu có thời gian, hãy gọi cho tôi nhé.',
      '時間があったら電話してください。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)면',
    sentence: '피곤하면 일찍 자.',
    trans: L(
      "If you're tired, go to bed early.",
      'Si estás cansado, acuéstate temprano.',
      'Si tu es fatigué, couche-toi tôt.',
      'Se estiver cansado, durma cedo.',
      'ถ้าเหนื่อยก็นอนแต่หัวค่ำนะ',
      'Kalau capek, tidur lebih awal.',
      'Nếu mệt thì đi ngủ sớm.',
      '疲れたら早く寝て。',
    ),
    level: 'casual',
  },
  {
    ko: '-ㄴ/는데',
    sentence: '지금 비가 오는데 우산이 없습니다.',
    trans: L(
      "It's raining right now, but I don't have an umbrella.",
      'Está lloviendo ahora, pero no tengo paraguas.',
      "Il pleut en ce moment, mais je n'ai pas de parapluie.",
      'Está chovendo agora, mas eu não tenho guarda-chuva.',
      'ตอนนี้ฝนตกอยู่ แต่ไม่มีร่ม',
      'Sekarang sedang hujan, tapi saya tidak punya payung.',
      'Bây giờ trời đang mưa mà tôi lại không có ô.',
      '今、雨が降っているんですが、傘がありません。',
    ),
    level: 'formal',
  },
  {
    ko: '-ㄴ/는데',
    sentence: '이 옷이 예쁜데 좀 비싸요.',
    trans: L(
      'These clothes are pretty, but a little expensive.',
      'Esta ropa es bonita, pero un poco cara.',
      'Ces vêtements sont jolis, mais un peu chers.',
      'Esta roupa é bonita, mas um pouco cara.',
      'เสื้อผ้าชุดนี้สวยนะ แต่แพงไปหน่อย',
      'Baju ini cantik, tapi agak mahal.',
      'Bộ đồ này đẹp mà hơi đắt.',
      'この服、かわいいんですけど、ちょっと高いです。',
    ),
    level: 'polite',
  },
  {
    ko: '-ㄴ/는데',
    sentence: '시간이 없는데 우리 빨리 가자.',
    trans: L(
      "We're out of time, so let's hurry up.",
      'No nos queda tiempo, así que vámonos rápido.',
      "On n'a plus le temps, alors dépêchons-nous.",
      'Não temos tempo, então vamos rápido.',
      'ไม่มีเวลาแล้ว เราไปเร็ว ๆ กันเถอะ',
      'Kita tidak punya waktu, ayo cepat pergi.',
      'Hết giờ rồi, mình đi nhanh thôi.',
      '時間がないんだけど、私たち早く行こう。',
    ),
    level: 'casual',
  },
  {
    ko: '-ㄴ/는데',
    sentence: '이 식당은 음식이 좋은데 너무 비싸요.',
    trans: L(
      "The food at this restaurant is good, but it's too expensive.",
      'La comida de este restaurante es buena, pero es demasiado cara.',
      'La nourriture de ce restaurant est bonne, mais elle est trop chère.',
      'A comida deste restaurante é boa, mas é cara demais.',
      'ร้านอาหารร้านนี้อาหารอร่อยดี แต่ราคาแพงเกินไป',
      'Makanan di restoran ini enak, tapi terlalu mahal.',
      'Đồ ăn ở nhà hàng này ngon nhưng lại quá đắt.',
      'このお店は料理がおいしいんですが、高すぎます。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 싶다',
    sentence: '물을 마시고 싶습니다.',
    trans: L(
      'I want to drink water.',
      'Quiero beber agua.',
      "Je veux boire de l'eau.",
      'Quero beber água.',
      'ฉันอยากดื่มน้ำ',
      'Saya ingin minum air.',
      'Tôi muốn uống nước.',
      '水を飲みたいです。',
    ),
    level: 'formal',
  },
  {
    ko: '-고 싶다',
    sentence: '집에 가고 싶어요.',
    trans: L(
      'I want to go home.',
      'Quiero ir a casa.',
      'Je veux rentrer à la maison.',
      'Quero ir para casa.',
      'ฉันอยากกลับบ้าน',
      'Saya ingin pulang ke rumah.',
      'Tôi muốn về nhà.',
      '家に帰りたいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 싶다',
    sentence: '빵을 먹고 싶어.',
    trans: L(
      'I want to eat bread.',
      'Quiero comer pan.',
      'Je veux manger du pain.',
      'Quero comer pão.',
      'ฉันอยากกินขนมปัง',
      'Aku mau makan roti.',
      'Tớ muốn ăn bánh mì.',
      'パンが食べたい。',
    ),
    level: 'casual',
  },
  {
    ko: '-고 있다',
    sentence: '저는 지금 밥을 먹고 있습니다.',
    trans: L(
      'I am eating now.',
      'Ahora estoy comiendo.',
      'Je suis en train de manger maintenant.',
      'Agora estou comendo.',
      'ตอนนี้ฉันกำลังกินข้าวอยู่',
      'Saya sedang makan sekarang.',
      'Bây giờ tôi đang ăn cơm.',
      '私は今ご飯を食べています。',
    ),
    level: 'formal',
  },
  {
    ko: '-고 있다',
    sentence: '친구가 책을 읽고 있어요.',
    trans: L(
      'My friend is reading a book.',
      'Mi amigo está leyendo un libro.',
      'Mon ami est en train de lire un livre.',
      'Meu amigo está lendo um livro.',
      'เพื่อนกำลังอ่านหนังสืออยู่',
      'Teman saya sedang membaca buku.',
      'Bạn tôi đang đọc sách.',
      '友達が本を読んでいます。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 있다',
    sentence: '동생이 음악을 듣고 있어.',
    trans: L(
      'My younger sibling is listening to music.',
      'Mi hermano menor está escuchando música.',
      'Mon petit frère écoute de la musique.',
      'Meu irmão mais novo está ouvindo música.',
      'น้องกำลังฟังเพลงอยู่',
      'Adik saya sedang mendengarkan musik.',
      'Em tôi đang nghe nhạc.',
      '弟が音楽を聞いている。',
    ),
    level: 'casual',
  },
]
