import type { GrammarExample } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-1 grammar examples (roadmap Step 6). `ko` values match grammars-n1.ts
 * verbatim. 12 verb-ending/expression points x 3 register-tagged examples each
 * (formal/polite/casual), 8-locale translations.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow
 * (grammaticality/naturalness, register-tag accuracy, 8-locale fidelity,
 * conjugation check). Native (Korean wife) review is the documented final gate.
 */
export const TOPIK_1_EXAMPLES: GrammarExample[] = [
  {
    ko: '-아/어요',
    sentence: '저는 물을 마셔요.',
    trans: L(
      'I drink water.',
      'Yo bebo agua.',
      "Je bois de l'eau.",
      'Eu bebo água.',
      'ฉันดื่มน้ำ',
      'Saya minum air.',
      'Tôi uống nước.',
      '私は水を飲みます。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어요',
    sentence: '친구가 책을 읽어요.',
    trans: L(
      'My friend reads a book.',
      'Mi amigo lee un libro.',
      'Mon ami lit un livre.',
      'Meu amigo lê um livro.',
      'เพื่อนอ่านหนังสือ',
      'Teman saya membaca buku.',
      'Bạn tôi đọc sách.',
      '友だちが本を読みます。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어요',
    sentence: '오늘 날씨가 좋아요.',
    trans: L(
      'The weather is nice today.',
      'Hoy hace buen tiempo.',
      "Il fait beau aujourd'hui.",
      'Hoje o tempo está bom.',
      'วันนี้อากาศดี',
      'Hari ini cuacanya bagus.',
      'Hôm nay thời tiết đẹp.',
      '今日は天気がいいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었어요',
    sentence: '어제 친구를 만났어요.',
    trans: L(
      'I met a friend yesterday.',
      'Ayer me encontré con un amigo.',
      "Hier, j'ai vu un ami.",
      'Ontem encontrei um amigo.',
      'เมื่อวานเจอเพื่อน',
      'Kemarin saya bertemu teman.',
      'Hôm qua tôi đã gặp bạn.',
      '昨日友達に会いました。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었어요',
    sentence: '아침에 빵을 먹었어요.',
    trans: L(
      'I ate bread in the morning.',
      'Por la mañana comí pan.',
      "Le matin, j'ai mangé du pain.",
      'De manhã comi pão.',
      'ตอนเช้ากินขนมปัง',
      'Pagi tadi saya makan roti.',
      'Buổi sáng tôi đã ăn bánh mì.',
      '朝、パンを食べました。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었어요',
    sentence: '어젯밤에 일찍 잤어요.',
    trans: L(
      'I went to bed early last night.',
      'Anoche me acosté temprano.',
      'Hier soir, je me suis couché tôt.',
      'Ontem à noite dormi cedo.',
      'เมื่อคืนนอนเร็ว',
      'Tadi malam saya tidur lebih awal.',
      'Tối qua tôi đã đi ngủ sớm.',
      '昨夜は早く寝ました。',
    ),
    level: 'polite',
  },
  {
    ko: '-ㅂ/습니다',
    sentence: '저는 학생입니다.',
    trans: L(
      'I am a student.',
      'Soy estudiante.',
      'Je suis étudiant.',
      'Eu sou estudante.',
      'ผม/ฉันเป็นนักเรียน',
      'Saya seorang pelajar.',
      'Tôi là học sinh.',
      '私は学生です。',
    ),
    level: 'formal',
  },
  {
    ko: '-ㅂ/습니다',
    sentence: '매일 아침을 먹습니다.',
    trans: L(
      'I eat breakfast every day.',
      'Desayuno todos los días.',
      'Je prends le petit-déjeuner tous les jours.',
      'Eu tomo café da manhã todos os dias.',
      'ผม/ฉันกินอาหารเช้าทุกวัน',
      'Saya sarapan setiap hari.',
      'Tôi ăn sáng mỗi ngày.',
      '毎日朝ごはんを食べます。',
    ),
    level: 'formal',
  },
  {
    ko: '-ㅂ/습니다',
    sentence: '지금 학교에 갑니다.',
    trans: L(
      'I am going to school now.',
      'Ahora voy a la escuela.',
      "Je vais à l'école maintenant.",
      'Agora eu vou para a escola.',
      'ตอนนี้ผม/ฉันไปโรงเรียน',
      'Sekarang saya pergi ke sekolah.',
      'Bây giờ tôi đi đến trường.',
      '今、学校へ行きます。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)세요',
    sentence: '천천히 오세요.',
    trans: L(
      'Please come slowly (take your time).',
      'Venga despacio, por favor (tómese su tiempo).',
      "Venez doucement, s'il vous plaît (prenez votre temps).",
      'Venha devagar, por favor (sem pressa).',
      'ค่อย ๆ มานะคะ (ไม่ต้องรีบ)',
      'Datanglah pelan-pelan (santai saja).',
      'Bạn cứ đến từ từ nhé (đừng vội).',
      'ゆっくり来てください。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)세요',
    sentence: '이 책을 읽으세요.',
    trans: L(
      'Please read this book.',
      'Lea este libro, por favor.',
      "Lisez ce livre, s'il vous plaît.",
      'Leia este livro, por favor.',
      'กรุณาอ่านหนังสือเล่มนี้ค่ะ',
      'Tolong baca buku ini.',
      'Bạn hãy đọc quyển sách này.',
      'この本を読んでください。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)세요',
    sentence: '약을 드세요.',
    trans: L(
      'Please take your medicine.',
      'Tome su medicina, por favor.',
      "Prenez votre médicament, s'il vous plaît.",
      'Tome o remédio, por favor.',
      'กรุณาทานยาด้วยนะคะ',
      'Silakan minum obatnya.',
      'Bạn hãy uống thuốc nhé.',
      'お薬を飲んでください。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 거예요',
    sentence: '내일 친구를 만날 거예요.',
    trans: L(
      "I'm going to meet a friend tomorrow.",
      'Mañana voy a quedar con un amigo.',
      'Demain, je vais voir un ami.',
      'Amanhã vou encontrar um amigo.',
      'พรุ่งนี้ฉันจะไปเจอเพื่อน',
      'Besok saya akan bertemu teman.',
      'Ngày mai tôi sẽ gặp bạn.',
      '明日、友達に会うつもりです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 거예요',
    sentence: '저는 집에서 밥을 먹을 거예요.',
    trans: L(
      "I'm going to eat at home.",
      'Voy a comer en casa.',
      'Je vais manger à la maison.',
      'Vou comer em casa.',
      'ฉันจะกินข้าวที่บ้าน',
      'Saya akan makan di rumah.',
      'Tôi sẽ ăn cơm ở nhà.',
      '私は家でご飯を食べるつもりです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 거예요',
    sentence: '주말에 책을 읽을 거예요.',
    trans: L(
      "I'm going to read a book on the weekend.",
      'El fin de semana voy a leer un libro.',
      'Le week-end, je vais lire un livre.',
      'No fim de semana vou ler um livro.',
      'สุดสัปดาห์ฉันจะอ่านหนังสือ',
      'Akhir pekan saya akan membaca buku.',
      'Cuối tuần tôi sẽ đọc sách.',
      '週末に本を読むつもりです。',
    ),
    level: 'polite',
  },
  {
    ko: '-고',
    sentence: '손을 씻고 밥을 먹습니다.',
    trans: L(
      'I wash my hands and (then) eat.',
      'Me lavo las manos y como.',
      'Je me lave les mains et je mange.',
      'Lavo as mãos e como.',
      'ล้างมือแล้วกินข้าว',
      'Saya cuci tangan lalu makan.',
      'Tôi rửa tay rồi ăn cơm.',
      '手を洗ってご飯を食べます。',
    ),
    level: 'formal',
  },
  {
    ko: '-고',
    sentence: '방이 크고 깨끗해요.',
    trans: L(
      'The room is big and clean.',
      'La habitación es grande y está limpia.',
      'La chambre est grande et propre.',
      'O quarto é grande e limpo.',
      'ห้องกว้างและสะอาด',
      'Kamarnya besar dan bersih.',
      'Phòng rộng và sạch.',
      '部屋が広くてきれいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-고',
    sentence: '숙제를 하고 놀았어.',
    trans: L(
      'I did my homework and (then) played.',
      'Hice la tarea y jugué.',
      "J'ai fait mes devoirs et j'ai joué.",
      'Fiz a lição e brinquei.',
      'ทำการบ้านแล้วก็เล่น',
      'Aku mengerjakan PR lalu bermain.',
      'Tớ làm bài tập rồi đi chơi.',
      '宿題をして遊んだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어서',
    sentence: '늦어서 죄송합니다.',
    trans: L(
      "I'm sorry I'm late.",
      'Siento llegar tarde.',
      "Désolé d'être en retard.",
      'Desculpe pelo atraso.',
      'ขอโทษที่มาสายครับ',
      'Maaf saya terlambat.',
      'Xin lỗi vì tôi đến muộn.',
      '遅れて申し訳ありません。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어서',
    sentence: '비가 와서 집에 있어요.',
    trans: L(
      "It's raining, so I'm staying home.",
      'Está lloviendo, así que me quedo en casa.',
      'Il pleut, alors je reste à la maison.',
      'Está chovendo, então fico em casa.',
      'ฝนตกเลยอยู่บ้านค่ะ',
      'Hujan, jadi saya di rumah.',
      'Trời mưa nên tôi ở nhà.',
      '雨が降っているので家にいます。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어서',
    sentence: '피곤해서 일찍 잤어.',
    trans: L(
      'I was tired, so I went to bed early.',
      'Estaba cansado, así que me acosté temprano.',
      "J'étais fatigué, alors je me suis couché tôt.",
      'Eu estava cansado, então dormi cedo.',
      'เหนื่อยเลยนอนเร็ว',
      'Aku capek, jadi tidur lebih awal.',
      'Tôi mệt nên đi ngủ sớm.',
      '疲れたから早く寝た。',
    ),
    level: 'casual',
  },
  {
    ko: '-지만',
    sentence: '한국어는 어렵지만 재미있습니다.',
    trans: L(
      "Korean is hard, but it's interesting.",
      'El coreano es difícil, pero es interesante.',
      "Le coréen est difficile, mais c'est intéressant.",
      'O coreano é difícil, mas é interessante.',
      'ภาษาเกาหลียาก แต่ก็น่าสนใจ',
      'Bahasa Korea sulit, tapi menarik.',
      'Tiếng Hàn khó nhưng thú vị.',
      '韓国語は難しいですが、面白いです。',
    ),
    level: 'formal',
  },
  {
    ko: '-지만',
    sentence: '비가 오지만 우산이 없어요.',
    trans: L(
      "It's raining, but I don't have an umbrella.",
      'Está lloviendo, pero no tengo paraguas.',
      "Il pleut, mais je n'ai pas de parapluie.",
      'Está chovendo, mas eu não tenho guarda-chuva.',
      'ฝนตกแต่ไม่มีร่ม',
      'Hujan turun, tapi saya tidak punya payung.',
      'Trời mưa nhưng tôi không có ô.',
      '雨が降っていますが、傘がありません。',
    ),
    level: 'polite',
  },
  {
    ko: '-지만',
    sentence: '배고프지만 돈이 없어.',
    trans: L(
      "I'm hungry, but I have no money.",
      'Tengo hambre, pero no tengo dinero.',
      "J'ai faim, mais je n'ai pas d'argent.",
      'Estou com fome, mas não tenho dinheiro.',
      'หิวแต่ไม่มีเงิน',
      'Aku lapar, tapi tidak punya uang.',
      'Tớ đói nhưng không có tiền.',
      'お腹が空いたけど、お金がない。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)면',
    sentence: '비가 오면 집에 있습니다.',
    trans: L(
      'If it rains, I stay home.',
      'Si llueve, me quedo en casa.',
      "S'il pleut, je reste à la maison.",
      'Se chover, fico em casa.',
      'ถ้าฝนตก ฉันจะอยู่บ้าน',
      'Kalau hujan, saya di rumah.',
      'Nếu trời mưa, tôi ở nhà.',
      '雨が降ったら家にいます。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)면',
    sentence: '시간이 있으면 전화하세요.',
    trans: L(
      'If you have time, please call me.',
      'Si tienes tiempo, llámame por favor.',
      'Si vous avez le temps, appelez-moi.',
      'Se tiver tempo, me ligue.',
      'ถ้ามีเวลา โทรหาฉันด้วยนะคะ',
      'Kalau ada waktu, telepon saya ya.',
      'Nếu có thời gian, hãy gọi cho tôi nhé.',
      '時間があったら電話してください。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)면',
    sentence: '피곤하면 일찍 자.',
    trans: L(
      "If you're tired, go to bed early.",
      'Si estás cansado, acuéstate temprano.',
      'Si tu es fatigué, couche-toi tôt.',
      'Se estiver cansado, durma cedo.',
      'ถ้าเหนื่อยก็นอนแต่หัวค่ำนะ',
      'Kalau capek, tidur lebih awal.',
      'Nếu mệt thì đi ngủ sớm.',
      '疲れたら早く寝て。',
    ),
    level: 'casual',
  },
  {
    ko: '-ㄴ/는데',
    sentence: '지금 비가 오는데 우산이 없습니다.',
    trans: L(
      "It's raining right now, but I don't have an umbrella.",
      'Está lloviendo ahora, pero no tengo paraguas.',
      "Il pleut en ce moment, mais je n'ai pas de parapluie.",
      'Está chovendo agora, mas eu não tenho guarda-chuva.',
      'ตอนนี้ฝนตกอยู่ แต่ไม่มีร่ม',
      'Sekarang sedang hujan, tapi saya tidak punya payung.',
      'Bây giờ trời đang mưa mà tôi lại không có ô.',
      '今、雨が降っているんですが、傘がありません。',
    ),
    level: 'formal',
  },
  {
    ko: '-ㄴ/는데',
    sentence: '이 옷이 예쁜데 좀 비싸요.',
    trans: L(
      'These clothes are pretty, but a little expensive.',
      'Esta ropa es bonita, pero un poco cara.',
      'Ces vêtements sont jolis, mais un peu chers.',
      'Esta roupa é bonita, mas um pouco cara.',
      'เสื้อผ้าชุดนี้สวยนะ แต่แพงไปหน่อย',
      'Baju ini cantik, tapi agak mahal.',
      'Bộ đồ này đẹp mà hơi đắt.',
      'この服、かわいいんですけど、ちょっと高いです。',
    ),
    level: 'polite',
  },
  {
    ko: '-ㄴ/는데',
    sentence: '시간이 없는데 우리 빨리 가자.',
    trans: L(
      "We're out of time, so let's hurry up.",
      'No nos queda tiempo, así que vámonos rápido.',
      "On n'a plus le temps, alors dépêchons-nous.",
      'Não temos tempo, então vamos rápido.',
      'ไม่มีเวลาแล้ว เราไปเร็ว ๆ กันเถอะ',
      'Kita tidak punya waktu, ayo cepat pergi.',
      'Hết giờ rồi, mình đi nhanh thôi.',
      '時間がないんだけど、私たち早く行こう。',
    ),
    level: 'casual',
  },
  {
    ko: '-고 싶다',
    sentence: '물을 마시고 싶습니다.',
    trans: L(
      'I want to drink water.',
      'Quiero beber agua.',
      "Je veux boire de l'eau.",
      'Quero beber água.',
      'ฉันอยากดื่มน้ำ',
      'Saya ingin minum air.',
      'Tôi muốn uống nước.',
      '水を飲みたいです。',
    ),
    level: 'formal',
  },
  {
    ko: '-고 싶다',
    sentence: '집에 가고 싶어요.',
    trans: L(
      'I want to go home.',
      'Quiero ir a casa.',
      'Je veux rentrer à la maison.',
      'Quero ir para casa.',
      'ฉันอยากกลับบ้าน',
      'Saya ingin pulang ke rumah.',
      'Tôi muốn về nhà.',
      '家に帰りたいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 싶다',
    sentence: '빵을 먹고 싶어.',
    trans: L(
      'I want to eat bread.',
      'Quiero comer pan.',
      'Je veux manger du pain.',
      'Quero comer pão.',
      'ฉันอยากกินขนมปัง',
      'Aku mau makan roti.',
      'Tớ muốn ăn bánh mì.',
      'パンが食べたい。',
    ),
    level: 'casual',
  },
  {
    ko: '-고 있다',
    sentence: '저는 지금 밥을 먹고 있습니다.',
    trans: L(
      'I am eating now.',
      'Ahora estoy comiendo.',
      'Je suis en train de manger maintenant.',
      'Agora estou comendo.',
      'ตอนนี้ฉันกำลังกินข้าวอยู่',
      'Saya sedang makan sekarang.',
      'Bây giờ tôi đang ăn cơm.',
      '私は今ご飯を食べています。',
    ),
    level: 'formal',
  },
  {
    ko: '-고 있다',
    sentence: '친구가 책을 읽고 있어요.',
    trans: L(
      'My friend is reading a book.',
      'Mi amigo está leyendo un libro.',
      'Mon ami est en train de lire un livre.',
      'Meu amigo está lendo um livro.',
      'เพื่อนกำลังอ่านหนังสืออยู่',
      'Teman saya sedang membaca buku.',
      'Bạn tôi đang đọc sách.',
      '友達が本を読んでいます。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 있다',
    sentence: '동생이 음악을 듣고 있어.',
    trans: L(
      'My younger sibling is listening to music.',
      'Mi hermano menor está escuchando música.',
      'Mon petit frère écoute de la musique.',
      'Meu irmão mais novo está ouvindo música.',
      'น้องกำลังฟังเพลงอยู่',
      'Adik saya sedang mendengarkan musik.',
      'Em tôi đang nghe nhạc.',
      '弟が音楽を聞いている。',
    ),
    level: 'casual',
  },
  {
    ko: '은/는',
    sentence: '동생은 지금 학교에 있어요.',
    trans: L(
      'My younger sibling is at school right now.',
      'Mi hermano menor está ahora en la escuela.',
      "Mon petit frère est à l'école en ce moment.",
      'Meu irmão mais novo está na escola agora.',
      'น้องของฉันอยู่ที่โรงเรียนตอนนี้',
      'Adik saya sedang di sekolah sekarang.',
      'Em tôi bây giờ đang ở trường.',
      '弟は今学校にいます。',
    ),
    level: 'polite',
  },
  {
    ko: '은/는',
    sentence: '오늘 날씨는 정말 좋네요.',
    trans: L(
      'The weather today is really nice.',
      'El clima de hoy está muy agradable.',
      "Le temps aujourd'hui est vraiment agréable.",
      'O tempo hoje está muito bom.',
      'อากาศวันนี้ดีจริง ๆ เลย',
      'Cuaca hari ini benar-benar bagus.',
      'Thời tiết hôm nay thật là đẹp.',
      '今日の天気は本当にいいですね。',
    ),
    level: 'polite',
  },
  {
    ko: '이/가',
    sentence: '값이 너무 비싸요.',
    trans: L(
      'The price is too expensive.',
      'El precio es demasiado caro.',
      'Le prix est trop élevé.',
      'O preço está caro demais.',
      'ราคาแพงเกินไป',
      'Harganya terlalu mahal.',
      'Giá đắt quá.',
      '値段が高すぎます。',
    ),
    level: 'polite',
  },
  {
    ko: '이/가',
    sentence: '오늘 날씨가 정말 좋다.',
    trans: L(
      'The weather is really nice today.',
      'Hoy hace muy buen tiempo.',
      "Il fait vraiment beau aujourd'hui.",
      'O tempo está muito bom hoje.',
      'วันนี้อากาศดีจริงๆ',
      'Cuaca hari ini benar-benar bagus.',
      'Hôm nay thời tiết thật đẹp.',
      '今日は天気が本当にいい。',
    ),
    level: 'casual',
  },
  {
    ko: '을/를',
    sentence: '동생이 물을 마셔요.',
    trans: L(
      'My younger sibling drinks water.',
      'Mi hermano menor bebe agua.',
      "Mon petit frère boit de l'eau.",
      'Meu irmão mais novo bebe água.',
      'น้องดื่มน้ำ',
      'Adik saya minum air.',
      'Em tôi uống nước.',
      '弟が水を飲みます。',
    ),
    level: 'polite',
  },
  {
    ko: '을/를',
    sentence: '저는 영화를 좋아해요.',
    trans: L(
      'I like movies.',
      'Me gustan las películas.',
      "J'aime les films.",
      'Eu gosto de filmes.',
      'ฉันชอบดูหนัง',
      'Saya suka film.',
      'Tôi thích phim.',
      '私は映画が好きです。',
    ),
    level: 'polite',
  },
  {
    ko: '와/과 · 하고 · (이)랑',
    sentence: '아침에 빵과 우유를 먹습니다.',
    trans: L(
      'In the morning I eat bread and milk.',
      'Por la mañana como pan y leche.',
      'Le matin, je mange du pain et du lait.',
      'De manhã eu como pão e leite.',
      'ตอนเช้าฉันกินขนมปังและนม',
      'Pada pagi hari saya makan roti dan susu.',
      'Buổi sáng tôi ăn bánh mì và uống sữa.',
      '朝、パンと牛乳を食べます。',
    ),
    level: 'formal',
  },
  {
    ko: '와/과 · 하고 · (이)랑',
    sentence: '주말에 가족하고 공원에 갔어요.',
    trans: L(
      'On the weekend I went to the park with my family.',
      'El fin de semana fui al parque con mi familia.',
      'Le week-end, je suis allé au parc avec ma famille.',
      'No fim de semana fui ao parque com a minha família.',
      'สุดสัปดาห์ฉันไปสวนสาธารณะกับครอบครัว',
      'Pada akhir pekan saya pergi ke taman bersama keluarga.',
      'Cuối tuần tôi đã đi công viên với gia đình.',
      '週末に家族と公園に行きました。',
    ),
    level: 'polite',
  },
  {
    ko: '와/과 · 하고 · (이)랑',
    sentence: '동생이랑 같이 떡볶이 먹자.',
    trans: L(
      "Let's eat tteokbokki together with my younger sibling.",
      'Comamos tteokbokki juntos con mi hermano menor.',
      'Mangeons des tteokbokki ensemble avec mon petit frère.',
      'Vamos comer tteokbokki juntos com o meu irmão mais novo.',
      'กินต๊อกบกกีด้วยกันกับน้องเถอะ',
      'Ayo makan tteokbokki bersama dengan adikku.',
      'Cùng ăn tteokbokki với em mình đi.',
      '弟と一緒にトッポッキを食べよう。',
    ),
    level: 'casual',
  },
  {
    ko: '에게 / 한테 / 께',
    sentence: '동생에게 편지를 보냈어요.',
    trans: L(
      'I sent a letter to my younger sibling.',
      'Le envié una carta a mi hermano menor.',
      "J'ai envoyé une lettre à mon petit frère.",
      'Enviei uma carta para o meu irmão mais novo.',
      'ฉันส่งจดหมายให้น้อง',
      'Saya mengirim surat kepada adik saya.',
      'Tôi đã gửi thư cho em tôi.',
      '弟に手紙を送りました。',
    ),
    level: 'polite',
  },
  {
    ko: '에게 / 한테 / 께',
    sentence: '나 친구한테 문자 보냈어.',
    trans: L(
      'I sent a text to my friend.',
      'Le mandé un mensaje a mi amigo.',
      "J'ai envoyé un texto à mon ami.",
      'Mandei uma mensagem para o meu amigo.',
      'ฉันส่งข้อความหาเพื่อน',
      'Aku mengirim pesan ke temanku.',
      'Tớ đã nhắn tin cho bạn tớ.',
      '友達にメッセージを送ったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '에게 / 한테 / 께',
    sentence: '할머니께 선물을 드렸습니다.',
    trans: L(
      'I gave a present to my grandmother.',
      'Le di un regalo a mi abuela.',
      "J'ai offert un cadeau à ma grand-mère.",
      'Dei um presente para a minha avó.',
      'ผมมอบของขวัญให้คุณยาย',
      'Saya memberikan hadiah kepada nenek saya.',
      'Tôi đã tặng quà cho bà.',
      '祖母にプレゼントを差し上げました。',
    ),
    level: 'formal',
  },
  {
    ko: '부터 / 까지',
    sentence: '방학은 다음 주부터 시작해요.',
    trans: L(
      'Vacation starts from next week.',
      'Las vacaciones empiezan a partir de la próxima semana.',
      'Les vacances commencent à partir de la semaine prochaine.',
      'As férias começam a partir da próxima semana.',
      'ปิดเทอมเริ่มตั้งแต่สัปดาห์หน้า',
      'Liburan mulai dari minggu depan.',
      'Kỳ nghỉ bắt đầu từ tuần sau.',
      '休みは来週から始まります。',
    ),
    level: 'polite',
  },
  {
    ko: '부터 / 까지',
    sentence: '이 책을 내일까지 다 읽으세요.',
    trans: L(
      'Please finish reading this book by tomorrow.',
      'Por favor, termina de leer este libro para mañana.',
      "Finissez de lire ce livre d'ici demain, s'il vous plaît.",
      'Por favor, termine de ler este livro até amanhã.',
      'กรุณาอ่านหนังสือเล่มนี้ให้จบภายในพรุ่งนี้',
      'Tolong selesaikan membaca buku ini sebelum besok.',
      'Hãy đọc xong quyển sách này trước ngày mai.',
      'この本を明日まで全部読んでください。',
    ),
    level: 'polite',
  },
  {
    ko: 'N(이)랑 / 하고 + 같이 / 함께',
    sentence: '저는 가족하고 함께 공원에 갔어요.',
    trans: L(
      'I went to the park together with my family.',
      'Fui al parque junto con mi familia.',
      'Je suis allé au parc avec ma famille.',
      'Eu fui ao parque junto com a minha família.',
      'ฉันไปสวนสาธารณะด้วยกันกับครอบครัว',
      'Saya pergi ke taman bersama keluarga.',
      'Tôi đã đi công viên cùng với gia đình.',
      '私は家族と一緒に公園へ行きました。',
    ),
    level: 'polite',
  },
  {
    ko: 'N(이)랑 / 하고 + 같이 / 함께',
    sentence: '동생이랑 같이 영화를 봤어.',
    trans: L(
      'I watched a movie together with my younger sibling.',
      'Vi una película con mi hermano menor.',
      "J'ai regardé un film avec mon petit frère.",
      'Assisti a um filme junto com o meu irmão mais novo.',
      'ฉันดูหนังด้วยกันกับน้อง',
      'Aku menonton film bareng adik.',
      'Tôi đã xem phim cùng với em.',
      '弟と一緒に映画を見たよ。',
    ),
    level: 'casual',
  },
  {
    ko: '이다 / 아니다',
    sentence: '여기가 우리 학교예요.',
    trans: L(
      'This place is our school.',
      'Aquí es nuestra escuela.',
      "Ici, c'est notre école.",
      'Aqui é a nossa escola.',
      'ที่นี่คือโรงเรียนของเรา',
      'Di sini adalah sekolah kami.',
      'Đây là trường của chúng tôi.',
      'ここがうちの学校です。',
    ),
    level: 'polite',
  },
  {
    ko: '이다 / 아니다',
    sentence: '저 사람은 제 동생이 아니에요.',
    trans: L(
      'That person is not my younger sibling.',
      'Esa persona no es mi hermano menor.',
      "Cette personne n'est pas mon cadet.",
      'Aquela pessoa não é meu irmão mais novo.',
      'คนนั้นไม่ใช่น้องของฉัน',
      'Orang itu bukan adik saya.',
      'Người kia không phải là em của tôi.',
      'あの人は私の弟ではありません。',
    ),
    level: 'polite',
  },
  {
    ko: '있다 / 없다',
    sentence: '냉장고에 우유가 있어요.',
    trans: L(
      'There is milk in the fridge.',
      'Hay leche en el refrigerador.',
      'Il y a du lait dans le réfrigérateur.',
      'Tem leite na geladeira.',
      'มีนมอยู่ในตู้เย็น',
      'Ada susu di kulkas.',
      'Trong tủ lạnh có sữa.',
      '冷蔵庫に牛乳があります。',
    ),
    level: 'polite',
  },
  {
    ko: '있다 / 없다',
    sentence: '오늘은 숙제가 없어.',
    trans: L(
      "There's no homework today.",
      'Hoy no hay tarea.',
      "Aujourd'hui, il n'y a pas de devoirs.",
      'Hoje não tem lição de casa.',
      'วันนี้ไม่มีการบ้าน',
      'Hari ini tidak ada PR.',
      'Hôm nay không có bài tập về nhà.',
      '今日は宿題がないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ 적이 있다/없다',
    sentence: '저는 제주도에서 산 적이 있어요.',
    trans: L(
      'I have lived on Jeju Island before.',
      'He vivido en la isla de Jeju antes.',
      "J'ai déjà vécu sur l'île de Jeju.",
      'Eu já morei na ilha de Jeju.',
      'ฉันเคยอาศัยอยู่ที่เกาะเชจูมาก่อน',
      'Saya pernah tinggal di Pulau Jeju.',
      'Tôi đã từng sống ở đảo Jeju.',
      '私は済州島で暮らしたことがあります。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ 적이 있다/없다',
    sentence: '저는 김치를 만든 적이 없어요.',
    trans: L(
      'I have never made kimchi.',
      'Nunca he hecho kimchi.',
      "Je n'ai jamais fait de kimchi.",
      'Eu nunca fiz kimchi.',
      'ฉันไม่เคยทำกิมจิเลย',
      'Saya belum pernah membuat kimchi.',
      'Tôi chưa bao giờ làm kimchi.',
      '私はキムチを作ったことがありません。',
    ),
    level: 'polite',
  },
  {
    ko: '안 + V / -지 않다',
    sentence: '저는 커피를 안 마셔요.',
    trans: L(
      "I don't drink coffee.",
      'No tomo café.',
      'Je ne bois pas de café.',
      'Eu não tomo café.',
      'ฉันไม่ดื่มกาแฟ',
      'Saya tidak minum kopi.',
      'Tôi không uống cà phê.',
      '私はコーヒーを飲みません。',
    ),
    level: 'polite',
  },
  {
    ko: '안 + V / -지 않다',
    sentence: '오늘은 날씨가 춥지 않아요.',
    trans: L(
      'The weather is not cold today.',
      'Hoy no hace frío.',
      "Aujourd'hui, il ne fait pas froid.",
      'Hoje não está frio.',
      'วันนี้อากาศไม่หนาว',
      'Hari ini cuacanya tidak dingin.',
      'Hôm nay thời tiết không lạnh.',
      '今日は天気が寒くありません。',
    ),
    level: 'polite',
  },
  {
    ko: '못 + V / -지 못하다',
    sentence: '저는 운전을 못 해요.',
    trans: L(
      "I can't drive.",
      'No sé conducir.',
      'Je ne sais pas conduire.',
      'Eu não sei dirigir.',
      'ฉันขับรถไม่เป็น',
      'Saya tidak bisa menyetir.',
      'Tôi không biết lái xe.',
      '私は運転ができません。',
    ),
    level: 'polite',
  },
  {
    ko: '못 + V / -지 못하다',
    sentence: '매워서 김치를 먹지 못해요.',
    trans: L(
      "It's spicy, so I can't eat the kimchi.",
      'Es picante, así que no puedo comer el kimchi.',
      "C'est épicé, donc je ne peux pas manger le kimchi.",
      'É picante, então não consigo comer o kimchi.',
      'เผ็ดเลยกินกิมจิไม่ได้',
      'Karena pedas, saya tidak bisa makan kimchi.',
      'Vì cay nên tôi không ăn được kimchi.',
      '辛くてキムチを食べられません。',
    ),
    level: 'polite',
  },
  {
    ko: '좋아하다 / 싫어하다',
    sentence: '저는 강아지를 좋아해요.',
    trans: L(
      'I like dogs.',
      'Me gustan los perros.',
      "J'aime les chiens.",
      'Eu gosto de cachorros.',
      'ฉันชอบหมา',
      'Saya suka anjing.',
      'Tôi thích chó.',
      '私は犬が好きです。',
    ),
    level: 'polite',
  },
  {
    ko: '좋아하다 / 싫어하다',
    sentence: '저는 벌레를 싫어해요.',
    trans: L(
      'I dislike bugs.',
      'No me gustan los insectos.',
      "Je n'aime pas les insectes.",
      'Eu não gosto de insetos.',
      'ฉันไม่ชอบแมลง',
      'Saya tidak suka serangga.',
      'Tôi không thích côn trùng.',
      '私は虫が嫌いです。',
    ),
    level: 'polite',
  },
  {
    ko: '이 / 그 / 저',
    sentence: '이 책은 제 거예요.',
    trans: L(
      'This book is mine.',
      'Este libro es mío.',
      'Ce livre est à moi.',
      'Este livro é meu.',
      'หนังสือเล่มนี้เป็นของฉัน',
      'Buku ini milik saya.',
      'Quyển sách này là của tôi.',
      'この本は私のです。',
    ),
    level: 'polite',
  },
  {
    ko: '이 / 그 / 저',
    sentence: '그 영화 정말 재미있어요.',
    trans: L(
      'That movie is really fun.',
      'Esa película es muy divertida.',
      'Ce film est vraiment amusant.',
      'Esse filme é muito divertido.',
      'หนังเรื่องนั้นสนุกมากเลย',
      'Film itu benar-benar seru.',
      'Bộ phim đó thật sự rất hay.',
      'その映画は本当に面白いです。',
    ),
    level: 'polite',
  },
  {
    ko: '이 / 그 / 저',
    sentence: '저 산 이름이 뭐예요?',
    trans: L(
      'What is the name of that mountain over there?',
      '¿Cómo se llama aquella montaña?',
      "Comment s'appelle cette montagne là-bas ?",
      'Qual é o nome daquela montanha ali?',
      'ภูเขาลูกโน้นชื่ออะไร',
      'Apa nama gunung yang di sana itu?',
      'Ngọn núi đằng kia tên là gì?',
      'あの山の名前は何ですか。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)러 가다/오다',
    sentence: '점심을 먹으러 식당에 갔어요.',
    trans: L(
      'I went to the restaurant to eat lunch.',
      'Fui al restaurante a comer el almuerzo.',
      'Je suis allé au restaurant pour déjeuner.',
      'Fui ao restaurante para almoçar.',
      'ฉันไปร้านอาหารเพื่อกินข้าวกลางวัน',
      'Saya pergi ke restoran untuk makan siang.',
      'Tôi đã đến nhà hàng để ăn trưa.',
      '昼ご飯を食べにレストランへ行きました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)러 가다/오다',
    sentence: '친구가 우리 집에 놀러 왔어요.',
    trans: L(
      'My friend came to my house to hang out.',
      'Mi amigo vino a mi casa a pasar el rato.',
      'Mon ami est venu chez moi pour passer du temps ensemble.',
      'Meu amigo veio à minha casa para passar um tempo.',
      'เพื่อนมาเที่ยวที่บ้านของฉัน',
      'Teman saya datang ke rumah saya untuk main.',
      'Bạn tôi đã đến nhà tôi để chơi.',
      '友達がうちに遊びに来ました。',
    ),
    level: 'polite',
  },
]
