import type { GrammarExample } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-2 grammar examples (roadmap Step 6 / plan Part B Tier-1). Per-FORM
 * coverage for the two-form TOPIK-2 grammars: each grammar whose `ko` names ≥2
 * distinct surface forms shows ≥1 example per form. `ko` values match
 * grammars-n2.ts verbatim; sentences differ from each grammar's canonical
 * `Grammar.example` (the "above ≠ below" invariant).
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow
 * (grammaticality/naturalness, per-form realization, register-tag accuracy,
 * 8-locale fidelity). Native (Korean wife) review is the documented final gate.
 */
export const TOPIK_2_EXAMPLES: GrammarExample[] = [
  {
    ko: '-(으)ㄴ 후에 / 다음에',
    sentence: '숙제를 끝낸 후에 친구를 만났어요.',
    trans: L(
      'After I finished my homework, I met a friend.',
      'Después de terminar la tarea, quedé con un amigo.',
      "Après avoir fini mes devoirs, j'ai retrouvé un ami.",
      'Depois de terminar a lição de casa, encontrei um amigo.',
      'หลังจากทำการบ้านเสร็จแล้ว ฉันก็ไปเจอเพื่อน',
      'Setelah selesai mengerjakan PR, saya bertemu teman.',
      'Sau khi làm xong bài tập, tôi đã gặp bạn.',
      '宿題を終えた後に友達に会いました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ 후에 / 다음에',
    sentence: '손을 씻은 다음에 과일을 먹었어요.',
    trans: L(
      'After washing my hands, I ate some fruit.',
      'Después de lavarme las manos, comí fruta.',
      "Après m'être lavé les mains, j'ai mangé des fruits.",
      'Depois de lavar as mãos, comi frutas.',
      'หลังจากล้างมือแล้ว ฉันก็กินผลไม้',
      'Setelah mencuci tangan, saya makan buah.',
      'Sau khi rửa tay, tôi đã ăn trái cây.',
      '手を洗った後に果物を食べました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 수 있다/없다',
    sentence: '내일은 시간이 있어서 모임에 갈 수 있어요.',
    trans: L(
      'I have time tomorrow, so I can go to the gathering.',
      'Mañana tengo tiempo, así que puedo ir a la reunión.',
      "Demain j'ai du temps, donc je peux aller à la réunion.",
      'Amanhã eu tenho tempo, então posso ir ao encontro.',
      'พรุ่งนี้ฉันมีเวลา เลยไปงานรวมตัวได้',
      'Besok saya ada waktu, jadi saya bisa pergi ke pertemuan itu.',
      'Ngày mai tôi có thời gian nên tôi có thể đi đến buổi gặp mặt.',
      '明日は時間があるので、集まりに行けます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 수 있다/없다',
    sentence: '다리를 다쳐서 지금은 빨리 걸을 수 없어요.',
    trans: L(
      "I hurt my leg, so I can't walk fast right now.",
      'Me lastimé la pierna, así que ahora no puedo caminar rápido.',
      'Je me suis blessé à la jambe, donc je ne peux pas marcher vite en ce moment.',
      'Eu machuquei a perna, então agora não consigo andar rápido.',
      'ฉันบาดเจ็บที่ขา ตอนนี้เลยเดินเร็วไม่ได้',
      'Saya cedera di kaki, jadi sekarang saya tidak bisa berjalan cepat.',
      'Tôi bị thương ở chân nên bây giờ tôi không thể đi nhanh được.',
      '足をけがしたので、今は速く歩けません。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 필요가 있다/없다',
    sentence: '감기에 걸렸으니까 병원에 갈 필요가 있어요.',
    trans: L(
      "Since you've caught a cold, you need to go to the hospital.",
      'Como te has resfriado, hace falta que vayas al hospital.',
      "Comme tu as attrapé un rhume, il faut que tu ailles à l'hôpital.",
      'Como você pegou um resfriado, é preciso ir ao hospital.',
      'เพราะเป็นหวัด เลยจำเป็นต้องไปโรงพยาบาล',
      'Karena kamu kena flu, kamu perlu pergi ke rumah sakit.',
      'Vì bị cảm rồi nên cần phải đi bệnh viện.',
      '風邪をひいたから、病院に行く必要があります。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 필요가 있다/없다',
    sentence: '이미 다 준비했으니까 더 살 필요가 없어요.',
    trans: L(
      "We've already got everything ready, so there's no need to buy any more.",
      'Ya lo tenemos todo preparado, así que no hace falta comprar más.',
      "On a déjà tout préparé, donc il n'y a pas besoin d'en acheter plus.",
      'Já preparamos tudo, então não é preciso comprar mais.',
      'เตรียมทุกอย่างไว้หมดแล้ว เลยไม่จำเป็นต้องซื้อเพิ่ม',
      'Semuanya sudah disiapkan, jadi tidak perlu membeli lagi.',
      'Đã chuẩn bị hết rồi nên không cần phải mua thêm.',
      'もう全部準備したので、これ以上買う必要がありません。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 나서 / -고 나면',
    sentence: '운동을 하고 나서 샤워를 했어요.',
    trans: L(
      'After I worked out, I took a shower.',
      'Después de hacer ejercicio, me duché.',
      "Après avoir fait du sport, j'ai pris une douche.",
      'Depois de me exercitar, tomei banho.',
      'หลังจากออกกำลังกายเสร็จ ฉันก็อาบน้ำ',
      'Setelah selesai berolahraga, saya mandi.',
      'Sau khi tập thể dục xong, tôi đã đi tắm.',
      '運動をしてから、シャワーを浴びました。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 나서 / -고 나면',
    sentence: '이 책을 다 읽고 나면 마음이 편해질 거예요.',
    trans: L(
      "Once you finish reading this book, you'll feel at ease.",
      'Una vez que termines de leer este libro, te sentirás tranquilo.',
      'Une fois que tu auras fini de lire ce livre, tu te sentiras apaisé.',
      'Depois que você terminar de ler este livro, vai se sentir tranquilo.',
      'พออ่านหนังสือเล่มนี้จบ คุณก็จะรู้สึกสบายใจขึ้น',
      'Setelah selesai membaca buku ini, hatimu akan menjadi tenang.',
      'Một khi đọc xong cuốn sách này, bạn sẽ thấy lòng nhẹ nhõm.',
      'この本を読み終えると、心が楽になりますよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-군요 / -구나',
    sentence: '오늘 날씨가 정말 춥군요.',
    trans: L(
      'Oh, the weather is really cold today.',
      'Vaya, hoy hace mucho frío.',
      "Tiens, il fait vraiment froid aujourd'hui.",
      'Nossa, hoje está mesmo frio.',
      'วันนี้อากาศหนาวจริง ๆ เลยนะ',
      'Wah, hari ini cuacanya dingin sekali ya.',
      'Ồ, hôm nay trời lạnh thật đấy.',
      '今日は本当に寒いですね。',
    ),
    level: 'polite',
  },
  {
    ko: '-군요 / -구나',
    sentence: '너 벌써 다 컸구나.',
    trans: L(
      "Wow, you've already grown up so much.",
      'Vaya, ya has crecido un montón.',
      'Oh, tu as déjà tellement grandi.',
      'Nossa, você já cresceu tanto.',
      'โอ้ เธอโตขึ้นเยอะเลยนะ',
      'Wah, kamu sudah besar sekali ya.',
      'Ồ, cháu đã lớn thế này rồi cơ à.',
      'もうこんなに大きくなったんだね。',
    ),
    level: 'casual',
  },
  {
    ko: '-기 쉽다/어렵다',
    sentence: '겨울에는 길이 미끄러워서 넘어지기 쉬워요.',
    trans: L(
      "In winter the roads are slippery, so it's easy to fall.",
      'En invierno las calles están resbaladizas, así que es fácil caerse.',
      'En hiver, les routes sont glissantes, donc on tombe facilement.',
      'No inverno as ruas ficam escorregadias, então é fácil cair.',
      'ในฤดูหนาวถนนลื่น เลยหกล้มได้ง่าย',
      'Di musim dingin jalanan licin, jadi mudah terpeleset jatuh.',
      'Vào mùa đông đường trơn nên rất dễ bị ngã.',
      '冬は道が滑りやすいので、転びやすいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-기 쉽다/어렵다',
    sentence: '외국어로 농담을 이해하기 어려워요.',
    trans: L(
      "It's hard to understand jokes in a foreign language.",
      'Es difícil entender los chistes en un idioma extranjero.',
      "C'est difficile de comprendre les blagues dans une langue étrangère.",
      'É difícil entender piadas em uma língua estrangeira.',
      'เป็นเรื่องยากที่จะเข้าใจมุกตลกในภาษาต่างประเทศ',
      'Sulit memahami lelucon dalam bahasa asing.',
      'Thật khó để hiểu những câu nói đùa bằng tiếng nước ngoài.',
      '外国語で冗談を理解するのは難しいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고요? / -(이)라고요?',
    sentence: '지금 밖에 비가 온다고요?',
    trans: L(
      "It's raining outside right now, you said?",
      '¿Dices que ahora está lloviendo afuera?',
      "Tu dis qu'il pleut dehors en ce moment ?",
      'Você disse que está chovendo lá fora agora?',
      'บอกว่าตอนนี้ข้างนอกฝนตกเหรอ',
      'Katanya sekarang di luar sedang hujan?',
      'Bạn bảo bây giờ bên ngoài đang mưa à?',
      '今、外で雨が降っていると言いましたか？',
    ),
    level: 'polite',
  },
  {
    ko: '-다고요? / -(이)라고요?',
    sentence: '저분이 새로 오신 선생님이라고요?',
    trans: L(
      'That person is the new teacher who just joined, you said?',
      '¿Dices que esa persona es el nuevo profesor que acaba de llegar?',
      "Tu dis que cette personne est le nouveau professeur qui vient d'arriver ?",
      'Você disse que aquela pessoa é o novo professor que acabou de chegar?',
      'บอกว่าท่านนั้นคือคุณครูคนใหม่ที่เพิ่งมาเหรอ',
      'Katanya orang itu guru baru yang baru datang?',
      'Bạn bảo vị đó là thầy giáo mới vừa đến à?',
      'あの方が新しく来られた先生だと言いましたか？',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 놓다 / -아/어 두다',
    sentence: '창문을 열어 놓았으니까 방이 곧 시원해질 거예요.',
    trans: L(
      "I've opened the window (and left it open), so the room will cool down soon.",
      'Dejé la ventana abierta, así que la habitación se enfriará pronto.',
      "J'ai laissé la fenêtre ouverte, donc la pièce va vite se rafraîchir.",
      'Deixei a janela aberta, então o quarto vai esfriar logo.',
      'เปิดหน้าต่างทิ้งไว้แล้ว เดี๋ยวห้องก็จะเย็นลงเอง',
      'Saya sudah membuka jendela (dan membiarkannya terbuka), jadi kamarnya akan segera sejuk.',
      'Tôi đã mở sẵn cửa sổ rồi, nên phòng sẽ mát ngay thôi.',
      '窓を開けておいたので、部屋がすぐ涼しくなりますよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 놓다 / -아/어 두다',
    sentence: '친구 전화번호를 휴대폰에 저장해 뒀어요.',
    trans: L(
      "I saved my friend's phone number in my phone (and keep it there).",
      'Guardé el número de mi amigo en el móvil (y lo tengo ahí guardado).',
      "J'ai enregistré le numéro de mon ami dans mon téléphone (et je le garde).",
      'Salvei o número do meu amigo no celular (e deixo guardado lá).',
      'บันทึกเบอร์โทรของเพื่อนเก็บไว้ในมือถือแล้ว',
      'Saya sudah menyimpan nomor telepon teman saya di ponsel (dan menyimpannya di sana).',
      'Tôi đã lưu sẵn số điện thoại của bạn vào điện thoại rồi.',
      '友達の電話番号を携帯に保存しておきました。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어야 하다 / 되다',
    sentence: '약을 먹기 전에 밥을 먼저 먹어야 해요.',
    trans: L(
      'You have to eat something first before taking the medicine.',
      'Tienes que comer algo primero antes de tomar la medicina.',
      "Tu dois d'abord manger quelque chose avant de prendre le médicament.",
      'Você tem que comer algo primeiro antes de tomar o remédio.',
      'ต้องกินข้าวก่อนถึงจะกินยาได้',
      'Kamu harus makan dulu sebelum minum obat.',
      'Bạn phải ăn gì đó trước khi uống thuốc.',
      '薬を飲む前に、まずご飯を食べなければなりません。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어야 하다 / 되다',
    sentence: '내일 아침에 일찍 일어나야 돼요.',
    trans: L(
      'I have to get up early tomorrow morning.',
      'Tengo que levantarme temprano mañana por la mañana.',
      'Je dois me lever tôt demain matin.',
      'Tenho que acordar cedo amanhã de manhã.',
      'พรุ่งนี้เช้าฉันต้องตื่นแต่เช้า',
      'Besok pagi saya harus bangun pagi-pagi.',
      'Sáng mai tôi phải dậy sớm.',
      '明日の朝は早く起きなければなりません。',
    ),
    level: 'polite',
  },
  {
    ko: '-처럼 / -같이',
    sentence: '오늘 날씨가 봄처럼 따뜻해요.',
    trans: L(
      'The weather today is warm like spring.',
      'Hoy el clima está cálido como en primavera.',
      "Aujourd'hui, le temps est doux comme au printemps.",
      'Hoje o tempo está quente como na primavera.',
      'วันนี้อากาศอบอุ่นเหมือนฤดูใบไม้ผลิ',
      'Cuaca hari ini hangat seperti musim semi.',
      'Thời tiết hôm nay ấm áp như mùa xuân.',
      '今日は天気が春のように暖かいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-처럼 / -같이',
    sentence: '동생은 토끼같이 빨리 뛰어요.',
    trans: L(
      'My little brother runs fast like a rabbit.',
      'Mi hermano menor corre rápido como un conejo.',
      'Mon petit frère court vite comme un lapin.',
      'Meu irmão mais novo corre rápido como um coelho.',
      'น้องวิ่งเร็วเหมือนกระต่าย',
      'Adik saya berlari cepat seperti kelinci.',
      'Em tôi chạy nhanh như một con thỏ.',
      '弟はウサギのように速く走ります。',
    ),
    level: 'polite',
  },
  {
    ko: '때문에 / 기 때문에',
    sentence: '시험 때문에 요즘 너무 바빠요.',
    trans: L(
      "Because of the exam, I'm really busy these days.",
      'A causa del examen, estos días estoy muy ocupado.',
      "À cause de l'examen, je suis très occupé ces jours-ci.",
      'Por causa da prova, ando muito ocupado esses dias.',
      'เพราะการสอบ ช่วงนี้ฉันยุ่งมากเลย',
      'Karena ujian, akhir-akhir ini saya sangat sibuk.',
      'Vì kỳ thi, dạo này tôi rất bận.',
      '試験のせいで、最近とても忙しいです。',
    ),
    level: 'polite',
  },
  {
    ko: '때문에 / 기 때문에',
    sentence: '내일 일찍 일어나야 하기 때문에 지금 자려고 해요.',
    trans: L(
      "Because I have to get up early tomorrow, I'm going to sleep now.",
      'Como mañana tengo que levantarme temprano, voy a dormir ahora.',
      'Comme je dois me lever tôt demain, je vais dormir maintenant.',
      'Como amanhã tenho que acordar cedo, vou dormir agora.',
      'เพราะพรุ่งนี้ต้องตื่นเช้า ตอนนี้เลยจะเข้านอนแล้ว',
      'Karena besok harus bangun pagi, sekarang saya mau tidur.',
      'Vì ngày mai phải dậy sớm nên bây giờ tôi định đi ngủ.',
      '明日早く起きなければならないので、今から寝ようと思います。',
    ),
    level: 'polite',
  },
  {
    ko: '아무 N(이)나 / 아무 N도',
    sentence: '급하니까 아무 펜이나 주세요.',
    trans: L(
      "I'm in a hurry, so just give me any pen.",
      'Como tengo prisa, deme cualquier bolígrafo.',
      "Je suis pressé, alors donnez-moi n'importe quel stylo.",
      'Estou com pressa, então me dê qualquer caneta.',
      'รีบอยู่ ขอปากกาด้ามไหนก็ได้ค่ะ',
      'Saya buru-buru, jadi berikan saja pulpen apa saja.',
      'Tôi đang vội, nên cho tôi cây bút nào cũng được.',
      '急いでいるので、どのペンでもいいから渡してください。',
    ),
    level: 'polite',
  },
  {
    ko: '아무 N(이)나 / 아무 N도',
    sentence: '주말이라서 가게에 아무 손님도 없었어요.',
    trans: L(
      "Because it was the weekend, there wasn't a single customer in the shop.",
      'Como era fin de semana, no había ningún cliente en la tienda.',
      "Comme c'était le week-end, il n'y avait aucun client dans la boutique.",
      'Como era fim de semana, não havia nenhum cliente na loja.',
      'เพราะเป็นวันหยุดสุดสัปดาห์ ในร้านจึงไม่มีลูกค้าสักคนเลย',
      'Karena akhir pekan, tidak ada satu pelanggan pun di toko.',
      'Vì là cuối tuần nên trong cửa hàng không có một người khách nào.',
      '週末だったので、店にはお客さんが一人もいませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '아직 / 벌써 / 이미',
    sentence: '엄마는 아직 안 주무세요.',
    trans: L(
      "Mom isn't asleep yet.",
      'Mamá todavía no está durmiendo.',
      'Maman ne dort pas encore.',
      'A mamãe ainda não está dormindo.',
      'แม่ยังไม่นอนเลย',
      'Ibu masih belum tidur.',
      'Mẹ vẫn chưa ngủ.',
      'お母さんはまだ寝ていません。',
    ),
    level: 'polite',
  },
  {
    ko: '아직 / 벌써 / 이미',
    sentence: '벌써 12시예요? 시간 정말 빠르네요.',
    trans: L(
      "It's already 12 o'clock? Time really flies.",
      '¿Ya son las 12? El tiempo vuela de verdad.',
      'Il est déjà midi ? Le temps passe vraiment vite.',
      'Já são 12 horas? O tempo voa mesmo.',
      'เที่ยงแล้วเหรอ เวลาผ่านไปเร็วจริง ๆ',
      'Sudah jam 12? Waktu benar-benar cepat berlalu.',
      'Đã 12 giờ rồi à? Thời gian trôi nhanh thật.',
      'もう12時ですか？時間が経つのは本当に早いですね。',
    ),
    level: 'polite',
  },
  {
    ko: '아직 / 벌써 / 이미',
    sentence: '제가 도착했을 때 회의는 이미 끝났어요.',
    trans: L(
      'When I arrived, the meeting had already ended.',
      'Cuando llegué, la reunión ya había terminado.',
      'Quand je suis arrivé, la réunion était déjà terminée.',
      'Quando cheguei, a reunião já tinha terminado.',
      'ตอนที่ฉันมาถึง การประชุมจบไปแล้ว',
      'Ketika saya tiba, rapatnya sudah selesai.',
      'Khi tôi đến thì cuộc họp đã kết thúc rồi.',
      '私が着いたとき、会議はもう終わっていました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 때',
    sentence: '운전할 때는 휴대폰을 보면 안 됩니다.',
    trans: L(
      "When you're driving, you must not look at your phone.",
      'Cuando conduces, no debes mirar el teléfono.',
      'Quand on conduit, il ne faut pas regarder son téléphone.',
      'Quando você está dirigindo, não deve olhar para o celular.',
      'ตอนขับรถ ห้ามดูโทรศัพท์มือถือ',
      'Saat menyetir, kamu tidak boleh melihat ponsel.',
      'Khi lái xe, bạn không được nhìn điện thoại.',
      '運転するときは携帯電話を見てはいけません。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ 때',
    sentence: '어렸을 때 시골에서 할머니랑 살았어.',
    trans: L(
      'When I was little, I lived in the countryside with my grandmother.',
      'Cuando era pequeño, vivía en el campo con mi abuela.',
      "Quand j'étais petit, je vivais à la campagne avec ma grand-mère.",
      'Quando eu era pequeno, morava no interior com a minha avó.',
      'ตอนเด็ก ๆ ฉันอยู่ที่ชนบทกับคุณยาย',
      'Waktu kecil, aku tinggal di desa bersama nenek.',
      'Hồi nhỏ, tớ sống ở quê với bà.',
      '小さいとき、田舎でおばあちゃんと暮らしていたよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-기 전에',
    sentence: '회사에 가기 전에 커피를 한 잔 마셔요.',
    trans: L(
      'Before going to work, I drink a cup of coffee.',
      'Antes de ir al trabajo, tomo una taza de café.',
      "Avant d'aller au travail, je bois une tasse de café.",
      'Antes de ir para o trabalho, eu tomo uma xícara de café.',
      'ก่อนไปทำงาน ฉันดื่มกาแฟหนึ่งแก้ว',
      'Sebelum berangkat kerja, saya minum secangkir kopi.',
      'Trước khi đi làm, tôi uống một cốc cà phê.',
      '会社に行く前に、コーヒーを一杯飲みます。',
    ),
    level: 'polite',
  },
  {
    ko: '-기 전에',
    sentence: '밥을 먹기 전에 손을 깨끗이 씻어라.',
    trans: L(
      'Wash your hands well before you eat.',
      'Lávate bien las manos antes de comer.',
      'Lave-toi bien les mains avant de manger.',
      'Lave bem as mãos antes de comer.',
      'ล้างมือให้สะอาดก่อนกินข้าว',
      'Cuci tanganmu sampai bersih sebelum makan.',
      'Hãy rửa tay sạch sẽ trước khi ăn cơm.',
      'ご飯を食べる前に、手をきれいに洗いなさい。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 동안',
    sentence: '제가 회의하는 동안 아이를 좀 봐 주시겠어요?',
    trans: L(
      "While I'm in the meeting, could you watch my child for a bit?",
      'Mientras estoy en la reunión, ¿podría cuidar a mi hijo un momento?',
      'Pendant que je suis en réunion, pourriez-vous garder mon enfant un instant ?',
      'Enquanto eu estiver na reunião, você poderia cuidar do meu filho um pouco?',
      'ระหว่างที่ฉันประชุมอยู่ ช่วยดูลูกให้หน่อยได้ไหมคะ',
      'Selama saya rapat, bisakah Anda menjaga anak saya sebentar?',
      'Trong lúc tôi họp, bạn có thể trông con giúp tôi một chút được không?',
      '私が会議をしている間、子供を少し見ていただけますか？',
    ),
    level: 'polite',
  },
  {
    ko: '-는 동안',
    sentence: '비가 오는 동안 우리는 카페에서 기다렸어.',
    trans: L(
      'While it was raining, we waited at the cafe.',
      'Mientras llovía, esperamos en la cafetería.',
      "Pendant qu'il pleuvait, nous avons attendu au café.",
      'Enquanto chovia, a gente esperou no café.',
      'ระหว่างที่ฝนตก พวกเรารออยู่ที่ร้านกาแฟ',
      'Selama hujan turun, kami menunggu di kafe.',
      'Trong lúc trời mưa, chúng tôi đã đợi ở quán cà phê.',
      '雨が降っている間、私たちはカフェで待っていた。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 것',
    sentence: '운동하는 것이 건강에 정말 좋아요.',
    trans: L(
      'Exercising is really good for your health.',
      'Hacer ejercicio es muy bueno para la salud.',
      "Faire de l'exercice est vraiment bon pour la santé.",
      'Fazer exercício é muito bom para a saúde.',
      'การออกกำลังกายดีต่อสุขภาพมากจริงๆ',
      'Berolahraga itu sangat baik untuk kesehatan.',
      'Việc tập thể dục thật sự rất tốt cho sức khỏe.',
      '運動することは健康に本当にいいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-는 것',
    sentence: '혼자 영화 보는 거 별로 안 좋아해.',
    trans: L(
      "I don't really like watching movies alone.",
      'No me gusta mucho ver películas sola.',
      "Je n'aime pas trop regarder des films tout seul.",
      'Eu não gosto muito de assistir filme sozinho.',
      'ฉันไม่ค่อยชอบดูหนังคนเดียวเท่าไหร่',
      'Aku nggak terlalu suka nonton film sendirian.',
      'Mình không thích lắm việc xem phim một mình.',
      '一人で映画を見るのはあまり好きじゃない。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 것 같다',
    sentence: '민수 씨는 벌써 집에 간 것 같아요.',
    trans: L(
      'It seems Minsu already went home.',
      'Parece que Minsu ya se fue a casa.',
      'On dirait que Minsu est déjà rentré chez lui.',
      'Parece que o Minsu já foi para casa.',
      'ดูเหมือนว่ามินซูจะกลับบ้านไปแล้ว',
      'Sepertinya Minsu sudah pulang ke rumah.',
      'Hình như Minsu đã về nhà rồi.',
      'ミンスさんはもう家に帰ったようです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 것 같다',
    sentence: '밖에 비가 오는 것 같아.',
    trans: L(
      "It seems like it's raining outside.",
      'Parece que está lloviendo afuera.',
      "On dirait qu'il pleut dehors.",
      'Parece que está chovendo lá fora.',
      'ข้างนอกเหมือนฝนกำลังตกอยู่เลย',
      'Sepertinya di luar sedang hujan.',
      'Hình như bên ngoài đang mưa.',
      '外は雨が降っているみたい。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 모양이다',
    sentence: '표가 매진됐네요. 이 영화가 인기가 많은 모양이에요.',
    trans: L(
      'The tickets are sold out — this movie must be quite popular.',
      'Las entradas están agotadas; parece que esta película es muy popular.',
      "Les billets sont épuisés ; ce film a l'air d'être très populaire.",
      'Os ingressos estão esgotados; parece que esse filme é bem popular.',
      'ตั๋วขายหมดแล้ว ดูท่าหนังเรื่องนี้คงจะดังมากเลย',
      'Tiketnya habis terjual; sepertinya film ini sangat populer.',
      'Vé đã bán hết rồi; xem chừng bộ phim này rất nổi tiếng.',
      'チケットが売り切れですね。この映画は人気があるようです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 모양이다',
    sentence: '옆집 형은 요즘 매일 도서관에 가던데, 시험이 곧 있는 모양이야.',
    trans: L(
      'The guy next door has been going to the library every day lately, so it seems he has an exam coming up soon.',
      'El chico de al lado ha ido a la biblioteca todos los días últimamente, así que parece que pronto tiene un examen.',
      "Le gars d'à côté va à la bibliothèque tous les jours ces temps-ci, on dirait qu'il a bientôt un examen.",
      'O cara do lado tem ido à biblioteca todos os dias ultimamente, parece que ele vai ter uma prova em breve.',
      'พี่บ้านข้างๆ ช่วงนี้ไปห้องสมุดทุกวันเลย ท่าทางจะมีสอบเร็วๆ นี้',
      'Kakak rumah sebelah belakangan ini tiap hari ke perpustakaan, sepertinya sebentar lagi ada ujian.',
      'Anh nhà bên dạo này ngày nào cũng đi thư viện, có vẻ như sắp có kỳ thi rồi.',
      '隣のお兄さんは最近毎日図書館に行ってるけど、もうすぐ試験があるみたいだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)면 되다',
    sentence: '이 약은 하루에 세 번 식사 후에 먹으면 됩니다.',
    trans: L(
      'You just need to take this medicine three times a day after meals.',
      'Solo tienes que tomar este medicamento tres veces al día después de las comidas.',
      'Il vous suffit de prendre ce médicament trois fois par jour après les repas.',
      'Você só precisa tomar este remédio três vezes ao dia após as refeições.',
      'คุณแค่กินยานี้วันละสามครั้งหลังอาหารก็พอ',
      'Anda cukup minum obat ini tiga kali sehari setelah makan.',
      'Bạn chỉ cần uống thuốc này ba lần một ngày sau bữa ăn là được.',
      'この薬は一日三回、食後に飲めばいいです。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)면 되다',
    sentence: '걱정하지 마, 늦으면 그냥 나한테 전화하면 돼.',
    trans: L(
      "Don't worry, if you're running late just call me, that's all.",
      'No te preocupes, si llegas tarde solo llámame y ya está.',
      "Ne t'inquiète pas, si tu es en retard tu n'as qu'à m'appeler.",
      'Não se preocupe, se você se atrasar é só me ligar.',
      'ไม่ต้องห่วงนะ ถ้ามาสายก็แค่โทรหาฉันก็พอ',
      'Jangan khawatir, kalau kamu terlambat tinggal telepon aku saja.',
      'Đừng lo, nếu trễ thì cứ gọi cho mình là được.',
      '心配しないで、遅れたら私に電話すればいいよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)면 안 되다',
    sentence: '수업 시간에 휴대폰을 보면 안 됩니다.',
    trans: L(
      'You must not look at your phone during class.',
      'No se puede mirar el móvil durante la clase.',
      'Il ne faut pas regarder son téléphone pendant le cours.',
      'Não pode olhar o celular durante a aula.',
      'ห้ามดูโทรศัพท์ในเวลาเรียน',
      'Tidak boleh melihat ponsel saat pelajaran.',
      'Không được xem điện thoại trong giờ học.',
      '授業中に携帯を見てはいけません。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)면 안 되다',
    sentence: '이건 비밀이니까 누구한테도 말하면 안 돼.',
    trans: L(
      "This is a secret, so you can't tell anyone.",
      'Esto es un secreto, así que no puedes decírselo a nadie.',
      "C'est un secret, alors tu ne dois le dire à personne.",
      'Isso é segredo, então não pode contar pra ninguém.',
      'นี่เป็นความลับ ห้ามบอกใครนะ',
      'Ini rahasia, jadi tidak boleh bilang ke siapa pun.',
      'Đây là bí mật nên không được nói với ai cả.',
      'これは秘密だから誰にも言っちゃだめだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ게요',
    sentence: '내일 아침에 일찍 전화할게요.',
    trans: L(
      "I'll call you early tomorrow morning.",
      'Te llamaré temprano mañana por la mañana.',
      "Je t'appellerai tôt demain matin.",
      'Vou te ligar cedo amanhã de manhã.',
      'พรุ่งนี้เช้าฉันจะโทรหาคุณแต่เช้าเลยนะ',
      'Besok pagi-pagi aku akan meneleponmu.',
      'Sáng mai tôi sẽ gọi cho bạn sớm nhé.',
      '明日の朝、早く電話しますね。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ게요',
    sentence: '설거지는 내가 할게.',
    trans: L(
      "I'll do the dishes.",
      'Yo lavo los platos.',
      'Je fais la vaisselle, moi.',
      'Eu lavo a louça.',
      'เดี๋ยวเราล้างจานเอง',
      'Aku saja yang cuci piring.',
      'Để tớ rửa bát cho.',
      '皿洗いは僕がやるね。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ까요?',
    sentence: '창문을 좀 열까요?',
    trans: L(
      'Shall I open the window a little?',
      '¿Abro un poco la ventana?',
      'Je peux ouvrir un peu la fenêtre ?',
      'Quer que eu abra um pouco a janela?',
      'เปิดหน้าต่างสักหน่อยดีไหม',
      'Mau saya bukakan jendelanya sedikit?',
      'Tôi mở cửa sổ một chút nhé?',
      '窓を少し開けましょうか？',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ까요?',
    sentence: '내일 날씨가 좋을까요?',
    trans: L(
      'Do you think the weather will be nice tomorrow?',
      '¿Crees que mañana hará buen tiempo?',
      "Penses-tu qu'il fera beau demain ?",
      'Será que o tempo vai estar bom amanhã?',
      'พรุ่งนี้อากาศจะดีไหมนะ',
      'Apakah besok cuacanya akan bagus ya?',
      'Ngày mai thời tiết liệu có đẹp không nhỉ?',
      '明日は天気がいいでしょうか？',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)려고',
    sentence: '버스를 놓치지 않으려고 아침 일찍 집을 나섰어.',
    trans: L(
      "I left the house early in the morning so I wouldn't miss the bus.",
      'Salí de casa temprano por la mañana para no perder el autobús.',
      'Je suis parti de la maison tôt le matin pour ne pas rater le bus.',
      'Saí de casa cedo de manhã para não perder o ônibus.',
      'ฉันออกจากบ้านแต่เช้าเพื่อจะได้ไม่พลาดรถบัส',
      'Aku keluar rumah pagi-pagi supaya tidak ketinggalan bus.',
      'Tôi ra khỏi nhà sớm vào buổi sáng để không bị lỡ xe buýt.',
      'バスに乗り遅れないように、朝早く家を出たよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)려고',
    sentence: '건강을 지키려고 매일 아침 공원에서 운동합니다.',
    trans: L(
      'I exercise at the park every morning to stay healthy.',
      'Hago ejercicio en el parque todas las mañanas para cuidar mi salud.',
      'Je fais du sport au parc chaque matin pour préserver ma santé.',
      'Faço exercício no parque toda manhã para cuidar da saúde.',
      'ผมออกกำลังกายที่สวนสาธารณะทุกเช้าเพื่อรักษาสุขภาพ',
      'Saya berolahraga di taman setiap pagi untuk menjaga kesehatan.',
      'Tôi tập thể dục ở công viên mỗi sáng để giữ gìn sức khỏe.',
      '健康を守るために、毎朝公園で運動します。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 보다',
    sentence: '제주도에 한번 가 보세요. 정말 좋아요.',
    trans: L(
      "Try going to Jeju Island sometime. It's really nice.",
      'Anímate a ir a la isla de Jeju alguna vez. Es muy bonita.',
      "Essayez d'aller sur l'île de Jeju un jour. C'est vraiment magnifique.",
      'Experimente ir à ilha de Jeju algum dia. É muito bonita.',
      'ลองไปเกาะเชจูดูสักครั้งสิ สวยมากเลย',
      'Coba sekali-kali pergi ke Pulau Jeju. Bagus banget.',
      'Hãy thử đến đảo Jeju một lần đi. Đẹp lắm đấy.',
      '一度済州島に行ってみてください。本当にいいですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 보다',
    sentence: '이 신발 한번 신어 봐도 돼요?',
    trans: L(
      'Can I try these shoes on?',
      '¿Puedo probarme estos zapatos?',
      'Est-ce que je peux essayer ces chaussures ?',
      'Posso experimentar estes sapatos?',
      'ขอลองสวมรองเท้าคู่นี้หน่อยได้ไหมคะ',
      'Boleh saya coba pakai sepatu ini?',
      'Tôi thử đi đôi giày này được không ạ?',
      'この靴、ちょっと履いてみてもいいですか？',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 주다',
    sentence: '창문 좀 열어 주세요.',
    trans: L(
      'Please open the window.',
      'Abre la ventana, por favor.',
      "Ouvre la fenêtre, s'il te plaît.",
      'Abra a janela, por favor.',
      'ช่วยเปิดหน้าต่างให้หน่อยนะคะ',
      'Tolong bukakan jendelanya.',
      'Làm ơn mở cửa sổ giúp tôi với.',
      '窓を開けてください。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 주다',
    sentence: '친구가 무거운 가방을 들어 줬어.',
    trans: L(
      'My friend carried the heavy bag for me.',
      'Mi amigo me cargó la bolsa pesada.',
      'Mon ami a porté le sac lourd pour moi.',
      'Meu amigo carregou a bolsa pesada para mim.',
      'เพื่อนช่วยถือกระเป๋าหนักๆ ให้ฉัน',
      'Temanku membawakan tas yang berat untukku.',
      'Bạn tôi đã xách giúp tôi cái túi nặng.',
      '友達が重いカバンを持ってくれた。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 버리다',
    sentence: '버스가 눈앞에서 그냥 가 버렸어요.',
    trans: L(
      'The bus just left right in front of me.',
      'El autobús se fue justo delante de mis narices.',
      'Le bus est parti juste sous mon nez.',
      'O ônibus foi embora bem na minha frente.',
      'รถเมล์ออกไปต่อหน้าต่อตาเลย',
      'Bisnya pergi begitu saja tepat di depan mataku.',
      'Xe buýt đã đi mất ngay trước mắt tôi.',
      'バスが目の前で行ってしまいました。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 버리다',
    sentence: '배가 너무 고파서 케이크를 혼자 다 먹어 버렸어.',
    trans: L(
      'I was so hungry I ended up eating the whole cake by myself.',
      'Tenía tanta hambre que me comí todo el pastel yo sola.',
      "J'avais tellement faim que j'ai fini par manger tout le gâteau toute seule.",
      'Eu estava com tanta fome que acabei comendo o bolo inteiro sozinha.',
      'หิวมากเลยกินเค้กหมดทั้งก้อนคนเดียวเลย',
      'Aku lapar banget sampai akhirnya menghabiskan kuenya sendirian.',
      'Tớ đói quá nên đã ăn hết cả cái bánh một mình luôn.',
      'お腹がすごく空いてて、ケーキを一人で全部食べてしまった。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)니까',
    sentence: '지금 길이 많이 막히니까 우리 지하철로 가자.',
    trans: L(
      "The roads are really jammed right now, so let's take the subway.",
      'Ahora hay mucho tráfico, así que vámonos en metro.',
      "Il y a beaucoup d'embouteillages en ce moment, alors prenons le métro.",
      'O trânsito está muito ruim agora, então vamos de metrô.',
      'ตอนนี้รถติดมาก เราไปรถไฟใต้ดินกันเถอะ',
      'Sekarang jalanannya macet parah, jadi ayo kita naik kereta bawah tanah.',
      'Bây giờ đường kẹt xe lắm nên mình đi tàu điện ngầm đi.',
      '今は道がすごく混んでいるから、地下鉄で行こう。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)니까',
    sentence: '처음 오셨으니까 제가 사무실을 안내해 드리겠습니다.',
    trans: L(
      "Since it's your first time here, I'll show you around the office.",
      'Como es su primera vez aquí, le mostraré la oficina.',
      "Comme c'est votre première visite, je vais vous faire visiter le bureau.",
      'Como é a sua primeira vez aqui, vou lhe mostrar o escritório.',
      'เนื่องจากท่านมาที่นี่เป็นครั้งแรก ผมจะพาท่านชมสำนักงานครับ',
      'Karena Anda baru pertama kali datang ke sini, saya akan menunjukkan kantornya.',
      'Vì đây là lần đầu quý vị đến nên tôi sẽ dẫn quý vị đi tham quan văn phòng.',
      '初めていらっしゃったので、私がオフィスをご案内いたします。',
    ),
    level: 'formal',
  },
  {
    ko: '-거나',
    sentence: '심심할 때는 게임을 하거나 친구한테 전화해.',
    trans: L(
      "When I'm bored, I play games or call a friend.",
      'Cuando me aburro, juego videojuegos o llamo a un amigo.',
      "Quand je m'ennuie, je joue à des jeux ou j'appelle un ami.",
      'Quando fico entediado, jogo videogame ou ligo para um amigo.',
      'เวลาเบื่อ ฉันจะเล่นเกมหรือไม่ก็โทรหาเพื่อน',
      'Kalau bosan, aku main game atau menelepon teman.',
      'Khi buồn chán, tôi chơi game hoặc gọi điện cho bạn.',
      '退屈なときはゲームをしたり友達に電話したりするよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-거나',
    sentence: '면접에 늦거나 결석하면 합격하기 어렵습니다.',
    trans: L(
      'If you are late for or absent from the interview, it is hard to pass.',
      'Si llega tarde a la entrevista o falta, es difícil ser admitido.',
      "Si vous arrivez en retard à l'entretien ou que vous y êtes absent, il est difficile d'être admis.",
      'Se você se atrasar para a entrevista ou faltar, é difícil ser aprovado.',
      'หากมาสัมภาษณ์สายหรือขาดสอบสัมภาษณ์ ก็จะผ่านได้ยาก',
      'Jika terlambat atau tidak hadir saat wawancara, akan sulit untuk lolos.',
      'Nếu đến muộn hoặc vắng mặt buổi phỏng vấn thì rất khó trúng tuyển.',
      '面接に遅れたり欠席したりすると、合格するのは難しいです。',
    ),
    level: 'formal',
  },
  {
    ko: '-보다',
    sentence: '동생이 저보다 키가 더 커요.',
    trans: L(
      'My younger sibling is taller than me.',
      'Mi hermano menor es más alto que yo.',
      'Mon cadet est plus grand que moi.',
      'Meu irmão mais novo é mais alto do que eu.',
      'น้องตัวสูงกว่าฉัน',
      'Adik saya lebih tinggi daripada saya.',
      'Em tôi cao hơn tôi.',
      '弟は私より背が高いです。',
    ),
    level: 'polite',
  },
  {
    ko: '-보다',
    sentence: '오늘은 어제보다 훨씬 추워.',
    trans: L(
      'Today is much colder than yesterday.',
      'Hoy hace mucho más frío que ayer.',
      "Aujourd'hui, il fait bien plus froid qu'hier.",
      'Hoje está muito mais frio do que ontem.',
      'วันนี้หนาวกว่าเมื่อวานมาก',
      'Hari ini jauh lebih dingin daripada kemarin.',
      'Hôm nay lạnh hơn hôm qua nhiều.',
      '今日は昨日よりずっと寒い。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는지',
    sentence: '내일 비가 올지 안 올지 잘 모르겠어요.',
    trans: L(
      "I'm not really sure whether it'll rain tomorrow or not.",
      'No estoy muy seguro de si lloverá o no mañana.',
      "Je ne sais pas trop s'il va pleuvoir ou non demain.",
      'Não tenho muita certeza se vai chover ou não amanhã.',
      'ไม่ค่อยแน่ใจว่าพรุ่งนี้ฝนจะตกหรือเปล่า',
      'Aku tidak begitu yakin apakah besok akan hujan atau tidak.',
      'Tôi không chắc lắm ngày mai trời có mưa hay không.',
      '明日雨が降るかどうかよくわかりません。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는지',
    sentence: '이 영화가 왜 그렇게 인기가 많은지 모르겠다.',
    trans: L(
      "I don't get why this movie is so popular.",
      'No entiendo por qué esta película es tan popular.',
      'Je ne comprends pas pourquoi ce film est si populaire.',
      'Não entendo por que esse filme é tão popular.',
      'ไม่เข้าใจเลยว่าทำไมหนังเรื่องนี้ถึงได้ดังขนาดนี้',
      'Aku tidak mengerti kenapa film ini begitu populer.',
      'Mình không hiểu tại sao bộ phim này lại nổi tiếng đến vậy.',
      'この映画がどうしてそんなに人気があるのか分からない。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는데요',
    sentence: '지금 밖에 비가 오는데요.',
    trans: L(
      "It's raining outside right now, though...",
      'Es que ahora está lloviendo afuera...',
      "C'est qu'il pleut dehors en ce moment...",
      'Acontece que está chovendo lá fora agora...',
      'คือตอนนี้ข้างนอกฝนตกอยู่นะคะ...',
      'Soalnya sekarang di luar sedang hujan...',
      'Chuyện là bây giờ bên ngoài đang mưa đấy ạ...',
      '今、外は雨が降っているんですけど…',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는데요',
    sentence: '저는 매운 거 잘 못 먹는데요.',
    trans: L(
      "The thing is, I'm not really good with spicy food...",
      'Es que a mí lo picante no se me da muy bien...',
      "C'est que moi, le piquant, j'ai du mal...",
      'É que eu não como muito bem comida apimentada...',
      'คือเรากินเผ็ดไม่ค่อยเก่งอ่ะ...',
      'Soalnya aku nggak begitu kuat makan pedas...',
      'Chuyện là mình ăn cay không giỏi lắm...',
      '私、辛いものあんまり食べられないんだけど…',
    ),
    level: 'polite',
  },
  {
    ko: '얼마나',
    sentence: '이 영화가 얼마나 재미있는지 몰라. 너도 꼭 봐.',
    trans: L(
      'You have no idea how fun this movie is. You have to watch it too.',
      'No tienes idea de lo divertida que es esta película. Tú también tienes que verla.',
      "Tu n'imagines pas à quel point ce film est génial. Toi aussi, regarde-le absolument.",
      'Você nem imagina como esse filme é divertido. Você também precisa assistir.',
      'เธอไม่รู้หรอกว่าหนังเรื่องนี้สนุกแค่ไหน เธอก็ต้องดูให้ได้นะ',
      'Kamu tidak tahu betapa serunya film ini. Kamu juga harus menontonnya.',
      'Cậu không biết bộ phim này hay đến mức nào đâu. Cậu cũng phải xem cho bằng được đấy.',
      'この映画がどれだけ面白いか分からないよ。君もぜひ見て。',
    ),
    level: 'casual',
  },
  {
    ko: '얼마나',
    sentence: '어제 하루 종일 얼마나 많이 걸었는지 다리가 너무 아파요.',
    trans: L(
      'My legs hurt so much because of how much I walked all day yesterday.',
      'Me duelen muchísimo las piernas de lo mucho que caminé ayer todo el día.',
      "J'ai tellement mal aux jambes tant j'ai marché toute la journée hier.",
      'Minhas pernas estão doendo demais de tanto que andei ontem o dia inteiro.',
      'เมื่อวานเดินทั้งวันเยอะมากจนขาปวดไปหมดเลย',
      'Kaki saya sakit sekali karena kemarin seharian saya berjalan begitu banyak.',
      'Hôm qua tôi đi bộ nhiều cả ngày đến nỗi chân đau quá.',
      '昨日一日中どれだけたくさん歩いたか、脚がとても痛いです。',
    ),
    level: 'polite',
  },
  {
    ko: '에 대해(서)',
    sentence: '이번 사고에 대해서 자세히 설명해 주시겠습니까?',
    trans: L(
      'Could you please explain this accident in detail?',
      '¿Podría explicar este accidente en detalle, por favor?',
      "Pourriez-vous expliquer cet accident en détail, s'il vous plaît ?",
      'Você poderia explicar este acidente em detalhes, por favor?',
      'ช่วยอธิบายเกี่ยวกับอุบัติเหตุครั้งนี้อย่างละเอียดได้ไหมครับ',
      'Bisakah Anda menjelaskan tentang kecelakaan ini secara rinci?',
      'Anh/chị có thể giải thích chi tiết về vụ tai nạn này không ạ?',
      '今回の事故について詳しく説明していただけますか。',
    ),
    level: 'formal',
  },
  {
    ko: '에 대해(서)',
    sentence: '나 그 영화에 대해 아무것도 몰라.',
    trans: L(
      "I don't know anything about that movie.",
      'No sé nada sobre esa película.',
      'Je ne sais rien sur ce film.',
      'Eu não sei nada sobre aquele filme.',
      'ฉันไม่รู้อะไรเกี่ยวกับหนังเรื่องนั้นเลย',
      'Aku tidak tahu apa-apa tentang film itu.',
      'Tớ chẳng biết gì về bộ phim đó cả.',
      '私はあの映画について何も知らない。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ까 봐',
    sentence: '친구가 화났을까 봐 계속 연락했어요.',
    trans: L(
      'I kept reaching out because I was worried my friend might be upset.',
      'Seguí contactándolo porque temía que mi amigo estuviera enfadado.',
      "Je n'arrêtais pas de le contacter de peur que mon ami soit fâché.",
      'Fiquei entrando em contato com receio de que meu amigo estivesse bravo.',
      'ฉันติดต่อไปเรื่อยๆ เพราะกลัวว่าเพื่อนจะโกรธ',
      'Aku terus menghubunginya karena khawatir temanku marah.',
      'Tôi cứ liên lạc mãi vì sợ bạn tôi giận.',
      '友達が怒っているかと思って、ずっと連絡しました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ까 봐',
    sentence: '늦을까 봐 택시를 탔어.',
    trans: L(
      "I took a taxi because I was afraid I'd be late.",
      'Tomé un taxi porque tenía miedo de llegar tarde.',
      "J'ai pris un taxi de peur d'être en retard.",
      'Peguei um táxi com medo de me atrasar.',
      'ฉันนั่งแท็กซี่เพราะกลัวว่าจะไปสาย',
      'Aku naik taksi karena takut terlambat.',
      'Tôi đi taxi vì sợ bị trễ.',
      '遅れるかと思ってタクシーに乗ったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-더라도',
    sentence: '아무리 바쁘더라도 가족과 보내는 시간은 꼭 챙기세요.',
    trans: L(
      'No matter how busy you are, be sure to make time for your family.',
      'Por muy ocupado que estés, asegúrate de reservar tiempo para tu familia.',
      'Aussi occupé que tu sois, veille à garder du temps pour ta famille.',
      'Por mais ocupado que você esteja, não deixe de reservar um tempo para a família.',
      'ไม่ว่าจะยุ่งแค่ไหน ก็ขอให้เผื่อเวลาให้ครอบครัวด้วยนะคะ',
      'Sesibuk apa pun, pastikan tetap menyediakan waktu untuk keluarga.',
      'Dù có bận đến mấy cũng nhất định phải dành thời gian cho gia đình nhé.',
      'どんなに忙しくても、家族と過ごす時間は必ず作ってください。',
    ),
    level: 'polite',
  },
  {
    ko: '-더라도',
    sentence: '내일 비가 오더라도 우리는 예정대로 등산을 갈 거야.',
    trans: L(
      "Even if it rains tomorrow, we're going hiking as planned.",
      'Aunque mañana llueva, iremos de excursión a la montaña como estaba previsto.',
      "Même s'il pleut demain, on ira en randonnée comme prévu.",
      'Mesmo que chova amanhã, vamos fazer a trilha como planejado.',
      'ถึงพรุ่งนี้ฝนจะตก พวกเราก็จะไปเดินเขาตามที่นัดไว้',
      'Meskipun besok hujan, kita tetap akan mendaki sesuai rencana.',
      'Dù ngày mai có mưa thì tụi mình vẫn sẽ đi leo núi như đã định.',
      '明日雨が降っても、私たちは予定どおり山登りに行くよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ지도 모르다',
    sentence: '지금 출발 안 하면 기차를 놓칠지도 몰라요.',
    trans: L(
      "If we don't leave now, we might miss the train.",
      'Si no salimos ahora, puede que perdamos el tren.',
      'Si on ne part pas maintenant, on risque de rater le train.',
      'Se a gente não sair agora, pode ser que a gente perca o trem.',
      'ถ้าไม่ออกเดินทางตอนนี้ เราอาจจะพลาดรถไฟก็ได้',
      'Kalau kita tidak berangkat sekarang, kita mungkin akan ketinggalan kereta.',
      'Nếu bây giờ không xuất phát thì có thể chúng ta sẽ lỡ chuyến tàu đấy.',
      '今出発しないと、電車に乗り遅れるかもしれません。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ지도 모르다',
    sentence: '민수는 아직 그 소식을 모를지도 몰라.',
    trans: L(
      'Minsu might not know that news yet.',
      'Puede que Minsu todavía no sepa esa noticia.',
      'Il se peut que Minsu ne soit pas encore au courant de cette nouvelle.',
      'Pode ser que o Minsu ainda não saiba dessa notícia.',
      'มินซูอาจจะยังไม่รู้ข่าวนั้นก็ได้',
      'Mungkin Minsu belum tahu kabar itu.',
      'Có thể Minsu vẫn chưa biết tin đó đâu.',
      'ミンスはまだそのニュースを知らないかもしれない。',
    ),
    level: 'casual',
  },
  {
    ko: '-잖아요',
    sentence: '내일 시험 있잖아요, 오늘은 일찍 자야겠어요.',
    trans: L(
      'We have an exam tomorrow, you know, so I think I should sleep early today.',
      'Mañana tenemos examen, ya sabes, así que hoy debería dormir temprano.',
      "On a un examen demain, tu sais bien, alors je devrais me coucher tôt aujourd'hui.",
      'Amanhã tem prova, você sabe, então hoje eu devia dormir cedo.',
      'พรุ่งนี้มีสอบไงคะ วันนี้เลยน่าจะนอนเร็วหน่อย',
      'Besok kan ada ujian, jadi hari ini sebaiknya aku tidur lebih awal.',
      'Ngày mai có bài thi mà, nên hôm nay chắc mình phải ngủ sớm.',
      '明日試験あるじゃないですか、だから今日は早く寝なきゃ。',
    ),
    level: 'polite',
  },
  {
    ko: '-잖아요',
    sentence: '야, 그거 내가 어제 말했잖아.',
    trans: L(
      'Hey, I told you that yesterday, remember?',
      'Oye, eso ya te lo dije ayer, ¿no te acuerdas?',
      "Hé, je te l'ai dit hier, tu te souviens ?",
      'Ei, eu te falei isso ontem, lembra?',
      'นี่ ฉันบอกเธอไปแล้วเมื่อวานไง จำได้ไหม',
      'Hei, kan kemarin sudah aku bilang itu.',
      'Này, hôm qua tớ nói rồi mà, nhớ không?',
      'ねえ、それ昨日言ったじゃん。',
    ),
    level: 'casual',
  },
  {
    ko: '-더라고요',
    sentence: '오랜만에 고향에 갔더니 동네가 정말 많이 변했더라고요.',
    trans: L(
      'When I went back to my hometown after so long, the neighborhood had really changed a lot.',
      'Cuando volví a mi pueblo después de mucho tiempo, vi que el barrio había cambiado muchísimo.',
      "Quand je suis retourné dans ma ville natale après si longtemps, j'ai constaté que le quartier avait vraiment beaucoup changé.",
      'Quando voltei à minha cidade natal depois de muito tempo, percebi que o bairro tinha mudado bastante.',
      'พอกลับไปบ้านเกิดหลังจากไม่ได้ไปนาน ก็เห็นว่าย่านนั้นเปลี่ยนไปเยอะเลย',
      'Waktu pulang ke kampung halaman setelah sekian lama, ternyata daerahnya sudah banyak berubah.',
      'Lâu rồi mới về quê, tôi thấy khu phố đã thay đổi rất nhiều.',
      '久しぶりに故郷に行ったら、町が本当にすごく変わっていたんですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-더라고요',
    sentence: '어제 새로 산 신발을 신어 봤는데 생각보다 좀 작더라고요.',
    trans: L(
      'I tried on the shoes I bought yesterday, and they turned out to be a bit smaller than I expected.',
      'Me probé los zapatos que compré ayer y resultó que me quedaban un poco pequeños.',
      "J'ai essayé les chaussures que j'ai achetées hier, et elles étaient un peu plus petites que prévu.",
      'Experimentei o tênis que comprei ontem e ele estava um pouco menor do que eu esperava.',
      'เมื่อวานลองใส่รองเท้าที่เพิ่งซื้อมา ปรากฏว่ามันเล็กกว่าที่คิดนิดหน่อยเลย',
      'Kemarin aku coba pakai sepatu yang baru kubeli, ternyata agak lebih kecil dari yang kukira.',
      'Hôm qua tôi thử đôi giày mới mua, hóa ra nó hơi nhỏ hơn tôi tưởng.',
      '昨日買った靴を履いてみたんだけど、思ったよりちょっと小さかったんだよね。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 만큼',
    sentence: '어제는 다리가 후들거릴 만큼 오래 걸었어요.',
    trans: L(
      'Yesterday I walked so long that my legs were trembling.',
      'Ayer caminé tanto que me temblaban las piernas.',
      "Hier, j'ai marché au point que mes jambes tremblaient.",
      'Ontem eu andei tanto que minhas pernas tremiam.',
      'เมื่อวานฉันเดินนานจนขาสั่น',
      'Kemarin aku berjalan begitu lama sampai kakiku gemetar.',
      'Hôm qua tôi đi bộ lâu đến mức chân run lẩy bẩy.',
      '昨日は足が震えるくらい長く歩きました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 만큼',
    sentence: '그 영화는 두 번 봐도 안 질릴 만큼 재미있어.',
    trans: L(
      "That movie is so good you won't get tired of it even after watching it twice.",
      'Esa película es tan buena que no te cansas de ella ni viéndola dos veces.',
      "Ce film est si bon qu'on ne s'en lasse pas même en le regardant deux fois.",
      'Esse filme é tão bom que você não enjoa nem vendo duas vezes.',
      'หนังเรื่องนั้นสนุกขนาดที่ดูสองรอบก็ไม่เบื่อ',
      'Film itu seru sampai ditonton dua kali pun tidak bosan.',
      'Bộ phim đó hay đến mức xem hai lần cũng không chán.',
      'あの映画は二回見ても飽きないくらい面白いよ。',
    ),
    level: 'casual',
  },
  {
    ko: '(이)라도',
    sentence: '시간 없으면 라면이라도 끓여 먹어.',
    trans: L(
      "If you don't have time, at least make some ramen and eat.",
      'Si no tienes tiempo, al menos hazte un ramen y come algo.',
      "Si tu n'as pas le temps, fais-toi au moins un ramen à manger.",
      'Se você não tem tempo, pelo menos faça um miojo e coma.',
      'ถ้าไม่มีเวลา อย่างน้อยก็ต้มรามยอนกินก็ยังดี',
      'Kalau nggak ada waktu, setidaknya masak ramen aja buat dimakan.',
      'Nếu không có thời gian thì ít nhất cũng nấu mì ramen mà ăn đi.',
      '時間がないなら、ラーメンでも作って食べな。',
    ),
    level: 'casual',
  },
  {
    ko: '(이)라도',
    sentence: '잠깐이라도 쉬셨으면 좋겠습니다.',
    trans: L(
      "I hope you'll get some rest, even if just for a moment.",
      'Ojalá pudiera usted descansar, aunque sea un momento.',
      "J'aimerais que vous vous reposiez, ne serait-ce qu'un instant.",
      'Eu gostaria que o senhor descansasse, nem que seja por um instante.',
      'อยากให้ท่านได้พักผ่อนบ้าง แม้แค่ชั่วครู่ก็ยังดี',
      'Saya harap Anda bisa beristirahat, walau hanya sebentar.',
      'Tôi mong ngài được nghỉ ngơi, dù chỉ một lát thôi cũng được.',
      '少しでも休んでいただけたらと思います。',
    ),
    level: 'formal',
  },
  {
    ko: '이/가 되다',
    sentence: '우리 딸이 벌써 대학생이 되었어요.',
    trans: L(
      'Our daughter has already become a college student.',
      'Nuestra hija ya se ha hecho universitaria.',
      "Notre fille est déjà devenue étudiante à l'université.",
      'Nossa filha já virou universitária.',
      'ลูกสาวของเรากลายเป็นนักศึกษามหาวิทยาลัยไปแล้ว',
      'Putri kami sudah menjadi mahasiswa.',
      'Con gái chúng tôi đã trở thành sinh viên đại học rồi.',
      'うちの娘はもう大学生になりました。',
    ),
    level: 'polite',
  },
  {
    ko: '이/가 되다',
    sentence: '열심히 연습하면 너도 좋은 가수가 될 거야.',
    trans: L(
      "If you practice hard, you'll become a good singer too.",
      'Si practicas mucho, tú también llegarás a ser un buen cantante.',
      "Si tu t'entraînes dur, toi aussi tu deviendras un bon chanteur.",
      'Se você praticar bastante, você também vai se tornar um bom cantor.',
      'ถ้าฝึกหนัก ๆ เธอก็จะกลายเป็นนักร้องที่เก่งได้เหมือนกัน',
      'Kalau berlatih keras, kamu juga akan menjadi penyanyi yang hebat.',
      'Nếu chăm chỉ luyện tập thì cậu cũng sẽ trở thành một ca sĩ giỏi.',
      '一生懸命練習すれば、君もいい歌手になるよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 죽겠다',
    sentence: '오늘 날씨가 너무 더워 죽겠어요.',
    trans: L(
      "It's so hot today I'm dying.",
      'Hoy hace tanto calor que me muero.',
      "Il fait tellement chaud aujourd'hui que j'en meurs.",
      'Hoje está tão quente que estou morrendo.',
      'วันนี้อากาศร้อนจนจะแย่แล้ว',
      'Hari ini panas sekali sampai rasanya mau mati.',
      'Hôm nay nóng quá đến chết mất.',
      '今日は暑すぎて死にそうです。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 죽겠다',
    sentence: '할 일이 너무 많아서 힘들어 죽겠다.',
    trans: L(
      "I have so much to do, I'm dying.",
      'Tengo tanto que hacer que me muero.',
      "J'ai tellement de choses à faire que j'en meurs.",
      'Tenho tanta coisa pra fazer que estou morrendo.',
      'มีงานต้องทำเยอะมากจนจะแย่แล้ว',
      'Kerjaan banyak banget sampai rasanya mau mati.',
      'Có quá nhiều việc phải làm, mệt chết đi được.',
      'やることが多すぎて死にそうだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 가지고',
    sentence: '어제 친구를 만나 가지고 늦게까지 수다를 떨었어.',
    trans: L(
      'I met up with a friend yesterday, so we ended up chatting until late.',
      'Ayer quedé con un amigo, así que estuvimos charlando hasta tarde.',
      "Hier j'ai retrouvé un ami, du coup on a papoté jusqu'à tard.",
      'Ontem encontrei um amigo, aí a gente ficou de conversa até tarde.',
      'เมื่อวานเจอเพื่อน เลยนั่งคุยกันจนดึกเลย',
      'Kemarin aku ketemu teman, jadinya kami ngobrol sampai larut.',
      'Hôm qua tôi gặp bạn nên ngồi tám chuyện tới khuya luôn.',
      '昨日友達に会って、それで遅くまでおしゃべりしちゃった。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 가지고',
    sentence: '국이 너무 짜 가지고 물을 좀 더 넣었어요.',
    trans: L(
      'The soup was too salty, so I added a little more water.',
      'La sopa estaba demasiado salada, así que le eché un poco más de agua.',
      "La soupe était trop salée, alors j'ai rajouté un peu d'eau.",
      'A sopa estava salgada demais, então coloquei um pouco mais de água.',
      'ซุปเค็มเกินไป เลยเติมน้ำลงไปอีกหน่อย',
      'Sopnya terlalu asin, jadi saya tambahkan air sedikit lagi.',
      'Canh mặn quá nên tôi cho thêm một chút nước.',
      'スープがしょっぱすぎたので、水を少し足しました。',
    ),
    level: 'polite',
  },
  {
    ko: '-다(가) 말다',
    sentence: '밥을 먹다가 말고 갑자기 밖으로 나가 버렸어요.',
    trans: L(
      'He stopped eating halfway and suddenly went outside.',
      'Dejó de comer a medias y de repente salió afuera.',
      'Il a arrêté de manger en plein milieu et est soudain sorti dehors.',
      'Ele parou de comer no meio e de repente saiu para fora.',
      'เขากินข้าวได้ครึ่งทางก็หยุดแล้วจู่ๆ ก็ออกไปข้างนอก',
      'Dia berhenti makan di tengah jalan dan tiba-tiba keluar.',
      'Anh ấy đang ăn dở thì dừng lại rồi đột nhiên đi ra ngoài.',
      'ご飯を食べかけてやめ、急に外へ出て行ってしまいました。',
    ),
    level: 'polite',
  },
  {
    ko: '-다(가) 말다',
    sentence: '어제 청소를 하다가 말아서 방이 아직 엉망이야.',
    trans: L(
      'I stopped cleaning halfway yesterday, so the room is still a mess.',
      'Ayer dejé la limpieza a medias, así que el cuarto todavía está hecho un desastre.',
      "Hier, j'ai arrêté le ménage à mi-chemin, alors la chambre est encore en désordre.",
      'Ontem parei de limpar no meio, então o quarto ainda está uma bagunça.',
      'เมื่อวานทำความสะอาดได้ครึ่งเดียวก็เลิก ห้องเลยยังรกอยู่เลย',
      'Kemarin aku berhenti bersih-bersih di tengah jalan, jadi kamarnya masih berantakan.',
      'Hôm qua tôi dọn dẹp dở chừng rồi bỏ, nên phòng vẫn còn bừa bộn.',
      '昨日、掃除をしかけてやめたから、部屋がまだぐちゃぐちゃだよ。',
    ),
    level: 'casual',
  },
  // --- Sentence Garden short-sentence pilot: one short (3-5 eojeol), rigid
  // single-order example for the 19 TOPIK-2 grammars that previously had only
  // long (6+ eojeol) examples, so they were unplayable in 문장 정원. Authored +
  // adversarially Korean-verified (grammaticality, single valid order, register,
  // 8-locale fidelity); native (owner's wife) review is the final gate. ---
  {
    ko: '-(으)ㄹ 수 있다/없다',
    sentence: '저는 운전할 수 있어요.',
    trans: L(
      'I can drive.',
      'Yo sé conducir.',
      'Je sais conduire.',
      'Eu sei dirigir.',
      'ฉันขับรถได้',
      'Saya bisa menyetir.',
      'Tôi biết lái xe.',
      '私は運転できます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 필요가 있다/없다',
    sentence: '예약할 필요가 없어요.',
    trans: L(
      "There's no need to make a reservation.",
      'No hace falta reservar.',
      'Pas besoin de réserver.',
      'Não é preciso reservar.',
      'ไม่จำเป็นต้องจอง',
      'Tidak perlu memesan.',
      'Không cần đặt chỗ.',
      '予約する必要はありません。',
    ),
    level: 'polite',
  },
  {
    ko: '-기 전에',
    sentence: '출발하기 전에 전화하세요.',
    trans: L(
      'Call before you leave.',
      'Llame antes de salir.',
      'Appelez avant de partir.',
      'Ligue antes de sair.',
      'โทรก่อนออกเดินทางนะคะ',
      'Telepon sebelum berangkat.',
      'Hãy gọi điện trước khi đi.',
      '出発する前に電話してください。',
    ),
    level: 'polite',
  },
  {
    ko: '-는 동안',
    sentence: '제가 요리하는 동안 전화가 왔어요.',
    trans: L(
      'A phone call came in while I was cooking.',
      'Llegó una llamada mientras yo cocinaba.',
      'Un appel est arrivé pendant que je cuisinais.',
      'Uma ligação chegou enquanto eu cozinhava.',
      'มีโทรศัพท์เข้ามาตอนที่ฉันทำอาหารอยู่',
      'Ada telepon masuk saat saya memasak.',
      'Có cuộc gọi đến trong khi tôi đang nấu ăn.',
      '私が料理している間に電話が来ました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 모양이다',
    sentence: '밖에 비가 오는 모양이에요.',
    trans: L(
      'It seems to be raining outside.',
      'Parece que está lloviendo afuera.',
      "On dirait qu'il pleut dehors.",
      'Parece que está chovendo lá fora.',
      'ดูเหมือนข้างนอกฝนกำลังตก',
      'Sepertinya di luar sedang hujan.',
      'Hình như bên ngoài đang mưa.',
      '外は雨が降っているようです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)면 되다',
    sentence: '여기에 이름을 쓰면 됩니다.',
    trans: L(
      'You just need to write your name here.',
      'Solo tiene que escribir su nombre aquí.',
      "Il suffit d'écrire votre nom ici.",
      'Basta escrever o seu nome aqui.',
      'แค่เขียนชื่อตรงนี้ก็พอครับ',
      'Cukup tulis nama Anda di sini.',
      'Bạn chỉ cần viết tên vào đây là được.',
      'ここに名前を書けばいいです。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)면 안 되다',
    sentence: '여기에서 사진을 찍으면 안 됩니다.',
    trans: L(
      "You're not allowed to take photos here.",
      'No se puede tomar fotos aquí.',
      'Il est interdit de prendre des photos ici.',
      'Não pode tirar fotos aqui.',
      'ที่นี่ห้ามถ่ายรูปครับ',
      'Anda tidak boleh mengambil foto di sini.',
      'Không được chụp ảnh ở đây.',
      'ここで写真を撮ってはいけません。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)려고',
    sentence: '저는 살을 빼려고 운동해.',
    trans: L(
      'I exercise to lose weight.',
      'Hago ejercicio para bajar de peso.',
      'Je fais du sport pour perdre du poids.',
      'Eu faço exercício para perder peso.',
      'ฉันออกกำลังกายเพื่อลดน้ำหนัก',
      'Saya berolahraga untuk menurunkan berat badan.',
      'Tôi tập thể dục để giảm cân.',
      '私は痩せようと運動する。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 보다',
    sentence: '이 옷을 입어 보세요.',
    trans: L(
      'Try on these clothes.',
      'Pruébate esta ropa.',
      'Essayez ce vêtement.',
      'Experimente esta roupa.',
      'ลองใส่เสื้อผ้าชุดนี้ดูสิ',
      'Coba pakai baju ini.',
      'Hãy mặc thử bộ quần áo này.',
      'この服を着てみてください。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)니까',
    sentence: '날씨가 좋으니까 산책하자.',
    trans: L(
      "The weather's nice, so let's take a walk.",
      'Como hace buen tiempo, vamos a pasear.',
      'Il fait beau, alors allons nous promener.',
      'O tempo está bom, então vamos passear.',
      'อากาศดี ไปเดินเล่นกันเถอะ',
      'Cuacanya bagus, jadi ayo jalan-jalan.',
      'Thời tiết đẹp nên đi dạo thôi.',
      '天気がいいから散歩しよう。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는지',
    sentence: '여기가 어디인지 모르겠어요.',
    trans: L(
      "I don't know where this place is.",
      'No sé dónde queda este lugar.',
      "Je ne sais pas où c'est.",
      'Não sei onde fica este lugar.',
      'ฉันไม่รู้ว่าที่นี่คือที่ไหน',
      'Saya tidak tahu ini di mana.',
      'Tôi không biết đây là đâu.',
      'ここがどこなのか分かりません。',
    ),
    level: 'polite',
  },
  {
    ko: '얼마나',
    sentence: '집에서 회사까지 얼마나 걸려?',
    trans: L(
      'How long does it take from home to work?',
      '¿Cuánto se tarda de casa al trabajo?',
      'Combien de temps faut-il de chez toi au travail ?',
      'Quanto tempo leva de casa até o trabalho?',
      'จากบ้านไปที่ทำงานใช้เวลานานแค่ไหน',
      'Dari rumah ke kantor butuh berapa lama?',
      'Từ nhà đến công ty mất bao lâu?',
      '家から会社までどれくらいかかる？',
    ),
    level: 'casual',
  },
  {
    ko: '에 대해(서)',
    sentence: '한국 역사에 대해서 발표하겠습니다.',
    trans: L(
      'I will give a presentation about Korean history.',
      'Voy a hacer una presentación sobre la historia de Corea.',
      "Je vais faire un exposé sur l'histoire de la Corée.",
      'Vou fazer uma apresentação sobre a história da Coreia.',
      'ผมจะนำเสนอเกี่ยวกับประวัติศาสตร์เกาหลีครับ',
      'Saya akan mempresentasikan tentang sejarah Korea.',
      'Tôi sẽ thuyết trình về lịch sử Hàn Quốc.',
      '韓国の歴史について発表します。',
    ),
    level: 'formal',
  },
  {
    ko: '-더라도',
    sentence: '힘들더라도 끝까지 해 보세요.',
    trans: L(
      'Even if it is hard, try to see it through to the end.',
      'Aunque sea difícil, intente terminarlo hasta el final.',
      "Même si c'est dur, essayez d'aller jusqu'au bout.",
      'Mesmo que seja difícil, tente ir até o fim.',
      'ถึงจะลำบาก ก็ลองทำให้จบดูนะคะ',
      'Meskipun sulit, cobalah selesaikan sampai akhir.',
      'Dù có khó khăn, hãy cố làm đến cùng.',
      '大変でも最後までやってみてください。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ지도 모르다',
    sentence: '생각보다 비쌀지도 몰라요.',
    trans: L(
      'It might be more expensive than you think.',
      'Puede que sea más caro de lo que crees.',
      "C'est peut-être plus cher que tu ne le penses.",
      'Pode ser mais caro do que você pensa.',
      'อาจจะแพงกว่าที่คิดก็ได้',
      'Mungkin lebih mahal dari yang kamu kira.',
      'Có thể đắt hơn bạn nghĩ đấy.',
      '思ったより高いかもしれません。',
    ),
    level: 'polite',
  },
  {
    ko: '-더라고요',
    sentence: '날씨가 정말 춥더라고요.',
    trans: L(
      'The weather was really cold.',
      'Hacía muchísimo frío, te digo.',
      'Il faisait vraiment froid, tu sais.',
      'O tempo estava muito frio, viu.',
      'อากาศหนาวมากเลยนะ',
      'Ternyata cuacanya dingin sekali.',
      'Thời tiết lạnh thật đấy.',
      '天気が本当に寒かったんですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 만큼',
    sentence: '배가 터질 만큼 많이 먹었어요.',
    trans: L(
      'I ate so much I felt like I would burst.',
      'Comí tanto que sentí que iba a explotar.',
      "J'ai mangé au point de me sentir prêt à exploser.",
      'Comi tanto que senti que ia explodir.',
      'ฉันกินเยอะจนท้องจะแตก',
      'Saya makan banyak sampai rasanya mau meledak.',
      'Tôi ăn nhiều đến mức tưởng như sắp nổ bụng.',
      'お腹がはち切れるほどたくさん食べました。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 가지고',
    sentence: '늦잠을 자 가지고 지각했어.',
    trans: L(
      'I overslept, so I was late.',
      'Me quedé dormido, así que llegué tarde.',
      "J'ai fait la grasse matinée, du coup j'étais en retard.",
      'Dormi demais, por isso me atrasei.',
      'ฉันตื่นสาย เลยมาสาย',
      'Aku ketiduran, jadinya telat.',
      'Tôi ngủ quên nên đã bị trễ.',
      '寝坊しちゃって遅刻した。',
    ),
    level: 'casual',
  },
  {
    ko: '-다(가) 말다',
    sentence: '편지를 쓰다가 말았어요.',
    trans: L(
      'I started writing a letter but stopped midway.',
      'Empecé a escribir una carta, pero la dejé a medias.',
      "J'ai commencé à écrire une lettre, puis j'ai arrêté en cours de route.",
      'Comecei a escrever uma carta, mas parei no meio.',
      'ฉันเขียนจดหมายค้างไว้ครึ่งทาง',
      'Saya menulis surat tapi berhenti di tengah jalan.',
      'Tôi viết thư dở dang rồi bỏ.',
      '手紙を書きかけてやめました。',
    ),
    level: 'polite',
  },
]
