import type { GrammarExample } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-2 grammar examples (roadmap Step 6 / plan Part B Tier-1). Per-FORM
 * coverage for the two-form TOPIK-2 grammars: each grammar whose `ko` names ≥2
 * distinct surface forms shows ≥1 example per form. `ko` values match
 * grammars-n2.ts verbatim; sentences differ from each grammar's canonical
 * `Grammar.example` (the "above ≠ below" invariant).
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow
 * (grammaticality/naturalness, per-form realization, register-tag accuracy,
 * 8-locale fidelity). Native (Korean wife) review is the documented final gate.
 */
export const TOPIK_2_EXAMPLES: GrammarExample[] = [
  {
    ko: '-(으)ㄴ 후에 / 다음에',
    sentence: '숙제를 끝낸 후에 친구를 만났어요.',
    trans: L(
      'After I finished my homework, I met a friend.',
      'Después de terminar la tarea, quedé con un amigo.',
      "Après avoir fini mes devoirs, j'ai retrouvé un ami.",
      'Depois de terminar a lição de casa, encontrei um amigo.',
      'หลังจากทำการบ้านเสร็จแล้ว ฉันก็ไปเจอเพื่อน',
      'Setelah selesai mengerjakan PR, saya bertemu teman.',
      'Sau khi làm xong bài tập, tôi đã gặp bạn.',
      '宿題を終えた後に友達に会いました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ 후에 / 다음에',
    sentence: '손을 씻은 다음에 과일을 먹었어요.',
    trans: L(
      'After washing my hands, I ate some fruit.',
      'Después de lavarme las manos, comí fruta.',
      "Après m'être lavé les mains, j'ai mangé des fruits.",
      'Depois de lavar as mãos, comi frutas.',
      'หลังจากล้างมือแล้ว ฉันก็กินผลไม้',
      'Setelah mencuci tangan, saya makan buah.',
      'Sau khi rửa tay, tôi đã ăn trái cây.',
      '手を洗った後に果物を食べました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 수 있다/없다',
    sentence: '내일은 시간이 있어서 모임에 갈 수 있어요.',
    trans: L(
      'I have time tomorrow, so I can go to the gathering.',
      'Mañana tengo tiempo, así que puedo ir a la reunión.',
      "Demain j'ai du temps, donc je peux aller à la réunion.",
      'Amanhã eu tenho tempo, então posso ir ao encontro.',
      'พรุ่งนี้ฉันมีเวลา เลยไปงานรวมตัวได้',
      'Besok saya ada waktu, jadi saya bisa pergi ke pertemuan itu.',
      'Ngày mai tôi có thời gian nên tôi có thể đi đến buổi gặp mặt.',
      '明日は時間があるので、集まりに行けます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 수 있다/없다',
    sentence: '다리를 다쳐서 지금은 빨리 걸을 수 없어요.',
    trans: L(
      "I hurt my leg, so I can't walk fast right now.",
      'Me lastimé la pierna, así que ahora no puedo caminar rápido.',
      'Je me suis blessé à la jambe, donc je ne peux pas marcher vite en ce moment.',
      'Eu machuquei a perna, então agora não consigo andar rápido.',
      'ฉันบาดเจ็บที่ขา ตอนนี้เลยเดินเร็วไม่ได้',
      'Saya cedera di kaki, jadi sekarang saya tidak bisa berjalan cepat.',
      'Tôi bị thương ở chân nên bây giờ tôi không thể đi nhanh được.',
      '足をけがしたので、今は速く歩けません。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 필요가 있다/없다',
    sentence: '감기에 걸렸으니까 병원에 갈 필요가 있어요.',
    trans: L(
      "Since you've caught a cold, you need to go to the hospital.",
      'Como te has resfriado, hace falta que vayas al hospital.',
      "Comme tu as attrapé un rhume, il faut que tu ailles à l'hôpital.",
      'Como você pegou um resfriado, é preciso ir ao hospital.',
      'เพราะเป็นหวัด เลยจำเป็นต้องไปโรงพยาบาล',
      'Karena kamu kena flu, kamu perlu pergi ke rumah sakit.',
      'Vì bị cảm rồi nên cần phải đi bệnh viện.',
      '風邪をひいたから、病院に行く必要があります。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 필요가 있다/없다',
    sentence: '이미 다 준비했으니까 더 살 필요가 없어요.',
    trans: L(
      "We've already got everything ready, so there's no need to buy any more.",
      'Ya lo tenemos todo preparado, así que no hace falta comprar más.',
      "On a déjà tout préparé, donc il n'y a pas besoin d'en acheter plus.",
      'Já preparamos tudo, então não é preciso comprar mais.',
      'เตรียมทุกอย่างไว้หมดแล้ว เลยไม่จำเป็นต้องซื้อเพิ่ม',
      'Semuanya sudah disiapkan, jadi tidak perlu membeli lagi.',
      'Đã chuẩn bị hết rồi nên không cần phải mua thêm.',
      'もう全部準備したので、これ以上買う必要がありません。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 나서 / -고 나면',
    sentence: '운동을 하고 나서 샤워를 했어요.',
    trans: L(
      'After I worked out, I took a shower.',
      'Después de hacer ejercicio, me duché.',
      "Après avoir fait du sport, j'ai pris une douche.",
      'Depois de me exercitar, tomei banho.',
      'หลังจากออกกำลังกายเสร็จ ฉันก็อาบน้ำ',
      'Setelah selesai berolahraga, saya mandi.',
      'Sau khi tập thể dục xong, tôi đã đi tắm.',
      '運動をしてから、シャワーを浴びました。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 나서 / -고 나면',
    sentence: '이 책을 다 읽고 나면 마음이 편해질 거예요.',
    trans: L(
      "Once you finish reading this book, you'll feel at ease.",
      'Una vez que termines de leer este libro, te sentirás tranquilo.',
      'Une fois que tu auras fini de lire ce livre, tu te sentiras apaisé.',
      'Depois que você terminar de ler este livro, vai se sentir tranquilo.',
      'พออ่านหนังสือเล่มนี้จบ คุณก็จะรู้สึกสบายใจขึ้น',
      'Setelah selesai membaca buku ini, hatimu akan menjadi tenang.',
      'Một khi đọc xong cuốn sách này, bạn sẽ thấy lòng nhẹ nhõm.',
      'この本を読み終えると、心が楽になりますよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-군요 / -구나',
    sentence: '오늘 날씨가 정말 춥군요.',
    trans: L(
      'Oh, the weather is really cold today.',
      'Vaya, hoy hace mucho frío.',
      "Tiens, il fait vraiment froid aujourd'hui.",
      'Nossa, hoje está mesmo frio.',
      'วันนี้อากาศหนาวจริง ๆ เลยนะ',
      'Wah, hari ini cuacanya dingin sekali ya.',
      'Ồ, hôm nay trời lạnh thật đấy.',
      '今日は本当に寒いですね。',
    ),
    level: 'polite',
  },
  {
    ko: '-군요 / -구나',
    sentence: '너 벌써 다 컸구나.',
    trans: L(
      "Wow, you've already grown up so much.",
      'Vaya, ya has crecido un montón.',
      'Oh, tu as déjà tellement grandi.',
      'Nossa, você já cresceu tanto.',
      'โอ้ เธอโตขึ้นเยอะเลยนะ',
      'Wah, kamu sudah besar sekali ya.',
      'Ồ, cháu đã lớn thế này rồi cơ à.',
      'もうこんなに大きくなったんだね。',
    ),
    level: 'casual',
  },
  {
    ko: '-기 쉽다/어렵다',
    sentence: '겨울에는 길이 미끄러워서 넘어지기 쉬워요.',
    trans: L(
      "In winter the roads are slippery, so it's easy to fall.",
      'En invierno las calles están resbaladizas, así que es fácil caerse.',
      'En hiver, les routes sont glissantes, donc on tombe facilement.',
      'No inverno as ruas ficam escorregadias, então é fácil cair.',
      'ในฤดูหนาวถนนลื่น เลยหกล้มได้ง่าย',
      'Di musim dingin jalanan licin, jadi mudah terpeleset jatuh.',
      'Vào mùa đông đường trơn nên rất dễ bị ngã.',
      '冬は道が滑りやすいので、転びやすいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-기 쉽다/어렵다',
    sentence: '외국어로 농담을 이해하기 어려워요.',
    trans: L(
      "It's hard to understand jokes in a foreign language.",
      'Es difícil entender los chistes en un idioma extranjero.',
      "C'est difficile de comprendre les blagues dans une langue étrangère.",
      'É difícil entender piadas em uma língua estrangeira.',
      'เป็นเรื่องยากที่จะเข้าใจมุกตลกในภาษาต่างประเทศ',
      'Sulit memahami lelucon dalam bahasa asing.',
      'Thật khó để hiểu những câu nói đùa bằng tiếng nước ngoài.',
      '外国語で冗談を理解するのは難しいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고요? / -(이)라고요?',
    sentence: '지금 밖에 비가 온다고요?',
    trans: L(
      "It's raining outside right now, you said?",
      '¿Dices que ahora está lloviendo afuera?',
      "Tu dis qu'il pleut dehors en ce moment ?",
      'Você disse que está chovendo lá fora agora?',
      'บอกว่าตอนนี้ข้างนอกฝนตกเหรอ',
      'Katanya sekarang di luar sedang hujan?',
      'Bạn bảo bây giờ bên ngoài đang mưa à?',
      '今、外で雨が降っていると言いましたか？',
    ),
    level: 'polite',
  },
  {
    ko: '-다고요? / -(이)라고요?',
    sentence: '저분이 새로 오신 선생님이라고요?',
    trans: L(
      'That person is the new teacher who just joined, you said?',
      '¿Dices que esa persona es el nuevo profesor que acaba de llegar?',
      "Tu dis que cette personne est le nouveau professeur qui vient d'arriver ?",
      'Você disse que aquela pessoa é o novo professor que acabou de chegar?',
      'บอกว่าท่านนั้นคือคุณครูคนใหม่ที่เพิ่งมาเหรอ',
      'Katanya orang itu guru baru yang baru datang?',
      'Bạn bảo vị đó là thầy giáo mới vừa đến à?',
      'あの方が新しく来られた先生だと言いましたか？',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 놓다 / -아/어 두다',
    sentence: '창문을 열어 놓았으니까 방이 곧 시원해질 거예요.',
    trans: L(
      "I've opened the window (and left it open), so the room will cool down soon.",
      'Dejé la ventana abierta, así que la habitación se enfriará pronto.',
      "J'ai laissé la fenêtre ouverte, donc la pièce va vite se rafraîchir.",
      'Deixei a janela aberta, então o quarto vai esfriar logo.',
      'เปิดหน้าต่างทิ้งไว้แล้ว เดี๋ยวห้องก็จะเย็นลงเอง',
      'Saya sudah membuka jendela (dan membiarkannya terbuka), jadi kamarnya akan segera sejuk.',
      'Tôi đã mở sẵn cửa sổ rồi, nên phòng sẽ mát ngay thôi.',
      '窓を開けておいたので、部屋がすぐ涼しくなりますよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 놓다 / -아/어 두다',
    sentence: '친구 전화번호를 휴대폰에 저장해 뒀어요.',
    trans: L(
      "I saved my friend's phone number in my phone (and keep it there).",
      'Guardé el número de mi amigo en el móvil (y lo tengo ahí guardado).',
      "J'ai enregistré le numéro de mon ami dans mon téléphone (et je le garde).",
      'Salvei o número do meu amigo no celular (e deixo guardado lá).',
      'บันทึกเบอร์โทรของเพื่อนเก็บไว้ในมือถือแล้ว',
      'Saya sudah menyimpan nomor telepon teman saya di ponsel (dan menyimpannya di sana).',
      'Tôi đã lưu sẵn số điện thoại của bạn vào điện thoại rồi.',
      '友達の電話番号を携帯に保存しておきました。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어야 하다 / 되다',
    sentence: '약을 먹기 전에 밥을 먼저 먹어야 해요.',
    trans: L(
      'You have to eat something first before taking the medicine.',
      'Tienes que comer algo primero antes de tomar la medicina.',
      "Tu dois d'abord manger quelque chose avant de prendre le médicament.",
      'Você tem que comer algo primeiro antes de tomar o remédio.',
      'ต้องกินข้าวก่อนถึงจะกินยาได้',
      'Kamu harus makan dulu sebelum minum obat.',
      'Bạn phải ăn gì đó trước khi uống thuốc.',
      '薬を飲む前に、まずご飯を食べなければなりません。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어야 하다 / 되다',
    sentence: '내일 아침에 일찍 일어나야 돼요.',
    trans: L(
      'I have to get up early tomorrow morning.',
      'Tengo que levantarme temprano mañana por la mañana.',
      'Je dois me lever tôt demain matin.',
      'Tenho que acordar cedo amanhã de manhã.',
      'พรุ่งนี้เช้าฉันต้องตื่นแต่เช้า',
      'Besok pagi saya harus bangun pagi-pagi.',
      'Sáng mai tôi phải dậy sớm.',
      '明日の朝は早く起きなければなりません。',
    ),
    level: 'polite',
  },
  {
    ko: '-처럼 / -같이',
    sentence: '오늘 날씨가 봄처럼 따뜻해요.',
    trans: L(
      'The weather today is warm like spring.',
      'Hoy el clima está cálido como en primavera.',
      "Aujourd'hui, le temps est doux comme au printemps.",
      'Hoje o tempo está quente como na primavera.',
      'วันนี้อากาศอบอุ่นเหมือนฤดูใบไม้ผลิ',
      'Cuaca hari ini hangat seperti musim semi.',
      'Thời tiết hôm nay ấm áp như mùa xuân.',
      '今日は天気が春のように暖かいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-처럼 / -같이',
    sentence: '동생은 토끼같이 빨리 뛰어요.',
    trans: L(
      'My little brother runs fast like a rabbit.',
      'Mi hermano menor corre rápido como un conejo.',
      'Mon petit frère court vite comme un lapin.',
      'Meu irmão mais novo corre rápido como um coelho.',
      'น้องวิ่งเร็วเหมือนกระต่าย',
      'Adik saya berlari cepat seperti kelinci.',
      'Em tôi chạy nhanh như một con thỏ.',
      '弟はウサギのように速く走ります。',
    ),
    level: 'polite',
  },
  {
    ko: '때문에 / 기 때문에',
    sentence: '시험 때문에 요즘 너무 바빠요.',
    trans: L(
      "Because of the exam, I'm really busy these days.",
      'A causa del examen, estos días estoy muy ocupado.',
      "À cause de l'examen, je suis très occupé ces jours-ci.",
      'Por causa da prova, ando muito ocupado esses dias.',
      'เพราะการสอบ ช่วงนี้ฉันยุ่งมากเลย',
      'Karena ujian, akhir-akhir ini saya sangat sibuk.',
      'Vì kỳ thi, dạo này tôi rất bận.',
      '試験のせいで、最近とても忙しいです。',
    ),
    level: 'polite',
  },
  {
    ko: '때문에 / 기 때문에',
    sentence: '내일 일찍 일어나야 하기 때문에 지금 자려고 해요.',
    trans: L(
      "Because I have to get up early tomorrow, I'm going to sleep now.",
      'Como mañana tengo que levantarme temprano, voy a dormir ahora.',
      'Comme je dois me lever tôt demain, je vais dormir maintenant.',
      'Como amanhã tenho que acordar cedo, vou dormir agora.',
      'เพราะพรุ่งนี้ต้องตื่นเช้า ตอนนี้เลยจะเข้านอนแล้ว',
      'Karena besok harus bangun pagi, sekarang saya mau tidur.',
      'Vì ngày mai phải dậy sớm nên bây giờ tôi định đi ngủ.',
      '明日早く起きなければならないので、今から寝ようと思います。',
    ),
    level: 'polite',
  },
  {
    ko: '아무 N(이)나 / 아무 N도',
    sentence: '급하니까 아무 펜이나 주세요.',
    trans: L(
      "I'm in a hurry, so just give me any pen.",
      'Como tengo prisa, deme cualquier bolígrafo.',
      "Je suis pressé, alors donnez-moi n'importe quel stylo.",
      'Estou com pressa, então me dê qualquer caneta.',
      'รีบอยู่ ขอปากกาด้ามไหนก็ได้ค่ะ',
      'Saya buru-buru, jadi berikan saja pulpen apa saja.',
      'Tôi đang vội, nên cho tôi cây bút nào cũng được.',
      '急いでいるので、どのペンでもいいから渡してください。',
    ),
    level: 'polite',
  },
  {
    ko: '아무 N(이)나 / 아무 N도',
    sentence: '주말이라서 가게에 아무 손님도 없었어요.',
    trans: L(
      "Because it was the weekend, there wasn't a single customer in the shop.",
      'Como era fin de semana, no había ningún cliente en la tienda.',
      "Comme c'était le week-end, il n'y avait aucun client dans la boutique.",
      'Como era fim de semana, não havia nenhum cliente na loja.',
      'เพราะเป็นวันหยุดสุดสัปดาห์ ในร้านจึงไม่มีลูกค้าสักคนเลย',
      'Karena akhir pekan, tidak ada satu pelanggan pun di toko.',
      'Vì là cuối tuần nên trong cửa hàng không có một người khách nào.',
      '週末だったので、店にはお客さんが一人もいませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '아직 / 벌써 / 이미',
    sentence: '엄마는 아직 안 주무세요.',
    trans: L(
      "Mom isn't asleep yet.",
      'Mamá todavía no está durmiendo.',
      'Maman ne dort pas encore.',
      'A mamãe ainda não está dormindo.',
      'แม่ยังไม่นอนเลย',
      'Ibu masih belum tidur.',
      'Mẹ vẫn chưa ngủ.',
      'お母さんはまだ寝ていません。',
    ),
    level: 'polite',
  },
  {
    ko: '아직 / 벌써 / 이미',
    sentence: '벌써 12시예요? 시간 정말 빠르네요.',
    trans: L(
      "It's already 12 o'clock? Time really flies.",
      '¿Ya son las 12? El tiempo vuela de verdad.',
      'Il est déjà midi ? Le temps passe vraiment vite.',
      'Já são 12 horas? O tempo voa mesmo.',
      'เที่ยงแล้วเหรอ เวลาผ่านไปเร็วจริง ๆ',
      'Sudah jam 12? Waktu benar-benar cepat berlalu.',
      'Đã 12 giờ rồi à? Thời gian trôi nhanh thật.',
      'もう12時ですか？時間が経つのは本当に早いですね。',
    ),
    level: 'polite',
  },
  {
    ko: '아직 / 벌써 / 이미',
    sentence: '제가 도착했을 때 회의는 이미 끝났어요.',
    trans: L(
      'When I arrived, the meeting had already ended.',
      'Cuando llegué, la reunión ya había terminado.',
      'Quand je suis arrivé, la réunion était déjà terminée.',
      'Quando cheguei, a reunião já tinha terminado.',
      'ตอนที่ฉันมาถึง การประชุมจบไปแล้ว',
      'Ketika saya tiba, rapatnya sudah selesai.',
      'Khi tôi đến thì cuộc họp đã kết thúc rồi.',
      '私が着いたとき、会議はもう終わっていました。',
    ),
    level: 'polite',
  },
]
