import type { GrammarExample } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-3 grammar examples (plan Part B Tier-1, level 3). Per-FORM coverage for
 * the two-form TOPIK-3 grammars: each grammar whose `ko` names ≥2 distinct
 * surface forms shows ≥1 example per form. `ko` values match grammars-n3.ts
 * verbatim; sentences differ from each grammar's canonical `Grammar.example`.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow.
 * Native (Korean wife) review is the documented final gate.
 */
export const TOPIK_3_EXAMPLES: GrammarExample[] = [
  {
    ko: '-(으)ㄴ/는 줄 알다/몰랐다',
    sentence: '불이 꺼져 있어서 아무도 없는 줄 알았어요.',
    trans: L(
      'The lights were off, so I thought nobody was here.',
      'Como las luces estaban apagadas, pensé que no había nadie.',
      "Comme les lumières étaient éteintes, je croyais qu'il n'y avait personne.",
      'As luzes estavam apagadas, então pensei que não tinha ninguém.',
      'ไฟดับอยู่ ฉันก็เลยนึกว่าไม่มีใครอยู่',
      'Lampunya mati, jadi kukira tidak ada orang.',
      'Đèn tắt nên tôi cứ tưởng không có ai ở đây.',
      '電気が消えていたので、誰もいないと思っていました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 줄 알다/몰랐다',
    sentence: '네가 매운 음식을 못 먹는 줄 몰랐어.',
    trans: L(
      "I didn't realize you can't eat spicy food.",
      'No sabía que no podías comer comida picante.',
      'Je ne savais pas que tu ne pouvais pas manger épicé.',
      'Eu não sabia que você não conseguia comer comida picante.',
      'ฉันไม่รู้เลยว่าเธอกินเผ็ดไม่ได้',
      'Aku nggak tahu kalau kamu nggak bisa makan pedas.',
      'Tớ không biết là cậu không ăn được đồ cay.',
      '君が辛い物を食べられないなんて知らなかったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 줄 알다/모르다',
    sentence: '제 동생은 자전거를 탈 줄 알아요.',
    trans: L(
      'My younger brother knows how to ride a bicycle.',
      'Mi hermano menor sabe andar en bicicleta.',
      'Mon petit frère sait faire du vélo.',
      'Meu irmão mais novo sabe andar de bicicleta.',
      'น้องชายของฉันขี่จักรยานเป็น',
      'Adik laki-laki saya bisa naik sepeda.',
      'Em trai tôi biết đi xe đạp.',
      '私の弟は自転車に乗れます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 줄 알다/모르다',
    sentence: '저는 아직 운전할 줄 몰라요.',
    trans: L(
      "I still don't know how to drive.",
      'Todavía no sé conducir.',
      'Je ne sais pas encore conduire.',
      'Eu ainda não sei dirigir.',
      'ฉันยังขับรถไม่เป็น',
      'Saya masih belum bisa menyetir.',
      'Tôi vẫn chưa biết lái xe.',
      '私はまだ運転できません。',
    ),
    level: 'polite',
  },
  {
    ko: '-기 위해(서) / -을/를 위해(서)',
    sentence: '한국어 시험에 합격하기 위해서 매일 단어를 외워요.',
    trans: L(
      'I memorize vocabulary every day in order to pass the Korean exam.',
      'Memorizo vocabulario todos los días para aprobar el examen de coreano.',
      "Je mémorise du vocabulaire chaque jour pour réussir l'examen de coréen.",
      'Memorizo vocabulário todos os dias para passar no exame de coreano.',
      'ฉันท่องศัพท์ทุกวันเพื่อที่จะสอบภาษาเกาหลีให้ผ่าน',
      'Saya menghafal kosakata setiap hari untuk lulus ujian bahasa Korea.',
      'Tôi học thuộc từ vựng mỗi ngày để thi đỗ kỳ thi tiếng Hàn.',
      '韓国語の試験に合格するために毎日単語を覚えています。',
    ),
    level: 'polite',
  },
  {
    ko: '-기 위해(서) / -을/를 위해(서)',
    sentence: '부모님을 위해서 작은 선물을 준비했어요.',
    trans: L(
      'I prepared a small gift for my parents.',
      'Preparé un pequeño regalo para mis padres.',
      "J'ai préparé un petit cadeau pour mes parents.",
      'Preparei um pequeno presente para os meus pais.',
      'ฉันเตรียมของขวัญชิ้นเล็ก ๆ ไว้สำหรับพ่อแม่',
      'Saya menyiapkan hadiah kecil untuk orang tua saya.',
      'Tôi đã chuẩn bị một món quà nhỏ cho bố mẹ.',
      '両親のために小さなプレゼントを用意しました。',
    ),
    level: 'polite',
  },
  {
    ko: '-는다면 / -(이)라면',
    sentence: '복권에 당첨된다면 제일 먼저 부모님께 집을 사 드리고 싶어요.',
    trans: L(
      "If I won the lottery, the first thing I'd want to do is buy my parents a house.",
      'Si me tocara la lotería, lo primero que querría hacer es comprarles una casa a mis padres.',
      "Si je gagnais à la loterie, la première chose que je voudrais faire serait d'acheter une maison à mes parents.",
      'Se eu ganhasse na loteria, a primeira coisa que eu gostaria de fazer seria comprar uma casa para os meus pais.',
      'ถ้าฉันถูกลอตเตอรี่ สิ่งแรกที่อยากทำคือซื้อบ้านให้พ่อแม่',
      'Kalau aku menang lotre, hal pertama yang ingin kulakukan adalah membelikan rumah untuk orang tuaku.',
      'Nếu trúng số, điều đầu tiên tôi muốn làm là mua nhà cho bố mẹ.',
      '宝くじが当たったら、まず最初に両親に家を買ってあげたいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-는다면 / -(이)라면',
    sentence: '제가 사장이라면 직원들에게 휴가를 더 많이 줄 거예요.',
    trans: L(
      "If I were the boss, I'd give the employees a lot more vacation time.",
      'Si yo fuera el jefe, les daría muchas más vacaciones a los empleados.',
      "Si j'étais le patron, je donnerais beaucoup plus de congés aux employés.",
      'Se eu fosse o chefe, daria muito mais férias aos funcionários.',
      'ถ้าฉันเป็นเจ้านาย ฉันจะให้วันหยุดกับพนักงานมากกว่านี้',
      'Kalau aku jadi bos, aku akan memberi karyawan lebih banyak cuti.',
      'Nếu tôi là sếp, tôi sẽ cho nhân viên nhiều ngày nghỉ phép hơn.',
      'もし私が社長なら、社員にもっとたくさん休暇をあげるでしょう。',
    ),
    level: 'polite',
  },
  {
    ko: '-게 되다',
    sentence: '여행을 가려고 했는데 갑자기 일이 생겨서 못 가게 됐어요.',
    trans: L(
      "I was planning to go on a trip, but something suddenly came up, so it turned out I couldn't go.",
      'Pensaba irme de viaje, pero de repente surgió algo y al final no pude ir.',
      "Je comptais partir en voyage, mais quelque chose est arrivé soudainement, alors finalement je n'ai pas pu y aller.",
      'Eu ia viajar, mas de repente surgiu um imprevisto e acabei não podendo ir.',
      'ฉันตั้งใจจะไปเที่ยว แต่จู่ๆ ก็มีธุระเข้ามา เลยกลายเป็นว่าไปไม่ได้',
      'Saya berniat pergi berlibur, tapi tiba-tiba ada urusan, jadi akhirnya tidak bisa pergi.',
      'Tôi định đi du lịch, nhưng đột nhiên có việc nên rốt cuộc lại không đi được.',
      '旅行に行こうとしたのに、急に用事ができて行けなくなりました。',
    ),
    level: 'polite',
  },
  {
    ko: '-게 되다',
    sentence: '처음엔 김치를 싫어했는데 한국에 살다 보니 이제 좋아하게 됐어.',
    trans: L(
      "At first I hated kimchi, but after living in Korea I've come to like it now.",
      'Al principio odiaba el kimchi, pero después de vivir en Corea ahora me ha llegado a gustar.',
      "Au début je détestais le kimchi, mais à force de vivre en Corée, j'ai fini par l'aimer.",
      'No começo eu odiava kimchi, mas depois de morar na Coreia acabei passando a gostar.',
      'ตอนแรกฉันเกลียดกิมจิ แต่พออยู่เกาหลีไปนานๆ ตอนนี้ก็เลยกลายเป็นชอบไปแล้ว',
      'Awalnya aku benci kimchi, tapi setelah tinggal di Korea sekarang jadi suka.',
      'Lúc đầu tớ ghét kimchi, nhưng sống ở Hàn Quốc lâu rồi giờ lại đâm ra thích.',
      '最初はキムチが嫌いだったけど、韓国に住んでいるうちに今は好きになったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어지다',
    sentence: '운동을 시작하고 나서 몸이 건강해졌어요.',
    trans: L(
      'After I started exercising, my body got healthier.',
      'Después de empezar a hacer ejercicio, mi cuerpo se puso más sano.',
      "Depuis que j'ai commencé à faire du sport, mon corps est devenu plus sain.",
      'Depois que comecei a me exercitar, meu corpo ficou mais saudável.',
      'หลังจากเริ่มออกกำลังกาย ร่างกายก็แข็งแรงขึ้น',
      'Setelah mulai berolahraga, tubuh saya menjadi lebih sehat.',
      'Sau khi bắt đầu tập thể dục, cơ thể tôi đã trở nên khỏe hơn.',
      '運動を始めてから、体が健康になりました。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어지다',
    sentence: '요즘 한국어가 점점 재미있어졌어.',
    trans: L(
      'These days Korean has gradually become more fun.',
      'Últimamente el coreano se ha ido volviendo más divertido.',
      'Ces derniers temps, le coréen est devenu de plus en plus amusant.',
      'Ultimamente o coreano foi ficando cada vez mais divertido.',
      'ช่วงนี้ภาษาเกาหลีค่อย ๆ สนุกขึ้นเรื่อย ๆ',
      'Akhir-akhir ini bahasa Korea jadi semakin menyenangkan.',
      'Dạo này tiếng Hàn dần trở nên thú vị hơn.',
      '最近、韓国語がだんだん面白くなってきた。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 있다',
    sentence: '벽에 가족사진이 걸려 있어요.',
    trans: L(
      'A family photo is hanging on the wall.',
      'Hay una foto familiar colgada en la pared.',
      'Une photo de famille est accrochée au mur.',
      'Há uma foto de família pendurada na parede.',
      'มีรูปครอบครัวแขวนอยู่บนผนัง',
      'Ada foto keluarga yang tergantung di dinding.',
      'Có một tấm ảnh gia đình đang treo trên tường.',
      '壁に家族写真がかかっています。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 있다',
    sentence: '할머니는 소파에 앉아 있다.',
    trans: L(
      'Grandmother is sitting on the sofa.',
      'La abuela está sentada en el sofá.',
      'La grand-mère est assise sur le canapé.',
      'A avó está sentada no sofá.',
      'คุณยายนั่งอยู่บนโซฟา',
      'Nenek sedang duduk di sofa.',
      'Bà đang ngồi trên ghế sô-pha.',
      'おばあさんはソファに座っている。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 보이다',
    sentence: '이 옷을 입으니까 훨씬 어려 보여요.',
    trans: L(
      'Wearing these clothes, you look much younger.',
      'Con esta ropa te ves mucho más joven.',
      "Avec ces vêtements, tu as l'air bien plus jeune.",
      'Com essa roupa, você parece bem mais novo.',
      'พอใส่เสื้อผ้าชุดนี้แล้วดูเด็กลงเยอะเลย',
      'Dengan baju ini, kamu kelihatan jauh lebih muda.',
      'Mặc bộ đồ này vào trông trẻ hơn hẳn.',
      'この服を着るとずっと若く見えますよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 보이다',
    sentence: '그 식당 음식이 사진보다 더 맛있어 보인다.',
    trans: L(
      "That restaurant's food looks even more delicious than in the photos.",
      'La comida de ese restaurante se ve aún más rica que en las fotos.',
      "La nourriture de ce restaurant a l'air encore plus appétissante que sur les photos.",
      'A comida daquele restaurante parece ainda mais gostosa do que nas fotos.',
      'อาหารร้านนั้นดูน่ากินกว่าในรูปอีก',
      'Makanan restoran itu kelihatan lebih enak daripada di foto.',
      'Đồ ăn của quán đó trông còn ngon hơn cả trong ảnh.',
      'あの食堂の料理、写真よりもっとおいしそうに見える。',
    ),
    level: 'casual',
  },
  {
    ko: '-기 때문에',
    sentence: '내일 시험이 있기 때문에 오늘은 친구를 못 만나요.',
    trans: L(
      "Because I have an exam tomorrow, I can't meet my friend today.",
      'Como tengo un examen mañana, hoy no puedo ver a mi amigo.',
      "Comme j'ai un examen demain, je ne peux pas voir mon ami aujourd'hui.",
      'Como tenho prova amanhã, hoje não posso encontrar meu amigo.',
      'เพราะพรุ่งนี้มีสอบ วันนี้เลยไปเจอเพื่อนไม่ได้',
      'Karena besok ada ujian, hari ini aku tidak bisa bertemu teman.',
      'Vì ngày mai có bài thi nên hôm nay tôi không thể gặp bạn được.',
      '明日試験があるので、今日は友達に会えません。',
    ),
    level: 'polite',
  },
  {
    ko: '-기 때문에',
    sentence: '길이 많이 막혔기 때문에 회의에 늦었습니다.',
    trans: L(
      'I was late for the meeting because there was a lot of traffic.',
      'Llegué tarde a la reunión porque había mucho tráfico.',
      "J'étais en retard à la réunion parce qu'il y avait beaucoup de circulation.",
      'Cheguei atrasado à reunião porque havia muito trânsito.',
      'เพราะรถติดมาก ผมจึงมาประชุมสาย',
      'Karena jalanan sangat macet, saya terlambat ke rapat.',
      'Vì đường tắc nghẽn nhiều nên tôi đã đến cuộc họp muộn.',
      '道がとても混んでいたので、会議に遅れました。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)면서',
    sentence: '전화하면서 운전하면 너무 위험해요.',
    trans: L(
      "It's really dangerous to drive while talking on the phone.",
      'Es muy peligroso conducir mientras hablas por teléfono.',
      "C'est très dangereux de conduire en téléphonant.",
      'É muito perigoso dirigir enquanto fala ao telefone.',
      'การขับรถไปคุยโทรศัพท์ไปอันตรายมากเลยค่ะ',
      'Menyetir sambil menelepon itu sangat berbahaya.',
      'Vừa lái xe vừa gọi điện thoại thì rất nguy hiểm.',
      '電話をしながら運転するととても危ないですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)면서',
    sentence: '형은 웃으면서 내 어깨를 두드렸다.',
    trans: L(
      'My older brother patted my shoulder while smiling.',
      'Mi hermano mayor me dio una palmada en el hombro mientras sonreía.',
      "Mon grand frère m'a tapoté l'épaule en souriant.",
      'Meu irmão mais velho deu um tapinha no meu ombro enquanto sorria.',
      'พี่ชายตบไหล่ผมไปยิ้มไป',
      'Kakak laki-lakiku menepuk bahuku sambil tersenyum.',
      'Anh trai tôi vừa cười vừa vỗ vai tôi.',
      '兄は笑いながら僕の肩を叩いた。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 수밖에 없다',
    sentence: '물가가 계속 오르니까 외식을 줄일 수밖에 없어요.',
    trans: L(
      'Since prices keep going up, we have no choice but to eat out less.',
      'Como los precios siguen subiendo, no nos queda más remedio que comer fuera menos.',
      "Comme les prix ne cessent d'augmenter, nous n'avons pas d'autre choix que de manger moins souvent au restaurant.",
      'Como os preços continuam subindo, não temos outra opção a não ser comer fora com menos frequência.',
      'เพราะราคาสินค้าขึ้นเรื่อยๆ เราก็เลยจำเป็นต้องลดการกินข้าวนอกบ้านลง',
      'Karena harga terus naik, kami terpaksa mengurangi makan di luar.',
      'Vì giá cả cứ tăng mãi nên chúng tôi đành phải giảm ăn ngoài thôi.',
      '物価がずっと上がっているので、外食を減らすしかありません。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 수밖에 없다',
    sentence: '약속 시간에 늦었는데 차까지 막혀서 정말 미안하다고 할 수밖에 없었어.',
    trans: L(
      'I was late for our meet-up and got stuck in traffic on top of that, so I really had no choice but to say sorry.',
      'Llegué tarde a la cita y encima había atasco, así que de verdad no me quedó más remedio que pedir perdón.',
      "J'étais en retard au rendez-vous et en plus il y avait des embouteillages, alors je n'ai vraiment eu d'autre choix que de m'excuser.",
      'Cheguei atrasado ao nosso encontro e ainda peguei trânsito, então realmente não tive escolha a não ser pedir desculpas.',
      'ฉันมาสายตามนัด แถมรถยังติดอีก เลยจำเป็นต้องขอโทษจริงๆ',
      'Aku terlambat dari janji ketemuan, ditambah lagi macet, jadi mau tidak mau aku harus minta maaf.',
      'Tớ đã trễ hẹn rồi lại còn kẹt xe nữa, nên thật sự chỉ còn cách xin lỗi thôi.',
      '約束の時間に遅れた上に渋滞までして、本当にごめんと言うしかなかったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '에 따라(서)',
    sentence: '사람마다 생각이 다르니까 상황에 따라서 결정하는 게 좋아.',
    trans: L(
      "Since everyone thinks differently, it's better to decide according to the situation.",
      'Como cada persona piensa distinto, es mejor decidir según la situación.',
      'Comme chacun pense différemment, il vaut mieux décider selon la situation.',
      'Como cada pessoa pensa diferente, é melhor decidir conforme a situação.',
      'เพราะแต่ละคนคิดไม่เหมือนกัน ตัดสินใจตามสถานการณ์จะดีกว่า',
      'Karena setiap orang berpikir berbeda, lebih baik memutuskan sesuai situasi.',
      'Vì mỗi người nghĩ khác nhau, nên quyết định tùy theo tình huống thì tốt hơn.',
      '人それぞれ考えが違うから、状況によって決めたほうがいいよ。',
    ),
    level: 'casual',
  },
  {
    ko: '에 따라(서)',
    sentence: '이번 정책에 따라 내년부터 세금이 조금 오를 예정입니다.',
    trans: L(
      'In accordance with this policy, taxes are scheduled to rise slightly starting next year.',
      'De acuerdo con esta política, los impuestos subirán ligeramente a partir del próximo año.',
      "Conformément à cette politique, les impôts vont légèrement augmenter à partir de l'année prochaine.",
      'De acordo com esta política, os impostos vão subir um pouco a partir do próximo ano.',
      'ตามนโยบายนี้ ภาษีจะปรับขึ้นเล็กน้อยตั้งแต่ปีหน้าเป็นต้นไป',
      'Sesuai dengan kebijakan ini, pajak akan sedikit naik mulai tahun depan.',
      'Theo chính sách lần này, thuế dự kiến sẽ tăng nhẹ kể từ năm sau.',
      '今回の政策に従って、来年から税金が少し上がる予定です。',
    ),
    level: 'formal',
  },
  {
    ko: '에 비해(서)',
    sentence: '이 식당은 가격에 비해 양이 정말 많아요.',
    trans: L(
      'Compared to the price, this restaurant gives you really generous portions.',
      'En comparación con el precio, este restaurante sirve porciones muy generosas.',
      'Par rapport au prix, ce restaurant sert des portions vraiment généreuses.',
      'Em comparação com o preço, este restaurante serve porções bem generosas.',
      'เมื่อเทียบกับราคาแล้ว ร้านอาหารนี้ให้ปริมาณเยอะมากจริง ๆ',
      'Dibandingkan dengan harganya, restoran ini memberi porsi yang benar-benar banyak.',
      'So với giá tiền thì nhà hàng này cho phần ăn nhiều thật sự.',
      '値段の割に、この食堂は量が本当に多いです。',
    ),
    level: 'polite',
  },
  {
    ko: '에 비해(서)',
    sentence: '형은 나에 비해서 키가 훨씬 커.',
    trans: L(
      'Compared to me, my older brother is much taller.',
      'En comparación conmigo, mi hermano mayor es mucho más alto.',
      'Par rapport à moi, mon grand frère est bien plus grand.',
      'Em comparação comigo, meu irmão mais velho é bem mais alto.',
      'เมื่อเทียบกับฉันแล้ว พี่ชายสูงกว่ามากเลย',
      'Dibandingkan denganku, kakak laki-lakiku jauh lebih tinggi.',
      'So với mình thì anh trai cao hơn nhiều.',
      '僕に比べて、兄は背がずっと高い。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 것 같다',
    sentence: '이 영화 정말 재미있을 것 같아.',
    trans: L(
      'I think this movie is going to be really fun.',
      'Creo que esta película va a ser muy divertida.',
      'Je pense que ce film va être vraiment amusant.',
      'Acho que esse filme vai ser muito divertido.',
      'ฉันว่าหนังเรื่องนี้น่าจะสนุกมากเลย',
      'Sepertinya film ini bakal seru sekali.',
      'Mình nghĩ bộ phim này sẽ rất hay.',
      'この映画、すごく面白そう。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 것 같다',
    sentence: '길이 많이 막혀서 약속에 좀 늦을 것 같습니다.',
    trans: L(
      "The traffic is really bad, so I think I'll be a little late for our appointment.",
      'Hay mucho tráfico, así que creo que llegaré un poco tarde a la cita.',
      'Il y a beaucoup de circulation, donc je pense que je serai un peu en retard au rendez-vous.',
      'O trânsito está muito ruim, então acho que vou me atrasar um pouco para o compromisso.',
      'รถติดมากเลยครับ ผมว่าผมน่าจะไปสายนิดหน่อยตามนัด',
      'Jalanan macet sekali, jadi sepertinya saya akan sedikit terlambat untuk janji kita.',
      'Đường kẹt xe nhiều quá nên chắc là tôi sẽ đến trễ hẹn một chút.',
      '道がすごく混んでいるので、約束に少し遅れそうです。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는 것처럼',
    sentence: '그 사람은 모든 걸 다 아는 것처럼 말해요.',
    trans: L(
      'He talks as if he knows everything.',
      'Esa persona habla como si lo supiera todo.',
      'Cette personne parle comme si elle savait tout.',
      'Essa pessoa fala como se soubesse tudo.',
      'คนนั้นพูดราวกับว่ารู้ทุกอย่าง',
      'Orang itu bicara seolah-olah tahu segalanya.',
      'Người đó nói chuyện như thể biết hết mọi thứ.',
      'あの人は何でも知っているかのように話します。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 것처럼',
    sentence: '동생이 자기가 그린 것처럼 내 그림을 자랑했어.',
    trans: L(
      "My little brother showed off my drawing as if he'd drawn it himself.",
      'Mi hermano menor presumió de mi dibujo como si lo hubiera dibujado él.',
      "Mon petit frère a frimé avec mon dessin comme s'il l'avait fait lui-même.",
      'Meu irmão mais novo se gabou do meu desenho como se ele mesmo o tivesse feito.',
      'น้องชายอวดรูปวาดของฉันราวกับว่าเขาเป็นคนวาดเอง',
      'Adikku memamerkan gambarku seolah-olah dia yang menggambarnya sendiri.',
      'Em trai tôi khoe bức tranh của tôi như thể chính nó đã vẽ vậy.',
      '弟が自分で描いたかのように私の絵を自慢した。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)면 좋겠다',
    sentence: '이번 시험에 꼭 합격하면 좋겠어요.',
    trans: L(
      'I really hope I pass this exam.',
      'Ojalá apruebe este examen sin falta.',
      "J'espère vraiment réussir cet examen.",
      'Tomara que eu passe nesta prova de qualquer jeito.',
      'หวังว่าจะสอบครั้งนี้ผ่านให้ได้',
      'Semoga aku benar-benar lulus ujian ini.',
      'Mình mong sao lần này nhất định thi đậu.',
      '今回の試験に絶対に受かればいいなと思います。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)면 좋겠다',
    sentence: '네가 우리 집에 자주 놀러 오면 좋겠어.',
    trans: L(
      "I wish you'd come over to hang out at our place more often.",
      'Ojalá vinieras a casa a pasar el rato más seguido.',
      "J'aimerais que tu viennes traîner chez nous plus souvent.",
      'Eu queria que você viesse mais vezes lá em casa pra gente curtir.',
      'อยากให้เธอมาเที่ยวที่บ้านเราบ่อย ๆ จัง',
      'Aku harap kamu sering-sering main ke rumahku.',
      'Mình ước gì cậu hay sang nhà mình chơi hơn.',
      'あなたがうちにもっと頻繁に遊びに来てくれたらいいな。',
    ),
    level: 'casual',
  },
  {
    ko: '-기 마련이다',
    sentence: '노력하면 언젠가는 성공하기 마련입니다.',
    trans: L(
      "If you work hard, you're bound to succeed someday.",
      'Si te esfuerzas, tarde o temprano es natural que llegues a tener éxito.',
      "Si l'on fait des efforts, on finit forcément par réussir un jour.",
      'Se você se esforçar, é natural que um dia acabe tendo sucesso.',
      'ถ้าพยายาม สักวันก็ย่อมประสบความสำเร็จเป็นเรื่องธรรมดา',
      'Kalau berusaha, suatu saat pasti akan berhasil, itu sudah biasa.',
      'Nếu nỗ lực thì sớm muộn gì cũng sẽ thành công, đó là chuyện thường.',
      '努力すれば、いつかは成功するものです。',
    ),
    level: 'formal',
  },
  {
    ko: '-기 마련이다',
    sentence: '겨울이 지나면 봄이 오기 마련이야.',
    trans: L(
      'Once winter passes, spring is bound to come.',
      'Cuando pasa el invierno, es natural que llegue la primavera.',
      "Une fois l'hiver passé, le printemps arrive forcément.",
      'Depois que o inverno passa, é natural que a primavera chegue.',
      'พอฤดูหนาวผ่านไป ฤดูใบไม้ผลิก็ย่อมมาถึงเป็นเรื่องธรรมดา',
      'Setelah musim dingin berlalu, musim semi pasti datang, itu sudah pasti.',
      'Mùa đông qua đi thì mùa xuân ắt sẽ đến thôi.',
      '冬が過ぎれば、春が来るものだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-기로 하다',
    sentence: '우리는 다음 달부터 매일 아침에 운동하기로 했어요.',
    trans: L(
      'We decided to exercise every morning starting next month.',
      'Decidimos hacer ejercicio cada mañana a partir del próximo mes.',
      "Nous avons décidé de faire de l'exercice tous les matins à partir du mois prochain.",
      'Decidimos nos exercitar toda manhã a partir do próximo mês.',
      'เราตัดสินใจว่าจะออกกำลังกายทุกเช้าตั้งแต่เดือนหน้าเป็นต้นไป',
      'Kami memutuskan untuk berolahraga setiap pagi mulai bulan depan.',
      'Chúng tôi đã quyết định sẽ tập thể dục mỗi sáng kể từ tháng sau.',
      '私たちは来月から毎朝運動することにしました。',
    ),
    level: 'polite',
  },
  {
    ko: '-기로 하다',
    sentence: '건강을 위해서 이제부터 담배를 끊기로 했어.',
    trans: L(
      "For my health, I've decided to quit smoking from now on.",
      'Por mi salud, he decidido dejar de fumar a partir de ahora.',
      "Pour ma santé, j'ai décidé d'arrêter de fumer à partir de maintenant.",
      'Pela minha saúde, decidi parar de fumar de agora em diante.',
      'เพื่อสุขภาพ ฉันตัดสินใจว่าจะเลิกบุหรี่ตั้งแต่นี้เป็นต้นไป',
      'Demi kesehatan, mulai sekarang aku memutuskan untuk berhenti merokok.',
      'Vì sức khỏe, từ giờ mình đã quyết định sẽ bỏ thuốc lá.',
      '健康のために、これからタバコをやめることにした。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 편이다',
    sentence: '우리 형은 말이 별로 없고 조용한 편이에요.',
    trans: L(
      "My older brother doesn't talk much and is rather quiet.",
      'Mi hermano mayor no habla mucho y es más bien callado.',
      'Mon grand frère ne parle pas beaucoup et est plutôt silencieux.',
      'Meu irmão mais velho não fala muito e é mais para o quieto.',
      'พี่ชายของฉันพูดไม่ค่อยมากและค่อนข้างเงียบ',
      'Kakak laki-lakiku tidak banyak bicara dan cenderung pendiam.',
      'Anh trai mình ít nói và khá là trầm tính.',
      'うちの兄はあまり喋らなくて、どちらかというと無口なほうです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 편이다',
    sentence: '나는 약속 시간보다 좀 일찍 도착하는 편이야.',
    trans: L(
      'I tend to arrive a little early for appointments.',
      'Yo suelo llegar un poco antes de la hora acordada.',
      "J'ai plutôt tendance à arriver un peu en avance aux rendez-vous.",
      'Eu costumo chegar um pouco antes do horário combinado.',
      'ฉันมักจะมาถึงก่อนเวลานัดสักหน่อย',
      'Aku cenderung datang sedikit lebih awal dari waktu janji.',
      'Mình thường đến sớm hơn giờ hẹn một chút.',
      '私は約束の時間より少し早めに着くほうだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-도록',
    sentence: '감기에 걸리지 않도록 따뜻하게 입으세요.',
    trans: L(
      "Dress warmly so you don't catch a cold.",
      'Abrígate bien para que no te resfríes.',
      'Habille-toi chaudement pour ne pas attraper froid.',
      'Vista-se com agasalho para não pegar um resfriado.',
      'แต่งตัวให้อบอุ่นเพื่อไม่ให้เป็นหวัดนะ',
      'Pakai baju yang hangat supaya tidak masuk angin.',
      'Hãy mặc ấm để khỏi bị cảm nhé.',
      '風邪をひかないように暖かくしてください。',
    ),
    level: 'polite',
  },
  {
    ko: '-도록',
    sentence: '내일 늦지 않도록 알람을 다섯 개나 맞춰 놨어.',
    trans: L(
      "I set five alarms so I won't be late tomorrow.",
      'Puse cinco alarmas para no llegar tarde mañana.',
      "J'ai réglé cinq alarmes pour ne pas être en retard demain.",
      'Coloquei cinco alarmes para não me atrasar amanhã.',
      'ตั้งนาฬิกาปลุกไว้ตั้งห้าอันเลย จะได้ไม่สายพรุ่งนี้',
      'Aku pasang lima alarm biar besok tidak terlambat.',
      'Tớ đặt tận năm cái báo thức để mai khỏi bị muộn.',
      '明日遅れないように、目覚ましを五つもセットしておいたよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-자마자',
    sentence: '알람이 울리자마자 바로 일어났어요.',
    trans: L(
      'As soon as the alarm went off, I got up right away.',
      'En cuanto sonó la alarma, me levanté enseguida.',
      "Dès que l'alarme a sonné, je me suis levé tout de suite.",
      'Assim que o alarme tocou, eu me levantei na hora.',
      'พอนาฬิกาปลุกดังปุ๊บ ฉันก็ลุกขึ้นทันทีเลย',
      'Begitu alarm berbunyi, aku langsung bangun.',
      'Vừa nghe chuông báo thức reo là tôi dậy ngay.',
      'アラームが鳴るとすぐに起きました。',
    ),
    level: 'polite',
  },
  {
    ko: '-자마자',
    sentence: '소식을 듣자마자 너한테 전화했어.',
    trans: L(
      'As soon as I heard the news, I called you.',
      'En cuanto me enteré de la noticia, te llamé.',
      "Dès que j'ai appris la nouvelle, je t'ai appelé.",
      'Assim que soube da notícia, te liguei.',
      'พอได้ยินข่าวปุ๊บ ฉันก็โทรหาเธอเลย',
      'Begitu mendengar kabarnya, aku langsung meneleponmu.',
      'Vừa nghe tin là tớ gọi cho cậu ngay.',
      '知らせを聞くとすぐに君に電話したよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ 지',
    sentence: '이 동네로 이사 온 지 벌써 석 달이 지났어요.',
    trans: L(
      "It's already been three months since I moved to this neighborhood.",
      'Ya han pasado tres meses desde que me mudé a este barrio.',
      "Cela fait déjà trois mois que j'ai emménagé dans ce quartier.",
      'Já se passaram três meses desde que me mudei para este bairro.',
      'ผ่านมาสามเดือนแล้วตั้งแต่ที่ฉันย้ายมาอยู่ย่านนี้',
      'Sudah tiga bulan berlalu sejak aku pindah ke lingkungan ini.',
      'Đã ba tháng trôi qua kể từ khi tôi chuyển đến khu phố này rồi.',
      'この町に引っ越してきてもう三ヶ月が過ぎました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ 지',
    sentence: '우리 강아지가 죽은 지 일 년이 다 돼 간다.',
    trans: L(
      "It's been almost a year since our dog died.",
      'Ya va a hacer casi un año desde que murió nuestro perro.',
      'Ça fait bientôt un an que notre chien est mort.',
      'Já vai fazer quase um ano desde que nosso cachorro morreu.',
      'ใกล้จะครบหนึ่งปีแล้วตั้งแต่ที่หมาของเราตาย',
      'Sudah hampir setahun sejak anjing kami mati.',
      'Sắp tròn một năm kể từ khi con chó của nhà mình chết rồi.',
      'うちの犬が死んでからもうすぐ一年になる。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어도',
    sentence: '아무리 바빠도 밥은 꼭 챙겨 먹어.',
    trans: L(
      'No matter how busy you are, make sure you eat.',
      'No importa lo ocupado que estés, asegúrate de comer.',
      "Peu importe à quel point tu es occupé, n'oublie pas de manger.",
      'Não importa o quão ocupado você esteja, não deixe de comer.',
      'ไม่ว่าจะยุ่งแค่ไหนก็ตาม อย่าลืมกินข้าวด้วยนะ',
      'Sesibuk apa pun kamu, jangan lupa makan ya.',
      'Dù bận đến mấy thì cũng phải nhớ ăn cơm nhé.',
      'どんなに忙しくても、ご飯はちゃんと食べてね。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어도',
    sentence: '값이 비싸도 품질이 좋으면 삽니다.',
    trans: L(
      "Even if the price is high, I'll buy it as long as the quality is good.",
      'Aunque el precio sea alto, lo compro si la calidad es buena.',
      "Même si le prix est élevé, je l'achète si la qualité est bonne.",
      'Mesmo que o preço seja alto, eu compro se a qualidade for boa.',
      'ถึงราคาจะแพง แต่ถ้าคุณภาพดีก็จะซื้อครับ',
      'Meskipun harganya mahal, saya tetap membelinya kalau kualitasnya bagus.',
      'Dù giá có đắt, nếu chất lượng tốt thì tôi vẫn mua.',
      '値段が高くても、品質が良ければ買います。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는데도',
    sentence: '약을 먹었는데도 아직 머리가 아파요.',
    trans: L(
      'Even though I took medicine, my head still hurts.',
      'Aunque me tomé la medicina, todavía me duele la cabeza.',
      "Bien que j'aie pris un médicament, j'ai encore mal à la tête.",
      'Mesmo tendo tomado o remédio, minha cabeça ainda dói.',
      'กินยาไปแล้วก็ยังปวดหัวอยู่เลย',
      'Padahal sudah minum obat, kepala masih sakit.',
      'Dù đã uống thuốc rồi mà đầu vẫn còn đau.',
      '薬を飲んだのに、まだ頭が痛いです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는데도',
    sentence: '주말인데도 회사에 가야 해.',
    trans: L(
      "Even though it's the weekend, I have to go to work.",
      'Aunque es fin de semana, tengo que ir al trabajo.',
      'Bien que ce soit le week-end, je dois aller au travail.',
      'Mesmo sendo fim de semana, tenho que ir ao trabalho.',
      'ทั้งที่เป็นวันหยุดสุดสัปดาห์ก็ยังต้องไปทำงาน',
      'Padahal akhir pekan, tapi tetap harus ke kantor.',
      'Dù là cuối tuần nhưng vẫn phải đi làm.',
      '週末なのに、会社に行かなきゃ。',
    ),
    level: 'casual',
  },
  {
    ko: '밖에 + neg',
    sentence: '오늘은 너무 바빠서 한 시간밖에 못 잤어요.',
    trans: L(
      'I was so busy today that I only slept one hour.',
      'Hoy estaba tan ocupado que solo dormí una hora.',
      "J'étais tellement occupé aujourd'hui que je n'ai dormi qu'une heure.",
      'Hoje eu estava tão ocupado que só dormi uma hora.',
      'วันนี้ยุ่งมากจนนอนได้แค่ชั่วโมงเดียว',
      'Hari ini saya sangat sibuk sampai hanya bisa tidur satu jam.',
      'Hôm nay tôi bận quá nên chỉ ngủ được một tiếng thôi.',
      '今日は忙しすぎて一時間しか寝られませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '밖에 + neg',
    sentence: '냉장고에 우유밖에 없네.',
    trans: L(
      "There's nothing but milk in the fridge.",
      'En el refri no hay más que leche.',
      "Il n'y a que du lait dans le frigo.",
      'Na geladeira só tem leite.',
      'ในตู้เย็นมีแค่นมเท่านั้นเอง',
      'Di kulkas cuma ada susu.',
      'Trong tủ lạnh chỉ có mỗi sữa thôi.',
      '冷蔵庫に牛乳しかないね。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)려다가',
    sentence: '버스를 타려다가 시간이 없어서 택시를 탔어요.',
    trans: L(
      'I was going to take the bus, but I had no time so I took a taxi.',
      'Iba a tomar el autobús, pero no tenía tiempo así que tomé un taxi.',
      "J'allais prendre le bus, mais je n'avais pas le temps alors j'ai pris un taxi.",
      'Eu ia pegar o ônibus, mas não tinha tempo, então peguei um táxi.',
      'ตอนแรกจะขึ้นรถเมล์ แต่ไม่มีเวลาเลยนั่งแท็กซี่ไปแทน',
      'Tadinya mau naik bus, tapi tidak ada waktu jadi naik taksi.',
      'Tôi định đi xe buýt nhưng không có thời gian nên đã bắt taxi.',
      'バスに乗ろうとしたけど、時間がなくてタクシーに乗りました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)려다가',
    sentence: '케이크를 직접 만들려다가 너무 어려워서 그냥 사 왔어.',
    trans: L(
      'I tried to make the cake myself, but it was too hard so I just bought one.',
      'Iba a hacer el pastel yo mismo, pero era muy difícil así que mejor lo compré.',
      "J'allais faire le gâteau moi-même, mais c'était trop difficile alors je l'ai simplement acheté.",
      'Eu ia fazer o bolo eu mesmo, mas era difícil demais, então só comprei.',
      'ตอนแรกจะทำเค้กเอง แต่มันยากเกินไปเลยซื้อมาแทน',
      'Tadinya mau bikin kue sendiri, tapi terlalu susah jadi beli aja.',
      'Tôi định tự làm bánh nhưng khó quá nên đành mua luôn.',
      'ケーキを自分で作ろうとしたけど、難しすぎてただ買ってきた。',
    ),
    level: 'casual',
  },
  {
    ko: '-다 보면',
    sentence: '매일 일기를 쓰다 보면 글솜씨가 좋아져요.',
    trans: L(
      'If you keep writing in a diary every day, your writing skills get better.',
      'Si escribes un diario todos los días, tu manera de escribir va mejorando.',
      "À force d'écrire un journal tous les jours, on finit par mieux écrire.",
      'Se você continuar escrevendo um diário todos os dias, sua escrita vai melhorando.',
      'ถ้าเขียนไดอารี่ทุกวันไปเรื่อย ๆ ฝีมือการเขียนก็จะดีขึ้นเอง',
      'Kalau terus menulis diari setiap hari, kemampuan menulismu akan membaik.',
      'Cứ viết nhật ký mỗi ngày thì khả năng viết sẽ tốt lên.',
      '毎日日記を書いていると、文章力が良くなりますよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-다 보면',
    sentence: '서울에 살다 보면 지하철이 편해질 거야.',
    trans: L(
      'If you keep living in Seoul, the subway will start feeling convenient.',
      'Si vives en Seúl un tiempo, el metro acabará pareciéndote cómodo.',
      'À force de vivre à Séoul, le métro finira par te sembler pratique.',
      'Se você for morando em Seul, o metrô vai acabar ficando prático pra você.',
      'ถ้าอยู่โซลไปเรื่อย ๆ เดี๋ยวรถไฟใต้ดินก็จะสะดวกขึ้นเอง',
      'Kalau tinggal di Seoul lama-lama, kereta bawah tanah akan terasa nyaman kok.',
      'Cứ sống ở Seoul một thời gian thì tàu điện ngầm sẽ thành tiện thôi.',
      'ソウルに住んでいると、地下鉄が便利になるよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-다 보니',
    sentence: '매일 지하철로 출퇴근하다 보니 책 읽는 습관이 생겼어요.',
    trans: L(
      "Since I commute by subway every day, I've ended up developing a habit of reading books.",
      'Como voy y vuelvo del trabajo en metro todos los días, acabé adquiriendo el hábito de leer libros.',
      "À force de faire les trajets domicile-travail en métro chaque jour, j'ai fini par prendre l'habitude de lire des livres.",
      'De tanto ir e voltar do trabalho de metrô todo dia, acabei criando o hábito de ler livros.',
      'พอนั่งรถไฟใต้ดินไปกลับที่ทำงานทุกวัน ก็เลยติดนิสัยอ่านหนังสือขึ้นมา',
      'Karena setiap hari pulang-pergi kerja naik kereta bawah tanah, lama-lama jadi punya kebiasaan membaca buku.',
      'Vì ngày nào cũng đi làm bằng tàu điện ngầm nên dần dần tôi đã hình thành thói quen đọc sách.',
      '毎日地下鉄で通勤していたら、本を読む習慣がつきました。',
    ),
    level: 'polite',
  },
  {
    ko: '-다 보니',
    sentence: '혼자 살다 보니 요리 실력이 많이 늘었어.',
    trans: L(
      'Living on my own, my cooking skills have improved a lot.',
      'Como vivo solo, mis habilidades para cocinar han mejorado mucho.',
      'À force de vivre seul, mes talents de cuisinier se sont beaucoup améliorés.',
      'De tanto morar sozinho, minhas habilidades na cozinha melhoraram muito.',
      'พออยู่คนเดียว ฝีมือทำอาหารก็เลยพัฒนาขึ้นเยอะเลย',
      'Karena tinggal sendirian, kemampuan memasakku jadi meningkat banyak.',
      'Sống một mình riết rồi tay nghề nấu ăn của mình lên nhiều lắm.',
      '一人暮らしをしていたら、料理の腕がずいぶん上がったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 대다',
    sentence: '옆집 개가 밤새 짖어 대서 한숨도 못 잤어요.',
    trans: L(
      "The neighbor's dog kept barking all night, so I couldn't sleep a wink.",
      'El perro del vecino no paró de ladrar en toda la noche, así que no pegué ojo.',
      "Le chien du voisin n'a pas arrêté d'aboyer toute la nuit, alors je n'ai pas fermé l'œil.",
      'O cachorro do vizinho ficou latindo a noite toda, então não preguei o olho.',
      'หมาบ้านข้างๆ เห่าไม่หยุดทั้งคืน เลยนอนไม่หลับเลยสักงีบ',
      'Anjing tetangga menggonggong terus semalaman, jadi aku tidak bisa tidur sama sekali.',
      'Con chó nhà hàng xóm cứ sủa mãi suốt đêm nên tôi không chợp mắt được chút nào.',
      '隣の家の犬が一晩中吠えまくって、一睡もできませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 대다',
    sentence: '그만 좀 떠들어 대, 정신 사나워 죽겠어!',
    trans: L(
      "Quit yammering already — you're driving me up the wall!",
      '¡Deja ya de parlotear, me estás volviendo loco!',
      'Arrête un peu de jacasser, tu me rends dingue !',
      'Para de tagarelar, você está me deixando louco!',
      'เลิกพูดพล่ามได้แล้ว รำคาญจะแย่อยู่แล้ว!',
      'Berhenti dong mengoceh terus, aku jadi pusing setengah mati!',
      'Thôi đừng có lảm nhảm mãi nữa, làm tao điên cả đầu!',
      'もうちょっと騒ぎまくるのやめてよ、うるさくて気が散ってしょうがない！',
    ),
    level: 'casual',
  },
  {
    ko: '-고 말다',
    sentence: '아끼던 컵을 떨어뜨려서 깨고 말았어요.',
    trans: L(
      'I dropped the cup I treasured and ended up breaking it.',
      'Se me cayó la taza que tanto cuidaba y terminé rompiéndola.',
      "J'ai fait tomber la tasse à laquelle je tenais et j'ai fini par la casser.",
      'Deixei cair a xícara que eu tanto prezava e acabei quebrando.',
      'ทำแก้วที่รักหวงหล่นจนแตกไปในที่สุด',
      'Aku menjatuhkan cangkir kesayanganku dan akhirnya memecahkannya.',
      'Tôi làm rơi cái cốc mình rất quý và cuối cùng đã làm vỡ mất.',
      '大事にしていたコップを落として、割ってしまいました。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 말다',
    sentence: '다이어트 중인데 결국 케이크를 다 먹고 말았어.',
    trans: L(
      "I'm on a diet, but in the end I went and ate the whole cake.",
      'Estoy a dieta, pero al final terminé comiéndome todo el pastel.',
      "Je suis au régime, mais j'ai fini par manger tout le gâteau.",
      'Estou de dieta, mas no fim acabei comendo o bolo inteiro.',
      'กำลังลดน้ำหนักอยู่ แต่สุดท้ายก็กินเค้กหมดจนได้',
      'Aku lagi diet, tapi akhirnya malah menghabiskan seluruh kuenya.',
      'Mình đang ăn kiêng mà cuối cùng vẫn ăn hết cả cái bánh kem.',
      'ダイエット中なのに、結局ケーキを全部食べてしまった。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 가다',
    sentence: '이제 봄이 다 돼 가네요.',
    trans: L(
      'Spring is almost here now.',
      'Ya casi llega la primavera.',
      'Le printemps approche peu à peu.',
      'A primavera já está quase chegando.',
      'ตอนนี้ฤดูใบไม้ผลิใกล้จะมาถึงแล้วนะ',
      'Sekarang musim semi sudah hampir tiba ya.',
      'Giờ thì mùa xuân cũng sắp đến rồi.',
      'もうすっかり春になってきましたね。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 가다',
    sentence: '조금씩 한국 생활에 익숙해져 갑니다.',
    trans: L(
      "Little by little, I'm getting used to life in Korea.",
      'Poco a poco me voy acostumbrando a la vida en Corea.',
      "Petit à petit, je m'habitue à la vie en Corée.",
      'Aos poucos, vou me acostumando com a vida na Coreia.',
      'ค่อย ๆ ปรับตัวให้ชินกับชีวิตในเกาหลีไปเรื่อย ๆ ครับ',
      'Sedikit demi sedikit saya semakin terbiasa dengan kehidupan di Korea.',
      'Tôi đang dần quen với cuộc sống ở Hàn Quốc.',
      '少しずつ韓国での生活に慣れていきます。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 오다',
    sentence: '지금까지 이 가게를 혼자서 운영해 왔어요.',
    trans: L(
      'Up to now, I have been running this shop all by myself.',
      'Hasta ahora he llevado esta tienda yo solo.',
      "Jusqu'à présent, j'ai géré cette boutique tout seul.",
      'Até agora, venho administrando esta loja sozinho.',
      'จนถึงตอนนี้ ฉันบริหารร้านนี้มาคนเดียวตลอด',
      'Sampai sekarang, saya sudah menjalankan toko ini sendirian.',
      'Cho đến nay, tôi đã một mình điều hành cửa hàng này.',
      '今まで、この店を一人で営んできました。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 오다',
    sentence: '우리 가족은 30년 동안 이 동네에서 살아왔다.',
    trans: L(
      'My family has lived in this neighborhood for 30 years.',
      'Mi familia ha vivido en este barrio durante 30 años.',
      'Ma famille vit dans ce quartier depuis 30 ans.',
      'Minha família vive neste bairro há 30 anos.',
      'ครอบครัวของเราอาศัยอยู่ในย่านนี้มา 30 ปีแล้ว',
      'Keluarga kami sudah tinggal di lingkungan ini selama 30 tahun.',
      'Gia đình tôi đã sống ở khu phố này suốt 30 năm.',
      '私の家族は30年間この町に住んできた。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 내다',
    sentence: '포기하지 않고 끝까지 버텨 냈습니다.',
    trans: L(
      'I held out to the very end without giving up.',
      'Aguanté hasta el final sin rendirme.',
      "J'ai tenu jusqu'au bout sans abandonner.",
      'Aguentei até o fim sem desistir.',
      'ผมอดทนจนถึงที่สุดโดยไม่ยอมแพ้',
      'Saya bertahan sampai akhir tanpa menyerah.',
      'Tôi đã trụ vững đến cùng mà không bỏ cuộc.',
      'あきらめずに最後まで耐え抜きました。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 내다',
    sentence: '온 가족이 힘을 모아서 결국 그 돈을 다 갚아 냈어.',
    trans: L(
      'The whole family pulled together and in the end managed to pay off all that money.',
      'Toda la familia se unió y al final logramos pagar todo ese dinero.',
      "Toute la famille s'est unie et on a fini par rembourser tout cet argent.",
      'A família toda se uniu e no fim conseguimos pagar todo aquele dinheiro.',
      'ทั้งครอบครัวร่วมแรงกัน สุดท้ายก็ใช้เงินก้อนนั้นคืนจนหมดได้',
      'Seluruh keluarga bahu-membahu dan akhirnya berhasil melunasi semua uang itu.',
      'Cả nhà chung sức và cuối cùng đã trả hết được số tiền đó.',
      '家族みんなで力を合わせて、結局そのお金を全部返し切ったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-지 그래(요)?',
    sentence: '그렇게 걱정되면 의사한테 한번 물어보지 그래요?',
    trans: L(
      "If you're that worried, why don't you ask the doctor about it?",
      'Si tanto te preocupa, ¿por qué no se lo preguntas al médico?',
      "Si ça t'inquiète à ce point, pourquoi ne pas demander au médecin ?",
      'Se você está tão preocupado, por que não pergunta ao médico?',
      'ถ้ากังวลขนาดนั้น ทำไมไม่ลองถามหมอดูล่ะ?',
      'Kalau sekhawatir itu, kenapa tidak coba tanya ke dokter saja?',
      'Nếu lo lắng đến thế thì sao bạn không thử hỏi bác sĩ xem?',
      'そんなに心配なら、医者に一度聞いてみたらどうですか？',
    ),
    level: 'polite',
  },
  {
    ko: '-지 그래(요)?',
    sentence: '계속 졸리면 커피 한 잔 마시지 그래?',
    trans: L(
      "If you keep feeling sleepy, why don't you have a cup of coffee?",
      'Si sigues con sueño, ¿por qué no te tomas un café?',
      'Si tu as encore sommeil, pourquoi tu ne bois pas un café ?',
      'Se você continua com sono, por que não toma um café?',
      'ถ้ายังง่วงอยู่ ทำไมไม่ดื่มกาแฟสักแก้วล่ะ?',
      'Kalau masih ngantuk terus, kenapa tidak minum kopi saja?',
      'Nếu cứ buồn ngủ thì sao không uống một ly cà phê đi?',
      'ずっと眠いなら、コーヒーでも一杯飲んだら？',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어야지(요)',
    sentence: '건강을 위해서 이제부터 운동을 좀 해야지요.',
    trans: L(
      'For the sake of my health, I really should start exercising a bit from now on.',
      'Por mi salud, a partir de ahora sí que debería hacer algo de ejercicio.',
      'Pour ma santé, à partir de maintenant je devrais vraiment faire un peu de sport.',
      'Pela minha saúde, de agora em diante eu tenho que me exercitar um pouco.',
      'เพื่อสุขภาพ ต่อจากนี้ก็ต้องออกกำลังกายบ้างสิ',
      'Demi kesehatan, mulai sekarang aku harus olahraga sedikit dong.',
      'Vì sức khỏe, từ giờ mình phải tập thể dục một chút chứ.',
      '健康のために、これからは少し運動しなきゃね。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어야지(요)',
    sentence: '또 늦었어? 다음부터는 좀 일찍 나와야지.',
    trans: L(
      'Late again? You really should leave a bit earlier next time.',
      '¿Otra vez tarde? La próxima vez deberías salir un poco antes.',
      'Encore en retard ? La prochaine fois, tu devrais partir un peu plus tôt.',
      'Atrasado de novo? Da próxima vez você devia sair um pouco mais cedo.',
      'สายอีกแล้วเหรอ? คราวหน้าก็ออกมาให้เร็วขึ้นหน่อยสิ',
      'Telat lagi? Lain kali berangkatnya agak lebih awal, dong.',
      'Lại trễ nữa à? Lần sau phải đi sớm hơn một chút chứ.',
      'また遅刻？次からはもう少し早く出なきゃ。',
    ),
    level: 'casual',
  },
  {
    ko: '-거든(요)',
    sentence: '내일은 일찍 자야 해요. 아침에 중요한 면접이 있거든요.',
    trans: L(
      'I have to go to bed early tomorrow. You see, I have an important interview in the morning.',
      'Mañana tengo que acostarme temprano. Es que tengo una entrevista importante por la mañana.',
      "Demain, je dois me coucher tôt. C'est que j'ai un entretien important le matin.",
      'Amanhã preciso dormir cedo. É que tenho uma entrevista importante de manhã.',
      'พรุ่งนี้ต้องเข้านอนเร็วน่ะ พอดีตอนเช้ามีสัมภาษณ์งานสำคัญน่ะ',
      'Besok aku harus tidur lebih awal. Soalnya pagi-pagi ada wawancara penting.',
      'Ngày mai tôi phải đi ngủ sớm. Tại vì sáng mai tôi có một buổi phỏng vấn quan trọng mà.',
      '明日は早く寝なきゃいけないんです。朝に大事な面接があるんですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-거든(요)',
    sentence: '그 식당은 미리 예약하는 게 좋아. 주말에는 항상 사람이 많거든.',
    trans: L(
      "You'd better book that restaurant in advance. It's always packed on weekends, you know.",
      'Mejor reserva ese restaurante con antelación. Es que los fines de semana siempre está lleno.',
      "Tu ferais mieux de réserver ce restaurant à l'avance. C'est qu'il y a toujours du monde le week-end.",
      'É melhor você reservar aquele restaurante com antecedência. É que no fim de semana sempre está cheio.',
      'ร้านนั้นจองล่วงหน้าดีกว่านะ เพราะวันหยุดสุดสัปดาห์คนเยอะตลอดเลย',
      'Mending pesan tempat di restoran itu dari jauh-jauh hari. Soalnya kalau akhir pekan selalu ramai.',
      'Cậu nên đặt bàn nhà hàng đó trước đi. Tại cuối tuần lúc nào cũng đông người mà.',
      'あのレストランは前もって予約したほうがいいよ。週末はいつも人が多いんだ。',
    ),
    level: 'casual',
  },
  {
    ko: 'N + 답다',
    sentence: '역시 프로 선수답게 어려운 상황에서도 침착하더라고요.',
    trans: L(
      'As expected, true to a pro athlete, he stayed calm even in the tough situation.',
      'Como era de esperar, digno de un atleta profesional, se mantuvo tranquilo incluso en esa situación difícil.',
      "Comme on pouvait s'y attendre, en vrai athlète professionnel, il est resté calme même dans cette situation difficile.",
      'Como era de se esperar, digno de um atleta profissional, ele se manteve calmo mesmo na situação difícil.',
      'สมเป็นนักกีฬาอาชีพจริง ๆ แม้ในสถานการณ์ที่ยากลำบากเขาก็ยังใจเย็น',
      'Memang pantas sebagai atlet profesional, dia tetap tenang bahkan dalam situasi sulit itu.',
      'Đúng là xứng đáng một vận động viên chuyên nghiệp, ngay cả trong tình huống khó khăn anh ấy vẫn rất bình tĩnh.',
      'さすがプロ選手らしく、難しい状況でも落ち着いていましたよ。',
    ),
    level: 'polite',
  },
  {
    ko: 'N + 답다',
    sentence: '날씨가 이제 좀 봄답게 따뜻해졌네.',
    trans: L(
      'The weather has finally gotten warm, like spring really should be.',
      'El clima por fin se puso cálido, como debe ser en primavera.',
      'Le temps est enfin devenu chaud, comme il se doit au printemps.',
      'O tempo finalmente esquentou, como deve ser na primavera.',
      'อากาศตอนนี้อบอุ่นขึ้นแล้วนะ สมกับเป็นฤดูใบไม้ผลิจริง ๆ',
      'Cuacanya sekarang sudah menghangat, benar-benar seperti musim semi.',
      'Thời tiết bây giờ đã ấm lên rồi, đúng chất mùa xuân thật đấy.',
      '天気がやっと春らしく暖かくなったね。',
    ),
    level: 'casual',
  },
  {
    ko: 'N + 스럽다',
    sentence: '어른들 앞에서 그렇게 행동하다니, 정말 자랑스럽구나.',
    trans: L(
      "To behave like that in front of the grown-ups, I'm really proud of you.",
      'Comportarte así delante de los mayores, de verdad estoy orgulloso de ti.',
      'Te comporter ainsi devant les adultes, je suis vraiment fier de toi.',
      'Se comportar assim na frente dos adultos, estou muito orgulhoso de você.',
      'ทำตัวแบบนั้นต่อหน้าผู้ใหญ่ น่าภูมิใจจริง ๆ เลยนะ',
      'Berperilaku seperti itu di depan orang dewasa, aku benar-benar bangga padamu.',
      'Cư xử như vậy trước mặt người lớn, thật sự rất đáng tự hào.',
      '大人たちの前でそんなふうに振る舞うなんて、本当に誇らしいね。',
    ),
    level: 'casual',
  },
  {
    ko: 'N + 스럽다',
    sentence: '처음 보는 사람이 비싼 선물을 줘서 너무 부담스러워요.',
    trans: L(
      'A stranger gave me an expensive gift, so I feel really uncomfortable about it.',
      'Un desconocido me dio un regalo caro y me siento muy incómodo.',
      "Un inconnu m'a offert un cadeau cher, alors je me sens vraiment gêné.",
      'Um estranho me deu um presente caro, então me sinto muito constrangido.',
      'คนที่เพิ่งเจอกันให้ของขวัญราคาแพง เลยรู้สึกเกรงใจมากเลย',
      'Orang yang baru kukenal memberi hadiah mahal, jadi aku merasa sungkan sekali.',
      'Người mới gặp lần đầu lại tặng quà đắt tiền nên tôi thấy rất ngại.',
      '初対面の人に高価なプレゼントをもらって、とても恐縮です。',
    ),
    level: 'polite',
  },
]
