import type { GrammarExample } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-4 grammar examples (plan Part B Tier-1, level 4). Per-FORM coverage for
 * the multi-form TOPIK-4 grammars: each grammar whose `ko` names ≥2 distinct
 * surface forms (or a quotative + cognition-verb slot) shows ≥1 example per
 * form. `ko` values match grammars-n4.ts verbatim; sentences differ from each
 * grammar's canonical `Grammar.example`.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow.
 * Native (Korean wife) review is the documented final gate.
 */
export const TOPIK_4_EXAMPLES: GrammarExample[] = [
  {
    ko: '-냐고 하다 / -(으)냐고 묻다',
    sentence: '친구가 저한테 시험이 많이 어렵냐고 했어요.',
    trans: L(
      'My friend asked me whether the exam was very hard.',
      'Mi amigo me preguntó si el examen era muy difícil.',
      "Mon ami(e) m'a demandé si l'examen était très difficile.",
      'Meu amigo me perguntou se a prova estava muito difícil.',
      'เพื่อนถามฉันว่าข้อสอบยากมากไหม',
      'Teman saya menanyakan kepada saya apakah ujiannya sangat sulit.',
      'Bạn tôi hỏi tôi rằng bài thi có khó lắm không.',
      '友達が私に試験がとても難しいかと聞きました。',
    ),
    level: 'polite',
  },
  {
    ko: '-냐고 하다 / -(으)냐고 묻다',
    sentence: '동생이 언제 집에 오냐고 물었어요.',
    trans: L(
      'My younger sibling asked when I was coming home.',
      'Mi hermano menor me preguntó cuándo volvía a casa.',
      "Mon cadet m'a demandé quand je rentrais à la maison.",
      'Meu irmão mais novo perguntou quando eu voltaria para casa.',
      'น้องถามว่าฉันจะกลับบ้านเมื่อไหร่',
      'Adik saya menanyakan kapan saya pulang ke rumah.',
      'Em tôi hỏi khi nào tôi về nhà.',
      '弟（妹）がいつ家に帰るのかと尋ねました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 듯하다 / -(으)ㄹ 듯이',
    sentence: '이번 시험은 생각보다 어려울 듯해요.',
    trans: L(
      "This exam seems like it'll be harder than I expected.",
      'Parece que este examen va a ser más difícil de lo que pensaba.',
      'Cet examen va sans doute être plus difficile que je ne le pensais.',
      'Parece que esta prova vai ser mais difícil do que eu pensava.',
      'ดูเหมือนว่าข้อสอบครั้งนี้จะยากกว่าที่คิดไว้',
      'Sepertinya ujian kali ini akan lebih sulit dari yang kukira.',
      'Bài thi lần này có vẻ sẽ khó hơn mình nghĩ.',
      '今回の試験は思ったより難しそうです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 듯하다 / -(으)ㄹ 듯이',
    sentence: '그는 모든 걸 다 아는 듯이 고개를 끄덕였어요.',
    trans: L(
      'He nodded as if he knew everything.',
      'Él asintió con la cabeza como si lo supiera todo.',
      "Il a hoché la tête comme s'il savait tout.",
      'Ele balançou a cabeça como se soubesse de tudo.',
      'เขาพยักหน้าราวกับว่ารู้ทุกอย่าง',
      'Dia mengangguk seolah-olah tahu segalanya.',
      'Anh ấy gật đầu như thể biết hết mọi thứ.',
      '彼はすべてを知っているかのようにうなずきました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)로서 / -(으)로써',
    sentence: '한 가정의 가장으로서 저는 가족의 생계를 책임지고 있습니다.',
    trans: L(
      'As the head of the household, I am responsible for supporting my family.',
      'Como cabeza de familia, soy responsable del sustento de mi familia.',
      'En tant que chef de famille, je suis responsable de subvenir aux besoins de ma famille.',
      'Como chefe da família, sou responsável pelo sustento da minha família.',
      'ในฐานะหัวหน้าครอบครัว ผมมีหน้าที่รับผิดชอบในการหาเลี้ยงครอบครัว',
      'Sebagai kepala keluarga, saya bertanggung jawab atas nafkah keluarga saya.',
      'Với tư cách là trụ cột gia đình, tôi có trách nhiệm lo sinh kế cho gia đình mình.',
      '一家の大黒柱として、私は家族の生計に責任を負っています。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)로서 / -(으)로써',
    sentence: '꾸준한 운동으로써 건강을 지킬 수 있어요.',
    trans: L(
      'You can protect your health by exercising regularly.',
      'Puedes cuidar tu salud haciendo ejercicio con constancia.',
      "On peut préserver sa santé en faisant de l'exercice régulièrement.",
      'Você pode proteger a sua saúde praticando exercícios com regularidade.',
      'เราสามารถรักษาสุขภาพได้ด้วยการออกกำลังกายอย่างสม่ำเสมอ',
      'Anda bisa menjaga kesehatan dengan berolahraga secara teratur.',
      'Bạn có thể giữ gìn sức khỏe bằng cách tập thể dục đều đặn.',
      'こつこつとした運動によって健康を守ることができます。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 봤자 / 봐야',
    sentence: '이렇게 비싼 약은 먹어 봤자 효과도 없어요.',
    trans: L(
      "Even if you take such expensive medicine, it won't even work.",
      'Aunque tomes una medicina tan cara, no servirá de nada.',
      'Même si tu prends un médicament aussi cher, ça ne marchera même pas.',
      'Mesmo que você tome um remédio tão caro, não vai adiantar nada.',
      'ต่อให้กินยาแพงขนาดนี้ ก็ไม่ได้ผลอะไรหรอก',
      'Meski kamu minum obat semahal ini, tidak akan ada gunanya.',
      'Dù có uống thuốc đắt như vậy thì cũng chẳng có tác dụng gì đâu.',
      'こんなに高い薬を飲んだところで、効果もありませんよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 봤자 / 봐야',
    sentence: '이미 다 끝난 일인데 후회해 봐야 소용없어.',
    trans: L(
      "It's all over already, so even if you regret it, it's no use.",
      'Ya está todo terminado, así que de nada sirve arrepentirse.',
      'Tout est déjà fini, alors ça ne sert à rien de regretter.',
      'Já acabou tudo, então não adianta nada se arrepender.',
      'เรื่องมันจบไปหมดแล้ว ต่อให้มานั่งเสียใจก็ไม่มีประโยชน์หรอก',
      'Semuanya sudah berakhir, jadi menyesal pun percuma.',
      'Mọi chuyện đã kết thúc cả rồi, có hối hận thì cũng vô ích thôi.',
      'もう全部終わったことだから、後悔したって無駄だよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-고 보다 / -고 보니(까)',
    sentence: '고민만 하지 말고 일단 지원하고 봐요.',
    trans: L(
      'Stop just agonizing over it — go ahead and apply first, then see what happens.',
      'Deja de darle vueltas y, para empezar, presenta la solicitud y luego ya veremos.',
      "Arrête de te torturer l'esprit : commence par poser ta candidature, on verra après.",
      'Pare de só ficar remoendo — primeiro se inscreva e depois a gente vê.',
      'อย่าเอาแต่คิดมาก ลองสมัครไปก่อนแล้วค่อยดูผล',
      'Jangan cuma dipikirin terus — lamar dulu saja, lihat hasilnya nanti.',
      'Đừng cứ đắn đo mãi — cứ nộp đơn trước đã rồi tính sau.',
      '悩んでばかりいないで、とりあえず応募してみましょう。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 보다 / -고 보니(까)',
    sentence: '급하게 짐을 싸고 보니까 여권을 안 챙겼더라고요.',
    trans: L(
      "After hurriedly packing, I realized I hadn't grabbed my passport.",
      'Después de hacer la maleta a las prisas, me di cuenta de que no había cogido el pasaporte.',
      "Après avoir fait ma valise à la hâte, je me suis rendu compte que je n'avais pas pris mon passeport.",
      'Depois de fazer as malas às pressas, percebi que não tinha pegado o passaporte.',
      'พอรีบเก็บกระเป๋าเสร็จถึงรู้ว่าไม่ได้หยิบพาสปอร์ตมา',
      'Setelah buru-buru mengemas barang, baru sadar saya tidak membawa paspor.',
      'Sau khi vội vàng xếp hành lý xong tôi mới nhận ra mình chưa cầm hộ chiếu.',
      '急いで荷造りしてみたら、パスポートを持っていないことに気づいたんですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-다면서요? / -다며?',
    sentence: '이번 주말에 부산으로 이사 가신다면서요?',
    trans: L(
      "I heard you're moving to Busan this weekend, is that right?",
      'Me dijeron que se muda a Busan este fin de semana, ¿es verdad?',
      "J'ai entendu dire que vous déménagez à Busan ce week-end, c'est vrai ?",
      'Ouvi dizer que você vai se mudar para Busan neste fim de semana, é verdade?',
      'ได้ยินมาว่าคุณจะย้ายไปปูซานสุดสัปดาห์นี้ใช่ไหมคะ',
      'Katanya akhir pekan ini Anda pindah ke Busan, benar begitu?',
      'Nghe nói cuối tuần này anh chuyển đến Busan, đúng không ạ?',
      '今週末にプサンへ引っ越されるんですってね？',
    ),
    level: 'polite',
  },
  {
    ko: '-다면서요? / -다며?',
    sentence: '너 다음 달에 군대 간다며?',
    trans: L(
      "I heard you're going to the army next month, that true?",
      'Oí que el mes que viene te vas al ejército, ¿es verdad?',
      "Il paraît que tu pars à l'armée le mois prochain, c'est vrai ?",
      'Ouvi dizer que você vai pro exército mês que vem, é verdade?',
      'ได้ยินว่าเดือนหน้าแกจะไปเป็นทหารเหรอ',
      'Katanya bulan depan kamu masuk wajib militer, beneran?',
      'Nghe nói tháng sau cậu đi nghĩa vụ quân sự à?',
      'あんた、来月軍隊に行くんだって？',
    ),
    level: 'casual',
  },
  {
    ko: '-다고 + 생각하다 / 믿다 / 듣다 / 보다 / 알다 / 느끼다 / 여기다',
    sentence: '저는 이 일이 생각보다 어렵다고 생각해요.',
    trans: L(
      'I think this work is harder than I expected.',
      'Creo que este trabajo es más difícil de lo que esperaba.',
      'Je pense que ce travail est plus difficile que prévu.',
      'Acho que este trabalho é mais difícil do que eu esperava.',
      'ฉันคิดว่างานนี้ยากกว่าที่คิดไว้',
      'Saya pikir pekerjaan ini lebih sulit daripada yang saya kira.',
      'Tôi nghĩ rằng công việc này khó hơn tôi tưởng.',
      '私はこの仕事が思ったより難しいと思います。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고 + 생각하다 / 믿다 / 듣다 / 보다 / 알다 / 느끼다 / 여기다',
    sentence: '이번 겨울이 유난히 춥다고 들었어요.',
    trans: L(
      'I heard that this winter is unusually cold.',
      'Oí que este invierno es excepcionalmente frío.',
      "J'ai entendu dire que cet hiver est particulièrement froid.",
      'Ouvi dizer que este inverno está excepcionalmente frio.',
      'ฉันได้ยินมาว่าฤดูหนาวปีนี้หนาวเป็นพิเศษ',
      'Saya dengar bahwa musim dingin kali ini luar biasa dingin.',
      'Tôi nghe nói mùa đông năm nay lạnh khác thường.',
      '今年の冬は特に寒いと聞きました。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고 + 생각하다 / 믿다 / 듣다 / 보다 / 알다 / 느끼다 / 여기다',
    sentence: '요즘 들어 시간이 정말 빠르다고 느껴요.',
    trans: L(
      'Lately I feel that time really flies.',
      'Últimamente siento que el tiempo pasa muy rápido.',
      'Ces derniers temps, je sens que le temps passe vraiment vite.',
      'Ultimamente sinto que o tempo passa muito rápido.',
      'ช่วงนี้ฉันรู้สึกว่าเวลาผ่านไปเร็วมากจริงๆ',
      'Akhir-akhir ini saya merasa bahwa waktu berlalu sangat cepat.',
      'Dạo này tôi cảm thấy thời gian trôi qua thật nhanh.',
      '最近、時間が本当に速いと感じます。',
    ),
    level: 'polite',
  },
]
