import type { GrammarExample } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-4 grammar examples (plan Part B Tier-1, level 4). Per-FORM coverage for
 * the multi-form TOPIK-4 grammars: each grammar whose `ko` names ≥2 distinct
 * surface forms (or a quotative + cognition-verb slot) shows ≥1 example per
 * form. `ko` values match grammars-n4.ts verbatim; sentences differ from each
 * grammar's canonical `Grammar.example`.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow.
 * Native (Korean wife) review is the documented final gate.
 */
export const TOPIK_4_EXAMPLES: GrammarExample[] = [
  {
    ko: '-냐고 하다 / -(으)냐고 묻다',
    sentence: '친구가 저한테 시험이 많이 어렵냐고 했어요.',
    trans: L(
      'My friend asked me whether the exam was very hard.',
      'Mi amigo me preguntó si el examen era muy difícil.',
      "Mon ami(e) m'a demandé si l'examen était très difficile.",
      'Meu amigo me perguntou se a prova estava muito difícil.',
      'เพื่อนถามฉันว่าข้อสอบยากมากไหม',
      'Teman saya menanyakan kepada saya apakah ujiannya sangat sulit.',
      'Bạn tôi hỏi tôi rằng bài thi có khó lắm không.',
      '友達が私に試験がとても難しいかと聞きました。',
    ),
    level: 'polite',
  },
  {
    ko: '-냐고 하다 / -(으)냐고 묻다',
    sentence: '동생이 언제 집에 오냐고 물었어요.',
    trans: L(
      'My younger sibling asked when I was coming home.',
      'Mi hermano menor me preguntó cuándo volvía a casa.',
      "Mon cadet m'a demandé quand je rentrais à la maison.",
      'Meu irmão mais novo perguntou quando eu voltaria para casa.',
      'น้องถามว่าฉันจะกลับบ้านเมื่อไหร่',
      'Adik saya menanyakan kapan saya pulang ke rumah.',
      'Em tôi hỏi khi nào tôi về nhà.',
      '弟（妹）がいつ家に帰るのかと尋ねました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 듯하다 / -(으)ㄹ 듯이',
    sentence: '이번 시험은 생각보다 어려울 듯해요.',
    trans: L(
      "This exam seems like it'll be harder than I expected.",
      'Parece que este examen va a ser más difícil de lo que pensaba.',
      'Cet examen va sans doute être plus difficile que je ne le pensais.',
      'Parece que esta prova vai ser mais difícil do que eu pensava.',
      'ดูเหมือนว่าข้อสอบครั้งนี้จะยากกว่าที่คิดไว้',
      'Sepertinya ujian kali ini akan lebih sulit dari yang kukira.',
      'Bài thi lần này có vẻ sẽ khó hơn mình nghĩ.',
      '今回の試験は思ったより難しそうです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 듯하다 / -(으)ㄹ 듯이',
    sentence: '그는 모든 걸 다 아는 듯이 고개를 끄덕였어요.',
    trans: L(
      'He nodded as if he knew everything.',
      'Él asintió con la cabeza como si lo supiera todo.',
      "Il a hoché la tête comme s'il savait tout.",
      'Ele balançou a cabeça como se soubesse de tudo.',
      'เขาพยักหน้าราวกับว่ารู้ทุกอย่าง',
      'Dia mengangguk seolah-olah tahu segalanya.',
      'Anh ấy gật đầu như thể biết hết mọi thứ.',
      '彼はすべてを知っているかのようにうなずきました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)로서 / -(으)로써',
    sentence: '한 가정의 가장으로서 저는 가족의 생계를 책임지고 있습니다.',
    trans: L(
      'As the head of the household, I am responsible for supporting my family.',
      'Como cabeza de familia, soy responsable del sustento de mi familia.',
      'En tant que chef de famille, je suis responsable de subvenir aux besoins de ma famille.',
      'Como chefe da família, sou responsável pelo sustento da minha família.',
      'ในฐานะหัวหน้าครอบครัว ผมมีหน้าที่รับผิดชอบในการหาเลี้ยงครอบครัว',
      'Sebagai kepala keluarga, saya bertanggung jawab atas nafkah keluarga saya.',
      'Với tư cách là trụ cột gia đình, tôi có trách nhiệm lo sinh kế cho gia đình mình.',
      '一家の大黒柱として、私は家族の生計に責任を負っています。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)로서 / -(으)로써',
    sentence: '꾸준한 운동으로써 건강을 지킬 수 있어요.',
    trans: L(
      'You can protect your health by exercising regularly.',
      'Puedes cuidar tu salud haciendo ejercicio con constancia.',
      "On peut préserver sa santé en faisant de l'exercice régulièrement.",
      'Você pode proteger a sua saúde praticando exercícios com regularidade.',
      'เราสามารถรักษาสุขภาพได้ด้วยการออกกำลังกายอย่างสม่ำเสมอ',
      'Anda bisa menjaga kesehatan dengan berolahraga secara teratur.',
      'Bạn có thể giữ gìn sức khỏe bằng cách tập thể dục đều đặn.',
      'こつこつとした運動によって健康を守ることができます。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 봤자 / 봐야',
    sentence: '이렇게 비싼 약은 먹어 봤자 효과도 없어요.',
    trans: L(
      "Even if you take such expensive medicine, it won't even work.",
      'Aunque tomes una medicina tan cara, no servirá de nada.',
      'Même si tu prends un médicament aussi cher, ça ne marchera même pas.',
      'Mesmo que você tome um remédio tão caro, não vai adiantar nada.',
      'ต่อให้กินยาแพงขนาดนี้ ก็ไม่ได้ผลอะไรหรอก',
      'Meski kamu minum obat semahal ini, tidak akan ada gunanya.',
      'Dù có uống thuốc đắt như vậy thì cũng chẳng có tác dụng gì đâu.',
      'こんなに高い薬を飲んだところで、効果もありませんよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 봤자 / 봐야',
    sentence: '이미 다 끝난 일인데 후회해 봐야 소용없어.',
    trans: L(
      "It's all over already, so even if you regret it, it's no use.",
      'Ya está todo terminado, así que de nada sirve arrepentirse.',
      'Tout est déjà fini, alors ça ne sert à rien de regretter.',
      'Já acabou tudo, então não adianta nada se arrepender.',
      'เรื่องมันจบไปหมดแล้ว ต่อให้มานั่งเสียใจก็ไม่มีประโยชน์หรอก',
      'Semuanya sudah berakhir, jadi menyesal pun percuma.',
      'Mọi chuyện đã kết thúc cả rồi, có hối hận thì cũng vô ích thôi.',
      'もう全部終わったことだから、後悔したって無駄だよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-고 보다 / -고 보니(까)',
    sentence: '고민만 하지 말고 일단 지원하고 봐요.',
    trans: L(
      'Stop just agonizing over it — go ahead and apply first, then see what happens.',
      'Deja de darle vueltas y, para empezar, presenta la solicitud y luego ya veremos.',
      "Arrête de te torturer l'esprit : commence par poser ta candidature, on verra après.",
      'Pare de só ficar remoendo — primeiro se inscreva e depois a gente vê.',
      'อย่าเอาแต่คิดมาก ลองสมัครไปก่อนแล้วค่อยดูผล',
      'Jangan cuma dipikirin terus — lamar dulu saja, lihat hasilnya nanti.',
      'Đừng cứ đắn đo mãi — cứ nộp đơn trước đã rồi tính sau.',
      '悩んでばかりいないで、とりあえず応募してみましょう。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 보다 / -고 보니(까)',
    sentence: '급하게 짐을 싸고 보니까 여권을 안 챙겼더라고요.',
    trans: L(
      "After hurriedly packing, I realized I hadn't grabbed my passport.",
      'Después de hacer la maleta a las prisas, me di cuenta de que no había cogido el pasaporte.',
      "Après avoir fait ma valise à la hâte, je me suis rendu compte que je n'avais pas pris mon passeport.",
      'Depois de fazer as malas às pressas, percebi que não tinha pegado o passaporte.',
      'พอรีบเก็บกระเป๋าเสร็จถึงรู้ว่าไม่ได้หยิบพาสปอร์ตมา',
      'Setelah buru-buru mengemas barang, baru sadar saya tidak membawa paspor.',
      'Sau khi vội vàng xếp hành lý xong tôi mới nhận ra mình chưa cầm hộ chiếu.',
      '急いで荷造りしてみたら、パスポートを持っていないことに気づいたんですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-다면서요? / -다며?',
    sentence: '이번 주말에 부산으로 이사 가신다면서요?',
    trans: L(
      "I heard you're moving to Busan this weekend, is that right?",
      'Me dijeron que se muda a Busan este fin de semana, ¿es verdad?',
      "J'ai entendu dire que vous déménagez à Busan ce week-end, c'est vrai ?",
      'Ouvi dizer que você vai se mudar para Busan neste fim de semana, é verdade?',
      'ได้ยินมาว่าคุณจะย้ายไปปูซานสุดสัปดาห์นี้ใช่ไหมคะ',
      'Katanya akhir pekan ini Anda pindah ke Busan, benar begitu?',
      'Nghe nói cuối tuần này anh chuyển đến Busan, đúng không ạ?',
      '今週末にプサンへ引っ越されるんですってね？',
    ),
    level: 'polite',
  },
  {
    ko: '-다면서요? / -다며?',
    sentence: '너 다음 달에 군대 간다며?',
    trans: L(
      "I heard you're going to the army next month, that true?",
      'Oí que el mes que viene te vas al ejército, ¿es verdad?',
      "Il paraît que tu pars à l'armée le mois prochain, c'est vrai ?",
      'Ouvi dizer que você vai pro exército mês que vem, é verdade?',
      'ได้ยินว่าเดือนหน้าแกจะไปเป็นทหารเหรอ',
      'Katanya bulan depan kamu masuk wajib militer, beneran?',
      'Nghe nói tháng sau cậu đi nghĩa vụ quân sự à?',
      'あんた、来月軍隊に行くんだって？',
    ),
    level: 'casual',
  },
  {
    ko: '-다고 + 생각하다 / 믿다 / 듣다 / 보다 / 알다 / 느끼다 / 여기다',
    sentence: '저는 이 일이 생각보다 어렵다고 생각해요.',
    trans: L(
      'I think this work is harder than I expected.',
      'Creo que este trabajo es más difícil de lo que esperaba.',
      'Je pense que ce travail est plus difficile que prévu.',
      'Acho que este trabalho é mais difícil do que eu esperava.',
      'ฉันคิดว่างานนี้ยากกว่าที่คิดไว้',
      'Saya pikir pekerjaan ini lebih sulit daripada yang saya kira.',
      'Tôi nghĩ rằng công việc này khó hơn tôi tưởng.',
      '私はこの仕事が思ったより難しいと思います。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고 + 생각하다 / 믿다 / 듣다 / 보다 / 알다 / 느끼다 / 여기다',
    sentence: '이번 겨울이 유난히 춥다고 들었어요.',
    trans: L(
      'I heard that this winter is unusually cold.',
      'Oí que este invierno es excepcionalmente frío.',
      "J'ai entendu dire que cet hiver est particulièrement froid.",
      'Ouvi dizer que este inverno está excepcionalmente frio.',
      'ฉันได้ยินมาว่าฤดูหนาวปีนี้หนาวเป็นพิเศษ',
      'Saya dengar bahwa musim dingin kali ini luar biasa dingin.',
      'Tôi nghe nói mùa đông năm nay lạnh khác thường.',
      '今年の冬は特に寒いと聞きました。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고 + 생각하다 / 믿다 / 듣다 / 보다 / 알다 / 느끼다 / 여기다',
    sentence: '요즘 들어 시간이 정말 빠르다고 느껴요.',
    trans: L(
      'Lately I feel that time really flies.',
      'Últimamente siento que el tiempo pasa muy rápido.',
      'Ces derniers temps, je sens que le temps passe vraiment vite.',
      'Ultimamente sinto que o tempo passa muito rápido.',
      'ช่วงนี้ฉันรู้สึกว่าเวลาผ่านไปเร็วมากจริงๆ',
      'Akhir-akhir ini saya merasa bahwa waktu berlalu sangat cepat.',
      'Dạo này tôi cảm thấy thời gian trôi qua thật nhanh.',
      '最近、時間が本当に速いと感じます。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고 하다',
    sentence: '친구가 요즘 너무 바쁘다고 했어요.',
    trans: L(
      "My friend said they're really busy these days.",
      'Mi amigo dijo que está muy ocupado estos días.',
      "Mon ami a dit qu'il est très occupé ces jours-ci.",
      'Meu amigo disse que anda muito ocupado esses dias.',
      'เพื่อนบอกว่าช่วงนี้ยุ่งมาก',
      'Temanku bilang dia sangat sibuk akhir-akhir ini.',
      'Bạn tôi nói rằng dạo này rất bận.',
      '友達が最近とても忙しいと言っていました。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고 하다',
    sentence: '엄마가 저녁에 비가 온다고 하니까 우산 챙겨.',
    trans: L(
      "Mom says it'll rain in the evening, so grab an umbrella.",
      'Mamá dice que va a llover por la noche, así que lleva un paraguas.',
      "Maman dit qu'il va pleuvoir ce soir, alors prends un parapluie.",
      'A mamãe disse que vai chover à noite, então leve um guarda-chuva.',
      'แม่บอกว่าตอนเย็นฝนจะตก เอาร่มไปด้วยนะ',
      'Ibu bilang nanti malam akan hujan, jadi bawa payung ya.',
      'Mẹ bảo tối nay trời sẽ mưa nên mang theo ô đi.',
      'お母さんが夜に雨が降ると言ってるから傘を持っていって。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)라고 하다',
    sentence: '의사 선생님이 약을 식사 후에 드시라고 했어요.',
    trans: L(
      'The doctor told me to take the medicine after meals.',
      'El doctor me dijo que tomara la medicina después de las comidas.',
      "Le médecin m'a dit de prendre le médicament après les repas.",
      'O médico me disse para tomar o remédio depois das refeições.',
      'คุณหมอบอกให้กินยาหลังอาหาร',
      'Dokter menyuruh saya minum obat setelah makan.',
      'Bác sĩ bảo tôi uống thuốc sau bữa ăn.',
      'お医者さんが薬を食後に飲むようにと言いました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)라고 하다',
    sentence: '엄마가 동생한테 빨리 자라고 했어.',
    trans: L(
      'Mom told my little brother to go to sleep quickly.',
      'Mamá le dijo a mi hermano menor que se durmiera rápido.',
      'Maman a dit à mon petit frère de vite aller dormir.',
      'A mamãe disse para o meu irmão mais novo dormir logo.',
      'แม่บอกให้น้องรีบไปนอน',
      'Ibu menyuruh adik cepat tidur.',
      'Mẹ bảo em tôi mau đi ngủ.',
      'お母さんが弟に早く寝なさいと言ったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-자고 하다',
    sentence: '주말에 등산 가자고 했는데 비가 와서 취소했어요.',
    trans: L(
      'Someone suggested we go hiking on the weekend, but it rained so we canceled.',
      'Propuso que fuéramos de excursión a la montaña el fin de semana, pero llovió y lo cancelamos.',
      "On avait proposé d'aller faire de la randonnée le week-end, mais il a plu alors on a annulé.",
      'Sugeriram irmos fazer trilha no fim de semana, mas choveu e cancelamos.',
      'มีคนชวนให้ไปปีนเขากันช่วงสุดสัปดาห์ แต่ฝนตกเลยยกเลิกไป',
      'Dia mengajak kami pergi mendaki saat akhir pekan, tapi hujan jadi dibatalkan.',
      'Có người rủ cuối tuần đi leo núi, nhưng trời mưa nên đã hủy rồi.',
      '週末に山登りに行こうと言ったけど、雨が降って中止になりました。',
    ),
    level: 'polite',
  },
  {
    ko: '-자고 하다',
    sentence: '팀장님이 회의를 내일로 미루자고 하셨어.',
    trans: L(
      'The team leader suggested we push the meeting to tomorrow.',
      'El jefe de equipo propuso que aplazáramos la reunión para mañana.',
      "Le chef d'équipe a proposé de reporter la réunion à demain.",
      'O líder da equipe sugeriu adiarmos a reunião para amanhã.',
      'หัวหน้าทีมเสนอว่าให้เลื่อนการประชุมไปเป็นพรุ่งนี้',
      'Ketua tim mengusulkan agar rapatnya ditunda ke besok.',
      'Trưởng nhóm đề nghị dời cuộc họp sang ngày mai.',
      'チーム長が会議を明日に延ばそうとおっしゃった。',
    ),
    level: 'casual',
  },
  {
    ko: '-다면서요?',
    sentence: '민수 씨, 다음 달에 회사를 그만두신다면서요?',
    trans: L(
      "Minsu, I heard you're quitting the company next month, is that right?",
      'Minsu, me dijeron que el mes que viene dejas la empresa, ¿es verdad?',
      "Minsu, il paraît que tu quittes l'entreprise le mois prochain, c'est vrai ?",
      'Minsu, ouvi dizer que você vai sair da empresa no mês que vem, é verdade?',
      'คุณมินซู ได้ยินมาว่าเดือนหน้าจะลาออกจากบริษัทใช่ไหมคะ',
      'Minsu, katanya bulan depan kamu keluar dari perusahaan, benar?',
      'Anh Minsu, nghe nói tháng sau anh nghỉ việc ở công ty phải không ạ?',
      'ミンスさん、来月会社を辞められるんですってね？',
    ),
    level: 'polite',
  },
  {
    ko: '-다면서요?',
    sentence: '너 요즘 강아지 키운다며?',
    trans: L(
      "Hey, I heard you've got a puppy these days, that true?",
      'Oye, me dijeron que ahora tienes un perrito, ¿es cierto?',
      "Dis, il paraît que tu as un chiot en ce moment, c'est vrai ?",
      'Ei, ouvi dizer que você está com um cachorrinho agora, é verdade?',
      'นี่ ได้ยินว่าช่วงนี้แกเลี้ยงหมาเหรอ',
      'Eh, katanya sekarang kamu pelihara anjing, beneran?',
      'Này, nghe nói dạo này cậu nuôi cún à?',
      'あんた、最近子犬を飼ってるんだって？',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 뿐만 아니라',
    sentence: '그 배우는 연기를 잘할 뿐만 아니라 노래도 정말 잘해요.',
    trans: L(
      'That actor not only acts well but also sings really well.',
      'Ese actor no solo actúa bien, sino que también canta muy bien.',
      'Cet acteur ne joue pas seulement bien la comédie, il chante aussi très bien.',
      'Aquele ator não só atua bem, como também canta muito bem.',
      'นักแสดงคนนั้นไม่เพียงแต่แสดงเก่งเท่านั้น แต่ยังร้องเพลงเก่งมากอีกด้วย',
      'Aktor itu tidak hanya pandai berakting, tetapi juga sangat pandai bernyanyi.',
      'Diễn viên đó không những diễn xuất giỏi mà còn hát rất hay nữa.',
      'あの俳優は演技が上手なだけでなく、歌も本当に上手です。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 뿐만 아니라',
    sentence: '오늘은 길이 막힐 뿐만 아니라 비까지 와서 회사에 늦었어.',
    trans: L(
      'Today not only was the traffic bad, it even rained too, so I was late for work.',
      'Hoy no solo había mucho tráfico, sino que encima llovió, así que llegué tarde al trabajo.',
      "Aujourd'hui, non seulement il y avait des embouteillages, mais en plus il pleuvait, alors je suis arrivé en retard au travail.",
      'Hoje não só tinha trânsito, como ainda por cima choveu, então cheguei atrasado no trabalho.',
      'วันนี้ไม่เพียงแต่รถติดเท่านั้น แต่ฝนยังตกอีก เลยไปทำงานสาย',
      'Hari ini bukan hanya jalanan macet, tapi malah hujan juga, jadi aku telat ke kantor.',
      'Hôm nay không những tắc đường mà còn mưa nữa nên tớ đi làm muộn.',
      '今日は道が混んでいただけでなく、雨まで降って会社に遅れたよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 반면에',
    sentence: '이 식당은 음식 값이 싼 반면에 양이 좀 적어요.',
    trans: L(
      "This restaurant's food is cheap, but on the other hand the portions are a bit small.",
      'En este restaurante la comida es barata, pero en cambio las porciones son algo pequeñas.',
      'Dans ce restaurant, la nourriture est bon marché, mais en revanche les portions sont un peu petites.',
      'Neste restaurante a comida é barata, mas, por outro lado, as porções são um pouco pequenas.',
      'ร้านอาหารนี้ราคาถูกก็จริง แต่ในทางกลับกันปริมาณค่อนข้างน้อย',
      'Di restoran ini makanannya murah, tetapi sebaliknya porsinya agak sedikit.',
      'Quán ăn này đồ ăn rẻ, nhưng ngược lại phần ăn hơi ít.',
      'このお店は料理が安い反面、量がちょっと少ないです。',
    ),
    level: 'polite',
  },
  {
    ko: '-는 반면에',
    sentence: '도시는 생활이 편리한 반면에 시골은 공기가 맑다.',
    trans: L(
      'Life in the city is convenient, whereas in the countryside the air is clean.',
      'La vida en la ciudad es cómoda, mientras que en el campo el aire es puro.',
      "La vie en ville est pratique, tandis qu'à la campagne l'air est pur.",
      'A vida na cidade é prática, ao passo que no campo o ar é puro.',
      'ชีวิตในเมืองสะดวกสบาย ในขณะที่ชนบทอากาศบริสุทธิ์',
      'Kehidupan di kota praktis, sedangkan di desa udaranya bersih.',
      'Cuộc sống ở thành phố tiện lợi, trong khi ở nông thôn không khí trong lành.',
      '都市は生活が便利な反面、田舎は空気がきれいだ。',
    ),
    level: 'formal',
  },
  {
    ko: '-에도 불구하고',
    sentence: '열심히 준비했음에도 불구하고 시험에 떨어졌습니다.',
    trans: L(
      'Despite having prepared hard, I failed the exam.',
      'A pesar de haberme preparado mucho, suspendí el examen.',
      "Malgré une préparation acharnée, j'ai échoué à l'examen.",
      'Apesar de ter me preparado bastante, fui reprovado no exame.',
      'ทั้งที่เตรียมตัวมาอย่างหนัก แต่ก็สอบตก',
      'Meskipun sudah belajar dengan giat, saya tetap gagal dalam ujian.',
      'Mặc dù đã chuẩn bị rất chăm chỉ, tôi vẫn trượt kỳ thi.',
      '一生懸命準備したにもかかわらず、試験に落ちました。',
    ),
    level: 'formal',
  },
  {
    ko: '-에도 불구하고',
    sentence: '몸살에도 불구하고 끝까지 회의에 참석했어요.',
    trans: L(
      'Despite a bad cold, I attended the meeting to the very end.',
      'A pesar de un fuerte resfriado, asistí a la reunión hasta el final.',
      "Malgré une mauvaise grippe, j'ai assisté à la réunion jusqu'au bout.",
      'Apesar de uma forte gripe, participei da reunião até o fim.',
      'ทั้งที่เป็นไข้หวัด ฉันก็เข้าประชุมจนจบ',
      'Meskipun sedang sakit flu, saya tetap mengikuti rapat sampai akhir.',
      'Dù bị cảm nặng, tôi vẫn dự họp đến cùng.',
      'ひどい風邪にもかかわらず、最後まで会議に参加しました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ수록',
    sentence: '나이가 들수록 시간이 빨리 가는 것 같아요.',
    trans: L(
      'The older I get, the faster time seems to go by.',
      'Cuanto más mayor me hago, más rápido parece pasar el tiempo.',
      'Plus je vieillis, plus le temps semble passer vite.',
      'Quanto mais velho fico, mais rápido o tempo parece passar.',
      'ยิ่งอายุมากขึ้น เวลายิ่งดูเหมือนผ่านไปเร็วขึ้น',
      'Semakin bertambah usia, waktu terasa semakin cepat berlalu.',
      'Càng lớn tuổi, thời gian dường như càng trôi nhanh hơn.',
      '年を取るほど、時間が速く過ぎていく気がします。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ수록',
    sentence: '이 노래는 들으면 들을수록 좋아져.',
    trans: L(
      'The more you listen to this song, the more you like it.',
      'Esta canción te gusta más cuanto más la escuchas.',
      "Plus tu écoutes cette chanson, plus tu l'aimes.",
      'Quanto mais você escuta essa música, mais gosta dela.',
      'เพลงนี้ยิ่งฟังก็ยิ่งชอบ',
      'Lagu ini semakin didengar semakin disukai.',
      'Bài hát này càng nghe càng thấy hay.',
      'この歌は聞けば聞くほど好きになる。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 한',
    sentence: '비밀번호를 잊어버리지 않는 한 계정에 다시 들어갈 수 있어요.',
    trans: L(
      "As long as you don't forget your password, you can get back into your account.",
      'Mientras no olvides tu contraseña, podrás volver a entrar en la cuenta.',
      "Tant que tu n'oublies pas ton mot de passe, tu pourras te reconnecter à ton compte.",
      'Contanto que você não esqueça a senha, dá para entrar na conta de novo.',
      'ตราบใดที่คุณไม่ลืมรหัสผ่าน คุณก็จะกลับเข้าบัญชีได้',
      'Selama kamu tidak lupa kata sandi, kamu bisa masuk lagi ke akun.',
      'Chừng nào bạn không quên mật khẩu thì bạn vẫn có thể đăng nhập lại vào tài khoản.',
      'パスワードを忘れない限り、またアカウントにログインできますよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-는 한',
    sentence: '내가 여기 있는 한 아무도 너를 못 건드려.',
    trans: L(
      "As long as I'm here, no one can touch you.",
      'Mientras yo esté aquí, nadie podrá tocarte.',
      'Tant que je suis là, personne ne pourra te toucher.',
      'Enquanto eu estiver aqui, ninguém vai encostar em você.',
      'ตราบใดที่ฉันอยู่ตรงนี้ ไม่มีใครแตะต้องเธอได้หรอก',
      'Selama aku di sini, tidak ada yang bisa menyentuhmu.',
      'Chừng nào còn có tôi ở đây thì không ai động được vào cậu đâu.',
      '俺がここにいる限り、誰もお前に手出しできないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 데다가',
    sentence: '이 식당은 음식이 맛있는 데다가 값도 싸서 자주 가요.',
    trans: L(
      'On top of the food being delicious, this restaurant is cheap too, so I go often.',
      'Además de que la comida es deliciosa, este restaurante también es barato, así que voy a menudo.',
      "En plus d'avoir une cuisine délicieuse, ce restaurant est aussi bon marché, alors j'y vais souvent.",
      'Além de a comida ser deliciosa, este restaurante também é barato, por isso vou com frequência.',
      'ร้านนี้นอกจากอาหารอร่อยแล้ว ราคายังถูกอีกด้วย เลยไปบ่อย',
      'Selain makanannya enak, restoran ini juga murah, jadi saya sering ke sana.',
      'Quán này đồ ăn ngon, hơn nữa giá lại còn rẻ nên mình hay đến.',
      'この店は料理がおいしいうえに値段も安いので、よく行きます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 데다가',
    sentence: '그 사람은 일을 빨리 끝낸 데다가 실수도 거의 안 했어.',
    trans: L(
      'On top of finishing the work fast, that person barely made any mistakes either.',
      'Además de terminar el trabajo rápido, esa persona casi no cometió errores.',
      "En plus d'avoir fini le travail rapidement, cette personne n'a presque pas fait d'erreurs.",
      'Além de terminar o trabalho rápido, essa pessoa quase não cometeu erros.',
      'คนนั้นนอกจากทำงานเสร็จเร็วแล้ว ยังแทบไม่ทำพลาดเลยด้วย',
      'Selain menyelesaikan pekerjaan dengan cepat, orang itu juga hampir tidak membuat kesalahan.',
      'Người đó làm xong việc nhanh, hơn nữa lại còn hầu như không mắc lỗi.',
      'あの人は仕事を早く終わらせたうえに、ミスもほとんどしなかった。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 뿐더러',
    sentence: '그 식당은 음식이 맛있을 뿐더러 사장님도 친절하셔서 자주 가요.',
    trans: L(
      "That restaurant's food is not only delicious, but the owner is also kind, so I go there often.",
      'La comida de ese restaurante no solo es deliciosa, sino que el dueño también es amable, así que voy a menudo.',
      "Non seulement la nourriture de ce restaurant est délicieuse, mais le patron est aussi gentil, alors j'y vais souvent.",
      'A comida daquele restaurante não só é deliciosa, como o dono também é gentil, então vou lá com frequência.',
      'ร้านอาหารร้านนั้นไม่เพียงแต่อาหารอร่อยเท่านั้น เจ้าของร้านยังใจดีอีกด้วย เลยไปบ่อยค่ะ',
      'Restoran itu tidak hanya makanannya enak, pemiliknya juga ramah, jadi saya sering ke sana.',
      'Nhà hàng đó không những đồ ăn ngon mà ông chủ cũng thân thiện nữa, nên tôi hay đến đó.',
      'あの食堂は料理がおいしいうえに、店長さんも親切なので、よく行きます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 뿐더러',
    sentence: '이번 프로젝트는 일정이 촉박할 뿐더러 예산까지 부족해서 정말 힘들었다.',
    trans: L(
      'This project not only had a tight schedule, but the budget was also short, so it was really tough.',
      'Este proyecto no solo tenía un calendario ajustado, sino que también faltaba presupuesto, así que fue realmente duro.',
      "Non seulement le calendrier de ce projet était serré, mais le budget manquait aussi, alors ç'a été vraiment difficile.",
      'Este projeto não só tinha um cronograma apertado, como também faltava orçamento, então foi realmente difícil.',
      'โปรเจกต์ครั้งนี้ไม่เพียงแต่กำหนดการกระชั้นชิดเท่านั้น งบประมาณยังไม่พออีก เลยลำบากมากจริง ๆ',
      'Proyek kali ini tidak hanya jadwalnya mepet, anggarannya pun kurang, jadi benar-benar berat.',
      'Dự án lần này không những lịch trình gấp gáp mà ngân sách cũng thiếu nữa, nên thật sự rất vất vả.',
      '今回のプロジェクトはスケジュールが厳しいうえに、予算まで足りなくて本当に大変だった。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 한편',
    sentence: '형은 회사에 다니는 한편 주말마다 봉사 활동도 해요.',
    trans: L(
      'My older brother works at a company while also volunteering every weekend.',
      'Mi hermano mayor trabaja en una empresa y, por otro lado, hace voluntariado cada fin de semana.',
      'Mon grand frère travaille dans une entreprise et, parallèlement, fait du bénévolat chaque week-end.',
      'Meu irmão mais velho trabalha numa empresa e, ao mesmo tempo, faz trabalho voluntário todo fim de semana.',
      'พี่ชายของฉันทำงานบริษัท ขณะเดียวกันก็ทำงานอาสาสมัครทุกสุดสัปดาห์ด้วย',
      'Di satu sisi kakak laki-laki saya bekerja di perusahaan, di sisi lain ia juga menjadi sukarelawan setiap akhir pekan.',
      'Anh trai tôi một mặt đi làm ở công ty, mặt khác còn đi làm tình nguyện vào mỗi cuối tuần.',
      '兄は会社に勤める一方で、毎週末ボランティア活動もしています。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 한편',
    sentence: '이번 정책은 일부 사람들에게 도움이 되는 한편 다른 사람들에게는 부담이 된다.',
    trans: L(
      'This policy helps some people while becoming a burden to others.',
      'Esta política, por un lado, ayuda a algunas personas; por otro, se convierte en una carga para otras.',
      "Cette politique, d'une part, aide certaines personnes ; d'autre part, elle devient un fardeau pour d'autres.",
      'Esta política, por um lado, ajuda algumas pessoas; por outro, torna-se um fardo para outras.',
      'นโยบายนี้ในด้านหนึ่งเป็นประโยชน์ต่อคนบางกลุ่ม ขณะเดียวกันก็เป็นภาระต่อคนอีกกลุ่มหนึ่ง',
      'Di satu sisi kebijakan ini membantu sebagian orang, di sisi lain menjadi beban bagi orang lain.',
      'Chính sách lần này một mặt giúp ích cho một số người, mặt khác lại trở thành gánh nặng cho những người khác.',
      '今回の政策は一部の人々には役立つ一方で、ほかの人々には負担になる。',
    ),
    level: 'formal',
  },
  {
    ko: '-은/는 물론이고',
    sentence: '주말에는 카페는 물론이고 식당도 사람이 너무 많아요.',
    trans: L(
      'On weekends, not only the cafes but the restaurants too are packed with people.',
      'Los fines de semana, no solo las cafeterías sino también los restaurantes están llenísimos de gente.',
      'Le week-end, non seulement les cafés mais aussi les restaurants sont bondés de monde.',
      'Nos fins de semana, não só os cafés mas também os restaurantes ficam cheíssimos de gente.',
      'ช่วงสุดสัปดาห์ ไม่ใช่แค่ร้านกาแฟ แต่ร้านอาหารก็คนเยอะมากเหมือนกัน',
      'Di akhir pekan, bukan hanya kafe, restoran pun penuh sesak.',
      'Vào cuối tuần, không chỉ quán cà phê mà nhà hàng cũng rất đông người.',
      '週末はカフェはもちろん、レストランも人がとても多いです。',
    ),
    level: 'polite',
  },
  {
    ko: '-은/는 물론이고',
    sentence: '그 배우는 연기는 물론이고 노래까지 잘해서 정말 부러워.',
    trans: L(
      "That actor is great at acting, not to mention singing too, so I'm really jealous.",
      'Ese actor actúa genial, y por si fuera poco también canta bien, así que de verdad le tengo envidia.',
      "Cet acteur joue très bien, sans parler du chant qu'il maîtrise aussi, du coup je suis vraiment jaloux.",
      'Aquele ator atua muito bem, sem falar que ainda canta bem, então fico com inveja de verdade.',
      'นักแสดงคนนั้นแสดงเก่งอยู่แล้ว ยังร้องเพลงเก่งอีกด้วย เลยอิจฉาจริง ๆ',
      'Aktor itu bukan hanya jago akting, nyanyi pun jago, jadi aku benar-benar iri.',
      'Diễn viên đó diễn xuất giỏi là đương nhiên, đến cả hát cũng hay nữa nên tớ ghen tị thật sự.',
      'あの俳優は演技はもちろん、歌まで上手だから本当にうらやましい。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 바람에',
    sentence: '버스를 놓치는 바람에 약속에 늦었어요.',
    trans: L(
      'I missed the bus, so I ended up being late for the appointment.',
      'Como perdí el autobús, terminé llegando tarde a la cita.',
      "J'ai raté le bus, du coup je suis arrivé en retard au rendez-vous.",
      'Como perdi o ônibus, acabei me atrasando para o compromisso.',
      'เพราะพลาดรถบัส เลยไปสายตามนัด',
      'Gara-gara ketinggalan bus, aku jadi terlambat ke janji temu.',
      'Vì lỡ chuyến xe buýt nên tôi đã đến trễ cuộc hẹn.',
      'バスに乗り遅れたせいで、約束に遅れてしまいました。',
    ),
    level: 'polite',
  },
  {
    ko: '-는 바람에',
    sentence: '옆집에서 밤새 공사를 하는 바람에 한숨도 못 잤어.',
    trans: L(
      "The neighbors were doing construction all night, so I couldn't sleep a wink.",
      'Como en la casa de al lado estuvieron de obras toda la noche, no pegué ojo.',
      "À cause des travaux des voisins toute la nuit, je n'ai pas fermé l'œil.",
      'Por causa da obra do vizinho a noite toda, não preguei o olho.',
      'บ้านข้าง ๆ ก่อสร้างทั้งคืน เลยนอนไม่หลับเลย',
      'Gara-gara tetangga sebelah renovasi semalaman, aku jadi tidak tidur sama sekali.',
      'Vì nhà bên cạnh thi công cả đêm nên tớ chẳng ngủ được tí nào.',
      '隣の家が一晩中工事をしたせいで、一睡もできなかった。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 통에',
    sentence: '옆집에서 밤새 공사를 하는 통에 한숨도 못 잤습니다.',
    trans: L(
      "Because the people next door were doing construction all night, I couldn't sleep a wink.",
      'Como los vecinos estuvieron de obras toda la noche, no pude pegar ojo.',
      "Comme les voisins faisaient des travaux toute la nuit, je n'ai pas pu fermer l'œil.",
      'Como os vizinhos ficaram em obras a noite toda, não consegui pregar o olho.',
      'เพราะบ้านข้างๆ ก่อสร้างกันทั้งคืน ฉันเลยนอนไม่หลับเลยสักนิด',
      'Gara-gara tetangga sebelah melakukan konstruksi semalaman, aku tidak bisa tidur sama sekali.',
      'Vì nhà bên cạnh thi công suốt đêm nên tôi không chợp mắt được chút nào.',
      '隣の家が一晩中工事をするせいで、一睡もできませんでした。',
    ),
    level: 'formal',
  },
  {
    ko: '-는 통에',
    sentence: '사람들이 갑자기 몰려드는 통에 지갑을 잃어버렸어.',
    trans: L(
      'In the chaos of people suddenly swarming in, I lost my wallet.',
      'Con el lío de la gente que de repente se amontonó, perdí la cartera.',
      "Dans la cohue des gens qui se sont soudain pressés, j'ai perdu mon portefeuille.",
      'Naquela confusão de gente que de repente se amontoou, perdi a carteira.',
      'เพราะผู้คนกรูเข้ามาอย่างกะทันหันจนวุ่นวาย ฉันเลยทำกระเป๋าสตางค์หาย',
      'Gara-gara orang-orang tiba-tiba berkerumun dan ribut, dompetku hilang.',
      'Giữa lúc người ta đột nhiên chen lấn ùa vào, tớ làm mất cái ví.',
      '人が急に押し寄せるどさくさで、財布をなくしちゃった。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 텐데',
    sentence: '지금 출발하면 길이 많이 막힐 텐데 지하철로 가는 게 어때요?',
    trans: L(
      'If we leave now the roads will probably be jammed — how about taking the subway instead?',
      'Si salimos ahora seguramente habrá mucho tráfico, ¿qué tal si vamos en metro?',
      'Si on part maintenant, il y aura sûrement beaucoup de bouchons, alors pourquoi pas le métro ?',
      'Se sairmos agora o trânsito deve estar bem ruim, que tal irmos de metrô?',
      'ถ้าออกเดินทางตอนนี้รถน่าจะติดมาก ไปรถไฟใต้ดินดีไหม',
      'Kalau berangkat sekarang jalanan pasti macet, bagaimana kalau naik kereta bawah tanah saja?',
      'Bây giờ mà đi thì chắc đường sẽ kẹt xe lắm, hay là mình đi tàu điện ngầm nhé?',
      '今出発したら道がかなり混むだろうに、地下鉄で行くのはどう？',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 텐데',
    sentence: '내일 시험인데 친구가 아직도 공부를 안 하네. 분명 후회할 텐데.',
    trans: L(
      "The exam's tomorrow but my friend still isn't studying. He's definitely going to regret it.",
      'El examen es mañana y mi amigo todavía no estudia. Seguro que se va a arrepentir.',
      "L'examen est demain mais mon ami n'étudie toujours pas. Il va sûrement le regretter.",
      'A prova é amanhã, mas meu amigo ainda não está estudando. Com certeza vai se arrepender.',
      'พรุ่งนี้สอบแล้วแต่เพื่อนยังไม่อ่านหนังสือเลย เดี๋ยวต้องเสียใจแน่ ๆ',
      'Besok ujian tapi temanku masih belum belajar juga. Pasti nanti dia menyesal.',
      'Mai thi rồi mà bạn tôi vẫn chưa học gì cả. Chắc chắn rồi sẽ hối hận cho xem.',
      '明日試験なのに友達はまだ勉強してないなあ。きっと後悔するだろうに。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 리가 없다',
    sentence: '민수가 벌써 집에 갔을 리가 없어요. 아까 도서관에서 봤는데요.',
    trans: L(
      "There's no way Minsu has already gone home. I just saw him at the library.",
      'No puede ser que Minsu ya se haya ido a casa. Lo acabo de ver en la biblioteca.',
      'Il est impossible que Minsu soit déjà rentré chez lui. Je viens de le voir à la bibliothèque.',
      'Não tem como o Minsu já ter ido para casa. Acabei de vê-lo na biblioteca.',
      'มินซูจะกลับบ้านไปแล้วไม่ได้หรอก เมื่อกี้ฉันเพิ่งเห็นเขาที่ห้องสมุด',
      'Tidak mungkin Minsu sudah pulang. Tadi aku baru saja melihatnya di perpustakaan.',
      'Không thể nào Minsu đã về nhà rồi. Lúc nãy mình vừa thấy cậu ấy ở thư viện mà.',
      'ミンスがもう家に帰ったはずがありません。さっき図書館で見かけたんですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 리가 없다',
    sentence: '이렇게 열심히 공부했는데 시험에 떨어질 리가 없어.',
    trans: L(
      "I studied this hard, so there's no way I'll fail the exam.",
      'Estudié tantísimo, así que es imposible que suspenda el examen.',
      "J'ai étudié si dur, il n'y a aucune chance que je rate l'examen.",
      'Estudei tanto, não tem como eu reprovar na prova.',
      'ตั้งใจอ่านหนังสือขนาดนี้ จะสอบตกไม่ได้หรอก',
      'Aku sudah belajar segiat ini, tidak mungkin aku gagal ujian.',
      'Mình đã học chăm chỉ thế này thì không thể nào trượt kỳ thi được.',
      'こんなに一生懸命勉強したんだから、試験に落ちるはずがない。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ걸 그랬다',
    sentence: '표를 미리 예매할걸 그랬어요.',
    trans: L(
      'I should have booked the tickets in advance.',
      'Debería haber reservado las entradas con antelación.',
      "J'aurais dû réserver les billets à l'avance.",
      'Eu deveria ter reservado os ingressos com antecedência.',
      'น่าจะจองตั๋วไว้ล่วงหน้าก็ดี',
      'Seharusnya aku memesan tiketnya jauh-jauh hari.',
      'Lẽ ra tôi nên đặt vé trước thì hơn.',
      'チケットを前もって予約しておけばよかった。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ걸 그랬다',
    sentence: '어제 일찍 잘걸 그랬다.',
    trans: L(
      'I should have gone to bed early yesterday.',
      'Debería haberme acostado temprano ayer.',
      "J'aurais dû me coucher tôt hier.",
      'Eu deveria ter dormido cedo ontem.',
      'เมื่อวานน่าจะนอนเร็วก็ดี',
      'Seharusnya aku tidur lebih awal kemarin.',
      'Lẽ ra hôm qua mình nên đi ngủ sớm.',
      '昨日早く寝ればよかった。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 것을 보니',
    sentence: '하늘이 잔뜩 흐린 것을 보니 곧 비가 오겠어요.',
    trans: L(
      "Judging by how overcast the sky is, it looks like it'll rain soon.",
      'Viendo lo nublado que está el cielo, parece que pronto va a llover.',
      'Vu à quel point le ciel est couvert, il va sûrement pleuvoir bientôt.',
      'Pelo céu tão nublado, parece que vai chover logo.',
      'ดูจากที่ท้องฟ้ามืดครึ้มขนาดนี้ อีกเดี๋ยวคงจะฝนตกแล้วล่ะ',
      'Melihat langit yang begitu mendung, sepertinya sebentar lagi akan hujan.',
      'Nhìn bầu trời âm u thế này, chắc sắp mưa rồi.',
      '空がすっかり曇っているのを見ると、もうすぐ雨が降りそうですね。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 것을 보니',
    sentence: '민수가 밥을 두 그릇이나 먹는 걸 보니 배가 많이 고팠나 봐.',
    trans: L(
      "Seeing Minsu eat two whole bowls, he must've been really hungry.",
      'Viendo que Minsu se está comiendo dos platos enteros, debía de tener mucha hambre.',
      'À voir Minsu manger deux bols entiers, il devait avoir vraiment faim.',
      'Vendo o Minsu comer dois pratos inteiros, ele devia estar com muita fome.',
      'ดูจากที่มินซูกินตั้งสองชาม เขาคงหิวมากเลยแหละ',
      'Melihat Minsu makan sampai dua mangkuk, dia pasti tadi sangat lapar.',
      'Nhìn Minsu ăn tận hai bát, chắc cậu ấy đói lắm.',
      'ミンスがご飯を二杯も食べるのを見ると、よっぽどお腹が空いていたみたいだね。',
    ),
    level: 'casual',
  },
  {
    ko: '-다가',
    sentence: '집에 가다가 친구를 만났어요.',
    trans: L(
      'On my way home, I ran into a friend.',
      'Yendo a casa, me encontré con un amigo.',
      "En rentrant à la maison, j'ai croisé un ami.",
      'Indo para casa, encontrei um amigo.',
      'ระหว่างทางกลับบ้าน ฉันบังเอิญเจอเพื่อน',
      'Dalam perjalanan pulang, saya bertemu teman.',
      'Đang trên đường về nhà thì tôi gặp một người bạn.',
      '家に帰る途中で友達に会いました。',
    ),
    level: 'polite',
  },
  {
    ko: '-다가',
    sentence: '텔레비전을 보다가 갑자기 전화가 왔어.',
    trans: L(
      'I was watching TV when suddenly the phone rang.',
      'Estaba viendo la tele cuando de repente sonó el teléfono.',
      'Je regardais la télé quand soudain le téléphone a sonné.',
      'Eu estava vendo TV quando de repente o telefone tocou.',
      'กำลังดูทีวีอยู่ จู่ ๆ ก็มีโทรศัพท์เข้ามา',
      'Lagi nonton TV, tiba-tiba ada telepon masuk.',
      'Đang xem tivi thì bỗng có điện thoại gọi đến.',
      'テレビを見ていたら、突然電話がかかってきた。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 척하다',
    sentence: '동생이 자는 척해서 깨우기가 좀 그래요.',
    trans: L(
      'My little brother is pretending to be asleep, so it feels a bit awkward to wake him up.',
      'Mi hermano menor finge estar dormido, así que da un poco de cosa despertarlo.',
      "Mon petit frère fait semblant de dormir, alors c'est un peu gênant de le réveiller.",
      'Meu irmão mais novo está fingindo que está dormindo, então fico meio sem jeito de acordá-lo.',
      'น้องชายแกล้งทำเป็นหลับ เลยรู้สึกกระดากนิดหน่อยที่จะปลุก',
      'Adik laki-lakiku pura-pura tidur, jadi agak sungkan untuk membangunkannya.',
      'Em trai tôi giả vờ ngủ nên hơi ngại đánh thức nó dậy.',
      '弟が寝ているふりをしているので、起こすのがちょっと気まずいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 척하다',
    sentence: '많이 아프면서 괜찮은 척하지 마.',
    trans: L(
      "You're clearly in pain, so don't pretend you're fine.",
      'Se nota que te duele, así que no finjas que estás bien.',
      'On voit bien que tu as mal, alors ne fais pas comme si tout allait bien.',
      'Dá pra ver que está doendo, então não finja que está tudo bem.',
      'เห็นชัดว่าเจ็บ อย่าแกล้งทำเป็นว่าไม่เป็นไรสิ',
      'Kelihatan banget kamu kesakitan, jadi jangan pura-pura baik-baik saja.',
      'Rõ ràng là đau mà, đừng giả vờ là không sao nữa.',
      '痛いくせに、平気なふりをしないで。',
    ),
    level: 'casual',
  },
  {
    ko: '-게 하다',
    sentence: '엄마가 동생에게 방을 청소하게 했어요.',
    trans: L(
      'Mom made my younger sibling clean the room.',
      'Mamá hizo que mi hermano menor limpiara la habitación.',
      'Maman a fait nettoyer la chambre à mon petit frère.',
      'A mamãe fez meu irmão mais novo limpar o quarto.',
      'แม่ให้น้องทำความสะอาดห้อง',
      'Ibu menyuruh adik membersihkan kamar.',
      'Mẹ bắt em tôi dọn dẹp phòng.',
      '母が弟に部屋を掃除させました。',
    ),
    level: 'polite',
  },
  {
    ko: '-게 하다',
    sentence: '그 영화가 나를 많이 울게 했어.',
    trans: L(
      'That movie made me cry a lot.',
      'Esa película me hizo llorar mucho.',
      "Ce film m'a fait beaucoup pleurer.",
      'Aquele filme me fez chorar muito.',
      'หนังเรื่องนั้นทำให้ฉันร้องไห้หนักมาก',
      'Film itu membuatku menangis banyak.',
      'Bộ phim đó làm tôi khóc rất nhiều.',
      'あの映画は私をすごく泣かせた。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 대로',
    sentence: '공항에 도착하는 대로 바로 전화드릴게요.',
    trans: L(
      "I'll call you right away as soon as I arrive at the airport.",
      'Te llamaré en cuanto llegue al aeropuerto.',
      "Je vous appellerai dès que j'arriverai à l'aéroport.",
      'Eu ligo para você assim que eu chegar no aeroporto.',
      'พอไปถึงสนามบินปุ๊บ ฉันจะโทรหาคุณทันทีเลยนะ',
      'Begitu sampai di bandara, saya akan langsung menelepon Anda.',
      'Vừa đến sân bay là tôi sẽ gọi điện cho anh ngay.',
      '空港に着き次第すぐにお電話しますね。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 대로',
    sentence: '설명서에 적힌 대로 조립했더니 문제가 없었습니다.',
    trans: L(
      'When I assembled it exactly as written in the manual, there were no problems.',
      'Cuando lo monté tal como estaba escrito en el manual, no hubo ningún problema.',
      "Quand je l'ai assemblé exactement comme indiqué dans le manuel, il n'y a eu aucun problème.",
      'Quando montei exatamente como estava escrito no manual, não houve nenhum problema.',
      'พอประกอบตามที่เขียนไว้ในคู่มือ ก็ไม่มีปัญหาอะไรเลย',
      'Setelah saya merakitnya persis seperti yang tertulis di buku petunjuk, tidak ada masalah.',
      'Khi tôi lắp ráp đúng như những gì được ghi trong hướng dẫn thì không có vấn đề gì cả.',
      '説明書に書かれているとおりに組み立てたところ、問題はありませんでした。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ 만하다',
    sentence: '그 식당은 한번 가 볼 만해요.',
    trans: L(
      'That restaurant is worth going to once.',
      'Ese restaurante vale la pena visitarlo una vez.',
      "Ce restaurant vaut la peine d'y aller une fois.",
      'Esse restaurante vale a pena ir uma vez.',
      'ร้านอาหารร้านนั้นน่าไปลองสักครั้ง',
      'Restoran itu layak dikunjungi sekali.',
      'Nhà hàng đó đáng để đến thử một lần.',
      'あの食堂は一度行ってみる価値がありますよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 만하다',
    sentence: '오늘은 그렇게 안 추워서 밖에서 좀 걸을 만해.',
    trans: L(
      "It's not that cold today, so walking outside a bit is bearable.",
      'Hoy no hace tanto frío, así que caminar un poco afuera se aguanta.',
      "Il ne fait pas si froid aujourd'hui, donc marcher un peu dehors, ça va.",
      'Hoje não está tão frio, então dá para caminhar um pouco lá fora.',
      'วันนี้ไม่หนาวเท่าไร เลยพอจะเดินเล่นข้างนอกได้อยู่',
      'Hari ini tidak terlalu dingin, jadi jalan-jalan di luar sebentar masih lumayan.',
      'Hôm nay không lạnh lắm nên đi bộ một chút ngoài trời cũng chịu được.',
      '今日はそんなに寒くないから、外を少し歩くくらいなら大丈夫だよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 정도로',
    sentence: '배가 아플 정도로 많이 웃었어요.',
    trans: L(
      'I laughed so hard my stomach hurt.',
      'Me reí tanto que me dolía el estómago.',
      "J'ai ri au point d'en avoir mal au ventre.",
      'Eu ri tanto que minha barriga doeu.',
      'หัวเราะหนักจนปวดท้องเลย',
      'Aku tertawa sampai perutku sakit.',
      'Tôi cười đến mức đau cả bụng.',
      'お腹が痛くなるほど大笑いしました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 정도로',
    sentence: '그 가수는 모르는 사람이 없을 정도로 유명해.',
    trans: L(
      "That singer is so famous that there's nobody who doesn't know them.",
      'Ese cantante es tan famoso que no hay nadie que no lo conozca.',
      "Ce chanteur est célèbre au point qu'il n'y a personne qui ne le connaisse pas.",
      'Esse cantor é tão famoso que não há ninguém que não o conheça.',
      'นักร้องคนนั้นดังจนไม่มีใครไม่รู้จักเลย',
      'Penyanyi itu terkenal sampai tidak ada orang yang tidak mengenalnya.',
      'Ca sĩ đó nổi tiếng đến mức không ai là không biết.',
      'あの歌手は知らない人がいないほど有名だよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-기에 앞서',
    sentence: '회의를 시작하기에 앞서 지난 회의록을 잠깐 검토하겠습니다.',
    trans: L(
      'Before beginning the meeting, I will briefly review the previous meeting minutes.',
      'Antes de comenzar la reunión, revisaré brevemente el acta de la reunión anterior.',
      'Avant de commencer la réunion, je vais brièvement examiner le compte rendu de la réunion précédente.',
      'Antes de iniciar a reunião, vou revisar brevemente a ata da reunião anterior.',
      'ก่อนจะเริ่มการประชุม ผมจะขอทบทวนรายงานการประชุมครั้งก่อนสักครู่',
      'Sebelum memulai rapat, saya akan meninjau sebentar notulen rapat sebelumnya.',
      'Trước khi bắt đầu cuộc họp, tôi sẽ xem lại biên bản cuộc họp lần trước một chút.',
      '会議を始めるに先立ち、前回の議事録を少し確認いたします。',
    ),
    level: 'formal',
  },
  {
    ko: '-기에 앞서',
    sentence: '본격적인 등산을 하기에 앞서 가벼운 준비 운동을 하는 게 좋아요.',
    trans: L(
      "Before doing the actual hiking, it's a good idea to do some light warm-up exercises.",
      'Antes de empezar a hacer senderismo en serio, conviene hacer algunos ejercicios de calentamiento ligeros.',
      "Avant de partir vraiment en randonnée, il vaut mieux faire quelques exercices d'échauffement légers.",
      'Antes de começar a trilha de verdade, é bom fazer alguns exercícios leves de aquecimento.',
      'ก่อนจะเริ่มเดินป่าจริงจัง ควรอบอุ่นร่างกายเบา ๆ สักหน่อยจะดีกว่า',
      'Sebelum benar-benar mulai mendaki, sebaiknya lakukan sedikit pemanasan ringan.',
      'Trước khi thực sự bắt đầu leo núi, nên khởi động nhẹ một chút thì tốt hơn.',
      '本格的に登山をするに先立って、軽い準備運動をするのがいいですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었더라면',
    sentence: '조금만 일찍 출발했더라면 기차를 놓치지 않았을 텐데.',
    trans: L(
      "If only I had left a little earlier, I wouldn't have missed the train.",
      'Si hubiera salido un poco antes, no habría perdido el tren.',
      "Si seulement j'étais parti un peu plus tôt, je n'aurais pas raté le train.",
      'Se eu tivesse saído um pouco mais cedo, não teria perdido o trem.',
      'ถ้าออกเดินทางเร็วกว่านี้สักหน่อยก็คงไม่พลาดรถไฟหรอก',
      'Seandainya aku berangkat sedikit lebih awal, aku tidak akan ketinggalan kereta.',
      'Giá mà tôi xuất phát sớm hơn một chút thì đã không lỡ chuyến tàu.',
      'もう少し早く出発していたら、電車に乗り遅れなかったのに。',
    ),
    level: 'casual',
  },
  {
    ko: '-았/었더라면',
    sentence: '그날 우산을 챙겼더라면 비를 안 맞았을 거예요.',
    trans: L(
      "If I had brought an umbrella that day, I wouldn't have gotten rained on.",
      'Si hubiera llevado un paraguas ese día, no me habría mojado con la lluvia.',
      "Si j'avais pris un parapluie ce jour-là, je ne me serais pas fait mouiller par la pluie.",
      'Se eu tivesse levado um guarda-chuva naquele dia, não teria me molhado na chuva.',
      'ถ้าวันนั้นเอาร่มไปด้วยก็คงไม่โดนฝนหรอกค่ะ',
      'Seandainya hari itu saya membawa payung, saya tidak akan kehujanan.',
      'Giá mà hôm đó tôi mang theo ô thì đã không bị dính mưa.',
      'あの日傘を持って行っていたら、雨に濡れなかったでしょう。',
    ),
    level: 'polite',
  },
  {
    ko: '-ㄴ/는다는 것이',
    sentence: '조용히 문을 닫는다는 것이 그만 쾅 닫아 버렸어요.',
    trans: L(
      'I meant to close the door quietly, but I ended up slamming it shut.',
      'Quería cerrar la puerta con cuidado, pero acabé dando un portazo.',
      "Je voulais fermer la porte doucement, mais j'ai fini par la claquer.",
      'Eu queria fechar a porta com cuidado, mas acabei batendo com força.',
      'ตั้งใจจะปิดประตูเบาๆ แต่กลับเผลอปิดดังปังเลย',
      'Niatnya menutup pintu pelan-pelan, malah membantingnya keras.',
      'Định đóng cửa nhẹ nhàng, không ngờ lại đóng sầm một cái.',
      'ドアを静かに閉めようとしたのに、つい思いきり閉めてしまいました。',
    ),
    level: 'polite',
  },
  {
    ko: '-ㄴ/는다는 것이',
    sentence: '커피에 설탕을 넣는다는 것이 그만 소금을 넣어 버렸다.',
    trans: L(
      'I meant to put sugar in the coffee, but I ended up putting in salt.',
      'Quería echarle azúcar al café, pero sin querer le eché sal.',
      "Je voulais mettre du sucre dans le café, mais j'ai fini par mettre du sel.",
      'Eu queria colocar açúcar no café, mas acabei colocando sal.',
      'จะใส่น้ำตาลลงในกาแฟ กลับเผลอใส่เกลือลงไปแทน',
      'Niatnya menambahkan gula ke kopi, malah memasukkan garam.',
      'Định cho đường vào cà phê, không ngờ lại cho nhầm muối.',
      'コーヒーに砂糖を入れようとして、うっかり塩を入れてしまった。',
    ),
    level: 'casual',
  },
  {
    ko: '-고서야',
    sentence: '병원에 가고서야 그게 큰 병이라는 걸 알았어요.',
    trans: L(
      'It was only after going to the hospital that I realized it was a serious illness.',
      'Solo después de ir al hospital me di cuenta de que era una enfermedad grave.',
      "Ce n'est qu'après être allé à l'hôpital que j'ai compris que c'était une maladie grave.",
      'Só depois de ir ao hospital é que percebi que era uma doença grave.',
      'หลังจากไปโรงพยาบาลแล้วฉันถึงได้รู้ว่ามันเป็นโรคร้ายแรง',
      'Baru setelah pergi ke rumah sakit aku sadar bahwa itu penyakit serius.',
      'Mãi đến khi đi bệnh viện tôi mới biết đó là một căn bệnh nặng.',
      '病院に行ってからやっと、それが大きな病気だと分かりました。',
    ),
    level: 'polite',
  },
  {
    ko: '-고서야',
    sentence: '직접 키워 보고서야 부모님의 마음을 이해하게 됐어.',
    trans: L(
      "It was only after raising a child myself that I came to understand my parents' feelings.",
      'Solo después de criar a un hijo yo mismo llegué a entender los sentimientos de mis padres.',
      "Ce n'est qu'après avoir élevé un enfant moi-même que j'ai fini par comprendre les sentiments de mes parents.",
      'Só depois de criar um filho eu mesmo é que passei a entender os sentimentos dos meus pais.',
      'หลังจากที่ได้เลี้ยงลูกด้วยตัวเองฉันถึงได้เข้าใจความรู้สึกของพ่อแม่',
      'Baru setelah membesarkan anak sendiri aku jadi mengerti perasaan orang tuaku.',
      'Mãi đến khi tự mình nuôi con tôi mới hiểu được tấm lòng của bố mẹ.',
      '自分で育ててみてからやっと、両親の気持ちが分かるようになった。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 빠지다',
    sentence: '이 국이 싱거워 빠져서 도저히 못 먹겠어.',
    trans: L(
      "This soup is so utterly bland I really can't eat it.",
      'Esta sopa está tan sosa que de verdad no puedo comérmela.',
      "Cette soupe est tellement fade que je n'arrive vraiment pas à la manger.",
      'Essa sopa está tão sem graça que eu realmente não consigo comer.',
      'ซุปนี้จืดสนิทจนกินไม่ลงเลยจริง ๆ',
      'Sup ini hambar sekali sampai aku benar-benar tidak bisa memakannya.',
      'Món canh này nhạt toẹt đến mức tôi thật sự không thể ăn nổi.',
      'このスープは味が薄くてしょうがなくて、とても食べられないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 빠지다',
    sentence: '그 가방은 낡아 빠져서 이제 그만 버리는 게 좋겠어요.',
    trans: L(
      "That bag is so worn out that it'd be better to just throw it away now.",
      'Ese bolso está tan gastado que sería mejor tirarlo ya.',
      "Ce sac est tellement usé qu'il vaudrait mieux le jeter maintenant.",
      'Aquela bolsa está tão surrada que seria melhor jogá-la fora agora.',
      'กระเป๋าใบนั้นเก่าจนเปื่อย ทิ้งไปเลยน่าจะดีกว่า',
      'Tas itu sudah usang sekali, lebih baik dibuang saja sekarang.',
      'Cái túi đó cũ nát hết rồi, giờ bỏ đi thì tốt hơn.',
      'そのカバンは古ぼけてしまっているので、もう捨てたほうがいいですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 치우다',
    sentence: '쌓인 설거지를 한꺼번에 다 해 치웠어.',
    trans: L(
      'I just knocked out all the piled-up dishes in one go.',
      'Me despaché de una vez todos los platos acumulados.',
      "J'ai expédié d'un coup toute la vaisselle qui s'était accumulée.",
      'Dei conta de toda a louça acumulada de uma vez só.',
      'จัดการล้างจานที่กองอยู่ให้เสร็จรวดเดียวเลย',
      'Aku langsung beresin semua cucian piring yang menumpuk sekaligus.',
      'Tớ giải quyết hết đống bát đĩa chất đống một lèo cho xong luôn.',
      'たまった洗い物を一気に全部やってしまった。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 치우다',
    sentence: '남은 음식은 그냥 다 먹어 치웠어요.',
    trans: L(
      'I just ate up all the leftover food.',
      'Me comí todas las sobras de una vez.',
      "J'ai mangé tous les restes d'un coup.",
      'Comi todas as sobras de uma vez.',
      'อาหารที่เหลือ ฉันก็จัดการกินให้หมดเลย',
      'Sisa makanannya langsung kuhabiskan semua.',
      'Đồ ăn còn thừa tôi ăn sạch hết luôn rồi.',
      '残った料理は全部食べてしまいました。',
    ),
    level: 'polite',
  },
  {
    ko: '-고 말겠다',
    sentence: '올해는 담배를 반드시 끊고 말겠어.',
    trans: L(
      "This year I'm going to quit smoking for good, no matter what.",
      'Este año voy a dejar de fumar sí o sí, pase lo que pase.',
      "Cette année, j'arrêterai de fumer coûte que coûte.",
      'Este ano eu vou parar de fumar de vez, custe o que custar.',
      'ปีนี้ฉันจะเลิกบุหรี่ให้ได้ ไม่ว่าจะยังไงก็ตาม',
      'Tahun ini aku pasti akan berhenti merokok, apa pun yang terjadi.',
      'Năm nay tôi nhất định sẽ bỏ thuốc lá cho bằng được.',
      '今年こそ絶対にタバコをやめてみせる。',
    ),
    level: 'casual',
  },
  {
    ko: '-고 말겠다',
    sentence: '어떤 어려움이 있어도 저는 이 회사를 꼭 성공시키고 말겠습니다.',
    trans: L(
      'No matter what difficulties arise, I will make this company succeed, without fail.',
      'Por más dificultades que haya, haré que esta empresa tenga éxito sin falta.',
      'Quelles que soient les difficultés, je ferai réussir cette entreprise, sans faute.',
      'Não importa as dificuldades que surjam, vou fazer esta empresa ter sucesso, sem falta.',
      'ไม่ว่าจะมีอุปสรรคใด ผมจะทำให้บริษัทนี้ประสบความสำเร็จให้จงได้',
      'Apa pun kesulitan yang ada, saya pasti akan membuat perusahaan ini sukses.',
      'Dù có khó khăn gì đi nữa, tôi nhất định sẽ làm cho công ty này thành công cho bằng được.',
      'どんな困難があっても、私はこの会社を必ず成功させてみせます。',
    ),
    level: 'formal',
  },
  {
    ko: '-았/었어야 했다',
    sentence: '어제 약을 먹었어야 했는데 깜빡했어요.',
    trans: L(
      'I should have taken my medicine yesterday, but I forgot.',
      'Debería haber tomado la medicina ayer, pero se me olvidó.',
      "J'aurais dû prendre mon médicament hier, mais j'ai oublié.",
      'Eu deveria ter tomado o remédio ontem, mas esqueci.',
      'เมื่อวานฉันควรจะกินยาแต่ดันลืมไป',
      'Kemarin aku seharusnya minum obat, tapi malah lupa.',
      'Hôm qua mình đáng lẽ phải uống thuốc mà lại quên mất.',
      '昨日、薬を飲むべきだったのに、うっかり忘れてしまいました。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었어야 했다',
    sentence: '그때 너한테 솔직하게 말했어야 했어.',
    trans: L(
      'I should have been honest with you back then.',
      'En ese momento debería haber sido sincero contigo.',
      "À ce moment-là, j'aurais dû être honnête avec toi.",
      'Naquela hora, eu deveria ter sido sincero com você.',
      'ตอนนั้นฉันน่าจะพูดกับเธอตามตรง',
      'Waktu itu aku seharusnya jujur sama kamu.',
      'Lúc đó đáng lẽ mình phải nói thật với cậu.',
      'あのとき、君に正直に言うべきだったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 테니까',
    sentence: '지금쯤 길이 막힐 테니까 지하철로 가는 게 좋겠습니다.',
    trans: L(
      'The roads must be jammed by now, so it would be better to take the subway.',
      'A esta hora seguro hay atasco, así que será mejor ir en metro.',
      'Les routes doivent être embouteillées à cette heure, donc il vaudrait mieux prendre le métro.',
      'A esta hora o trânsito deve estar parado, então é melhor ir de metrô.',
      'ตอนนี้รถน่าจะติดแล้ว ฉะนั้นไปด้วยรถไฟใต้ดินน่าจะดีกว่าครับ',
      'Jalanan pasti sudah macet sekarang, jadi lebih baik naik kereta bawah tanah.',
      'Giờ này đường chắc đang kẹt rồi, nên đi tàu điện ngầm thì hơn.',
      '今ごろ道が混んでいるでしょうから、地下鉄で行くのがよさそうです。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ 테니까',
    sentence: '내가 먼저 가서 자리 잡고 있을 테니까 천천히 와.',
    trans: L(
      "I'll go ahead and save us a spot, so take your time coming.",
      'Voy yendo primero y guardo el sitio, así que ven con calma.',
      "J'y vais en premier et je garde une place, alors prends ton temps pour venir.",
      'Eu vou na frente e guardo um lugar, então venha com calma.',
      'เดี๋ยวเราไปก่อนแล้วจองที่ไว้ให้ ฉะนั้นค่อย ๆ มานะ',
      'Aku duluan dan mengamankan tempat, jadi datanglah pelan-pelan saja.',
      'Tớ đi trước giữ chỗ rồi, nên cậu cứ thong thả mà đến.',
      '私が先に行って席を取っておくから、ゆっくり来てね。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ 채(로)',
    sentence: '창문을 열어 둔 채로 외출해서 방이 추워졌어요.',
    trans: L(
      'I went out leaving the window open, so the room got cold.',
      'Salí dejando la ventana abierta, así que el cuarto se enfrió.',
      'Je suis sorti en laissant la fenêtre ouverte, alors la pièce est devenue froide.',
      'Saí deixando a janela aberta, então o quarto esfriou.',
      'ออกไปข้างนอกทั้งที่เปิดหน้าต่างทิ้งไว้ ห้องเลยเย็นเฉียบ',
      'Saya pergi keluar dengan jendela dibiarkan terbuka, jadi kamarnya jadi dingin.',
      'Tôi ra ngoài trong khi vẫn để cửa sổ mở, nên phòng bị lạnh.',
      '窓を開けたまま外出したので、部屋が寒くなりました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ 채(로)',
    sentence: '그는 눈을 감은 채 한참 동안 음악을 들었다.',
    trans: L(
      'He listened to music for a long while with his eyes closed.',
      'Escuchó música un buen rato con los ojos cerrados.',
      'Il a écouté de la musique un long moment, les yeux fermés.',
      'Ele ouviu música por um bom tempo com os olhos fechados.',
      'เขาฟังเพลงอยู่นานทั้งที่หลับตา',
      'Dia mendengarkan musik cukup lama dengan mata terpejam.',
      'Anh ấy nghe nhạc một hồi lâu trong khi vẫn nhắm mắt.',
      '彼は目を閉じたまま、しばらくの間音楽を聴いた。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는 김에',
    sentence: '청소하는 김에 창문도 닦았어요.',
    trans: L(
      'Since I was cleaning anyway, I wiped the windows too.',
      'Ya que estaba limpiando, también limpié las ventanas.',
      "Puisque je faisais le ménage, j'en ai profité pour laver les vitres aussi.",
      'Já que eu estava limpando mesmo, limpei as janelas também.',
      'ในเมื่อกำลังทำความสะอาดอยู่แล้ว ก็เลยเช็ดกระจกหน้าต่างไปด้วยเลย',
      'Mumpung sedang bersih-bersih, sekalian aku lap jendelanya juga.',
      'Nhân tiện đang dọn dẹp, tôi lau luôn cả cửa sổ.',
      '掃除するついでに窓も拭きました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 김에',
    sentence: '서울에 출장 온 김에 친구도 만나고 가려고.',
    trans: L(
      "Since I'm on a business trip in Seoul anyway, I'm gonna meet a friend before I head back.",
      'Ya que vine a Seúl por trabajo, voy a aprovechar para ver a un amigo antes de volver.',
      "Puisque je suis à Séoul pour le travail, j'en profite pour voir un ami avant de repartir.",
      'Já que vim a Seul a trabalho, vou aproveitar pra encontrar um amigo antes de voltar.',
      'ในเมื่อมาทำงานที่โซลแล้ว ก็จะถือโอกาสไปเจอเพื่อนก่อนกลับ',
      'Mumpung lagi dinas ke Seoul, sekalian mau ketemu teman dulu sebelum balik.',
      'Nhân tiện đi công tác ở Seoul, mình định gặp luôn bạn rồi mới về.',
      'ソウルに出張に来たついでに、友達にも会ってから帰るつもり。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 길에',
    sentence: '회사에 가는 길에 우체국에 잠깐 들렀어요.',
    trans: L(
      'On the way to work, I stopped by the post office for a moment.',
      'De camino al trabajo, pasé un momento por la oficina de correos.',
      'En allant au travail, je suis passé un instant à la poste.',
      'A caminho do trabalho, passei rapidinho nos correios.',
      'ระหว่างทางไปที่ทำงาน ฉันแวะที่ทำการไปรษณีย์สักครู่',
      'Dalam perjalanan ke kantor, aku mampir sebentar ke kantor pos.',
      'Trên đường đi làm, tôi ghé qua bưu điện một lát.',
      '会社に行く途中で郵便局にちょっと寄りました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 길에',
    sentence: '퇴근하는 길에 마트에 들러서 우유 좀 사 와.',
    trans: L(
      'On your way home from work, stop by the store and grab some milk.',
      'De camino a casa al salir del trabajo, pasa por el súper y trae leche.',
      'En rentrant du travail, passe au supermarché et rapporte du lait.',
      'Na volta do trabalho, passa no mercado e traz leite.',
      'ตอนขากลับจากที่ทำงาน แวะซื้อนมที่ซูเปอร์มาด้วยนะ',
      'Dalam perjalanan pulang kerja, mampir ke supermarket dan beli susu, ya.',
      'Trên đường đi làm về, ghé siêu thị mua ít sữa nhé.',
      '仕事から帰る途中でスーパーに寄って牛乳買ってきて。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 겸',
    sentence: '디자인 공부도 할 겸 미술관에 자주 가요.',
    trans: L(
      'I often go to the art museum, partly to study design too.',
      'Voy a menudo al museo de arte, en parte también para estudiar diseño.',
      "Je vais souvent au musée d'art, en partie pour étudier le design.",
      'Vou muito ao museu de arte, em parte para estudar design também.',
      'ฉันไปพิพิธภัณฑ์ศิลปะบ่อย ๆ ถือเป็นการเรียนรู้เรื่องดีไซน์ไปด้วย',
      'Aku sering ke museum seni, sekalian belajar desain juga.',
      'Tôi hay đến bảo tàng mỹ thuật, tiện thể học thêm về thiết kế.',
      'デザインの勉強も兼ねて、美術館によく行きます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 겸',
    sentence: '오랜만에 부모님도 뵐 겸 고향에 다녀왔습니다.',
    trans: L(
      'I went back to my hometown, also taking the chance to see my parents for the first time in a while.',
      'Volví a mi pueblo natal, aprovechando también para ver a mis padres después de mucho tiempo.',
      'Je suis retourné dans ma ville natale, en profitant aussi pour revoir mes parents après longtemps.',
      'Voltei à minha cidade natal, aproveitando também para ver meus pais depois de muito tempo.',
      'ผมกลับไปบ้านเกิด ถือโอกาสไปเยี่ยมพ่อแม่ที่ไม่ได้เจอกันนานด้วย',
      'Saya pulang ke kampung halaman, sekalian menemui orang tua yang sudah lama tidak bertemu.',
      'Tôi về quê, tiện thể thăm bố mẹ sau một thời gian dài không gặp.',
      '久しぶりに両親に会うのも兼ねて、故郷に行ってきました。',
    ),
    level: 'formal',
  },
  {
    ko: '-느라(고)',
    sentence: '아이를 돌보느라 점심도 못 먹었어요.',
    trans: L(
      "I couldn't even eat lunch because I was busy looking after the kids.",
      'No pude ni almorzar porque estuve cuidando a los niños.',
      "Je n'ai même pas pu déjeuner parce que je m'occupais des enfants.",
      'Nem consegui almoçar porque estava cuidando das crianças.',
      'ผมมัวแต่ดูแลลูกเลยไม่ได้กินข้าวกลางวันด้วยซ้ำ',
      'Saya bahkan tidak sempat makan siang karena sibuk mengurus anak-anak.',
      'Tôi bận trông con nên đến cả bữa trưa cũng không ăn được.',
      '子どもの世話をしていてお昼ご飯も食べられませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '-느라(고)',
    sentence: '어제 친구랑 노느라 숙제를 다 못 했어.',
    trans: L(
      "I was playing with my friend yesterday, so I didn't get all my homework done.",
      'Ayer estuve jugando con mi amigo y no terminé toda la tarea.',
      "Hier, j'ai joué avec mon ami, du coup je n'ai pas pu finir tous mes devoirs.",
      'Ontem fiquei brincando com meu amigo e não consegui terminar toda a lição.',
      'เมื่อวานมัวแต่เล่นกับเพื่อนเลยทำการบ้านไม่เสร็จ',
      'Kemarin aku asyik main sama teman, jadi PR-ku tidak selesai semua.',
      'Hôm qua mải chơi với bạn nên mình không làm hết bài tập.',
      '昨日友達と遊んでいて宿題を全部できなかった。',
    ),
    level: 'casual',
  },
  {
    ko: '-길래',
    sentence: '친구가 맛있다고 추천하길래 그 식당에 한번 가 봤어요.',
    trans: L(
      'My friend recommended it as delicious, so I gave that restaurant a try.',
      'Como mi amigo me lo recomendó diciendo que estaba rico, probé ese restaurante.',
      "Comme mon ami me l'a recommandé en disant que c'était bon, j'ai essayé ce restaurant.",
      'Como meu amigo recomendou dizendo que era gostoso, resolvi experimentar aquele restaurante.',
      'เพื่อนแนะนำว่าอร่อย ฉันเลยลองไปร้านอาหารนั้นดู',
      'Karena teman merekomendasikannya katanya enak, aku coba mampir ke restoran itu.',
      'Vì bạn tôi khen ngon và giới thiệu nên tôi đã thử đến nhà hàng đó.',
      '友達がおいしいと勧めてくれたので、そのお店に一度行ってみました。',
    ),
    level: 'polite',
  },
  {
    ko: '-길래',
    sentence: '동생이 자꾸 졸길래 일찍 재웠어.',
    trans: L(
      'My little brother kept dozing off, so I put him to bed early.',
      'Mi hermanito se quedaba dormido a cada rato, así que lo acosté temprano.',
      "Mon petit frère n'arrêtait pas de s'endormir, alors je l'ai couché tôt.",
      'Meu irmãozinho vivia cochilando, então o coloquei pra dormir cedo.',
      'น้องง่วงนอนตลอดเลย ฉันเลยพาไปนอนแต่หัวค่ำ',
      'Adikku terus mengantuk, jadi aku menidurkannya lebih awal.',
      'Em tôi cứ ngủ gà ngủ gật nên tôi cho nó đi ngủ sớm.',
      '弟がしきりに居眠りするので、早めに寝かせたよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-다가는',
    sentence: '운전하면서 자꾸 휴대폰을 보다가는 큰 사고가 날 거예요.',
    trans: L(
      "If you keep looking at your phone while driving, you'll end up causing a big accident.",
      'Si sigues mirando el móvil mientras conduces, vas a acabar provocando un accidente grave.',
      'Si tu continues à regarder ton téléphone en conduisant, tu finiras par provoquer un grave accident.',
      'Se você continuar olhando o celular enquanto dirige, vai acabar causando um acidente grave.',
      'ถ้ามัวแต่ดูโทรศัพท์ขณะขับรถอยู่แบบนี้ เดี๋ยวจะเกิดอุบัติเหตุร้ายแรงนะ',
      'Kalau kamu terus-terusan melihat ponsel sambil menyetir, nanti bisa terjadi kecelakaan parah.',
      'Cứ vừa lái xe vừa nhìn điện thoại như vậy là sẽ gây tai nạn lớn đấy.',
      '運転しながらしょっちゅうスマホを見ていると、大きな事故を起こしますよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-다가는',
    sentence: '돈을 그렇게 펑펑 쓰다가는 월급날도 되기 전에 다 떨어진다.',
    trans: L(
      "If you keep spending money so freely, it'll all be gone before payday even comes.",
      'Si sigues gastando el dinero tan a lo loco, se te acabará todo antes de que llegue el día de pago.',
      "Si tu continues à dépenser l'argent à tout-va, tu n'auras plus rien avant même le jour de paie.",
      'Se você continuar gastando dinheiro assim à toa, vai acabar tudo antes mesmo de chegar o dia do pagamento.',
      'ถ้าใช้เงินสุรุ่ยสุร่ายแบบนี้ต่อไป เงินจะหมดก่อนถึงวันเงินเดือนเลยนะ',
      'Kalau kamu terus boros begitu, uangnya bakal habis bahkan sebelum hari gajian tiba.',
      'Cứ tiêu tiền hoang phí như thế thì sẽ hết sạch trước cả ngày lãnh lương đấy.',
      'そんなにお金を湯水のように使っていると、給料日になる前に全部なくなるよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-다니(요)?',
    sentence: '벌써 시험이 끝났다니, 시간 진짜 빠르다.',
    trans: L(
      'The exams are already over? Time really flies.',
      '¿Que los exámenes ya terminaron? El tiempo vuela de verdad.',
      'Les examens sont déjà finis ? Le temps file vraiment.',
      'As provas já acabaram? O tempo voa mesmo.',
      'สอบจบแล้วเหรอเนี่ย เวลาผ่านไปเร็วจริง ๆ',
      'Ujiannya sudah selesai? Waktu benar-benar berlalu cepat.',
      'Kỳ thi đã kết thúc rồi sao? Thời gian trôi nhanh thật.',
      'もう試験が終わったなんて、時間が本当に早いね。',
    ),
    level: 'casual',
  },
  {
    ko: '-다니(요)?',
    sentence: '이렇게 어려운 문제를 혼자 다 풀었다니요? 정말 대단하네요.',
    trans: L(
      "You solved such a hard problem all by yourself? That's truly amazing.",
      '¿Resolviste un problema tan difícil tú solo? Es realmente impresionante.',
      "Vous avez résolu un problème aussi difficile tout seul ? C'est vraiment impressionnant.",
      'Você resolveu um problema tão difícil sozinho? Isso é realmente incrível.',
      'แก้โจทย์ยากขนาดนี้ได้คนเดียวเลยเหรอ สุดยอดจริง ๆ',
      'Anda menyelesaikan soal sesulit ini sendirian? Sungguh luar biasa.',
      'Bạn đã tự mình giải hết bài toán khó thế này sao? Thật sự đáng nể.',
      'こんなに難しい問題を一人で全部解いたなんて？本当にすごいですね。',
    ),
    level: 'polite',
  },
  {
    ko: '-다니까(요)',
    sentence: '내가 거기 가 봤다니까. 음식 진짜 별로였어.',
    trans: L(
      "I'm telling you, I've been there. The food really wasn't great.",
      'Que sí, ya estuve ahí. La comida de verdad no era para tanto.',
      "Je te dis que j'y suis allé. La nourriture n'était vraiment pas terrible.",
      'Já disse que eu fui lá. A comida realmente não era grande coisa.',
      'ก็บอกแล้วไงว่าฉันเคยไปที่นั่นมา อาหารไม่อร่อยจริง ๆ',
      'Sudah kubilang aku pernah ke sana. Makanannya benar-benar biasa saja.',
      'Đã bảo là tớ từng đến đó rồi mà. Đồ ăn thật sự chẳng ngon gì cả.',
      'あそこ行ってみたんだってば。料理、ほんとイマイチだったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-다니까(요)',
    sentence: '저 벌써 출발했다니까요. 조금만 더 기다려 주세요.',
    trans: L(
      "I'm telling you, I already left. Please wait just a little longer.",
      'Que ya salí, en serio. Espéreme solo un poquito más, por favor.',
      "Je vous dis que je suis déjà parti. Attendez encore un petit instant, s'il vous plaît.",
      'Já disse que eu já saí. Por favor, espere só mais um pouquinho.',
      'ก็บอกแล้วไงคะว่าออกมาแล้ว รบกวนรออีกนิดเดียวนะคะ',
      'Sudah saya bilang saya sudah berangkat. Tolong tunggu sebentar lagi ya.',
      'Đã bảo là em xuất phát rồi mà. Anh đợi thêm một chút nữa thôi nhé.',
      'もう出発したって言ってるじゃないですか。もう少しだけ待ってくださいね。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고(요)?',
    sentence: '내일부터 출근 안 한다고요?',
    trans: L(
      "You're saying you won't be coming to work starting tomorrow?",
      '¿Dices que a partir de mañana no vas a venir a trabajar?',
      "Tu dis qu'à partir de demain tu ne viens plus travailler ?",
      'Você está dizendo que a partir de amanhã não vai mais vir trabalhar?',
      'บอกว่าตั้งแต่พรุ่งนี้จะไม่มาทำงานเหรอ',
      'Katanya mulai besok kamu tidak masuk kerja?',
      'Bạn nói là từ ngày mai sẽ không đi làm nữa à?',
      '明日から仕事に来ないって言うんですか？',
    ),
    level: 'polite',
  },
  {
    ko: '-다고(요)?',
    sentence: '벌써 다 끝났다고?',
    trans: L(
      "You're saying it's already all finished?",
      '¿Dices que ya se terminó todo?',
      "Tu dis que c'est déjà complètement fini ?",
      'Você está dizendo que já acabou tudo?',
      'บอกว่าเสร็จหมดแล้วเหรอ',
      'Katanya semuanya sudah selesai?',
      'Cậu bảo là đã xong hết rồi á?',
      'もう全部終わったって？',
    ),
    level: 'casual',
  },
  {
    ko: '-다는 + N',
    sentence: '다음 주에 회의가 취소됐다는 메일을 받았어요.',
    trans: L(
      "I got an email saying next week's meeting was canceled.",
      'Recibí un correo que decía que la reunión de la próxima semana se canceló.',
      "J'ai reçu un e-mail disant que la réunion de la semaine prochaine était annulée.",
      'Recebi um e-mail dizendo que a reunião da próxima semana foi cancelada.',
      'ฉันได้รับอีเมลที่บอกว่าการประชุมสัปดาห์หน้าถูกยกเลิก',
      'Saya menerima email yang mengatakan bahwa rapat minggu depan dibatalkan.',
      'Tôi nhận được email báo rằng cuộc họp tuần sau đã bị hủy.',
      '来週の会議が中止になったというメールを受け取りました。',
    ),
    level: 'polite',
  },
  {
    ko: '-다는 + N',
    sentence: '친구가 곧 결혼한다는 말을 듣고 깜짝 놀랐어.',
    trans: L(
      'I was shocked to hear that my friend is getting married soon.',
      'Me quedé sorprendido al oír que mi amigo se casa pronto.',
      "J'ai été surpris d'apprendre que mon ami va bientôt se marier.",
      'Fiquei surpreso ao ouvir que meu amigo vai se casar em breve.',
      'ฉันตกใจมากเมื่อได้ยินว่าเพื่อนจะแต่งงานเร็ว ๆ นี้',
      'Aku kaget mendengar bahwa temanku akan segera menikah.',
      'Mình giật mình khi nghe tin bạn mình sắp kết hôn.',
      '友達がもうすぐ結婚するという話を聞いてびっくりした。',
    ),
    level: 'casual',
  },
  {
    ko: '-나 보다',
    sentence: '동생이 아직도 안 일어난 걸 보니 어제 많이 피곤했나 봐.',
    trans: L(
      "Seeing that my little brother still isn't up, he must have been really tired yesterday.",
      'Como mi hermano menor todavía no se ha levantado, parece que ayer estaba muy cansado.',
      "Vu que mon petit frère ne s'est toujours pas levé, il devait être très fatigué hier.",
      'Como meu irmão mais novo ainda não acordou, parece que ele estava muito cansado ontem.',
      'ดูจากที่น้องชายยังไม่ตื่นเลย เมื่อวานคงจะเหนื่อยมากสินะ',
      'Melihat adikku masih belum bangun juga, sepertinya dia kemarin sangat lelah.',
      'Thấy em trai vẫn chưa dậy, chắc hôm qua nó mệt lắm.',
      '弟がまだ起きてないのを見ると、昨日かなり疲れてたみたい。',
    ),
    level: 'casual',
  },
  {
    ko: '-나 보다',
    sentence: '옆집에서 계속 웃음소리가 나는 걸 보니 손님이 왔나 봐요.',
    trans: L(
      'Judging by the laughter that keeps coming from next door, it seems they have guests.',
      'Por las risas que se oyen sin parar en la casa de al lado, parece que tienen visitas.',
      "À en juger par les rires qui viennent sans cesse d'à côté, il semble qu'ils aient des invités.",
      'Pelas risadas que não param de vir da casa ao lado, parece que eles estão com visitas.',
      'ดูจากเสียงหัวเราะที่ดังมาจากบ้านข้าง ๆ ไม่หยุด ท่าทางจะมีแขกมาเยี่ยมนะคะ',
      'Dilihat dari suara tawa yang terus terdengar dari rumah sebelah, sepertinya mereka kedatangan tamu.',
      'Nghe tiếng cười cứ vọng sang từ nhà bên cạnh, có vẻ như họ có khách đến chơi.',
      '隣の家から笑い声がずっと聞こえてくるのを見ると、お客さんが来てるみたいですね。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ가 보다',
    sentence: '표정이 어두운 걸 보니 동생이 시험을 망쳤나 봐요.',
    trans: L(
      'From the gloomy look on their face, my sibling must have bombed the exam.',
      'Por la cara tan seria, parece que a mi hermano le fue mal en el examen.',
      'Vu sa mine sombre, mon frère a dû rater son examen.',
      'Pela cara fechada, parece que meu irmão foi mal na prova.',
      'ดูจากสีหน้าหม่นหมอง ท่าทางน้องจะทำข้อสอบได้ไม่ดี',
      'Dilihat dari raut wajahnya yang muram, sepertinya adikku gagal dalam ujian.',
      'Nhìn vẻ mặt u ám là biết, chắc em tôi đã làm bài thi tệ lắm.',
      '表情が暗いのを見ると、弟は試験で失敗したみたいです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ가 보다',
    sentence: '창문에 불이 다 꺼져 있네. 집에 아무도 없나 봐.',
    trans: L(
      "All the lights are off — I guess no one's home.",
      'Todas las luces están apagadas; parece que no hay nadie en casa.',
      "Toutes les lumières sont éteintes ; on dirait qu'il n'y a personne.",
      'Todas as luzes estão apagadas; parece que não tem ninguém em casa.',
      'ไฟดับหมดเลย ท่าทางจะไม่มีใครอยู่บ้าน',
      'Lampunya mati semua; kayaknya tidak ada orang di rumah.',
      'Đèn tắt hết rồi, chắc là không có ai ở nhà.',
      '電気が全部消えてるね。家に誰もいないみたい。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ걸(요)',
    sentence: '지금 가도 식당 문 닫았을걸요.',
    trans: L(
      "Even if we go now, the restaurant's probably already closed.",
      'Aunque vayamos ahora, seguro que el restaurante ya estará cerrado.',
      'Même si on y va maintenant, le restaurant doit déjà être fermé.',
      'Mesmo se a gente for agora, o restaurante provavelmente já fechou.',
      'ถึงไปตอนนี้ ร้านอาหารก็คงปิดไปแล้วล่ะ',
      'Kalaupun kita pergi sekarang, restorannya mungkin sudah tutup.',
      'Bây giờ có đi thì nhà hàng chắc cũng đóng cửa rồi.',
      '今行っても、レストランはもう閉まってるだろうな。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ걸(요)',
    sentence: '이렇게 막힐 줄 알았으면 지하철을 탈걸.',
    trans: L(
      "If I'd known it would be this jammed, I should have taken the subway.",
      'Si hubiera sabido que habría tanto atasco, debería haber tomado el metro.',
      "Si j'avais su qu'il y aurait autant de bouchons, j'aurais dû prendre le métro.",
      'Se eu soubesse que teria tanto trânsito, devia ter pegado o metrô.',
      'รู้งี้รถติดขนาดนี้ น่าจะนั่งรถไฟใต้ดินไปซะ',
      'Kalau tahu bakal semacet ini, mendingan tadi naik kereta bawah tanah.',
      'Biết tắc đường thế này thì đáng lẽ mình nên đi tàu điện ngầm.',
      'こんなに渋滞するって知ってたら、地下鉄に乗ればよかった。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)면서도',
    sentence: '그 사람은 돈이 많으면서도 항상 없다고 해요.',
    trans: L(
      'He has a lot of money, yet he always says he has none.',
      'Él tiene mucho dinero y, aun así, siempre dice que no tiene.',
      "Il a beaucoup d'argent et pourtant il dit toujours qu'il n'en a pas.",
      'Ele tem muito dinheiro e, mesmo assim, sempre diz que não tem.',
      'เขามีเงินเยอะ แต่ก็ยังบอกตลอดว่าไม่มีเงิน',
      'Dia punya banyak uang, tapi selalu saja bilang tidak punya.',
      'Anh ấy có nhiều tiền mà lúc nào cũng bảo là không có.',
      'あの人はお金がたくさんあるのに、いつもないと言っています。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)면서도',
    sentence: '동생은 시험이 코앞이면서도 게임만 하고 있어.',
    trans: L(
      'Even though the exam is right around the corner, my little brother is just playing games.',
      'Aunque el examen está a la vuelta de la esquina, mi hermano menor solo juega videojuegos.',
      "Bien que l'examen soit juste devant la porte, mon petit frère ne fait que jouer aux jeux vidéo.",
      'Mesmo com a prova logo aí, meu irmão mais novo só fica jogando videogame.',
      'ทั้งที่สอบจะมาถึงในไม่ช้า น้องชายฉันก็ยังเอาแต่เล่นเกม',
      'Padahal ujian sudah di depan mata, adikku malah cuma main game terus.',
      'Dù kỳ thi đã cận kề nhưng em mình chỉ toàn chơi game.',
      '試験が目前なのに、弟はゲームばかりしている。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어다(가)',
    sentence: '도서관에서 책을 빌려다가 집에서 읽었어요.',
    trans: L(
      'I borrowed a book from the library and read it at home.',
      'Saqué un libro de la biblioteca y lo leí en casa.',
      "J'ai emprunté un livre à la bibliothèque et je l'ai lu à la maison.",
      'Peguei um livro emprestado na biblioteca e o li em casa.',
      'ยืมหนังสือจากห้องสมุดมาอ่านที่บ้าน',
      'Saya meminjam buku dari perpustakaan lalu membacanya di rumah.',
      'Tôi mượn sách ở thư viện rồi mang về nhà đọc.',
      '図書館で本を借りてきて家で読みました。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어다(가)',
    sentence: '마당에서 꽃을 꺾어다 꽃병에 꽂았어.',
    trans: L(
      'I picked some flowers in the yard and put them in a vase.',
      'Corté unas flores en el jardín y las puse en un jarrón.',
      "J'ai cueilli des fleurs dans le jardin et je les ai mises dans un vase.",
      'Colhi umas flores no quintal e as coloquei num vaso.',
      'เด็ดดอกไม้ที่สนามแล้วเอามาปักแจกัน',
      'Aku memetik bunga di halaman lalu menaruhnya di vas.',
      'Tớ hái hoa ở sân rồi đem cắm vào lọ.',
      '庭で花を摘んできて花瓶に挿したよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 만큼',
    sentence: '비가 많이 온 만큼 길이 많이 막혀요.',
    trans: L(
      'Since it rained so much, the roads are really backed up.',
      'Como llovió tanto, las calles están muy congestionadas.',
      'Comme il a beaucoup plu, les routes sont très embouteillées.',
      'Como choveu muito, o trânsito está bem congestionado.',
      'ฝนตกหนักมากเลยทำให้รถติดมากเลยค่ะ',
      'Karena hujannya deras sekali, jalanannya jadi macet parah.',
      'Vì trời mưa nhiều nên đường rất kẹt xe.',
      '雨がたくさん降っただけあって、道がとても混んでいます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 만큼',
    sentence: '월급을 많이 받는 만큼 일도 그만큼 힘들어.',
    trans: L(
      'You get paid a lot, but the work is just as tough to match.',
      'Ganas mucho, pero el trabajo es igual de duro en la misma medida.',
      'Tu es bien payé, mais le travail est tout aussi dur en proportion.',
      'Você ganha bem, mas o trabalho é igualmente puxado, na mesma medida.',
      'ได้เงินเดือนเยอะ งานก็หนักพอ ๆ กันนั่นแหละ',
      'Karena gajinya besar, pekerjaannya pun sama beratnya.',
      'Lương cao bao nhiêu thì công việc cũng vất vả bấy nhiêu.',
      '給料をたくさんもらう分、仕事もそれだけ大変だよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 척 + V',
    sentence: '동생은 다 아는 척 고개를 끄덕였어요.',
    trans: L(
      'My younger sibling nodded, pretending to know everything.',
      'Mi hermano menor asintió fingiendo que lo sabía todo.',
      'Mon petit frère a hoché la tête en faisant semblant de tout savoir.',
      'Meu irmão mais novo acenou com a cabeça fingindo que sabia de tudo.',
      'น้องของฉันพยักหน้าทำเป็นว่ารู้ไปหมดทุกอย่าง',
      'Adikku mengangguk berpura-pura tahu segalanya.',
      'Em tôi gật đầu giả vờ như biết hết mọi thứ.',
      '弟は何でも知っているふりをしてうなずきました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 척 + V',
    sentence: '엄마가 부를까 봐 자는 척 눈을 감고 있었어.',
    trans: L(
      'Afraid Mom would call me, I kept my eyes closed pretending to be asleep.',
      'Por miedo a que mamá me llamara, mantuve los ojos cerrados fingiendo que dormía.',
      "De peur que maman m'appelle, je gardais les yeux fermés en faisant semblant de dormir.",
      'Com medo de que a mamãe me chamasse, fiquei de olhos fechados fingindo que dormia.',
      'กลัวว่าแม่จะเรียก เลยหลับตาทำเป็นนอนหลับอยู่',
      'Takut Ibu memanggilku, aku memejamkan mata berpura-pura tidur.',
      'Sợ mẹ gọi nên tôi nhắm mắt giả vờ đang ngủ.',
      '母に呼ばれるかと思って、寝ているふりをして目を閉じていた。',
    ),
    level: 'casual',
  },
  {
    ko: '-았/었었-',
    sentence: '예전에는 담배를 피웠었는데 지금은 끊었어요.',
    trans: L(
      "I used to smoke in the past, but I've quit now.",
      'Antes fumaba, pero ya lo dejé.',
      "Avant, je fumais, mais j'ai arrêté maintenant.",
      'Antigamente eu fumava, mas agora parei.',
      'เมื่อก่อนเคยสูบบุหรี่ แต่ตอนนี้เลิกแล้ว',
      'Dulu saya merokok, tapi sekarang sudah berhenti.',
      'Trước đây tôi từng hút thuốc, nhưng bây giờ đã bỏ rồi.',
      '昔はタバコを吸っていたけど、今はやめました。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었었-',
    sentence: '작년에 그 영화 봤었는데 내용이 하나도 기억 안 나.',
    trans: L(
      "I watched that movie last year, but I don't remember a single thing about it.",
      'Vi esa película el año pasado, pero no recuerdo nada de la trama.',
      "J'avais vu ce film l'année dernière, mais je ne me souviens de rien.",
      'Eu vi aquele filme no ano passado, mas não lembro de nada.',
      'ปีที่แล้วเคยดูหนังเรื่องนั้นนะ แต่จำเนื้อเรื่องไม่ได้เลย',
      'Tahun lalu aku pernah nonton film itu, tapi sama sekali nggak ingat ceritanya.',
      'Năm ngoái tớ đã xem bộ phim đó rồi mà chẳng nhớ nội dung gì cả.',
      '去年あの映画を観たんだけど、内容を全然覚えてないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-지 않을 수 없다',
    sentence: '어머니가 그렇게까지 부탁하시는데 도와드리지 않을 수 없었어요.',
    trans: L(
      "Mother asked me so earnestly that I couldn't help but lend a hand.",
      'Mi madre me lo pidió con tanta insistencia que no pude evitar ayudarla.',
      "Ma mère me l'a demandé avec tant d'insistance que je n'ai pas pu m'empêcher de l'aider.",
      'Minha mãe pediu com tanta insistência que eu não pude deixar de ajudá-la.',
      'แม่ขอร้องถึงขนาดนั้น ฉันก็เลยอดช่วยท่านไม่ได้',
      'Ibu memohon sampai begitu, jadi aku tidak bisa tidak membantunya.',
      'Mẹ đã nhờ đến mức đó nên tôi không thể không giúp được.',
      '母にそこまで頼まれては、手伝わずにはいられませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '-지 않을 수 없다',
    sentence: '증거가 이렇게 명확하니 그의 말을 믿지 않을 수 없다.',
    trans: L(
      'The evidence is so clear that one cannot help but believe what he says.',
      'La evidencia es tan clara que no se puede sino creer lo que dice.',
      "Les preuves sont si claires qu'on ne peut s'empêcher de croire ce qu'il dit.",
      'As provas são tão claras que não há como não acreditar no que ele diz.',
      'หลักฐานชัดเจนขนาดนี้ ก็อดเชื่อคำพูดของเขาไม่ได้',
      'Buktinya begitu jelas, jadi mau tak mau harus memercayai perkataannya.',
      'Bằng chứng rõ ràng thế này thì không thể không tin lời anh ấy được.',
      '証拠がこれほど明確では、彼の言葉を信じざるを得ない。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는 데(에)다(가)',
    sentence: '이 식당은 음식이 맛있는 데다가 값도 싸서 항상 손님이 많아요.',
    trans: L(
      "At this restaurant the food is delicious, and on top of that it's cheap too, so it's always crowded with customers.",
      'En este restaurante la comida es deliciosa y, además, también es barata, así que siempre está lleno de clientes.',
      'Dans ce restaurant, la nourriture est délicieuse et, en plus, elle est aussi bon marché, donc il y a toujours beaucoup de clients.',
      'Neste restaurante a comida é deliciosa e, além disso, também é barata, então está sempre cheio de clientes.',
      'ร้านอาหารร้านนี้อาหารอร่อย แถมราคายังถูกอีกด้วย เลยมีลูกค้าเยอะตลอด',
      'Di restoran ini makanannya enak, ditambah lagi harganya juga murah, jadi selalu ramai pelanggan.',
      'Nhà hàng này đồ ăn ngon, hơn nữa giá lại còn rẻ, nên lúc nào cũng đông khách.',
      'このレストランは料理がおいしいうえに値段も安いので、いつもお客さんが多いです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 데(에)다(가)',
    sentence: '그 사람은 일도 잘하는 데다가 성격도 좋아서 회사에서 인기가 많아.',
    trans: L(
      "That person is good at their job, and on top of that has a nice personality too, so they're really popular at the company.",
      'Esa persona hace bien su trabajo y, encima, también tiene buen carácter, así que es muy popular en la empresa.',
      "Cette personne fait bien son travail et, en plus, elle a aussi un bon caractère, donc elle est très populaire dans l'entreprise.",
      'Essa pessoa faz bem o trabalho e, além disso, também tem um bom temperamento, então é muito popular na empresa.',
      'คนนั้นทำงานเก่ง แถมนิสัยยังดีอีก เลยเป็นที่นิยมในบริษัทมาก',
      'Orang itu pandai bekerja, ditambah lagi kepribadiannya juga baik, jadi dia populer banget di kantor.',
      'Người đó làm việc giỏi, hơn nữa tính tình lại còn tốt, nên rất được yêu thích ở công ty.',
      'あの人は仕事もできるうえに性格もいいから、会社ですごく人気があるんだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어다(가) 주다',
    sentence: '목마른데 물 좀 떠다 줘.',
    trans: L(
      "I'm thirsty, go get me some water.",
      'Tengo sed, ve a traerme un poco de agua.',
      "J'ai soif, va me chercher un peu d'eau.",
      'Estou com sede, vai pegar um pouco de água pra mim.',
      'หิวน้ำอะ ไปตักน้ำมาให้หน่อย',
      'Aku haus, tolong ambilkan air buat aku.',
      'Tớ khát quá, đi lấy nước về cho tớ với.',
      'のどかわいたから、水くんできてくれる？',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어다(가) 주다',
    sentence: '약국에서 약을 받아다 줄게요.',
    trans: L(
      "I'll pick up the medicine at the pharmacy and bring it to you.",
      'Te recojo la medicina en la farmacia y te la traigo.',
      "Je vais récupérer le médicament à la pharmacie et te l'apporter.",
      'Vou pegar o remédio na farmácia e te trazer.',
      'เดี๋ยวฉันไปรับยาที่ร้านขายยาแล้วเอามาให้นะ',
      'Nanti kuambilkan obatnya di apotek lalu kubawakan untukmu.',
      'Để tôi lấy thuốc ở hiệu thuốc rồi mang về cho bạn nhé.',
      '薬局で薬を受け取って持ってきてあげますね。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)면 -(으)ㄹ수록',
    sentence: '운동은 하면 할수록 몸이 가벼워지는 것 같아요.',
    trans: L(
      'The more I exercise, the lighter my body seems to feel.',
      'Cuanto más hago ejercicio, más ligero siento el cuerpo.',
      "Plus je fais de l'exercice, plus mon corps me semble léger.",
      'Quanto mais eu me exercito, mais leve meu corpo parece ficar.',
      'ยิ่งออกกำลังกายมากเท่าไร ร่างกายก็ยิ่งรู้สึกเบาขึ้นเท่านั้น',
      'Semakin sering berolahraga, tubuh rasanya semakin ringan.',
      'Càng tập thể dục thì cơ thể càng cảm thấy nhẹ nhõm hơn.',
      '運動はすればするほど体が軽くなる気がします。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)면 -(으)ㄹ수록',
    sentence: '그 사람은 알면 알수록 정이 가더라.',
    trans: L(
      'The more I got to know that person, the more I grew fond of them.',
      'Cuanto más conocía a esa persona, más cariño le iba tomando.',
      "Plus j'apprenais à connaître cette personne, plus je m'attachais à elle.",
      'Quanto mais eu conhecia aquela pessoa, mais afeto eu sentia por ela.',
      'ยิ่งรู้จักคนคนนั้นมากเท่าไร ก็ยิ่งรู้สึกผูกพันมากขึ้นเท่านั้น',
      'Makin kenal dengan orang itu, makin tumbuh rasa sayangku padanya.',
      'Càng tìm hiểu người đó thì mình lại càng thấy quý mến.',
      'あの人は知れば知るほど情が湧いてきたんだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-았/었어야',
    sentence: '네가 그때 진실을 말했어야 했는데, 결국 아무 말도 안 했잖아.',
    trans: L(
      "You should have told the truth back then, but in the end you didn't say a word.",
      'Deberías haber dicho la verdad en aquel momento, pero al final no dijiste ni una palabra.',
      "Tu aurais dû dire la vérité à ce moment-là, mais au final tu n'as rien dit.",
      'Você deveria ter dito a verdade naquela hora, mas no fim não disse uma palavra.',
      'ตอนนั้นเธอน่าจะพูดความจริงออกมา แต่สุดท้ายก็ไม่ได้พูดอะไรเลย',
      'Kamu seharusnya mengatakan yang sebenarnya waktu itu, tapi pada akhirnya kamu tidak berkata apa-apa.',
      'Lúc đó cậu lẽ ra phải nói ra sự thật, nhưng cuối cùng lại chẳng nói gì cả.',
      'あのとき本当のことを言うべきだったのに、結局何も言わなかったじゃない。',
    ),
    level: 'casual',
  },
  {
    ko: '-았/었어야',
    sentence: '약을 미리 챙겼어야 했는데 깜빡하고 집에 두고 왔어요.',
    trans: L(
      'I should have packed the medicine beforehand, but I forgot and left it at home.',
      'Debería haber preparado la medicina con antelación, pero se me olvidó y la dejé en casa.',
      "J'aurais dû préparer les médicaments à l'avance, mais j'ai oublié et je les ai laissés à la maison.",
      'Eu deveria ter separado o remédio com antecedência, mas esqueci e deixei em casa.',
      'ฉันน่าจะเตรียมยาไว้ล่วงหน้า แต่ลืมแล้วทิ้งไว้ที่บ้าน',
      'Saya seharusnya menyiapkan obatnya dari awal, tapi saya lupa dan meninggalkannya di rumah.',
      'Lẽ ra tôi phải chuẩn bị thuốc từ trước, nhưng tôi quên mất và để quên ở nhà rồi.',
      '薬を前もって用意しておくべきだったのに、うっかり家に置いてきてしまいました。',
    ),
    level: 'polite',
  },
]
