import type { GrammarExample } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-5 grammar examples (plan Part B Tier-1, level 5). Per-FORM coverage for
 * the multi-form TOPIK-5 grammars: each grammar whose `ko` names ≥2 distinct
 * surface forms shows ≥1 example per form. `ko` values match grammars-n5.ts
 * verbatim; sentences differ from each grammar's canonical `Grammar.example`.
 *
 * Drafted + Korean-lens adversarially verified by a multi-agent workflow.
 * Native (Korean wife) review is the documented final gate.
 */
export const TOPIK_5_EXAMPLES: GrammarExample[] = [
  {
    ko: '-(으)ㄴ/는 듯하다 / 듯싶다',
    sentence: '불이 다 꺼진 걸 보니 가족들이 벌써 잠든 듯해요.',
    trans: L(
      'Seeing that all the lights are off, it seems the family has already gone to sleep.',
      'Viendo que todas las luces están apagadas, parece que la familia ya se durmió.',
      'Vu que toutes les lumières sont éteintes, il semble que la famille dort déjà.',
      'Vendo que todas as luzes estão apagadas, parece que a família já dormiu.',
      'เห็นว่าไฟดับหมดแล้ว ดูเหมือนว่าคนในครอบครัวคงนอนหลับกันไปแล้ว',
      'Melihat semua lampu sudah mati, sepertinya keluarga sudah tidur.',
      'Thấy đèn đã tắt hết, có vẻ như cả nhà đã ngủ rồi.',
      '電気が全部消えているのを見ると、家族はもう寝てしまったようです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 듯하다 / 듯싶다',
    sentence: '그 식당은 평일인데도 줄이 긴 걸 보면 꽤 유명한 듯싶어요.',
    trans: L(
      "Given the long line even on a weekday, that restaurant seems to be quite famous, I'd guess.",
      'Viendo la cola tan larga incluso entre semana, diría que ese restaurante es bastante famoso.',
      "Vu la longue file même en semaine, j'ai l'impression que ce restaurant est assez célèbre.",
      'Pela fila tão longa mesmo em dia de semana, me parece que esse restaurante é bem famoso.',
      'ดูจากที่คนต่อแถวยาวทั้งที่เป็นวันธรรมดา ร้านนั้นน่าจะดังพอสมควรเลยล่ะ',
      'Melihat antrean yang panjang padahal hari kerja, sepertinya restoran itu cukup terkenal.',
      'Nhìn hàng người xếp dài dù là ngày thường, tôi đoán quán đó khá nổi tiếng.',
      '平日なのに行列が長いのを見ると、あの店はかなり有名なようですね。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고 할까 봐 / -다고 할 줄 알았다',
    sentence: '친구가 약속을 잊었다고 할까 봐 미리 문자를 보냈어요.',
    trans: L(
      "I texted in advance, afraid my friend might say he'd forgotten about our plans.",
      'Le mandé un mensaje por adelantado, por miedo a que mi amigo dijera que se había olvidado de la cita.',
      "J'ai envoyé un message à l'avance, de peur que mon ami dise qu'il avait oublié notre rendez-vous.",
      'Mandei uma mensagem com antecedência, com medo de que meu amigo dissesse que tinha esquecido do compromisso.',
      'ฉันส่งข้อความไว้ล่วงหน้า เพราะกลัวว่าเพื่อนจะบอกว่าลืมนัด',
      'Saya kirim pesan lebih dulu, khawatir teman saya bilang dia lupa janji kami.',
      'Tôi nhắn tin trước, vì sợ bạn tôi sẽ nói là đã quên mất cuộc hẹn.',
      '友達が約束を忘れたと言うかと思って、前もってメッセージを送りました。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고 할까 봐 / -다고 할 줄 알았다',
    sentence: '네가 또 바쁘다고 할 줄 알았어.',
    trans: L(
      "I knew you'd say you were busy again.",
      'Ya sabía que dirías que estabas ocupado otra vez.',
      'Je savais que tu dirais encore que tu étais occupé.',
      'Eu já sabia que você ia dizer que estava ocupado de novo.',
      'ฉันรู้อยู่แล้วว่าเธอจะบอกอีกว่ายุ่ง',
      'Sudah kuduga kamu bakal bilang sibuk lagi.',
      'Tôi đã biết là cậu lại nói rằng mình bận mà.',
      'あなたがまた忙しいって言うだろうと思ってた。',
    ),
    level: 'casual',
  },
  {
    ko: '-다는데 / -다더라 / -다더니',
    sentence: '내일 비가 많이 온다는데 우산 챙기는 게 좋겠어요.',
    trans: L(
      "They say it's going to rain a lot tomorrow, so you'd better bring an umbrella.",
      'Dicen que mañana va a llover mucho, así que mejor lleva un paraguas.',
      "On dit qu'il va beaucoup pleuvoir demain, alors tu ferais mieux de prendre un parapluie.",
      'Dizem que vai chover muito amanhã, então é melhor você levar um guarda-chuva.',
      'เขาว่ากันว่าพรุ่งนี้ฝนจะตกหนัก เพราะฉะนั้นเอาร่มไปด้วยจะดีกว่านะ',
      'Katanya besok hujannya bakal deras, jadi lebih baik kamu bawa payung.',
      'Nghe nói ngày mai mưa to lắm, nên bạn mang theo ô thì hơn.',
      '明日は雨がたくさん降るそうだから、傘を持っていったほうがいいですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-다는데 / -다더라 / -다더니',
    sentence: '그 영화 진짜 무섭다더라, 혼자 보지 마.',
    trans: L(
      "I heard that movie is really scary — don't watch it alone.",
      'Oí que esa película da mucho miedo, no la veas solo.',
      "J'ai entendu dire que ce film fait vraiment peur, ne le regarde pas tout seul.",
      'Ouvi dizer que esse filme é muito assustador, não assista sozinho.',
      'ได้ยินมาว่าหนังเรื่องนั้นน่ากลัวมากเลยนะ อย่าดูคนเดียวล่ะ',
      'Katanya film itu serem banget loh, jangan nonton sendirian.',
      'Nghe nói phim đó đáng sợ lắm đấy, đừng xem một mình.',
      'あの映画、めっちゃ怖いんだってさ、一人で見ないでね。',
    ),
    level: 'casual',
  },
  {
    ko: '-다는데 / -다더라 / -다더니',
    sentence: '오늘 하루 종일 안 바쁘다더니 왜 이렇게 연락이 안 됐어?',
    trans: L(
      "You said you weren't busy all day, so why couldn't I reach you?",
      'Dijiste que no estabas nada ocupado en todo el día, ¿y por qué no pude localizarte?',
      "Tu disais que tu n'étais pas occupé de toute la journée, alors pourquoi je n'ai pas pu te joindre ?",
      'Você disse que não estava nada ocupado o dia todo, então por que não consegui falar com você?',
      'บอกว่าทั้งวันไม่ได้ยุ่งนี่ แล้วทำไมถึงติดต่อไม่ได้เลยล่ะ',
      'Katanya seharian nggak sibuk, kok malah susah dihubungi?',
      'Cậu bảo cả ngày không bận mà, sao lại khó liên lạc thế?',
      '一日中忙しくないって言ってたのに、どうしてこんなに連絡がつかなかったの？',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 뵙다 / 봬요',
    sentence: '다음 주 월요일에 본사로 회장님을 직접 찾아 뵙겠습니다.',
    trans: L(
      'I will personally call on the chairman at the head office next Monday.',
      'El próximo lunes iré en persona a la sede a presentarme ante el presidente.',
      'Lundi prochain, je me rendrai en personne au siège pour rencontrer le président.',
      'Na próxima segunda-feira irei pessoalmente à matriz para me apresentar ao presidente.',
      'วันจันทร์หน้าผมจะไปพบท่านประธานด้วยตนเองที่สำนักงานใหญ่',
      'Senin depan saya akan datang sendiri ke kantor pusat untuk menghadap Bapak Ketua.',
      'Thứ Hai tuần sau tôi sẽ đích thân đến trụ sở chính để gặp chủ tịch.',
      '来週の月曜日に本社へ伺い、会長に直接お目にかかります。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 뵙다 / 봬요',
    sentence: '부장님, 그럼 회의 끝나고 로비에서 봬요.',
    trans: L(
      "Then, sir, I'll see you in the lobby after the meeting.",
      'Entonces, jefe, nos vemos en el vestíbulo después de la reunión.',
      'Alors, chef, on se voit dans le hall après la réunion.',
      'Então, chefe, a gente se vê no saguão depois da reunião.',
      'หัวหน้า งั้นเดี๋ยวหลังประชุมเจอกันที่ล็อบบี้นะ',
      'Kalau begitu, Pak, sampai jumpa di lobi setelah rapat ya.',
      'Trưởng phòng ơi, vậy sau cuộc họp gặp ở sảnh nhé ạ.',
      '部長、では会議が終わったらロビーでお会いしましょう。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)며 살다 / 지내다',
    sentence: '할머니는 시골에서 작은 텃밭을 가꾸며 사세요.',
    trans: L(
      'Grandmother lives tending a small vegetable garden in the countryside.',
      'La abuela vive cultivando un pequeño huerto en el campo.',
      'Grand-mère vit en cultivant un petit potager à la campagne.',
      'A vovó vive cuidando de uma pequena horta no interior.',
      'คุณยายใช้ชีวิตด้วยการดูแลแปลงผักเล็ก ๆ อยู่ในชนบท',
      'Nenek menjalani hidupnya dengan merawat kebun sayur kecil di desa.',
      'Bà sống cuộc đời mình bằng việc chăm sóc một mảnh vườn rau nhỏ ở quê.',
      '祖母は田舎で小さな畑を育てながら暮らしていらっしゃいます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)며 살다 / 지내다',
    sentence: '요즘은 매일 운동하며 건강하게 지내고 있어요.',
    trans: L(
      "These days I'm getting by in good health, exercising every day.",
      'Últimamente me las arreglo manteniéndome sano, haciendo ejercicio todos los días.',
      'Ces jours-ci, je passe mes journées en bonne santé en faisant du sport tous les jours.',
      'Ultimamente venho levando os dias com saúde, fazendo exercícios todos os dias.',
      'ช่วงนี้ฉันใช้ชีวิตอย่างมีสุขภาพดีด้วยการออกกำลังกายทุกวัน',
      'Akhir-akhir ini saya menjalani hari-hari dengan sehat sambil berolahraga setiap hari.',
      'Dạo này tôi sống khỏe mạnh qua ngày bằng việc tập thể dục mỗi ngày.',
      '最近は毎日運動しながら健康に過ごしています。',
    ),
    level: 'polite',
  },
  {
    ko: '-더니',
    sentence: '동생이 어제 늦게까지 게임을 하더니 오늘 아침에 못 일어나네요.',
    trans: L(
      "My little brother played games until late last night, and now he can't get up this morning.",
      'Mi hermano menor estuvo jugando videojuegos hasta tarde ayer, y hoy por la mañana no puede levantarse.',
      "Mon petit frère a joué aux jeux vidéo jusqu'à tard hier, et ce matin il n'arrive pas à se lever.",
      'Meu irmão mais novo ficou jogando videogame até tarde ontem, e hoje de manhã não consegue se levantar.',
      'เมื่อวานน้องเล่นเกมจนดึก พอเช้านี้เลยตื่นไม่ขึ้นเลย',
      'Kemarin adik main game sampai larut malam, dan pagi ini dia jadi tidak bisa bangun.',
      'Hôm qua em tôi chơi game đến khuya, thế mà sáng nay lại không dậy nổi.',
      '弟が昨日遅くまでゲームをしていたと思ったら、今朝は起きられないんですよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-더니',
    sentence: '민수가 한동안 말이 없더니 갑자기 회사를 그만뒀어.',
    trans: L(
      'Minsu had been quiet for a while, and then he suddenly quit his job.',
      'Minsu llevaba un tiempo callado, y de repente renunció a su trabajo.',
      'Minsu était silencieux depuis un moment, et tout à coup il a quitté son travail.',
      'O Minsu estava quieto fazia um tempo, e de repente pediu demissão.',
      'มินซูเงียบไปพักหนึ่ง อยู่ๆ ก็ลาออกจากงานเลย',
      'Minsu beberapa waktu ini diam saja, lalu tiba-tiba berhenti dari pekerjaannya.',
      'Minsu im lặng một thời gian, rồi đột nhiên nghỉ việc.',
      'ミンスがしばらく口数が少ないと思ったら、突然会社を辞めたんだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-던',
    sentence: '이거 제가 마시던 커피인데 한 모금 드실래요?',
    trans: L(
      'This is the coffee I was drinking — would you like a sip?',
      'Este es el café que estaba tomando, ¿quieres un sorbo?',
      "C'est le café que j'étais en train de boire, tu en veux une gorgée ?",
      'Este é o café que eu estava bebendo, quer um gole?',
      'นี่คือกาแฟที่ฉันกำลังดื่มอยู่ ลองจิบสักคำไหม',
      'Ini kopi yang tadi sedang kuminum, mau coba seteguk?',
      'Đây là cốc cà phê tôi đang uống dở, bạn uống một ngụm không?',
      'これ、私が飲んでいたコーヒーなんですけど、一口いかがですか？',
    ),
    level: 'polite',
  },
  {
    ko: '-던',
    sentence: '그렇게 매일 운동하던 형이 요즘은 왜 안 나와?',
    trans: L(
      "Why doesn't that brother who used to work out every day show up these days?",
      '¿Por qué ya no viene el hermano que solía entrenar todos los días?',
      "Pourquoi ce grand frère qui s'entraînait tous les jours ne vient-il plus ces temps-ci ?",
      'Por que aquele irmão que treinava todo dia não aparece mais ultimamente?',
      'พี่คนที่เคยออกกำลังกายทุกวันแบบนั้น ช่วงนี้ทำไมไม่มาเลยล่ะ',
      'Kenapa kakak yang dulu rajin olahraga tiap hari itu sekarang nggak muncul?',
      'Sao dạo này ông anh ngày nào cũng tập thể dục đó lại không thấy đến nữa?',
      'あんなに毎日運動してた兄貴が、最近どうして来ないの？',
    ),
    level: 'casual',
  },
  {
    ko: '-더니만',
    sentence: '아침까지 날씨가 멀쩡하더니만 갑자기 비가 쏟아지네요.',
    trans: L(
      "The weather was perfectly fine until this morning, and now, sure enough, it's suddenly pouring.",
      'El tiempo estuvo despejado hasta esta mañana y ahora, como era de esperar, de repente se ha puesto a diluviar.',
      "Le temps était parfaitement dégagé jusqu'à ce matin, et voilà que, sans surprise, il se met soudain à pleuvoir des cordes.",
      'O tempo estava ótimo até de manhã e agora, como era de se esperar, começou a chover torrencialmente de repente.',
      'เมื่อเช้าอากาศยังดีอยู่เลย แล้วนี่ไงจู่ ๆ ก็ฝนตกหนักขึ้นมาเฉยเลย',
      'Tadi sampai pagi cuacanya cerah-cerah saja, eh benar saja sekarang tiba-tiba hujan deras.',
      'Đến tận sáng trời còn quang đãng, vậy mà đúng như đã ngờ, giờ tự nhiên đổ mưa như trút.',
      '朝までは天気が良かったのに、案の定、急に土砂降りになってきましたね。',
    ),
    level: 'polite',
  },
  {
    ko: '-더니만',
    sentence: '동생이 밤새 게임만 하더니만 결국 시험을 완전히 망쳤어.',
    trans: L(
      'My little brother was up all night just gaming, and sure enough he ended up totally bombing the exam.',
      'Mi hermano menor se pasó toda la noche jugando videojuegos y, como era de esperar, al final reprobó el examen por completo.',
      'Mon petit frère a passé toute la nuit à jouer aux jeux vidéo, et sans surprise, il a complètement raté son examen au final.',
      'Meu irmão mais novo passou a noite toda só jogando videogame e, como era de se esperar, acabou indo super mal na prova.',
      'น้องเล่นเกมทั้งคืนเลย สุดท้ายก็เลยสอบพังไม่เป็นท่าจริง ๆ ตามคาด',
      'Adikku semalaman cuma main game terus, dan benar saja akhirnya ujiannya hancur total.',
      'Thằng em suốt đêm chỉ cắm đầu chơi game, đúng như đã đoán, cuối cùng nó thi hỏng bét.',
      '弟が一晩中ゲームばっかりしていたから、案の定、結局試験を完全にしくじったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ지언정',
    sentence: '회사가 망할지언정 직원들 월급은 절대 미루지 않겠습니다.',
    trans: L(
      "Even if the company goes under, I will never delay the employees' wages.",
      'Aunque la empresa quiebre, jamás retrasaré el sueldo de los empleados.',
      "Même si l'entreprise fait faillite, je ne retarderai jamais le salaire des employés.",
      'Nem que a empresa vá à falência, eu jamais atrasarei o salário dos funcionários.',
      'ถึงแม้บริษัทจะล้มละลาย ผมก็จะไม่มีวันจ่ายเงินเดือนพนักงานช้าเด็ดขาด',
      'Sekalipun perusahaan bangkrut, saya tidak akan pernah menunda gaji para karyawan.',
      'Dù công ty có phá sản đi nữa, tôi cũng tuyệt đối không bao giờ trả chậm lương cho nhân viên.',
      '会社が潰れることはあっても、社員の給料は絶対に遅らせません。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ지언정',
    sentence: '시험에 떨어질지언정 남의 답을 베끼는 짓은 하지 않을 거야.',
    trans: L(
      "Even if I fail the exam, I won't do something like copying someone else's answers.",
      'Aunque suspenda el examen, no voy a hacer algo como copiarle las respuestas a otro.',
      "Même si je rate l'examen, je ne m'abaisserai pas à copier les réponses des autres.",
      'Mesmo que eu reprove na prova, não vou fazer uma coisa dessas, como colar as respostas dos outros.',
      'ต่อให้สอบตก ฉันก็จะไม่ทำเรื่องอย่างการลอกคำตอบของคนอื่นเด็ดขาด',
      'Sekalipun aku gagal ujian, aku tidak akan melakukan hal seperti menyontek jawaban orang lain.',
      'Dù có thi trượt đi nữa, tớ cũng sẽ không làm cái việc như chép bài người khác đâu.',
      '試験に落ちることはあっても、人の答えを写すような真似はしないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ지라도',
    sentence: '비록 실패할지라도 도전해 볼 가치는 있습니다.',
    trans: L(
      "Even if it ends in failure, it's worth giving it a try.",
      'Aunque termine en fracaso, vale la pena intentarlo.',
      "Même si cela se solde par un échec, cela vaut la peine d'essayer.",
      'Mesmo que acabe em fracasso, vale a pena tentar.',
      'แม้ว่าจะล้มเหลว ก็คุ้มค่าที่จะลองดู',
      'Meskipun berakhir dengan kegagalan, tetap layak untuk dicoba.',
      'Dù cho có thất bại đi nữa thì cũng đáng để thử.',
      'たとえ失敗するとしても、挑戦してみる価値はあります。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ지라도',
    sentence: '아무리 바쁠지라도 가족과의 약속은 꼭 지켜요.',
    trans: L(
      'No matter how busy I am, I always keep my promises with family.',
      'Por muy ocupado que esté, siempre cumplo las promesas con mi familia.',
      'Aussi occupé que je sois, je tiens toujours mes promesses envers ma famille.',
      'Por mais ocupado que eu esteja, sempre cumpro as promessas com a família.',
      'ไม่ว่าจะยุ่งแค่ไหน ฉันก็รักษาสัญญาที่ให้ไว้กับครอบครัวเสมอ',
      'Sesibuk apa pun, saya selalu menepati janji dengan keluarga.',
      'Dù bận đến mấy, tôi cũng nhất định giữ lời hứa với gia đình.',
      'どんなに忙しくても、家族との約束は必ず守ります。',
    ),
    level: 'polite',
  },
  {
    ko: '-고도',
    sentence: '그 사람은 잘못을 하고도 사과 한마디 안 했어요.',
    trans: L(
      "Even though he did something wrong, he didn't say a single word of apology.",
      'Aunque hizo algo mal, no dijo ni una palabra de disculpa.',
      "Bien qu'il ait commis une faute, il n'a pas dit un seul mot d'excuse.",
      'Mesmo tendo feito algo errado, ele não disse uma única palavra de desculpa.',
      'ทั้งที่ทำผิด เขากลับไม่พูดขอโทษสักคำ',
      'Meskipun sudah berbuat salah, dia tidak mengucapkan sepatah kata maaf pun.',
      'Dù đã làm sai, anh ta lại không nói một lời xin lỗi nào.',
      'あの人は間違いを犯しておきながら、謝罪の一言もありませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '-고도',
    sentence: '분명히 알고도 모르는 척하지 마.',
    trans: L(
      "Don't pretend you don't know when you clearly do.",
      'No finjas que no lo sabes cuando claramente lo sabes.',
      'Ne fais pas semblant de ne pas savoir alors que tu sais très bien.',
      'Não finja que não sabe quando claramente sabe.',
      'ทั้งที่รู้อยู่ชัด ๆ อย่าทำเป็นไม่รู้สิ',
      'Jangan pura-pura tidak tahu padahal jelas-jelas kamu tahu.',
      'Rõ ràng là biết rồi, đừng có giả vờ không biết.',
      'はっきり知っていながら、知らないふりをするな。',
    ),
    level: 'casual',
  },
  {
    ko: '-느니 (차라리)',
    sentence: '이렇게 매일 야근하느니 차라리 회사를 그만두는 게 낫겠어요.',
    trans: L(
      "Rather than working overtime every day like this, I'd be better off just quitting the company.",
      'Antes que hacer horas extra cada día así, casi mejor renuncio a la empresa.',
      "Plutôt que de faire des heures supplémentaires tous les jours comme ça, je ferais mieux de quitter l'entreprise.",
      'Em vez de fazer hora extra todo dia assim, é melhor eu largar a empresa de uma vez.',
      'แทนที่จะทำงานล่วงเวลาทุกวันแบบนี้ ลาออกจากบริษัทไปเลยยังจะดีกว่า',
      'Daripada lembur setiap hari seperti ini, lebih baik aku berhenti dari perusahaan saja.',
      'Thà nghỉ việc ở công ty còn hơn ngày nào cũng phải tăng ca như thế này.',
      '毎日こんなに残業するくらいなら、いっそ会社を辞めたほうがましです。',
    ),
    level: 'polite',
  },
  {
    ko: '-느니 (차라리)',
    sentence: '그 사람한테 부탁하느니 차라리 내가 직접 하고 말지.',
    trans: L(
      "Rather than ask that guy for a favor, I'd sooner just do it myself.",
      'Antes que pedirle un favor a ese, prefiero hacerlo yo mismo y ya está.',
      'Plutôt que de demander un service à ce type, je préfère encore le faire moi-même.',
      'Em vez de pedir um favor pra aquele cara, prefiro fazer eu mesmo e pronto.',
      'แทนที่จะไปขอร้องคนนั้น ฉันทำเองเลยยังจะดีกว่า',
      'Daripada minta tolong ke orang itu, mending aku kerjakan sendiri saja.',
      'Thà tự mình làm còn hơn đi nhờ vả người đó.',
      'あの人に頼むくらいなら、いっそ自分で直接やったほうがましだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)면 몰라도',
    sentence: '지금 출발하면 몰라도 그 시간에 도착하기는 어려울 거예요.',
    trans: L(
      "Unless we leave right now, it'll be hard to get there by that time.",
      'A no ser que salgamos ahora mismo, será difícil llegar a esa hora.',
      "À moins de partir tout de suite, ce sera difficile d'arriver à cette heure-là.",
      'A não ser que a gente saia agora mesmo, vai ser difícil chegar nesse horário.',
      'นอกจากจะออกเดินทางตอนนี้เลย ไม่อย่างนั้นคงไปถึงตามเวลานั้นยาก',
      'Kecuali kita berangkat sekarang juga, sulit sampai sana tepat waktu.',
      'Trừ phi mình xuất phát ngay bây giờ, chứ đến kịp giờ đó thì khó đấy.',
      '今すぐ出発するなら別だけど、その時間に着くのは難しいと思います。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)면 몰라도',
    sentence: '네가 직접 사과하면 몰라도 그냥 넘어가면 형은 절대 안 풀려.',
    trans: L(
      'Unless you apologize to him yourself, your brother will never let it go.',
      'A menos que te disculpes tú mismo, tu hermano nunca lo va a superar.',
      "À moins que tu t'excuses toi-même, ton frère ne passera jamais l'éponge.",
      'A não ser que você peça desculpas pessoalmente, seu irmão nunca vai deixar isso pra lá.',
      'นอกจากนายจะไปขอโทษเองนะ ไม่อย่างนั้นพี่เขาไม่มีทางหายโกรธหรอก',
      'Kecuali kamu minta maaf langsung, kakakmu nggak bakal pernah luluh.',
      'Trừ phi mày tự đi xin lỗi, chứ cứ cho qua là anh ấy không bao giờ nguôi đâu.',
      '君が直接謝るなら別だけど、このまま流したら兄貴は絶対に許してくれないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-다손 치더라도',
    sentence: '아무리 바쁘다손 치더라도 부모님 전화는 받아야지.',
    trans: L(
      "Even granting that you're busy, you should at least answer your parents' calls.",
      'Aun suponiendo que estés muy ocupado, al menos deberías contestar las llamadas de tus padres.',
      'À supposer même que tu sois occupé, tu devrais au moins répondre aux appels de tes parents.',
      'Mesmo supondo que você esteja ocupado, pelo menos deveria atender as ligações dos seus pais.',
      'ต่อให้จะยุ่งแค่ไหน อย่างน้อยก็ควรจะรับโทรศัพท์พ่อแม่สิ',
      'Sekalipun kamu sibuk, setidaknya kamu harus mengangkat telepon dari orang tuamu.',
      'Cho dù có bận đến mấy đi nữa thì ít nhất cũng phải nghe điện thoại của bố mẹ chứ.',
      'いくら忙しいとしても、せめて親の電話には出るべきでしょう。',
    ),
    level: 'casual',
  },
  {
    ko: '-다손 치더라도',
    sentence: '그 계획이 완벽하다손 치더라도 예산이 없으면 실행할 수 없습니다.',
    trans: L(
      "Even supposing that plan is perfect, it can't be carried out without a budget.",
      'Aun suponiendo que ese plan sea perfecto, no se puede ejecutar sin presupuesto.',
      'À supposer même que ce plan soit parfait, il ne peut pas être réalisé sans budget.',
      'Mesmo supondo que esse plano seja perfeito, não dá para executá-lo sem orçamento.',
      'ต่อให้แผนนั้นจะสมบูรณ์แบบก็ตาม ถ้าไม่มีงบประมาณก็ไม่สามารถดำเนินการได้',
      'Sekalipun rencana itu sempurna, tetap tidak bisa dijalankan tanpa anggaran.',
      'Cho dù kế hoạch đó có hoàn hảo đi nữa thì nếu không có ngân sách cũng không thể thực hiện được.',
      'その計画が完璧だとしても、予算がなければ実行することはできません。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는 셈이다',
    sentence: '이번 달엔 사고 싶은 걸 거의 다 샀으니까 돈을 다 쓴 셈이에요.',
    trans: L(
      "This month I bought almost everything I wanted, so I've basically spent all my money.",
      'Este mes compré casi todo lo que quería, así que viene a ser que ya gasté todo el dinero.',
      "Ce mois-ci j'ai acheté presque tout ce que je voulais, autant dire que j'ai dépensé tout mon argent.",
      'Neste mês comprei quase tudo o que queria, então é como se já tivesse gastado todo o dinheiro.',
      'เดือนนี้ฉันซื้อของที่อยากได้เกือบหมดแล้ว ก็เท่ากับว่าใช้เงินไปหมดแล้วนั่นเอง',
      'Bulan ini aku membeli hampir semua yang kuinginkan, jadi praktisnya uangku sudah habis.',
      'Tháng này tôi mua gần hết những thứ mình muốn rồi, nên coi như là đã tiêu hết tiền.',
      '今月は買いたいものをほとんど買ったから、お金を全部使ったようなものです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 셈이다',
    sentence: '열 명 중에 아홉 명이 찬성했으니까 거의 다 찬성한 셈이야.',
    trans: L(
      "Nine out of ten people agreed, so it's basically as if everyone agreed.",
      'Nueve de cada diez personas estuvieron a favor, así que es como si todos hubieran estado de acuerdo.',
      "Neuf personnes sur dix étaient pour, donc autant dire que tout le monde était d'accord.",
      'Nove de dez pessoas concordaram, então é como se todos tivessem concordado.',
      'สิบคนเห็นด้วยตั้งเก้าคน ก็เท่ากับว่าเกือบทุกคนเห็นด้วยนั่นแหละ',
      'Sembilan dari sepuluh orang setuju, jadi praktisnya hampir semua orang setuju.',
      'Mười người thì có chín người tán thành, nên coi như là gần như tất cả đều tán thành.',
      '十人のうち九人が賛成したから、ほぼ全員が賛成したようなものだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 따름이다',
    sentence: '저는 그저 제 일을 했을 따름입니다.',
    trans: L(
      "I merely did my job, that's all.",
      'Yo simplemente hice mi trabajo, nada más.',
      "Je n'ai fait que mon travail, rien de plus.",
      'Eu apenas fiz o meu trabalho, só isso.',
      'ผมแค่ทำหน้าที่ของผมเท่านั้นเองครับ',
      'Saya hanya melakukan tugas saya saja.',
      'Tôi chỉ làm công việc của mình mà thôi.',
      '私はただ自分の仕事をしただけです。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ 따름이다',
    sentence: '이미 끝난 일인데 후회해도 마음만 아플 따름이야.',
    trans: L(
      "It's already over, so regretting it only ends up hurting my heart, that's all.",
      'Ya es algo que terminó, así que arrepentirme solo termina doliéndome el corazón, nada más.',
      "C'est déjà fini, alors avoir des regrets ne fait que me briser le cœur, c'est tout.",
      'Já é coisa do passado, então me arrepender só acaba doendo no coração, só isso.',
      'เรื่องมันจบไปแล้ว ต่อให้เสียใจก็แค่เจ็บใจเปล่า ๆ เท่านั้นเอง',
      'Itu sudah berlalu, jadi menyesalinya pun hanya membuat hati sakit saja.',
      'Chuyện đã xong rồi, dù có hối hận thì cũng chỉ thêm đau lòng mà thôi.',
      'もう終わったことだから、後悔しても心が痛むだけだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 뿐이다',
    sentence: '저는 그냥 시키는 대로 했을 뿐입니다.',
    trans: L(
      "I just did exactly as I was told, that's all.",
      'Yo solo hice lo que me ordenaron, nada más.',
      "Je n'ai fait qu'obéir aux ordres, rien de plus.",
      'Eu apenas fiz o que me mandaram, só isso.',
      'ผมแค่ทำตามที่ถูกสั่งเท่านั้นเอง',
      'Saya hanya melakukan sesuai perintah, itu saja.',
      'Tôi chỉ làm đúng như được bảo thôi.',
      '私はただ言われたとおりにしただけです。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ 뿐이다',
    sentence: '걱정하지 마, 난 그냥 농담했을 뿐이야.',
    trans: L(
      "Don't worry, I was just joking, that's all.",
      'No te preocupes, solo estaba bromeando, nada más.',
      "Ne t'inquiète pas, je plaisantais, c'est tout.",
      'Não se preocupe, eu só estava brincando, só isso.',
      'ไม่ต้องห่วงนะ ฉันแค่ล้อเล่นเฉย ๆ เอง',
      'Jangan khawatir, aku cuma bercanda kok.',
      'Đừng lo, tớ chỉ đùa thôi mà.',
      '心配しないで、ただ冗談を言っただけだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '에 불과하다',
    sentence: '그건 핑계에 불과합니다.',
    trans: L(
      "That's nothing more than an excuse.",
      'Eso no es más que una excusa.',
      "Ce n'est qu'une simple excuse.",
      'Isso não passa de uma desculpa.',
      'นั่นเป็นเพียงแค่ข้ออ้างเท่านั้น',
      'Itu hanyalah sebuah alasan.',
      'Đó chẳng qua chỉ là một cái cớ.',
      'それは言い訳にすぎません。',
    ),
    level: 'formal',
  },
  {
    ko: '에 불과하다',
    sentence: '우리가 만난 지 일주일밖에 안 됐으니까 아직 서로 모르는 사이에 불과해.',
    trans: L(
      "We only met a week ago, so we're still nothing more than strangers to each other.",
      'Solo nos conocimos hace una semana, así que todavía no somos más que dos desconocidos.',
      "On s'est rencontrés il y a seulement une semaine, alors on n'est encore que des inconnus l'un pour l'autre.",
      'A gente se conheceu só faz uma semana, então ainda não passamos de dois estranhos um para o outro.',
      'พวกเราเพิ่งเจอกันได้แค่อาทิตย์เดียว เพราะงั้นตอนนี้ก็ยังเป็นแค่คนที่ไม่รู้จักกันเท่านั้นแหละ',
      'Kita baru kenal seminggu, jadi sekarang kita masih sekadar orang asing satu sama lain.',
      'Tụi mình mới quen nhau được một tuần thôi, nên giờ vẫn chỉ là hai người xa lạ với nhau mà.',
      '出会ってまだ一週間しか経ってないから、お互いまだ知らない者同士にすぎないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-기 나름이다',
    sentence: '아이는 부모가 가르치기 나름이야.',
    trans: L(
      'How a child turns out depends on how the parents raise them.',
      'Cómo resulta un niño depende de cómo lo críen los padres.',
      "Ce que devient un enfant dépend de la façon dont les parents l'élèvent.",
      'Como uma criança se torna depende de como os pais a criam.',
      'เด็กจะเป็นอย่างไรก็ขึ้นอยู่กับวิธีที่พ่อแม่อบรมสั่งสอน',
      'Bagaimana jadinya seorang anak tergantung cara orang tua mendidiknya.',
      'Đứa trẻ nên người hay không là tùy cách bố mẹ dạy dỗ.',
      '子どもは親の育て方次第だよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-기 나름이다',
    sentence: '건강은 평소에 관리하기 나름입니다.',
    trans: L(
      'Your health depends on how you take care of it day to day.',
      'La salud depende de cómo la cuides en el día a día.',
      'La santé dépend de la façon dont on en prend soin au quotidien.',
      'A saúde depende de como você cuida dela no dia a dia.',
      'สุขภาพขึ้นอยู่กับว่าเราดูแลตัวเองในชีวิตประจำวันอย่างไร',
      'Kesehatan tergantung pada cara kita merawatnya sehari-hari.',
      'Sức khỏe là tùy vào cách mình chăm sóc thường ngày.',
      '健康は普段の管理の仕方次第です。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ 나위가 없다',
    sentence: '이 식당 음식은 맛도 좋고 가격도 싸서 더 바랄 나위가 없어요.',
    trans: L(
      "This restaurant's food tastes great and is cheap too, so there's nothing more I could ask for.",
      'La comida de este restaurante está buenísima y además es barata, así que no hay nada más que pedir.',
      "La cuisine de ce restaurant est délicieuse et en plus bon marché, alors il n'y a rien de plus à désirer.",
      'A comida deste restaurante é deliciosa e ainda barata, então não há nada mais a desejar.',
      'อาหารร้านนี้อร่อยแถมราคาก็ถูก เลยไม่มีอะไรให้ต้องการมากไปกว่านี้แล้ว',
      'Makanan restoran ini enak dan harganya juga murah, jadi tidak ada lagi yang bisa diharapkan lebih dari ini.',
      'Đồ ăn ở nhà hàng này vừa ngon vừa rẻ nên không còn gì để mong muốn hơn nữa.',
      'このお店の料理は味も良くて値段も安いので、これ以上望むことは何もありません。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 나위가 없다',
    sentence: '그 친구가 얼마나 성실한지는 더 말할 나위도 없지.',
    trans: L(
      "There's no need to say how diligent that friend is.",
      'No hace falta decir lo diligente que es ese amigo.',
      'Inutile de dire à quel point cet ami est sérieux.',
      'Nem é preciso dizer o quanto esse amigo é dedicado.',
      'ไม่ต้องพูดเลยว่าเพื่อนคนนั้นขยันแค่ไหน',
      'Tak perlu dikatakan lagi betapa rajinnya teman itu.',
      'Khỏi phải nói cậu bạn đó chăm chỉ đến mức nào.',
      'あの友達がどれほど誠実かは、言うまでもないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 것 없이',
    sentence: '택시 부를 것 없이 그냥 같이 걸어가요.',
    trans: L(
      "There's no need to call a taxi, let's just walk together.",
      'No hace falta llamar un taxi, vamos andando juntos.',
      "Pas besoin d'appeler un taxi, marchons ensemble.",
      'Não precisa chamar táxi, vamos a pé juntos.',
      'ไม่ต้องเรียกแท็กซี่หรอก เดินไปด้วยกันเถอะ',
      'Tidak perlu memanggil taksi, ayo jalan kaki bersama saja.',
      'Không cần gọi taxi đâu, mình cùng đi bộ đi.',
      'タクシーを呼ぶまでもなく、一緒に歩いて行きましょう。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 것 없이',
    sentence: '별것 아니니까 멀리서 찾을 것 없이 우리 집에서 먹자.',
    trans: L(
      "It's nothing special, so there's no need to look far—let's just eat at my place.",
      'No es nada del otro mundo, así que no hace falta buscar lejos; comamos en mi casa.',
      "Ce n'est rien d'extraordinaire, alors pas besoin de chercher loin, mangeons chez moi.",
      'Não é nada de mais, então não precisa procurar longe; vamos comer na minha casa.',
      'ไม่ใช่อะไรพิเศษหรอก เลยไม่ต้องไปหาไกล ๆ กินที่บ้านเรากันเถอะ',
      'Bukan hal istimewa kok, jadi tidak usah cari jauh-jauh, makan di rumahku saja.',
      'Có gì đặc biệt đâu, nên khỏi cần tìm đâu xa, ăn ở nhà tớ đi.',
      '大したものじゃないから、遠くまで探すまでもなく、うちで食べよう。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)면 그만이다',
    sentence: '이 옷이 마음에 안 들면 그냥 환불받으면 그만이야.',
    trans: L(
      "If you don't like these clothes, you can just get a refund — that's all there is to it.",
      'Si no te gusta esta ropa, basta con pedir el reembolso y ya está.',
      "Si ces vêtements ne te plaisent pas, tu n'as qu'à te faire rembourser, c'est tout.",
      'Se você não gostar dessas roupas, é só pedir o reembolso e pronto.',
      'ถ้าไม่ชอบเสื้อผ้าชุดนี้ ก็แค่ขอเงินคืนก็จบ',
      'Kalau tidak suka baju ini, tinggal minta uang kembali saja, selesai.',
      'Nếu không thích bộ đồ này thì cứ xin hoàn tiền là xong.',
      'この服が気に入らなければ、返金してもらえばそれでいい。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)면 그만이다',
    sentence: '남들이 뭐라고 하든 저는 제 일만 열심히 하면 그만입니다.',
    trans: L(
      'No matter what others say, all I need to do is just work hard at my own job.',
      'Digan lo que digan los demás, a mí me basta con esforzarme en mi propio trabajo.',
      'Quoi que disent les autres, il me suffit de travailler dur à ma propre tâche.',
      'Digam o que disserem os outros, basta eu me dedicar ao meu próprio trabalho.',
      'ไม่ว่าคนอื่นจะพูดอะไร ผมแค่ตั้งใจทำงานของตัวเองก็พอแล้ว',
      'Apa pun kata orang lain, saya cukup bekerja keras pada pekerjaan saya sendiri saja.',
      'Người khác có nói gì đi nữa thì tôi chỉ cần chăm chỉ làm việc của mình là đủ.',
      '他人が何と言おうと、私は自分の仕事を頑張ればそれでいいのです。',
    ),
    level: 'formal',
  },
  {
    ko: '-기에',
    sentence: '비가 오기에 우산을 챙겨 나왔어요.',
    trans: L(
      'Since it was raining, I grabbed an umbrella on my way out.',
      'Como estaba lloviendo, agarré un paraguas al salir.',
      "Comme il pleuvait, j'ai pris un parapluie en sortant.",
      'Como estava chovendo, peguei um guarda-chuva ao sair.',
      'เพราะฝนตก ฉันเลยหยิบร่มออกมาด้วย',
      'Karena hujan, aku membawa payung saat keluar.',
      'Vì trời mưa nên tôi đã mang theo ô khi ra ngoài.',
      '雨が降っていたので、傘を持って出てきました。',
    ),
    level: 'polite',
  },
  {
    ko: '-기에',
    sentence: '친구가 부산에 간다기에 나도 같이 가기로 했어.',
    trans: L(
      'My friend said they were going to Busan, so I decided to tag along too.',
      'Mi amigo dijo que iba a Busan, así que decidí ir con él también.',
      "Mon ami a dit qu'il allait à Busan, alors j'ai décidé d'y aller avec lui aussi.",
      'Meu amigo disse que ia para Busan, então decidi ir junto também.',
      'เพื่อนบอกว่าจะไปปูซาน ฉันเลยตัดสินใจไปด้วยกัน',
      'Temanku bilang mau pergi ke Busan, jadi aku memutuskan ikut juga.',
      'Bạn tôi bảo sẽ đi Busan nên tôi cũng quyết định đi cùng.',
      '友達がプサンに行くと言うので、私も一緒に行くことにした。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 탓에',
    sentence: '어제 비가 많이 온 탓에 길이 많이 막혔어요.',
    trans: L(
      'Because it rained so much yesterday, the roads were really congested.',
      'Por culpa de la mucha lluvia de ayer, las calles estaban muy congestionadas.',
      "À cause de la forte pluie d'hier, les routes étaient très embouteillées.",
      'Por causa da chuva forte de ontem, as ruas ficaram muito congestionadas.',
      'เพราะเมื่อวานฝนตกหนัก ถนนเลยรถติดมาก',
      'Gara-gara kemarin hujan deras, jalanan jadi sangat macet.',
      'Tại hôm qua mưa nhiều nên đường bị kẹt xe rất nặng.',
      '昨日たくさん雨が降ったせいで、道がとても混みました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 탓에',
    sentence: '급하게 먹은 탓에 배탈이 났어.',
    trans: L(
      'Because I ate in a hurry, I got an upset stomach.',
      'Por comer con prisa, me dolió el estómago.',
      "Comme j'ai mangé trop vite, j'ai eu mal au ventre.",
      'Por ter comido com pressa, fiquei com dor de barriga.',
      'เพราะกินรีบๆ เลยท้องเสีย',
      'Gara-gara makan buru-buru, perutku jadi sakit.',
      'Tại ăn vội nên mình bị đau bụng.',
      '急いで食べたせいでお腹を壊しちゃった。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)로 인해(서)',
    sentence: '이번 폭설로 인해 모든 항공편이 결항되었습니다.',
    trans: L(
      'Due to this heavy snowfall, all flights have been cancelled.',
      'Debido a esta fuerte nevada, todos los vuelos han sido cancelados.',
      'En raison de ces fortes chutes de neige, tous les vols ont été annulés.',
      'Devido a esta forte nevasca, todos os voos foram cancelados.',
      'เนื่องจากหิมะตกหนักครั้งนี้ เที่ยวบินทั้งหมดถูกยกเลิก',
      'Akibat hujan salju lebat ini, semua penerbangan dibatalkan.',
      'Do trận tuyết lớn lần này, tất cả các chuyến bay đã bị hủy.',
      '今回の大雪により、すべての航空便が欠航となりました。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)로 인해(서)',
    sentence: '윗집 소음으로 인해서 어젯밤에 한숨도 못 잤어요.',
    trans: L(
      "Because of the noise from upstairs, I couldn't sleep a wink last night.",
      'Por el ruido del piso de arriba, anoche no pude pegar ojo.',
      "À cause du bruit de l'étage du dessus, je n'ai pas pu fermer l'œil de la nuit.",
      'Por causa do barulho do andar de cima, ontem à noite não preguei o olho.',
      'เพราะเสียงดังจากชั้นบน เมื่อคืนฉันนอนไม่หลับเลยสักนิด',
      'Karena suara berisik dari lantai atas, tadi malam saya tidak bisa tidur sama sekali.',
      'Vì tiếng ồn từ tầng trên, tối qua tôi không chợp mắt được chút nào.',
      '上の階の騒音のせいで、昨夜は一睡もできませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '-고자',
    sentence: '회사의 경쟁력을 높이고자 신기술 도입을 추진하고 있습니다.',
    trans: L(
      "In order to strengthen the company's competitiveness, we are pushing forward with adopting new technology.",
      'Con el propósito de aumentar la competitividad de la empresa, estamos impulsando la adopción de nuevas tecnologías.',
      "Dans le but de renforcer la compétitivité de l'entreprise, nous poussons l'adoption de nouvelles technologies.",
      'A fim de aumentar a competitividade da empresa, estamos promovendo a adoção de novas tecnologias.',
      'เพื่อยกระดับขีดความสามารถในการแข่งขันของบริษัท เรากำลังผลักดันการนำเทคโนโลยีใหม่มาใช้',
      'Demi meningkatkan daya saing perusahaan, kami sedang mendorong penerapan teknologi baru.',
      'Nhằm nâng cao năng lực cạnh tranh của công ty, chúng tôi đang thúc đẩy việc đưa công nghệ mới vào áp dụng.',
      '会社の競争力を高めようと、新技術の導入を推進しております。',
    ),
    level: 'formal',
  },
  {
    ko: '-고자',
    sentence: '그동안의 연구 결과를 발표하고자 이 자리에 섰습니다.',
    trans: L(
      'I have come up here intending to present the research results from all this time.',
      'Me he puesto de pie aquí con la intención de presentar los resultados de la investigación de todo este tiempo.',
      "Je me suis présenté ici dans le but d'exposer les résultats de recherche obtenus jusqu'à présent.",
      'Vim até aqui com a intenção de apresentar os resultados da pesquisa de todo este tempo.',
      'ผมขึ้นมายืน ณ ที่นี้เพื่อนำเสนอผลการวิจัยที่ผ่านมา',
      'Saya berdiri di sini dengan maksud untuk memaparkan hasil penelitian selama ini.',
      'Tôi đứng ở đây nhằm trình bày kết quả nghiên cứu trong suốt thời gian qua.',
      'これまでの研究結果を発表しようと、この場に立ちました。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는 나머지',
    sentence: '시험 결과를 걱정한 나머지 밤새 한숨도 못 잤어요.',
    trans: L(
      "I was so worried about the exam results that I couldn't sleep a wink all night.",
      'Me preocupé tanto por los resultados del examen que no pude pegar ojo en toda la noche.',
      "J'étais tellement inquiet pour les résultats de l'examen que je n'ai pas fermé l'œil de la nuit.",
      'Fiquei tão preocupado com o resultado da prova que não preguei o olho a noite toda.',
      'กังวลเรื่องผลสอบมากจนนอนไม่หลับทั้งคืนเลยค่ะ',
      'Saya begitu cemas akan hasil ujian sampai tidak bisa tidur semalaman.',
      'Vì quá lo lắng về kết quả thi nên tôi đã không chợp mắt được suốt đêm.',
      '試験の結果を心配するあまり、一晩中一睡もできませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 나머지',
    sentence: '그 소식을 듣고 너무 놀란 나머지 들고 있던 컵을 떨어뜨렸다.',
    trans: L(
      'Upon hearing the news, I was so startled that I dropped the cup I was holding.',
      'Al oír esa noticia, me asusté tanto que se me cayó la taza que tenía en la mano.',
      "En entendant cette nouvelle, j'ai été si surpris que j'ai laissé tomber la tasse que je tenais.",
      'Ao ouvir a notícia, fiquei tão assustado que deixei cair a xícara que segurava.',
      'พอได้ยินข่าวนั้นก็ตกใจมากจนทำแก้วที่ถืออยู่หล่น',
      'Mendengar kabar itu, saya begitu terkejut sampai menjatuhkan cangkir yang sedang saya pegang.',
      'Nghe tin đó, tôi giật mình đến mức làm rơi cái cốc đang cầm trên tay.',
      'その知らせを聞いて、驚きのあまり持っていたコップを落としてしまった。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ 지경이다',
    sentence: '배가 너무 고파서 죽을 지경이에요.',
    trans: L(
      "I'm so hungry I could die.",
      'Tengo tanta hambre que me muero.',
      "J'ai tellement faim que je vais mourir.",
      'Estou com tanta fome que vou morrer.',
      'หิวจนจะเป็นจะตายแล้ว',
      'Aku lapar sekali sampai rasanya mau mati.',
      'Tôi đói đến mức tưởng chừng sắp chết.',
      'お腹が空きすぎて死にそうです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 지경이다',
    sentence: '아이들이 하루 종일 떠들어서 머리가 터질 지경이야.',
    trans: L(
      "The kids have been making noise all day, my head's about to explode.",
      'Los niños han estado gritando todo el día, la cabeza me va a estallar.',
      'Les enfants font du bruit toute la journée, ma tête va exploser.',
      'As crianças ficaram fazendo barulho o dia todo, minha cabeça vai explodir.',
      'เด็กๆ ส่งเสียงดังทั้งวัน หัวจะระเบิดอยู่แล้ว',
      'Anak-anak ribut seharian, sampai kepalaku mau pecah rasanya.',
      'Bọn trẻ ồn ào cả ngày, đầu tôi sắp nổ tung đến nơi rồi.',
      '子どもたちが一日中騒いで、頭が爆発しそうだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 커녕',
    sentence: '주말에 쉬기는커녕 회사에 또 나가야 돼.',
    trans: L(
      'Far from resting this weekend, I have to go in to work again.',
      'Lejos de descansar el fin de semana, tengo que ir otra vez a la oficina.',
      'Loin de me reposer ce week-end, je dois encore aller au bureau.',
      'Longe de descansar no fim de semana, ainda tenho que ir trabalhar de novo.',
      'วันหยุดสุดสัปดาห์อย่าว่าแต่จะได้พักเลย ยังต้องไปทำงานอีก',
      'Jangankan istirahat di akhir pekan, aku malah harus masuk kerja lagi.',
      'Cuối tuần đừng nói đến chuyện nghỉ ngơi, tôi còn phải đi làm nữa.',
      '週末に休むどころか、また会社に出なきゃいけないんだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 커녕',
    sentence: '그 식당은 맛있기는커녕 너무 짜서 한 입도 못 먹었어요.',
    trans: L(
      "Far from being delicious, that restaurant's food was so salty I couldn't eat a single bite.",
      'Lejos de estar rico, ese restaurante estaba tan salado que no pude comer ni un bocado.',
      "Loin d'être bon, ce restaurant était si salé que je n'ai pas pu en avaler une bouchée.",
      'Longe de ser gostoso, aquele restaurante estava tão salgado que não consegui comer nem uma garfada.',
      'ร้านนั้นอย่าว่าแต่อร่อยเลย เค็มมากจนกินไม่ได้สักคำ',
      'Jangankan enak, restoran itu malah terlalu asin sampai aku tidak bisa makan sesuap pun.',
      'Quán đó đừng nói đến ngon, mặn đến mức tôi không ăn nổi một miếng.',
      'あの店はおいしいどころか、しょっぱすぎて一口も食べられませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '-든지',
    sentence: '밥을 먹든지 빵을 먹든지 빨리 정하세요.',
    trans: L(
      'Whether you eat rice or eat bread, please decide quickly.',
      'Ya sea que comas arroz o que comas pan, decídete rápido, por favor.',
      "Que tu manges du riz ou que tu manges du pain, décide-toi vite, s'il te plaît.",
      'Quer você coma arroz, quer coma pão, decida logo, por favor.',
      'จะกินข้าวหรือจะกินขนมปังก็ได้ ช่วยตัดสินใจเร็ว ๆ หน่อยนะคะ',
      'Mau makan nasi atau makan roti, tolong cepat putuskan.',
      'Dù ăn cơm hay ăn bánh mì thì cũng xin hãy quyết định nhanh lên.',
      'ご飯を食べるにせよパンを食べるにせよ、早く決めてください。',
    ),
    level: 'polite',
  },
  {
    ko: '-든지',
    sentence: '네가 가든지 말든지 나는 신경 안 써.',
    trans: L(
      "Whether you go or not, I don't care.",
      'Que vayas o no, me da igual.',
      "Que tu y ailles ou non, ça m'est égal.",
      'Quer você vá ou não, eu não ligo.',
      'เธอจะไปหรือไม่ไป ฉันก็ไม่สนใจหรอก',
      'Mau kamu pergi atau tidak, aku tidak peduli.',
      'Cậu đi hay không thì tớ cũng chẳng quan tâm.',
      '君が行こうが行くまいが、僕は気にしないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ 끝에',
    sentence: '오랜 시간 연습한 끝에 드디어 운전면허를 땄습니다.',
    trans: L(
      "After practicing for a long time, I finally got my driver's license.",
      'Tras practicar mucho tiempo, por fin saqué el permiso de conducir.',
      "Après m'être entraîné longtemps, j'ai enfin obtenu mon permis de conduire.",
      'Depois de muito tempo praticando, finalmente tirei a carteira de motorista.',
      'หลังจากฝึกฝนมาเป็นเวลานาน ในที่สุดฉันก็สอบใบขับขี่ผ่าน',
      'Setelah lama berlatih, akhirnya saya mendapatkan SIM.',
      'Sau một thời gian dài luyện tập, cuối cùng tôi đã lấy được bằng lái xe.',
      '長い間練習した末に、ついに運転免許を取りました。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ 끝에',
    sentence: '한참을 헤맨 끝에 겨우 호텔을 찾았어.',
    trans: L(
      'After wandering around for ages, I barely found the hotel.',
      'Después de dar vueltas un buen rato, por fin encontré el hotel a duras penas.',
      "Après avoir tourné en rond un bon moment, j'ai fini par trouver l'hôtel de justesse.",
      'Depois de ficar perdido por um bom tempo, mal consegui achar o hotel.',
      'หลังจากหลงทางอยู่นาน ในที่สุดก็หาโรงแรมเจอแบบเฉียดฉิว',
      'Setelah lama tersesat, akhirnya dengan susah payah aku menemukan hotelnya.',
      'Sau một hồi lạc đường, cuối cùng mình mới tìm được khách sạn một cách chật vật.',
      'ずいぶん迷った末に、なんとかホテルを見つけたよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-자',
    sentence: '버스에서 내리자 비가 쏟아지기 시작했어요.',
    trans: L(
      'As soon as I got off the bus, it started pouring rain.',
      'En cuanto bajé del autobús, empezó a llover a cántaros.',
      "Dès que je suis descendu du bus, il s'est mis à pleuvoir à verse.",
      'Assim que desci do ônibus, começou a chover torrencialmente.',
      'พอลงจากรถบัส ฝนก็เริ่มตกหนักเลย',
      'Begitu saya turun dari bus, hujan langsung turun deras.',
      'Vừa xuống xe buýt thì trời bắt đầu mưa như trút nước.',
      'バスを降りると、雨が激しく降り始めました。',
    ),
    level: 'polite',
  },
  {
    ko: '-자',
    sentence: '선생님이 교실을 나가자 아이들이 떠들기 시작했다.',
    trans: L(
      'The moment the teacher left the classroom, the children started making noise.',
      'En cuanto el profesor salió del aula, los niños empezaron a alborotar.',
      'Dès que le professeur a quitté la classe, les enfants se sont mis à chahuter.',
      'No momento em que o professor saiu da sala, as crianças começaram a fazer barulho.',
      'พอครูออกจากห้องเรียน เด็ก ๆ ก็เริ่มส่งเสียงดัง',
      'Begitu guru keluar dari kelas, anak-anak mulai ribut.',
      'Ngay khi thầy giáo rời khỏi lớp, bọn trẻ bắt đầu ồn ào.',
      '先生が教室を出ると、子供たちが騒ぎ始めた。',
    ),
    level: 'formal',
  },
  {
    ko: '-고서',
    sentence: '손을 깨끗이 씻고서 밥을 먹었어요.',
    trans: L(
      'I washed my hands clean and then ate.',
      'Me lavé bien las manos y luego comí.',
      "Je me suis bien lavé les mains, puis j'ai mangé.",
      'Lavei bem as mãos e depois comi.',
      'ล้างมือให้สะอาดแล้วค่อยกินข้าว',
      'Saya mencuci tangan sampai bersih lalu makan.',
      'Tôi rửa tay sạch sẽ rồi mới ăn cơm.',
      '手をきれいに洗ってからご飯を食べました。',
    ),
    level: 'polite',
  },
  {
    ko: '-고서',
    sentence: '지갑을 집에 두고서 그냥 나와 버렸어.',
    trans: L(
      'I left my wallet at home and just walked out.',
      'Me dejé la cartera en casa y salí sin más.',
      "J'ai laissé mon portefeuille à la maison et je suis sorti comme ça.",
      'Deixei a carteira em casa e simplesmente saí.',
      'ลืมกระเป๋าเงินไว้ที่บ้านแล้วก็ออกมาเฉยเลย',
      'Aku meninggalkan dompet di rumah dan langsung keluar begitu saja.',
      'Tôi để quên ví ở nhà rồi cứ thế đi ra ngoài.',
      '財布を家に置いたまま、そのまま出てきちゃった。',
    ),
    level: 'casual',
  },
  {
    ko: '-다 못해',
    sentence: '그 케이크는 달다 못해 머리가 아플 정도였어요.',
    trans: L(
      'That cake was so sweet it actually gave me a headache.',
      'Ese pastel era tan dulce que hasta me dio dolor de cabeza.',
      'Ce gâteau était sucré au point de me donner mal à la tête.',
      'Aquele bolo era tão doce que até me deu dor de cabeça.',
      'เค้กชิ้นนั้นหวานจนปวดหัวเลยล่ะ',
      'Kue itu manis sampai-sampai bikin kepala saya pusing.',
      'Cái bánh đó ngọt đến mức làm tôi đau cả đầu.',
      'あのケーキは甘いを通り越して頭が痛くなるほどでした。',
    ),
    level: 'polite',
  },
  {
    ko: '-다 못해',
    sentence: '동생은 참다 못해 결국 화를 냈습니다.',
    trans: L(
      "My younger sibling couldn't hold it in any longer and finally lost their temper.",
      'Mi hermano menor no aguantó más y al final se enojó.',
      "Mon cadet n'en pouvait plus de se retenir et a fini par s'emporter.",
      'Meu irmão mais novo não aguentou mais e acabou se irritando.',
      'น้องอดทนจนทนไม่ไหว สุดท้ายก็โมโหขึ้นมา',
      'Adik saya tidak tahan lagi menahan diri dan akhirnya marah.',
      'Em tôi nhịn đến mức không nhịn nổi nữa nên cuối cùng đã nổi giận.',
      '弟は我慢しきれず、ついに怒り出した。',
    ),
    level: 'formal',
  },
  {
    ko: '-다고 해서',
    sentence: '친구가 그 영화가 재미있다고 해서 주말에 보러 갈 거예요.',
    trans: L(
      "A friend said that movie was fun, so I'm going to go see it this weekend.",
      'Una amiga me dijo que esa película es divertida, así que iré a verla el fin de semana.',
      "Une amie m'a dit que ce film était amusant, alors je vais aller le voir ce week-end.",
      'Uma amiga disse que aquele filme é divertido, então vou assisti-lo no fim de semana.',
      'เพื่อนบอกว่าหนังเรื่องนั้นสนุก เลยจะไปดูช่วงสุดสัปดาห์',
      'Teman saya bilang film itu seru, jadi akhir pekan ini saya akan pergi menontonnya.',
      'Bạn tôi nói bộ phim đó hay nên cuối tuần tôi sẽ đi xem.',
      '友達がその映画が面白いと言っていたので、週末に見に行くつもりです。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고 해서',
    sentence: '내일 비가 온다고 해서 우산을 미리 챙겼어.',
    trans: L(
      "They said it's going to rain tomorrow, so I packed an umbrella in advance.",
      'Dijeron que mañana va a llover, así que preparé un paraguas por adelantado.',
      "On a dit qu'il allait pleuvoir demain, alors j'ai pris un parapluie à l'avance.",
      'Disseram que vai chover amanhã, então já separei um guarda-chuva.',
      'เขาบอกว่าพรุ่งนี้ฝนจะตก เลยเตรียมร่มไว้ล่วงหน้า',
      'Katanya besok akan hujan, jadi aku sudah menyiapkan payung dari sekarang.',
      'Người ta nói mai trời mưa nên tôi đã chuẩn bị sẵn ô.',
      '明日雨が降ると言うので、傘を前もって準備しておいた。',
    ),
    level: 'casual',
  },
  {
    ko: '-다고 해도',
    sentence: '아무리 바쁘다고 해도 밥은 꼭 챙겨 드세요.',
    trans: L(
      'No matter how busy you say you are, please be sure to eat properly.',
      'Por muy ocupado que digas que estás, no dejes de comer bien.',
      'Même si tu dis que tu es très occupé, prends bien le temps de manger.',
      'Por mais ocupado que você diga que está, não deixe de se alimentar bem.',
      'ต่อให้บอกว่ายุ่งแค่ไหน ก็อย่าลืมกินข้าวให้ครบนะคะ',
      'Sesibuk apa pun katamu, jangan lupa makan dengan teratur ya.',
      'Dù có bảo bận đến mấy thì cũng nhớ ăn uống đầy đủ nhé.',
      'どんなに忙しいと言っても、ご飯はちゃんと食べてくださいね。',
    ),
    level: 'polite',
  },
  {
    ko: '-다고 해도',
    sentence: '그 사람이 천재라고 해도 난 별로 안 부러워.',
    trans: L(
      "Even if they say he's a genius, I'm not really envious.",
      'Aunque digan que es un genio, no lo envidio mucho.',
      "Même si on dit que c'est un génie, je ne l'envie pas vraiment.",
      'Mesmo que digam que ele é um gênio, eu não invejo muito.',
      'ต่อให้บอกว่าเขาเป็นอัจฉริยะ ฉันก็ไม่ค่อยอิจฉาหรอก',
      'Meskipun katanya dia jenius, aku tidak terlalu iri.',
      'Dù có nói anh ấy là thiên tài thì mình cũng chẳng ganh tị mấy.',
      'あの人が天才だと言われても、私は別にうらやましくない。',
    ),
    level: 'casual',
  },
  {
    ko: '-다는 게',
    sentence: '매일 운동한다는 게 생각보다 쉽지 않더라고요.',
    trans: L(
      'Working out every day turns out to be harder than I thought.',
      'Eso de hacer ejercicio todos los días resulta más difícil de lo que pensaba.',
      "Faire du sport tous les jours s'avère plus difficile que je ne le pensais.",
      'Isso de se exercitar todos os dias é mais difícil do que eu pensava.',
      'การออกกำลังกายทุกวันมันยากกว่าที่คิดไว้นะ',
      'Berolahraga setiap hari ternyata lebih sulit daripada yang kukira.',
      'Việc tập thể dục mỗi ngày hóa ra khó hơn tôi nghĩ.',
      '毎日運動するというのは思ったより簡単じゃないんですよね。',
    ),
    level: 'polite',
  },
  {
    ko: '-다는 게',
    sentence: '혼자 외국에서 산다는 게 가끔은 너무 외로워.',
    trans: L(
      'Living abroad alone sometimes gets so lonely.',
      'Vivir solo en el extranjero a veces se vuelve muy solitario.',
      "Vivre seul à l'étranger, c'est parfois tellement solitaire.",
      'Morar sozinho no exterior às vezes fica tão solitário.',
      'การอยู่คนเดียวในต่างประเทศบางทีมันเหงามากเลย',
      'Tinggal sendirian di luar negeri kadang terasa sangat kesepian.',
      'Việc sống một mình ở nước ngoài đôi khi cô đơn lắm.',
      '一人で外国で暮らすというのは、たまにすごく寂しいんだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ까 싶다',
    sentence: '비가 올까 싶어서 우산을 챙겼어요.',
    trans: L(
      'I brought an umbrella, thinking it might rain.',
      'Cogí un paraguas por si acaso llovía.',
      "J'ai pris un parapluie au cas où il pleuvrait.",
      'Levei um guarda-chuva achando que talvez chovesse.',
      'เผื่อว่าฝนจะตกเลยพกร่มไปด้วย',
      'Saya membawa payung karena pikir-pikir mungkin akan hujan.',
      'Tôi mang theo ô vì nghĩ chắc trời sẽ mưa.',
      '雨が降るかと思って傘を持って行きました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ까 싶다',
    sentence: '오늘은 그냥 집에서 쉴까 싶다.',
    trans: L(
      "I'm thinking I might just rest at home today.",
      'Hoy estoy pensando en quedarme descansando en casa.',
      "Aujourd'hui, je me dis que je vais juste me reposer à la maison.",
      'Hoje fico pensando em só descansar em casa.',
      'วันนี้ชักจะอยากอยู่บ้านพักผ่อนเฉย ๆ',
      'Hari ini aku pikir-pikir mau istirahat saja di rumah.',
      'Hôm nay tôi đang nghĩ chắc cứ ở nhà nghỉ ngơi thôi.',
      '今日はただ家で休もうかと思う。',
    ),
    level: 'casual',
  },
  {
    ko: '-지 싶다',
    sentence: '이번 시험은 생각보다 어렵지 싶어요.',
    trans: L(
      'I think this exam is going to be harder than expected.',
      'Me parece que este examen va a ser más difícil de lo esperado.',
      "J'ai l'impression que cet examen sera plus difficile que prévu.",
      'Acho que esta prova vai ser mais difícil do que o esperado.',
      'ฉันคิดว่าข้อสอบครั้งนี้น่าจะยากกว่าที่คิดนะ',
      'Kurasa ujian kali ini akan lebih sulit dari yang dibayangkan.',
      'Tôi nghĩ kỳ thi lần này có lẽ khó hơn mình tưởng.',
      '今回の試験は思ったより難しいんじゃないかと思います。',
    ),
    level: 'polite',
  },
  {
    ko: '-지 싶다',
    sentence: '지금 출발하면 늦지 싶다.',
    trans: L(
      "I have a feeling we'll be late if we leave now.",
      'Tengo la sensación de que llegaremos tarde si salimos ahora.',
      "J'ai l'impression qu'on sera en retard si on part maintenant.",
      'Tenho a impressão de que vamos nos atrasar se sairmos agora.',
      'รู้สึกว่าถ้าออกไปตอนนี้คงจะสายแน่',
      'Rasanya kalau berangkat sekarang kita bakal telat.',
      'Tôi có cảm giác giờ mà đi thì sẽ bị trễ mất.',
      '今出発したら遅れるんじゃないかな。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ가 싶다',
    sentence: '요즘 그 친구가 좀 힘든가 싶어서 자주 연락해요.',
    trans: L(
      'I wonder if my friend is having a hard time these days, so I get in touch often.',
      'Me pregunto si a esa amiga le está costando un poco últimamente, así que la contacto seguido.',
      'Je me demande si cette amie ne traverse pas une période difficile en ce moment, alors je la contacte souvent.',
      'Fico me perguntando se esse amigo não está passando por um momento difícil ultimamente, então falo com ele com frequência.',
      'สงสัยว่าช่วงนี้เพื่อนคนนั้นจะลำบากอยู่หรือเปล่า เลยติดต่อไปบ่อย ๆ',
      'Jangan-jangan teman itu sedang kesulitan belakangan ini, makanya aku sering menghubunginya.',
      'Không biết dạo này người bạn đó có đang vất vả không nên mình hay liên lạc.',
      '最近あの子はちょっと大変なのかなと思って、よく連絡しています。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ가 싶다',
    sentence: '내가 아까 말실수를 한 건가 싶어서 계속 신경 쓰여.',
    trans: L(
      'I keep wondering if I said something wrong earlier, so it keeps bugging me.',
      'Me pregunto si metí la pata al hablar hace un rato, y no se me quita de la cabeza.',
      "Je me demande si je n'ai pas fait une gaffe tout à l'heure, et ça me trotte sans cesse dans la tête.",
      'Fico me perguntando se falei alguma besteira ainda há pouco, e isso não sai da minha cabeça.',
      'สงสัยว่าเมื่อกี้เราจะพูดพลาดไปหรือเปล่า เลยกังวลอยู่ตลอด',
      'Jangan-jangan tadi aku salah ngomong ya, jadi terus kepikiran.',
      'Không biết lúc nãy mình có lỡ lời không nữa, nên cứ bứt rứt mãi.',
      'さっき言い間違いをしたのかなと思って、ずっと気になってる。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㅁ',
    sentence: '내일 오후 2시에 팀 회의 있음. 회의 자료 미리 준비할 것.',
    trans: L(
      'Team meeting tomorrow at 2 p.m. Prepare the meeting materials in advance.',
      'Reunión de equipo mañana a las 2 p. m. Preparar el material de la reunión con antelación.',
      "Réunion d'équipe demain à 14 h. Préparer les documents de la réunion à l'avance.",
      'Reunião de equipe amanhã às 14h. Preparar o material da reunião com antecedência.',
      'มีประชุมทีมพรุ่งนี้บ่ายสองโมง เตรียมเอกสารการประชุมไว้ล่วงหน้า',
      'Ada rapat tim besok pukul 2 siang. Siapkan materi rapat sebelumnya.',
      'Có họp nhóm vào 2 giờ chiều mai. Chuẩn bị tài liệu họp trước.',
      '明日午後2時にチーム会議あり。会議資料を事前に準備すること。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㅁ',
    sentence: '경찰은 그가 범인임을 밝혀냈습니다.',
    trans: L(
      'The police revealed that he was the culprit.',
      'La policía reveló que él era el culpable.',
      "La police a révélé qu'il était le coupable.",
      'A polícia revelou que ele era o culpado.',
      'ตำรวจเปิดเผยว่าเขาเป็นคนร้าย',
      'Polisi mengungkap bahwa dia adalah pelakunya.',
      'Cảnh sát đã làm rõ rằng anh ta chính là thủ phạm.',
      '警察は彼が犯人であることを突き止めました。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는 데에',
    sentence: '한국어를 배우는 데에 시간이 꽤 많이 걸렸어요.',
    trans: L(
      'It took quite a lot of time to learn Korean.',
      'Aprender coreano me llevó bastante tiempo.',
      "Apprendre le coréen m'a pris pas mal de temps.",
      'Levou bastante tempo para aprender coreano.',
      'ใช้เวลาค่อนข้างมากในการเรียนภาษาเกาหลี',
      'Belajar bahasa Korea memakan waktu cukup banyak.',
      'Việc học tiếng Hàn đã mất khá nhiều thời gian.',
      '韓国語を学ぶのにかなり時間がかかりました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 데에',
    sentence: '이 가위는 종이를 자르는 데에 정말 편해.',
    trans: L(
      'These scissors are really convenient for cutting paper.',
      'Estas tijeras son muy cómodas para cortar papel.',
      'Ces ciseaux sont vraiment pratiques pour couper du papier.',
      'Esta tesoura é muito prática para cortar papel.',
      'กรรไกรอันนี้สะดวกมากสำหรับการตัดกระดาษ',
      'Gunting ini benar-benar praktis untuk memotong kertas.',
      'Cái kéo này thật sự tiện lợi để cắt giấy.',
      'このはさみは紙を切るのに本当に便利だよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(이)나마 / -(으)나마',
    sentence: '잠깐이나마 쉴 수 있어서 다행이었어요.',
    trans: L(
      "I'm glad I got to rest, even if only for a moment.",
      'Me alegro de haber podido descansar, aunque solo fuera un momento.',
      "Je suis content d'avoir pu me reposer, même si ce n'était qu'un instant.",
      'Fico feliz por ter podido descansar, mesmo que só por um instante.',
      'ดีที่ได้พักบ้าง แม้จะเพียงชั่วครู่ก็ตาม',
      'Untunglah aku bisa istirahat, meskipun hanya sebentar.',
      'May mà tôi được nghỉ ngơi, dù chỉ trong chốc lát.',
      'ほんの少しの間なりとも休めてよかったです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(이)나마 / -(으)나마',
    sentence: '사진으로나마 고향 풍경을 볼 수 있어서 좋다.',
    trans: L(
      "It's nice that I can see my hometown's scenery, even if only through photos.",
      'Está bien poder ver el paisaje de mi pueblo, aunque sea solo en fotos.',
      "C'est agréable de pouvoir voir les paysages de mon pays natal, même si ce n'est qu'en photos.",
      'É bom poder ver a paisagem da minha terra natal, mesmo que só por fotos.',
      'ดีนะที่ได้เห็นวิวบ้านเกิด แม้จะเป็นแค่ในรูปก็ตาม',
      'Senang rasanya bisa melihat pemandangan kampung halaman, meskipun hanya lewat foto.',
      'Thật vui khi được ngắm cảnh quê hương, dù chỉ là qua những bức ảnh.',
      '写真ででも故郷の風景を見られてうれしい。',
    ),
    level: 'casual',
  },
  {
    ko: '-느니만 못하다',
    sentence: '마음에도 없는 사과는 차라리 안 하느니만 못합니다.',
    trans: L(
      "An apology you don't even mean is worse than not apologizing at all.",
      'Una disculpa que ni sientes es peor que no disculparse en absoluto.',
      "Des excuses que l'on ne pense même pas valent moins que pas d'excuses du tout.",
      'Um pedido de desculpas que você nem sente é pior do que não se desculpar.',
      'การขอโทษที่ไม่ได้รู้สึกจริงยังแย่กว่าการไม่ขอโทษเสียอีก',
      'Permintaan maaf yang tidak tulus malah lebih buruk daripada tidak minta maaf sama sekali.',
      'Lời xin lỗi mà bạn còn chẳng thật lòng thì còn tệ hơn là không xin lỗi.',
      '心にもない謝罪は、いっそしない方がましです。',
    ),
    level: 'formal',
  },
  {
    ko: '-느니만 못하다',
    sentence: '이렇게 대충 공부할 거면 아예 안 하느니만 못해.',
    trans: L(
      "If you're going to study this sloppily, you're better off not studying at all.",
      'Si vas a estudiar tan a la ligera, mejor no estudies nada.',
      "Si c'est pour réviser aussi mollement, autant ne pas réviser du tout.",
      'Se for estudar nas coxas assim, é melhor nem estudar.',
      'ถ้าจะอ่านหนังสือแบบขอไปทีแบบนี้ ไม่อ่านเสียยังจะดีกว่า',
      'Kalau belajarnya asal-asalan begini, mendingan tidak usah belajar sekalian.',
      'Nếu học qua loa kiểu này thì thà đừng học còn hơn.',
      'こんなにいい加減に勉強するなら、いっそやらない方がましだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-았/었던들',
    sentence: '조금만 일찍 출발했던들 막차를 놓치지는 않았을 거예요.',
    trans: L(
      "Had we left just a little earlier, we wouldn't have missed the last train.",
      'Si hubiéramos salido solo un poco antes, no habríamos perdido el último tren.',
      "Si seulement nous étions partis un peu plus tôt, nous n'aurions pas raté le dernier train.",
      'Se tivéssemos saído só um pouco mais cedo, não teríamos perdido o último trem.',
      'หากออกเดินทางเร็วกว่านี้สักหน่อย ก็คงไม่พลาดรถไฟเที่ยวสุดท้าย',
      'Andai kita berangkat sedikit lebih awal, pasti tidak akan ketinggalan kereta terakhir.',
      'Giá mà chúng ta khởi hành sớm hơn một chút thì đã không lỡ chuyến tàu cuối.',
      'もう少し早く出発していたなら、終電を逃さなかったでしょうに。',
    ),
    level: 'polite',
  },
  {
    ko: '-았/었던들',
    sentence: '그의 경고를 귀담아들었던들 이런 참사는 일어나지 않았으리라.',
    trans: L(
      'Had we heeded his warning, such a disaster would surely not have occurred.',
      'Si hubiéramos prestado atención a su advertencia, semejante desastre no habría ocurrido.',
      'Si seulement nous avions tenu compte de son avertissement, une telle catastrophe ne serait pas arrivée.',
      'Se ao menos tivéssemos dado ouvidos ao seu aviso, tamanho desastre não teria acontecido.',
      'หากได้ใส่ใจฟังคำเตือนของเขา หายนะเช่นนี้คงไม่เกิดขึ้นเป็นแน่',
      'Andai dulu kita mengindahkan peringatannya, bencana seperti ini tentu tidak akan terjadi.',
      'Giá mà ta đã lắng nghe lời cảnh báo của ông ấy thì thảm họa thế này hẳn đã không xảy ra.',
      '彼の警告に耳を傾けていたなら、このような惨事は起こらなかったであろう。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ 새(도) 없이',
    sentence: '아이가 넘어져서 울 새도 없이 다시 일어나 뛰어갔어요.',
    trans: L(
      'The child fell down and, without even a moment to cry, got right back up and ran off.',
      'El niño se cayó y, sin tiempo siquiera para llorar, se levantó de nuevo y salió corriendo.',
      "L'enfant est tombé et, sans même avoir le temps de pleurer, s'est relevé et est reparti en courant.",
      'A criança caiu e, sem tempo nem para chorar, se levantou de novo e saiu correndo.',
      'เด็กล้มลงแล้วลุกขึ้นวิ่งต่อทันทีโดยไม่มีเวลาแม้แต่จะร้องไห้',
      'Anak itu jatuh, lalu tanpa sempat menangis pun langsung bangun dan berlari lagi.',
      'Đứa bé ngã xuống rồi đứng dậy chạy đi ngay, không kịp cả khóc.',
      '子供が転んで、泣く間もなくまた立ち上がって走って行きました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ 새(도) 없이',
    sentence: '손님이 계속 밀려와서 점심을 먹을 새 없이 일했다.',
    trans: L(
      'Customers kept pouring in, so I worked without even a chance to eat lunch.',
      'Los clientes no paraban de llegar, así que trabajé sin tener tiempo ni de almorzar.',
      "Les clients n'arrêtaient pas d'affluer, alors j'ai travaillé sans même avoir le temps de déjeuner.",
      'Os clientes não paravam de chegar, então trabalhei sem nem ter tempo de almoçar.',
      'ลูกค้าเข้ามาไม่หยุด เลยทำงานจนไม่มีเวลาแม้แต่จะกินข้าวกลางวัน',
      'Pelanggan terus berdatangan, jadi aku bekerja tanpa sempat makan siang sama sekali.',
      'Khách cứ ùn ùn kéo đến nên tôi làm việc đến mức không có cả thời gian ăn trưa.',
      'お客さんがひっきりなしに来て、昼ごはんを食べる間もなく働いた。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 한이 있어도',
    sentence: '회사를 그만두는 한이 있어도 이 프로젝트는 끝까지 책임지겠습니다.',
    trans: L(
      'Even if it means quitting the company, I will take responsibility for this project to the very end.',
      'Aunque tenga que renunciar a la empresa, me haré responsable de este proyecto hasta el final.',
      "Même si je dois quitter l'entreprise, j'assumerai la responsabilité de ce projet jusqu'au bout.",
      'Mesmo que eu tenha que pedir demissão da empresa, vou me responsabilizar por este projeto até o fim.',
      'ถึงแม้จะต้องลาออกจากบริษัท ผมก็จะรับผิดชอบโครงการนี้จนถึงที่สุด',
      'Bahkan kalau sampai harus keluar dari perusahaan, saya akan bertanggung jawab atas proyek ini sampai akhir.',
      'Dù có phải nghỉ việc ở công ty, tôi cũng sẽ chịu trách nhiệm với dự án này đến cùng.',
      '会社を辞めることになっても、このプロジェクトは最後まで責任を持ちます。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는 한이 있어도',
    sentence: '밤을 새우는 한이 있어도 내일까지 이거 다 끝낼 거야.',
    trans: L(
      "Even if I have to pull an all-nighter, I'm going to finish all of this by tomorrow.",
      'Aunque tenga que pasar la noche en vela, voy a terminar todo esto para mañana.',
      "Même si je dois passer une nuit blanche, je vais finir tout ça d'ici demain.",
      'Mesmo que eu tenha que virar a noite, vou terminar tudo isso até amanhã.',
      'ถึงแม้จะต้องอดนอนทั้งคืน พรุ่งนี้ฉันก็จะทำอันนี้ให้เสร็จหมด',
      'Bahkan kalau harus begadang semalaman, aku akan menyelesaikan semua ini sampai besok.',
      'Dù có phải thức trắng đêm, đến mai tớ cũng sẽ làm xong hết cái này.',
      '徹夜することになっても、明日までにこれ全部終わらせるよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-답시고',
    sentence: '다이어트한답시고 점심을 굶더니 저녁에 폭식했어요.',
    trans: L(
      'She skipped lunch on the excuse of dieting, then binge-ate at dinner.',
      'Bajo el pretexto de hacer dieta se saltó el almuerzo y luego se atracó en la cena.',
      "Sous prétexte de faire un régime, elle a sauté le déjeuner, puis s'est goinfrée au dîner.",
      'Com a desculpa de estar de dieta, pulou o almoço e depois se empanturrou no jantar.',
      'อ้างว่ากำลังลดน้ำหนักเลยอดมื้อกลางวัน แล้วตกเย็นก็กินมูมมามเสียอย่างนั้น',
      'Dengan dalih sedang diet dia melewatkan makan siang, lalu malah makan kalap saat makan malam.',
      'Lấy cớ đang ăn kiêng nên bỏ bữa trưa, rồi tối lại ăn lấy ăn để.',
      'ダイエットするとか言って昼食を抜いたのに、夜にどか食いしました。',
    ),
    level: 'polite',
  },
  {
    ko: '-답시고',
    sentence: '어른이랍시고 큰소리만 치고 책임은 안 지더라.',
    trans: L(
      "Acting all high and mighty just because he's an adult, he only talks big and never takes responsibility.",
      'Presumiendo de ser un adulto, solo habla a lo grande pero nunca asume responsabilidades.',
      "Sous prétexte d'être un adulte, il ne fait que jouer les gros bras et n'assume jamais ses responsabilités.",
      'Achando-se superior só por ser adulto, só fala grosso e nunca assume responsabilidade.',
      'อ้างว่าเป็นผู้ใหญ่ก็เอาแต่พูดเสียงดัง แต่ไม่เคยรับผิดชอบอะไรเลย',
      'Mentang-mentang merasa sudah dewasa, dia cuma besar mulut tapi tak pernah bertanggung jawab.',
      'Lấy cớ là người lớn nên chỉ to mồm thôi chứ chẳng chịu trách nhiệm gì cả.',
      '大人だからと言って大きな口ばかり叩いて、責任は取らないんだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는다거나',
    sentence: '심심하면 게임을 한다거나 유튜브를 본다거나 하면서 시간을 보내.',
    trans: L(
      "When I'm bored, I pass the time doing things like playing games or watching YouTube.",
      'Cuando me aburro, paso el rato haciendo cosas como jugar videojuegos o ver YouTube.',
      "Quand je m'ennuie, je passe le temps à faire des choses comme jouer ou regarder YouTube.",
      'Quando fico entediado, passo o tempo fazendo coisas como jogar ou ver YouTube.',
      'พอเบื่อ ก็ฆ่าเวลาด้วยการเล่นเกมบ้าง ดู YouTube บ้าง',
      'Kalau bosan, aku habiskan waktu dengan main game atau nonton YouTube.',
      'Lúc buồn chán thì mình giết thời gian bằng cách chơi game hay xem YouTube.',
      '退屈なときは、ゲームをするとかユーチューブを見るとかして時間をつぶすよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는다거나',
    sentence: '스트레스를 받으면 매운 걸 먹는다거나 노래방에 간다거나 해요.',
    trans: L(
      "When I'm stressed, I do things like eat something spicy or go to a karaoke room.",
      'Cuando tengo estrés, hago cosas como comer algo picante o ir al karaoke.',
      'Quand je suis stressée, je fais des choses comme manger épicé ou aller au karaoké.',
      'Quando estou estressada, faço coisas como comer algo picante ou ir ao karaokê.',
      'เวลาเครียด ฉันก็จะกินของเผ็ดบ้าง ไปร้องคาราโอเกะบ้าง',
      'Kalau lagi stres, saya biasanya makan yang pedas atau pergi ke karaoke.',
      'Khi bị căng thẳng thì tôi hay ăn đồ cay hoặc đi hát karaoke.',
      'ストレスがたまると、辛い物を食べるとかカラオケに行くとかします。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)며',
    sentence: '그는 음악을 들으며 천천히 공원을 걸었다.',
    trans: L(
      'He walked slowly through the park while listening to music.',
      'Caminó despacio por el parque mientras escuchaba música.',
      'Il marchait lentement dans le parc tout en écoutant de la musique.',
      'Ele caminhou devagar pelo parque enquanto ouvia música.',
      'เขาเดินช้า ๆ ในสวนสาธารณะไปพลางฟังเพลงไปพลาง',
      'Dia berjalan pelan-pelan di taman sambil mendengarkan musik.',
      'Anh ấy vừa nghe nhạc vừa đi bộ chậm rãi trong công viên.',
      '彼は音楽を聞きながらゆっくりと公園を歩いた。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)며',
    sentence: '저는 보통 아침을 먹으며 뉴스를 봐요.',
    trans: L(
      'I usually watch the news while eating breakfast.',
      'Normalmente veo las noticias mientras desayuno.',
      "D'habitude, je regarde les infos en prenant mon petit-déjeuner.",
      'Geralmente assisto ao noticiário enquanto tomo café da manhã.',
      'ปกติฉันดูข่าวไปพลางกินข้าวเช้าไปพลาง',
      'Saya biasanya menonton berita sambil sarapan.',
      'Tôi thường vừa ăn sáng vừa xem tin tức.',
      '私はたいてい朝ごはんを食べながらニュースを見ます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)며 -(으)며',
    sentence: '할머니는 콩나물을 다듬으며 노래를 흥얼거리며 옛날이야기를 들려주셨다.',
    trans: L(
      'While trimming the bean sprouts and humming a tune, Grandmother told us old stories.',
      'Mientras limpiaba los brotes de soja y tarareaba una canción, la abuela nos contaba historias de antaño.',
      "Tout en nettoyant les pousses de soja et en fredonnant un air, grand-mère nous racontait des histoires d'autrefois.",
      'Enquanto limpava os brotos de feijão e cantarolava uma melodia, a vovó nos contava histórias de antigamente.',
      'คุณยายเด็ดถั่วงอกไปพลางฮัมเพลงไปพลาง พลางเล่าเรื่องเก่าๆ ให้เราฟัง',
      'Sambil membersihkan tauge dan menyenandungkan lagu, nenek menceritakan kisah-kisah zaman dulu kepada kami.',
      'Bà vừa nhặt giá đỗ vừa ngân nga một giai điệu, kể cho chúng tôi nghe những câu chuyện ngày xưa.',
      'おばあちゃんは豆もやしを下処理しながら鼻歌を歌いながら、昔話を聞かせてくれた。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)며 -(으)며',
    sentence: '그 카페는 분위기도 좋으며 커피도 맛있으며 가격까지 저렴해서 자주 가요.',
    trans: L(
      'That café has a nice atmosphere, the coffee tastes good, and the prices are even cheap, so I go there often.',
      'Ese café tiene buen ambiente, el café está rico y encima los precios son baratos, así que voy a menudo.',
      "Ce café a une bonne ambiance, le café y est délicieux et les prix sont même bon marché, alors j'y vais souvent.",
      'Aquele café tem um ambiente agradável, o café é gostoso e ainda por cima os preços são baratos, por isso vou com frequência.',
      'คาเฟ่นั้นบรรยากาศก็ดี กาแฟก็อร่อย แถมราคายังถูกอีก เลยไปบ่อยค่ะ',
      'Kafe itu suasananya enak, kopinya juga enak, dan harganya pun murah, jadi saya sering ke sana.',
      'Quán cà phê đó không khí dễ chịu, cà phê ngon, giá lại còn rẻ nữa nên tôi hay đến lắm.',
      'あのカフェは雰囲気も良くて、コーヒーもおいしくて、値段まで安いので、よく行きます。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)나',
    sentence: '이 식당은 값은 비싸나 맛은 정말 좋습니다.',
    trans: L(
      'This restaurant is expensive, but the food is really good.',
      'Este restaurante es caro, pero la comida es realmente buena.',
      'Ce restaurant est cher, mais la nourriture est vraiment bonne.',
      'Este restaurante é caro, mas a comida é realmente boa.',
      'ร้านอาหารนี้แพงก็จริง แต่อาหารอร่อยมากจริงๆ',
      'Restoran ini mahal, tetapi makanannya benar-benar enak.',
      'Nhà hàng này đắt, nhưng món ăn thì thật sự ngon.',
      'このレストランは値段は高いですが、味は本当においしいです。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)나',
    sentence: '동생에게 여러 번 전화했으나 한 번도 받지 않았다.',
    trans: L(
      'I called my younger sibling several times, but they never picked up once.',
      'Llamé a mi hermano menor varias veces, pero no contestó ni una sola vez.',
      "J'ai appelé mon cadet plusieurs fois, mais il n'a pas répondu une seule fois.",
      'Liguei para o meu irmão mais novo várias vezes, mas ele não atendeu nenhuma vez.',
      'ฉันโทรหาน้องหลายครั้ง แต่เขาไม่รับสักครั้งเลย',
      'Aku menelepon adikku beberapa kali, tetapi dia tidak mengangkat sama sekali.',
      'Tôi đã gọi cho em mình mấy lần, nhưng nó không bắt máy lần nào cả.',
      '弟に何度も電話したが、一度も出なかった。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)려고 들다',
    sentence: '동생은 뭐든지 혼자 하려고 들어서 가끔 위험해요.',
    trans: L(
      "My younger sibling is bent on doing everything alone, so it's sometimes dangerous.",
      'Mi hermano menor se empeña en hacerlo todo solo, así que a veces es peligroso.',
      "Mon petit frère s'obstine à tout faire tout seul, alors c'est parfois dangereux.",
      'Meu irmão mais novo faz questão de fazer tudo sozinho, então às vezes é perigoso.',
      'น้องของฉันจะเอาแต่ทำทุกอย่างคนเดียว เลยบางครั้งก็อันตราย',
      'Adikku selalu ngotot mengerjakan semuanya sendiri, jadi kadang berbahaya.',
      'Em tôi cứ nằng nặc đòi tự làm mọi thứ một mình nên đôi khi rất nguy hiểm.',
      '弟は何でも一人でやろうとするので、時々危ないんです。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)려고 들다',
    sentence: '그 사람은 내 말을 끝까지 안 듣고 자기 생각만 밀어붙이려고 든다.',
    trans: L(
      "That person won't hear me out and just insists on pushing his own ideas through.",
      'Esa persona no me escucha hasta el final y se empeña en imponer solo sus propias ideas.',
      "Cette personne ne m'écoute pas jusqu'au bout et s'acharne à imposer ses propres idées.",
      'Essa pessoa não me escuta até o fim e teima em impor só as próprias ideias.',
      'คนคนนั้นไม่ฟังฉันให้จบ เอาแต่จะดันความคิดของตัวเองอย่างเดียว',
      'Orang itu tidak mau mendengarkanku sampai habis dan malah ngotot memaksakan idenya sendiri.',
      'Người đó không chịu nghe tôi nói hết mà cứ khăng khăng áp đặt ý của mình.',
      'あの人は私の話を最後まで聞かずに、自分の考えだけを押し通そうとする。',
    ),
    level: 'casual',
  },
  {
    ko: '-기 십상이다',
    sentence: '초보자는 그런 실수를 하기 십상이에요.',
    trans: L(
      'Beginners are apt to make that kind of mistake.',
      'Los principiantes suelen cometer ese tipo de errores.',
      "Les débutants ont tendance à faire ce genre d'erreur.",
      'Iniciantes costumam cometer esse tipo de erro.',
      'มือใหม่มักจะทำผิดพลาดแบบนั้นได้ง่าย ๆ',
      'Pemula cenderung mudah melakukan kesalahan seperti itu.',
      'Người mới thường rất dễ mắc phải lỗi như thế.',
      '初心者はそういう間違いをしがちです。',
    ),
    level: 'polite',
  },
  {
    ko: '-기 십상이다',
    sentence: '급하게 결정하면 나중에 후회하기 십상이야.',
    trans: L(
      "If you decide in a rush, you're bound to regret it later.",
      'Si decides con prisa, es muy fácil que luego te arrepientas.',
      'Si tu décides à la hâte, tu as vite fait de le regretter plus tard.',
      'Se você decide às pressas, é fácil acabar se arrependendo depois.',
      'ถ้าตัดสินใจรีบ ๆ มีโอกาสสูงที่จะมาเสียใจทีหลัง',
      'Kalau memutuskan dengan terburu-buru, mudah saja menyesal nanti.',
      'Quyết định vội vàng thì dễ hối hận về sau lắm.',
      '急いで決めると、後で後悔しがちだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 셈 치다',
    sentence: '오늘은 운동도 못 했으니까 엘리베이터 안 탄 셈 치고 계단으로 걸어 올라가요.',
    trans: L(
      "I didn't get to work out today, so let's pretend there's no elevator and take the stairs.",
      'Hoy no pude hacer ejercicio, así que hagamos como si no hubiera ascensor y subamos por las escaleras.',
      "Je n'ai pas pu faire de sport aujourd'hui, alors faisons comme s'il n'y avait pas d'ascenseur et montons par l'escalier.",
      'Hoje não consegui me exercitar, então vamos fazer de conta que não há elevador e subir pela escada.',
      'วันนี้ไม่ได้ออกกำลังกายเลย ถือซะว่าไม่มีลิฟต์แล้วเดินขึ้นบันไดกันเถอะ',
      'Hari ini aku tidak sempat olahraga, jadi anggap saja tidak ada lift dan kita naik tangga.',
      'Hôm nay tôi chưa tập thể dục, nên cứ coi như không có thang máy và đi thang bộ đi.',
      '今日は運動できなかったから、エレベーターがないことにして階段で上がりましょう。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 셈 치다',
    sentence: '그 돈은 친구한테 빌려준 게 아니라 그냥 밥 한 끼 산 셈 치기로 했어.',
    trans: L(
      "I decided to treat that money not as a loan to my friend, but just as if I'd treated him to a meal.",
      'Decidí no considerar ese dinero como un préstamo a mi amigo, sino como si simplemente le hubiera invitado a comer.',
      "J'ai décidé de ne pas considérer cet argent comme un prêt à mon ami, mais simplement comme si je lui avais offert un repas.",
      'Decidi não considerar aquele dinheiro como um empréstimo ao meu amigo, mas como se eu simplesmente tivesse pago uma refeição pra ele.',
      'เงินก้อนนั้นฉันตัดสินใจว่าจะไม่ถือว่าเป็นการให้เพื่อนยืม แต่ถือว่าเลี้ยงข้าวเพื่อนไปมื้อหนึ่งซะเลย',
      'Uang itu kuputuskan untuk tidak dianggap sebagai pinjaman ke temanku, tapi anggap saja aku mentraktirnya makan.',
      'Số tiền đó mình quyết định không coi là cho bạn vay, mà cứ coi như mình đã mời nó một bữa cơm.',
      'あのお金は友達に貸したんじゃなくて、ただ一食おごったことにすることにしたよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ락 말락 하다',
    sentence: '슬픈 영화를 보다가 눈물이 날락 말락 했어요.',
    trans: L(
      'While watching the sad movie, the tears were almost coming but not quite falling.',
      'Viendo la película triste, las lágrimas estaban a punto de salir pero no llegaban a caer.',
      'En regardant le film triste, les larmes étaient sur le point de couler sans tout à fait tomber.',
      'Assistindo ao filme triste, as lágrimas estavam quase saindo, mas não chegavam a cair.',
      'ตอนดูหนังเศร้า น้ำตาจะไหลก็ไม่ไหล เกือบจะร่วงแต่ก็ไม่',
      'Saat menonton film sedih, air mata hampir keluar tetapi tidak sampai jatuh.',
      'Khi xem bộ phim buồn, nước mắt cứ chực trào mà không hẳn rơi.',
      '悲しい映画を見ていたら、涙が出そうで出ないという感じでした。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄹ락 말락 하다',
    sentence: '안개 때문에 산 정상이 보일락 말락 해.',
    trans: L(
      'Because of the fog, the mountain peak keeps barely showing and then vanishing.',
      'Por la niebla, la cima de la montaña se ve y no se ve.',
      'À cause du brouillard, le sommet de la montagne apparaît et disparaît à peine.',
      'Por causa do nevoeiro, o cume da montanha mal aparece e some.',
      'เพราะหมอก ยอดเขาเลยเห็นบ้างไม่เห็นบ้าง เดี๋ยวโผล่เดี๋ยวหาย',
      'Karena kabut, puncak gunung itu samar-samar kelihatan lalu hilang.',
      'Vì sương mù, đỉnh núi cứ thấp thoáng ẩn hiện.',
      '霧のせいで山の頂上が見えるか見えないかという感じだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 둥 마는 둥',
    sentence: '어제 너무 피곤해서 청소를 하는 둥 마는 둥 하고 그냥 잤어요.',
    trans: L(
      'Yesterday I was so tired that I cleaned only half-heartedly and just went to sleep.',
      'Ayer estaba tan cansado que limpié a medias y me fui a dormir sin más.',
      "Hier, j'étais si fatigué que j'ai fait le ménage à moitié et je suis simplement allé dormir.",
      'Ontem eu estava tão cansado que limpei pela metade e simplesmente fui dormir.',
      'เมื่อวานเหนื่อยมากเลยทำความสะอาดแบบลวก ๆ แล้วก็เข้านอนเลย',
      'Kemarin aku capek sekali jadi membersihkan asal-asalan lalu langsung tidur.',
      'Hôm qua tôi mệt quá nên dọn dẹp qua loa cho có rồi đi ngủ luôn.',
      '昨日はとても疲れていたので、掃除をするのかしないのか適当に済ませてそのまま寝ました。',
    ),
    level: 'polite',
  },
  {
    ko: '-는 둥 마는 둥',
    sentence: '동생은 시험이 코앞인데 공부를 하는 둥 마는 둥 하더니 결국 떨어졌어.',
    trans: L(
      'My little brother barely bothered to study even with the exam right around the corner, and in the end he failed.',
      'Mi hermano menor apenas estudió aunque tenía el examen encima, y al final reprobó.',
      "Mon petit frère a à peine étudié alors que l'examen était imminent, et finalement il a échoué.",
      'Meu irmão mais novo mal estudou mesmo com a prova chegando, e no fim acabou sendo reprovado.',
      'น้องชายฉันใกล้สอบแล้วแต่อ่านหนังสือแบบขอไปที สุดท้ายก็สอบตก',
      'Adikku ujiannya sudah di depan mata tapi belajarnya setengah hati, akhirnya tidak lulus.',
      'Em trai tôi sắp thi đến nơi mà học hành qua loa cho xong, cuối cùng thi trượt.',
      '弟は試験が目前なのに勉強をするのかしないのか中途半端にやって、結局落ちた。',
    ),
    level: 'casual',
  },
  {
    ko: '-느냐에 따라(서)',
    sentence: '평소에 어떻게 관리하느냐에 따라서 결과가 완전히 달라질 수 있습니다.',
    trans: L(
      'Depending on how you maintain it day to day, the results can be completely different.',
      'Según cómo se cuide en el día a día, los resultados pueden ser completamente distintos.',
      "Selon la manière dont on l'entretient au quotidien, les résultats peuvent être complètement différents.",
      'Dependendo de como se cuida no dia a dia, os resultados podem ser completamente diferentes.',
      'ผลลัพธ์อาจแตกต่างกันโดยสิ้นเชิง ขึ้นอยู่กับว่าปกติดูแลรักษาอย่างไร',
      'Tergantung bagaimana cara merawatnya sehari-hari, hasilnya bisa sangat berbeda.',
      'Tùy vào việc bạn chăm sóc nó hằng ngày thế nào mà kết quả có thể khác hẳn.',
      '普段どのように管理するかによって、結果は全く変わり得ます。',
    ),
    level: 'formal',
  },
  {
    ko: '-느냐에 따라(서)',
    sentence: '네가 어떤 친구를 사귀느냐에 따라 성격도 달라진다.',
    trans: L(
      'Depending on what kind of friends you make, your personality changes too.',
      'Según qué clase de amigos hagas, tu carácter también cambia.',
      "Selon le genre d'amis que tu te fais, ton caractère change aussi.",
      'Dependendo do tipo de amigos que você faz, sua personalidade também muda.',
      'ขึ้นอยู่กับว่าเธอคบเพื่อนแบบไหน นิสัยก็เปลี่ยนไปด้วย',
      'Tergantung teman seperti apa yang kamu jalin, kepribadianmu juga berubah.',
      'Tùy vào việc bạn kết bạn với kiểu người nào, tính cách của bạn cũng thay đổi.',
      '君がどんな友達と付き合うかによって、性格も変わるんだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 가운데',
    sentence: '경기가 침체된 가운데 정부가 새로운 대책을 발표했습니다.',
    trans: L(
      'Amid the economic downturn, the government announced new measures.',
      'En medio de la recesión económica, el gobierno anunció nuevas medidas.',
      'Dans un contexte de récession économique, le gouvernement a annoncé de nouvelles mesures.',
      'Em meio à recessão econômica, o governo anunciou novas medidas.',
      'ท่ามกลางภาวะเศรษฐกิจซบเซา รัฐบาลได้ประกาศมาตรการใหม่',
      'Di tengah kelesuan ekonomi, pemerintah mengumumkan langkah-langkah baru.',
      'Trong bối cảnh kinh tế suy thoái, chính phủ đã công bố các biện pháp mới.',
      '景気が低迷する中、政府が新たな対策を発表しました。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는 가운데',
    sentence: '여러 가지로 어수선한 가운데 이렇게 자리를 빛내 주셔서 진심으로 감사합니다.',
    trans: L(
      'Amid all this turmoil, I sincerely thank you for honoring us with your presence.',
      'En medio de tanta agitación, les agradezco sinceramente por honrarnos con su presencia.',
      "Au milieu de toute cette agitation, je vous remercie sincèrement d'honorer cet événement de votre présence.",
      'Em meio a toda essa turbulência, agradeço sinceramente por honrarem este evento com a sua presença.',
      'ท่ามกลางความวุ่นวายหลายอย่าง ขอขอบพระคุณอย่างจริงใจที่ท่านมาร่วมงานในวันนี้',
      'Di tengah berbagai kesibukan, saya dengan tulus berterima kasih atas kehadiran Anda yang memuliakan acara ini.',
      'Giữa lúc bộn bề thế này, tôi chân thành cảm ơn quý vị đã đến chung vui.',
      '何かと慌ただしい中、このようにお越しいただき、心より感謝申し上げます。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)랴 -(으)랴',
    sentence: '아이 키우랴 회사 다니랴 하루가 어떻게 가는지 모르겠어요.',
    trans: L(
      "What with raising the kids and going to work, I don't even know where the days go.",
      'Entre criar a los niños y ir al trabajo, ni sé cómo se me pasan los días.',
      'Entre élever les enfants et aller au travail, je ne sais même pas comment mes journées passent.',
      'Entre criar os filhos e ir trabalhar, nem sei como os dias passam.',
      'ทั้งเลี้ยงลูกทั้งไปทำงาน ไม่รู้เลยว่าแต่ละวันผ่านไปยังไง',
      'Antara mengurus anak dan pergi bekerja, sampai tidak sadar hari berlalu.',
      'Vừa nuôi con vừa đi làm, tôi chẳng biết ngày trôi qua thế nào nữa.',
      '子育てするやら会社に通うやらで、一日がどう過ぎるのか分かりません。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)랴 -(으)랴',
    sentence: '어제는 청소하랴 손님 맞으랴 정신이 하나도 없었어.',
    trans: L(
      'Yesterday, what with cleaning and welcoming the guests, I was completely frazzled.',
      'Ayer, entre limpiar y recibir a los invitados, no me quedaba ni un respiro.',
      "Hier, entre faire le ménage et accueillir les invités, j'étais complètement débordé.",
      'Ontem, entre limpar e receber os convidados, fiquei completamente sem cabeça.',
      'เมื่อวานทั้งทำความสะอาดทั้งต้อนรับแขก วุ่นวายจนหัวจะระเบิด',
      'Kemarin, antara bersih-bersih dan menyambut tamu, aku sampai kalang kabut.',
      'Hôm qua vừa dọn dẹp vừa tiếp khách, tôi rối hết cả lên.',
      '昨日は掃除するやらお客さんを迎えるやらで、てんてこ舞いだったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ다는 게',
    sentence: '소금을 넣는다는 게 설탕을 넣어 버렸어요.',
    trans: L(
      'I meant to add salt, but I ended up putting in sugar.',
      'Quería echar sal, pero terminé poniendo azúcar.',
      "Je voulais mettre du sel, mais j'ai fini par mettre du sucre.",
      'Eu queria pôr sal, mas acabei colocando açúcar.',
      'ตั้งใจจะใส่เกลือ แต่ดันใส่น้ำตาลซะงั้น',
      'Maksudnya mau menambahkan garam, tapi malah memasukkan gula.',
      'Định cho muối vào mà lại lỡ cho đường vào mất.',
      '塩を入れるつもりが、砂糖を入れてしまいました。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ다는 게',
    sentence: '친구한테 문자를 보낸다는 게 엄마한테 보냈어.',
    trans: L(
      'I meant to text my friend, but I sent it to my mom.',
      'Quería mandarle el mensaje a mi amigo, pero se lo envié a mi mamá.',
      "Je voulais envoyer le message à mon ami, mais je l'ai envoyé à ma mère.",
      'Eu queria mandar a mensagem para o meu amigo, mas mandei para a minha mãe.',
      'ตั้งใจจะส่งข้อความหาเพื่อน แต่ดันส่งหาแม่ซะได้',
      'Niatnya mau mengirim pesan ke teman, tapi malah terkirim ke ibu.',
      'Định nhắn tin cho bạn mà lại gửi nhầm cho mẹ.',
      '友達にメッセージを送るつもりが、お母さんに送っちゃった。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ 따름입니다',
    sentence: '저는 그저 제가 맡은 일을 했을 따름입니다.',
    trans: L(
      'I merely did the job that was given to me.',
      'Solo hice el trabajo que me encomendaron, nada más.',
      "Je n'ai fait que le travail qui m'avait été confié.",
      'Eu apenas fiz o trabalho que me foi confiado.',
      'ผมเพียงแค่ทำงานที่ได้รับมอบหมายเท่านั้นครับ',
      'Saya hanya melakukan pekerjaan yang dipercayakan kepada saya.',
      'Tôi chỉ làm công việc được giao mà thôi.',
      '私はただ与えられた仕事をしたまでです。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ 따름입니다',
    sentence: '최선을 다했지만 결과가 이렇게 되어 안타까울 따름입니다.',
    trans: L(
      'I did my best, but the result turned out this way; I can only feel regret.',
      'Di lo mejor de mí, pero el resultado fue este; no me queda más que lamentarlo.',
      "J'ai fait de mon mieux, mais le résultat est tel, et je ne peux qu'en être désolé.",
      'Dei o meu melhor, mas o resultado foi este; só me resta lamentar.',
      'ผมทำเต็มที่แล้ว แต่ผลออกมาเป็นแบบนี้ ได้แต่รู้สึกเสียดายเท่านั้น',
      'Saya sudah berusaha sebaik mungkin, tapi hasilnya jadi begini; saya hanya bisa merasa menyesal.',
      'Tôi đã cố hết sức, nhưng kết quả lại thế này, tôi chỉ biết tiếc nuối mà thôi.',
      '最善を尽くしましたが、結果がこうなってしまい、ただ残念でなりません。',
    ),
    level: 'formal',
  },
]
