import type { GrammarExample } from '~/lib/domain'
import { L } from '../locale'

/**
 * TOPIK-6 grammar examples (plan Part B Tier-1, level 6). Per-FORM coverage for
 * the multi-form, literary/archaic TOPIK-6 grammars: each grammar whose `ko`
 * names ≥2 distinct surface forms shows ≥1 example per form. `ko` values match
 * grammars-n6.ts verbatim; sentences differ from each grammar's canonical
 * `Grammar.example`.
 *
 * Drafted + Korean-lens (literary) adversarially verified by a multi-agent
 * workflow. Native (Korean wife) review is the documented final gate — these
 * elevated/archaic endings especially warrant it.
 */
export const TOPIK_6_EXAMPLES: GrammarExample[] = [
  {
    ko: '-(으)련마는 / -(으)련만',
    sentence: '비가 흠뻑 내리면 메마른 논밭에 더없이 좋으련마는 하늘은 야속하게도 구름 한 점 내주지 않는구나.',
    trans: L(
      'If rain were to pour down it would surely be a blessing for the parched fields — yet the heavens, so unkind, will not yield even a single cloud.',
      'Si la lluvia cayera a cántaros sería sin duda una bendición para los campos resecos — mas el cielo, tan cruel, no concede ni una sola nube.',
      'Si la pluie tombait à verse, ce serait à coup sûr une bénédiction pour les champs desséchés — mais le ciel, si impitoyable, ne consent pas même un seul nuage.',
      'Se a chuva caísse em abundância seria sem dúvida uma bênção para os campos ressecados — mas o céu, tão cruel, não concede nem uma única nuvem.',
      'หากฝนหลั่งลงมาชุ่มฉ่ำ ย่อมเป็นพรอันประเสริฐแก่ไร่นาที่แห้งผาก แต่ฟากฟ้าช่างไร้เมตตา ไม่ยอมประทานแม้เพียงเมฆสักก้อน',
      'Andai hujan mencurah deras, sungguh itu akan menjadi berkah bagi ladang yang kering kerontang — namun langit, betapa kejamnya, tak sudi memberi seujung awan pun.',
      'Nếu mưa trút xuống dầm dề thì hẳn sẽ là phúc lành cho ruộng đồng khô cằn — nhưng trời cao, sao mà tàn nhẫn, chẳng chịu ban cho lấy một áng mây.',
      '雨がたっぷり降れば干からびた田畑にこの上なく良かろうものを、空はつれなくも一片の雲さえ恵んではくれぬのだ。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)련마는 / -(으)련만',
    sentence: '벗이 곁에 있다면 이 먼 길도 함께 가련만 홀로 떠나는 나그네의 발걸음이 한없이 무겁기만 하구나.',
    trans: L(
      'Were a friend at my side I would surely walk even this long road together — yet the steps of this wayfarer setting off alone weigh on me without end.',
      'Si un amigo estuviera a mi lado, recorrería sin duda junto a él incluso este largo camino, mas los pasos de este caminante que parte solo me pesan sin fin.',
      'Si un ami était à mes côtés, je parcourrais sûrement avec lui même cette longue route — mais les pas de ce voyageur qui s’en va seul me pèsent sans fin.',
      'Se um amigo estivesse a meu lado eu sem dúvida percorreria junto até esta longa estrada — mas os passos deste viajante que parte sozinho me pesam sem fim.',
      'หากมีสหายเคียงข้าง ถนนอันไกลโพ้นนี้ข้าก็คงร่วมเดินไปด้วยกัน แต่ย่างก้าวของผู้จรที่ออกเดินทางเพียงลำพังนี้กลับหนักอึ้งไม่รู้สิ้น',
      'Andai ada sahabat di sisiku, jalan sejauh ini pun tentu kutempuh bersama — namun langkah pengembara yang berangkat seorang diri ini terasa berat tiada habisnya.',
      'Nếu có bạn hữu bên cạnh thì con đường xa xôi này hẳn ta cũng cùng nhau cất bước — nhưng bước chân của kẻ lữ hành ra đi đơn độc này nặng trĩu khôn cùng.',
      '友が傍らにあれば、この遠い道もともに行こうものを、独り旅立つ旅人の足取りはどこまでも重いばかりだ。',
    ),
    level: 'formal',
  },
  {
    ko: '-건대 / 생각건대 / 바라건대',
    sentence: '듣건대, 그 고을의 백성들이 오랜 가뭄으로 큰 고초를 겪고 있다 하더이다.',
    trans: L(
      'As I hear it, the people of that district are said to be suffering greatly from a long drought.',
      'Según tengo entendido, dicen que los habitantes de aquella comarca padecen grandes penurias por una prolongada sequía.',
      "À ce que l'on entend dire, les habitants de cette contrée souffriraient grandement d'une longue sécheresse.",
      'Pelo que ouço dizer, conta-se que o povo daquela região padece imensamente por causa de uma longa seca.',
      'เท่าที่ได้ยินมา ว่ากันว่าราษฎรแห่งเมืองนั้นกำลังทุกข์ยากแสนสาหัสจากภัยแล้งอันยาวนาน',
      'Sebagaimana yang kudengar, konon rakyat di daerah itu tengah menderita hebat akibat kemarau panjang.',
      'Ta nghe nói dân chúng vùng ấy đang phải chịu cảnh khốn khổ vô cùng vì hạn hán kéo dài.',
      '聞くところによれば、その地の民は長き旱魃のために甚だしき苦しみを受けているとのことである。',
    ),
    level: 'formal',
  },
  {
    ko: '-건대 / 생각건대 / 바라건대',
    sentence: '생각건대, 나라의 흥망은 결국 백성의 마음을 얻느냐 잃느냐에 달려 있는 것이다.',
    trans: L(
      'On reflection, the rise and fall of a nation ultimately rests on whether one wins or loses the hearts of the people.',
      'Bien pensado, el auge y la caída de una nación dependen, al fin, de si se gana o se pierde el corazón del pueblo.',
      "Toute réflexion faite, la grandeur et la décadence d'une nation tiennent, en définitive, à ce que l'on gagne ou perde le cœur du peuple.",
      'Refletindo bem, a ascensão e a queda de uma nação dependem, no fim, de se conquistar ou perder o coração do povo.',
      'เมื่อพิเคราะห์ดูแล้ว ความรุ่งเรืองและล่มสลายของชาติบ้านเมืองนั้น สุดท้ายย่อมขึ้นอยู่กับว่าจะได้หรือเสียซึ่งใจของราษฎร',
      'Setelah kurenungkan, jaya dan runtuhnya suatu bangsa pada akhirnya bergantung pada apakah hati rakyat diraih atau hilang.',
      'Ngẫm cho kỹ, sự hưng vong của một nước rốt cuộc tùy thuộc ở chỗ được hay mất lòng dân.',
      '思うに、国の興亡は結局のところ、民の心を得るか失うかにかかっているのである。',
    ),
    level: 'formal',
  },
  {
    ko: '-건대 / 생각건대 / 바라건대',
    sentence: '바라건대, 이 땅에 다시는 그와 같은 비극이 되풀이되지 않기를.',
    trans: L(
      'Would that such a tragedy never be repeated upon this land again.',
      'Ojalá que nunca jamás se repita en esta tierra una tragedia semejante.',
      'Puisse une telle tragédie ne plus jamais se répéter sur cette terre.',
      'Oxalá tamanha tragédia jamais se repita outra vez sobre esta terra.',
      'ขอจงอย่าให้โศกนาฏกรรมเช่นนั้นหวนกลับมาเกิดซ้ำบนผืนแผ่นดินนี้อีกเลย',
      'Semoga tragedi seperti itu tak pernah lagi terulang di atas tanah ini.',
      'Mong sao thảm kịch như thế chẳng bao giờ còn tái diễn trên mảnh đất này nữa.',
      '願わくは、この地に二度と再びそのような悲劇が繰り返されることのなきように。',
    ),
    level: 'formal',
  },
  {
    ko: '-로다 / -(이)로다',
    sentence: '아, 이 강산이 천하의 절경이로구나… 참으로 빼어난 경치로다.',
    trans: L(
      'Ah, this land is the finest sight under heaven... truly, what splendid scenery it is!',
      'Ah, esta tierra es el paisaje más bello bajo el cielo... ¡en verdad, qué espléndido paisaje es!',
      'Ah, cette terre est le plus beau site sous le ciel... en vérité, quel paysage splendide !',
      'Ah, esta terra é a vista mais bela sob o céu... em verdade, que paisagem esplêndida!',
      'อา ดินแดนนี้คือทัศนียภาพงดงามที่สุดใต้หล้า... ช่างเป็นภูมิทัศน์อันวิจิตรเหลือเกินหนอ',
      'Ah, negeri ini adalah pemandangan terindah di kolong langit... sungguh, alangkah indahnya panorama ini!',
      'Ôi, dải non sông này là tuyệt cảnh đệ nhất thiên hạ... thật là một cảnh sắc tuyệt diệu thay!',
      'ああ、この山河は天下随一の絶景… まことに見事な景色であることよ。',
    ),
    level: 'formal',
  },
  {
    ko: '-로다 / -(이)로다',
    sentence: '오랜 세월을 견뎌 온 이 한 그루 소나무야말로 이 산의 주인이로다.',
    trans: L(
      'This lone pine, having endured the long ages, is the very master of this mountain!',
      '¡Este solitario pino, que ha resistido las largas eras, es el verdadero señor de esta montaña!',
      'Ce pin solitaire, qui a enduré les longs âges, est bien le maître de cette montagne !',
      'Este pinheiro solitário, que resistiu às longas eras, é o próprio senhor desta montanha!',
      'ต้นสนโดดเดี่ยวต้นนี้ ที่ทนผ่านกาลเวลาอันยาวนานมา คือเจ้าแห่งขุนเขาลูกนี้เองหนอ',
      'Pohon pinus tunggal ini, yang telah bertahan melintasi zaman yang panjang, sungguh tuan dari gunung ini!',
      'Cây tùng đơn độc này, đã chịu đựng qua bao năm tháng dài, chính là chủ nhân của ngọn núi này vậy!',
      '長き歳月を耐え抜いてきたこの一本の松こそ、この山の主であることよ。',
    ),
    level: 'formal',
  },
  {
    ko: '-ㄴ들',
    sentence: '아무리 비싼 옷을 입은들 마음이 고약하면 무슨 소용이에요?',
    trans: L(
      'No matter how expensive the clothes you wear, what good is it if your heart is cruel?',
      'Por muy caras que sean las ropas que lleves, ¿de qué sirve si tienes mal corazón?',
      'Même si tu portes les vêtements les plus chers, à quoi bon si ton cœur est mauvais ?',
      'Por mais caras que sejam as roupas que você vista, de que adianta se o seu coração é ruim?',
      'ต่อให้ใส่เสื้อผ้าแพงแค่ไหน ถ้าจิตใจไม่ดีแล้วจะมีประโยชน์อะไร',
      'Sebagus apa pun mahalnya pakaian yang kamu kenakan, apa gunanya kalau hatimu jahat?',
      'Dù có mặc quần áo đắt tiền đến đâu thì có ích gì nếu tâm địa xấu xa?',
      'どんなに高い服を着たところで、心が醜ければ何の意味があるんですか。',
    ),
    level: 'polite',
  },
  {
    ko: '-ㄴ들',
    sentence: '천하를 다 가진들 사랑하는 사람이 없다면 그게 다 무슨 의미가 있겠습니까?',
    trans: L(
      'Even if one possessed the whole world, what meaning would any of it have without someone to love?',
      'Aunque se poseyera el mundo entero, ¿qué sentido tendría todo eso sin alguien a quien amar?',
      "Même si l'on possédait le monde entier, quel sens tout cela aurait-il sans personne à aimer ?",
      'Mesmo que se possuísse o mundo inteiro, que sentido teria tudo isso sem alguém para amar?',
      'ต่อให้ครอบครองทั้งโลกได้ ถ้าไม่มีคนที่รัก ทั้งหมดนั้นจะมีความหมายอะไร',
      'Sekalipun memiliki seluruh dunia, apa artinya semua itu jika tak ada orang yang dicintai?',
      'Dù có nắm cả thiên hạ đi nữa thì nếu không có người mình yêu thương, tất cả những điều đó có ý nghĩa gì?',
      '天下をすべて手にしたところで、愛する人がいなければ、それが一体何の意味を持つでしょうか。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ망정',
    sentence: '시험에 떨어질망정 남의 답안을 베끼지는 않겠습니다.',
    trans: L(
      "Even if I fail the exam, I will never copy someone else's answers.",
      'Aunque suspenda el examen, jamás copiaré las respuestas de otro.',
      "Quitte à échouer à l'examen, je ne copierai jamais les réponses d'un autre.",
      'Mesmo que eu seja reprovado na prova, jamais vou copiar as respostas de outra pessoa.',
      'ถึงจะสอบตกก็ตาม ผมก็จะไม่ลอกคำตอบของคนอื่นเด็ดขาด',
      'Sekalipun saya gagal ujian, saya tidak akan menyontek jawaban orang lain.',
      'Cho dù có thi trượt đi nữa, tôi cũng nhất quyết không chép bài của người khác.',
      '試験に落ちることはあっても、人の答案を写すことはしません。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ망정',
    sentence: '굶을망정 친구한테 손을 벌리고 싶지는 않아.',
    trans: L(
      "I'd rather go hungry than ask a friend for a handout.",
      'Prefiero pasar hambre antes que pedirle dinero a un amigo.',
      'Quitte à crever de faim, je ne veux pas tendre la main à un ami.',
      'Prefiro passar fome a pedir dinheiro emprestado a um amigo.',
      'ต่อให้ต้องอดข้าวก็ยอม แต่ฉันไม่อยากเอ่ยปากขอเงินเพื่อนหรอก',
      'Lebih baik aku kelaparan daripada harus meminta-minta uang ke teman.',
      'Thà chịu đói chứ tớ không muốn ngửa tay xin tiền bạn bè đâu.',
      '飢えることはあっても、友達にお金をせびりたくはないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-기로서니',
    sentence: '아무리 화가 나기로서니 부모님께 그렇게 말하면 안 되지.',
    trans: L(
      "No matter how angry you are, you shouldn't talk to your parents like that.",
      'Por muy enfadado que estés, no deberías hablarles así a tus padres.',
      "Tu as beau être en colère, ce n'est pas une raison pour parler ainsi à tes parents.",
      'Por mais bravo que você esteja, não pode falar assim com os seus pais.',
      'ต่อให้โกรธแค่ไหน ก็ไม่ควรพูดกับพ่อแม่แบบนั้น',
      'Semarah apa pun kamu, tidak seharusnya bicara seperti itu kepada orang tua.',
      'Dù có giận đến đâu thì cũng không được nói với bố mẹ như thế.',
      'いくら腹が立ったからといって、両親にそんな口をきいてはいけないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-기로서니',
    sentence: '사정이 급하기로서니 남의 물건에 함부로 손을 대서야 되겠습니까?',
    trans: L(
      "However urgent your situation may be, surely you can't just lay hands on someone else's belongings?",
      'Por muy urgente que sea su situación, ¿acaso es admisible tocar las cosas ajenas a la ligera?',
      "Aussi urgente que soit votre situation, peut-on vraiment se permettre de toucher les affaires d'autrui ainsi ?",
      'Por mais urgente que seja a sua situação, será admissível mexer assim nos pertences alheios?',
      'ต่อให้สถานการณ์เร่งด่วนแค่ไหน จะไปแตะต้องของของคนอื่นตามใจชอบได้อย่างนั้นหรือ',
      'Sekalipun keadaan Anda mendesak, apakah pantas seenaknya menyentuh barang milik orang lain?',
      'Dù hoàn cảnh có cấp bách đến mấy, lẽ nào lại có thể tùy tiện đụng vào đồ của người khác như vậy?',
      'いくら事情が急だからといって、他人の物に勝手に手を出していいものでしょうか。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)로 말미암아',
    sentence: '이번 폭우로 말미암아 농작물 피해가 막대했습니다.',
    trans: L(
      'Owing to this heavy rain, the damage to crops was enormous.',
      'A raíz de estas fuertes lluvias, los daños a los cultivos fueron enormes.',
      'Du fait de ces pluies torrentielles, les dégâts aux cultures ont été énormes.',
      'Em razão dessas chuvas intensas, os danos às lavouras foram enormes.',
      'อันสืบเนื่องมาจากฝนที่ตกหนักครั้งนี้ ความเสียหายต่อพืชผลจึงมหาศาล',
      'Akibat dari hujan deras kali ini, kerusakan tanaman pun sangat besar.',
      'Do trận mưa lớn lần này, thiệt hại đối với mùa màng là vô cùng to lớn.',
      '今回の豪雨により、農作物の被害は甚大でした。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)로 말미암아',
    sentence: '오랜 전쟁으로 말미암아 수많은 사람들이 고향을 떠나야 했어요.',
    trans: L(
      'Owing to the long war, countless people had to leave their hometowns.',
      'A raíz de la larga guerra, innumerables personas tuvieron que abandonar su tierra natal.',
      "Du fait de la longue guerre, d'innombrables personnes ont dû quitter leur région natale.",
      'Em razão da longa guerra, inúmeras pessoas tiveram que deixar sua terra natal.',
      'อันสืบเนื่องมาจากสงครามอันยาวนาน ผู้คนจำนวนมากจึงต้องละทิ้งบ้านเกิด',
      'Akibat dari perang yang berkepanjangan, banyak sekali orang harus meninggalkan kampung halamannya.',
      'Do cuộc chiến tranh kéo dài, vô số người đã phải rời bỏ quê hương.',
      '長い戦争により、数多くの人々が故郷を離れなければなりませんでした。',
    ),
    level: 'polite',
  },
  {
    ko: '-(으)ㄴ/는 즉',
    sentence: '이번 회의는 비공개로 진행됩니다. 즉 외부 인사의 참석은 허용되지 않습니다.',
    trans: L(
      'This meeting will be held behind closed doors. That is, attendance by outside parties is not permitted.',
      'Esta reunión se celebrará a puerta cerrada. Es decir, no se permite la asistencia de personas externas.',
      "Cette réunion se tiendra à huis clos. Autrement dit, la présence de personnes extérieures n'est pas autorisée.",
      'Esta reunião será realizada a portas fechadas. Ou seja, não é permitida a presença de pessoas externas.',
      'การประชุมครั้งนี้จะจัดแบบปิด กล่าวคือ ไม่อนุญาตให้บุคคลภายนอกเข้าร่วม',
      'Rapat ini akan diadakan secara tertutup. Artinya, kehadiran pihak luar tidak diizinkan.',
      'Cuộc họp này được tổ chức kín. Tức là không cho phép người ngoài tham dự.',
      '今回の会議は非公開で行われます。すなわち、外部の人の参加は認められません。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는 즉',
    sentence: '마감이 내일이래. 즉 오늘 밤 안에 다 끝내야 한다는 거지.',
    trans: L(
      "The deadline's tomorrow, apparently. In other words, it means we've got to finish everything by tonight.",
      'Dicen que la fecha límite es mañana. O sea, que tenemos que terminarlo todo esta noche.',
      "Il paraît que la date limite, c'est demain. Autrement dit, on doit tout finir avant ce soir.",
      'Dizem que o prazo é amanhã. Ou seja, a gente tem que terminar tudo até hoje à noite.',
      'เขาว่ากำหนดส่งคือพรุ่งนี้ พูดง่าย ๆ ก็คือต้องทำให้เสร็จหมดภายในคืนนี้',
      'Katanya tenggatnya besok. Dengan kata lain, kita harus menyelesaikan semuanya malam ini.',
      'Nghe nói hạn chót là ngày mai. Nói cách khác, tức là phải làm xong hết trong tối nay.',
      '締め切りは明日だって。つまり、今夜中に全部終わらせなきゃってことだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-거니와',
    sentence: '오늘은 날씨도 춥거니와 바람까지 불어서 도저히 못 나가겠어요.',
    trans: L(
      "Not only is it cold today, but it's even windy on top of that, so there's no way I can go out.",
      'Hoy no solo hace frío, sino que además sopla el viento, así que no hay manera de que pueda salir.',
      "Non seulement il fait froid aujourd'hui, mais en plus il y a du vent, alors je ne peux vraiment pas sortir.",
      'Hoje não só está frio, como ainda por cima está ventando, então não tem como eu sair.',
      'วันนี้ไม่เพียงแต่อากาศหนาว แต่ยังมีลมพัดอีก เลยออกไปข้างนอกไม่ไหวเลย',
      'Hari ini bukan hanya dingin, tetapi juga berangin, jadi sama sekali tidak bisa keluar.',
      'Hôm nay không những trời lạnh mà còn có gió nữa, nên chẳng thể nào ra ngoài được.',
      '今日は寒いうえに風まで吹いていて、とても外に出られそうにありません。',
    ),
    level: 'polite',
  },
  {
    ko: '-거니와',
    sentence: '이 식당은 음식이 맛있거니와 값도 싸서 늘 손님이 많아.',
    trans: L(
      "The food at this restaurant is delicious, and on top of that it's cheap, so it's always packed with customers.",
      'La comida de este restaurante está rica y, además, es barata, por eso siempre está lleno de clientes.',
      'Dans ce restaurant, la nourriture est délicieuse et, en plus, les prix sont bas, alors il y a toujours plein de clients.',
      'A comida desse restaurante é gostosa e, além disso, é barata, por isso vive cheio de clientes.',
      'ร้านอาหารร้านนี้อาหารอร่อย อีกทั้งราคายังถูก เลยมีลูกค้าเยอะตลอด',
      'Makanan di restoran ini enak, lagi pula harganya murah, jadi selalu ramai pelanggan.',
      'Quán này đồ ăn ngon mà giá lại còn rẻ nữa, nên lúc nào cũng đông khách.',
      'この店は料理がおいしいうえに値段も安いから、いつもお客さんが多いんだ。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 마당에',
    sentence: '회사가 망하는 마당에 월급 인상을 바랄 수는 없죠.',
    trans: L(
      "Given that the company is going under, we can't really expect a pay raise, can we.",
      'Con la empresa yéndose a pique, no podemos esperar un aumento de sueldo, ¿verdad?',
      "Alors que l'entreprise fait faillite, on ne peut pas vraiment espérer une augmentation de salaire, n'est-ce pas.",
      'Com a empresa indo à falência, não dá para esperar um aumento de salário, né.',
      'ในเมื่อบริษัทกำลังจะเจ๊งอยู่แล้ว จะไปหวังขึ้นเงินเดือนได้ยังไงล่ะ',
      'Di saat perusahaan sedang bangkrut begini, mana bisa kita berharap kenaikan gaji.',
      'Trong tình cảnh công ty đang phá sản thế này thì đâu thể mong được tăng lương.',
      '会社が潰れようとしている状況で、給料アップを望むなんてできませんよ。',
    ),
    level: 'polite',
  },
  {
    ko: '-는 마당에',
    sentence: '다 같이 굶는 마당에 너만 혼자 살겠다고 도망치냐?',
    trans: L(
      "When we're all starving together, you're running off to save just yourself?",
      'Cuando todos estamos pasando hambre juntos, ¿tú te largas para salvarte tú solo?',
      "Alors qu'on crève tous de faim ensemble, tu te tires pour sauver ta seule peau ?",
      'Numa hora em que estamos todos passando fome juntos, você foge pra salvar só a si mesmo?',
      'ในเมื่อพวกเราอดอยากกันหมดทั้งกลุ่ม เอ็งจะหนีไปเอาตัวรอดคนเดียวงั้นเหรอ',
      'Di saat kita semua kelaparan bareng-bareng, kamu malah kabur mau selamat sendirian?',
      'Lúc cả đám đang chết đói cùng nhau mà mày bỏ chạy lo thân mình thôi à?',
      'みんな一緒に飢えてるってのに、お前だけ自分が助かろうと逃げるのか?',
    ),
    level: 'casual',
  },
  {
    ko: '-(이)야말로',
    sentence: '건강이야말로 가장 큰 재산입니다.',
    trans: L(
      'Health is truly the greatest wealth of all.',
      'La salud es justamente la mayor riqueza de todas.',
      'La santé est véritablement la plus grande des richesses.',
      'A saúde é justamente a maior riqueza de todas.',
      'สุขภาพนี่แหละคือทรัพย์สมบัติที่ยิ่งใหญ่ที่สุด',
      'Kesehatanlah yang merupakan kekayaan terbesar.',
      'Sức khỏe mới chính là tài sản lớn nhất.',
      '健康こそが一番の財産です。',
    ),
    level: 'formal',
  },
  {
    ko: '-(이)야말로',
    sentence: '이번 여행이야말로 정말 잊지 못할 추억이었어.',
    trans: L(
      'This trip was truly an unforgettable memory.',
      'Este viaje fue precisamente un recuerdo inolvidable.',
      'Ce voyage a vraiment été un souvenir inoubliable.',
      'Esta viagem foi justamente uma lembrança inesquecível.',
      'ทริปครั้งนี้นี่แหละที่เป็นความทรงจำที่ลืมไม่ลงจริงๆ',
      'Perjalanan kali inilah yang benar-benar menjadi kenangan tak terlupakan.',
      'Chuyến đi lần này mới thực sự là kỷ niệm không thể nào quên.',
      '今回の旅行こそ本当に忘れられない思い出だったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '에 있어서',
    sentence: '회사 생활에 있어서 가장 중요한 것은 동료들과의 신뢰입니다.',
    trans: L(
      'When it comes to working at a company, the most important thing is trust with your colleagues.',
      'En lo que respecta a la vida laboral en una empresa, lo más importante es la confianza con los compañeros.',
      'En ce qui concerne la vie en entreprise, le plus important est la confiance avec ses collègues.',
      'Quando se trata da vida na empresa, o mais importante é a confiança com os colegas.',
      'ในเรื่องของชีวิตการทำงานในบริษัท สิ่งที่สำคัญที่สุดคือความไว้วางใจกับเพื่อนร่วมงาน',
      'Dalam hal kehidupan di perusahaan, hal yang paling penting adalah kepercayaan dengan rekan kerja.',
      'Trong cuộc sống làm việc ở công ty, điều quan trọng nhất là sự tin tưởng với đồng nghiệp.',
      '会社生活において最も大切なのは同僚との信頼です。',
    ),
    level: 'formal',
  },
  {
    ko: '에 있어서',
    sentence: '건강 관리에 있어서 규칙적인 운동만큼 좋은 게 없어.',
    trans: L(
      "When it comes to managing your health, there's nothing as good as regular exercise.",
      'En cuanto al cuidado de la salud, no hay nada mejor que el ejercicio regular.',
      'Pour ce qui est de prendre soin de sa santé, rien ne vaut un exercice régulier.',
      'Quando se trata de cuidar da saúde, não há nada melhor do que exercício regular.',
      'ในเรื่องของการดูแลสุขภาพ ไม่มีอะไรดีเท่าการออกกำลังกายอย่างสม่ำเสมอเลย',
      'Dalam hal menjaga kesehatan, tidak ada yang sebaik olahraga teratur.',
      'Về việc chăm sóc sức khỏe, không có gì tốt bằng việc tập thể dục đều đặn cả.',
      '健康管理において規則的な運動ほどいいものはないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-는 법이다',
    sentence: '급하게 먹으면 체하는 법입니다.',
    trans: L(
      "When you eat in a hurry, you're bound to get an upset stomach.",
      'Cuando comes con prisa, es normal que te siente mal el estómago.',
      "Quand on mange à la hâte, on a forcément l'estomac dérangé.",
      'Quando você come com pressa, é natural ficar com o estômago embrulhado.',
      'ถ้ากินรีบ ๆ ก็ย่อมจะท้องไส้ปั่นป่วนเป็นธรรมดา',
      'Kalau makan terburu-buru, perut memang jadi tidak enak.',
      'Ăn vội thì kiểu gì cũng bị đau bụng thôi.',
      '急いで食べると、お腹を壊すものです。',
    ),
    level: 'formal',
  },
  {
    ko: '-는 법이다',
    sentence: '시간이 지나면 아픈 기억도 잊히는 법이야.',
    trans: L(
      'As time passes, even painful memories naturally fade away.',
      'Con el tiempo, hasta los recuerdos dolorosos se olvidan, así son las cosas.',
      "Avec le temps, même les souvenirs douloureux finissent par s'effacer, c'est ainsi.",
      'Com o tempo, até as memórias dolorosas acabam sendo esquecidas, é assim mesmo.',
      'พอเวลาผ่านไป ความทรงจำที่เจ็บปวดก็ลืมเลือนไปเองนั่นแหละ',
      'Seiring waktu berlalu, kenangan menyakitkan pun akan terlupakan dengan sendirinya.',
      'Thời gian trôi qua thì những ký ức đau buồn rồi cũng phai nhạt thôi.',
      '時間が経てば、つらい記憶も忘れていくものだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄴ/는 이상',
    sentence: '회사에 입사한 이상 회사 규칙을 따라야 합니다.',
    trans: L(
      "Now that you've joined the company, you must follow the company rules.",
      'Ya que entraste en la empresa, tienes que seguir las normas de la empresa.',
      "Dès lors que vous avez rejoint l'entreprise, vous devez en respecter les règles.",
      'Já que você entrou na empresa, tem que seguir as regras da empresa.',
      'ในเมื่อเข้าทำงานในบริษัทแล้ว ก็ต้องปฏิบัติตามกฎของบริษัท',
      'Karena sudah masuk ke perusahaan, kamu harus mengikuti peraturan perusahaan.',
      'Đã vào công ty làm việc thì phải tuân theo nội quy của công ty.',
      '会社に入社した以上、会社の規則に従わなければなりません。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄴ/는 이상',
    sentence: '시험을 보는 이상 최선을 다해야지.',
    trans: L(
      "As long as I'm taking the exam, I should give it my best.",
      'Ya que voy a hacer el examen, tengo que dar lo mejor de mí.',
      "Du moment que je passe l'examen, autant donner le meilleur de moi-même.",
      'Já que vou fazer a prova, tenho que dar o meu melhor.',
      'ในเมื่อจะสอบแล้ว ก็ต้องทำให้เต็มที่สิ',
      'Karena toh ikut ujian, ya harus berusaha sebaik mungkin.',
      'Đã đi thi thì phải cố hết sức chứ.',
      '試験を受ける以上、ベストを尽くさなきゃ。',
    ),
    level: 'casual',
  },
  {
    ko: '-다시피',
    sentence: '보시다시피 지금 가게가 너무 바빠서 잠깐 기다려 주셔야 할 것 같습니다.',
    trans: L(
      "As you can see, the shop is so busy right now that I'm afraid you'll have to wait a moment.",
      'Como puede ver, la tienda está muy ocupada ahora mismo, así que me temo que tendrá que esperar un momento.',
      'Comme vous pouvez le voir, la boutique est très occupée en ce moment, donc je crains que vous deviez patienter un instant.',
      'Como o senhor pode ver, a loja está muito movimentada agora, então acho que terá que esperar um momento.',
      'อย่างที่เห็น ตอนนี้ร้านยุ่งมากเลยค่ะ คงต้องรบกวนรอสักครู่นะคะ',
      'Seperti yang Anda lihat, toko sedang sangat ramai sekarang, jadi sepertinya Anda harus menunggu sebentar.',
      'Như quý khách thấy đấy, bây giờ cửa hàng đang rất bận nên có lẽ quý khách phải đợi một lát ạ.',
      'ご覧のとおり、今お店がとても混んでいるので、少々お待ちいただくことになりそうです。',
    ),
    level: 'formal',
  },
  {
    ko: '-다시피',
    sentence: '너도 알다시피 나 요즘 시험 준비 때문에 정신이 하나도 없어.',
    trans: L(
      "As you know too, I've been completely swamped lately because of preparing for exams.",
      'Como tú también sabes, últimamente estoy hecha un lío por la preparación de los exámenes.',
      'Comme tu le sais toi aussi, je suis complètement débordée ces temps-ci à cause de la préparation des examens.',
      'Como você também sabe, ando completamente sem cabeça ultimamente por causa da preparação para as provas.',
      'อย่างที่เธอก็รู้ ช่วงนี้ฉันยุ่งจนหัวหมุนเพราะต้องเตรียมตัวสอบเลยล่ะ',
      'Seperti yang kamu juga tahu, akhir-akhir ini aku benar-benar kewalahan karena persiapan ujian.',
      'Như cậu cũng biết đấy, dạo này tớ rối tung cả lên vì phải chuẩn bị thi.',
      '君も知ってのとおり、最近は試験の準備でてんてこ舞いなんだよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-ㄴ/는다',
    sentence: '나는 매일 아침 일곱 시에 일어난다.',
    trans: L(
      "I wake up at seven o'clock every morning.",
      'Me levanto a las siete todas las mañanas.',
      'Je me lève à sept heures tous les matins.',
      'Eu acordo às sete horas todas as manhãs.',
      'ฉันตื่นนอนตอนเจ็ดโมงทุกเช้า',
      'Saya bangun jam tujuh setiap pagi.',
      'Tôi thức dậy lúc bảy giờ mỗi sáng.',
      '私は毎朝七時に起きる。',
    ),
    level: 'casual',
  },
  {
    ko: '-ㄴ/는다',
    sentence: '동생은 주말마다 도서관에서 책을 읽는다.',
    trans: L(
      'My younger sibling reads books at the library every weekend.',
      'Mi hermano menor lee libros en la biblioteca todos los fines de semana.',
      'Mon cadet lit des livres à la bibliothèque chaque week-end.',
      'Meu irmão mais novo lê livros na biblioteca todo fim de semana.',
      'น้องของฉันอ่านหนังสือที่ห้องสมุดทุกสุดสัปดาห์',
      'Adik saya membaca buku di perpustakaan setiap akhir pekan.',
      'Em tôi đọc sách ở thư viện vào mỗi cuối tuần.',
      '弟は週末ごとに図書館で本を読む。',
    ),
    level: 'casual',
  },
  {
    ko: '-노라',
    sentence: '내 너에게 한 가지 약속을 하노라.',
    trans: L(
      'I hereby make you a single promise.',
      'Te hago, por la presente, una sola promesa.',
      'Je te fais ici une seule promesse.',
      'Eu te faço, por meio desta, uma única promessa.',
      'ข้าขอให้สัญญาแก่เจ้าหนึ่งข้อ',
      'Dengan ini aku berikan satu janji kepadamu.',
      'Ta xin hứa với ngươi một điều.',
      '我は汝に一つの約束をなさん。',
    ),
    level: 'formal',
  },
  {
    ko: '-노라',
    sentence: '오늘 우리는 마침내 자유를 얻었노라.',
    trans: L(
      'Today we have at last won our freedom.',
      'Hoy por fin hemos conquistado la libertad.',
      "Aujourd'hui, nous avons enfin conquis la liberté.",
      'Hoje, enfim, conquistamos a liberdade.',
      'วันนี้ในที่สุดพวกเราก็ได้รับอิสรภาพแล้ว',
      'Hari ini akhirnya kita telah meraih kebebasan.',
      'Hôm nay, cuối cùng chúng ta đã giành được tự do.',
      '今日、我らはついに自由を勝ち取ったのだ。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ진대',
    sentence: '이미 엎질러진 물일진대 후회한들 무슨 소용이 있겠는가.',
    trans: L(
      'Since the water has already been spilled, what use could there be in regretting it?',
      'Siendo que el agua ya está derramada, ¿de qué serviría arrepentirse?',
      "Puisque l'eau est déjà renversée, à quoi bon le regretter ?",
      'Já que a água já foi derramada, de que adiantaria se arrepender?',
      'ในเมื่อน้ำหกไปแล้ว ต่อให้เสียใจไปก็จะมีประโยชน์อันใดเล่า',
      'Karena air sudah telanjur tumpah, apa gunanya menyesalinya?',
      'Một khi nước đã đổ rồi, dẫu có hối hận thì phỏng có ích gì?',
      'すでにこぼれた水であろうから、悔やんだところで何の役に立とうか。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ진대',
    sentence: '그가 진심으로 뉘우쳤을진대 우리가 어찌 용서하지 않을 수 있으랴.',
    trans: L(
      'If he has indeed repented sincerely, how could we possibly not forgive him?',
      'Si en verdad se ha arrepentido de corazón, ¿cómo podríamos no perdonarlo?',
      "S'il s'est vraiment repenti du fond du cœur, comment pourrions-nous ne pas lui pardonner ?",
      'Se ele de fato se arrependeu sinceramente, como poderíamos não perdoá-lo?',
      'หากเขาสำนึกผิดด้วยใจจริงแล้วไซร้ เราจะไม่ให้อภัยได้อย่างไรกัน',
      'Jika dia sungguh-sungguh telah bertobat, bagaimana mungkin kita tidak memaafkannya?',
      'Nếu quả thật anh ấy đã ăn năn từ tận đáy lòng, lẽ nào chúng ta lại không thể tha thứ?',
      '彼が心から悔い改めたのであろうから、我々がどうして許さずにいられようか。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ쏘냐',
    sentence: '내가 그깟 시련에 무너질쏘냐.',
    trans: L(
      'Would I crumble before such a trifling hardship? (Never.)',
      '¿Acaso me derrumbaría yo ante una prueba tan insignificante? (Jamás.)',
      "Vais-je m'effondrer devant une épreuve aussi dérisoire ? (Jamais.)",
      'Será que eu desmoronaria diante de uma provação tão insignificante? (Nunca.)',
      'ข้าจะยอมพังทลายเพราะความยากลำบากเล็กน้อยเช่นนั้นเชียวหรือ (ไม่มีวัน)',
      'Akankah aku runtuh hanya karena cobaan sepele seperti itu? (Tak akan pernah.)',
      'Lẽ nào ta lại gục ngã trước một thử thách cỏn con như thế? (Không bao giờ.)',
      '私がそんなちっぽけな試練に崩れ落ちたりするものか。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ쏘냐',
    sentence: '조상님이 물려주신 이 뜻을 후손이 어찌 저버릴쏘냐.',
    trans: L(
      'How could we descendants ever forsake this will handed down by our ancestors? (We never will.)',
      '¿Cómo podríamos los descendientes abandonar esta voluntad que nos legaron nuestros ancestros? (Jamás lo haremos.)',
      'Comment, nous descendants, pourrions-nous trahir cette volonté que nos ancêtres nous ont léguée ? (Jamais.)',
      'Como poderíamos, nós descendentes, abandonar esta vontade legada por nossos antepassados? (Jamais.)',
      'ลูกหลานอย่างเราจะทอดทิ้งเจตนารมณ์ที่บรรพบุรุษมอบไว้ได้อย่างไรกัน (ไม่มีทาง)',
      'Bagaimana mungkin kami para keturunan menelantarkan kehendak yang diwariskan leluhur ini? (Tak mungkin.)',
      'Con cháu chúng ta lẽ nào lại từ bỏ chí nguyện mà tổ tiên truyền lại? (Không đời nào.)',
      'ご先祖が遺してくださったこの志を、子孫である我々がどうして見捨てたりしようか。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 마지않다',
    sentence: '두 분의 결혼을 진심으로 축하해 마지않습니다.',
    trans: L(
      'We sincerely congratulate the two of you on your marriage.',
      'Felicitamos de todo corazón a ambos por su matrimonio.',
      'Nous vous félicitons de tout cœur pour votre mariage.',
      'Felicitamos sinceramente os dois pelo casamento.',
      'ขอแสดงความยินดีกับการแต่งงานของทั้งสองท่านอย่างจริงใจ',
      'Kami dengan tulus mengucapkan selamat atas pernikahan kalian berdua.',
      'Chúng tôi xin chân thành chúc mừng hôn lễ của hai bạn.',
      'お二人のご結婚を心よりお祝い申し上げてやみません。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 마지않다',
    sentence: '선생님의 빠른 쾌유를 바라 마지않습니다.',
    trans: L(
      'I sincerely wish you a speedy recovery, sir.',
      'Le deseo de corazón una pronta recuperación, profesor.',
      'Je vous souhaite de tout cœur un prompt rétablissement, Monsieur.',
      'Desejo sinceramente sua rápida recuperação, professor.',
      'ผมขออวยพรให้อาจารย์หายป่วยโดยเร็วอย่างสุดใจ',
      'Saya sungguh-sungguh mendoakan kesembuhan Anda yang cepat, Guru.',
      'Em thành tâm mong thầy sớm bình phục.',
      '先生の一日も早いご回復を願ってやみません。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 마땅하다',
    sentence: '약속을 어긴 사람은 비난받아 마땅합니다.',
    trans: L(
      'A person who breaks a promise deserves to be blamed.',
      'Quien rompe una promesa merece ser reprochado.',
      "Celui qui rompt une promesse mérite d'être blâmé.",
      'Quem quebra uma promessa merece ser repreendido.',
      'คนที่ผิดสัญญาสมควรถูกตำหนิ',
      'Orang yang mengingkari janji memang pantas dicela.',
      'Người thất hứa thì đáng bị chỉ trích.',
      '約束を破った人は非難されて当然です。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 마땅하다',
    sentence: '이렇게 열심히 일했으니 너는 상을 받아 마땅해.',
    trans: L(
      'Since you worked this hard, you deserve to get the award.',
      'Ya que trabajaste tan duro, mereces recibir el premio.',
      'Puisque tu as travaillé si dur, tu mérites de recevoir le prix.',
      'Já que você trabalhou tão duro, você merece receber o prêmio.',
      'ในเมื่อเธอทำงานหนักขนาดนี้ เธอก็สมควรได้รับรางวัล',
      'Karena kamu sudah bekerja sekeras ini, kamu pantas menerima hadiah itu.',
      'Vì cậu đã làm việc chăm chỉ như vậy nên cậu xứng đáng được nhận phần thưởng.',
      'こんなに一生懸命働いたんだから、君は賞をもらって当然だよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)리라(고)',
    sentence: '그는 반드시 돌아오리라고 다짐하며 길을 떠났다.',
    trans: L(
      'He set off, vowing to himself that he would surely return.',
      'Partió prometiéndose a sí mismo que sin duda regresaría.',
      "Il partit en se jurant qu'il reviendrait à coup sûr.",
      'Ele partiu prometendo a si mesmo que com certeza voltaria.',
      'เขาออกเดินทางพร้อมตั้งปณิธานว่าจะต้องกลับมาให้ได้',
      'Dia berangkat sambil berjanji pada diri sendiri bahwa dia pasti akan kembali.',
      'Anh ấy lên đường, tự nhủ rằng nhất định mình sẽ trở về.',
      '彼は必ず戻ってこようと心に誓いながら旅立った。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)리라(고)',
    sentence: '내일은 날씨가 맑으리라 생각하고 우산을 안 가져왔어.',
    trans: L(
      "I figured the weather would be clear tomorrow, so I didn't bring an umbrella.",
      'Pensé que mañana haría buen tiempo, así que no traje paraguas.',
      "Je me suis dit qu'il ferait beau demain, alors je n'ai pas pris de parapluie.",
      'Achei que amanhã o tempo estaria bom, então não trouxe guarda-chuva.',
      'คิดว่าพรุ่งนี้อากาศคงจะแจ่มใส เลยไม่ได้เอาร่มมา',
      'Aku pikir besok cuacanya bakal cerah, jadi nggak bawa payung.',
      'Mình nghĩ mai trời sẽ nắng nên không mang ô theo.',
      '明日は晴れるだろうと思って、傘を持ってこなかったよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-(으)ㄹ세라',
    sentence: '행여 부모님이 걱정하실세라 매일 안부 전화를 드립니다.',
    trans: L(
      'For fear that my parents might worry, I call to check in on them every day.',
      'Por temor a que mis padres se preocupen, los llamo todos los días para saludarlos.',
      "De peur que mes parents ne s'inquiètent, je les appelle tous les jours pour prendre des nouvelles.",
      'Com medo de que meus pais se preocupem, ligo todos os dias para saber como estão.',
      'เพราะกลัวว่าพ่อแม่จะเป็นห่วง ฉันจึงโทรไปถามไถ่สารทุกข์สุกดิบทุกวัน',
      'Karena khawatir orang tuaku cemas, aku menelepon menanyakan kabar setiap hari.',
      'Vì sợ bố mẹ lo lắng, tôi gọi điện hỏi thăm mỗi ngày.',
      '両親が心配するといけないので、毎日安否の電話をかけています。',
    ),
    level: 'formal',
  },
  {
    ko: '-(으)ㄹ세라',
    sentence: '혹시 비밀이 새어 나갈세라 우리는 작은 목소리로 속삭였다.',
    trans: L(
      'For fear the secret might leak out, we whispered in low voices.',
      'Por temor a que el secreto se filtrara, susurrábamos en voz baja.',
      "De peur que le secret ne s'échappe, nous chuchotions à voix basse.",
      'Com medo de que o segredo vazasse, sussurrávamos em voz baixa.',
      'เพราะกลัวว่าความลับจะรั่วไหลออกไป พวกเราจึงกระซิบกันด้วยเสียงเบา ๆ',
      'Karena takut rahasianya bocor, kami berbisik dengan suara pelan.',
      'Vì sợ bí mật bị lộ ra ngoài, chúng tôi thì thầm bằng giọng rất nhỏ.',
      'もしや秘密が漏れるといけないと、私たちは小さな声でささやいた。',
    ),
    level: 'casual',
  },
  {
    ko: '-건만',
    sentence: '분명히 약속했건만 그는 끝내 나타나지 않았다.',
    trans: L(
      'He clearly promised, and yet in the end he never showed up.',
      'Aunque lo prometió claramente, al final nunca apareció.',
      "Il l'avait pourtant clairement promis, mais finalement il n'est jamais venu.",
      'Ele prometeu claramente, mas no fim nunca apareceu.',
      'ทั้งที่เขาสัญญาไว้อย่างชัดเจน แต่สุดท้ายเขาก็ไม่มาเลย',
      'Padahal dia sudah jelas-jelas berjanji, tetapi pada akhirnya dia tak pernah muncul.',
      'Rõ ràng anh ấy đã hứa, vậy mà cuối cùng anh ấy chẳng hề xuất hiện.',
      'はっきり約束したのに、彼は結局現れなかった。',
    ),
    level: 'formal',
  },
  {
    ko: '-건만',
    sentence: '열심히 노력했건만 결과는 신통치 않네요.',
    trans: L(
      "I worked so hard, and yet the results just aren't great.",
      'Me esforcé mucho, pero los resultados no son nada buenos.',
      "J'ai travaillé dur, et pourtant les résultats ne sont guère brillants.",
      'Eu me esforcei muito, mas os resultados não são lá essas coisas.',
      'ทั้งที่พยายามอย่างหนัก แต่ผลลัพธ์กลับไม่ค่อยดีเลยค่ะ',
      'Padahal sudah berusaha keras, tetapi hasilnya kurang memuaskan.',
      'Tôi đã cố gắng hết sức, vậy mà kết quả lại chẳng được như ý.',
      '一生懸命努力したのに、結果はいまいちですね。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 주십사 (하고)',
    sentence: '회장님께 행사에 꼭 참석해 주십사 하고 정중히 청하였습니다.',
    trans: L(
      'We respectfully asked the chairman, requesting that he please attend the event.',
      'Le pedimos respetuosamente al presidente que tuviera la bondad de asistir al evento.',
      "Nous avons prié respectueusement le président de bien vouloir assister à l'événement.",
      'Pedimos respeitosamente ao presidente que tivesse a gentileza de comparecer ao evento.',
      'เราได้เรียนเชิญท่านประธานอย่างสุภาพ ขอความกรุณาให้ท่านมาร่วมงานด้วย',
      'Kami dengan hormat memohon kepada ketua agar berkenan menghadiri acara tersebut.',
      'Chúng tôi đã kính cẩn thỉnh cầu chủ tịch xin hãy đến tham dự sự kiện.',
      '会長に行事へぜひご出席いただきたいと、丁重にお願い申し上げました。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 주십사 (하고)',
    sentence: '선생님께 추천서를 좀 써 주십사 하고 조심스럽게 여쭤봤어요.',
    trans: L(
      'I cautiously asked the teacher, requesting that she please write me a recommendation letter.',
      'Le pregunté con cautela a la profesora, pidiéndole que tuviera la amabilidad de escribirme una carta de recomendación.',
      "J'ai demandé prudemment à mon professeur de bien vouloir me rédiger une lettre de recommandation.",
      'Perguntei com cautela à professora, pedindo que tivesse a bondade de me escrever uma carta de recomendação.',
      'ฉันค่อย ๆ เรียนถามอาจารย์ ขอความกรุณาให้ท่านช่วยเขียนจดหมายแนะนำตัวให้หน่อย',
      'Saya dengan hati-hati menanyakan kepada guru, memohon agar beliau berkenan menuliskan surat rekomendasi untuk saya.',
      'Tôi đã dè dặt hỏi thầy, xin thầy vui lòng viết cho tôi một lá thư giới thiệu.',
      '先生に推薦状を書いていただきたいと、おそるおそる伺ってみました。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 마다하지 않다',
    sentence: '그 의사는 환자를 살리기 위해 밤샘 수술도 마다하지 않았습니다.',
    trans: L(
      'That doctor did not refuse even all-night surgery in order to save the patient.',
      'Ese médico no rehusó ni siquiera una cirugía que duró toda la noche con tal de salvar al paciente.',
      "Ce médecin n'a pas refusé même une opération qui a duré toute la nuit pour sauver le patient.",
      'Aquele médico não recusou nem mesmo uma cirurgia que durou a noite toda para salvar o paciente.',
      'คุณหมอคนนั้นไม่ปฏิเสธแม้แต่การผ่าตัดข้ามคืนเพื่อช่วยชีวิตคนไข้',
      'Dokter itu tidak menolak bahkan operasi semalaman demi menyelamatkan pasien.',
      'Vị bác sĩ đó đã không từ chối cả ca phẫu thuật thâu đêm để cứu sống bệnh nhân.',
      'あの医者は患者を救うために徹夜の手術もいとわなかったです。',
    ),
    level: 'formal',
  },
  {
    ko: '-아/어 마다하지 않다',
    sentence: '그 친구는 내가 부탁하면 궂은일도 마다하지 않아.',
    trans: L(
      "That friend doesn't refuse even unpleasant tasks when I ask.",
      'Ese amigo no rechaza ni las tareas más ingratas cuando se lo pido.',
      'Cet ami ne refuse même pas les corvées ingrates quand je le lui demande.',
      'Esse amigo não recusa nem as tarefas mais ingratas quando eu peço.',
      'เพื่อนคนนั้นไม่ปฏิเสธแม้แต่งานที่ยากลำบากเลยเวลาที่ฉันขอ',
      'Teman itu tidak menolak bahkan pekerjaan yang berat sekalipun kalau aku minta.',
      'Người bạn đó dù tôi nhờ việc khó nhọc cũng không từ chối.',
      'あの友達は私が頼むと面倒な仕事もいとわないよ。',
    ),
    level: 'casual',
  },
  {
    ko: '-노라면',
    sentence: '매일 꾸준히 연습하노라면 어느새 실력이 늘어 있을 거예요.',
    trans: L(
      'If you keep practicing diligently every day, your skills will have improved before you know it.',
      'Si practicas con constancia cada día, sin darte cuenta habrás mejorado.',
      "Si tu t'exerces assidûment chaque jour, tes compétences se seront améliorées sans que tu t'en aperçoives.",
      'Se você praticar com constância todos os dias, suas habilidades terão melhorado sem que você perceba.',
      'ถ้าฝึกฝนอย่างสม่ำเสมอทุกวัน ไม่ทันรู้ตัวฝีมือก็จะดีขึ้นเอง',
      'Kalau kamu terus berlatih dengan tekun setiap hari, tanpa terasa kemampuanmu akan meningkat.',
      'Nếu cứ chăm chỉ luyện tập mỗi ngày, lúc nào không hay năng lực của bạn sẽ tiến bộ.',
      '毎日こつこつ練習していれば、いつの間にか実力が伸びているはずです。',
    ),
    level: 'polite',
  },
  {
    ko: '-노라면',
    sentence: '이 길을 묵묵히 걷노라면 언젠가 끝이 보이겠지.',
    trans: L(
      "If I keep walking this path silently, someday I'll see the end.",
      'Si sigo recorriendo este camino en silencio, algún día veré el final.',
      "Si je continue à parcourir ce chemin en silence, un jour j'en verrai le bout.",
      'Se eu continuar percorrendo este caminho em silêncio, um dia verei o fim.',
      'ถ้าเดินไปบนเส้นทางนี้อย่างเงียบ ๆ ต่อไป สักวันก็คงเห็นจุดสิ้นสุดเอง',
      'Kalau aku terus menyusuri jalan ini dalam diam, suatu hari nanti pasti terlihat ujungnya.',
      'Nếu cứ lặng lẽ bước đi trên con đường này, một ngày nào đó hẳn sẽ thấy được điểm cuối.',
      'この道を黙々と歩いていれば、いつかは終わりが見えてくるだろう。',
    ),
    level: 'casual',
  },
  {
    ko: '-아/어 죽을 지경이다',
    sentence: '요즘 일이 너무 많아서 바빠 죽을 지경이에요.',
    trans: L(
      "These days I have so much work I'm about to die from how busy I am.",
      'Últimamente tengo tanto trabajo que estoy que me muero de lo ocupada que estoy.',
      "Ces temps-ci j'ai tellement de travail que je suis à deux doigts de mourir tellement je suis occupé.",
      'Ultimamente tenho tanto trabalho que estou a ponto de morrer de tão ocupada.',
      'ช่วงนี้งานเยอะมากจนแทบจะตายเพราะยุ่งสุดๆ',
      'Akhir-akhir ini pekerjaan saya banyak sekali sampai hampir mati saking sibuknya.',
      'Dạo này công việc nhiều quá nên tôi bận đến sắp chết mất.',
      '最近仕事が多すぎて、忙しくて死にそうな状態です。',
    ),
    level: 'polite',
  },
  {
    ko: '-아/어 죽을 지경이다',
    sentence: '아까부터 배가 아파 죽을 지경이야.',
    trans: L(
      "My stomach has been hurting so bad since a while ago I feel like I'm about to die.",
      'Desde hace rato me duele tanto el estómago que me muero.',
      "Depuis tout à l'heure j'ai tellement mal au ventre que je suis à deux doigts de mourir.",
      'Faz um tempinho que minha barriga dói tanto que estou a ponto de morrer.',
      'ปวดท้องตั้งแต่เมื่อกี้แล้ว แทบจะตายเลย',
      'Dari tadi perutku sakit sampai hampir mati rasanya.',
      'Từ nãy giờ tôi đau bụng đến sắp chết mất.',
      'さっきからお腹が痛くて死にそうなんだ。',
    ),
    level: 'casual',
  },
]
