// AUTO-GENERATED by scripts/escape-i18n-gen.mjs - do not edit by hand.
import { createEscapeTranslator, type EscapeLevelTranslations } from '../../../create-translator'
import { enLevel03 } from './en'
import { frLevel03 } from './fr'
import { ptBRLevel03 } from './pt-BR'
import { thLevel03 } from './th'
import { idLevel03 } from './id'
import { viLevel03 } from './vi'
import { jaLevel03 } from './ja'

export const LEVEL_03_TRANSLATIONS: EscapeLevelTranslations = {
  "en": enLevel03,
  "fr": frLevel03,
  "pt-BR": ptBRLevel03,
  "th": thLevel03,
  "id": idLevel03,
  "vi": viLevel03,
  "ja": jaLevel03,
}

export const t = createEscapeTranslator(LEVEL_03_TRANSLATIONS)
