// AUTO-GENERATED by scripts/escape-i18n-gen.mjs - do not edit by hand.
import { createEscapeTranslator, type EscapeLevelTranslations } from '../../../create-translator'
import { enLevel07 } from './en'
import { frLevel07 } from './fr'
import { ptBRLevel07 } from './pt-BR'
import { thLevel07 } from './th'
import { idLevel07 } from './id'
import { viLevel07 } from './vi'
import { jaLevel07 } from './ja'

export const LEVEL_07_TRANSLATIONS: EscapeLevelTranslations = {
  "en": enLevel07,
  "fr": frLevel07,
  "pt-BR": ptBRLevel07,
  "th": thLevel07,
  "id": idLevel07,
  "vi": viLevel07,
  "ja": jaLevel07,
}

export const t = createEscapeTranslator(LEVEL_07_TRANSLATIONS)
