// Generated from the adversarially-verified workflow output. Do not hand-edit.
import type { Ending, Particle, VerbClass } from '~/lib/korean'

export const GOLDEN_CONJUGATIONS: { dict: string; klass: VerbClass; ending: Ending; surface: string }[] = [
  { dict: "먹다", klass: "regular", ending: "-아/어요", surface: "먹어요" },
  { dict: "먹다", klass: "regular", ending: "-았/었어요", surface: "먹었어요" },
  { dict: "먹다", klass: "regular", ending: "-(으)니까", surface: "먹으니까" },
  { dict: "먹다", klass: "regular", ending: "-(으)면", surface: "먹으면" },
  { dict: "먹다", klass: "regular", ending: "-(으)세요", surface: "먹으세요" },
  { dict: "먹다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "먹을 거예요" },
  { dict: "가다", klass: "regular", ending: "-아/어요", surface: "가요" },
  { dict: "가다", klass: "regular", ending: "-았/었어요", surface: "갔어요" },
  { dict: "가다", klass: "regular", ending: "-(으)니까", surface: "가니까" },
  { dict: "가다", klass: "regular", ending: "-(으)면", surface: "가면" },
  { dict: "가다", klass: "regular", ending: "-(으)세요", surface: "가세요" },
  { dict: "가다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "갈 거예요" },
  { dict: "보다", klass: "regular", ending: "-아/어요", surface: "봐요" },
  { dict: "보다", klass: "regular", ending: "-았/었어요", surface: "봤어요" },
  { dict: "보다", klass: "regular", ending: "-(으)니까", surface: "보니까" },
  { dict: "보다", klass: "regular", ending: "-(으)면", surface: "보면" },
  { dict: "보다", klass: "regular", ending: "-(으)세요", surface: "보세요" },
  { dict: "보다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "볼 거예요" },
  { dict: "오다", klass: "regular", ending: "-아/어요", surface: "와요" },
  { dict: "오다", klass: "regular", ending: "-았/었어요", surface: "왔어요" },
  { dict: "마시다", klass: "regular", ending: "-아/어요", surface: "마셔요" },
  { dict: "마시다", klass: "regular", ending: "-았/었어요", surface: "마셨어요" },
  { dict: "되다", klass: "regular", ending: "-아/어요", surface: "돼요" },
  { dict: "되다", klass: "regular", ending: "-았/었어요", surface: "됐어요" },
  { dict: "주다", klass: "regular", ending: "-아/어요", surface: "줘요" },
  { dict: "주다", klass: "regular", ending: "-았/었어요", surface: "줬어요" },
  { dict: "만나다", klass: "regular", ending: "-아/어요", surface: "만나요" },
  { dict: "만나다", klass: "regular", ending: "-았/었어요", surface: "만났어요" },
  { dict: "공부하다", klass: "hada", ending: "-아/어요", surface: "공부해요" },
  { dict: "공부하다", klass: "hada", ending: "-았/었어요", surface: "공부했어요" },
  { dict: "좋다", klass: "regular", ending: "-아/어요", surface: "좋아요" },
  { dict: "좋다", klass: "regular", ending: "-았/었어요", surface: "좋았어요" },
  { dict: "좋다", klass: "regular", ending: "-(으)니까", surface: "좋으니까" },
  { dict: "좋다", klass: "regular", ending: "-(으)면", surface: "좋으면" },
  { dict: "좋다", klass: "regular", ending: "-(으)세요", surface: "좋으세요" },
  { dict: "좋다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "좋을 거예요" },
  { dict: "받다", klass: "regular", ending: "-아/어요", surface: "받아요" },
  { dict: "받다", klass: "regular", ending: "-았/었어요", surface: "받았어요" },
  { dict: "받다", klass: "regular", ending: "-(으)니까", surface: "받으니까" },
  { dict: "받다", klass: "regular", ending: "-(으)면", surface: "받으면" },
  { dict: "받다", klass: "regular", ending: "-(으)세요", surface: "받으세요" },
  { dict: "받다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "받을 거예요" },
  { dict: "덥다", klass: "p_irr", ending: "-아/어요", surface: "더워요" },
  { dict: "덥다", klass: "p_irr", ending: "-았/었어요", surface: "더웠어요" },
  { dict: "덥다", klass: "p_irr", ending: "-(으)니까", surface: "더우니까" },
  { dict: "덥다", klass: "p_irr", ending: "-(으)면", surface: "더우면" },
  { dict: "덥다", klass: "p_irr", ending: "-(으)세요", surface: "더우세요" },
  { dict: "덥다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "더울 거예요" },
  { dict: "춥다", klass: "p_irr", ending: "-아/어요", surface: "추워요" },
  { dict: "춥다", klass: "p_irr", ending: "-았/었어요", surface: "추웠어요" },
  { dict: "춥다", klass: "p_irr", ending: "-(으)니까", surface: "추우니까" },
  { dict: "춥다", klass: "p_irr", ending: "-(으)면", surface: "추우면" },
  { dict: "춥다", klass: "p_irr", ending: "-(으)세요", surface: "추우세요" },
  { dict: "춥다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "추울 거예요" },
  { dict: "쉽다", klass: "p_irr", ending: "-아/어요", surface: "쉬워요" },
  { dict: "쉽다", klass: "p_irr", ending: "-았/었어요", surface: "쉬웠어요" },
  { dict: "쉽다", klass: "p_irr", ending: "-(으)니까", surface: "쉬우니까" },
  { dict: "쉽다", klass: "p_irr", ending: "-(으)면", surface: "쉬우면" },
  { dict: "쉽다", klass: "p_irr", ending: "-(으)세요", surface: "쉬우세요" },
  { dict: "쉽다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "쉬울 거예요" },
  { dict: "어렵다", klass: "p_irr", ending: "-아/어요", surface: "어려워요" },
  { dict: "어렵다", klass: "p_irr", ending: "-았/었어요", surface: "어려웠어요" },
  { dict: "어렵다", klass: "p_irr", ending: "-(으)니까", surface: "어려우니까" },
  { dict: "어렵다", klass: "p_irr", ending: "-(으)면", surface: "어려우면" },
  { dict: "어렵다", klass: "p_irr", ending: "-(으)세요", surface: "어려우세요" },
  { dict: "어렵다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "어려울 거예요" },
  { dict: "가깝다", klass: "p_irr", ending: "-아/어요", surface: "가까워요" },
  { dict: "가깝다", klass: "p_irr", ending: "-았/었어요", surface: "가까웠어요" },
  { dict: "가깝다", klass: "p_irr", ending: "-(으)니까", surface: "가까우니까" },
  { dict: "가깝다", klass: "p_irr", ending: "-(으)면", surface: "가까우면" },
  { dict: "가깝다", klass: "p_irr", ending: "-(으)세요", surface: "가까우세요" },
  { dict: "가깝다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "가까울 거예요" },
  { dict: "아름답다", klass: "p_irr", ending: "-아/어요", surface: "아름다워요" },
  { dict: "아름답다", klass: "p_irr", ending: "-았/었어요", surface: "아름다웠어요" },
  { dict: "아름답다", klass: "p_irr", ending: "-(으)니까", surface: "아름다우니까" },
  { dict: "아름답다", klass: "p_irr", ending: "-(으)면", surface: "아름다우면" },
  { dict: "아름답다", klass: "p_irr", ending: "-(으)세요", surface: "아름다우세요" },
  { dict: "아름답다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "아름다울 거예요" },
  { dict: "맵다", klass: "p_irr", ending: "-아/어요", surface: "매워요" },
  { dict: "맵다", klass: "p_irr", ending: "-았/었어요", surface: "매웠어요" },
  { dict: "맵다", klass: "p_irr", ending: "-(으)니까", surface: "매우니까" },
  { dict: "맵다", klass: "p_irr", ending: "-(으)면", surface: "매우면" },
  { dict: "맵다", klass: "p_irr", ending: "-(으)세요", surface: "매우세요" },
  { dict: "맵다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "매울 거예요" },
  { dict: "굽다", klass: "p_irr", ending: "-아/어요", surface: "구워요" },
  { dict: "굽다", klass: "p_irr", ending: "-았/었어요", surface: "구웠어요" },
  { dict: "굽다", klass: "p_irr", ending: "-(으)니까", surface: "구우니까" },
  { dict: "굽다", klass: "p_irr", ending: "-(으)면", surface: "구우면" },
  { dict: "굽다", klass: "p_irr", ending: "-(으)세요", surface: "구우세요" },
  { dict: "굽다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "구울 거예요" },
  { dict: "눕다", klass: "p_irr", ending: "-아/어요", surface: "누워요" },
  { dict: "눕다", klass: "p_irr", ending: "-았/었어요", surface: "누웠어요" },
  { dict: "눕다", klass: "p_irr", ending: "-(으)니까", surface: "누우니까" },
  { dict: "눕다", klass: "p_irr", ending: "-(으)면", surface: "누우면" },
  { dict: "눕다", klass: "p_irr", ending: "-(으)세요", surface: "누우세요" },
  { dict: "눕다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "누울 거예요" },
  { dict: "돕다", klass: "p_irr", ending: "-아/어요", surface: "도와요" },
  { dict: "돕다", klass: "p_irr", ending: "-았/었어요", surface: "도왔어요" },
  { dict: "돕다", klass: "p_irr", ending: "-(으)니까", surface: "도우니까" },
  { dict: "돕다", klass: "p_irr", ending: "-(으)면", surface: "도우면" },
  { dict: "돕다", klass: "p_irr", ending: "-(으)세요", surface: "도우세요" },
  { dict: "돕다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "도울 거예요" },
  { dict: "곱다", klass: "p_irr", ending: "-아/어요", surface: "고와요" },
  { dict: "곱다", klass: "p_irr", ending: "-았/었어요", surface: "고왔어요" },
  { dict: "곱다", klass: "p_irr", ending: "-(으)니까", surface: "고우니까" },
  { dict: "곱다", klass: "p_irr", ending: "-(으)면", surface: "고우면" },
  { dict: "곱다", klass: "p_irr", ending: "-(으)세요", surface: "고우세요" },
  { dict: "곱다", klass: "p_irr", ending: "-(으)ㄹ 거예요", surface: "고울 거예요" },
  { dict: "좁다", klass: "regular", ending: "-아/어요", surface: "좁아요" },
  { dict: "좁다", klass: "regular", ending: "-았/었어요", surface: "좁았어요" },
  { dict: "좁다", klass: "regular", ending: "-(으)니까", surface: "좁으니까" },
  { dict: "좁다", klass: "regular", ending: "-(으)면", surface: "좁으면" },
  { dict: "좁다", klass: "regular", ending: "-(으)세요", surface: "좁으세요" },
  { dict: "좁다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "좁을 거예요" },
  { dict: "입다", klass: "regular", ending: "-아/어요", surface: "입어요" },
  { dict: "입다", klass: "regular", ending: "-았/었어요", surface: "입었어요" },
  { dict: "입다", klass: "regular", ending: "-(으)니까", surface: "입으니까" },
  { dict: "입다", klass: "regular", ending: "-(으)면", surface: "입으면" },
  { dict: "입다", klass: "regular", ending: "-(으)세요", surface: "입으세요" },
  { dict: "입다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "입을 거예요" },
  { dict: "잡다", klass: "regular", ending: "-아/어요", surface: "잡아요" },
  { dict: "잡다", klass: "regular", ending: "-았/었어요", surface: "잡았어요" },
  { dict: "잡다", klass: "regular", ending: "-(으)니까", surface: "잡으니까" },
  { dict: "잡다", klass: "regular", ending: "-(으)면", surface: "잡으면" },
  { dict: "잡다", klass: "regular", ending: "-(으)세요", surface: "잡으세요" },
  { dict: "잡다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "잡을 거예요" },
  { dict: "씹다", klass: "regular", ending: "-아/어요", surface: "씹어요" },
  { dict: "씹다", klass: "regular", ending: "-았/었어요", surface: "씹었어요" },
  { dict: "씹다", klass: "regular", ending: "-(으)니까", surface: "씹으니까" },
  { dict: "씹다", klass: "regular", ending: "-(으)면", surface: "씹으면" },
  { dict: "씹다", klass: "regular", ending: "-(으)세요", surface: "씹으세요" },
  { dict: "씹다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "씹을 거예요" },
  { dict: "뽑다", klass: "regular", ending: "-아/어요", surface: "뽑아요" },
  { dict: "뽑다", klass: "regular", ending: "-았/었어요", surface: "뽑았어요" },
  { dict: "뽑다", klass: "regular", ending: "-(으)니까", surface: "뽑으니까" },
  { dict: "뽑다", klass: "regular", ending: "-(으)면", surface: "뽑으면" },
  { dict: "뽑다", klass: "regular", ending: "-(으)세요", surface: "뽑으세요" },
  { dict: "뽑다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "뽑을 거예요" },
  { dict: "듣다", klass: "t_irr", ending: "-아/어요", surface: "들어요" },
  { dict: "듣다", klass: "t_irr", ending: "-았/었어요", surface: "들었어요" },
  { dict: "듣다", klass: "t_irr", ending: "-(으)니까", surface: "들으니까" },
  { dict: "듣다", klass: "t_irr", ending: "-(으)면", surface: "들으면" },
  { dict: "듣다", klass: "t_irr", ending: "-(으)세요", surface: "들으세요" },
  { dict: "듣다", klass: "t_irr", ending: "-(으)ㄹ 거예요", surface: "들을 거예요" },
  { dict: "걷다", klass: "t_irr", ending: "-아/어요", surface: "걸어요" },
  { dict: "걷다", klass: "t_irr", ending: "-았/었어요", surface: "걸었어요" },
  { dict: "걷다", klass: "t_irr", ending: "-(으)니까", surface: "걸으니까" },
  { dict: "걷다", klass: "t_irr", ending: "-(으)면", surface: "걸으면" },
  { dict: "걷다", klass: "t_irr", ending: "-(으)세요", surface: "걸으세요" },
  { dict: "걷다", klass: "t_irr", ending: "-(으)ㄹ 거예요", surface: "걸을 거예요" },
  { dict: "묻다", klass: "t_irr", ending: "-아/어요", surface: "물어요" },
  { dict: "묻다", klass: "t_irr", ending: "-았/었어요", surface: "물었어요" },
  { dict: "묻다", klass: "t_irr", ending: "-(으)니까", surface: "물으니까" },
  { dict: "묻다", klass: "t_irr", ending: "-(으)면", surface: "물으면" },
  { dict: "묻다", klass: "t_irr", ending: "-(으)세요", surface: "물으세요" },
  { dict: "묻다", klass: "t_irr", ending: "-(으)ㄹ 거예요", surface: "물을 거예요" },
  { dict: "싣다", klass: "t_irr", ending: "-아/어요", surface: "실어요" },
  { dict: "싣다", klass: "t_irr", ending: "-았/었어요", surface: "실었어요" },
  { dict: "싣다", klass: "t_irr", ending: "-(으)니까", surface: "실으니까" },
  { dict: "싣다", klass: "t_irr", ending: "-(으)면", surface: "실으면" },
  { dict: "싣다", klass: "t_irr", ending: "-(으)세요", surface: "실으세요" },
  { dict: "싣다", klass: "t_irr", ending: "-(으)ㄹ 거예요", surface: "실을 거예요" },
  { dict: "깨닫다", klass: "t_irr", ending: "-아/어요", surface: "깨달아요" },
  { dict: "깨닫다", klass: "t_irr", ending: "-았/었어요", surface: "깨달았어요" },
  { dict: "깨닫다", klass: "t_irr", ending: "-(으)니까", surface: "깨달으니까" },
  { dict: "깨닫다", klass: "t_irr", ending: "-(으)면", surface: "깨달으면" },
  { dict: "깨닫다", klass: "t_irr", ending: "-(으)세요", surface: "깨달으세요" },
  { dict: "깨닫다", klass: "t_irr", ending: "-(으)ㄹ 거예요", surface: "깨달을 거예요" },
  { dict: "닫다", klass: "regular", ending: "-아/어요", surface: "닫아요" },
  { dict: "닫다", klass: "regular", ending: "-았/었어요", surface: "닫았어요" },
  { dict: "닫다", klass: "regular", ending: "-(으)니까", surface: "닫으니까" },
  { dict: "닫다", klass: "regular", ending: "-(으)면", surface: "닫으면" },
  { dict: "닫다", klass: "regular", ending: "-(으)세요", surface: "닫으세요" },
  { dict: "닫다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "닫을 거예요" },
  { dict: "믿다", klass: "regular", ending: "-아/어요", surface: "믿어요" },
  { dict: "믿다", klass: "regular", ending: "-았/었어요", surface: "믿었어요" },
  { dict: "믿다", klass: "regular", ending: "-(으)니까", surface: "믿으니까" },
  { dict: "믿다", klass: "regular", ending: "-(으)면", surface: "믿으면" },
  { dict: "믿다", klass: "regular", ending: "-(으)세요", surface: "믿으세요" },
  { dict: "믿다", klass: "regular", ending: "-(으)ㄹ 거예요", surface: "믿을 거예요" },
  { dict: "바쁘다", klass: "eu_elision", ending: "-아/어요", surface: "바빠요" },
  { dict: "바쁘다", klass: "eu_elision", ending: "-았/었어요", surface: "바빴어요" },
  { dict: "바쁘다", klass: "eu_elision", ending: "-(으)니까", surface: "바쁘니까" },
  { dict: "예쁘다", klass: "eu_elision", ending: "-아/어요", surface: "예뻐요" },
  { dict: "예쁘다", klass: "eu_elision", ending: "-았/었어요", surface: "예뻤어요" },
  { dict: "예쁘다", klass: "eu_elision", ending: "-(으)니까", surface: "예쁘니까" },
  { dict: "쓰다", klass: "eu_elision", ending: "-아/어요", surface: "써요" },
  { dict: "쓰다", klass: "eu_elision", ending: "-았/었어요", surface: "썼어요" },
  { dict: "쓰다", klass: "eu_elision", ending: "-(으)니까", surface: "쓰니까" },
  { dict: "크다", klass: "eu_elision", ending: "-아/어요", surface: "커요" },
  { dict: "크다", klass: "eu_elision", ending: "-았/었어요", surface: "컸어요" },
  { dict: "크다", klass: "eu_elision", ending: "-(으)니까", surface: "크니까" },
  { dict: "아프다", klass: "eu_elision", ending: "-아/어요", surface: "아파요" },
  { dict: "아프다", klass: "eu_elision", ending: "-았/었어요", surface: "아팠어요" },
  { dict: "아프다", klass: "eu_elision", ending: "-(으)니까", surface: "아프니까" },
  { dict: "모으다", klass: "eu_elision", ending: "-아/어요", surface: "모아요" },
  { dict: "모으다", klass: "eu_elision", ending: "-았/었어요", surface: "모았어요" },
  { dict: "모으다", klass: "eu_elision", ending: "-(으)니까", surface: "모으니까" },
  { dict: "슬프다", klass: "eu_elision", ending: "-아/어요", surface: "슬퍼요" },
  { dict: "슬프다", klass: "eu_elision", ending: "-았/었어요", surface: "슬펐어요" },
  { dict: "슬프다", klass: "eu_elision", ending: "-(으)니까", surface: "슬프니까" },
  { dict: "기쁘다", klass: "eu_elision", ending: "-아/어요", surface: "기뻐요" },
  { dict: "기쁘다", klass: "eu_elision", ending: "-았/었어요", surface: "기뻤어요" },
  { dict: "기쁘다", klass: "eu_elision", ending: "-(으)니까", surface: "기쁘니까" },
  { dict: "고프다", klass: "eu_elision", ending: "-아/어요", surface: "고파요" },
  { dict: "고프다", klass: "eu_elision", ending: "-았/었어요", surface: "고팠어요" },
  { dict: "고프다", klass: "eu_elision", ending: "-(으)니까", surface: "고프니까" },
  { dict: "나쁘다", klass: "eu_elision", ending: "-아/어요", surface: "나빠요" },
  { dict: "나쁘다", klass: "eu_elision", ending: "-았/었어요", surface: "나빴어요" },
  { dict: "나쁘다", klass: "eu_elision", ending: "-(으)니까", surface: "나쁘니까" },
  { dict: "잠그다", klass: "eu_elision", ending: "-아/어요", surface: "잠가요" },
  { dict: "잠그다", klass: "eu_elision", ending: "-았/었어요", surface: "잠갔어요" },
  { dict: "잠그다", klass: "eu_elision", ending: "-(으)니까", surface: "잠그니까" },
  { dict: "담그다", klass: "eu_elision", ending: "-아/어요", surface: "담가요" },
  { dict: "담그다", klass: "eu_elision", ending: "-았/었어요", surface: "담갔어요" },
  { dict: "담그다", klass: "eu_elision", ending: "-(으)니까", surface: "담그니까" },
  { dict: "치르다", klass: "eu_elision", ending: "-아/어요", surface: "치러요" },
  { dict: "치르다", klass: "eu_elision", ending: "-았/었어요", surface: "치렀어요" },
  { dict: "치르다", klass: "eu_elision", ending: "-(으)니까", surface: "치르니까" },
  { dict: "따르다", klass: "eu_elision", ending: "-아/어요", surface: "따라요" },
  { dict: "따르다", klass: "eu_elision", ending: "-았/었어요", surface: "따랐어요" },
  { dict: "따르다", klass: "eu_elision", ending: "-(으)니까", surface: "따르니까" },
  { dict: "들르다", klass: "eu_elision", ending: "-아/어요", surface: "들러요" },
  { dict: "들르다", klass: "eu_elision", ending: "-았/었어요", surface: "들렀어요" },
  { dict: "들르다", klass: "eu_elision", ending: "-(으)니까", surface: "들르니까" },
  { dict: "끄다", klass: "eu_elision", ending: "-아/어요", surface: "꺼요" },
  { dict: "끄다", klass: "eu_elision", ending: "-았/었어요", surface: "껐어요" },
  { dict: "끄다", klass: "eu_elision", ending: "-(으)니까", surface: "끄니까" },
  { dict: "뜨다", klass: "eu_elision", ending: "-아/어요", surface: "떠요" },
  { dict: "뜨다", klass: "eu_elision", ending: "-았/었어요", surface: "떴어요" },
  { dict: "뜨다", klass: "eu_elision", ending: "-(으)니까", surface: "뜨니까" },
  { dict: "빠르다", klass: "reu_irr", ending: "-아/어요", surface: "빨라요" },
  { dict: "빠르다", klass: "reu_irr", ending: "-았/었어요", surface: "빨랐어요" },
  { dict: "빠르다", klass: "reu_irr", ending: "-(으)니까", surface: "빠르니까" },
  { dict: "부르다", klass: "reu_irr", ending: "-아/어요", surface: "불러요" },
  { dict: "부르다", klass: "reu_irr", ending: "-았/었어요", surface: "불렀어요" },
  { dict: "부르다", klass: "reu_irr", ending: "-(으)니까", surface: "부르니까" },
  { dict: "모르다", klass: "reu_irr", ending: "-아/어요", surface: "몰라요" },
  { dict: "모르다", klass: "reu_irr", ending: "-았/었어요", surface: "몰랐어요" },
  { dict: "모르다", klass: "reu_irr", ending: "-(으)니까", surface: "모르니까" },
  { dict: "다르다", klass: "reu_irr", ending: "-아/어요", surface: "달라요" },
  { dict: "다르다", klass: "reu_irr", ending: "-았/었어요", surface: "달랐어요" },
  { dict: "다르다", klass: "reu_irr", ending: "-(으)니까", surface: "다르니까" },
  { dict: "자르다", klass: "reu_irr", ending: "-아/어요", surface: "잘라요" },
  { dict: "자르다", klass: "reu_irr", ending: "-았/었어요", surface: "잘랐어요" },
  { dict: "자르다", klass: "reu_irr", ending: "-(으)니까", surface: "자르니까" },
  { dict: "흐르다", klass: "reu_irr", ending: "-아/어요", surface: "흘러요" },
  { dict: "흐르다", klass: "reu_irr", ending: "-았/었어요", surface: "흘렀어요" },
  { dict: "흐르다", klass: "reu_irr", ending: "-(으)니까", surface: "흐르니까" },
  { dict: "그렇다", klass: "h_irr", ending: "-아/어요", surface: "그래요" },
  { dict: "그렇다", klass: "h_irr", ending: "-았/었어요", surface: "그랬어요" },
  { dict: "그렇다", klass: "h_irr", ending: "-(으)니까", surface: "그러니까" },
  { dict: "그렇다", klass: "h_irr", ending: "-(으)면", surface: "그러면" },
  { dict: "빨갛다", klass: "h_irr", ending: "-아/어요", surface: "빨개요" },
  { dict: "빨갛다", klass: "h_irr", ending: "-았/었어요", surface: "빨갰어요" },
  { dict: "빨갛다", klass: "h_irr", ending: "-(으)니까", surface: "빨가니까" },
  { dict: "빨갛다", klass: "h_irr", ending: "-(으)면", surface: "빨가면" },
  { dict: "파랗다", klass: "h_irr", ending: "-아/어요", surface: "파래요" },
  { dict: "파랗다", klass: "h_irr", ending: "-았/었어요", surface: "파랬어요" },
  { dict: "파랗다", klass: "h_irr", ending: "-(으)니까", surface: "파라니까" },
  { dict: "파랗다", klass: "h_irr", ending: "-(으)면", surface: "파라면" },
  { dict: "어떻다", klass: "h_irr", ending: "-아/어요", surface: "어때요" },
  { dict: "어떻다", klass: "h_irr", ending: "-았/었어요", surface: "어땠어요" },
  { dict: "어떻다", klass: "h_irr", ending: "-(으)니까", surface: "어떠니까" },
  { dict: "어떻다", klass: "h_irr", ending: "-(으)면", surface: "어떠면" },
  { dict: "노랗다", klass: "h_irr", ending: "-아/어요", surface: "노래요" },
  { dict: "노랗다", klass: "h_irr", ending: "-았/었어요", surface: "노랬어요" },
  { dict: "노랗다", klass: "h_irr", ending: "-(으)니까", surface: "노라니까" },
  { dict: "노랗다", klass: "h_irr", ending: "-(으)면", surface: "노라면" },
  { dict: "하얗다", klass: "h_irr", ending: "-아/어요", surface: "하얘요" },
  { dict: "하얗다", klass: "h_irr", ending: "-았/었어요", surface: "하얬어요" },
  { dict: "하얗다", klass: "h_irr", ending: "-(으)니까", surface: "하야니까" },
  { dict: "하얗다", klass: "h_irr", ending: "-(으)면", surface: "하야면" },
  { dict: "이렇다", klass: "h_irr", ending: "-아/어요", surface: "이래요" },
  { dict: "이렇다", klass: "h_irr", ending: "-았/었어요", surface: "이랬어요" },
  { dict: "이렇다", klass: "h_irr", ending: "-(으)니까", surface: "이러니까" },
  { dict: "이렇다", klass: "h_irr", ending: "-(으)면", surface: "이러면" },
  { dict: "저렇다", klass: "h_irr", ending: "-아/어요", surface: "저래요" },
  { dict: "저렇다", klass: "h_irr", ending: "-았/었어요", surface: "저랬어요" },
  { dict: "저렇다", klass: "h_irr", ending: "-(으)니까", surface: "저러니까" },
  { dict: "저렇다", klass: "h_irr", ending: "-(으)면", surface: "저러면" },
  { dict: "까맣다", klass: "h_irr", ending: "-아/어요", surface: "까매요" },
  { dict: "까맣다", klass: "h_irr", ending: "-았/었어요", surface: "까맸어요" },
  { dict: "까맣다", klass: "h_irr", ending: "-(으)니까", surface: "까마니까" },
  { dict: "까맣다", klass: "h_irr", ending: "-(으)면", surface: "까마면" },
  { dict: "짓다", klass: "s_irr", ending: "-아/어요", surface: "지어요" },
  { dict: "짓다", klass: "s_irr", ending: "-았/었어요", surface: "지었어요" },
  { dict: "짓다", klass: "s_irr", ending: "-(으)니까", surface: "지으니까" },
  { dict: "낫다", klass: "s_irr", ending: "-아/어요", surface: "나아요" },
  { dict: "낫다", klass: "s_irr", ending: "-았/었어요", surface: "나았어요" },
  { dict: "낫다", klass: "s_irr", ending: "-(으)니까", surface: "나으니까" },
  { dict: "붓다", klass: "s_irr", ending: "-아/어요", surface: "부어요" },
  { dict: "붓다", klass: "s_irr", ending: "-았/었어요", surface: "부었어요" },
  { dict: "붓다", klass: "s_irr", ending: "-(으)니까", surface: "부으니까" },
  { dict: "잇다", klass: "s_irr", ending: "-아/어요", surface: "이어요" },
  { dict: "잇다", klass: "s_irr", ending: "-았/었어요", surface: "이었어요" },
  { dict: "잇다", klass: "s_irr", ending: "-(으)니까", surface: "이으니까" },
  { dict: "긋다", klass: "s_irr", ending: "-아/어요", surface: "그어요" },
  { dict: "긋다", klass: "s_irr", ending: "-(으)니까", surface: "그으니까" },
  { dict: "젓다", klass: "s_irr", ending: "-아/어요", surface: "저어요" },
  { dict: "젓다", klass: "s_irr", ending: "-(으)니까", surface: "저으니까" },
  { dict: "웃다", klass: "regular", ending: "-아/어요", surface: "웃어요" },
  { dict: "웃다", klass: "regular", ending: "-았/었어요", surface: "웃었어요" },
  { dict: "웃다", klass: "regular", ending: "-(으)니까", surface: "웃으니까" },
  { dict: "씻다", klass: "regular", ending: "-아/어요", surface: "씻어요" },
  { dict: "씻다", klass: "regular", ending: "-았/었어요", surface: "씻었어요" },
  { dict: "씻다", klass: "regular", ending: "-(으)니까", surface: "씻으니까" },
  { dict: "벗다", klass: "regular", ending: "-아/어요", surface: "벗어요" },
  { dict: "벗다", klass: "regular", ending: "-았/었어요", surface: "벗었어요" },
  { dict: "벗다", klass: "regular", ending: "-(으)니까", surface: "벗으니까" },
  { dict: "살다", klass: "l_drop", ending: "-아/어요", surface: "살아요" },
  { dict: "살다", klass: "l_drop", ending: "-았/었어요", surface: "살았어요" },
  { dict: "살다", klass: "l_drop", ending: "-(으)니까", surface: "사니까" },
  { dict: "살다", klass: "l_drop", ending: "-(으)면", surface: "살면" },
  { dict: "살다", klass: "l_drop", ending: "-(으)세요", surface: "사세요" },
  { dict: "살다", klass: "l_drop", ending: "-(으)ㄹ 거예요", surface: "살 거예요" },
  { dict: "알다", klass: "l_drop", ending: "-아/어요", surface: "알아요" },
  { dict: "알다", klass: "l_drop", ending: "-았/었어요", surface: "알았어요" },
  { dict: "알다", klass: "l_drop", ending: "-(으)니까", surface: "아니까" },
  { dict: "알다", klass: "l_drop", ending: "-(으)면", surface: "알면" },
  { dict: "알다", klass: "l_drop", ending: "-(으)세요", surface: "아세요" },
  { dict: "알다", klass: "l_drop", ending: "-(으)ㄹ 거예요", surface: "알 거예요" },
  { dict: "만들다", klass: "l_drop", ending: "-아/어요", surface: "만들어요" },
  { dict: "만들다", klass: "l_drop", ending: "-았/었어요", surface: "만들었어요" },
  { dict: "만들다", klass: "l_drop", ending: "-(으)니까", surface: "만드니까" },
  { dict: "만들다", klass: "l_drop", ending: "-(으)면", surface: "만들면" },
  { dict: "만들다", klass: "l_drop", ending: "-(으)세요", surface: "만드세요" },
  { dict: "만들다", klass: "l_drop", ending: "-(으)ㄹ 거예요", surface: "만들 거예요" },
  { dict: "놀다", klass: "l_drop", ending: "-아/어요", surface: "놀아요" },
  { dict: "놀다", klass: "l_drop", ending: "-았/었어요", surface: "놀았어요" },
  { dict: "놀다", klass: "l_drop", ending: "-(으)니까", surface: "노니까" },
  { dict: "놀다", klass: "l_drop", ending: "-(으)면", surface: "놀면" },
  { dict: "놀다", klass: "l_drop", ending: "-(으)세요", surface: "노세요" },
  { dict: "놀다", klass: "l_drop", ending: "-(으)ㄹ 거예요", surface: "놀 거예요" },
  { dict: "멀다", klass: "l_drop", ending: "-아/어요", surface: "멀어요" },
  { dict: "멀다", klass: "l_drop", ending: "-았/었어요", surface: "멀었어요" },
  { dict: "멀다", klass: "l_drop", ending: "-(으)니까", surface: "머니까" },
  { dict: "멀다", klass: "l_drop", ending: "-(으)면", surface: "멀면" },
  { dict: "멀다", klass: "l_drop", ending: "-(으)세요", surface: "머세요" },
  { dict: "멀다", klass: "l_drop", ending: "-(으)ㄹ 거예요", surface: "멀 거예요" },
]

export const GOLDEN_PARTICLES: { noun: string; particle: Particle; surface: string }[] = [
  { noun: "책", particle: "은/는", surface: "책은" },
  { noun: "책", particle: "이/가", surface: "책이" },
  { noun: "책", particle: "을/를", surface: "책을" },
  { noun: "책", particle: "와/과", surface: "책과" },
  { noun: "책", particle: "(으)로", surface: "책으로" },
  { noun: "책", particle: "(이)나", surface: "책이나" },
  { noun: "사과", particle: "은/는", surface: "사과는" },
  { noun: "사과", particle: "이/가", surface: "사과가" },
  { noun: "사과", particle: "을/를", surface: "사과를" },
  { noun: "사과", particle: "와/과", surface: "사과와" },
  { noun: "사과", particle: "(으)로", surface: "사과로" },
  { noun: "사과", particle: "(이)나", surface: "사과나" },
  { noun: "학생", particle: "은/는", surface: "학생은" },
  { noun: "학생", particle: "이/가", surface: "학생이" },
  { noun: "학생", particle: "을/를", surface: "학생을" },
  { noun: "학생", particle: "와/과", surface: "학생과" },
  { noun: "학생", particle: "(으)로", surface: "학생으로" },
  { noun: "학생", particle: "(이)나", surface: "학생이나" },
  { noun: "친구", particle: "은/는", surface: "친구는" },
  { noun: "친구", particle: "이/가", surface: "친구가" },
  { noun: "친구", particle: "을/를", surface: "친구를" },
  { noun: "친구", particle: "와/과", surface: "친구와" },
  { noun: "친구", particle: "(으)로", surface: "친구로" },
  { noun: "친구", particle: "(이)나", surface: "친구나" },
  { noun: "서울", particle: "은/는", surface: "서울은" },
  { noun: "서울", particle: "이/가", surface: "서울이" },
  { noun: "서울", particle: "을/를", surface: "서울을" },
  { noun: "서울", particle: "와/과", surface: "서울과" },
  { noun: "서울", particle: "(으)로", surface: "서울로" },
  { noun: "서울", particle: "(이)나", surface: "서울이나" },
  { noun: "물", particle: "은/는", surface: "물은" },
  { noun: "물", particle: "이/가", surface: "물이" },
  { noun: "물", particle: "을/를", surface: "물을" },
  { noun: "물", particle: "와/과", surface: "물과" },
  { noun: "물", particle: "(으)로", surface: "물로" },
  { noun: "물", particle: "(이)나", surface: "물이나" },
  { noun: "집", particle: "은/는", surface: "집은" },
  { noun: "집", particle: "이/가", surface: "집이" },
  { noun: "집", particle: "을/를", surface: "집을" },
  { noun: "집", particle: "와/과", surface: "집과" },
  { noun: "집", particle: "(으)로", surface: "집으로" },
  { noun: "집", particle: "(이)나", surface: "집이나" },
  { noun: "나무", particle: "은/는", surface: "나무는" },
  { noun: "나무", particle: "이/가", surface: "나무가" },
  { noun: "나무", particle: "을/를", surface: "나무를" },
  { noun: "나무", particle: "와/과", surface: "나무와" },
  { noun: "나무", particle: "(으)로", surface: "나무로" },
  { noun: "나무", particle: "(이)나", surface: "나무나" },
  { noun: "펜", particle: "은/는", surface: "펜은" },
  { noun: "펜", particle: "이/가", surface: "펜이" },
  { noun: "펜", particle: "을/를", surface: "펜을" },
  { noun: "펜", particle: "와/과", surface: "펜과" },
  { noun: "펜", particle: "(으)로", surface: "펜으로" },
  { noun: "펜", particle: "(이)나", surface: "펜이나" },
  { noun: "의자", particle: "은/는", surface: "의자는" },
  { noun: "의자", particle: "이/가", surface: "의자가" },
  { noun: "의자", particle: "을/를", surface: "의자를" },
  { noun: "의자", particle: "와/과", surface: "의자와" },
  { noun: "의자", particle: "(으)로", surface: "의자로" },
  { noun: "의자", particle: "(이)나", surface: "의자나" },
]
