// app/seed/register-transform/honor-extra.ts
import type { RegisterItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * Additional subject/object honorification items (-(으)시-, 께서/께, suppletion +
 * honorific nouns), extending HONOR_ITEMS in honor.ts. The speaker (저/제가) is
 * NEVER self-honorified; the speaker's own verb is humbled (드리다/여쭙다/뵙다), not raised.
 * Drafted + Korean-lens adversarially verified. Korean wife native review = documented final gate.
 */

export const HONOR_EXTRA: RegisterItem[] = [
  {
    source: '손님이 커피를 마셔요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '손님께서 커피를 드세요.',
    distractors: [
      '손님께서 커피를 마셔요.',
      '손님이 커피를 드세요.',
      '손님께서 커피를 마시세요.',
    ],
    trans: L(
      'The guest is drinking coffee.',
      'El cliente está tomando café.',
      'Le client boit du café.',
      'O cliente está tomando café.',
      'ลูกค้ากำลังดื่มกาแฟ',
      'Tamu sedang minum kopi.',
      'Khách đang uống cà phê.',
      'お客様がコーヒーを召し上がります。',
    ),
    why: L(
      'Subject honor: 이/가 → 께서, and 마시다 shares the suppletive honorific 드시다 → 드세요 (not 마시세요, not plain 마셔요).',
      'Honor del sujeto: 이/가 → 께서, y 마시다 comparte el honorífico supletivo 드시다 → 드세요 (no 마시세요, ni el llano 마셔요).',
      'Honneur du sujet : 이/가 → 께서, et 마시다 partage le suppletif honorifique 드시다 → 드세요 (pas 마시세요, ni le neutre 마셔요).',
      'Honra do sujeito: 이/가 → 께서, e 마시다 compartilha o honorífico supletivo 드시다 → 드세요 (não 마시세요, nem o neutro 마셔요).',
      'ยกย่องประธาน: 이/가 → 께서 และ 마시다 ใช้รูปยกย่องพิเศษร่วม 드시다 → 드세요 (ไม่ใช่ 마시세요 หรือ 마셔요 ธรรมดา)',
      'Honor subjek: 이/가 → 께서, dan 마시다 berbagi honorifik supletif 드시다 → 드세요 (bukan 마시세요, bukan 마셔요 biasa).',
      'Tôn kính chủ ngữ: 이/가 → 께서, và 마시다 dùng chung dạng kính ngữ thay thế 드시다 → 드세요 (không phải 마시세요, không phải 마셔요 thường).',
      '主体尊敬：이/가 → 께서、마시다も補充法の尊敬語드시다 → 드세요（마시세요でも素の마셔요でもない）。',
    ),
  },
  {
    source: '할머니가 안방에서 자요.',
    mode: 'honor',
    target: 'formal',
    set: 'verb',
    answer: '할머니께서 안방에서 주무십니다.',
    distractors: [
      '할머니께서 안방에서 자십니다.',
      '할머니가 안방에서 주무십니다.',
      '할머니께서 안방에서 주무세요.',
    ],
    trans: L(
      'Grandmother is sleeping in the master bedroom.',
      'La abuela está durmiendo en el dormitorio principal.',
      'Grand-mère dort dans la chambre principale.',
      'A avó está dormindo no quarto principal.',
      'คุณยายกำลังนอนอยู่ในห้องนอนใหญ่',
      'Nenek sedang tidur di kamar utama.',
      'Bà đang ngủ trong phòng ngủ chính.',
      'おばあさんが主寝室でお休みになります。',
    ),
    why: L(
      '합쇼체 subject honor: 이/가 → 께서, and 자다 has the suppletive 주무시다 → 주무십니다 (not 자십니다; 주무세요 is 해요체, wrong level for formal).',
      'Honor del sujeto en 합쇼체: 이/가 → 께서, y 자다 tiene el supletivo 주무시다 → 주무십니다 (no 자십니다; 주무세요 es 해요체, nivel incorrecto).',
      'Honneur du sujet en 합쇼체 : 이/가 → 께서, et 자다 a le suppletif 주무시다 → 주무십니다 (pas 자십니다 ; 주무세요 est du 해요체, mauvais niveau).',
      'Honra do sujeito em 합쇼체: 이/가 → 께서, e 자다 tem o supletivo 주무시다 → 주무십니다 (não 자십니다; 주무세요 é 해요체, nível errado).',
      'ยกย่องประธานแบบ 합쇼체: 이/가 → 께서 และ 자다 มีรูปพิเศษ 주무시다 → 주무십니다 (ไม่ใช่ 자십니다; 주무세요 เป็น 해요체 ระดับผิด)',
      'Honor subjek 합쇼체: 이/가 → 께서, dan 자다 punya supletif 주무시다 → 주무십니다 (bukan 자십니다; 주무세요 itu 해요체, tingkat salah).',
      'Tôn kính chủ ngữ thể 합쇼체: 이/가 → 께서, và 자다 có dạng thay thế 주무시다 → 주무십니다 (không phải 자십니다; 주무세요 là 해요체, sai cấp độ).',
      '합쇼체の主体尊敬：이/가 → 께서、자다は補充法の주무시다 → 주무십니다（자십니다ではない。주무세요は해요체で待遇レベルが誤り）。',
    ),
  },
  {
    source: '부모님이 거실에 있어요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '부모님께서 거실에 계세요.',
    distractors: [
      '부모님께서 거실에 있으세요.',
      '부모님이 거실에 계세요.',
      '부모님께서 거실에 계셔.',
    ],
    trans: L(
      'My parents are in the living room.',
      'Mis padres están en la sala.',
      'Mes parents sont dans le salon.',
      'Meus pais estão na sala de estar.',
      'พ่อแม่อยู่ในห้องนั่งเล่น',
      'Orang tua saya ada di ruang tamu.',
      'Bố mẹ tôi đang ở phòng khách.',
      'ご両親が居間にいらっしゃいます。',
    ),
    why: L(
      'Subject honor: 이/가 → 께서, and existential 있다 has the suppletive 계시다 → 계세요 (not 있으세요; 계셔 is 반말, wrong level for polite).',
      'Honor del sujeto: 이/가 → 께서, y el existencial 있다 tiene el supletivo 계시다 → 계세요 (no 있으세요; 계셔 es 반말, nivel incorrecto).',
      "Honneur du sujet : 이/가 → 께서, et l'existentiel 있다 a le suppletif 계시다 → 계세요 (pas 있으세요 ; 계셔 est du 반말, mauvais niveau).",
      'Honra do sujeito: 이/가 → 께서, e o existencial 있다 tem o supletivo 계시다 → 계세요 (não 있으세요; 계셔 é 반말, nível errado).',
      'ยกย่องประธาน: 이/가 → 께서 และ 있다 (มีอยู่) มีรูปพิเศษ 계시다 → 계세요 (ไม่ใช่ 있으세요; 계셔 เป็น 반말 ระดับผิด)',
      'Honor subjek: 이/가 → 께서, dan 있다 (keberadaan) punya supletif 계시다 → 계세요 (bukan 있으세요; 계셔 itu 반말, tingkat salah).',
      'Tôn kính chủ ngữ: 이/가 → 께서, và 있다 (tồn tại) có dạng thay thế 계시다 → 계세요 (không phải 있으세요; 계셔 là 반말, sai cấp độ).',
      '主体尊敬：이/가 → 께서、存在の있다は補充法の계시다 → 계세요（있으세요ではない。계셔は반말で待遇レベルが誤り）。',
    ),
  },
  {
    source: '회장님이 직원들에게 말해요.',
    mode: 'honor',
    target: 'formal',
    set: 'verb',
    answer: '회장님께서 직원들에게 말씀하십니다.',
    distractors: [
      '회장님께서 직원들에게 말하십니다.',
      '회장님이 직원들에게 말씀하십니다.',
      '회장님께서 직원들에게 말씀하세요.',
    ],
    trans: L(
      'The chairman speaks to the employees.',
      'El presidente habla a los empleados.',
      'Le président parle aux employés.',
      'O presidente fala com os funcionários.',
      'ท่านประธานบริษัทพูดกับพนักงาน',
      'Ketua berbicara kepada para karyawan.',
      'Chủ tịch nói chuyện với nhân viên.',
      '会長が社員たちにお話しになります。',
    ),
    why: L(
      '합쇼체 subject honor: 이/가 → 께서, and 말하다 has the suppletive 말씀하시다 → 말씀하십니다 (not 말하십니다; 말씀하세요 is 해요체, wrong level for formal).',
      'Honor del sujeto en 합쇼체: 이/가 → 께서, y 말하다 tiene el supletivo 말씀하시다 → 말씀하십니다 (no 말하십니다; 말씀하세요 es 해요체, nivel incorrecto).',
      'Honneur du sujet en 합쇼체 : 이/가 → 께서, et 말하다 a le suppletif 말씀하시다 → 말씀하십니다 (pas 말하십니다 ; 말씀하세요 est du 해요체, mauvais niveau).',
      'Honra do sujeito em 합쇼체: 이/가 → 께서, e 말하다 tem o supletivo 말씀하시다 → 말씀하십니다 (não 말하십니다; 말씀하세요 é 해요체, nível errado).',
      'ยกย่องประธานแบบ 합쇼체: 이/가 → 께서 และ 말하다 มีรูปพิเศษ 말씀하시다 → 말씀하십니다 (ไม่ใช่ 말하십니다; 말씀하세요 เป็น 해요체 ระดับผิด)',
      'Honor subjek 합쇼체: 이/가 → 께서, dan 말하다 punya supletif 말씀하시다 → 말씀하십니다 (bukan 말하십니다; 말씀하세요 itu 해요체, tingkat salah).',
      'Tôn kính chủ ngữ thể 합쇼체: 이/가 → 께서, và 말하다 có dạng thay thế 말씀하시다 → 말씀하십니다 (không phải 말하십니다; 말씀하세요 là 해요체, sai cấp độ).',
      '합쇼체の主体尊敬：이/가 → 께서、말하다は補充法の말씀하시다 → 말씀하십니다（말하십니다ではない。말씀하세요は해요체で待遇レベルが誤り）。',
    ),
  },
  {
    source: '제가 부모님에게 용돈을 줘요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '제가 부모님께 용돈을 드려요.',
    distractors: [
      '제가 부모님께 용돈을 드리세요.',
      '제가 부모님에게 용돈을 드려요.',
      '제가 부모님께 용돈을 줘요.',
    ],
    trans: L(
      'I give my parents an allowance.',
      'Les doy una mesada a mis padres.',
      'Je donne de l\'argent de poche à mes parents.',
      'Eu dou uma mesada aos meus pais.',
      'ฉันให้เงินค่าขนมแก่พ่อแม่',
      'Saya memberi orang tua saya uang saku.',
      'Tôi đưa tiền tiêu vặt cho bố mẹ.',
      '私が両親にお小遣いを差し上げます。',
    ),
    why: L(
      'Object honor (겸양): toward a respected object 에게 → 께 and humble 주다 → 드리다; never put -(으)시- on your own humble verb (드리세요 wrong) — 저 is never self-honorified.',
      'Honor del objeto (겸양): hacia un objeto respetado 에게 → 께 y humilde 주다 → 드리다; nunca pongas -(으)시- en tu propio verbo humilde (드리세요 incorrecto) — 저 nunca se autohonorifica.',
      "Honneur de l'objet (겸양) : envers un objet respecté 에게 → 께 et humble 주다 → 드리다 ; ne jamais mettre -(으)시- sur son propre verbe humble (드리세요 faux) — 저 ne s'honore jamais soi-même.",
      'Honra do objeto (겸양): para um objeto respeitado 에게 → 께 e humilde 주다 → 드리다; nunca ponha -(으)시- no seu próprio verbo humilde (드리세요 errado) — 저 nunca se auto-honra.',
      'ยกย่องกรรม (겸양): ต่อผู้ที่เคารพ 에게 → 께 และรูปถ่อมตน 주다 → 드리다 อย่าใส่ -(으)시- ในกริยาถ่อมตนของตัวเอง (드리세요 ผิด) — 저 ไม่ยกย่องตัวเอง',
      'Honor objek (겸양): kepada objek terhormat 에게 → 께 dan bentuk rendah hati 주다 → 드리다; jangan beri -(으)시- pada verba rendah hati sendiri (드리세요 salah) — 저 tak pernah dihormati sendiri.',
      'Khiêm nhường với tân ngữ (겸양): hướng tới người được tôn kính 에게 → 께 và dạng khiêm 주다 → 드리다; không gắn -(으)시- vào động từ khiêm của chính mình (드리세요 sai) — 저 không tự tôn kính.',
      '客体尊敬（겸양）：敬う相手へ에게 → 께、謙譲の주다 → 드리다。自分の謙譲語に-(으)시-は付けない（드리세요は誤り）。저は自分を高めない。',
    ),
  },
  {
    source: '어머니가 밥을 차려요.',
    mode: 'honor',
    target: 'polite',
    set: 'noun',
    answer: '어머니께서 진지를 차리세요.',
    distractors: [
      '어머니께서 밥을 차리세요.',
      '어머니께서 말씀을 차리세요.',
      '어머니가 진지를 차려요.',
    ],
    trans: L(
      'Mother is setting the table (preparing the meal).',
      'Mamá está preparando la comida.',
      'Maman prépare le repas.',
      'Mamãe está preparando a refeição.',
      'คุณแม่กำลังจัดเตรียมอาหาร',
      'Ibu sedang menyiapkan makanan.',
      'Mẹ đang dọn bữa cơm.',
      'お母さんがお食事の用意をなさいます。',
    ),
    why: L(
      '밥→진지 (honorific noun) + 께서 + 차리세요 (-(으)시-); keeping 밥, swapping to 말씀(wrong noun = words), or 차려요 without 께서/-(으)시- are all wrong.',
      '밥→진지 (sustantivo honorífico) + 께서 + 차리세요 (-(으)시-); mantener 밥, cambiar a 말씀(sustantivo erróneo = palabras) o 차려요 sin 께서/-(으)시- son errores.',
      '밥→진지 (nom honorifique) + 께서 + 차리세요 (-(으)시-) ; garder 밥, mettre 말씀(mauvais nom = paroles) ou 차려요 sans 께서/-(으)시- sont fautifs.',
      '밥→진지 (substantivo honorífico) + 께서 + 차리세요 (-(으)시-); manter 밥, trocar por 말씀(substantivo errado = palavras) ou 차려요 sem 께서/-(으)시- estão errados.',
      '밥→진지 (คำนามยกย่อง) + 께서 + 차리세요 (-(으)시-); การคง 밥, เปลี่ยนเป็น 말씀(คำนามผิด = คำพูด) หรือ 차려요 ที่ไม่มี 께서/-(으)시- ผิดทั้งหมด',
      '밥→진지 (nomina hormat) + 께서 + 차리세요 (-(으)시-); mempertahankan 밥, mengganti ke 말씀(nomina salah = perkataan), atau 차려요 tanpa 께서/-(으)시- salah.',
      '밥→진지 (danh từ kính ngữ) + 께서 + 차리세요 (-(으)시-); giữ 밥, đổi sang 말씀(danh từ sai = lời nói) hay 차려요 thiếu 께서/-(으)시- đều sai.',
      '밥→진지（尊敬名詞）+ 께서 + 차리세요 (-(으)시-)；밥 のまま・말씀(誤った名詞=言葉)への置換・께서/-(으)시- なしの 차려요 は誤り。',
    ),
  },
  {
    source: '사장님이 나이가 어떻게 돼요?',
    mode: 'honor',
    target: 'polite',
    set: 'noun',
    answer: '사장님께서 연세가 어떻게 되세요?',
    distractors: [
      '사장님께서 나이가 어떻게 되세요?',
      '사장님께서 성함이 어떻게 되세요?',
      '사장님이 연세가 어떻게 돼요?',
    ],
    trans: L(
      'Boss, how old are you?',
      'Jefe, ¿qué edad tiene usted?',
      'Patron, quel âge avez-vous ?',
      'Chefe, qual é a sua idade?',
      'ท่านประธาน อายุเท่าไหร่ครับ/คะ',
      'Bos, berapa usia Anda?',
      'Thưa giám đốc, ngài bao nhiêu tuổi ạ?',
      '社長、お年はおいくつですか？',
    ),
    why: L(
      '나이→연세 + 께서 + 되세요 (-(으)시-); keeping 나이, swapping to 성함(wrong noun = name), or 돼요 without 께서/-(으)시- are wrong.',
      '나이→연세 + 께서 + 되세요 (-(으)시-); mantener 나이, cambiar a 성함(sustantivo erróneo = nombre) o 돼요 sin 께서/-(으)시- son errores.',
      '나이→연세 + 께서 + 되세요 (-(으)시-) ; garder 나이, mettre 성함(mauvais nom = nom propre) ou 돼요 sans 께서/-(으)시- sont fautifs.',
      '나이→연세 + 께서 + 되세요 (-(으)시-); manter 나이, trocar por 성함(substantivo errado = nome) ou 돼요 sem 께서/-(으)시- estão errados.',
      '나이→연세 + 께서 + 되세요 (-(으)시-); การคง 나이, เปลี่ยนเป็น 성함(คำนามผิด = ชื่อ) หรือ 돼요 ที่ไม่มี 께서/-(으)시- ผิด',
      '나이→연세 + 께서 + 되세요 (-(으)시-); mempertahankan 나이, mengganti ke 성함(nomina salah = nama), atau 돼요 tanpa 께서/-(으)시- salah.',
      '나이→연세 + 께서 + 되세요 (-(으)시-); giữ 나이, đổi sang 성함(danh từ sai = họ tên) hay 돼요 thiếu 께서/-(으)시- đều sai.',
      '나이→연세 + 께서 + 되세요 (-(으)시-)；나이 のまま・성함(誤った名詞=氏名)への置換・께서/-(으)시- なしの 돼요 は誤り。',
    ),
  },
  {
    source: '손님 이름이 어떻게 돼요?',
    mode: 'honor',
    target: 'polite',
    set: 'noun',
    answer: '손님 성함이 어떻게 되세요?',
    distractors: [
      '손님 이름이 어떻게 되세요?',
      '손님 연세가 어떻게 되세요?',
      '손님 성함이 어떻게 돼요?',
    ],
    trans: L(
      'May I have your name, sir/madam?',
      'Cliente, ¿cuál es su nombre?',
      'Cher client, quel est votre nom ?',
      'Cliente, qual é o seu nome?',
      'คุณลูกค้า ชื่ออะไรครับ/คะ',
      'Bapak/Ibu, siapa nama Anda?',
      'Thưa quý khách, tên của quý khách là gì ạ?',
      'お客様、お名前は何とおっしゃいますか？',
    ),
    why: L(
      '이름→성함 + 되세요 (-(으)시-); plain 이름, 연세(wrong noun = age), and 성함이 돼요 (no honorific verb) are all wrong.',
      '이름→성함 + 되세요 (-(으)시-); 이름 simple, 연세(sustantivo erróneo = edad) y 성함이 돼요 (sin verbo honorífico) son errores.',
      '이름→성함 + 되세요 (-(으)시-) ; 이름 ordinaire, 연세(mauvais nom = âge) et 성함이 돼요 (sans verbe honorifique) sont fautifs.',
      '이름→성함 + 되세요 (-(으)시-); 이름 simples, 연세(substantivo errado = idade) e 성함이 돼요 (sem verbo honorífico) estão errados.',
      '이름→성함 + 되세요 (-(으)시-); 이름 ธรรมดา, 연세(คำนามผิด = อายุ) และ 성함이 돼요 (ไม่มีกริยายกย่อง) ผิดทั้งหมด',
      '이름→성함 + 되세요 (-(으)시-); 이름 biasa, 연세(nomina salah = usia), dan 성함이 돼요 (tanpa verba hormat) salah.',
      '이름→성함 + 되세요 (-(으)시-); 이름 thường, 연세(danh từ sai = tuổi) và 성함이 돼요 (không có động từ kính ngữ) đều sai.',
      '이름→성함 + 되세요 (-(으)시-)；素の 이름、연세(誤った名詞=年齢)、성함이 돼요(尊敬動詞なし)はすべて誤り。',
    ),
  },
  {
    source: '저는 할아버지한테 편지를 줬어요.',
    mode: 'honor',
    target: 'polite',
    set: 'particle',
    answer: '저는 할아버지께 편지를 드렸어요.',
    distractors: [
      '저는 할아버지한테 편지를 드렸어요.',
      '저는 할아버지께 편지를 줬어요.',
      '저는 할아버지께서 편지를 드렸어요.',
    ],
    trans: L(
      'I gave my grandfather a letter.',
      'Le di una carta a mi abuelo.',
      'J\'ai donné une lettre à mon grand-père.',
      'Eu dei uma carta ao meu avô.',
      'ฉันให้จดหมายแก่คุณปู่',
      'Saya memberi kakek sebuah surat.',
      'Tôi đã đưa cho ông một lá thư.',
      '私は祖父に手紙を差し上げました。',
    ),
    why: L(
      'Object humbling (객체높임/겸양): 한테 → 께 pairs with humble 주다 → 드리다. Keeping 한테, keeping plain 주다, or using subject-marker 께서 on the recipient are all wrong.',
      'Humillación del objeto (객체높임/겸양): 한테 → 께 va con humilde 주다 → 드리다. Mantener 한테, mantener 주다 simple o usar 께서 (sujeto) en el receptor son errores.',
      "Humilité envers l'objet (객체높임/겸양) : 한테 → 께 va avec humble 주다 → 드리다. Garder 한테, garder 주다 ordinaire ou mettre 께서 (sujet) sur le destinataire sont faux.",
      'Humildade ao objeto (객체높임/겸양): 한테 → 께 combina com humilde 주다 → 드리다. Manter 한테, manter 주다 comum ou usar 께서 (sujeito) no destinatário estão errados.',
      'ถ่อมตนต่อกรรม (객체높임/겸양): 한테 → 께 ใช้คู่กับรูปถ่อมตน 주다 → 드리다 การคง 한테 คง 주다 ธรรมดา หรือใช้ 께서 (รูปประธาน) กับผู้รับ ล้วนผิด',
      'Merendah pada objek (객체높임/겸양): 한테 → 께 berpasangan dengan 주다 → 드리다 rendah hati. Tetap 한테, tetap 주다 biasa, atau pakai 께서 (subjek) pada penerima semuanya salah.',
      'Khiêm nhường với tân ngữ (객체높임/겸양): 한테 → 께 đi với dạng khiêm 주다 → 드리다. Giữ 한테, giữ 주다 thường, hoặc dùng 께서 (chủ ngữ) cho người nhận đều sai.',
      '客体の謙譲（객체높임/겸양）：한테 → 께は謙譲の주다 → 드리다と対応。한테のまま、普通の주다のまま、受け手に主語標識께서を付けるのはいずれも誤り。',
    ),
  },
  {
    source: '어머니가 시장에서 과일을 사요.',
    mode: 'honor',
    target: 'polite',
    set: 'particle',
    answer: '어머니께서 시장에서 과일을 사세요.',
    distractors: [
      '어머니가 시장에서 과일을 사세요.',
      '어머니께 시장에서 과일을 사세요.',
      '어머니께서 시장에서 과일을 사요.',
    ],
    trans: L(
      'Mother is buying fruit at the market.',
      'Mamá está comprando fruta en el mercado.',
      'Maman achète des fruits au marché.',
      'Mamãe está comprando frutas no mercado.',
      'คุณแม่กำลังซื้อผลไม้ที่ตลาด',
      'Ibu sedang membeli buah di pasar.',
      'Mẹ đang mua trái cây ở chợ.',
      'お母さんが市場で果物をお買いになります。',
    ),
    why: L(
      'Subject honor (주체높임): 이/가 → 께서 pairs with -(으)시- → 사세요. Keeping 가, swapping to dative 께, or 께서 without 시 are all wrong.',
      'Honor al sujeto (주체높임): 이/가 → 께서 va con -(으)시- → 사세요. Mantener 가, cambiar al dativo 께 o 께서 sin 시 son errores.',
      'Honneur du sujet (주체높임) : 이/가 → 께서 va avec -(으)시- → 사세요. Garder 가, passer au datif 께 ou 께서 sans 시 sont faux.',
      'Honra ao sujeito (주체높임): 이/가 → 께서 combina com -(으)시- → 사세요. Manter 가, trocar pelo dativo 께 ou 께서 sem 시 estão errados.',
      'ยกย่องประธาน (주체높임): 이/가 → 께서 ใช้คู่กับ -(으)시- → 사세요 การคง 가 เปลี่ยนเป็น 께 (รูปกรรมรอง) หรือ 께서 ที่ไม่มี 시 ล้วนผิด',
      'Hormat subjek (주체높임): 이/가 → 께서 berpasangan dengan -(으)시- → 사세요. Tetap 가, ganti ke datif 께, atau 께서 tanpa 시 semuanya salah.',
      'Tôn kính chủ ngữ (주체높임): 이/가 → 께서 đi với -(으)시- → 사세요. Giữ 가, đổi sang 께 (tặng cách), hoặc 께서 mà thiếu 시 đều sai.',
      '主語の尊敬（주체높임）：이/가 → 께서は-(으)시- → 사세요と対応。가のまま、与格の께に替える、시の無い께서はいずれも誤り。',
    ),
  },
  {
    source: '선생님이 책을 읽어요.',
    mode: 'honor',
    target: 'polite',
    set: 'si',
    answer: '선생님께서 책을 읽으세요.',
    distractors: [
      '선생님이 책을 읽어요.',
      '선생님께서 책을 읽세요.',
      '선생님께서 책을 읽으십니다.',
    ],
    trans: L(
      'The teacher reads a book.',
      'El profesor lee un libro.',
      'Le professeur lit un livre.',
      'O professor lê um livro.',
      'คุณครูอ่านหนังสือ',
      'Guru membaca buku.',
      'Thầy giáo đọc sách.',
      '先生が本をお読みになります。',
    ),
    why: L(
      '읽다 is regular: 이/가 → 께서 and the consonant stem takes epenthetic -(으)시- → 읽으세요 (읽세요 drops the required 으; plain 읽어요 has no 시; 읽으십니다 is 합쇼체, wrong level for polite).',
      '읽다 es regular: 이/가 → 께서 y la raíz consonántica toma la -(으)시- epentética → 읽으세요 (읽세요 omite el 으 obligatorio; el llano 읽어요 no lleva 시; 읽으십니다 es 합쇼체, nivel incorrecto).',
      "읽다 est régulier : 이/가 → 께서 et le radical consonantique prend le -(으)시- épenthétique → 읽으세요 (읽세요 omet le 으 requis ; le neutre 읽어요 n'a pas de 시 ; 읽으십니다 est du 합쇼체, mauvais niveau).",
      '읽다 é regular: 이/가 → 께서 e o radical consonantal recebe o -(으)시- epentético → 읽으세요 (읽세요 omite o 으 obrigatório; o neutro 읽어요 não tem 시; 읽으십니다 é 합쇼체, nível errado).',
      '읽다 ปกติ: 이/가 → 께서 และก้านพยัญชนะเติม -(으)시- → 읽으세요 (읽세요 ตัด 으 ที่ต้องมีออก; 읽어요 ธรรมดาไม่มี 시; 읽으십니다 เป็น 합쇼체 ระดับผิด)',
      '읽다 reguler: 이/가 → 께서 dan batang berkonsonan memakai -(으)시- epentetik → 읽으세요 (읽세요 menghapus 으 yang wajib; 읽어요 biasa tanpa 시; 읽으십니다 itu 합쇼체, tingkat salah).',
      '읽다 thường: 이/가 → 께서 và thân kết thúc phụ âm thêm -(으)시- → 읽으세요 (읽세요 bỏ mất 으 bắt buộc; 읽어요 thường không có 시; 읽으십니다 là 합쇼체, sai cấp độ).',
      '읽다は規則：이/가 → 께서、子音語幹は媒介母音付きの-(으)시-で읽으세요（읽세요は必要な으の脱落、素の읽어요には시が無い。읽으십니다は합쇼체で待遇レベルが誤り）。',
    ),
  },
  {
    source: '할아버지가 편지를 써요.',
    mode: 'honor',
    target: 'formal',
    set: 'si',
    answer: '할아버지께서 편지를 쓰십니다.',
    distractors: [
      '할아버지가 편지를 쓰십니다.',
      '할아버지께서 편지를 쓰으십니다.',
      '할아버지께서 편지를 쓰세요.',
    ],
    trans: L(
      'Grandfather is writing a letter.',
      'El abuelo está escribiendo una carta.',
      'Grand-père écrit une lettre.',
      'O avô está escrevendo uma carta.',
      'คุณปู่กำลังเขียนจดหมาย',
      'Kakek sedang menulis surat.',
      'Ông đang viết thư.',
      'おじいさんが手紙をお書きになります。',
    ),
    why: L(
      '쓰다 is regular: 합쇼체 needs 이/가 → 께서 with the vowel stem 쓰- taking -시- (NO 으) + -ㅂ니다 → 쓰십니다 (쓰으십니다 wrong epenthesis; 쓰십니다 without 께서 misses subject-marking; 쓰세요 is 해요체, wrong level for formal).',
      '쓰다 es regular: el 합쇼체 requiere 이/가 → 께서 con la raíz vocálica 쓰- tomando -시- (SIN 으) + -ㅂ니다 → 쓰십니다 (쓰으십니다 epéntesis errónea; 쓰십니다 sin 께서 omite la marca de sujeto; 쓰세요 es 해요체, nivel incorrecto).',
      "쓰다 est régulier : le 합쇼체 exige 이/가 → 께서 avec le radical vocalique 쓰- prenant -시- (SANS 으) + -ㅂ니다 → 쓰십니다 (쓰으십니다 mauvaise épenthèse ; 쓰십니다 sans 께서 omet le marquage du sujet ; 쓰세요 est du 해요체, mauvais niveau).",
      '쓰다 é regular: o 합쇼체 exige 이/가 → 께서 com o radical vocálico 쓰- recebendo -시- (SEM 으) + -ㅂ니다 → 쓰십니다 (쓰으십니다 epêntese errada; 쓰십니다 sem 께서 omite a marca de sujeito; 쓰세요 é 해요체, nível errado).',
      '쓰다 ปกติ: 합쇼체 ต้องใช้ 이/가 → 께서 กับก้านสระ 쓰- ที่เติม -시- (ไม่มี 으) + -ㅂ니다 → 쓰십니다 (쓰으십니다 เติม 으 ผิด; 쓰십니다 ที่ไม่มี 께서 ขาดการชี้ประธาน; 쓰세요 เป็น 해요체 ระดับผิด)',
      '쓰다 reguler: 합쇼체 butuh 이/가 → 께서 dengan batang vokal 쓰- memakai -시- (TANPA 으) + -ㅂ니다 → 쓰십니다 (쓰으십니다 epentesis salah; 쓰십니다 tanpa 께서 melewatkan penanda subjek; 쓰세요 itu 해요체, tingkat salah).',
      '쓰다 thường: 합쇼체 cần 이/가 → 께서 với thân nguyên âm 쓰- dùng -시- (KHÔNG có 으) + -ㅂ니다 → 쓰십니다 (쓰으십니다 thêm 으 sai; 쓰십니다 thiếu 께서 là thiếu đánh dấu chủ ngữ; 쓰세요 là 해요체, sai cấp độ).',
      '쓰다は規則：합쇼체は이/가 → 께서と母音語幹쓰-の으なし-시-+-ㅂ니다で쓰십니다（쓰으십니다は媒介母音の誤付加、께서の無い쓰십니다は主語標示の欠落、쓰세요は해요체で待遇レベルが誤り）。',
    ),
  },
]
