// app/seed/register-transform/honor.ts
import type { RegisterItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * Subject/object honorification items (-(으)시-, 께서/께, suppletion + honorific nouns),
 * seeded from the spine honorificVocab table. The speaker is NEVER self-honorified.
 * Drafted + Korean-lens adversarially verified. Korean wife native review = documented final gate.
 */

export const HONOR_ITEMS: RegisterItem[] = [
  {
    source: '할머니가 진지를 먹어요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '할머니께서 진지를 드세요.',
    distractors: [
      '할머니께서 진지를 먹으세요.',
      '할머니가 진지를 드세요.',
      '할머니께서 진지를 드셔.',
    ],
    trans: L(
      'Grandmother is eating her meal.',
      'La abuela está comiendo su comida.',
      'Grand-mère prend son repas.',
      'A avó está comendo sua refeição.',
      'คุณยายกำลังรับประทานอาหาร',
      'Nenek sedang makan.',
      'Bà đang dùng bữa.',
      'おばあさんが食事を召し上がります。',
    ),
    why: L(
      'Subject honor: 이/가 → 께서, and 먹다 has the suppletive honorific 드시다 → 드세요 (not 먹으세요).',
      'Honor del sujeto: 이/가 → 께서, y 먹다 tiene el honorífico supletivo 드시다 → 드세요 (no 먹으세요).',
      'Honneur du sujet : 이/가 → 께서, et 먹다 a le suppletif honorifique 드시다 → 드세요 (pas 먹으세요).',
      'Honra do sujeito: 이/가 → 께서, e 먹다 tem o honorífico supletivo 드시다 → 드세요 (não 먹으세요).',
      'ยกย่องประธาน: 이/가 → 께서 และ 먹다 มีรูปยกย่องพิเศษ 드시다 → 드세요 (ไม่ใช่ 먹으세요)',
      'Honor subjek: 이/가 → 께서, dan 먹다 punya honorifik supletif 드시다 → 드세요 (bukan 먹으세요).',
      'Tôn kính chủ ngữ: 이/가 → 께서, và 먹다 có dạng kính ngữ thay thế 드시다 → 드세요 (không phải 먹으세요).',
      '主体尊敬：이/가 → 께서、먹다は補充法の尊敬語드시다 → 드세요（먹으세요ではない）。',
    ),
  },
  {
    source: '할아버지가 약을 먹어요.',
    mode: 'honor',
    target: 'formal',
    set: 'verb',
    answer: '할아버지께서 약을 잡수십니다.',
    distractors: [
      '할아버지께서 약을 먹습니다.',
      '할아버지가 약을 잡수십니다.',
      '할아버지께서 약을 잡수세요.',
    ],
    trans: L(
      'Grandfather is taking his medicine.',
      'El abuelo está tomando su medicina.',
      'Grand-père prend son médicament.',
      'O avô está tomando o remédio.',
      'คุณปู่กำลังรับประทานยา',
      'Kakek sedang minum obat.',
      'Ông đang uống thuốc.',
      'おじいさんが薬を召し上がります。',
    ),
    why: L(
      '합쇼체 subject honor: 이/가 → 께서, and 먹다 has the suppletive 잡수시다 → 잡수십니다 (not 먹습니다).',
      'Honor del sujeto en 합쇼체: 이/가 → 께서, y 먹다 tiene el supletivo 잡수시다 → 잡수십니다 (no 먹습니다).',
      'Honneur du sujet en 합쇼체 : 이/가 → 께서, et 먹다 a le suppletif 잡수시다 → 잡수십니다 (pas 먹습니다).',
      'Honra do sujeito em 합쇼체: 이/가 → 께서, e 먹다 tem o supletivo 잡수시다 → 잡수십니다 (não 먹습니다).',
      'ยกย่องประธานแบบ 합쇼체: 이/가 → 께서 และ 먹다 มีรูปพิเศษ 잡수시다 → 잡수십니다 (ไม่ใช่ 먹습니다)',
      'Honor subjek 합쇼체: 이/가 → 께서, dan 먹다 punya supletif 잡수시다 → 잡수십니다 (bukan 먹습니다).',
      'Tôn kính chủ ngữ thể 합쇼체: 이/가 → 께서, và 먹다 có dạng thay thế 잡수시다 → 잡수십니다 (không phải 먹습니다).',
      '합쇼체の主体尊敬：이/가 → 께서、먹다は補充法の잡수시다 → 잡수십니다（먹습니다ではない）。',
    ),
  },
  {
    source: '사장님이 사무실에 있어요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '사장님께서 사무실에 계세요.',
    distractors: [
      '사장님께서 사무실에 있으세요.',
      '사장님이 사무실에 계세요.',
      '사장님께서 사무실에 계셔.',
    ],
    trans: L(
      'The boss is in the office.',
      'El jefe está en la oficina.',
      'Le patron est au bureau.',
      'O chefe está no escritório.',
      'ท่านประธานอยู่ในออฟฟิศ',
      'Bos sedang ada di kantor.',
      'Giám đốc đang ở trong văn phòng.',
      '社長が事務所にいらっしゃいます。',
    ),
    why: L(
      'Subject honor: 이/가 → 께서, and existential 있다 has the suppletive 계시다 → 계세요 (not 있으세요).',
      'Honor del sujeto: 이/가 → 께서, y el existencial 있다 tiene el supletivo 계시다 → 계세요 (no 있으세요).',
      "Honneur du sujet : 이/가 → 께서, et l'existentiel 있다 a le suppletif 계시다 → 계세요 (pas 있으세요).",
      'Honra do sujeito: 이/가 → 께서, e o existencial 있다 tem o supletivo 계시다 → 계세요 (não 있으세요).',
      'ยกย่องประธาน: 이/가 → 께서 และ 있다 (มีอยู่) มีรูปพิเศษ 계시다 → 계세요 (ไม่ใช่ 있으세요)',
      'Honor subjek: 이/가 → 께서, dan 있다 (keberadaan) punya supletif 계시다 → 계세요 (bukan 있으세요).',
      'Tôn kính chủ ngữ: 이/가 → 께서, và 있다 (tồn tại) có dạng thay thế 계시다 → 계세요 (không phải 있으세요).',
      '主体尊敬：이/가 → 께서、存在の있다は補充法の계시다 → 계세요（있으세요ではない）。',
    ),
  },
  {
    source: '교수님이 오늘 학교에 없어요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '교수님께서 오늘 학교에 안 계세요.',
    distractors: [
      '교수님께서 오늘 학교에 없으세요.',
      '교수님이 오늘 학교에 안 계세요.',
      '교수님께서 오늘 학교에 안 계셔.',
    ],
    trans: L(
      'The professor is not at school today.',
      'El profesor no está en la escuela hoy.',
      "Le professeur n'est pas à l'école aujourd'hui.",
      'O professor não está na escola hoje.',
      'วันนี้อาจารย์ไม่อยู่ที่โรงเรียน',
      'Hari ini profesor tidak ada di sekolah.',
      'Hôm nay giáo sư không có ở trường.',
      '教授は今日学校にいらっしゃいません。',
    ),
    why: L(
      'Subject honor: 이/가 → 께서, and 없다 (absence) uses 안 계시다 → 안 계세요 (not 없으세요).',
      'Honor del sujeto: 이/가 → 께서, y 없다 (ausencia) usa 안 계시다 → 안 계세요 (no 없으세요).',
      'Honneur du sujet : 이/가 → 께서, et 없다 (absence) utilise 안 계시다 → 안 계세요 (pas 없으세요).',
      'Honra do sujeito: 이/가 → 께서, e 없다 (ausência) usa 안 계시다 → 안 계세요 (não 없으세요).',
      'ยกย่องประธาน: 이/가 → 께서 และ 없다 (ไม่อยู่) ใช้ 안 계시다 → 안 계세요 (ไม่ใช่ 없으세요)',
      'Honor subjek: 이/가 → 께서, dan 없다 (ketiadaan) memakai 안 계시다 → 안 계세요 (bukan 없으세요).',
      'Tôn kính chủ ngữ: 이/가 → 께서, và 없다 (vắng mặt) dùng 안 계시다 → 안 계세요 (không phải 없으세요).',
      '主体尊敬：이/가 → 께서、없다（不在）は안 계시다 → 안 계세요（없으세요ではない）。',
    ),
  },
  {
    source: '할아버지가 지금 자요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '할아버지께서 지금 주무세요.',
    distractors: [
      '할아버지께서 지금 자세요.',
      '할아버지가 지금 주무세요.',
      '할아버지께서 지금 주무셔.',
    ],
    trans: L(
      'Grandfather is sleeping now.',
      'El abuelo está durmiendo ahora.',
      'Grand-père dort maintenant.',
      'O avô está dormindo agora.',
      'ตอนนี้คุณปู่กำลังนอนหลับ',
      'Kakek sedang tidur sekarang.',
      'Bây giờ ông đang ngủ.',
      'おじいさんが今お休みです。',
    ),
    why: L(
      'Subject honor: 이/가 → 께서, and 자다 has the suppletive honorific 주무시다 → 주무세요 (not 자세요).',
      'Honor del sujeto: 이/가 → 께서, y 자다 tiene el honorífico supletivo 주무시다 → 주무세요 (no 자세요).',
      'Honneur du sujet : 이/가 → 께서, et 자다 a le suppletif honorifique 주무시다 → 주무세요 (pas 자세요).',
      'Honra do sujeito: 이/가 → 께서, e 자다 tem o honorífico supletivo 주무시다 → 주무세요 (não 자세요).',
      'ยกย่องประธาน: 이/가 → 께서 และ 자다 มีรูปยกย่องพิเศษ 주무시다 → 주무세요 (ไม่ใช่ 자세요)',
      'Honor subjek: 이/가 → 께서, dan 자다 punya honorifik supletif 주무시다 → 주무세요 (bukan 자세요).',
      'Tôn kính chủ ngữ: 이/가 → 께서, và 자다 có dạng kính ngữ thay thế 주무시다 → 주무세요 (không phải 자세요).',
      '主体尊敬：이/가 → 께서、자다は補充法の尊敬語주무시다 → 주무세요（자세요ではない）。',
    ),
  },
  {
    source: '선생님이 학생들에게 말해요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '선생님께서 학생들에게 말씀하세요.',
    distractors: [
      '선생님께서 학생들에게 말하세요.',
      '선생님이 학생들에게 말씀하세요.',
      '선생님께서 학생들에게 말씀하셔.',
    ],
    trans: L(
      'The teacher speaks to the students.',
      'El profesor habla a los estudiantes.',
      'Le professeur parle aux élèves.',
      'O professor fala com os alunos.',
      'คุณครูพูดกับนักเรียน',
      'Guru berbicara kepada para murid.',
      'Thầy giáo nói chuyện với học sinh.',
      '先生が学生たちにお話しになります。',
    ),
    why: L(
      'Subject honor: 이/가 → 께서, and 말하다 has the suppletive 말씀하시다 → 말씀하세요 (not 말하세요).',
      'Honor del sujeto: 이/가 → 께서, y 말하다 tiene el supletivo 말씀하시다 → 말씀하세요 (no 말하세요).',
      'Honneur du sujet : 이/가 → 께서, et 말하다 a le suppletif 말씀하시다 → 말씀하세요 (pas 말하세요).',
      'Honra do sujeito: 이/가 → 께서, e 말하다 tem o supletivo 말씀하시다 → 말씀하세요 (não 말하세요).',
      'ยกย่องประธาน: 이/가 → 께서 และ 말하다 มีรูปพิเศษ 말씀하시다 → 말씀하세요 (ไม่ใช่ 말하세요)',
      'Honor subjek: 이/가 → 께서, dan 말하다 punya supletif 말씀하시다 → 말씀하세요 (bukan 말하세요).',
      'Tôn kính chủ ngữ: 이/가 → 께서, và 말하다 có dạng thay thế 말씀하시다 → 말씀하세요 (không phải 말하세요).',
      '主体尊敬：이/가 → 께서、말하다は補充法の말씀하시다 → 말씀하세요（말하세요ではない）。',
    ),
  },
  {
    source: '할아버지가 작년에 죽었어요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '할아버지께서 작년에 돌아가셨어요.',
    distractors: [
      '할아버지께서 작년에 죽으셨어요.',
      '할아버지가 작년에 돌아가셨어요.',
      '할아버지께서 작년에 돌아가셨어.',
    ],
    trans: L(
      'Grandfather passed away last year.',
      'El abuelo falleció el año pasado.',
      "Grand-père est décédé l'année dernière.",
      'O avô faleceu no ano passado.',
      'คุณปู่เสียชีวิตเมื่อปีที่แล้ว',
      'Kakek meninggal tahun lalu.',
      'Ông đã qua đời năm ngoái.',
      'おじいさんが昨年お亡くなりになりました。',
    ),
    why: L(
      'Subject honor: 이/가 → 께서, and 죽다 uses the suppletive 돌아가시다 → 돌아가셨어요 (not 죽으셨어요).',
      'Honor del sujeto: 이/가 → 께서, y 죽다 usa el supletivo 돌아가시다 → 돌아가셨어요 (no 죽으셨어요).',
      'Honneur du sujet : 이/가 → 께서, et 죽다 utilise le suppletif 돌아가시다 → 돌아가셨어요 (pas 죽으셨어요).',
      'Honra do sujeito: 이/가 → 께서, e 죽다 usa o supletivo 돌아가시다 → 돌아가셨어요 (não 죽으셨어요).',
      'ยกย่องประธาน: 이/가 → 께서 และ 죽다 ใช้รูปพิเศษ 돌아가시다 → 돌아가셨어요 (ไม่ใช่ 죽으셨어요)',
      'Honor subjek: 이/가 → 께서, dan 죽다 memakai supletif 돌아가시다 → 돌아가셨어요 (bukan 죽으셨어요).',
      'Tôn kính chủ ngữ: 이/가 → 께서, và 죽다 dùng dạng thay thế 돌아가시다 → 돌아가셨어요 (không phải 죽으셨어요).',
      '主体尊敬：이/가 → 께서、죽다は補充法の돌아가시다 → 돌아가셨어요（죽으셨어요ではない）。',
    ),
  },
  {
    source: '할머니가 요즘 많이 아파요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '할머니께서 요즘 많이 편찮으세요.',
    distractors: [
      '할머니께서 요즘 많이 아프세요.',
      '할머니가 요즘 많이 편찮으세요.',
      '할머니께서 요즘 많이 편찮으셔.',
    ],
    trans: L(
      'Grandmother is very ill these days.',
      'La abuela está muy enferma últimamente.',
      'Grand-mère est très malade ces jours-ci.',
      'A avó está muito doente ultimamente.',
      'ช่วงนี้คุณยายป่วยมาก',
      'Akhir-akhir ini nenek sangat sakit.',
      'Dạo này bà ốm nặng.',
      'おばあさんが最近とても具合が悪くていらっしゃいます。',
    ),
    why: L(
      'Subject honor: 이/가 → 께서, and 아프다 uses the suppletive 편찮으시다 → 편찮으세요 (not 아프세요).',
      'Honor del sujeto: 이/가 → 께서, y 아프다 usa el supletivo 편찮으시다 → 편찮으세요 (no 아프세요).',
      'Honneur du sujet : 이/가 → 께서, et 아프다 utilise le suppletif 편찮으시다 → 편찮으세요 (pas 아프세요).',
      'Honra do sujeito: 이/가 → 께서, e 아프다 usa o supletivo 편찮으시다 → 편찮으세요 (não 아프세요).',
      'ยกย่องประธาน: 이/가 → 께서 และ 아프다 ใช้รูปพิเศษ 편찮으시다 → 편찮으세요 (ไม่ใช่ 아프세요)',
      'Honor subjek: 이/가 → 께서, dan 아프다 memakai supletif 편찮으시다 → 편찮으세요 (bukan 아프세요).',
      'Tôn kính chủ ngữ: 이/가 → 께서, và 아프다 dùng dạng thay thế 편찮으시다 → 편찮으세요 (không phải 아프세요).',
      '主体尊敬：이/가 → 께서、아프다は補充法の편찮으시다 → 편찮으세요（아프세요ではない）。',
    ),
  },
  {
    source: '제가 할머니에게 선물을 줘요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '제가 할머니께 선물을 드려요.',
    distractors: [
      '제가 할머니께 선물을 드리세요.',
      '제가 할머니에게 선물을 드려요.',
      '제가 할머니께 선물을 줘요.',
    ],
    trans: L(
      'I give a gift to my grandmother.',
      'Le doy un regalo a mi abuela.',
      'Je donne un cadeau à ma grand-mère.',
      'Eu dou um presente para a minha avó.',
      'ฉันมอบของขวัญให้คุณยาย',
      'Saya memberi hadiah kepada nenek.',
      'Tôi tặng quà cho bà.',
      '私が祖母にプレゼントを差し上げます。',
    ),
    why: L(
      'Object honor (겸양): toward a respected object 에게 → 께 and humble 주다 → 드리다; never put -(으)시- on your own humble verb (드리세요 wrong).',
      'Honor del objeto (겸양): hacia un objeto respetado 에게 → 께 y humilde 주다 → 드리다; nunca pongas -(으)시- en tu propio verbo humilde (드리세요 incorrecto).',
      "Honneur de l'objet (겸양) : envers un objet respecté 에게 → 께 et humble 주다 → 드리다 ; ne jamais mettre -(으)시- sur son propre verbe humble (드리세요 faux).",
      'Honra do objeto (겸양): para um objeto respeitado 에게 → 께 e humilde 주다 → 드리다; nunca ponha -(으)시- no seu próprio verbo humilde (드리세요 errado).',
      'ยกย่องกรรม (겸양): ต่อผู้ที่เคารพ 에게 → 께 และรูปถ่อมตน 주다 → 드리다 อย่าใส่ -(으)시- ในกริยาถ่อมตนของตัวเอง (드리세요 ผิด)',
      'Honor objek (겸양): kepada objek terhormat 에게 → 께 dan bentuk rendah hati 주다 → 드리다; jangan beri -(으)시- pada verba rendah hati sendiri (드리세요 salah).',
      'Khiêm nhường với tân ngữ (겸양): hướng tới người được tôn kính 에게 → 께 và dạng khiêm 주다 → 드리다; không gắn -(으)시- vào động từ khiêm của chính mình (드리세요 sai).',
      '客体尊敬（겸양）：敬う相手へ에게 → 께、謙譲の주다 → 드리다。自分の謙譲語に-(으)시-は付けない（드리세요は誤り）。',
    ),
  },
  {
    source: '제가 선생님에게 질문을 물어봐요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '제가 선생님께 질문을 여쭤봐요.',
    distractors: [
      '제가 선생님께 질문을 여쭤보세요.',
      '제가 선생님에게 질문을 여쭤봐요.',
      '제가 선생님께 질문을 물어봐요.',
    ],
    trans: L(
      'I ask the teacher a question.',
      'Le hago una pregunta al profesor.',
      'Je pose une question au professeur.',
      'Eu faço uma pergunta ao professor.',
      'ฉันถามคำถามคุณครู',
      'Saya bertanya kepada guru.',
      'Tôi hỏi thầy giáo một câu hỏi.',
      '私が先生に質問をお伺いします。',
    ),
    why: L(
      'Object honor (겸양): 에게 → 께 and humble 묻다/물어보다 → 여쭤보다; never put -(으)시- on your own humble verb (여쭤보세요 wrong).',
      'Honor del objeto (겸양): 에게 → 께 y humilde 묻다/물어보다 → 여쭤보다; nunca pongas -(으)시- en tu propio verbo humilde (여쭤보세요 incorrecto).',
      "Honneur de l'objet (겸양) : 에게 → 께 et humble 묻다/물어보다 → 여쭤보다 ; ne jamais mettre -(으)시- sur son propre verbe humble (여쭤보세요 faux).",
      'Honra do objeto (겸양): 에게 → 께 e humilde 묻다/물어보다 → 여쭤보다; nunca ponha -(으)시- no seu próprio verbo humilde (여쭤보세요 errado).',
      'ยกย่องกรรม (겸양): 에게 → 께 และรูปถ่อมตน 묻다/물어보다 → 여쭤보다 อย่าใส่ -(으)시- ในกริยาถ่อมตนของตัวเอง (여쭤보세요 ผิด)',
      'Honor objek (겸양): 에게 → 께 dan bentuk rendah hati 묻다/물어보다 → 여쭤보다; jangan beri -(으)시- pada verba rendah hati sendiri (여쭤보세요 salah).',
      'Khiêm nhường với tân ngữ (겸양): 에게 → 께 và dạng khiêm 묻다/물어보다 → 여쭤보다; không gắn -(으)시- vào động từ khiêm của chính mình (여쭤보세요 sai).',
      '客体尊敬（겸양）：에게 → 께、謙譲の묻다/물어보다 → 여쭤보다。自分の謙譲語に-(으)시-は付けない（여쭤보세요は誤り）。',
    ),
  },
  {
    source: '제가 내일 교수님을 봐요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '제가 내일 교수님을 봬요.',
    distractors: [
      '제가 내일 교수님을 뵈세요.',
      '제가 내일 교수님을 보세요.',
      '제가 내일 교수님을 봐요.',
    ],
    trans: L(
      'I will see the professor tomorrow.',
      'Veré al profesor mañana.',
      'Je verrai le professeur demain.',
      'Verei o professor amanhã.',
      'พรุ่งนี้ฉันจะไปพบอาจารย์',
      'Besok saya akan menemui profesor.',
      'Ngày mai tôi sẽ gặp giáo sư.',
      '私が明日教授にお目にかかります。',
    ),
    why: L(
      'Object honor (겸양): humble 보다 → 뵙다/뵈다 → 뵈어요(=봬요); you lower yourself, so no -(으)시- on your own verb (뵈세요/보세요 wrong).',
      'Honor del objeto (겸양): humilde 보다 → 뵙다/뵈다 → 뵈어요(=봬요); te rebajas, así que sin -(으)시- en tu propio verbo (뵈세요/보세요 incorrecto).',
      "Honneur de l'objet (겸양) : humble 보다 → 뵙다/뵈다 → 뵈어요(=봬요) ; on s'abaisse, donc pas de -(으)시- sur son propre verbe (뵈세요/보세요 faux).",
      'Honra do objeto (겸양): humilde 보다 → 뵙다/뵈다 → 뵈어요(=봬요); você se rebaixa, então sem -(으)시- no seu verbo (뵈세요/보세요 errado).',
      'ยกย่องกรรม (겸양): รูปถ่อมตน 보다 → 뵙다/뵈다 → 뵈어요(=봬요) ถ่อมตนเอง จึงไม่ใส่ -(으)시- ในกริยาของตัวเอง (뵈세요/보세요 ผิด)',
      'Honor objek (겸양): bentuk rendah hati 보다 → 뵙다/뵈다 → 뵈어요(=봬요); merendahkan diri, jadi tanpa -(으)시- pada verba sendiri (뵈세요/보세요 salah).',
      'Khiêm nhường với tân ngữ (겸양): dạng khiêm 보다 → 뵙다/뵈다 → 뵈어요(=봬요); tự hạ mình, nên không -(으)시- trên động từ của mình (뵈세요/보세요 sai).',
      '客体尊敬（겸양）：謙譲の보다 → 뵙다/뵈다 → 뵈어요(=봬요)。自らを低めるので自分の動詞に-(으)시-は付けない（뵈세요/보세요は誤り）。',
    ),
  },
  {
    source: '손님이 식당에서 음식을 먹어요.',
    mode: 'honor',
    target: 'polite',
    set: 'verb',
    answer: '손님께서 식당에서 음식을 드세요.',
    distractors: [
      '손님께서 식당에서 음식을 먹으세요.',
      '손님이 식당에서 음식을 드세요.',
      '손님께서 식당에서 음식을 드셔.',
    ],
    trans: L(
      'The guest is eating food at the restaurant.',
      'El cliente está comiendo comida en el restaurante.',
      'Le client mange au restaurant.',
      'O cliente está comendo no restaurante.',
      'ลูกค้ากำลังรับประทานอาหารที่ร้าน',
      'Tamu sedang makan di restoran.',
      'Khách đang dùng món ăn tại nhà hàng.',
      'お客様がレストランで食事を召し上がります。',
    ),
    why: L(
      'Subject honor: 이/가 → 께서, and 먹다 has the suppletive honorific 드시다 → 드세요 (not 먹으세요).',
      'Honor del sujeto: 이/가 → 께서, y 먹다 tiene el honorífico supletivo 드시다 → 드세요 (no 먹으세요).',
      'Honneur du sujet : 이/가 → 께서, et 먹다 a le suppletif honorifique 드시다 → 드세요 (pas 먹으세요).',
      'Honra do sujeito: 이/가 → 께서, e 먹다 tem o honorífico supletivo 드시다 → 드세요 (não 먹으세요).',
      'ยกย่องประธาน: 이/가 → 께서 และ 먹다 มีรูปยกย่องพิเศษ 드시다 → 드세요 (ไม่ใช่ 먹으세요)',
      'Honor subjek: 이/가 → 께서, dan 먹다 punya honorifik supletif 드시다 → 드세요 (bukan 먹으세요).',
      'Tôn kính chủ ngữ: 이/가 → 께서, và 먹다 có dạng kính ngữ thay thế 드시다 → 드세요 (không phải 먹으세요).',
      '主体尊敬：이/가 → 께서、먹다は補充法の尊敬語드시다 → 드세요（먹으세요ではない）。',
    ),
  },
  {
    source: '선생님, 이름이 뭐예요?',
    mode: 'honor',
    target: 'polite',
    set: 'noun',
    answer: '선생님, 성함이 어떻게 되세요?',
    distractors: [
      '선생님, 이름이 어떻게 되세요?',
      '선생님, 연세가 어떻게 되세요?',
      '선생님, 성함이 뭐예요?',
    ],
    trans: L(
      'Teacher, what is your name?',
      'Profesor, ¿cómo se llama usted?',
      'Professeur, quel est votre nom ?',
      'Professor, qual é o seu nome?',
      'คุณครู ชื่ออะไรครับ/คะ',
      'Bu/Pak Guru, siapa nama Anda?',
      'Thưa thầy/cô, tên của thầy/cô là gì ạ?',
      '先生、お名前は何ですか？',
    ),
    why: L(
      '이름→성함 + 되세요 (-(으)시-); plain 이름, 연세(wrong noun = age), and 성함이 뭐예요 (no honorific verb) are all wrong.',
      '이름→성함 + 되세요 (-(으)시-); 이름 simple, 연세(sustantivo erróneo = edad) y 성함이 뭐예요 (sin verbo honorífico) son errores.',
      '이름→성함 + 되세요 (-(으)시-) ; 이름 ordinaire, 연세(mauvais nom = âge) et 성함이 뭐예요 (sans verbe honorifique) sont fautifs.',
      '이름→성함 + 되세요 (-(으)시-); 이름 simples, 연세(substantivo errado = idade) e 성함이 뭐예요 (sem verbo honorífico) estão errados.',
      '이름→성함 + 되세요 (-(으)시-); 이름 ธรรมดา, 연세(คำนามผิด = อายุ) และ 성함이 뭐예요 (ไม่มีกริยายกย่อง) ผิดทั้งหมด',
      '이름→성함 + 되세요 (-(으)시-); 이름 biasa, 연세(nomina salah = usia), dan 성함이 뭐예요 (tanpa verba hormat) salah.',
      '이름→성함 + 되세요 (-(으)시-); 이름 thường, 연세(danh từ sai = tuổi) và 성함이 뭐예요 (không có động từ kính ngữ) đều sai.',
      '이름→성함 + 되세요 (-(으)시-)；素の 이름、연세(誤った名詞=年齢)、성함이 뭐예요(尊敬動詞なし)はすべて誤り。',
    ),
  },
  {
    source: '할머니는 나이가 많아요.',
    mode: 'honor',
    target: 'polite',
    set: 'noun',
    answer: '할머니께서는 연세가 많으세요.',
    distractors: [
      '할머니께서는 나이가 많으세요.',
      '할머니께서는 성함이 많으세요.',
      '할머니는 연세가 많아요.',
    ],
    trans: L(
      'Grandmother is old (advanced in age).',
      'La abuela es mayor (de edad avanzada).',
      'Grand-mère est âgée.',
      'A avó é idosa (de idade avançada).',
      'คุณยายอายุมาก',
      'Nenek sudah berusia lanjut.',
      'Bà đã lớn tuổi.',
      'おばあさんはお年を召しています。',
    ),
    why: L(
      '나이→연세 + 께서 + 많으세요 (-(으)시-); keeping 나이, swapping to 성함(wrong noun), or dropping -(으)시- are all wrong.',
      '나이→연세 + 께서 + 많으세요 (-(으)시-); mantener 나이, cambiar a 성함(sustantivo erróneo) o quitar -(으)시- son errores.',
      '나이→연세 + 께서 + 많으세요 (-(으)시-) ; garder 나이, mettre 성함(mauvais nom) ou omettre -(으)시- sont fautifs.',
      '나이→연세 + 께서 + 많으세요 (-(으)시-); manter 나이, trocar por 성함(substantivo errado) ou omitir -(으)시- estão errados.',
      '나이→연세 + 께서 + 많으세요 (-(으)시-); การคง 나이, เปลี่ยนเป็น 성함(คำนามผิด) หรือตัด -(으)시- ผิดทั้งหมด',
      '나이→연세 + 께서 + 많으세요 (-(으)시-); mempertahankan 나이, mengganti ke 성함(nomina salah), atau menghilangkan -(으)시- semua salah.',
      '나이→연세 + 께서 + 많으세요 (-(으)시-); giữ 나이, đổi sang 성함(danh từ sai) hay bỏ -(으)시- đều sai.',
      '나이→연세 + 께서 + 많으세요 (-(으)시-)；나이 のまま・성함(誤った名詞)への置換・-(으)시- 脱落はすべて誤り。',
    ),
  },
  {
    source: '교수님 집이 여기에서 멀어요?',
    mode: 'honor',
    target: 'polite',
    set: 'noun',
    answer: '교수님 댁이 여기에서 머세요?',
    distractors: [
      '교수님 집이 여기에서 머세요?',
      '교수님 진지가 여기에서 머세요?',
      '교수님 댁이 여기에서 멀어요?',
    ],
    trans: L(
      'Professor, is your house far from here?',
      'Profesor, ¿su casa está lejos de aquí?',
      "Professeur, votre maison est-elle loin d'ici ?",
      'Professor, a sua casa é longe daqui?',
      'อาจารย์ครับ/คะ บ้านอยู่ไกลจากที่นี่ไหม',
      'Pak/Bu Profesor, apakah rumah Anda jauh dari sini?',
      'Thưa giáo sư, nhà của giáo sư có xa đây không ạ?',
      '教授、お宅はここから遠いですか？',
    ),
    why: L(
      '집→댁 + 머세요 (멀다 + -(으)시-, ㄹ drops); plain 집, 진지(wrong noun = meal), and 멀어요 without -(으)시- are wrong.',
      '집→댁 + 머세요 (멀다 + -(으)시-, cae ㄹ); 집 simple, 진지(sustantivo erróneo = comida) y 멀어요 sin -(으)시- son errores.',
      '집→댁 + 머세요 (멀다 + -(으)시-, le ㄹ tombe) ; 집 ordinaire, 진지(mauvais nom = repas) et 멀어요 sans -(으)시- sont fautifs.',
      '집→댁 + 머세요 (멀다 + -(으)시-, cai o ㄹ); 집 simples, 진지(substantivo errado = refeição) e 멀어요 sem -(으)시- estão errados.',
      '집→댁 + 머세요 (멀다 + -(으)시-, ㄹ หลุด); 집 ธรรมดา, 진지(คำนามผิด = อาหาร) และ 멀어요 ที่ไม่มี -(으)시- ผิด',
      '집→댁 + 머세요 (멀다 + -(으)시-, ㄹ luruh); 집 biasa, 진지(nomina salah = makanan) dan 멀어요 tanpa -(으)시- salah.',
      '집→댁 + 머세요 (멀다 + -(으)시-, rụng ㄹ); 집 thường, 진지(danh từ sai = bữa ăn) và 멀어요 không -(으)시- đều sai.',
      '집→댁 + 머세요 (멀다 + -(으)시-、ㄹ 脱落)；素の 집、진지(誤った名詞=食事)、-(으)시- なしの 멀어요 は誤り。',
    ),
  },
  {
    source: '할아버지, 밥 먹었어요?',
    mode: 'honor',
    target: 'polite',
    set: 'noun',
    answer: '할아버지, 진지 드셨어요?',
    distractors: [
      '할아버지, 밥 드셨어요?',
      '할아버지, 말씀 드셨어요?',
      '할아버지, 진지 먹었어요?',
    ],
    trans: L(
      'Grandfather, have you eaten?',
      'Abuelo, ¿ha comido?',
      'Grand-père, avez-vous mangé ?',
      'Vovô, o senhor já comeu?',
      'คุณตา/คุณปู่ ทานข้าวแล้วหรือยังครับ/คะ',
      'Kakek, sudah makan?',
      'Ông ơi, ông đã ăn cơm chưa ạ?',
      'おじいさん、お食事は召し上がりましたか？',
    ),
    why: L(
      '밥→진지 + 드셨어요 (먹다→드시다); keeping 밥, using 말씀(wrong noun = words), or plain 먹었어요 are wrong.',
      '밥→진지 + 드셨어요 (먹다→드시다); mantener 밥, usar 말씀(sustantivo erróneo = palabras) o 먹었어요 simple son errores.',
      '밥→진지 + 드셨어요 (먹다→드시다) ; garder 밥, employer 말씀(mauvais nom = paroles) ou 먹었어요 ordinaire sont fautifs.',
      '밥→진지 + 드셨어요 (먹다→드시다); manter 밥, usar 말씀(substantivo errado = palavras) ou 먹었어요 simples estão errados.',
      '밥→진지 + 드셨어요 (먹다→드시다); การคง 밥, ใช้ 말씀(คำนามผิด = คำพูด) หรือ 먹었어요 ธรรมดา ผิด',
      '밥→진지 + 드셨어요 (먹다→드시다); mempertahankan 밥, memakai 말씀(nomina salah = perkataan), atau 먹었어요 biasa salah.',
      '밥→진지 + 드셨어요 (먹다→드시다); giữ 밥, dùng 말씀(danh từ sai = lời nói) hay 먹었어요 thường đều sai.',
      '밥→진지 + 드셨어요 (먹다→드시다)；밥 のまま・말씀(誤った名詞=言葉)・素の 먹었어요 は誤り。',
    ),
  },
  {
    source: '사장님이 무슨 말을 했어요?',
    mode: 'honor',
    target: 'polite',
    set: 'noun',
    answer: '사장님께서 무슨 말씀을 하셨어요?',
    distractors: [
      '사장님께서 무슨 말을 하셨어요?',
      '사장님께서 무슨 진지를 하셨어요?',
      '사장님이 무슨 말씀을 했어요?',
    ],
    trans: L(
      'What did the boss say?',
      '¿Qué dijo el jefe?',
      "Qu'a dit le patron ?",
      'O que o chefe disse?',
      'ท่านประธาน/เจ้านายพูดว่าอะไร',
      'Apa yang dikatakan oleh bos?',
      'Giám đốc đã nói gì ạ?',
      '社長は何とおっしゃいましたか？',
    ),
    why: L(
      '말→말씀 + 께서 + 하셨어요 (-(으)시-); keeping 말, using 진지(wrong noun = meal), or 했어요 without -(으)시- are wrong.',
      '말→말씀 + 께서 + 하셨어요 (-(으)시-); mantener 말, usar 진지(sustantivo erróneo = comida) o 했어요 sin -(으)시- son errores.',
      '말→말씀 + 께서 + 하셨어요 (-(으)시-) ; garder 말, employer 진지(mauvais nom = repas) ou 했어요 sans -(으)시- sont fautifs.',
      '말→말씀 + 께서 + 하셨어요 (-(으)시-); manter 말, usar 진지(substantivo errado = refeição) ou 했어요 sem -(으)시- estão errados.',
      '말→말씀 + 께서 + 하셨어요 (-(으)시-); การคง 말, ใช้ 진지(คำนามผิด = อาหาร) หรือ 했어요 ที่ไม่มี -(으)시- ผิด',
      '말→말씀 + 께서 + 하셨어요 (-(으)시-); mempertahankan 말, memakai 진지(nomina salah = makanan), atau 했어요 tanpa -(으)시- salah.',
      '말→말씀 + 께서 + 하셨어요 (-(으)시-); giữ 말, dùng 진지(danh từ sai = bữa ăn) hay 했어요 không -(으)시- đều sai.',
      '말→말씀 + 께서 + 하셨어요 (-(으)시-)；말 のまま・진지(誤った名詞=食事)・-(으)시- なしの 했어요 は誤り。',
    ),
  },
  {
    source: '부모님 생일이 언제예요?',
    mode: 'honor',
    target: 'polite',
    set: 'noun',
    answer: '부모님 생신이 언제세요?',
    distractors: [
      '부모님 생일이 언제세요?',
      '부모님 연세가 언제세요?',
      '부모님 생신이 언제예요?',
    ],
    trans: L(
      "When is your parents' birthday?",
      '¿Cuándo es el cumpleaños de tus padres?',
      "Quand est l'anniversaire de tes parents ?",
      'Quando é o aniversário dos seus pais?',
      'วันเกิดของคุณพ่อคุณแม่คือเมื่อไหร่',
      'Kapan ulang tahun orang tua Anda?',
      'Sinh nhật của bố mẹ bạn là khi nào?',
      'ご両親のお誕生日はいつですか？',
    ),
    why: L(
      '생일→생신 + 언제세요 (-(으)시-); plain 생일, 연세(wrong noun = age), and 언제예요 without -(으)시- are wrong.',
      '생일→생신 + 언제세요 (-(으)시-); 생일 simple, 연세(sustantivo erróneo = edad) y 언제예요 sin -(으)시- son errores.',
      '생일→생신 + 언제세요 (-(으)시-) ; 생일 ordinaire, 연세(mauvais nom = âge) et 언제예요 sans -(으)시- sont fautifs.',
      '생일→생신 + 언제세요 (-(으)시-); 생일 simples, 연세(substantivo errado = idade) e 언제예요 sem -(으)시- estão errados.',
      '생일→생신 + 언제세요 (-(으)시-); 생일 ธรรมดา, 연세(คำนามผิด = อายุ) และ 언제예요 ที่ไม่มี -(으)시- ผิด',
      '생일→생신 + 언제세요 (-(으)시-); 생일 biasa, 연세(nomina salah = usia), dan 언제예요 tanpa -(으)시- salah.',
      '생일→생신 + 언제세요 (-(으)시-); 생일 thường, 연세(danh từ sai = tuổi) và 언제예요 không -(으)시- đều sai.',
      '생일→생신 + 언제세요 (-(으)시-)；素の 생일、연세(誤った名詞=年齢)、-(으)시- なしの 언제예요 は誤り。',
    ),
  },
  {
    source: '할머니가 방에서 텔레비전을 봐요.',
    mode: 'honor',
    target: 'polite',
    set: 'particle',
    answer: '할머니께서 방에서 텔레비전을 보세요.',
    distractors: [
      '할머니가 방에서 텔레비전을 보세요.',
      '할머니께 방에서 텔레비전을 보세요.',
      '할머니께서 방에서 텔레비전을 봐요.',
    ],
    trans: L(
      'Grandmother is watching television in the room.',
      'La abuela está viendo televisión en la habitación.',
      'Grand-mère regarde la télévision dans la chambre.',
      'A avó está assistindo televisão no quarto.',
      'คุณยายกำลังดูโทรทัศน์อยู่ในห้อง',
      'Nenek sedang menonton televisi di kamar.',
      'Bà đang xem tivi trong phòng.',
      'おばあさんは部屋でテレビを見ていらっしゃいます。',
    ),
    why: L(
      'Subject honor (주체높임): 이/가 → 께서 pairs with -(으)시- → 보세요. Keeping 가, swapping to dative 께, or 께서 without 시 are all wrong.',
      'Honor al sujeto (주체높임): 이/가 → 께서 va con -(으)시- → 보세요. Mantener 가, cambiar al dativo 께 o 께서 sin 시 son errores.',
      'Honneur du sujet (주체높임) : 이/가 → 께서 va avec -(으)시- → 보세요. Garder 가, passer au datif 께 ou 께서 sans 시 sont faux.',
      'Honra ao sujeito (주체높임): 이/가 → 께서 combina com -(으)시- → 보세요. Manter 가, trocar pelo dativo 께 ou 께서 sem 시 estão errados.',
      'ยกย่องประธาน (주체높임): 이/가 → 께서 ใช้คู่กับ -(으)시- → 보세요 การคง 가 เปลี่ยนเป็น 께 (รูปกรรมรอง) หรือ 께서 ที่ไม่มี 시 ล้วนผิด',
      'Hormat subjek (주체높임): 이/가 → 께서 berpasangan dengan -(으)시- → 보세요. Tetap 가, ganti ke datif 께, atau 께서 tanpa 시 semuanya salah.',
      'Tôn kính chủ ngữ (주체높임): 이/가 → 께서 đi với -(으)시- → 보세요. Giữ 가, đổi sang 께 (tặng cách), hoặc 께서 mà thiếu 시 đều sai.',
      '主語の尊敬（주체높임）：이/가 → 께서は-(으)시- → 보세요と対応。가のまま、与格の께に替える、시の無い께서はいずれも誤り。',
    ),
  },
  {
    source: '저는 선생님한테 선물을 줬어요.',
    mode: 'honor',
    target: 'polite',
    set: 'particle',
    answer: '저는 선생님께 선물을 드렸어요.',
    distractors: [
      '저는 선생님한테 선물을 드렸어요.',
      '저는 선생님께 선물을 줬어요.',
      '저는 선생님께서 선물을 드렸어요.',
    ],
    trans: L(
      'I gave the teacher a gift.',
      'Le di un regalo al profesor.',
      "J'ai donné un cadeau au professeur.",
      'Eu dei um presente ao professor.',
      'ฉันให้ของขวัญแก่คุณครู',
      'Saya memberi guru sebuah hadiah.',
      'Tôi đã tặng thầy giáo một món quà.',
      '私は先生にプレゼントを差し上げました。',
    ),
    why: L(
      'Object humbling (객체높임/겸양): 한테 → 께 pairs with the humble verb 주다 → 드리다. Keeping 한테, keeping plain 주다, or using subject-marker 께서 on the recipient are all wrong.',
      'Humillación del objeto (객체높임/겸양): 한테 → 께 va con el verbo humilde 주다 → 드리다. Mantener 한테, mantener 주다 simple o usar 께서 (sujeto) en el receptor son errores.',
      "Humilité envers l'objet (객체높임/겸양) : 한테 → 께 va avec le verbe humble 주다 → 드리다. Garder 한테, garder 주다 ordinaire ou mettre 께서 (sujet) sur le destinataire sont faux.",
      'Humildade ao objeto (객체높임/겸양): 한테 → 께 combina com o verbo humilde 주다 → 드리다. Manter 한테, manter 주다 comum ou usar 께서 (sujeito) no destinatário estão errados.',
      'ถ่อมตนต่อกรรม (객체높임/겸양): 한테 → 께 ใช้คู่กับคำกริยาถ่อมตน 주다 → 드리다 การคง 한테 คง 주다 ธรรมดา หรือใช้ 께서 (รูปประธาน) กับผู้รับ ล้วนผิด',
      'Merendah pada objek (객체높임/겸양): 한테 → 께 berpasangan dengan verba merendah 주다 → 드리다. Tetap 한테, tetap 주다 biasa, atau pakai 께서 (subjek) pada penerima semuanya salah.',
      'Khiêm nhường với tân ngữ (객체높임/겸양): 한테 → 께 đi với động từ khiêm nhường 주다 → 드리다. Giữ 한테, giữ 주다 thường, hoặc dùng 께서 (chủ ngữ) cho người nhận đều sai.',
      '客体の謙譲（객체높임/겸양）：한테 → 께は謙譲動詞주다 → 드리다と対応。한테のまま、普通の주다のまま、受け手に主語標識께서を付けるのはいずれも誤り。',
    ),
  },
  {
    source: '사장님이 어제 회의를 했어요.',
    mode: 'honor',
    target: 'polite',
    set: 'particle',
    answer: '사장님께서 어제 회의를 하셨어요.',
    distractors: [
      '사장님이 어제 회의를 하셨어요.',
      '사장님께 어제 회의를 하셨어요.',
      '사장님께서 어제 회의를 했어요.',
    ],
    trans: L(
      'The boss held a meeting yesterday.',
      'El jefe tuvo una reunión ayer.',
      'Le patron a tenu une réunion hier.',
      'O chefe teve uma reunião ontem.',
      'เมื่อวานท่านประธานประชุม',
      'Bos mengadakan rapat kemarin.',
      'Hôm qua giám đốc đã họp.',
      '社長は昨日会議をなさいました。',
    ),
    why: L(
      'Subject honor (주체높임): 이/가 → 께서 pairs with -(으)시- → 하셨어요. Keeping 이, swapping to dative 께, or 께서 without 시 are all wrong.',
      'Honor al sujeto (주체높임): 이/가 → 께서 va con -(으)시- → 하셨어요. Mantener 이, cambiar al dativo 께 o 께서 sin 시 son errores.',
      'Honneur du sujet (주체높임) : 이/가 → 께서 va avec -(으)시- → 하셨어요. Garder 이, passer au datif 께 ou 께서 sans 시 sont faux.',
      'Honra ao sujeito (주체높임): 이/가 → 께서 combina com -(으)시- → 하셨어요. Manter 이, trocar pelo dativo 께 ou 께서 sem 시 estão errados.',
      'ยกย่องประธาน (주체높임): 이/가 → 께서 ใช้คู่กับ -(으)시- → 하셨어요 การคง 이 เปลี่ยนเป็น 께 (รูปกรรมรอง) หรือ 께서 ที่ไม่มี 시 ล้วนผิด',
      'Hormat subjek (주체높임): 이/가 → 께서 berpasangan dengan -(으)시- → 하셨어요. Tetap 이, ganti ke datif 께, atau 께서 tanpa 시 semuanya salah.',
      'Tôn kính chủ ngữ (주체높임): 이/가 → 께서 đi với -(으)시- → 하셨어요. Giữ 이, đổi sang 께 (tặng cách), hoặc 께서 mà thiếu 시 đều sai.',
      '主語の尊敬（주체높임）：이/가 → 께서は-(으)시- → 하셨어요と対応。이のまま、与格の께に替える、시の無い께서はいずれも誤り。',
    ),
  },
  {
    source: '저는 교수님에게 질문을 물어봤어요.',
    mode: 'honor',
    target: 'polite',
    set: 'particle',
    answer: '저는 교수님께 질문을 여쭤봤어요.',
    distractors: [
      '저는 교수님에게 질문을 여쭤봤어요.',
      '저는 교수님께 질문을 물어봤어요.',
      '저는 교수님께서 질문을 여쭤봤어요.',
    ],
    trans: L(
      'I asked the professor a question.',
      'Le hice una pregunta al profesor.',
      "J'ai posé une question au professeur.",
      'Eu fiz uma pergunta ao professor.',
      'ฉันถามคำถามกับอาจารย์',
      'Saya mengajukan pertanyaan kepada profesor.',
      'Tôi đã hỏi giáo sư một câu hỏi.',
      '私は教授に質問をお伺いしました。',
    ),
    why: L(
      'Object humbling (객체높임/겸양): 에게 → 께 pairs with the humble verb 묻다/물어보다 → 여쭤보다. Keeping 에게, keeping plain 물어보다, or using subject-marker 께서 on the addressee are all wrong.',
      'Humillación del objeto (객체높임/겸양): 에게 → 께 va con el verbo humilde 묻다/물어보다 → 여쭤보다. Mantener 에게, mantener 물어보다 simple o usar 께서 (sujeto) en el interlocutor son errores.',
      "Humilité envers l'objet (객체높임/겸양) : 에게 → 께 va avec le verbe humble 묻다/물어보다 → 여쭤보다. Garder 에게, garder 물어보다 ordinaire ou mettre 께서 (sujet) sur l'interlocuteur sont faux.",
      'Humildade ao objeto (객체높임/겸양): 에게 → 께 combina com o verbo humilde 묻다/물어보다 → 여쭤보다. Manter 에게, manter 물어보다 comum ou usar 께서 (sujeito) no interlocutor estão errados.',
      'ถ่อมตนต่อกรรม (객체높임/겸양): 에게 → 께 ใช้คู่กับคำกริยาถ่อมตน 묻다/물어보다 → 여쭤보다 การคง 에게 คง 물어보다 ธรรมดา หรือใช้ 께서 (รูปประธาน) กับคู่สนทนา ล้วนผิด',
      'Merendah pada objek (객체높임/겸양): 에게 → 께 berpasangan dengan verba merendah 묻다/물어보다 → 여쭤보다. Tetap 에게, tetap 물어보다 biasa, atau pakai 께서 (subjek) pada lawan bicara semuanya salah.',
      'Khiêm nhường với tân ngữ (객체높임/겸양): 에게 → 께 đi với động từ khiêm nhường 묻다/물어보다 → 여쭤보다. Giữ 에게, giữ 물어보다 thường, hoặc dùng 께서 (chủ ngữ) cho người nghe đều sai.',
      '客体の謙譲（객체높임/겸양）：에게 → 께は謙譲動詞묻다/물어보다 → 여쭤보다と対応。에게のまま、普通の물어보다のまま、相手に主語標識께서を付けるのはいずれも誤り。',
    ),
  },
  {
    source: '할머니가 선물을 받아요.',
    mode: 'honor',
    target: 'polite',
    set: 'si',
    answer: '할머니께서 선물을 받으세요.',
    distractors: [
      '할머니가 선물을 받아요.',
      '할머니께서 선물을 받세요.',
      '할머니께서 선물을 받으십니다.',
    ],
    trans: L(
      'Grandmother receives a gift.',
      'La abuela recibe un regalo.',
      'Grand-mère reçoit un cadeau.',
      'A avó recebe um presente.',
      'คุณยายรับของขวัญ',
      'Nenek menerima hadiah.',
      'Bà nhận một món quà.',
      'おばあさんがプレゼントを受け取られます。',
    ),
    why: L(
      '받다 is a regular verb (no suppletion): 이/가 → 께서 and the consonant stem takes epenthetic -(으)시- → 받으세요 (not 받세요, not plain 받아요; 받으십니다 is 합쇼체, wrong level for polite).',
      '받다 es un verbo regular (sin supleción): 이/가 → 께서 y la raíz consonántica toma la -(으)시- epentética → 받으세요 (no 받세요, ni el llano 받아요; 받으십니다 es 합쇼체, nivel incorrecto).',
      '받다 est régulier (pas de supplétion) : 이/가 → 께서 et le radical consonantique prend le -(으)시- épenthétique → 받으세요 (pas 받세요, ni le neutre 받아요 ; 받으십니다 est du 합쇼체, mauvais niveau).',
      '받다 é regular (sem supleção): 이/가 → 께서 e o radical consonantal recebe o -(으)시- epentético → 받으세요 (não 받세요, nem o neutro 받아요; 받으십니다 é 합쇼체, nível errado).',
      '받다 เป็นกริยาปกติ (ไม่มีรูปพิเศษ): 이/가 → 께서 และก้านพยัญชนะเติม -(으)시- → 받으세요 (ไม่ใช่ 받세요 หรือ 받아요 ธรรมดา; 받으십니다 เป็น 합쇼체 ระดับผิด)',
      '받다 verba reguler (tanpa supletif): 이/가 → 께서 dan batang berkonsonan memakai -(으)시- epentetik → 받으세요 (bukan 받세요, bukan 받아요 biasa; 받으십니다 itu 합쇼체, tingkat salah).',
      '받다 là động từ thường (không có dạng thay thế): 이/가 → 께서 và thân kết thúc phụ âm thêm -(으)시- → 받으세요 (không phải 받세요, không phải 받아요 thường; 받으십니다 là 합쇼체, sai cấp độ).',
      '받다は規則動詞（補充法なし）：이/가 → 께서、子音語幹は媒介母音付きの-(으)시-で받으세요（받세요でも素の받아요でもない。받으십니다は합쇼체で待遇レベルが誤り）。',
    ),
  },
  {
    source: '할아버지가 공원에 가요.',
    mode: 'honor',
    target: 'polite',
    set: 'si',
    answer: '할아버지께서 공원에 가세요.',
    distractors: [
      '할아버지가 공원에 가요.',
      '할아버지께서 공원에 가으세요.',
      '할아버지께서 공원에 가십니다.',
    ],
    trans: L(
      'Grandfather goes to the park.',
      'El abuelo va al parque.',
      'Grand-père va au parc.',
      'O avô vai ao parque.',
      'คุณปู่ไปสวนสาธารณะ',
      'Kakek pergi ke taman.',
      'Ông đi đến công viên.',
      'おじいさんが公園に行かれます。',
    ),
    why: L(
      '가다 is regular: 이/가 → 께서 and the vowel stem takes -시- with NO 으 → 가세요 (가으세요 wrong epenthesis; plain 가요 has no 시; 가십니다 is 합쇼체, wrong level for polite).',
      '가다 es regular: 이/가 → 께서 y la raíz vocálica toma -시- SIN 으 → 가세요 (가으세요 epéntesis errónea; el llano 가요 no lleva 시; 가십니다 es 합쇼체, nivel incorrecto).',
      "가다 est régulier : 이/가 → 께서 et le radical vocalique prend -시- SANS 으 → 가세요 (가으세요 mauvaise épenthèse ; le neutre 가요 n'a pas de 시 ; 가십니다 est du 합쇼체, mauvais niveau).",
      '가다 é regular: 이/가 → 께서 e o radical vocálico recebe -시- SEM 으 → 가세요 (가으세요 epêntese errada; o neutro 가요 não tem 시; 가십니다 é 합쇼체, nível errado).',
      '가다 ปกติ: 이/가 → 께서 และก้านสระเติม -시- โดยไม่มี 으 → 가세요 (가으세요 เติม 으 ผิด; 가요 ธรรมดาไม่มี 시; 가십니다 เป็น 합쇼체 ระดับผิด)',
      '가다 reguler: 이/가 → 께서 dan batang vokal memakai -시- TANPA 으 → 가세요 (가으세요 epentesis salah; 가요 biasa tanpa 시; 가십니다 itu 합쇼체, tingkat salah).',
      '가다 thường: 이/가 → 께서 và thân nguyên âm dùng -시- KHÔNG có 으 → 가세요 (가으세요 thêm 으 sai; 가요 thường không có 시; 가십니다 là 합쇼체, sai cấp độ).',
      '가다は規則：이/가 → 께서、母音語幹は으なしの-시-で가세요（가으세요は媒介母音の誤付加、素の가요には시が無い。가십니다は합쇼체で待遇レベルが誤り）。',
    ),
  },
  {
    source: '선생님이 의자에 앉아요.',
    mode: 'honor',
    target: 'polite',
    set: 'si',
    answer: '선생님께서 의자에 앉으세요.',
    distractors: [
      '선생님이 의자에 앉아요.',
      '선생님께서 의자에 앉세요.',
      '선생님께서 의자에 앉으십니다.',
    ],
    trans: L(
      'The teacher sits on the chair.',
      'El profesor se sienta en la silla.',
      "Le professeur s'assoit sur la chaise.",
      'O professor se senta na cadeira.',
      'คุณครูนั่งบนเก้าอี้',
      'Guru duduk di kursi.',
      'Thầy giáo ngồi trên ghế.',
      '先生が椅子にお座りになります。',
    ),
    why: L(
      '앉다 is regular: 이/가 → 께서 and the consonant stem takes epenthetic -(으)시- → 앉으세요 (앉세요 drops the required 으; plain 앉아요 has no 시; 앉으십니다 is 합쇼체, wrong level for polite).',
      '앉다 es regular: 이/가 → 께서 y la raíz consonántica toma la -(으)시- epentética → 앉으세요 (앉세요 omite el 으 obligatorio; el llano 앉아요 no lleva 시; 앉으십니다 es 합쇼체, nivel incorrecto).',
      "앉다 est régulier : 이/가 → 께서 et le radical consonantique prend le -(으)시- épenthétique → 앉으세요 (앉세요 omet le 으 requis ; le neutre 앉아요 n'a pas de 시 ; 앉으십니다 est du 합쇼체, mauvais niveau).",
      '앉다 é regular: 이/가 → 께서 e o radical consonantal recebe o -(으)시- epentético → 앉으세요 (앉세요 omite o 으 obrigatório; o neutro 앉아요 não tem 시; 앉으십니다 é 합쇼체, nível errado).',
      '앉다 ปกติ: 이/가 → 께서 และก้านพยัญชนะเติม -(으)시- → 앉으세요 (앉세요 ตัด 으 ที่ต้องมีออก; 앉아요 ธรรมดาไม่มี 시; 앉으십니다 เป็น 합쇼체 ระดับผิด)',
      '앉다 reguler: 이/가 → 께서 dan batang berkonsonan memakai -(으)시- epentetik → 앉으세요 (앉세요 menghapus 으 yang wajib; 앉아요 biasa tanpa 시; 앉으십니다 itu 합쇼체, tingkat salah).',
      '앉다 thường: 이/가 → 께서 và thân kết thúc phụ âm thêm -(으)시- → 앉으세요 (앉세요 bỏ mất 으 bắt buộc; 앉아요 thường không có 시; 앉으십니다 là 합쇼체, sai cấp độ).',
      '앉다は規則：이/가 → 께서、子音語幹は媒介母音付きの-(으)시-で앉으세요（앉세요は必要な으の脱落、素の앉아요には시が無い。앉으십니다は합쇼체で待遇レベルが誤り）。',
    ),
  },
  {
    source: '사장님이 한복을 입어요.',
    mode: 'honor',
    target: 'formal',
    set: 'si',
    answer: '사장님께서 한복을 입으십니다.',
    distractors: [
      '사장님이 한복을 입습니다.',
      '사장님께서 한복을 입십니다.',
      '사장님께서 한복을 입으세요.',
    ],
    trans: L(
      'The boss wears a hanbok.',
      'El jefe lleva un hanbok.',
      'Le patron porte un hanbok.',
      'O chefe veste um hanbok.',
      'ท่านประธานสวมชุดฮันบก',
      'Bos memakai hanbok.',
      'Giám đốc mặc hanbok.',
      '社長がハンボクをお召しになります。',
    ),
    why: L(
      '입다 is regular: 합쇼체 needs 이/가 → 께서 with epenthetic -(으)시- + -ㅂ니다 → 입으십니다 (입십니다 drops 으; 입습니다 has no 시 nor 께서; 입으세요 is 해요체, wrong level for formal).',
      '입다 es regular: 합쇼체 requiere 이/가 → 께서 con -(으)시- epentética + -ㅂ니다 → 입으십니다 (입십니다 omite 으; 입습니다 no lleva 시 ni 께서; 입으세요 es 해요체, nivel incorrecto).',
      "입다 est régulier : le 합쇼체 exige 이/가 → 께서 avec -(으)시- épenthétique + -ㅂ니다 → 입으십니다 (입십니다 omet le 으 ; 입습니다 n'a ni 시 ni 께서 ; 입으세요 est du 해요체, mauvais niveau).",
      '입다 é regular: o 합쇼체 exige 이/가 → 께서 com -(으)시- epentético + -ㅂ니다 → 입으십니다 (입십니다 omite o 으; 입습니다 não tem 시 nem 께서; 입으세요 é 해요체, nível errado).',
      '입다 ปกติ: 합쇼체 ต้องใช้ 이/가 → 께서 กับ -(으)시- + -ㅂ니다 → 입으십니다 (입십니다 ตัด 으; 입습니다 ไม่มี 시 และ 께서; 입으세요 เป็น 해요체 ระดับผิด)',
      '입다 reguler: 합쇼체 butuh 이/가 → 께서 dengan -(으)시- epentetik + -ㅂ니다 → 입으십니다 (입십니다 menghapus 으; 입습니다 tanpa 시 dan 께서; 입으세요 itu 해요체, tingkat salah).',
      '입다 thường: 합쇼체 cần 이/가 → 께서 với -(으)시- + -ㅂ니다 → 입으십니다 (입십니다 bỏ 으; 입습니다 thiếu 시 và 께서; 입으세요 là 해요체, sai cấp độ).',
      '입다は規則：합쇼체は이/가 → 께서と媒介母音付き-(으)시-+-ㅂ니다で입으십니다（입십니다は으の脱落、입습니다は시も께서も無い、입으세요は해요체で待遇レベルが誤り）。',
    ),
  },
  {
    source: '손님이 가게에서 옷을 입어요.',
    mode: 'honor',
    target: 'polite',
    set: 'si',
    answer: '손님께서 가게에서 옷을 입으세요.',
    distractors: [
      '손님이 가게에서 옷을 입어요.',
      '손님께서 가게에서 옷을 입세요.',
      '손님께서 가게에서 옷을 입으십니다.',
    ],
    trans: L(
      'The customer puts on clothes at the shop.',
      'El cliente se pone ropa en la tienda.',
      'Le client met des vêtements au magasin.',
      'O cliente veste roupas na loja.',
      'ลูกค้าสวมเสื้อผ้าที่ร้าน',
      'Pelanggan memakai baju di toko.',
      'Khách mặc thử quần áo ở cửa hàng.',
      'お客様が店で服を着られます。',
    ),
    why: L(
      '입다 is regular: 이/가 → 께서 and the consonant stem takes epenthetic -(으)시- → 입으세요 (입세요 drops the required 으; plain 입어요 has no 시; 입으십니다 is 합쇼체, wrong level for polite).',
      '입다 es regular: 이/가 → 께서 y la raíz consonántica toma la -(으)시- epentética → 입으세요 (입세요 omite el 으 obligatorio; el llano 입어요 no lleva 시; 입으십니다 es 합쇼체, nivel incorrecto).',
      "입다 est régulier : 이/가 → 께서 et le radical consonantique prend le -(으)시- épenthétique → 입으세요 (입세요 omet le 으 requis ; le neutre 입어요 n'a pas de 시 ; 입으십니다 est du 합쇼체, mauvais niveau).",
      '입다 é regular: 이/가 → 께서 e o radical consonantal recebe o -(으)시- epentético → 입으세요 (입세요 omite o 으 obrigatório; o neutro 입어요 não tem 시; 입으십니다 é 합쇼체, nível errado).',
      '입다 ปกติ: 이/가 → 께서 และก้านพยัญชนะเติม -(으)시- → 입으세요 (입세요 ตัด 으 ที่ต้องมีออก; 입어요 ธรรมดาไม่มี 시; 입으십니다 เป็น 합쇼체 ระดับผิด)',
      '입다 reguler: 이/가 → 께서 dan batang berkonsonan memakai -(으)시- epentetik → 입으세요 (입세요 menghapus 으 yang wajib; 입어요 biasa tanpa 시; 입으십니다 itu 합쇼체, tingkat salah).',
      '입다 thường: 이/가 → 께서 và thân kết thúc phụ âm thêm -(으)시- → 입으세요 (입세요 bỏ mất 으 bắt buộc; 입어요 thường không có 시; 입으십니다 là 합쇼체, sai cấp độ).',
      '입다は規則：이/가 → 께서、子音語幹は媒介母音付きの-(으)시-で입으세요（입세요は必要な으の脱落、素の입어요には시が無い。입으십니다は합쇼체で待遇レベルが誤り）。',
    ),
  },
  {
    source: '교수님이 학생을 만나요.',
    mode: 'honor',
    target: 'polite',
    set: 'si',
    answer: '교수님께서 학생을 만나세요.',
    distractors: [
      '교수님이 학생을 만나요.',
      '교수님께서 학생을 만나으세요.',
      '교수님께서 학생을 만나십니다.',
    ],
    trans: L(
      'The professor meets the student.',
      'El profesor se reúne con el estudiante.',
      "Le professeur rencontre l'étudiant.",
      'O professor encontra o aluno.',
      'ศาสตราจารย์พบนักศึกษา',
      'Profesor menemui mahasiswa.',
      'Giáo sư gặp sinh viên.',
      '教授が学生にお会いになります。',
    ),
    why: L(
      '만나다 is regular: 이/가 → 께서 and the vowel stem 만나- takes -시- with NO 으 → 만나세요 (만나으세요 wrong epenthesis; plain 만나요 has no 시; 만나십니다 is 합쇼체, wrong level for polite).',
      '만나다 es regular: 이/가 → 께서 y la raíz vocálica 만나- toma -시- SIN 으 → 만나세요 (만나으세요 epéntesis errónea; el llano 만나요 no lleva 시; 만나십니다 es 합쇼체, nivel incorrecto).',
      "만나다 est régulier : 이/가 → 께서 et le radical vocalique 만나- prend -시- SANS 으 → 만나세요 (만나으세요 mauvaise épenthèse ; le neutre 만나요 n'a pas de 시 ; 만나십니다 est du 합쇼체, mauvais niveau).",
      '만나다 é regular: 이/가 → 께서 e o radical vocálico 만나- recebe -시- SEM 으 → 만나세요 (만나으세요 epêntese errada; o neutro 만나요 não tem 시; 만나십니다 é 합쇼체, nível errado).',
      '만나다 ปกติ: 이/가 → 께서 และก้านสระ 만나- เติม -시- โดยไม่มี 으 → 만나세요 (만나으세요 เติม 으 ผิด; 만나요 ธรรมดาไม่มี 시; 만나십니다 เป็น 합쇼체 ระดับผิด)',
      '만나다 reguler: 이/가 → 께서 dan batang vokal 만나- memakai -시- TANPA 으 → 만나세요 (만나으세요 epentesis salah; 만나요 biasa tanpa 시; 만나십니다 itu 합쇼체, tingkat salah).',
      '만나다 thường: 이/가 → 께서 và thân nguyên âm 만나- dùng -시- KHÔNG có 으 → 만나세요 (만나으세요 thêm 으 sai; 만나요 thường không có 시; 만나십니다 là 합쇼체, sai cấp độ).',
      '만나다は規則：이/가 → 께서、母音語幹만나-は으なしの-시-で만나세요（만나으세요は媒介母音の誤付加、素の만나요には시が無い。만나십니다は합쇼체で待遇レベルが誤り）。',
    ),
  },
]
