// app/seed/register-transform/level-extra.ts
import type { RegisterItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * Extra speech-level transform items (반말 ↔ 해요체 ↔ 합쇼체), neutral subject.
 * Drafted + Korean-lens adversarially verified (single-correct-answer, no self-honorification,
 * plausible-wrong distractors, 8-locale). Korean wife native review = documented final gate.
 */

export const LEVEL_EXTRA: RegisterItem[] = [
  {
    source: '저는 한국어를 배워요.',
    mode: 'level',
    target: 'formal',
    set: 'formal',
    answer: '저는 한국어를 배웁니다.',
    distractors: [
      '저는 한국어를 배워.',
      '나는 한국어를 배웁니다.',
      '저는 한국어를 배우십니다.',
    ],
    trans: L(
      'I learn Korean.',
      'Aprendo coreano.',
      "J'apprends le coréen.",
      'Eu aprendo coreano.',
      'ฉันเรียนภาษาเกาหลี',
      'Saya belajar bahasa Korea.',
      'Tôi học tiếng Hàn.',
      '私は韓国語を学んでいます。',
    ),
    why: L(
      '합쇼체 uses -ㅂ니다 on a vowel stem: 배우다 → 배웁니다; keep 저 (not 나) and never self-honorify your own action with -(으)시- (배우십니다).',
      '합쇼체 usa -ㅂ니다 en raíz vocálica: 배우다 → 배웁니다; mantén 저 (no 나) y nunca te auto-honres con -(으)시- (배우십니다).',
      "합쇼체 emploie -ㅂ니다 sur radical vocalique : 배우다 → 배웁니다 ; garde 저 (pas 나) et ne t'auto-honore jamais avec -(으)시- (배우십니다).",
      '합쇼체 usa -ㅂ니다 em raiz vocálica: 배우다 → 배웁니다; mantenha 저 (não 나) e nunca se auto-honre com -(으)시- (배우십니다).',
      '합쇼체 ใช้ -ㅂ니다 กับก้านเสียงสระ: 배우다 → 배웁니다; คง 저 (ไม่ใช่ 나) และห้ามยกย่องตัวเองด้วย -(으)시- (배우십니다)',
      '합쇼체 memakai -ㅂ니다 pada akar vokal: 배우다 → 배웁니다; tetap 저 (bukan 나) dan jangan menghormati diri sendiri dengan -(으)시- (배우십니다).',
      '합쇼체 dùng -ㅂ니다 với gốc nguyên âm: 배우다 → 배웁니다; giữ 저 (không phải 나) và đừng tự tôn kính bằng -(으)시- (배우십니다).',
      '합쇼체は母音語幹に-ㅂ니다：배우다 → 배웁니다。저のまま（나にしない）、自分の動作に-(으)시-を付けない（배우십니다）。',
    ),
  },
  {
    source: '저는 약속을 잊었어요.',
    mode: 'level',
    target: 'formal',
    set: 'formal',
    answer: '저는 약속을 잊었습니다.',
    distractors: [
      '저는 약속을 잊었어.',
      '나는 약속을 잊었습니다.',
      '저는 약속을 잊으셨습니다.',
    ],
    trans: L(
      'I forgot the appointment.',
      'Olvidé la cita.',
      "J'ai oublié le rendez-vous.",
      'Eu esqueci o compromisso.',
      'ฉันลืมนัด',
      'Saya lupa janji itu.',
      'Tôi đã quên cuộc hẹn.',
      '私は約束を忘れました。',
    ),
    why: L(
      'Past tense -었- plus consonant 받침 takes -습니다: 잊었- → 잊었습니다; keep 저 and do not add -(으)시- to yourself (잊으셨습니다 honors the speaker).',
      'El pasado -었- con 받침 consonántico toma -습니다: 잊었- → 잊었습니다; mantén 저 y no añadas -(으)시- a ti mismo (잊으셨습니다 honra al hablante).',
      'Le passé -었- avec 받침 consonantique prend -습니다 : 잊었- → 잊었습니다 ; garde 저 et n\'ajoute pas -(으)시- à toi-même (잊으셨습니다 honore le locuteur).',
      'O passado -었- com 받침 consonantal leva -습니다: 잊었- → 잊었습니다; mantenha 저 e não acrescente -(으)시- a si (잊으셨습니다 honra o falante).',
      'อดีต -었- ที่มี 받침 พยัญชนะใช้ -습니다: 잊었- → 잊었습니다; คง 저 และอย่าเติม -(으)시- ให้ตนเอง (잊으셨습니다 ยกย่องผู้พูด)',
      'Lampau -었- dengan 받침 konsonan memakai -습니다: 잊었- → 잊었습니다; tetap 저 dan jangan tambah -(으)시- pada diri (잊으셨습니다 menghormati penutur).',
      'Quá khứ -었- với 받침 phụ âm dùng -습니다: 잊었- → 잊었습니다; giữ 저 và đừng thêm -(으)시- cho mình (잊으셨습니다 tôn kính người nói).',
      '過去-었-で子音받침は-습니다：잊었- → 잊었습니다。저のまま、自分に-(으)시-を付けない（잊으셨습니다は話し手を敬う誤り）。',
    ),
  },
  {
    source: '저는 내일 부산에 가요.',
    mode: 'level',
    target: 'formal',
    set: 'formal',
    answer: '저는 내일 부산에 갑니다.',
    distractors: [
      '저는 내일 부산에 가.',
      '나는 내일 부산에 갑니다.',
      '저는 내일 부산에 가십니다.',
    ],
    trans: L(
      "I'm going to Busan tomorrow.",
      'Mañana voy a Busan.',
      'Demain je vais à Busan.',
      'Amanhã eu vou a Busan.',
      'พรุ่งนี้ฉันจะไปปูซาน',
      'Besok saya pergi ke Busan.',
      'Ngày mai tôi đi Busan.',
      '私は明日釜山へ行きます。',
    ),
    why: L(
      'Vowel stem 가다 → 갑니다 in 합쇼체 (-ㅂ니다 attaches directly); keep 저 (not 나) and never -(으)시- on yourself (가십니다 self-honorifies the speaker).',
      'Raíz vocálica 가다 → 갑니다 en 합쇼체 (se añade -ㅂ니다 directamente); mantén 저 (no 나) y nunca -(으)시- sobre ti (가십니다 se auto-honra).',
      'Radical vocalique 가다 → 갑니다 en 합쇼체 (-ㅂ니다 s\'attache directement) ; garde 저 (pas 나) et jamais -(으)시- sur toi-même (가십니다 s\'auto-honore).',
      'Raiz vocálica 가다 → 갑니다 no 합쇼체 (-ㅂ니다 se anexa diretamente); mantenha 저 (não 나) e nunca -(으)시- em si (가십니다 auto-honra).',
      'ก้านเสียงสระ 가다 → 갑니다 ใน 합쇼체 (เติม -ㅂ니다 ตรง ๆ); คง 저 (ไม่ใช่ 나) และห้าม -(으)시- กับตนเอง (가십니다 คือยกย่องตัวเอง)',
      'Akar vokal 가다 → 갑니다 dalam 합쇼체 (-ㅂ니다 melekat langsung); tetap 저 (bukan 나) dan jangan -(으)시- pada diri (가십니다 menghormati diri).',
      'Gốc nguyên âm 가다 → 갑니다 trong 합쇼체 (-ㅂ니다 gắn trực tiếp); giữ 저 (không phải 나) và đừng -(으)시- với bản thân (가십니다 là tự tôn kính).',
      '母音語幹가다 → 갑니다（합쇼체、-ㅂ니다が直接付く）。저のまま（나にしない）、自分に-(으)시-を付けない（가십니다は自敬）。',
    ),
  },
  {
    source: '저는 음악을 자주 듣습니다.',
    mode: 'level',
    target: 'polite',
    set: 'polite',
    answer: '저는 음악을 자주 들어요.',
    distractors: [
      '저는 음악을 자주 듣습니다.',
      '저는 음악을 자주 들어.',
      '저는 음악을 자주 듣어요.',
    ],
    trans: L(
      'I often listen to music.',
      'Escucho música a menudo.',
      "J'écoute souvent de la musique.",
      'Eu escuto música com frequência.',
      'ฉันฟังเพลงบ่อย ๆ',
      'Saya sering mendengarkan musik.',
      'Tôi thường nghe nhạc.',
      '私はよく音楽を聞きます。',
    ),
    why: L(
      '듣다 is a ㄷ-irregular: stem ㄷ → ㄹ before 어요, so 듣다 → 들어요 (해요체); 듣어요 keeps the ㄷ and is wrong, and keep 저.',
      '듣다 es ㄷ-irregular: la ㄷ del radical → ㄹ ante 어요, así 듣다 → 들어요 (해요체); 듣어요 conserva la ㄷ y es incorrecto; mantén 저.',
      '듣다 est un verbe en ㄷ irrégulier : ㄷ du radical → ㄹ devant 어요, donc 듣다 → 들어요 (해요체) ; 듣어요 garde le ㄷ et est faux ; garde 저.',
      '듣다 é ㄷ-irregular: ㄷ do radical → ㄹ antes de 어요, então 듣다 → 들어요 (해요체); 듣어요 mantém o ㄷ e é errado; mantenha 저.',
      '듣다 เป็นกริยาผัน ㄷ ไม่ปกติ: ㄷ ของก้าน → ㄹ หน้า 어요 จึง 듣다 → 들어요 (해요체); 듣어요 คง ㄷ ไว้จึงผิด และคง 저',
      '듣다 adalah ㄷ-tak beraturan: ㄷ akar → ㄹ sebelum 어요, jadi 듣다 → 들어요 (해요체); 듣어요 mempertahankan ㄷ dan salah; tetap 저.',
      '듣다 là bất quy tắc ㄷ: ㄷ của gốc → ㄹ trước 어요, nên 듣다 → 들어요 (해요체); 듣어요 giữ ㄷ nên sai; giữ 저.',
      '듣다はㄷ不規則：語幹のㄷが어요の前でㄹに変わり듣다 → 들어요（해요체）。듣어요はㄷを残すので誤り、저のまま。',
    ),
  },
  {
    source: '나 어제 친구를 만났어.',
    mode: 'level',
    target: 'polite',
    set: 'polite',
    answer: '저 어제 친구를 만났어요.',
    distractors: [
      '나 어제 친구를 만났어.',
      '저 어제 친구를 만났습니다.',
      '나 어제 친구를 만났어요.',
    ],
    trans: L(
      'I met a friend yesterday.',
      'Ayer me encontré con un amigo.',
      "Hier j'ai rencontré un ami.",
      'Ontem eu encontrei um amigo.',
      'เมื่อวานฉันเจอเพื่อน',
      'Kemarin saya bertemu teman.',
      'Hôm qua tôi gặp một người bạn.',
      '昨日友達に会いました。',
    ),
    why: L(
      '해요체 adds 요 to 반말 past 만났어 → 만났어요; raising the level shifts 나 → 저 (polite 1st-person pronoun).',
      'El 해요체 añade 요 al pasado 반말 만났어 → 만났어요; subir el nivel cambia 나 → 저 (pronombre de 1ª persona cortés).',
      'Le 해요체 ajoute 요 au passé 반말 만났어 → 만났어요 ; monter le niveau fait passer 나 → 저 (pronom poli de 1re personne).',
      'O 해요체 acrescenta 요 ao passado 반말 만났어 → 만났어요; elevar o nível muda 나 → 저 (pronome de 1ª pessoa polido).',
      '해요체 เติม 요 ให้อดีต 반말 만났어 → 만났어요 และการยกระดับเปลี่ยน 나 → 저 (สรรพนามบุรุษที่ 1 แบบสุภาพ)',
      '해요체 menambah 요 pada lampau 반말 만났어 → 만났어요; menaikkan tingkat mengubah 나 → 저 (kata ganti orang pertama sopan).',
      '해요체 thêm 요 vào quá khứ 반말 만났어 → 만났어요; nâng cấp độ đổi 나 → 저 (đại từ ngôi thứ nhất lịch sự).',
      '해요체は반말過去の만났어に요を付ける → 만났어요。レベルを上げると나 → 저（丁寧な一人称代名詞）。',
    ),
  },
  {
    source: '오늘 일이 너무 바쁩니다.',
    mode: 'level',
    target: 'polite',
    set: 'polite',
    answer: '오늘 일이 너무 바빠요.',
    distractors: [
      '오늘 일이 너무 바쁩니다.',
      '오늘 일이 너무 바빠.',
      '오늘 일이 너무 바쁘어요.',
    ],
    trans: L(
      "Work is so busy today.",
      'Hoy el trabajo está muy ocupado.',
      "Aujourd'hui le travail est très chargé.",
      'Hoje o trabalho está muito corrido.',
      'วันนี้งานยุ่งมาก',
      'Hari ini pekerjaan sangat sibuk.',
      'Hôm nay công việc rất bận.',
      '今日は仕事がとても忙しいです。',
    ),
    why: L(
      '바쁘다 is a 으-irregular: the 으 drops before 아요 (stem vowel ㅏ), so 바쁘다 → 바빠요 (해요체); 바쁘어요 keeps the 으 and is wrong.',
      '바쁘다 es 으-irregular: la 으 cae ante 아요 (vocal del radical ㅏ), así 바쁘다 → 바빠요 (해요체); 바쁘어요 conserva la 으 y es incorrecto.',
      '바쁘다 est un verbe en 으 irrégulier : le 으 tombe devant 아요 (voyelle du radical ㅏ), donc 바쁘다 → 바빠요 (해요체) ; 바쁘어요 garde le 으 et est faux.',
      '바쁘다 é 으-irregular: o 으 cai antes de 아요 (vogal do radical ㅏ), então 바쁘다 → 바빠요 (해요체); 바쁘어요 mantém o 으 e é errado.',
      '바쁘다 เป็นกริยาผัน 으 ไม่ปกติ: 으 หลุดหน้า 아요 (สระก้าน ㅏ) จึง 바쁘다 → 바빠요 (해요체); 바쁘어요 คง 으 ไว้จึงผิด',
      '바쁘다 adalah 으-tak beraturan: 으 luruh sebelum 아요 (vokal akar ㅏ), jadi 바쁘다 → 바빠요 (해요체); 바쁘어요 mempertahankan 으 dan salah.',
      '바쁘다 là bất quy tắc 으: 으 rụng trước 아요 (nguyên âm gốc ㅏ), nên 바쁘다 → 바빠요 (해요체); 바쁘어요 giữ 으 nên sai.',
      '바쁘다は으不規則：語幹母音ㅏの아요の前で으が落ち바쁘다 → 바빠요（해요체）。바쁘어요は으を残すので誤り。',
    ),
  },
  {
    source: '저는 매운 음식을 잘 먹어요.',
    mode: 'level',
    target: 'casual',
    set: 'casual',
    answer: '나는 매운 음식을 잘 먹어.',
    distractors: [
      '저는 매운 음식을 잘 먹어요.',
      '저는 매운 음식을 잘 먹습니다.',
      '나는 매운 음식을 잘 먹는다.',
    ],
    trans: L(
      'I can eat spicy food well.',
      'Como bien la comida picante.',
      'Je mange bien la nourriture épicée.',
      'Eu como bem comida apimentada.',
      'ฉันกินอาหารเผ็ดได้ดี',
      'Saya pandai makan makanan pedas.',
      'Tôi ăn đồ cay khá tốt.',
      '私は辛い食べ物をよく食べる。',
    ),
    why: L(
      '반말 (해체) drops 요 and 저→나: 먹어요 → 먹어. (먹는다 is 한다체 writing style, not spoken 반말.)',
      '반말 (해체) quita 요 y 저→나: 먹어요 → 먹어. (먹는다 es estilo escrito 한다체, no 반말 hablado.)',
      '반말 (해체) enlève 요 et 저→나 : 먹어요 → 먹어. (먹는다 est le style écrit 한다체, pas le 반말 parlé.)',
      '반말 (해체) tira 요 e 저→나: 먹어요 → 먹어. (먹는다 é estilo escrito 한다체, não 반말 falado.)',
      '반말 (해체) ตัด 요 ออกและ 저→나: 먹어요 → 먹어 (먹는다 เป็นสไตล์เขียน 한다체 ไม่ใช่ 반말 ที่พูดกัน)',
      '반말 (해체) menghapus 요 dan 저→나: 먹어요 → 먹어. (먹는다 gaya tulis 한다체, bukan 반말 lisan.)',
      '반말 (해체) bỏ 요 và 저→나: 먹어요 → 먹어. (먹는다 là văn viết 한다체, không phải 반말 nói.)',
      '반말（해체）は요を落とし저→나：먹어요 → 먹어。（먹는다は한다체の書き言葉で、話し言葉の반말ではない。）',
    ),
  },
  {
    source: '저는 노래를 잘 못해요.',
    mode: 'level',
    target: 'casual',
    set: 'casual',
    answer: '나는 노래를 잘 못해.',
    distractors: [
      '저는 노래를 잘 못해요.',
      '저는 노래를 잘 못합니다.',
      '나는 노래를 잘 못한다.',
    ],
    trans: L(
      "I'm not good at singing.",
      'No canto bien.',
      'Je ne chante pas bien.',
      'Eu não canto bem.',
      'ฉันร้องเพลงไม่เก่ง',
      'Saya tidak pandai menyanyi.',
      'Tôi hát không hay.',
      '私は歌が下手だ。',
    ),
    why: L(
      '반말 (해체) drops 요 and 저→나: 하다 → 해, so 못해요 → 못해. (못한다 is 한다체 writing style, not spoken 반말.)',
      '반말 (해체) quita 요 y 저→나: 하다 → 해, así 못해요 → 못해. (못한다 es estilo escrito 한다체, no 반말 hablado.)',
      '반말 (해체) enlève 요 et 저→나 : 하다 → 해, donc 못해요 → 못해. (못한다 est le style écrit 한다체, pas le 반말 parlé.)',
      '반말 (해체) tira 요 e 저→나: 하다 → 해, então 못해요 → 못해. (못한다 é estilo escrito 한다체, não 반말 falado.)',
      '반말 (해체) ตัด 요 ออกและ 저→나: 하다 → 해 จึง 못해요 → 못해 (못한다 เป็นสไตล์เขียน 한다체 ไม่ใช่ 반말 ที่พูดกัน)',
      '반말 (해체) menghapus 요 dan 저→나: 하다 → 해, jadi 못해요 → 못해. (못한다 gaya tulis 한다체, bukan 반말 lisan.)',
      '반말 (해체) bỏ 요 và 저→나: 하다 → 해, nên 못해요 → 못해. (못한다 là văn viết 한다체, không phải 반말 nói.)',
      '반말（해체）は요を落とし저→나：하다 → 해なので못해요 → 못해。（못한다は한다체の書き言葉で、話し言葉の반말ではない。）',
    ),
  },
  {
    source: '지금 비가 와요.',
    mode: 'level',
    target: 'casual',
    set: 'casual',
    answer: '지금 비가 와.',
    distractors: [
      '지금 비가 와요.',
      '지금 비가 옵니다.',
      '지금 비가 온다.',
    ],
    trans: L(
      "It's raining now.",
      'Ahora está lloviendo.',
      'Il pleut maintenant.',
      'Agora está chovendo.',
      'ตอนนี้ฝนตก',
      'Sekarang sedang hujan.',
      'Bây giờ trời đang mưa.',
      '今雨が降っている。',
    ),
    why: L(
      '반말 (해체) drops 요: 오다 contracts to 와요 → 와. (온다 is 한다체 writing style, not spoken 반말.)',
      '반말 (해체) quita 요: 오다 se contrae a 와요 → 와. (온다 es estilo escrito 한다체, no 반말 hablado.)',
      '반말 (해체) enlève 요 : 오다 se contracte en 와요 → 와. (온다 est le style écrit 한다체, pas le 반말 parlé.)',
      '반말 (해체) tira 요: 오다 contrai para 와요 → 와. (온다 é estilo escrito 한다체, não 반말 falado.)',
      '반말 (해체) ตัด 요 ออก: 오다 ย่อเป็น 와요 → 와 (온다 เป็นสไตล์เขียน 한다체 ไม่ใช่ 반말 ที่พูดกัน)',
      '반말 (해체) menghapus 요: 오다 menyingkat jadi 와요 → 와. (온다 gaya tulis 한다체, bukan 반말 lisan.)',
      '반말 (해체) bỏ 요: 오다 rút gọn thành 와요 → 와. (온다 là văn viết 한다체, không phải 반말 nói.)',
      '반말（해체）は요を落とす：오다は와요に縮約 → 와。（온다は한다체の書き言葉で、話し言葉の반말ではない。）',
    ),
  },
]
