// app/seed/register-transform/level.ts
import type { RegisterItem } from '~/lib/domain'
import { L } from '../locale'

/**
 * Speech-level transform items (반말 ↔ 해요체 ↔ 합쇼체), neutral subject.
 * Drafted + Korean-lens adversarially verified (single-correct-answer, no self-honorification,
 * plausible-wrong distractors, 8-locale). Korean wife native review = documented final gate.
 */

export const LEVEL_ITEMS: RegisterItem[] = [
  {
    source: '저는 회사에 다녀요.',
    mode: 'level',
    target: 'formal',
    set: 'formal',
    answer: '저는 회사에 다닙니다.',
    distractors: [
      '저는 회사에 다녀.',
      '나는 회사에 다닙니다.',
      '저는 회사에 다니세요.',
    ],
    trans: L(
      'I work at a company.',
      'Trabajo en una empresa.',
      'Je travaille dans une entreprise.',
      'Eu trabalho numa empresa.',
      'ฉันทำงานที่บริษัท',
      'Saya bekerja di sebuah perusahaan.',
      'Tôi làm việc ở một công ty.',
      '私は会社に勤めています。',
    ),
    why: L(
      '합쇼체 uses -ㅂ니다 on a vowel stem: 다니다 → 다닙니다; keep 저 (not 나) and never self-honorify with -(으)시-.',
      '합쇼체 usa -ㅂ니다 en raíz vocálica: 다니다 → 다닙니다; mantén 저 (no 나) y nunca te auto-honres con -(으)시-.',
      "합쇼체 emploie -ㅂ니다 sur radical vocalique : 다니다 → 다닙니다 ; garde 저 (pas 나) et ne t'auto-honore jamais avec -(으)시-.",
      '합쇼체 usa -ㅂ니다 em raiz vocálica: 다니다 → 다닙니다; mantenha 저 (não 나) e nunca se auto-honre com -(으)시-.',
      '합쇼체 ใช้ -ㅂ니다 กับก้านเสียงสระ: 다니다 → 다닙니다; คง 저 (ไม่ใช่ 나) และห้ามยกย่องตัวเองด้วย -(으)시-',
      '합쇼체 memakai -ㅂ니다 pada akar vokal: 다니다 → 다닙니다; tetap 저 (bukan 나) dan jangan menghormati diri sendiri dengan -(으)시-.',
      '합쇼체 dùng -ㅂ니다 với gốc nguyên âm: 다니다 → 다닙니다; giữ 저 (không phải 나) và đừng tự tôn kính bằng -(으)시-.',
      '합쇼체は母音語幹に-ㅂ니다：다니다 → 다닙니다。저のまま（나にしない）、-(으)시-で自分を敬わない。',
    ),
  },
  {
    source: '저는 매일 아침을 먹어요.',
    mode: 'level',
    target: 'formal',
    set: 'formal',
    answer: '저는 매일 아침을 먹습니다.',
    distractors: [
      '저는 매일 아침을 먹어.',
      '나는 매일 아침을 먹습니다.',
      '저는 매일 아침을 드십니다.',
    ],
    trans: L(
      'I eat breakfast every day.',
      'Desayuno todos los días.',
      'Je prends le petit-déjeuner tous les jours.',
      'Eu tomo café da manhã todos os dias.',
      'ฉันกินข้าวเช้าทุกวัน',
      'Saya sarapan setiap hari.',
      'Tôi ăn sáng mỗi ngày.',
      '私は毎日朝ごはんを食べます。',
    ),
    why: L(
      '합쇼체 on a consonant stem is -습니다: 먹다 → 먹습니다; the speaker is never honorified, so 드시다 (드십니다) is wrong here.',
      '합쇼체 en raíz consonántica es -습니다: 먹다 → 먹습니다; al hablante nunca se le honra, así que 드시다 (드십니다) está mal aquí.',
      "합쇼체 sur radical consonantique est -습니다 : 먹다 → 먹습니다 ; le locuteur n'est jamais honoré, donc 드시다 (드십니다) est faux ici.",
      '합쇼체 em raiz consonantal é -습니다: 먹다 → 먹습니다; o falante nunca é honrado, então 드시다 (드십니다) está errado aqui.',
      '합쇼체 กับก้านเสียงพยัญชนะคือ -습니다: 먹다 → 먹습니다; ผู้พูดไม่ถูกยกย่อง ดังนั้น 드시다 (드십니다) จึงผิดในที่นี้',
      '합쇼체 pada akar konsonan adalah -습니다: 먹다 → 먹습니다; penutur tak pernah dihormati, jadi 드시다 (드십니다) salah di sini.',
      '합쇼체 với gốc phụ âm là -습니다: 먹다 → 먹습니다; người nói không bao giờ được tôn kính, nên 드시다 (드십니다) sai ở đây.',
      '합쇼체は子音語幹に-습니다：먹다 → 먹습니다。話し手は敬わないので드시다（드십니다）は誤り。',
    ),
  },
  {
    source: '저는 주말에 책을 읽어요.',
    mode: 'level',
    target: 'formal',
    set: 'formal',
    answer: '저는 주말에 책을 읽습니다.',
    distractors: [
      '저는 주말에 책을 읽어.',
      '나는 주말에 책을 읽습니다.',
      '저는 주말에 책을 읽으십니다.',
    ],
    trans: L(
      'I read books on weekends.',
      'Leo libros los fines de semana.',
      'Je lis des livres le week-end.',
      'Eu leio livros nos fins de semana.',
      'ฉันอ่านหนังสือในวันหยุดสุดสัปดาห์',
      'Saya membaca buku di akhir pekan.',
      'Tôi đọc sách vào cuối tuần.',
      '私は週末に本を読みます。',
    ),
    why: L(
      'Consonant stem takes -습니다: 읽다 → 읽습니다; do not add -(으)시- to your own action — 읽으십니다 self-honorifies the speaker.',
      'Raíz consonántica toma -습니다: 읽다 → 읽습니다; no añadas -(으)시- a tu propia acción — 읽으십니다 se auto-honra.',
      "Le radical consonantique prend -습니다 : 읽다 → 읽습니다 ; n'ajoute pas -(으)시- à ta propre action — 읽으십니다 t'auto-honore.",
      'Raiz consonantal leva -습니다: 읽다 → 읽습니다; não acrescente -(으)시- à própria ação — 읽으십니다 auto-honra o falante.',
      'ก้านเสียงพยัญชนะใช้ -습니다: 읽다 → 읽습니다; อย่าเติม -(으)시- ให้การกระทำของตน — 읽으십니다 คือยกย่องตัวเอง',
      'Akar konsonan memakai -습니다: 읽다 → 읽습니다; jangan tambah -(으)시- pada tindakan sendiri — 읽으십니다 menghormati diri sendiri.',
      'Gốc phụ âm dùng -습니다: 읽다 → 읽습니다; đừng thêm -(으)시- vào hành động của mình — 읽으십니다 là tự tôn kính.',
      '子音語幹は-습니다：읽다 → 읽습니다。自分の動作に-(으)시-を付けない——읽으십니다は自分を敬う誤り。',
    ),
  },
  {
    source: '저는 지하철로 출근해요.',
    mode: 'level',
    target: 'formal',
    set: 'formal',
    answer: '저는 지하철로 출근합니다.',
    distractors: [
      '저는 지하철로 출근해.',
      '나는 지하철로 출근합니다.',
      '저는 지하철로 출근하십니다.',
    ],
    trans: L(
      'I commute to work by subway.',
      'Voy al trabajo en metro.',
      'Je vais au travail en métro.',
      'Eu vou ao trabalho de metrô.',
      'ฉันไปทำงานด้วยรถไฟใต้ดิน',
      'Saya berangkat kerja dengan kereta bawah tanah.',
      'Tôi đi làm bằng tàu điện ngầm.',
      '私は地下鉄で通勤します。',
    ),
    why: L(
      '하다 verbs become -합니다: 출근하다 → 출근합니다; keep 저 (not 나) and never -(으)시- on yourself (출근하십니다 is self-honoring).',
      'Los verbos en 하다 pasan a -합니다: 출근하다 → 출근합니다; mantén 저 (no 나) y nunca -(으)시- sobre ti (출근하십니다 se auto-honra).',
      "Les verbes en 하다 deviennent -합니다 : 출근하다 → 출근합니다 ; garde 저 (pas 나) et jamais -(으)시- sur toi-même (출근하십니다 s'auto-honore).",
      'Verbos em 하다 viram -합니다: 출근하다 → 출근합니다; mantenha 저 (não 나) e nunca -(으)시- em si (출근하십니다 auto-honra).',
      'คำกริยา 하다 กลายเป็น -합니다: 출근하다 → 출근합니다; คง 저 (ไม่ใช่ 나) และห้าม -(으)시- กับตนเอง (출근하십니다 คือยกย่องตัวเอง)',
      'Kata kerja 하다 menjadi -합니다: 출근하다 → 출근합니다; tetap 저 (bukan 나) dan jangan -(으)시- pada diri (출근하십니다 menghormati diri).',
      'Động từ 하다 thành -합니다: 출근하다 → 출근합니다; giữ 저 (không phải 나) và đừng -(으)시- với bản thân (출근하십니다 là tự tôn kính).',
      '하다動詞は-합니다：출근하다 → 출근합니다。저のまま（나にしない）、自分に-(으)시-を付けない（출근하십니다は自敬）。',
    ),
  },
  {
    source: '저는 커피를 안 마셔요.',
    mode: 'level',
    target: 'formal',
    set: 'formal',
    answer: '저는 커피를 안 마십니다.',
    distractors: [
      '저는 커피를 안 마셔.',
      '나는 커피를 안 마십니다.',
      '저는 커피를 안 드십니다.',
    ],
    trans: L(
      "I don't drink coffee.",
      'No tomo café.',
      'Je ne bois pas de café.',
      'Eu não tomo café.',
      'ฉันไม่ดื่มกาแฟ',
      'Saya tidak minum kopi.',
      'Tôi không uống cà phê.',
      '私はコーヒーを飲みません。',
    ),
    why: L(
      'Vowel stem 마시다 → 마십니다 in 합쇼체; the honorific form 드시다 (드십니다) is for a respected subject, never for the speaker.',
      'Raíz vocálica 마시다 → 마십니다 en 합쇼체; la forma honorífica 드시다 (드십니다) es para un sujeto respetado, nunca para el hablante.',
      'Radical vocalique 마시다 → 마십니다 en 합쇼체 ; la forme honorée 드시다 (드십니다) vise un sujet respecté, jamais le locuteur.',
      'Raiz vocálica 마시다 → 마십니다 no 합쇼체; a forma honorífica 드시다 (드십니다) é para um sujeito respeitado, nunca para o falante.',
      'ก้านเสียงสระ 마시다 → 마십니다 ใน 합쇼체; รูปยกย่อง 드시다 (드십니다) ใช้กับประธานที่เคารพ ไม่ใช่ผู้พูด',
      'Akar vokal 마시다 → 마십니다 dalam 합쇼체; bentuk hormat 드시다 (드십니다) untuk subjek terhormat, bukan penutur.',
      'Gốc nguyên âm 마시다 → 마십니다 trong 합쇼체; dạng tôn kính 드시다 (드십니다) dành cho chủ ngữ được kính trọng, không phải người nói.',
      '母音語幹마시다 → 마십니다（합쇼체）。尊敬形드시다（드십니다）は敬う主語用で、話し手には使わない。',
    ),
  },
  {
    source: '저는 운동을 별로 안 좋아해요.',
    mode: 'level',
    target: 'formal',
    set: 'formal',
    answer: '저는 운동을 별로 안 좋아합니다.',
    distractors: [
      '저는 운동을 별로 안 좋아해.',
      '나는 운동을 별로 안 좋아합니다.',
      '저는 운동을 별로 안 좋아하십니다.',
    ],
    trans: L(
      "I don't really like exercising.",
      'No me gusta mucho hacer ejercicio.',
      "Je n'aime pas trop faire du sport.",
      'Eu não gosto muito de me exercitar.',
      'ฉันไม่ค่อยชอบออกกำลังกาย',
      'Saya kurang suka berolahraga.',
      'Tôi không thích tập thể dục lắm.',
      '私は運動があまり好きではありません。',
    ),
    why: L(
      '하다 verbs take -합니다: 좋아하다 → 좋아합니다; keep 저 (not 나), and -(으)시- on your own preference (좋아하십니다) wrongly honors the speaker.',
      'Los verbos en 하다 toman -합니다: 좋아하다 → 좋아합니다; mantén 저 (no 나), y -(으)시- sobre tu propio gusto (좋아하십니다) honra mal al hablante.',
      "Les verbes en 하다 prennent -합니다 : 좋아하다 → 좋아합니다 ; garde 저 (pas 나), et -(으)시- sur ton propre goût (좋아하십니다) honore à tort le locuteur.",
      'Verbos em 하다 levam -합니다: 좋아하다 → 좋아합니다; mantenha 저 (não 나), e -(으)시- no próprio gosto (좋아하십니다) honra erradamente o falante.',
      'คำกริยา 하다 ใช้ -합니다: 좋아하다 → 좋아합니다; คง 저 (ไม่ใช่ 나) และ -(으)시- กับความชอบของตน (좋아하십니다) เป็นการยกย่องผู้พูดอย่างผิด',
      'Kata kerja 하다 memakai -합니다: 좋아하다 → 좋아합니다; tetap 저 (bukan 나), dan -(으)시- pada selera sendiri (좋아하십니다) keliru menghormati penutur.',
      'Động từ 하다 dùng -합니다: 좋아하다 → 좋아합니다; giữ 저 (không phải 나), và -(으)시- với sở thích của mình (좋아하십니다) tôn kính người nói một cách sai.',
      '하다動詞は-합니다：좋아하다 → 좋아합니다。저のまま（나にしない）、自分の好みに-(으)시-（좋아하십니다）は話し手を誤って敬う。',
    ),
  },
  {
    source: '저는 보통 열한 시에 자요.',
    mode: 'level',
    target: 'formal',
    set: 'formal',
    answer: '저는 보통 열한 시에 잡니다.',
    distractors: [
      '저는 보통 열한 시에 자.',
      '나는 보통 열한 시에 잡니다.',
      '저는 보통 열한 시에 주무십니다.',
    ],
    trans: L(
      'I usually go to sleep at eleven.',
      'Normalmente me acuesto a las once.',
      "D'habitude je me couche à onze heures.",
      'Eu normalmente durmo às onze.',
      'ปกติฉันนอนตอนห้าทุ่ม',
      'Saya biasanya tidur jam sebelas.',
      'Tôi thường đi ngủ lúc mười một giờ.',
      '私はたいてい十一時に寝ます。',
    ),
    why: L(
      'Vowel stem 자다 → 잡니다 in 합쇼체 (-ㅂ니다 attaches directly); 주무시다 (주무십니다) is the honorific suppletive for a respected subject, never the speaker.',
      'Raíz vocálica 자다 → 잡니다 en 합쇼체 (se añade -ㅂ니다 directamente); 주무시다 (주무십니다) es la forma supletiva honorífica para un sujeto respetado, nunca para el hablante.',
      "Radical vocalique 자다 → 잡니다 en 합쇼체 (-ㅂ니다 s'attache directement) ; 주무시다 (주무십니다) est le supplétif honorifique pour un sujet respecté, jamais le locuteur.",
      'Raiz vocálica 자다 → 잡니다 no 합쇼체 (-ㅂ니다 se anexa diretamente); 주무시다 (주무십니다) é a forma supletiva honorífica para um sujeito respeitado, nunca o falante.',
      'ก้านเสียงสระ 자다 → 잡니다 ใน 합쇼체 (เติม -ㅂ니다 ตรง ๆ); 주무시다 (주무십니다) คือรูปยกย่องแบบพิเศษสำหรับประธานที่เคารพ ไม่ใช่ผู้พูด',
      'Akar vokal 자다 → 잡니다 dalam 합쇼체 (-ㅂ니다 melekat langsung); 주무시다 (주무십니다) adalah bentuk supletif hormat untuk subjek terhormat, bukan penutur.',
      'Gốc nguyên âm 자다 → 잡니다 trong 합쇼체 (-ㅂ니다 gắn trực tiếp); 주무시다 (주무십니다) là dạng tôn kính bổ sung dành cho chủ ngữ được kính trọng, không phải người nói.',
      '母音語幹자다 → 잡니다（합쇼체、-ㅂ니다が直接付く）。주무시다（주무십니다）は敬う主語用の尊敬の特殊形で、話し手には使わない。',
    ),
  },
  {
    source: '저는 매일 운동합니다.',
    mode: 'level',
    target: 'polite',
    set: 'polite',
    answer: '저는 매일 운동해요.',
    distractors: [
      '저는 매일 운동합니다.',
      '저는 매일 운동해.',
      '나는 매일 운동해요.',
    ],
    trans: L(
      'I exercise every day.',
      'Hago ejercicio todos los días.',
      "Je fais de l'exercice tous les jours.",
      'Eu me exercito todos os dias.',
      'ฉันออกกำลังกายทุกวัน',
      'Saya berolahraga setiap hari.',
      'Tôi tập thể dục mỗi ngày.',
      '私は毎日運動します。',
    ),
    why: L(
      '해요체 polite uses -아/어요: 하다 → 해요; keep 저 (a 1st-person subject is never self-honorified).',
      'El 해요체 cortés usa -아/어요: 하다 → 해요; se mantiene 저 (un sujeto en 1ª persona nunca se autohonorifica).',
      "Le 해요체 poli utilise -아/어요 : 하다 → 해요 ; on garde 저 (un sujet à la 1re personne ne s'auto-honorifie jamais).",
      'O 해요체 polido usa -아/어요: 하다 → 해요; mantém-se 저 (um sujeito de 1ª pessoa nunca se auto-honorifica).',
      '해요체 แบบสุภาพใช้ -아/어요: 하다 → 해요 และคงคำว่า 저 (ประธานบุรุษที่ 1 ไม่ยกย่องตัวเอง)',
      '해요체 sopan memakai -아/어요: 하다 → 해요; tetap 저 (subjek orang pertama tidak pernah dihormati sendiri).',
      '해요체 lịch sự dùng -아/어요: 하다 → 해요; giữ 저 (chủ ngữ ngôi thứ nhất không bao giờ tự tôn kính).',
      '해요체（丁寧）は-아/어요：하다 → 해요。저のまま（一人称主語は自分を敬わない）。',
    ),
  },
  {
    source: '나 지금 밥 먹어.',
    mode: 'level',
    target: 'polite',
    set: 'polite',
    answer: '저 지금 밥 먹어요.',
    distractors: [
      '나 지금 밥 먹어.',
      '저 지금 밥 먹습니다.',
      '저 지금 밥 먹어.',
    ],
    trans: L(
      "I'm eating now.",
      'Estoy comiendo ahora.',
      'Je mange maintenant.',
      'Estou comendo agora.',
      'ตอนนี้ฉันกำลังกินข้าว',
      'Saya sedang makan sekarang.',
      'Bây giờ tôi đang ăn cơm.',
      '今ご飯を食べています。',
    ),
    why: L(
      '해요체 adds 요 to 반말 먹어 → 먹어요; raising the level shifts 나 → 저 (polite 1st-person pronoun).',
      'El 해요체 añade 요 al 반말 먹어 → 먹어요; subir el nivel cambia 나 → 저 (pronombre de 1ª persona cortés).',
      'Le 해요체 ajoute 요 au 반말 먹어 → 먹어요 ; monter le niveau fait passer 나 → 저 (pronom poli de 1re personne).',
      'O 해요체 acrescenta 요 ao 반말 먹어 → 먹어요; elevar o nível muda 나 → 저 (pronome de 1ª pessoa polido).',
      '해요체 เติม 요 ให้ 반말 먹어 → 먹어요 และการยกระดับเปลี่ยน 나 → 저 (สรรพนามบุรุษที่ 1 แบบสุภาพ)',
      '해요체 menambah 요 pada 반말 먹어 → 먹어요; menaikkan tingkat mengubah 나 → 저 (kata ganti orang pertama sopan).',
      '해요체 thêm 요 vào 반말 먹어 → 먹어요; nâng cấp độ đổi 나 → 저 (đại từ ngôi thứ nhất lịch sự).',
      '해요체는반말 먹어に요を付ける → 먹어요。レベルを上げると나 → 저（丁寧な一人称代名詞）。',
    ),
  },
  {
    source: '주말에 영화를 봅니다.',
    mode: 'level',
    target: 'polite',
    set: 'polite',
    answer: '주말에 영화를 봐요.',
    distractors: [
      '주말에 영화를 봅니다.',
      '주말에 영화를 봐.',
      '주말에 영화를 보세요.',
    ],
    trans: L(
      'I watch a movie on the weekend.',
      'Veo una película el fin de semana.',
      'Je regarde un film le week-end.',
      'Vejo um filme no fim de semana.',
      'สุดสัปดาห์ฉันดูหนัง',
      'Di akhir pekan saya menonton film.',
      'Cuối tuần tôi xem phim.',
      '週末に映画を見ます。',
    ),
    why: L(
      '해요체 contracts 보다 → 봐요; -세요 would add 주체높임 -(으)시- to a neutral 1st-person subject (wrong here).',
      'El 해요체 contrae 보다 → 봐요; -세요 añadiría 주체높임 -(으)시- a un sujeto neutro de 1ª persona (incorrecto aquí).',
      'Le 해요체 contracte 보다 → 봐요 ; -세요 ajouterait le 주체높임 -(으)시- à un sujet neutre à la 1re personne (faux ici).',
      'O 해요체 contrai 보다 → 봐요; -세요 acrescentaria o 주체높임 -(으)시- a um sujeito neutro de 1ª pessoa (errado aqui).',
      '해요체 ย่อ 보다 → 봐요; -세요 จะเติม 주체높임 -(으)시- ให้ประธานบุรุษที่ 1 ทั่วไป (ผิดในที่นี้)',
      '해요체 menyingkat 보다 → 봐요; -세요 akan menambah 주체높임 -(으)시- pada subjek orang pertama netral (salah di sini).',
      '해요체 rút gọn 보다 → 봐요; -세요 sẽ thêm 주체높임 -(으)시- vào chủ ngữ ngôi thứ nhất trung tính (sai ở đây).',
      '해요체는보다 → 봐요と縮約。-세요は中立的な一人称主語に주체높임-(으)시-を付けてしまう（ここでは誤り）。',
    ),
  },
  {
    source: '나는 커피를 안 마셔.',
    mode: 'level',
    target: 'polite',
    set: 'polite',
    answer: '저는 커피를 안 마셔요.',
    distractors: [
      '나는 커피를 안 마셔.',
      '저는 커피를 안 마십니다.',
      '저는 커피를 안 마셔.',
    ],
    trans: L(
      "I don't drink coffee.",
      'No tomo café.',
      'Je ne bois pas de café.',
      'Eu não tomo café.',
      'ฉันไม่ดื่มกาแฟ',
      'Saya tidak minum kopi.',
      'Tôi không uống cà phê.',
      '私はコーヒーを飲みません。',
    ),
    why: L(
      '해요체 adds 요 to 마셔 → 마셔요; raising 반말 to polite also shifts 나 → 저.',
      'El 해요체 añade 요 a 마셔 → 마셔요; subir del 반말 a cortés también cambia 나 → 저.',
      'Le 해요체 ajoute 요 à 마셔 → 마셔요 ; passer du 반말 au poli fait aussi 나 → 저.',
      'O 해요체 acrescenta 요 a 마셔 → 마셔요; subir do 반말 ao polido também muda 나 → 저.',
      '해요체 เติม 요 ให้ 마셔 → 마셔요; การยกจาก 반말 เป็นสุภาพยังเปลี่ยน 나 → 저',
      '해요체 menambah 요 pada 마셔 → 마셔요; menaikkan dari 반말 ke sopan juga mengubah 나 → 저.',
      '해요체 thêm 요 vào 마셔 → 마셔요; nâng từ 반말 lên lịch sự cũng đổi 나 → 저.',
      '해요체는마셔に요を付ける → 마셔요。반말から丁寧へ上げると나 → 저にもなる。',
    ),
  },
  {
    source: '이 책은 정말 재미있습니다.',
    mode: 'level',
    target: 'polite',
    set: 'polite',
    answer: '이 책은 정말 재미있어요.',
    distractors: [
      '이 책은 정말 재미있습니다.',
      '이 책은 정말 재미있어.',
      '이 책은 정말 재미있으세요.',
    ],
    trans: L(
      'This book is really interesting.',
      'Este libro es muy interesante.',
      'Ce livre est vraiment intéressant.',
      'Este livro é muito interessante.',
      'หนังสือเล่มนี้สนุกมากจริง ๆ',
      'Buku ini benar-benar menarik.',
      'Cuốn sách này thật sự thú vị.',
      'この本は本当に面白いです。',
    ),
    why: L(
      '해요체 of 재미있다 is 재미있어요; -으세요 would force 주체높임 onto an inanimate subject (a book), which is wrong.',
      'El 해요체 de 재미있다 es 재미있어요; -으세요 forzaría 주체높임 sobre un sujeto inanimado (un libro), lo cual es incorrecto.',
      'Le 해요체 de 재미있다 est 재미있어요 ; -으세요 imposerait le 주체높임 à un sujet inanimé (un livre), ce qui est faux.',
      'O 해요체 de 재미있다 é 재미있어요; -으세요 forçaria o 주체높임 sobre um sujeito inanimado (um livro), o que é errado.',
      '해요체 ของ 재미있다 คือ 재미있어요; -으세요 จะบังคับ 주체높임 ลงบนประธานที่ไม่มีชีวิต (หนังสือ) ซึ่งผิด',
      '해요체 dari 재미있다 adalah 재미있어요; -으세요 akan memaksakan 주체높임 pada subjek tak bernyawa (buku), itu salah.',
      '해요체 của 재미있다 là 재미있어요; -으세요 sẽ áp 주체높임 lên chủ ngữ vô tri (quyển sách), điều đó sai.',
      '재미있다の해요체は재미있어요。-으세요は無生物主語（本）に주체높임を付けてしまい誤り。',
    ),
  },
  {
    source: '나 내일 학교에 가.',
    mode: 'level',
    target: 'polite',
    set: 'polite',
    answer: '저 내일 학교에 가요.',
    distractors: [
      '나 내일 학교에 가.',
      '저 내일 학교에 갑니다.',
      '저 내일 학교에 가.',
    ],
    trans: L(
      "I'm going to school tomorrow.",
      'Mañana voy a la escuela.',
      "Demain je vais à l'école.",
      'Amanhã eu vou à escola.',
      'พรุ่งนี้ฉันจะไปโรงเรียน',
      'Besok saya pergi ke sekolah.',
      'Ngày mai tôi đến trường.',
      '明日学校に行きます。',
    ),
    why: L(
      '해요체 of 가다 is 가요 (vowel stem just adds 요); raising 반말 to polite shifts 나 → 저.',
      'El 해요체 de 가다 es 가요 (raíz vocálica solo añade 요); subir del 반말 a cortés cambia 나 → 저.',
      'Le 해요체 de 가다 est 가요 (radical vocalique : on ajoute juste 요) ; passer du 반말 au poli fait 나 → 저.',
      'O 해요체 de 가다 é 가요 (radical em vogal só acrescenta 요); subir do 반말 ao polido muda 나 → 저.',
      '해요체 ของ 가다 คือ 가요 (ก้านสระเติม 요 เฉย ๆ); การยกจาก 반말 เป็นสุภาพเปลี่ยน 나 → 저',
      '해요체 dari 가다 adalah 가요 (akar vokal cukup tambah 요); menaikkan 반말 ke sopan mengubah 나 → 저.',
      '해요체 của 가다 là 가요 (gốc nguyên âm chỉ thêm 요); nâng 반말 lên lịch sự đổi 나 → 저.',
      '가다の해요체は가요（母音語幹は요を付けるだけ）。반말から丁寧へ上げると나 → 저。',
    ),
  },
  {
    source: '날씨가 많이 춥습니다.',
    mode: 'level',
    target: 'polite',
    set: 'polite',
    answer: '날씨가 많이 추워요.',
    distractors: [
      '날씨가 많이 춥습니다.',
      '날씨가 많이 추워.',
      '날씨가 많이 춥어요.',
    ],
    trans: L(
      'The weather is very cold.',
      'Hace mucho frío.',
      'Il fait très froid.',
      'O tempo está muito frio.',
      'อากาศหนาวมาก',
      'Cuacanya sangat dingin.',
      'Thời tiết rất lạnh.',
      '天気がとても寒いです。',
    ),
    why: L(
      '춥다 is a ㅂ-irregular: stem ㅂ → 우 before 어요, so 춥다 → 추워요 (해요체); 춥어요 keeps the ㅂ and is wrong.',
      '춥다 es ㅂ-irregular: la ㅂ del radical → 우 ante 어요, así 춥다 → 추워요 (해요체); 춥어요 conserva la ㅂ y es incorrecto.',
      '춥다 est un verbe en ㅂ irrégulier : ㅂ du radical → 우 devant 어요, donc 춥다 → 추워요 (해요체) ; 춥어요 garde le ㅂ et est faux.',
      '춥다 é ㅂ-irregular: ㅂ do radical → 우 antes de 어요, então 춥다 → 추워요 (해요체); 춥어요 mantém o ㅂ e é errado.',
      '춥다 เป็นกริยาผัน ㅂ ไม่ปกติ: ㅂ ของก้าน → 우 หน้า 어요 จึง 춥다 → 추워요 (해요체); 춥어요 คง ㅂ ไว้จึงผิด',
      '춥다 adalah ㅂ-tak beraturan: ㅂ akar → 우 sebelum 어요, jadi 춥다 → 추워요 (해요체); 춥어요 mempertahankan ㅂ dan salah.',
      '춥다 là bất quy tắc ㅂ: ㅂ của gốc → 우 trước 어요, nên 춥다 → 추워요 (해요체); 춥어요 giữ ㅂ nên sai.',
      '춥다はㅂ不規則：語幹のㅂが어요の前で우に変わり춥다 → 추워요（해요체）。춥어요はㅂを残すので誤り。',
    ),
  },
  {
    source: '나는 커피를 마셔요.',
    mode: 'level',
    target: 'casual',
    set: 'casual',
    answer: '나는 커피를 마셔.',
    distractors: [
      '나는 커피를 마셔요.',
      '나는 커피를 마십니다.',
      '나는 커피를 마신다.',
    ],
    trans: L(
      'I drink coffee.',
      'Bebo café.',
      'Je bois du café.',
      'Eu bebo café.',
      'ฉันดื่มกาแฟ',
      'Saya minum kopi.',
      'Tôi uống cà phê.',
      '私はコーヒーを飲む。',
    ),
    why: L(
      '반말 (해체) drops 요: 마셔요 → 마셔. (마신다 is 한다체 writing style, not spoken 반말.)',
      '반말 (해체) quita 요: 마셔요 → 마셔. (마신다 es estilo escrito 한다체, no 반말 hablado.)',
      '반말 (해체) enlève 요 : 마셔요 → 마셔. (마신다 est le style écrit 한다체, pas le 반말 parlé.)',
      '반말 (해체) tira 요: 마셔요 → 마셔. (마신다 é estilo escrito 한다체, não 반말 falado.)',
      '반말 (해체) ตัด 요 ออก: 마셔요 → 마셔 (마신다 เป็นสไตล์เขียน 한다체 ไม่ใช่ 반말 ที่พูดกัน)',
      '반말 (해체) menghapus 요: 마셔요 → 마셔. (마신다 gaya tulis 한다체, bukan 반말 lisan.)',
      '반말 (해체) bỏ 요: 마셔요 → 마셔. (마신다 là văn viết 한다체, không phải 반말 nói.)',
      '반말（해체）は요を落とす：마셔요 → 마셔。（마신다は한다체の書き言葉で、話し言葉の반말ではない。）',
    ),
  },
  {
    source: '저는 책을 읽어요.',
    mode: 'level',
    target: 'casual',
    set: 'casual',
    answer: '나는 책을 읽어.',
    distractors: [
      '저는 책을 읽어요.',
      '저는 책을 읽습니다.',
      '나는 책을 읽는다.',
    ],
    trans: L(
      'I read a book.',
      'Leo un libro.',
      'Je lis un livre.',
      'Eu leio um livro.',
      'ฉันอ่านหนังสือ',
      'Saya membaca buku.',
      'Tôi đọc sách.',
      '私は本を読む。',
    ),
    why: L(
      '반말 (해체) drops 요 and 저→나: 읽어요 → 읽어. (읽는다 is 한다체 writing style, not spoken 반말.)',
      '반말 (해체) quita 요 y 저→나: 읽어요 → 읽어. (읽는다 es estilo escrito 한다체, no 반말 hablado.)',
      '반말 (해체) enlève 요 et 저→나 : 읽어요 → 읽어. (읽는다 est le style écrit 한다체, pas le 반말 parlé.)',
      '반말 (해체) tira 요 e 저→나: 읽어요 → 읽어. (읽는다 é estilo escrito 한다체, não 반말 falado.)',
      '반말 (해체) ตัด 요 ออกและ 저→나: 읽어요 → 읽어 (읽는다 เป็นสไตล์เขียน 한다체 ไม่ใช่ 반말 ที่พูดกัน)',
      '반말 (해체) menghapus 요 dan 저→나: 읽어요 → 읽어. (읽는다 gaya tulis 한다체, bukan 반말 lisan.)',
      '반말 (해체) bỏ 요 và 저→나: 읽어요 → 읽어. (읽는다 là văn viết 한다체, không phải 반말 nói.)',
      '반말（해체）は요を落とし저→나：읽어요 → 읽어。（읽는다は한다체の書き言葉で、話し言葉の반말ではない。）',
    ),
  },
  {
    source: '날씨가 정말 좋아요.',
    mode: 'level',
    target: 'casual',
    set: 'casual',
    answer: '날씨가 정말 좋아.',
    distractors: [
      '날씨가 정말 좋아요.',
      '날씨가 정말 좋습니다.',
      '날씨가 정말 좋다.',
    ],
    trans: L(
      'The weather is really nice.',
      'El clima está muy bueno.',
      'Il fait vraiment beau.',
      'O tempo está muito bom.',
      'อากาศดีจริง ๆ',
      'Cuacanya benar-benar bagus.',
      'Thời tiết thật sự đẹp.',
      '天気が本当にいい。',
    ),
    why: L(
      '반말 (해체) of an adjective drops 요: 좋아요 → 좋아. (좋다 is the 한다체/dictionary written form, not spoken 반말.)',
      '반말 (해체) de un adjetivo quita 요: 좋아요 → 좋아. (좋다 es la forma escrita 한다체/diccionario, no 반말 hablado.)',
      "반말 (해체) d'un adjectif enlève 요 : 좋아요 → 좋아. (좋다 est la forme écrite 한다체/dictionnaire, pas le 반말 parlé.)",
      '반말 (해체) de um adjetivo tira 요: 좋아요 → 좋아. (좋다 é a forma escrita 한다체/dicionário, não 반말 falado.)',
      '반말 (해체) ของคำคุณศัพท์ตัด 요 ออก: 좋아요 → 좋아 (좋다 เป็นรูปเขียน 한다체/พจนานุกรม ไม่ใช่ 반말 ที่พูดกัน)',
      '반말 (해체) untuk kata sifat menghapus 요: 좋아요 → 좋아. (좋다 bentuk tulis 한다체/kamus, bukan 반말 lisan.)',
      '반말 (해체) của tính từ bỏ 요: 좋아요 → 좋아. (좋다 là dạng viết 한다체/từ điển, không phải 반말 nói.)',
      '形容詞の반말（해체）は요を落とす：좋아요 → 좋아。（좋다は한다체/辞書形の書き言葉で、話し言葉の반말ではない。）',
    ),
  },
  {
    source: '저는 회사원이에요.',
    mode: 'level',
    target: 'casual',
    set: 'casual',
    answer: '나는 회사원이야.',
    distractors: [
      '저는 회사원이에요.',
      '저는 회사원입니다.',
      '나는 회사원이다.',
    ],
    trans: L(
      "I'm an office worker.",
      'Soy oficinista.',
      'Je suis employé de bureau.',
      'Eu sou funcionário de escritório.',
      'ฉันเป็นพนักงานออฟฟิศ',
      'Saya pegawai kantoran.',
      'Tôi là nhân viên văn phòng.',
      '私は会社員だ。',
    ),
    why: L(
      'Copula 반말 (해체) is 이야 (after 받침): 이에요 → 이야, 저→나. (이다 is the 한다체 written form, not spoken 반말.)',
      'El 반말 (해체) de la cópula es 이야 (tras 받침): 이에요 → 이야, 저→나. (이다 es forma escrita 한다체, no 반말 hablado.)',
      'Le 반말 (해체) de la copule est 이야 (après 받침) : 이에요 → 이야, 저→나. (이다 est la forme écrite 한다체, pas le 반말 parlé.)',
      'O 반말 (해체) da cópula é 이야 (após 받침): 이에요 → 이야, 저→나. (이다 é forma escrita 한다체, não 반말 falado.)',
      "반말 (해체) ของกริยา 'เป็น' คือ 이야 (หลัง 받침): 이에요 → 이야, 저→나 (이다 เป็นรูปเขียน 한다체 ไม่ใช่ 반말 ที่พูดกัน)",
      '반말 (해체) untuk kopula adalah 이야 (setelah 받침): 이에요 → 이야, 저→나. (이다 bentuk tulis 한다체, bukan 반말 lisan.)',
      '반말 (해체) của hệ từ là 이야 (sau 받침): 이에요 → 이야, 저→나. (이다 là dạng viết 한다체, không phải 반말 nói.)',
      'コピュラの반말（해체）は이야（받침の後）：이에요 → 이야、저→나。（이다は한다체の書き言葉で、話し言葉の반말ではない。）',
    ),
  },
  {
    source: '주말에 영화를 봐요.',
    mode: 'level',
    target: 'casual',
    set: 'casual',
    answer: '주말에 영화를 봐.',
    distractors: [
      '주말에 영화를 봐요.',
      '주말에 영화를 봅니다.',
      '주말에 영화를 본다.',
    ],
    trans: L(
      'I watch a movie on the weekend.',
      'Veo una película el fin de semana.',
      'Je regarde un film le week-end.',
      'Vejo um filme no fim de semana.',
      'ฉันดูหนังในวันหยุดสุดสัปดาห์',
      'Saya menonton film di akhir pekan.',
      'Cuối tuần tôi xem phim.',
      '週末に映画を見る。',
    ),
    why: L(
      '반말 (해체) drops 요: 봐요 → 봐. (본다 is 한다체 writing style, not spoken 반말.)',
      '반말 (해체) quita 요: 봐요 → 봐. (본다 es estilo escrito 한다체, no 반말 hablado.)',
      '반말 (해체) enlève 요 : 봐요 → 봐. (본다 est le style écrit 한다체, pas le 반말 parlé.)',
      '반말 (해체) tira 요: 봐요 → 봐. (본다 é estilo escrito 한다체, não 반말 falado.)',
      '반말 (해체) ตัด 요 ออก: 봐요 → 봐 (본다 เป็นสไตล์เขียน 한다체 ไม่ใช่ 반말 ที่พูดกัน)',
      '반말 (해체) menghapus 요: 봐요 → 봐. (본다 gaya tulis 한다체, bukan 반말 lisan.)',
      '반말 (해체) bỏ 요: 봐요 → 봐. (본다 là văn viết 한다체, không phải 반말 nói.)',
      '반말（해체）は요を落とす：봐요 → 봐。（본다は한다체の書き言葉で、話し言葉の반말ではない。）',
    ),
  },
  {
    source: '오늘은 날씨가 추워요.',
    mode: 'level',
    target: 'casual',
    set: 'casual',
    answer: '오늘은 날씨가 추워.',
    distractors: [
      '오늘은 날씨가 추워요.',
      '오늘은 날씨가 춥습니다.',
      '오늘은 날씨가 춥다.',
    ],
    trans: L(
      'The weather is cold today.',
      'Hoy hace frío.',
      "Il fait froid aujourd'hui.",
      'Hoje o tempo está frio.',
      'วันนี้อากาศหนาว',
      'Hari ini cuacanya dingin.',
      'Hôm nay trời lạnh.',
      '今日は天気が寒い。',
    ),
    why: L(
      'ㅂ-irregular 반말 (해체) drops 요: 추워요 → 추워. (춥다 is the 한다체/dictionary written form, not spoken 반말.)',
      'El 반말 (해체) del irregular ㅂ quita 요: 추워요 → 추워. (춥다 es la forma escrita 한다체/diccionario, no 반말 hablado.)',
      "Le 반말 (해체) de l'irrégulier ㅂ enlève 요 : 추워요 → 추워. (춥다 est la forme écrite 한다체/dictionnaire, pas le 반말 parlé.)",
      'O 반말 (해체) do irregular ㅂ tira 요: 추워요 → 추워. (춥다 é a forma escrita 한다체/dicionário, não 반말 falado.)',
      '반말 (해체) ของกริยาผัน ㅂ ตัด 요 ออก: 추워요 → 추워 (춥다 เป็นรูปเขียน 한다체/พจนานุกรม ไม่ใช่ 반말 ที่พูดกัน)',
      '반말 (해체) untuk ㅂ-tak beraturan menghapus 요: 추워요 → 추워. (춥다 bentuk tulis 한다체/kamus, bukan 반말 lisan.)',
      '반말 (해체) của bất quy tắc ㅂ bỏ 요: 추워요 → 추워. (춥다 là dạng viết 한다체/từ điển, không phải 반말 nói.)',
      'ㅂ不規則の반말（해체）は요を落とす：추워요 → 추워。（춥다は한다체/辞書形の書き言葉で、話し言葉の반말ではない。）',
    ),
  },
]
