import type { LocalizedString, Reward, TopikLevel } from '~/lib/domain'

/** Lightweight metadata needed before a player enters a story. */
export type EscapeLevelStatus = 'playable' | 'coming-soon'

export interface EscapeLevelCatalogEntry {
  id: string
  /** 1-based page number in the notebook. */
  number: number
  title: LocalizedString
  tagline: LocalizedString
  mood: LocalizedString
  /** Cover image URL under /public. */
  cover: string
  topikLevel: TopikLevel
  status: EscapeLevelStatus
  /** Notebook-only rule projection; gameplay owns the complete rules object. */
  maxErrors: number
  /** Collection/listing projection; rooms, slots and narrative stay async. */
  rewards: Record<'common' | 'rare' | 'epic' | 'legendary', Reward>
}

/**
 * Escape Room's lightweight catalog.
 *
 * This file intentionally contains no imports from level-01...level-10 or the
 * full translation dictionaries. Keep it in parity with authored levels via
 * the catalog tests; gameplay data is loaded only by load-level.ts.
 */
export const ESCAPE_LEVEL_CATALOG = [
  {
    id: 'level-01',
    number: 1,
    title: {
      en: 'A morning at the minbak',
      es: 'Una mañana en el minbak',
      fr: 'Un matin au minbak',
      'pt-BR': 'Uma manhã no minbak',
      th: 'เช้าวันหนึ่งที่ minbak',
      id: 'Suatu pagi di minbak',
      vi: 'Một buổi sáng ở minbak',
      ja: 'minbak の朝',
    },
    tagline: {
      en: "You wake up in a house that isn't yours. It smells of freshly cooked rice. And someone left you a note.",
      es: 'Despiertas en una casa que no es tuya. Huele a arroz recién hecho. Y alguien te dejó una nota.',
      fr: "Tu te réveilles dans une maison qui n'est pas la tienne. Ça sent le riz fraîchement cuit. Et quelqu'un t'a laissé une note.",
      'pt-BR':
        'Você acorda numa casa que não é sua. Cheira a arroz recém-feito. E alguém deixou um bilhete para você.',
      th: 'เธอตื่นขึ้นในบ้านที่ไม่ใช่ของเธอ มีกลิ่นข้าวหุงใหม่ และมีใครบางคนทิ้งโน้ตไว้ให้เธอ',
      id: 'Kamu terbangun di rumah yang bukan milikmu. Tercium aroma nasi yang baru ditanak. Dan seseorang meninggalkan catatan untukmu.',
      vi: 'Bạn thức dậy trong một ngôi nhà không phải của mình. Mùi cơm vừa nấu thoang thoảng. Và ai đó đã để lại cho bạn một mẩu ghi chú.',
      ja: '自分のものではない家で目覚める。炊きたてのごはんの匂いがする。そして誰かがメモを残していった。',
    },
    mood: {
      en: 'Slice of life · Warm',
      es: 'Slice of life · Cálido',
      fr: 'Tranche de vie · Chaleureux',
      'pt-BR': 'Slice of life · Caloroso',
      th: 'ชีวิตประจำวัน · อบอุ่น',
      id: 'Slice of life · Hangat',
      vi: 'Đời thường · Ấm áp',
      ja: '日常もの · 温かい',
    },
    cover: '/escape-room/level-01/rooms/cinematic-intro-v2.webp',
    topikLevel: 1,
    status: 'playable',
    maxErrors: 2,
    rewards: {
      common: {
        id: 'cosmetic-bg-sunrise',
        image: 'cosmetics/cosmetic-bg-sunrise.png',
        name: {
          en: 'Background "Minbak Sunrise"',
          es: 'Fondo "Minbak Sunrise"',
          fr: 'Fond « Minbak Sunrise »',
          'pt-BR': 'Fundo "Minbak Sunrise"',
          th: 'พื้นหลัง "Minbak Sunrise"',
          id: 'Latar "Minbak Sunrise"',
          vi: 'Hình nền "Minbak Sunrise"',
          ja: '背景「Minbak Sunrise」',
        },
        description: {
          en: 'Pink-peach sunrise over the hanok roof.',
          es: 'Amanecer rosa-melocotón sobre el techo del hanok.',
          fr: 'Aube rose-pêche au-dessus du toit du hanok.',
          'pt-BR': 'Amanhecer rosa-pêssego sobre o telhado do hanok.',
          th: 'รุ่งอรุณสีชมพู-พีชเหนือหลังคา hanok',
          id: 'Fajar merah jambu kepersikan di atas atap hanok.',
          vi: 'Bình minh hồng đào trên mái nhà hanok.',
          ja: 'hanok の屋根の上に広がる桃色がかったピンクの夜明け。',
        },
      },
      rare: {
        id: 'cosmetic-frame-apron',
        image: 'cosmetics/cosmetic-frame-apron.png',
        name: {
          en: 'Frame "Halmeoni\'s Apron"',
          es: 'Marco "Delantal de Halmeoni"',
          fr: 'Cadre « Tablier de Halmeoni »',
          'pt-BR': 'Moldura "Avental da Halmeoni"',
          th: 'กรอบ "ผ้ากันเปื้อนของ Halmeoni"',
          id: 'Bingkai "Celemek Halmeoni"',
          vi: 'Khung "Tạp dề của Halmeoni"',
          ja: 'フレーム「Halmeoni のエプロン」',
        },
        description: {
          en: 'Frame with a floral Korean apron pattern.',
          es: 'Marco con estampado de delantal coreano floreado.',
          fr: 'Cadre à motif de tablier coréen fleuri.',
          'pt-BR': 'Moldura com estampa de avental coreano florido.',
          th: 'กรอบลายผ้ากันเปื้อนเกาหลีลายดอกไม้',
          id: 'Bingkai bermotif celemek Korea bercorak bunga.',
          vi: 'Khung với họa tiết tạp dề Hàn Quốc hoa lá.',
          ja: '花柄の韓国エプロン模様のフレーム。',
        },
      },
      epic: {
        id: 'cosmetic-avatar-lantern',
        image: 'cosmetics/cosmetic-avatar-lantern.png',
        name: {
          en: 'Avatar "Hanji Lantern"',
          es: 'Avatar "Linterna Hanji"',
          fr: 'Avatar « Lanterne Hanji »',
          'pt-BR': 'Avatar "Lanterna Hanji"',
          th: 'อวตาร "โคม Hanji"',
          id: 'Avatar "Lentera Hanji"',
          vi: 'Avatar "Đèn lồng Hanji"',
          ja: 'アバター「Hanji の灯籠」',
        },
        description: {
          en: 'Animated silhouette with a Korean paper lantern.',
          es: 'Silueta animada con linterna de papel coreano.',
          fr: 'Silhouette animée avec une lanterne en papier coréen.',
          'pt-BR': 'Silhueta animada com lanterna de papel coreano.',
          th: 'เงาเคลื่อนไหวพร้อมโคมกระดาษเกาหลี',
          id: 'Siluet beranimasi dengan lentera kertas Korea.',
          vi: 'Bóng dáng chuyển động với chiếc đèn lồng giấy Hàn Quốc.',
          ja: '韓国の紙の灯籠を持つアニメーション付きのシルエット。',
        },
      },
      legendary: {
        id: 'cosmetic-set-complete',
        image: 'cosmetics/cosmetic-set-complete.png',
        name: {
          en: 'Complete set "민박 손님"',
          es: 'Set completo "민박 손님"',
          fr: 'Set complet « 민박 손님 »',
          'pt-BR': 'Conjunto completo "민박 손님"',
          th: 'เซ็ตเต็ม "민박 손님"',
          id: 'Set lengkap "민박 손님"',
          vi: 'Bộ hoàn chỉnh "민박 손님"',
          ja: 'コンプリートセット「민박 손님」',
        },
        description: {
          en: 'Avatar + frame + background + title "Minbak guest".',
          es: 'Avatar + marco + fondo + título "Huésped del minbak".',
          fr: 'Avatar + cadre + fond + titre « Hôte du minbak ».',
          'pt-BR': 'Avatar + moldura + fundo + título "Hóspede do minbak".',
          th: 'อวตาร + กรอบ + พื้นหลัง + ฉายา "แขกของ minbak"',
          id: 'Avatar + bingkai + latar + gelar "Tamu minbak".',
          vi: 'Avatar + khung + hình nền + danh hiệu "Khách của minbak".',
          ja: 'アバター + フレーム + 背景 + 称号「minbak の客」。',
        },
      },
    },
  },
  {
    id: 'level-02',
    number: 2,
    title: {
      en: 'The temple of the rain',
      es: 'El templo de la lluvia',
      fr: 'Le temple de la pluie',
      'pt-BR': 'O templo da chuva',
      th: 'วัดแห่งสายฝน',
      id: 'Kuil hujan',
      vi: 'Ngôi chùa của mưa',
      ja: '雨の寺',
    },
    tagline: {
      en: 'You climbed up to the temple to wait out the downpour. The monk served you tea, smiled, and said the bell only lets out whoever understands what they lost.',
      es: 'Subiste al templo a esperar que pasara el aguacero. El monje te sirvió té, sonrió, y dijo que la campana solo deja salir a quien entiende lo que perdió.',
      fr: "Tu es monté au temple pour attendre que l'averse passe. Le moine t'a servi le thé, a souri, et a dit que la cloche ne laisse sortir que celui qui comprend ce qu'il a perdu.",
      'pt-BR':
        'Você subiu ao templo para esperar a tempestade passar. O monge serviu chá, sorriu, e disse que o sino só deixa sair quem entende o que perdeu.',
      th: 'เธอขึ้นไปบนวัดเพื่อรอให้ฝนหยุด พระหนุ่มเสิร์ฟชาให้เธอ ยิ้ม และบอกว่าระฆังจะปล่อยให้ออกไปได้เฉพาะคนที่เข้าใจสิ่งที่ตนสูญเสียไป',
      id: 'Kamu naik ke kuil untuk menunggu hujan deras reda. Sang biksu menyuguhimu teh, tersenyum, dan berkata bahwa lonceng hanya melepaskan keluar orang yang memahami apa yang telah hilang.',
      vi: 'Bạn lên chùa để đợi cơn mưa rào tạnh. Vị sư rót trà cho bạn, mỉm cười, và nói rằng quả chuông chỉ cho ra đi người nào hiểu được điều mình đã mất.',
      ja: 'あなたは土砂降りが過ぎるのを待とうと寺に登った。僧はお茶を出し、微笑み、鐘は失ったものを理解した者だけを外へ出してくれる、と言った。',
    },
    mood: {
      en: 'Mystical · Contemplative',
      es: 'Místico · Contemplativo',
      fr: 'Mystique · Contemplatif',
      'pt-BR': 'Místico · Contemplativo',
      th: 'ลึกลับ · ครุ่นคิด',
      id: 'Mistis · Kontemplatif',
      vi: 'Huyền bí · Trầm tư',
      ja: '神秘的 · 瞑想的',
    },
    cover: '/escape-room/level-02/rooms/cinematic-intro-v2.webp',
    topikLevel: 2,
    status: 'playable',
    maxErrors: 2,
    rewards: {
      common: {
        id: 'cosmetic-bg-rainsound',
        image: 'cosmetics/cosmetic-bg-rainsound.png',
        name: {
          en: 'Background "빗소리"',
          es: 'Fondo "빗소리"',
          fr: 'Fond « 빗소리 »',
          'pt-BR': 'Fundo "빗소리"',
          th: 'พื้นหลัง "빗소리"',
          id: 'Latar "빗소리"',
          vi: 'Hình nền "빗소리"',
          ja: '背景「빗소리」',
        },
        description: {
          en: 'The roof of the 대웅전 in the rain at dusk; the 49 lanterns like warm halos behind the curtain of water.',
          es: 'El tejado del 대웅전 bajo la lluvia al atardecer; las 49 linternas como halos cálidos tras la cortina de agua.',
          fr: "Le toit du 대웅전 sous la pluie au crépuscule ; les 49 lanternes comme des halos chaleureux derrière le rideau d'eau.",
          'pt-BR':
            'O telhado do 대웅전 sob a chuva ao entardecer; as 49 lanternas como halos quentes atrás da cortina de água.',
          th: 'หลังคาของ 대웅전 ท่ามกลางสายฝนยามเย็น; โคม 49 ดวงเหมือนรัศมีอบอุ่นหลังม่านน้ำ',
          id: 'Atap 대웅전 di tengah hujan saat senja; ke-49 lentera bagai halo hangat di balik tirai air.',
          vi: 'Mái nhà của 대웅전 dưới mưa lúc chiều tà; 49 chiếc đèn lồng như những vầng hào quang ấm áp sau bức màn nước.',
          ja: '夕暮れの雨の中の 대웅전 の屋根；水のカーテンの向こうで温かな光輪のような四十九の灯籠。',
        },
      },
      rare: {
        id: 'cosmetic-frame-dancheong',
        image: 'cosmetics/cosmetic-frame-dancheong.png',
        name: {
          en: 'Frame "단청"',
          es: 'Marco "단청"',
          fr: 'Cadre « 단청 »',
          'pt-BR': 'Moldura "단청"',
          th: 'กรอบ "단청"',
          id: 'Bingkai "단청"',
          vi: 'Khung "단청"',
          ja: 'フレーム「단청」',
        },
        description: {
          en: 'Polychrome temple beams with the 사물 (bell, drum, wooden fish, cloud-plaque) in the corners.',
          es: 'Vigas policromadas del templo con los 사물 (campana, tambor, pez de madera, placa-nube) en las esquinas.',
          fr: 'Poutres polychromes du temple avec les 사물 (cloche, tambour, poisson de bois, plaque-nuage) dans les coins.',
          'pt-BR':
            'Vigas policromadas do templo com os 사물 (sino, tambor, peixe de madeira, placa-nuvem) nos cantos.',
          th: 'คานวัดที่ทาสีหลากสีพร้อม 사물 (ระฆัง, กลอง, ปลาไม้, แผ่นเมฆ) ที่มุมต่างๆ',
          id: 'Balok-balok kuil berwarna-warni dengan 사물 (lonceng, genderang, ikan kayu, papan-awan) di sudut-sudutnya.',
          vi: 'Những xà nhà chùa sơn nhiều màu với bộ 사물 (chuông, trống, mõ cá gỗ, bảng mây) ở các góc.',
          ja: '寺の極彩色の梁、四隅に 사물（鐘、太鼓、木の魚、雲版）。',
        },
      },
      epic: {
        id: 'cosmetic-avatar-templecat',
        image: 'cosmetics/cosmetic-avatar-templecat.png',
        name: {
          en: 'Avatar "절고양이"',
          es: 'Avatar "절고양이"',
          fr: 'Avatar « 절고양이 »',
          'pt-BR': 'Avatar "절고양이"',
          th: 'อวตาร "절고양이"',
          id: 'Avatar "절고양이"',
          vi: 'Avatar "절고양이"',
          ja: 'アバター「절고양이」',
        },
        description: {
          en: "The temple's brown cat sheltered under the eaves; every few cycles it looks at something off-frame.",
          es: 'El gato pardo del templo a resguardo en el alero; cada pocos ciclos mira algo fuera de cuadro.',
          fr: "Le chat brun du temple à l'abri sous l'avant-toit ; à intervalles de quelques cycles, il regarde quelque chose hors champ.",
          'pt-BR':
            'O gato pardo do templo abrigado no beiral; a cada poucos ciclos olha algo fora de quadro.',
          th: 'แมวสีน้ำตาลของวัดที่หลบอยู่ใต้ชายคา; ทุกๆ ไม่กี่รอบจะมองอะไรบางอย่างที่อยู่นอกเฟรม',
          id: 'Kucing cokelat kuil berteduh di bawah tepi atap; setiap beberapa siklus ia menatap sesuatu di luar bingkai.',
          vi: 'Con mèo nâu của ngôi chùa trú dưới mái hiên; cứ vài chu kỳ lại nhìn cái gì đó ngoài khung hình.',
          ja: '軒下で雨宿りする寺の茶色い猫；数サイクルごとに枠の外の何かを見る。',
        },
      },
      legendary: {
        id: 'cosmetic-set-complete-02',
        image: 'cosmetics/cosmetic-set-complete.png',
        name: {
          en: 'Complete set "마흔아홉 번째 손님"',
          es: 'Set completo "마흔아홉 번째 손님"',
          fr: 'Set complet « 마흔아홉 번째 손님 »',
          'pt-BR': 'Conjunto completo "마흔아홉 번째 손님"',
          th: 'เซ็ตเต็ม "마흔아홉 번째 손님"',
          id: 'Set lengkap "마흔아홉 번째 손님"',
          vi: 'Bộ hoàn chỉnh "마흔아홉 번째 손님"',
          ja: 'コンプリートセット「마흔아홉 번째 손님」',
        },
        description: {
          en: "The guest of the 49th day: avatar under the master's paper umbrella, bronze frame with 비천상, and the background of the final shot with the two shadows.",
          es: 'El huésped del día 49: avatar bajo el paraguas de papel del maestro, marco de bronce con 비천상, y el fondo del plano final con las dos sombras.',
          fr: "L'hôte du jour 49 : avatar sous le parapluie en papier du maître, cadre de bronze avec une 비천상, et le fond du plan final avec les deux ombres.",
          'pt-BR':
            'O hóspede do dia 49: avatar sob o guarda-chuva de papel do mestre, moldura de bronze com 비천상, e o fundo do plano final com as duas sombras.',
          th: 'แขกแห่งวันที่ 49: อวตารใต้ร่มกระดาษของอาจารย์ กรอบสำริดพร้อม 비천상 และพื้นหลังของฉากสุดท้ายพร้อมเงาสองเงา',
          id: 'Tamu hari ke-49: avatar di bawah payung kertas sang guru, bingkai perunggu dengan 비천상, dan latar adegan terakhir dengan dua bayangan.',
          vi: 'Vị khách của ngày thứ 49: avatar dưới chiếc ô giấy của thầy, khung đồng với 비천상, và hình nền của cảnh cuối với hai cái bóng.',
          ja: '四十九日目の客：師匠の紙の傘の下のアバター、비천상 をあしらった青銅のフレーム、二つの影のある最終カットの背景。',
        },
      },
    },
  },
  {
    id: 'level-03',
    number: 3,
    title: {
      en: 'The night market',
      es: 'El mercado nocturno',
      fr: 'Le marché nocturne',
      'pt-BR': 'O mercado noturno',
      th: 'ตลาดยามค่ำคืน',
      id: 'Pasar malam',
      vi: 'Chợ đêm',
      ja: '夜市',
    },
    tagline: {
      en: "You went up to the market to grab something to eat before the last bus. The lady at the 호떡 stall took your backpack, smiled, and said: «help me close up and I'll give it back».",
      es: 'Subiste al mercado a comer algo antes del último autobús. La señora del puesto de 호떡 te quitó la mochila, sonrió y dijo: «ayúdame a cerrar y te la devuelvo».',
      fr: "Tu es monté au marché pour manger un morceau avant le dernier bus. La dame du stand de 호떡 t'a pris ton sac à dos, a souri et a dit : « aide-moi à fermer et je te le rends ».",
      'pt-BR':
        'Você subiu ao mercado para comer algo antes do último ônibus. A senhora da barraca de 호떡 tirou sua mochila, sorriu e disse: «me ajude a fechar e eu te devolvo».',
      th: 'เธอขึ้นไปที่ตลาดเพื่อหาอะไรกินก่อนรถเมล์เที่ยวสุดท้าย ป้าเจ้าของแผง 호떡 ปลดเป้ของเธอออก ยิ้ม และพูดว่า: «ช่วยฉันปิดร้านแล้วฉันจะคืนให้»',
      id: 'Kamu naik ke pasar untuk makan sesuatu sebelum bus terakhir. Ibu pemilik kios 호떡 mengambil ranselmu, tersenyum, dan berkata: «bantu aku menutup kios, nanti kukembalikan».',
      vi: 'Bạn lên chợ để ăn chút gì đó trước chuyến xe buýt cuối. Bà chủ quầy 호떡 lấy chiếc ba lô của bạn, mỉm cười và nói: «giúp cô dọn dẹp rồi cô trả lại cho».',
      ja: 'あなたは終バスの前に何か食べようと市場に上がった。호떡 の屋台のおばさんがあなたのリュックを取り上げ、微笑んで言った：「店じまいを手伝ってくれたら返してあげる」。',
    },
    mood: {
      en: 'Energetic · Streetwise',
      es: 'Energético · Callejero',
      fr: 'Énergique · Urbain',
      'pt-BR': 'Enérgico · De rua',
      th: 'มีพลัง · ข้างถนน',
      id: 'Energik · Jalanan',
      vi: 'Tràn đầy năng lượng · Đường phố',
      ja: '活気 · 路地裏',
    },
    cover: '/escape-room/level-03/rooms/cinematic-intro-v2.webp',
    topikLevel: 2,
    status: 'playable',
    maxErrors: 2,
    rewards: {
      common: {
        id: 'cosmetic-bg-neonalley',
        image: 'cosmetics/cosmetic-bg-neonalley.png',
        name: {
          en: 'Background «네온 골목»',
          es: 'Fondo «네온 골목»',
          fr: 'Fond « 네온 골목 »',
          'pt-BR': 'Fundo «네온 골목»',
          th: 'พื้นหลัง «네온 골목»',
          id: 'Latar «네온 골목»',
          vi: 'Hình nền «네온 골목»',
          ja: '背景「네온 골목」',
        },
        description: {
          en: 'The market alley head-on under the night neon: steaming griddles like islands of amber, pink/cyan/green signs like blurred halos, the wet asphalt giving them back broken.',
          es: 'El callejón del mercado de frente bajo el neón nocturno: planchas humeantes como islas de ámbar, carteles rosa/cian/verde como halos difuminados, el asfalto mojado devolviéndolos partidos.',
          fr: "La ruelle du marché de face sous le néon nocturne : planchas fumantes comme des îlots d'ambre, panneaux rose/cyan/vert comme des halos flous, l'asphalte mouillé les renvoyant brisés.",
          'pt-BR':
            'O beco do mercado de frente sob o neon noturno: chapas fumegantes como ilhas de âmbar, cartazes rosa/ciano/verde como halos difusos, o asfalto molhado devolvendo-os partidos.',
          th: 'ซอยตลาดมองจากด้านหน้าใต้แสงนีออนยามค่ำคืน: กระทะที่พ่นไอเหมือนเกาะสีอำพัน ป้ายสีชมพู/ฟ้า/เขียวเหมือนรัศมีพร่ามัว ยางมะตอยที่เปียกชื้นสะท้อนภาพแตกกระจาย',
          id: 'Gang pasar dari depan di bawah neon malam: wajan-wajan datar yang mengepul bagai pulau-pulau amber, papan-papan merah jambu/sian/hijau bagai halo yang kabur, aspal basah memantulkannya terbelah.',
          vi: 'Con ngõ chợ nhìn thẳng dưới ánh neon đêm: những chiếc vỉ bốc hơi như những hòn đảo màu hổ phách, biển hiệu hồng/lục lam/lục như những vầng hào quang nhòe nhoẹt, mặt đường nhựa ẩm ướt phản chiếu chúng vỡ vụn.',
          ja: '夜のネオンの下、正面から見た市場の路地：琥珀色の島のような湯気を立てる鉄板、ぼやけた光輪のようなピンク／シアン／緑の看板、それらを割って映し返す濡れたアスファルト。',
        },
      },
      rare: {
        id: 'cosmetic-frame-hotteokbag',
        image: 'cosmetics/cosmetic-frame-hotteokbag.png',
        name: {
          en: 'Frame «호떡 봉지»',
          es: 'Marco «호떡 봉지»',
          fr: 'Cadre « 호떡 봉지 »',
          'pt-BR': 'Moldura «호떡 봉지»',
          th: 'กรอบ «호떡 봉지»',
          id: 'Bingkai «호떡 봉지»',
          vi: 'Khung «호떡 봉지»',
          ja: 'フレーム「호떡 봉지」',
        },
        description: {
          en: 'Kraft paper bag frame, oil-stained, with market ink stamps in the corners: a griddle, a ladle, a 호떡, and a chopstick.',
          es: 'Marco de bolsa de papel de estraza, manchado de aceite, con sellos de tinta del mercado en las esquinas: una plancha, un cucharón, un 호떡 y un palillo.',
          fr: "Cadre de sachet en papier kraft, taché d'huile, avec des tampons d'encre du marché dans les coins : une plancha, une louche, un 호떡 et un bâtonnet.",
          'pt-BR':
            'Moldura de sacola de papel pardo, manchada de óleo, com carimbos de tinta do mercado nos cantos: uma chapa, uma concha, um 호떡 e um palito.',
          th: 'กรอบถุงกระดาษน้ำตาล เปื้อนน้ำมัน พร้อมตราหมึกของตลาดที่มุมต่างๆ: กระทะ กระบวย 호떡 หนึ่งชิ้น และไม้เสียบ',
          id: 'Bingkai kantong kertas cokelat kasar, bernoda minyak, dengan cap tinta pasar di sudut-sudutnya: sebuah wajan datar, sebuah centong, sebuah 호떡, dan sebatang tusuk.',
          vi: 'Khung túi giấy kraft, lấm lem dầu mỡ, với những con dấu mực của chợ ở các góc: một cái vỉ, một cái vá, một cái 호떡 và một chiếc đũa.',
          ja: '油染みのついたクラフト紙袋のフレーム、四隅に市場のインクの判子：鉄板、杓子、호떡、そして串。',
        },
      },
      epic: {
        id: 'cosmetic-avatar-marketcat',
        image: 'cosmetics/cosmetic-avatar-marketcat.png',
        name: {
          en: 'Avatar «시장 고양이»',
          es: 'Avatar «시장 고양이»',
          fr: 'Avatar « 시장 고양이 »',
          'pt-BR': 'Avatar «시장 고양이»',
          th: 'อวตาร «시장 고양이»',
          id: 'Avatar «시장 고양이»',
          vi: 'Avatar «시장 고양이»',
          ja: 'アバター「시장 고양이」',
        },
        description: {
          en: 'The market cat sitting on a cardboard box next to the griddle; every few cycles it licks its paw and watches the rising steam, with a smear of pink neon crossing its back.',
          es: 'El gato del mercado sentado sobre una caja de cartón junto a la plancha; cada pocos ciclos se lame la pata y mira el vapor que sube, con una mancha de neón rosa cruzándole el lomo.',
          fr: 'Le chat du marché assis sur un carton à côté de la plancha ; à intervalles de quelques cycles, il se lèche la patte et regarde la vapeur monter, avec une tache de néon rose lui traversant le dos.',
          'pt-BR':
            'O gato do mercado sentado sobre uma caixa de papelão junto à chapa; a cada poucos ciclos lambe a pata e olha o vapor que sobe, com uma mancha de neon rosa cruzando o lombo.',
          th: 'แมวตลาดนั่งอยู่บนกล่องกระดาษข้างกระทะ; ทุกๆ ไม่กี่รอบจะเลียอุ้งเท้าและมองไอน้ำที่ลอยขึ้น โดยมีปื้นนีออนสีชมพูพาดผ่านหลังของมัน',
          id: 'Kucing pasar duduk di atas kotak kardus di samping wajan datar; setiap beberapa siklus ia menjilati kakinya dan menatap uap yang mengepul, dengan secercah neon merah jambu melintasi punggungnya.',
          vi: 'Con mèo của chợ ngồi trên một thùng các-tông cạnh cái vỉ; cứ vài chu kỳ lại liếm chân và nhìn làn hơi bốc lên, với một vệt neon hồng lướt ngang lưng.',
          ja: '鉄板の隣の段ボール箱の上に座る市場の猫；数サイクルごとに前足をなめ、立ち上る湯気を見る、背中をピンクのネオンの染みが横切っている。',
        },
      },
      legendary: {
        id: 'cosmetic-set-complete-03',
        image: 'cosmetics/cosmetic-set-complete-03.png',
        name: {
          en: 'Complete set «막차 손님»',
          es: 'Set completo «막차 손님»',
          fr: 'Set complet « 막차 손님 »',
          'pt-BR': 'Conjunto completo «막차 손님»',
          th: 'เซ็ตเต็ม «막차 손님»',
          id: 'Set lengkap «막차 손님»',
          vi: 'Bộ hoàn chỉnh «막차 손님»',
          ja: 'コンプリートセット「막차 손님」',
        },
        description: {
          en: 'The guest of the last bus: avatar with the warm 호떡 in hand wrapped in its napkin, pink-green neon frame with a string of bulbs, and the background of the final shot with the bus pulling away under the neon while 이모 and 하나 wave goodbye from the platform.',
          es: 'El huésped del último bus: avatar con el 호떡 caliente en la mano envuelto en su servilleta, marco de neón rosa-verde con guirnalda de bombillas, y el fondo del plano final con el bus arrancando bajo el neón mientras 이모 y 하나 despiden desde el andén.',
          fr: "L'hôte du dernier bus : avatar avec le 호떡 chaud à la main enveloppé dans sa serviette, cadre de néon rose-vert avec une guirlande d'ampoules, et le fond du plan final avec le bus qui démarre sous le néon tandis que 이모 et 하나 saluent depuis le quai.",
          'pt-BR':
            'O hóspede do último ônibus: avatar com o 호떡 quente na mão envolto no guardanapo, moldura de neon rosa-verde com guirlanda de lâmpadas, e o fundo do plano final com o ônibus arrancando sob o neon enquanto 이모 e 하나 se despedem da plataforma.',
          th: 'แขกของรถเมล์เที่ยวสุดท้าย: อวตารพร้อม 호떡 ร้อนในมือห่อด้วยกระดาษทิชชู กรอบนีออนสีชมพู-เขียวพร้อมพวงหลอดไฟ และพื้นหลังของฉากสุดท้ายพร้อมรถเมล์ที่ออกตัวใต้แสงนีออนขณะที่ 이모 และ 하나 ส่งจากชานชาลา',
          id: 'Tamu bus terakhir: avatar dengan 호떡 panas di tangan terbungkus tisunya, bingkai neon merah jambu-hijau dengan untaian bohlam, dan latar adegan terakhir dengan bus yang berangkat di bawah neon sementara 이모 dan 하나 melepas dari peron.',
          vi: 'Vị khách của chuyến xe cuối: avatar với chiếc 호떡 nóng trong tay được gói trong tờ giấy ăn, khung neon hồng-lục với dây bóng đèn, và hình nền của cảnh cuối với chiếc xe buýt khởi hành dưới ánh neon trong khi 이모 và 하나 tiễn biệt từ sân ga.',
          ja: '終バスの客：ナプキンに包んだ熱い 호떡 を手にしたアバター、電球の花綱つきのピンク・緑のネオンのフレーム、そして 이모 と 하나 がプラットホームから見送るなか、ネオンの下でバスが動き出す最終カットの背景。',
        },
      },
    },
  },
  {
    id: 'level-04',
    number: 4,
    title: {
      en: 'The last train to Seoul',
      es: 'El último tren a Seúl',
      fr: 'Le dernier train pour Séoul',
      'pt-BR': 'O último trem para Seul',
      th: 'รถไฟเที่ยวสุดท้ายสู่โซล',
      id: 'Kereta terakhir ke Seoul',
      vi: 'Chuyến tàu cuối về Seoul',
      ja: 'Seoul 行きの終電',
    },
    tagline: {
      en: 'The storm erased the displays, the platform changed, and only minutes remain before the final train leaves this station.',
      es: 'La tormenta borró los paneles, el andén cambió y quedan minutos para el último tren que saldrá de esta estación.',
      fr: 'La tempête a effacé les panneaux, le quai a changé et il ne reste que quelques minutes avant le départ du dernier train.',
      'pt-BR':
        'A tempestade apagou os painéis, a plataforma mudou e faltam poucos minutos para o último trem que partirá desta estação.',
      th: 'พายุได้ลบแผง ชานชาลาเปลี่ยนไป และเหลือเวลาอีกไม่กี่นาทีก่อนที่รถไฟขบวนสุดท้ายจะออกจากสถานีนี้',
      id: 'Badai menghapus tampilan papan, peron telah berubah, dan hanya tersisa beberapa menit sebelum kereta terakhir meninggalkan stasiun ini.',
      vi: 'Cơn bão đã xóa bỏ các tấm bảng, sân ga đã thay đổi và còn vài phút nữa là đến chuyến tàu cuối cùng sẽ rời khỏi ga này.',
      ja: '嵐で掲示板が消え、発着ホームも変わった。この駅を出る最後の列車まで、残された時間はあとわずか。',
    },
    mood: {
      en: 'Urgent · Contemporary',
      es: 'Urgente · Contemporáneo',
      fr: 'Urgent · Contemporain',
      'pt-BR': 'Urgente · Contemporâneo',
      th: 'เร่งด่วน · ร่วมสมัย',
      id: 'Mendesak · Kontemporer',
      vi: 'Gấp gáp · Đương đại',
      ja: '切迫 · 現代',
    },
    cover: '/escape-room/level-04/rooms/cinematic-intro-v2.webp',
    topikLevel: 3,
    status: 'playable',
    maxErrors: 2,
    rewards: {
      common: {
        id: 'cosmetic-bg-rainy-rails',
        image: 'cosmetics/cosmetic-bg-rainy-rails.png',
        name: {
          en: 'Background “Rails in the Rain”',
          es: 'Fondo «Raíles bajo la lluvia»',
          fr: 'Arrière-plan «Rails sous la pluie»',
          'pt-BR': 'Plano de fundo «Trilhos na chuva»',
          th: 'พื้นหลัง "รางในสายฝน"',
          id: 'Latar «Rel di Tengah Hujan»',
          vi: 'Phông nền «Đường ray dưới mưa»',
          ja: '背景「雨のレール」',
        },
        description: {
          en: 'The amber reflection of the final train stretching across two rain-soaked tracks.',
          es: 'El reflejo ámbar del último tren estirándose sobre dos vías mojadas.',
          fr: "Le reflet ambré du dernier train s'étirant sur deux voies détrempées.",
          'pt-BR': 'O reflexo âmbar do último trem se estendendo em dois trilhos molhados.',
          th: 'เงาสะท้อนของรถไฟขบวนสุดท้ายที่ทอดยาวไปบนรางเปียกสองราง',
          id: 'Pantulan kuning keemasan kereta terakhir memanjang di atas dua rel basah.',
          vi: 'Ánh sáng hổ phách của chuyến tàu cuối cùng kéo dài trên hai đường ray ướt.',
          ja: '濡れた二本の線路に長く伸びる、最終列車の琥珀色の反射。',
        },
      },
      rare: {
        id: 'cosmetic-frame-paper-ticket',
        image: 'cosmetics/cosmetic-frame-paper-ticket.png',
        name: {
          en: 'Frame “Ticket to 해솔”',
          es: 'Marco «Billete de 해솔»',
          fr: 'Cadre «Billet pour 해솔»',
          'pt-BR': 'Moldura «Bilhete de 해솔»',
          th: 'กรอบ “ตั๋ว 해솔”',
          id: 'Bingkai «Tiket 해솔»',
          vi: 'Khung «Vé ga 해솔»',
          ja: 'フレーム「해솔 の切符」',
        },
        description: {
          en: 'A frame of punched railway card, its corners worn by countless journeys.',
          es: 'Un marco de cartón ferroviario perforado, con esquinas gastadas por muchos viajes.',
          fr: "Un cadre en carton ferroviaire perforé, aux coins usés par d'innombrables voyages.",
          'pt-BR':
            'Uma moldura ferroviária de papelão perfurada, com cantos desgastados por muitas viagens.',
          th: 'โครงกระดาษแข็งเจาะรู มีมุมชำรุดจากการเดินทางหลายครั้ง',
          id: 'Bingkai karton tiket kereta yang berlubang, dengan sudut-sudut aus oleh banyak perjalanan.',
          vi: 'Một khung bìa cứng của đường sắt có lỗ, với các góc bị mòn do nhiều chuyến đi.',
          ja: '旅を重ねて角が擦れた、鉄道切符風の穴あき厚紙フレーム。',
        },
      },
      epic: {
        id: 'cosmetic-avatar-green-lamp',
        image: 'cosmetics/cosmetic-avatar-green-lamp.png',
        name: {
          en: 'Avatar “Departure Lamp”',
          es: 'Avatar «Lámpara de salida»',
          fr: 'Avatar «Lampe de départ»',
          'pt-BR': 'Avatar «Lâmpada de saída»',
          th: 'อวตาร «โคมไฟทางออก»',
          id: 'Avatar «Lampu Keberangkatan»',
          vi: 'Ảnh đại diện «Đèn xuất»',
          ja: 'アバター「出発合図灯」',
        },
        description: {
          en: "The stationmaster's green departure lamp shining against the storm.",
          es: 'La lámpara verde del jefe de estación brillando contra la tormenta.',
          fr: 'La lampe verte de départ du chef de gare, brillant contre la tempête.',
          'pt-BR': 'A lâmpada verde do chefe da estação brilhando contra a tempestade.',
          th: 'โคมไฟสีเขียวของนายสถานีส่องแสงท่ามกลางพายุ',
          id: 'Lampu hijau kepala stasiun bersinar menghadapi badai.',
          vi: 'Đèn màu xanh của trưởng ga chiếu sáng trong cơn bão.',
          ja: '嵐の中で輝く、駅長の緑の合図灯。',
        },
      },
      legendary: {
        id: 'cosmetic-set-complete-04',
        image: 'cosmetics/cosmetic-set-complete-04.png',
        name: {
          en: 'Complete set “마지막 역무원”',
          es: 'Set completo «마지막 역무원»',
          fr: 'Ensemble complet «마지막 역무원»',
          'pt-BR': 'Conjunto completo «마지막 역무원»',
          th: 'เซ็ตครบชุด «마지막 역무원»',
          id: 'Set lengkap «마지막 역무원»',
          vi: 'Trọn bộ «마지막 역무원»',
          ja: 'コンプリートセット「마지막 역무원」',
        },
        description: {
          en: "Ticket, cap, lamp, and final platform united in the last stationmaster's set.",
          es: 'Billete, gorra, lámpara y el andén final reunidos en el set del último jefe de estación.',
          fr: "Billet, casquette, lampe et dernier quai réunis dans l'ensemble du dernier chef de gare.",
          'pt-BR':
            'Bilhete, boné, lâmpada e plataforma final reunidos no conjunto do último chefe da estação.',
          th: 'ตั๋ว หมวก โคมไฟ และแท่นสุดท้ายมารวมตัวกันในชุดของนายสถานีคนสุดท้าย',
          id: 'Tiket, topi, lampu, dan peron terakhir dipadukan dalam set kepala stasiun terakhir.',
          vi: 'Vé, mũ, đèn và sân ga cuối cùng tụ họp tại bối cảnh của trưởng ga cuối cùng.',
          ja: '切符、帽子、合図灯、最後のホームをそろえた、最後の駅長のセット。',
        },
      },
    },
  },
  {
    id: 'level-05',
    number: 5,
    title: {
      en: "Grandfather's kitchen",
      es: 'La cocina del abuelo',
      fr: 'La cuisine du grand-père',
      'pt-BR': 'A cozinha do avô',
      th: 'ครัวของคุณตา',
      id: 'Dapur sang kakek',
      vi: 'Căn bếp của ông',
      ja: 'おじいちゃんの台所',
    },
    tagline: {
      en: 'One final reservation, a recipe full of corrections, and the flavour your grandfather refuses to measure with numbers alone.',
      es: 'Una última reserva, una receta llena de correcciones y el sabor que tu abuelo se niega a medir solo con números.',
      fr: 'Une dernière réservation, une recette pleine de corrections et le goût que votre grand-père refuse de mesurer avec des chiffres seuls.',
      'pt-BR':
        'Uma última reserva, uma receita cheia de correções e o sabor que seu avô se recusa a medir apenas com números.',
      th: 'การจองครั้งสุดท้าย สูตรที่เต็มไปด้วยการแก้ไข และรสชาติที่ปู่ของคุณปฏิเสธที่จะวัดด้วยตัวเลขเพียงอย่างเดียว',
      id: 'Satu reservasi terakhir, sebuah resep penuh koreksi, dan rasa yang tidak mau diukur Kakek hanya dengan angka.',
      vi: 'Một lần đặt chỗ cuối cùng, một công thức đầy những sửa đổi và hương vị mà ông bạn từ chối chỉ đo bằng con số.',
      ja: '残る予約はあと一組。書き直しだらけのレシピと、祖父が数字だけでは量ろうとしない味。',
    },
    mood: {
      en: 'Nostalgic · Family-centered',
      es: 'Nostálgico · Familiar',
      fr: 'Nostalgique · Familial',
      'pt-BR': 'Nostálgico · Familiar',
      th: 'ถวิลหาอดีต · อบอุ่นแบบครอบครัว',
      id: 'Nostalgis · Kekeluargaan',
      vi: 'Hoài niệm · Gia đình',
      ja: '懐かしい · 家族',
    },
    cover: '/escape-room/level-05/rooms/cinematic-intro-v2.webp',
    topikLevel: 3,
    status: 'playable',
    maxErrors: 2,
    rewards: {
      common: {
        id: 'cosmetic-bg-grandfather-kitchen',
        image: 'cosmetics/cosmetic-bg-grandfather-kitchen.png',
        name: {
          en: 'Background “Sunday Steam”',
          es: 'Fondo «Vapor del domingo»',
          fr: 'Arrière-plan «Vapeur du dimanche»',
          'pt-BR': 'Plano de fundo «Vapor de domingo»',
          th: 'พื้นหลัง “ซันเดย์สตีม”',
          id: 'Latar «Uap Hari Minggu»',
          vi: 'Phông nền «Hơi nước Chủ nhật»',
          ja: '背景「日曜日の湯気」',
        },
        description: {
          en: 'The kitchen at dawn, with six bowls and a pot breathing over a low flame.',
          es: 'La cocina al amanecer, con seis cuencos y una olla respirando sobre el fuego bajo.',
          fr: "La cuisine à l'aube, avec six bols et une marmite qui respire sur un feu doux.",
          'pt-BR':
            'A cozinha ao amanhecer, com seis tigelas e uma panela respirando sobre o fogo baixo.',
          th: 'ห้องครัวยามรุ่งสาง มีชามหกใบและหม้อพ่นไฟเหนือไฟ',
          id: 'Dapur saat fajar, dengan enam mangkuk dan sebuah panci yang mengepul di atas api kecil.',
          vi: 'Nhà bếp vào lúc bình minh, với sáu bát và một chiếc nồi đang thở trên ngọn lửa thấp.',
          ja: '夜明けの厨房。六つの椀と、弱火の上で静かに息づく鍋。',
        },
      },
      rare: {
        id: 'cosmetic-frame-fermentation-jar',
        image: 'cosmetics/cosmetic-frame-fermentation-jar.png',
        name: {
          en: 'Frame “장독대”',
          es: 'Marco «장독대»',
          fr: 'Cadre «장독대»',
          'pt-BR': 'Quadro «장독대»',
          th: 'กรอบ «장독대»',
          id: 'Bingkai «장독대»',
          vi: 'Khung «장독대»',
          ja: 'フレーム「장독대」',
        },
        description: {
          en: 'Earthenware jars, handwritten labels, and mulberry leaves surround the portrait.',
          es: 'Tinajas de barro, etiquetas manuscritas y hojas de morera rodean el retrato.',
          fr: 'Des jarres en terre, des étiquettes manuscrites et des feuilles de mûrier entourent le portrait.',
          'pt-BR': 'Potes de barro, etiquetas manuscritas e folhas de amoreira cercam o retrato.',
          th: 'โถดินเผา ป้ายที่เขียนด้วยลายมือ และใบหม่อนล้อมรอบภาพบุคคล',
          id: 'Tempayan tanah liat, label tulisan tangan, dan daun murbei mengelilingi potret.',
          vi: 'Những chum đất, nhãn viết tay và lá dâu bao quanh bức chân dung.',
          ja: '土の甕、手書きの札、桑紙の葉が肖像を囲む。',
        },
      },
      epic: {
        id: 'cosmetic-avatar-recipe-ladle',
        image: 'cosmetics/cosmetic-avatar-recipe-ladle.png',
        name: {
          en: 'Avatar “Ladle of Memory”',
          es: 'Avatar «Cucharón de memoria»',
          fr: 'Avatar «Louche des souvenirs»',
          'pt-BR': 'Avatar «Concha de memória»',
          th: 'อวตาร «ทัพพีแห่งความทรงจำ»',
          id: 'Avatar «Sendok Sayur Kenangan»',
          vi: 'Ảnh đại diện «Muỗng ký ức»',
          ja: 'アバター「記憶のおたま」',
        },
        description: {
          en: "Grandpa's old wooden ladle, polished by forty years of Sundays.",
          es: 'El viejo cucharón de madera del abuelo, pulido por cuarenta años de domingos.',
          fr: 'La vieille louche en bois de Grand-père, polie par quarante années de dimanches.',
          'pt-BR': 'A velha concha de madeira do vovô, polida por quarenta anos de domingos.',
          th: 'ทัพพีไม้เก่าของคุณปู่ ขัดโดยวันอาทิตย์สี่สิบปี',
          id: 'Sendok sayur kayu tua milik Kakek, mengilap setelah empat puluh tahun digunakan setiap hari Minggu.',
          vi: 'Cái vá gỗ cũ của ông, được đánh bóng bởi bốn mươi năm Chủ nhật.',
          ja: '四十年分の日曜日に磨かれた、祖父の古い木のおたま。',
        },
      },
      legendary: {
        id: 'cosmetic-set-complete-05',
        image: 'cosmetics/cosmetic-set-complete-05.png',
        name: {
          en: 'Complete set “기억의 조리법”',
          es: 'Set completo «기억의 조리법»',
          fr: 'Ensemble complet «기억의 조리법»',
          'pt-BR': 'Conjunto completo «기억의 조리법»',
          th: 'เซ็ตครบชุด «기억의 조리법»',
          id: 'Set lengkap «기억의 조리법»',
          vi: 'Trọn bộ «기억의 조리법»',
          ja: 'コンプリートセット「기억의 조리법」',
        },
        description: {
          en: 'Notebook, earthenware jar, ladle, and table united in the recipe of memory set.',
          es: 'Cuaderno, tinaja, cucharón y mesa reunidos en el set de la receta de la memoria.',
          fr: "Cahier, jarre, louche et table réunis dans l'ensemble de la recette des souvenirs.",
          'pt-BR': 'Caderno, pote, concha e mesa reunidos no conjunto da receita da memória.',
          th: 'สมุดบันทึก โถ ทัพพี และโต๊ะ รวมอยู่ในชุดสูตรความจำ',
          id: 'Buku catatan, tempayan, sendok sayur, dan meja dipadukan dalam set resep kenangan.',
          vi: 'Vở, bình, muỗng và bàn tụ họp trên bối cảnh của công thức ký ức.',
          ja: '帳面、甕、おたま、食卓をそろえた、記憶のレシピセット。',
        },
      },
    },
  },
  {
    id: 'level-06',
    number: 6,
    title: {
      en: 'The K-drama studio',
      es: 'El estudio de K-drama',
      fr: 'Le studio de K-drama',
      'pt-BR': 'O estúdio de K-drama',
      th: 'สตูดิโอ K-drama',
      id: 'Studio K-drama',
      vi: 'Phim trường K-drama',
      ja: 'K-drama の撮影スタジオ',
    },
    tagline: {
      en: 'The lead never arrived, the script is soaked, and the director has just pointed at you: rebuild the episode while the cameras keep rolling.',
      es: 'El protagonista no llegó, el guion está empapado y la directora acaba de señalarte: reconstruye el episodio mientras las cámaras siguen grabando.',
      fr: "La vedette n'est pas arrivée, le scénario est trempé et la réalisatrice vient de vous désigner: reconstruisez l'épisode pendant que les caméras tournent.",
      'pt-BR':
        'O protagonista não chegou, o roteiro está encharcado e a diretora acaba de apontar para você: reconstrua o episódio enquanto as câmeras continuam gravando.',
      th: 'ตัวเอกไม่มา บทละครเปียกโชก และผู้กำกับเพิ่งชี้ไปที่คุณ: สร้างฉากนั้นขึ้นมาใหม่ในขณะที่กล้องยังถ่ายอยู่',
      id: 'Pemeran utama belum tiba, naskahnya basah kuyup, dan sutradara baru saja menunjukmu: susun kembali episode itu sementara kamera terus merekam.',
      vi: 'Nhân vật chính không đến, kịch bản đã ướt sũng và đạo diễn vừa chỉ vào bạn: hãy tái hiện lại tập phim trong khi các máy quay vẫn tiếp tục ghi hình.',
      ja: '主演は来ない。台本はずぶ濡れ。監督があなたを指名した。カメラが回り続ける中、第16話を組み直せ。',
    },
    mood: {
      en: 'Meta-pop · Fun',
      es: 'Meta-pop · Divertido',
      fr: 'Méta-pop · Amusant',
      'pt-BR': 'Meta-pop · Divertido',
      th: 'เมต้า-ป็อป · สนุกสนาน',
      id: 'Meta-pop · Seru',
      vi: 'Meta-pop · Vui nhộn',
      ja: 'メタ・ポップ · 楽しい',
    },
    cover: '/escape-room/level-06/rooms/cinematic-intro-v2.webp',
    topikLevel: 4,
    status: 'playable',
    maxErrors: 2,
    rewards: {
      common: {
        id: 'cosmetic-bg-summer-studio',
        image: 'cosmetics/cosmetic-bg-summer-studio.webp',
        name: {
          en: 'Background “한여름 세트”',
          es: 'Fondo «한여름 세트»',
          fr: 'Arrière-plan «한여름 세트»',
          'pt-BR': 'Plano de fundo «한여름 세트»',
          th: 'พื้นหลัง «한여름 세트»',
          id: 'Latar «한여름 세트»',
          vi: 'Phông nền «한여름 세트»',
          ja: '背景「한여름 세트」',
        },
        description: {
          en: "The television rooftop at sunset, with mechanical rain and the cyclorama's edge revealing the illusion.",
          es: 'La azotea televisiva al atardecer, con lluvia mecánica y el borde del ciclorama revelando el truco.',
          fr: "Le toit du studio au couchant, avec sa pluie mécanique et le bord du cyclorama qui révèle l'illusion.",
          'pt-BR':
            'A cobertura da televisão ao pôr do sol, com a chuva mecânica e a borda do ciclorama revelando a manobra.',
          th: 'ดาดฟ้าโทรทัศน์ยามพระอาทิตย์ตกดิน โดยมีฝนตกหนักและขอบไซโคลรามาเผยให้เห็นเคล็ดลับ',
          id: 'Atap studio televisi saat senja, dengan hujan mekanis dan tepi siklorama yang membongkar triknya.',
          vi: 'Sân thượng trường quay lúc hoàng hôn, với mưa nhân tạo và mép phông nền cong để lộ kỹ xảo.',
          ja: '夕暮れのテレビ屋上セット。人工の雨と、仕掛けを見せるホリゾントの端。',
        },
      },
      rare: {
        id: 'cosmetic-frame-clapperboard',
        image: 'cosmetics/cosmetic-frame-clapperboard.png',
        name: {
          en: 'Frame “마지막 테이크”',
          es: 'Marco «마지막 테이크»',
          fr: 'Cadre «마지막 테이크»',
          'pt-BR': 'Quadro «마지막 테이크»',
          th: 'กรอบ «마지막 테이크»',
          id: 'Bingkai «마지막 테이크»',
          vi: 'Khung «마지막 테이크»',
          ja: 'フレーム「마지막 테이크」',
        },
        description: {
          en: 'A clapperboard frame with camera tape and tiny continuity marks in electric blue.',
          es: 'Un marco de claqueta, cinta de cámara y pequeñas marcas de continuidad en azul eléctrico.',
          fr: 'Un cadre en forme de clap, avec ruban de caméra et petites marques de raccord bleu électrique.',
          'pt-BR':
            'Moldura de claquete, fita de câmera e pequenas marcas de continuidade em azul elétrico.',
          th: 'กรอบตกแต่งด้วยแผ่นสเลต เทปกล้อง และเครื่องหมายความต่อเนื่องเล็ก ๆ สีฟ้าไฟฟ้า',
          id: 'Bingkai papan adegan, pita kamera, dan tanda kontinuitas kecil berwarna biru elektrik.',
          vi: 'Một khung trang trí bằng bảng ghi cảnh, băng máy quay và những dấu nối cảnh nhỏ màu xanh điện.',
          ja: 'カチンコ、カメラテープ、鮮やかな青のコンティニュイティ記号をあしらったフレーム。',
        },
      },
      epic: {
        id: 'cosmetic-avatar-extra-47',
        image: 'cosmetics/cosmetic-avatar-extra-47.png',
        name: {
          en: 'Avatar “엑스트라 47번”',
          es: 'Avatar «엑스트라 47번»',
          fr: 'Avatar «엑스트라 47번»',
          'pt-BR': 'Avatar «엑스트라 47번»',
          th: 'อวตาร «엑스트라 47번»',
          id: 'Avatar «엑스트라 47번»',
          vi: 'Ảnh đại diện «엑스트라 47번»',
          ja: 'アバター「엑스트라 47번」',
        },
        description: {
          en: 'Extra number forty-seven, blue umbrella in hand, wearing the expression of an accidental lead.',
          es: 'El extra número cuarenta y siete con paraguas azul y expresión de protagonista accidental.',
          fr: "L'extra numéro quarante-sept, parapluie bleu en main, avec l'expression d'une vedette par accident.",
          'pt-BR':
            'Número extra quarenta e sete com guarda-chuva azul e expressão de protagonista acidental.',
          th: 'ตัวประกอบหมายเลขสี่สิบเจ็ดถือร่มสีน้ำเงิน พร้อมสีหน้าราวกับกลายเป็นตัวเอกโดยไม่ตั้งใจ',
          id: 'Figuran nomor empat puluh tujuh dengan payung biru dan ekspresi pemeran utama yang tidak disengaja.',
          vi: 'Diễn viên quần chúng số bốn mươi bảy với chiếc ô xanh và biểu cảm như nhân vật chính tình cờ.',
          ja: '青い傘を持ち、思いがけず主演の表情を見せるエキストラ47番。',
        },
      },
      legendary: {
        id: 'cosmetic-set-complete-06',
        image: 'cosmetics/cosmetic-set-complete-06.png',
        name: {
          en: 'Complete set “카메라는 돌고 있다”',
          es: 'Set completo «카메라는 돌고 있다»',
          fr: 'Ensemble complet «카메라는 돌고 있다»',
          'pt-BR': 'Conjunto completo «카메라는 돌고 있다»',
          th: 'เซ็ตครบชุด «카메라는 돌고 있다»',
          id: 'Set lengkap «카메라는 돌고 있다»',
          vi: 'Trọn bộ «카메라는 돌고 있다»',
          ja: 'コンプリートセット「카메라는 돌고 있다」',
        },
        description: {
          en: 'The entire studio mid-take: rain, spotlights, monitors, and the whole crew finally entering the frame.',
          es: 'El estudio completo en plena toma: lluvia, focos, monitores y todo el equipo entrando por fin en el encuadre.',
          fr: "Le studio entier en pleine prise: pluie, projecteurs, moniteurs et toute l'équipe entrant enfin dans le cadre.",
          'pt-BR':
            'O estúdio inteiro em plena gravação: chuva, refletores, monitores e toda a equipe finalmente entrando no enquadramento.',
          th: 'ภาพทั้งสตูดิโอถ่ายเต็มทั้งฝนตก สปอตไลท์ จอภาพ และอุปกรณ์ทั้งหมดเข้ามาในเฟรมในที่สุด',
          id: 'Seluruh studio saat pengambilan gambar: hujan, lampu sorot, monitor, dan seluruh kru akhirnya masuk ke dalam bingkai.',
          vi: 'Toàn bộ trường quay giữa lúc ghi hình: mưa, đèn chiếu, màn hình và cả đoàn cuối cùng cùng bước vào khung hình.',
          ja: '雨、照明、モニター、そしてスタッフ全員がついに画面へ入る、撮影中のスタジオセット。',
        },
      },
    },
  },
  {
    id: 'level-07',
    number: 7,
    title: {
      en: 'The company retreat',
      es: 'El retiro de la empresa',
      fr: "Le séminaire d'entreprise",
      'pt-BR': 'O retiro da empresa',
      th: 'ทริปบริษัท',
      id: 'Retret perusahaan',
      vi: 'Chuyến nghỉ dưỡng của công ty',
      ja: '会社の研修',
    },
    tagline: {
      en: 'Your first corporate retreat ends at night, in the rain, with two teams fighting over a box that opens only when they stop competing.',
      es: 'Tu primer retiro corporativo termina de noche, bajo la lluvia y con dos equipos disputándose una caja que solo se abre cuando dejan de competir.',
      fr: "Votre premier séminaire d'entreprise s'achève de nuit, sous la pluie, avec deux équipes qui se disputent une boîte ne s'ouvrant que lorsqu'elles cessent de rivaliser.",
      'pt-BR':
        'Seu primeiro retiro corporativo termina à noite, sob a chuva, com duas equipes disputando uma caixa que só se abre quando elas param de competir.',
      th: 'การลาออกจากบริษัทครั้งแรกของคุณจบลงในตอนกลางคืน ภายใต้สายฝน และกับสองทีมที่กำลังแข่งขันกันเพื่อกล่องที่เปิดได้ก็ต่อเมื่อพวกเขาหยุดการแข่งขัน',
      id: 'Retret perusahaan pertamamu berakhir pada malam hari, di tengah hujan, dengan dua tim memperebutkan kotak yang hanya terbuka ketika mereka berhenti bersaing.',
      vi: 'Chuyến nghỉ dưỡng công ty đầu tiên của bạn kết thúc vào ban đêm, dưới mưa và với hai đội đang tranh giành một chiếc hộp chỉ mở ra khi họ ngừng cạnh tranh.',
      ja: '初めての社員研修は、雨の夜と賞品箱を争う二チームで終わる。その箱が開くのは、彼らが競うことをやめたときだけ。',
    },
    mood: {
      en: 'Corporate · After Dark',
      es: 'Corporativo · Nocturno',
      fr: 'Séminaire d’entreprise · Nocturne',
      'pt-BR': 'Corporativo · Noturno',
      th: 'องค์กร · ยามค่ำคืน',
      id: 'Korporat · Malam',
      vi: 'Công sở · Về đêm',
      ja: '企業 · 夜',
    },
    cover: '/escape-room/level-07/rooms/cinematic-intro-v2.webp',
    topikLevel: 4,
    status: 'playable',
    maxErrors: 2,
    rewards: {
      common: {
        id: 'cosmetic-bg-night-retreat',
        image: 'cosmetics/cosmetic-bg-night-retreat.webp',
        name: {
          en: 'Background “야간 워크숍”',
          es: 'Fondo «야간 워크숍»',
          fr: 'Arrière-plan «야간 워크숍»',
          'pt-BR': 'Plano de fundo «야간 워크숍»',
          th: 'พื้นหลัง «야간 워크숍»',
          id: 'Latar «야간 워크숍»',
          vi: 'Phông nền «야간 워크숍»',
          ja: '背景「야간 워크숍」',
        },
        description: {
          en: 'The mountain lodge beneath blue rain, its windows warm and two flashlight trails meeting again.',
          es: 'El refugio de montaña bajo lluvia azul, con ventanas cálidas y dos senderos de linternas que vuelven a encontrarse.',
          fr: 'Le refuge de montagne sous une pluie bleue, ses fenêtres chaleureuses et deux pistes de lampes torches qui se rejoignent.',
          'pt-BR':
            'O refúgio da montanha sob a chuva azul, com janelas quentes e dois trilhos de lanternas que se reencontram.',
          th: 'ที่พักในภูเขาท่ามกลางสายฝนสีฟ้า พร้อมหน้าต่างที่อบอุ่นและเส้นทางโคมไฟสองเส้นทางที่กลับมาพบกันอีกครั้ง',
          id: 'Penginapan pegunungan di bawah hujan biru, dengan jendela hangat dan dua jalur senter yang kembali bertemu.',
          vi: 'Chỗ trú núi dưới mưa xanh, với những cửa sổ ấm áp và hai con đường mòn đèn lồng hội tụ trở lại.',
          ja: '青い雨に包まれた山荘。暖かな窓と、再び合流する二筋の灯り。',
        },
      },
      rare: {
        id: 'cosmetic-frame-team-badges',
        image: 'cosmetics/cosmetic-frame-team-badges.png',
        name: {
          en: 'Frame “한 팀”',
          es: 'Marco «한 팀»',
          fr: 'Cadre «한 팀»',
          'pt-BR': 'Quadro «한 팀»',
          th: 'กรอบ «한 팀»',
          id: 'Bingkai «한 팀»',
          vi: 'Khung «한 팀»',
          ja: 'フレーム「한 팀」',
        },
        description: {
          en: 'Blue and Amber badges joined by a safety cord and small rain-soaked leaves.',
          es: 'Las insignias Azul y Ámbar unidas por una cuerda de seguridad y pequeñas hojas mojadas.',
          fr: 'Les insignes des équipes Bleue et Ambre reliés par un cordon de sécurité et de petites feuilles mouillées.',
          'pt-BR':
            'As insígnias Azul e Âmbar unidas por uma corda de segurança e pequenas folhas molhadas.',
          th: 'ตราสัญลักษณ์สีน้ำเงินและสีอำพันเชื่อมด้วยเชือกนิรภัยและใบเล็กที่เปียก',
          id: 'Lambang Biru dan Amber disatukan oleh tali pengaman dan daun-daun kecil yang basah.',
          vi: 'Các huân chương Xanh và Hổ phách nối với nhau bằng một sợi dây an toàn và những chiếc lá nhỏ ướt đẫm.',
          ja: '安全ロープと濡れた小さな葉で結ばれた、ブルーとアンバーの徽章。',
        },
      },
      epic: {
        id: 'cosmetic-avatar-radio-lead',
        image: 'cosmetics/cosmetic-avatar-radio-lead.png',
        name: {
          en: 'Avatar “신입 인솔자”',
          es: 'Avatar «신입 인솔자»',
          fr: 'Avatar «신입 인솔자»',
          'pt-BR': 'Avatar «신입 인솔자»',
          th: 'อวตาร «신입 인솔자»',
          id: 'Avatar «신입 인솔자»',
          vi: 'Ảnh đại diện «신입 인솔자»',
          ja: 'アバター「신입 인솔자」',
        },
        description: {
          en: 'The new employee with flashlight, radio, and formal folder, guiding without leaving anyone behind.',
          es: 'El empleado nuevo con linterna, radio y carpeta formal, guiando sin dejar a nadie atrás.',
          fr: 'Le nouvel employé avec lampe torche, radio et dossier officiel, guidant le groupe sans abandonner personne.',
          'pt-BR':
            'O novo funcionário com lanterna, rádio e pasta formal, orientando sem deixar ninguém para trás.',
          th: 'พนักงานใหม่พร้อมไฟฉาย วิทยุ และแฟ้มอย่างเป็นทางการ นำทางโดยไม่ทิ้งใครไว้ข้างหลัง',
          id: 'Karyawan baru dengan senter, radio, dan map resmi, memandu tanpa meninggalkan siapa pun.',
          vi: 'Nhân viên mới với đèn pin, radio và cặp tài liệu, dẫn đường mà không bỏ lại ai phía sau.',
          ja: '懐中電灯、無線機、業務ファイルを手に、誰も置き去りにせず導く新人社員。',
        },
      },
      legendary: {
        id: 'cosmetic-set-complete-07',
        image: 'cosmetics/cosmetic-set-complete-07.png',
        name: {
          en: 'Complete set “모두의 보상”',
          es: 'Set completo «모두의 보상»',
          fr: 'Ensemble complet «모두의 보상»',
          'pt-BR': 'Conjunto completo «모두의 보상»',
          th: 'เซ็ตครบชุด «모두의 보상»',
          id: 'Set lengkap «모두의 보상»',
          vi: 'Trọn bộ «모두의 보상»',
          ja: 'コンプリートセット「모두의 보상」',
        },
        description: {
          en: 'The open box beside the campfire: envelopes for everyone, two linked badges, and the whole team beneath one awning.',
          es: 'La caja abierta junto a la fogata: sobres para todos, dos insignias enlazadas y el equipo completo bajo un mismo toldo.',
          fr: "La boîte ouverte près du feu: des enveloppes pour tous, deux insignes reliés et toute l'équipe sous le même auvent.",
          'pt-BR':
            'A caixa aberta perto da fogueira: envelopes para todos, dois crachás interligados e toda a equipe sob o mesmo toldo.',
          th: 'กล่องที่เปิดอยู่ข้างกองไฟ: ซองจดหมายสำหรับทุกคน, เข็มกลัดสองอันที่เชื่อมต่อกัน และอุปกรณ์ครบชุดใต้เต็นท์เดียวกัน',
          id: 'Kotak terbuka di dekat api unggun: amplop untuk semua orang, dua lambang yang terhubung, dan seluruh tim di bawah satu terpal.',
          vi: 'Chiếc hộp mở bên cạnh đống lửa: phong bì cho mọi người, hai huy hiệu nối với nhau và toàn bộ đội dưới một tấm mui duy nhất.',
          ja: '焚き火のそばで開いた箱。全員分の封筒、つながった二つの徽章、同じ屋根に集うチーム。',
        },
      },
    },
  },
  {
    id: 'level-08',
    number: 8,
    title: {
      en: 'The palace of lanterns',
      es: 'El palacio de las linternas',
      fr: 'Le palais des lanternes',
      'pt-BR': 'O palácio das lanternas',
      th: 'พระราชวังแห่งโคมไฟ',
      id: 'Istana lentera',
      vi: 'Cung điện đèn lồng',
      ja: '灯籠の宮殿',
    },
    tagline: {
      en: 'You agreed to catalogue six lanterns before dawn. When you lit the first, the corridor moved and a guardian erased from history spoke your name.',
      es: 'Aceptaste catalogar seis linternas antes del amanecer. Cuando encendiste la primera, el pasillo cambió de lugar y una guardiana borrada de la historia pronunció tu nombre.',
      fr: "Vous aviez accepté d'inventorier six lanternes avant l'aube. Lorsque vous avez allumé la première, le couloir a changé de place et une gardienne effacée de l'Histoire a prononcé votre nom.",
      'pt-BR':
        'Você aceitou catalogar seis lanternas antes do amanhecer. Quando acendeu a primeira, o corredor mudou de lugar e uma guardiã apagada da história pronunciou seu nome.',
      th: 'คุณรับงานบันทึกตะเกียงหกดวงก่อนรุ่งสาง แต่เมื่อจุดดวงแรก ทางเดินกลับเปลี่ยนตำแหน่ง และผู้พิทักษ์หญิงซึ่งถูกลบจากประวัติศาสตร์ก็เอ่ยชื่อคุณ',
      id: 'Kamu menerima tugas untuk mendata enam lentera sebelum fajar. Ketika lentera pertama dinyalakan, lorong berpindah tempat dan seorang penjaga yang dihapus dari sejarah menyebut namamu.',
      vi: 'Bạn nhận ghi chép sáu chiếc đèn lồng trước bình minh. Khi thắp chiếc đầu tiên, hành lang đổi chỗ và một nữ vệ binh bị xóa khỏi lịch sử gọi tên bạn.',
      ja: '夜明けまでに六つの灯籠を記録するだけのはずだった。最初の火をともした瞬間、廊下が場所を変え、歴史から消された女性守衛があなたの名を呼んだ。',
    },
    mood: {
      en: 'Historical · Mysterious',
      es: 'Histórico · Misterioso',
      fr: 'Historique · Mystérieux',
      'pt-BR': 'Histórico · Misterioso',
      th: 'ประวัติศาสตร์ · ลึกลับ',
      id: 'Historis · Misterius',
      vi: 'Lịch sử · Bí ẩn',
      ja: '歴史 · 謎めいた',
    },
    cover: '/escape-room/level-08/rooms/cinematic-intro-v2.webp',
    topikLevel: 5,
    status: 'playable',
    maxErrors: 2,
    rewards: {
      common: {
        id: 'cosmetic-bg-lantern-palace',
        image: 'cosmetics/cosmetic-bg-lantern-palace.png',
        name: {
          en: 'Background “궁궐의 등불”',
          es: 'Fondo «궁궐의 등불»',
          fr: 'Arrière-plan «궁궐의 등불»',
          'pt-BR': 'Plano de fundo «궁궐의 등불»',
          th: 'พื้นหลัง «궁궐의 등불»',
          id: 'Latar «궁궐의 등불»',
          vi: 'Phông nền «궁궐의 등불»',
          ja: '背景「궁궐의 등불」',
        },
        description: {
          en: 'A palace corridor in the rain, lit by six lanterns tracing a route in blue and amber.',
          es: 'Un corredor palaciego bajo la lluvia, iluminado por seis linternas que trazan una ruta azul y ámbar.',
          fr: 'Un couloir du palais sous la pluie, éclairé par six lanternes traçant un chemin bleu et ambre.',
          'pt-BR':
            'Um corredor palaciano à chuva, iluminado por seis lanternas que traçam um percurso azul e âmbar.',
          th: 'ทางเดินในพระราชวังกลางสายฝน ส่องสว่างด้วยตะเกียงหกดวงที่วาดเส้นทางสีน้ำเงินและสีอำพัน',
          id: 'Koridor istana di tengah hujan, diterangi enam lentera yang membentuk rute biru dan kuning keemasan.',
          vi: 'Hành lang cung điện dưới mưa, được sáu chiếc đèn lồng soi sáng thành một lộ trình xanh lam và hổ phách.',
          ja: '雨の宮殿回廊を照らす六つの灯籠が、青と琥珀色の道筋を描く。',
        },
      },
      rare: {
        id: 'cosmetic-frame-moon-gate',
        image: 'cosmetics/cosmetic-frame-moon-gate.png',
        name: {
          en: 'Frame “월문”',
          es: 'Marco «월문»',
          fr: 'Cadre «월문»',
          'pt-BR': 'Quadro «월문»',
          th: 'กรอบ «월문»',
          id: 'Bingkai «월문»',
          vi: 'Khung «월문»',
          ja: 'フレーム「월문」',
        },
        description: {
          en: 'A lacquered wood-and-brass frame inspired by the moon gate and the restored astronomical disc.',
          es: 'Marco de madera lacada y latón inspirado en la puerta lunar y el disco astronómico restaurado.',
          fr: 'Un cadre en bois laqué et laiton inspiré de la porte lunaire et du disque astronomique restauré.',
          'pt-BR':
            'Moldura em madeira lacada e latão inspirada no portão lunar e no disco astronômico restaurado.',
          th: 'กรอบไม้เคลือบแลคเกอร์และทองเหลือง ได้รับแรงบันดาลใจจากประตูจันทราและดิสก์ดาราศาสตร์ที่ได้รับการบูรณะ',
          id: 'Bingkai kayu berpernis dan kuningan yang terinspirasi oleh gerbang bulan dan cakram astronomi yang dipulihkan.',
          vi: 'Khung gỗ sơn mài và đồng lấy cảm hứng từ cổng trăng và đĩa thiên văn được phục hồi.',
          ja: '月門と復元された天文円盤をモチーフにした、漆塗りの木と真鍮のフレーム。',
        },
      },
      epic: {
        id: 'cosmetic-avatar-haewon',
        image: 'cosmetics/cosmetic-avatar-haewon.png',
        name: {
          en: 'Avatar “기록 수호자 해원”',
          es: 'Avatar «기록 수호자 해원»',
          fr: 'Avatar «기록 수호자 해원»',
          'pt-BR': 'Avatar «기록 수호자 해원»',
          th: 'อวตาร «기록 수호자 해원»',
          id: 'Avatar «기록 수호자 해원»',
          vi: 'Ảnh đại diện «기록 수호자 해원»',
          ja: 'アバター「기록 수호자 해원」',
        },
        description: {
          en: "해원 with her blue lantern, conservator's uniform, and the shadow of the archive's final guardian.",
          es: '해원 con la linterna azul, su uniforme de conservación y la sombra de la última guardiana del archivo.',
          fr: "해원 avec sa lanterne bleue, son uniforme de conservatrice et l'ombre de la dernière gardienne des archives.",
          'pt-BR':
            '해원 com a lanterna azul, seu uniforme de conservadora e a sombra da última guardiã do arquivo.',
          th: '해원 กับตะเกียงสีน้ำเงิน เครื่องแบบนักอนุรักษ์ และเงาของผู้พิทักษ์หญิงคนสุดท้ายแห่งหอจดหมายเหตุ',
          id: '해원 dengan lentera biru, seragam konservator, dan bayangan penjaga terakhir arsip.',
          vi: '해원 với chiếc đèn lồng xanh, đồng phục bảo tồn và bóng của nữ vệ binh cuối cùng bảo vệ kho lưu trữ.',
          ja: '青い灯籠を持つ 해원。文化財保存担当者の制服の背後に、文書庫を守った最後の女性衛兵の影が伸びる。',
        },
      },
      legendary: {
        id: 'cosmetic-set-complete-08',
        image: 'cosmetics/cosmetic-set-complete-08.png',
        name: {
          en: 'Complete set “마지막 순찰”',
          es: 'Set completo «마지막 순찰»',
          fr: 'Ensemble complet «마지막 순찰»',
          'pt-BR': 'Conjunto completo «마지막 순찰»',
          th: 'เซ็ตครบชุด «마지막 순찰»',
          id: 'Set lengkap «마지막 순찰»',
          vi: 'Trọn bộ «마지막 순찰»',
          ja: 'コンプリートセット「마지막 순찰」',
        },
        description: {
          en: "The final patrol: 해원's avatar, a moon-gate frame, and the motionless palace at dawn.",
          es: 'La última patrulla: avatar de 해원, marco de puerta lunar y fondo del palacio inmóvil al amanecer.',
          fr: "La dernière patrouille: l'avatar de 해원, un cadre de porte lunaire et le palais immobile à l'aube.",
          'pt-BR':
            'A última patrulha: avatar de 해원, moldura do portão lunar e plano de fundo do palácio imóvel ao amanhecer.',
          th: 'ลาดตระเวนครั้งสุดท้าย: อวาตารของ 해원, กรอบประตูพระจันทร์และพื้นหลังปราสาทที่นิ่งในยามรุ่งอรุณ',
          id: 'Patroli terakhir: avatar 해원, bingkai gerbang bulan, dan latar istana yang diam saat fajar.',
          vi: 'Đội tuần tra cuối cùng: hình đại diện của 해원, khung cửa mặt trăng và nền cung điện bất động vào lúc bình minh.',
          ja: '最後の巡回を再現する、해원 のアバター、月門のフレーム、夜明けに静止した宮殿の背景。',
        },
      },
    },
  },
  {
    id: 'level-09',
    number: 9,
    title: {
      en: 'The mansion of the will',
      es: 'La mansión del testamento',
      fr: 'Le manoir du testament',
      'pt-BR': 'A mansão do testamento',
      th: 'คฤหาสน์แห่งพินัยกรรม',
      id: 'Rumah besar surat wasiat',
      vi: 'Dinh thự của bản di chúc',
      ja: '遺言状の邸宅',
    },
    tagline: {
      en: 'Seven heirs came to hear a final will. The door locked, two incompatible testaments appeared, and a voice declared that only those who proved the true meaning of every clause would inherit.',
      es: 'Siete herederos entraron a escuchar una última voluntad. La puerta se cerró, aparecieron dos testamentos incompatibles y una voz anunció que solo heredaría quien pudiera demostrar qué significaba realmente cada cláusula.',
      fr: 'Sept héritiers sont venus assister à une ultime lecture testamentaire. La porte s’est verrouillée, deux testaments incompatibles sont apparus et une voix a déclaré que seuls ceux capables de démontrer le véritable sens de chaque clause hériteraient.',
      'pt-BR':
        'Sete herdeiros entraram para ouvir a leitura de um último testamento. A porta se fechou, surgiram dois testamentos incompatíveis e uma voz anunciou que só herdaria quem conseguisse demonstrar o verdadeiro significado de cada cláusula.',
      th: 'ทายาทเจ็ดคนเข้ามาฟังพินัยกรรมครั้งสุดท้าย ประตูปิดลง ปรากฏพินัยกรรมสองฉบับที่ขัดแย้งกัน และมีเสียงประกาศว่าจะมีเพียงผู้ที่สามารถพิสูจน์ความหมายที่แท้จริงของแต่ละข้อเท่านั้นที่จะได้รับมรดก',
      id: 'Tujuh ahli waris datang untuk mendengar wasiat terakhir. Pintu tertutup, dua surat wasiat yang saling bertentangan muncul, dan sebuah suara mengumumkan bahwa hanya orang yang dapat membuktikan arti sebenarnya dari setiap klausul yang akan mewarisi.',
      vi: 'Bảy người thừa kế đi vào để nghe di chúc cuối cùng. Cánh cửa đóng lại, xuất hiện hai bản di chúc mâu thuẫn và một giọng nói thông báo rằng chỉ người nào có thể chứng minh ý nghĩa thực sự của từng điều khoản mới được thừa kế.',
      ja: '七人の相続人が、故人の最後の意思を聞くために集まった。扉が閉まり、両立しない二通の遺言書が現れる。そして声が告げた。各条項の本当の意味を証明できた者だけが、遺産を継ぐ。',
    },
    mood: {
      en: 'Intrigue · Brooding',
      es: 'Intriga · Denso',
      fr: 'Intrigue · Sombre',
      'pt-BR': 'Intriga · Denso',
      th: 'ปริศนาซ่อนเงื่อน · เข้มข้น',
      id: 'Intrik · Padat',
      vi: 'Âm mưu · Nặng nề',
      ja: '陰謀 · 濃密',
    },
    cover: '/escape-room/level-09/rooms/cinematic-intro-v2.webp',
    topikLevel: 5,
    status: 'playable',
    maxErrors: 2,
    rewards: {
      common: {
        id: 'cosmetic-bg-testament-mansion',
        image: 'cosmetics/cosmetic-bg-testament-mansion.png',
        name: {
          en: 'Background “유언의 밤”',
          es: 'Fondo «유언의 밤»',
          fr: 'Arrière-plan «유언의 밤»',
          'pt-BR': 'Plano de fundo «유언의 밤»',
          th: 'พื้นหลัง «유언의 밤»',
          id: 'Latar «유언의 밤»',
          vi: 'Phông nền «유언의 밤»',
          ja: '背景「유언의 밤」',
        },
        description: {
          en: 'The mansion hall at midnight, with seven chairs, two wills, and a single green lamp.',
          es: 'El salón de la mansión a medianoche, con siete sillas, dos testamentos y una única lámpara verde.',
          fr: 'Le salon du manoir à minuit, avec sept chaises, deux testaments et une unique lampe verte.',
          'pt-BR':
            'O salão da mansão à meia-noite, com sete cadeiras, dois testamentos e uma única lâmpada verde.',
          th: 'ห้องโถงของคฤหาสน์ในเวลาตีหนึ่ง มีเก้าอี้เจ็ดตัว พินัยกรรมสองฉบับ และโคมไฟสีเขียวเพียงหนึ่งอัน',
          id: 'Aula rumah besar pada tengah malam, dengan tujuh kursi, dua surat wasiat, dan satu lampu hijau.',
          vi: 'Phòng khách của dinh thự vào nửa đêm, với bảy chiếc ghế, hai bản di chúc và một chiếc đèn xanh duy nhất.',
          ja: '真夜中の邸宅の広間。七脚の椅子、二通の遺言書、ただ一つの緑のランプ。',
        },
      },
      rare: {
        id: 'cosmetic-frame-seven-keys',
        image: 'cosmetics/cosmetic-frame-seven-keys.png',
        name: {
          en: 'Frame “일곱 개의 열쇠”',
          es: 'Marco «일곱 개의 열쇠»',
          fr: 'Cadre «일곱 개의 열쇠»',
          'pt-BR': 'Moldura «일곱 개의 열쇠»',
          th: 'กรอบ «일곱 개의 열쇠»',
          id: 'Bingkai «일곱 개의 열쇠»',
          vi: 'Khung «일곱 개의 열쇠»',
          ja: 'フレーム「일곱 개의 열쇠」',
        },
        description: {
          en: 'Seven brass keys linked by lines of evidence and small seals of dark wax.',
          es: 'Siete llaves de latón enlazadas por líneas de evidencia y pequeños sellos de cera oscura.',
          fr: 'Sept clés en laiton reliées par des lignes de preuve et de petits sceaux de cire sombre.',
          'pt-BR':
            'Sete chaves de latão ligadas por linhas de evidência e pequenos selos de cera escura.',
          th: 'กุญแจทองเหลืองเจ็ดดอกเชื่อมโยงกันด้วยเส้นของหลักฐานและตราประทับขี้ผึ้งสีน้ำตาลเข้มเล็ก ๆ',
          id: 'Tujuh kunci kuningan yang dihubungkan oleh garis bukti dan segel-segel kecil dari lilin gelap.',
          vi: 'Bảy chìa khóa bằng đồng liên kết bởi các đường chứng cứ và những dấu sáp nhỏ màu tối.',
          ja: '証拠を示す線と小さな黒い封蝋で結ばれた、七本の真鍮の鍵。',
        },
      },
      epic: {
        id: 'cosmetic-avatar-archivist-eunjae',
        image: 'cosmetics/cosmetic-avatar-archivist-eunjae.png',
        name: {
          en: 'Avatar “기록자 은재”',
          es: 'Avatar «기록자 은재»',
          fr: 'Avatar «기록자 은재»',
          'pt-BR': 'Avatar «기록자 은재»',
          th: 'อวตาร «기록자 은재»',
          id: 'Avatar «기록자 은재»',
          vi: 'Ảnh đại diện «기록자 은재»',
          ja: 'アバター「기록자 은재」',
        },
        description: {
          en: "Archivist 박은재 before the eighth portrait, holding the inventory that preserved the house's memory.",
          es: 'La archivera 박은재 frente al octavo retrato, sosteniendo el inventario que conservó la memoria de la casa.',
          fr: "L'archiviste 박은재 devant le huitième portrait, tenant l'inventaire qui a préservé la mémoire de la maison.",
          'pt-BR':
            'A arquivista 박은재 diante do oitavo retrato, segurando o inventário que preservou a memória da casa.',
          th: 'ผู้เก็บเอกสาร 박은재 ตรงหน้าภาพบุคคลที่แปด ถือบัญชีสินค้าที่เก็บความทรงจำของบ้านไว้',
          id: 'Arsiparis 박은재 berdiri di depan potret kedelapan sambil memegang inventaris yang menjaga ingatan rumah.',
          vi: 'Người lưu trữ 박은재 đối diện với bức chân dung thứ tám, cầm danh sách mà đã lưu giữ ký ức của ngôi nhà.',
          ja: '八枚目の肖像画の前で、邸宅の記憶を守った目録を手にする文書管理人 박은재。',
        },
      },
      legendary: {
        id: 'cosmetic-set-complete-09',
        image: 'cosmetics/cosmetic-set-complete-09.png',
        name: {
          en: 'Complete set “여덟 번째 이름”',
          es: 'Set completo «여덟 번째 이름»',
          fr: 'Ensemble complet «여덟 번째 이름»',
          'pt-BR': 'Conjunto completo «여덟 번째 이름»',
          th: 'เซ็ตครบชุด «여덟 번째 이름»',
          id: 'Set lengkap «여덟 번째 이름»',
          vi: 'Trọn bộ «여덟 번째 이름»',
          ja: 'コンプリートセット「여덟 번째 이름」',
        },
        description: {
          en: "The eighth name: 은재's avatar, a seven-key frame, and the public archive at dawn.",
          es: 'El octavo nombre: avatar de 은재, marco de siete llaves y fondo del archivo público al amanecer.',
          fr: "Le huitième nom: l'avatar de 은재, un cadre aux sept clés et les archives publiques à l'aube.",
          'pt-BR':
            'O oitavo nome: avatar de 은재, moldura de sete chaves e plano de fundo do arquivo público ao amanhecer.',
          th: 'ชื่อที่แปด: อวตารของ 은재, กรอบเจ็ดกุญแจและด้านล่างของแฟ้มสาธารณะตอนรุ่งสาง',
          id: 'Nama kedelapan: avatar 은재, bingkai tujuh kunci, dan latar arsip publik saat fajar.',
          vi: 'Tên thứ tám: avatar của 은재, khung bảy chìa khóa và phần nền của hồ sơ công khai vào lúc bình minh.',
          ja: '八番目の名前を巡る、은재 のアバター、七本の鍵のフレーム、夜明けの公共文書館の背景。',
        },
      },
    },
  },
  {
    id: 'level-10',
    number: 10,
    title: {
      en: 'The midnight summit',
      es: 'La cumbre de medianoche',
      fr: 'Le sommet de minuit',
      'pt-BR': 'A cúpula da meia-noite',
      th: 'การประชุมสุดยอดเที่ยงคืน',
      id: 'Konferensi tengah malam',
      vi: 'Hội nghị thượng đỉnh nửa đêm',
      ja: '真夜中の首脳会談',
    },
    tagline: {
      en: 'Two delegations, a neutral castle, and a statement that must be signed before dawn. Every nuance can close a border or open it. You hold the final pen.',
      es: 'Dos delegaciones, un castillo neutral y un comunicado que debe firmarse antes del amanecer. Cada matiz puede cerrar una frontera o abrirla. Tú sostienes la última pluma.',
      fr: "Deux délégations, un château neutre et un communiqué à signer avant l'aube. Chaque nuance peut fermer une frontière ou l'ouvrir. Vous tenez la dernière plume.",
      'pt-BR':
        'Duas delegações, um castelo neutro e um comunicado que precisa ser assinado antes do amanhecer. Cada nuance pode fechar uma fronteira ou abri-la. Você segura a última caneta.',
      th: 'คณะผู้แทนสองฝ่าย ปราสาทเป็นกลาง และแถลงการณ์ที่ต้องลงนามก่อนรุ่งสาง ทุกความหมายละเอียดอ่อนอาจปิดหรือเปิดพรมแดน ปากกาด้ามสุดท้ายอยู่ในมือคุณ',
      id: 'Dua delegasi, sebuah kastel netral, dan pernyataan yang harus ditandatangani sebelum fajar. Setiap nuansa dapat menutup atau membuka perbatasan. Kamu memegang pena terakhir.',
      vi: 'Hai phái đoàn, một lâu đài trung lập và một thông cáo phải được ký trước bình minh. Mỗi sắc thái có thể đóng hoặc mở biên giới. Bạn nắm giữ chiếc bút cuối cùng.',
      ja: '二つの代表団、中立の城、夜明けまでに署名しなければならない共同声明。一つのニュアンスが国境を閉ざしもすれば、開きもする。最後の儀礼ペンを握るのは、あなた。',
    },
    mood: {
      en: 'Diplomatic · Tense',
      es: 'Diplomático · Tenso',
      fr: 'Diplomatique · Tendu',
      'pt-BR': 'Diplomático · Tenso',
      th: 'การทูต · ตึงเครียด',
      id: 'Diplomatik · Tegang',
      vi: 'Ngoại giao · Căng thẳng',
      ja: '外交 · 緊迫',
    },
    cover: '/escape-room/level-10/rooms/cinematic-intro-v2.webp',
    topikLevel: 6,
    status: 'playable',
    maxErrors: 2,
    rewards: {
      common: {
        id: 'cosmetic-bg-midnight-summit',
        image: 'cosmetics/cosmetic-bg-midnight-summit.webp',
        name: {
          en: 'Background “새벽 회담”',
          es: 'Fondo «새벽 회담»',
          fr: 'Arrière-plan «새벽 회담»',
          'pt-BR': 'Plano de fundo «새벽 회담»',
          th: 'พื้นหลัง «새벽 회담»',
          id: 'Latar «새벽 회담»',
          vi: 'Phông nền «새벽 회담»',
          ja: '背景「새벽 회담」',
        },
        description: {
          en: 'The diplomatic retreat above the snowy mountains, its windows lit until dawn.',
          es: 'El refugio diplomático sobre las montañas nevadas, con sus ventanas encendidas hasta el amanecer.',
          fr: "Le refuge diplomatique au-dessus des montagnes enneigées, ses fenêtres éclairées jusqu'à l'aube.",
          'pt-BR':
            'O refúgio diplomático sobre as montanhas nevadas, com as janelas iluminadas até o amanhecer.',
          th: 'ที่พักทางการทูตบนภูเขาหิมะ พร้อมหน้าต่างที่เปิดไฟจนถึงรุ่งสาง',
          id: 'Tempat perundingan diplomatik di atas pegunungan bersalju, dengan jendela menyala hingga fajar.',
          vi: 'Nơi trú ẩn ngoại giao trên những ngọn núi phủ tuyết, với những ô cửa sổ sáng đến tận bình minh.',
          ja: '雪山に建つ外交会談の館。窓の明かりは夜明けまで消えない。',
        },
      },
      rare: {
        id: 'cosmetic-frame-six-seals',
        image: 'cosmetics/cosmetic-frame-six-seals.png',
        name: {
          en: 'Frame “여섯 인장”',
          es: 'Marco «여섯 인장»',
          fr: 'Cadre «여섯 인장»',
          'pt-BR': 'Moldura «여섯 인장»',
          th: 'กรอบ «여섯 인장»',
          id: 'Bingkai «여섯 인장»',
          vi: 'Khung «여섯 인장»',
          ja: 'フレーム「여섯 인장」',
        },
        description: {
          en: 'An indigo-and-gold lacquer frame, bordered with ivory paper and six red wax seals.',
          es: 'Un marco de laca índigo y oro, rodeado de papel marfil y seis sellos de cera roja.',
          fr: 'Un cadre en laque indigo et or, bordé de papier ivoire et de six sceaux de cire rouge.',
          'pt-BR':
            'Uma moldura de laca índigo e ouro, cercada por papel marfim e seis selos de cera vermelha.',
          th: 'กรอบสีน้ำเงินครามและทอง ล้อมรอบด้วยกระดาษสีงาช้างและตราประทับขี้ผึ้งสีแดงหกดวง',
          id: 'Bingkai pernis nila dan emas, dikelilingi kertas gading dan enam segel lilin merah.',
          vi: 'Một khung sơn mài màu chàm và vàng, được bao quanh bởi giấy ngà và sáu con dấu sáp đỏ.',
          ja: '象牙色の紙と六つの赤い封蝋に囲まれた、藍と金の漆塗りフレーム。',
        },
      },
      epic: {
        id: 'cosmetic-avatar-interpreter-pen',
        image: 'cosmetics/cosmetic-avatar-interpreter-pen.webp',
        name: {
          en: 'Avatar “마지막 통역관”',
          es: 'Avatar «마지막 통역관»',
          fr: 'Avatar «마지막 통역관»',
          'pt-BR': 'Avatar «마지막 통역관»',
          th: 'อวตาร «마지막 통역관»',
          id: 'Avatar «마지막 통역관»',
          vi: 'Ảnh đại diện «마지막 통역관»',
          ja: 'アバター「마지막 통역관」',
        },
        description: {
          en: 'The midnight interpreter with her earpiece and the ceremonial pen ready for the final line.',
          es: 'La intérprete de medianoche con auricular y la pluma ceremonial preparada para la última línea.',
          fr: "L'interprète de minuit avec son écouteur et la plume cérémonielle prête pour la dernière ligne.",
          'pt-BR':
            'A intérprete da meia-noite com fone de ouvido e a caneta cerimonial pronta para a última linha.',
          th: 'นักแปลเวลากลางคืนที่สวมหูฟังและปากกาพิธีที่เตรียมไว้สำหรับบรรทัดสุดท้าย',
          id: 'Penerjemah tengah malam dengan alat dengar dan pena upacara yang siap untuk baris terakhir.',
          vi: 'Thông dịch viên nửa đêm với tai nghe và bút nghi lễ chuẩn bị cho câu cuối cùng.',
          ja: 'イヤホンを着け、最後の一文に備えて儀礼ペンを構える深夜の通訳者。',
        },
      },
      legendary: {
        id: 'cosmetic-set-dawn-accord',
        image: 'cosmetics/cosmetic-set-dawn-accord.webp',
        name: {
          en: 'Complete set “새벽의 합의”',
          es: 'Set completo «새벽의 합의»',
          fr: 'Ensemble complet «새벽의 합의»',
          'pt-BR': 'Conjunto completo «새벽의 합의»',
          th: 'เซ็ตครบชุด «새벽의 합의»',
          id: 'Set lengkap «새벽의 합의»',
          vi: 'Trọn bộ «새벽의 합의»',
          ja: 'コンプリートセット「새벽의 합의」',
        },
        description: {
          en: 'The agreement case: document, six seals, ceremonial pen, and first light over the mountains.',
          es: 'El estuche del acuerdo: documento, seis sellos, pluma ceremonial y la primera luz sobre las montañas.',
          fr: "L'écrin de l'accord: document, six sceaux, plume cérémonielle et première lumière sur les montagnes.",
          'pt-BR':
            'O estojo do acordo: documento, seis selos, caneta cerimonial e a primeira luz sobre as montanhas.',
          th: 'ชุดข้อตกลง: เอกสาร หกตราประทับ ปากกาพิธี และแสงแรกเหนือภูเขา',
          id: 'Kotak perjanjian: dokumen, enam segel, pena upacara, dan cahaya pertama di atas pegunungan.',
          vi: 'Hộp của thỏa thuận: tài liệu, sáu con dấu, cây bút lễ và ánh sáng đầu tiên trên những ngọn núi.',
          ja: '文書、六つの印章、儀礼ペン、山々を照らす最初の光を収めた協定のケース。',
        },
      },
    },
  },
] as const satisfies readonly EscapeLevelCatalogEntry[]

export function escapeLevelCatalogEntry(id: string): EscapeLevelCatalogEntry | null {
  return ESCAPE_LEVEL_CATALOG.find((entry) => entry.id === id) ?? null
}
