// AUTO-GENERATED by scripts/escape-i18n-gen.mjs - do not edit by hand.
import { createEscapeTranslator, type EscapeLevelTranslations } from '../../../create-translator'
import { enLevel10 } from './en'
import { frLevel10 } from './fr'
import { ptBRLevel10 } from './pt-BR'
import { thLevel10 } from './th'
import { idLevel10 } from './id'
import { viLevel10 } from './vi'
import { jaLevel10 } from './ja'

export const LEVEL_10_TRANSLATIONS: EscapeLevelTranslations = {
  "en": enLevel10,
  "fr": frLevel10,
  "pt-BR": ptBRLevel10,
  "th": thLevel10,
  "id": idLevel10,
  "vi": viLevel10,
  "ja": jaLevel10,
}

export const t = createEscapeTranslator(LEVEL_10_TRANSLATIONS)
