import type { PracticeHelpContent } from '~/lib/domain'
import { L } from '../locale'

/**
 * 활용 (conjugation) — explanation for the conjugation drill.
 * Korean examples are language-neutral; prose is localized via L().
 * Native review (owner's wife) pending on the 8 translations.
 */
export const CONJUGATION_HELP: PracticeHelpContent = {
  ko: '활용',
  romanization: 'hwaryong',
  subtitle: L(
    'conjugating verbs and adjectives',
    'conjugar verbos y adjetivos',
    'conjuguer verbes et adjectifs',
    'conjugar verbos e adjetivos',
    'การผันคำกริยาและคำคุณศัพท์',
    'mengonjugasikan verba dan adjektiva',
    'chia động từ và tính từ',
    '動詞・形容詞の活用',
  ),
  concept: L(
    "In Korean, a verb or adjective is a stem plus an ending. The ending carries the meaning — politeness, tense, mood — while the stem stays put. How the two join depends on the stem's last vowel and whether it has a final consonant (받침), and some stems are irregular, changing shape when an ending is attached.",
    'En coreano, un verbo o adjetivo es una raíz más una terminación. La terminación lleva el significado —cortesía, tiempo, modo— mientras la raíz permanece. Cómo se unen depende de la última vocal de la raíz y de si tiene consonante final (받침); además, algunas raíces son irregulares y cambian de forma al añadir la terminación.',
    "En coréen, un verbe ou un adjectif est un radical plus une terminaison. La terminaison porte le sens — politesse, temps, mode — tandis que le radical reste stable. Leur jonction dépend de la dernière voyelle du radical et de la présence d'une consonne finale (받침) ; de plus, certains radicaux sont irréguliers et changent de forme quand on ajoute la terminaison.",
    'Em coreano, um verbo ou adjetivo é um radical mais uma terminação. A terminação carrega o significado — cortesia, tempo, modo — enquanto o radical permanece. Como os dois se unem depende da última vogal do radical e de ele ter ou não consoante final (받침); além disso, alguns radicais são irregulares e mudam de forma ao receber a terminação.',
    'ในภาษาเกาหลี คำกริยาหรือคำคุณศัพท์ประกอบด้วยรากศัพท์บวกกับท้ายคำ ท้ายคำเป็นตัวบอกความหมาย ทั้งความสุภาพ กาล และมาลา ส่วนรากศัพท์คงเดิม การเชื่อมทั้งสองขึ้นกับสระตัวท้ายของรากศัพท์และว่ามีตัวสะกด (받침) หรือไม่ อีกทั้งรากศัพท์บางตัวเป็นแบบไม่ปกติและจะเปลี่ยนรูปเมื่อเติมท้ายคำ',
    'Dalam bahasa Korea, verba atau adjektiva adalah akar kata ditambah akhiran. Akhiran membawa makna — kesopanan, kala, modus — sementara akar kata tetap. Cara keduanya bergabung bergantung pada vokal terakhir akar dan ada-tidaknya konsonan akhir (받침); selain itu, sebagian akar bersifat tak beraturan dan berubah bentuk saat akhiran ditambahkan.',
    'Trong tiếng Hàn, một động từ hay tính từ gồm gốc từ cộng với đuôi từ. Đuôi từ mang ý nghĩa — độ lịch sự, thì, thức — còn gốc từ giữ nguyên. Cách hai phần ghép lại tùy thuộc vào nguyên âm cuối của gốc và việc gốc có phụ âm cuối (받침) hay không; ngoài ra, một số gốc bất quy tắc sẽ đổi hình khi gắn đuôi.',
    '韓国語では、動詞や形容詞は「語幹＋語尾」でできている。語尾が意味（丁寧さ・時制・ムード）を担い、語幹は基本そのまま。二つの結びつき方は語幹の最後の母音と、終声（받침）の有無で決まり、さらに一部の語幹は不規則で、語尾が付くと形が変わる。',
  ),
  types: [
    {
      ko: '해요체 / 합니다체 / 반말',
      label: L(
        'speech levels', 'niveles de habla', 'niveaux de langue', 'níveis de fala',
        'ระดับการพูด', 'tingkat tutur', 'cấp độ lời nói', '丁寧さのレベル',
      ),
      desc: L(
        'The ending sets how polite you sound. 해요체 (-아/어요) is the everyday polite form, 합니다체 (-ㅂ/습니다) is formal, and 반말 (the 해요체 form minus the 요) is casual, for close friends and family.',
        'La terminación marca cuán cortés suenas. 해요체 (-아/어요) es la forma cortés de todos los días, 합니다체 (-ㅂ/습니다) es formal y 반말 (la forma 해요체 sin el 요) es casual, para amigos cercanos y familia.',
        "La terminaison fixe le degré de politesse. 해요체 (-아/어요) est la forme polie du quotidien, 합니다체 (-ㅂ/습니다) est formelle, et 반말 (la forme 해요체 sans le 요) est familière, pour les proches et la famille.",
        'A terminação define o quão cortês você soa. 해요체 (-아/어요) é a forma cortês do dia a dia, 합니다체 (-ㅂ/습니다) é formal e 반말 (a forma 해요체 sem o 요) é casual, para amigos próximos e família.',
        'ท้ายคำกำหนดว่าคุณพูดสุภาพแค่ไหน 해요체 (-아/어요) เป็นรูปสุภาพในชีวิตประจำวัน 합니다체 (-ㅂ/습니다) เป็นทางการ และ 반말 (รูป 해요체 ที่ตัด 요 ออก) เป็นแบบกันเอง ใช้กับเพื่อนสนิทและครอบครัว',
        'Akhiran menentukan seberapa sopan Anda terdengar. 해요체 (-아/어요) adalah bentuk sopan sehari-hari, 합니다체 (-ㅂ/습니다) bersifat formal, dan 반말 (bentuk 해요체 tanpa 요) bersifat santai, untuk teman dekat dan keluarga.',
        'Đuôi từ quyết định bạn nghe lịch sự đến mức nào. 해요체 (-아/어요) là dạng lịch sự thường ngày, 합니다체 (-ㅂ/습니다) là trang trọng, còn 반말 (dạng 해요체 bỏ 요) là thân mật, dùng với bạn thân và người nhà.',
        '語尾で丁寧さが決まる。해요체（-아/어요）は日常の丁寧形、합니다체（-ㅂ/습니다）はフォーマル、반말（해요체から 요 を取った形）はタメ口で、親しい友人や家族に使う。',
      ),
      example: '가다 → 가요 / 갑니다 / 가',
      gloss: L(
        '"to go" → polite / formal / casual',
        '"ir" → cortés / formal / casual',
        '« aller » → poli / formel / familier',
        '"ir" → cortês / formal / casual',
        '"ไป" → สุภาพ / ทางการ / กันเอง',
        '"pergi" → sopan / formal / santai',
        '"đi" → lịch sự / trang trọng / thân mật',
        '「行く」→ 丁寧／フォーマル／タメ口',
      ),
    },
    {
      ko: '시제 (현재 / 과거)',
      label: L(
        'tense', 'tiempo', 'temps', 'tempo',
        'กาล', 'kala', 'thì', '時制',
      ),
      desc: L(
        'Present is the plain ending (-아/어요). For the past, insert 았/었 between the stem and the ending: 았 after the bright vowels ㅏ/ㅗ, 었 elsewhere, and 했 for 하다 verbs.',
        'El presente es la terminación simple (-아/어요). Para el pasado, inserta 았/었 entre la raíz y la terminación: 았 tras las vocales claras ㅏ/ㅗ, 었 en los demás casos, y 했 para los verbos en 하다.',
        "Le présent est la terminaison simple (-아/어요). Pour le passé, insérez 았/었 entre le radical et la terminaison : 았 après les voyelles claires ㅏ/ㅗ, 었 ailleurs, et 했 pour les verbes en 하다.",
        'O presente é a terminação simples (-아/어요). Para o passado, insira 았/었 entre o radical e a terminação: 았 após as vogais claras ㅏ/ㅗ, 었 nos demais casos, e 했 para verbos em 하다.',
        'รูปปัจจุบันคือท้ายคำธรรมดา (-아/어요) ส่วนอดีตให้แทรก 았/었 ระหว่างรากศัพท์กับท้ายคำ ใช้ 았 หลังสระสว่าง ㅏ/ㅗ ใช้ 었 ในกรณีอื่น และใช้ 했 สำหรับคำกริยา 하다',
        'Bentuk kini adalah akhiran biasa (-아/어요). Untuk lampau, sisipkan 았/었 di antara akar dan akhiran: 았 setelah vokal terang ㅏ/ㅗ, 었 untuk lainnya, dan 했 untuk verba 하다.',
        'Thì hiện tại là đuôi đơn (-아/어요). Với thì quá khứ, chèn 았/었 vào giữa gốc và đuôi: 았 sau nguyên âm sáng ㅏ/ㅗ, 었 cho các trường hợp khác, và 했 cho động từ 하다.',
        '現在は基本の語尾（-아/어요）。過去は語幹と語尾の間に 았/었 を入れる：明るい母音 ㅏ/ㅗ の後は 았、それ以外は 었、하다 動詞は 했。',
      ),
      example: '먹다 → 먹어요 / 먹었어요',
      gloss: L(
        '"to eat" → eat(s) / ate',
        '"comer" → come / comió',
        '« manger » → mange / a mangé',
        '"comer" → come / comeu',
        '"กิน" → กิน / กินแล้ว',
        '"makan" → makan / sudah makan',
        '"ăn" → ăn / đã ăn',
        '「食べる」→ 食べます／食べました',
      ),
    },
    {
      ko: '불규칙 활용',
      label: L(
        'irregular stems', 'raíces irregulares', 'radicaux irréguliers', 'radicais irregulares',
        'การผันแบบไม่ปกติ', 'akar tak beraturan', 'gốc bất quy tắc', '不規則活用',
      ),
      desc: L(
        "Some stems change shape before a vowel ending. With a ㅂ-irregular, the final ㅂ turns into 우/오; with a ㄷ-irregular, the final ㄷ turns into ㄹ. The drill mixes these in so you can't just glue endings on mechanically.",
        'Algunas raíces cambian de forma ante una terminación vocálica. En una irregular en ㅂ, la ㅂ final se vuelve 우/오; en una irregular en ㄷ, la ㄷ final se vuelve ㄹ. El ejercicio las mezcla para que no pegues terminaciones de forma mecánica.',
        "Certains radicaux changent de forme devant une terminaison vocalique. Pour un irrégulier en ㅂ, le ㅂ final devient 우/오 ; pour un irrégulier en ㄷ, le ㄷ final devient ㄹ. L'exercice les mêle pour vous empêcher de coller les terminaisons mécaniquement.",
        'Alguns radicais mudam de forma diante de uma terminação vocálica. Num irregular em ㅂ, o ㅂ final vira 우/오; num irregular em ㄷ, o ㄷ final vira ㄹ. O exercício os mistura para você não colar terminações de forma mecânica.',
        'รากศัพท์บางตัวเปลี่ยนรูปเมื่ออยู่หน้าท้ายคำที่ขึ้นด้วยสระ แบบไม่ปกติ ㅂ ตัว ㅂ ท้ายจะกลายเป็น 우/오 ส่วนแบบไม่ปกติ ㄷ ตัว ㄷ ท้ายจะกลายเป็น ㄹ แบบฝึกหัดจะคละพวกนี้เข้ามาเพื่อไม่ให้คุณเติมท้ายคำแบบกลไก',
        'Sebagian akar berubah bentuk sebelum akhiran berawalan vokal. Pada tak beraturan ㅂ, ㅂ akhir menjadi 우/오; pada tak beraturan ㄷ, ㄷ akhir menjadi ㄹ. Latihan ini mencampurnya agar Anda tidak menempelkan akhiran secara mekanis.',
        'Một số gốc đổi hình trước đuôi bắt đầu bằng nguyên âm. Với bất quy tắc ㅂ, ㅂ cuối biến thành 우/오; với bất quy tắc ㄷ, ㄷ cuối biến thành ㄹ. Bài luyện trộn chúng vào để bạn không thể gắn đuôi một cách máy móc.',
        '一部の語幹は母音語尾の前で形が変わる。ㅂ 不規則では語幹末の ㅂ が 우/오 に、ㄷ 不規則では語幹末の ㄷ が ㄹ になる。ドリルはこれらを混ぜるので、機械的に語尾を付けるだけでは正解できない。',
      ),
      example: '덥다 → 더워요, 듣다 → 들어요',
      gloss: L(
        '"to be hot" → 더워요, "to listen" → 들어요',
        '"hacer calor" → 더워요, "escuchar" → 들어요',
        '« avoir chaud » → 더워요, « écouter » → 들어요',
        '"estar quente" → 더워요, "ouvir" → 들어요',
        '"ร้อน" → 더워요, "ฟัง" → 들어요',
        '"panas" → 더워요, "mendengar" → 들어요',
        '"nóng" → 더워요, "nghe" → 들어요',
        '「暑い」→ 더워요、「聞く」→ 들어요',
      ),
    },
  ],
  howToPlay: [
    L(
      'Pick a verb class to drill — everything mixed, or a single irregular like ㅂ 불규칙 or ㄷ 불규칙.',
      'Elige una clase de verbo para practicar: todo mezclado, o una sola irregular como ㅂ 불규칙 o ㄷ 불규칙.',
      'Choisissez une classe de verbes à travailler : tout mélangé, ou une seule irrégularité comme ㅂ 불규칙 ou ㄷ 불규칙.',
      'Escolha uma classe de verbo para praticar: tudo misturado, ou uma única irregular como ㅂ 불규칙 ou ㄷ 불규칙.',
      'เลือกกลุ่มคำกริยาที่จะฝึก จะคละทั้งหมด หรือเลือกแบบไม่ปกติเดียว เช่น ㅂ 불규칙 หรือ ㄷ 불규칙 ก็ได้',
      'Pilih kelas verba untuk dilatih: semua campur, atau satu kelas tak beraturan seperti ㅂ 불규칙 atau ㄷ 불규칙.',
      'Chọn một nhóm động từ để luyện: trộn tất cả, hoặc một loại bất quy tắc như ㅂ 불규칙 hay ㄷ 불규칙.',
      '練習する動詞クラスを選ぶ：全部ミックスか、ㅂ 불규칙・ㄷ 불규칙 のような単一の不規則。',
    ),
    L(
      'Each card shows a dictionary form plus a target ending; pick the correctly conjugated form from four choices.',
      'Cada tarjeta muestra una forma de diccionario más una terminación objetivo; elige la forma conjugada correcta entre cuatro opciones.',
      "Chaque carte affiche une forme du dictionnaire et une terminaison cible ; choisissez la forme conjuguée correcte parmi quatre propositions.",
      'Cada cartão mostra uma forma de dicionário mais uma terminação alvo; escolha a forma conjugada correta entre quatro opções.',
      'การ์ดแต่ละใบแสดงรูปพจนานุกรมพร้อมท้ายคำเป้าหมาย ให้เลือกรูปที่ผันถูกต้องจากสี่ตัวเลือก',
      'Tiap kartu menampilkan bentuk kamus plus akhiran target; pilih bentuk terkonjugasi yang benar dari empat pilihan.',
      'Mỗi thẻ hiển thị dạng từ điển kèm một đuôi mục tiêu; chọn dạng chia đúng trong bốn lựa chọn.',
      '各カードに辞書形と目標の語尾が出る。四つの選択肢から正しく活用した形を選ぶ。',
    ),
    L(
      'Finish the round of eight; correct answers raise that class’s mastery, and you can replay the ones you missed.',
      'Termina la ronda de ocho; los aciertos suben la maestría de esa clase y puedes repetir los que fallaste.',
      'Terminez la manche de huit ; les bonnes réponses augmentent la maîtrise de cette classe, et vous pouvez rejouer celles ratées.',
      'Termine a rodada de oito; os acertos aumentam o domínio dessa classe e você pode repetir os que errou.',
      'เล่นให้จบรอบละแปดข้อ คำตอบที่ถูกจะเพิ่มความเชี่ยวชาญของกลุ่มนั้น และเล่นซ้ำข้อที่พลาดได้',
      'Selesaikan ronde delapan soal; jawaban benar menaikkan penguasaan kelas itu, dan Anda bisa mengulang yang meleset.',
      'Hoàn thành vòng tám câu; câu đúng làm tăng độ thành thạo của nhóm đó, và bạn có thể chơi lại những câu sai.',
      '8問のラウンドをやり切る。正解でそのクラスの習熟度が上がり、間違えた問題は再挑戦できる。',
    ),
  ],
  tip: L(
    "Watch the irregulars: 덥다 isn't 덥어요 but 더워요 (ㅂ→우), and 듣다 isn't 듣어요 but 들어요 (ㄷ→ㄹ). The change only happens before a vowel ending, so 덥다→덥고 keeps the ㅂ.",
    "Cuidado con las irregulares: 덥다 no es 덥어요 sino 더워요 (ㅂ→우), y 듣다 no es 듣어요 sino 들어요 (ㄷ→ㄹ). El cambio solo ocurre ante una terminación vocálica, así que 덥다→덥고 conserva la ㅂ.",
    "Attention aux irréguliers : 덥다 ne donne pas 덥어요 mais 더워요 (ㅂ→우), et 듣다 ne donne pas 듣어요 mais 들어요 (ㄷ→ㄹ). Le changement n'a lieu que devant une terminaison vocalique, donc 덥다→덥고 garde le ㅂ.",
    "Cuidado com os irregulares: 덥다 não é 덥어요, mas 더워요 (ㅂ→우), e 듣다 não é 듣어요, mas 들어요 (ㄷ→ㄹ). A mudança só ocorre diante de terminação vocálica, então 덥다→덥고 mantém o ㅂ.",
    "ระวังพวกไม่ปกติ: 덥다 ไม่ใช่ 덥어요 แต่เป็น 더워요 (ㅂ→우) และ 듣다 ไม่ใช่ 듣어요 แต่เป็น 들어요 (ㄷ→ㄹ) การเปลี่ยนเกิดเฉพาะหน้าท้ายคำที่ขึ้นด้วยสระ ดังนั้น 덥다→덥고 จึงยังคง ㅂ ไว้",
    "Perhatikan yang tak beraturan: 덥다 bukan 덥어요 melainkan 더워요 (ㅂ→우), dan 듣다 bukan 듣어요 melainkan 들어요 (ㄷ→ㄹ). Perubahan hanya terjadi sebelum akhiran berawalan vokal, jadi 덥다→덥고 tetap memakai ㅂ.",
    "Chú ý các từ bất quy tắc: 덥다 không phải 덥어요 mà là 더워요 (ㅂ→우), và 듣다 không phải 듣어요 mà là 들어요 (ㄷ→ㄹ). Sự thay đổi chỉ xảy ra trước đuôi bắt đầu bằng nguyên âm, nên 덥다→덥고 vẫn giữ ㅂ.",
    "不規則に注意：덥다 は 덥어요 ではなく 더워요（ㅂ→우）、듣다 は 듣어요 ではなく 들어요（ㄷ→ㄹ）。変化は母音語尾の前だけなので、덥다→덥고 では ㅂ がそのまま残る。",
  ),
}
