import type { PracticeHelpContent } from '~/lib/domain'
import { L } from '../locale'

/**
 * 조사 (particles) — explanation for the particle lab.
 * Korean examples are language-neutral; prose is localized via L().
 * Native review (owner's wife) pending on the 8 translations.
 */
export const PARTICLES_HELP: PracticeHelpContent = {
  ko: '조사',
  romanization: 'josa',
  subtitle: L(
    'the particles that mark grammatical roles',
    'las partículas que marcan los roles gramaticales',
    'les particules qui marquent les rôles grammaticaux',
    'as partículas que marcam os papéis gramaticais',
    'อนุภาคที่บอกบทบาททางไวยากรณ์',
    'partikel yang menandai peran gramatikal',
    'các tiểu từ đánh dấu vai trò ngữ pháp',
    '文法的な役割を示す助詞',
  ),
  concept: L(
    'Korean attaches a small particle behind a word to tell you its job in the sentence — who acts, what gets acted on, where it happens. Word order is flexible because the particle, not the position, carries the role. Most have two forms chosen by whether the word ends in a 받침 (final consonant).',
    'El coreano coloca una pequeña partícula detrás de una palabra para indicar su función en la frase: quién actúa, sobre qué se actúa, dónde ocurre. El orden de las palabras es flexible porque el rol lo lleva la partícula, no la posición. La mayoría tiene dos formas según si la palabra termina en 받침 (consonante final).',
    "Le coréen ajoute une petite particule derrière un mot pour indiquer son rôle dans la phrase : qui agit, sur quoi on agit, où cela se passe. L'ordre des mots est libre car c'est la particule, et non la position, qui porte le rôle. La plupart ont deux formes selon que le mot finit ou non par une 받침 (consonne finale).",
    'O coreano acrescenta uma pequena partícula atrás de uma palavra para indicar sua função na frase: quem age, sobre o que se age, onde acontece. A ordem das palavras é flexível porque o papel é carregado pela partícula, não pela posição. A maioria tem duas formas conforme a palavra termine ou não em 받침 (consoante final).',
    'ภาษาเกาหลีเติมอนุภาคเล็ก ๆ ไว้หลังคำเพื่อบอกหน้าที่ในประโยค ว่าใครเป็นผู้กระทำ สิ่งใดถูกกระทำ และเกิดที่ไหน ลำดับคำจึงยืดหยุ่นเพราะอนุภาคเป็นตัวบอกบทบาท ไม่ใช่ตำแหน่ง ส่วนใหญ่มีสองรูป ขึ้นกับว่าคำลงท้ายด้วย 받침 (พยัญชนะสะกด) หรือไม่',
    'Bahasa Korea menempelkan partikel kecil di belakang kata untuk menunjukkan perannya dalam kalimat: siapa pelaku, apa yang dikenai, di mana terjadi. Urutan kata fleksibel karena yang membawa peran adalah partikel, bukan posisi. Sebagian besar punya dua bentuk tergantung apakah kata berakhir dengan 받침 (konsonan akhir).',
    'Tiếng Hàn gắn một tiểu từ nhỏ sau từ để cho biết vai trò của nó trong câu: ai làm, cái gì bị tác động, xảy ra ở đâu. Trật tự từ linh hoạt vì vai trò do tiểu từ mang, không phải vị trí. Phần lớn có hai dạng tùy theo từ có kết thúc bằng 받침 (phụ âm cuối) hay không.',
    '韓国語は単語の後ろに小さな助詞を付けて、その語の文中での役割（誰が動作するか、何が対象か、どこで起きるか）を示す。語順が自由なのは、役割を担うのが位置ではなく助詞だから。多くは語が 받침（終声）で終わるかどうかで二つの形を選ぶ。',
  ),
  types: [
    {
      ko: '주격 조사 (이/가)',
      label: L(
        'subject marker', 'marcador de sujeto', 'marqueur de sujet', 'marcador de sujeito',
        'อนุภาคบอกประธาน', 'penanda subjek', 'tiểu từ chủ ngữ', '主格助詞',
      ),
      desc: L(
        'Marks who or what performs the action — the subject. Use 이 after a 받침, 가 after a vowel. It often introduces new or focused information.',
        'Marca quién o qué realiza la acción — el sujeto. Usa 이 tras 받침 y 가 tras vocal. Suele presentar información nueva o enfocada.',
        "Marque qui ou quoi accomplit l'action — le sujet. Employez 이 après une 받침, 가 après une voyelle. Il introduit souvent une information nouvelle ou mise en relief.",
        'Marca quem ou o que realiza a ação — o sujeito. Use 이 após 받침 e 가 após vogal. Costuma introduzir informação nova ou em foco.',
        'บอกว่าใครหรือสิ่งใดเป็นผู้กระทำ คือประธาน ใช้ 이 หลัง 받침 และ 가 หลังสระ มักใช้แนะนำข้อมูลใหม่หรือเน้น',
        'Menandai siapa atau apa yang melakukan tindakan — subjek. Pakai 이 setelah 받침, 가 setelah vokal. Sering memperkenalkan informasi baru atau yang ditekankan.',
        'Đánh dấu ai hoặc cái gì thực hiện hành động — chủ ngữ. Dùng 이 sau 받침, 가 sau nguyên âm. Thường giới thiệu thông tin mới hoặc được nhấn mạnh.',
        '動作をするのが誰か・何か（主語）を示す。받침 の後は 이、母音の後は 가。新情報や焦点を導入することが多い。',
      ),
      example: '동생이 빵을 먹어요.',
      gloss: L(
        'My younger sibling eats bread.', 'Mi hermano menor come pan.',
        'Mon cadet mange du pain.', 'Meu irmão mais novo come pão.',
        'น้องกินขนมปัง', 'Adik saya makan roti.',
        'Em tôi ăn bánh mì.', '弟（妹）がパンを食べます。',
      ),
    },
    {
      ko: '목적격 조사 (을/를)',
      label: L(
        'object marker', 'marcador de objeto', "marqueur d'objet", 'marcador de objeto',
        'อนุภาคบอกกรรม', 'penanda objek', 'tiểu từ tân ngữ', '目的格助詞',
      ),
      desc: L(
        'Marks the thing the action is done to — the direct object. Use 을 after a 받침, 를 after a vowel. In casual speech it is often dropped.',
        'Marca aquello sobre lo que recae la acción — el objeto directo. Usa 을 tras 받침 y 를 tras vocal. En el habla informal suele omitirse.',
        "Marque ce sur quoi porte l'action — le complément d'objet direct. Employez 을 après une 받침, 를 après une voyelle. À l'oral familier il est souvent omis.",
        'Marca aquilo sobre o qual recai a ação — o objeto direto. Use 을 após 받침 e 를 após vogal. Na fala informal costuma ser omitido.',
        'บอกสิ่งที่ถูกกระทำ คือกรรมตรง ใช้ 을 หลัง 받침 และ 를 หลังสระ ในภาษาพูดทั่วไปมักละไว้',
        'Menandai hal yang dikenai tindakan — objek langsung. Pakai 을 setelah 받침, 를 setelah vokal. Dalam percakapan santai sering dihilangkan.',
        'Đánh dấu thứ chịu tác động của hành động — tân ngữ trực tiếp. Dùng 을 sau 받침, 를 sau nguyên âm. Trong lời nói thân mật thường được lược bỏ.',
        '動作の対象（直接目的語）を示す。받침 の後は 을、母音の後は 를。くだけた話し言葉ではよく省略される。',
      ),
      example: '저는 책을 읽어요.',
      gloss: L(
        'I read a book.', 'Yo leo un libro.',
        'Je lis un livre.', 'Eu leio um livro.',
        'ฉันอ่านหนังสือ', 'Saya membaca buku.',
        'Tôi đọc sách.', '私は本を読みます。',
      ),
    },
    {
      ko: '보조사 (은/는)',
      label: L(
        'topic / contrast marker', 'marcador de tema / contraste', 'marqueur de thème / contraste', 'marcador de tema / contraste',
        'อนุภาคบอกหัวเรื่อง/เปรียบต่าง', 'penanda topik / kontras', 'tiểu từ chủ đề / tương phản', '主題・対照の補助詞',
      ),
      desc: L(
        "Sets the word up as the topic ('as for ...') or contrasts it with something else. Use 은 after a 받침, 는 after a vowel. It rides on top of a role rather than naming one.",
        "Establece la palabra como tema ('en cuanto a ...') o la contrasta con otra cosa. Usa 은 tras 받침 y 는 tras vocal. Se monta sobre un rol en vez de nombrarlo.",
        "Pose le mot comme thème (« quant à ... ») ou l'oppose à autre chose. Employez 은 après une 받침, 는 après une voyelle. Il se superpose à un rôle au lieu d'en désigner un.",
        "Estabelece a palavra como tema ('quanto a ...') ou a contrasta com outra coisa. Use 은 após 받침 e 는 após vogal. Ele se sobrepõe a um papel em vez de nomeá-lo.",
        "ตั้งคำให้เป็นหัวเรื่อง ('ส่วน...นั้น') หรือเปรียบต่างกับสิ่งอื่น ใช้ 은 หลัง 받침 และ 는 หลังสระ มันซ้อนทับบทบาทหนึ่งแทนที่จะระบุบทบาท",
        "Menetapkan kata sebagai topik ('adapun ...') atau mengontraskannya dengan hal lain. Pakai 은 setelah 받침, 는 setelah vokal. Ia menumpang di atas suatu peran alih-alih menamainya.",
        "Đặt từ làm chủ đề ('còn về ...') hoặc đối lập nó với thứ khác. Dùng 은 sau 받침, 는 sau nguyên âm. Nó chồng lên một vai trò thay vì gọi tên vai trò đó.",
        '語を主題（「〜は」）として立てるか、他と対照させる。받침 の後は 은、母音の後は 는。役割を名指すのではなく、ある役割の上に重なる。',
      ),
      example: '저는 학생이에요. 동생은 회사원이에요.',
      gloss: L(
        'I am a student. My sibling, on the other hand, is an office worker.',
        'Yo soy estudiante. Mi hermano, en cambio, es oficinista.',
        'Moi, je suis étudiant. Mon cadet, lui, est employé de bureau.',
        'Eu sou estudante. Meu irmão, por outro lado, é funcionário de escritório.',
        'ฉันเป็นนักเรียน ส่วนน้องเป็นพนักงานบริษัท',
        'Saya seorang pelajar. Adik saya, sebaliknya, seorang pegawai kantor.',
        'Tôi là học sinh. Còn em tôi thì là nhân viên văn phòng.',
        '私は学生です。弟（妹）は会社員です。',
      ),
    },
    {
      ko: '부사격 조사 (에 / 에서 / 에게 / (으)로)',
      label: L(
        'place / direction markers', 'marcadores de lugar / dirección', 'marqueurs de lieu / direction', 'marcadores de lugar / direção',
        'อนุภาคบอกสถานที่/ทิศทาง', 'penanda tempat / arah', 'tiểu từ nơi chốn / phương hướng', '副詞格助詞',
      ),
      desc: L(
        'Mark setting and direction. 에 = a static place or time, 에서 = where an action happens (or a source), 에게/한테 = a recipient person, (으)로 = direction or means.',
        'Marcan el escenario y la dirección. 에 = lugar estático o tiempo, 에서 = dónde ocurre una acción (u origen), 에게/한테 = persona destinataria, (으)로 = dirección o medio.',
        "Marquent le cadre et la direction. 에 = lieu statique ou temps, 에서 = où se déroule une action (ou provenance), 에게/한테 = personne destinataire, (으)로 = direction ou moyen.",
        'Marcam o cenário e a direção. 에 = lugar estático ou tempo, 에서 = onde ocorre uma ação (ou origem), 에게/한테 = pessoa destinatária, (으)로 = direção ou meio.',
        'บอกฉากและทิศทาง 에 = สถานที่คงที่หรือเวลา, 에서 = ที่ที่การกระทำเกิดขึ้น (หรือจุดเริ่ม), 에게/한테 = บุคคลผู้รับ, (으)로 = ทิศทางหรือวิธีการ',
        'Menandai latar dan arah. 에 = tempat statis atau waktu, 에서 = tempat suatu tindakan terjadi (atau asal), 에게/한테 = orang penerima, (으)로 = arah atau cara.',
        'Đánh dấu bối cảnh và phương hướng. 에 = nơi chốn tĩnh hoặc thời gian, 에서 = nơi hành động diễn ra (hoặc nguồn), 에게/한테 = người nhận, (으)로 = phương hướng hoặc phương tiện.',
        '場面と方向を示す。에 ＝静的な場所や時間、에서 ＝動作が起きる場所（または起点）、에게/한테 ＝受け手の人、(으)로 ＝方向や手段。',
      ),
      example: '저는 도서관에서 친구에게 책을 줬어요.',
      gloss: L(
        'At the library, I gave a book to my friend.',
        'En la biblioteca, le di un libro a mi amigo.',
        "À la bibliothèque, j'ai donné un livre à mon ami.",
        'Na biblioteca, dei um livro ao meu amigo.',
        'ที่ห้องสมุด ฉันให้หนังสือแก่เพื่อน',
        'Di perpustakaan, saya memberi buku kepada teman.',
        'Ở thư viện, tôi đã đưa sách cho bạn.',
        '私は図書館で友達に本をあげました。',
      ),
    },
  ],
  howToPlay: [
    L(
      'In Explore, tap a highlighted particle to switch it OFF and watch the translation and nuance shift — see exactly what that particle was carrying.',
      'En Explorar, toca una partícula resaltada para apagarla y observa cómo cambian la traducción y el matiz: ve exactamente qué aportaba esa partícula.',
      "Dans Explorer, touchez une particule en surbrillance pour la désactiver et observez le changement de traduction et de nuance — voyez exactement ce que cette particule portait.",
      'No Explorar, toque uma partícula destacada para desligá-la e observe a tradução e a nuance mudarem — veja exatamente o que aquela partícula carregava.',
      'ในโหมดสำรวจ แตะอนุภาคที่ไฮไลต์เพื่อปิดมัน แล้วดูคำแปลและความหมายแฝงเปลี่ยนไป จะเห็นชัดว่าอนุภาคนั้นแบกความหมายอะไรไว้',
      'Di mode Jelajah, ketuk partikel yang disorot untuk mematikannya dan lihat terjemahan serta nuansanya berubah — lihat persis apa yang dibawa partikel itu.',
      'Ở chế độ Khám phá, chạm vào một tiểu từ được tô sáng để tắt nó và xem bản dịch cùng sắc thái thay đổi — thấy rõ tiểu từ đó đang mang điều gì.',
      '探索モードでは、強調された助詞をタップしてオフにすると、訳とニュアンスがどう変わるかがわかる。その助詞が何を担っていたかがはっきり見える。',
    ),
    L(
      'Switch to Clash (⚡) and pick a card set, then choose the right particle — 은/는 vs 이/가 — for each sentence.',
      'Cambia a Choque (⚡) y elige un set de cartas; luego escoge la partícula correcta — 은/는 vs 이/가 — para cada frase.',
      'Passez à Choc (⚡) et choisissez un jeu de cartes, puis sélectionnez la bonne particule — 은/는 vs 이/가 — pour chaque phrase.',
      'Mude para Choque (⚡) e escolha um conjunto de cartas; depois selecione a partícula correta — 은/는 vs 이/가 — para cada frase.',
      'สลับไปโหมดปะทะ (⚡) เลือกชุดการ์ด แล้วเลือกอนุภาคที่ถูกต้อง — 은/는 หรือ 이/가 — สำหรับแต่ละประโยค',
      'Beralih ke Bentrok (⚡) dan pilih satu set kartu, lalu pilih partikel yang benar — 은/는 vs 이/가 — untuk tiap kalimat.',
      'Chuyển sang Đối đầu (⚡) và chọn một bộ thẻ, rồi chọn tiểu từ đúng — 은/는 hay 이/가 — cho mỗi câu.',
      '対戦（⚡）に切り替えてカードセットを選び、各文に正しい助詞（은/는 か 이/가）を選ぶ。',
    ),
    L(
      'A wrong 받침 match is blocked so you can retry; a wrong choice is logged. Clear the round to grow your garden; misses can be replayed.',
      'Una concordancia de 받침 incorrecta se bloquea para que reintentes; una elección errónea se registra. Supera la ronda para hacer crecer tu jardín; los fallos se pueden repetir.',
      "Un mauvais accord de 받침 est bloqué pour vous laisser réessayer ; un mauvais choix est enregistré. Terminez la manche pour faire pousser votre jardin ; les erreurs peuvent être rejouées.",
      'Uma concordância de 받침 errada é bloqueada para você tentar de novo; uma escolha errada é registrada. Conclua a rodada para fazer seu jardim crescer; os erros podem ser repetidos.',
      'การจับคู่ 받침 ผิดจะถูกบล็อกให้ลองใหม่ ส่วนการเลือกผิดจะถูกบันทึก ผ่านรอบเพื่อให้สวนเติบโต และเล่นซ้ำส่วนที่พลาดได้',
      'Pencocokan 받침 yang salah diblokir agar bisa dicoba lagi; pilihan yang salah dicatat. Selesaikan ronde untuk menumbuhkan taman Anda; yang meleset bisa diulang.',
      'Ghép sai 받침 sẽ bị chặn để bạn thử lại; chọn sai sẽ được ghi lại. Hoàn thành vòng để khu vườn lớn lên; câu sai có thể chơi lại.',
      '받침 の不一致はブロックされて再挑戦できる。間違った選択は記録される。ラウンドをクリアすると庭が育ち、ミスは再プレイできる。',
    ),
  ],
  tip: L(
    "The 은/는 vs 이/가 trap: use 이/가 to introduce or single out NEW information ('누가 왔어요?' → '제가 왔어요'), and 은/는 for the known topic or a contrast ('저는 괜찮아요'). New = 이/가; already on the table = 은/는.",
    "La trampa 은/는 vs 이/가: usa 이/가 para introducir o destacar información NUEVA ('누가 왔어요?' → '제가 왔어요'), y 은/는 para el tema ya conocido o un contraste ('저는 괜찮아요'). Nuevo = 이/가; ya sobre la mesa = 은/는.",
    "Le piège 은/는 vs 이/가 : employez 이/가 pour introduire ou mettre en avant une information NOUVELLE ('누가 왔어요?' → '제가 왔어요'), et 은/는 pour le thème déjà connu ou un contraste ('저는 괜찮아요'). Nouveau = 이/가 ; déjà évoqué = 은/는.",
    "A pegadinha 은/는 vs 이/가: use 이/가 para introduzir ou destacar informação NOVA ('누가 왔어요?' → '제가 왔어요'), e 은/는 para o tema já conhecido ou um contraste ('저는 괜찮아요'). Novo = 이/가; já na mesa = 은/는.",
    "กับดัก 은/는 กับ 이/가: ใช้ 이/가 เพื่อแนะนำหรือเน้นข้อมูลใหม่ ('누가 왔어요?' → '제가 왔어요') และใช้ 은/는 กับหัวเรื่องที่รู้แล้วหรือการเปรียบต่าง ('저는 괜찮아요') ใหม่ = 이/가; รู้อยู่แล้ว = 은/는",
    "Jebakan 은/는 vs 이/가: pakai 이/가 untuk memperkenalkan atau menonjolkan informasi BARU ('누가 왔어요?' → '제가 왔어요'), dan 은/는 untuk topik yang sudah diketahui atau kontras ('저는 괜찮아요'). Baru = 이/가; sudah dibahas = 은/는.",
    "Bẫy 은/는 với 이/가: dùng 이/가 để giới thiệu hoặc làm nổi bật thông tin MỚI ('누가 왔어요?' → '제가 왔어요'), và dùng 은/는 cho chủ đề đã biết hoặc sự tương phản ('저는 괜찮아요'). Mới = 이/가; đã được nhắc tới = 은/는.",
    '은/는 と 이/가 の落とし穴：新情報を導入・際立たせるときは 이/가（「누가 왔어요?」→「제가 왔어요」）、すでに分かっている主題や対照には 은/는（「저는 괜찮아요」）。新情報＝이/가、既出＝은/는。',
  ),
}
