<script lang="ts">
/**
 * PixelTree — layered pixel-art tree for the TOPIK garden.
 *
 * Renders the 5 cumulative growth layers of one species, generated by
 * `tools/pixel-trees/generate_trees.py` onto a 128x160 canvas anchored
 * at (64,148). Layers stack and are never removed once visible:
 *
 *   progress 0     -> tree_skeleton
 *   progress >= 10 -> + trunk_alive + leaves_layer_1   (sprout)
 *   progress >= 40 -> + leaves_layer_2                 (leafy)
 *   progress >= 80 -> + bloom_full                     (bloom)
 *
 * Spec: docs/superpowers/specs/2026-06-11-garden-tree-dashboard.md §4.2, §7
 * Asset pipeline: tools/pixel-trees/README.md
 */

export const TREE_SPECIES = ['cherry', 'magnolia', 'zelkova', 'mugunghwa', 'maple', 'ginkgo'] as const
export type TreeSpecies = (typeof TREE_SPECIES)[number]

/** Progress thresholds (in %) at which each visual layer appears. */
export const TREE_THRESHOLDS = { sprout: 10, leafy: 40, bloom: 80 } as const

/** Generator canvas geometry — single source for stage/zone positioning. */
export const TREE_CANVAS = { width: 128, height: 160, anchorX: 64, anchorY: 148 } as const

const LAYER_ORDER = [
  'tree_skeleton',
  'trunk_alive',
  'leaves_layer_1',
  'leaves_layer_2',
  'bloom_full',
] as const
export type TreeLayer = (typeof LAYER_ORDER)[number]

/** Cumulative layer stack for a 0–100 progress value. */
export function layersForProgress(progress: number): TreeLayer[] {
  const layers: TreeLayer[] = ['tree_skeleton']
  if (progress >= TREE_THRESHOLDS.sprout) layers.push('trunk_alive', 'leaves_layer_1')
  if (progress >= TREE_THRESHOLDS.leafy) layers.push('leaves_layer_2')
  if (progress >= TREE_THRESHOLDS.bloom) layers.push('bloom_full')
  return layers
}
</script>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'

interface Props {
  species: TreeSpecies
  /** Level progress 0–100; decides which layers are visible. */
  progress?: number
  /** Integer pixel scale (x2/x3/x4). Fractional values are floored — never stretch. */
  scale?: number
  /** Paint the shared ground shadow under the trunk. */
  shadow?: boolean
  /** Accessible name; when empty the tree is decorative (aria-hidden). */
  label?: string
}

const props = withDefaults(defineProps<Props>(), {
  progress: 0,
  scale: 3,
  shadow: true,
  label: '',
})

const intScale = computed(() => Math.max(1, Math.floor(props.scale)))
const pxWidth = computed(() => TREE_CANVAS.width * intScale.value)
const pxHeight = computed(() => TREE_CANVAS.height * intScale.value)

const layerSrc = (layer: TreeLayer) => `/img/tree/${props.species}/${layer}.png`

const visibleLayers = computed(() => layersForProgress(props.progress))

// ── Preload: all 5 layers of the species before showing anything, so a
// growth transition never pops in a half-loaded PNG (spec §7.4).
const ready = ref(false)

watch(
  () => props.species,
  (species) => {
    ready.value = false
    if (import.meta.server) return
    const urls = [...LAYER_ORDER.map((l) => `/img/tree/${species}/${l}.png`), '/img/tree/ground_shadow.png']
    let pending = urls.length
    const done = () => {
      pending -= 1
      if (pending === 0 && species === props.species) ready.value = true
    }
    for (const url of urls) {
      const img = new Image()
      img.onload = done
      img.onerror = done
      img.src = url
    }
  },
  { immediate: true },
)

// ── Layer pop: when a NEW layer crosses its threshold while mounted,
// it lands with a one-shot scale pop from the trunk anchor.
const popping = ref(new Set<TreeLayer>())

watch(visibleLayers, (now, before) => {
  if (!ready.value) return
  const fresh = now.filter((l) => !before.includes(l))
  if (!fresh.length) return
  for (const l of fresh) popping.value.add(l)
  popping.value = new Set(popping.value)
  setTimeout(() => {
    for (const l of fresh) popping.value.delete(l)
    popping.value = new Set(popping.value)
  }, 500)
})
</script>

<template>
  <div
    class="pixel-tree"
    :style="{ width: `${pxWidth}px`, height: `${pxHeight}px` }"
    :role="label ? 'img' : undefined"
    :aria-label="label || undefined"
    :aria-hidden="!label"
  >
    <template v-if="ready">
      <img
        v-if="shadow"
        class="pixel-tree__layer pixel"
        src="/img/tree/ground_shadow.png"
        alt=""
        :width="pxWidth"
        :height="pxHeight"
        draggable="false"
      />
      <img
        v-for="layer in visibleLayers"
        :key="layer"
        class="pixel-tree__layer pixel"
        :class="{ 'pixel-tree__layer--pop': popping.has(layer) }"
        :src="layerSrc(layer)"
        alt=""
        :width="pxWidth"
        :height="pxHeight"
        draggable="false"
      />
    </template>
  </div>
</template>

<style scoped>
.pixel-tree {
  position: relative;
  flex-shrink: 0;
}

.pixel-tree__layer {
  position: absolute;
  inset: 0;
  user-select: none;
  /* grow/pop scales from the trunk anchor (64,148 of 128x160) */
  transform-origin: 50% 92.5%;
}

.pixel-tree__layer--pop {
  animation: pixel-tree-pop 0.45s steps(6) both;
}

@keyframes pixel-tree-pop {
  0% {
    transform: scale(0.6);
    opacity: 0;
  }
  55% {
    transform: scale(1.07);
    opacity: 1;
  }
  100% {
    transform: scale(1);
  }
}

@media (prefers-reduced-motion: reduce) {
  .pixel-tree__layer--pop {
    animation: none;
  }
}
</style>
