// AUTO-GENERATED by scripts/escape-i18n-gen.mjs - do not edit by hand.
import { createEscapeTranslator, type EscapeLevelTranslations } from '../../../create-translator'
import { enLevel05 } from './en'
import { frLevel05 } from './fr'
import { ptBRLevel05 } from './pt-BR'
import { thLevel05 } from './th'
import { idLevel05 } from './id'
import { viLevel05 } from './vi'
import { jaLevel05 } from './ja'

export const LEVEL_05_TRANSLATIONS: EscapeLevelTranslations = {
  "en": enLevel05,
  "fr": frLevel05,
  "pt-BR": ptBRLevel05,
  "th": thLevel05,
  "id": idLevel05,
  "vi": viLevel05,
  "ja": jaLevel05,
}

export const t = createEscapeTranslator(LEVEL_05_TRANSLATIONS)
