// AUTO-GENERATED by scripts/escape-i18n-gen.mjs - do not edit by hand.
import { createEscapeTranslator, type EscapeLevelTranslations } from '../../../create-translator'
import { enLevel06 } from './en'
import { frLevel06 } from './fr'
import { ptBRLevel06 } from './pt-BR'
import { thLevel06 } from './th'
import { idLevel06 } from './id'
import { viLevel06 } from './vi'
import { jaLevel06 } from './ja'

export const LEVEL_06_TRANSLATIONS: EscapeLevelTranslations = {
  "en": enLevel06,
  "fr": frLevel06,
  "pt-BR": ptBRLevel06,
  "th": thLevel06,
  "id": idLevel06,
  "vi": viLevel06,
  "ja": jaLevel06,
}

export const t = createEscapeTranslator(LEVEL_06_TRANSLATIONS)
