// AUTO-GENERATED by scripts/escape-i18n-gen.mjs - do not edit by hand.
import { createEscapeTranslator, type EscapeLevelTranslations } from '../../../create-translator'
import { enLevel04 } from './en'
import { frLevel04 } from './fr'
import { ptBRLevel04 } from './pt-BR'
import { thLevel04 } from './th'
import { idLevel04 } from './id'
import { viLevel04 } from './vi'
import { jaLevel04 } from './ja'

export const LEVEL_04_TRANSLATIONS: EscapeLevelTranslations = {
  "en": enLevel04,
  "fr": frLevel04,
  "pt-BR": ptBRLevel04,
  "th": thLevel04,
  "id": idLevel04,
  "vi": viLevel04,
  "ja": jaLevel04,
}

export const t = createEscapeTranslator(LEVEL_04_TRANSLATIONS)
